### ISSUE TITLE
var->green.length may be left uninitialized

### ISSUE THREAD

**Issue by eisensheng** [raspberrypi/linux#1]
I'm not sure since I haven't read the full source yet but it looks to me like `var->green.length` could leave the function [here](https://github.com/raspberrypi/linux/blob/4593b68d5da44244266737c3c18da81666fa6d15/drivers/video/bcm2708_fb.c#L90) without being initialized.

**Comment by nomis** [comment]
It can't be left uninitialised but it's likely to be uninitialised when reading it.

The kmalloc in bcm2708_fb_register should be a kzalloc so that green.length is 0 and gets set to 6.

Currently it could happen to be 5 when registering the device but that's unlikely.

**Comment by nomis** [comment]
I've just noticed that there's a memset so green.length will be initialised to 0 and then updated to 6.

**Comment by eisensheng** [comment]
thanks for investigating this one, I guess we can close it then.

**Comment by broker-eg** [comment]
https://github.com/awdawd12qw/xx
