### ISSUE TITLE
wmii colour misrepresentation

### ISSUE THREAD

**Issue by colons** [raspberrypi/linux#10]
When running [wmii-hg](http://aur.archlinux.org/packages.php?ID=3497) on Arch Linux Arm on the Raspberry Pi with [my favourite wmiirc](https://bitbucket.org/colons/dotfiles/src/3f4ee6a307e6/wmiirc), the window decoration colours are modified in a bizarre way I have yet to identify.

Screenshots:
distortion: [pi](http://dump.musicfortheblind.co.uk/gallery/photos/rpiwmii/rudiment.png) ([photo](http://dump.musicfortheblind.co.uk/gallery/photos/rpiwmii/IMG_0771.JPG))
expected: [arch x86 box](http://dump.musicfortheblind.co.uk/gallery/photos/rpiwmii/banana.png) ([photo](http://dump.musicfortheblind.co.uk/gallery/photos/rpiwmii/IMG_0772.JPG))

What's weird about this (and what leads me to believe it's a low-level issue) is that when run in a tightvnc x server, the colours load and render fine. Additionally, everything else under the broken wmii instances works fine — images, webpages, etc. render perfectly. I assume this means it's a bug in whatever system wmii uses to initially select its colours.

If this doesn't belong here, I apologise and will be willing to resubmit elsewehere.

**Comment by popcornmix** [comment]
There's an update to kernel source that might fix this. Either rebuild kernel, or wait for an Arch udpate and report back.
