### ISSUE TITLE
raspberrypi-bootloader (1.20120810-1) update deletes files in /boot

### ISSUE THREAD

**Issue by xnosek00** [raspberrypi/linux#100]
I did 
aptitude update; aptitude safe upgrade and after that, my RASPI freezes

after reboot I did: dpkg --configure -a

root@raspberrypi:/home/pi# dpkg --configure -a
Setting up raspberrypi-bootloader (1.20120810-1) …
Your current start.elf is the same as arm240_start.elf
Was not able to detect current memory split
Diversion „diversion /boot/arm128_start.elf by package rpikernelhack“ doesn't exist, not deleted
Diversion „diversion /boot/arm192_start.elf by package rpikernelhack“ doesn't exist, not deleted
Diversion „diversion /boot/arm224_start.elf by package rpikernelhack“ doesn't exist, not deleted
Diversion „diversion /boot/arm240_start.elf by package rpikernelhack“ doesn't exist, not deleted

and so on

All files in my /boot are deleted and RASPI can't boot. 

Deleted files: (bootcode.bin, kernel.img, kernel_cutdown.img, kernel_emergency.img, arm*_start.elf)

What is wrong?

I have to insert SD card into other PC and copy these files into /boot. But after I do dpkg --configure -a -> the same problem.

**Comment by popcornmix** [comment]
There was a problem with FAT corruption with kernels before 2nd August. You may be hitting that.
Can you start with the "2012-08-16-wheezy-raspbian.zip" image from download page?

Aleternatively download latest kernel.img from https://github.com/Hexxeh/rpi-firmware and boot from that before trying to upgrade firmware.

**Comment by xnosek00** [comment]
I tried download latest kernel.img from Hexxeh and boot from it. I have the same problem. System is working before I do: dpgk --configure -a

Is there any other way? I don't want to start with the: "2012-08-16-wheezy-raspbian.zip". I want to repair my system.

Maybe this could help. I put my SD card into another computer and ran fsck. 

gentoovbi root # fsck.vfat /dev/mmcblk0p1 
dosfsck 3.0.9, 31 Jan 2010, FAT32, LFN
/kernel_emergency.img.dpkg-divert.tmp
  File size is 10158080 bytes, cluster chain length is > 10158080 bytes.
  Truncating file to 10158080 bytes.
Reclaimed 146 unused clusters (1196032 bytes).
Leaving file system unchanged.
/dev/mmcblk0p1: 7 files, 1356/7161 clusters

**Comment by xnosek00** [comment]
I deleted   kernel_emergency.img.dpkg-divert.tmp

and after that I ran fsck:

gentoovbi root # fsck /dev/mmcblk0p1 
fsck na util-linux 2.20.1
dosfsck 3.0.9, 31 Jan 2010, FAT32, LFN
Reclaimed 233 unused clusters (1908736 bytes).
Leaving file system unchanged.
/dev/mmcblk0p1: 17 files, 4495/7161 clusters

gentoovbi nosek # fsck /dev/mmcblk0p2
fsck na util-linux 2.20.1
e2fsck 1.42 (29-Nov-2011)
/dev/mmcblk0p2: clean, 165204/491520 files, 1226921/1942272 blocks

then: dpgk --configure -a   (with a kernel from Hexxeh) and my problem remains.

Btw.: before I put aptitude safe-upgrade, I did: rpi-update. 

Latest firmware was in my Raspi before i ran aptitude safe-upgrade.

**Comment by asb** [comment]
Just to clarify the initial message - your problem is that the Raspberry Pi froze during the upgrade procedure? Could you look in /var/log/apt/term.log.\* to see if anything at all was logged for this initial upgrade. I'll get back to you with some advice on fixing your dpkg database.

**Comment by xnosek00** [comment]
Yes, you're right. My problem is, that the RasPI froze during the upgrade procedure.

I was looking in /va/log/apt/term.log

Preparing substitution raspberrypi-bootloader 1.20120714-1 ( …/raspberrypi-bootloader_1.20120810-1_armhf.deb) …
Adding diversion „diversion /boot/arm128_start.elf do /usr/share/rpikernelhack/arm128_start.elf by package rpikernelhack“
Adding diversion „diversion /boot/arm192_start.elf do /usr/share/rpikernelhack/arm192_start.elf by package rpikernelhack“
Adding diversion „diversion /boot/kernel.img do /usr/share/rpikernelhack/kernel.img by package rpikernelhack“
.
.
.
Unpacking raspberrypi-bootloader ...

.
.
.

Setting up package raspberrypi-bootloader (1.20120810-1) ...
Your current start.elf is the same as arm128_start.elf
Deleting „diversion /boot/arm128_start.elf into /usr/share/rpikernelhack/arm128_start.elf by package rpikernelhack“ 
Deleting „diversion /boot/arm192_start.elf into /usr/share/rpikernelhack/arm192_start.elf by package rpikernelhack“
.
.
.

**Comment by xnosek00** [comment]
The problem is, that upgrade procedure deletes kernel and files in /boot.

After that RasPi freeze and can't boot after restart, because kernel and files in /boot are missing.

**Comment by xnosek00** [comment]
Problem is solved. My SD card was bad and it broke my update. It is not a problem in aptitude update.

**Comment by singpolyma** [comment]
I just had this same problem.  I think the script to add the new diversions didn't run, but then finishing the upgrade removes the old ones...  Hopefully I can just manually add them to my `/boot` again to get my system back up...
