### ISSUE TITLE
spi-bcm2708 driver ignores device tree specified GPIOs and always allocates GPIO7-11

### ISSUE THREAD

**Issue by jimbojr** [raspberrypi/linux#1002]
As per description - we need to properly support DT GPIOs so we can use alternate pin mappings (for Compute Module) and also use only one chip select if that is all that is necessary (current driver always enables CLK,MISO,MOSI,CS0 and CS1 on fixed pins).

**Comment by Ruffio** [comment]
@jimbojr has your issue been resolved? If so, please close this issue. Thanks.
