### ISSUE TITLE
Exported sysfs node permissions race condition

### ISSUE THREAD

**Issue by nsayer** [raspberrypi/linux#1007]
This has been noticed on a Raspberry Pi running Raspbian 3.18.11-v7+.

If you export gpio 8 (for instance), there is a race condition where the "direction" node will appear very briefly as read-only for the gpio group, and then suddenly change to read-write.

This article seems relevant: http://kroah.com/log/blog/2013/06/26/how-to-create-a-sysfs-file-correctly

I believe the race is between lines 794 and 806 of linux/drivers/gpio/gpiolib.c.

See also http://raspberrypi.stackexchange.com/questions/23162/gpio-value-file-appears-with-wrong-permissions-momentarily

**Comment by pelwell** [comment]
This is unmodified upstream kernel code. If this is an issue for you then you will have to raise it with the maintainers; once it is fixed upstream then we will pick up the new version. Until then I suggest a short delay, optionally with a loop to check the permissions are correct.
