### ISSUE TITLE
Oops 80f/17 Unable to handle kernel paging request at virtual address ffffffec

### ISSUE THREAD

**Issue by schuhmam** [raspberrypi/linux#1019]
Today I received my Raspberry PI 2 Model B. To be sure to have a proper power supply I bought a kit containing a transparent case and a 2A output power supply and some cooling.
The microSDHC card is a Transcend 16GB class 10 (TS16GUSDHC10U1)

The device is supposed to work as router to replace a virtual machine running Ubuntu on Microsoft Hyper-V (so server can be turned off over night). Anyways. Everything is working but often the system stops reacting. I only see the attached message on the display.

The last time the error appears was after I tried to configure the perl CPAN with perl -MCPAN -e shell. After pressing twice enter (2 questions with default answer 'yes') this error occurs. After a reboot I retried and at the same spot it happened again. Don't get me wrong this happened before - the same error. I am not 100% sure but I think the mentioned virtual address is always the same.
I configure the system via putty SSH.

![20150610_oops](https://cloud.githubusercontent.com/assets/12836846/8096002/ea11b8d2-0fd2-11e5-84e2-5f1602cbfcb2.png)

Sorry for the light bulb but otherwise my Windows Phone is too stupid to make a proper autofocus.

Unable to handle kernel paging request at virtual address 7f1dd14c
pgd = 80004000
[7f1dd14c] *pgd=393ad811, *pte=3611a4df, *ppte=3611a65e
Internal error: Oops: 80f [#1] PREEMPT SMP ARM
Modules linked in: [...]
[...]
Process kworker/0:1 (pid: 34)

I tried to raise "vm.min_free_kbytes" in /etc/sysctl.conf to 16384 but it did not help. While googleing I turned off the VLANs in the switch for the PI so that I can use the old virtual machine for internet. During this process the PI run well. Very strange...
This routing, IPv6 and so on is very basic stuff. I can't imagine that this cause so many problems. The memory consumption was about 68 MiB. The device is not in the case yet. I can't imagine that it is going to hot - it is even not overclocked and handle some packages from network can't be that exhausting.
Any ideas?

The distribution is a Ubuntu with Kernel 3.18.0-20-rpi2 #21-Ubuntu

The original source is my recorded video:
https://drive.google.com/open?id=0B0R5aKIdB-XzQ2FIdUhVeDN4ZmM&authuser=0
(alternative) http://1drv.ms/1S5OGfH

**Comment by schuhmam** [comment]
Additional info:
- The PI: http://www.amazon.de/dp/B00T3BX0L8
- The microSDHC: http://www.amazon.de/dp/B00BLHWYWS
- The power supply: http://www.amazon.de/dp/B00UCSO9G6
- used Win32 Disk Imager under Windows 7 to put the Ubuntu image onto the SD card (booted successfully asap)

Some "specials" of my system (I don't know if it is that special but I better mention it):
- installed with apt-get install: build-essential, vim, htop, wide-dhcpv6-client, vlan (don't remember 100%)
- modprobe 8021q for VLAN usage; added VLAN 1, 4 and 3 on eth0 with vconfig add eth0 1; then added the appropriate IP address configurations in the /etc/network/interfaces
- set in "/etc/sysctl.conf": net.ipv4.tcp_syncookies=1, net.ipv6.conf.all.forwarding=1, net.ipv6.conf.ppp0.accept_ra=2 and vm.min_free_kbytes = 16384
- changed the keyboard layout to German and changed timezone with dpkg-reconfigure
- added "ipv6 ipv6cp-use-ipaddr" in /etc/ppp/options to receive the IPv6 address from ISP (dynamic prefix :/)
- installed curl and run rpi-update (after error occurred)

**Comment by popcornmix** [comment]
I assume you've seen no warning squares in top right of display? (for under-voltage or over-temperature)?

Do you get the same failure with raspbian?
Ubuntu is not something tested or directly supported by us so it's hard to offer advice.
If the issue doesn't occur with raspbian then it may suggest a problem with Ubuntu's kernel configuration or other setup.

**Comment by schuhmam** [comment]
The warning square? Well at least I didn't know that they exist. So I think I should have recognized them.

But you are right. Ubuntu is nothing official with the Raspberry. I knew Ubuntu already so I wanted to give it a try first. I already started configuring the system and using Raspian now.

Now I am finished with setting up the system. I will have a look at the stability. Currently it runs fine. No crash so fare. Hope that will stay this way because I have absolutely no idea were the error is hidden.
Thank you so far.

**Comment by schuhmam** [comment]
Looking good so far. I will come back if any problems show up.
Thanks.
