### ISSUE TITLE
rpi-4.0.y compile error

### ISSUE THREAD

**Issue by malgrati-ferdinando** [raspberrypi/linux#1033]
try to compile rpi-4.0.y I get the following error:

drivers/built-in.o: In function `mmc_fixup_device':
/data/elinux/linux-rpi-4.0/drivers/mmc/core/quirks.c:95: undefined reference to`mmc_debug'
make: **\* [vmlinux] Error 1

Regards

Ferdinando

**Comment by pelwell** [comment]
It appears you are not using one of the standard configurations - bcmrpi_defconfig (Pi 1) or bcm2709_defconfig (Pi 2). Your configuration appears to lack the MMC_BCM2835 option, hence the build error.
