### ISSUE TITLE
Request inclusion of "Batman Advanced" module. (batman-adv)

### ISSUE THREAD

**Issue by netlore** [raspberrypi/linux#104]
I have a project which uses the "batman-adv" module for mesh networking, and while it's been educational trying to compile modules to support a rapidly developing system, after posting about it on the forum I was advised that there's no reason this module should not be included and I should post an issue here.

The project details are here:-

http://www.netlore.co.uk/airmesh/About.html

James

**Comment by asb** [comment]
Ref: http://www.raspberrypi.org/phpBB3/viewtopic.php?p=166622#p166622

Config is CONFIG_BATMAN_ADV

**Comment by popcornmix** [comment]
Latest firmware adds CONFIG_BATMAN_ADV. Is this okay?
