### ISSUE TITLE
libprocps0 doesn't export freeproc

### ISSUE THREAD

**Issue by jgressmann** [raspberrypi/linux#1047]
The header proc/readproc.h (libprocps0-dev) declares 

extern void freeproc(proc_t\* p);

which isn't available in libprocps0 (version 1:3.3.3-3).

**Comment by popcornmix** [comment]
This repo is for the linux kernel and I don't believe this is part of the kernel.
I suspect this is a debian packaging question. You could try asking here:
https://www.raspberrypi.org/forums/viewforum.php?f=66
