### ISSUE TITLE
Ralink firmware - rt2800usb not listing Logitec Corp. device

### ISSUE THREAD

**Issue by tombo9999** [raspberrypi/linux#106]
Posted request in the forum http://www.raspberrypi.org/phpBB3/viewtopic.php?p=166651#p166651
Licaon_Kter told me to post my request here.

On RaspberryPi "lsusb" command shows:
tombo9999@raspberrypi ~ $ lsusb
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 001 Device 002: ID 0424:9512 Standard Microsystems Corp.
Bus 001 Device 003: ID 0424:ec00 Standard Microsystems Corp.
Bus 001 Device 004: ID 0789:0168 Logitec Corp. LAN-W150N/U2 Wireless LAN Adapter

lsmod doesn't show any module.

I found something "strange" from modinfo command filtered for Logitec Corp.:
tombo9999@raspberrypi ~ $ modinfo rt2800usb | grep 0789
alias: usb:v0789p0166d_dc_dsc_dp_ic_isc_ip*
alias: usb:v0789p0164d_dc_dsc_dp_ic_isc_ip*
alias: usb:v0789p0163d_dc_dsc_dp_ic_isc_ip*
alias: usb:v0789p0162d_dc_dsc_dp_ic_isc_ip*

On my old PC running Linux tombo9999-desktop 3.2.0-29-generic-pae #46-Ubuntu SMP Fri Jul 27 17:25:43 UTC 2012 i686 i686 i386 GNU/Linux

Running same command the device is properly listed.
tombo9999@tombo9999-desktop:~$ modinfo rt2800usb | grep 0789
alias: usb:v0789p0169d_dc_dsc_dp_ic_isc_ip*
alias: usb:v0789p0168d_dc_dsc_dp_ic_isc_ip*
alias: usb:v0789p0166d_dc_dsc_dp_ic_isc_ip*
alias: usb:v0789p0164d_dc_dsc_dp_ic_isc_ip*
alias: usb:v0789p0163d_dc_dsc_dp_ic_isc_ip*
alias: usb:v0789p0162d_dc_dsc_dp_ic_isc_ip*

And, of course the dongle works properly.

Thanks, in advance :)

tombo9999@raspberrypi ~ $ dpkg-query -W -f='${Status} ${Version}\n' firmware-ralink install ok installed 0.36

Firmware version
filename: /lib/modules/3.2.27+/kernel/drivers/net/wireless/rt2x00/rt2800lib.ko
license: GPL
description: Ralink RT2800 library
version: 2.3.0
author: http://rt2x00.serialmonkey.com, Bartlomiej Zolnierkiewicz
srcversion: 569C0D9B076744C20D1B836
depends: rt2x00lib,mac80211,crc-ccitt
intree: Y
vermagic: 3.2.27+ preempt mod_unload modversions ARMv6 p2v8

One last info ;)

I think the proper driver should be (but i'm quite a newbie about Linux) the following:
http://wiki.debian.org/rt2870sta#Wheezy

**Comment by licaon-kter** [comment]
and another one: http://www.raspberrypi.org/phpBB3/viewtopic.php?f=26&t=16953

CONFIG_RT2800USB_RT33XX=y
CONFIG_RT2800USB_RT35XX=y
CONFIG_RT2800USB_UNKNOWN=y
CONFIG_RT2800_LIB=m
CONFIG_RT2X00_LIB_USB=m
CONFIG_RT2X00_LIB=m
CONFIG_RT2X00_LIB_FIRMWARE=y
CONFIG_RT2X00_LIB_CRYPTO=y
CONFIG_RT2X00_LIB_LEDS=y

**Comment by tombo9999** [comment]
Not the only one:

RT2870 Chipset and wireless, I'm desperate
http://www.raspberrypi.org/phpBB3/viewtopic.php?f=28&t=15465&p=158036&hilit=rt2870#p158036

**Comment by tombo9999** [comment]
One more:

http://www.raspberrypi.org/phpBB3/viewtopic.php?p=148784#p148784

------- post -------
I have one in mind. Ralink RT2870.

I have spent ages trying to get this to work on the RPi but failed every time.
If you can get this one to work you will be a genius!!!
I will give your other help a try when I get time. Busy right now.

**Comment by licaon-kter** [comment]
did you get a chance to test my builds? I have all the modules compiled there

**Comment by tombo9999** [comment]
not yet, waiting for new SD card  ;)

2012/9/11 licaon-kter notifications@github.com

**Comment by licaon-kter** [comment]
you can just copy it on the card along your current kernels

**Comment by asb** [comment]
We've already got all those CONFIG_ options enabled other than CONFIG_RT2800USB_UNKNOWN, which it looks like we should add. Thanks for the report.

**Comment by popcornmix** [comment]
CONFIG_RT2800USB_UNKNOWN has been added.

**Comment by tombo9999** [comment]
After rpi-update wifi dongle now works properly. Thanks a lot :)
