### ISSUE TITLE
Updated kernel patches disabled keyboard and mouse

### ISSUE THREAD

**Issue by williamhbell** [raspberrypi/linux#107]
Hi,

At around 18:00 (GMT) I ran an apt-get update , apt-get install.  This pulled down a number of updated.  During the kernel patch update the installer hung.  The Pi will now boot successfully, but when X is running the keyboard and mouse are disabled.  Before X starts, different consoles can be selected with the keyboard.  The setup is simple,

Raspberry Pi directly connected to logitech keyboard and mouse.
Connection from the Pi to the outside world via the RJ45 connection.

This setup has worked under Squeeze and Raspbian until this evening.

---

Since the Pi loads X straight away and sshd is disabled, it looks like it will have to be reinstalled.

Thank and best regards,

Will

**Comment by popcornmix** [comment]
The update can take a long time. You almost certainly have a mixure of old and new /boot/kernel.img and /lib/modules.
Running "apt-get upgrade" again may allow it to finish. Also running rpi-update may fix it:
http://elinux.org/R-Pi_Troubleshooting#Updating_firmware

However reinstalling may be the surest solution.

**Comment by williamhbell** [comment]
Hi,

The trouble is that I cannot type anything.  I can select another console before X startsx, but as soon as X starts the Pi forgets about the keyboard.  Presumably, a complete re-install is needed.

Thanks and best regards,

Will

**Comment by kripton** [comment]
With the X-server running (on the keyboard not working) can you try if these things here do work:
https://www.kernel.org/doc/Documentation/sysrq.txt ?

**Comment by williamhbell** [comment]
Hi,

After X has started the SysRq key does not respond.  Before X starts it seems to work.  Since I am really short of time and my son very much wants to get back on the Pi, I am going to do a full re-install.

Regards,  Will

**Comment by williamhbell** [comment]
After re-installation the Pi is completely dead.  The red power light is on, but nothing is happening.  Changing between two previously working power supplies does not work.  Presumably the firmware is completely messed up and there is no way of recovering it.

**Comment by williamhbell** [comment]
Switching to an old class 4 SD with squeeze, the Raspberry Pi boots successfully.  It looks like the class 10 Transcend (8GB) card partially failed during the kernel update and then completely failed when it was reinstalled.

**Comment by williamhbell** [comment]
Having booted the Pi twice with the old card, first with squeeze and then raspbian and flashed the class 10 card again, the Pi now boots with the class 10.  Before trying the class 10 card again, upgrade was run using the old card with raspbian.  Now the class 10 card seems to be working again.  What is the recommended way of checking for SD card errors?  fsck or something else?

**Comment by williamhbell** [comment]
After a complete update, the Pi locked up again with the class 10 card, it really seems to be the card.  Therefore, proceeding with an other class 6 card instead.

**Comment by williamhbell** [comment]
After quite a lot of time testing the affected system out, it looks like the firmware update did not complete successfully.  The Pi is refusing to be shutdown from X, but can be shutdown by root from the command line.  Time to re-flash the firmware.

**Comment by licaon-kter** [comment]
refusing to reboot ( 'cause there is no real shutdown ) from X is not a firmware thing by far, but a LXDE/X/etc misconfiguration

**Comment by williamhbell** [comment]
Yes, it sounds like it should be.  How it got in through some harmless apt-get upgrade commands is beyond me.  I am still concerned that the firmware is not completely right though.

**Comment by licaon-kter** [comment]
comparing md5sums for the written files and the downloaded files confirms this?
