### ISSUE TITLE
Update to 4.2

### ISSUE THREAD

**Issue by heniotierra** [raspberrypi/linux#1074]
I think it's time for an update to 4.2 kernel. You see, 4.2 has included new driver for the chips Mediatek mt7610u, which a lot of RPi owners use, including myself ofc. The old driver is not maintained anymore and the current version of the kernel is not compatible with it.

**Comment by popcornmix** [comment]
No.

Upstream 4.2 is not even stable yet (it's at rc2). You are free to test the 4.2 kernel if you build from source (https://github.com/raspberrypi/linux/tree/rpi-4.2.y).

I imagine we may move to 4.2 for official kernel in two or three months. No way now.
