### ISSUE TITLE
Problem with DVB.S2 USB in kernel Rpi2 openelec

### ISSUE THREAD

**Issue by tnds82** [raspberrypi/linux#1075]
Hello!

I have a problem with de fw with dvb-s2 usb card e lost connection in RPi2

https://www.dropbox.com/s/4lbnhs20lk1s7zq/log-2015-07-18-13.18.46.zip?dl=0

https://www.dropbox.com/s/hrwi4mjlci0v89r/log-2015-07-18-13.24.22.zip?dl=0

https://www.dropbox.com/s/zru995j35jqfnf1/log-2015-07-18-13.25.30.zip?dl=0

Can you help to fix problem in kernel on RPi2 ?

Best Regards

**Comment by P33M** [comment]
This line

```
[   14.624228] usb 1-1-port2: over-current change
```

means that your DVB-S2 card got switched off and on again by the USB port overcurrent monitor.
1. Make sure your power supply is adequate - the red PWR LED must remain continuously illuminated.
2. If 1. is OK, then try adding `max_usb_current=1` to config.txt in the boot partition.

**Comment by tnds82** [comment]
Hello,

Sorry for the delay on my update but i was on vacations and without any possibility of tests / update. Sorry for that.

I had made the change in the config.txt and it worked.
Also, i had discovered that my hardware (GENIEATECH) had came with a AC power supply with a 7.5V 1A, and we find out, that this hardwarr needs to work with at least 9V 1.5A. The seller has trick us sending a work AC Adapter.

I had start using a correct AC Adapter and everything is working well!! 

Thanks for the help!! Many thanks!
