### ISSUE TITLE
PCF8563 modules in armhf update please

### ISSUE THREAD

**Issue by fangfufu** [raspberrypi/linux#108]
Hi, I have a PCF8563 RTC chip attached to my Raspberry Pi. Every time I do rpi-update, I lose access to it as my old modules gets outdated. Could this module be supplied in the official kernel compilation please? RTC DS1307's module always gets automatically updated.

**Comment by asb** [comment]
Yes sure, just an oversight on our part. What CONFIG_ option is required?

**Comment by licaon-kter** [comment]
CONFIG_RTC_DRV_PCF8563

**Comment by fangfufu** [comment]
CONFIG_RTC_DRV_PCF8563=m

Cheers.

**Comment by popcornmix** [comment]
The full set of I2C and SPI RTC modules are now built.
