### ISSUE TITLE
Raspberry pi 2 stability and browser issue

### ISSUE THREAD

**Issue by JyotiranjanR** [raspberrypi/linux#1089]
I have purchased on Pi2. However, after a long struggle its not connecting to WIFI or with Ethernet cable. That is, internet is not working and browser can not open any page. However, when I gave it back for testing to where I have purchased, they are saying its working? So its very unstable and can not be used for IoT applications.

**Comment by popcornmix** [comment]
Sorry, this repo is for confirmed linux kernel bug reports.
I'd suggest asking for advise in the forum: https://www.raspberrypi.org/forums/viewforum.php?f=28
