### ISSUE TITLE
add LinuxPPS to pi gpio pin 

### ISSUE THREAD

**Issue by peterwillcn** [raspberrypi/linux#109]
Hi there, I found this thread while searching for related info on google. There is indeed a PPS-GPIO client, see http://groups.google.com/group/linux.kernel/browse_thread/thread/8455cc53fa14c298  It has been in mainline kernel since 3.2. You need to select PPS and PPS-GPIO client while doing menuconfig. I was able to register gpio1_31 (I hard-coded it as gpio_pin=63) on another ARM machine with an appropriate level shifter.

I don't have a RPI to play with. You would need to add the following to your board support package (probably in arch/arm/ to register the gpio pin that will be used for PPS:

add
# include <linux/pps-gpio.h>

add
/\* PPS-GPIO platform data */
static struct pps_gpio_platform_data pps_gpio_info = {
.assert_falling_edge = false,
.capture_clear= false,
.gpio_pin=63,
.gpio_label="PPS",
};

static struct platform_device pps_gpio_device = {
.name = "pps-gpio",
.id = -1,
.dev = {
.platform_data = &pps_gpio_info
},
};

static void pps_init(int evm_id, int profile)
{
int err;

err = platform_device_register(&pps_gpio_device);
if (err) {
pr_warning("Could not register PPS_GPIO device");
}
}

You will need to call pps_init in the configuration routine along with the calls to init other devices on the board.

dmesg will show the pps registration during boot up and show the pps capture events if you have pps debugging turned on.

[ 0.080893] pps_core: LinuxPPS API ver. 1 registered
[ 0.080906] pps_core: Software ver. 5.3.6 - Copyright 2005-2007 Rodolfo Giometti giometti@linux.it
[ 2.030757] pps_core: source pps-gpio.-1 got cdev (253:0)
[ 2.030773] pps pps0: new PPS source pps-gpio.-1
[ 2.035711] pps pps0: Registered IRQ 223 as PPS source

.....  later, after attaching the pps line from GPS

[ 8524.440161] pps pps0: capture assert seq #1531
[ 8525.439891] pps pps0: PPS event at 1328721600.905551895
[ 8525.439913] pps pps0: capture assert seq #1532
[ 8526.440188] pps pps0: PPS event at 1328721601.905827102
[ 8526.440232] pps pps0: capture assert seq #1533

As far as I know, there is none. 
Here's what I did (huge thanks to goodx for the help in doing this):
Prepare to compile the raspberry pi's kernel as instructed by this page:
http://elinux.org/RPi_Kernel_Compilation

Once you have the pi's kernel downloaded locally, merge everything under the drivers/pps section of the main linux branch (https://github.com/mirrors/linux/tree/master/drivers/pps) into the pi's kernel. You'll also need include/linux/pps-gpio.h from the main kernel, copy it into pikernel/include/linux. Overwrite files as needed.

I can't attach .c files, so I'm guessing there is a rule against it, so you'll unfortunately have to modify the architecture code yourself. 

Head over to pikernel/arch/arm/mach-bcm3807 and modify bcm3807.c. For this you'll want to include the pps-gpio.h file that you copied over earlier (#include <linux/pps-gpio.h>), and also add 
CODE: SELECT ALL
/\* PPS-GPIO platform data */
static struct pps_gpio_platform_data pps_gpio_info = {
.assert_falling_edge = false,
.capture_clear= false,
.gpio_pin=9,
.gpio_label="PPS",
};

static struct platform_device pps_gpio_device = {
.name = "pps-gpio",
.id = -1,
.dev = {
.platform_data = &pps_gpio_info
},
};

to the file. I added it right in the #ifdef CONFIG_BCM2708_GPIO section. 
Finally, search for 
CODE: SELECT ALL
bcm_register_device(&bcm2708_gpio_device);

and right after that put 
CODE: SELECT ALL
bcm_register_device(&pps_gpio_device);

Take note at all of the options in this struct, because they do matter. I've already confirmed that .gpio_pin represents the actual GPIO pin on the pi, not the pin numbering. so, in the example above, I chose to use GPIO 9, which is P1-21. 
PPS (Pin 16, GPIO 23) or  PPS (Pin 18, GPIO 24)
After you're done, save the file and exit. Configure the kernel appropriately, making sure that you're including the PPS GPIO drivers as well as PPS support (modules), and build the kernel normally. At this point you can follow all the normal procedures for building the Pi. 

Once you've copied over the kernel, firmware, and drivers, and then are able to boot the pi, run
CODE: SELECT ALL
sudo modprobe pps-gpio
to load the module. Check dmesg, and if your pulse is setup already, try using the pps-tools available at http://www.linuxpps.org/gitweb/?p=pps-tools;a=summary to test the pulse.

If this all sounds like an awful amount of work, I could potentially share my already compiled kernel. It's only 4MB, so if you're interested, I can pop it on a file sharing site. 

Eventually I hope to make a more readable guide, but since I don't have it completely working, I haven't got that far yet.
Linux raspberrypi 3.1.9-pps+ #6 PREEMPT Wed Aug 1 19:44:18 EDT 2012 armv6l

ref:
http://www.raspberrypi.org/phpBB3/viewtopic.php?f=41&t=1970

**Comment by popcornmix** [comment]
If you want this in the standard kernel tree, then you need to create a pull request.
It needs to be tested.
It needs to have no effect as a default. It shouldn't just grab a specific GPIO pin (that others may be using). The GPIO can be acquired after some explicit user commands (e.g. a modprobe, or by writing to /sys)

**Comment by Ferroin** [comment]
Control via sysfs is probably the best option as it doesn’t need any special tools, and the configuration can be changed without having to reload the module.  If you do choose to use sysfs, I would suggest adding a control to enable/disable it at runtime, and have it disabled by default.

**Comment by kukabu** [comment]
#717

**Comment by popcornmix** [comment]
PPS support is present now.
