### ISSUE TITLE
Kernel built for lesser CPU.

### ISSUE THREAD

**Issue by hexameron** [raspberrypi/linux#11]
The Linux kernel has options for CPU_V6K , but your kernel patches force  CPU_V6 only. The kernel overrides your toolchain so that kernel modules are being built for v6 not v6k

**Comment by popcornmix** [comment]
Good point. I've locally switched to CPU_V6K and it still works. Looking though the change in disassembly there's very little difference. Any idea what could be improved with this change?

**Comment by hexameron** [comment]
From the source I would not expect a lot of difference, and arch/arm/Makefile still uses:
tune-$(CONFIG_CPU_V6K)      :=$(call cc-option,-mtune=arm1136j-s,-mtune=strongarm)

My main concern is that I expected readelf to tell me that your kernel modules use vfp, and it doesn`t.
