### ISSUE TITLE
Enable MMC_SPI kernel config

### ISSUE THREAD

**Issue by bseibold** [raspberrypi/linux#111]
It would be great if `mmc-spi` was configured as a module (config is named `MMC_SPI`). This way you could attach a second (and third) SD card using the SPI interface on the GPIO header.

**Comment by STrRedWolf** [comment]
I second this request.  I'd like to do a high-storage media streamer with the Pi, and right now, it's got 64 gigs of space on it.

**Comment by popcornmix** [comment]
This is enabled in "next" firmware tree.
