### ISSUE TITLE
Tell kernel to log on tty2?

### ISSUE THREAD

**Issue by kosirdavid** [raspberrypi/linux#1114]
Hi,

I'm trying to get kernel log on `tty2` so I set `console=tty2` in `cmdline.txt`.
Still, kernel outputs it's log to `tty1`, while `tty2` is used for userspace programs output.

I'm not sure if this is right place to ask, but it seams pretty straightforward - how to tell kernel to use `tty2` for it's log?

I tried to play with fb kernel options, but I can only completely disable console fb, I see no way to set it on tty2 other than by cmdline parameter (which give no results).

Any ideas? Is this even a bug or it is supposed to be this way?

**Comment by P33M** [comment]
You're better off asking this on the forums:

https://raspberrypi.org/forums/

Also you may want to refer to 
http://www.tldp.org/HOWTO/Remote-Serial-Console-HOWTO/configure-kernel.html

Closing as not a pi-specific kernel issue.
