### ISSUE TITLE
Some patches seem to have gone missing in 4.1

### ISSUE THREAD

**Issue by Wren6991** [raspberrypi/linux#1120]
@pelwell some patches that existed in earlier branches seem to be missing in 4.1, e.g. the patch for bcm2708-dmaengine.c that silenced some compiler warnings.

What's the current process for migrating these patches to 4.1?

**Comment by pelwell** [comment]
Some patches do go missing, but I don't think this was one of them - it never made it into the tree, as far as I can tell.
