### ISSUE TITLE
mkknlimg not compatible with busybox

### ISSUE THREAD

**Issue by Ypnose** [raspberrypi/linux#1136]
Good evening,
<code>mkknlimg</code> is not compatible with <code>busybox</code>. <code>grep</code> implementation lacks <code>-b</code> option. So, we are almost unable to mark the kernel, on distro like Alpine Linux, which uses <code>busybox</code> natively for the system tools.
:no_entry_sign: @pelwell 

Output:

```
grep: unrecognized option: b
BusyBox v1.23.2 (2015-04-24 15:46:01 GMT) multi-call binary.

Usage: grep [-HhnlLoqvsriwFE] [-m N] [-A/B/C N] PATTERN/-e PATTERN.../-f FILE [FILE]...

Search for PATTERN in FILEs (or stdin)

        -H      Add 'filename:' prefix
        -h      Do not add 'filename:' prefix
        -n      Add 'line_no:' prefix
        -l      Show only names of files that match
        -L      Show only names of files that don't match
        -c      Show only count of matching lines
        -o      Show only the matching part of line
        -q      Quiet. Return 0 if PATTERN is found, 1 otherwise
        -v      Select non-matching lines
        -s      Suppress open and read errors
        -r      Recurse
        -i      Ignore case
        -w      Match whole words only
        -x      Match whole lines only
        -F      PATTERN is a literal (not regexp)
        -E      PATTERN is an extended regexp
        -m N    Match up to N times per file
        -A N    Print N lines of trailing context
        -B N    Print N lines of leading context
        -C N    Same as '-A N -B N'
        -e PTRN Pattern to match
        -f FILE Read pattern from file
```

**Comment by pelwell** [comment]
Adding --dtok will force it to append the trailer, whatever the input file. It won't include a valid kernel version string, but that doesn't matter.

**Comment by Ypnose** [comment]
Why not replace <code>-b</code> option by a "pure" Perl function?

**Comment by pelwell** [comment]
If somebody in the Alpine Linux community wants to create a Pull Request I'm sure it will be accepted.

**Comment by Ypnose** [comment]
The official <code>APKBUILD</code> for the <code>RPi</code> do not use <code>mkknlimg</code>, so I doubt it's gonna happen. It is not about Alpine Linux, it is about supporting <b>non-GNU</b> implementations.
I probably do not need to say you busybox is quite common in embedded world. You could simply let it go, but it's definitely a wrong idea…
