### ISSUE TITLE
Shut down instead of reboot

### ISSUE THREAD

**Issue by exander77** [raspberrypi/linux#1138]
I am using rpi-4.1.y current HEAD build of kernel. Every time I do reboot (sudo reboot) the system shuts down instead. Could it be kernel related?

**Comment by popcornmix** [comment]
Can you describe what happens with ACT LED when you type "sudo reboot".
e.g. are there are any regular flashing patterns.
Do the network LEDs go off?
What's the last line you see on console?

**Comment by Ruffio** [comment]
@exander77 has your issue been resolved? If so, please close this issue. Thanks.

**Comment by JamesH65** [comment]
Seems to work fine on latest kernel.
