### ISSUE TITLE
Pls add IT913x options in kernel

### ISSUE THREAD

**Issue by Beacha** [raspberrypi/linux#114]
Dear developers.

Thank you for your efforts in Raspbian.
Could you pls invoke the DVB USB option IT913X in the kernel, and add the module dvb-usb-it913x and firmwares dvb-usb-it913x-01.fw and dvb-usb-it913x-02.fw in the lib/firmware directory.

That would really help me in my quest to build a home TV server.

**Comment by TommyFlowers** [comment]
I would also like to vote for support for IT9135 Version 2 in the kernel.

The code available from linuxtv has support for Version 2 devices:
./linux/drivers/media/usb/dvb-usb-v2/it913x.c

MODULE_PARM_DESC(firmware, "set firmware 0=auto"\
        "1=IT9137 2=IT9135 V1 3=IT9135 V2");

Like Beacha, I am trying to use this USB DVB-T device with the Pi to create a home PVR.

Many thanks for your help.

**Comment by Beacha** [comment]
The request still stands, but I found a temp solution:
http://www.raspberrypi.org/phpBB3/viewtopic.php?p=207519#p207519

Hope this helps for now

**Comment by popcornmix** [comment]
The default kernel should support this:
/lib/modules/3.2.27+/kernel/drivers/media/dvb/frontends/it913x-fe.ko
/lib/modules/3.2.27+/kernel/drivers/media/dvb/dvb-usb/dvb-usb-it913x.ko

You will have to download the firmware yourself.

The "next" kernel should support the v2 device:
modules/3.6.7+/kernel/drivers/media/dvb/dvb-usb/dvb-usb-it913x.ko
modules/3.6.7+/kernel/drivers/media/dvb/frontends/it913x-fe.ko
modules/3.6.7+/kernel/drivers/media/rc/keymaps/rc-it913x-v2.ko
modules/3.6.7+/kernel/drivers/media/rc/keymaps/rc-it913x-v1.ko

again, you will need to download the firmware.

For info about "next" firmware see:
http://www.raspberrypi.org/phpBB3/viewtopic.php?f=29&t=19334&p=218734p218734

**Comment by TommyFlowers** [comment]
Many thanks both for your quick replies.
