### ISSUE TITLE
forgotten Password

### ISSUE THREAD

**Issue by HBMBR** [raspberrypi/linux#1146]
Hi - how would i reset a forgotten root password?

**Comment by popcornmix** [comment]
You should use the forum for support. But:
`sudo passwd root`
should allow you to set it.

**Comment by HBMBR** [comment]
No no - after you have installed the system how would you reset the password then after you have set it.

I installed the system set the password - went away for a month, now am back and i dont remember the password - how would i reset it ?

**Comment by popcornmix** [comment]
Just try it. With "sudo" you can change root password without knowing it.

**Comment by HBMBR** [comment]
from which prompt - i cannot log into the System

**Comment by popcornmix** [comment]
Do you have the pi password? It will be user=pi password=raspberry if you haven't changed it.

**Comment by HBMBR** [comment]
I changed all the passwords - 

on the desktop version you can reset it during the grub boot-loader screen.

**Comment by popcornmix** [comment]
There are a few ways of doing this, but create a thread here: https://www.raspberrypi.org/forums/
This is not the right place for this - each message spams a large number of developers who follow the github repo.
