### ISSUE TITLE
Please enable CONFIG_UHID

### ISSUE THREAD

**Issue by matlo** [raspberrypi/linux#1148]
Hello,
Please consider adding the uhid module in the next update.

**Comment by pelwell** [comment]
Can you say what it does and why it would be useful?

**Comment by matlo** [comment]
It allows connecting a userspace-managed device to the HID core driver.
I need it for the GIMX project.

**Comment by pelwell** [comment]
I've got no objections - the option just causes a small, simple, self-contained module to be built. @popcornmix ?

**Comment by popcornmix** [comment]
Sounds okay - will add.

**Comment by matlo** [comment]
Thanks!

**Comment by popcornmix** [comment]
This should be in latest rpi-update firmware.

**Comment by matlo** [comment]
I got the uhid module in the update, and tested it successfully.
Thanks. This is great for the GIMX users.

**Comment by popcornmix** [comment]
No problem. GIMX looks interesting. No (new enough) games console here, but it's an interesting use of a Pi.
