### ISSUE TITLE
DWC_OTG code fails during write opration

### ISSUE THREAD

**Issue by anviksingh** [raspberrypi/linux#115]
Hi, 
I am using synopsys dwc_otg core in our SoC (IP version 2.92a).
I have downloaded the code (dwc_otg 2.94a) from the dwc_otg in raspberry main line (raspberrypi-linux-78f82bc\drivers\usb\host).

I have configured the core as host and I am using HSIC mode of operation.
Enumeration happens properly with following Device settings:
1) Internal DMA mode ON.
2) HSIC mode of operation ON.
3) Non-SG mode of operation ON.

Queries:
1) When data read is called from the device node /dev/sda, 0x55AA55AA is read as 0x66996699 when I print the data dump.
2) Data write fails when the data size is >= 4096 and device resets.

Could some one please suggest where should I look to make the data transfer correct ?
Do you think this is related to platform settings (clock settings, external fifo etc.) ?

~
Anvik

**Comment by popcornmix** [comment]
Sorry nothing immediately springs to mind, and I can't help with dwc_otg on other platforms. We have enough USB problems to deal with on Raspberry Pi without supporting other platforms.
