### ISSUE TITLE
scripts/mkknlimg assumes ARCH_BCM283x when bcm2835_wdt is builtin

### ISSUE THREAD

**Issue by notro** [raspberrypi/linux#1157]
@pelwell Can we drop this:

``` perl
        $is_283x ||= config_bool($res, 'brcm,bcm2835-pm-wdt');
```

I want to have this driver builtin on ARCH_BCM270x to take advantage of it's restart/poweroff code, but currently that means I have to use --dtok to get the right DT.

**Comment by pelwell** [comment]
Good call. Done.
