### ISSUE TITLE
fatal error: mach/gpio.h: No such file or directory

### ISSUE THREAD

**Issue by weakiwi** [raspberrypi/linux#1168]
when I try to make the newest kernel，I meet with this question.And I used `find -name gpio.h`.The result showed that there is gpio.h under the mach folder.So how can I solve this probelm.
thx~

**Comment by popcornmix** [comment]
Are you talking about rpi-4.1.y kernel?
Are you using bcm2709_defconfig or bcmrpi_defconfig?

**Comment by weakiwi** [comment]
yes,it's rpi-4.1.y
and I used 'make allyesconfig' before 'make'

**Comment by pelwell** [comment]
Why would you use "allyesconfig"? Follow the kernel building guide [here](https://www.raspberrypi.org/documentation/linux/kernel/building.md).
