### ISSUE TITLE
How to getting FB_TFT_ILI9163 enabled?

### ISSUE THREAD

**Issue by semico** [raspberrypi/linux#1169]
Could anyone give me a step by step tutorial to getting FB_TFT_ILI9163 enabled?

I've no idea about any linux programming, just know a little basic commands and want use a small ftf screen with raspberry pi. 

thx a lot

**Comment by pelwell** [comment]
This isn't the right place for queries like this. Try the [Interfacing Forum](https://www.raspberrypi.org/forums/viewforum.php?f=44).
