### ISSUE TITLE
Failure: sudo apt-get update after installing new raspbian image

### ISSUE THREAD

**Issue by ckuehnel** [raspberrypi/linux#117]
I get always errors for apt-get update or apt-get install <prog>  with the latest image (can't resolve ....).
apt-get -f install makes no changes. 
I changed  /etc/apt/sources.list to deb archive.raspbian.org/.... and deb downloads.raspbian.org/..., but there is no change in behavior.
Is there anything wrong with the image or the repository?

**Comment by licaon-kter** [comment]
do list the errors too

**Comment by ghollingworth** [comment]
No further information, reopen if still a problem
