### ISSUE TITLE
mkknlimg: Problem on Gentoo with xz-compressed Kernel

### ISSUE THREAD

**Issue by mkrsn** [raspberrypi/linux#1171]
I've Compressed my RPi2-Kernel (4.1.10-v7+) with XZ on Gentoo. It seems that mkknlimg can't detect that the Kernel is xz-compressed and copy's the kernel in Passthrough Mode. After changing the Compress-methode to gzip it's working.

If i'am right (my Perl-Knowledge is very minimal), the Script uses "unxz --single-stream" to try decompressing the Kernel. The Parameter "--single-stream" doesn't exist on unxz (xz-utils v5.0.8), which is the actually Stable Version on Gentoo. After Upgrading to testing (v5.2.2) it's working now.

Unfortunately the Script says nothing about that Problem, just goes in Passthrough. So It would be nice if the Script would contain a Version-Check of unxz.

Thanks :)

Greeting from Germany
Matthias

**Comment by pelwell** [comment]
We don't officially support any distribution other than Raspbian, but if you want to submit a Pull Request with a suitable check we are likely to accept it.

**Comment by Ruffio** [comment]
@mkrsn has your issue been resolved? If so, please close this issue. Thanks.

**Comment by mkrsn** [comment]
Yes, it was solved by gentoo.
