### ISSUE TITLE
Provide udlfb (support for displaylink) in firmware

### ISSUE THREAD

**Issue by paines** [raspberrypi/linux#1180]
Any chance compiling kernel/modules width udlfb ? There is a bunch of us guys using the PI with USB displays. That would be awesome. Thanks!

**Comment by pssc** [comment]
this was enabled at some point I know I asked for it and tested it when enabled but that was in the 3.X series

**Comment by popcornmix** [comment]
Is `CONFIG_FB_UDL=m` sufficient?

**Comment by paines** [comment]
@pssc 
When I fired up raspbian it workd just out of the bix. So you are right, it was enabled for 3.X. But after I firmware upgrade, which would pull kernel + overlays, it doesn't work anymore out of the box. One has to pull the sources, and recompile the whole thing.

**Comment by paines** [comment]
@popcornmix 
Yes, that would be suffcient.

**Comment by popcornmix** [comment]
Okay - added to linux tree. Will appear in next firmware update.

**Comment by paines** [comment]
Great! Thank you so much

**Comment by popcornmix** [comment]
rpi-update firmware now has this module
