### ISSUE TITLE
Kernel and module version mismatch after upgrade

### ISSUE THREAD

**Issue by b64** [raspberrypi/linux#1181]
Start out with a vanilla Raspian. Do a apt-get update / apt-get upgrade. Compare uname -r (= 3.18.11-v7+) with the directory names in /lib/modules (= 4.1.7+ and 4.1.7-v7+), an obvious mismatch.

**Comment by pelwell** [comment]
Did you reboot?

**Comment by b64** [comment]
You are right.  The mismatch disappears after a reboot. My error.
