### ISSUE TITLE
Boot cmdline filesystem

### ISSUE THREAD

**Issue by licaon-kter** [raspberrypi/linux#119]
Either modify linux/arch/arm/configs/bcmrpi_\* -> CONFIG_CMDLINE="dwc_otg.lpm_enable=0 console=ttyAMA0,115200 kgdboc=ttyAMA0,115200 root=/dev/mmcblk0p2 rootfstype=ext3 rootwait"  to rootfstype=ext4 or build in Ext3 support. Yeah, i know cmdline.txt overrides it but if that file gets corrupted/deleted at least it will still boot correctly.

**Comment by popcornmix** [comment]
Actually if there is no cmdline.txt, start.elf does fill in a usable one (with ext4).
However I agree, ext4 in the default makes more sense than ext3.

**Comment by popcornmix** [comment]
ext3 was switched to ext4 long ago.
