### ISSUE TITLE
Kernel OOPS in SDHCI on boot with the llm patch

### ISSUE THREAD

**Issue by ddv2005** [raspberrypi/linux#120]
Kernel OOPS in SDHCI on boot with the llm patch because sdhci_reset called with enabled preempt.
sdhci_spin_enable_schedule unnecessary in sdhci_reset.
This is patch to fix it https://gist.github.com/3761879 .

**Comment by popcornmix** [comment]
Thanks.
So the reset could still cause 100ms of latency to usb?

**Comment by ddv2005** [comment]
Usually it never entered to busy loop but on some slow SD cards it can take 1-2ms. Moreover, it does not matter for reset on init because IRQ's not disabled.

**Comment by popcornmix** [comment]
Thanks. Pushed out.
