### ISSUE TITLE
Input: xpad - add support for NEW Xbox One controllers

### ISSUE THREAD

**Issue by drsternau** [raspberrypi/linux#1202]
When I plug in the new Xbox One Controller (this one has a audio jack) my system crashes. 
The issue seems to be the unrecognized id of the controller. 
As Erik Lundgren pointed out, this issue can be addressed by adding 

{ 0x045e, 0x02dd, "Microsoft X-Box One pad (Covert Forces)", 0, XTYPE_XBOXONE }, 

as line 128.

It it possible to insert this?

**Comment by Ferroin** [comment]
This is a known issue in upstream Linux, and a patch has been posted there.

**Comment by lurch** [comment]
I suspect if you provide a link to the (accepted?) upstream patch, @popcornmix will be happy to pull it into this repo.

**Comment by popcornmix** [comment]
@Ferroin can you point at the upstream commit? I'm not seeing it on 4.4 for example.
In general if it is accepted upstream and we can cherry-pick it, we are much more likely to add to the kernel (as the patch will be dropped at some future kernel bump).
If it's not accepted upstream, then we are less likely to pick it.

**Comment by Ferroin** [comment]
I don't know the exact commit, and I don't recall when it got merged, but I'm pretty sure something ended up in 4.3 to fix it.

I can defiantly look though, but it may be tomorrow or Wednesday before I get a chance to.

**Comment by popcornmix** [comment]
Okay it seems to be in 4.4:
https://github.com/raspberrypi/linux/blob/rpi-4.4.y/drivers/input/joystick/xpad.c#L128

we are moving to this kernel in the near future and it can be tested early with:
`sudo BRANCH=next rpi-update`

**Comment by Ruffio** [comment]
@drsternau has your issue been resolved? If so, please close this issue. Thanks.

**Comment by drsternau** [comment]
@Ruffio Sorry! Yeah, the issue has been resolved.

**Comment by drsternau** [comment]
@Ruffio Sorry! Yeah, the issue has been resolved.
