### ISSUE TITLE
Include bmp085-i2c module

### ISSUE THREAD

**Issue by anomen-s** [raspberrypi/linux#1204]
raspberrypi/firmare provides  bmp085_i2c-sensor-overlay.dtb but kernel module is missing.

Please enable:
CONFIG_BMP085_I2C=m

**Comment by Ruffio** [comment]
@anomen-s has your issue been resolved? If so, please close this issue. Thanks.

**Comment by JamesH65** [comment]
@popcornmix This doesn't appear to be set in the current kernel - are we likely to want it?

**Comment by pelwell** [comment]
I think we should have it - there is an overlay that uses it.

**Comment by pelwell** [comment]
This config option (and driver) has been subsumed by BMP280 which supports BMP085, BMP180, BMP280 and BME280. Current kernels support all of these over I2C (and SPI where appropriate).
