### ISSUE TITLE
Selecting USB Card as default in Audio Device Settings not working

### ISSUE THREAD

**Issue by rbnpi** [raspberrypi/linux#1209]
On Jessie the GUI Audio Device Settings sees my 3 Audio Cards {internal bcm2835 ALSA, USB Audio device (Alsa mixer) and IQaudIODAC (Alsa mixer)} and I can click the Make Default button for any of them, but it will not remember the setting for the USB card even though it marks it as default. It works for the other two.
Alsa Mixer shows the three cards 0 bcm2835, 1 USB Audio and 2 IQaudIODAC
If I edit the .asoundrc file in the Pi home directory directly and modify it to read
pcm.!default {
              type hw
              card 1
}

ctl.!default {
           type hw
           card 1
}

then I can successfully play through the USB card.
If I then look at Audio Device settings again, it has the USB card marked as default, and if I change it to another card and set it as default it does so, but it will not then let me change back again to the USB card without editing the  .asoundrc file directly.

I also want to set the USB card as default when running on my pizero, and the same problem occurs there as on my Pi2 described above.

**Comment by popcornmix** [comment]
This isn't a linux kernel issue. Probably best reported here:
https://github.com/RPi-Distro/repo
