### ISSUE TITLE
mount using 100% CPU

### ISSUE THREAD

**Issue by Dmole** [raspberrypi/linux#121]
https://bugs.launchpad.net/raspbian/+bug/1054768

**Comment by popcornmix** [comment]
I think you will need to provide more evidence that this is a linux kernel bug. 
Is the encrypted filesystem on sdcard or USB disk or something else?

**Comment by Dmole** [comment]
If you can't kill something it's likely not a user space problem.
but just to be sure I installed the old image and reproduced the problem after updating the kernel but no packages;

dd bs=1m if=2012-08-16-wheezy-raspbian.img of=/dev/rdisk3
#booted, resized root, rebooted
apt-get install git lvm2 cryptsetup
wget http://goo.gl/1BOfJ -O /usr/bin/rpi-update;
chmod +x /usr/bin/rpi-update; rpi-update 240;
shutdown now -r;
vgimport vg_right
vgchange -ay vg_right
cryptsetup luksOpen /dev/vg_right/lv_right crypt_right
mount /dev/mapper/crypt_right /media/right

nasty hang where before there was non.

I don't have a backup of the intermediate kernel that had XTS support but no mount problems, but I'll try checking out a few different commits from git to see if I can find out which one was the regression.

**Comment by Dmole** [comment]
using git clone http://github.com/Hexxeh/rpi-firmware.git
I have narrowed down where the regression is/was:

Current HEAD fails (mount hangs) (kernel.img md5sum 81282fe2ad1d3fb1ac967f37a08ede74)
commit fa03a4070e42ba7d0c632debbe87bdd809ff9e2a
Date:   Sat Sep 1 01:04:11 2012 +0100

...9 commits...

fails (kernel.img md5sum 832534b281dd72cf5ed89d0feef78865)
commit 424079987166d37652236988f691bbe00f58ba6f
Date:   Sun Aug 19 12:48:04 2012 +0100

won't boot (kernel.img md5sum aa4de6903ce9c5a9489ffe2fff2c5706) (Rebase to kernel 3.2.27)
commit 0ef3d91e613a3d8db5debbd7eb8105071bfcb9be
Date:   Sat Aug 18 15:30:25 2012 +0100

won't boot (kernel.img md5sum 2c3ace3249aabc90d5dae39332bd269b)
commit 800d33e6f1284d8ef4f255c35017b32e5a118bda
Date:   Fri Aug 17 23:55:17 2012 +0100

WORKS   (kernel.img md5sum 2c3ace3249aabc90d5dae39332bd269b)
commit 8c628900aabe4a15743d8a11cb6169ad0bf1918e
Date:   Fri Aug 17 18:29:51 2012 +0100

WORKS First kernel i can test with (XTS support)
commit 8ddf43766192b3c7549262b376bb4d840a610ff7
Date:   Wed Aug 15 21:25:43 2012 +0100

so kernel 3.2.27 is likely the culprit

**Comment by popcornmix** [comment]
Thanks for investigating.
Unfortunately if it is the change to 3.2.27, it is not a Raspberry Pi specific change, and is may be an upstream bug. 
Might be worth searching for any reports of this problem on other platforms.

**Comment by Dmole** [comment]
Yes it's likely upstream, As pointed out in the link of the first post there are similar but not identical mount problems in other distributions. maybe we should use a more stable branch for the official build?

Also this repo is not listed as down stream of anything on github, so should I assume it's re-basing off https://github.com/torvalds/linux ?

Any pointers on where to look for the problem code?

**Comment by Dmole** [comment]
This is now fixed ( tested in kernel 3.6.11 )
