### ISSUE TITLE
Could not load fbtft module on boot

### ISSUE THREAD

**Issue by incyi** [raspberrypi/linux#1215]
It didn't worked to load the module fbtft from notro on boot. Everytime when the Raspberry Pi Zero is started I run this command to load it:
sudo modprobe fbtft_device custom name=fb_ili9341  gpios=reset:25,dc:24,led:18 speed=16000000 rotate=90 bgr=1

And then run to show the console:
con2fbmap 1 1

Raspbian Jessie on Raspberry Pi Zero with this kernel:
pi@raspi:~ $ uname -a
Linux raspi 4.1.13+ #826 PREEMPT Fri Nov 13 20:13:22 GMT 2015 armv6l GNU/Linux

**Comment by notro** [comment]
Have you tried this: https://github.com/notro/fbtft/wiki#make-it-permanent-debian-jessie-arch-linux-systemd

**Comment by incyi** [comment]
This worked ! Thanks. Now I need to figure out to load the console on the tft.

**Comment by dlech** [comment]
See https://github.com/notro/fbtft/wiki/Boot-console

**Comment by incyi** [comment]
Yes that did the work !

Problem solved. I have a working lcd now which is autostarting from boot ! Great !

**Comment by popcornmix** [comment]
Okay to close?

**Comment by incyi** [comment]
Yes. Okay to close.
