### ISSUE TITLE
provide headers for module-compilation

### ISSUE THREAD

**Issue by herzi** [raspberrypi/linux#1220]
As of today, kernel module developers have to recommend against running the kernel shipped with rpi-bootloader because there are no headers to compile against. See e.g. [rtl8812AU_8821AU_linux](https://github.com/abperiasamy/rtl8812AU_8821AU_linux/blob/master/README.md#compiling-for-raspberry-pi).

This is very unfortunate, as these users cannot benefit of improvements in this kernel image.

Please consider shipping a package called `linux-headers-rpi-bootloader` or `raspberry-bootloader-headers`, so we can happily compile against a more modern Linux kernel without having to build one on our own.

**Comment by popcornmix** [comment]
This is a packaging issue rather than a kernel issue. I'd suggest requesting the package here:
https://github.com/RPi-Distro/repo/issues/
