### ISSUE TITLE
lirc_rpi.c does not compile

### ISSUE THREAD

**Issue by imbens** [raspberrypi/linux#1236]
I cloned branch rpi-4.4.y and made some changes as described in https://www.raspberrypi.org/forums/viewtopic.php?f=29&t=129653&p=866209
The file lirc_rpi.c does not compile, complaining about the incomplete type gpio_chip.
I am new to kernel compilations, so I may be doing something I should not do.

**Comment by popcornmix** [comment]
This isn't really the right place to ask for how to compile.
The kernel builds for me and presumably others in the thread, so it's probably worth asking in forum.

I'd suggest as a first step you follow these instructions without making any config changes:
https://www.raspberrypi.org/documentation/linux/kernel/building.md

to make sure your environment is correct. Once that builds okay you can try making the changes described in thread.
