### ISSUE TITLE
Kernel Oops  when USB receiver connected at boot(USB hid as a module)

### ISSUE THREAD

**Issue by hex445** [raspberrypi/linux#125]
Hello,

Yesterday I recompiled kernel with these options:
CONFIG_HID=m
CONFIG_USB_HID=m

I need this to use driver for PHILIPS MCE USB IR Receiver- Spinel plusf0r ASUS

"The module depends on usbhid but it has to be loaded _before_ the usbhid module, in order to claim the device. Otherwise usbhid claims the device and hid-philips-asus can not act on it"

When receiver is connected at boot it causes kernel oops:
http://web1.ezrodlo.pl/oops.jpg

But when connected after boot(hid-philips-asus loaded) it works correctly.

Do you have any suggestions ?

**Comment by hex445** [comment]
One more thing. When keyboard(or bluetooth adapter I had at hand) is not connected and usb receiver is plugged after complete boot, this oops also appears. 

I use this script(/etc/rc.local) if it matters.
#!/bin/sh

# This script forces loading hid-philips-asus module before usbhid

MODINFO=`modinfo hid-philips-asus 2>/dev/null`
if [ -z "$MODINFO" ]; then
    echo "Module 'hid-philips-asus' is not installed."
    exit
fi

# get list of existing hid modules

MODULES=`lsmod|grep hid| cut -d " " -f 1 | grep hid`

# unload them

echo "Unloading existing hid modules."
for module in $MODULES; do
    modprobe -vr $module
done

echo "Loading hid_philips_asus module."

# load hid_philips_asus first

modprobe -v hid_philips_asus

echo "Reloading other hid modules."

# load the rest modules

for module in $MODULES; do
    modprobe -v $module
done

**Comment by ghollingworth** [comment]
The stacktrace doesn't actually list where the crash happened.  can you search for the PC address in the System.map file to see which function it was sat in?

**Comment by popcornmix** [comment]
@ghollingworth 
There is mention of mce_request_packet (from drivers/media/rc/mceusb.c) in the photo.

**Comment by hex445** [comment]
Linux raspberrypi 3.2.27+ #1 PREEMPT Wed Nov 14 19:42:38 UTC 2012 armv6l GNU/Linux
Still the same
http://web1.ezrodlo.pl/oops2.jpg

**Comment by hex445** [comment]
3.6.11+
Still the same

**Comment by ghollingworth** [comment]
We've found and fixed a bunch of errors that could have caused this (dequeueing errors) Could you try again with the latest 3.6.y kernel

$ sudo rpi-update
