### ISSUE TITLE
WLAN: USB Wireless device stick 0bda:818b does not work

### ISSUE THREAD

**Issue by vit1251** [raspberrypi/linux#1250]
Hello kernel developer,

```
I pay on eBay USB Wireless device 0bda:818b it is USB WiFI WLAN card. Supporting only Wireless 802.11n standart.

Now it does not work on current version of system. Could you provide more details about this problem? How to fix this?
```

Thanx.

**Comment by popcornmix** [comment]
I don't believe that device is supported by upstream linux. As such we don't support it.

There may be a workaround here:
https://www.raspberrypi.org/forums/viewtopic.php?f=45&t=103989

but really you should check for upstream linux support before buying a dongle.

**Comment by 14praveenk** [comment]
Try using a different Linux kernel. Sometimes a kernel does not support one USB dongle. For example the version 4 did not support my USB whereas the version 3 did

**Comment by Ruffio** [comment]
@vit1251 has your issue been resolved? If so, please close this issue. Thanks.

**Comment by vit1251** [comment]
Techivally, no. But I lost this WiFi dongle and it resolve current issue ;)
Have a nice day.
