### ISSUE TITLE
Module bcm2708_wdog may be duplicate and should be removed

### ISSUE THREAD

**Issue by Terminus-IMRC** [raspberrypi/linux#1263]
There are two(!) watchdog drivers which uses the same hardware registers: `bcm2708_wdog` and `bcm2835_wdt`.

`bcm2708_wdog` looks just a temporary implementation because it processes ioctls and other stuffs only in the code. In contrast, `bcm2835_wdog` uses Linux's generic watchdog code to do the stuffs. In addition, `bcm2835_wdog` was merged to Linux mainline.

So I think `bcm2708_wdog` is duplicate and should be removed from the tree.

**Comment by pelwell** [comment]
If you look at the rpi-4.3.y and rpi-4.4.y branches you will see that it has already been removed, and we will be switching to rpi-4.4.y very soon.

**Comment by Terminus-IMRC** [comment]
Thank you for your reply.
I'm really sorry for my lack of research...

**Comment by pelwell** [comment]
It's no problem - your suggestion was a good one, but great minds think alike.
