### ISSUE TITLE
Network stops working randomly (running 3.2.27-cutdown-g9245b4c)

### ISSUE THREAD

**Issue by dflogeras** [raspberrypi/linux#127]
Hi, I'm running Gentoo with the aforementioned kernel (latest as of time of writing). It occasionally will have a problem with either the USB or the USB network card and stop talking on the network, requiring a reboot. Unfortunately I don't have much to debug from, but I will post the kernel message at the time it stopped. I can also post my .config if required.  I have set "vm.min_free_kbytes = 4096" when following setup instructions (not sure if this is still required).

Sep 30 11:26:36 pie kernel: ------------[ cut here ]------------
Sep 30 11:26:36 pie kernel: WARNING: at net/sched/sch_generic.c:255 0xc02caf0c()
Sep 30 11:26:36 pie kernel: NETDEV WATCHDOG: eth0 (smsc95xx): transmit queue 0 timed out
Sep 30 11:26:36 pie kernel: Modules linked in: cpufreq_ondemand xt_recent iptable_filter ip_tables smsc95xx
Sep 30 11:26:36 pie kernel: Backtrace:
Sep 30 11:26:36 pie kernel: Function entered at [<c0011e50>] from [<c0353440>]
Sep 30 11:26:36 pie kernel: r6:000000ff r5:c02caf0c r4:c03f3e10 r3:00000000
Sep 30 11:26:36 pie kernel: Function entered at [<c0353428>] from [<c002233c>]
Sep 30 11:26:36 pie kernel: Function entered at [<c00222e8>] from [<c00223f8>]
Sep 30 11:26:36 pie kernel: r8:c046074c r7:c03faeb8 r6:00000000 r5:ce955000 r4:c03f2000
Sep 30 11:26:36 pie kernel: r3:00000009
Sep 30 11:26:36 pie kernel: Function entered at [<c00223c0>] from [<c02caf0c>]
Sep 30 11:26:36 pie kernel: r3:ce955000 r2:c03a8a08
Sep 30 11:26:36 pie kernel: Function entered at [<c02cac5c>] from [<c002dba8>]
Sep 30 11:26:36 pie kernel: Function entered at [<c002da90>] from [<c0027fd4>]
Sep 30 11:26:36 pie kernel: Function entered at [<c0027f3c>] from [<c00284d8>]
Sep 30 11:26:36 pie kernel: Function entered at [<c0028440>] from [<c000f4d0>]
Sep 30 11:26:36 pie kernel: r4:c040a854 r3:00000000
Sep 30 11:26:36 pie kernel: Function entered at [<c000f494>] from [<c00081f0>]
Sep 30 11:26:36 pie kernel: r6:f200b200 r5:60000013 r4:c000f624 r3:c000f620
Sep 30 11:26:36 pie kernel: Function entered at [<c00081e0>] from [<c000e134>]
Sep 30 11:26:36 pie kernel: Exception stack(0xc03f3f38 to 0xc03f3f80)
Sep 30 11:26:36 pie kernel: 3f20:                                                       ffffffed 00000000
Sep 30 11:26:36 pie kernel: 3f40: c03f3f80 00000000 c03f2000 c04189c4 c03f7634 c03f762c 00004008 410fb767
Sep 30 11:26:36 pie kernel: 3f60: 003eaf74 c03f3f8c c03f3f90 c03f3f80 c000f620 c000f624 60000013 ffffffff
Sep 30 11:26:36 pie kernel: Function entered at [<c000f5f8>] from [<c000f850>]
Sep 30 11:26:36 pie kernel: Function entered at [<c000f798>] from [<c0351da0>]
Sep 30 11:26:36 pie kernel: r6:c0647900 r5:c03ec224 r4:c03f2000 r3:00000001
Sep 30 11:26:36 pie kernel: Function entered at [<c0351d18>] from [<c03d274c>]
Sep 30 11:26:36 pie kernel: r4:c03f40bc r3:00000000
Sep 30 11:26:36 pie kernel: Function entered at [<c03d2500>] from [<00008040>]
Sep 30 11:26:36 pie kernel: ---[ end trace 940d8875178e3e8a ]---

**Comment by dflogeras** [comment]
I see the bug report stripped all of the addresses from the call stack. Let me know if there's anything I can do to get a more useful BT, I'm comfortable modifying kernels.

**Comment by licaon-kter** [comment]
afaik, **vm.min_free_kbytes** should be at least 8192

setting **smsc95xx.turbo_mode=N** in cmdline.txt helps somehow?

( both covered here: http://elinux.org/R-Pi_Troubleshooting#Crashes_occur_with_high_network_load )

**Comment by dflogeras** [comment]
hmm, I tried upping the min_free_kbytes to 8192, and it still stopped working after a few days.  Also, unlike most of the other reports it isn't due to high network load, and doesn't show the same kernel warnings (smsc95xx 1-1.1:1.0: eth0: kevent 2 may have been dropped). I will try again with turbo_mode=N.

**Comment by dflogeras** [comment]
And with turbo_mode=N it stopped working after about a day of uptime. Could anyone suggest a way to get a decent kernel bactrace for the developers?

**Comment by Ferroin** [comment]
Same problem with cutdown, full, and locally built kernels on debian softfloat.
Network stops working consistently within 1 hour of boot.
Network load (while it is working) is near 0, dosen't seem to change based on cmdline.txt options.

**Comment by kelvinlawson** [comment]
I get the same "NETDEV WATCHDOG: eth0 (smsc95xx): transmit queue 0 timed out" and random Ethernet outages using Arch Linux 2012-09-18.

I was previously using Raspbian 2012-09-18-wheezy which had Ethernet outages but with the message "smsc95xx 1-1.1:1.0: eth0: Failed to write register index". Raspbian also trashed my rootfs on the SD card so I switched to Arch but it evidently is having similar Ethernet problems.

I have tried two PSUs, an HTC phone charger rated at 1A, and the Nexus 7 charger rated at 2A.

The one thing that might be out of the ordinary here is that I have an FTDI USB/serial device attached and am polling it frequently. Ethernet traffic is very low.

**Comment by Ferroin** [comment]
Still having same problem with the current kernel and firmware versions, no peripherals at all except network connection.  I didn't have this problem prior to commit 2843e37f77f0b01001f5659906166c92ba3801d0.

**Comment by dflogeras** [comment]
Not sure how relevant this is, but here goes:

my system is a very lightly loaded system (in terms of both CPU and network).  It typically runs dnsmasq for dhcp (very light load, 1 client), ntpd, ddclient to update dynamic dns, apcupsd to monitor a battery.

Until recently I had been leaving myself signed into IRC (irssi) inside of a screen session which would be a constant, but pretty low ethernet traffic (sitting in 3-4 channels).  It was typically hitting the "NETDEV WATCHDOG: eth0 (smsc95xx): transmit queue 0 timed out" issue about every 2-3 days requiring a reset (network is my only access).  After a month of consistent crashes like this, I have stopped leaving IRC connected 24/7, and now it seems to stay running much longer (so far, for the past 10 days without a lockup).

**Comment by popcornmix** [comment]
This may have been fixed with:
https://github.com/raspberrypi/linux/commit/42a864b123a47542aa0db530e0f4fe10851faaf2
Please run rpi-update and test again.

**Comment by dflogeras** [comment]
Thank you! I've been running a kernel with that fix (3.2.27-cutdown-g4b61ead) for the past week or so without issue. I'll keep an eye on it and close in a few weeks.

**Comment by ghollingworth** [comment]
Closing with no update
