### ISSUE TITLE
[4.5] missing bcm2835-i2s commit

### ISSUE THREAD

**Issue by HiassofT** [raspberrypi/linux#1271]
commit c8225021ad8a8e8d2b4560bed644c5552f9f6684 "bcm2835-i2s: get base address for DMA from devicetree" is missing in the 4.5rc tree.

ping @popcornmix  could you please add it?

**Comment by popcornmix** [comment]
Added.

**Comment by HiassofT** [comment]
thanks a lot, i2s seems to be working fine!
