### ISSUE TITLE
Difference between raspberrypi/linux and the officiel linux kernel

### ISSUE THREAD

**Issue by chfakht** [raspberrypi/linux#1274]
Hi,
can somoene tell me the differences between official linux kernel  [ https://github.com/torvalds/linux](url) and linux in raspberry repo  [https://github.com/raspberrypi/linux](url)

Thanks

**Comment by popcornmix** [comment]
This sort of question is best asked in the forum.
Github issues are for bug tracking.

**Comment by chfakht** [comment]
@popcornmix  well i see that github put a label named 'question' so i posted the question :+1:

**Comment by microaaron** [comment]
@chfakht Here is a chinese blog said about how to using offical linux kernel on the raspberrypi:
http://blog.sina.com.cn/s/blog_7cedb56d0102uzyh.html

**Comment by chfakht** [comment]
@microaaron thanks but it explain only one difference in USB
