### ISSUE TITLE
bcm2835 ALSA sound: pop on sound playback start/completion

### ISSUE THREAD

**Issue by P33M** [raspberrypi/linux#128]
Hello

After doing some testing with sound onboard the Rpi, I can characterize (via oscilloscope) the conditions that result in a rather jarring click on start of playback and pop on completion of playback

Running FW 339137
Kernel Linux raspberrypi 3.2.27+ #174 PREEMPT Wed Sep 26 14:09:47 

Sample command:
mpg321blah.mp3
(sound plays)
^C
(_pop_)

The rpi schematic details use of PWM channels for audio carrier generation - having read some other information on improving the rpi's sound quality, I can offer insight on to what happens when the PWM is initiated/released in playback.

On boot and in an "idle" state, the PWM output is 0V (disabled). When playback commences, the voltage measured at C20/C26 pin "2" ramps to +0.56V quite quickly, causing an audible click. This is because the output 10u AC coupling capacitor C34/C48 passes this ramp, which then saturates any input stage in a downstream amp expecting a ~700mV rms AC signal. The effect is variable depending on the input coupling used on the downstream amp.

A similar but more complex effect happens when the audio playback is interrupted or completes. On measuring C20 pin "2" the +0.56V DC biased audio signal has a brief pulse at +1.8V for 6.5ms, then 0V for 16.5ms, then a pulse back to 0.56V for 4ms, then 0V idle state [a fat pair of square pulses]. Similar to the start of playback case, this causes the pop sound on playback.

Maybe the open/close functions in ALSA need to be set so that they preserve PWM at 50% duty cycle on a) driver loading and b) start/finish of playback

**Comment by damiencorpataux** [comment]
Hi. Same here.

Linux raspberrypi 3.1.9+ #90 Wed Apr 18 18:23:05 BST 2012 armv6l GNU/Linux

GPU (useful?):
/opt/vc/bin/vcgencmd version
Apr 18 2012 15:04:46 
Copyright (c) 2012 Broadcom
version 310376 (release)

**Comment by licaon-kter** [comment]
updating to the latest kernel & firmware help?

**Comment by hetsch** [comment]
Hi, same problem..

root@XBian:~# /opt/vc/bin/vcgencmd version
Oct 19 2012 23:40:40 
Copyright (c) 2012 Broadcom
version 345130 (release)

Linux XBian 3.2.27+ #250 PREEMPT Thu Oct 18 19:03:02 BST 2012 armv6l GNU/Linux

If you need more information, I will be happy to deliver that.

**Comment by ghost** [comment]
http://www.raspberrypi.org/phpBB3/viewtopic.php?f=28&t=20689
IMO It seems to be a longstanding VideoCore firmware issue (not alsa related).
Pausing/starting a video in the omxplayer produces the same voltage jumps.

**Comment by tiagocpontesp** [comment]
I'm using MPD to play stuff as a workaround, since it doesn't stop/start pops between tracks.

**Comment by mdxe** [comment]
I haven't tried it yet, but apparently the Arch Linux doesn't have this problem

**Comment by tiagocpontesp** [comment]
Aye, it does! (or did)

**Comment by paintjob** [comment]
Arch definitely still has the problem, as well. I experience it at the start and end of tracks in pianobar when using the 3.5mm audio out port. This is with both the Raspian & Arch distros. Sound over HDMI works without a problem.

**Comment by hetsch** [comment]
Any news on this one?
I really want to help, but still have no idea where to start...

**Comment by cyclooctane** [comment]
I can confirm this issue on both the 256 and 512mb versions of the Raspberry pi using the current Raspbian image.
As paintjob noted, sound over HDMI works without a problem in both cases.

Regards

Note: the current image in this case is 
2012-10-28-wheezy-raspbian

**Comment by JstNnyms** [comment]
same issue here... this is really painfull to endure :(

**Comment by dbader** [comment]
I have the same problem with the 512MB version and analog output. 

As a workaround I use mpd with the PulseAudio output plugin. If you disable PulseAudio's **module-suspend-on-idle** the pops disappear (even when switching songs in mpd) because the audio device is never closed.

**Comment by JstNnyms** [comment]
dbader: could you please give a further explanation how your workaround is ought to be used? im not sure what to do.

should i just comment the line "module-suspend-on-idle" in /etc/pulse/default.pa   out?

edit: just commenting the line out didnt work for me.

**Comment by dbader** [comment]
This gives me playback without crackling in mpd (on the latest Raspbian)
- Install PulseAudio: `sudo apt-get install pulseaudio`
- Configure mpd to use PulseAudio in `/etc/mpd.conf`:

```
audio_output {
  type   "pulse"
  name   "MPD PulseAudio Output"
}
```
- Comment out `load-module module-suspend-on-idle` in `/etc/pulse/default.pa`
- Restart PulseAudio and mpd:

```
sudo /etc/init.d/pulseaudio restart
sudo /etc/init.d/mpd restart
```

**Comment by JstNnyms** [comment]
thank you so far. i just need to figure out how to apply that to raspbmc... :+1:

**Comment by andrzej-bieniek** [comment]
dbader thanks!
It works (I had to reboot the system).

Tested on Pi Revision B (512MB), rasbian:
pi@raspberrypi ~ $ uname -a
Linux raspberrypi 3.2.27+ #250 PREEMPT Thu Oct 18 19:03:02 BST 2012 armv6l GNU/Linux
pi@raspberrypi ~ $ pulseaudio --version
pulseaudio 2.0
pi@raspberrypi ~ $ mpd --version
mpd (MPD: Music Player Daemon) 0.16.7

**Comment by Matthijss** [comment]
It also works for xmms2 with pulseaudio. I also had to reboot the system. Now, it only clicks once during start up.

**Comment by skipper79** [comment]
@dbader; is this also possible for xbian? Can you describe the steps with some more detail? I'm just a beginner ;-) and I really looking forward for a solution for the pop-on-sound.

**Comment by Goofinder** [comment]
I have enabled pulseaudio on my RPi with mpd, however if I pause the mpd output it fails to restart complaining about the device being suspended despite having commented out module-suspend-on-idle.

Can anyone else repeat this problem? (start playing audio using mpd, pause the output, attempt to restart. No output is possible until the RPi is rebooted).

**Comment by acieroid** [comment]
Same problem as Goofinder here, on raspbian, doing mpc play, mpc pause, mpc play. MPD logs contains:

> Dec 22 16:43 : output: "My Pulse Output" [pulse] failed to play: suspended

**Comment by eisenrah** [comment]
Works fine for me, but only for mpd.
I also installed Shairport and changed /etc/libao.conf to "default_driver=pulse", rebooted my Pi, but still no sound from Shairport...
Any thoughts?

**Comment by acieroid** [comment]
Note that launching PulseAudio (which is [not recommended](http://www.freedesktop.org/wiki/Software/PulseAudio/Documentation/User/WhatIsWrongWithSystemWide)) in system mode avoid the problem with suspended input. You can do so by adapting the pulseaudio initscript, and adding the mpd user to the group pulse-access.

**Comment by dbader** [comment]
@JstNnyms @skipper79 I've described the necessary steps in more detail on my blog: https://dbader.org/blog/crackle-free-audio-on-the-raspberry-pi-with-mpd-and-pulseaudio

**Comment by comotion** [comment]
workaround ain't good enough for openelec and friends :-(
is there a known setting in the firmware to fix the pops/clicks?

**Comment by acieroid** [comment]
Also, note that by setting your RPi's volume to the maximum (by default mine is at 40%...), the pops volume is acceptable (compared to the video/audio volume).

**Comment by hetsch** [comment]
Think Mr. Upton knows about the problems with the als driver:
http://permalink.gmane.org/gmane.linux.alsa.devel/104114

**Comment by robgithub** [comment]
uname -a
Linux raspberrypi 3.6.11+ #348 PREEMPT Tue Jan 1 16:33:22 GMT 2013 armv6l GNU/Linux
/opt/vc/bin/vcgencmd version
Jan  2 2013 23:40:34 
Copyright (c) 2012 Broadcom
version 360331 (release)

still pops at the beginning and end of each audio sample (I am using espeak)

**Comment by bob2hh** [comment]
Dear Experts,
As far as I can see, you are very knowledgeable about how the sound system using pulse audio works on the raspbian. 

I have 2 questions:
- How can I avoid such "clicks" when using omxplayer ? They happen at the start and the end of a track when using the analog output (e.g. omxplayer -o local anyfile.mp3).
- I have tried to obtain an output from the 3.5 mm jack local headphone output using mplayer and the pulse audio / alsa mixer. However, I didi not succeed on getting any output at all, always silent. However, on the HDMI output it works fine. I know that in ancient raspbian images the command sudo amixer cset numid=3 1 was supossed to redirect ALSA output to the headphone local jack, but I read somewhere that in the latest raspbian releases this no longer works. Actaully this command refers to the Master Playback Volume control and this only reduces the volume to an unaudible level. Does any of you know how can one redirect the alsa mixer output to the local headphone jack in the latest raspbian releases?

Mine is actually as follows;

pi@raspberrypi ~ $ uname -a
Linux raspberrypi 3.2.27+ #250 PREEMPT Thu Oct 18 19:03:02 BST 2012 armv6l GNU/Linux
pi@raspberrypi ~ $ sudo amixer controls  
numid=4,iface=MIXER,name='Master Playback Switch'
numid=3,iface=MIXER,name='Master Playback Volume'
numid=2,iface=MIXER,name='Capture Switch'
numid=1,iface=MIXER,name='Capture Volume'
pi@raspberrypi ~ $ sudo amixer cset numid=3 1
numid=3,iface=MIXER,name='Master Playback Volume'
  ; type=INTEGER,access=rw------,values=2,min=0,max=65536,step=1
  : values=1,1
(... the only difference when doing this is that the volume is practically unadible, but it is still going to the HDMI output and not to the local headphone oputput).
pi@raspberrypi ~ $ sudo amixer cset numid=3 65536
numid=3,iface=MIXER,name='Master Playback Volume'
  ; type=INTEGER,access=rw------,values=2,min=0,max=65536,step=1
  : values=65536,65536
(... previous command resumes normal volume to the HDMI output).
pi@raspberrypi ~ $ aplay -L
null
    Discard all samples (playback) or generate zero samples (capture)
pulse
    Playback/recording through the PulseAudio sound server
sysdefault:CARD=ALSA
    bcm2835 ALSA, bcm2835 ALSA
    Default Audio Device

Many thanks in advance!

Bob.

**Comment by robgithub** [comment]
uname -a
Linux raspberrypi 3.6.11+ #358 PREEMPT Tue Jan 15 00:45:33 GMT 2013 armv6l GNU/Linux
/opt/vc/bin/vcgencmd version
Jan 15 2013 12:54:01 
Copyright (c) 2012 Broadcom
version 362704 (release)

still pops at the beginning and end of each audio sample (I am using espeak)

**Comment by skechboy** [comment]
Same problem here
Linux raspberrypi 3.6.11-4-ARCH+ #1 PREEMPT Wed Jan 16 19:06:54 UTC 2013 armv6l GNU/Linux

Isn't there any way to disable alsa power saving mode so the sound card is constantly on?

**Comment by licaon-kter** [comment]
**sudo echo "performance" >  /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor** ?

**Comment by robgithub** [comment]
> sudo echo "performance" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor ?

no change, still pops at the beginning and end of each audio sample

**Comment by jamesblackburn** [comment]
Someone's written a blog post about pop-free audio for XBMC using the analog jack:
http://www.oxymoronical.com/blog/2013/01/Pop-free-sound-from-a-Raspberry-Pi-running-XBMC

**Comment by mrbrdo** [comment]
Yeah but that requires pulseaudio, which for example OpenELEC doesn't have by default. And it's a hack anyway, not a real solution.

Seeing this issue is like 4 months old, would be really nice to see a fix soon...

**Comment by jamesblackburn** [comment]
Agreed. The problem has existed since the beginning so just thought I'd post one workaround in case it helps someone...

**Comment by sjmurdoch** [comment]
I've put some more detail in my blog post, along with a work-around suitable for playing back sound with varying sample rate: http://www.lightbluetouchpaper.org/2013/02/10/fixing-poppingclicking-audio-on-raspberry-pi/

**Comment by Dmole** [comment]
The workaround only fixes the stop pop not the start pop.
related: https://github.com/OpenELEC/OpenELEC.tv/issues/923

**Comment by P33M** [comment]
A recent firmware update should have fixed some of these issues - the GPU firmware now doesn't switch off the PWM after the device is released.

**Comment by leucos** [comment]
Awesome. The click is here at first play, but then never happens again.

**Comment by robgithub** [comment]
uname -a
Linux raspberrypi 3.6.11+ #389 PREEMPT Wed Mar 6 12:43:30 GMT 2013 armv6l GNU/Linux
/opt/vc/bin/vcgencmd version
Mar  4 2013 22:02:46 
Copyright (c) 2012 Broadcom
version 374489 (release)

Pop is on first audio use, clear until next reboot, HUGE improvement, Many Thanks!

**Comment by andyhunti** [comment]
I used rpi-update to update to commit c2d133fb4efe9c9995da7fd7e1c45d74254f5c4b
That caused the problem again.
Downgrading with sudo rpi-update 779f0fb6139452a0f1c4be32dab58eb87359517e fixed it.

**Comment by popcornmix** [comment]
@andyhunti 
Are you saying c2d133f has popping or some other issue?
Can you narrow down exactly which commit causes the problem?

**Comment by andyhunti** [comment]
@popcornmix
Well, I'm not entirely sure I'm afraid – the day after rpi-update seemed to work just like @robgithub listed I ran 
sudo apt-get update
and 
sudo apt-get upgrade
Quite a lot of packages were updated and the popping at the start and end of playback using mpg321 and aplay returned.
Rolling back using rpi-update appears to have fixed the issue.
I'm not particularly clear on where the list of packages upgraded is stored, but I assume there's a log with that info in it (I'm pretty new to cmdline Linux). If you can advise I can dig out the detail!

**Comment by popcornmix** [comment]
@andyhunti
apt-get upgrade gets you back onto stable releases. This fix is only on the testing rpi-update tree.

To get back to the testing firmware, run:
sudo rm /boot/.firmware_revision
sudo rpi-update

**Comment by kfrncs** [comment]
I'm still experiencing an extremely intense pop when using the Pi with USB audio (Arturia Audiofuse, which works great otherwise).

**Comment by pelwell** [comment]
That's a separate problem - feel free to create a new issue, explaining your setup and the symptoms.

**Comment by NicoHood** [comment]
I have the same problem. I tried 4 different usb soundcards on all raspberry pi versions 1-3, all have bad sound when the bass is loud. I am using pulseaudio to stream the music to my raspberry. Other linux systems dont have any problem with the usb sound card.

**Comment by Dmole** [comment]
@NicoHood Pwm an usb are separate issues, clipping loud sound is yet a 3rd issue. Start a new issue if you want help.
