### ISSUE TITLE
Renaming file to its own name raises error.

### ISSUE THREAD

**Issue by elliotcubit** [raspberrypi/linux#1283]
Trying to rename a file, and giving it its original name and accepting will raise an error; "could not rename file; file already exists". This is unnecessary.

**Comment by JamesH65** [comment]
How are you trying to do the rename? Using the file manager or command line?

To be honest, whichever you are using, neither are down to the Raspberry Pi foundation to fix - they are standard linux commands (command line) or LXDE functionality (desktop). This github project is for issues with the Linux OS on the Raspberry Pi.

**Comment by Ferroin** [comment]
Add to that, this is standard behavior on every UNIX derived OS in existence, and at a low level, on Windows as well.
