### ISSUE TITLE
gpsd systemd does not start at boot

### ISSUE THREAD

**Issue by msemtd** [raspberrypi/linux#1286]
The gpsd package does not have the right systemd magic to start at boot despite having START_DAEMON="true" in /etc/default/gpsd

NB: I am not using USB hotplugging! Most of the raspbian gpsd workarounds for the startup problems seem to rely on udev rules.

Also the "-G" option is ignored by systemd as the socket access is restricted by /lib/systemd/system/gpsd.socket

**Comment by popcornmix** [comment]
This is a distribution rather than a kernel issue, so this isn't the right place for this.

**Comment by msemtd** [comment]
Whoops, sorry - I think I followed the wrong link - reposted to https://github.com/RPi-Distro/repo
