### ISSUE TITLE
Config request

### ISSUE THREAD

**Issue by pepedog** [raspberrypi/linux#130]
Could you please add
CONFIG_CGROUPS=y
CONFIG_IPV6=m
CONFIG_NET_NS=y
as per https://wiki.archlinux.org/index.php/Systemd#Q:_What_kernel_options_do_I_need_to_enable_in_my_kernel_in_case_I_do_not_use_the_official_Arch_kernel.3F
so kernel image in firmware is more compatable with arch, thanks

**Comment by asb** [comment]
We already have those options enabled in our standard config? Make sure you're looking at the full .config as opposed to the defconfig, which doesn't list those options which are implied by the presence of others.

**Comment by popcornmix** [comment]
```
pi@raspberrypi:~$ zcat /proc/config.gz |grep -w CONFIG_CGROUPS
CONFIG_CGROUPS=y
pi@raspberrypi:~$ zcat /proc/config.gz |grep -w CONFIG_IPV6
CONFIG_IPV6=m
pi@raspberrypi:~$ zcat /proc/config.gz |grep -w CONFIG_NET_NS
CONFIG_NET_NS=y
```

**Comment by pepedog** [comment]
Ah, I assumed defconfig was used, thanks. Without loading deb, is config available somewhere? I try my best

**Comment by asb** [comment]
Either boot a kernel from github.com/raspberrypi/firmware and then read /proc/config.gz or else check out github.com/raspberrypi/linux and make ARCH=arm bcmrpi_defconfig and inspect the generated .config.

**Comment by pepedog** [comment]
Thanks
