### ISSUE TITLE
snd_usb_audio /firmware audio bugg alsa

### ISSUE THREAD

**Issue by t1ger1** [raspberrypi/linux#132]
Audio playback to USB DAC only work fine on 32KHz 44.1Khz, but not on 48KHz.
When playing 48KHz audio there is popping and disordet sound.

If using odd rate setting in asound.conf "rate 1" , playback can work partly if using, ex folowing config

pcm.!default {
       type dmix
       ipc_key 1024
       slave {
           pcm "hw:1"
           rate 1
       }
       bindings {
           0 0
           1 1
       }
}

ctl.dmixer {
   type hw
   card 1
}

same result if playing mp3 from sd card, should not be related to USB transfer bug "ethernet card" 

I do belewe the is the same problem

http://www.raspberrypi.org/phpBB3/viewtopic.php?f=50&t=18810&p=184956&hilit=alsa+modem#p184956

**Comment by t1ger1** [comment]
Hi
I have confirm the firmware bug by using both raspbian and arch 

Linux pi 3.2.27+ #244 PREEMPT Sat Oct 6 17:26:38 BST 2012 armv6l GNU/Linux
Linux pi 3.2.27-10-ARCH+ #1 PREEMPT Fri Oct 5 03:13:45 UTC 2012 armv6l GNU/Linux

Is there any more info to get this assigned

**Comment by t1ger1** [comment]
to clearify, it seams that all usb soundcard has problem with 48KHz, regardlingless config or distro with RPI

**Comment by ghollingworth** [comment]
Audio playback has been significantly improved recently, update and retry (reopen if still evident)

**Comment by ghost** [comment]
The bug still persists in Raspbian (2013-09-25-wheezy; Linux version 3.6.11+). Sound popping occurs every couple of second when playing 192kHz/24bit sound files via asynchronous USB DAC. 44.1kHz/16bit files play just fine. It seems that some people are also trying to fix that but without much success: http://www.raspyfi.com/raspberry-pi-usb-audio-fix/
