### ISSUE TITLE
HDMI audio no longer bit perfect after switch back from using 3.5mm jack

### ISSUE THREAD

**Issue by tghewett** [raspberrypi/linux#1336]
Using the BCM API (ala. hello_audio example), playing a DTS WAV file to the HDMI output from a clean boot results in good decoding (bit perfect), but if the 3.5mm jack is played to at some point and then switch back to using the HDMI output, the DTS audio is no longer decoded successfully - only noise is heard, therefore bit-perfectness is lost.

The problem (at the moment) clears by changing the sample rate to a different value, playing, then changing it back to the right one for the WAV file (then playing again). Other times a reboot has been witnessed as being needed.

Resetting the receiver / amplifier makes no difference, restarting the playback software also makes no difference - the problem seems to be deeper in the firmware and not stateful within the process. The "sample rate changing" workaround even works if the playback software is restarted between each step.

The problem doesn't happen when using the ALSA device interface, even when it has been provoked to happen with the BCM API.

**Comment by popcornmix** [comment]
Might be worth looking at the state of `vcgencmd hdmi_stream_channels`
That is 1 when we are in passthrough mode and 0 when in pcm mode.
PCM mode supports mixing and resampling so may not be bit exact.
A suspect the use of the analogue path is affecting the hdmi_stream_channels state.

**Comment by tghewett** [comment]
The command shows that `hdmi_stream_channels` is always set to 0, so it appears that using the 3.5mm jack output affects the HDMI state, for some reason cleared by changing the sample rate and changing it back again.

I tried forcing passthrough mode:

```
OMX_CONFIG_BOOLEANTYPE passthrough;
memset( &passthrough, 0, sizeof( passthrough ) );
passthrough.nSize = sizeof( OMX_CONFIG_BOOLEANTYPE );
passthrough.nVersion.nVersion = OMX_VERSION;
passthrough.bEnabled = 1;

error = OMX_SetConfig( ILC_GET_HANDLE( st->audio_render ), OMX_IndexConfigBrcmDecoderPassThrough, &passthrough );

if ( error )
    errorLog( "BCM %s: OMX_SetConfig( OMX_IndexConfigBrcmDecoderPassThrough ) failed: %s", __func__, OMXStrError( error ) );
```

but this fails with `BCM bcm_configure: OMX_SetConfig( OMX_IndexConfigBrcmDecoderPassThrough ) failed: OMX_ErrorUnsupportedIndex`

Just as a side issue, which may demand a new issue, I see that 8-channel output on the HDMI is limited to 96kHz when 192kHz is selected, as reported by the receiving amplifier. With the Raspberry Pi 3 clocking more quickly might the over/underflow issues which happened previously no longer exist and is there a way to override the limit to try? I have `no_hdmi_resample=1` set in config.txt but this seems to have no influence (on this matter or the other one above).

**Comment by tghewett** [comment]
> Might be worth looking at the state of vcgencmd hdmi_stream_channels
> That is 1 when we are in passthrough mode and 0 when in pcm mode.

I have tried using omxplayer to play a raw AC3 file (not WAV/SPDIF format) in passthrough mode with `omxplayer -p -o hdmi file.ac3` and the `vcgencmd hdmi_stream_channels` command still shows 0. Is that right when passthrough mode is enabled?

The file played fine.

**Comment by tghewett** [comment]
Further information just noticed: this issue only seems to affect DTS sampled and played at 44.1kHz, 48kHz DTS plays fine. The same is the case for AC3 - 44.1kHz AC3 is played as just noise, 48kHz AC3 is fine.

On this occasion changing the sample rate is not clearing the problem, but rebooting the host did.

**Comment by tghewett** [comment]
I saw a change has been committed so I updated the .dat, .elf and .bin files in /boot to those in the latest raspian download, but the problem is still there.

However I have noticed something else which is likely to be very helpful: when the RP is booted from cold, the problem occurs, but if it is rebooted from warm the problem ceases. Further investigation shows that when booted from cold the RP >>always<< plays the audio at 48kHz no matter what sample rate the audio is sent in as from the audio application, i.e. it always resamples it to 48kHz. This is what my amp's display shows and it explains why 48kHz samples play bit-perfectly but 44.1kHz ones don't. Reboot the RP without a power-off and it always plays at whatever sample rate you set it to, as shown by the amp.

**Comment by tghewett** [comment]
Further information which seems very likely to be related: if cold booting the RP, any audio played over HDMI is always resampled to 48kHz no matter what the sample rate setting, as shown by my amp. If it is then warm booted the sample rate setting is that set by the application. This explains why the problem is cleared by rebooting.

**Comment by tghewett** [comment]
Further information: this problem only seems to affect the Raspberry Pi Zero, other models work fine from a cold boot.

I would quite like to find a workaround for this problem if at all possible, rather than having to warm-reboot the computer. Is there anything that can be done in the software API or config.txt which will get the relevant area into the same state as a warm boot?

**Comment by tghewett** [comment]
This problem seems to have been solved on the latest Raspbian download.
