### ISSUE TITLE
dtoverlay=vc4-kms-v3d with HDMI unplugged causes boot failure

### ISSUE THREAD

**Issue by greyltc** [raspberrypi/linux#1338]
My Pi2 B v1.1 fails to boot when I have `dtoverlay=vc4-kms-v3d` in my config.txt unless an HDMI display is plugged in. This is not solved even when I have the official display connected. This bug seems to be present both in the latest released rasbian and in a kernel I built just now from the `rpi-4.1.y` branch here.

**Comment by popcornmix** [comment]
Can you report this here: https://github.com/anholt/linux/issues
