### ISSUE TITLE
Raspberry Pi 2 B Crash after couple of hours

### ISSUE THREAD

**Issue by ksy5662** [raspberrypi/linux#1346]
Hi.

I have experienced every crash with my Raspberry Pi 2 B model.
3.8A maximum power Samsung 16GB micro SD class 10 memory...

Raspbian Jessi image with apt-get update and apt-get upgrade

Here are two screenshot after crash

anybody give me any suggestion to cope with

![img_20160313_173836](https://cloud.githubusercontent.com/assets/1783034/13727788/f101a86e-e943-11e5-8b02-b7b564215c64.jpg)
![img_20160313_072151](https://cloud.githubusercontent.com/assets/1783034/13727792/fc619bba-e943-11e5-9054-ac4b4382a6f9.jpg)

**Comment by popcornmix** [comment]
Can you run in a higher resolution mode where we might see more of the kernel backtrace?
Do you have any peripherals attached? Do you still get the panic with them removed?
What does `uname -a` and `vcgencmd version` report?
Are you overclocking? If you are try removing that.
Any other non-default config.txt options?
Do you see any flickering of the PWR LED?

**Comment by JosephGarrone** [comment]
We too are having this issue:

![img_0430 1](https://cloud.githubusercontent.com/assets/4310797/14068788/6d9e57b2-f4d1-11e5-8df7-0c55fd9ff983.JPG)

**Comment by ksy5662** [comment]
I got my money back from distributor. They said it is problem^^
2016. 3. 28. 오전 9:43에 "Joseph Garrone" notifications@github.com님이 작성:

**Comment by popcornmix** [comment]
Closing as it sounds like a hardware issue.

**Comment by JosephGarrone** [comment]
We managed to resolve this by turning off device tree in the raspi config. Not sure if that makes it hardware or kernel issue.
