### ISSUE TITLE
Quake 3 demo loop freezes

### ISSUE THREAD

**Issue by zerxy** [raspberrypi/linux#135]
192/64 memory split (start.elf md5 hash `95f3b4d4e11f1fd4f48f82a32d3edc93`) with vcgencmd version 342141 on kernel 3.2.27+ #244 running Quake 3 with the following:

`~/quake3/build/release-linux-arm/ioquake3.arm +exec four.cfg`

The following is the four.cfg file in ~/.q3a/baseq3/four.cfg

`timedemo 1`
`set loop "demo four ; set nextdemo vstr loop"`
`vstr loop`

Quake 3 will freeze after looping demo for about an hour or two.  A SIGINT or Control-C will cause Quake 3 to exit gracefully and it can be restarted successfully without rebooting but it will freeze again eventually.  dmesg logs: `vchiq: 0: prs BULK_TX_DONE@ffd8c588 (11->9) unexpected`

**Comment by zerxy** [comment]
Quake 3 executable from https://dl.dropbox.com/u/3669512/temp/ioquake3.arm

**Comment by popcornmix** [comment]
Yes, known problem. VCHIQ is a bit broken since last the update. It is being worked on.
http://www.raspberrypi.org/phpBB3/viewtopic.php?f=29&t=19334

**Comment by sonictruth** [comment]
After doing rpi-update RetroArch is freezing also. I bet is related to vchiq!

**Comment by zerxy** [comment]
Doing a rpi-update will now revert you to vcgencmd version 339133 and kernel 3.2.27+ #174.  Running the Quake 3 executable from https://dl.dropbox.com/u/3669512/temp/ioquake3.arm now fails and prevents the old executable from working until a reboot.  Old executable I compiled (with OpenAL support) is here: http://speedy.sh/MQRyK/ioquake3.arm.old

**Comment by licaon-kter** [comment]
One needs to recompile q3demo as the libs change, gives an error and exits, so maybe this is a recompile issue?
Anyway I had to find out by my self, Raspbian up to date, I just let it run for 4.5 hours last night ( as per my testing procedure mentioned here: http://www.raspberrypi.org/phpBB3/viewtopic.php?p=183723#p183723 ). Latest kernel/firmware afaik f9506a194a as per **rpi-update**. It run without any issues what so ever for 1.5 hours with only **q3demo** and after that some 3 hours of **q3demo**+**stress**. Also, these runs were with my stable OC of arm850/core450/gpu300/300/300/sdr450/no-overvolt.

**Comment by zerxy** [comment]
192/64 memory split (start.elf md5 hash <code>2033bf2312a19bf12eec1d7460eed188</code>) with vcgencmd version 344164 on kernel 3.2.27+ #247.

Quake 3 appears to lock up the CPU after looping four.cfg (mentioned in first post) for about an hour or two causing the watchdog to reset the system.  Lock up always occurs at the same point just before the demo starts, Quake 3 outputs the following ("x" not literal):

```
x msec to draw all images
Com_TouchMemory: x msec
```

then the CPU locks up.

**Comment by popcornmix** [comment]
@zerxy 
Can you confirm this test worked in previous firmware?

**Comment by zerxy** [comment]
@popcornmix 
It absolutely worked.  I spent over a week fine-tuning my overclocked settings with Quake 3.  I confirmed my final settings by running Quake 3 in tandem with a script that calculates Pi to 10,000,000 digits then computes an MD5 hash of the result to compare to the stored correct hash.  This was done to to check integrity.  Ran for 24 hours+ without problems at my final settings which are within 5 MHz of maximum stable values, CPU 840, GPU 275, RAM 480.

Will test Quake 3 again with current firmware and kernel, this time at stock speeds.  I'm not expecting to see a change...

**Comment by zerxy** [comment]
Quake 3 still running after 18 hours at stock speeds.  So it looks like an excessive overclock was the problem.

**Comment by zerxy** [comment]
Just tried Quake 3 demo loop with my previously working overclocked settings again, 192/64 memory split (start.elf md5 hash <code>daadc5249499a22ec91644f627d6af07</code>) with vcgencmd version 344899 on kernel 3.2.27+ #247.  Same problem as before: ran for a couple of hours perfectly, then CPU lockup at the same point as before, just before the demo starts.  Watchdog then resets system.

My overclocked configuration was definitely working rock solid prior to my opening of this issue.
