### ISSUE TITLE
openmax implementation flaw

### ISSUE THREAD

**Issue by acornblue** [raspberrypi/linux#138]
currently omxplayer is calling a bcm_host_init() when it wants to use the gpu to decode videos.  Should this not be called by openmax api since it is a hardware specific requirement?

**Comment by popcornmix** [comment]
Technically bcm_host_init sets up the vchiq interface to the GPU, so is not openMAX specific.
You need to call it for dispman, or vcgencmd, or openGL, or tvservice etc.

**Comment by acornblue** [comment]
yup. in order for openmax to use the gpu.  as per the rpi wiki, bcm_host_init needs to be called to use the gpu.
