### ISSUE TITLE
fatal error: locking.h: No such file or directory  #include "locking.h" in 3.18kernel

### ISSUE THREAD

**Issue by rbmedisettii09** [raspberrypi/linux#1389]
fs/btrfs/ctree.c:26:21: fatal error: locking.h: No such file or directory
 #include "locking.h"
                     ^
compilation terminated.
make[2]: **\* [fs/btrfs/ctree.o] Error 1
make[1]: **\* [fs/btrfs] Error 2
make: **\* [fs] Error 2
rajendra@rajendra9:~/km/projects/rpi/kernel/linux-rpi-3.18.y$ ^C
rajendra@rajendra9:~/km/projects/rpi/kernel/linux-rpi-3.18.y$ make ARCH=arm clean
  CLEAN   .
  CLEAN   arch/arm/kernel
./scripts/Makefile.clean:17: drivers/media/usb/hdpvr/Makefile: No such file or directory
make[4]: **\* No rule to make target `drivers/media/usb/hdpvr/Makefile'.  Stop.
make[3]: **\* [drivers/media/usb/hdpvr] Error 2
make[2]: **\* [drivers/media/usb] Error 2
make[1]: **\* [drivers/media] Error 2
make: **\* [_clean_drivers] Error 2

**Comment by popcornmix** [comment]
Are you following the instructions here?
https://www.raspberrypi.org/documentation/linux/kernel/building.md

What platform are you building on? How did you get the kernel source?
Do you have a file `fs/btrfs/locking.h`?

Note that 3.18 is no longer supported by us. Updating to 4.1 or 4.4 would be recommended.
