### ISSUE TITLE
lsb_release doesn't report a codename

### ISSUE THREAD

**Issue by pedrocr** [raspberrypi/linux#139]
Here's the result of running lsb_release on an up to date version of raspbian:

$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux testing/unstable
Release:    testing/unstable
Codename:   n/a

As you can see the Codename shows up as n/a. This makes things like unattended-upgrades fail:

$ sudo unattended-upgrade
Traceback (most recent call last):
  File "/usr/bin/unattended-upgrade", line 56, in <module>
    DISTRO_CODENAME = lsb_release.get_distro_information()['CODENAME']
KeyError: 'CODENAME'

**Comment by Ferroin** [comment]
This isn't really a linux problem, it's a problem with the lsb_release package in whatever distro you are using.

**Comment by pedrocr** [comment]
You're right. I came here from:

http://www.raspbian.org/RaspbianBugs

And assumed this was their bugtracker when in fact rereading the page they were just mentioning to check here first. Sorry for the confusion.
