### ISSUE TITLE
IXXAT USB-to-CAN drivers

### ISSUE THREAD

**Issue by arjamizo** [raspberrypi/linux#1392]
Is this possible to run those drivers on my RPi?

http://www.ixxat.com/support/file-and-documents-download/drivers/eci-driver#jump1

**Comment by pelwell** [comment]
This area is for reporting problems with the RPi Linux trees. You should ask this question in the forums on the Raspberry Pi website.

**Comment by arjamizo** [comment]
Thanks. 

btw. it seems https://github.com/linux-can/can-utils is the answer
