### ISSUE TITLE
Ramdisk files for emergency kernel

### ISSUE THREAD

**Issue by Hexxeh** [raspberrypi/linux#14]
Can the FS files for the emergency kernel be made public? They're referred to as ../target_fs in the emergency kernel config, but are nowhere to be found in the repo.

I'm trying to build something that runs entirely out of a ramdisk, and I'm having trouble getting /anything/ running in a ramdisk, so it'd be nice to be able to use the emergency one as a reference.

**Comment by popcornmix** [comment]
https://github.com/raspberrypi/target_fs

**Comment by Hexxeh** [comment]
Excellent, thanks!
