### ISSUE TITLE
Config request: Increase COMMAND_LINE_SIZE

### ISSUE THREAD

**Issue by pezz** [raspberrypi/linux#140]
Hey there,

Given the amount of args prepended to the kernel command line before adding cmdline.txt, and given the amount of stuff required in cmdline.txt by default, I've found myself hitting the 512 character limit for the kernel command line.

This can result in an unbootable system due to crucial options being truncated.

Could COMMAND_LINE_SIZE in include/asm-generic/setup.h please be set to something bigger than 512?

Cheers.

**Comment by Ferroin** [comment]
I would think that it shouldn't be a problem to do so, the 512 character limit is mostly intended to save space on systems with very small amounts of memory.  The full amount of space stays allocated permanently, and only gets released on a reboot or kexec.

**Comment by popcornmix** [comment]
I believe we are using:
#define COMMAND_LINE_SIZE 1024
from
arch/arm/include/asm/setup.h

However the (start.elf) firmware does have a limit of 500. I'll increase that.

**Comment by popcornmix** [comment]
Latest firmware should support 1024 characters.
