### ISSUE TITLE
integrate improved SPI with less latencies by using RealTime threads (backport from 3.6)

### ISSUE THREAD

**Issue by msperl** [raspberrypi/linux#141]
Hi!

There is a patched version of SPI driver that shows much improved thruput.

Please see: http://www.raspberrypi.org/phpBB3/viewtopic.php?f=44&t=19489 for the patch.

It includes:
- backport of the SPI interface (generic worker queues) from 3.6
- 3 modes of operation:
  *\* polling
  *\* interrupt driven
  *\* DMA driven (if the rx_dma and tx_dma fields are filled in, otherwise fallback to interrupt driven))

This allows the RPI with a MCP2515 CAN-bus-chip attached to handle 500kbit CAN bus traffic to get handled without packet-loss. the original driver shows major "gaps" by sometimes sleeping 4ms (during which time 13 messages arrive and stay unprocessed). Only at 100KBit/s CAN bus speed there was no longer any packet loss!

Thanks, Martin

**Comment by popcornmix** [comment]
We do have a 3.6.1 kernel port:
https://github.com/raspberrypi/linux/tree/rpi-3.6.y
Does that simplify the patch?

**Comment by msperl** [comment]
yes - just use the driver/spi/spi-bcm2708.c part of the patch.

For DMA also the section in arch/arm/mach-bcm2708/bcm2708.c:
@@ -584,24 +590,50 @@ static struct platform_device bcm2708_spi_device = {
        .id = 0,
        .num_resources = ARRAY_SIZE(bcm2708_spi_resources),
        .resource = bcm2708_spi_resources,
-       .dev = {
-               .coherent_dma_mask = DMA_BIT_MASK(DMA_MASK_BITS_COMMON),
-       },
  };

otherwise coherent memory allocation for DMA will not work...

I will try to make a patch to the 3.6.y branch

**Comment by msperl** [comment]
The patch relative to 3.6.y has been added to the thread mentioned above (there is no means to attach a patch here)

**Comment by licaon-kter** [comment]
fork this repo, apply patch, check it first, add a "Pull request"

**Comment by msperl** [comment]
I am still new to git, so give me a bit of time to do that ;)

**Comment by licaon-kter** [comment]
gogogo: https://help.github.com/articles/fork-a-repo ;)

**Comment by msperl** [comment]
See 147 for the patch to get applied to 3.6.y
