### ISSUE TITLE
RPI-kernel branch 3.6.y not rebooting

### ISSUE THREAD

**Issue by msperl** [raspberrypi/linux#142]
Hi!

After switching from git 3.2.27 to git 3.6.y (commit 3bc2651e30d39a37432cf932f29834b307c466c2)
the RPI stays stuck when doing a "typical" /sbin/reboot.

Only thing visible on the serial Console is:
[    7.068853] ftdi_sio: v1.6.0:USB FTDI Serial Converters Driver
[    9.179254] EXT4-fs (mmcblk0p2): re-mounted. Opts: (null)
Debian GNU/Linux wheezy/sid raspberrypi ttyAMA0

raspberrypi login: [   50.542724] Restarting system.

This makes the system essentially unsafe to use - especially when not sitting in front of the RPI, but working remotely...

No jump to kernel debugger or anything that would typically indicate a crash on the kernel level.
Seems to happen in the videocore part, where something is not initialized as expected.
After power off/on it the machine boots correctly - no filesystem check or similar, so the filesystem is shut down correctly.

Ciao,
         Martin

p.s: the .config was copied from the running (and rebooting) git-version of 3.2.7 and the defaults applied for all new config-values

**Comment by popcornmix** [comment]
Do the network LEDs stop flashing?

**Comment by msperl** [comment]
Link flashes all others are "on" - except ACT.

**Comment by popcornmix** [comment]
That does mean linux didn't get to the shutdown function (bcm2708_power_off) which resets the chip (and so the LAN chip). So it's not a firmware problem.

I imagine it means a linux task is hung when trying to shut down.

**Comment by msperl** [comment]
Maybe a hint:
booting with /boot/arm240_start.elf (md5sum b77e7028caa3d733985b0baf6510e144)
taken from git version: 17ff0bb5bb46210bad235d32589d35f951f269cf

**Comment by popcornmix** [comment]
Does "sudo reboot -f" reboot? (save your work and sync first)

**Comment by msperl** [comment]
no - same effect...

Running a RPI  with HW revision 4 (256MB)

**Comment by msperl** [comment]
power down works correctly - leds all off after shutdown -h now

**Comment by Ferroin** [comment]
Do you have your system setup to use kexec to reboot?  I've seen intermittent problems with kexec() operation not only on the rpi, but on other ARM systems as well.

**Comment by msperl** [comment]
no - just the default config that came with the original kernel from raspbian.
used that successfully with 3.2.27 for some time and now when moving/testing to 3.6.y I am experience the issue

I also tried to remove everything attached (USB, GPIO,...) - no changes with only power+network connected.

**Comment by popcornmix** [comment]
I see the problem. 3.2.27 does: (arch/arm/kernel/process.c)
void (*arm_pm_restart)(char str, const char *cmd) = arm_machine_restart;

and 3.6.1 does:
void (*arm_pm_restart)(char str, const char *cmd) = null_restart;

Seems there's a new restart method of the machine type. I'll look into it.

**Comment by msperl** [comment]
I tried to build with the default config from arch/arm/configs/bcmrpi_defconfig
and wanted to test the reboot tomorrow when RPI has finished compiling...

Steps:
make clean
cp arch/arm/configs/bcmrpi_defconfig .config
make silentoldconfig (just pressing enter until finished - taking the defaults for unknown configs)
make

but make stops almost immediately:
root@raspberrypi:/usr/src/linux.3.6.y# make
/bin/sh: 1:  gcc: not found
  CHK     include/linux/version.h
  CHK     include/generated/utsrelease.h
  UPD     include/generated/utsrelease.h
make[1]: `include/generated/mach-types.h' is up to date.
  CC      kernel/bounds.s
/bin/sh: 1:  gcc: not found
make[1]: **\* [kernel/bounds.s] Error 127
make: **\* [prepare0] Error 2

moving back to the config used before 
cp .config.backup .config; make silentoldconfig;make
works again...

So maybe the "bcmrpi_defconfig" are no longer valid when compiling the kernel (at least when compiling on the RPI) - 
this may also need a review/replacement...

**Comment by popcornmix** [comment]
Fix pushed for reboot.

**Comment by Ferroin** [comment]
The compilation error probably isn't something in the config, but either something in the Makefile or how your system is configured.

**Comment by popcornmix** [comment]
`/bin/sh: 1: gcc: not found`
sound like you don't have gcc installed.

**Comment by licaon-kter** [comment]
@msperl: it easier to export the running config of a working kernel: **zcat /proc/config.gz > ~/config.default** and work your way from that one

**Comment by msperl** [comment]
well, as said: if I do the following:

zcat /proc/config.gzip .config; make

it compiles, but if I:

cp arch/arm/configs/bcmrpi_defconfig .config;make

it does NOT work and complains about gcc.

and that in the SAME shell without adding/removing anything else (especially not removing gcc from the system...)

**Comment by msperl** [comment]
I have just seen the new patch - compiling the kernel right now to see if it works now.
I will let you know if it works...

**Comment by msperl** [comment]
@licaon-kter: I know it is better (especially since /proc/config.gz), but I was assuming that the reboot issue may be related to a kernel configuration issue. So I wanted to test with a "stock" config, that should be working - hence the use of arch/arm/configs/bcmrpi_defconfig (which I was hoping to be working). But then I stumbled across the issue of "missing compiler" (even though the other config compiles). But I believe we should branch this to a different "issue"...

**Comment by msperl** [comment]
Reboots now correctly - thanks!
