### ISSUE TITLE
Community 64bit Kernel; Official Branch needed

### ISSUE THREAD

**Issue by IComplainInComments** [raspberrypi/linux#1424]
With the firmware now having support for a 64bit kernel boot, I think the community needs an official place to take care of working on a 64bit kernel for the Raspberry Pi, as their are A LOT of kernels with different patches being made.

I think if we have one place for an official kernel this will allow the community to make a proper kernel for everyone to have access to, and allow non-programmer access to a 64bit kernel if desired.

Now I understand that the Foundation doesn't really want to focus on a kernel, and that is their decision, but I do think their needs to be a place where the community can work on an official 64bit rpi kernel that is at least in the view of the Foundation.

**Comment by P33M** [comment]
Supplying an ARMv8 kernel is not currently a priority for Raspberry Pi. Supporting third-party kernels, however, is largely implemented in recent firmware. The upstream effort for ARMv8 on Pi3 is well underway: https://www.raspberrypi.org/forums/viewtopic.php?f=72&t=137963

The centralised location for the "official" ARMv8 kernel is the Linux kernel mailing lists.

As time goes on, we're shedding downstream-only code and slowly narrowing the gap between our repository and upstream.
