### ISSUE TITLE
Keyboad event random drop after plugin in a wireless mouse

### ISSUE THREAD

**Issue by ghost** [raspberrypi/linux#143]
_update Di 6. Nov 14:56:42 CET 2012_

This makes an USB keyboard almost unusable. E.g. a missing a key-up event causes an endless rrrrrrrrrepeating of the key.

Tested with several keyboards and rPIs (vB2.0/Sony), Vcc (TP1/2) is exact 5.0V.

vcgencmd version
Oct 31 2012 17:57:31 
Copyright (c) 2012 Broadcom
version 347415 (release)

uname -a
Linux raspberrypi 3.2.27+ #257 PREEMPT Mon Nov 5 00:01:55 GMT 2012 armv6l GNU/Linux

dmesg shows for a keyboard (~ 10x/min):
[11022.474455] usb 1-1.3.4: reset low-speed USB device number 11 using dwc_otg
[11029.513811] usb 1-1.3.4: reset low-speed USB device number 11 using dwc_otg
[11064.970674] usb 1-1.3.4: reset low-speed USB device number 11 using dwc_otg
...

After disconnecting the mouse dongle,
Nov  6 14:22:50 raspberrypi kernel: [14931.073728] usb 1-1.3.1: USB disconnect, device number 12
Nov  6 14:22:50 raspberrypi kernel: [14931.263161] usb 1-1.3.4: reset low-speed USB device number 11 using dwc_otg

the keybord starts working again as expected (without other kernel message).
The same hardware works flawlessly on an Ubuntu/Fedora Linux machine.

```
lsusb -vs 009

Bus 001 Device 009: ID 046d:c526 Logitech, Inc. Nano Receiver
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 (Defined at Interface level)
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        32
  idVendor           0x046d Logitech, Inc.
  idProduct          0xc526 Nano Receiver
  bcdDevice            5.00
  iManufacturer           1 Logitech
  iProduct                2 USB Receiver
  iSerial                 0 
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength           59
    bNumInterfaces          2
    bConfigurationValue     1
    iConfiguration          4 RQR05.00_B0023
    bmAttributes         0xa0
      (Bus Powered)
      Remote Wakeup
    MaxPower               98mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      1 Boot Interface Subclass
      bInterfaceProtocol      2 Mouse
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      67
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               1
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        1
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 No Subclass
      bInterfaceProtocol      0 None
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.11
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      79
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0014  1x 20 bytes
        bInterval               1
Device Status:     0x0000
  (Bus Powered)
```

**Comment by doc** [comment]
Seing very similar behaviour with an apple usb keyboard. I've read lots of speculation that its a power problem but the same keyboard works perfectly in the same rpi under arch linux.

**Comment by popcornmix** [comment]
@doc 
what does "uname -a" return on raspbian and arch?

**Comment by doc** [comment]
on arch it returns:
Linux alarmpi 3.2.27-5-ARCH+ #1 PREEMPT Fri Sep 14 13:23:44 UTC 2012 armv6l GNU/Linux

and on raspbian we have:
Linux raspberrypi 3.1.9+ #168 PREEMPT Sat Jul 14 18:56:31 BST 2012 armv6l GNU/Linux

**Comment by ghollingworth** [comment]
Yeah,

Looks like you have a very old Raspbian build without any of the fixes

Gordon

On 08/12/2012, Mark notifications@github.com wrote:

> on arch it returns:
> Linux alarmpi 3.2.27-5-ARCH+ #1 PREEMPT Fri Sep 14 13:23:44 UTC 2012 armv6l
> GNU/Linux
> 
> and on raspbian we have:
> Linux raspberrypi 3.1.9+ #168 PREEMPT Sat Jul 14 18:56:31 BST 2012 armv6l
> GNU/Linux
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/raspberrypi/linux/issues/143#issuecomment-11160875

## 

Sent from my mobile device

**Comment by doc** [comment]
Thanks, updated raspbian to the latest and its now working fine .. thanks!
