### ISSUE TITLE
branch 3.6.y: VCHIQka blocked for more than 120 seconds 

### ISSUE THREAD

**Issue by msperl** [raspberrypi/linux#144]
The issue that has been resolved in the 3.2.27 branch shows still up with the 3.6.y branch:

[ 1201.159939] INFO: task VCHIQka-0:28 blocked for more than 120 seconds.
[ 1201.159960] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[ 1201.159972] VCHIQka-0       D c03939b4     0    28      2 0x00000000
[ 1201.160058] [<c03939b4>](__schedule+0x310/0x610) from [<c003a7b0>](kthread+0x68/0x90)
[ 1201.160101] [<c003a7b0>](kthread+0x68/0x90) from [<c000e99c>](kernel_thread_exit+0x0/0x8)
[ 1321.149865] INFO: task VCHIQka-0:28 blocked for more than 120 seconds.
[ 1321.149887] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[ 1321.149899] VCHIQka-0       D c03939b4     0    28      2 0x00000000
[ 1321.149988] [<c03939b4>](__schedule+0x310/0x610) from [<c003a7b0>](kthread+0x68/0x90)
[ 1321.150030] [<c003a7b0>](kthread+0x68/0x90) from [<c000e99c>](kernel_thread_exit+0x0/0x8)

Thanks,
            Martin

**Comment by popcornmix** [comment]
Yes, new vchiq is not working reliably, and 3.6.y uses new vchiq.
You can switch to driver/misc/vco4_services from 3.2.27 and that should avoid the problem.

**Comment by msperl** [comment]
As I run headless (I think my RPI has been introduced to a HDMI cable once...) - do I need it at all? 
Can I disable it without any issues?

**Comment by popcornmix** [comment]
Yes, vchiq is needed for GPU accelerated features. If you are not using 3D/Video it should be fine to disable vchiq.
