### ISSUE TITLE
How does kernel 4.4 get entropy from /dev/hwrng ?

### ISSUE THREAD

**Issue by Mausy5043** [raspberrypi/linux#1453]
After upgrading from 3.18 to 4.4 I noticed that  `/dev/hwrng` exists but the module that I used to need to load in the past (bcm2708-rng) is not found. So, I'm guessing that this functionality is now compiled into the kernel and nolonger supplied as a module.

The question that I have is: does the kernel also use `/dev/hwrng` as a source of entropy or do I still need to use `/usr/sbin/rngd`  (provided by the package `rng-tools`) to feed the HWRNG source to the kernel?

**Comment by popcornmix** [comment]
Probably best to ask these questions on the forum.
Yes, the hw rng module is now built in.
Yes, some scheme for moving data from /dev/hwrng to /dev/random is required (like rng-tools).

**Comment by Mausy5043** [comment]
forum?

**Comment by popcornmix** [comment]
This github is for reporting kernel bugs.
The forum is best for "how to" discussions:
https://www.raspberrypi.org/forums
