### ISSUE TITLE
CONFIG_DRM_LOAD_EDID_FIRMWARE is disabled in the default config

### ISSUE THREAD

**Issue by tdaede** [raspberrypi/linux#1456]
Enabling this allows custom EDID loading for the vc4 driver, for feature parity with the firmware's mode forcing.

**Comment by popcornmix** [comment]
Have you tested this works?

**Comment by tdaede** [comment]
I have tested that it will successfully load and parse EDID files in /usr/lib/firmware. Unfortunately the resulting timings are broken - however that's an unrelated issue, because looking at the code the same issue would happen if these EDIDs were in a "real" monitor.

**Comment by popcornmix** [comment]
Ok, will add.

**Comment by popcornmix** [comment]
This is in latest rpi-update firmware. Okay to close?

**Comment by tdaede** [comment]
Yes, I pulled the latest rpi-update and see it there. Thanks!
