### ISSUE TITLE
[feature request] enable FB_TFT_ST7789V as a module in kernel config

### ISSUE THREAD

**Issue by matikij** [raspberrypi/linux#1474]
4.4 mainline kernel has merged a driver for my C-Berry28 TFT display, unfortunately it's disabled in the raspberrypi kernel. Is there any specific reason why it's not enabled except for being new?

**Comment by JamesH65** [comment]
Ping @popcornmix 

It is in the 4.9 source tree but not enabled.

**Comment by popcornmix** [comment]
Added: https://github.com/raspberrypi/linux/commit/2c2c783abeb6564b279aa4b3b7fed6b540d66132
Will be in next rpi-update kernel.

**Comment by popcornmix** [comment]
Should be in latest rpi-update kernel. Please test and close if happy.

**Comment by JamesH65** [comment]
Confirmed this is in 4.14.y as a module, so closing this.
