### ISSUE TITLE
7" touch screen with drm (vc4)

### ISSUE THREAD

**Issue by chbae** [raspberrypi/linux#1478]
Environment:
- meta-raspberrypi master branch
- kernel 4.4.y

I can use "1920x1080" touch monitor with vc drm and drm is initialized successfully.

However, When I use 7" touch screen (official raspberrypi monitor 800x480), I didn't get the "drm initialized" message in dmesg and I got the below errors.

Do you have any idea?

`
[   11.314518] [drm] No driver support for vblank timestamp query.
[   11.327805] vc4-drm soc:gpu@7e4c0000: No connectors reported connected with modes
[   11.327835] [drm] Cannot find any crtc or sizes - going 1024x768
[   11.445197] vc4-drm soc:gpu@7e4c0000: fb0:  frame buffer device
`

**Comment by chbae** [comment]
@anholt 
I thought that current official kernel (4.4) for raspberrypi doesn't support DSI right?
if yes, when do you expect to merge drm-vc4-dsi branch into rpi-4.4.y or rpi-4.4.y branch?

Thanks

**Comment by popcornmix** [comment]
No DSI/DPI display support in the raspberrypi kernel with vc4-kms-drm overlay enabled. 
We'll get updates from @anhol when they are stable.
For now bug reports or feature requests are best reported here:
https://github.com/anholt/linux/issues

**Comment by chbae** [comment]
@popcornmix Ok. Thanks.

**Comment by tom--pollard** [comment]
Hi, do we know if this support was merged yet to 4.4.y ?

**Comment by popcornmix** [comment]
Keep an eye on https://github.com/raspberrypi/linux/pull/1556
