### ISSUE TITLE
ip6t_rpfilter missing in Raspbian (armhf)

### ISSUE THREAD

**Issue by maddes-b** [raspberrypi/linux#1483]
The kernel module ip6t_rpfilter is missing in Raspbian (Jessie 2016-03-18 with latest updates), therefore reverse path filtering cannot be done for IPv6.
Please consider adding it to Raspbian as it is standard in Debian [1].

[1] https://packages.debian.org/search?searchon=contents&keywords=ip6t_rpfilter.ko&mode=exactfilename&suite=stable&arch=any

**Comment by popcornmix** [comment]
Okay.

**Comment by popcornmix** [comment]
ip6t_rpfilter.ko should be present in latest rpi-update firmware.

**Comment by maddes-b** [comment]
Thanks a lot. Got it via `rpi-update` with kernel 4.4.11-v7+.
