### ISSUE TITLE
new stuttering on IQAudio Dac

### ISSUE THREAD

**Issue by rbnpi** [raspberrypi/linux#1497]
Since upgrading to the latest Raspbian 2016-05-10 I have noticed a stuttering on the audio output of my IQAudio DacPlus. I use this with Sonic Pi 2.10 On previous versions of Raspbian it is fine. I gather that the same effect has been noted on the HiFiBerry card as well.

Sam Aaaron (developer of Sonic Pi) also tells me that he has noticed the effect as well. The card plays .wav files OK directly with aplay, so the problem may be connected to the jackd connection that Sonic Pi uses.

**Comment by multivac61** [comment]
Can confirm that I have silmilar issues with specific audio output from my HiFiBerry card after upgrading to the lastest Raspbian. I get crystal clear audio when running `aplay` but when I run `jackd` commands and play audio that way the issue becomes apparent.

**Comment by stuzog** [comment]
Same issue with Sonic Pi on a RPi2 with a HiFiBerry DAC+. Sonic Pi uses 'jackd' but a `qjackctrl` window shows Jack not running and many instances of "skipped 13" and "skipped 14" in the log window (the distorted sound and clicking). It also shows system audio connected, but not Sonic Pi. The green light on the DAC+ comes on, however, so it is running.

Comments on [this Google group](https://groups.google.com/forum/#!msg/sonic-pi/BvkSTW0Cqnk/nRtzYn4aAwAJ) suggest that it's a Linux problem.

**Comment by clivem** [comment]
The long and the short of it, from reading that link......

MMAP is now disabled by default with brcm2835 I2S driver. You need to re-enable it with an overlay, "dtoverlay=i2s-mmap".

My memory is hazy. I remember at one time, MMAP was enabled by default. Then it got disabled with a patch and the overlay was the way to re-enable it. Can't remember why.

**Comment by stuzog** [comment]
`dtoverly=i2s-mmap` was already enabled to get Sonic Pi running.

**Comment by rbnpi** [comment]
That’s not the problem it is enabled with that line in the config.txt file.

**Comment by clivem** [comment]
Sorry, not really clear to me what is going on. That Google thread starts with "jack doesn't work without MMAP" and then halfway through it now seems to be about "ticks" in the audio stream.

**Comment by rbnpi** [comment]
Yes. initially mmap was the problem. This was then sorted (a long time ago) and things have been fine until the latest release, when a clicking sound has been introduced using HiFiBerry or IQAudio cards. They work fine with aplay. The problem is in the jack connection necessary for Sonic Pi

**Comment by stuzog** [comment]
STUTTERING AUDIO SOLVED -- Updating both distribution (apt-get dist-update) and kernel (using rpi-update) results in clean audio, no stuttering on RPi2 with HiFiBerry DAC+. Thanks to Martin Sperl for this, info via Clive Messer.

Stuart

**Comment by popcornmix** [comment]
@rbnpi Please run rpi-update and close if issue is resolved.

**Comment by rbnpi** [comment]
Thanks guys for all your hard work. Works perfectly now :-)
Closed.
