### ISSUE TITLE
snd_usb errors "delay: estimated 0, actual"

### ISSUE THREAD

**Issue by mrzk-pl** [raspberrypi/linux#150]
My Card: SB X-Fi 5.1, 
ID 041e:30df Creative Technology, Ltd

Sound works, but in dmesg i have many errors:
[  115.264605] delay: estimated 0, actual 191
[  115.272597] delay: estimated 0, actual 191
[  115.280601] delay: estimated 0, actual 192

and sometimes after few minutes:
usb_set_interface failed (-71)
and I need reboot pi to use card again

I've tried many 3.2.\* kernels, and 3.6.x. On 3.6.x there is a fix for this issue:
## Signed-off-by: Takashi Iwai tiwai@xxxxxxx

sound/usb/pcm.c | 6 ++++++
1 file changed, 6 insertions(+)

diff --git a/sound/usb/pcm.c b/sound/usb/pcm.c
index fd5e982..f782ce1 100644
--- a/sound/usb/pcm.c
+++ b/sound/usb/pcm.c
@@ -1140,6 +1140,12 @@ static void retire_playback_urb(struct snd_usb_substream *subs,
int processed = urb->transfer_buffer_length / stride;
int est_delay;
- /\* ignore the delay accounting when procssed=0 is given, i.e.
- \* silent payloads are procssed before handling the actual data
- */
- if (!processed)
- return;
  +
  spin_lock_irqsave(&subs->lock, flags);
  est_delay = snd_usb_pcm_delay(subs, runtime->rate);
  /\* update delay with exact number of samples played */

But this patch not solve problem on Raspberry
Card works fine (without errors) when USB1 speed is set (dwc_otg.speed=1)

**Comment by ghollingworth** [comment]
Can you test this again with the latest kernel with rpi-update? (Reopen if still found)
