### ISSUE TITLE
VC4: different colors with kernel 4.4.11

### ISSUE THREAD

**Issue by anyc** [raspberrypi/linux#1503]
After the upgrade to (a self-built) 4.4.11, I noticed that the colors on my HDMI TV look brighter and light colors become white. I guess this has something to do with the VC4 update and "drm/vc4: Add support for gamma ramps". Hence, I wanted to ask if this is intended? I will check if I can change these values somehow as I don't run a DE but just a fullscreen slideshow.

**Comment by anyc** [comment]
Okay, although xrandr shows me that the brightness is set to 1, setting it again to 1 seems to fix the colors. I noticed though that the gamma also gets changed from 0.46:0.46:0.46 to 1:1:1 although I only set the brightness.

**Comment by popcornmix** [comment]
Are you using the experimental graphics driver?

**Comment by anyc** [comment]
Yes, I enabled the overlay and the VC4 module gets loaded. I use Xorg and qmlscene to show a QML-based slideshow (that is not released yet). Everything else looks good. No errors in the kernel log.

**Comment by popcornmix** [comment]
Can you report it here:
https://github.com/anholt/linux/issues
We don't directly support the experimental graphics driver, so I don't know if the behaviour is expected.
Eric Anholt who develops it will know.
