### ISSUE TITLE
FIQ interrupt not triggering IRQ interrupt causing USB to dropout

### ISSUE THREAD

**Issue by gholling** [raspberrypi/linux#151]
This is the ethernet drop out many people are seeing when running their boxes for extended periods...

To test this wait until it drops out and then do:

<pre>
sudo -s
echo 08 > /sys/devices/platform/bcm2708_usb/regoffset
cat /sys/devices/platform/bcm2708_usb/regvalue
</pre>

I expect the value to be 0x00000031

If the value is 0x00000030 then do this:

<pre>
echo 0x31 > /sys/devices/platform/bcm2708_usb/regvalue
</pre>

If this fixes the ethernet it will be very useful to know...

**Comment by tgghtp** [comment]
it fixes,

a test script found elsewhere, modified, running every minute from cron:

<pre>
#--------------------------------------------------
#!/bin/sh
# cron script for checking wlan connectivity
IP_FOR_TEST="a.b.c.d"
PING_COUNT=1
PING="/bin/ping"
INTERFACE="eth0"
FFLAG="/opt/check_lan/stuck.fflg"
# ping test
$PING -c $PING_COUNT $IP_FOR_TEST > /dev/null 2> /dev/null
if [ $? -ge 1 ]
then
    logger "check_lan: $INTERFACE is down"
touch $FFLAG
date >> $FFLAG
echo 08 > /sys/devices/platform/bcm2708_usb/regoffset
cat /sys/devices/platform/bcm2708_usb/regvalue >> $FFLAG
echo 0x31 > /sys/devices/platform/bcm2708_usb/regvalue
cat /sys/devices/platform/bcm2708_usb/regvalue >> $FFLAG
else
    logger "check_lan: $INTERFACE is up"
#    rm -f $FFLAG 2>/dev/null
fi
#---------------------------------------------------------------
</pre>

the resulting file:

<pre>
root@raspberrypi:~# cat /opt/check_lan/stuck.fflg
Mo 5. Nov 06:58:11 CET 2012
Reg@0x000008 = 0x00000030
Reg@0x000008 = 0x00000031
Mo 5. Nov 08:42:01 CET 2012
Reg@0x000008 = 0x00000030
Reg@0x000008 = 0x00000031
Mo 5. Nov 09:21:11 CET 2012
Reg@0x000008 = 0x00000030
Reg@0x000008 = 0x00000031
Mo 5. Nov 09:57:11 CET 2012
Reg@0x000008 = 0x00000030
Reg@0x000008 = 0x00000031
Mo 5. Nov 10:24:11 CET 2012
Reg@0x000008 = 0x00000030
Reg@0x000008 = 0x00000031
Mo 5. Nov 11:35:04 CET 2012
Reg@0x000008 = 0x00000030
Reg@0x000008 = 0x00000031
</pre>

parts from syslog:

<pre>
Nov  5 11:34:01 raspberrypi logger: check_lan: eth0 is up
Nov  5 11:34:10 ..................
Nov  5 11:34:20 raspberrypi kernel: [75050.559308] smsc95xx 1-1.1:1.0: eth0: Failed to read register index 0x00000114
Nov  5 11:34:25 raspberrypi kernel: [75055.559353] smsc95xx 1-1.1:1.0: eth0: Failed to write register index 0x00000114
Nov  5 11:34:30 raspberrypi kernel: [75060.559384] smsc95xx 1-1.1:1.0: eth0: Failed to read register index 0x00000114
Nov  5 11:34:35 raspberrypi kernel: [75065.559438] smsc95xx 1-1.1:1.0: eth0: Failed to read register index 0x00000118
Nov  5 11:34:40 raspberrypi kernel: [75070.559486] smsc95xx 1-1.1:1.0: eth0: Failed to read register index 0x00000114
Nov  5 11:34:45 raspberrypi kernel: [75075.559530] smsc95xx 1-1.1:1.0: eth0: Failed to write register index 0x00000114
Nov  5 11:34:50 raspberrypi kernel: [75080.559585] smsc95xx 1-1.1:1.0: eth0: Failed to read register index 0x00000114
Nov  5 11:34:55 raspberrypi kernel: [75085.559620] smsc95xx 1-1.1:1.0: eth0: Failed to read register index 0x00000118
Nov  5 11:35:01 raspberrypi kernel: [75091.659677] smsc95xx 1-1.1:1.0: eth0: Failed to read register index 0x00000114
Nov  5 11:35:04 raspberrypi logger: check_lan: eth0 is down
Nov  5 11:35:04 ............................
Nov  5 11:35:05 ............................
Nov  5 11:35:11 ............................
Nov  5 11:36:01 raspberrypi logger: check_lan: eth0 is up
Nov  5 11:34:01 raspberrypi logger: check_lan: eth0 is up
Nov  5 11:34:10 ..................
Nov  5 11:34:20 raspberrypi kernel: [75050.559308] smsc95xx 1-1.1:1.0: eth0: Failed to read register index 0x00000114
Nov  5 11:34:25 raspberrypi kernel: [75055.559353] smsc95xx 1-1.1:1.0: eth0: Failed to write register index 0x00000114
Nov  5 11:34:30 raspberrypi kernel: [75060.559384] smsc95xx 1-1.1:1.0: eth0: Failed to read register index 0x00000114
Nov  5 11:34:35 raspberrypi kernel: [75065.559438] smsc95xx 1-1.1:1.0: eth0: Failed to read register index 0x00000118
Nov  5 11:34:40 raspberrypi kernel: [75070.559486] smsc95xx 1-1.1:1.0: eth0: Failed to read register index 0x00000114
Nov  5 11:34:45 raspberrypi kernel: [75075.559530] smsc95xx 1-1.1:1.0: eth0: Failed to write register index 0x00000114
Nov  5 11:34:50 raspberrypi kernel: [75080.559585] smsc95xx 1-1.1:1.0: eth0: Failed to read register index 0x00000114
Nov  5 11:34:55 raspberrypi kernel: [75085.559620] smsc95xx 1-1.1:1.0: eth0: Failed to read register index 0x00000118
Nov  5 11:35:01 raspberrypi kernel: [75091.659677] smsc95xx 1-1.1:1.0: eth0: Failed to read register index 0x00000114
Nov  5 11:35:04 raspberrypi logger: check_lan: eth0 is down
Nov  5 11:35:04 ........................
Nov  5 11:36:01 raspberrypi logger: check_lan: eth0 is up
</pre>

hope this helps

**Comment by ghollingworth** [comment]
Can you now update and check again?

I believe this is now fixed, can you run a long term test and make sure the
problem has gone away?

**Comment by tgghtp** [comment]
Update: from where ?

<pre>
root@raspberrypi:~# cat /etc/issue
Debian GNU/Linux wheezy/sid \n \l
root@raspberrypi:~# uname -a
Linux raspberrypi 3.2.27+ #250 PREEMPT Thu Oct 18 19:03:02 BST 2012 armv6l GNU/Linux
root@raspberrypi:~# apt-get update
Holen: 1 http://mirrordirector.raspbian.org wheezy InRelease [12,5 kB]
OK   http://archive.raspberrypi.org wheezy InRelease
OK   http://archive.raspberrypi.org wheezy/main armhf Packages
Holen: 2 http://mirrordirector.raspbian.org wheezy/main armhf Packages [7.377 kB]
Ign http://archive.raspberrypi.org wheezy/main Translation-de_DE
Ign http://archive.raspberrypi.org wheezy/main Translation-de
Ign http://archive.raspberrypi.org wheezy/main Translation-en
Holen: 3 http://mirrordirector.raspbian.org wheezy/contrib armhf Packages [23,3 kB]
Holen: 4 http://mirrordirector.raspbian.org wheezy/non-free armhf Packages [47,3 kB]
Holen: 5 http://mirrordirector.raspbian.org wheezy/rpi armhf Packages [14 B]
Ign http://mirrordirector.raspbian.org wheezy/contrib Translation-de_DE
Ign http://mirrordirector.raspbian.org wheezy/contrib Translation-de
Ign http://mirrordirector.raspbian.org wheezy/contrib Translation-en
Ign http://mirrordirector.raspbian.org wheezy/main Translation-de_DE
Ign http://mirrordirector.raspbian.org wheezy/main Translation-de
Ign http://mirrordirector.raspbian.org wheezy/main Translation-en
Ign http://mirrordirector.raspbian.org wheezy/non-free Translation-de_DE
Ign http://mirrordirector.raspbian.org wheezy/non-free Translation-de
Ign http://mirrordirector.raspbian.org wheezy/non-free Translation-en
Ign http://mirrordirector.raspbian.org wheezy/rpi Translation-de_DE
Ign http://mirrordirector.raspbian.org wheezy/rpi Translation-de
Ign http://mirrordirector.raspbian.org wheezy/rpi Translation-en
Es wurden 7.460 kB in 58 s geholt (128 kB/s).
Paketlisten werden gelesen... Fertig
</pre>

**Comment by asb** [comment]
From the git firmware repo, using e.g. rpi-update.

**Comment by ghollingworth** [comment]
This seems to work as expected and fixes the ethernet dropping out problem

**Comment by RussNelson** [comment]
This is a good fix for me, too. Any idea when this is going to get into the Raspbian distribution? Or should I just bite the bullet and start using rpi-update?

**Comment by licaon-kter** [comment]
Just wait for it to update in 1 or 2 months? :D Oh, come on,gogogo https://github.com/Hexxeh/rpi-update

**Comment by popcornmix** [comment]
I think apt-get will be updated to current rpi-update in the next few days.

**Comment by Fabio72** [comment]
I'm on xbian
Distribution: XBian 1.0 (knockout)
Kernel version: Linux 3.18.8+ armv6l
Firmware: 115f63aa0915cdb5b6dff23822eb16699b72ae8b (4 Feb 2015 21:04:27)

Sometimes I'm facing system freezes without errors in logs. I don't know it they are system or network/usb freezes.
I'm getting

```
cat /sys/devices/platform/bcm2708_usb/regoffset
0xffffffff
cat /sys/devices/platform/bcm2708_usb/regvalue
invalid offset
```

I'm trying to fix following this article
https://raspberrypispot.wordpress.com/2013/07/08/wifi-and-ethernet-dropout-problems-in-raspberry-pi/

I opened a thread about this problem in
http://forum.xbian.org/thread-2785-post-27814.html
