### ISSUE TITLE
Wrong Y axis for HID: dragonrise

### ISSUE THREAD

**Issue by sec** [raspberrypi/linux#1527]
Hi,
I think that Y axis for this USB gamepad is wrong. Currently it reports Y values on axis 3.
According to current driver source, axis are in order X, Ry, Z, Y, Ry(?).
Shouldn't this be X,Y,Z,Ry, Rx(y) ?
This makes unable to play games/emulators which use new evdev to access the joystick (which don't provide option to rebind axis) - under old joydev this can be rebinded, but it's also in wrong order IMO.

Simply swaping (https://github.com/raspberrypi/linux/blob/rpi-4.4.y/drivers/hid/hid-dr.c):
0x09, 0x33,        /\*     Usage (Ry)            _/
with
0x09, 0x31,        /_     Usage (Y)         */
fixes the issue - axis Y is reported on axis 1.

**Comment by P33M** [comment]
This is an upstream driver - which means other distributions will be affected.

Post the bug report to the upstream HID device mailing list:
linux-input@vger.kernel.org

An FAQ on submitting bug reports to the mailing list can be found here:
www.tux.org/lkml/#s2

If an upstream patch is accepted, we can backport it if necessary.

**Comment by netpipe** [comment]
in jstest-gtk it has analog values for x axis from 0 to 255 but y axis behaves like dpad.. i think it should be on axis 3
![Screenshot at 2021-01-30 03-08-50](https://user-images.githubusercontent.com/172564/106353713-c2ac5100-62a9-11eb-9df6-d4847fc1e064.png)
![Screenshot at 2021-01-30 03-08-39](https://user-images.githubusercontent.com/172564/106353715-c344e780-62a9-11eb-851e-21634f52a93e.png)

the difference between half way there


found this too https://retropie.org.uk/forum/post/28586

**Comment by netpipe** [comment]
https://github.com/twinone/n64-arduino
