### ISSUE TITLE
ask

### ISSUE THREAD

**Issue by Farouk00321** [raspberrypi/linux#1531]
high i wont to do a project with raseberry pi zero and i don't know what i do? can you help with some source where i can find some useful tutorial about beginners in raseberry pi 
                                                   thunks a lot

**Comment by pelwell** [comment]
Sure - try [here](http://lmgtfy.com/?q=raspberry+pi+zero+tutorial).

**Comment by Farouk00321** [comment]
hhhhhhhhhhh funy
