### ISSUE TITLE
HPLIP plugin for ARM

### ISSUE THREAD

**Issue by drdanz** [raspberrypi/linux#1538]
According to [HPLIP release notess](http://hplipopensource.com/hplip-web/release_notes.html), the HPLIP plugin for the arm architecture is available since 3.15.4. At the moment on raspbian only version 3.14.6 is available, and therefore some HP printers are not supported.
On debian jessie-backports repository 3.16.3 is available and I can confirm that rebuilding that it works if rebuilt on a raspberry pi

**Comment by popcornmix** [comment]
This repo is for the linux kernel. It sounds like this issue relates to updating a raspbian package.
Try reporting here: https://www.raspbian.org/RaspbianBugs
