### ISSUE TITLE
MN88473 not being built

### ISSUE THREAD

**Issue by mcaptur** [raspberrypi/linux#1562]
MN88473 module not being built with latest kernel.. was being built fine with 4.6 tree

**Comment by pelwell** [comment]
As of 4.6 the driver has moved out of staging and become one of the approved modules. The current stock RPi kernel is built from the 4.4 tree, where the driver is still in staging, which is why it isn't part of the standard configuration.

**Comment by mcaptur** [comment]
It exits on 4.4 tree in staging and builds and works fine, but doesn't build on rpi-4.6.y and rpi-4.7.y

**Comment by JamesH65** [comment]
Should be OK on the latest kernel (4.9).
