### ISSUE TITLE
rpi-4.4.y doesn't boot on raspberry pi 1

### ISSUE THREAD

**Issue by FandM-Tele** [raspberrypi/linux#1569]
Hi
i git clone the rpi-4.4.y on my system and cross compiled it via exist cross-toolchain in https://github.com/raspberrypi/tools, but it doesn't boot on my raspberry pi 1. i must notice that i'v cross compiled the kernel version 4.1.y later and that worked.
the following is the procedure that i used :
git clone https://github.com/raspberrypi/linux
cd linux
get the config.gz from running raspbian image :
gunzip -c config.gz > linux/.config
ARCH=arm CROSS_COMPILE=${CCPREFIX} make oldconfig
ARCH=arm CROSS_COMPILE=${CCPREFIX} make -j2
ARCH=arm CROSS_COMPILE=${CCPREFIX} INSTALL_MOD_PATH=../linux_modules make modules_install

**Comment by howardqiao** [comment]
do not use old config
follow this:
https://www.raspberrypi.org/documentation/linux/kernel/building.md
make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- bcmrpi_defconfig

**Comment by Ruffio** [comment]
@FandM-Tele have you tried @howardqiao solution? Did it work? If yes, then please close this issue.

**Comment by Ruffio** [comment]
@popcornmix consider to close this issue, as there haven't been any response/feedback in a month
