### ISSUE TITLE
gcc crashes with -mtune=native on RPi3 only

### ISSUE THREAD

**Issue by staceycampbell** [raspberrypi/linux#1571]
gcc 4.9.2-10 is core dumping if the command line contains -mtune=native. This is on the new RPi3 64 bit platform only as far as I can tell.

```
pi@emu:~/tmp $ cat hello.c
#include <stdio.h>

int
main(void)
{
        printf("hello world\n");
        return 0;
}
pi@emu:~/tmp $ gcc -o hello -mtune=native hello.c
*** Error in `gcc': double free or corruption (top): 0x001c6cb0 ***
Aborted
```

**Comment by popcornmix** [comment]
Sounds like a 64-bit debian issue, rather than anything related to raspberry pi kernel.

**Comment by noloader** [comment]
@popcornmix - You seem to have to do a lot of _... NOT related to raspberry pi kernel"_.

I noticed some GitHubs have custom messages. For example, look at the [developer agreement prompt added in the Kovri GitHub](http://github.com/monero-project/kovri/pull/275):

![github-prompt](https://cloud.githubusercontent.com/assets/3538226/17233293/ad34d7da-54fc-11e6-9f78-91e3309a751c.png)

Maybe you could add similar to help manage the flow of non-relevant bug reports.

Also, you should change the link at [Raspbian Bug Reports](https://www.raspbian.org/RaspbianBugs). The link to **_[filed with Raspberry Pi]()**_ points here.

Finally, do you know where the link is to file Raspian Bug Reports?

**Comment by Ruffio** [comment]
@staceycampbell has this issue been resolved? Please close it if it has. Thanks.

**Comment by feilong** [comment]
A temporary solution is to install gcc from Stretch instead of Jessie, which worked for me when I tried to make linuxbrew work.

I follow most of the steps from this link (https://solarianprogrammer.com/2016/06/24/raspberry-pi-raspbian-install-gcc-compile-cpp-14-and-cpp-17-programs/) except that I installed `gcc` instead of `gcc-6` (so that gcc won't crash when I run `brew install`).

**Comment by staceycampbell** [comment]
This issue still exists. Is this the place to report the issue? If not, where?

**Comment by popcornmix** [comment]
gcc is a part of debian so I'd suggest here: https://www.debian.org/Bugs/

I'll close this as no linux kernel fix will help this issue.

**Comment by staceycampbell** [comment]
OK, sure. Bug has been submitted: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=851903
