### ISSUE TITLE
How to edit kernel option when building the raspbian kernel?

### ISSUE THREAD

**Issue by zfyseu** [raspberrypi/linux#1579]
Hello popcornmix!

I have followed the link "https://www.raspberrypi.org/documentation/linux/kernel/building.md" to cross compile my raspbian kernel.
But I don't know how and where to eidt kernel option to support apparmor?

Do you know how to do it ?
Thanks!

**Comment by howardqiao** [comment]
After 
make bcmrpi_defconfig or bck2709_defconfig
run 
make menuconfig

**Comment by zfyseu** [comment]
Hello,howardqiao!

I have tried what you said.
however when I run "make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- zImage modules dtbs"
it will returns: 
"scripts/kconfig/conf  --silentoldconfig Kconfig
*
- Restart config...
  *
  *
- Configure standard kernel features (expert users)
  *
  Configure standard kernel features (expert users) (EXPERT) [Y/?] y
  Enable 16-bit UID system calls (UID16) [Y/n/?](NEW) "

Do you know how to deal with it?

Thanks!

**Comment by lurch** [comment]
Did you also read https://www.raspberrypi.org/documentation/linux/kernel/configuring.md ?

IMHO this issue should be closed, and you should ask your question on the Raspberry Pi Forums https://www.raspberrypi.org/forums/
