### ISSUE TITLE
GCC Issue 70132: -mcpu=native can cause a double free abort. 

### ISSUE THREAD

**Issue by noloader** [raspberrypi/linux#1580]
I'm experiencing GCC's [Issue 70132: -mcpu=native can cause a double free abort](http://gcc.gnu.org/bugzilla/show_bug.cgi?id=70132). It appears GCC has fixed it.

Perhaps it would be a good idea to apply it to Raspian's GCC.

**Comment by popcornmix** [comment]
This repo is for the linux kernel. Your issue is a debian packaging issue.
Jessie uses gcc 4.9.2-2. The bug you've referenced is due in 4.9.5:
https://packages.debian.org/jessie/gcc

You'll get the fix when debian bumps the gcc version for Jessie.
