### ISSUE TITLE
w1-therm behavior

### ISSUE THREAD

**Issue by dkirkby** [raspberrypi/linux#1582]
I am reading 5 DS18B20 temperature sensors in 4.4.9-v7+ and noticed two features of `drivers/w1/slaves/w1-therm.c` that I have not seen documented:
- The values returned when reading the sensor device are often (always?) the result of the conversion triggered by the previous read, even when this was quite a long time ago.
- The time taken to read the sensor device is usually about 70ms but sometimes closer to 800ms. The datasheet reports a maximum conversion time of 750ms and the driver is indeed calling `msleep_interruptible(750)`, but apparently usually being interrupted.

I have an application where accurate timestamps for temperature measurements are important, so any advice is welcome. I am happy to contribute documentation once I understand better how this is working.

**Comment by x29a** [comment]
I think this is not an issue per se with the raspberry version of the linux kernel, right? Id try to get an answer on [a linux mailing list](http://vger.kernel.org/vger-lists.html) or [stackoverflow](https://stackoverflow.com/) instead.

**Comment by popcornmix** [comment]
Agreed, I don't see this as being anything Pi specific, so I don't think this is the best place to report this.

**Comment by JamesH65** [comment]
Closing as this issue has been deemed unnecessary.
