### ISSUE TITLE
drbl depends on syslinux - alternative?

### ISSUE THREAD

**Issue by vanguard2016** [raspberrypi/linux#1591]
Dear maintainers,

as there is no package "syslinux" available (which was first mentioned 3 years ago and could still not be fixed), is there an alternative for this?

I wanted to install drbl and clonezilla, but drbl depends on syslinux. So drbl and clonezilla cannot be installed. But maybe you can change the dependencies of drbl from syslinux to (existing) syslinux-efi in the repo?

Doing so should one to be enable, to install drbl and clonezilla. And I believe, syslinux-efi will do the same as syslinux (maybe better). However, this needs to change the deps in your repo.

Hope this can be done without any harm.

Thanks for reading this.

Best regards

Hans-J. Ullrich

**Comment by popcornmix** [comment]
This repo is for reporting bugs in the linux kernel. It is not for packaging issues.
If you think it is a raspbian issue then report here: https://www.raspbian.org/RaspbianBugs
