### ISSUE TITLE
arm64 rpi3_defconfig

### ISSUE THREAD

**Issue by drtyhlpr** [raspberrypi/linux#1593]
Hi kernel freaks, thanks for your great work!

I wanted to try to get arm64 rpi3 kernel running on stretch/arm64 booting via uboot/arm64.
- debootstrap of Debian stretch with qemu-aarch64 :heavy_check_mark:
- compile and install uboot (rpi_3_defconfig) inside chroot with gcc-5-arm  :heavy_check_mark:
- Entering aarch64 execution state by setting config.txt  :heavy_check_mark:

Is there any untested rpi3/BCM2837 arm64 kernel defconfig available?
Is there any list of errors or "things to patch list" for the rpi3 arm64 support, any buglists?

Well its kind of strange the "rpi marketing guys" did add "64bit cpu" in the headerlines of any rpi3 product description you can find. and definitely created some kind of selling point (and arm64 is very sexy these days). I ask myself: the performance increase of rpi3-64bit might not be "worth the work" for any regular rpi3 user - the BCM2837 "is a great 32bit cpu - thats why decided to pick it".

Maybe it was written somewhere but I did not find any official info on this question:

Will arm64 be supported by rpi3 - is it a goal of the developers? or will arm64 only be possible if "the community" will work on it? what do you think (in short) are the biggest issues with running the current arm64 kernel on rpi3? (just write what you think, I dont expect any "official statement" or such)

thanks for your time!

**Comment by popcornmix** [comment]
Currently we are not focusing on arm64 for Pi3.
We haven't seen strong enough evidence of a performance boost to justify the fragmentation. Losing the ability to switch sdcards between different Pi devices is a definite negative.

There is work going - Eric Anholt is getting arm64 support into the upstream kernel tree for Pi:
http://lists.infradead.org/pipermail/linux-rpi-kernel/2016-June/004077.html

And a number of community successes. Info here on what has been achieved:
https://www.raspberrypi.org/forums/viewtopic.php?f=72&t=137963

And Fedora 23 supports arm64 on Pi3:
https://www.raspberrypi.org/forums/viewtopic.php?f=51&t=152270

But this is a really a discussion for the forum and not a github issue.
arm64 support in raspbian may or may not happen.
If you are keen for it to happen then play with an arm64 bit image and find some reasons why we should support it. E.g. if a set of benchmarks using Chromium ran 15% faster with a 64-bit build compared to a 32-bit build, that would obviously be an argument towards supporting it.
