### ISSUE TITLE
Feature request - Add a module for sc16is752 to the standard configurations

### ISSUE THREAD

**Issue by MasterWuff** [raspberrypi/linux#1594]
Hi,

Recently I had a problem when I was switching from RPi2 to RPi3, because of only one UART interface. Never the less, I decided to buy a SC16IS752 from NXP. It can connected it to the RPi via I2C and SPI. The external interfaces are two UART ports and 8 GPIOs.

But here is the problem, the module isn't in the standard configurations to work with that.
There is the solution to complile the kernel, but I don't feel really confident with that.

Why to add the module?
-The code already exists: https://github.com/raspberrypi/linux/blob/rpi-4.1.y/drivers/tty/serial/sc16is7xx.c
-The overlay already exists (/boot/overlays/sc16is752-spi1.dtbo)
-It is only 24kB
-i'm not the only one who is dealing with one UART interface

Thanks in advance and on spending so much time to keep the system up to date.

**Comment by pelwell** [comment]
It's fine with me. @popcornmix?

**Comment by popcornmix** [comment]
Okay.

**Comment by popcornmix** [comment]
This is now in latest `rpi-update` kernel.

**Comment by MasterWuff** [comment]
Thanks a lot, this is what I call a support. Less then 24 hours.
Short Feedback: it works GREAT

**Comment by popcornmix** [comment]
Cool. Feel free to close the issue.

**Comment by DimionDR** [comment]
Hello!
 Why I2C drivers implementation?!!
Overlay file only for SPI - /boot/overlays/sc16is752-spi1.dtbo

**Comment by MasterWuff** [comment]
Hi DimionDR,
the kernel add on is for I2C and SPI. By default there is one overlay for a SPI connection, but you can write your own for I2C. Or have a look here:  https://www.raspberrypi.org/forums/viewtopic.php?f=107&t=146908&start=25
You can use both

**Comment by DimionDR** [comment]
Hello,
I am new in DTS, is it possible to change working interface for the sc16is7xx module without recompiling? My problem is what I want to use the module with SPI...
modinfo output:
pi@raspberrypi:~ $ modinfo sc16is7xx
filename:       /lib/modules/4.4.17-v7+/kernel/drivers/tty/serial/sc16is7xx.ko
description:    SC16IS7XX serial driver
author:         Jon Ringle jringle@gridpoint.com
license:        GPL
srcversion:     2021DCD9C98A4797C2CB85D
alias:          of:N_T_Cnxp,sc16is762*
alias:          of:N_T_Cnxp,sc16is760*
alias:          of:N_T_Cnxp,sc16is752*
alias:          of:N_T_Cnxp,sc16is750*
alias:          of:N_T_Cnxp,sc16is741*
alias:          of:N_T_Cnxp,sc16is740*
alias:          i2c:sc16is762
alias:          i2c:sc16is760
alias:          i2c:sc16is752
alias:          i2c:sc16is750
alias:          i2c:sc16is741
alias:          i2c:sc16is740
alias:          i2c:sc16is74x
depends:        regmap-i2c
intree:         Y
vermagic:       4.4.17-v7+ SMP mod_unload modversions ARMv7

**Comment by MasterWuff** [comment]
I'm sorry, I didn't get the file working with SPI. With i2c it works, but to be honest, the commends to controll the chip are missing (like setting bau drate or gpios). I know how to write to the registers with I2C or SPI, but the overlay was too much for my knowledge. Perhaps someone else has more experience and will complete the work and thread in the forum. To spend nearly two weeks on such a small issue is too long.

**Comment by pelwell** [comment]
What @DimionDR has spotted is that the config change only enables support for the I2C interface, not the SPI mode, which explains the behaviour you are seeing:

```
$ grep SC16 .config
CONFIG_SERIAL_SC16IS7XX_CORE=m
CONFIG_SERIAL_SC16IS7XX=m
CONFIG_SERIAL_SC16IS7XX_I2C=y
# CONFIG_SERIAL_SC16IS7XX_SPI is not set
```

I'll reopen this until SERIAL_SC16IS7XX_SPI is also defined.

**Comment by MasterWuff** [comment]
Okay, my fault. I will edit the thread in the forum

**Comment by pelwell** [comment]
With the SERIAL_SC16IS7XX_SPI option specified, modinfo now includes:

```
alias:          spi:sc16is7xx
...
depends:        regmap-spi,regmap-i2c
```

I've merged a patch that adds this option to the standard configurations. It will get picked up by the next kernel build.

**Comment by popcornmix** [comment]
latest `rpi-update` firmware has this in

**Comment by Ruffio** [comment]
@MasterWuff have you tried the new firmware? Feel free to close the issue, if the issue has been fixed.

**Comment by MasterWuff** [comment]
Just checked it with SPI - it works

**Comment by paulenuta** [comment]
Hi there,
I try to add a sc16is752-i2c but command `dtc -@ -I dts –O dtb –o sc16is752-i2c.dtbo sc16is752-i2c.dts` give me `Error: missing files`.  If I load sc16is752-spi1 overlay in /boot/config.txt I have no option to put'it on i2c and is not worling. If I put  sc16is750-i2c in /boot/config.txt is working but I only get ttySC0 :(.
Also datasheet said 1843200 crystal.
Please advise.
Thanks,
Paul

**Comment by pelwell** [comment]
Please start a topic on the [Device Tree forum](https://www.raspberrypi.org/forums/viewforum.php?f=107) with your problem - please include full details of what you have tried, and post or link to your overlay file(s).

**Comment by paulenuta** [comment]
OK I created this new topic [https://www.raspberrypi.org/forums/viewtopic.php?p=1059608#p1059608](https://www.raspberrypi.org/forums/viewtopic.php?p=1059652#p1059652) I was hopping i get some help here, my interest and issues are with existing overlays that have been discussed here, why there is available only overlays for single uart sc16is750 on i2c and dual sc16is752 on spi? There is some config where I can tell that the sc16is752-spi1 overlay will be used on i2c?
Thanks a lot!

**Comment by paulenuta** [comment]
Problem was solved and I got 2 more UARTs, thanks to PhilE, it was caused by copy/paste and "EN Dash" mixed with "Hyphen-Minus"
[https://www.raspberrypi.org/forums/viewtopic.php?p=1059652#p1059652](https://www.raspberrypi.org/forums/viewtopic.php?p=1059652#p1059652).

**Comment by pelwell** [comment]
Cool. Yes, that PhilE can be quite helpful. ;-)
