### ISSUE TITLE
Feature Request - Add IPv6 6RD module to standard configuration

### ISSUE THREAD

**Issue by rickard2** [raspberrypi/linux#1598]
Hello

I'm following this guide trying to enable IPv6 using 6RD on my Raspberry Pi: http://www.litech.org/6rd/

It seems that the current kernel `4.4.17+ #109` does not support this: 

```
$ zgrep 6RD /proc/config.gz
# CONFIG_IPV6_SIT_6RD is not set
```

Would it be possible to add this to the standard configuration? 

Thank you for all your great work, keep it up!

**Comment by JamesH65** [comment]
@popcornmix Still not in 4.9 kernel - worth adding? It doesn't seem to be included in very many architectures.

**Comment by popcornmix** [comment]
The code size increase is low and it is enabled in Ubuntu so I've let this in: https://github.com/raspberrypi/linux/commit/8dad3ff88215827e4a5ada04a717ea8fda01c267
Will be in next rpi-update kernel.

**Comment by popcornmix** [comment]
Should be in latest rpi-update kernel. Please test and close if happy.

**Comment by rickard2** [comment]
Works like a charm, thank you very much!
