### ISSUE TITLE
Bootloader offset

### ISSUE THREAD

**Issue by nomis** [raspberrypi/linux#16]
Could the bootloader be changed to load kernel.img at 0x8000 and provide the instructions and data for the first 32K itself?

Alternatively it could load a separate file for the first 32K and then kernel.bin at 0x8000?

Then there's no need to put extra data on the start of the kernel image every time.

**Comment by popcornmix** [comment]
What's the motivation for this? Saving 32K of disk space? Making build process simpler? of is there a more significant benefit?
I'm a little wary of just changing the convention, as it makes it harder to switch kernels/firmware from before/after the event.
I could add a new config.txt setting to switch between the two behaviours.
I could see if md5sum of first 32K of kernel matches the normal version, and if not, then load it at 0x8000 and fill in the normal version's first32k. Any preference?

**Comment by nomis** [comment]
The motivation is to make the build process simpler as it looks unlikely that the current process would ever get integrated with the kernel build process as the kernel shouldn't be including a fixed machine ID. It's also awkward even as a memory image that another bootloader then partially overwrites to provide arguments.

No one can use the first 32KB anyway because of the kernel arguments being written at 0x100.

I'm not sure what the best option is. I think the current boot process may loop if loaded at 0x8000.

**Comment by popcornmix** [comment]
The latest github start.elf supports config.txt option:
disable_commandline_tags=1
which avoids writing kernel arguments.

How about:
if (disable_commandline_tags=1) load kernel.img at 0. Don't fill in arguments.
else if (md5sum first32k matches) load kernel.img at 0 and fill in aguments (*)
else load kernel.img at 0x8000, GPU inserts first32K, and fills in aguments

Case (*) is deprecated and removed at some point in future.

**Comment by nomis** [comment]
That sounds reasonable but you'll need to warn people that it's happening as I know haiku is already using a "b 0x8000" as the only opcode in the first 32KB.

**Comment by nomis** [comment]
It looks like proper devicetree support makes things even more complicated because the bootloader is supposed to provide that information at 0x100, which implies that the ability to load a 32KB section from a separate file would be useful.

How you're going to get the extra parameters (serial number, etc.) to the kernel in that scenario I don't know...

**Comment by nomis** [comment]
I think you could load a device tree blob from a file to 0x100 and append the ATAGs.

**Comment by bootc** [comment]
If I understand this correctly then, the bootloader could have a device-tree mode. If there is a 'bcm2708.dtb' file in the boot partition, its contents is loaded at 0x100 instead of the ATAGS, and it could also assume that it should load the kernel at 0x8000 and put its own code at 0x0000 as necessary to setup r0/r1/r2 for kernel entry.

That way we kill several birds with one stone: device tree booting (with a .dtb file we can edit as things evolve) as well as removing the need for a custom kernel image, and the whole thing can be managed as a single transition without needing to specify special configuration options in config.txt.

Note that I don't know enough about device-tree yet to know exactly how the bootloader should insert kernel arguments into the device tree file.

**Comment by nomis** [comment]
I'd suggest the .dtb file is named something other than bcm2708.dtb as there would need to be different files for different device models (e.g. rpi-model-b.dtb) so a generic filename, something like "kernel.dtb" would be less confusing than the hardware model.

**Comment by popcornmix** [comment]
I don't know a lot about device tree, but if you tell me what is neeed I can arrange for a dtb file to be loaded at 0x100.
Do you want existing ATAGS (e.g. cmdline.txt) to be added after the dtb file ?

**Comment by bootc** [comment]
For full device tree support, we'd need the bootloader to load in the .dtb file and then edit the structure to add such things as memory size and command-line arguments added in. Device-tree should completely replace the ATAGS support.

**Comment by nomis** [comment]
It should also provide the system serial number and the MAC address.

There isn't currently any code in Linux to get the serial number from device tree even though it's a generic part of the arm arch...

**Comment by nomis** [comment]
It would also be natural for the display size/depth to be provided in the device tree instead of as module parameters.

**Comment by popcornmix** [comment]
If you provide me with a .dtb file, and explain where useful values should be inserted (ideally provide a C code function that parses/modifies the loaded .dtb), then I'll make the GPU do it.

I've implemented the optional first32k scheme described earlier. I'll share that later tonight after some testing. It also has the UART setup.

**Comment by nomis** [comment]
The list of DMA channels should also be provided (although I've not added a suitable device to the .dts file for that yet).

I don't know that much about .dtb files, but you can find the .dts in my rpi-linear branch as arch/arm/boot/dts/bcm2835.dts (this branch will currently boot with uart0 and the display but has no usb or mmc support). [You need to provide the .dtb at 0x100 via r2 or configure it to be appended to the kernel image (and then append it yourself) otherwise it won't boot]

Running "make dtbs" will create arch/arm/boot/bcm2835.dtb if you have the BCM2708 arch configured.

This file in the kernel source is strictly a convenience template, so it would be ok to put in placeholders to aid the bootloader. Everything's be32 so it should be simple to overwrite default values as required. There's already a placeholder for the memory.

**Comment by nomis** [comment]
The memory area to use (i.e. L2 on/off) could also be provided in the device tree although I haven't looked into how the kernel could reconfigure those at runtime.

**Comment by nomis** [comment]
There's libfdt for manipulating the .dtb here: git://git.jdl.com/software/dtc.git (dual GPL/BSD so you'd be able to use it).

**Comment by popcornmix** [comment]
So how do you want it loaded?
config.txt options:
 device_tree=bcm2835.dtb (possibly that will be a default in future)
 device_tree_address=0x100 (again the default)
GPU will then load it at 0x100, and overwrite the fields it knows about.
Does the code at 0x0 set r2? Should I modify that?

**Comment by nomis** [comment]
Yes, the code at 0x0 should set r2 to the device_tree_address

**Comment by popcornmix** [comment]
Okay, a test firmware:
http://dl.dropbox.com/u/3669512/start.elf

This should support:
   CONFIG_STR(device_tree)
   CONFIG(device_tree_address)
   CONFIG(kernel_address)
   CONFIG(disable_commandline_tags)

It also sets up the UART to 115200 with a 3MHz clock as requested elsewhere. You can modify these:
   CONFIG(init_uart_baud)
   CONFIG(init_uart_clock)

So, as described start32k is now optional (and should be removed from kernel.img when using device tree)
You can load a device_tree with 
device_tree=bcm2835.dtb
device_tree_address=0x100
r2 should be set to this address is initial code.
I don't (yet) modify the device tree 

I did try parsing the device tree from GPU and it looked okay (http://pastebin.com/ty66Jies)

**Comment by nomis** [comment]
This works for me!

[    0.000000] Machine: BCM2708, model: BCM2835
[    0.000000] Memory: 192MB = 192MB total
[    0.000000] bank0: VIC at 0x2000b200 (8 IRQs)
[    0.000000] bank1: VIC at 0x2000b204 (32 IRQs)
[    0.000000] bank2: VIC at 0x2000b208 (32 IRQs)
[    0.000000] sched_clock: 32 bits at 1000kHz, resolution 1000ns, wraps every 4294967ms
[    0.000000] timer1: timer at MMIO 0x20003010 (irq = 1)
[    0.000000] timer3: timer at MMIO 0x20003018 (irq = 3)
[    0.112351] Serial: AMBA PL011 UART driver
[    0.113869] 20201000.uart0: ttyAMA0 at MMIO 0x20201000 (irq = 57) is a PL011 rev3
[    0.696930] console [ttyAMA0] enabled
[    0.703394] bcm-mbox: Broadcom VideoCore Mailbox driver
[    0.709829] bcm-mbox 2000b880.mbox0: mailbox at MMIO 0x2000b880 (irq = 65, channels = 0x000b)
[    0.719777] stc: 32-bit clock at MMIO 0x20003004, 1000000 Hz
[    0.754826] Switching to clocksource stc
[    1.964569] bcm2708_fb display.0: registering framebuffer (800x480@16)
[    1.985666] Console: switching to colour frame buffer device 100x30
[    2.001894] bcm2708_wdog: default timeout=16 (nowayout=0)
[    2.012992] bcm2708_wdog 20100000.watchdog: at MMIO 0x20100000
[    2.124425] Freeing init memory: 10304K

At that point it waits forever for mmc0 as I was using cmdline.txt instead of the default :)

**Comment by kallisti5** [comment]
aaah... just when we get Haiku uart working :)  Thanks for all the hard work on this guys.

**Comment by popcornmix** [comment]
Firmware now pushed to github. Please close issue if happy.

**Comment by nomis** [comment]
The bootloader is able to load the kernel at 0x8000 and the device tree file at 0x100 so I'll close this issue and raise another one specifically on the device tree population.
