### ISSUE TITLE
Please enable CONFIG_IPVLAN=m

### ISSUE THREAD

**Issue by grigorig** [raspberrypi/linux#1612]
The ipvlan network device offers a bridge-like virtual device that can be paired with physical network devices. It's particularly interesting for easy networking of containers and virtualization. It's like macvlan, but because it's working on a different layer it can function with WiFi. Here's the documentation:

https://www.kernel.org/doc/Documentation/networking/ipvlan.txt

Can you please enable it as a module?

**Comment by popcornmix** [comment]
This is in latest `rpi-update` firmware.

**Comment by grigorig** [comment]
Thanks!
