### ISSUE TITLE
please enable CONFIG_VXLAN

### ISSUE THREAD

**Issue by justincormack** [raspberrypi/linux#1614]
We have started building official Docker builds for Raspbian since Docker 1.12.1, but the Docker Swarm mode requires vxlan for networking, so it would be good if CONFIG_VXLAN could be enabled.

See https://github.com/docker/docker/issues/25892

**Comment by popcornmix** [comment]
This is in latest `rpi-update` firmware.

**Comment by justincormack** [comment]
Brilliant thanks!

**Comment by DieterReuter** [comment]
@popcornmix WOOT - that was pretty fast!
