### ISSUE TITLE
Enable raw HID device support

### ISSUE THREAD

**Issue by ozancaglayan** [raspberrypi/linux#164]
Current rpi kernel have CONFIG_HIDRAW disabled. Enabling this will enable raw HID devices on Raspberry Pi like the Emotiv EEG brain headset's USB dongle.

**Comment by ghollingworth** [comment]
Anyone else want this? 

Otherwise just rebuild the kernel

**Comment by ozancaglayan** [comment]
There's some people in here needing it for a touchscreen:
  http://www.raspberrypi.org/phpBB3/viewtopic.php?f=29&t=9054

also there are manual blog entries dedicated to enabling HIDRAW and rebuilding the kernel.

I don't know how do you decide to enable/disable things in kernel but enabling this may help a lot of DIY people to get out-of-the-box HID support

**Comment by asb** [comment]
Yes, we should enable this.

**Comment by popcornmix** [comment]
It's in the "next" firmware tree.
https://github.com/Hexxeh/rpi-firmware/commit/bed00525a7d5ea232e2a0afb631771fe61026e77
