### ISSUE TITLE
dtoverlay=vc4-kms-v3d doesn't work with analog video

### ISSUE THREAD

**Issue by grray** [raspberrypi/linux#1648]
I enabled experimental OpenGL driver and got black screen on my analog TV, connected to Raspberry pi via RCA cable. Raspberry pi is working and I can login to it via ssh. All is fine, when I connect it to monitor via HDMI cable. Before enabling experimental OpenGL driver all also was good on analog TV. Is it even supposed to work with TV? I'll provide logs, if needed.

**Comment by popcornmix** [comment]
Can you create the issue here: https://github.com/anholt/linux/issues
