### ISSUE TITLE
please enable CoDel in 3.6 kernel

### ISSUE THREAD

**Issue by rpodgorny** [raspberrypi/linux#165]
the config should say:

CONFIG_NET_SCH_CODEL=m
CONFIG_NET_SCH_FQ_CODEL=m

...so i can use my raspi as a low-latency router. thank you very much!

(originally at https://github.com/archlinuxarm/PKGBUILDs/issues/314)

**Comment by ghollingworth** [comment]
Why can't you just rebuild the kernel?

Gordon

**Comment by rpodgorny** [comment]
well, of course i can. i just can't see any reason why this is not enabled by default... ;-)

**Comment by simonjhall** [comment]
Hi there,
have you tried this on the rpi - does it make a noticeable difference?
If not it would just add to the compile time...

**Comment by rpodgorny** [comment]
hi! ...not yet since i've had some other issues with the -next kernel. ...but anyway, compile time delta for this module is negligible. ...and compile time shouldn't be an obstacle anyway imho (you compile only once).

**Comment by popcornmix** [comment]
This is enabled in "next" firmware tree:
https://github.com/raspberrypi/linux/commit/ff1c7e11bbbf4e0c81c3de07d887b471603927e7

**Comment by rpodgorny** [comment]
thank you very much! closing...
