### ISSUE TITLE
Debug Message DEBUG_TIME_EACH_UPDATE fps allways 0 in fbtft_update_display

### ISSUE THREAD

**Issue by gdampf** [raspberrypi/linux#1655]
Line 398 and 399 in fbtft-core.c (rpi-4.4.y) seems to be switched.
fps (frames per second) allways 0, because last update time changed before calculation!

**Comment by popcornmix** [comment]
Yes, I agree. fps will always be zero.
@ghollingworth okay for me to change?

**Comment by popcornmix** [comment]
Sorry - this isn't @ghollingworth 's driver (I was thinking it was from the Pi display driver).
This is actually upstream driver code. It would be best submitted upstream:
https://www.kernel.org/doc/Documentation/SubmittingPatches
and we can pull it in from there.

**Comment by gdampf** [comment]
Additional to switching the two lines, the expression in line 395 has to be negated. A leading "!" works well. The complete patch looks like this:

<pre>
--- linux/drivers/staging/fbtft/fbtft-core.c.orig       2016-09-27 07:25:30.209652437 +0200
+++ linux/drivers/staging/fbtft/fbtft-core.c    2016-09-27 07:23:37.201794540 +0200
@@ -391,10 +391,9 @@ static void fbtft_update_display(struct
        if (unlikely(timeit)) {
                ts_end = ktime_get();
-               if (ktime_to_ns(par->update_time))
+               if (!ktime_to_ns(par->update_time))
                        par->update_time = ts_start;
-               par->update_time = ts_start;
                fps = ktime_us_delta(ts_start, par->update_time);
                fps = fps ? 1000000 / fps : 0;
@@ -406,6 +405,7 @@ static void fbtft_update_display(struct
                        "Display update: %ld kB/s, fps=%ld\n",
                        throughput, fps);
                par->first_update_done = true;
+               par->update_time = ts_start;
        }
 }
</pre>

@popcornmix : I never submitted a patch before and it seems to me a bit too much work to find the right place. The document you linked to, I don't want to read completely.
I just wanted you to know, that there is a bug in the code.

**Comment by popcornmix** [comment]
I've sent an email to the author of the commit that appeared to introduce the fps bug. We'll see if he sorts out a fix.

**Comment by KsenijaS** [comment]
Hi, I am the author of the patch that introduced this bug, sorry about that. I don't have a raspberry pi to test this patch. Also I wonder if this would to fix the issue:

--- linux/drivers/staging/fbtft/fbtft-core.c.orig       2016-09-27 07:25:30.209652437 +0200
+++ linux/drivers/staging/fbtft/fbtft-core.c    2016-09-27 07:23:37.201794540 +0200
@@ -391,10 +391,9 @@ static void fbtft_update_display(struct

        if (unlikely(timeit)) {
                ts_end = ktime_get();
-               if (ktime_to_ns(par->update_time))
+               if (!ktime_to_ns(par->update_time))
                        par->update_time = ts_start;

-               par->update_time = ts_start;
                fps = ktime_us_delta(ts_start, par->update_time);
+              par->update_time = ts_start;
                fps = fps ? 1000000 / fps : 0;

@@ -406,6 +405,7 @@ static void fbtft_update_display(struct
                        "Display update: %ld kB/s, fps=%ld\n",
                        throughput, fps);
                par->first_update_done = true;
        }
 }

There is a more simple tutorial how to send a patch: https://kernelnewbies.org/FirstKernelPatch
I can send @gdampf patch, but I would also like to give him/her credit for it

**Comment by KsenijaS** [comment]
Hi, I am the author of the patch that introduced this bug, sorry about that. I cannot test this patch since I don't have the hardware. I also wonder if this would work:

```
--- a/drivers/staging/fbtft/fbtft-core.c
+++ b/drivers/staging/fbtft/fbtft-core.c
@@ -391,11 +391,11 @@ static void fbtft_update_display(struct fbtft_par *par, un

        if (unlikely(timeit)) {
                ts_end = ktime_get();
-               if (ktime_to_ns(par->update_time))
+               if (!ktime_to_ns(par->update_time))
                        par->update_time = ts_start;

-               par->update_time = ts_start;
                fps = ktime_us_delta(ts_start, par->update_time);
+               par->update_time = ts_start;
                fps = fps ? 1000000 / fps : 0;

                throughput = ktime_us_delta(ts_end, ts_start);
```

There is a more simple tutorial how to send a patch: https://kernelnewbies.org/FirstKernelPatch
I can send @gdampf patch but I would also like to give him/her credit for it.
