### ISSUE TITLE
dist-upgrade breaks perl and dpkg

### ISSUE THREAD

**Issue by boilerbots** [raspberrypi/linux#167]
I ran apt-get update followed by apt-get dist-upgrade and it fails leaving python busted and the upgrade in a bad state. Here is the output:

root@pi:/home/pi# apt-get update
Get:1 http://archive.raspberrypi.org wheezy InRelease [7,737 B]
Get:2 http://mirrordirector.raspbian.org wheezy InRelease [12.5 kB]
Get:3 http://archive.raspberrypi.org wheezy/main armhf Packages [5,753 B]
Get:4 http://mirrordirector.raspbian.org wheezy/main armhf Packages [7,384 kB]
Ign http://archive.raspberrypi.org wheezy/main Translation-en_GB  
Ign http://archive.raspberrypi.org wheezy/main Translation-en
Get:5 http://mirrordirector.raspbian.org wheezy/contrib armhf Packages [23.3 kB]  
Get:6 http://mirrordirector.raspbian.org wheezy/non-free armhf Packages [47.7 kB]  
Get:7 http://mirrordirector.raspbian.org wheezy/rpi armhf Packages [14 B]  
Ign http://mirrordirector.raspbian.org wheezy/contrib Translation-en_GB  
Ign http://mirrordirector.raspbian.org wheezy/contrib Translation-en  
Ign http://mirrordirector.raspbian.org wheezy/main Translation-en_GB  
Ign http://mirrordirector.raspbian.org wheezy/main Translation-en  
Ign http://mirrordirector.raspbian.org wheezy/non-free Translation-en_GB  
Ign http://mirrordirector.raspbian.org wheezy/non-free Translation-en  
Ign http://mirrordirector.raspbian.org wheezy/rpi Translation-en_GB  
Ign http://mirrordirector.raspbian.org wheezy/rpi Translation-en  
Fetched 7,481 kB in 54s (137 kB/s)  
Reading package lists... Done
root@pi:/home/pi# apt-get -f install
Reading package lists... Done
Building dependency tree  
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
root@pi:/home/pi# apt-get upgrade
Reading package lists... Done
Building dependency tree  
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
root@pi:/home/pi# apt-get dist-upgrade
Reading package lists... Done
Building dependency tree  
Reading state information... Done
Calculating upgrade... Done
The following NEW packages will be installed:
  apt apt-utils base-files base-passwd bash bash-completion bsdmainutils bsdutils ca-certificates coreutils dash debconf debconf-i18n debianutils
  diffutils dpkg e2fslibs e2fsprogs findutils gcc-4.7-base gnupg gnupg-curl gpgv grep gzip hostname initscripts insserv krb5-locales libacl1
  libapt-inst1.5 libapt-pkg4.12 libattr1 libblkid1 libbz2-1.0 libc-bin libc6 libcomerr2 libcurl3-gnutls libdb5.1 libgcc1 libgcrypt11 libgnutls26
  libgpg-error0 libgpm2 libgssapi-krb5-2 libidn11 libk5crypto3 libkeyutils1 libkrb5-3 libkrb5support0 libldap-2.4-2 liblocale-gettext-perl liblzma5
  libmount1 libncurses5 libp11-kit0 libpam-modules libpam-modules-bin libpam-runtime libpam0g libpng12-0 libreadline6 librtmp0 libsasl2-2
  libsasl2-modules libselinux1 libsemanage-common libsemanage1 libsepol1 libslang2 libss2 libssh2-1 libssl1.0.0 libstdc++6 libtasn1-3
  libtext-charwidth-perl libtext-iconv-perl libtext-wrapi18n-perl libtinfo5 libusb-0.1-4 libustr-1.0-1 libuuid1 login lsb-base mount multiarch-support
  ncurses-base ncurses-bin openssl original-awk passwd perl-base psmisc raspbian-archive-keyring readline-common sed sensible-utils sysv-rc sysvinit
  sysvinit-utils tar tzdata util-linux uuid-runtime zlib1g
0 upgraded, 106 newly installed, 0 to remove and 0 not upgraded.
Need to get 13.5 MB/41.5 MB of archives.
After this operation, 103 MB of additional disk space will be used.
Do you want to continue [Y/n]? y
Get:1 http://mirrordirector.raspbian.org/raspbian/ wheezy/main original-awk armhf 2011-08-10-2 [69.7 kB]
Get:2 http://mirrordirector.raspbian.org/raspbian/ wheezy/main sensible-utils all 0.0.7 [8,850 B]
Get:3 http://mirrordirector.raspbian.org/raspbian/ wheezy/main debianutils armhf 4.3.2 [77.6 kB]
Get:4 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libbz2-1.0 armhf 1.0.6-4 [47.4 kB]
Get:5 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libselinux1 armhf 2.1.9-5 [84.1 kB]
Get:6 http://mirrordirector.raspbian.org/raspbian/ wheezy/main zlib1g armhf 1:1.2.7.dfsg-13 [87.2 kB]
Get:7 http://mirrordirector.raspbian.org/raspbian/ wheezy/main tar armhf 1.26-4 [967 kB]
Get:8 http://mirrordirector.raspbian.org/raspbian/ wheezy/main dash armhf 0.5.7-3 [104 kB]  
Get:9 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libtinfo5 armhf 5.9-10 [264 kB]  
Get:10 http://mirrordirector.raspbian.org/raspbian/ wheezy/main bash armhf 4.2-4 [1,439 kB]  
Get:11 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libattr1 armhf 1:2.4.46-8 [18.5 kB]  
Get:12 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libacl1 armhf 2.2.51-8 [27.7 kB]  
Get:13 http://mirrordirector.raspbian.org/raspbian/ wheezy/main diffutils armhf 1:3.2-6 [353 kB]  
Get:14 http://mirrordirector.raspbian.org/raspbian/ wheezy/main e2fslibs armhf 1.42.5-1 [185 kB]  
Get:15 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libpam0g armhf 1.1.3-7.1 [122 kB]  
Get:16 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libsemanage-common all 2.1.6-6 [23.2 kB]  
Get:17 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libsepol1 armhf 2.1.4-3 [126 kB]  
Get:18 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libustr-1.0-1 armhf 1.0.4-3 [72.4 kB]  
Get:19 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libsemanage1 armhf 2.1.6-6 [89.1 kB]  
Get:20 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libdb5.1 armhf 5.1.29-5 [648 kB]  
Get:21 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libpam-modules-bin armhf 1.1.3-7.1 [100 kB]  
Get:22 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libpam-modules armhf 1.1.3-7.1 [324 kB]  
Get:23 http://mirrordirector.raspbian.org/raspbian/ wheezy/main passwd armhf 1:4.1.5.1-1 [1,173 kB]  
Get:24 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libcomerr2 armhf 1.42.5-1 [54.7 kB]  
Get:25 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libss2 armhf 1.42.5-1 [59.0 kB]  
Get:26 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libncurses5 armhf 5.9-10 [94.6 kB]  
Get:27 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libslang2 armhf 2.2.4-15 [515 kB]  
Get:28 http://mirrordirector.raspbian.org/raspbian/ wheezy/main e2fsprogs armhf 1.42.5-1 [983 kB]  
Get:29 http://mirrordirector.raspbian.org/raspbian/ wheezy/main findutils armhf 4.4.2-4 [607 kB]  
Get:30 http://mirrordirector.raspbian.org/raspbian/ wheezy/main grep armhf 2.12-2 [433 kB]  
Get:31 http://mirrordirector.raspbian.org/raspbian/ wheezy/main gzip armhf 1.5-1.1 [116 kB]  
Get:32 http://mirrordirector.raspbian.org/raspbian/ wheezy/main hostname armhf 3.11 [14.4 kB]  
Get:33 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libpam-runtime all 1.1.3-7.1 [228 kB]  
Get:34 http://mirrordirector.raspbian.org/raspbian/ wheezy/main login armhf 1:4.1.5.1-1 [974 kB]  
Get:35 http://mirrordirector.raspbian.org/raspbian/ wheezy/main ncurses-bin armhf 5.9-10 [332 kB]  
Get:36 http://mirrordirector.raspbian.org/raspbian/ wheezy/main sed armhf 4.2.1-10 [246 kB]  
Get:37 http://mirrordirector.raspbian.org/raspbian/ wheezy/main readline-common all 6.2-8 [55.3 kB]  
Get:38 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libreadline6 armhf 6.2-8 [146 kB]  
Get:39 http://mirrordirector.raspbian.org/raspbian/ wheezy/main raspbian-archive-keyring all 20120528.2 [3,514 B]  
Get:40 http://mirrordirector.raspbian.org/raspbian/ wheezy/main base-passwd armhf 3.5.26 [45.2 kB]  
Get:41 http://mirrordirector.raspbian.org/raspbian/ wheezy/main ncurses-base all 5.9-10 [198 kB]  
Get:42 http://mirrordirector.raspbian.org/raspbian/ wheezy/main liblocale-gettext-perl armhf 1.05-7 [19.6 kB]  
Get:43 http://mirrordirector.raspbian.org/raspbian/ wheezy/main bash-completion all 1:2.0-1 [193 kB]  
Get:44 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libgcrypt11 armhf 1.5.0-3 [301 kB]  
Get:45 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libp11-kit0 armhf 0.12-3 [48.2 kB]  
Get:46 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libtasn1-3 armhf 2.13-2 [63.3 kB]  
Get:47 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libgpm2 armhf 1.20.4-6 [34.9 kB]  
Get:48 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libkeyutils1 armhf 1.5.5-3 [7,754 B]  
Get:49 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libidn11 armhf 1.25-2 [175 kB]  
Get:50 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libldap-2.4-2 armhf 2.4.31-1 [218 kB]  
Get:51 http://mirrordirector.raspbian.org/raspbian/ wheezy/main librtmp0 armhf 2.4+20111222.git4e06e21-1 [58.0 kB]  
Get:52 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libpng12-0 armhf 1.2.49-1 [179 kB]  
Get:53 http://mirrordirector.raspbian.org/raspbian/ wheezy/main bsdmainutils armhf 9.0.3 [207 kB]  
Get:54 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libtext-iconv-perl armhf 1.7-5 [16.7 kB]  
Get:55 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libtext-charwidth-perl armhf 0.04-7 [10.6 kB]  
Get:56 http://mirrordirector.raspbian.org/raspbian/ wheezy/main libtext-wrapi18n-perl all 0.06-7 [8,980 B]  
Get:57 http://mirrordirector.raspbian.org/raspbian/ wheezy/main ca-certificates all 20120623 [183 kB]  
Get:58 http://mirrordirector.raspbian.org/raspbian/ wheezy/main gnupg-curl armhf 1.4.12-6 [61.2 kB]  
Get:59 http://mirrordirector.raspbian.org/raspbian/ wheezy/main psmisc armhf 22.19-1 [131 kB]  
Get:60 http://mirrordirector.raspbian.org/raspbian/ wheezy/main uuid-runtime armhf 2.20.1-5.2 [61.1 kB]  
Fetched 13.5 MB in 1min 11s (189 kB/s)  
/usr/bin/perl: error while loading shared libraries: : cannot open shared object file: No such file or directory
Selecting previously unselected package libc-bin.
(Reading database ... 41 files and directories currently installed.)
Unpacking libc-bin (from .../libc-bin_2.13-37+rpi1_armhf.deb) ...
Setting up libc-bin (2.13-37+rpi1) ...
Selecting previously unselected package gcc-4.7-base:armhf.
(Reading database ... 112 files and directories currently installed.)
Unpacking gcc-4.7-base:armhf (from .../gcc-4.7-base_4.7.2-4+rpi1_armhf.deb) ...
Setting up gcc-4.7-base:armhf (4.7.2-4+rpi1) ...
Selecting previously unselected package multiarch-support.
(Reading database ... 121 files and directories currently installed.)
Unpacking multiarch-support (from .../multiarch-support_2.13-37+rpi1_armhf.deb) ...
Selecting previously unselected package libc6:armhf.
Unpacking libc6:armhf (from .../libc6_2.13-37+rpi1_armhf.deb) ...
Selecting previously unselected package libgcc1:armhf.
dpkg: regarding .../libgcc1_1%3a4.7.2-4+rpi1_armhf.deb containing libgcc1:armhf, pre-dependency problem:
 libgcc1 pre-depends on multiarch-support
  multiarch-support is unpacked, but has never been configured.

dpkg: error processing /var/cache/apt/archives/libgcc1_1%3a4.7.2-4+rpi1_armhf.deb (--unpack):
 pre-dependency problem - not installing libgcc1:armhf
Errors were encountered while processing:
 /var/cache/apt/archives/libgcc1_1%3a4.7.2-4+rpi1_armhf.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
root@pi:/home/pi#

**Comment by boilerbots** [comment]
Now that perl is broken it seems dpkg is screwed.

When I try to run perl:

pi@pi ~ $ perl
perl: error while loading shared libraries: : cannot open shared object file: No such file or directory

When I try upgrade perl:

pi@pi ~ $ sudo apt-get install perl
Reading package lists... Done
Building dependency tree  
Reading state information... Done
You might want to run 'apt-get -f install' to correct these:
The following packages have unmet dependencies:
 libc6 : Depends: libgcc1 but it is not going to be installed
 perl : Depends: perl-base (= 5.14.2-15+rpi1) but it is not going to be installed
        Depends: perl-modules (>= 5.14.2-15+rpi1) but it is not going to be installed
        Depends: libbz2-1.0 but it is not going to be installed
        Depends: libdb5.1 but it is not going to be installed
        Depends: libgcc1 (>= 1:4.4.0) but it is not going to be installed
        Depends: libgdbm3 (>= 1.8.3) but it is not going to be installed
        Depends: zlib1g (>= 1:1.2.3.3) but it is not going to be installed
        Recommends: netbase but it is not going to be installed
E: Unmet dependencies. Try 'apt-get -f install' with no packages (or specify a solution).

When I tried to fix the missing dependencies, apt-get just segfaults:

sudopi@pi ~ $ sudo apt-get -f install
Reading package lists... Done
Building dependency tree  
Reading state information... Done
Correcting dependencies... Done
The following extra packages will be installed:
  libgcc1
The following NEW packages will be installed:
  libgcc1
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
2 not fully installed or removed.
Need to get 0 B/54.5 kB of archives.
After this operation, 209 kB of additional disk space will be used.
Do you want to continue [Y/n]? y
pi@pi ~ $ 

There was a segfault, I believe because perl is now busted.

**Comment by popcornmix** [comment]
Is it possible the scdard was full?
Can you confirm if same problem occurs from a clean image of sdcard?

**Comment by boilerbots** [comment]
Still have 13G free space.

**Comment by boilerbots** [comment]
I started over from scratch.
