### ISSUE TITLE
raspbian pixel network preferences doesn't have any way of specifying a hidden ssid

### ISSUE THREAD

**Issue by mintslice** [raspberrypi/linux#1673]
The Network Preferences doesn't allow you to specify a hidden SSID, making connecting very difficult.

After selecting SSID, the list only includes "non hidden" SSID's (or nothing if there are no other SSIDs) and it's not possible to specify a SSID if you're trying to connect to a hidden network.

There should be an option to select "Other network" and then specify the SSID manually.

**Comment by popcornmix** [comment]
This isn't a linux kernel issue. Please report this here:
https://github.com/RPi-Distro/raspberrypi-ui-mods
