### ISSUE TITLE
Mac addess in Device Tree

### ISSUE THREAD

**Issue by kukabu** [raspberrypi/linux#1679]
Currently the firmware sets mac-address node. It doesn't meet specifications.
doc says:
- local-mac-address: array of 6 bytes, specifies the MAC address that was
  assigned to the network device;
- mac-address: array of 6 bytes, specifies the MAC address that was last used by
  the boot program; should be used in cases where the MAC address assigned to
  the device by the boot program is different from the "local-mac-address"
  property;

It's useful with https://github.com/raspberrypi/linux/commit/c489565b536ff5382460273fd9513f0adebec024 for dropping https://github.com/raspberrypi/linux/commit/1bc556871ead5d8c9f1c2721523d5b80365d308f

**Comment by pelwell** [comment]
I'll make the change in the firmware, and I can guarantee it won't break anything because the smsc95xx driver isn't using it - as a USB device it doesn't have an associated Device Tree node (dev->udev->dev.of_node == NULL), so of_get_mac_address() will always fail.

**Comment by kukabu** [comment]
Fixed.
