### ISSUE TITLE
Powered hub, USB wifi dongle and Ethernet: issues correlation

### ISSUE THREAD

**Issue by ghost** [raspberrypi/linux#168]
My configuration around end of October:
1 Raspberry Pi 256M (manuf. in UK)
1 Sitecom 7-port hub
1 Sitecom RTL8191S WLAN adapter (USB)
rpi kernel + rpi firmware + default kernel parameter
Raspberry powered with an USB cable coming from the hub

Problems with wifi: sometimes it would randomly be dead, rebooting or unplug/replug would work.
Problems with ethernet: did not use it

My configuration now - scenario 1:
1 Raspberry Pi 512M
1 Sitecom 7-port hub
1 Sitecom RTL8191S WLAN adapter (USB)
rpi kernel + rpi firmware + default kernel parameter
Raspberry powered with an USB cable coming from the hub

Problems with wifi: the RTL8191S correctly associates to AP but cannot communicate, furthermore its MAC address is all FF:FF:FF:FF:FF:FF
Problems with ethernet: will randomly disconnect, never coming back online, see relevant "grep smsc95xx /var/log/kern.log" pasted below.

My configuration now - scenario 2:
same hardware, tested with kernel command line parameter smsc95xx.turbo_mode=N

same problems

My configuration now - scenario 3:
same hardware
power the RPI with a 5.1V phone charger instead of through hub
put the wifi dongle directly connected to the RPI
hub completely detached from RPI

Wifi will get correct MAC address and connect successfully (RX/TX working, not only RX like before)
no ethernet issues so far (little testing done so far)

My configuration now - scenario 4:
same hardware
power the RPI with a 5.1V phone charger instead of through hub
put the wifi dongle on the hub

Wifi will get correct MAC address and connect successfully, but will also go back to the FF:FF:FF:FF:FF:FF dead mode after a while
no ethernet issues so far (little testing done so far)

---

Summary

The laptop HUB and RPI are taking power from the same power socket multiplier, thus this post claiming GND as guilt could be relevant:
http://www.raspberrypi.org/phpBB3/viewtopic.php?f=66&t=11971

---

Update

I have tested out that the 4 ports on the left half of my Sitecom 7-ports hub are all providing not enough power, leading to the wifi dongle issue.
The ethernet problem could be unrelated.

Can you please update the elinux.org wiki page with information about this Sitecom 7-ports hub  art.no CN-061? It would be nice to spare the pain to other users.

Basically only the remaining 3 ports are providing enough power. Unfortunately I do not have a multimeter here to measure it.

---

Dec  2 15:53:34 raspberrypi kernel: [    1.305619] usbcore: registered new interface driver smsc95xx
Dec  2 15:53:34 raspberrypi kernel: [    3.013480] smsc95xx v1.0.4
Dec  2 15:53:34 raspberrypi kernel: [    3.090294] smsc95xx 1-1.1:1.0: eth0: register 'smsc95xx' at usb-bcm2708_usb-1.1, smsc95xx USB 2.0 Ethernet, b8:27:eb:94:bd:f0
Dec  2 15:53:34 raspberrypi kernel: [   30.062970] smsc95xx 1-1.1:1.0: eth0: link up, 100Mbps, full-duplex, lpa 0xCDE1
Dec  2 16:02:51 raspberrypi kernel: [  535.944858] smsc95xx 1-1.1:1.0: eth0: Failed to read register index 0x00000114
Dec  2 16:02:56 raspberrypi kernel: [  540.944854] smsc95xx 1-1.1:1.0: eth0: Failed to write register index 0x00000114
Dec  2 16:03:01 raspberrypi kernel: [  545.944860] smsc95xx 1-1.1:1.0: eth0: Failed to read register index 0x00000114
Dec  2 16:03:06 raspberrypi kernel: [  550.944864] smsc95xx 1-1.1:1.0: eth0: Failed to read register index 0x00000118
Dec  2 16:03:11 raspberrypi kernel: [  555.944863] smsc95xx 1-1.1:1.0: eth0: Failed to read register index 0x00000114
Dec  2 16:03:16 raspberrypi kernel: [  560.944863] smsc95xx 1-1.1:1.0: eth0: Failed to write register index 0x00000114
Dec  2 16:03:21 raspberrypi kernel: [  565.944860] smsc95xx 1-1.1:1.0: eth0: Failed to read register index 0x00000114
Dec  2 16:03:26 raspberrypi kernel: [  570.944860] smsc95xx 1-1.1:1.0: eth0: Failed to read register index 0x00000118
Dec  2 16:03:32 raspberrypi kernel: [  577.044871] smsc95xx 1-1.1:1.0: eth0: Failed to read register index 0x00000114
Dec  2 16:03:37 raspberrypi kernel: [  582.044866] smsc95xx 1-1.1:1.0: eth0: Failed to write register index 0x00000114
Dec  2 16:03:42 raspberrypi kernel: [  587.044867] smsc95xx 1-1.1:1.0: eth0: Failed to read register index 0x00000114
Dec  2 16:03:47 raspberrypi kernel: [  592.044867] smsc95xx 1-1.1:1.0: eth0: Failed to read register index 0x00000118
Dec  2 16:03:52 raspberrypi kernel: [  597.044865] smsc95xx 1-1.1:1.0: eth0: Failed to read register index 0x00000114
Dec  2 16:03:57 raspberrypi kernel: [  602.044869] smsc95xx 1-1.1:1.0: eth0: Failed to write register index 0x00000114
Dec  2 16:04:02 raspberrypi kernel: [  607.044866] smsc95xx 1-1.1:1.0: eth0: Failed to read register index 0x00000114
Dec  2 16:04:07 raspberrypi kernel: [  612.044869] smsc95xx 1-1.1:1.0: eth0: Failed to read register index 0x00000118
Dec  2 16:04:12 raspberrypi kernel: [  617.214897] smsc95xx 1-1.1:1.0: eth0: Failed to write register index 0x00000014
Dec  2 16:04:12 raspberrypi kernel: [  617.214929] smsc95xx 1-1.1:1.0: eth0: Failed to write HW_CFG_LRST_ bit in HW_CFG register, ret = -110
Dec  2 16:04:18 raspberrypi kernel: [  623.214894] smsc95xx 1-1.1:1.0: eth0: Failed to write register index 0x00000014
Dec  2 16:04:18 raspberrypi kernel: [  623.214926] smsc95xx 1-1.1:1.0: eth0: Failed to write HW_CFG_LRST_ bit in HW_CFG register, ret = -110
Dec  2 16:04:24 raspberrypi kernel: [  629.214872] smsc95xx 1-1.1:1.0: eth0: Failed to write register index 0x00000014
Dec  2 16:04:24 raspberrypi kernel: [  629.214903] smsc95xx 1-1.1:1.0: eth0: Failed to write HW_CFG_LRST_ bit in HW_CFG register, ret = -110
Dec  2 16:04:30 raspberrypi kernel: [  635.214874] smsc95xx 1-1.1:1.0: eth0: Failed to write register index 0x00000014
Dec  2 16:04:30 raspberrypi kernel: [  635.214904] smsc95xx 1-1.1:1.0: eth0: Failed to write HW_CFG_LRST_ bit in HW_CFG register, ret = -110
Dec  2 16:04:36 raspberrypi kernel: [  641.214872] smsc95xx 1-1.1:1.0: eth0: Failed to write register index 0x00000014
Dec  2 16:04:36 raspberrypi kernel: [  641.214915] smsc95xx 1-1.1:1.0: eth0: Failed to write HW_CFG_LRST_ bit in HW_CFG register, ret = -110
Dec  2 16:04:42 raspberrypi kernel: [  647.214891] smsc95xx 1-1.1:1.0: eth0: Failed to write register index 0x00000014
Dec  2 16:04:42 raspberrypi kernel: [  647.214923] smsc95xx 1-1.1:1.0: eth0: Failed to write HW_CFG_LRST_ bit in HW_CFG register, ret = -110
Dec  2 16:04:48 raspberrypi kernel: [  653.214884] smsc95xx 1-1.1:1.0: eth0: Failed to write register index 0x00000014
Dec  2 16:04:48 raspberrypi kernel: [  653.214915] smsc95xx 1-1.1:1.0: eth0: Failed to write HW_CFG_LRST_ bit in HW_CFG register, ret = -110
Dec  2 16:04:54 raspberrypi kernel: [  659.214956] smsc95xx 1-1.1:1.0: eth0: Failed to write register index 0x00000014
Dec  2 16:04:54 raspberrypi kernel: [  659.214987] smsc95xx 1-1.1:1.0: eth0: Failed to write HW_CFG_LRST_ bit in HW_CFG register, ret = -110
Dec  2 16:05:00 raspberrypi kernel: [  665.214880] smsc95xx 1-1.1:1.0: eth0: Failed to write register index 0x00000014
Dec  2 16:05:00 raspberrypi kernel: [  665.214910] smsc95xx 1-1.1:1.0: eth0: Failed to write HW_CFG_LRST_ bit in HW_CFG register, ret = -110
Dec  2 16:05:06 raspberrypi kernel: [  671.214884] smsc95xx 1-1.1:1.0: eth0: Failed to write register index 0x00000014
Dec  2 16:05:06 raspberrypi kernel: [  671.214915] smsc95xx 1-1.1:1.0: eth0: Failed to write HW_CFG_LRST_ bit in HW_CFG register, ret = -110
Dec  2 16:05:12 raspberrypi kernel: [  677.214974] smsc95xx 1-1.1:1.0: eth0: Failed to write register index 0x00000014
Dec  2 16:05:12 raspberrypi kernel: [  677.215005] smsc95xx 1-1.1:1.0: eth0: Failed to write HW_CFG_LRST_ bit in HW_CFG register, ret = -110
Dec  2 16:05:18 raspberrypi kernel: [  683.214876] smsc95xx 1-1.1:1.0: eth0: Failed to write register index 0x00000014
Dec  2 16:05:18 raspberrypi kernel: [  683.214907] smsc95xx 1-1.1:1.0: eth0: Failed to write HW_CFG_LRST_ bit in HW_CFG register, ret = -110
Dec  2 16:05:24 raspberrypi kernel: [  689.214914] smsc95xx 1-1.1:1.0: eth0: Failed to write register index 0x00000014
Dec  2 16:05:24 raspberrypi kernel: [  689.214946] smsc95xx 1-1.1:1.0: eth0: Failed to write HW_CFG_LRST_ bit in HW_CFG register, ret = -110
Dec  2 16:05:30 raspberrypi kernel: [  695.214955] smsc95xx 1-1.1:1.0: eth0: Failed to write register index 0x00000014
Dec  2 16:05:30 raspberrypi kernel: [  695.214986] smsc95xx 1-1.1:1.0: eth0: Failed to write HW_CFG_LRST_ bit in HW_CFG register, ret = -110
Dec  2 16:05:36 raspberrypi kernel: [  701.214883] smsc95xx 1-1.1:1.0: eth0: Failed to write register index 0x00000014
Dec  2 16:05:36 raspberrypi kernel: [  701.214914] smsc95xx 1-1.1:1.0: eth0: Failed to write HW_CFG_LRST_ bit in HW_CFG register, ret = -110
Dec  2 16:05:42 raspberrypi kernel: [  707.214877] smsc95xx 1-1.1:1.0: eth0: Failed to write register index 0x00000014
Dec  2 16:05:42 raspberrypi kernel: [  707.214908] smsc95xx 1-1.1:1.0: eth0: Failed to write HW_CFG_LRST_ bit in HW_CFG register, ret = -110
Dec  2 16:05:48 raspberrypi kernel: [  713.214956] smsc95xx 1-1.1:1.0: eth0: Failed to write register index 0x00000014
Dec  2 16:05:48 raspberrypi kernel: [  713.214986] smsc95xx 1-1.1:1.0: eth0: Failed to write HW_CFG_LRST_ bit in HW_CFG register, ret = -110
Dec  2 16:05:54 raspberrypi kernel: [  719.214885] smsc95xx 1-1.1:1.0: eth0: Failed to write register index 0x00000014
Dec  2 16:05:54 raspberrypi kernel: [  719.214915] smsc95xx 1-1.1:1.0: eth0: Failed to write HW_CFG_LRST_ bit in HW_CFG register, ret = -110
Dec  2 16:06:00 raspberrypi kernel: [  725.214878] smsc95xx 1-1.1:1.0: eth0: Failed to write register index 0x00000014
Dec  2 16:06:00 raspberrypi kernel: [  725.214910] smsc95xx 1-1.1:1.0: eth0: Failed to write HW_CFG_LRST_ bit in HW_CFG register, ret = -110
Dec  2 16:06:06 raspberrypi kernel: [  731.214972] smsc95xx 1-1.1:1.0: eth0: Failed to write register index 0x00000014
Dec  2 16:06:06 raspberrypi kernel: [  731.215004] smsc95xx 1-1.1:1.0: eth0: Failed to write HW_CFG_LRST_ bit in HW_CFG register, ret = -110
Dec  2 16:06:12 raspberrypi kernel: [  737.214879] smsc95xx 1-1.1:1.0: eth0: Failed to write register index 0x00000014
Dec  2 16:06:12 raspberrypi kernel: [  737.214911] smsc95xx 1-1.1:1.0: eth0: Failed to write HW_CFG_LRST_ bit in HW_CFG register, ret = -110
Dec  2 16:06:18 raspberrypi kernel: [  743.215003] smsc95xx 1-1.1:1.0: eth0: Failed to write register index 0x00000014
Dec  2 16:06:18 raspberrypi kernel: [  743.215033] smsc95xx 1-1.1:1.0: eth0: Failed to write HW_CFG_LRST_ bit in HW_CFG register, ret = -110
Dec  2 16:06:24 raspberrypi kernel: [  749.214956] smsc95xx 1-1.1:1.0: eth0: Failed to write register index 0x00000014
Dec  2 16:06:24 raspberrypi kernel: [  749.214987] smsc95xx 1-1.1:1.0: eth0: Failed to write HW_CFG_LRST_ bit in HW_CFG register, ret = -110
Dec  2 16:06:30 raspberrypi kernel: [  755.214903] smsc95xx 1-1.1:1.0: eth0: Failed to write register index 0x00000014
Dec  2 16:06:30 raspberrypi kernel: [  755.214936] smsc95xx 1-1.1:1.0: eth0: Failed to write HW_CFG_LRST_ bit in HW_CFG register, ret = -110
Dec  2 16:06:36 raspberrypi kernel: [  761.214887] smsc95xx 1-1.1:1.0: eth0: Failed to write register index 0x00000014
Dec  2 16:06:36 raspberrypi kernel: [  761.214919] smsc95xx 1-1.1:1.0: eth0: Failed to write HW_CFG_LRST_ bit in HW_CFG register, ret = -110
Dec  2 16:06:42 raspberrypi kernel: [  767.214872] smsc95xx 1-1.1:1.0: eth0: Failed to write register index 0x00000014
Dec  2 16:06:42 raspberrypi kernel: [  767.214903] smsc95xx 1-1.1:1.0: eth0: Failed to write HW_CFG_LRST_ bit in HW_CFG register, ret = -110
Dec  2 16:06:48 raspberrypi kernel: [  773.214871] smsc95xx 1-1.1:1.0: eth0: Failed to write register index 0x00000014
Dec  2 16:06:48 raspberrypi kernel: [  773.214902] smsc95xx 1-1.1:1.0: eth0: Failed to write HW_CFG_LRST_ bit in HW_CFG register, ret = -110
Dec  2 16:06:54 raspberrypi kernel: [  779.214873] smsc95xx 1-1.1:1.0: eth0: Failed to write register index 0x00000014
Dec  2 16:06:54 raspberrypi kernel: [  779.214904] smsc95xx 1-1.1:1.0: eth0: Failed to write HW_CFG_LRST_ bit in HW_CFG register, ret = -110
Dec  2 16:07:00 raspberrypi kernel: [  785.214876] smsc95xx 1-1.1:1.0: eth0: Failed to write register index 0x00000014
Dec  2 16:07:00 raspberrypi kernel: [  785.214907] smsc95xx 1-1.1:1.0: eth0: Failed to write HW_CFG_LRST_ bit in HW_CFG register, ret = -110
Dec  2 16:07:06 raspberrypi kernel: [  791.214892] smsc95xx 1-1.1:1.0: eth0: Failed to write register index 0x00000014
Dec  2 16:07:06 raspberrypi kernel: [  791.214923] smsc95xx 1-1.1:1.0: eth0: Failed to write HW_CFG_LRST_ bit in HW_CFG register, ret = -110
Dec  2 16:07:12 raspberrypi kernel: [  797.214871] smsc95xx 1-1.1:1.0: eth0: Failed to write register index 0x00000014
Dec  2 16:07:12 raspberrypi kernel: [  797.214903] smsc95xx 1-1.1:1.0: eth0: Failed to write HW_CFG_LRST_ bit in HW_CFG register, ret = -110
Dec  2 16:07:18 raspberrypi kernel: [  803.214871] smsc95xx 1-1.1:1.0: eth0: Failed to write register index 0x00000014
Dec  2 16:07:18 raspberrypi kernel: [  803.214902] smsc95xx 1-1.1:1.0: eth0: Failed to write HW_CFG_LRST_ bit in HW_CFG register, ret = -110
Dec  2 16:07:24 raspberrypi kernel: [  809.214883] smsc95xx 1-1.1:1.0: eth0: Failed to write register index 0x00000014
Dec  2 16:07:24 raspberrypi kernel: [  809.214914] smsc95xx 1-1.1:1.0: eth0: Failed to write HW_CFG_LRST_ bit in HW_CFG register, ret = -110
Dec  2 16:07:30 raspberrypi kernel: [  815.214873] smsc95xx 1-1.1:1.0: eth0: Failed to write register index 0x00000014
Dec  2 16:07:30 raspberrypi kernel: [  815.214904] smsc95xx 1-1.1:1.0: eth0: Failed to write HW_CFG_LRST_ bit in HW_CFG register, ret = -110
Dec  2 16:07:36 raspberrypi kernel: [  821.214894] smsc95xx 1-1.1:1.0: eth0: Failed to write register index 0x00000014
Dec  2 16:07:36 raspberrypi kernel: [  821.214926] smsc95xx 1-1.1:1.0: eth0: Failed to write HW_CFG_LRST_ bit in HW_CFG register, ret = -110

**Comment by ghollingworth** [comment]
Looks like this is not a linux issue
