### ISSUE TITLE
When using apt, [Y/n] prompt for installing additional packages is case sensitive

### ISSUE THREAD

**Issue by mcvittal** [raspberrypi/linux#1682]
While installing the package `fortune`, the packages `fortune-mod fortunes-min librecode0` also needed to be installed, prompting a `Do you want to continue? [Y/n]` prompt. I responded with a lower-case `y`, and it aborted. Trying again with a capital `Y` succeeded in installing. 

In my previous experience with using apt and apt-get in Ubuntu, it was never an issue to use a lower-case y when updating or installing packages. Is this a Debian-specific thing? I'm using Raspbian's version of debian jesse.

**Comment by popcornmix** [comment]
Lower case y works fine.
This repo's issue tracker is for confirmed bug reports in the linux kernel.
I'd suggest asking your question on the forum.
https://www.raspberrypi.org/forums/viewforum.php?f=66
