### ISSUE TITLE
Ruby packages from sid should be generated with ruby 2.3 instead of 2.2

### ISSUE THREAD

**Issue by OsterlaD** [raspberrypi/linux#1688]
The sid ruby packages from raspbian contains ruby 2.2 specifications path, but should be 2.3.
Here is a list of packages I have regenerated to fix this. Maybe it is not complete.
- ruby-allocations_1.0.3-1_armhf.deb
- ruby-atomic_1.1.16-2_armhf.deb
- ruby-browser_2.2.0-2_all.deb
- ruby-bson-ext_1.10.0-2_armhf.deb
- ruby-builder_3.2.2-4_all.deb
- ruby-builder-doc_3.2.2-4_all.deb
- ruby-byebug_5.0.0-1_armhf.deb
- ruby-connection-pool_2.2.0-1_all.deb
- ruby-debug-inspector_0.0.2-1.1_armhf.deb
- ruby-escape-utils_1.1.0-1_armhf.deb
- ruby-eventmachine_1.0.7-3+rpi1_armhf.deb
- ruby-ffi_1.9.10debian-1_armhf.deb
- ruby-health-check_2.2.1-2_all.deb
- ruby-hitimes_1.2.1-3_armhf.deb
- ruby-http-parser.rb_0.6.0-3_armhf.deb
- ruby-http-parser.rb-doc_0.6.0-3_all.deb
- ruby-jquery-ui-rails_5.0.5-4_all.deb
- ruby-kgio_2.10.0-1_armhf.deb
- ruby-net-ssh_3.2.0-1_all.deb
- ruby-omniauth-crowd_2.2.3-2_all.deb
- ruby-posix-spawn_0.3.11-1_armhf.deb
- ruby-select2-rails_3.5.9.3-2_all.deb
- ruby-timfel-krb5-auth_0.8.3-2_armhf.deb
- ruby-tzinfo_1.2.2-1_all.deb
- ruby-unicode_0.4.4-2_armhf.deb
- ruby-vmstat_2.2.0-2_armhf.deb
- ruby-web-console_2.2.1-2_all.deb

This will allow to compile unicorn_5.0.1-2_armhf.deb from sid, which is not yet available on raspian sid.

**Comment by popcornmix** [comment]
This repo is for the linux kernel.
If your issue is present in debian jessie then you should be reporting it to debian:
https://www.debian.org/releases/jessie/reportingbugs

if the issue is only present in raspbian jessie then report here:
https://www.raspbian.org/RaspbianBugs
or on the forum.
