### ISSUE TITLE
USB error with MCP2200 USB to Serial Converter

### ISSUE THREAD

**Issue by expeyes** [raspberrypi/linux#17]
Tried to communicate to a serial device using the MCP2200 converter. It works well if there are only 2 USB devices in total. If both keyboard and mouse are plugged in it gives error but works perfectly is only one of them are present.

The problem can be tested using an MCP2200 breakout board, like

http://dangerousprototypes.com…..b-built-6/

by shorting the Rx and Tx pins, and running the following program.

————————————————————————–

import serial, time
fd = serial.Serial('/dev/ttyACM0', 38400, stopbits=1, \
timeout = 1.0, parity=serial.PARITY_EVEN)
fd.flush()

for k in range(256):
         fd.write(chr(k))  
         time.sleep(0.01)        #some delay
         res = fd.read()
         if ord(res) != k:
                 print 'ERROR ', k, ord(res)

——————————————————————————-
The kernel error massage is:

Apr 17 14:52:11 raspberrypi kernel:
Apr 17 14:52:11 raspberrypi kernel: INFO:: periodic_channel_available: Total channels: 8, Periodic: 6, Non-periodic: 2
Apr 17 14:52:11 raspberrypi kernel:
Apr 17 14:52:11 raspberrypi kernel: INFO:: schedule_periodic: No host channel available for periodic transfer.
Apr 17 14:52:11 raspberrypi kernel:
Apr 17 14:52:11 raspberrypi kernel: ERROR::dwc_otg_hcd_urb_enqueue:487: DWC OTG HCD URB Enqueue failed adding QTD. Error status -4008

 Ajith

http://www.raspberrypi.org/forum/troubleshooting/usb-cdc-device-mcp2200-error?value=mcp2200&type=1&include=1&search=1&ret=all

**Comment by asb** [comment]
I'll also note that as suggested by @narensankar, we tried modifying dwc_otg_core_if.h to change #define dwc_param_host_channels_default from 12 to 16. This seemed to have no effect.

**Comment by ghollingworth** [comment]
This is now fixed in latest kernel
