### ISSUE TITLE
keepass2

### ISSUE THREAD

**Issue by roszel** [raspberrypi/linux#1704]
Hi guys!

I installed [keepass2](https://sourceforge.net/p/keepass/discussion/329220/thread/17d1bd26/) on my RPI 3 B (10_21_2016-Raspbian).

sudo apt-add-repository ppa:jtaylor/keepass
sudo apt-get update
sudo apt-get install keepass2

====== **I got the following Error after the start from Terminal** ===

> SendMessage (39845930, 0x112c, 0x4, 0x4)
> SendMessage (39845924, 0x101f, (nil), (nil))
> SendMessage (0, 0x1203, (nil), 0x7ec87920)
> SendMessage (0, 0x1204, (nil), 0x7ec87920)
> SendMessage (0, 0x1203, 0x1, 0x7ec87920)
> SendMessage (0, 0x1204, 0x1, 0x7ec87920)
> SendMessage (0, 0x1203, 0x2, 0x7ec87920)
> SendMessage (0, 0x1204, 0x2, 0x7ec87920)
> SendMessage (0, 0x1203, 0x3, 0x7ec87920)
> SendMessage (0, 0x1204, 0x3, 0x7ec87920)
> SendMessage (0, 0x1203, 0x4, 0x7ec87920)
> SendMessage (0, 0x1204, 0x4, 0x7ec87920)
> SendMessage (39845924, 0x101f, (nil), (nil))
> SendMessage (0, 0x1203, (nil), 0x7ec885d8)
> SendMessage (0, 0x1204, (nil), 0x7ec885d8)
> SendMessage (0, 0x1203, 0x1, 0x7ec885d8)
> SendMessage (0, 0x1204, 0x1, 0x7ec885d8)
> SendMessage (0, 0x1203, 0x2, 0x7ec885d8)
> SendMessage (0, 0x1204, 0x2, 0x7ec885d8)
> SendMessage (0, 0x1203, 0x3, 0x7ec885d8)
> SendMessage (0, 0x1204, 0x3, 0x7ec885d8)
> SendMessage (0, 0x1203, 0x4, 0x7ec885d8)
> SendMessage (0, 0x1204, 0x4, 0x7ec885d8)
> - Assertion at mini-codegen.c:807, condition `i == sel' not met
> 
> Stacktrace:
> 
>   at <unknown> <0xffffffff>
>   at System.Windows.Forms.TextBoxBase.Draw (System.Drawing.Graphics,System.Drawing.Rectangle) <0x000ab>
>   at System.Windows.Forms.TextBoxBase.OnPaintInternal (System.Windows.Forms.PaintEventArgs) <0x00063>
>   at System.Windows.Forms.Control.WmPaint (System.Windows.Forms.Message&) <0x0017f>
>   at System.Windows.Forms.Control.WndProc (System.Windows.Forms.Message&) <0x00217>
>   at System.Windows.Forms.TextBoxBase.WndProc (System.Windows.Forms.Message&) <0x00313>
>   at System.Windows.Forms.RichTextBox.WndProc (System.Windows.Forms.Message&) <0x0001b>
>   at System.Windows.Forms.Control/ControlWindowTarget.OnMessage (System.Windows.Forms.Message&) <0x0002b>
>   at System.Windows.Forms.Control/ControlNativeWindow.WndProc (System.Windows.Forms.Message&) <0x0003b>
>   at System.Windows.Forms.NativeWindow.WndProc (intptr,System.Windows.Forms.Msg,intptr,intptr) <0x002b7>
>   at System.Windows.Forms.XplatUIX11.DispatchMessage (System.Windows.Forms.MSG&) <0x00023>
>   at System.Windows.Forms.XplatUI.DispatchMessage (System.Windows.Forms.MSG&) <0x0002b>
>   at System.Windows.Forms.Application.RunLoop (bool,System.Windows.Forms.ApplicationContext) <0x00ac7>
>   at System.Windows.Forms.Application.Run (System.Windows.Forms.ApplicationContext) <0x0005f>
>   at System.Windows.Forms.Application.Run (System.Windows.Forms.Form) <0x0002b>
>   at KeePass.Program.Main (string[]) <0x00a8f>
>   at (wrapper runtime-invoke) <Module>.runtime_invoke_void_object (object,intptr,intptr,intptr) <0xffffffff>
> 
> Native stacktrace:
> 
> Debug info from gdb:
> 
> [New LWP 4768]
> [New LWP 4767]
> [New LWP 4766]
> [New LWP 4762]
> [Thread debugging using libthread_db enabled]
> Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
> 0x76df0ef8 in __libc_waitpid (Cannot access memory at address 0x3
> pid=4771, stat_loc=0x7ec87908, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:40
> 40    ../sysdeps/unix/sysv/linux/waitpid.c: No such file or directory.
>   Id   Target Id         Frame 
>   5    Thread 0x76993430 (LWP 4762) "cli" 0x76deea40 in do_futex_wait (isem=isem@entry=0x3181a4) at ../nptl/sysdeps/unix/sysv/linux/sem_wait.c:48
>   4    Thread 0x732ff430 (LWP 4766) "cli" 0x76d62830 in read () at ../sysdeps/unix/syscall-template.S:81
>   3    Thread 0x731ff430 (LWP 4767) "cli" 0x76df0730 in nanosleep () at ../sysdeps/unix/syscall-template.S:81
>   2    Thread 0x72eff430 (LWP 4768) "cli" 0x76deec50 in do_futex_timed_wait (isem=isem@entry=0x317edc, rt=rt@entry=0x72efecd8) at ../nptl/sysdeps/unix/sysv/linux/sem_timedwait.c:41
> - 1    Thread 0x76f05000 (LWP 4761) "cli" 0x76df0ef8 in __libc_waitpid (Cannot access memory at address 0x3
>   pid=4771, stat_loc=0x7ec87908, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:40
> 
> Thread 5 (Thread 0x76993430 (LWP 4762)):
> # 0  0x76deea40 in do_futex_wait (isem=isem@entry=0x3181a4) at ../nptl/sysdeps/unix/sysv/linux/sem_wait.c:48
> # 1  0x76deeaf4 in __new_sem_wait (sem=0x3181a4) at ../nptl/sysdeps/unix/sysv/linux/sem_wait.c:69
> # 2  0x00219f98 in mono_sem_wait ()
> # 3  0x0019091c in ?? ()
> 
> Backtrace stopped: previous frame identical to this frame (corrupt stack?)
> 
> Thread 4 (Thread 0x732ff430 (LWP 4766)):
> # 0  0x76d62830 in read () at ../sysdeps/unix/syscall-template.S:81
> # 1  0x7341b8c8 in ?? ()
> 
> Backtrace stopped: previous frame identical to this frame (corrupt stack?)
> 
> Thread 3 (Thread 0x731ff430 (LWP 4767)):
> # 0  0x76df0730 in nanosleep () at ../sysdeps/unix/syscall-template.S:81
> # 1  0x0020e8b0 in ?? ()
> 
> Backtrace stopped: previous frame identical to this frame (corrupt stack?)
> 
> Thread 2 (Thread 0x72eff430 (LWP 4768)):
> # 0  0x76deec50 in do_futex_timed_wait (isem=isem@entry=0x317edc, rt=rt@entry=0x72efecd8) at ../nptl/sysdeps/unix/sysv/linux/sem_timedwait.c:41
> # 1  0x76deed7c in sem_timedwait (sem=0x317edc, abstime=0x72efed1c) at ../nptl/sysdeps/unix/sysv/linux/sem_timedwait.c:96
> # 2  0x0021a08c in mono_sem_timedwait ()
> # 3  0x001790f0 in ?? ()
> 
> Backtrace stopped: previous frame identical to this frame (corrupt stack?)
> 
> Thread 1 (Thread 0x76f05000 (LWP 4761)):
> Cannot access memory at address 0x3
> # 0  0x76df0ef8 in __libc_waitpid (pid=4771, stat_loc=0x7ec87908, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:40
> # 1  0x000c0ba4 in ?? ()
> 
> Cannot access memory at address 0x3
> Backtrace stopped: previous frame identical to this frame (corrupt stack?)
> # 
> 
> Got a SIGABRT while executing native code. This usually indicates
> a fatal error in the mono runtime or one of the native libraries 
> # used by your application.
> ---

There was suggested to mention the bug on the Debian/Raspberry community

**Comment by popcornmix** [comment]
This issue tracker is for linux kernel bugs.
Your issue seems to be a bug in a user program installed from a custom repository.
I'd suggest reporting it to jtaylor or the debian issue tracker as mentioned in your linked thread.
