### ISSUE TITLE
Add iio module for htu21

### ISSUE THREAD

**Issue by TobbeJ** [raspberrypi/linux#1705]
Hi

Please consider enabling the htu21 iio kernel module for temp and humidity sensor.
module already exists in kernel but is not compiled by default.
Having it makes it much easier to access the sensors temp and humidity readings from simple shell scripts.

There might be other iio modules worth enable at the same time like accelerometer and magnetometer sensors.

**Comment by popcornmix** [comment]
Added. Try latest `rpi-update` firmware.

**Comment by JamesH65** [comment]
Closing this issue as questions answered/issue resolved.
Please update to the latest kernel which may contain a fix for this issue.
