### ISSUE TITLE
VIDEO_BCM2835/VIDEO_BCM2835_MMAL not in bcm2709_defconfig

### ISSUE THREAD

**Issue by ghost** [raspberrypi/linux#1718]
HI,

I noticed that VIDEO_BCM2835/VIDEO_BCM2835_MMAL are no longer in the default config for bcm2709 on rpi-4.9.0.  I was wondering if these drivers are being deprecated in favor of the V4L upstream drivers?

**Comment by popcornmix** [comment]
Not sure what you mean:
https://github.com/raspberrypi/linux/blob/rpi-4.9.y/arch/arm/configs/bcm2709_defconfig#L796-L797

**Comment by ghost** [comment]
I guess I just got confused.  I'll just close the issue then.
