### ISSUE TITLE
Include RTC support

### ISSUE THREAD

**Issue by klattimer** [raspberrypi/linux#172]
I'd like to propose the following kernel options get added to the raspberry pi kernel configuration;

CONFIG_RTC_LIB=y
CONFIG_RTC_CLASS=y
CONFIG_RTC_INTF_SYSFS=y
CONFIG_RTC_INTF_PROC=y
CONFIG_RTC_INTF_DEV=y
CONFIG_RTC_DRV_DS1307=m

To enable the Dallas/Maxim DS1307 RTC - this is trivial to attach to the I2C bus.

A guide for how to wire this in can be found here; http://binerry.de/post/26685647322/raspberry-pi-and-i2c

Also, I have a kickstarter project for a raspberry-pi peripheral which includes this RTC chip; http://www.kickstarter.com/projects/582604098/hotpi

**Comment by popcornmix** [comment]
I believe these options are all enabled. E.g.
zcat /proc/config.gz |grep 1307
CONFIG_RTC_DRV_DS1307=m

**Comment by klattimer** [comment]
Can you point me to a commit? I've got a slightly old version running it would appear.

**Comment by popcornmix** [comment]
https://github.com/raspberrypi/linux/commit/a915a4f6e8969a599627ca6b3e2cd7714608d222

Four months ago.
