### ISSUE TITLE
still Bluetooth TX timeout with 3.6.10

### ISSUE THREAD

**Issue by lanmarc77** [raspberrypi/linux#174]
Since forever I have my PIs the bluetooth module is crashing. This topic is discussed but still not fixed in 3.6.10. I changed to 3.6.10 in the hope the errors would be fixed. But I still get different Bluetooth: hci0 command 0x***\* tx timeout messages and the bluetooth module is not working anymore until a reboot..
I suggest that the following patch is applied, which seems to me a possible solution:
http://www.spinics.net/lists/linux-bluetooth/msg31626.html

I will gladly test it and report back after a new firmware was compiled from it.

**Comment by popcornmix** [comment]
I've added this patch to the latest "next" firmware.

**Comment by ghollingworth** [comment]
You said you'd test and report back?  Please close if happy

**Comment by lanmarc77** [comment]
I forgot about it.
Can be closed, as it seems to work for me. I had to switch bluetooth modules though. The original one broke and I had to get a new one. That was working with the patch applied from the beginning. So it might have been a faulty bluetooth module from the beginning.
