### ISSUE TITLE
reisefs kernel module

### ISSUE THREAD

**Issue by ufa** [raspberrypi/linux#1743]
Hi,
I have a bunch of old HDs with reiserfs and would like to mount them.
But it seems that the reiserfs kernel module is missing:

mount: unknown filesystem type 'reiserfs'

I searched the code and it seems it supports reiserfs, but I cannot find the module.
Any help would be much appreciated. 
Thank you for the excellent work.

**Comment by ufa** [comment]
"REISERFS (device sdb1): found reiserfs format "3.6" with standard journal"

wait what? Was it silent included?

**Comment by ufa** [comment]
Closing it

**Comment by popcornmix** [comment]
Looks to me like it's always been present.

**Comment by ufa** [comment]
Yeah, but I couldn't open any reiserfs partition at that time. The reiserfs module was not present.



Am 28. Januar 2017 10:26:43 GMT-02:00 schrieb popcornmix <notifications@github.com>:
>Looks to me like it's always been present.
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/raspberrypi/linux/issues/1743#issuecomment-275845504

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.
