### ISSUE TITLE
Pi hangs during boot on some powered USB hubs.

### ISSUE THREAD

**Issue by Ferroin** [raspberrypi/linux#175]
When powering the Raspberry Pi from a known good powered USB hub, Linux gets stuck in an infinite loop trying to get identification info from it the Pi's power cable.

Kernel is locally built from the 3.6.y branch; if needed, i can post the full config.
The hub is a D-Link DUB-H7.
This worked previously, prior to 523029f607564ab2080e83a3384feac4439b2b38.

Works fine if not powering the Pi from the hub.

**Comment by popcornmix** [comment]
The USB power cable into the Pi has no data lines, so there is no identification info.
If you say it works when powered from an external source and fails from the hub, then you need to check the voltage between TP1 and TP2. 
http://elinux.org/R-Pi_Troubleshooting#Troubleshooting_power_problems

I don't think the change in kernel version is significant. I think you have probably been underpowering the Pi and getting away with it. Possibly the kernel change has changed the timing of bootup, and you are getting a power surge (and hence a voltage drop) at a more critical time than before.

**Comment by Ferroin** [comment]
I've checked the voltages, and they appear to be fine (average 4.97 volts)
Watching the console shows a large number of messages about timeouts trying to get device ID info from the bus device that corresponds to the power cable to the PI.

**Comment by popcornmix** [comment]
Are you powering the Pi through the micro usb power socket (S1)?
Or are you back-powering it through the standard USB sockets (S7)?

**Comment by Ferroin** [comment]
Through the micro socket.

Just checked the console again, it looks like one of the two chips in the hub may be bad, the Pi is trying to talk to devices that don't exist.

**Comment by Ferroin** [comment]
Double checked without the hub; it won't boot at all, but I think that that is because the SSD that the root filesystem is on is not getting enough power.

**Comment by Ferroin** [comment]
I've double checked the hub on another system, and have determined that the problem that I was having was in the hub itself, apparently the 4-port hub IC's the device uses aren't very well designed, and long term continuous use can cause them to overheat.
