### ISSUE TITLE
Debian directory for building Debian packages

### ISSUE THREAD

**Issue by stefanberger** [raspberrypi/linux#1757]
I would like to be able to build a recent Debian package. Do you maintain a public package for the 4.8 or 4.9 kernels that contains the debian directory for building debian packages via 'debuild -us -uc'?

**Comment by popcornmix** [comment]
No. This git repo is the place to get kernel source.
We don't provide debian packages for the Pi specific kernel source.

**Comment by stefanberger** [comment]
I think I found it: mirrordirector.raspbian.org/raspbian/pool/main/l/linux/linux_4.8.7-1.debian.tar.xz

**Comment by dlech** [comment]
Creating a debian package is built into the kernel source code makefiles. You can do something like this:

    make ARCH=arm CROSS_COMPILE=/path/to/toolchain deb-pkg KDEB_PKGVERSION=1
