### ISSUE TITLE
Alacarte new item ok button permanently greyed

### ISSUE THREAD

**Issue by StuartIanNaylor** [raspberrypi/linux#1759]
Linux raspberrypi 4.4.36-v7+ #933

Happened with the last upgrade as was able to enter menu items,

Run as root or pi same and unable to add new items.

**Comment by StuartIanNaylor** [comment]
doh apologies permissions wasn't executable.

**Comment by pelwell** [comment]
In case you do find a real issue with Alacarte, you would be better off reporting it in the [raspberrypi/alacarte repo](https://github.com/raspberrypi/alacarte).

**Comment by StuartIanNaylor** [comment]
Cool apols as getting to grips with things, will do. Is there an easy way to know what has and has not its own repo ? Where you can do an overall search?

**Comment by pelwell** [comment]
[This page](https://github.com/raspberrypi/) is a reasonable place to start, combining a list of our repositories and a search tool.
