### ISSUE TITLE
LXC virtualization support

### ISSUE THREAD

**Issue by webmeister** [raspberrypi/linux#176]
Please enable support for memory cgroups in bcmrpi_defconfig which is necessary to run LXC guests:

CONFIG_CGROUP_MEM_RES_CTLR=y
CONFIG_CGROUP_MEM_RES_CTLR_SWAP=y

Starting with kernel 3.6 these options have been renamed to:

CONFIG_MEMCG=y
CONFIG_MEMCG_SWAP=y

Support for multiple instances of the devpts filesystem is not strictly required, but provides better isolation of guests, so consider enabling it as well:

CONFIG_DEVPTS_MULTIPLE_INSTANCES=y

Please also enable CONFIG_VETH=y which is necessary for libvirt to create virtual network adapters for the guests.

libvirtd/virt-manager will still complain about missing /sys/devices/system/cpu/cpu0/topology/thread_siblings and I found no way to enable this information (this might be related to a similar problem Debian saw on a different architecture: http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=649216). But after patching virt-manager to ignore these errors and use some dummy values instead it works just fine for creating and managing LXC guests.

**Comment by caglar10ur** [comment]
Supporting LXC would be a great addition to platform as it enable developers to create containers to test their work without modifying the underlying OS (like installing external packages, trying new tools) and since it can run another distribution on top of underlying distro, we no longer need to deal with multiple SD cards for using different Linux distributions.

**Comment by hvenzke** [comment]
I try top compile on 3.8.7 . from make oldconfig :

   Memory Resource Controller for Control Groups (MEMCG) [Y/n/?] y
      Memory Resource Controller Swap Extension (MEMCG_SWAP) [Y/n/?] y
        Memory Resource Controller Swap Extension enabled by default (MEMCG_SWAP_ENABLED) [Y/n/?](NEW) y
      Memory Resource Controller Kernel Memory accounting (EXPERIMENTAL) (MEMCG_KMEM) [N/y/?](NEW) y
  Enable perf_event per-cpu per-container group (cgroup) monitoring (CGROUP_PERF) [N/y/?] y

**Comment by hvenzke** [comment]
Tested successfully LXC virtualization support with kernel 3.8.7/3.8.8  works fine.

LXC docu help : http://www.greenhills.co.uk/2011/06/10/lxc.html

**Comment by caglar10ur** [comment]
Happy to report that LXC 1.0.x is working fine with 3.12.24+

**Comment by popcornmix** [comment]
@webmeister 
okay to close?

**Comment by webmeister** [comment]
All necessary config options appear to be set now.
