### ISSUE TITLE
platform.h not found

### ISSUE THREAD

**Issue by mayur-who** [raspberrypi/linux#1771]
I have written a device driver which inherently uses platform.h which is located in arch/arm/mach-bcm2709/include/mach/platform.h

but in current master branch, it is not available.

**Comment by pelwell** [comment]
What do you need from platform.h?

**Comment by mayur-who** [comment]
I use ST_BASE and GPIO_BASE #defines in my character device driver

**Comment by pelwell** [comment]
See my answer to #1772 .

**Comment by pelwell** [comment]
If you are happy with the answer to this and #1772, please close them both.

**Comment by Ruffio** [comment]
@mayurcools can this be closed?
