### ISSUE TITLE
Noob, Compiling kernel.

### ISSUE THREAD

**Issue by murray1978** [raspberrypi/linux#1786]
Is there a tutorial or file which shows how to compile the current 4.4.y kernel, what hair I had left is now on the floor.

**Comment by pelwell** [comment]
Yes: https://www.raspberrypi.org/documentation/linux/kernel/building.md

**Comment by murray1978** [comment]
Im quite sure ive tried that method before, may have missed a step, will retry.

**Comment by murray1978** [comment]
It works!!!!!

**Comment by pelwell** [comment]
Oh good. Can you close this issue then?
