### ISSUE TITLE
Bootloader UART setup

### ISSUE THREAD

**Issue by bootc** [raspberrypi/linux#18]
Could the bootloader set up the PL011 UART before it hands over to the kernel? Currently I have code in https://github.com/bootc/linux/commit/a91fe13824cde1187bb1acfdea7140c9ee0ba66c that sets up the serial port during the kernel decompression stage so that it can be used during decompression and then during early printk.

It would really be ideal if that was done outside the kernel as is more customary, and would mean you could boot compressed or uncompressed kernels and get the same behaviour.

**Comment by popcornmix** [comment]
You would like the code inside your arch_decomp_setup (5 peripheral writes) to be done by GPU before kernel starts?
Sounds okay.

**Comment by bootc** [comment]
Yep, just so the UART is good to go. Perhaps even have a config.txt option to change the baud rate if someone wants a different speed.

**Comment by popcornmix** [comment]
This link is no longer valid:
https://github.com/bootc/linux/commit/a91fe13824cde1187bb1acfdea7140c9ee0ba66c

I'd quite like to see the code in that commit.

**Comment by bootc** [comment]
Ahh sorry I had a bit of a reorganisation on github so it's moved to:
https://github.com/bootc/linux-rpi-orig/commit/a91fe13824cde1187bb1acfdea7140c9ee0ba66c

**Comment by bootc** [comment]
I should add, I will happily provide you with the generated ARM assembly if that's any help.

**Comment by popcornmix** [comment]
Can you try:
http://dl.dropbox.com/u/3669512/start.elf

which should set up UART to 115200 with a 3MHz clock as requested elsewhere. You can modify these:
CONFIG(init_uart_baud)
CONFIG(init_uart_clock)

**Comment by nomis** [comment]
This is the same start.elf from #16 and writes to the UART without prior initialisation by the kernel worked too.

**Comment by popcornmix** [comment]
Firmware now pushed to github. Please close issue if happy.

**Comment by bootc** [comment]
I haven't actually managed to test this myself yet, but Simon has and assures me it's fine. So I'll close it for now and reopen it if I run into any trouble.

Thanks!
Chris

**Comment by Stonie** [comment]
This is not working for me, please see: https://github.com/raspberrypi/linux/issues/105
