### ISSUE TITLE
Config request CONFIG_USB_NET_ZAURUS

### ISSUE THREAD

**Issue by sdjf** [raspberrypi/linux#180]
The only access I have to my Raspberry Pi is as a headless server accessed by my Zaurus PDA.  I can successfully ssh in, using the September 2012 soft float version  [Linux version 3.2.27-5-ARCH+ (nobody@fermium) (gcc version 4.7.1 20120721 (prerelease) (GCC) ) #1 PREEMPT Fri Sep 14 15:16:00 UTC 2012], but the new hard float versions seem to have had the Zaurus module removed.  Without this module, the Zaurus is seen as usb-storage instead, and I cannot get in to my Raspberry Pi.

I did try setting up ethernet but my Zaurus 2.4 kernels are too old to find viable ethernet hardware and drivers.   

I am disabled and unable to get other hardware, the zaurus module should not have been dropped, please restore it.

**Comment by popcornmix** [comment]
Seems reasonable. I'll add it in next update.

**Comment by sdjf** [comment]
Oh, thank you.  I was worried you might not want to for some reason.

**Comment by popcornmix** [comment]
Firmware updated. Use rpi-update and let me know if it worked.

**Comment by sdjf** [comment]
This is good,  I discovered that the zaurus module is also needed by some cellphones for connecting to the pi, not just zauruses.

I should explain my status.  Am running Pi totally headless and not far enough along with my setup to update yet or install the newest image on another SD card.  Have two zauruses, sl5500 binds to zaurus driver in the september arch linux arm image, it now seems that sl6000 will not due to "bad cdc descriptor", and I definitely  need to access my pi from the sl6000.

There seems to have been a bug or problem in the zaurus module for some devices that resulted in the "bad cdc descriptor" error that my sl6000 is suffering from in the older version.  Patch/code for recompiling the zaurus module is explained in following thread, is that in the module you added back in?  This stuff is way above my head.

  http://www.raspberrypi.org/phpBB3/viewtopic.php?t=6543

**Comment by licaon-kter** [comment]
This tree follows the main kernel tree + Pi specific patches, if this is a general problem (as in "it happens on a desktop too") I don't think this is the place for it but you rather need to go upstream.
