### ISSUE TITLE
List of old kernels

### ISSUE THREAD

**Issue by sabrehagen** [raspberrypi/linux#1814]
Hi all,

A list of Ubuntu's old kernels can be accessed [here](http://kernel.ubuntu.com/~kernel-ppa/mainline/). Is there an equivalent list of old kernels for raspberrypi? I'd like to download an older version than the one I'm currently using.

Thanks

**Comment by pelwell** [comment]
All the previous kernel+firmware builds are listed here: https://github.com/Hexxeh/rpi-firmware/commits/master

You can switch to any build you see there using its commit hash (use the "copy to clipboard" button to get the full 40 character hash) - just type `sudo rpi-update <hash>` to switch to that version. For example:
```
sudo rpi-update ef80bf59de8a511a61297521d51576f51f3e67aa
```
will select the first 4.4.10 build.
