### ISSUE TITLE
feature request - add slcan kernel module 

### ISSUE THREAD

**Issue by GBert** [raspberrypi/linux#1819]
Hi,

slcan is a CAN driver for SLCAN API based boards. These adapters are easy to build and cheap - [like this](https://github.com/GBert/misc/tree/master/stm32-slcan). 
Would you be so kind to add slcan to the standard Raspbian distribution ? The slcan kernel module only consumes a few kbytes (roughly 15kByte) disc space.

Thx in advance
Gerd

**Comment by 6by9** [comment]
Is it just ```CONFIG_CAN_SLCAN=m``` that you want, or other options?

**Comment by GBert** [comment]
` CONFIG_CAN_SLCAN=m` -> yes, that's it. And distribute the slcan.ko with the Raspbian release, of course ;-)

**Comment by popcornmix** [comment]
This has been added and is in latest rpi-update kernel.

**Comment by Ruffio** [comment]
@GBert  so this issue can be closed now?

**Comment by GBert** [comment]
Many Thx !

**Comment by GBert** [comment]
slcan is missing again:
pi@raspberrypi:/lib/modules/4.9.11-v7+ $ find ./ -name slcan.ko
pi@raspberrypi:/lib/modules/4.9.11-v7+ $

**Comment by pelwell** [comment]
That commit got dropped in the move to 4.9, but it's back in now and will be in the next build.

**Comment by GBert** [comment]
Thx - it's back !

**Comment by alejandro-amo** [comment]
just for the record: 4.4.21 (newest jessie kernel available at the time of this writing) is still missing slcan module. in this case, apt-get dist-upgrade required in order to get a new version of raspbian and hence getting 4.9.35+
