### ISSUE TITLE
config request CONFIG_NETFILTER_NETLINK_LOG

### ISSUE THREAD

**Issue by dorchain** [raspberrypi/linux#182]
Hello,

I want to have a simple firewall with some logging to syslog. 

Can you please add the module for xt_LOG by adding CONFIG_NETFILTER_NETLINK_LOG=m?

ulogd is not appropriate for me as
- Yet another daemon staying im memory when is it scarce already
- The version in wheezy lacks the SYSLOG plugin and to bug report about it has not changed for long
- The workarounds will eat up much more memory than just the module

Beside almost any other netfilter related module is there, so I assume it was just overlooked.

Thanks for including it.

Bye,

Joerg

**Comment by popcornmix** [comment]
This is included in recent firmwares:
https://github.com/raspberrypi/linux/commit/44a00b02a67d1e94e44ea9654d71fa0351dbcbb9

**Comment by dorchain** [comment]
Thanks a lot, works perfectly :-)
