### ISSUE TITLE
Can't install esp8089 with raspbian jessie pixel?

### ISSUE THREAD

**Issue by czarina** [raspberrypi/linux#1821]
I'm trying to install ESP8089 driver to the jessie pixel: https://github.com/al177/esp8089

But I get:

"Makefile:19: *** No .config found in /lib/modules/4.4.34/build, please set KBUILD to configured kernel.  Stop."

It says in Makefile that ''KBUILD is the path to the Linux kernel build tree''

Has this changed location in the recent Raspbian? I can't find a .config file anywhere in /lib/modules/4.4.34 and there is no 'build' folder. 

Can anyone point me to the path or how else to install ESP8089?

**Comment by pelwell** [comment]
You've already reported this in the correct place: https://github.com/al177/esp8089/issues/7

You could try asking in the Raspberry Pi forums, but this isn't the correct place to ask for general support like this.
