### ISSUE TITLE
Avahi: auto-rename stalls ZeroConf registration

### ISSUE THREAD

**Issue by jeremybernstein** [raspberrypi/linux#1831]
When registering a service which shares the name with an already-running mdns service (in my case, on another machine on the local network), DNSServiceRegister() returns immediately with an error code of 0, but doesn't call the registration callback.

```
DNSServiceErrorType error;

error = DNSServiceRegister(&_serviceRef,
		   0, // no flags
		   0, // all network interfaces
		   "NameInUse", // name,
		   "_test._tcp", // service type
		   NULL, // register in default domain(s)
		   NULL, // use default host name
		   htons(1234), // port number
		   0, // length of TXT record
		   NULL, // no TXT record
		   RegistrationCallback, // This won't get called
		   NULL); // no context

```

In fact, the name should be decorated (e.g. "NameInUse (2)") and everything should work as expected. Currently, the RasPi-hosted service won't appear in my ZeroConf Browser until the already-running service is exited. I could not find Debian or Raspberry Pi bugs referencing this issue.

**Comment by popcornmix** [comment]
This repo is for the linux kernel. Your issue won't be a kernel issue.
I'd suggest posting in the forum to see if anyone can offer advice.
Otherwise the debian bug tracker may be a better place:
https://www.debian.org/Bugs/Reporting
