### ISSUE TITLE
zip file has extract error (tried twice!)

### ISSUE THREAD

**Issue by genewitch** [raspberrypi/linux#184]
here's the tail of the console output. It tries to symlink the contents of a file to a file, i think? No idea how to repair this on my side so i am doing a clone :-(

  inflating: linux-rpi-3.6.y/virt/kvm/async_pf.h  
  inflating: linux-rpi-3.6.y/virt/kvm/coalesced_mmio.c  
  inflating: linux-rpi-3.6.y/virt/kvm/coalesced_mmio.h  
  inflating: linux-rpi-3.6.y/virt/kvm/eventfd.c  
  inflating: linux-rpi-3.6.y/virt/kvm/ioapic.c  
  inflating: linux-rpi-3.6.y/virt/kvm/ioapic.h  
  inflating: linux-rpi-3.6.y/virt/kvm/iodev.h  
  inflating: linux-rpi-3.6.y/virt/kvm/iommu.c  
  inflating: linux-rpi-3.6.y/virt/kvm/irq_comm.c  
  inflating: linux-rpi-3.6.y/virt/kvm/kvm_main.c  
finishing deferred symbolic links:
  linux-rpi-3.6.y/arch/microblaze/boot/dts/system.dts -> ../../platform/generic/system.dts
  linux-rpi-3.6.y/drivers/net/wireless/hostap/hostap_common.h -> #ifndef HOSTAP_COMMON_H^J#define HOSTAP_COMMON_H^J^J#include <linux/types.h>^J#include <linux/if_ether.h>^J^J/\* IEEE 802.11 defines _/^J^J/_ HFA384X Configuration RIDs _/^J#define HFA384X_RID_CNFPORTTYPE 0xFC00^J#define HFA384X_RID_CNFOWNMACADDR 0xFC01^J#define HFA384X_RID_CNFDESIREDSSID 0xFC02^J#define HFA384X_RID_CNFOWNCHANNEL 0xFC03^J#define HFA384X_RID_CNFOWNSSID 0xFC04^J#define HFA384X_RID_CNFOWNATIMWINDOW 0xFC05^J#define HFA384X_RID_CNFSYSTEMSCALE 0xFC06^J#define HFA384X_RID_CNFMAXDATALEN 0xFC07^J#define HFA384X_RID_CNFWDSADDRESS 0xFC08^J#define HFA384X_RID_CNFPMENABLED 0xFC09^J#define HFA384X_RID_CNFPMEPS 0xFC0A^J#define HFA384X_RID_CNFMULTICASTRECEIVE 0xFC0B^J#define HFA384X_RID_CNFMAXSLEEPDURATION 0xFC0C^J#define HFA384X_RID_CNFPMHOLDOVERDURATION 0xFC0D^J#define HFA384X_RID_CNFOWNNAME 0xFC0E^J#define HFA384X_RID_CNFOWNDTIMPERIOD 0xFC10^J#define HFA384X_RID_CNFWDSADDRESS1 0xFC11 /_ AP f/w only _/^J#define HFA384X_RID_CNFWDSADDRESS2 0xFC12 /_ AP f/w only _/^J#define HFA384X_RID_CNFWDSADDRESS3 0xFC13 /_ AP f/w only _/^J#define HFA384X_RID_CNFWDSADDRESS4 0xFC14 /_ AP f/w only _/^J#define HFA384X_RID_CNFWDSADDRESS5 0xFC15 /_ AP f/w only _/^J#define HFA384X_RID_CNFWDSADDRESS6 0xFC16 /_ AP f/w only _/^J#define HFA384X_RID_CNFMULTICASTPMBUFFERING 0xFC17 /_ AP f/w only _/^J#define HFA384X_RID_UNKNOWN1 0xFC20^J#define HFA384X_RID_UNKNOWN2 0xFC21^J#define HFA384X_RID_CNFWEPDEFAULTKEYID 0xFC23^J#define HFA384X_RID_CNFDEFAULTKEY0 0xFC24^J#define HFA384X_RID_CNFDEFAULTKEY1 0xFC25^J#define HFA384X_RID_CNFDEFAULTKEY2 0xFC26^J#define HFA384X_RID_CNFDEFAULTKEY3 0xFC27^J#define HFA384X_RID_CNFWEPFLAGS 0xFC28^J#define HFA384X_RID_CNFWEPKEYMAPPINGTABLE 0xFC29^J#define HFA384X_RID_CNFAUTHENTICATION 0xFC2A^J#define HFA384X_RID_CNFMAXASSOCSTA 0xFC2B /_ AP f/w only _/^J#define HFA384X_RID_CNFTXCONTROL 0xFC2C^J#define HFA384X_RID_CNFROAMINGMODE 0xFC2D^J#define HFA384X_RID_CNFHOSTAUTHENTICATION 0xFC2E /_ AP f/w only _/^J#define HFA384X_RID_CNFRCVCRCERROR 0xFC30^J#define HFA384X_RID_CNFMMLIFE 0xFC31^J#define HFA384X_RID_CNFALTRETRYCOUNT 0xFC32^J#define HFA384X_RID_CNFBEACONINT 0xFC33^J#define HFA384X_RID_CNFAPPCFINFO 0xFC34 /_ AP f/w only _/^J#define HFA384X_RID_CNFSTAPCFINFO 0xFC35^J#define HFA384X_RID_CNFPRIORITYQUSAGE 0xFC37^J#define HFA384X_RID_CNFTIMCTRL 0xFC40^J#define HFA384X_RID_UNKNOWN3 0xFC41 /_ added in STA f/w 0.7.x _/^J#define HFA384X_RID_CNFTHIRTY2TALLY 0xFC42 /_ added in STA f/w 0.8.0 _/^J#define HFA384X_RID_CNFENHSECURITY 0xFC43 /_ AP f/w or STA f/w >= 1.6.3 _/^J#define HFA384X_RID_CNFDBMADJUST 0xFC46 /_ added in STA f/w 1.3.1 _/^J#define HFA384X_RID_GENERICELEMENT 0xFC48 /_ added in STA f/w 1.7.0;^J^I^I^I^I^I   \* write only _/^J#define HFA384X_RID_PROPAGATIONDELAY 0xFC49 /_ added in STA f/w 1.7.6 _/^J#define HFA384X_RID_GROUPADDRESSES 0xFC80^J#define HFA384X_RID_CREATEIBSS 0xFC81^J#define HFA384X_RID_FRAGMENTATIONTHRESHOLD 0xFC82^J#define HFA384X_RID_RTSTHRESHOLD 0xFC83^J#define HFA384X_RID_TXRATECONTROL 0xFC84^J#define HFA384X_RID_PROMISCUOUSMODE 0xFC85^J#define HFA384X_RID_FRAGMENTATIONTHRESHOLD0 0xFC90 /_ AP f/w only _/^J#define HFA384X_RID_FRAGMENTATIONTHRESHOLD1 0xFC91 /_ AP f/w only _/^J#define HFA384X_RID_FRAGMENTATIONTHRESHOLD2 0xFC92 /_ AP f/w only _/^J#define HFA384X_RID_FRAGMENTATIONTHRESHOLD3 0xFC93 /_ AP f/w only _/^J#define HFA384X_RID_FRAGMENTATIONTHRESHOLD4 0xFC94 /_ AP f/w only _/^J#define HFA384X_RID_FRAGMENTATIONTHRESHOLD5 0xFC95 /_ AP f/w only _/^J#define HFA384X_RID_FRAGMENTATIONTHRESHOLD6 0xFC96 /_ AP f/w only _/^J#define HFA384X_RID_RTSTHRESHOLD0 0xFC97 /_ AP f/w only _/^J#define HFA384X_RID_RTSTHRESHOLD1 0xFC98 /_ AP f/w only _/^J#define HFA384X_RID_RTSTHRESHOLD2 0xFC99 /_ AP f/w only _/^J#define HFA384X_RID_RTSTHRESHOLD3 0xFC9A /_ AP f/w only _/^J#define HFA384X_RID_RTSTHRESHOLD4 0xFC9B /_ AP f/w only _/^J#define HFA384X_RID_RTSTHRESHOLD5 0xFC9C /_ AP f/w only _/^J#define HFA384X_RID_RTSTHRESHOLD6 0xFC9D /_ AP f/w only _/^J#define HFA384X_RID_TXRATECONTROL0 0xFC9E /_ AP f/w only _/^J#define HFA384X_RID_TXRATECONTROL1 0xFC9F /_ AP f/w only _/^J#define HFA384X_RID_TXRATECONTROL2 0xFCA0 /_ AP f/w only _/^J#define HFA384X_RID_TXRATECONTROL3 0xFCA1 /_ AP f/w only _/^J#define HFA384X_RID_TXRATECONTROL4 0xFCA2 /_ AP f/w only _/^J#define HFA384X_RID_TXRATECONTROL5 0xFCA3 /_ AP f/w only _/^J#define HFA384X_RID_TXRATECONTROL6 0xFCA4 /_ AP f/w only _/^J#define HFA384X_RID_CNFSHORTPREAMBLE 0xFCB0^J#define HFA384X_RID_CNFEXCLUDELONGPREAMBLE 0xFCB1^J#define HFA384X_RID_CNFAUTHENTICATIONRSPTO 0xFCB2^J#define HFA384X_RID_CNFBASICRATES 0xFCB3^J#define HFA384X_RID_CNFSUPPORTEDRATES 0xFCB4^J#define HFA384X_RID_CNFFALLBACKCTRL 0xFCB5 /_ added in STA f/w 1.3.1 _/^J#define HFA384X_RID_WEPKEYDISABLE 0xFCB6 /_ added in STA f/w 1.3.1 _/^J#define HFA384X_RID_WEPKEYMAPINDEX 0xFCB7 /_ ? _/^J#define HFA384X_RID_BROADCASTKEYID 0xFCB8 /_ ? _/^J#define HFA384X_RID_ENTSECFLAGEYID 0xFCB9 /_ ? _/^J#define HFA384X_RID_CNFPASSIVESCANCTRL 0xFCBA /_ added in STA f/w 1.5.0 _/^J#define HFA384X_RID_SSNHANDLINGMODE 0xFCBB /_ added in STA f/w 1.7.0 _/^J#define HFA384X_RID_MDCCONTROL 0xFCBC /_ added in STA f/w 1.7.0 _/^J#define HFA384X_RID_MDCCOUNTRY 0xFCBD /_ added in STA f/w 1.7.0 _/^J#define HFA384X_RID_TXPOWERMAX 0xFCBE /_ added in STA f/w 1.7.0 _/^J#define HFA384X_RID_CNFLFOENABLED 0xFCBF /_ added in STA f/w 1.6.3 _/^J#define HFA384X_RID_CAPINFO 0xFCC0 /_ added in STA f/w 1.7.0 _/^J#define HFA384X_RID_LISTENINTERVAL 0xFCC1 /_ added in STA f/w 1.7.0 _/^J#define HFA384X_RID_SW_ANT_DIV 0xFCC2 /_ added in STA f/w 1.7.0; Prism3 _/^J#define HFA384X_RID_LED_CTRL 0xFCC4 /_ added in STA f/w 1.7.6 _/^J#define HFA384X_RID_HFODELAY 0xFCC5 /_ added in STA f/w 1.7.6 _/^J#define HFA384X_RID_DISALLOWEDBSSID 0xFCC6 /_ added in STA f/w 1.8.0 _/^J#define HFA384X_RID_TICKTIME 0xFCE0^J#define HFA384X_RID_SCANREQUEST 0xFCE1^J#define HFA384X_RID_JOINREQUEST 0xFCE2^J#define HFA384X_RID_AUTHENTICATESTATION 0xFCE3 /_ AP f/w only _/^J#define HFA384X_RID_CHANNELINFOREQUEST 0xFCE4 /_ AP f/w only _/^J#define HFA384X_RID_HOSTSCAN 0xFCE5 /_ added in STA f/w 1.3.1 _/^J^J/_ HFA384X Information RIDs _/^J#define HFA384X_RID_MAXLOADTIME 0xFD00^J#define HFA384X_RID_DOWNLOADBUFFER 0xFD01^J#define HFA384X_RID_PRIID 0xFD02^J#define HFA384X_RID_PRISUPRANGE 0xFD03^J#define HFA384X_RID_CFIACTRANGES 0xFD04^J#define HFA384X_RID_NICSERNUM 0xFD0A^J#define HFA384X_RID_NICID 0xFD0B^J#define HFA384X_RID_MFISUPRANGE 0xFD0C^J#define HFA384X_RID_CFISUPRANGE 0xFD0D^J#define HFA384X_RID_CHANNELLIST 0xFD10^J#define HFA384X_RID_REGULATORYDOMAINS 0xFD11^J#define HFA384X_RID_TEMPTYPE 0xFD12^J#define HFA384X_RID_CIS 0xFD13^J#define HFA384X_RID_STAID 0xFD20^J#define HFA384X_RID_STASUPRANGE 0xFD21^J#define HFA384X_RID_MFIACTRANGES 0xFD22^J#define HFA384X_RID_CFIACTRANGES2 0xFD23^J#define HFA384X_RID_PRODUCTNAME 0xFD24 /_ added in STA f/w 1.3.1;^J^I^I^I^I^I\* only Prism2.5(?) _/^J#define HFA384X_RID_PORTSTATUS 0xFD40^J#define HFA384X_RID_CURRENTSSID 0xFD41^J#define HFA384X_RID_CURRENTBSSID 0xFD42^J#define HFA384X_RID_COMMSQUALITY 0xFD43^J#define HFA384X_RID_CURRENTTXRATE 0xFD44^J#define HFA384X_RID_CURRENTBEACONINTERVAL 0xFD45^J#define HFA384X_RID_CURRENTSCALETHRESHOLDS 0xFD46^J#define HFA384X_RID_PROTOCOLRSPTIME 0xFD47^J#define HFA384X_RID_SHORTRETRYLIMIT 0xFD48^J#define HFA384X_RID_LONGRETRYLIMIT 0xFD49^J#define HFA384X_RID_MAXTRANSMITLIFETIME 0xFD4A^J#define HFA384X_RID_MAXRECEIVELIFETIME 0xFD4B^J#define HFA384X_RID_CFPOLLABLE 0xFD4C^J#define HFA384X_RID_AUTHENTICATIONALGORITHMS 0xFD4D^J#define HFA384X_RID_PRIVACYOPTIONIMPLEMENTED 0xFD4F^J#define HFA384X_RID_DBMCOMMSQUALITY 0xFD51 /_ added in STA f/w 1.3.1 _/^J#define HFA384X_RID_CURRENTTXRATE1 0xFD80 /_ AP f/w only _/^J#define HFA384X_RID_CURRENTTXRATE2 0xFD81 /_ AP f/w only _/^J#define HFA384X_RID_CURRENTTXRATE3 0xFD82 /_ AP f/w only _/^J#define HFA384X_RID_CURRENTTXRATE4 0xFD83 /_ AP f/w only _/^J#define HFA384X_RID_CURRENTTXRATE5 0xFD84 /_ AP f/w only _/^J#define HFA384X_RID_CURRENTTXRATE6 0xFD85 /_ AP f/w only _/^J#define HFA384X_RID_OWNMACADDR 0xFD86 /_ AP f/w only _/^J#define HFA384X_RID_SCANRESULTSTABLE 0xFD88 /_ added in STA f/w 0.8.3 _/^J#define HFA384X_RID_HOSTSCANRESULTS 0xFD89 /_ added in STA f/w 1.3.1 _/^J#define HFA384X_RID_AUTHENTICATIONUSED 0xFD8A /_ added in STA f/w 1.3.4 _/^J#define HFA384X_RID_CNFFAASWITCHCTRL 0xFD8B /_ added in STA f/w 1.6.3 _/^J#define HFA384X_RID_ASSOCIATIONFAILURE 0xFD8D /_ added in STA f/w 1.8.0 _/^J#define HFA384X_RID_PHYTYPE 0xFDC0^J#define HFA384X_RID_CURRENTCHANNEL 0xFDC1^J#define HFA384X_RID_CURRENTPOWERSTATE 0xFDC2^J#define HFA384X_RID_CCAMODE 0xFDC3^J#define HFA384X_RID_SUPPORTEDDATARATES 0xFDC6^J#define HFA384X_RID_LFO_VOLT_REG_TEST_RES 0xFDC7 /_ added in STA f/w 1.7.1 _/^J#define HFA384X_RID_BUILDSEQ 0xFFFE^J#define HFA384X_RID_FWID 0xFFFF^J^J^Jstruct hfa384x_comp_ident^J{^J^I__le16 id;^J^I__le16 variant;^J^I__le16 major;^J^I__le16 minor;^J} __packed;^J^J#define HFA384X_COMP_ID_PRI 0x15^J#define HFA384X_COMP_ID_STA 0x1f^J#define HFA384X_COMP_ID_FW_AP 0x14b^J^Jstruct hfa384x_sup_range^J{^J^I__le16 role;^J^I__le16 id;^J^I__le16 variant;^J^I__le16 bottom;^J^I__le16 top;^J} __packed;^J^J^Jstruct hfa384x_build_id^J{^J^I__le16 pri_seq;^J^I__le16 sec_seq;^J} __packed;^J^J/_ FD01 - Download Buffer _/^Jstruct hfa384x_rid_download_buffer^J{^J^I__le16 page;^J^I__le16 offset;^J^I__le16 length;^J} __packed;^J^J/_ BSS connection quality (RID FD43 range, RID FD51 dBm-normalized) _/^Jstruct hfa384x_comms_quality {^J^I__le16 comm_qual; /_ 0 .. 92 _/^J^I__le16 signal_level; /_ 27 .. 154 _/^J^I__le16 noise_level; /_ 27 .. 154 _/^J} __packed;^J^J^J/_ netdevice private ioctls (used, e.g., with iwpriv from user space) _/^J^J/_ New wireless extensions API - SET/GET convention (even ioctl numbers are^J \* root only)^J _/^J#define PRISM2_IOCTL_PRISM2_PARAM (SIOCIWFIRSTPRIV + 0)^J#define PRISM2_IOCTL_GET_PRISM2_PARAM (SIOCIWFIRSTPRIV + 1)^J#define PRISM2_IOCTL_WRITEMIF (SIOCIWFIRSTPRIV + 2)^J#define PRISM2_IOCTL_READMIF (SIOCIWFIRSTPRIV + 3)^J#define PRISM2_IOCTL_MONITOR (SIOCIWFIRSTPRIV + 4)^J#define PRISM2_IOCTL_RESET (SIOCIWFIRSTPRIV + 6)^J#define PRISM2_IOCTL_INQUIRE (SIOCIWFIRSTPRIV + 8)^J#define PRISM2_IOCTL_WDS_ADD (SIOCIWFIRSTPRIV + 10)^J#define PRISM2_IOCTL_WDS_DEL (SIOCIWFIRSTPRIV + 12)^J#define PRISM2_IOCTL_SET_RID_WORD (SIOCIWFIRSTPRIV + 14)^J#define PRISM2_IOCTL_MACCMD (SIOCIWFIRSTPRIV + 16)^J#define PRISM2_IOCTL_ADDMAC (SIOCIWFIRSTPRIV + 18)^J#define PRISM2_IOCTL_DELMAC (SIOCIWFIRSTPRIV + 20)^J#define PRISM2_IOCTL_KICKMAC (SIOCIWFIRSTPRIV + 22)^J^J/_ following are not in SIOCGIWPRIV list; check permission in the driver code^J _/^J#define PRISM2_IOCTL_DOWNLOAD (SIOCDEVPRIVATE + 13)^J#define PRISM2_IOCTL_HOSTAPD (SIOCDEVPRIVATE + 14)^J^J^J/_ PRISM2_IOCTL_PRISM2_PARAM ioctl() subtypes: _/^Jenum {^J^I/_ PRISM2_PARAM_PTYPE = 1, _/ /_ REMOVED 2003-10-22 _/^J^IPRISM2_PARAM_TXRATECTRL = 2,^J^IPRISM2_PARAM_BEACON_INT = 3,^J^IPRISM2_PARAM_PSEUDO_IBSS = 4,^J^IPRISM2_PARAM_ALC = 5,^J^I/_ PRISM2_PARAM_TXPOWER = 6, _/ /_ REMOVED 2003-10-22 _/^J^IPRISM2_PARAM_DUMP = 7,^J^IPRISM2_PARAM_OTHER_AP_POLICY = 8,^J^IPRISM2_PARAM_AP_MAX_INACTIVITY = 9,^J^IPRISM2_PARAM_AP_BRIDGE_PACKETS = 10,^J^IPRISM2_PARAM_DTIM_PERIOD = 11,^J^IPRISM2_PARAM_AP_NULLFUNC_ACK = 12,^J^IPRISM2_PARAM_MAX_WDS = 13,^J^IPRISM2_PARAM_AP_AUTOM_AP_WDS = 14,^J^IPRISM2_PARAM_AP_AUTH_ALGS = 15,^J^IPRISM2_PARAM_MONITOR_ALLOW_FCSERR = 16,^J^IPRISM2_PARAM_HOST_ENCRYPT = 17,^J^IPRISM2_PARAM_HOST_DECRYPT = 18,^J^I/_ PRISM2_PARAM_BUS_MASTER_THRESHOLD_RX = 19, REMOVED 2005-08-14 _/^J^I/_ PRISM2_PARAM_BUS_MASTER_THRESHOLD_TX = 20, REMOVED 2005-08-14 _/^J^IPRISM2_PARAM_HOST_ROAMING = 21,^J^IPRISM2_PARAM_BCRX_STA_KEY = 22,^J^IPRISM2_PARAM_IEEE_802_1X = 23,^J^IPRISM2_PARAM_ANTSEL_TX = 24,^J^IPRISM2_PARAM_ANTSEL_RX = 25,^J^IPRISM2_PARAM_MONITOR_TYPE = 26,^J^IPRISM2_PARAM_WDS_TYPE = 27,^J^IPRISM2_PARAM_HOSTSCAN = 28,^J^IPRISM2_PARAM_AP_SCAN = 29,^J^IPRISM2_PARAM_ENH_SEC = 30,^J^IPRISM2_PARAM_IO_DEBUG = 31,^J^IPRISM2_PARAM_BASIC_RATES = 32,^J^IPRISM2_PARAM_OPER_RATES = 33,^J^IPRISM2_PARAM_HOSTAPD = 34,^J^IPRISM2_PARAM_HOSTAPD_STA = 35,^J^IPRISM2_PARAM_WPA = 36,^J^IPRISM2_PARAM_PRIVACY_INVOKED = 37,^J^IPRISM2_PARAM_TKIP_COUNTERMEASURES = 38,^J^IPRISM2_PARAM_DROP_UNENCRYPTED = 39,^J^IPRISM2_PARAM_SCAN_CHANNEL_MASK = 40,^J};^J^Jenum { HOSTAP_ANTSEL_DO_NOT_TOUCH = 0, HOSTAP_ANTSEL_DIVERSITY = 1,^J       HOSTAP_ANTSEL_LOW = 2, HOSTAP_ANTSEL_HIGH = 3 };^J^J^J/_ PRISM2_IOCTL_MACCMD ioctl() subcommands: _/^Jenum { AP_MAC_CMD_POLICY_OPEN = 0, AP_MAC_CMD_POLICY_ALLOW = 1,^J       AP_MAC_CMD_POLICY_DENY = 2, AP_MAC_CMD_FLUSH = 3,^J       AP_MAC_CMD_KICKALL = 4 };^J^J^J/_ PRISM2_IOCTL_DOWNLOAD ioctl() dl_cmd: _/^Jenum {^J^IPRISM2_DOWNLOAD_VOLATILE = 1 /_ RAM _/,^J^I/_ Note! Old versions of prism2_srec have a fatal error in CRC-16^J^I \* calculation, which will corrupt all non-volatile downloads.^J^I \* PRISM2_DOWNLOAD_NON_VOLATILE used to be 2, but it is now 3 to^J^I \* prevent use of old versions of prism2_srec for non-volatile^J^I \* download. _/^J^IPRISM2_DOWNLOAD_NON_VOLATILE = 3 /_ FLASH _/,^J^IPRISM2_DOWNLOAD_VOLATILE_GENESIS = 4 /_ RAM in Genesis mode _/,^J^I/_ Persistent versions of volatile download commands (keep firmware^J^I \* data in memory and automatically re-download after hw_reset _/^J^IPRISM2_DOWNLOAD_VOLATILE_PERSISTENT = 5,^J^IPRISM2_DOWNLOAD_VOLATILE_GENESIS_PERSISTENT = 6,^J};^J^Jstruct prism2_download_param {^J^Iu32 dl_cmd;^J^Iu32 start_addr;^J^Iu32 num_areas;^J^Istruct prism2_download_area {^J^I^Iu32 addr; /_ wlan card address _/^J^I^Iu32 len;^J^I^Ivoid __user *ptr; /_ pointer to data in user space _/^J^I} data[0];^J};^J^J#define PRISM2_MAX_DOWNLOAD_AREA_LEN 131072^J#define PRISM2_MAX_DOWNLOAD_LEN 262144^J^J^J/_ PRISM2_IOCTL_HOSTAPD ioctl() cmd: _/^Jenum {^J^IPRISM2_HOSTAPD_FLUSH = 1,^J^IPRISM2_HOSTAPD_ADD_STA = 2,^J^IPRISM2_HOSTAPD_REMOVE_STA = 3,^J^IPRISM2_HOSTAPD_GET_INFO_STA = 4,^J^I/_ REMOVED: PRISM2_HOSTAPD_RESET_TXEXC_STA = 5, _/^J^IPRISM2_SET_ENCRYPTION = 6,^J^IPRISM2_GET_ENCRYPTION = 7,^J^IPRISM2_HOSTAPD_SET_FLAGS_STA = 8,^J^IPRISM2_HOSTAPD_GET_RID = 9,^J^IPRISM2_HOSTAPD_SET_RID = 10,^J^IPRISM2_HOSTAPD_SET_ASSOC_AP_ADDR = 11,^J^IPRISM2_HOSTAPD_SET_GENERIC_ELEMENT = 12,^J^IPRISM2_HOSTAPD_MLME = 13,^J^IPRISM2_HOSTAPD_SCAN_REQ = 14,^J^IPRISM2_HOSTAPD_STA_CLEAR_STATS = 15,^J};^J^J#define PRISM2_HOSTAPD_MAX_BUF_SIZE 1024^J#define PRISM2_HOSTAPD_RID_HDR_LEN ^Joffsetof(struct prism2_hostapd_param, u.rid.data)^J#define PRISM2_HOSTAPD_GENERIC_ELEMENT_HDR_LEN ^Joffsetof(struct prism2_hostapd_param, u.generic_elem.data)^J^J/_ Maximum length for algorithm names (-1 for nul termination) used in ioctl()^J _/^J#define HOSTAP_CRYPT_ALG_NAME_LEN 16^J^J^Jstruct prism2_hostapd_param {^J^Iu32 cmd;^J^Iu8 sta_addr[ETH_ALEN];^J^Iunion {^J^I^Istruct {^J^I^I^Iu16 aid;^J^I^I^Iu16 capability;^J^I^I^Iu8 tx_supp_rates;^J^I^I} add_sta;^J^I^Istruct {^J^I^I^Iu32 inactive_sec;^J^I^I} get_info_sta;^J^I^Istruct {^J^I^I^Iu8 alg[HOSTAP_CRYPT_ALG_NAME_LEN];^J^I^I^Iu32 flags;^J^I^I^Iu32 err;^J^I^I^Iu8 idx;^J^I^I^Iu8 seq[8]; /_ sequence counter (set: RX, get: TX) _/^J^I^I^Iu16 key_len;^J^I^I^Iu8 key[0];^J^I^I} crypt;^J^I^Istruct {^J^I^I^Iu32 flags_and;^J^I^I^Iu32 flags_or;^J^I^I} set_flags_sta;^J^I^Istruct {^J^I^I^Iu16 rid;^J^I^I^Iu16 len;^J^I^I^Iu8 data[0];^J^I^I} rid;^J^I^Istruct {^J^I^I^Iu8 len;^J^I^I^Iu8 data[0];^J^I^I} generic_elem;^J^I^Istruct {^J#define MLME_STA_DEAUTH 0^J#define MLME_STA_DISASSOC 1^J^I^I^Iu16 cmd;^J^I^I^Iu16 reason_code;^J^I^I} mlme;^J^I^Istruct {^J^I^I^Iu8 ssid_len;^J^I^I^Iu8 ssid[32];^J^I^I} scan_req;^J^I} u;^J};^J^J#define HOSTAP_CRYPT_FLAG_SET_TX_KEY BIT(0)^J#define HOSTAP_CRYPT_FLAG_PERMANENT BIT(1)^J^J#define HOSTAP_CRYPT_ERR_UNKNOWN_ALG 2^J#define HOSTAP_CRYPT_ERR_UNKNOWN_ADDR 3^J#define HOSTAP_CRYPT_ERR_CRYPT_INIT_FAILED 4^J#define HOSTAP_CRYPT_ERR_KEY_SET_FAILED 5^J#define HOSTAP_CRYPT_ERR_TX_KEY_SET_FAILED 6^J#define HOSTAP_CRYPT_ERR_CARD_CONF_FAILED 7^J^J^J#endif /_ HOSTAP_COMMON_H */^J
symlink error: File name too long

**Comment by gamaral** [comment]
That might be github's fault, why don't you try the tar.gz?

**Comment by genewitch** [comment]
I got it working with a clone, i was just alerting someone to the presence of this error.

**Comment by popcornmix** [comment]
Just a limitation of zip files. I imagine you would get the same result from:
https://github.com/torvalds/linux

You can download the tar.gz file from:
https://github.com/raspberrypi/linux/tarball/master
(which will extract correctly) or use git clone.
