### ISSUE TITLE
Upgrade failure

### ISSUE THREAD

**Issue by rch33** [raspberrypi/linux#1848]
I have tried several times but "apt-get upgrade" always fails. This is after reboot, update, autoclean and autoremove (which also fails). The worst part of this is that my Rpi is now missing the important block devices -- namely /dev/sda*. Is there any fix or will I have to clone another Rpi's SD card?

Here's the end of the upgrade text:
Do you want to continue [Y/n]? Y
Setting up rsyslog (5.8.11-3+deb7u2) ...
insserv: Service ramlog has to be enabled to start service rsyslog
insserv: exiting now!
update-rc.d: error: insserv rejected the script header
dpkg: error processing rsyslog (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 rsyslog
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by popcornmix** [comment]
This repo is for the linux kernel.
Your issue seems to be a distribution (raspbian?) related. Possibly some files have been deleted/corrupted.
I'd suggest you create a thread on the [forum](https://www.raspberrypi.org/forums/index.php) to see if that are any better suggestions that a reinstall.
