### ISSUE TITLE
LVM - new kernel 3.6.11 - leaked on lvcreate invocation

### ISSUE THREAD

**Issue by xnosek00** [raspberrypi/linux#185]
Hi,

I updated firmware right now. There is problem with LVM. The latest version works:
root@raspberrypi:/# uname -a
Linux raspberrypi 3.2.27+ #260 PREEMPT Thu Nov 8 00:34:12 GMT 2012 armv6l GNU/Linux

now I use this version:
root@raspberrypi:/var/log# uname -a
Linux raspberrypi 3.6.11+ #348 PREEMPT Tue Jan 1 16:33:22 GMT 2013 armv6l GNU/Linux

After reboot - these errors:

setting up lvm volume groups
mlock failed cannot allocate memory 
munlock failed

After lvcreate: 
root@raspberrypi:# lvcreate -L 1G -n test vg2t
File descriptor 8 (pipe:[15832]) leaked on lvcreate invocation. Parent PID 3635: bash
ffff0000-ffff1000 r-xp 00000000 00:00 0 [vectors]: mlock failed: Cannot allocate memory
ffff0000-ffff1000 r-xp 00000000 00:00 0 [vectors]: munlock failed: Cannot allocate memory
Logical volume "test" created

![2013-01-04 22 08 50](https://f.cloud.github.com/assets/1574100/44222/09be797a-56b4-11e2-9f2f-342465c2914b.jpg)
Something is wrong in kernel. LVM worked fine before kernel update.

**Comment by xnosek00** [comment]
I found this thread: http://readlist.com/lists/redhat.com/linux-lvm/1/6244.html

It seems, that kernel is OK, but we need newer LVM2 in raspbian. Is it right?

**Comment by popcornmix** [comment]
Searching around it seems to be a common problem (on other platforms) and is probably in the LVM tools.
Not something I know much about though.

**Comment by xnosek00** [comment]
Thank you for reply. 

I report a bug there: https://bugs.launchpad.net/raspbian/+bug/1096224

**Comment by xnosek00** [comment]
I reported bug there: http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=698153

And it seems, that there is a solution:

If you don't have this patch installed, try it:
  https://lists.fedorahosted.org/pipermail/lvm2-commits/2012-November/000391.html

**Comment by popcornmix** [comment]
Good to hear there is a solution. I'll close this issue, as the fix is needed in Raspbian distribution..
