### ISSUE TITLE
Dual display Official 7" DSI Touch Display  and HDMI  display using Raspberry pi 3 , OS raspbian jessie pixel

### ISSUE THREAD

**Issue by haridiy** [raspberrypi/linux#1856]
Is it possible to run DSI raspberry pi 7inch display as main display and HDMI for projector as extended display using Raspberry pi 3 , OS raspbian jessie pixel

**Comment by Electron752** [comment]
I haven't tried it with raspbian pixel, but this pull request which was merged a bit ago might work for you.  I'm sure kms works with duel displays, but I'm not sure if fkms got fixed or not.

Essentially, you will need kernel version 4.9.

https://github.com/raspberrypi/linux/pull/1813

**Comment by anholt** [comment]
Yes, it does work when you enable the open source graphics stack in raspi-config.

**Comment by JamesH65** [comment]
Closing this issue as questions answered/issue resolved.
