### ISSUE TITLE
Kernel 4.9 misses bcm2835-v4l2 module

### ISSUE THREAD

**Issue by crashmaster1** [raspberrypi/linux#1860]
Older kernels have this module included. It creates '/dev/video0' device to get motion with the rpi camera working.
Is there a replacement with kernel 4.9 now?
Thanks and greets,
CM1

**Comment by popcornmix** [comment]
Module is still present. What does:
``sudo modprobe bcm2835-v4l2`` 
output?

**Comment by crashmaster1** [comment]
I use Archlinux, it says:
'modprobe: FATAL: Module bcm2835-v4l2 not found in directory /lib/modules/4.9.12-1-ARCH'

Looks like they haven't it configured.
Thanks!

**Comment by Cyborg91** [comment]
So how to configured it?

**Comment by crashmaster1** [comment]
In the Archlinux kernel (i currently use 4.9.22) it is included again and everything works fine now, 
You need just to install it. ;)
