### ISSUE TITLE
Bad kernel download

### ISSUE THREAD

**Issue by rascol** [raspberrypi/linux#1861]
Downloaded kernels for 4.9.11 are faulty:

gzip: stdin: invalid compressed data--format violated
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now
Traceback (most recent call last):
  File "/usr/bin/rpi-source", line 345, in <module>
    sh("cd %s && tar --checkpoint=100 --checkpoint-action=dot -xzf %s" % (args.dest, linux_tar))
  File "/usr/bin/rpi-source", line 85, in sh
    subprocess.check_call(cmd, shell=True)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'cd /home/pi/rpi && tar --checkpoint=100 --checkpoint-action=dot -xzf /home/pi/rpi/linux-204050d0eafb565b68abf512710036c10ef1bd23.tar.gz' returned non-zero exit status 2

**Comment by popcornmix** [comment]
I've just tested and it works fine for me.
You may be hitting a temporary github issue.
Try again in an hour.
If you still have a problem then report here:
https://github.com/Hexxeh/rpi-update/issues
