### ISSUE TITLE
libstdc++6 : Breaks: libboost-date-time1.55.0

### ISSUE THREAD

**Issue by tiborh** [raspberrypi/linux#1862]
**Command issued and error message:**
(after `sudo apt update`)
$ sudo apt upgrade 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libstdc++6 : Breaks: libboost-date-time1.55.0 but 1.55.0+dfsg-3 is to be installed
E: Broken packages

**installed libstdc++6 version (6.3.0 only):**
libstdc++6/testing,now 6.3.0-5+rpi1 armhf [installed]
libstdc++6/stable 4.9.2-10 armhf

**Installed libboost-date-time libraries (only 1.61 and 1.62):**
libboost-date-time-dev/testing 1.62.0.1+b4 armhf
libboost-date-time1.49-dev/stable 1.49.0-4+b2 armhf
libboost-date-time1.49.0/stable 1.49.0-4+b2 armhf
libboost-date-time1.50-dev/stable 1.50.0-1+b2 armhf
libboost-date-time1.50.0/stable 1.50.0-1+b2 armhf
libboost-date-time1.53-dev/stable 1.53.0-6+b2 armhf
libboost-date-time1.53.0/stable 1.53.0-6+b2 armhf
libboost-date-time1.54-dev/stable 1.54.0-5 armhf
libboost-date-time1.54.0/stable 1.54.0-5 armhf
libboost-date-time1.55-dev/stable 1.55.0+dfsg-3 armhf
libboost-date-time1.55.0/stable,now 1.55.0+dfsg-3 armhf [residual-config]
libboost-date-time1.58-dev/testing 1.58.0+dfsg-5.1+rpi1+b1 armhf
libboost-date-time1.58.0/testing 1.58.0+dfsg-5.1+rpi1+b1 armhf
libboost-date-time1.60-dev/testing 1.60.0+dfsg-6+b2 armhf
libboost-date-time1.60.0/testing 1.60.0+dfsg-6+b2 armhf
libboost-date-time1.61-dev/testing 1.61.0+dfsg-3 armhf
libboost-date-time1.61.0/testing,now 1.61.0+dfsg-3 armhf [installed,automatic]
libboost-date-time1.62-dev/testing 1.62.0+dfsg-4 armhf
libboost-date-time1.62.0/testing,now 1.62.0+dfsg-4 armhf [installed,automatic]

**Comment by popcornmix** [comment]
This repo is for the linux kernel.
You seem to have a packaging issue.
I'd suggest the forum or https://github.com/RPi-Distro/repo/issues
