### ISSUE TITLE
CH34x USB to serial chip support

### ISSUE THREAD

**Issue by justinasjaronis** [raspberrypi/linux#1863]
CH340 and present USB2serial converters are present in the wild. However present driver ``ch341`` does not manage to set parity and stop bits for the chip (it works correctly only in "7N1" configuration). Small patch is required to have usable support of these devices:

https://github.com/karlp/ch341-linux/blob/master/0001-usb-serial-ch341-Add-parity-support.patch

I have tested this patch to be working with various ch34x devices.  What is workflow to submit patch to Raspberry Pi kernel ? I would be willing to cooperate to get this merged upstream.

**Comment by 6by9** [comment]
This is an upstream kernel driver, so all changes should be fixed upstream and we'll then automatically pick them up once released, and can backport if there is good need.
https://github.com/raspberrypi/linux/blob/rpi-4.9.y/REPORTING-BUGS for details of the process

This patch doesn't apply on top of the 4.9 branch - what branch have you been testing? Upstream will only update the main upstream tree in the first instance.

Having just checked the upstream usb/serial tree (git://git.kernel.org/pub/scm/linux/kernel/git/johan/usb-serial.git) there is a ch341 branch with commits from Dec 2016, so there appears to be some tinkering going on.  Check out the mailing list, and email the maintainer/list for more details (https://github.com/raspberrypi/linux/blob/rpi-4.9.y/MAINTAINERS#L12596)

**Comment by grigorig** [comment]
This is upstream already. Linux 4.10 has a bunch of improvements to the ch341 driver, including parity support. You'll just have to wait if you don't want to compile a kernel on your own.

**Comment by justinasjaronis** [comment]
Hi, Thanks a lot for the information. Yes originally patch was for some older Linux version. 
If someone needs dirty quick fix on 4.4.x kernel here is my commit that fixes it:
https://github.com/justinasjaronis/linux/commit/0866ccda19db50ec6886eb4e4425bf3293555e35

There are a lot of devices in the wild which use this chipset, it's maybe second by popularity after PL2303 so I believe that backport would be very useful.

**Comment by JamesH65** [comment]
@popcornmix Can we cherry pick the required patches to solve this issue?

**Comment by popcornmix** [comment]
Let me look into it. There are several patches on 4.10 not on 4.9 and they don't apply cleanly.
Let me check if @justinasjaronis patch applies okay to 4.9.

**Comment by popcornmix** [comment]
The patch linked to by @justinasjaronis has been applied to rpi-4.9.y tree.
It will be in next rpi-update firmware.

**Comment by JamesH65** [comment]
Please update to the latest kernel which may contain a fix for this issue.
