### ISSUE TITLE
xpad module not being compiled

### ISSUE THREAD

**Issue by adrianmoisey** [raspberrypi/linux#187]
http://www.raspberrypi.org/phpBB3/viewtopic.php?t=14450&p=149173

Some people need the xpad module so that various gamepads can be used on the Raspberry Pi. Can this be included?

**Comment by licaon-kter** [comment]
isn't this better anyway: https://github.com/Grumbel/xboxdrv/ ?

**Comment by adrianmoisey** [comment]
I tried it on my Logitech F310, and it doesn't work. The only way I know how to get it working is the xpad module.

**Comment by adrianmoisey** [comment]
Will this happen?

**Comment by adrianmoisey** [comment]
I've compiled this module myself for now, but it would be nice if it was included in the main package.

**Comment by usul294** [comment]
Any help on doing that? I downloaded xpad.c and xpad.h but I'm having trouble compiling it with any makefile I can find. Trying to use an f310 as well

**Comment by Silent-Hunter** [comment]
Yes please! I have a Razer Sabertooth, and even though it works on an actual XBOX 360, it will not work with xboxdrv no matter what I do. However it works perfectly on xpad. Come to think of it, I can't get a standard XBOX 360 controller to work on xboxdrv either.

**Comment by adrianmoisey** [comment]
@popcornmix how do we get this to happen?

**Comment by popcornmix** [comment]
It's included in the next (3.10) kernel tree.
`sudo BRANCH=next rpi-update`
will get it.

**Comment by adrianmoisey** [comment]
Awesome! Looks like it worked! Thanks :)

```
[    3.760363] input: Generic X-Box pad as /devices/platform/bcm2708_usb/usb1/1-1/1-1.3/1-1.3:1.0/input/input0
```

**Comment by Silent-Hunter** [comment]
I'm getting "sudo: rpi-update: command not found".

**Comment by popcornmix** [comment]
You can get it from here:
https://github.com/Hexxeh/rpi-update
