### ISSUE TITLE
Rpi0-4.9.x freezes under heavy load with usb hub

### ISSUE THREAD

**Issue by pinoverclock** [raspberrypi/linux#1870]
kernel 4.9 branch patched with the corresponding RT patches. (https://www.kernel.org/pub/linux/kernel/projects/rt/) freezes instantly under heavy cpu load if a usb hub is connected, no matter the number of usb devices conected to it or if it is a powered hub or not, the rpi0 just freezes without printing a line so i'm unable to provide any logs.

**Comment by P33M** [comment]
The -RT patchset (which touches dozens of low-level kernel internals) has never been supported by Raspberry Pi. Closing unless you can replicate the result with one of our shipped kernels.
