### ISSUE TITLE
Empty /sys/class/leds/ on kernel 4.10.1/rpi3

### ISSUE THREAD

**Issue by mkreisl** [raspberrypi/linux#1871]
Testing kernel 4.10.1 on my Raspberry Pi 3. Everything looks fine expect green LED is always off and /sys/class/leds is empty.

So, is this bug or feature. (took my working 4.9 kernel .config for building kernel 4.10.1)

**Comment by asavah** [comment]
Make sure you have CONFIG_GPIO_BCM_EXP=y in your .config
See https://github.com/raspberrypi/linux/commit/09dcf79342037846d1518a691f7e274b0e5d4874

**Comment by mkreisl** [comment]
> Make sure you have CONFIG_GPIO_BCM_EXP=y in your .config

It was not. Now it works. Thanks a lot :+1:
