### ISSUE TITLE
Gadget serial locks up.

### ISSUE THREAD

**Issue by ED6E0F17** [raspberrypi/linux#1876]
https://www.raspberrypi.org/forums/viewtopic.php?f=29&t=167934&start=179

When using g_serial, or telnet over g_ether, the tty will lock up on certain text strings. (tested on Linux 4.9)
"dmesg|head" or "ls" tend to fail, while "dmesg|tail" or "ls -l" may succeed. This issue goes away when using ssh over g_ether.

This will be an upstream bug, since it affects the dwc2 USB driver.

EDIT:
````
Working with Linux 4.9-rc2 
    Working before usb-4.9.rc3
    Broken with usb-4.9-rc3
    Broken before tty-4.9-rc3
Broken with 4.9-rc3
````
Bisected to usb-4.9-rc3, 20+ commits.
````
Working with:
    Revert "usb: dwc2: gadget: change variable name to more meaningful"
Broken with
    Revert "usb: dwc2: gadget: fix TX FIFO size and address initialization"
````
Bisected to:
    https://github.com/raspberrypi/linux/commit/3fa9538539ac737096c81f3315a14670b1609092

**Comment by AmosAnderson** [comment]
After updating to 4.9 none of the gadgets that I've tried (g_serial or g_ether) seem to work correctly. This is with a configuration that worked correctly before the update. It seems that they're no longer passing any data over them. The device functions as normal but the gadget interface doesn't.  

https://www.raspberrypi.org/forums/viewtopic.php?f=29&t=167934&start=177

**Comment by ED6E0F17** [comment]
This is a "known issue": https://www.spinics.net/lists/linux-usb/msg150016.html

There may be a solution in 4.11 that would be better than reverting the broken commit.
