### ISSUE TITLE
config request CONFIG_NET_IPGRE

### ISSUE THREAD

**Issue by ghost** [raspberrypi/linux#188]
Please could the ip_gre module be added as it would be very useful for anyone experimenting with GRE tunnels.

**Comment by popcornmix** [comment]
Latest firmware adds 
CONFIG_NET_IPGRE_DEMUX=m
CONFIG_NET_IPGRE=m

is this what you wanted?

**Comment by ghost** [comment]
Yes please.

**Comment by popcornmix** [comment]
Okay, try rpi-update and it should be there.
