### ISSUE TITLE
xset not adjusting mouse settings

### ISSUE THREAD

**Issue by knutegit** [raspberrypi/linux#1881]
Tested on an up to date RPi 3B, xset mouse setting have no effect on mouse movement.

**Comment by Electron752** [comment]
I'm not associated with the PI foundation, but this sounds like a Raspbian issue.  Perhaps it would be better to open a topic in the regular raspberrypi forum at www.raspberrypi.org since it doesn't appear to be a kernel issue.

**Comment by JamesH65** [comment]
Indeed, not a kernel issue.

Closing as this issue is not relevant to this repo.
