### ISSUE TITLE
Make spidev unloadable

### ISSUE THREAD

**Issue by ghost** [raspberrypi/linux#1897]
Can you please make spidev unloadable like i2cdev?
Therefore I cannot access the spi devices from kernelmod.
In the forum it was mentioned that, there are some dependencies on the spi files. 
https://www.raspberrypi.org/forums/viewtopic.php?f=66&t=177203
But if you unload the spi_bcm2835 module every still works perfectly fine (except for spi)

**Comment by pelwell** [comment]
The defconfigs on rpi-4.9.y and rpi-4.10.y now set spidev to be built as a loadable module.

**Comment by pelwell** [comment]
The latest rpi-update kernel now comes with spidev as a loadable module, so I'm closing this.
