### ISSUE TITLE
7" Touch screen wont go back to sleep mode.

### ISSUE THREAD

**Issue by JacoFourie1** [raspberrypi/linux#1904]
If you use the 7" Pi screen and you use VNC to remote control the screen / console it will not always (at random) go back to sleep mode (black). The screen will stay on all the time and only after you touch the screen will it go black (screen saver) after being idle for some time. Is there a setting to fix this so it will always act like somebody touched the screen locally if you use VNC or any remote console application.

**Comment by popcornmix** [comment]
This doesn't sound like a linux kernel issue, so this is the wrong place for this.
I'm pretty my Ubuntu PC behaves the same way (display wakes up and remains on when I use VNC).
I'd suggest asking this question in the [forum](www.raspberrypi.org/forums).
