### ISSUE TITLE
ipt_LOG module missing

### ISSUE THREAD

**Issue by gstreeter** [raspberrypi/linux#191]
The 3.6 kernel build does not appear to now include the ipt_LOG module which means that IPTABLES cannot now use the LOG target to record events in the system log. This has a significant impact on system security. Please re-instate this module in the kernel build.

**Comment by popcornmix** [comment]
Is this the setting you want: CONFIG_NETFILTER_XT_TARGET_LOG?

**Comment by gstreeter** [comment]
I've just been checking and I believe its CONFIG_IP_NF_TARGET_LOG and CONFIG_IP6_NF_TARGET_LOG.

**Comment by gstreeter** [comment]
Looks like this has changed between 3.2 and 3.6 kernels and is CONFIG_NETFILTER_XT_TARGET_LOG.

**Comment by gstreeter** [comment]
More research has revealed that this is a problem with the MENUCONFIG for the kernel options which has lost the LOG target setup for Netfilter preventing the modules being generated.

**Comment by gstreeter** [comment]
Having investigated further it seems that the Linux team have replaced the ipt_LOG module with a new xt_LOG module that covers both IPV4 and IPV6 which previously had separate kernel configuration values. I'm not sure what the problem is but it looks to me like the IPTABLES in Raspian is still expecting the older LOG target implementation and hence fails as the module is no longer present. An update to IPTABLE is probably needed to match the 3.6 kernel changes.

**Comment by ghost** [comment]
iptables logging seems to be working now on kernel 3.6.11+ following commit "Enable modules for netfilter log and dvb modules." (kernel #354)
