### ISSUE TITLE
SPIdev SPI1 clock polarity ignored.

### ISSUE THREAD

**Issue by hugeone** [raspberrypi/linux#1917]
When using SP1 mode is ignored and clock is always inactive low. SOC datasheet shows that microSPI (SPI1 & 2) have this capability.

**Comment by pelwell** [comment]
Although the driver does seem to set the CPOL bit when requested, it's possible that calling ..._reset_hw from ..._unprepare_message is causing the clock to be inactive low between messages when you are expecting it to be inactive high. Can you confirm whether polarity within a message is correct?

**Comment by pelwell** [comment]
The existing polarity handling code was only added in Linux 4.6. Raspbian is still on 4.4, but if you `sudo rpi-update` you will get a 4.9 kernel with the updated driver.

**Comment by hugeone** [comment]
Thank you. After update it works great 🥇 .
![spi1-works](https://cloud.githubusercontent.com/assets/16731021/24329772/2a7a270e-1208-11e7-8693-8a186f3a7dba.png)

> Can you confirm whether polarity within a message is correct?

Unfortunately before update it did not. In desperation I wrote low level driver :)

**Comment by pelwell** [comment]
Can we close this issue? We'll be switching to 4.9 once we feel it's had
sufficient testing.

**Comment by hugeone** [comment]
Closing =
