### ISSUE TITLE
Can't find default configuration "arch/x86/configs/bcm2709_defconfig"!

### ISSUE THREAD

**Issue by dhimantaa** [raspberrypi/linux#1928]
Hi all,

I am trying to build kernel for RASPBERRY PI 2/3 and facing this error.

  HOSTCC  scripts/basic/fixdep
  HOSTCC  scripts/kconfig/conf.o
  HOSTCC  scripts/kconfig/zconf.tab.o
  HOSTLD  scripts/kconfig/conf
***
 *** Can't find default configuration "arch/x86/configs/bcm2709_defconfig"!
 ***
scripts/kconfig/Makefile:112: recipe for target 'bcm2709_defconfig' failed
make[1]: *** [bcm2709_defconfig] Error 1
Makefile:546: recipe for target 'bcm2709_defconfig' failed
make: *** [bcm2709_defconfig] Error 2

**Comment by pelwell** [comment]
You need to include "ARCH=arm" on the kernel make command line. See https://www.raspberrypi.org/documentation/linux/kernel/building.md for full instructions.

**Comment by dhimantaa** [comment]
Thanks @pelwell.

Closing this issue. As i was not following instructions.

**Comment by pabigot** [comment]
FWIW: the current content of https://www.raspberrypi.org/documentation/linux/kernel/building.md says nothing about `ARCH=arm`, but the fix still works.

**Comment by pelwell** [comment]
The building instructions describe compiling _and_ cross-compiling; the cross-compilation instructions are careful to include `ARCH=arm`. You just need to read a bit further.

**Comment by pabigot** [comment]
> You just need to read a bit further.

Quite right; I fumbled the search with `ARCG=`.  Thanks.
