### ISSUE TITLE
Problem with bootcode.bin

### ISSUE THREAD

**Issue by Matthaiks** [raspberrypi/linux#1942]
My Pi 1 Model B+ won't boot (blank screen, no disk activity) with the latest (commit e5ca26f) bootcode.bin.

**Comment by popcornmix** [comment]
Are you sure that is the version you are using? Can you report:
```md5sum bootcode.bin```
The previous version of bootcode did have a problem on Pi1.

**Comment by Matthaiks** [comment]
Bad: 60009c193abdc91edc6439223266b00d
Good: 90f09cba99869fd2d4eda0b533546ffe

For sure.

**Comment by popcornmix** [comment]
Can you confirm if this works:
https://github.com/raspberrypi/firmware/blob/3e82d90123edb0f2225eff2dede74652c18c8040/boot/bootcode.bin?raw=true

**Comment by Matthaiks** [comment]
Yes, it's OK.

**Comment by popcornmix** [comment]
What is on sdcard? Raspbian jessie? Are you using noobs?
Any custom config.txt options?

**Comment by Matthaiks** [comment]
Only Arch Linux ARM. Default config.txt didn't help.

**Comment by popcornmix** [comment]
Ping @XECDesign @pelwell 
Any suggestions other than reverting bootcode change?

**Comment by pelwell** [comment]
I don't think we have much choice but to revert the change until we can work out what the problem is.

**Comment by ED6E0F17** [comment]
I am picking up a rather strange issue where one of my PiZeros will refuse to start (from rpiboot -d) on a warm reboot;  this has been reported in other issues, so be careful what you are testing.

In my case the issue is only apparent on Linux 4.11, and appears to be resolved by switching back to my  "bcm2708-rpi-b-plus.dtb" from linux 4.9 

I noticed that the 4.11 dtb file was a lot larger, but I have not examined the changes.

**Comment by pelwell** [comment]
Does reverting bootcode.bin make any difference? If not, can you create a separate issue?

**Comment by pelwell** [comment]
Can you try with [these firmware files](https://drive.google.com/file/d/0B_P-i4u-SLBXWDRKTFp1MzR3MkE/view?usp=sharing)? Functionally they should be the same as pre-issue firmwares, but after booting if you run `sudo vcdbg log msg |& grep DEBUG` it will show some register values that will help to debug this problem.

**Comment by pelwell** [comment]
The latest rpi-update firmware release should fix this problem.

**Comment by Matthaiks** [comment]
Thanks!
