### ISSUE TITLE
Richard Hirst's ServoBlaster

### ISSUE THREAD

**Issue by chrismeyersfsu** [raspberrypi/linux#196]
What steps would need to be taken to get Richard Hirtst's ServoBlaster in the raspberrypi kernel source-tree and, ultimately, into the raspbian release?

Richard Hirst's ServoBlaster
https://github.com/richardghirst/PiBits ... rvoBlaster

Raspberrypi Kernel
https://github.com/raspberrypi/linux

**Comment by popcornmix** [comment]
Out of tree drivers produce a maintanance headache and the potential to introduce instability.
I need to see substantial demand for this first. People who want this should post here to indicate it is desired.

**Comment by paul-lalonde** [comment]
This little driver is exemplary, and extraordinarily useful.

**Comment by ghost** [comment]
I agree with Paul: for us hardware hackers, a reliable, stable servo driver would be invaluable on the Pi. Please consider the request. Thanks.

**Comment by mitchtech** [comment]
I've been using Richard's ServoBlaster with great success for weeks now... I would love to see it included in the raspberrypi kernel source-tree too!

**Comment by mikecruz** [comment]
This is a very useful driver and I think it should be included.  Thanks.

**Comment by lmykdms** [comment]
Please consider putting ServoBlaster into raspberry pi kernel tree. It provides great convinence for hardware DIYers. Thanks

**Comment by joeberry** [comment]
Definately need something to control more then one servo. I am new to linux , and it would be a great motivation after all that 'sudo' frustrations. Ps3 controller , bluetooth controller and some lego or rc stuff will look like lots of fun.
Regards joE

**Comment by TechColab** [comment]
Yes, please.  I don't want to stray too far from the standard build so that I can be sure that examples I see in mags & blogs are sure to work on my Pi too.  The driver in Adafruit's Ocidentals is only for a single servo and needs a whole new distro (which is currently behind the Raspian distro).

**Comment by jwilker2** [comment]
Kernel level support for servos would be an outstanding addition, what better demonstration of physical computing than 'movement'? From an educational point of view controlling servos encourages development of a whole host of practical mathematical skills, seems like a natural fit.

**Comment by popcornmix** [comment]
Be aware that the servoblaster module uses GPIO 21 which breaks the upcoming camera board.

**Comment by soniyaenator** [comment]
Hey in Richardghirst's servoblaster code the servoblaster.h file is empty....If anybody has the one which is a working file please send it across

**Comment by rsuinux** [comment]
Please consider putting ServoBlaster into raspberry pi kernel tree, and if possible, in debian repository

**Comment by stefannilsson** [comment]
Would also really like the ServoBlaster to be included in the pi tree.

**Comment by miho** [comment]
+1

**Comment by chrismeyersfsu** [comment]
Pretty please :)

**Comment by pageauc** [comment]
I have written a face and motion tracking python demo.  It runs OK but eventually hangs the system latest Raspbian Jessie due to a servod issue as far as I can tell.  Here is my GitHub repo fyi [face and motion tracking demo](https://github.com/pageauc/face-track-demo) There is an auto install script to make install of dependencies and setup easier.
It would be much better if servod was included with RPI build.
Regards Claude ...

**Comment by JamesH65** [comment]
@popcornmix Pretty old issue, are we going to add this? Or just close?

**Comment by popcornmix** [comment]
Seeing as the README says:

> The user space daemon implementation is much more convenient to use and now has rather more
features than the kernel based one.  I would strongly recommend you use the
user space implementation.

I think it is safe to close this.
