### ISSUE TITLE
drivers/spi/spi-bcm2708: bcm2708_spi_setup() must propagate error from bcm2708_setup_state()

### ISSUE THREAD

**Issue by notro** [raspberrypi/linux#197]
## Description

SPI Controller driver **spi-bcm2708** does not report most errors on setup().
Source code: https://github.com/raspberrypi/linux/blob/rpi-3.2.27/drivers/spi/spi-bcm2708.c

Test program used: https://github.com/raspberrypi/linux/blob/rpi-3.2.27/Documentation/spi/spidev_test.c
## How-To-Repeat

Debug ouput is turned on in drivers/spi/spi-bcm2708.c to see what's going on, but is not needed to reproduce error.

```
# Compile spidev_test
cp /usr/src/linux/Documentation/spi/spidev_test.c /tmp
cd /tmp
gcc -o spidev_test spidev_test.c

# Run spidev_test with unsupported bits_per_word value
./spidev_test --device /dev/spidev0.0 --bpw 10
spi mode: 0
bits per word: 10
max speed: 500000 Hz (500 KHz)
can't send spi message: Invalid argument
Aborted
```

The problem with this error is that it is given when trying to send the message in transfer(), not when 10 bpw is requested in main().
The error should have been: pabort("can't set bits per word")

dmesg

```
[ 2896.514851] spidev spi0.0: setup: want 500000 Hz; bus_hz=250000000 / cdiv=512 == 488281 Hz; mode 0: cs 0x00000000
[ 2896.514885] spidev spi0.0: setup: cd 0: 500000 Hz, bpw 8, mode 0x0 -> CS=00000000 CDIV=0200
[ 2896.514912] spidev spi0.0: setup: invalid bits_per_word 10 (must be 8)
[ 2896.514934] spidev spi0.0: setup: cd 0: 500000 Hz, bpw 10, mode 0x0 -> CS=00000000 CDIV=0200
[ 2896.514958] spidev spi0.0: setup: invalid bits_per_word 10 (must be 8)
[ 2896.514979] spidev spi0.0: setup: cd 0: 500000 Hz, bpw 10, mode 0x0 -> CS=00000000 CDIV=0000
[ 2896.518952] spidev spi0.0: setup: invalid bits_per_word 10 (must be 8)
```

From dmesg we see that spi setup fails 3 times on: invalid bits_per_word 10 (must be 8)
2 times in main() and one in transfer(). But only the one in transfer() is detected by the program.
## Fix

Patch drivers/spi/spi-bcm2708.c (sorry it's not a complete patch, but I have other changes in the file)

```
@@ -407,6 +408,7 @@ static int bcm2708_spi_setup(struct spi_device *spi)
        if (ret < 0) {
                kfree(state);
                spi->controller_state = NULL;
+               return ret;
        }

        dev_dbg(&spi->dev,
```

Now the program fails as it should

```
./spidev_test --device /dev/spidev0.0 --bpw 10
can't set bits per word: Invalid argument
Aborted
```

**Comment by popcornmix** [comment]
Looks reasonable. Added to linux source tree. Will be in next firmware build.
