### ISSUE TITLE
ARM64: RPI3 error -110 whilst initialising sd card

### ISSUE THREAD

**Issue by ghost** [raspberrypi/linux#1972]
Whenever I try to boot kernels 4.9 to 4.11 using debian arn64 even on a clean install it fails to boot saying mmc0: error -110 whilst initialising sd card. It fails to start. I even tried changing memory cards but to no avail. The only version that's bootable is 4.8.10. Is anyone able to find out why this is happening?

**Comment by lategoodbye** [comment]
AFAIK support for ARM64 won't be provide here.

Btw you need to provide more information.
Which kernel do you use (mainline, foundation, exact version)?
Which devicetree do you use?
Can you provide a kernel config?
Does the problem occur with every sd card?

**Comment by ghost** [comment]
1. I tried the master, stable, rpi-4.9.y rpi-4.10.y and rpi-4.11.y branches of this repo. 2. the kernel config is the bcmrpi3_defconfig default found in arch/arm64/configs folder for all of those. and 3. yes it happens on every single card and raspberry pi 3 I try. and 4. it also does the same for 32-bit as well on both rpi-4.10.y and rpi-4.11.y branches.

**Comment by lategoodbye** [comment]
Can you please provide a kernellog from startup until the issue?

**Comment by ghost** [comment]
Unless there's a way of outputting it to a file I can only take a picture.

**Comment by pelwell** [comment]
`dmesg > file.txt`

**Comment by raidensnake** [comment]
Any idea where I can place it? I can't boot the os.

**Comment by ghost** [comment]
Being as I can't even boot to the os to run that command. I posted pictures of what it displays.

![wp_20170501_00_21_21_rich](https://cloud.githubusercontent.com/assets/1094029/25568950/f1c409a2-2e04-11e7-8be8-63b3bd3b95b2.jpg)
![wp_20170501_00_21_24_rich](https://cloud.githubusercontent.com/assets/1094029/25568948/f1c1a81a-2e04-11e7-8851-b08e50f4cefc.jpg)
![wp_20170501_00_21_36_rich](https://cloud.githubusercontent.com/assets/1094029/25568949/f1c2f3c8-2e04-11e7-9475-1b86a9622e51.jpg)

**Comment by lategoodbye** [comment]
Could you please add the output before Exception stack timestamp 1.3xxx?

**Comment by ghost** [comment]
I'm not able to as the HDMI only displays when the first screenshot is. It says no signal otherwise.

**Comment by pelwell** [comment]
The usual way to get kernel tracing output is using a serial port connected to header pins 6 (GND), 8 (TXD0) and 10 (RXD0). To enable it you would need to add `enable_uart=1` to config.txt and `console=serial0,11520 loglevel=8` to cmdline.txt, removing `quiet` if it is present.

You can often get to see more logging output on screen by adding the following to config.txt:
```
framebuffer_width=3840
framebuffer_height=2160
```

It might also save time if you post the contents of your config.txt and cmdline.txt.

**Comment by ghost** [comment]
1. I don't have the kit to do the serial part. And 2. The config.txt and codeine.txt files look like this.

Cmdline.txt:

consoleblank=0 console=ttyAMA0,115200 kgdboc=ttyAMA0,115200 console=tty1 root=/dev/mmcblk0p2

Config.txt:

arm_control=0x200
kernel=kernel8.img
hdmi_drive=2
dtparam=audio=on
dtparam=i2c_arm=on
dtparam=i2s=on
dtparam=spi=on

**Comment by lategoodbye** [comment]
Did you tried without arm_control parameter?

**Comment by ghost** [comment]
Yes and it wouldn't boot at all. Just a rainbow screen.

**Comment by pelwell** [comment]
I just built an Pi3 ARMv8 kernel using bcmrpi3_defconfig, set device_tree=broadcom/bcm2710-rpi-3-b.dtb (`ARCH=arm64` puts the dtb files in the broadcom subdirectory) and it booted just fine.

My build script uses the `dtbs_install` make target, which creates and populates the broadcom subdirectory, so if you aren't careful you can end up using the old `ARCH=arm` dtbs instead. I found that with the new kernel and old dtb the mmc0/mmc1 assignments were backwards; DT aliases to manage the mapping were added at the end of March.

**Comment by ghost** [comment]
Do you have an example? This is how I'm compiling it:


Here's the complete bash command list I use: (note: sdc is the memory card)

git clone --depth=1 -b rpi-4.11.y https://github.com/raspberrypi/linux
cd linux
mkdir mnt
cd mnt
mkdir fat32
mkdir ext4
cd ../
mount /dev/sdc1 mnt/fat32
mount /dev/sdc2 mnt/ext4
make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- bcmrpi3_defconfig
make -j8 ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- Image modules dtbs
cp arch/arm64/boot/dts/broadcom/*.dtb mnt/fat32/
cp arch/arm64/boot/dts/overlays/*.dtb* mnt/fat32/overlays/
cp arch/arm64/boot/Image mnt/fat32/kernel8.img
make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- INSTALL_MOD_PATH=mnt/ext4 modules_install
umount mnt/fat32
umount mnt/ext4

**Comment by pelwell** [comment]
That looks alright - it doesn't use the dtbs_install rule, and explicitly copies out of the Broadcom directory into the fat32 root, so you should be using the correct dtb.

**Comment by ghost** [comment]
The problem is when I try this it doesn't boot and gives me that error.

**Comment by pelwell** [comment]
I understand that. If you did manage to get some more kernel logging output, from a serial port or a screenshot, then that might give us enough information to see what is causing your problem,. Until then, considering that nobody else has reported a problem, and since we don't support 64-bit mode, I can't help you any further.

**Comment by ghost** [comment]
is there an option of outputting the log using another working pi? if so how can I go about doing that?

**Comment by lategoodbye** [comment]
Yes, that would be a nice hack. I recommend a RPi 1 or 2 (now called dumper). Here my untested suggestion:

1. Enable 1 UART of the dumper and but disable its console ( remove console=ttyS0,115200 from cmdline.txt )
2. Make sure the debug UART of the affected RPI3 is enabled ( enable_uart=1 in config.txt )
3. Power off both Pis
4. connect GND lines of both pis with each other
5. cross the rx/tx lines between them ( rx of RPI3 to tx of the dumper and vice versa)
6. power on the dumper and control it via the other UART or HDMI
7. configure the trace UART which is connected to the RPI 3 ( sudo stty -F /dev/ttyAMA0 115200 )
8. start dumping into a file ( cat /dev/ttyAMA0 > dump.txt )
9. now start the affected RPI 3
10. wait a moment
11. stop the trace on the dumper with Strg+C

**Comment by pelwell** [comment]
You can also follow the same steps using a Pi3 as the receiver if you put `dtoverlay=pi3-disable-bt` in config.txt.

**Comment by ghost** [comment]
well now for some reason the pi has gone to an sd card error to a blank screen and doing absolutely nothing.

**Comment by lategoodbye** [comment]
Maybe the filesystem is corrupt now?

**Comment by JamesH65** [comment]
Inclined to close this as we don't specifically support ARM64 and conversation has dried up.. You could certainly continue the conversation on the forums, which is probably a  better place for it anyway. Put in a link back to this issue for context.

**Comment by ghost** [comment]
I tried doing the debug however it's still failing to boot. it's not outputting anything. Also I wasn't able to respond sooner as my connection had been down due to an outside cable fault in my area for the last month. This was due to some idiot drilling through the cable while fitting gas lines! It took BT Openreach ages to sort it out!

**Comment by raidensnake** [comment]
it's not outputting anything.
