### ISSUE TITLE
PDM Input Mode Operation

### ISSUE THREAD

**Issue by pyrog** [raspberrypi/linux#1981]
Hi,

How to use the **Pulse Digital Modulation** (PDM) mode to connect one or two _"PDM microphones"_ directly to the SoC pins ?

The [Broadcom BCM2835 data sheet](https://cdn-shop.adafruit.com/product-files/2885/BCM2835Datasheet.pdf) describe registers to use.

The [ALSA SoC I2S Audio Layer](https://github.com/raspberrypi/linux/blob/linux_stable/sound/soc/bcm/bcm2835-i2s.c) source code use the I2S audio layer in PCM mode only (but have the definition of all registers).

Schematics from [SiSonic Design Guide](http://www.all-electronics.de/wp-content/uploads/migrated/document/191061/104pdfsisonic-design-guide-v10.pdf)
<img width="686" alt="pdm microphone" src="https://cloud.githubusercontent.com/assets/2158081/25587267/94c1ae22-2ea3-11e7-993c-eec7a5fe58de.png">

Thanks,

—
Yves

See also: [Introduction to MEMS Microphones](https://curiouser.cheshireeng.com/2014/10/21/introduction-to-mems-microphones/) and [Using a PDM Microphone](https://curiouser.cheshireeng.com/2014/11/04/using-a-pdm-microphone/).

**Comment by P33M** [comment]
This repository is for kernel issues and PRs that implement additional features or fix bugs. As this is a feature that doesn't yet have support, this isn't the best place to have the discussion.

You're likely to get a more lively discussion going on the Interfacing section of the community forum - there are several knowledgeable people there that would probably be interested in exploring this feature.

https://www.raspberrypi.org/forums/viewforum.php?f=44

**Comment by pyrog** [comment]
Thank you for the link 😄
