### ISSUE TITLE
uvcvideo: Non-zero status (-5) in video completion handler.

### ISSUE THREAD

**Issue by peterlee0127** [raspberrypi/linux#199]
I got this error after update Raspberry Pi

Device : Logitech, Inc. Webcam C310
Pi: Raspberry Pi Linux Pi 3.6.11+ 
Using mjpg_streamer

MJPG Streamer Version: svn rev: Unversioned directory
i: Using V4L2 device.: /dev/video0
i: Desired Resolution: 320 x 240
i: Frames Per Second.: 30
i: Format............: MJPEG
Adding control for Pan (relative)
UVCIOC_CTRL_ADD - Error: Inappropriate ioctl for device
Adding control for Tilt (relative)
UVCIOC_CTRL_ADD - Error: Inappropriate ioctl for device
Adding control for Pan Reset
UVCIOC_CTRL_ADD - Error: Inappropriate ioctl for device
Adding control for Tilt Reset
UVCIOC_CTRL_ADD - Error: Inappropriate ioctl for device
Adding control for Pan/tilt Reset
UVCIOC_CTRL_ADD - Error: Inappropriate ioctl for device
Adding control for Focus (absolute)
UVCIOC_CTRL_ADD - Error: Inappropriate ioctl for device
mapping control for Pan (relative)
UVCIOC_CTRL_MAP - Error: Inappropriate ioctl for device
mapping control for Tilt (relative)
UVCIOC_CTRL_MAP - Error: Inappropriate ioctl for device
mapping control for Pan Reset
UVCIOC_CTRL_MAP - Error: Inappropriate ioctl for device
mapping control for Tilt Reset
UVCIOC_CTRL_MAP - Error: Inappropriate ioctl for device
mapping control for Pan/tilt Reset
UVCIOC_CTRL_MAP - Error: Inappropriate ioctl for device
mapping control for Focus (absolute)
UVCIOC_CTRL_MAP - Error: Inappropriate ioctl for device
mapping control for LED1 Mode
UVCIOC_CTRL_MAP - Error: Inappropriate ioctl for device
mapping control for LED1 Frequency
UVCIOC_CTRL_MAP - Error: Inappropriate ioctl for device
mapping control for Disable video processing
UVCIOC_CTRL_MAP - Error: Inappropriate ioctl for device
mapping control for Raw bits per pixel
UVCIOC_CTRL_MAP - Error: Inappropriate ioctl for device
o: www-folder-path...: ./www/
o: HTTP TCP port.....: 8081
o: username:password.: disabled
o: commands..........: disabled

Kernel log
Jan 22 02:41:06 localhost kernel: [ 48.482369] uvcvideo: Non-zero status (-5) in video completion handler.
Jan 22 02:43:25 localhost kernel: [ 187.856301] uvcvideo: Non-zero status (-5) in video completion handler.
Jan 22 02:45:45 localhost kernel: [ 327.609291] uvcvideo: Non-zero status (-5) in video completion handler.
Jan 22 02:46:13 localhost kernel: [ 355.135032] uvcvideo: Non-zero status (-5) in video completion handler.
Jan 22 02:49:32 localhost kernel: [ 554.531625] uvcvideo: Non-zero status (-5) in video completion handler.
Jan 22 03:08:02 localhost kernel: [ 1664.113372] uvcvideo: Non-zero status (-5) in video completion handler.
Jan 22 03:08:30 localhost kernel: [ 1692.565968] uvcvideo: Non-zero status (-5) in video completion handler.

I follow this website. It work perfectly before I update to 3.6
http://wolfpaulus.com/journal/embedded/raspberrypi_webcam

Then webcam will not work.
Now, I can only see the white streamer page.

$ lsusb
Bus 001 Device 006: ID 046d:081b Logitech, Inc. Webcam C310

peterlee@Pi:~ $ sudo vcgencmd version
Jan 15 2013 12:54:01 
Copyright (c) 2012 Broadcom
version 362704 (release)

Here is some similar problem.
http://mmbrothers.exblog.jp/16923993/

thanks

**Comment by popcornmix** [comment]
-5 is EIO (I/O error) returned in urb->status. Possibly coming from:

```
    case DWC_OTG_HC_XFER_PERIODIC_INCOMPLETE:
        DWC_DEBUGPL(DBG_HCDV,
            "  Complete URB with I/O error\n");
        free_qtd = 1;
        qtd->urb->status = -DWC_E_IO;
        hcd->fops->complete(hcd, qtd->urb->priv,
            qtd->urb, -DWC_E_IO);
        break;
```

Seems like a usb driver issue, so Gordon may have a better idea.

**Comment by ghost** [comment]
I have the same issue with Microsoft LifeCam VX-800. I tried the modprobe with nodrop=1 parameter, but it did not help (possibly the 3.6.11+ #393 is not compiled with that option).
Anyhow, the webcam is therefore not working at all - after some 120 seconds I always receive the error, no matter what resolution or framerate I select.

**Comment by ghost** [comment]
Can I somehow help with debuging/identifying the issue here?

**Comment by ghollingworth** [comment]
What's the CPU usage whilst doing this? Is it mostly idle?

Gordon

**Comment by ghost** [comment]
Without the module parameter the CPU usage was almost none (1-3% including network streaming), with the parameter it raised a little to 5-7%, again including streaming.

**Comment by gitsead** [comment]
[possible work around]

(exactly same setup - custom debian minbase)
Device : Logitech, Inc. Webcam C310
Pi: Raspberry Pi Linux Pi 3.6.11+ 
Using mjpg_streamer

I have the same errors from mjpg_streamer. seems to have problems with some ioctls hmmm...
well 'for me' it worked to manually set resolution and pixelformat using v4l2-ctl:

v4l2-ctl -v width=640,height=480,pixelformat=MJPG

after this i at least got a good quality video stream (quite better than i expected) over usb-wlan adhoc.

maybe this helps aka you maybe can ignore the erros and still get video stream working

**Comment by P33M** [comment]
The majority of webcams now work with latest kernel/firmware.
