### ISSUE TITLE
JIRA SW-5991

### ISSUE THREAD

**Issue by nomis** [raspberrypi/linux#20]
Could you provide an explanation of the workaround that references JIRA SW-5991?

```
diff --git a/arch/arm/mm/proc-v6.S b/arch/arm/mm/proc-v6.S
index 5900cd5..952736d 100644
--- a/arch/arm/mm/proc-v6.S
+++ b/arch/arm/mm/proc-v6.S
@@ -73,10 +73,19 @@ ENDPROC(cpu_v6_reset)
  *
  * IRQs are already disabled.
  */
+
+/* See jira SW-5991 for details of this workaround */
 ENTRY(cpu_v6_do_idle)
-   mov r1, #0
-   mcr p15, 0, r1, c7, c10, 4      @ DWB - WFI may enter a low-power mode
-   mcr p15, 0, r1, c7, c0, 4       @ wait for interrupt
+   .align 5
+   mov     r1, #2
+1: subs    r1, #1
+   nop
+   mcreq   p15, 0, r1, c7, c10, 4      @ DWB - WFI may enter a low-power mode
+   mcreq   p15, 0, r1, c7, c0, 4       @ wait for interrupt
+   nop
+   nop
+   nop
+   bne 1b
    mov pc, lr

 ENTRY(cpu_v6_dcache_clean_area)
```

**Comment by raspberrypi** [comment]
Entering WFI state with an outstanding instruction cache read in
flight can hang the ARM core, so you have to be very careful to
preload the region following the WFI into the cache before going to
sleep. We do this by going round a loop once with the mcr instructions
conditionally disabled before doing it for real.

On Sat, May 12, 2012 at 8:39 PM, Simon Arlott
reply@reply.github.com
wrote:

**Comment by swarren** [comment]
Is there an ARM bug number that can be referenced when upstreaming this code, or is is somehow specific to Broadcom's implementation?

**Comment by raspberrypi** [comment]
I don't have an ARM bug number for this, I'm afraid, and I can't
actually find the errata list any more on ARM's website. I debugged
this one myself, and I'm certain that it will affect other ARM11
implementations. I believe the code in proc_v6.S was provided to us by
ARM, so I know they're aware of the problem.

Eben

On Fri, May 25, 2012 at 3:27 AM, Stephen Warren
reply@reply.github.com
wrote:
