### ISSUE TITLE
Kernel Module Request 

### ISSUE THREAD

**Issue by mypiandrew** [raspberrypi/linux#2017]
Hi

Would it be possible to include this module in the 4.9.x build :

kernel/drivers/i2c/busses/i2c-robotfuzz-osif.ko

**Comment by popcornmix** [comment]
I assume this is option ``CONFIG_I2C_ROBOTFUZZ_OSIF``
Seems reasonable.

**Comment by mypiandrew** [comment]
Sounds right to me

**Comment by popcornmix** [comment]
Added [here](https://github.com/raspberrypi/linux/commit/8b607d1fd1baa4448df39b50cd907fc080e7f960) - will be in next rpi-update.

**Comment by mypiandrew** [comment]
Cheers!

**Comment by popcornmix** [comment]
Should be in latest rpi-update kernel.
