### ISSUE TITLE
USB can not be built as a module

### ISSUE THREAD

**Issue by yann-morin-1998** [raspberrypi/linux#203]
When USB is configured as a module, the build fails with:

```
  LD      init/built-in.o
arch/arm/mach-bcm2708/built-in.o: In function `bcm2708_init':
:(.init.text+0x300): undefined reference to `fiq_fix_enable'
```

That's because 'fiq_fix_enable' is declared in drivers/usb/host/dwc_otg/dwc_otg_driver.c and the symbol is not available if dwc_otg is compiled as a module, so it can not be used from arch/arm/mach-bcm2708/bcm2708.c in this case.

**Comment by licaon-kter** [comment]
see this: https://github.com/raspberrypi/linux/issues/112

**Comment by popcornmix** [comment]
Duplicate.

**Comment by yann-morin-1998** [comment]
Indeed, I missed it before filling. I'll go comment there.
Thank you. :-)
