### ISSUE TITLE
Backport joystick polling rate commandline option

### ISSUE THREAD

**Issue by vanfanel** [raspberrypi/linux#2036]
I have found that, at last, the polling rate will be configurable for USB joysticks in 4.12 kernel:
https://patchwork.kernel.org/patch/9591909/

It seems to have been merged upstream, so, could that be backported to Pi's current kernel? It will be some time until we are at 4.12 as default, and the feature is interesting enough.
Also, it's a very simple patch really.

Thanks

**Comment by popcornmix** [comment]
@pelwell I've tested and 4.12 patch applies without much grief. Any objections?

**Comment by pelwell** [comment]
Go ahead - it looks safe.

**Comment by popcornmix** [comment]
Added: https://github.com/raspberrypi/linux/commit/3db4135e6fbae417e0b297afa680c6caeaf52c19
Will be in next rpi-update kernel.

**Comment by vanfanel** [comment]
Thanks for the backport! When can we expect the next rpi-update with this?

**Comment by popcornmix** [comment]
Should be in latest rpi-update kernel. Please test and close if happy.

**Comment by vanfanel** [comment]
Works great, 500Hz according to evhz! 
Thanks, closing!
