### ISSUE TITLE
Please enable CONFIG_SENSORS_JC42

### ISSUE THREAD

**Issue by rumpelsepp** [raspberrypi/linux#2046]
With this module [this](https://learn.adafruit.com/adafruit-mcp9808-precision-i2c-temperature-sensor-guide/overview) temperature sensor and several others should be accessible. [Here](https://github.com/torvalds/linux/blob/master/Documentation/devicetree/bindings/hwmon/jc42.txt) is the device tree documentation. I will provide a device tree overlay configuration for the `i2c-sensor-overlay` once the option is enabled.

**Comment by pelwell** [comment]
10KB for so many sensors isn't bad. The CONFIG_SENSOR_JC42 is now in the RPi defconfigs and will be picked up by the next firmware build.

**Comment by rumpelsepp** [comment]
Nice, thanks!

**Comment by popcornmix** [comment]
Okay to close this?

**Comment by JamesH65** [comment]
Please update to the latest kernel which may contain a fix for this issue.
