### ISSUE TITLE
Add Support for Harmony Hub PS3 remote

### ISSUE THREAD

**Issue by saue0** [raspberrypi/linux#2047]
I Need to add the support for the Harmony Hub PS3 remote.
I currently recompile the kernel localy to add it.
Can someone add these line to de HID.

Thanks

**Edit: /drivers/hid/hid-ids.h**

	Find : 
		USB_DEVICE_ID_LOGITECH_HARMONY_PS3 
	Add:
		#define USB_DEVICE_ID_LOGITECH_HARMONY_HUB_PS3  0xc129

**Edit: /drivers/hid/hid-core.c**

	Find :
		USB_DEVICE_ID_LOGITECH_HARMONY_PS3 
	Add:
		{ HID_BLUETOOTH_DEVICE(USB_VENDOR_ID_LOGITECH, USB_DEVICE_ID_LOGITECH_HARMONY_HUB_PS3) },

	Find : 
		case USB_VENDOR_ID_LOGITECH:
		if (hdev->product >= USB_DEVICE_ID_LOGITECH_HARMONY_FIRST &&
		    hdev->product <= USB_DEVICE_ID_LOGITECH_HARMONY_LAST)
			return true;

	Add  in the confition:
		 hdev->product != USB_DEVICE_ID_LOGITECH_HARMONY_HUB_PS3

**Edit:  /drivers/hid/hid-sony.c**

	Find:
		 /* Logitech Harmony Adapter for PS3 */

	Add:
		/* Logitech Harmony Hub for PS3 */
		{ HID_BLUETOOTH_DEVICE(USB_VENDOR_ID_LOGITECH, USB_DEVICE_ID_LOGITECH_HARMONY_HUB_PS3),
			.driver_data = PS3REMOTE },

**Compile and install**

**Comment by pelwell** [comment]
These are unaltered upstream files, so you will have to create a patch and submit it to the maintainers. Or you could try emailing the maintainer, Jiri Kosina <jikos@kernel.org>, who may create the patch for you.
