### ISSUE TITLE
Apply a rt patch in 4.4.y

### ISSUE THREAD

**Issue by bigoplus** [raspberrypi/linux#2053]
Hi,guys

I am using a ZERO W. And I want to apply a linux rt patch for it.
Firstly, I found I need to use 4.4. version linux kernel. So I choice 4.4.y branch.
But I found rt patch 4.4.66-rt79 can not be compile with this version. So Can you
tell me how to match kernel and patch.

**Comment by popcornmix** [comment]
Sorry, this isn't the right place to explaining how to apply out-of-tree patches to no longer supported kernels (we have moved to 4.9 tree).

I'd suggest posting in the [forum](https://www.raspberrypi.org/forums/viewforum.php?f=29) where discussion of applying RT patches crop up from time to time.
