### ISSUE TITLE
GPSMANSHP

### ISSUE THREAD

**Issue by N7JYS** [raspberrypi/linux#206]
DPKG: Error  processing gpsmanshp (--configure)

This is the error I get trying to install gpsmanshp with aptitude in debian on a Raspberry Pi.
This package is needed by xastir  and imagemagick. Even after and upgrade I get the same
results>

**Comment by kripton** [comment]
Definitely not a kernel issue though

**Comment by N7JYS** [comment]
No but is is a problem with the repository and would be nice to see it fixed.

**Comment by popcornmix** [comment]
Can't be fixed here. I suggest you post on raspian forum:
http://www.raspberrypi.org/phpBB3/viewforum.php?f=66
Plugwash may be able to help.
