### ISSUE TITLE
vc4-vkms-v3d overlay and omxplayer subtitles

### ISSUE THREAD

**Issue by vanfanel** [raspberrypi/linux#2062]
Hi,

Using vc4-vkms-v3d overlay allows omxplayer to work along with KMS/DRM apps (which I program and use), but it seems that omxplayer uses openvg for subtitles so it won't work without disabling osd explicitly (--no-osd option).
Any chances that omxplayer subs work with the vc4-vkms-v3d by simply using dispmanx to display subs on their own dispmanx element or other similar solution?

**Comment by popcornmix** [comment]
This isn't related to the linux kernel. Open an issue here:
https://github.com/popcornmix/omxplayer

Yes, in the vc4-kms-v3d or vc4-fkms-v3d world gpu side OpenVG is not an option, so the subtitle code will need to be rewritten.
