### ISSUE TITLE
No RAID0 support?

### ISSUE THREAD

**Issue by ghost** [raspberrypi/linux#207]
In an attempt to combine two USB memory sticks into one device, I was surprided by the fact that mdadm allows me to configure it the way I like but the kernel does not support it.

There's no raid0.ko module. Why?

**Comment by popcornmix** [comment]
Not sure why it's missing. You want CONFIG_MD_RAID0?
I'll include it with next firmware update.

**Comment by ghost** [comment]
Thanks!

Rolf

Op 1 feb. 2013 om 18:28 heeft "popcornmix" <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:

Not sure why it's missing. You want CONFIG_MD_RAID0?
I'll include it with next firmware update.

**Comment by popcornmix** [comment]
/lib/modules/3.6.11+/kernel/drivers/md/raid0.ko is included in recent firmware
