### ISSUE TITLE
Raspbian Jessie Hash Sum mismatch

### ISSUE THREAD

**Issue by bayrem-gharsellaoui** [raspberrypi/linux#2070]
when i run **sudo apt-get update** i get the following:
Hit http://mirrordirector.raspbian.org jessie InRelease
Hit http://archive.raspberrypi.org jessie InRelease
Hit http://mirrordirector.raspbian.org jessie/main armhf Packages
Get:1 http://archive.raspberrypi.org jessie/main armhf Packages [163 kB]
Hit http://mirrordirector.raspbian.org jessie/contrib armhf Packages
Get:2 http://mirrordirector.raspbian.org jessie/non-free armhf Packages [84.2 kB]
Get:3 http://mirrordirector.raspbian.org jessie/rpi armhf Packages [1,356 B]
Hit http://archive.raspberrypi.org jessie/ui armhf Packages
Ign http://mirrordirector.raspbian.org jessie/contrib Translation-en_GB
Ign http://mirrordirector.raspbian.org jessie/contrib Translation-en
Ign http://mirrordirector.raspbian.org jessie/main Translation-en_GB
Ign http://mirrordirector.raspbian.org jessie/main Translation-en
Ign http://mirrordirector.raspbian.org jessie/non-free Translation-en_GB
Ign http://mirrordirector.raspbian.org jessie/non-free Translation-en
Ign http://archive.raspberrypi.org jessie/main Translation-en_GB
Ign http://mirrordirector.raspbian.org jessie/rpi Translation-en_GB
Ign http://archive.raspberrypi.org jessie/main Translation-en
Ign http://mirrordirector.raspbian.org jessie/rpi Translation-en
Ign http://archive.raspberrypi.org jessie/ui Translation-en_GB
Ign http://archive.raspberrypi.org jessie/ui Translation-en
Fetched 248 kB in 12s (20.4 kB/s)
W: Failed to fetch http://archive.raspberrypi.org/debian/dists/jessie/main/binary-armhf/Packages  Hash Sum mismatch

E: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by popcornmix** [comment]
This doesn't sound like a linux kernel issue.
Better to report it here: https://github.com/RPi-Distro/repo
