### ISSUE TITLE
Terminal frozen after typed Pi's Password

### ISSUE THREAD

**Issue by Khoa-NT** [raspberrypi/linux#2072]
Hi,

My Pi Zero W os is _Raspbian Jessie with PIXEL_ (2017-04-10)

I can ssh over wifi to my Pi zero W on my desktop ( ubuntu 16.10) in my lab
But at home, when I use my laptop ( ubuntu 14.04) to ssh over wifi , after I enter my pi's password, the terminal is frozen.
I can't Ctrl+C or do anything. Just like the process is stuck. 
I can use my mouse to close the terminal.

I tried delete file on my laptop ` ~/.ssh/known_hosts`
but It doesn't work.

Would you mind helping me ?
thank

**Comment by JamesH65** [comment]
This sort of question is better served by posting on the Raspberry Pi forums. This github tracker is for reporting bugs in the Raspberry Pi linux kernel.

https://www.raspberrypi.org/forums
