### ISSUE TITLE
lxtask 0.1.4 all -1% in CPU column on Raspberry Pi

### ISSUE THREAD

**Issue by sevillalarry** [raspberrypi/linux#208]
Got Raspberry Pi
Installed 2012-12-16-wheezy-raspbian
updated & upgraded

In lxtask v. 0.1.4, the CPU column always displays -1% on all running tasks.

**Comment by popcornmix** [comment]
We don't believe this to be a kernel issue (as top reports correctly) but probably an lxtask issue.
It's reported here:
https://github.com/asb/spindle/issues/21
