### ISSUE TITLE
Checkout kernel source

### ISSUE THREAD

**Issue by ghost** [raspberrypi/linux#2080]
Hey guys,

i have to build the kernel with version 4.9.27 and rt-preempt.
When i clone the branch 4.9.y and checkout 4.9.27 there a files lost e.g. mkknlimg...

Why are the files in 4.9.y and not in 4.9.27 but in the past as 4.9.27 was 4.9.y they are?

**Comment by pelwell** [comment]
You should be using the `rpi-4.9.y` branch from the `git@github.com:/raspberrypi/linux.git` repo, otherwise you won't be getting the Pi-specific extensions and enhancements.

Having said that, we no longer recommend using `mkknlimg` - just copy the output `zImage` to `kernel.img` or `kernel7.img`.

**Comment by popcornmix** [comment]
Make sure you are using the 4.9.27 commit from raspberrypi/rpi-4.9.y tree not the v4.9.27 tag from the upstream kernel tree which won't have Pi specific commits in.
e.g. 
```
git checkout 89f3b8d5f264d5dab9818c6667c71e3cc55b13f5
```

**Comment by ghost** [comment]
Thanks 👍 
My mistake was the wrong tree like @popcornmix  said.
