### ISSUE TITLE
Has ipvlan been removed? 

### ISSUE THREAD

**Issue by alexellis** [raspberrypi/linux#2083]
Hi, I was doing some testing with folks in the Docker community and we found the `ipvlan` Kernel module   disappears when we do an `rpi-update`. Apparently Justin Cormack from Docker Inc raised an issue here last year asking for the module to be included.

Please could it be reintroduced to the Kernel? At the moment Docker Swarm will break if we do an `dpi-update`.

Thanks,

Alex

**Comment by alexellis** [comment]
I can't find the original issue or PR - but I saw these which are related:

https://github.com/raspberrypi/linux/issues/1612 @grigorig
https://github.com/raspberrypi/linux/issues/1809 @DieterReuter

**Comment by remonlam** [comment]
Apparently it is broken for some time.

Looking at the commit logs over at [rpi-firmware](https://github.com/Hexxeh/rpi-firmware/tree/master) it appears that kernel [4.4.50-v7+](https://github.com/Hexxeh/rpi-firmware/tree/52241088c1da59a359110d39c1875cda56496764/modules/4.4.50-v7%2B/kernel/drivers/net) is the last one that has support for IPVLAN, the next kernel version [4.9.11-v7+](https://github.com/Hexxeh/rpi-firmware/tree/3e1c3e9ba2b948e6023114b9633223363da78679/modules/4.9.11-v7%2B/kernel/drivers/net) does not have IPVLAN support enabled.

If I'm correct when running `rpi-update` by default, it's using the [next branch](https://github.com/Hexxeh/rpi-firmware/tree/next/modules/4.9.13-v7%2B/kernel/drivers/net), however this is also without IPVLAN support enabled.

**Comment by JamesH65** [comment]
@popcornmix Was this omitted deliberately or can we re-add it?

**Comment by wedi** [comment]
Are there any news about this?

**Comment by popcornmix** [comment]
I assume this is ``CONFIG_IPVLAN``?
It depends on ``CONFIG_NET_L3_MASTER_DEV`` which isn't currently enabled.
That's a bool so does add some extra core code, but doesn't look too much.
@pelwell any objections?

**Comment by pelwell** [comment]
No objections - go for it.

**Comment by alexellis** [comment]
Thanks guys. Any idea why this took 9 months for an actionable response?

**Comment by pelwell** [comment]
Because although this is probably the most important issue in the world to you, we have lots of other issues to look at, and occasionally one gets forgotten.

**Comment by pelwell** [comment]
Why did it take a third party to remind us?

**Comment by popcornmix** [comment]
Every option requested has some cost (the kernel gets a little bigger, extra modules on the sdcard, free memory goes down, possible increased CPU overhead, chance of unwanted side effects) so there is generally a little reluctance to add every option immediately.
Some options are easier to accept (the cost being just a small extra modules on sdcard), but this sort is trickier (it requires an ``=y`` option which adds extra code even when users are not using this feature).

Tricky options without an obvious benefit to a lot of users tend to fall into the "investigate when not busy" category, which doesn't get serviced very often. Encouraging other users who would benefit from the option to post here might help. An occasional reminder is also okay.

Anyway, latest rpi-update kernel has this option enabled. Let us know if it solves your request.

**Comment by wedi** [comment]
Thank you very much for your quick response. Works like a charm. :+1:
