### ISSUE TITLE
disagrees about version of symbol module_layout

### ISSUE THREAD

**Issue by sgbihu** [raspberrypi/linux#2088]
I have an issue when I try to build my module. 
The below command can't get the latest release header files. But it can't get the latest release version. It seem get the latest version on the git. It doesn't match the kernel. 
`sudo apt-get install raspberrypi-kernel-headers`

I get the header file from below link and install with dpkg -i linux-headers-4.4.50-v7+_4.4.50-v7+-2_armhf.deb
https://www.niksula.hut.fi/~mhiienka/Rpi/linux-headers-rpi/

The module can build success. But it has an error when execute insmod. 
`insmod: ERROR: could not insert module ads1256.ko: Invalid module format
`
The dmesg output:
`[26799.457745] ads1256: disagrees about version of symbol module_layout`

From the internet, I found the reason is Module.symvers. But I can't get the correct version and it has error if I replace it in /usr/src/linux-headers-4.4.50-v7+

The modinfo's output is :
```
srcversion:     D296FFBC2CCC13478F31574
alias:          of:N*T*Cads1256*
alias:          spi:ads1256
depends:        industrialio
vermagic:       4.4.50-v7 SMP mod_unload modversions ARMv7
```

 ```
uname -a
Linux raspberrypi 4.4.50-v7+ #970 SMP Mon Feb 20 19:18:29 GMT 2017 armv7l GNU/Linux

```
I used the latest release. So how to make my own module works and get the correct header files?

**Comment by JamesH65** [comment]
I believe this should be OK on the latest Raspbian release and Stretch.
