### ISSUE TITLE
mmc_block quirks possibly not correct in 4.9

### ISSUE THREAD

**Issue by jorisvergeer** [raspberrypi/linux#2090]
commit https://github.com/raspberrypi/linux/commit/04ddf9031a62eaf7048e5920d1e3a621aa7fcade changes some quirk presets in the mmc block driver in 4.4.

This patch is not done in 4.9

Some kingston cards of type "broken" SD16G ended up in my production and were corrupted after an update. They do not get corrupted if add to cmdline.txt:
mmcblk.mmc_quirks=0x80000000 mmc_block.mmc_quirks=0x80000000 

I do not know the history of the driver between 4.4 and 4.9 but maybe this patch should also be done in 4.9.

Related:
If this does not matter, then does the whole fixup thing actually work? It seems to not be enabled without explicitly adding the lines to cmdline.txt. At least for this specific kingston card. (manfid: 0x000041, oemid: 0x3432, name: SD16G)

**Comment by pelwell** [comment]
Yes, that fixing commit got lost in the switch to 4.9. The two should really be squashed together.

It's in rpi-4.9.y now.

**Comment by pelwell** [comment]
This patch is in the latest rpi-update kernel. Please test, then close if appropriate.

**Comment by jorisvergeer** [comment]
@pelwell I can confirm that in 4.9.35 the quirk works without specifying it explicitly in the cmdline.txt
