### ISSUE TITLE
USB video class (webcam) support

### ISSUE THREAD

**Issue by maxnet** [raspberrypi/linux#21]
Was wondering if USB video class support (universal protocol that most modern webcams use) could be added to the default configuration.
So that people wanting to play with webcams do not have to build their own kernel modules.

From menuconfig select:

"device drivers" -> "multimedia support" -> "video for linux"
"device drivers" -> "multimedia support" -> "video for linux" -> "video capture adapters" -> "V4L usb devices" -> "USB video class (UVC)" 

Generates the following options:

CONFIG_MEDIA_SUPPORT=y
CONFIG_VIDEO_DEV=m
CONFIG_VIDEO_V4L2_COMMON=m
CONFIG_VIDEO_MEDIA=m
CONFIG_VIDEO_V4L2=m
CONFIG_VIDEO_CAPTURE_DRIVERS=y
CONFIG_V4L_USB_DRIVERS=y
CONFIG_USB_VIDEO_CLASS=m
CONFIG_USB_VIDEO_CLASS_INPUT_EVDEV=y

**Comment by popcornmix** [comment]
Thanks for the clearly defined request. I should be able to add this.
Out of interest, have you had any success with this? Any specific hardware working?

**Comment by maxnet** [comment]
To be honest: I have not tested it on an actual device, as my Raspberry has not arrived yet.
Just playing a bit with QEMU and noticed the modules lacking in /lib/modules.

I did build the exact same modules to hook up a webcam to my ARM-based NAS device recently, so that's why I know which settings are needed, and have good faith they will work just fine for the Raspberry as well.
In the case of my NAS I'm using a Microsoft Lifecam HD-5000 laptop camera.
Webcam sends a series of JPEG compressed frames at 30 fps 720p.
CPU usage to dump those to disk, or serve them to a webbrowser is only about 3% on my NAS (1,2 Ghz Marvell 6281 ARM CPU).
So as long as you are not doing any advanced image processing or transcoding, I suspect a Raspberry to be fast enough as well.

**Comment by XECDesign** [comment]
@popcornmix, people on the IRC channel have had success with uvc webcams:

gurgalof: just takes like 9%cpu to stream 320x240 30fps
ShiftPlusOne: gurgalof, which uvc webcam did you try that was working?
gurgalof: ShiftPlusOne, http://www.logitech.com/en-us/435/204 this one

**Comment by azbesthu** [comment]
I tried arch distro that uses this kernel with some patches and built with v4l support. I had success with an rtl2832u dvb-t tuner and hts-tvheadend. The dvb driver and hts-tvheadend built from source.
Streaming one SD 2-3Mbps h264 tv channel with conax decryption used 30% cpu power. Streaming an HD 6-8Mbps h264 free-to-air channel used 60% cpu power. Maybe it can be better with hardfp.

Unfortunately I was not able to use the latest dvb drivers:
http://www.linuxtv.org/wiki/index.php/How_to_Obtain,_Build_and_Install_V4L-DVB_Device_Drivers
Because after installation I had "disagrees about version of symbol" errors with my it9135 tuner:
https://gist.github.com/2699586

**Comment by popcornmix** [comment]
I've pushed support for usb webcams to linux source tree.
I had success with a "Genius i-Look 1321" and could run Cheese (which was very slow, but produced pictures).
Binary kernel will be pushed later today.

**Comment by popcornmix** [comment]
Pre built kernel pushed to firmware github. Please report if working.

**Comment by maxnet** [comment]
Finally got a real device, and can report my uvc cam works in principle with the binary kernel from firmware github.

Only when running headless and not having anything else hooked up to usb though (no keyboard, no mouse).
If I do have anything else attached the webcam capture stops after a second or so.
dmesg then also show a eth0 error (even though I'm not using the network at that time).

```
==
usb 1-1.2: new high speed USB device number 13 using dwc_otg
usb 1-1.2: New USB device found, idVendor=045e, idProduct=076f
usb 1-1.2: New USB device strings: Mfr=1, Product=2, SerialNumber=0
usb 1-1.2: Product: Microsoft® LifeCam HD-6000 for Notebooks
usb 1-1.2: Manufacturer: Microsoft
uvcvideo: Found UVC 1.00 device Microsoft® LifeCam HD-6000 for Notebooks (045e:076f)
input: Microsoft® LifeCam HD-6000 for as /devices/platform/bcm2708_usb/usb1/1-1/1-1.2/1-1.2:1.0/input/input8
13:3:1: cannot get freq at ep 0x82
smsc95xx 1-1.1:1.0: eth0: Failed to read register index 0x00000114
smsc95xx 1-1.1:1.0: eth0: Failed to write register index 0x00000114
==
```

A sign it is consuming too much power and tripped the usb fuse?

**Comment by popcornmix** [comment]
Very likely. Can you connect it though powered usb hub?

**Comment by maxnet** [comment]
May get one later, but don't have any powered hubs laying around, so cannot test that atm.

**Comment by maxnet** [comment]
Obtained a 2 amp powered hub

The good news is that it now continues capturing, so I think the power problem is solved.

The bad news is that I still get (multiple) "eth0 failed to read/write register index" messages.
And if I actually do anything that uses the network during capturing (e.g. open up a browser), the entire system hangs quickly (mouse cursor no longer moves, leds on the USB hub indicate it lost connection)
