### ISSUE TITLE
gpu_mem=24 in config.txt prevents booting

### ISSUE THREAD

**Issue by zerxy** [raspberrypi/linux#212]
gpu_mem=24 in config.txt prevents booting on my 256 MB Raspberry Pi.  Operating system is fully up-to-date using rpi-update.

**Comment by popcornmix** [comment]
Yes, 24 uses the non-cutdown configuration, and there isn't enough memory for GPU to boot fully.
I'll make it switch to start_cd.elf earlier (<32M) so this case still boots.

**Comment by popcornmix** [comment]
This has been done for some time. Closing.
