### ISSUE TITLE
Sysrq not working over serial line

### ISSUE THREAD

**Issue by piso77** [raspberrypi/linux#2142]
While debugging another issue (and trying to use the sysrq over serial) i found it to be not working:

raspberrypi login: 
Raspbian GNU/Linux 8 raspberrypi ttyS0

raspberrypi login: ~#���������

this is the output of a sysrq req command invoked via serial line: BREAK + s for example, and after that the serial console is dead.

I tried different serial terminal adapters (cu, screen and minicom) but the result is always garbage and a dead serial.

On the other hand, invoking sysrq via /sys over ssh works:

pi@raspberrypi:~ $ uname -a
Linux raspberrypi 4.9.35-v7+ #1014 SMP Fri Jun 30 14:47:43 BST 2017 armv7l GNU/Linux
pi@raspberrypi:~ $ sudo bash
root@raspberrypi:/home/pi# echo s > /proc/sysrq-trigger

...
[  335.987115] sysrq: SysRq : Emergency Sync
[  336.005982] Emergency Sync complete
...

/boot/config.txt:
...
enable_uart=1

This on a fresh raspbian image just reinstalled and upgraded. Any idea?

**Comment by P33M** [comment]
Are you using a Pi 3?

**Comment by kukabu** [comment]
I think it's because CONFIG_MAGIC_SYSRQ_SERIAL=n

**Comment by piso77** [comment]
Yes, pi3 and there's no such a knob as MAGIC_SYSRQ_SERIAL in the entire Linux kernel

**Comment by piso77** [comment]
Oh, and by shutting down the board after invoking it via serial, the entire shut down messages are all garbage:

raspberrypi login: ~#������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������

this led me to think that the serial driver / line is really messed up after the sysrq invokation.

**Comment by P33M** [comment]
The mini UART doesn't support reception of BREAK line status (constant 0 on the UART RXD line). It will just spam NUL characters at you, filling up console buffers as it does so.

What happens if you swap to using the PL011 UART? In config.txt:
```
enable_uart=1
dtoverlay=pi3-disable-bt
```

**Comment by pelwell** [comment]
Or dtovrr

**Comment by piso77** [comment]
Yes, with the pi3-disable-bt it works - thanks

**Comment by pelwell** [comment]
You can also use `dtoverlay=pi3-miniuart-bt` if you want to use Bluetooth for keyboards and mice, etc.
