### ISSUE TITLE
how to add patches to your git hub account

### ISSUE THREAD

**Issue by bathinirakesh** [raspberrypi/linux#2145]
Is there any maintainer to review the patches?
I did changes in(4.12.y) bcm2837.dtsi and bcm2837-rpi-3-b.dts, and enabled  bluetooth,audio and wifi, so i want to add  that patches to tour raspberrypi github account. 
so could  you give information to how add that patches

Thanks 
Rakesh

**Comment by JamesH65** [comment]
You need to do a pull request, from your github to this one. Then the PR will be reviewed, and if acceptable and its something we want, will be merged.
