### ISSUE TITLE
Missing tags

### ISSUE THREAD

**Issue by sebknzl** [raspberrypi/linux#2148]
Hi,

Not all released kernel versions (raspberrypi-kernel debs) are tagged here in the repository.
E.g., there's no "1.20161125-1", among others.

Regards,
Seb.

**Comment by JamesH65** [comment]
Kernel trees are on the Raspberry Pi github page.

**Comment by popcornmix** [comment]
Ping @XECDesign who adds the kernel tags.

**Comment by XECDesign** [comment]
Should be fine now.
