### ISSUE TITLE
I2C clock speed isn't set per-device

### ISSUE THREAD

**Issue by rfmerrill** [raspberrypi/linux#215]
That is, you can't set different clock speeds on i2c-0 and i2c-1. This is an issue for me because I have some devices that I want to run at 400kHz for performance reasons and others that must be run at 100kHz.

Am I just unfamiliar with how module parameters work?

**Comment by rfmerrill** [comment]
To clarify, I mean per bus, not per device on bus.

**Comment by bitflippersanonymous** [comment]
I can confirm that's the way it's coded, but separate dividers are supported by the hardware.

sysfs baudrate parameter is here: /sys/module/i2c_bcm2708/parameters/baudrate
One for the whole controller, not per bus.

The clock divider is set in linux/drivers/i2c/busses/i2c-bcm2708.c bcm2708_bsc_setup
        bcm2708_wr(bi, BSC_DIV, cdiv);

It seems like the i2c-bcm2708 driver should keep the baudrate in the per-device data.

The datasheet section 3.2 shows each BCM has a separate clock divider control register.   0x7E20_5014 and 0x7E80_4014.

**Comment by bitflippersanonymous** [comment]
Try this:
sudo su
echo bcm2708_i2c.0 > /sys/bus/platform/drivers/bcm2708_i2c/unbind
echo 10000 > /sys/module/i2c_bcm2708/parameters/baudrate
echo bcm2708_i2c.0 > /sys/bus/platform/drivers/bcm2708_i2c/bind

dmesg | tail
[69836.311382] bcm2708_i2c bcm2708_i2c.0: BSC0 Controller at 0x20205000 (irq 79) (baudrate 10k)

**Comment by brabl2** [comment]
Using the commands above, both the i2c-0 and i2c-1 busses use the new baudrate.
Verified simply by 'time i2cdetect -y 0' and 'time i2cdetect -y 1'
So this method is not usable for setting different baudrates.

**Comment by Ruffio** [comment]
@rfmerrill has this issue been resolved? If yes, please close it. thanks.

**Comment by rfmerrill** [comment]
I no longer have a raspi in my possession so I don't know. If someone else believes it is now working feel free to close it.

**Comment by brabl2** [comment]
The Device Tree is used in current versions of the kernel, so it is very easy to use different speeds for each i2c channel (/boot/config.txt):
dtparam=i2c_arm=on
dtparam=i2c_arm_baudrate=9000
dtparam=i2c_vc=on
dtparam=i2c_vc_baudrate=50000
My suggestion is: close this issue.

**Comment by rfmerrill** [comment]
Done.
