### ISSUE TITLE
rt2x00 fails for rt2870

### ISSUE THREAD

**Issue by callegar** [raspberrypi/linux#216]
I wonder if this is an upstream kernel bug or something related to the arm build.

Wireless dongles with rt2870 sta do not work on the raspberry pi, but work perfectly on x86 (32, 64) PCs with the linux kernel.

Should not be a power issue: I'm powering with a high power powered usb hub.
Not specific to the specific 3.2.27 kernel version. Tried a recent 3.6.11 for the raspberry and it is the same.

kernel logs throw tons of 

Error - Vendor Request 0x07 failed for offset 0x0208 with error -71

offset changes and sometimes error is 19

When this happens all the network infrastructure stops working (cannot use the ethernet) and some commands hang forever: iwconfig, ifconfig, sudo.

**Comment by licaon-kter** [comment]
On my amd64 desktop I use the Ralink provided driver ( http://www.mediatek.com/_en/07_downloads/01_windows.php?sn=501 ) as I found that the kernel driver, at least when I bought my TL-WN321G ( 0x148F,0x2070 ) around kernel 2.6.36, was dropping my ad-hoc connection after a few minutes.

I get the latest driver from time to time, now it's RT5572 USB (10/22/2012) 2.6.1.3 ( on my amd64 system it kernel panics on module loading ooops, but older version 2.6.0.1 http://fbx.ro/as63ebkwyje7bv9a works fine ), yeah it says rt5572 but it supports rt2870 and my rt2070 if I just add my chipset id in line 39 of _ralinkdriver/common/rtusb_dev_id.c_ in the supported devices list **{USB_DEVICE(0x148F,0x2070)},**

Also of note, DO NOT remove the -DDBG option as the driver strangely will not compile without it, this will mean you will get **plenty** of syslog messages!

I never got around to compile this on my PI as I was missing some libs and the wired link worked fine, I'll try to find some time to mess with this in the next few days.

**Comment by callegar** [comment]
Ralink or mediatek driver for 2870 does not compile against 3.x kernels. If I'll have time I'll give the 5572 driver a try. But the tons of syslog messages are not a nice thing to have on the rasp pi.

In the meantime, can someone do an independent check of RT2870 with the in-kernel driver and confirm or unconfirm the bug? If there is really a bug related to the driver code on arm it should probably be propagated upstream.

**Comment by root42** [comment]
I also have problems with a rt2870 based device. I am discussing it over at Stackexchange (http://raspberrypi.stackexchange.com/questions/5364/wifi-connection-gets-dropped-very-often-with-edimax-ew-7711utn), and have lots of weird problems with this device. It works for a limited time, and then either the whole machine freezes or I get weird ssh messages like "disconnect, packet corrupt". Networking via built-in ethernet seems fine, no problems so far. Thr rt2870 is using the following modules:

```
rt2800usb              14940  0                              
rt2800lib              55351  1 rt2800usb                    
rt2x00usb              11215  1 rt2800usb                    
rt2x00lib              42334  3 rt2x00usb,rt2800lib,rt2800usb
```

**Comment by root42** [comment]
Trying to compile the module does not work, I guess I am missing part of the kernel sources:

```
pi@raspberrypi ~/Downloads/DPO_RT5572_LinuxSTA_2.6.1.3_20121022 $ make                                            
make -C tools                                                                                                     
make[1]: Entering directory `/home/pi/Downloads/DPO_RT5572_LinuxSTA_2.6.1.3_20121022/tools'                       
gcc -g bin2h.c -o bin2h                                                                                           
make[1]: Leaving directory `/home/pi/Downloads/DPO_RT5572_LinuxSTA_2.6.1.3_20121022/tools'                        
/home/pi/Downloads/DPO_RT5572_LinuxSTA_2.6.1.3_20121022/tools/bin2h                                               
cp -f os/linux/Makefile.6 /home/pi/Downloads/DPO_RT5572_LinuxSTA_2.6.1.3_20121022/os/linux/Makefile               
make -C /lib/modules/3.6.11+/build SUBDIRS=/home/pi/Downloads/DPO_RT5572_LinuxSTA_2.6.1.3_20121022/os/linux modules                                                                                                                 
make: *** /lib/modules/3.6.11+/build: No such file or directory.  Stop.                                           
make: *** [LINUX] Error 2
```

**Comment by P33M** [comment]
Retest with latest kernel, if this is still an issue.
