### ISSUE TITLE
block2mtd support?

### ISSUE THREAD

**Issue by nwf** [raspberrypi/linux#2163]
Could we get `CONFIG_MTD_BLOCK2MTD` kicked to `m` by default in subsequent builds?  It would be very useful to enable `ubifs` filesystems on sdcards for the crc32 checksums and transparent compression, which would allow smaller sdcards to be useful.

I hope to add support for ubifs root to https://github.com/debian-pi/raspbian-ua-netinst; I recognize that it will require an initramfs to load the `block2mtd` and `ubifs` modules.

ETA: On second thought, perhaps this is better filed against https://github.com/raspberrypi/firmware?  Please advise. :)

**Comment by popcornmix** [comment]
This repo is correct for requesting kernel config options.
The option looks reasonable to me - @pelwell any concerns?

**Comment by pelwell** [comment]
No concerns. It adds 400KB of modules, but that's not so much.

**Comment by JamesH65** [comment]
@popcornmix Was this added?

**Comment by nwf** [comment]
Ping?

**Comment by pelwell** [comment]
It will be in the next firmware release.

**Comment by nwf** [comment]
Thanks!
