### ISSUE TITLE
Is the hauppauge wintv dualhd fully supported (both tuners)? 

### ISSUE THREAD

**Issue by AlBundy33** [raspberrypi/linux#2168]
It seems that there are some patches to get both tuners to work. 
https://patchwork.kernel.org/patch/8741651/

and here are some additional patches https://github.com/b-rad-NDi/Ubuntu-media-tree-kernel-builder/tree/master/patches/ubuntu-zesty-4.10.0/extra

**Comment by AlBundy33** [comment]
Found this #2091 - does this mean that the tuner is currently not supported or only the second tuner is not supported?

**Comment by JamesH65** [comment]
We don't tend to give support for specific third party peripherals, and I
don't believe we have this particular device in house to test. @Popcornmix
may have some ideas as he works with Kodi.

Google is probably your best bet to see if anyone has tried this setup.

**Comment by 6by9** [comment]
There are the sets of patches you linked to kicking around.
The first is merged in 4.11 to support a single tuner on the WinTV-dualHD - you're free to build that tree from here, or IIRC OpenElec is using a more recent kernel so may already be suitable.
The second set of patches have not been pushed for review upstream, so as pelwell and popcornmix state on the PR, it's unlikely they'll get merged into the Pi tree.

Having said that, taking the two sets of patches does seem to give a system with WinTV-dualHD working (I have a pair of them that seem to work OK with tvheadend and the Pi 4.9 kernel. I'm currently having issues with it on Ubuntu 16.04 and rebuilding top-of-tree media_build tree)

**Comment by 6by9** [comment]
To relay info on what's happening upstream - http://www.spinics.net/lists/linux-media/msg121493.html

My experience is that I have a pair of them on an Ubuntu 17.04 HP Microserver now for about a fortnight, and it's been stable.
Whilst I had them running on the Pi, tvheadend was misbehaving. However I think that was down to trying to save everything over NFS to the NAS, and it was spinning up the RAID array too slowly. I might have another play at a later date using local storage.

**Comment by JamesH65** [comment]
@6by9 Any thing/progress to report on this?

**Comment by 6by9** [comment]
Action is all upstream. It's still not merged - radio silence since September when I posted the update.
Looking through his list of issues, I do see issue 29 saying he's been fixing checkpatch complaints and will begin sending them to the mailing list, so it may not be far off.

Ubuntu kept on updating the kernel on me, and I got bored of recompiling all the media drivers, so my setup is back to running them as single tuners.

**Comment by JamesH65** [comment]
@6by9 Did this ever make it through upstreaming?

**Comment by 6by9** [comment]
It's all upstream - can't recall which release it will have hit, although there have been a number of followups.

#2434 was me attempting to backport, but whilst early revisions worked the current state is broken, and I haven't had the energy to go messing in the evenings (no TV aerial in the office that I'm aware of).
