### ISSUE TITLE
Cannot route boot kernel logs to any console tty

### ISSUE THREAD

**Issue by this-self** [raspberrypi/linux#2170]
When I try to edit the param `console=tty3` with tty3 - the boot messages still going on tty1.
Also I tried this params `quiet logo.nologo loglevel=0`
But nothing. Text still out on tty1. Earlier (on kernel 4.4.y) it works as well.

**Comment by pelwell** [comment]
If I use `console=tty3` I also see kernel output, but with a non-existent console (`blah`,  etc.) or deleting (or renaming) the `console=` assignment the output disappears. Some console output does appear later, but that comes from `systemd`.

I suggest you delete the assignment.

**Comment by this-self** [comment]
@pelwell Thanks. That's works for me.
