### ISSUE TITLE
Unique local static IPv6 address issue on Rasbian Stretch

### ISSUE THREAD

**Issue by antoniosk** [raspberrypi/linux#2174]
Setting a static IPv4 configuration (address, mask, gateway) through dhcpcd.conf works perfectly. When I am trying to set a static IPv6 configuration on /etc/network/interfaces, the IPv6 configuration is not applied.

As a workaround I am doing an ifdown / ifup after restart. Restarting networking.service has no effect.

The very same configuration is working flawlessly in Debian/Rasbian Jessie and Debian Stretch. I installed Rasbian Stretch with Desktop (released on 2017-08-16) from scratch using the dd command.

**Comment by XECDesign** [comment]
Not a kernel issue. You should report it here https://github.com/RPi-Distro/repo/issues, providing more information. For example, what does your interfaces file look like.
