### ISSUE TITLE
Raspberrypi onboard wifi doesn't work (4.12-y)

### ISSUE THREAD

**Issue by yfang1644** [raspberrypi/linux#2179]
I'm compiling kernel 4.12.9 (arm64). The modules  brcmfmac and  brcmutil are installed,
but the wifi doesn't work.  kernel-4.11-y works find.

**Comment by UMRnInside** [comment]
See issue #2124,it **MIGHT** be helpful.

**Comment by yfang1644** [comment]
It's really helpful. Many thanks!

**Comment by popcornmix** [comment]
Closing this as duplicate of #2124
