### ISSUE TITLE
gtk+css problem

### ISSUE THREAD

**Issue by joukeHijlkema** [raspberrypi/linux#2183]
Hi all,

I have a problem with gtk+ version 3.22.11 on a raspberry pi running raspbian.
Not sure if this is the right place so please tell me if I have to ask somewhere else.

I build a small test GUI with glade (see debug.glade) and a python demo (debug.py) using a css (test.css) to change the fontsize of a label.

This works fine on my PC running Ubuntu and Gtk version version 3.18.9 (see PC.png) but the font size change is ignored on my RPI (see RPI.png)

The question is: is this a GTK issue or a raspbian issue ?

Thanks for your help,

Jouke

[debug.zip](https://github.com/raspberrypi/linux/files/1264144/debug.zip)

**Comment by pelwell** [comment]
This is definitely not the right place - try the Graphics Programming forum: https://www.raspberrypi.org/forums/viewforum.php?f=67
