### ISSUE TITLE
udevadm causes system crash

### ISSUE THREAD

**Issue by schlimmchen** [raspberrypi/linux#221]
Originally posted at launchpad: https://bugs.launchpad.net/raspbian/+bug/1031674

Raspbian crashes when using udevadm to list properties of usb flash sticks (when using option "--atribute-walk").

Fails:
udevadm info --name=/dev/sda --attribute-walk

Works:
udevadm info --name=/dev/sda
udevadm info --name=/dev/mmcblk0 --attribute-walk

Seems to be an issue when probing "/devices/platform/bcm2708_usb".

![IMG_20130212_211833-1](https://f.cloud.github.com/assets/3578416/150555/6b227846-7555-11e2-8bf6-92039b4dcc69.jpg)

**Comment by ghollingworth** [comment]
believe this is now fixed in raspberrypi/firmware #21
