### ISSUE TITLE
stream video from dvd player to raspberrypi

### ISSUE THREAD

**Issue by bs1278** [raspberrypi/linux#2210]
am trying to stream videos from external sources to rasberrypi,when i stream with mjpg streamer it works well for me now i'm trying to stream videos from dvd player to rasberrypi,

When I tried to stream the video from UVC Video Capture card to my laptop (Windows 7),using mjpg streamer it works well for me.tha titme i was given usb cam as an input source but for now dvd player(what ever the video i played in player that thing will be streamed into raspberrypi) how can i stream my video from dvd player to rasberrypi.

If it is possible to record that video how can i achieve that one also.

**Comment by popcornmix** [comment]
Sorry, this repo is for reporting bugs in the linux kernel. 
For issues with using higher level pieces of software you should start at the [forum](https://www.raspberrypi.org/forums/index.php).
