### ISSUE TITLE
Kernel panic when two processes write to two i2c buses (but only sometimes)

### ISSUE THREAD

**Issue by rfmerrill** [raspberrypi/linux#222]
Here's the code I'm using:

http://shiranui.lt3m.com/picrash/

Enable the i2c driver, with baud rate set to 400000, Compile both .c files and run:

./kracksplit ./krackoutput /dev/i2c-0 /dev/i2c-1 < ./kracktest.out

On my pi (raspbian, just did apt-get upgrade) this produces a kernel panic every time. Unfortunately the composite video out doesn't give me enough lines to give you a full kernel panic message and I don't have the means to get the serial console going.

I'll have more info for you hopefully within a week but I thought I'd open the issue right away in case you can investigate on your own.

Interestingly, all of my attempts to create simpler test cases have failed.

**Comment by popcornmix** [comment]
I tried your program:

```
....
Sending to address 20 (chars 14)
Sending to address 21 (chars 15)
Sending to address 22 (chars 16)
Sending to address 23 (chars 17)
Sending to address 24 (chars 18)
Sending to address 25 (chars 19)
Sending to address 26 (chars 1A)
Sending to address 27 (chars 1B)
Sending to address 28 (chars 1C)
Sending to address 29 (chars 1D)
Sending to address 30 (chars 1E)
Sending to address 30 (chars 1E)
```

nothing bad in dmesg log.
Do I need any connected hardware?

**Comment by rfmerrill** [comment]
Hmm, interesting... no, no connected hardware.

Do you have the i2c-dev module loaded?

**Comment by popcornmix** [comment]
I had it blacklisted. Removed the blacklist. Rebooted.  sudo modprobe i2c-dev.  sudo chmod 777  /dev/i2c-*

```
lsmod | grep i2c
i2c_dev                 5620  0
i2c_bcm2708             3759  0
ls -l /dev/i2c-*
crwxrwxrwx 1 root root 89, 0 Feb 13 17:47 /dev/i2c-0
crwxrwxrwx 1 root root 89, 1 Feb 13 17:47 /dev/i2c-1
```

but still no panic...

**Comment by rfmerrill** [comment]
How are you invoking it?

**Comment by rfmerrill** [comment]
Do you have the baud rate set to 400kHz? You have to set a module parameter to do that.

**Comment by rfmerrill** [comment]
So I just got serial console working. Turns out the error is "unable to handle kernel paging request". I might just be running out of swap space or something... going to try adding more swap on an external USB stick.

**Comment by rfmerrill** [comment]
Here's a backtrace for you:

http://pastebin.com/YMfk8mPa

**Comment by rfmerrill** [comment]
uname -a gives: Linux raspberrypi 3.6.11+ #371 PREEMPT Thu Feb 7 16:31:35 GMT 2013 armv6l GNU/Linux

**Comment by rfmerrill** [comment]
Just tested it on my other Pi (same SD card), and it doesn't happen, so it looks like I probably damaged the first one at some point. Never mind!
