### ISSUE TITLE
raspi-config behaves strangely when one tries to desactivate VNC

### ISSUE THREAD

**Issue by ussmarc** [raspberrypi/linux#2225]
I've noticed two small bugs in the version of **raspi-config** that ships with the **2017-09-07** version of Raspbian. To reproduce the first one, install a fresh copy of 2017-09-07-raspbian-stretch-lite.img on a card and boot the Pi. Launch raspi-config, and try to explicitly desactivate VNC : raspi-config replies that VNC is **enabled**, which is the exact opposite of what one wanted to do.

Then (to reproduce the second bug), try to update raspi-config to the latest available version, which is a little more recent than the one included in the 2017-09-07 image, and try to desactivate VNC again : raspi-config replies that VNC is... <nothing at all> (an empty string is displayed instead of the word "desactivated").

**Comment by pelwell** [comment]
Can you report this at the [raspi-config issues page](https://github.com/RPi-Distro/raspi-config/issues)? Thanks.
