### ISSUE TITLE
Adding lan78xx driver module

### ISSUE THREAD

**Issue by Isaturley** [raspberrypi/linux#2232]
We have requests from people that want to use a USB Ethernet device with Raspberry Pi, LAN7800.
http://www.microchip.com/wwwproducts/en/LAN7800

Can you add:
CONFIG_USB_LAN78XX=m

**Comment by pelwell** [comment]
That option just adds a small-to-medium-sized module (50KB) - not a problem.

Done.

**Comment by JamesH65** [comment]
Fixed, closing.
