### ISSUE TITLE
USB Gadget support for DVD-ROM emulation

### ISSUE THREAD

**Issue by ziotibia81** [raspberrypi/linux#2238]
Cold be nice to have kernel patched to enable DVD-ROM support on g_mass_storage module.

Reference patchs:

http://linuxehacking.ovh/2013/07/12/how-to-emulatore-dvd-rom-hardware-usb/
https://lkml.org/lkml/2015/3/7/388

**Comment by pelwell** [comment]
We aren't going to apply any new patches to upstream code unless absolutely necessary, so unless you can get this (or a similar patch) accepted upstream you are going to be disappointed.
