### ISSUE TITLE
USB HID issues with MiMo

### ISSUE THREAD

**Issue by erazor83** [raspberrypi/linux#224]
Hi all,

I was trying to set up a little kiosk PC with a raspberry and one of these USB-Touch-Monitors (MiMo).

The MiMo works perfectly on a normal PC but somehow on the raspberry the usbtouchscreen hid driver does not work.

I've compiled my kernel with debugging for usb enabled and am getting these messages:

<pre>
[    2.907285] usb 1-1.2.2: udev 6, busnum 1, minor = 5
[    2.907322] usb 1-1.2.2: New USB device found, idVendor=17e9, idProduct=401a
[    2.909554] usb 1-1.2.2: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[    2.911731] usb 1-1.2.2: Product: nanovision MiMo
[    2.913988] usb 1-1.2.2: Manufacturer: DisplayLink
[    2.916125] usb 1-1.2.2: SerialNumber: USM700-9A130971
[    2.918836] usb 1-1.2.2: usb_probe_device
[    2.918868] usb 1-1.2.2: configuration #1 chosen from 1 choice
[    2.919640] usb 1-1.2.2: adding 1-1.2.2:1.0 (config #1, interface 0)
[    2.920175] usb 1-1.2.2: adding 1-1.2.2:1.1 (config #1, interface 1)
[    2.920471] usbhid 1-1.2.2:1.1: usb_probe_interface
[    2.920488] usbhid 1-1.2.2:1.1: usb_probe_interface - got id
[    2.978472] usbhid 1-1.2.2:1.1: looking for a minor, starting at 0
[    2.978894] hid-generic 0003:17E9:401A.0001: hiddev0: USB HID v1.10 Device [DisplayLink nanovision MiMo] on usb-bcm2708_usb-1.2.2/input1
[    2.984124] hub 1-1.2:1.0: port 3, status 0101, change 0000, 12 Mb/s
[    3.003320] hub 1-1.2:1.0: port 3 not reset yet, waiting 10ms
[    3.083311] usb 1-1.2.3: new full-speed USB device number 7 using dwc_otg
[    3.103361] hub 1-1.2:1.0: port 3 not reset yet, waiting 10ms
[    3.603124] usb 1-1.2.3: device not accepting address 7, error -71
[    3.623254] hub 1-1.2:1.0: port 3 not reset yet, waiting 10ms
[    3.703264] usb 1-1.2.3: new full-speed USB device number 8 using dwc_otg
[    3.723319] hub 1-1.2:1.0: port 3 not reset yet, waiting 10ms
[    3.803282] usb 1-1.2.3: device descriptor read/64, error -71
[    3.933312] hub 1-1.2:1.0: port 3 not reset yet, waiting 10ms
[    4.013301] usb 1-1.2.3: device descriptor read/64, error -71
[    4.203334] usb 1-1.2.3: new full-speed USB device number 9 using dwc_otg
[    4.623133] usb 1-1.2.3: device not accepting address 9, error -71
[    4.643270] hub 1-1.2:1.0: port 3 not reset yet, waiting 10ms
[    4.723266] usb 1-1.2.3: new full-speed USB device number 10 using dwc_otg
[    5.143188] usb 1-1.2.3: device not accepting address 10, error -71
[    5.145492] hub 1-1.2:1.0: unable to enumerate USB device on port 3
[    5.147893] hub 1-1.2:1.0: state 7 ports 4 chg 0000 evt 0008
</pre>

The display itself works pretty nice and I'm sure It's not a power issue. Probably some issues in combination with the usbtouchscreen driver.

Maybe my lsusb output would be usefull too:

<pre>
Bus 001 Device 006: ID 17e9:401a DisplayLink 
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass            0 (Defined at Interface level)
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  idVendor           0x17e9 DisplayLink
  idProduct          0x401a 
  bcdDevice            0.07
  iManufacturer           1 DisplayLink
  iProduct                2 nanovision MiMo
  iSerial                 3 USM700-9A130971
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength           57
    bNumInterfaces          2
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xc0
      Self Powered
    MaxPower              500mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           2
      bInterfaceClass       255 Vendor Specific Class
      bInterfaceSubClass      0 
      bInterfaceProtocol      0 
      iInterface              0 
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x01  EP 1 OUT
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0200  1x 512 bytes
        bInterval               0
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x82  EP 2 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0008  1x 8 bytes
        bInterval               4
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        1
      bAlternateSetting       0
      bNumEndpoints           1
      bInterfaceClass         3 Human Interface Device
      bInterfaceSubClass      0 No Subclass
      bInterfaceProtocol      0 None
      iInterface              0 
        HID Device Descriptor:
          bLength                 9
          bDescriptorType        33
          bcdHID               1.10
          bCountryCode            0 Not supported
          bNumDescriptors         1
          bDescriptorType        34 Report
          wDescriptorLength      29
         Report Descriptors: 
           ** UNAVAILABLE **
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x85  EP 5 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0010  1x 16 bytes
        bInterval               4
Device Qualifier (for other device speed):
  bLength                10
  bDescriptorType         6
  bcdUSB               2.00
  bDeviceClass            0 (Defined at Interface level)
  bDeviceSubClass         0 
  bDeviceProtocol         0 
  bMaxPacketSize0        64
  bNumConfigurations      1
Device Status:     0x0000
  (Bus Powered)
</pre> 

I also tried
 <pre>
dwc_otg.fiq_fix_enable=0
</pre>
or
 <pre>
dwc_otg.fiq_fix_enable=1
</pre>

with no effect.

It'd be pretty cool if I could get this running. I'm open for testing.

Thanks a lot for any hints.

Regards,
Alex

**Comment by erazor83** [comment]
I think it's not just an USB-HID issue but maybe something with the integrated USB-hub of the MiMo.

Another type of these monitors are also having an uvc webcam and I'm getting similar errors with this device:

<pre>
[    2.373288] usb 1-1.3: new high-speed USB device number 4 using dwc_otg
[    2.473679] usb 1-1.3: udev 4, busnum 1, minor = 3
[    2.473722] usb 1-1.3: New USB device found, idVendor=058f, idProduct=6254
[    2.476027] usb 1-1.3: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[    2.478886] usb 1-1.3: usb_probe_device
[    2.478917] usb 1-1.3: configuration #1 chosen from 1 choice
[    2.479283] usb 1-1.3: adding 1-1.3:1.0 (config #1, interface 0)
[    2.479499] hub 1-1.3:1.0: usb_probe_interface
[    2.479516] hub 1-1.3:1.0: usb_probe_interface - got id
[    2.479530] hub 1-1.3:1.0: USB hub found
[    2.482033] hub 1-1.3:1.0: 4 ports detected
[    2.484299] hub 1-1.3:1.0: standalone hub
[    2.484332] hub 1-1.3:1.0: ganged power switching
[    2.484343] hub 1-1.3:1.0: global over-current protection
[    2.484352] hub 1-1.3:1.0: Single TT
[    2.484372] hub 1-1.3:1.0: TT requires at most 8 FS bit times (666 ns)
[    2.484382] hub 1-1.3:1.0: Port indicators are supported
[    2.484392] hub 1-1.3:1.0: power on to power good time: 100ms
[    2.484917] hub 1-1.3:1.0: local power source is good
[    2.484947] hub 1-1.3:1.0: no over-current condition exists
[    2.484963] hub 1-1.3:1.0: enabling power on all ports
[    2.583345] hub 1-1.3:1.0: port 1: status 0101 change 0001
[    2.583789] hub 1-1.3:1.0: port 3: status 0101 change 0001
[    2.584186] hub 1-1.3:1.0: port 4: status 0101 change 0001
[    2.683232] hub 1-1.3:1.0: state 7 ports 4 chg 001a evt 0000
[    2.683470] hub 1-1.3:1.0: port 1, status 0101, change 0000, 12 Mb/s
[    2.703333] hub 1-1.3:1.0: port 1 not reset yet, waiting 10ms
[    2.783321] usb 1-1.3.1: new high-speed USB device number 5 using dwc_otg
[    2.803376] hub 1-1.3:1.0: port 1 not reset yet, waiting 10ms
[    2.922918] usb 1-1.3.1: skipped 1 descriptor after configuration
[    2.922944] usb 1-1.3.1: skipped 5 descriptors after interface
[    2.922960] usb 1-1.3.1: skipped 1 descriptor after endpoint
[    2.922976] usb 1-1.3.1: skipped 10 descriptors after interface
[    2.923433] usb 1-1.3.1: default language 0x0409
[    2.924549] usb 1-1.3.1: udev 5, busnum 1, minor = 4
[    2.924571] usb 1-1.3.1: New USB device found, idVendor=0ac8, idProduct=c339
[    2.926885] usb 1-1.3.1: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[    2.929139] usb 1-1.3.1: Product: Venus USB2.0 Camera
[    2.931327] usb 1-1.3.1: Manufacturer: Vimicro Corp.
[    2.934148] usb 1-1.3.1: usb_probe_device
[    2.934179] usb 1-1.3.1: configuration #1 chosen from 1 choice
[    2.934528] usb 1-1.3.1: adding 1-1.3.1:1.0 (config #1, interface 0)
[    2.935551] usb 1-1.3.1: adding 1-1.3.1:1.1 (config #1, interface 1)
[    2.936255] hub 1-1.3:1.0: port 3, status 0101, change 0000, 12 Mb/s
[    2.953382] hub 1-1.3:1.0: port 3 not reset yet, waiting 10ms
[    3.033345] usb 1-1.3.3: new full-speed USB device number 6 using dwc_otg
[    3.053404] hub 1-1.3:1.0: port 3 not reset yet, waiting 10ms
[    3.133355] usb 1-1.3.3: device descriptor read/64, error -71
[    3.263273] hub 1-1.3:1.0: port 3 not reset yet, waiting 10ms
[    3.763156] usb 1-1.3.3: device not accepting address 6, error -71
[    3.783345] hub 1-1.3:1.0: port 3 not reset yet, waiting 10ms
[    3.863334] usb 1-1.3.3: new full-speed USB device number 7 using dwc_otg
[    3.883384] hub 1-1.3:1.0: port 3 not reset yet, waiting 10ms
[    3.963355] usb 1-1.3.3: device descriptor read/64, error -71
[    4.153386] usb 1-1.3.3: device descriptor read/64, error -71
[    4.343411] usb 1-1.3.3: new full-speed USB device number 8 using dwc_otg
[    4.763162] usb 1-1.3.3: device not accepting address 8, error -71
[    4.783338] hub 1-1.3:1.0: port 3 not reset yet, waiting 10ms
[    4.863332] usb 1-1.3.3: new full-speed USB device number 9 using dwc_otg
[    5.283154] usb 1-1.3.3: device not accepting address 9, error -71
[    5.285458] hub 1-1.3:1.0: unable to enumerate USB device on port 3
[    5.287904] hub 1-1.3:1.0: port 4, status 0101, change 0000, 12 Mb/s
[    5.303305] hub 1-1.3:1.0: port 4 not reset yet, waiting 10ms
[    5.383261] usb 1-1.3.4: new high-speed USB device number 10 using dwc_otg
[    5.403285] hub 1-1.3:1.0: port 4 not reset yet, waiting 10ms
[    5.504850] usb 1-1.3.4: skipped 1 descriptor after interface
[    5.505382] usb 1-1.3.4: default language 0x0409
[    5.507287] usb 1-1.3.4: udev 10, busnum 1, minor = 9
[    5.507323] usb 1-1.3.4: New USB device found, idVendor=17e9, idProduct=401a
[    5.509360] usb 1-1.3.4: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[    5.511329] usb 1-1.3.4: Product: nanovision MiMo
[    5.513382] usb 1-1.3.4: Manufacturer: DisplayLink
[    5.515312] usb 1-1.3.4: SerialNumber: USM700-91260327
[    5.517798] usb 1-1.3.4: usb_probe_device
[    5.517844] usb 1-1.3.4: configuration #1 chosen from 1 choice
[    5.518648] usb 1-1.3.4: adding 1-1.3.4:1.0 (config #1, interface 0)
[    5.519167] usb 1-1.3.4: adding 1-1.3.4:1.1 (config #1, interface 1)
[    5.519450] usbhid 1-1.3.4:1.1: usb_probe_interface
[    5.519468] usbhid 1-1.3.4:1.1: usb_probe_interface - got id
[    5.577426] usbhid 1-1.3.4:1.1: looking for a minor, starting at 0
[    5.577879] hid-generic 0003:17E9:401A.0001: hiddev0: USB HID v1.10 Device [DisplayLink nanovision MiMo] on usb-bcm2708_usb-1.3.4/input1
[   15.900037] udlfb 1-1.3.4:1.0: usb_probe_interface
[   15.900064] udlfb 1-1.3.4:1.0: usb_probe_interface - got id
[   15.900096] udlfb: DisplayLink nanovision MiMo - serial #USM700-91260327
[   15.900113] udlfb: vid_17e9&pid_401a&rev_0007 driver's dlfb_data struct at db9f3000
[   15.900119] udlfb: console enable=1
[   15.900124] udlfb: fb_defio enable=1
[   15.900128] udlfb: shadow enable=1
[   15.908606] udlfb: vendor descriptor not available (-32)
[   15.910902] udlfb: allocated 4 65024 byte urbs
[   15.911686] usbcore: registered new interface driver udlfb
[   16.000258] udlfb: 800x480 @ 61 Hz valid mode
[   16.000282] udlfb: Reallocating framebuffer. Addresses will change!
[   16.002045] udlfb: 800x480 @ 61 Hz valid mode
[   16.002065] udlfb: set_par mode 800x480
[   16.035240] udlfb: DisplayLink USB device /dev/fb1 attached. 800x480 resolution. Using 1504K framebuffer memory
</pre>

**Comment by jwilker2** [comment]
Hello Alex,
Have you seen this issue: https://github.com/raspberrypi/firmware/issues/141

pssc even makes mention of the 720 in one of his posts.

 popcornmix expresses doubt in his post that there is demand for expanded udlfb for displaylink screens.

**Comment by erazor83** [comment]
Ok, works now.

Steps I've done:
- select udlfb and usbtouchscreen as module
- apply changes to usbtouchscreen ( https://github.com/raspberrypi/linux/issues/236 )
- add kernel parameter dwc_otg.speed=1
- no special udev rules for the displaylink device
- create a script which removes modules udfb and usbtouchscreen after bootup, make sure to load udlfb first (you can blacklist udlfb and usbtouchscreen)

**Comment by ghollingworth** [comment]
Worth checking again with the latest kernel Please close if fixed
