### ISSUE TITLE
bcm2709_defconfig is missing ?

### ISSUE THREAD

**Issue by pficheux** [raspberrypi/linux#2240]
Hi

It looks like bcm2709_defconfig (+ some DT files for Pi 3) are not always available in some rpi-4.9.y commits? it that normal?

thx

**Comment by pelwell** [comment]
Can you give some examples?

**Comment by pficheux** [comment]
I use commit 089d7720383d7bc9ca6b8824a05dfa66f80d1f41 for 4.9.51, then 

$ ls arch/arm/configs/bcm*defconfig
arch/arm/configs/bcm2835_defconfig

**Comment by pelwell** [comment]
That's the wrong commit - you've accidentally chosen a pure upstream tree. Look for the merge commit after the Linux version commit - that is where we pull the upstream changes into our tree.

**Comment by pficheux** [comment]
ok thx for your help.
