### ISSUE TITLE
DS2438 Support?

### ISSUE THREAD

**Issue by mypiandrew** [raspberrypi/linux#2246]
Hi!

Any chance you could back port the DS2438 1wire module down to 4.9.x branch please?

It's a really useful part as it has an ADC built in :)

https://github.com/raspberrypi/linux/blob/rpi-4.12.y/drivers/w1/slaves/w1_ds2438.c

It would be much appreciated

Thanks in advance 

Andrew.

**Comment by pelwell** [comment]
It's a clean cherry-pick that (once enabled) results in a 9KB module. Any objections to a merge, @popcornmix ?

**Comment by popcornmix** [comment]
No objection.

**Comment by pelwell** [comment]
Thanks. Merged.

**Comment by mypiandrew** [comment]
Thanks guys, much appreciated
