### ISSUE TITLE
SPI stopped working on Rpi B1 from 4.9.43+ onwards

### ISSUE THREAD

**Issue by ghost** [raspberrypi/linux#2259]
Hello,
SPI stopped working for me in the latest Raspbian stretch update. So I went back through the kernel versions here bisecting until I found the latest working version.
Latest working version for me is 4.9.41+, it does not work in 4.9.43+ anymore.
Is there a benign explanation? Did I miss a required configuration change?
Best regards,
Max

**Comment by pelwell** [comment]
Resolved in https://github.com/Hexxeh/rpi-firmware/issues/161, but the takeway is to add:
```
spi.max_speed_hz = 500000
```
after `spi.open` to restore the old default/maximum speed.
