### ISSUE TITLE
config request CONFIG_IP_SCTP

### ISSUE THREAD

**Issue by kukabu** [raspberrypi/linux#226]
Please add the sctp module.

CONFIG_IP_SCTP=m
CONFIG_SCTP_HMAC_SHA1=y

**Comment by popcornmix** [comment]
Included in latest (rpi-update) firmware.

**Comment by kukabu** [comment]
Thanks

**Comment by kukabu** [comment]
https://github.com/raspberrypi/linux/commit/cbd6672e7e1b2dc5026f5dc7929a13a9a68f2a62 why?

**Comment by popcornmix** [comment]
I don't believe it's been removed - it's just a default due to other config options.

```
zcat /proc/config.gz | grep CONFIG_IP_SCTP
CONFIG_IP_SCTP=m
```

**Comment by kukabu** [comment]
I see. Thanks.
