### ISSUE TITLE
file can't be opened

### ISSUE THREAD

**Issue by chetanp628** [raspberrypi/linux#2270]
When I apply make bcm2709_defconfig 
>> it gives file can't be opened 
>> When I go to that path, the file name was too long (used ls -l command to check)

**Comment by pelwell** [comment]
Have you followed our kernel building guide here: https://www.raspberrypi.org/documentation/linux/kernel/building.md ?

1. Which platform, and using which filing system, are you building on?
2. How did you download the kernel source? We've known people to have problems with corrupted .zip archives, so git clone is preferred.
3. Please post full error messages - they usually contain important details.
