### ISSUE TITLE
Kernel 4.14 - Enable  HID_ASUS [=m] in defconfigs

### ISSUE THREAD

**Issue by paul-1** [raspberrypi/linux#2278]
Asus branded keyboard (Including USB keyboards) have been moved from hid-chicony to hid-asus

I've enabled the module locally and compiled kernel, keyboard works fine with the new module.

**Comment by JamesH65** [comment]
@paul-1 What are you asking for here?

**Comment by JamesH65** [comment]
@popcornmix @pelwell Any objections?

**Comment by pelwell** [comment]
It's a shame, because the Asus module is over twice the size of the Chicony equivalent, but we don't want to lose support we used to have.

Done.

**Comment by paul-1** [comment]
Agreed on the bloat comment, since the asus module includes all the code of the gaming keyboards, which I doubt anyone is using on the rpi.    My keyboard in question was just a simple standard 102 key board that happened to come with a Asus eebox. 

Thanks.
