### ISSUE TITLE
Alsaplayer crashes with 24bit FLAC files

### ISSUE THREAD

**Issue by billhuey** [raspberrypi/linux#2290]
Alsaplayer crashes with 24bit FLAC files on the latest Raspbian. It's version that uses ALSA as the output and not jackd. aplay works fine with those same files

**Comment by pelwell** [comment]
If it's a user space crash then this isn't the right place to report it. If it's a kernel crash we'll need to see a kernel crash log from the output of dmesg.

**Comment by billhuey** [comment]
This is a user space crash. Thanks

**Comment by pelwell** [comment]
I also get a segmentation fault in libflac_in.so when playing a 24-bit FLAC file with alsaplayer, on a Pi and running Ubuntu on an X86 machine under VirtualBox. This looks like a bug/limitation of alsaplayer, so the best place to report it would be at the Alsaplayer github: https://github.com/alsaplayer/alsaplayer/issues

Note that alsaplayer has it's own FLAC library, while other clients (mplayer, for example) use the standard libFLAC, which can read 24-bit FLACs.

**Comment by billhuey** [comment]
I just filed the report via the link you sent me. Will wait for a response.
Thank you.

bill

**Comment by JamesH65** [comment]
Closing as this issue is not kernel related.
