### ISSUE TITLE
CONFIG_GPIO_PCF857X=m would be nice to have

### ISSUE THREAD

**Issue by nwf** [raspberrypi/linux#2294]
PCF857x-s are nice, inexpensive I2C I/O expanders, very useful for low-bandwidth communication across a large number of I/O lines and/or at a distance (running just I2C being much easier than a dozen I/Os back to the Pi).  It'd be nice to have the kernel's GPIO subsystem driver for these around by default.  It's 15 KB.

**Comment by pelwell** [comment]
It sounds like you've compiled it yourself. Have you also created an overlay for it?

**Comment by nwf** [comment]
If I understand your question correctly, I have not and have just used the /sys interface to the I2C bus to attach the devices, rather than use a device tree overlay.

**Comment by pelwell** [comment]
Done.

**Comment by nwf** [comment]
Thanks!
