### ISSUE TITLE
kernel bug causing data corruption on USB drives (Super Top M6116)

### ISSUE THREAD

**Issue by ikarsokolov** [raspberrypi/linux#230]
Current raspbian kernel has bug causing data corruption on USB drives / USB 2.5"-3.5"enclosure boxes with **Super Top M6116** SATA chipset (very common among cheap boxes).

More info
- https://bugzilla.redhat.com/show_bug.cgi?id=909591
- https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1082215
- http://www.raspberrypi.org/phpBB3/viewtopic.php?f=28&t=28386

**Comment by popcornmix** [comment]
It sounds like this still affects the latest (3.8) upstream linux kernel.
That is where the bug should be fixed, and we can cherry-pick the fix.

Do you know if this has been reported as bug in upstream kernel?

**Comment by ikarsokolov** [comment]
> Do you know if this has been reported as bug in upstream kernel?

launchpad issue has comments about reporting it to upstream debian, but I dont know current status.

> That is where the bug should be fixed, and we can cherry-pick the fix.

I think earlier patch against upstream kernel should be considered because
a) fix is trivial http://www.mail-archive.com/linux-usb@vger.kernel.org/msg14819.html (one liner)
b) this bug critically affects RaPi users because most of them attach external USB storage of some sort

**Comment by asb** [comment]
Looks like the patch has been posted to linux-usb and the stable
mailing list for inclusion:
http://thread.gmane.org/gmane.linux.usb.general/80193

**Comment by popcornmix** [comment]
Alex, do you know how long it typically is for a patch like that to be accepted?
From my searching, the fix seems to have been verified by only a couple of people, and seems somewhat arbitrary.
1.60 wants the patch, 2.20 doesn't want the patch, so lets say 2.19 is the threshold based on a sample size of 2.
I'm not completely confident that this won't cause corruption for people on, say, 2.30, or 1.80 wouldn't have been a better threshold.

It would be nice to hear the guy responsible for this upstream code to say yes, the patch is good.

**Comment by ikarsokolov** [comment]
I can confirm that this patch works for me. But I have 2.20 too.

**Comment by popcornmix** [comment]
@Happy-Neko 
I imagine the patch is _probably_ an improvement, and it sounds like a particularly dangerous bug, so I'll pick it up sooner rather than later, but I may just wait a day or so to see if there are positive noises from the mailing list.

**Comment by asb** [comment]
On 25 February 2013 19:10, popcornmix notifications@github.com wrote:

> Alex, do you know how long it typically is for a patch like that to be
> accepted?

Hard to say. I imagine it has to go through the subsystem maintainer
so it will depend on their schedule.

**Comment by ikarsokolov** [comment]
This issue seems to be fixed in kernel 3.8.1
commit 18e03310b5caa6d11c1a8c61b982c37047693fba

**Comment by popcornmix** [comment]
Okay, I've cherry-picked it.
