### ISSUE TITLE
Need to add Overlay for ApplePi DAC to raspberry pi

### ISSUE THREAD

**Issue by orchardaudio** [raspberrypi/linux#2302]
I have attached a zip file containing the dts and compiled dtbo files.

I have tested the overlay and it works with the DAC.

Please let me know if I need to provide anything else.

[ApplePi-DAC_dtbo_dts.zip](https://github.com/raspberrypi/linux/files/1544886/ApplePi-DAC_dtbo_dts.zip)

**Comment by pelwell** [comment]
Added to all current branches.

**Comment by orchardaudio** [comment]
Thanks for adding support.
