### ISSUE TITLE
Cannot login to my pi after  wait for network on boot, even if network is present

### ISSUE THREAD

**Issue by mrl98** [raspberrypi/linux#2304]
I am following Ira Finch's guide to setting up a VPN.

Per the instructions, I have set raspi-config to wait for network on boot.  I have turned on SSH.

However, even if I do have a network connection, I get the message "system is booting up see pam_nologin" when I try to login.

I have checked and /run/nologon  is not present.   Something else must be preventing me from logging on

**Comment by JamesH65** [comment]
You are unlikely to get an answer to technical support style question on this github, it's for linux kernel bug reports, which this isn't. Please report your question on the forums where it will received a larger audience.
