### ISSUE TITLE
Kernel errors when using bcm2835-v4l2 module

### ISSUE THREAD

**Issue by jaxxzer** [raspberrypi/linux#2306]
As seen here: https://github.com/bluerobotics/companion/pull/94#issuecomment-349856225

The v4l2 device reports stepwise frame sizes and frame intervals, but not all combinations will work. Some combinations (ie 1080p@90fps) result in a kernel error.

**Comment by pelwell** [comment]
Duplicate of https://github.com/raspberrypi/linux/issues/2043. Feel free to add any new information you have to that thread.

**Comment by jaxxzer** [comment]
Thanks!
