### ISSUE TITLE
ER: Two issue -- CPU moniter display err and Panel Setting cause the display resolution problem

### ISSUE THREAD

**Issue by starsyiyi** [raspberrypi/linux#2314]
hi ,

Two issue:

1. CPU usage moniter display garbled in chinese localed.

2. Panel Setting cause the display resolution problem
     the following is the operation steps:
     a. Right click to select "Panel Setting-Panel Applets-Add spacer between CPU Usage Monitor and Digital Clock"
     b. Remove the just added spacer
     c. Also maybe set up the "Geometry-Position",I'm not sure the issue appeared after this step.

     omg,  that resolution has been changed and terminal's area of activity has also been changed.
     How do i change some configurations to modify this problem? thx

     Append info : dibian version is debian-11.27 , HW  pi3
     BTW, I found the 'create_ap' is unstable in Raspberry ,so I successfully created AP with Hostapd, Why not auto assign IP address to STA? thanks a lot .

**Comment by starsyiyi** [comment]
![image](https://user-images.githubusercontent.com/28339000/34321677-1c636be8-e850-11e7-9eca-d48cdd1dea07.png)
VNC service may be a problem as well that is the window does not change size with the viewer changes.

**Comment by JamesH65** [comment]
@spl237 More a distro issue, but any comments?

**Comment by spl237** [comment]
1 seems to be the wrong font being used when Chinese locale is set; I'll see what can be done to fix it.

I can't repeat 2 - I suspect it is a VNC issue rather than anything in our code, as the screenshot above shows the desktop running under VNC. We've seen a similar problem before. Suggest a bug should be raised with RealVNC rather than us.

**Comment by JamesH65** [comment]
@spl237 Inclined to close this, any further reports?

**Comment by JamesH65** [comment]
This issue will be closed within 30 days unless further interactions are posted. If you wish this issue to remain open, please add a comment. A closed issue may be reopened if requested.

**Comment by starsyiyi** [comment]
close id ,thx
