### ISSUE TITLE
Menu items disappear

### ISSUE THREAD

**Issue by symbios24** [raspberrypi/linux#2317]
Hello there i `m currently having some problems with the main menu
I added some item to the main menu from the main menu editor like a new menu and some new items
and after one or two reboots they keep disappearing or going in the menu named "other"
can this be fixed?
Also another thing i notice some disabled items/apps in the menu after i enabled them they also disappear after reboot.

I do regular update/upgrade/dist-upgrade but it did not fix anything

i will appreciate your help

**Comment by pelwell** [comment]
This isn't a Linux issue - you should ask in the [lxpanel repo](https://github.com/raspberrypi-ui/lxpanel) where your question will be seen by the right people.
