### ISSUE TITLE
VC4 kernel framework driver - memory leak fixup

### ISSUE THREAD

**Issue by nkichukov** [raspberrypi/linux#2326]
Hello,
On 29 Nov 2017 Stefan Schake provided a patch to fix a huge memory leak in the vc4 driver implementation as reported here: https://github.com/anholt/linux/issues/122

The location of the patch is:
https://github.com/anholt/linux/files/1514699/0001-drm-vc4-Release-fence-after-signalling.txt or can also be found attached to this pull request - 
[0001-drm-vc4-Release-fence-after-signalling.txt](https://github.com/raspberrypi/linux/files/1597158/0001-drm-vc4-Release-fence-after-signalling.txt)

Can this be included in one of the next 4.14.y releases, please? I have been running it for more than a month now and it works as expected and without any side (d)effects.

Thank you,
-Nikolay

**Comment by pelwell** [comment]
Eric gives us groups of back-ported patches periodically, but since that commit fixes a leak and is in 4.15 I've cherry-picked it into rpi-4.14.y.

**Comment by nkichukov** [comment]
Thank you!
