### ISSUE TITLE
Lock up while using kms (stock raspbian stretch)

### ISSUE THREAD

**Issue by Ealdwulf** [raspberrypi/linux#2327]
Steps to reproduce from stock raspbian (maybe not all necessary) :

 *    Install 2017-11-29-raspbian-stretch.zip
  *   Switch to full kms
  *   change gpu mem to 256
  *  enable ssh
  *  connect to wifi
  *  ssh in
  *  `export DISPLAY=:0`
  *  `xrandr --output HDMI-1 --mode 1280x1024`
  *  `wget https://github.com/KanoComputing/kano-video-files/raw/master/videos/minecraft.mp4`
  *  `sudo apt-get install mpv`
  *  `mpv --fs minecraft.mp4 --keepaspect=no`

If it doesn't immediatley lock up, switching back and forth between modes and playing a video each time seems to do so pretty quickly
  * `xrandr --output HDMI-1 --mode 1920x1080`
  * `mpv --fs minecraft.mp4 --keepaspect=no`
  *  `xrandr --output HDMI-1 --mode 1280x1024`
  *  `mpv --fs minecraft.mp4 --keepaspect=no`

I'm not sure this is the right place - the whole pi locks up so it's not obvious what crashed - but since kms is experimental I'm guessing that is the culprit. If there's a better place let me know and I'll post it there and close this. I've also mentioned it here: https://www.raspberrypi.org/forums/viewtopic.php?f=28&t=200556&p=1249434#p1249434

**Comment by popcornmix** [comment]
Can you report this issue here: https://github.com/anholt/linux/issues/
Eric handles the kms driver and we get periodic updates from his tree.

**Comment by Ealdwulf** [comment]
Sure, will do.
