### ISSUE TITLE
rotary encoder - additional overrides?

### ISSUE THREAD

**Issue by shawaj** [raspberrypi/linux#2331]
According to this doc - https://elixir.free-electrons.com/linux/latest/source/Documentation/devicetree/bindings/input/rotary-encoder.txt

There are more configurable parameters for the rotary-encoder driver.

Would it be acceptable to add these all in as additional overrides to the driver?

Maybe something like this:
```
	__overrides__ {
		rotary0_pin_a =     <&rotary0>,"gpios:4",
		                    <&rotary0_pins>,"brcm,pins:0";
		rotary0_pin_b =     <&rotary0>,"gpios:16",
		                    <&rotary0_pins>,"brcm,pins:4";
		relative_axis =     <&knob>,"rotary-encoder,relative-axis";
		linux_axis =        <&knob>,"linux,axis";
		rollover =          <&knob>,"rotary-encoder,rollover";
		steps-per-period =  <&knob>,"rotary-encoder,steps-per-period";
		steps =             <&knob>,"rotary-encoder,steps";
		wakeup =            <&knob>,"wakeup-source";
		encoding =          <&knob>,"rotary-encoder,encoding";
    };
```

**Comment by pelwell** [comment]
Yes, of course - go ahead.

As a general point, each PR is a both a request and a topic for discussion, so I don't consider it necessary to ask in this way, polite as it is. Going straight to a PR helps to reduce the clutter and keep all relevant discussion in the same place.

**Comment by shawaj** [comment]
Understood! I'm new to these parts so don't know the etiquette yet and didn't want to step on any toes :-P

See your point though... Better if all in one place

**Comment by shawaj** [comment]
Closing this issue now and moving over to #2334
