### ISSUE TITLE
maxcpus not working in config.txt

### ISSUE THREAD

**Issue by jakemagee** [raspberrypi/linux#2337]
Has support for "maxcpus=2" in config.txt been removed or disabled?  I can't seem to get it to work on my RPi 3B module.  Checking `lscpu` and `cat /proc/cpuinfo` still report 4 cpus.

**Comment by pelwell** [comment]
It's a kernel command line parameter, so it goes in `cmdline.txt`.

**Comment by jakemagee** [comment]
Ah... stupid me.  I should have caught that.  Thanks!
