### ISSUE TITLE
lockdep-enabled early boot BUG/WARN & deadlock

### ISSUE THREAD

**Issue by 10ne1** [raspberrypi/linux#2353]
Booting a custom compiled lockdep-enabled kernel I get these stack traces on both rpi-4.14-y and rpi-4.15-y branches on every boot on a rpi 3 model b.

Full config for 4.15: https://pastebin.com/vVp30tBX
Full dmesg log:  https://pastebin.com/7xve2PpL

Tell me if more info or on target debugging is needed.

**Comment by 10ne1** [comment]
Closed this because I went ahead and compiled and booted Linux mainline directly (works good enough for my purpouses) where I do not have this issue anymore at boot.

**Comment by 10ne1** [comment]
I'm re-opening this just to point out for posterity that a fix landed in the dwc_otg driver which solves the issue (confirmed by testing with the above lockdep enabled kernel). Thanks @P33M !

commit d93cf8be07b1ae31e2d6f2ba76731c93380ede8a
Author:     P33M <p33m@github.com>
AuthorDate: Thu Feb 15 11:22:44 2018 +0000
Commit:     popcornmix <popcornmix@gmail.com>
CommitDate: Mon Feb 26 15:30:48 2018 +0000

    dwc_otg: add smp_mb() to prevent driver state corruption on boot
    
    Occasional crashes have been seen where the FIQ code dereferences
    invalid/random pointers immediately after being set up, leading to
    panic on boot.
    
    The crash occurs as the FIQ code races against hcd_init_fiq() and
    the hcd_init_fiq() code races against the outstanding memory stores
    from dwc_otg_hcd_init(). Use explicit barriers after touching
    driver state.

**Comment by popcornmix** [comment]
Thanks for update.
