### ISSUE TITLE
How to I generate the deb packages for the kernel?

### ISSUE THREAD

**Issue by T-vK** [raspberrypi/linux#2384]
I successfully have built version 4.14.18 of the pi kernel. There are instructions on how to install the kernel manually here: https://www.raspberrypi.org/documentation/linux/kernel/building.md

But I would like to host my own kernel repository. Therefore I need to generate the .deb packages, though. 

Could you please tell me how this is done?

**Comment by kukabu** [comment]
uses 'make deb-pkg' instead of 'make zImage modules dtbs'

**Comment by T-vK** [comment]
That's all? Where will the deb files be saved?

**Comment by kukabu** [comment]
in a directory one level up

**Comment by T-vK** [comment]
I don't know, I can't find it. "One level up" is a bit messed up because I check out to `/linux` and there are dozens of folders in `/`. None of those seem too contain my .deb files, though. Can you tell me the name of the directory?

Edit:
It wasn't in a directory one level up, everything was just literally one level up.
