### ISSUE TITLE
Audio output device selection reverts to HDMI after reboot

### ISSUE THREAD

**Issue by doldi** [raspberrypi/linux#2389]
Hello,
i'm using a "snd_rpi_hifiberry_digi" as Audio Device output.
After a restart or a new-start after shut-down the device selection reverts always to HDMI.

Reportet is the isue first [on milhouse LE/Kodi18 Forum](https://forum.kodi.tv/showthread.php?tid=298461&pid=2704752#pid2704752), togehter with the dts problem, 
... meanwhile solved by popcornmix and FernetMenta. paplayer (vp): [fix out-of-bounds error in audiocodec passthrough ](https://github.com/popcornmix/xbmc/commit/83ae540225cfcadb34d963faec3d4753f035dbd3)
any chance to bring that also on the the right way?

Many Thanks for Your  work, verry good Job.
Harald
(doldi)

**Comment by popcornmix** [comment]
This is a kodi issue, not a linux kernel issue so this is the wrong place to report it.
The kodi forum is the best place for reporting this.
