### ISSUE TITLE
config request HWMON

### ISSUE THREAD

**Issue by kukabu** [raspberrypi/linux#239]
Please add CONFIG_HWMON=y , CONFIG_THERMAL_HWMON=y and I think all I2C/SPI sensors as modules.

I try to use TI TMP102 sensor with RPi.

**Comment by iz8mbw** [comment]
Yes. this is a very good idea! For using Texas Instruments TMP275 and Maxim DS7505 I should build hwmon (hardware monitoring) module and the latest LM75 driver. I hope that all will be included by the default.

**Comment by ngreatorex** [comment]
I would also like hwmon support. Probably best to use CONFIG_HWMON=m. I would also like CONFIG_SENSORS_INA2XX as I am using that chip to monitor a solar powered Pi!

**Comment by kukabu** [comment]
@popcornmix are you add it?
