### ISSUE TITLE
Feature request: NFS 4.1 client support in kernel

### ISSUE THREAD

**Issue by fuxjezz** [raspberrypi/linux#2405]
Hi,

Could you please change

CONFIG_NFS_V4_1 is not set

to :

CONFIG_NFS_V4_1=y

in upcoming builds of the firmware/kernel?

I think it is not possible to use Raspbian (fitted with Hexxeh firmware) as a nfsv4.1 client due to this setting (nfs-common and nfs-utils packages in Raspbian appear recent enough to support 4.1) :(

Kind regards,

Ruben

**Comment by popcornmix** [comment]
This has been added and should be in latest rpi-update kernel. Can you test and confirm it solves your issue?

**Comment by fuxjezz** [comment]
Hi popcornmix,

I've just updated an nfs client. NFS v4.1 mounts are possible since this change.

Thank you very much!

Kind regards,

Ruben
