### ISSUE TITLE
audioinjector-octo-soundcard.c - Clocks turn off

### ISSUE THREAD

**Issue by Dloranger** [raspberrypi/linux#2409]
The code turns off the clocks entirely when not playing audio out which is breaking an application that depends on these audio clocks being present.  I have spoken to the original developer about this and he provided the changes needed (moving 3 case statements) to resolve.

I would like to see these changes made mainstream, but I am not sure if there might be other factors involved that would warrant not changing them that I am not aware of. 

The changes are to move lines 180-182 to line 140 so the clocks stay on during all cases.

If there is a reason not to update the source with the changes, would it be possible to put in a variant with these changes so that I am not having to edit and compile each time there is an update?

The driver is brought in using the overlay "audioinjector-addons"

**Comment by pelwell** [comment]
I don't like the idea of changing the current behaviour for all users, so instead I've added a DT property that prevents the clocks from being switched off. The property is enabled with a new DT parameter of the `audioinjector-addons` overlay - `non-stop-clocks`:
```
dtoverlay=audioinjector-addons,non-stop-clocks
```
This change will be included in the next firmware release.

**Comment by Dloranger** [comment]
Makes total sense for me, appreciate the help.
