### ISSUE TITLE
Please add CONFIG_GPIO_MOCKUP=m

### ISSUE THREAD

**Issue by smurfix** [raspberrypi/linux#2410]
Sometimes people want to test programs without actually wiring things to GPIO pins.

Thus, please enable this module.

**Comment by popcornmix** [comment]
Okay - added to source tree. Will be in next rpi-update kernel.

**Comment by popcornmix** [comment]
This should be in latest rpi-update kernel.

**Comment by JamesH65** [comment]
Please update to the latest kernel which contains a fix for this issue.
