### ISSUE TITLE
Feature request: Move bluetooth firmware into brcm directory

### ISSUE THREAD

**Issue by lategoodbye** [raspberrypi/linux#2415]
Hi,
i hope this the right place for this feature request. Raspbian is a good rootfs for my upstream work. In order to make my life just a little bit easier it would be nice to move the bluetooth firmware ( /lib/firmware/BCM43430A1.hcd ) into the /lib/firmware/brcm directory. After this change the BT firmware could be loaded automatically without hciattach by the upstream driver (scheduled for 4.17).

**Comment by XECDesign** [comment]
@pelwell Shall I?

**Comment by pelwell** [comment]
Does hciattach find it in the new location? If not I'd rather duplicate it than wind up with a synchronisation problem.

@lategoodbye Are you saying that you haven't managed to get the kernel to patch the 43430 with the firmware in its current location?

**Comment by lategoodbye** [comment]
Yes, with the current location i will get this error:

```
[    5.103374] bluetooth hci0: Direct firmware load for brcm/BCM43430A1.hcd failed with error -2
[    5.103390] Bluetooth: hci0: BCM: Patch brcm/BCM43430A1.hcd not found
```

No need to hurry. Maybe a symlink could also be an option.

**Comment by pelwell** [comment]
hciattach finds the BT firmware in the brcm subdirectory:
```
Mar 06 15:11:40 raspberrypi systemd[1]: Starting Configure Bluetooth Modems connected by UART...
Mar 06 15:11:45 raspberrypi btuart[358]: bcm43xx_init
Mar 06 15:11:45 raspberrypi btuart[358]: Flash firmware /lib/firmware/brcm/BCM43430A1.hcd
Mar 06 15:11:45 raspberrypi btuart[358]: Set BDADDR UART: b8:27:eb:8d:01:2e
Mar 06 15:11:45 raspberrypi btuart[358]: Set Controller UART speed to 3000000 bit/s
Mar 06 15:11:45 raspberrypi btuart[358]: Device setup complete
```
I'm happy for it to be moved

**Comment by XECDesign** [comment]
Done. Should show up in the repo soon.

**Comment by lategoodbye** [comment]
Thanks a lot
