### ISSUE TITLE
PI2 v1.2 64bit kernel

### ISSUE THREAD

**Issue by matthew-l-weber** [raspberrypi/linux#2422]
Wondering if someone has tried porting a PI3 64bit kernel to the PI2 with the same A53 based chip?

**Comment by JamesH65** [comment]
Not really the right place to ask that sort of question - we don't provide a 64bit kernel for any of our devices, so any you find will have been generated by others.  You could try the forum.

TBH, if it works on the Pi3, it *might/probably/should* work on the Pi2, but probably quicker to try it than ask the question.
