### ISSUE TITLE
Raspberry Pi freezes with high network load

### ISSUE THREAD

**Issue by pl31** [raspberrypi/linux#244]
The Raspberry Pi freezes under high network load. Netload can be generated by a packet generator or arping using another computer:
  arping -w 100000 192.168.0.104

192.168.0.104 would be the IP-address of the Raspberry Pi.

The raspberry freezes, input via keyboard is ignored. When netload drops, the raspberry is reacting normally.

The problem does not occur, when using "dwc_otg.speed=1" in cmdline.txt.

Tested using two different Model B Devices "Made in China" and following systems:

Raspian:
Linux 3.6.11+ #371 PREEMPT Thu Feb 7 16:31:35 GMT 2013 armv6l GNU/Linux
slitaz:
Linux 3.2.27-slitaz #1 PREEMPT Fri Dec 14 15:01:17 CST 2012 armv6l GNU/Linux
tinycorelinux:
Linux 3.2.27 #4 PREEMPT Sun Sep 16 09:59:00 PDT 2012 armv6l GNU/Linux

Edit: changed 'heavy netload' to 'high network load' :).

**Comment by Ferroin** [comment]
This isn't specific to the P, or even to Linux. In theory, any system will react like that when the I/O load is 'high', it's just that 'high' is a relatively small number in this case.

**Comment by pl31** [comment]
Repeated test today using tinycorelinux (piCore-5.1.rc4):

tc@box:~$ uname -r
3.12.1-piCore+

When arping'ing the PI, it still reacted normally.

**Comment by P33M** [comment]
If the issue has been resolved, ok to close?

**Comment by pl31** [comment]
Closed. Thanks a lot.
