### ISSUE TITLE
RPi3 USB wifi adapter will not auto-reconnect to the AP after the March 2018 firmware updates

### ISSUE THREAD

**Issue by rsfitz** [raspberrypi/linux#2443]
**Description:**
When using a generic Realtek USB WiFi adapter with the onboard WiFi disabled, The adapter will not auto-reconnect to the AP if the connection has been lost. Attempts to manually reconnect will prompt for passphrase and fail to connect. The USB adapter will reconnect if it is removed and replaced.

**Steps to Reproduce:**
- Install compatible USB WiFi Adapter
- Disable on-board WiFi (dtoverlay=pi3-disable-wifi)
- apt-get update && upgrade
- Disconnect Access Point

**Comment by JamesH65** [comment]
Which USB adapter are you using? dmesh to get the vendor ID would be useful, and try lsub to get its name.

**Comment by rsfitz** [comment]
It is _generic_ Realtek Adapter
idProduct=7811

This appears to be an issue with re-connection to the AP: If the connection to the access point is lost it will not automatically or manually reconnect. Removing and replacing the USB adapter will restore the connection.

**Comment by JamesH65** [comment]
We had a recent problem with the onboard Wireless doing the same thing. It was a Linux driver problem. The firmware on the wireless device was fine, but it was new firmware. Older firmware worked with the older driver.

Using the same logic  this is not a Pi firmware issue, but a Realtek kernel driver issue or Realtek firmware issue. You will need to approach the Realtek maintainer for help on this one, usually done via the Linux wireless mailing list.

**Comment by rsfitz** [comment]
Will do, I did find a similar issue dating back to 2015 with the kernel driver that appears to have the same symptoms.

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=776816

**Comment by jakemagee** [comment]
@rsfitz, Sounds like this issue can be closed here?
