### ISSUE TITLE
LM75.c and LM75.h files

### ISSUE THREAD

**Issue by iz8mbw** [raspberrypi/linux#246]
Hi.
The LM75 sensor (and also others sensors compatible with LM75 driver) can supports also a resolution of 12bit (in addition to the 9bit by default). The LM75.c and LM75.h files available here https://github.com/raspberrypi/linux/tree/rpi-3.6.y/drivers/hwmon seem to support only 9bit resolution.
The upgraded LM75.c and LM75.h files available at lm-sensors here: http://khali.linux-fr.org/devel/misc/lm75/ support also a 12bit resolution and support also new chip.
Is it possibile to update these files?
Thanks!

**Comment by popcornmix** [comment]
Generally we don't pull in out of (kernel) tree drivers without a very good reason.
Have the modified files been accepted upstream into the linux kernel?
If not, then requesting they are is the first step (they may have been rejected for a reason).

**Comment by iz8mbw** [comment]
OK, do you know how to propose them into the linux kernel?

**Comment by technion** [comment]
iz8mbw: https://www.kernel.org/doc/Documentation/SubmittingPatches
There is a requirement on kernel submission involving a "Certificate of origin", see section 12.
It would be more appropriate to contact khali@linux-fr.org and ask him to submit it.

**Comment by iz8mbw** [comment]
It was already done, see: http://lists.lm-sensors.org/pipermail/lm-sensors/2013-March/038385.html and following.

**Comment by technion** [comment]
I could well be missing subsequent updates, but my reading there is that the patch was rejected, with a statement that more time was required for code review.
If that was the view from the upstream maintainer, I'd be cautious about accepting it elsewhere.

**Comment by iz8mbw** [comment]
So, should you wait for the patch approval? If it is not yet approved, I think that it will be approved soon. Should we wait?

**Comment by popcornmix** [comment]
Yes, we should wait for the upstream review of the patch.

**Comment by iz8mbw** [comment]
Hi.
It seem that the various improvements on LM75 driver (supports 12bit resolution and the add of the chip DS7505) was approved on 14 of March: https://git.kernel.org/cgit/linux/kernel/git/next/linux-next.git/log/?id=refs%2Ftags%2Fnext-20130315&qt=grep&q=hwmon

**Comment by popcornmix** [comment]
Can anyone who uses this driver test whether these commits:
2 days  hwmon: (lm75) Add support for the Dallas/Maxim DS7505   Jean Delvare    3   -5/+12
2 days  hwmon: (lm75) Tune resolution and sample time per chip  Jean Delvare    2   -9/+40
2 days  hwmon: (lm75) Prepare to support per-chip resolution and sample time    Jean Delvare    1   -5/+26
2 days  hwmon: (lm75) Per-chip configuration register initialization    Jean Delvare    1   -2/+22
2 days  hwmon: (lm75) Fix tcn75 prefix  Jean Delvare    1   -1/+1
2 days  hwmon: (lm75.h) Update header inclusion Jean Delvare    1   -1/+1

are all required, and if they are sufficient? (i.e. are there any other patches they rely on).

**Comment by iz8mbw** [comment]
On my Raspberry I have tested these patchs, I'm using the last version of LM75, I can read with a 12bit resolution and I can read correctly also the chip Dallas/Maxim DS7505 (in 12bit resolution too).
