### ISSUE TITLE
Create tag and release matching the official Raspbian image from 2018-03-13

### ISSUE THREAD

**Issue by VladimirTechMan** [raspberrypi/linux#2465]
Right now, the latest tag and release published for Raspberry Pi Linux kernel are still "raspberrypi-kernel_1.20171029-1". The ones matching the latest official Raspbian image from 2018-03-13 are missing, somehow. Having them as an official reference point is useful for those who build their own custom kernels – but want those to match the latest Raspbian image, aside from the custom modifications applied.

**Comment by XECDesign** [comment]
@popcornmix is HEAD of https://github.com/raspberrypi/linux/commits/rpi-4.9.y-stable the commit to tag?

**Comment by popcornmix** [comment]
Yes, HEAD of stable matches the last raspbian image (and apt-get firmware/kernel).

**Comment by XECDesign** [comment]
Tagged https://github.com/raspberrypi/linux/releases/tag/raspberrypi-kernel_1.20180313-1

**Comment by VladimirTechMan** [comment]
Thanks!
