### ISSUE TITLE
USB: add OWL CM-160 support to cp210x driver

### ISSUE THREAD

**Issue by mzielinskim** [raspberrypi/linux#247]
Please add support for the OWL CM-160 (Energy Monitor) in the cp210x driver.

More Infos:
http://permalink.gmane.org/gmane.linux.kernel.commits.head/361246
http://sourceforge.net/projects/electricowl/files/v2.2/owl_cm160_device_on_the_raspberrypi_platform.txt

**Comment by P33M** [comment]
Current branch is 3.12, has this commit in.
