### ISSUE TITLE
dtoverlay gpio-shutdown not working on pi 3B or 3B+

### ISSUE THREAD

**Issue by JamesGKent** [raspberrypi/linux#2472]
I was originally trying to get this to work on an OSMC install i had but i was unable to get that working, so i tried to go back to basics, get the latest raspbian lite image and configure it on that.
Version:March 2018
Release date:2018-03-13
Kernel version:4.9

however I couldn't get it to work on either the 3B or 3B+, i did get the image to work on a pi 1B using this in config.txt:
```
dtoverlay=gpio-shutdown
```

but the same image in either of the 3's didn't work?
I wondered if it could be an architecture/peripheral thing due to the change in the peripheral addresses on the 4 core pi's, but I've seen numerous reports on forums of people that have had it working on both pi 2's and 3's

can someone who knows a bit more about the device tree weigh in on this? how can I debug this?

Thanks

**Comment by pelwell** [comment]
I've just tried it on a 3B+ and it works as expected. The documentation says:
```
pi@raspberrypi:~ $ dtoverlay -h gpio-shutdown
Name:   gpio-shutdown

Info:   Initiates a shutdown when GPIO pin changes. The given GPIO pin
        is configured as an input key that generates KEY_POWER events.
        This event is handled by systemd-logind by initiating a
        shutdown. Systemd versions older than 225 need an udev rule
        enable listening to the input device:

                ACTION!="REMOVE", SUBSYSTEM=="input", KERNEL=="event*", \
                        SUBSYSTEMS=="platform", DRIVERS=="gpio-keys", \
                        ATTRS{keys}=="116", TAG+="power-switch"

        This overlay only handles shutdown. After shutdown, the system
        can be powered up again by driving GPIO3 low. The default
        configuration uses GPIO3 with a pullup, so if you connect a
        button between GPIO3 and GND (pin 5 and 6 on the 40-pin header),
        you get a shutdown and power-up button.

Usage:  dtoverlay=gpio-shutdown,<param>=<val>

Params: gpio_pin                GPIO pin to trigger on (default 3)

        active_low              When this is 1 (active low), a falling
                                edge generates a key down event and a
                                rising edge generates a key up event.
                                When this is 0 (active high), this is
                                reversed. The default is 1 (active low).

        gpio_pull               Desired pull-up/down state (off, down, up)
                                Default is "up".

                                Note that the default pin (GPIO3) has an
                                external pullup.
```
The default GPIO is 3 (_which appears on pin 5 of the 40-pin header_). The pin is configured to pull high by default (which is also the SoC's default), and the GPIO is marked as active low (the opposite to the pull, for obvious reasons).

If you are having trouble, you can debug using `raspi-gpio` on Raspbian. Assuming for now that the overlay applied correctly (`lsmod` should show gpio-keys as being loaded), `raspi-gpio get 3` will show the pin level (which should be 1) and function (INPUT). Now run it in a loop:
```
pi@raspberrypi:~ $ while true; do raspi-gpio get 3; done
```
Attach one end of a patch lead to pin 5 (GPIO3), and touch the other end on pin 6 (GND) - the Pi should shut down immediately, but if not you will see the pin level change to 0.

**Comment by JamesGKent** [comment]
i must have been doing something wrong previously, i can confirm it does work on raspbian, but still not on OSMC, the pin state change is seen there, but the gpio-keys module is not loaded. I suspect it's not present.
