### ISSUE TITLE
openssl faults with "illegal instruction" for e.d. squid, tor, etc.

### ISSUE THREAD

**Issue by ghost** [raspberrypi/linux#248]
OpenSSL has issues on the RPI.
With all kinds of software it fails in OPENSSL_cpuid_setup with a SIGILL.

E.g. with the squid proxy:
Program received signal SIGILL, Illegal instruction.
0xb6e585e0 in ?? () from /usr/lib/arm-linux-gnueabihf/libcrypto.so.1.0.0
(gdb) bt
#0  0xb6e585e0 in ?? () from /usr/lib/arm-linux-gnueabihf/libcrypto.so.1.0.0

Cannot access memory at address 0x0
#1  0xb6e54fc4 in OPENSSL_cpuid_setup () from /usr/lib/arm-linux-gnueabihf/libcrypto.so.1.0.0
#2  0xb6fe8254 in ?? () from /lib/ld-linux-armhf.so.3
#3  0xbefff7e6 in ?? ()
#4  0xbefff7e6 in ?? ()

Backtrace stopped: previous frame identical to this frame (corrupt stack?)

If you do a google you'll find that lots of people have issues like this. With e.g. tor etc.

**Comment by popcornmix** [comment]
This is a build/distribution issue, not a kernel issue.
Reporting http://www.raspbian.org/RaspbianBugs or http://www.raspberrypi.org/phpBB3/viewforum.php?f=66 would be more appropriate.
