### ISSUE TITLE
4.14: quiet, heavily distorted signal when capturing from HifiBerry Digi+I/O in S24_LE

### ISSUE THREAD

**Issue by supercurio** [raspberrypi/linux#2480]
On 4.9.80 kernel, the [HifiBerry Digi+ I/O](https://www.hifiberry.com/shop/boards/hifiberry-digi-io/) ALSA interface lists formats supported S16_LE and S32_LE.
On 4.14 kernels, the same lists S16_LE and S24_LE instead.

When capturing in S24_LE, the signal recorded is a heavily distorted, low level version of the original input.
It is fine however when capturing in S16_LE format.
On 4.9.80, the result was flawless for both S16_LE and S32_LE.

How to reproduce:
(note, make sure you're recording at the right sample rate)
- connect a source to the SPDIF or TOSLINK input
- run arecord -f S16_LE -c 2 -r 44100 -vv -V stereo -D hw:1,0 /tmp/record.wav

Also discussed here:
https://support.hifiberry.com/hc/en-us/community/posts/360002252145-Digi-I-O-broken-S24-LE-capture-with-4-14-kernel

**Comment by HiassofT** [comment]
This is actually an issue with how arecord stores S24_LE data in wav files. S24_LE is 24 bit data in a 32bit word with the upper 8 bits padded with zeroes. In wav files samples should be stored MSB aligned, i.e. when storing 24bit samples in 32bit words sample data must be in the upper 24 bits and the lower a 8 bit must be padded.

When recording 24bit samples in wav files it's best to store them in a 24bit packed format (3 bytes), in the ALSA context this format is called S24_3LE.

So, the solution is rather simple, don't use hw:1,0 when recording but the default alsa device or plughw:1,0 and use the S24_3LE format. The hw device will then be configured to S24_LE and the plug plugin packs the sampledata from S24_LE to S24_3LE.

eg: arecord -f S24_3LE -D plughw:1,0 ....

**Comment by supercurio** [comment]
That's right!
Thanks HiassofT, the bug in indeed in arecord in how it transforms S24_LE.
I didn't see that one coming as it affects both the output and the VU-meters.

My use case won't be via arecord but that's a good reminder that plughw is an alternative here and the kernel issue doesn't exist in the first place :)

I also checked that the 24 bits of resolution are preserved and they are.
