### ISSUE TITLE
moonlight-embedded : 3 seconds video lag on Raspberry Pi 2 latest firmwares

### ISSUE THREAD

**Issue by Astral91** [raspberrypi/linux#2488]
I originally posted it on the moonlight-embedded section (https://github.com/irtimmer/moonlight-embedded/issues/645)

On a RPi2 running Raspbian Stretch, the firmware ed6ece6b (https://github.com/Hexxeh/rpi-firmware/commit/ed6ece6b5c1c0d8aceb86568ffe3033bb9ae9ecc) and later introduce several seconds of video lag, making moonlight unusable. According to the release notes, the firmware contains clock/voltage modifications. 

Rollbacking to e0db6ba or earlier fixes the issue.

The issue is 11 days old, but I tested the latest firmware today and it still breaks moonlight.

**Comment by JamesH65** [comment]
Sorry about the delay. Might be worth trying the very latest build in case something has changed, but otherwise not sure we will be able to spend much time on this. And why is this called Moonlight? Very confusing considering there was another OSS project called Moonlight (OSS version of SIlverlight). Or is this a development of that?

**Comment by knives49** [comment]
desciption of Moonlight Embedded

Moonlight Embedded is an open source implementation of NVIDIA's GameStream, as used by the NVIDIA Shield, but built for Linux.
Moonlight Embedded allows you to stream your full collection of games from your powerful Windows desktop to your (embedded) Linux system, like Raspberry Pi, CuBox-i and ODROID.

**Comment by popcornmix** [comment]
Any change if you add ``force_turbo=1`` to config.txt?

**Comment by knives49** [comment]
less lag, but always 1 seconds lag.
I can't find the commit who change something in the rpi 2b between Hexxeh firmware e0db6ba and ed6ece6b

**Comment by Astral91** [comment]
I added both :

force_turbo=1
h264_freq=333

in config.txt and the issue is gone.
