### ISSUE TITLE
Will there be a official 4.9 release with 3B+ support or is it all 3.14 from now on?

### ISSUE THREAD

**Issue by jorisvergeer** [raspberrypi/linux#2493]
Like the title said:
Will there be a official 4.9 release with 3B+ support or is it all 3.14 from now on?

I have production pies running on various locaties on rasbian jessie with 3.9 and I prefer not to update to 3.14 and prefer using the same distribution for new instalation on the 3B+

I run software at 150+ location throughout the country that uses brcmGLES and those libraries have been renamed in 3.14. 
I either have to hack 3.14 into the current library and hack the GLES library names, support 2 versions of our software targetting 3.9 and 3.14 distros, or remote update to stretch.
None of those options seem pleasing.

**Comment by popcornmix** [comment]
It's not clear if your question is referring to kernel versions (did you mean 4.14 rather than 3.14?) or something in stretch.
Raspbian has moved to 4.14 kernel. There will be no further official released on 4.9.

The brcmGLES libraries are not related to the kernel. You can solve that issue with symlinks to the files in /opt/vc/lib (although rebuilding applications linking to the new library names would be preferable).

**Comment by jorisvergeer** [comment]
Yes, i meant 4.14 ;)

In raspbian, it looked like the firmware packages and kernel packages depend on each other. (Maybe I saw that wrong...)

In your opinion, is installing the 4.14 kernel on raspbian jessie stable? 
We use a customized raspbian image, and creating a stretch image would require some time. (And we have some 3B+ stock at the moment we cannot use)

**Comment by popcornmix** [comment]
Yes, the 4.14 kernel is now the default kernel for raspbian and is considered stable.

**Comment by monetny** [comment]
for install official release 4.9.80 kernel with 3B+ support run command
sudo rpi-update 936a8dc3a605c20058fbb23672d6b47bca77b0d5

**Comment by E3V3A** [comment]
@monetny 
> sudo rpi-update 936a8dc3a605c20058fbb23672d6b47bca77b0d5

So can I use the same to downgrade from 4.14 to 4.9.80 on RPi3B?

**Comment by monetny** [comment]
> So can I use the same to downgrade from 4.14 to 4.9.80 on RPi3B?

of course
This command work on all rPis in Raspbian and Ubuntu (I test ubuntu-mate 16.04.2)
This command install official kernel from last Raspbian release (2018-03-13) with 4.9 kernel.

But next time _apt-get upgrade_ may overwrite kernel again.

**Comment by Ferroin** [comment]
You can prevent the package manager from screwing with the kernel by putting a hold on the kernel package using `apt-mark hold` (you can later remove the hold with `apt-mark unhold`).

**Comment by E3V3A** [comment]
> putting a hold on the kernel package using apt-mark hold

Sorry for the OT, but I use this all the time for single packages, but I would guess for kernel, you'd need to include the bootloader, firmware and libraries as well?

**Comment by lurch** [comment]
> I have production pies running on various locaties on rasbian jessie with 3.9 and I prefer not to update to 3.14 and prefer using the same distribution for new instalation on the 3B+

If you've got systems in production and you don't want to modify your customized raspbian image, another option would be to keep buying the old model 3B and not the 3B+ ? :slightly_smiling_face: 
(The RPF make a big thing about not EOLing older models, for precisely this reason)

**Comment by JamesH65** [comment]
I think the question has been answered, any objections to this issue being closed?

**Comment by JamesH65** [comment]
Closing this issue as questions answered/issue resolved.
