### ISSUE TITLE
Automount (autofs with winbind) stops working on 4.14.30 kernel upgrade

### ISSUE THREAD

**Issue by drmullins** [raspberrypi/linux#2498]
Automount (using autofs with winbind) stopped working afer I upgraded from 4.9.80 to 4.14.30 kernel.

The problem is repeatable - I checked with a second sd card with same kernel update.  

My /etc/auto.master and /etc/auto.sambashares (listed at bottom of this page) have 
permissions set correctly as 755 (though 644 also works in some cases) and 644 respectively

These automounts have been and are still working perfectly on :
-	Several Raspberry Pi 2 model B, Raspberry 3 model B, and Raspberry 3 model B+
running Raspbian Jessie and Raspian Stretch with kernels 4.9.80 or earlier
-	Several old 32 bit x86 PC's running Debian Jessie and Debian Stretch

Nmap still finds all servers correctly listing the open ports

Shares can still be mounted manually using pcmanfm - Go - Network

However automount is not working at all (with 4.14.30 kernel)

I have tried adding 
	automount: 	files 
as a new row in /etc/nsswitch.conf (already configured for winbind see below) but this has no effect 

HELP PLEASE !

I had to revert to the 4.9.80 kernel
sudo rpi-update 5c80565c5c0c7f820258c792a98b56f22db2dd03
to get automount working again
- not a satisfactory solution going forward.

My /etc/auto.master contains :
#
# Sample auto.master file
# This is a 'master' automounter map and it has the following format:
# mount-point [map-type[,format]:]map [options]
# For details of the format look at auto.master(5).
#
#/misc	/etc/auto.misc
/media/mycifs /etc/auto.sambashares --timeout=7200 --ghost
 
#
# NOTE: mounts done from a hosts map will be mounted with the
#	"nosuid" and "nodev" options unless the "suid" and "dev"
#	options are explicitly given.
#
#/net	-hosts
#
# Include /etc/auto.master.d/*.autofs
# The included files must conform to the format of this file.
#
+dir:/etc/auto.master.d
#
# Include central master map if it can be found using
# nsswitch sources.
#
# Note that if there are entries for /net or /misc (as
# above) in the included master map any keys that are the
# same will not be seen as the first read key seen takes
# precedence.
#
+auto.master

My /etc/auto.sambashares contains :
ds215j -fstype=cifs,rw,uid=${UID},guest ://DS215J/PUBLIC
qnap112 -fstype=cifs,rw,uid=${UID},guest,sec=ntlm,nounix,noserverino ://QNAP112/Public
tplink -fstype=cifs,rw,uid=${UID},guest ://192.168.1.1/"volume(sda1)"
qnap2012 -fstype=cifs,rw,uid=${UID},guest,sec=ntlm,nounix,noserverino ://QNAP2012/Public
mybooknfs -fstype=nfs,nolock MyBookWorld:/nfs/Public
raspimusic -fstype=cifs,rw,uid=${UID},guest ://raspi6/pidrivemusic
transit -fstype=cifs,rw,uid=${UID},guest ://raspi6/transit
asus2012 -fstype=cifs,rw,uid=${UID},guest ://PERSONAL-743469/HOMESHARE

my /etc/nsswitch.conf contains :
# /etc/nsswitch.conf
#
# Example configuration of GNU Name Service Switch functionality.
# If you have the `glibc-doc-reference' and `info' packages installed, try:
# `info libc "Name Service Switch"' for information about this file.

passwd:         compat
group:          compat
shadow:         compat
gshadow:        files

hosts:          files wins mdns4_minimal [NOTFOUND=return] dns
networks:       files

protocols:      db files
services:       db files
ethers:         db files
rpc:            db files

netgroup:       nis

**Comment by drmullins** [comment]
I have now found that this issue seems to be due to changes in samba protocol between kernel 4.9.80 and kernel 4.14.30 - see my post https://www.raspberrypi.org/forums/viewtopic.php?f=66&t=210981
for details

**Comment by JamesH65** [comment]
@drmullins Is there anything else to report on this? Has the problem been fixed/worked round in your opinion?

**Comment by drmullins** [comment]
After initial shock I accept that this can only be fixed by a work round so it can be closed.
