### ISSUE TITLE
Kernel 4.14 behaves poorly in LibreELEC

### ISSUE THREAD

**Issue by smp79** [raspberrypi/linux#2503]
I have to use kernel 4.9 for my LibreELEC 9.0 builds because with the current default kernel 4.14 there are audio dropouts during heavy sdcard i/o activity. 
Among other things, this makes impossible to watch and record the TV channel at the same time. The issue is present in current Milhouse builds. No such issue when building with kernel 4.9.

**Comment by popcornmix** [comment]
You'll need to provide some details. What model of Pi? What audio interface?
Any custom config.txt settings or hardware attached?
Mediainfo of a file that has problems?
Can you reproduce without PVR? (e.g. play a test file and copy a file on sdcard at same time)

**Comment by smp79** [comment]
[I reported about this issue](https://forum.libreelec.tv/thread/4235-dvb-issue-since-le-switched-to-kernel-4-9-x/?postID=77001#post77001) right after the softirq/DVB fix was discovered. Kernel 4.9 and newer started to be usable for USB DVB owners and that's when I noticed another kernel issue (this time it seem to be Pi-specific).

The hardware is a Pi3, connected directly to a TV via HDMI. DVB tuner connected to the same Pi3.
I don't know how to reproduce without PVR but 1 user reported that my build with kernel 4.9 fixed a [similar issue for him](https://forum.kodi.tv/showthread.php?tid=298461&pid=2703880#pid2703880).

The easiest way for me to reproduce is to start recording when watching a TV channel. That's when the audio dropouts occur with tons of ActiveAE errors in kodi.log. Also any heavy network activity like copying a file over LAN will cause the short audio dropouts / ActiveAE errors.

I also tried to record to a USB drive instead of the sdcard - same issues. 

The recorded stream is perfectly fine, only the playback is affected.

**Comment by mkreisl** [comment]
Similar issue reported from an XBian user, see [this post](http://forum.xbian.org/thread-2877-post-35146.html#pid35146)

Reverting kernel 4.14.32+ to 4.9.91+ solves his issue

**Comment by smp79** [comment]
I will also add that I tested with different kernel versions - the issue was introduced in kernel 4.10.

**Comment by popcornmix** [comment]
Instructions to reproduce would be useful. e.g. play this file and run this program at the same time causes audio dropouts.

I'm running Kodi on 4.14 kernel (Milhouse nightly build), including running PVR and haven't had this issue.

I assume enabling omxplayer avoids the issue?
I've seen some reports that disabling file/memory cache (e.g removing custom advancedsettings.xml helps).
Does changing the audio output format make a difference? (e.g. passthough on/off, ac3 transcoding on/off, outputting to 5.1 with/without stereo upmix).

**Comment by smp79** [comment]
OMXPlayer does not avoid the issue, advancedsettings.xml is empty, audio output format does not make a difference.
I just tried to reproduce the issue without PVR and it is quite easy.
1. Start the playback of a high bitrate 1080p video from a **USB** flash drive.
2. During the playback start copying a large file to the Pi's sdcard over **LAN**.
That's when the audio dropouts will start to occur. Check kodi.log for ActiveAE errors.

**Comment by smp79** [comment]
Found [this](https://linuxmusicians.com/viewtopic.php?t=16920), possibly related issue.

**Comment by polojoe** [comment]
The described issue also exists if a download is started during livetv watching in le. After some time there's an audio dropout, after that a/v are out of sync.
Logs required?

**Comment by Krawei** [comment]
Any updates here?

**Comment by smp79** [comment]
I tested with kernel 4.17 and there is no improvement.

**Comment by SpeedyQ** [comment]
Any updates on this issue?

I recently tried updating to 4.14.54+ kernel (xbian on raspberry pi) which is current stable version, but the issue still exists where music playback seems to pause for millisecond(s) and continuing again where it paused.
I reverted back to 4.9.96+ kernel which is still ok regarding the stutter issue...

**Comment by smp79** [comment]
Similar issue reported [here](https://lkml.org/lkml/2018/5/28/1985). I reverted commit a1b8913 but unfortunately it didn't improve things.

**Comment by smp79** [comment]
I think I'm getting closer to solving this. I built 2 LibreELEC images: with kernel 4.10-rc1 and 4.10.0.
4.10-rc1: no audio dropouts at all when recording a DVB stream
4.10.0: lots of audio dropouts when recording a DVB stream

The offending commit is somewhere between 4.10-rc2 and 4.10-rc8. I will build more images and test.

**Comment by smp79** [comment]
Ok, I narrowed down the issue to kernel 4.10-rc6 (no dropouts with rc5 and earlier). Any suggestions on what commits I should try to revert are welcome.

**Comment by smp79** [comment]
Ok, I narrowed it down to kernel 4.10-rc6 (no issues with rc5 and older).

**Comment by popcornmix** [comment]
Interesting. Can you narrow it further?
Looking at the commit list (there's quite a few) the "mm" ones look like possible culprits.
Otherwise there's a number of net related commit which I guess could cause the issues here.

@smp79 Is network involved when you see the issue, or can you see it purely locally (dvb + local storage)?

**Comment by smp79** [comment]
@popcornmix I see the issue when recording/writing to a local sdcard with no network involved. I will try to narrow it further.

**Comment by mkreisl** [comment]
@SpeedyQ has reported [here](http://forum.xbian.org/thread-2877-post-35495.html#pid35495) after changing hardware from Pi3B to Pi3B+ stuttering has gone with 4.14.58+ kernel
Maybe it's network related (as everybody knows, Pi3B+ is using different network driver)

**Comment by polojoe** [comment]
I'm using rpi3+ and also have the issue when watching tv during recording on local storage. Issue is also present during dvb and download.

**Comment by smp79** [comment]
Ok, I'm not a git expert and I need some help with this.
I narrowed it down to those 4 commits:
67ade058ef2c65a3e56878af9c293ec76722a2e5
1fdf41941b8010691679638f8d0c8d08cfee7726
57b59ed2e5b91e958843609c7884794e29e6c4cb
99f300cf1f3877ad8ea923127de817a460b787bd

Commit a47b70ea86bdeb3091341f5ae3ef580f1a1ad822 is good, no audio issues.
Commit 99f300cf1f3877ad8ea923127de817a460b787bd is bad, I get audio dropouts.

**Comment by popcornmix** [comment]
How are you generating the commit hashes to test?
I wonder if you will be better off just using the merge commits
(e.g. ``git log --merges``) as the points to test.

**Comment by smp79** [comment]
I'm simply picking them one-by-one. I edit PKG_VERSION= in packages/linux/package.mk (in LibreELEC build system). The last good one is a47b70ea86bdeb3091341f5ae3ef580f1a1ad822. 

I use vanilla kernel + [this patch](https://github.com/LibreELEC/LibreELEC.tv/blob/feb4c4ef376a52ef4e14f05a350370b88a1a0689/projects/RPi2/patches/linux/linux-01-RPi_support.patch) to make it build in LibreELEC build system.

**Comment by popcornmix** [comment]
I think the problem is that the git history is not linear due to the merge commits.
You may be better off using the merge commits from:
```
 git log --pretty=oneline --merges 99f300c...a47b70e
```
(but I wouldn't claim to be a git expert either).

**Comment by smp79** [comment]
I found the bad commit. It took more than 20 hours and 50+ LibreELEC/kernel builds :)

424f6c4

I also [reverted that commit](https://github.com/smp79/linux/commit/6368fb6947feaa9751814d9dcc8bceac0b8f729c) for kernel 4.14 - audio dropouts are now gone.

**Comment by popcornmix** [comment]
Thank you. That commit does look plausible for causing kernel stalls.
@mkreisl can you confirm the fix?

See #2647

**Comment by mkreisl** [comment]
@popcornmix 
I was never able to reproduce this issue here, so it is impossible for me to confirm the fix

**Comment by popcornmix** [comment]
@smp79 without the commit reverted, does increasing CMA avoid the issue?
E.g. add ``cma=64M`` to cmdline.txt ?

**Comment by smp79** [comment]
No, cma=64M does nothing.

> People with issues tend to be recording and playing live TV or running background jobs like torrents

I actually noticed the audio dropouts when only watching live TV with no extra background jobs. Those were rare but still annoying. Doing stuff like recording will just make the issue very obvious and easy to reproduce.

**Comment by mkreisl** [comment]
Hmmm, that's weird. I'm running JDownloader2 in background while watching TV. Everything is on network (Videos, JDownloader saves data on network, even root fs is on iSCSI network disk) Never had audio dropouts even when playing 1080p HEVC vids

(XBian, Kodi Leia B1, 4.18.0+, Pi3B+)

**Comment by smp79** [comment]
The issue is more pronounced when the USB DVB tuner is used. It is harder to reproduce when just streaming video over LAN.
Also, those dropouts are sometimes very short - less than a second, so they can go unnoticed.
