### ISSUE TITLE
How to build kernel and firmware .deb

### ISSUE THREAD

**Issue by alexreinert** [raspberrypi/linux#2505]
Hi,

how can I build the .deb files for kernel and firmware?

Background: I need the fixes for bridging with the lan78xx but for some internal reasons I cannot use rpi-update.

Thanks,
Alex

**Comment by kukabu** [comment]
https://kernel-handbook.debian.net/ch-common-tasks.html#s-common-building

**Comment by alexreinert** [comment]
This does just build "normal" linux kernel packages, but not the packages used by Raspbian and not the firmware packages.

**Comment by pelwell** [comment]
This is a packaging issue, not a kernel issue - try here: https://github.com/RPi-Distro/repo/issues
