### ISSUE TITLE
Raspberry Pi corrupted packets over serial

### ISSUE THREAD

**Issue by leragequit** [raspberrypi/linux#2506]
When reading large packets from a Serial -> USB converter I can observe corrupted packages, with invalid or missing data. 

**This behaviour is only exibited using the raspberry pi linux kernel.** 

Could test and confirm this with rpi3, cm3, rpi1 model b+ and very late and early iterations ( 4 year ago) of raspbian.
The bug was not present in debian aarch64 on rpi3 and cm3, was not present when using the beaglebone.

Can anyone confirm this bug? Read 12k serial from an arduino or s.th. at 921600 baud. bytes should be missing or currupted regardless of hardware used when using the raspberry pi kernel.

Regards,
Sascha

**edit:**
the dwc_otc.speed=1 option seems to improve the situation.
but considering i have multiple highspeed devices attached this might not be a viable "workaround"

**Comment by P33M** [comment]
Ah. You have a high baudrate. It's likely that our endpoint throttling is causing FIFO overflows inside your usb-serial adapter.

What happens if you add `dwc_otg.nak_holdoff=1` to /boot/cmdline.txt?

**Comment by P33M** [comment]
No OP response after >2 weeks. Closing unless bug is reported as unfixed.
