### ISSUE TITLE
add CONFIG_F2FS_FS_XATTR=y

### ISSUE THREAD

**Issue by monetny** [raspberrypi/linux#2508]
I think CONFIG_F2FS_FS_XATTR=y is good idea for use f2fs as rootfs

PS more others built-in FS have it

Thx

**Comment by monetny** [comment]
Possible need add CONFIG_F2FS_FS_POSIX_ACL too
I do not know

**Comment by Ferroin** [comment]
For whoever from the foundation is looking at this, xattr support is needed for most LSM's other than AppArmor (including, but not limited to SELinux, SMACK, IMA, and EVM), as well as a number of user programs that are of particular interest when dealing with low-per-node-cost systems like the Pi (such as GlusterFS, which uses xattrs to store information about the synchronization state between nodes).

Also, adding POSIX ACL support has near zero overhead if you're already adding extended attribute support, though it's a rarely used feature in most cases (90% of the usage I've seen is in `/dev`, which doesn't need support for it in the root filesystem).

**Comment by JamesH65** [comment]
I think we are going to need a better specced list of what needs to be enabled in the kernel for your use case, and what impact it would have on memory and CPU.

**Comment by JamesH65** [comment]
I believe the current kernel (4.14.50, released today) has 

CONFIG_F2FS_FS=y
CONFIG_F2FS_STAT_FS=y
CONFIG_F2FS_FS_XATTR=y
CONFIG_F2FS_FS_POSIX_ACL=y

So I believe this covers the requirements in this issue.
