### ISSUE TITLE
DS1621 sensor driver kernel module is missing

### ISSUE THREAD

**Issue by soosp** [raspberrypi/linux#2509]
I'm running Raspbian 9.4 on an Raspebrry Pi 3 with the latest kernel (Linux pi1 4.14.33-v7+ #1109 SMP Tue Apr 10 17:28:38 BST 2018 armv7l GNU/Linux). I need to use a DS1621 I2C temperature sensor but the related kernel module is missing. Please include it into the next build.

**Comment by soosp** [comment]
It would be nice to add a proper overlay too.
Thanks in advance.

**Comment by soosp** [comment]
Sorry I did want to post it to the firmware repository.

**Comment by pelwell** [comment]
No - this is the right place.

**Comment by pelwell** [comment]
Done. It will be in the next firmware build.

**Comment by pelwell** [comment]
Usage is:
```
dtoverlay=i2c-sensor,ds1621
```
or
```
dtoverlay=i2c-sensor,ds1621,addr=0x4c
```
The address can range from 0x48 (the default) to 0x4f.

Note I don't have a ds1621 to test, but it ought to work.

**Comment by soosp** [comment]
Thank you! It works well:
\# sensors
ds1621-i2c-1-48
Adapter: bcm2835 I2C adapter
temp1:        +26.5°C  (low  = +10.0°C, high = +60.0°C)

I have to use it to monitor the internal temperature of the enclosure of Pi. This sensor is supported by watchdog daemon via the sysfs interface.

**Comment by soosp** [comment]
BTW: You mistyped the address range in the README of overlays.
