### ISSUE TITLE
brctl kernel internal errror

### ISSUE THREAD

**Issue by thecalle** [raspberrypi/linux#2516]
**4.14.30-v7+ #1102**
installed: bridge-utils (1.5-13+deb9u1) (apt-get -yf install **bridge-utils**)
run: brctl addbr br0 , OK
run **brctl addif br0 eth0**
effect:

Message from syslogd@raspberrypi at Apr 18 04:51:07 ...
**kernel:[ 2181.018431] Internal error: Oops: 17 [#1] SMP ARM**

Message from syslogd@raspberrypi at Apr 18 04:51:07 ...
kernel:[ 2181.066793] Process brctl (pid: 3206, stack limit = 0xb6b36210)

Message from syslogd@raspberrypi at Apr 18 04:51:07 ...
kernel:[ 2181.070141] Stack: (0xb6b37d28 to 0xb6b38000)

Message from syslogd@raspberrypi at Apr 18 04:51:07 ...
kernel:[ 2181.073476] 7d20: b9daf000 00000000 b6b37d5c b6b37d40 8058784c 8057fe78

**system LOST. Need hardware reboot.**

**Comment by pelwell** [comment]
1. Which model of Pi is this?
2. What does `uname -a` return?

**Comment by thecalle** [comment]
Linux raspberrypi 4.14.30-v7+ #1102 SMP Mon Mar 26 16:45:49 BST 2018 armv7l GNU/Linux
Raspberry Pi 3 Model B+

**Comment by pelwell** [comment]
That kernel pre-dates a fix I added to the lan78xx Ethernet driver that may prevent the crash. Please run `sudo rpi-update` to get the latest kernel, then retest.

**Comment by thecalle** [comment]
rpi-update move the kernel to last, but no kernel-headers to build from sources.
I need to build the DW-131 driver non present in kernel.

**Comment by pelwell** [comment]
You're in luck. Apparently we've just (today) updated the Raspbian kernel and kernel headers packages, so if you `sudo apt-get update` and reinstall them you should get a compatible pair including the Ethernet driver fixes.

**Comment by thecalle** [comment]
Firmware upgraded and Bridge is working correctly.
Sadly no build in headers:
make[1]: *** /lib/modules/4.14.34-v7+/build: No such file or directory.  Stop.
Can't build my drivers.

**Comment by XECDesign** [comment]
is raspberrypi-kernel-headers installed?

**Comment by thecalle** [comment]
of course. the /build folder is missing. Now I'm trying to use dkms

**Comment by XECDesign** [comment]
Seems to be there from here:
```
pi@serge-testpi:~ $ dpkg -S /lib/modules/4.14.34-v7+/build
raspberrypi-kernel-headers: /lib/modules/4.14.34-v7+/build
pi@serge-testpi:~ $ ls -la /lib/modules/4.14.34-v7+/build/
total 1104
drwxr-xr-x  24 root root   4096 Apr 18 11:56 .
drwxr-xr-x   4 root root   4096 Apr 18 12:01 ..
drwxr-xr-x  32 root root   4096 Apr 18 11:56 arch
drwxr-xr-x   3 root root   4096 Apr 18 11:56 block
drwxr-xr-x   2 root root   4096 Apr 18 11:56 certs
-rw-r--r--   1 root root 156088 Apr 17 13:06 .config
drwxr-xr-x   4 root root   4096 Apr 18 11:56 crypto
drwxr-xr-x  10 root root   4096 Apr 18 11:56 Documentation
drwxr-xr-x 130 root root   4096 Apr 18 11:56 drivers
drwxr-xr-x   2 root root   4096 Apr 18 11:57 firmware
drwxr-xr-x  74 root root   4096 Apr 18 11:57 fs
drwxr-xr-x  29 root root   4096 Apr 18 11:40 include
drwxr-xr-x   2 root root   4096 Apr 18 11:57 init
drwxr-xr-x   2 root root   4096 Apr 18 11:57 ipc
-rw-r--r--   1 root root    287 Apr 17 13:06 Kconfig
drwxr-xr-x  16 root root   4096 Apr 18 11:57 kernel
drwxr-xr-x  13 root root   4096 Apr 18 11:57 lib
-rw-r--r--   1 root root  60722 Apr 17 13:06 Makefile
drwxr-xr-x   3 root root   4096 Apr 18 11:57 mm
-rw-r--r--   1 root root 792352 Apr 17 13:06 Module.symvers
drwxr-xr-x  69 root root   4096 Apr 18 11:57 net
drwxr-xr-x  27 root root   4096 Apr 18 11:57 samples
drwxr-xr-x  14 root root   4096 Apr 18 11:57 scripts
drwxr-xr-x  10 root root   4096 Apr 18 11:57 security
drwxr-xr-x  24 root root   4096 Apr 18 11:57 sound
drwxr-xr-x  25 root root   4096 Apr 18 11:57 tools
drwxr-xr-x   2 root root   4096 Apr 18 11:57 usr
drwxr-xr-x   4 root root   4096 Apr 18 11:57 virt
```

**Comment by thecalle** [comment]
**SOLVED:**
root@raspberrypi:~# apt-get upgrade
Reading package lists... Done
Building dependency tree
Reading state information... Done
Calculating upgrade... Done
The following packages will be upgraded:
  **libraspberrypi-bin libraspberrypi-dev libraspberrypi-doc libraspberrypi0 raspberrypi-bootloader** **raspberrypi-kernel**
6 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
**REBOOT**
**apt-get install raspberrypi-kernel-headers**
root@raspberrypi:/home/pi# dpkg -S /lib/modules/4.14.34-v7+/build
raspberrypi-kernel-headers: /lib/modules/4.14.34-v7+/build
At the end, I got the build DIR.
