### ISSUE TITLE
1-Wire: crc=NO and w1_slave No such file or directory during high ethernet throughput

### ISSUE THREAD

**Issue by iz8mbw** [raspberrypi/linux#252]
Hi.
I'm using three 1-Wire temperature sensor in the same time on the Raspberry Pi, all works OK also in Parasite power (w1-gpio pullup=1 into the file /etc/modules).
There is only a problem during a considerable ethernet throughput.
I try to explane it better, follow this example:
I'm downloading three files in the same time, the total network download speed is 1.8 MB/sec, if I interrogate one or more sensor I beginning to get crc=NO, and later, after more crc=NO, I get: No such file or directory (es: cat /sys/devices/w1_bus_master1/3b-00000014fe14/w1_slave: No such file or directory). After same minutes the sensor come up again and the file w1_slave is again there. Leter the problem happens again untill the ethernet traffic will finish. This problem occurred even before the pullups option for w1 interface.
The /var/log/messages says:
Mar 19 11:23:13 raspberrypi kernel: [ 2694.207597] w1_slave_driver 3b-00000014fe14: 18S20 doesn't respond to CONVERT_TEMP.

but only during crc=NO, no infos during w1_slave: No such file or directory.

If you need more info, let me know.
Thanks!

**Comment by P33M** [comment]
This will have been significantly improved through the use of tasklet-context USB URB completions, which eliminates a significant source of hard-IRQ latency.

Additionally, smsc95xx.turbo_mode=N has been a default for a while which also seems to help with IRQ latency.

Reply if this is still an issue.

**Comment by arslankhawar** [comment]
File "temp.py", line 9, in <module>
    device_folder = glob.glob(base_dir + '28*')[0]
IndexError: list index out of range

I'm getting this error in my file .

I'm using DS18B20 with raspberry zero w.

These are the files it showing

sudo modprobe w1-gpio
pi@raspberrypi:~ $ sudo modprobe w1-therm
pi@raspberrypi:~ $ cd /sys/bus/w1/devices
pi@raspberrypi:/sys/bus/w1/devices $ ls
00-080000000000  00-700000000000  00-f00000000000  w1_bus_master1

and when is use
 cd 00-080000000000
pi@raspberrypi:/sys/bus/w1/devices/00-080000000000 $ cat w1_slave
cat: w1_slave: No such file or directory

it gives me this error...!!!
Kindly someone help me to resolve this issue...

Thanks in advance ....!!!!

**Comment by dennisdegreef** [comment]
```
[  161.713278] w1_master_driver w1_bus_master1: Attaching one wire slave 28.03172493c2ff crc ea
[  206.438617] w1_slave_driver 28-03172493c2ff: Read failed CRC check
[  266.850151] w1_slave_driver 28-03172493c2ff: Read failed CRC check
[  548.409108] w1_master_driver w1_bus_master1: Attaching one wire slave 28.03172493c2ff crc ea
[  567.491730] w1_slave_driver 28-03172493c2ff: Read failed CRC check
[  626.932544] w1_slave_driver 28-03172493c2ff: Read failed CRC check
[  767.080550] w1_master_driver w1_bus_master1: Attaching one wire slave 28.03172493c2ff crc ea
[  855.141339] w1_master_driver w1_bus_master1: Attaching one wire slave 00.800000000000 crc 8c
[  855.148409] w1_master_driver w1_bus_master1: Family 0 for 00.800000000000.8c is not registered.
[  918.762380] w1_master_driver w1_bus_master1: Attaching one wire slave 00.400000000000 crc 46
[  918.769537] w1_master_driver w1_bus_master1: Family 0 for 00.400000000000.46 is not registered.
[  969.503365] w1_master_driver w1_bus_master1: Attaching one wire slave 00.c00000000000 crc ca
[  969.510467] w1_master_driver w1_bus_master1: Family 0 for 00.c00000000000.ca is not registered.
[ 1045.944922] w1_master_driver w1_bus_master1: Attaching one wire slave 00.200000000000 crc 23
[ 1045.951998] w1_master_driver w1_bus_master1: Family 0 for 00.200000000000.23 is not registered.
[ 1109.546284] w1_master_driver w1_bus_master1: Attaching one wire slave 00.a00000000000 crc af
[ 1109.553347] w1_master_driver w1_bus_master1: Family 0 for 00.a00000000000.af is not registered.
[ 1147.467689] w1_master_driver w1_bus_master1: Attaching one wire slave 00.600000000000 crc 65
[ 1147.479078] w1_master_driver w1_bus_master1: Family 0 for 00.600000000000.65 is not registered.
[ 1187.948499] w1_master_driver w1_bus_master1: Attaching one wire slave 00.e00000000000 crc e9
[ 1187.956556] w1_master_driver w1_bus_master1: Family 0 for 00.e00000000000.e9 is not registered.
[ 1250.950440] w1_master_driver w1_bus_master1: Attaching one wire slave 00.100000000000 crc 9d
[ 1250.957441] w1_master_driver w1_bus_master1: Family 0 for 00.100000000000.9d is not registered.
[ 1290.071381] w1_master_driver w1_bus_master1: Attaching one wire slave 00.900000000000 crc 11
[ 1290.078443] w1_master_driver w1_bus_master1: Family 0 for 00.900000000000.11 is not registered.
[ 1818.484485] w1_master_driver w1_bus_master1: Attaching one wire slave 28.03172493c2ff crc ea
[ 1886.718380] w1_slave_driver 28-03172493c2ff: Read failed CRC check
[ 1909.918963] w1_slave_driver 28-03172493c2ff: Read failed CRC check
[ 1929.039410] w1_slave_driver 28-03172493c2ff: Read failed CRC check
[ 1947.119819] w1_slave_driver 28-03172493c2ff: Read failed CRC check
[ 1955.840021] w1_slave_driver 28-03172493c2ff: Read failed CRC check
```

I am experiencing the same...

**Comment by pelwell** [comment]
Raspberry Pis have no 1wire hardware - the interface is bit-bashed in software using GPIOs. For small numbers of devices where the system is lightly loaded this can work fine, but if you start doing exotic things like parasitic powering with more than one device then you are unlikely to succeed.

If you want more support you'll have to write more than a me-too, but essentially there isn't much we can do.
