### ISSUE TITLE
When LCD rotate ,and then Touch screen flip.

### ISSUE THREAD

**Issue by nickfox-taterli** [raspberrypi/linux#2525]
This is wrong. This problem does not occur with Windows Desktop.

When LCD rotate ,and then Touch screen flip.

Can not touch,I test with:

xinput set-prop 7 --type=int --format=8 "Evdev Axes Swap" 1
xinput set-prop 7 --type=int --format=8 "Evdev Axis Inversion" 0 1

not ok at all.

**Comment by JamesH65** [comment]
Are you using the Raspberry Pi LCD display? 

If so, have you tried setting the device tree values for the touchscreen to specify the rotates and flips?

**Comment by JamesH65** [comment]
@nickfox-taterli Ping. We cannot help if you don't tell us what you are trying.

**Comment by nickfox-taterli** [comment]
I using HDMI CTP display but that is not ok to flip touch screen and decided to give this try.
