### ISSUE TITLE
Dist-upgrade breaks jessie image

### ISSUE THREAD

**Issue by folder12** [raspberrypi/linux#2526]
Hello,

today I upgraded my jessie image, first with a normal upgrade (sudo apt-get upgrade). After the upgrade the system started normal.
Afterwards I did a
sudo apt-get dist-upgrade
After that the system is not accessible anymore. The red power LED is on, the green LED keeps signaling.
There is no HDMI output and the ethernet/wifi interface doesn't become accessible.
It's the same for pi 3 and pi 3+.
Attached, you will find the log file of the dist-upgrade:
[2018_04_23_dist-upgrade.log](https://github.com/raspberrypi/linux/files/1937567/2018_04_23_dist-upgrade.log)

Might this be a problem with the bootloader package? Also, it seems the kernel is de-installed.
I restored the backup of my SD card, but I would like to update my hardware to the new pi 3+.
Any help is appreciated.
Regards,

**Comment by XECDesign** [comment]
We don't support or update Jessie. The nokernel packages are not ours. You may wish to report the issue here: https://bugs.launchpad.net/raspbian/

**Comment by folder12** [comment]
Thank you for pointing me in the right direction.
