### ISSUE TITLE
usblp module

### ISSUE THREAD

**Issue by ghost** [raspberrypi/linux#253]
Could you include the usblp module in the next raspbian release ?

thanks

**Comment by popcornmix** [comment]
Is:
CONFIG_USB_ULPI=y

what you are requesting?

**Comment by Mkalla** [comment]
Yeah the usblp module would be very nice!

**Comment by ghost** [comment]
+1

**Comment by kadamski** [comment]
I believe that the OP was referring to `CONFIG_USB_PRINTER=y`:

```
$ grep usblp drivers/usb/class/Makefile
obj-$(CONFIG_USB_PRINTER)       += usblp.o
```

**Comment by ghost** [comment]
Yes - the one that produces the usblp.ko kernel module please. It is required for my printer - see http://andrum99.blogspot.co.uk/2013/06/getting-hp-laserjet-1018-printer.html

See also http://www.raspberrypi.org/phpBB3/viewtopic.php?f=29&t=22498

**Comment by ghost** [comment]
Fixed as of 3/6/2013 - thanks!
