### ISSUE TITLE
rpi 3b+: cat /sys/class/thermal/thermal_zone0/temp: invalid argument

### ISSUE THREAD

**Issue by m1027** [raspberrypi/linux#2530]
On my rapberry 3b+ I cannot read the cpu temperature:
```
cat /sys/class/thermal/thermal_zone0/temp: invalid argument
```
Kernel is 4.14.34 from https://github.com/raspberrypi/linux.git with
```
CONFIG_THERMAL=y                                                               
CONFIG_THERMAL_HWMON=y
CONFIG_THERMAL_OF=y
CONFIG_THERMAL_DEFAULT_GOV_STEP_WISE=y                                         
CONFIG_THERMAL_GOV_STEP_WISE=y                                                                              
CONFIG_BCM2835_THERMAL=y
```

Firmware is on
commit ae9a493932e47e08cabb25a2728037298075fd00
Author: popcornmix <popcornmix@gmail.com>
Date:   Tue Apr 10 18:34:46 2018 +0100

    kernel: LAN78xx VLAN checksum fix
from https://github.com/raspberrypi/firmware.git.

FYI: I have some rpi 3 (non-plus version) around with similar setup where reading the temperature works.

**Comment by pelwell** [comment]
It works for me, so your configuration must be different in some way. Based on your wording I'm guessing you've built your own kernel.

1. Try the same image - the same card - in a Pi 3B.
2. Try a Raspbian image - it shouldn't take long to download and install Raspbian Lite to a spare SD card.
3. In your kernel source tree, after the configuration step, run the following commands and report the output:
```
$ make ARCH=arm savedefconfig
$ diff arch/arm/configs/bcm2709_defconfig defconfig
```

**Comment by JamesH65** [comment]
@m1027 Any luck with the suggestions above?

**Comment by m1027** [comment]
> @m1027 Any luck with the suggestions above?

Thanks for asking.

I haven't tried yet since starting with a default kernel might fix it but
later stripping it down to what is actually required here is a huge task.

I thought I'd get some clues here to circumvent that way.

Feel free to close this issue or put it in a wait state. I'll come back on at
some point in the future.

**Comment by m1027** [comment]
Without using the default kernel, after a simple update of firmware and kernel
(4.14.34 to 4.14.39) the temperature value 'temp' can be read out properly.

Thanks
