### ISSUE TITLE
How to use ltc2941 on rpi3

### ISSUE THREAD

**Issue by Zhairgling** [raspberrypi/linux#2537]
Hi all,

With a friend we made a pcb wich use the ltc2941 for monitoring the batterie, I see the i2c id wich is 64. 

`pi@raspberrypi:~ $ i2cdetect -y 1

     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f

     00: -- -- -- -- -- -- -- -- -- -- -- -- --

     10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --

     20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --

     30: -- -- -- -- -- -- -- -- UU -- -- -- -- -- -- --

     40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --

     50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --

     60: -- -- -- -- 64 -- -- -- UU -- -- -- -- -- -- --

     70: -- -- -- -- -- -- -- --
`
I have seen in the linux kernel sources that a driver exist.( linux/drivers/power/supply/ltc2941-battery-gauge.c ).
Can someone help me to get it working ?

`
    pi@raspberrypi:~ $ uname -a 

    Linux raspberrypi 4.9.30-v7+ #1001 SMP Fri May 26 16:09:18 BST 2017 armv7l GNU/Linux
`

Thank's a lot.

**Comment by pelwell** [comment]
It will need `CONFIG_BATTERY_GAUGE_LTC2941=m` adding to the standard defconfigs (it results in a 13kB module, which is reasonable), and it will need an overlay (or an entry in an an overlay) to get it working.

Take a look at the [i2c-sensor overlay](https://github.com/raspberrypi/linux/blob/rpi-4.14.y/arch/arm/boot/dts/overlays/i2c-sensor-overlay.dts) and the [README](https://github.com/raspberrypi/linux/blob/rpi-4.14.y/arch/arm/boot/dts/overlays/README#L829). The [bindings document](https://github.com/raspberrypi/linux/blob/rpi-4.14.y/Documentation/devicetree/bindings/power/supply/ltc2941.txt) shows you the things you can tweak - the value of the sense resistor and the exponent for the prescaler. The overlay is likely to be a bit daunting, but if you write the README entry you would like then I can do the rest.

**Comment by Zhairgling** [comment]
Thank's for your help.


I was able to inform the structure of the README. without great convictions regarding the prescaler exponent. I'm not comfortable enough with the rest of the process.


`	fuelgauge: ltc2941@64 {

		compatible = "lltc,ltc2941";

		reg = <0x64>;

		lltc,resistor-sense = <50>;

		lltc,prescaler-exponent = <7>; 
	};`

does this seem legit to you?

**Comment by pelwell** [comment]
Yes, that looks sensible. Post your README entry here so I'm not starting with a blank page. Include parameters for setting the resistor value and exponent - don't worry how to implement them, just keep the units the same.

**Comment by Zhairgling** [comment]
Thank's again for the help,
can you explain me how to find this README ?

**Comment by pelwell** [comment]
I provided a link to it in the kernel source tree above (it's [here](https://github.com/raspberrypi/linux/blob/rpi-4.14.y/arch/arm/boot/dts/overlays/README#L829)), but you can also find it in the /boot/overlays directory on a Raspbian image.

**Comment by Zhairgling** [comment]
I writed something about your request, maybe something is missing, are you ok with that ?


```
Name:   ltc2941
Info:   Adds support for the ltc2941 battery gauge     
Load:   dtoverlay=ltc2941,<param>=<val>
Params: compatible              Should contain "lltc,ltc2941", "lltc,ltc2942",  
                                "lltc,ltc2943" or "lltc,ltc2944" which also 
                                indicates the type of I2C chip attached.

        reg                     The 7-bit I2C address.
                                

        resistor-sense          The sense resistor value in milli-ohms.
                                Can be a 32-bit
                                negative value when the battery has been 
                                connected to the wrong end of the resistor.

        prescaler-exponent      Range and accuracy of the gauge.The value 
        						is programmed into thechip only if it differs
        						from the current setting.
                                For LTC2941 only:
                                - Default value is 128
                                - 3 bits are available in register "B" to set 
                                the exponent, it should be 
                                like: 2^(4*B[5]+2*B[4]+B[3]).
                                - Due to the only 3 bits available to set the
                                Prescaler in LTC2941, it should be a multiple
                                of 2.
                                (1, 2, 4, 8, 16, 32, 64, 128).


```

**Comment by pelwell** [comment]
Thanks - that's good enough for me to work with.

**Comment by pelwell** [comment]
There is now provisional support in the kernel tree. Please test it when you can, either by building your own kernel or waiting for the next rpi-update kernel release.

**Comment by Zhairgling** [comment]
Thank's i want test it but don't know how to add provisional support with my current kernel wich is already custom.

**Comment by pelwell** [comment]
Is this custom kernel one you have built yourself? If so, all you need to do is add the addition config setting - I can upload the overlay somewhere for you to try.

**Comment by Zhairgling** [comment]
To try to be simple at first I will try to recompile the kernel from official sources with the changes you made. Where can I download the sources?
I'm interested too by the overlay

**Comment by pelwell** [comment]
Follow the guide here (https://www.raspberrypi.org/documentation/linux/kernel/building.md) to download and build the latest 4.14 kernel - the source code comes from _this_ git repo (https://github.com/raspberrypi/linux). Doing so will also build and install the overlay.

**Comment by Zhairgling** [comment]
I will try

**Comment by Zhairgling** [comment]
I followed the link you gave me.
After a reboot I have no more i2c or spi despite the fact that it is enabled in /boot/config.txt .
any idea ?

**Comment by pelwell** [comment]
Both of those drivers are modules - did you build and install the modules?
```
make -j4 zImage modules dtbs
sudo make modules_install              <===
sudo cp arch/arm/boot/dts/*.dtb /boot/
sudo cp arch/arm/boot/dts/overlays/*.dtb* /boot/overlays/
sudo cp arch/arm/boot/dts/overlays/README /boot/overlays/
sudo cp arch/arm/boot/zImage /boot/$KERNEL.img
```

**Comment by Zhairgling** [comment]
I've followed it Yes. I wil retry tomorow

**Comment by Zhairgling** [comment]
It seems to work, I need more testing but I use upower (https://packages.debian.org/en/jessie/upower) to check the values. Is this the best way?

**Comment by pelwell** [comment]
I'm not the best person to as - I spend much more time down at the kernel level - but it looks OK.

Please close this issue if you think the matter is now resolved.
