### ISSUE TITLE
pifacecommon not up-to-date

### ISSUE THREAD

**Issue by spiro-trikaliotis** [raspberrypi/linux#2539]
The package python3-pifacecommon reports itself as version 4.2.1. However, it differs in one patch from the version from here: https://github.com/piface/pifacecommon.

It misses the patch d4c568926e, cf. https://github.com/piface/pifacecommon/commit/d4c568926e49dc75a983e2fed41b79ebf317b10d?diff=unified. That one is needed in order to run piface (for example the digital IO) on newer kernels:

Can you include that one in a Raspbian package so the piface can be run without a local patch?

Regards
Spiro Trikaliotis

**Comment by spiro-trikaliotis** [comment]
I am sorry, I am in the wrong bug tracker. Closing here and searching for the right one.

**Comment by XECDesign** [comment]
The package was provided by piface. The correct place to report it is https://github.com/piface/pifacecommon. The last reply I saw from them was that they no longer support the debian package and tell people to use pip instead. I also think that they're having somebody look into providing .debs again.

**Comment by spiro-trikaliotis** [comment]
Thank you for your reply.
I just tried with pip (more precisely, pip3). It still gives the "wrong" spi.py file, without the patch. Thus, this is no solution, either.
