### ISSUE TITLE
Requesting CONFIG_DM_CACHE=m and CONFIG_DM_CACHE_SMQ=m for arm7 and aarch64

### ISSUE THREAD

**Issue by ShapeShifter499** [raspberrypi/linux#2553]
I'm requesting these two modules be added to the kernel config because they are required for the 'sd-lvm2' and 'lvm2' mkinitcpio modules on some operating systems.  From what I can tell 'CONFIG_DM_CACHE=m' is already on the arm7 config but not the aarch64 one.

**Comment by pelwell** [comment]
Actually, it looks like CONFIG_DM_CACHE was only ever enabled for rpi-4.4.y - it was requested in https://github.com/raspberrypi/linux/issues/1793 must have got lost in the move to rpi-4.5.y. Enabling CONFIG_DM_CACHE automatically enables CONFIG_DM_CACHE_SMQ, which means that the SMQ feature was also present in 4.4 but subsequently dropped.

I therefore have no problem re-enabling it - see 2a6adf636ba83c450f0140b2dbcda5fc66e6b0de.

**Comment by ShapeShifter499** [comment]
Thank you for fixing this, feel free to close this issue.
