### ISSUE TITLE
pi 3b+: after reboot LAN requires ping to work

### ISSUE THREAD

**Issue by m1027** [raspberrypi/linux#2554]
Since I've replaced my pi3 by a pi3b+ I encounter this strange behaviour:

After each reboot of the pi, a wlan router connected to the pi via lan cable
cannot reach the pi anymore, unless the pi simply pings the wlan box once.
Only after that ping, everything works as expected.

Some hints:

- To debug this issue I access the pi via another USB/ethernet adapter since
  the built-in LAN is disfunctional.

- When sending out the ping, the first package has a significant higher round
  trip time (about 2-15 ms) while the following ones are below 1 ms as usual
  for LAN.

- Simply pulling the LAN cable (or turning the wlan router off and on)
  does not help.

- The LAN cable is quite long, about 30 m.

- After a fresh reboot and before sending the ping the pi's LAN device is not
  DOWN but UP (as reported by ip link show).

- Firmware and Kernel (4.14.39) are from today (2018-05-13).

Any clues?

Thanks

**Comment by m1027** [comment]
Two issues that might be related:

https://github.com/raspberrypi/linux/issues/2449 deals with unsolved transfer
issues and drops/stalls concerning the ethernet connection of the pi 3b+
(while having the same working on a pi3).  I have the same issues, too.

https://github.com/raspberrypi/linux/issues/2522 sounds similar, while dealing
with wlan, not lan. Pinging somehow wakes up the system.

**Comment by m1027** [comment]
Just FYI:

I've replaced the pi 3B+ by the pi 3 again, keeping the exact OS (obviously
the kernel would use the other ethernet driver), and the forementioned issues
are gone.

**Comment by m1027** [comment]
Update: Checked 3B+ again, against new kernel 4.14.41 (was 4.14.39) which includes lan78xx fixes and also raspberry pi fixes for long cables. No solution for my issue, outgoing "wakeup" ping still required.

I will come back on this from time to time when I see interesting changes in the kernel or firmware.

**Comment by JamesH65** [comment]
This is an odd one. What make and model is the router? Is it a standard out of the box setup on both the Pi and the router?

**Comment by JamesH65** [comment]
@m1027 A probably fix for this is now in rpi-update, would you be able to test, and then close if fixed?

EDIT: Ignore that - not in rpi-update yet. But has been merged to our tree. Should be in rpi-update in next couple of days.

**Comment by m1027** [comment]
@JamesH65 Thanks for the hint. In case I can access the update this week I'd love to test it. Otherwise only end of August.

**Comment by m1027** [comment]
I've seen some related changes in firmware / kernel (I think 4.14.56 or so),
so I upgraded to the current firmware / kernel, now using 4.14.72.  Nothing
else changed, still long ethernet cables etc.

Issue solved.

Thank you all
