### ISSUE TITLE
Policykit problem after Stretch install

### ISSUE THREAD

**Issue by richardquint** [raspberrypi/linux#2568]
I am unable to get authentication dialogs for gui applications requiring root permissions in a vnc (tightvncserver) connection.  There is no problem with an x11vnc connection to the remote pi's desktop and I can use sudo in a terminal window in the tightvnc's desktop.  I've tried to make the Stretch install as close to my Jessie install as possible.  I have googled many similar reports, but none seem the same (usually on older Debian versions).

When I try to start synaptic from the drop down menu or in a terminal I get an error message in the terminal window.  When I try the Shutdown options I get nothing in the terminal window.

**Comment by XECDesign** [comment]
That's probably a question for the forum, since it's not a Linux kernel issue. It would help to include the exact error messages.
https://www.raspberrypi.org/forums/

**Comment by JamesH65** [comment]
Agreed, this is not a Linux kernel issue.

Closing as this issue is not kernel related.
