### ISSUE TITLE
bcm2708_fb_check_var: ERROR: VerticalTotal >= 1200; special treatment required! (TODO)

### ISSUE THREAD

**Issue by cleverca22** [raspberrypi/linux#259]
https://github.com/raspberrypi/linux/blob/rpi-3.6.y/drivers/video/bcm2708_fb.c#L194

how much work would it take to fix the 1200 pixel tall problem in here and add proper framebuffer panning?

its required for page-flipping to work properly most setups

**Comment by popcornmix** [comment]
For panning don't you want
yres == actual screen height (i.e. <=1200)
yres_virtual bigger than screen height.
yoffset as the pan offset

Doesn't that work?

**Comment by cleverca22** [comment]
let me check the code again...

ah, theres a minor difference in this fork of the driver, let me undo it and see how things work
(somebody is doubling yres in the driver, when the userspace app already handled that, oh wait, it just lacks the code for FB_VMODE_DOUBLE)

**Comment by cleverca22** [comment]
yeah, now that I've manually updated it to the same code as this repo, its not having a problem, yres is 1024 (under the limit) and yres_virtual is 2048 (code doesn't limit it)

its still showing symptoms of another problem, but my testing shows that they arent in the kernel side

dd if=/dev/urandom of=/dev/graphics/fb0 bs=1 count=1000000
this successfully writes garbage to the screen, and by watching dmesg for page-flips, it matches up with the whole screen blanking (kernel using the 2nd page, where i'm not writing yet)
everything in the kernel seems fine, i'll keep digging on the userspace side
