### ISSUE TITLE
Should the return value be checked to avoid Null Pointer Dereference error  ?

### ISSUE THREAD

**Issue by laoyaolandq** [raspberrypi/linux#2594]
In function _fc_eh_timed_out_ , which is defined in linux/drivers/scsi/scsi_transport_fc.c
```
2083-2086,
	struct fc_rport *rport = starget_to_rport(scsi_target(scmd->device));

	if (rport->port_state == FC_PORTSTATE_BLOCKED)
		return BLK_EH_RESET_TIMER;
```
_starget_to_rport_ is a macro defined in linux/include/scsi/scsi_transport_fc.h,
```
#define starget_to_rport(s)			\
	scsi_is_fc_rport(s->dev.parent) ? dev_to_rport(s->dev.parent) : NULL
```
Since _starget_to_rport_ may return a NULL value, the variable _report_  may be assigned NULL. Thus there is a potential Null Pointer Deref error in `if (rport->port_state == FC_PORTSTATE_BLOCKED)`. There should be a NULL value check for _rport_ .

**Comment by pelwell** [comment]
There are other places in the code (`fc_target_setup`, for example) where the return from `starget_to_rport is  checked, so I'm inclined to agree with you. However, this is untouched upstream Linux code and any issues should be reported to the maintainers:
```
$ scripts/get_maintainer.pl drivers/scsi/scsi_transport_fc.c
"James E.J. Bottomley" <jejb@linux.vnet.ibm.com> (maintainer:SCSI SUBSYSTEM)
"Martin K. Petersen" <martin.petersen@oracle.com> (maintainer:SCSI SUBSYSTEM)
linux-scsi@vger.kernel.org (open list:SCSI SUBSYSTEM)
linux-kernel@vger.kernel.org (open list)
```
