### ISSUE TITLE
Missing error check for function strdup in linux/scripts/mod/modpost.c

### ISSUE THREAD

**Issue by laoyaolandq** [raspberrypi/linux#2595]
In function _handle_modversions_ ,
```
680-683,
	char *munged = strdup(symname);
	munged[0] = '_';
	munged[1] = toupper(munged[1]);
	symname = munged;
```
Function _strdup_ will return a NULL pointer if an error occurs. Thus the return value of _strdup_ should be checked. Otherwise the dereference of _munged_ may be a Null Pointer Deref.

**Comment by pelwell** [comment]
This is untouched upstream Linux code and any issues should be reported to the maintainers.
