### ISSUE TITLE
bcm_dma_wait_idle not exported?

### ISSUE THREAD

**Issue by simonjhall** [raspberrypi/linux#26]
Hi there,

I'm using the BCM DMA functions from inside a kernel module.
I'm having a run-time link error as it appears that bcm_dma_wait_idle symbol is not exported. All the other interesting DMA functions are. Is this by design, or is this just an omission?

If it is by design, what is the best way of waiting for a DMA to finish? (IRQ?)

Kind regards,
Simon

**Comment by popcornmix** [comment]
That's just an omission as no-one is currently using that function.
Note the comment, this busy waits, so will hog the CPU.
This really need a down_interruptable that is triggered from the end of DMA imterrupt.

**Comment by simonjhall** [comment]
Ok cool cheers.
I'd seen the comment and was wondering if it's worth sticking in a schedule() call into the busy loop? (although I head that pre-emptive kernel doesn't work)

**Comment by ghollingworth** [comment]
Assuming this is now fixed?  It's been a while!
