### ISSUE TITLE
Create tag and release matching the official Raspbian image from 2018-06-27

### ISSUE THREAD

**Issue by VladimirTechMan** [raspberrypi/linux#2601]
The latest tag and release published for Raspberry Pi Linux kernel are "raspberrypi-kernel_1.20180417-1" at this point. Please, add a new tag and release matching the latest official Raspbian image from 2018-06-27: Having them is useful for those who build their own custom kernels – but want those to match the latest Raspbian image, aside from the custom modifications applied.

**Comment by XECDesign** [comment]
It takes a few days after release to update tags. Should be fine now.

**Comment by VladimirTechMan** [comment]
Yes, it looks fine now. Many thanks!
