### ISSUE TITLE
Possibility to use tags

### ISSUE THREAD

**Issue by graysky2** [raspberrypi/linux#262]
Have you guys considered the possibility of tagging your releases?  This would avoid the need for distro packagers to do a `git clone --depth 1 git://github.com/raspberrypi/linux.git` to bring down the source for compilation.

**Comment by popcornmix** [comment]
Can you be more explicit about what you would like?
Are you suggesting every commit to linux repo is tagged? Or just the points where the firmware repo is rebuilt? Or just the points where an sdcard release?
What would like the tag to consist of?

**Comment by graysky2** [comment]
I do not think every push should tagged at all... just points at which a distro would likely do a pkgrel or version bump.  Only when new key changes are made I guess.

In terms of the content of the tag, nothing fancy.  For example, I tend to use the following scheme in my stuff:
`git tag v5.23 -m 'v5.32 && git push --tags'`

You can use whatever kind of naming system you want, the key is that the tag is there so now I can point a package to a tarball github auto generates.

Example: https://github.com/graysky2/profile-sync-daemon/tags

**Comment by richo** [comment]
Bonus points if you can sign the tags with a PGP key with some trust behind
it.

**Comment by graysky2** [comment]
@richo - The tag is really harmless so no need for any kind of signing.  The security lies in the access to the source itself which is well protected with pub/priv keys.

**Comment by Ruffio** [comment]
@popcornmix this issue/feature request should be closed due to inactivity

**Comment by popcornmix** [comment]
Tags are now added when we update kernel is raspbian. See: https://github.com/raspberrypi/linux/tags
