### ISSUE TITLE
w1-gpio with parameters fails on loading file w1–gpio-overlay.dtb from config.txt

### ISSUE THREAD

**Issue by kcd83** [raspberrypi/linux#2627]
I found the dtoverlay command works as expected:
```
sudo dtoverlay w1-gpio gpiopin=17 pullup=0
cat /sys/bus/w1/devices/*/w1_slave
```
but placing the same overlay with the same parameters fails in `/boot/config.txt` on my Raspberry Pi 3

```
dtoverlay=w1–gpio,gpiopin=17,pullup=0
```

This is all new to me but I have done my homework and I think I've narrowed it down to the specific problem, if I have missed something let me know!

**Without parameters w1-gpio is OK**
`/boot/config.txt`
```
dtoverlay=w1-gpio
dtdebug=1
```

`$ vcdbg log msg`
```
002067.322: dtdebug: Opened overlay file 'overlays/w1-gpio.dtbo'
002069.919: brfs: File read: /mfs/sd/overlays/w1-gpio.dtbo
002078.478: Loaded overlay 'w1-gpio'
002078.522: dtdebug: Found fragment 0 (offset 36)
002078.615: dtdebug: merge_fragment(/,/fragment@0/__overlay__)
002092.562: dtdebug: merge_fragment(/onewire@0,/fragment@0/__overlay__/onewire@0)
002092.587: dtdebug:   +prop(compatible)
002095.486: dtdebug:   +prop(pinctrl-names)
002098.558: dtdebug:   +prop(pinctrl-0)
002101.633: dtdebug:   +prop(gpios)
002104.743: dtdebug:   +prop(rpi,parasitic-power)
002108.305: dtdebug:   +prop(status)
002111.422: dtdebug:   +prop(phandle)
002114.513: dtdebug: merge_fragment() end
```

**With parameters to change the pin w1-gpio fails to load**
`/boot/config.txt`
```
dtoverlay=w1–gpio,gpiopin=17,pullup=0
dtdebug=1
```

`$ vcdbg log msg`
```
002035.004: dtdebug: merge_fragment() end
002035.234: brfs: File read: 1689 bytes
002045.486: dtdebug: Failed to open overlay file 'overlays/w1–gpio.dtbo'
002053.786: dtdebug: Failed to open overlay file 'overlays/w1–gpio-overlay.dtb'
002062.083: dtdebug: Failed to open overlay file 'overlays/w1–gpio.dtb'
002062.096: Failed to load overlay 'w1–gpio'
002062.133: brfs: File read: /mfs/sd/overlays/w1–gpio.dtb
002073.613: dtparam: uart1=off
002078.732: dtdebug: Found override uart1
002078.767: dtdebug:   override uart1: string target 'status'
```

**However loading it ad-hoc with parameters works fine**

```
$ sudo dtoverlay -v w1-gpio gpiopin=17 pullup=0
run_cmd: which dtoverlay-pre >/dev/null 2>&1 && dtoverlay-pre
DTOVERLAY[debug]: Found override gpiopin
DTOVERLAY[debug]:   override gpiopin: cell target gpios @ offset 4 (size 4)
DTOVERLAY[debug]:   override gpiopin: cell target reg @ offset 0 (size 4)
DTOVERLAY[debug]:   override gpiopin: cell target brcm,pins @ offset 0 (size 4)
DTOVERLAY[debug]:   override gpiopin: cell target reg @ offset 0 (size 4)
DTOVERLAY[debug]: Found override pullup
DTOVERLAY[debug]:   override pullup: cell target rpi,parasitic-power @ offset 0 (size 4)
DTOVERLAY[debug]: delete_node(/__symbols__)
DTOVERLAY[debug]: Wrote 1036 bytes to '/tmp/.dtoverlays/0_w1-gpio.dtbo'
DTOVERLAY[debug]: Wrote 1057 bytes to '/sys/kernel/config/device-tree/overlays/0_w1-gpio/dtbo'
run_cmd: which dtoverlay-post >/dev/null 2>&1 && dtoverlay-post
$ cat /sys/bus/w1/devices/*/w1_slave
3c 01 4b 46 7f ff 0c 10 36 : crc=36 YES
3c 01 4b 46 7f ff 0c 10 36 t=19750

```

I also tried a few other variants including placing `dtoverlay=w1–gpio,gpiopin=17,pullup=0` first in `/boot/config.txt` and commenting out my `hifiberry-dacplus` so it doesn't seem like anything in my environment.

**My environment**
 
Details that may be relevant:

```
Linux version 4.14.52-v7+ (dc4@dc4-XPS13-9333) (gcc version 4.9.3 (crosstool-NG crosstool-ng-1.22.0-88-g8460611)) #1123 SMP Wed Jun 27 17:35:49 BST 2018
```

```
$ ls -la /boot/overlays/w1*
-rwxr-xr-x 1 root root 1116 May  5 14:32 /boot/overlays/w1-gpio.dtbo
-rwxr-xr-x 1 root root 1251 May  5 14:32 /boot/overlays/w1-gpio-pullup.dtbo
```

And again, outside of boot things look in order
```
pi@hifiberrry:~ $ sudo dtoverlay w1-gpio gpiopin=17 pullup=0
pi@hifiberrry:~ $ lsmod | grep w1
w1_therm               16384  0
w1_gpio                16384  0
wire                   40960  2 w1_gpio,w1_therm
(failed reverse-i-search)`dl': lsmo^C| grep w1
pi@hifiberrry:~ $ dtoverlay -l
Overlays (in load order):
0:  w1-gpio  gpiopin=17 pullup=0
```

I'm not sure why when my Hifiberry DAC is loaded it doesn't show in the above but works and is in the log.

```
002124.740: Loaded overlay 'hifiberry-dacplus'
```

https://pinout.xyz/pinout/1_wire
https://www.raspberrypi.org/documentation/configuration/device-tree.md#part4

**Comment by pelwell** [comment]
It being holiday season I'm unable to run any tests at the moment, but you have my interest.

Can you post the complete output of vcdbg log msg

**Comment by pelwell** [comment]
Try again.

It being holiday season I'm unable to run any tests at the moment, but you have my interest.

1. Please post the complete output of `vcdbg log msg |& grep -vi hdmi` for the cases where you load the overlay from config.txt, with and without parameters.

2. How are you booting your Pi - just from SD card, bootcode.bin on SD then network booting start.elf, or fully network booted?

The reason your hifiberry overlay doesn't show up in the list of applied overlays is that the firmware bakes them into the standard DTB - the kernel has no idea they are there, except for seeing they changes they make.

**Comment by kcd83** [comment]
Great, yes I will do that but I too am away even though it is not holiday season in this hemisphere.

I'm just booting from SD card, raspbian sketch lite and using ansible to configure it. Thanks for the answer about the hifiberry overlay too.

**Comment by bsimmo** [comment]
Can you try it without the pullup command in config.txt
dtoverlay=w1–gpio,gpiopin=17

I mention as that's how I use it, I have mine on pin22, same 4.14.52 (zero) and never had a problem through the updates.

**Comment by pelwell** [comment]
I've had a quick play with the overlay and it is behaving as I would expect, so complete logs and config.txt - when you are ready - are going to be essential to understanding your problem.

**Comment by kcd83** [comment]
oohhhhh FFS, sorry everyone

```
pi@hifiberrry:~ $ diff /boot/config.txt config.txtbad
58c58
< dtoverlay=w1-gpio,gpiopin=17,pullup=0
---
> dtoverlay=w1–gpio,gpiopin=17,pullup=0
```
Can you see it?

Here are the logs anyway: https://pastebin.com/jBp4pS0d

**Comment by bsimmo** [comment]
Flipping heck, that's hard to spot.  What character is that?

**Comment by pelwell** [comment]
No worries - this has happened before, and is probably the result of copying from a web page that has been prettified by a content management system (or copy editor).

**Comment by kcd83** [comment]
Yeah it doesn't look quite long enough to be an m-dash but it is clearly not the usual n-dash and would have come from a web page, ironically because I was copying and pasting to _prevent_ typos. I only spotted it in the git diff of my ansible playbook i read building. I can now spot it in my question above too so at least i was consistent.

FYI with or without pull up both work.

**Comment by kcd83** [comment]
Ha, my mobile browser doesn't render it any different but desktop browser did.
