### ISSUE TITLE
I-Sabre K2M

### ISSUE THREAD

**Issue by antonellocaroli** [raspberrypi/linux#2636]
why is the  I-Sabre K2M module not included directly in the kernel?

https://github.com/SatoruKawase/I-Sabre-K2M

**Comment by pelwell** [comment]
Because the driver hasn't been submitted/accepted upstream.

**Comment by clivem** [comment]
They make no secret (copyright attribution) that this code is either the original work (or based on) the original work done by Satoru Kawase for the SabreBerry DAC. Whilst the Japanese distributor for ESS gave permission for there to be an Open Source driver, (exposing I2C programming data contained in the ESS datasheet, which is under NDA), the US head office (legal people) expressly forbade this driver being made available as Open Source. It is not possible to publish any driver for an ESS chipset, that exposes any I2C programming info, that was obtained from the NDA'd datasheet under GPL. That several people/companies producing boards that use recent ESS DAC chipsets want to ignore the issue and shift the peril to third parties for publishing source or binary modules, doesn't make it right.

**Comment by JamesH65** [comment]
Closing this issue as questions answered/issue resolved.
