### ISSUE TITLE
Full support for CM3 needs to be added to raspberrypi3 64-bit build

### ISSUE THREAD

**Issue by ghost** [raspberrypi/linux#2641]
The raspberrypi3 64-bit build does not support the CM3.  It should.  That way, the 64-bit version can easily be built for and run on the industrial/commercial version of the R Pi 3B.

A few things are needed to implement this:
1. add the proper dts source file for the CM3 under arch/arm64/boot/dts/broadcom
2. add any dtsi file(s) included by the CM3 .dts under arch/arm64/boot/dts/broadcom
3. test that the dtb will successfully build

**Comment by pelwell** [comment]
The 64-bit builds are not officially supported, but a Pull Request making the changes you suggest is very likely to be merged.

**Comment by ghost** [comment]
OK, I forked the repo, made the change, tested that I could build the dtbs, then pushed the change.  Here's the Pull Request:  https://github.com/raspberrypi/linux/pull/2644

**Comment by pelwell** [comment]
Now that #2644 is merged, is it okay to close this issue?

**Comment by ghost** [comment]
Yes, I'll close it now.  Thanks much for the merge.
