### ISSUE TITLE
Welcome tool restricts Language per Country 

### ISSUE THREAD

**Issue by kenfallon** [raspberrypi/linux#2648]
In the welcome application "Set Country" page with the text "Enter the details of your location. This is used to set language time zone, keyboard and other international settings."

Selecting a Country restricts the user to a drop-down list of languages, and provides no option to add other languages. This selection incorrectly assumes that the only languages that people use in a given region are those with official language status. It fails to consider the diversity of the populations, and the fact that people may wish to use a non default language.

As an example, the country of Ireland only gives the option of English and Irish languages, while the 2011 national census shows a total of 182 different languages in use. It continues to say "As already reported in This Is Ireland, Part 1: 514,068 residents spoke a language other than Irish or English at home in 2011." Given ROI has a population of 4,792,500 this represents 10% of the install base that may wish to select an install language other than Irish or English.
https://en.wikipedia.org/wiki/Republic_of_Ireland#cite_note-145

The same extends to the Netherlands where we are restricted to Dutch, Limburgish, Low Saxon, and West Frisian. Despite 22.61% of the residents been described as non Dutch. Even then there is a sizable population of Dutch speakers that prefer to install English operating systems for one reason or another.

Please change this so that there is always the option to add another language not in the official list.

**Comment by popcornmix** [comment]
This repo is for the linux kernel. This isn't a kernel issue.
If you are talking about behaviour of raspbian stretch then
https://github.com/RPi-Distro/repo/issues
may be a more suitable place to report this.

**Comment by kenfallon** [comment]
Oops - sorry opened [an issue](https://github.com/RPi-Distro/repo/issues/108) over there instead.
