### ISSUE TITLE
IP_VS kernel modules missing - enablement request  on  raspberrypi / linux

### ISSUE THREAD

**Issue by hvenzke** [raspberrypi/linux#265]
Me and serval  others have the need to get the Corosync/ crm / heartbeat  to work with ldirectord  on rasberrian / debian / opensuse / fedora and more ...

See my Issue Firmware kernel Modules issue filed here :
https://github.com/Hexxeh/rpi-firmware/issues/13

regards

**Comment by popcornmix** [comment]
So, is the request for
CONFIG_IP_VS
to be added?

**Comment by hvenzke** [comment]
Yes CONFIG_IP_VS and all IP_VS Subfeatgers.

it Compiles well on 3.8.4

docu :  
basics : http://clusterlabs.org/wiki/Initial_Configuration
aktive/passive cluster - http://zeldor.biz/2010/12/activepassive-cluster-with-pacemaker-corosync/
mysql master/slaves - http://clusterlabs.org/wiki/Load_Balanced_MySQL_Replicated_Cluster
ldirectord setup : http://oss.clusterlabs.org/pipermail/pacemaker/2010-April/005816.html

My LB ´s Simple Setup:
- 2 rasperrys Type B used 
- i startup the crm by heartbeat
- i have confgured heartbeat using USB serial  with 19k2 ( more may probably load the cpu more .. ) as major HA LINK
- secondly  . I use old  2 USB ethernet 10/100 sticks +  crossover ethernet cable    as second HA link
  this link been used by CRM and HeartBeat v3
  Both Links may help to get rid for an Unknown cluster state.
- crm manage ldirectord and Virtual IP, cman ,  pacemaker , fencing and more.
- This setup require  at least 1200mA Power to power both devices and the PI ( need more ? dev  add Powerd Hub )
- i have an old used apc powerswitch to for stoneit to shoot( poweroff/reset ) the not working PI if required via snmp

<code>
 crm configure primitive MAILIP ocf:heartbeat:IPaddr2 params ip="192.168.1.31" nic="eth0" \
 op monitor interval="10s" meta is-managed="true"
 crm configure primitive SQLIP ocf:heartbeat:IPaddr2 params ip="192.168.1.42" nic="eth0" \
 op monitor interval="10s" meta is-managed="true"
 crm configure primitive WEBIP ocf:heartbeat:IPaddr2 params ip="192.168.1.40" nic="eth0" \
  op monitor interval="10s" mea is-managed="true"
</code>

<code>
 crm configure primitive ldirectord ocf:heartbeat:ldirectord  params configfile="/etc/ha.d/ldirectord.cf" \
     op monitor interval="2m" timeout="20s" op start interval="0" timeout="90s" \
    op stop interval="0" timeout="100s" meta target-role="Started"
</code>
You may need to create an Group at least ONE IP and the ldirectord together  to get the Failover to work.

<code>
 crm configure group LVS  WEBIP ldirectord  meta target-role="Started"
</code>

The Load Balancing been then managed by the ldirectord same way as the HeartBeat v2  samples on the Internet.

> > ! This been here the Important Item requested for , this require kernel / netfilter / ip_VS module support.<<!

**Comment by hvenzke** [comment]
Thanks for enable IP_VS and ARPD at  3.8.8 kernel

 dmesg | grep IPVS
[   25.328352] IPVS: Registered protocols (TCP, UDP, SCTP, AH, ESP)
[   25.328473] IPVS: Connection hash table configured (size=4096, memory=32Kbytes)
[   25.328865] IPVS: Creating netns size=1200 id=0
[   25.328948] IPVS: ipvs loaded.
[   26.045631] IPVS: sync thread started: state = MASTER, mcast_ifn = eth1, syncid = 0, id = 0
[   45.111214] IPVS: [wlc] scheduler registered.
[  884.732541] IPVS: __ip_vs_del_service: enter
root@lb1:/usr/src/linux# lsmod | ip_vs
-su: ip_vs: Kommando nicht gefunden.
root@lb1:/usr/src/linux# lsmod |grep ip_vs
ip_vs_wlc               1017  0
ip_vs                 125841  3 ip_vs_wlc
ipv6                  275137  21 ip_vs
nf_conntrack           79412  1 ip_vs
root@lb1:/usr/src/linux# uname -a
Linux lb1 3.8.8+ #421 PREEMPT Tue Apr 23 16:57:08 BST 2013 armv6l GNU/Linux
root@lb1:/usr/src/linux#
