### ISSUE TITLE
Kernel Compile 3.6.11 branch -  issue with drivers/char/broadcom/vc_cma/vc_cma.c ->  CONFIG_BCM_VC_CMA=m

### ISSUE THREAD

**Issue by hvenzke** [raspberrypi/linux#266]
Kernel compile failed on RPI ( no cross compole ) with CONFIG_BCM_VC_CMA=m
....

 CC [M]  drivers/char/broadcom/vc_cma/vc_cma.o
drivers/char/broadcom/vc_cma/vc_cma.c:184:13: error: expected declaration specifiers or '...' before string constan              t
drivers/char/broadcom/vc_cma/vc_cma.c:184:27: error: expected declaration specifiers or '...' before 'early_vc_cma_              mem'
drivers/char/broadcom/vc_cma/vc_cma.c:156:19: error: 'early_vc_cma_mem' defined but not used [-Werror=unused-functi              on]
cc1: all warnings being treated as errors
make[4]: **\* [drivers/char/broadcom/vc_cma/vc_cma.o] Error 1
make[3]: **\* [drivers/char/broadcom/vc_cma] Error 2
make[2]: **\* [drivers/char/broadcom] Error 2
make[1]: **\* [drivers/char] Error 2
make: **\* [drivers] Error 2

.. I am Not an Coder .

**Comment by hvenzke** [comment]
Found an Mulipatch RPI Patch that contains the fix  for that :

http://www.xilka.com/sheeva/3/3.6/3.6.11/source/linux-3.6.11-RaspberryPi.patch

**Comment by popcornmix** [comment]
Can you indicate what is fixed in the patch you linked?
vc_cma.c line 184 looks the same.

**Comment by hvenzke** [comment]
well ,.. I am Not an Coder .

 I  am just googled and  for vc_cma/vc_cma.c  issue and  given link was the only patch found.

**Comment by hvenzke** [comment]
at Moment im try to compile 3.8.4 on my PI .
Will report if that still happens again.

**Comment by hvenzke** [comment]
happend again on 3.8.7 ..

Well - i maybe found the reason for this compile error. 
Solution seems into the Kconfig from the  Mulipatch RPI Patch.
That was Incomplete applied .

-> There been NO warning by make oldconfig for that  missing depends "BCM_VC_SERVICES" <- 

the reason for that seems that the whole "config BCM_VC_CMA" missed at

probably missing Commit : http://searchco.de/codesearch/view/26439440

lets see what next compile round gives..

**Comment by popcornmix** [comment]
I've uncommented the depends line on 3.8.y kernel tree. Does that fix problem?
No.
vccma cannot be built as a module as it requires early_param. Made it boolean rather than tristate.

**Comment by hvenzke** [comment]
well, let me get latest  3.8.y  from your git , patch it up to 3.8.8 and try to compile it.

every compile round takes arrround 1 day.
maybe i shuold add more Pi´s ? for this Job ;-).

**Comment by thiagovespa** [comment]
Same here. I'm using 3.10.y branch.

**Comment by hvenzke** [comment]
gone - using 3.11.6 now
