### ISSUE TITLE
'ret' not defined. Kernel build fails.

### ISSUE THREAD

**Issue by errolt** [raspberrypi/linux#2665]
Hi XECDesign,

There seems to be a line missing defining the 'ret' variable.

Thank you,
Errol

https://github.com/raspberrypi/linux/blob/f6da082a790f857d5163ac99357beae6b59f1eb5/drivers/hwmon/rpi-poe-fan.c#L402\

**Comment by XECDesign** [comment]
Thanks for spotting that
