### ISSUE TITLE
Raspberry Pi Undervoltage

### ISSUE THREAD

**Issue by captainbob79** [raspberrypi/linux#2667]
I have a Raspberry Pi 3 running Kodi. Connected to it is an external HDD filled with video files. I use Kodi as a home media library to play the files. Recently I replaced my dying external drive with a new one and since then the Pi regularly gives me the lightning bolt warning and unmounts the external drive. A few moments later the drive is automatically remounted and is good to go for another few minutes before being unmounted again. What could be causing this undervoltage issue and how could I fix it?

**Comment by popcornmix** [comment]
Your power supply doens't provide enough power for the hard drive.
Technically it drops below 4.6V (causing the under-voltage warning) when the drive is taking significant current.
Does the drive have a separate power supply or just the USB connection?
What power supply are you using for the Pi3?

**Comment by captainbob79** [comment]
@popcornmix The external drive is not separately powered, just usb. I'm using the CanaKit 2.5A USB Power Supply that came with the Pi bundle I bought.

**Comment by popcornmix** [comment]
It's hard to know what the peak current the drive required is (but we know it's more than your current supply). Connecting the drive through a powered USB hub is one way of avoiding the issue.

**Comment by JamesH65** [comment]
Might be worth a look https://www.raspberrypi.org/forums/viewtopic.php?f=28&t=183495

**Comment by JamesH65** [comment]
This isn't really a kernel issue, you just need a less power hungry device, or power it separately.
