### ISSUE TITLE
qmi_wwan.c backport to 4.14.x to enable support for SIM7600 modems

### ISSUE THREAD

**Issue by mypiandrew** [raspberrypi/linux#2672]
Hi

Would it be possible to get this single line patch:

https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=102cd909635612c0be784a519651954a7924c786

Which is in the 4.18 branch (Line 1253)

https://github.com/raspberrypi/linux/blob/rpi-4.18.y/drivers/net/usb/qmi_wwan.c

Applied to the 4.14 tree?

**Comment by pelwell** [comment]
Done.

**Comment by mypiandrew** [comment]
Thanks Phil!
