### ISSUE TITLE
CM3 Crash after some fails 

### ISSUE THREAD

**Issue by JTrotta** [raspberrypi/linux#2675]
In the last two moths I'm facing a weird problem with a CM3. After the error: 
`smsc95xx 1-1.5.1:1.0 eth1: Failed to read reg index 0x00000114: -71`
`smsc95xx 1-1.5.1:1.0 eth1: Error reading MII_ACCESS`
`smsc95xx 1-1.5.1:1.0 eth1: Timed out writing MII reg 00`
the system freeze and crash. Kernel is:
 `Linux raspberrypi 4.14.67-v7+ #1139 SMP Wed Aug 29 15:17:05 BST 2018 armv7l GNU/`
Any Hints?

**Comment by r1bnc** [comment]
In my case (RPi2B), it was a hardware failure. Try different version of kernels so you can isolate the problem.
Not much familiar with the CM3 but does the USB port work?

**Comment by JTrotta** [comment]
@gr01d , Yes I suppose it's a hardware failure too. Very difficult to debug.
