### ISSUE TITLE
sc16is752   infinite interrupt loop in kernel module

### ISSUE THREAD

**Issue by idsoftgit** [raspberrypi/linux#2676]
I made a custom board with sc16is752. Everything work fine until kernel stall at 100% CPU usage and IRQ line hangs at low state and meander on the CS line. Looks like it run in circle in the sc16is7xx_port_irq handler. It is only possible if SC16IS7XX_IIR_NO_INT_BIT in IIR is active.
Any activity on RX line make it working back again.
This situation repeats at least 2-10 hr.

**Comment by idsoftgit** [comment]
Looks like I found a solution. Errors from LSR reads only if something placed in receiver FIFO, but what happens if there is no data in FIFO and any error occurred? It's just return true from sc16is7xx_port_irq and keep poling further in the endless loop. It seems like a wrong behavior. I added "return true" if rxlen is zero and now it works without hanging, But I think the right way is call sc16is7xx_handle_rx(port, rxlen, iir) without any check of buffer length at all.
Is there somebody use this chip?

**Comment by pelwell** [comment]
There are a number of users of this device. Please post your patch so I can better understand what you mean.

**Comment by idsoftgit** [comment]
[patch.txt](https://github.com/raspberrypi/linux/files/2418694/patch.txt)
Ok, after a while of test I guess it works. Ofcourse it should be tested strongly enough.

**Comment by idsoftgit** [comment]
It still hangs. But now it takes about 5 days for.

**Comment by idsoftgit** [comment]
[patch.txt](https://github.com/raspberrypi/linux/files/2552786/patch.txt)
So, the reason of hangs was when interrupt occurs with zero buffer length and it leads to the infinite loop. Please add patch to mainline.

**Comment by pelwell** [comment]
Thanks - that makes much more sense. It's now in rpi-4.14.y and rpi-4.19.y.

**Comment by JamesH65** [comment]
Closing this issue as questions answered/issue resolved.
