### ISSUE TITLE
4.9.y branch maintenance?

### ISSUE THREAD

**Issue by r1bnc** [raspberrypi/linux#2683]
Is the branch rpi-4.9.y-stable being maintained? I am interested in implementing dappersec (grsec) to harden the Pi's kernel as in this post: https://www.raspberrypi.org/forums/viewtopic.php?t=215552

The branch 4.9 linux kernel should be maintained until the End-of-Life.

**Comment by JamesH65** [comment]
I believe that from our point of view, 4.9 is end of life. 4.14 is our currently maintaine kernel. @pelwell Is that right?

**Comment by popcornmix** [comment]
That is correct.
