### ISSUE TITLE
Removal of NWFPE in its entirety, and VFP emulation code

### ISSUE THREAD

**Issue by licaon-kter** [raspberrypi/linux#269]
Will this http://lists.infradead.org/pipermail/linux-arm-kernel/2013-April/162121.html affect RPi ?

**Comment by popcornmix** [comment]
Not sure. We do have VFP, but I don't know if we fall back to VFP emulation for any operations.
From the linked thread Russel King mentioned he had a Pi, so may be worth checking with him.

**Comment by asb** [comment]
My understanding is that this code is irrelevant on modern ARM abis. Indeed, we don't build it in any of our kernels.

(Edit: I should wait till morning to reply to these things. I missed that vfp emulation was included as well as NWFPE).

**Comment by Ferroin** [comment]
From what I can tell, the only way this might affect the Raspberry Pi is that it might break building the kernel with a softfloat toolchain.

**Comment by Ferroin** [comment]
I've just looked into the particulars of this; it WILL break any softfloat distros, and will probably break some hardfloat programs as well (Golang inparticular comes to mind).

From what I can tell, our options are either:
1. Write our own ABI compatible, clean-room reverse engineered implementation.
2. Find some way to re-license the entire kernel under something that isn't hindered by the FSF's zealotry.
3. Something else I haven't thought of...

1 of course requires that we can find someone who has the required knowledge to write such code, but has no experience with the existing code.

This is yet another example of why I will never use the GPL unless I absolutely have to.

**Comment by popcornmix** [comment]
In reality, we don't update to this version of kernel unless it works.
The fact it affects many arm devices means we're not the only people wanting a solution.
I'm sure there will be a solution in the future (whether through alternative code, or licence negotiation).

**Comment by asb** [comment]
I think this issue really just needs a lawyer to look at the indemnification options and advise John appropriately. Every commonly used license (MIT, Apache etc) have a clause about no warranty being implied. If they don't have the effect that John wants, an analysis of this would make an interesting read. I suspect the major sticking point on SoftFloat is "USE OF THIS SOFTWARE IS RESTRICTED TO PERSONS AND ORGANIZATIONS WHO..." (http://www.jhauser.us/arithmetic/SoftFloat-2b/README.txt). As a non-lawyer, it's not clear to me how John Hauser's intent isn't satisfied by the text in something like the MIT license (3rd paragraph) http://en.wikipedia.org/wiki/MIT_License#License_terms

**Comment by nwp90** [comment]
It's certainly an interesting thread, and there is much to be learnt from it, in many ways.

However, as the last message: http://lists.infradead.org/pipermail/linux-arm-kernel/2013-April/163904.html makes clear, nothing is going to happen.

**Comment by asb** [comment]
Indeed, the issue has been resolved happily upstream (QEMU I believe were also affected, and reverted to a previous version of NWFPE). Closing.
