### ISSUE TITLE
[Question] Kernel timer frequency for single application without Xorg running

### ISSUE THREAD

**Issue by vanfanel** [raspberrypi/linux#2701]
HI there,

I have an usercase for several Raspberry PI 3B+ where they will be running RetroArch on KMS/DRM+GLES2 and ALSA. There's no X server running on the system, and no system loggers, cron-like services or any kind of net-related servers: just the bare minimum to get RetroArch running on the aforementioned lowlevel APIs.
VC4 graphics stack is used.

However, I'd like to know what's the best Timer Frequency for the kernel I am building for this enviroment: the current default, 1000Hz, seems a bit of overkilling for just an user task and the underlying ALSA and KMS/DRM-related processes, desn't it? Also, reading this from the HZ_300 option, makes me wonder if it's not better suited for ~60Hz framerates than 1000Hz is:
"...exactly dividing by both PAL and NTSC frame rates for video and multimedia work".

What do you think? Isn't 300Hz a better option for X-less enviroments that will be running ~60Hz framerates and no servers on the background?

**Comment by popcornmix** [comment]
I think this is a question for the forum.
Personally I'd say changing the timer HZ rate will have zero difference, but this isn't the right place for that discussion.

Feel free to change options and rebuild kernel:
https://www.raspberrypi.org/documentation/linux/kernel/building.md

if you want to find the answers.
