### ISSUE TITLE
Unable to download the Full source/tree

### ISSUE THREAD

**Issue by CrazyArjun** [raspberrypi/linux#2707]
Hi there, I am pentest user who has recently purchased the TL-WN722N V3 Wifi card and downloaded the Beta drivers for my Raspi. As part of the drivers setup I have downloaded this Linux source and while compiling I got the errors and noticed that the git clone command has not fully downloaded the tree. It As part of the compile, I need to copy few files from the dts directory by using the below commands.

```
$ make –j4 zImage modules dtbs
$ sudo make modules_install
$ sudo cp arch /arm/boot/dts/*.dtb /boot/
$ sudo cp arch/arm/boot/dts/overlays/*.dtb* /boot/overlays/
$ sudo cp arch/arm/boot/dts/overlays/README /boot/overlays/
$ sudo cp arch/arm/boot/zImage /boot/$KERNEL.img
```
While doing it I am getting an error as shown below.
```
root@raspberrypi:/home/pi/linux# make -j4 zImage modules dtbs
  CHK     include/config/kernel.release
  CHK     include/generated/uapi/linux/version.h
  CHK     scripts/mod/devicetable-offsets.h
  CHK     include/generated/utsrelease.h
  CHK     include/generated/timeconst.h
  CHK     include/generated/bounds.h
/bin/sh: 1: bc: not found
Kbuild:43: recipe for target 'include/generated/timeconst.h' failed
make[1]: *** [include/generated/timeconst.h] Error 127
make[1]: *** Waiting for unfinished jobs....
Makefile:1084: recipe for target 'prepare0' failed
make: *** [prepare0] Error 2
root@raspberrypi:/home/pi/linux# make modules_install
  DEPMOD  4.14.73-v7+
root@raspberrypi:/home/pi/linux# cp arch/arm/boot/dts/*.dtb /boot/
cp: cannot stat 'arch/arm/boot/dts/*.dtb': No such file or directory
root@raspberrypi:/home/pi/linux# cp arch/arm/boot/dts/overlays/*.dtb /boot/overlays/
cp: cannot stat 'arch/arm/boot/dts/overlays/*.dtb': No such file or directory
root@raspberrypi:/home/pi/linux# 

```

My Raspberry Pi setup
```
root@raspberrypi:/home/pi/linux# uname -a
Linux raspberrypi 4.14.70-v7+ #1144 SMP Tue Sep 18 17:34:46 BST 2018 armv7l GNU/Linux
root@raspberrypi:/home/pi/linux# 
```
While troubleshooting the above error I have noticed that required files are not downloaded from GIT due to the limitation of 1000 files per folder. Hence *.dtb files are not downloaded from the GIT.  When I manually browse through the files and got the error as "Sorry, we had to truncate this directory to 1,000 files. 648 entries were omitted from the list. " in the path linux/arch/arm/boot/dts/ 

I think there might be chance to happen this type of error in other folders as well. Could you please check a way to upload the full tree so that we can download the same.

**Comment by pelwell** [comment]
```
/bin/sh: 1: bc: not found
```
Run `sudo apt-get install bc`, which is one of the first instructions in https://www.raspberrypi.org/documentation/linux/kernel/building.md.

**Comment by CrazyArjun** [comment]
Hi Pelwell,

Thank you for letting me know the mistake. :-) I see that after installing that bc command, I am able to execute the command " make -j4 zImage modules dtbs ".

Now its been more than 5 minutes that it is still processing the command. I will post back if I get any errors. Thank you for your help.

**Comment by pelwell** [comment]
Closing, as I think this is likely to have resolved your problem. Let us know if that isn't the case.

**Comment by CrazyArjun** [comment]
HI Pelwell,

Thanks for the response. My issue partially resolved and the processing took close to 4 hours in my pi. On the next day when I try to execute the next set of commands which was given the manual for beta drivers I couldn't progress further as it says zImage folder is missing and unable to copy the files. Hence I tried redoing the entire project for second time and got stuck at the same place. Hence frustrated and returned the device and purchased a new one where my Kali Pi is detecting it. I will do the testing with the new device. If I need help, hope you don't mind me asking for help one more time. :-)

Thank you for your help. Have a wonderful weekend.
