### ISSUE TITLE
rpi 3.8.6 compile report

### ISSUE THREAD

**Issue by hvenzke** [raspberrypi/linux#271]
drivers/mmc/host/sdhci-bcm2708.c: In function 'sdhci_bcm2708_platdma_reset':
drivers/mmc/host/sdhci-bcm2708.c:650:16: warning: unused variable 'flags' [-Wunused-variable]
drivers/mmc/host/sdhci-bcm2708.c: In function 'sdhci_bcm2708_dma_complete_irq':
drivers/mmc/host/sdhci-bcm2708.c:747:16: warning: unused variable 'flags' [-Wunused-variable]

**Comment by popcornmix** [comment]
Fixed locally, will be in next push

**Comment by hvenzke** [comment]
msg gone , close
