### ISSUE TITLE
Jumbo Packets on Ethernet Gadget

### ISSUE THREAD

**Issue by ejolson2005** [raspberrypi/linux#2725]
Between the 4.9.x series and the 4.14.x series there was a regression that prevented the USB Ethernet Gadget from using jumbo packets.  Apparently the initial regression occurred in 4.12.x.  More information at

https://www.raspberrypi.org/forums/viewtopic.php?f=29&t=224931#p1382020

**Comment by pelwell** [comment]
You can increase the chance of this getting some attention by posting (or linking to) some concise instructions on setting up the Zero and host computer, along with what test to run, and what the desired and actual outcomes are. Assume the audience is a competent programmer with no USB gadget experience.

**Comment by 6by9** [comment]
Isn't this fixed by 8024dcb1164fd8266f3815aea1ebf7232365de61 ? #2556 Upstream commit date 6th May 2018, merged to rpi-4.14.y on 17 Jun 2018.

The commit was merged in the 4.18 release, so 4.18 and 4.19 shouldn't suffer from the problem.

**Comment by scramble45** [comment]
can confirm using a Pi 4 : `BCM54213` it should support up to 10KB but cannot set it.

**Comment by JamesH65** [comment]
Can you give more detail on what you are trying to do and how to test it please.

**Comment by ejolson2005** [comment]
This is now fixed in all recent kernels so I'm closing.
