### ISSUE TITLE
netlink error for cangw on Raspberry Pi 3 PiCAN2 Duo

### ISSUE THREAD

**Issue by rg4444** [raspberrypi/linux#2726]
Running cangw from `https://github.com/linux-can/can-utils` commands (cangw -F) on raspberry Pi 3 return error:
`netlink error -1 (Operation not permitted)`
Linux kernel: Linux/arm 4.14.71, mod-gw enabled
`modprobe can-gw `returns no error.
CAN board - PICAN2 DUO, CAN0 and CAN1 interfaces are up and running.

**Comment by 6by9** [comment]
I see you have asked the same question on the linux-can project - https://github.com/linux-can/can-utils/issues/111
I'd wait for an answer there before expecting us to search for a kernel issue.

**Comment by rg4444** [comment]
Yes. OK, thanx

**Comment by 6by9** [comment]
I see from the linked issue you just hadn't run as root. This issue should be closed.

**Comment by JamesH65** [comment]
Closing this issue as questions answered/issue resolved.
