### ISSUE TITLE
vchiq: Top-down description of driver

### ISSUE THREAD

**Issue by lategoodbye** [raspberrypi/linux#2730]
I wasn't sure where to raise this issue (here or in the documentation repo), but i think this fits better. There is [one point](https://github.com/raspberrypi/linux/blob/rpi-4.19.y/drivers/staging/vc04_services/interface/vchi/TODO#L48) on the TODO list for the vchiq driver before it can leave staging: documentation

This driver is too complex to get the idea behind it by looking at the code. So it would be nice if someone at RPF can provide so kind of overview / top-down description of the driver and its interfaces.

**Comment by lategoodbye** [comment]
Would be an issue in documentation better?

**Comment by ghost** [comment]
The linked document says: 

> "VCHI is just a tool to let drivers talk to the firmware."

A slight expansion on that would be:

"The Raspberry Pi runs two separate operating systems: Linux on the ARM, and a threedx RTOS called vcos running on the Videocore 4 VPU: vcos is commonly called "the firmware". Vcos is tasked with performing certain system services, for example running the display and audio outputs. The VCHI driver provides an interface to allow Linux drivers to talk to vcos. Raspberry Pi develop vcos and the VCHI interface based on demand for certain features and bug fixes, in concert with Broadcom".

The documentation issue is part of the process of getting VCHI included in the upstream Linux kernel. As such, the issue the linked document raises belongs in this repository. If you feel the need to explain the function of VCHI beyond the Linux kernel community, then you should file a separate issue in the documentation repository. A good starting point for any addition to the documentation repository might be my short explanation above.

**Comment by lategoodbye** [comment]
@andrum99 Thanks for your feedback. We need a better explanation of the software architecture (e.g. what is the function of those kernel threads: keepalive, recycle, slot handler, sync) and the userspace interfaces of VCHI ( /dev/vchiq , ioctl calls, debugfs ). So it should be focused on the kernel driver.

**Comment by JamesH65** [comment]
@andrum99 vcos isn't an OS, its an abstraction layer over the underlying ThreadX RTOS that runs on the Videocore. We actually have vcos versions for ThreadX, Linux and MS Windows OS calls, so a lot of the stuff can be recompiled for other OS architectures, as was done when Broadcom originally did the dev work. Useful for testing, and is also used in the userland repo. Nowadays, Broadcom do no firmware development/bug fixing for the Raspberry Pi firmware, it's all done by us. VCHI is the comms stack between the VC4 and the host OS.

**Comment by ghost** [comment]
Thanks @jamesh65. I will add a PR to the documentation repository with the information we have collected here about this part of the Pi architecture.

**Comment by abergmeier** [comment]
Soo what is the status of this?

**Comment by pelwell** [comment]
Overdue for closing.
