### ISSUE TITLE
RPi and mikroE Audio Codec PROTO - physical connection

### ISSUE THREAD

**Issue by aco92** [raspberrypi/linux#2748]
Hello,

I am doing integration between RPi and mikroElektronika PROTO audio codec. I found on this link: https://github.com/raspberrypi/linux/issues/1302 how to connect it via GPIOs and it's working, but I do not get it why to use those specific GPIO pins on RPi. 
I found similiar connection setup on another source as well:
https://www.fredrikolofsson.com/f0blog/?q=node/656

I understand connection for Power, Ground and I2C, but do not understand SPI connection. When I tried to connect MISO to MOSI, MOSI to MISO and SCLK to SCLK I couldnt perform some basic sound playback. When I connect as it says in articles it works. I have took a look to RPi pinout on https://pinout.xyz/ and makes no sense to me that connection from articles.

Also, could someone explain me point of this ADCL and DACL on PROTO, beacuse it says that those two pins from PROTO needs to be connected to the same GPIO on RPi (why?). I actually connected just one of them (doesnt matter which one) and it works fine. Any explanation for that?

Thank you in advance.

Best regards,
Aleksandar

**Comment by pelwell** [comment]
You aren't reporting an issue with the Raspberry Pi kernel - this is a request for help. Please start a new topic in the Raspberry Pi Forums - I suggest the "Interfacing" board.
