### ISSUE TITLE
Status of cross-compiling toolchain?

### ISSUE THREAD

**Issue by nkreeger** [raspberrypi/linux#2751]
I'm trying to roll a new graphics driver stack for Raspbian to supply a patch for half-float textures in the vc4 driver. This involves a change in the kernel module as well as a new mesa build.

I've mostly been following Eric's somewhat older build instructions here: https://github.com/anholt/mesa/wiki/Raspberry-Pi-cross-compile

However - he uses the debian gcc-arm-linux-gnueabihf* tool package instead of the toolchain that Raspberry pi has supplied here: https://github.com/raspberrypi/tools

Can I roll a kernel + modules with the debian package - or do I have to roll everything with that older toolchain supplied by raspberrypi? Do you have documents for how actual packages are rolled for Raspbian?

Thank you,

**Comment by popcornmix** [comment]
There is nothing special about the toolchain from tools repo - gcc-arm-linux-gnueabihf* tool package will work just fine.

But this repo is for reporting bugs in the kernel. For questions about building and packaging the forum is likely a better option.
