### ISSUE TITLE
USB Hard Float issue - drivers/usb/host/built-in - kernel Compile ERROR

### ISSUE THREAD

**Issue by hvenzke** [raspberrypi/linux#276]
kernel 3.8.7(kernel 3.8.y+incrmental patch )  + force hard float compile

..
LD      drivers/usb/storage/built-in.o
  CC      drivers/usb/usb-common.o
  LD      drivers/usb/built-in.o
ld: error: drivers/usb/host/built-in.o uses VFP register arguments, drivers/usb/built-in.o does not
ld: failed to merge target specific data of file drivers/usb/host/built-in.o
make[2]: **\* [drivers/usb/built-in.o] Fehler 1
make[1]: **\* [drivers/usb] Fehler 2
make: **\* [drivers] Fehler 2

^C[1]+  Exit 2                  nohup make CPPFLAGS="-Ofast -mfpu=vfp -mfloat-abi=hard -march=armv6zk -mtune=arm1176jzf-s" CFLAGS="-Ofast -mfpu=vfp -mfloat-abi=hard -march=armv6zk -mtune=arm1176jzf-s" dep zImage Modules

root@lb1:/usr/src#  echo "int main(void) { return 0; }" > test.c
root@lb1:/usr/src#  CPPFLAGS="-Ofast -mfpu=vfp -mfloat-abi=hard -march=armv6zk -mtune=arm1176jzf-s";CFLAGS="-Ofast -mfpu=vfp -mfloat-abi=hard -march=armv6zk -mtune=arm1176jzf-s"
root@lb1:/usr/src# gcc -mfloat-abi=hard test.c -o test
root@lb1:/usr/src# ./test

glibc  debian RPI been hartfload right ?
 since the simple test not failed.

Anyone assitance / helpfully Hints ?

**Comment by popcornmix** [comment]
There's no floating point in the kernel, so there's no benefit to building it with hard float abi.

**Comment by hvenzke** [comment]
Okay  got you.

I used just the recomened  Flags from http://elinux.org/RPi_Software#GPU_bootloaders  for Compile .

Been they still Correct written down ?
If not what whuold you recomend ?

**Comment by hvenzke** [comment]
here are the Documented reason for the issue  : http://wiki.debian.org/ArmHardFloatPort

The <b>combination of -mfpu=vfp and -mfloat-abi=hard/<b> is not available in FSF GCC 4.4; see TODO section below for options. ""

 gcc --version
gcc (Debian 4.6.3-14+rpi1) 4.6.3
Copyright (C) 2011 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

So , Compile with option " -mfloat-abi=hard"  using the standard delivered gcc may <b>not supported</b>.

With the comment from popcornmix , there is NO hardware based hardFP either on the bmc2708.

The only working combination  may then :  "-mfpu=vfp and -mfloat-abi=vfp" .

CLOSE issue.
