### ISSUE TITLE
Missing usbtmc module in kernel.

### ISSUE THREAD

**Issue by woocash19** [raspberrypi/linux#2765]
Is there any opportunity to add **usbtmc** module to the official raspbian kernel?

**Comment by dedekind** [comment]
+1

**Comment by popcornmix** [comment]
This has previously been requested here: https://github.com/raspberrypi/firmware/issues/929
Add your comments there.

**Comment by ajh34** [comment]
modprobe: FATAL: Module ceph not found in directory /lib/modules/4.14.98-v7+

Looks like the ceph package does not correctly install the required kernel module to support mounting ceph filesystems. Seems to be an issue on both Stretch and the previous release.
