### ISSUE TITLE
rpi kernel 3.8.y ( 3.8.4-3.8.8 ) Compile Error - CONFIG_MMC_BCM2708=[m|y]

### ISSUE THREAD

**Issue by hvenzke** [raspberrypi/linux#277]
CC [M]  drivers/mmc/host/bcm2708_mci.o
In file included from drivers/mmc/host/bcm2708_mci.c:38:0:
drivers/mmc/host/bcm2708_mci.h: In function 'bcm2708_mci_kmap_atomic':
drivers/mmc/host/bcm2708_mci.h:94:34: error: 'KM_BIO_SRC_IRQ' undeclared (first use in this function)
drivers/mmc/host/bcm2708_mci.h:94:34: note: each undeclared identifier is reported only once for each function it appears in
drivers/mmc/host/bcm2708_mci.h:94:2: error: too many arguments to function 'kmap_atomic'
include/linux/highmem.h:66:21: note: declared here
drivers/mmc/host/bcm2708_mci.h: In function 'bcm2708_mci_kunmap_atomic':
drivers/mmc/host/bcm2708_mci.h:99:38: error: macro "kunmap_atomic" passed 2 arguments, but takes just 1
drivers/mmc/host/bcm2708_mci.h:99:2: error: 'kunmap_atomic' undeclared (first use in this function)
drivers/mmc/host/bcm2708_mci.c: In function 'bcm2708_mci_get_cd':
drivers/mmc/host/bcm2708_mci.c:477:12: error: 'GP_LEV0' undeclared (first use in this function)
drivers/mmc/host/bcm2708_mci.c: At top level:
drivers/mmc/host/bcm2708_mci.c:600:22: error: expected '=', ',', ';', 'asm' or '**attribute**' before 'bcm2708_mci_probe'
drivers/mmc/host/bcm2708_mci.c:796:22: error: expected '=', ',', ';', 'asm' or '**attribute**' before 'bcm2708_mci_remove'
drivers/mmc/host/bcm2708_mci.c:864:12: error: 'bcm2708_mci_probe' undeclared here (not in a function)
drivers/mmc/host/bcm2708_mci.c:865:13: error: 'bcm2708_mci_remove' undeclared here (not in a function)
drivers/mmc/host/bcm2708_mci.c:506:20: warning: 'bcm2708_mci_sddet_irq' defined but not used [-Wunused-function]
drivers/mmc/host/bcm2708_mci.c:526:20: warning: 'bcm2708_mci_data_irq' defined but not used [-Wunused-function]
make[3]: **\* [drivers/mmc/host/bcm2708_mci.o] Fehler 1
make[2]: **\* [drivers/mmc/host] Fehler 2
make[1]: **\* [drivers/mmc] Fehler 2
make: **\* [drivers] Fehler 2

 # grep -i mmc .config | grep 2708
CONFIG_MMC_SDHCI_BCM2708=y
CONFIG_MMC_SDHCI_BCM2708_DMA=y
CONFIG_MMC_BCM2708=m
- Let me assume this cant be compiled as Module , right ?
  If so , the Kconfig must be boolean and not tristate, Correct ?
- don´t compiled either when CONFIG_MMC_BCM2708=y
- don´t compiled with 3.8.4 &  3.6.y either.

reopen https://github.com/raspberrypi/linux/issues/7
reopen https://github.com/raspberrypi/linux/issues/245 

if i am not wrong.

**Comment by hvenzke** [comment]
well .seems . https://patchwork.kernel.org/patch/517311/ removed KM_BIO_SRC_IRQ from i.e 
arch/arm/include/asm/kmap_types.  arch/arm/include/asm/kmap_types.h

https://lkml.org/lkml/2012/6/23/57 reference i found

**Comment by popcornmix** [comment]
This should be fixed (there is no bcm2708_mci now...)

**Comment by tomkcook** [comment]
IMO the problem with CONFIG_MMC_BCM2708 is a bigger one.  Might be time for a separate bug report on that one, though.

**Comment by hvenzke** [comment]
well , someone has to code the fixes..( not me , my coding skills are not fit for that) add an commit and then close  this one finaly.

**Comment by popcornmix** [comment]
Sorry, I don't understand the issue. 
CONFIG_MMC_BCM2708 does not exist in 3.8 and 3.9 kernels.
There is no drivers/mmc/host/bcm2708_mci.c.

So what is the current problem?

**Comment by hvenzke** [comment]
@popcornmix  , it exist No longer after you removed it. 

my Compile test was on 3.8.8 thus the above reported.

so we can close this  issue rigth ?

if all happy here with your Descion im happy to close it .
