### ISSUE TITLE
/usr/bin/raspi-config will freese boot if rootfs is not last partition because waiting key press in non interactive mode

### ISSUE THREAD

**Issue by doublehp** [raspberrypi/linux#2775]
Not sure exactly how /usr/bin/raspi-config is run at first boot, but I am 99% certain it is.

In short, my pi froze on "is not the last partition. Don't know how to expand" at first boot. And I have been waiting for network to come up for 1h, untill I plugged a monitor to see this dialog bog.

I use headless pis; a lot of them, and I don't have time to plug a monitor on them each time I install them. I just burn the SD card, insert the card, plug network and USB, and a few minutes later, I try network connexion.

I don't burn the cards manually; I burn them with a home made script which brings many modifications into rootfs after dd. In particular, I alter etc/hostname, crontab and network/interfaces. Since yesterday, I made my script also add a third partition at the end of the card. This way, when the filesystem crashes, I want to see which file system crashes: rootfs, or my data. 

The message I got was 
`whiptail --msgbox "$ROOT_PART is not the last partition. Don't know how to expand" 20 60 2`

which belongs to function
`do_expand_rootfs`

which is called by
```
#
# Command line options for non-interactive use
#
for i in $*
do
  case $i in
[...]
  --expand-rootfs)
    INTERACTIVE=False
    do_expand_rootfs
    printf "Please reboot\n"
    exit 0
    ;;
[...]
```

=> if it's a non interactive section, it should not call a function that is waiting life time for pressing a key.

The proposed fix is ... to add this condition before all whiptail lines:
`
[ "$INTERACTIVE" = True ] && whiptail ... || echo "Da error message" >&2`

This way, message will still be reported in syslogs (which I read).

**To reproduce**

allocate a third partition after dd, before first boot:

`echo -e "n\np\n3\n13000000\n\nw\n" | fdisk "/dev/sdb"`

**Expected behaviour**

first boot should complete without requirering keyboard interaction, whatever the issue.

* Which model of Raspberry Pi? e.g. Pi3B+, PiZeroW

Not sure, Pi2 or Pi3

* Which OS and version (`cat /etc/rpi-issue`)?

```
2018-11-13-raspbian-stretch-lite.zip

cat etc/rpi-issue 
Raspberry Pi reference 2018-11-13
Generated using pi-gen, https://github.com/RPi-Distro/pi-gen, 7e0c786c641ba15990b5662f092c106beed40c9f, stage2
```

**Comment by pelwell** [comment]
If you are modifying rootfs, isn't it easier to just prevent the auto-resize from running? A very brief search found this page: https://raspberrypi.stackexchange.com/questions/47773/disable-auto-file-system-expansion-in-new-jessie-image-2016-05-10

**Comment by doublehp** [comment]
Right, I was half wrong: the culprit is not raspi-config, but usr/lib/raspi-config/init_resize.sh 

The root issue remains the same: some init/boot script locks the whole boot of the machine because of some whiptail waiting for a keypress, and this is not acceptable on an rPi which must be presumed to not have any monitor.

Yes your link gives several solution; but still:
- init_resize.sh  should not lock the boot
- raspi-config expects keystrokes in non interactive mode

I am not talking about why those scripts want to produce messages, or about the content of those messages; I only explained how I got them: adding a third partition. My complaint is about having boot locked on headless machine due to waiting for a keypress, or, having any system script expecting keystrokes in explicitely non interactive mode.

So, for me, the solution is not to run
sed -i 's| init=/usr/lib/raspi-config/init_resize.sh||' /boot/cmdline.txt
and remove 
/etc/init.d/resize2fs_once

The solution is to replace whiptail --msgbox with anything else non locking boot. Or add a 60s timeout to whiptail if possible. Or as done after resize:
```
whiptail --infobox
sleep 60
```

**Comment by XECDesign** [comment]
The reason it is the way it is is to flag up that there's a problem and make sure that you're aware of it. If there's no error, it continues without requiring any input. It's working as intended.

**Comment by doublehp** [comment]
So, the script considers that rootfs being the 3rd partition, or, having a 3rd partition after rootfs is an issue ? (even if there is space after rootfs to allow growing it ... )

**Comment by pelwell** [comment]
The whole reason to have filesystem resizing is to allow a single image to be used on cards of different sizes. If you have another partition after the rootfs then why wouldn't you make the rootfs large enough to fill the gap? You must know how big the space is because your build system created the partition that marks the end of it.

**Comment by XECDesign** [comment]
The script is only intended to run on stock Raspbian images. If it's running on an unsupported image, that's an issue that's worth flagging up to the user.

**Comment by doublehp** [comment]
I disagree; but let's close because you are obviously not going to change your mind.

I am not arguing about partitions; I am arguing about producing a message that requires interaction. There is a very simple and smooth solution:

change /usr/lib/raspi-config/init_resize.sh

```
if main; then
  whiptail --infobox "Resized root filesystem. Rebooting in 5 seconds..." 20 60
  sleep 5
else
  sleep 5
  whiptail --msgbox "Could not expand filesystem, please try raspi-config or rc_gui.\n${FAIL_REASON}" 20 60
fi
```

into

```
if main; then
  whiptail --infobox "Resized root filesystem. Rebooting in 5 seconds..." 20 60
  sleep 5
else
  whiptail --infobox "Could not expand filesystem, please try raspi-config or rc_gui.\n${FAIL_REASON}" 20 60
  sleep 60
fi
```


If user has a monitor, he is informed; if he does not have a monitor, boot will continue.

**Comment by pelwell** [comment]
> If user has a monitor, he is informed; if he does not have a monitor, boot will continue.

Leaving him totally uninformed about the fact that he may have a tiny rootfs. Our way is better.
