### ISSUE TITLE
please remove ftp.yzu.edu.tw from apt mirror

### ISSUE THREAD

**Issue by JokerCatz** [raspberrypi/linux#2779]
apt mirror `ftp.yzu.edu.tw` is very slow and broken ... even can't success upgrade Pi from original image , you can try it , & IP at Taiwan will use it by default ... so please remove it or make it not be default mirror

**Comment by popcornmix** [comment]
This repo if for linux kernel issues. Might be better to report this here: https://github.com/RPi-Distro/repo
