### ISSUE TITLE
Why I have kernel's messages spam on all my tty's?

### ISSUE THREAD

**Issue by zervankoru** [raspberrypi/linux#2787]
Hello. I am using Arch Linux ARM with this standard kernel (latest version)
If I, for example, insert usb device, kernel messages appear in my terminal. No matter what tty1-6 I am using. This problem apeared with one of my system upgdates using pacman -Syu. I haven/t got any other arm devices to check is it ALARM problem or this kernel. Can you give your comment? Is it normal?

**Comment by initrider** [comment]
+1 It also affects me.

**Comment by zervankoru** [comment]
For ones, what do not understand, what we are talking about, here is the example.
![photo_2018-12-22_23-09-06](https://user-images.githubusercontent.com/39313092/50378258-ff271080-063e-11e9-81e3-e2e89c78651e.jpg)
![photo_2018-12-22_23-09-07](https://user-images.githubusercontent.com/39313092/50378261-02ba9780-063f-11e9-945d-9df6510db3d3.jpg)
Here I just take out and then insert my wireless keyboard's usb key.
I know, I just cn use quiet, but I dont want to hide boot process, but I want to hide them from tty console. You can also see, while in cmdline.txt console=tty1, these messages appears on tty1, tty2 and others.

**Comment by zervankoru** [comment]
And changing console to tty2 or others also doesn't change anything

**Comment by zervankoru** [comment]
I will ask them, but I thought that the reason in the kernel itself. Does it affects Raspbian?

**Comment by pelwell** [comment]
Not that I've noticed. If it did, I wouldn't have to use `dmesg -w` so often.

**Comment by zervankoru** [comment]
I've asked on Arch Linux ARM IRC, but it seems, that no one don't know why it happens. Maybe developers of Raspbian know something? I cant find, ehere I can ask them.

**Comment by pelwell** [comment]
What does `cat /proc/sys/kernel/printk` report on Arch?

**Comment by zervankoru** [comment]
7417

**Comment by pelwell** [comment]
The raspberrypi-sys-mods package includes [this file](https://github.com/RPi-Distro/raspberrypi-sys-mods/blob/master/etc.armhf/sysctl.d/98-rpi.conf), the content of which is:
```
kernel.printk = 3 4 1 3
vm.min_free_kbytes = 16384
```
Level 3 is Error level, while the 7 you see on Arch is Debug. This command should stop the console spam:
```
$ sudo echo 3 4 1 3 > /proc/sys/kernel/printk
```
On Raspbian the change is made at boot time through systemd, but Arch devs will know the best way for you.

**Comment by initrider** [comment]
It's me
