### ISSUE TITLE
lxappearance and obconf both exit with "Segmentation Fault"

### ISSUE THREAD

**Issue by COOLIRON2311** [raspberrypi/linux#2791]
To reproduce: lxappearance or obconf

Raspberry Pi 3B
Raspberry Pi reference 2017-07-05

OS and version:
dd7de2554c08e6db89806eb45d955356d0456c66, stage5

Firmware version:
version ed5baf9520a3c4ca82ba38594b898f0c0446da66 (clean) (release)

Kernel:
Linux username 4.14.79-v7+ #1159 SMP Sun Nov 4 17:50:20 GMT 2018 armv7l GNU/Linux

The issue can be **temporarily fixed** by moving `/usr/share/themes/PiX`.

**Comment by COOLIRON2311** [comment]
Will be fixed by the developer of “raspberrypi-ui-mods”.

**Comment by rocrail** [comment]
Same issue with PiOS 11, Bullseye, ARMHF.
With ARM64 its OK.
