### ISSUE TITLE
How to download the driver to raspberry pi

### ISSUE THREAD

**Issue by janzhen96** [raspberrypi/linux#2807]
Hi everyone. I'm very new to Linux and raspberry pi.

I have an inquiry regarding installing the driver to my raspberry pi. The link below is the driver that I am interested in using. I am interested in using usbtmc driver to connect it to my instrument. 

https://github.com/raspberrypi/linux/tree/rpi-4.14.y/drivers/usb/class  

So, how do i download this and install it to my raspberry pi?  I look through a lof of website but I'm still lost. 

Thanks in advance.
Jan Zhen

**Comment by pelwell** [comment]
Done via https://github.com/raspberrypi/firmware/issues/929 - see https://github.com/raspberrypi/linux/commit/b3a4c69c56f4db99b091305a33aa7c9b090aaad1. Now you just have to wait for the next firmware release, which should be in the next few days, and run `sudo rpi-update`.

**Comment by janzhen96** [comment]
Thanks for adding the usbtmc driver. Do I need to do any download before or after sudo rpi-update??

Also, after my firmware update,  will the raspberry pi will automatically use usbtmc driver to connect my instrument to raspberry pi?

**Comment by pelwell** [comment]
rpi-update should be sufficient - it will replace your firmware and kernel (and modules) with the most recent version.

I have no experience with the USB_TMC module or with devices that require it, but it appears to be a class driver so it ought to be loaded automatically when an appropriate device is plugged in.

**Comment by janzhen96** [comment]
Thanks a lot.  I will give it a go after the firmware update release. 

Can the firmware update be release within this week??

**Comment by popcornmix** [comment]
Available in latest rpi-update kernel.

**Comment by JamesH65** [comment]
Closing this issue as questions answered/issue resolved.
Please update to the latest kernel which may contain a fix for this issue.
