### ISSUE TITLE
Corosync / Cman with  IP_VS  : Missing  dlm module : CONFIG_DLM=m

### ISSUE THREAD

**Issue by hvenzke** [raspberrypi/linux#281]
... this going Crasy..  ocfs2_dlm enabled without the base linux dlm

This shuold be enabled per default allways  : <b>CONFIG_DLM=m</b>

root@lb1:~# service cman start

<pre>
Starting cluster:
   Checking Network Manager... [  OK  ]
   Global setup... [  OK  ]
   Loading kernel modules...<b> FATAL: Module dlm not found.</b>
[FAILED]

root@lb1:~# find /lib/modules | grep -i dlm
/lib/modules/3.8.8+/kernel/fs/ocfs2/dlm
/lib/modules/3.8.8+/kernel/fs/ocfs2/dlm/ocfs2_dlm.ko
/lib/modules/3.8.8+/kernel/fs/ocfs2/dlmfs
/lib/modules/3.8.8+/kernel/fs/ocfs2/dlmfs/ocfs2_dlmfs.ko
/lib/modules/3.6.11+/kernel/fs/ocfs2/dlm
/lib/modules/3.6.11+/kernel/fs/ocfs2/dlm/ocfs2_dlm.ko
/lib/modules/3.6.11+/kernel/fs/ocfs2/dlmfs
/lib/modules/3.6.11+/kernel/fs/ocfs2/dlmfs/ocfs2_dlmfs.ko

root@lb2:~# service cman start
Starting cluster:
   Checking Network Manager... [  OK  ]
   Global setup... [  OK  ]
   Loading kernel modules... [  OK  ]
   Mounting configfs... [  OK  ]
   Starting cman... [  OK  ]
   Waiting for quorum... [  OK  ]
   Starting fenced... [  OK  ]
   Starting dlm_controld... [  OK  ]
   Starting gfs_controld... [  OK  ]
   Unfencing self... [  OK  ]
   Joining fence domain... [  OK  ]

root@lb2:~# lsmod
Module                  Size  Used by

<b>
dlm                   138857  7
sctp                  188067  3 dlm
</b>
ip_vs_wrr               2260  1
ip_vs_wlc               1433  1
ip_vs_sh                2589  0
ip_vs_sed               1483  0
ip_vs_rr                1634  0
ip_vs_nq                1492  0
ip_vs_lc                1436  0
ip_vs_lblcr             6889  0
ip_vs_lblc              4909  0
ip_vs_dh                2295  0
ip_vs                 158484  23 ip_vs_dh,ip_vs_lc,ip_vs_nq,ip_vs_rr,ip_vs_sh,ip_vs_sed,ip_vs_wlc,ip_vs_wrr,ip_vs_lblcr,ip_vs_lblc
nf_conntrack           83599  1 ip_vs

root@lb2:~#  find /lib/modules | grep -i dlm
/lib/modules/3.8.4+/kernel/fs/ocfs2/dlm
/lib/modules/3.8.4+/kernel/fs/ocfs2/dlm/ocfs2_dlm.ko
/lib/modules/3.8.4+/kernel/fs/ocfs2/dlmfs
/lib/modules/3.8.4+/kernel/fs/ocfs2/dlmfs/ocfs2_dlmfs.ko
/lib/modules/3.8.7-4-raspberrypi/kernel/fs/dlm
/lib/modules/3.8.7-4-raspberrypi/kernel/fs/dlm/dlm.ko
/lib/modules/3.8.7-4-raspberrypi/kernel/fs/ocfs2/dlm
/lib/modules/3.8.7-4-raspberrypi/kernel/fs/ocfs2/dlm/ocfs2_dlm.ko
/lib/modules/3.8.7-4-raspberrypi/kernel/fs/ocfs2/dlmfs
/lib/modules/3.8.7-4-raspberrypi/kernel/fs/ocfs2/dlmfs/ocfs2_dlmfs.ko
/lib/modules/3.6.11+/kernel/fs/ocfs2/dlm
/lib/modules/3.6.11+/kernel/fs/ocfs2/dlm/ocfs2_dlm.ko
/lib/modules/3.6.11+/kernel/fs/ocfs2/dlmfs
/lib/modules/3.6.11+/kernel/fs/ocfs2/dlmfs/ocfs2_dlmfs.ko
root@lb2:~#

</pre>

**Comment by hvenzke** [comment]
patch for that :

<pre>
--- config-3.8.y        2013-05-09 15:00:09.305888785 +0200
+++ config-3.8.12       2013-05-09 15:01:17.042195938 +0200
@@ -3126,7 +3126,7 @@
 # CONFIG_NLS_MAC_ROMANIAN is not set
 # CONFIG_NLS_MAC_TURKISH is not set
 CONFIG_NLS_UTF8=m
-# CONFIG_DLM is not set
+CONFIG_DLM=m
 #
 # Kernel hacking
</pre>

**Comment by hvenzke** [comment]
@popcornmix   and others Please add the kernelmodule dlm  the rasberian  FIRMWARE !!

**Comment by popcornmix** [comment]
It's in 3.10.y firmware:

```
$ zcat /proc/config.gz |grep DLM
CONFIG_DLM=m
```

**Comment by hvenzke** [comment]
sorry - more clear  : 
 it´s not in rasberian´s Firmware.
 as up now i still  have to use the 3.10.y firmware or newer instead the default rasberian installed. 
my complains with modules was not going in that was i assumed past 6 month.

**Comment by popcornmix** [comment]
It should be in latest "apt-get upgrade" firmware.
It will be in next sdcard image.

**Comment by hvenzke** [comment]
@popcornmix  
Nice to hear  that .

it was not in at default 3.10.24 rasberian from apt-get distupgrade done ~ 12.12.2013

can you kindly check that the IPVS modules as well that they are permanently going into rasberian´s Firmware.

Why i realy want to have this :
As my Corosync/ldirectord/heartbeat3  Loadbalancer aka Linux Cluster run rasberian  ;
any updates must come from apt without manualy changes. 
Manualy Udates  on corosync etc pp are an horrible job.

Heartbeat-3  Infrastruckture  espacaily the cman  require that dlm & IPVS modules for startup .

**Comment by popcornmix** [comment]
The default kernel has
CONFIG_IP_VS=m
I believe latest apt-get kernel is "Thu Dec 19".

**Comment by hvenzke** [comment]
Thanks

this are required for Linux HA  Clusters  ( + that depends on that ):

<pre>
zcat /proc/config.gz | grep -i ip_vs
CONFIG_IP_VS=m
# CONFIG_IP_VS_IPV6 is not set
# CONFIG_IP_VS_DEBUG is not set
CONFIG_IP_VS_TAB_BITS=12
CONFIG_IP_VS_PROTO_TCP=y
CONFIG_IP_VS_PROTO_UDP=y
CONFIG_IP_VS_PROTO_AH_ESP=y
CONFIG_IP_VS_PROTO_ESP=y
CONFIG_IP_VS_PROTO_AH=y
CONFIG_IP_VS_PROTO_SCTP=y
CONFIG_IP_VS_RR=m
CONFIG_IP_VS_WRR=m
CONFIG_IP_VS_LC=m
CONFIG_IP_VS_WLC=m
CONFIG_IP_VS_LBLC=m
CONFIG_IP_VS_LBLCR=m
CONFIG_IP_VS_DH=m
CONFIG_IP_VS_SH=m
CONFIG_IP_VS_SED=m
CONFIG_IP_VS_NQ=m
CONFIG_IP_VS_SH_TAB_BITS=8
CONFIG_IP_VS_FTP=m
CONFIG_IP_VS_NFCT=y
CONFIG_IP_VS_PE_SIP=m
</pre>

**Comment by popcornmix** [comment]
Latest firmware has:

```
pi@raspberrypi ~ $ zcat /proc/config.gz | grep -i ip_vs
CONFIG_IP_VS=m
# CONFIG_IP_VS_IPV6 is not set
# CONFIG_IP_VS_DEBUG is not set
CONFIG_IP_VS_TAB_BITS=12
CONFIG_IP_VS_PROTO_TCP=y
CONFIG_IP_VS_PROTO_UDP=y
CONFIG_IP_VS_PROTO_AH_ESP=y
CONFIG_IP_VS_PROTO_ESP=y
CONFIG_IP_VS_PROTO_AH=y
CONFIG_IP_VS_PROTO_SCTP=y
CONFIG_IP_VS_RR=m
CONFIG_IP_VS_WRR=m
CONFIG_IP_VS_LC=m
CONFIG_IP_VS_WLC=m
CONFIG_IP_VS_LBLC=m
CONFIG_IP_VS_LBLCR=m
CONFIG_IP_VS_DH=m
CONFIG_IP_VS_SH=m
CONFIG_IP_VS_SED=m
CONFIG_IP_VS_NQ=m
CONFIG_IP_VS_SH_TAB_BITS=8
CONFIG_IP_VS_FTP=m
CONFIG_IP_VS_NFCT=y
CONFIG_IP_VS_PE_SIP=m
```
