### ISSUE TITLE
add CONFIG_CGROUP_NET_PRIO=y

### ISSUE THREAD

**Issue by sanpoChew** [raspberrypi/linux#2822]
**Describe the bug**
There is an issue with docker and systemd 420 that is resolved by enabling this flag:

https://github.com/docker/for-linux/issues/545

**Comment by JamesH65** [comment]
Do you have any figures for impact on kernel size, performance and run time memory requirements? Given a limited resources device like the Pi we like to ensure that kernel changes for smaller use cases do not have a detrimental impact?

**Comment by sanpoChew** [comment]
it's looking like this is going to be fixed by this MR to containerd: https://github.com/containerd/cgroups/pull/77

so I'll close this
