### ISSUE TITLE
RetroPie v4.4 Cannot Control USB Sound Volume After Update/Upgrade

### ISSUE THREAD

**Issue by tinkerBOY-git** [raspberrypi/linux#2833]
I'm using a [Game Boy Zero Controller with builtin C-Media USB audio](https://www.tinkerboy.xyz/product/tinkerboy-controller-v3-0-game-boy-zero-aio-pcb-controller/) on a Raspberry Pi Zero, 3 B, 3 B+, and 3 A+. Sound Settings under emulationstation menu works perfect with version 4.3 and stock 4.4 and I can control the sound volume level just fine. But after updating/upgrading RetroPie v4.4 I can no longer control the volume level. I can however move the slider under Sound Settings but the actual volume on the speaker is always the same at its loudest no matter what I do.

Here's how I updated the stock RetroPie v4.4:
```
sudo apt-get update
sudo apt-get upgrade
sudo apt-get dist-upgrade
```
I also tried updating RetroPie via the RetroPie-Setup but still the same issue.

**Comment by pelwell** [comment]
This is the repo for the Raspberry Pi Linux kernel branches. If the RetroPie devs can narrow it down to being a kernel problem then they (or anyone) can open an issue here - but it will have to refer to kernel versions, not RetroPie versions.

Personally, I think this is much more likely to be a BlueZ (or similar) problem.
