### ISSUE TITLE
E-MU 0404 USB dont change sampling rate automatic

### ISSUE THREAD

**Issue by taravasya** [raspberrypi/linux#2843]
**Describe the bug**
If in alsa dissabled resampling - DAC`s:

E-MU [0404, 0202, Tracker Pre] USB 

don`t change sampling rate. Then I start play song with different(from 44.1kHz), sampling rate - MPD (or ALSA?) 'forgets' to switch sampling rate frequency and I hear buzzing sound instead of music. If I run alsamixer and manually switch there sampling rate - it plays OK until I select song with again different sampling rate.

**To reproduce**
In alsa dissable resampling.
Use E-MU [0404, 0202, Tracker Pre] USB (with any firmware)
Play any tracks (At first 44.1kHz and then 48kHz)

**Expected behaviour**
Any tracks with 44.1kHz to 192kHz range, play without buzzing sound.

**Actual behaviour**
I hear buzzing sound instead of music.

**System**

* Which model of Raspberry Pi? e.g. Pi3B+, PiZeroW > Pi3B+ (but this will be on any model)
* Which OS and version (`cat /etc/rpi-issue`)? 
* Which firmware version (`vcgencmd version`)?
* Which kernel version (`uname -a`)? > 4.14.92 (and any others)

~~~~

**Additional context**
~~~~

For fixing this bug me (and several other people) use this patch:
https://github.com/taravasya/taravasya_snips/commit/a99bc93365aafbdc8a735fe24a9f4107f857144e

for this file:
https://github.com/raspberrypi/linux/blob/rpi-4.14.y/sound/usb/quirks.c

**Comment by pelwell** [comment]
Your patch looks reasonable, but it is to an unmodified file from the upstream kernel. You should submit it to the maintainers for the sound subsystem.

**Comment by taravasya** [comment]
I`m afraid I take your patience..
Unfortunately, I do not understand =( 

> upstream kernel

Is this?
https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/tree/?h=v4.14.97

> maintainers for the sound subsystem

This is totaly unclear. Where do I find them? ))

**Comment by pelwell** [comment]
"Upstream" is the pure, unmodified Linux kernel. Your link is to the upstream version of 4.14.97, but they will expect patches to be submitted to the current version (although it looks like a patch for 4.14.97 will apply to 4.20 and 5.0 without difficulty.

The patch submission process is described here: https://www.kernel.org/doc/html/v4.20/process/submitting-patches.html

**Comment by JamesH65** [comment]
Closing this issue as questions answered/issue resolved.
