### ISSUE TITLE
help with omx video_render only showing first frame when using OMX_DISPLAY_ROT90

### ISSUE THREAD

**Issue by zoff99** [raspberrypi/linux#2862]
here is the testcase we use:

https://gist.github.com/zoff99/ff0dad829b912f12308db2bbf3d8a5d1

if we change OMX_DISPLAY_ROT90 to OMX_DISPLAY_ROT0
we get a nice animation of frames. otherwise only the first frame is displayed.

what mistake did we make? any help welcome

**Comment by popcornmix** [comment]
This isn't a linux kernel issue. Try: https://github.com/raspberrypi/firmware/issues
