### ISSUE TITLE
Infrared touch bug

### ISSUE THREAD

**Issue by Knisy** [raspberrypi/linux#2870]
When I use the infrared touch screen, the click will be selected, it will remember the location of the last click and the location of the current click to do the checkbox selection, but not in other operating systems, such as Ubuntu, windows
![20190226_125540](https://user-images.githubusercontent.com/5736483/53388759-5ba00680-39c7-11e9-9b6f-e490f90ff6b0.gif)

**Comment by Knisy** [comment]
How to solve this problem

**Comment by pelwell** [comment]
So what you are saying is that an infrared touchscreen works as you want it to in Raspbian but not on other platforms? That isn't a bug, and definitely not a Linux on Raspberry Pi bug. Please open a topic at the Raspberry Pi Forums.
