### ISSUE TITLE
Please add Movian package

### ISSUE THREAD

**Issue by csgabe** [raspberrypi/linux#2877]
Please add Movian application package:
https://github.com/andoma/movian

**Comment by pelwell** [comment]
Movian is an application, which by definition is not part of the Linux kernel, so your request does not belong here. We are also unlikely to add it to the default Raspbian images, when Movian offers standalone SD card images.

**Comment by XECDesign** [comment]
If you would like it added to the repo, you can open an issue here - https://github.com/RPi-Distro/repo/issues/

It seems to have debian packaging already, so as long as it builds properly for the pi, passes lintian, adequate and piuparts, it could be added.

**Comment by csgabe** [comment]
@pelwell 
Sorry for posting in wrong place.
@XECDesign 
OK, I'll open an issue there.

**Comment by czz** [comment]
here is a deb package http://mp.czz78.com/rpi.html

**Comment by XECDesign** [comment]
Looks good at a glance. Is there the .dsc and associated files to go along with it somewhere?

**Comment by czz** [comment]
i had to modify some part of https://github.com/andoma/movian to compile it. most are fixes for gcc >= 8.  I might push up code on git, but it will be only for Raspberry so it will be easier to compile. I'll ask Andoma what he thinks about it before uploading code. I know he wants to port everything on snap, actually he already did for x64.
