### ISSUE TITLE
lirc_rpi missing with latest kernel update

### ISSUE THREAD

**Issue by steros76** [raspberrypi/linux#2878]
After upgrading raspbian, lirc is not working anymore because no "lirc*" modules are available for the new kernel.

**Comment by pelwell** [comment]
LIRC support has been removed. Use the gpio-ir overlay/modules instead.

**Comment by steros76** [comment]
Perfect.
Thank you.

**Comment by sxyandapp** [comment]
为什么？为什么会这样？啊啊啊啊啊啊啊啊啊啊啊
