### ISSUE TITLE
a oops problem when access kernel code address

### ISSUE THREAD

**Issue by chenkunxiao** [raspberrypi/linux#2887]
hello, today I met a problem. I wrote a module to access the address between kernel code. It will cause oops problems.
my test code：
#include <linux/kernel.h>
#include <linux/module.h>
MODULE_LICENSE("GPL");
extern unsigned long kallsyms_lookup_name(const char *name);

static int __init init_mm_test_init(void)
{
        struct mm_struct *init_mm = NULL;
        long code_len = 0;
        uint8_t *my_page = NULL;
        int dim_bytes = 0;
        unsigned long address = 0;

        my_page = (uint8_t *)__get_free_page(GFP_TEMPORARY);
        if (NULL == my_page) {
                return -1;
        }

        init_mm = (struct mm_struct *)(uintptr_t)kallsyms_lookup_name("init_mm");
        if (NULL == init_mm) {
                return -1;
        }

        code_len = init_mm->end_code - init_mm->start_code;
        address = init_mm->start_code;
        while (code_len > 0) {
                dim_bytes = (code_len > PAGE_SIZE) ? PAGE_SIZE : code_len;
                memcpy((void *)my_page, (void *)address, dim_bytes);
                address += dim_bytes;
                code_len -= dim_bytes;
        }
        printk("code len: %ld\n", code_len);
        return 0;
}

static __exit void init_mm_test_exit(void)
{
        printk("exit\n");
}

module_init(init_mm_test_init);
module_exit(init_mm_test_exit);

**Comment by pelwell** [comment]
Your crash is in an arm64 kernel, which we don't support.

You are using a Hisilicon board, which we don't support.
