### ISSUE TITLE
resize2fs segfaults on expanding ext4

### ISSUE THREAD

**Issue by funkyHat** [raspberrypi/linux#289]
When trying to run resize2fs on an ext4 formatted LVM lv, resize2fs crashes with no output.

I ran strace, output below:

```
execve("/sbin/resize2fs", ["resize2fs", "-p", "/dev/mapper/I1-i1"], [/* 14 vars */]) = 0
brk(0)                                  = 0x2d8000
uname({sys="Linux", node="keef", ...})  = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
mmap2(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0xb6f18000
access("/etc/ld.so.preload", R_OK)      = 0
open("/etc/ld.so.preload", O_RDONLY)    = 3
fstat64(3, {st_mode=S_IFREG|0644, st_size=44, ...}) = 0
mmap2(NULL, 44, PROT_READ|PROT_WRITE, MAP_PRIVATE, 3, 0) = 0xb6f17000
close(3)                                = 0
open("/usr/lib/arm-linux-gnueabihf/libcofi_rpi.so", O_RDONLY) = 3
read(3, "\177ELF\1\1\1\0\0\0\0\0\0\0\0\0\3\0(\0\1\0\0\0\260\4\0\0004\0\0\0"..., 512) = 512
lseek(3, 5716, SEEK_SET)                = 5716
read(3, "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 920) = 920
lseek(3, 5468, SEEK_SET)                = 5468
read(3, "A0\0\0\0aeabi\0\1&\0\0\0\0056\0\6\6\10\1\t\1\n\2\22\4\24\1\25"..., 49) = 49
fstat64(3, {st_mode=S_IFREG|0644, st_size=6636, ...}) = 0
mmap2(NULL, 38240, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0xb6eeb000
mprotect(0xb6eed000, 28672, PROT_NONE)  = 0
mmap2(0xb6ef4000, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1) = 0xb6ef4000
close(3)                                = 0
munmap(0xb6f17000, 44)                  = 0
open("/etc/ld.so.cache", O_RDONLY)      = 3
fstat64(3, {st_mode=S_IFREG|0644, st_size=41644, ...}) = 0
mmap2(NULL, 41644, PROT_READ, MAP_PRIVATE, 3, 0) = 0xb6ee0000
close(3)                                = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
open("/lib/arm-linux-gnueabihf/libc.so.6", O_RDONLY) = 3
read(3, "\177ELF\1\1\1\0\0\0\0\0\0\0\0\0\3\0(\0\1\0\0\0\214y\1\0004\0\0\0"..., 512) = 512
lseek(3, 1194784, SEEK_SET)             = 1194784
read(3, "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 1360) = 1360
lseek(3, 1194348, SEEK_SET)             = 1194348
read(3, "A.\0\0\0aeabi\0\1$\0\0\0\0056\0\6\6\10\1\t\1\n\2\22\4\24\1\25"..., 47) = 47
fstat64(3, {st_mode=S_IFREG|0755, st_size=1196144, ...}) = 0
mmap2(NULL, 1238312, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0xb6db1000
mprotect(0xb6ed3000, 28672, PROT_NONE)  = 0
mmap2(0xb6eda000, 12288, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x121) = 0xb6eda000
mmap2(0xb6edd000, 9512, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0xb6edd000
close(3)                                = 0
mmap2(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0xb6f17000
set_tls(0xb6f174c0, 0xb6f17b98, 0xb6f1b048, 0xb6f174c0, 0xb6f1b048) = 0
mprotect(0xb6eda000, 8192, PROT_READ)   = 0
--- SIGSEGV (Segmentation fault) @ 0 (0) ---
+++ killed by SIGSEGV +++
```

I don't know if this is specific to raspbian or if it would affect debian armhf too, so I'm filing this here first.

**Comment by hvenzke** [comment]
Had same issue few days ago. 
Killed 2 SD , all partions where Gone !! 
( lost no data since i know tedoroe tso ´s ext edit guide  )

using /sbin/resize2fs   resize   -- the ext4 resize code are currently STILL BETTA with Horrible bugs .

Since this i use ext4 only for an 5-10G root and others with XFS & lvm

XFS is STABLE since +20years.
XFS are either FASTER after kernel 3.3 then ext4.

Holy FS flame war on 

If i where an Curent RPI  distro maintainer  -
i wuold KILL ext4 anyhow as / ( root ) due stability issues  as its STILL marked EXPERIMENTAL into the kernel.

Holy FS flame war off

**Comment by richo** [comment]
Wat? ext4 was stable in 2.6.28:

> ext4 was released as a functionally complete and stable filesystem in Linux 2.6.28 [citation](https://ext4.wiki.kernel.org/index.php/Ext4_Howto#General_Information)

**Comment by hvenzke** [comment]
ext4  its not realy stable .

as an IT staff of some Big Irons , failed  multible times on PROD systems .
either SuSe´s  &  HP support fraction its self  saing NOT to use it in PRODUCTION !!

DAILY  BUG  reporting for EXT4 : http://blog.gmane.org/gmane.comp.file-systems.ext4
Every day with MULTIBLE issues . and more then 1 patch a week almost

NOT  to happen with XFS !!
http://lwn.net/Articles/476263/ for more about EXt4 vs XFS

**Comment by Ferroin** [comment]
Was the file-system mounted when you tried to resize (there are problems with online resizing)?
Can you post the output of `tune2fs -l` for the file-system, certain fs features are known to not work, but don't get caught by some distros' versions of resize2fs.

**Comment by hvenzke** [comment]
The FS resize  done  at FIRST boot witch where prepared by raspi-config.

This are the default used  rasberian ( 7.0, febuary RPI debian release ) parameters -  uchanged .

<pre>
 tune2fs -l /dev/mmcblk0p2
tune2fs 1.42.5 (29-Jul-2012)
Filesystem volume name:   <none>
Last mounted on:          /
Filesystem UUID:          62ba9ec9-47d9-4421-aaee-71dd6c0f3707
Filesystem magic number:  0xEF53
Filesystem revision #:    1 (dynamic)
Filesystem features:      has_journal ext_attr resize_inode dir_index filetype needs_recovery extent flex_bg sparse_super large_file uninit_bg dir_nlink extra_isize
Filesystem flags:         signed_directory_hash
Default mount options:    user_xattr acl
Filesystem state:         clean
Errors behavior:          Continue
Filesystem OS type:       Linux
Inode count:              655360
Block count:              2621440
Reserved block count:     131072
Free blocks:              1582212
Free inodes:              534880
First block:              0
Block size:               4096
Fragment size:            4096
Reserved GDT blocks:      111
Blocks per group:         32768
Fragments per group:      32768
Inodes per group:         8192
Inode blocks per group:   512
Flex block group size:    16
Filesystem created:       Sat Feb  9 01:46:10 2013
Last mount time:          Wed May  8 19:01:34 2013
Last write time:          Wed May  8 19:01:33 2013
Mount count:              11
Maximum mount count:      -1
Last checked:             Tue May  7 01:38:37 2013
Check interval:           0 (<none>)
Lifetime writes:          13 GB
Reserved blocks uid:      0 (user root)
Reserved blocks gid:      0 (group root)
First inode:              11
Inode size:               256
Required extra isize:     28
Desired extra isize:      28
Journal inode:            8
Default directory hash:   half_md4
Directory Hash Seed:      b329b0a2-759e-4040-b829-ca98fc22ab8d
Journal backup:           inode blocks
</pre>

**Comment by Ferroin** [comment]
`needs_recovery` under Filesystem Features is a definite red flag, resizing a filesystem that isn't clean is never a good idea, regardless of what the man pages might say otherwise.
Try running `e2fsck -f` before `resize2fs`.

**Comment by hvenzke** [comment]
@Ferroin 

I know  - but thats the EXt4 default featgers compiled in RPI standard ( 3.6.11+ ) and NEXT Firmware.

<pre>
Filesystem flags:         signed_directory_hash
</pre>

e2fsck -f  done allways - when myself resize ext\* FS manualy.

Just the raspi-config   DON´T do it.

<b>someone shuold togle & change the  raspi-config  accordingly. </b>

orign  raspi-config  resize code:

<pre>
case "$1" in
  start)
    log_daemon_msg "Starting resize2fs_once" &&
    resize2fs /dev/mmcblk0p2 &&
    rm /etc/init.d/resize2fs_once &&
    update-rc.d resize2fs_once remove &&
    log_end_msg $?
    ;;
</pre>

thus , NO FSCHK !!

**Comment by funkyHat** [comment]
tune2fs -l output:

```
tune2fs 1.42.5 (29-Jul-2012)
Filesystem volume name:   <none>
Last mounted on:          /I1
Filesystem UUID:          735d7b21-3149-4479-bb15-33b4ee07b3e3
Filesystem magic number:  0xEF53
Filesystem revision #:    1 (dynamic)
Filesystem features:      has_journal ext_attr resize_inode dir_index
filetype extent flex_bg sparse_super large_file huge_file uninit_bg
dir_nlink extra_isize
Filesystem flags:         unsigned_directory_hash
Default mount options:    user_xattr acl
Filesystem state:         clean
Errors behavior:          Continue
Filesystem OS type:       Linux
Inode count:              104505344
Block count:              417992704
Reserved block count:     20899635
Free blocks:              366624851
Free inodes:              104473855
First block:              0
Block size:               4096
Fragment size:            4096
Reserved GDT blocks:      924
Blocks per group:         32768
Fragments per group:      32768
Inodes per group:         8192
Inode blocks per group:   512
Flex block group size:    16
Filesystem created:       Wed May  1 18:45:48 2013
Last mount time:          Wed May  8 20:17:13 2013
Last write time:          Thu May  9 20:36:01 2013
Mount count:              5
Maximum mount count:      -1
Last checked:             Thu May  2 15:43:05 2013
Check interval:           0 (<none>)
Lifetime writes:          156 GB
Reserved blocks uid:      0 (user root)
Reserved blocks gid:      0 (group root)
First inode:              11
Inode size:               256
Required extra isize:     28
Desired extra isize:      28
Journal inode:            8
Default directory hash:   half_md4
Directory Hash Seed:      18c7adcd-5d48-4f0a-bacb-14d0555fb36c
Journal backup:           inode blocks
```

I have tried with the filesystem both mounted and not mounted.

The full size of the (lvm) volume is roughly double the current fs size.
It's spanned over 2 pvs on the same physical (USB) drive, not that I'm
expecting that to make a difference, just thought it might be worth
mentioning.

Posting again as github is apparently awkward with emailed comments...

**Comment by Ferroin** [comment]
I'm not seeing anything there that would seem to indicate a problem, it may in fact be partly due to the lvm configuration (I have had transient issues with LVM when using multiple PV's on the same underlying block device.).

**Comment by funkyHat** [comment]
This seems to be resolved (though I only tried an offline resize this time) with the most recent updates to raspbian (Linux 3.6.11, resize2fs 1.42.5)
