### ISSUE TITLE
How to use 2 SC16IS752,I USE I2C 

### ISSUE THREAD

**Issue by waveshare** [raspberrypi/linux#2892]
Hello, we am waveshare, how can I add two SC16IS752,
I added the following in config.txt:
`dtoverlay=sc16is752-i2c,int_pin=18,addr=0x48
dtoverlay=sc16is752-i2c,int_pin=25,addr=0x4c
`
and i reboot raspberryPi
I am running
ls /dev/tty
![image](https://user-images.githubusercontent.com/36142105/54187994-bff3b780-44e9-11e9-9e25-f7281d657060.png)
But ttySC2 and ttySC3 did not appear
can you help me.

**Comment by pelwell** [comment]
This is not the place to ask questions - try the [Device Tree area of the Raspberry Pi Forums](https://www.raspberrypi.org/forums/viewforum.php?f=107).

**Comment by waveshare** [comment]
OK.TKS
