### ISSUE TITLE
Kernel Oops on cifs mount

### ISSUE THREAD

**Issue by Mickael-Martin** [raspberrypi/linux#290]
Hi,

Mount a remote samba share with 
"//192.168.1.1/USB_2_0_Drive____1   /mnt cifs guest,_netdev   0   0" (with or without _netdev in /etc/fstab) 
causes "CIFS VFS: Error -32 sending data on socket to server" (in /var/log/kern.log) when I want to access to my files (>700Mo), then a "Kernel Oops" occurs (secutity of kernel ?)

Log of Kernel Oops : http://sebsauvage.net/paste/?11ab9acb953d0166#3tsphu0TG5ZjsUDfP6fP1nK0jvuaElt5+pRVYq/saHU=

Paquet cifs-utils : 2:5.5-1 testing                              

uname -a : Linux raspberrypi 3.6.11+ #371 PREEMPT Thu Feb 7 16:31:35 GMT 2013 armv6l GNU/Linux

Can you help me please...

**Comment by popcornmix** [comment]
You could try rpi-update
https://github.com/Hexxeh/rpi-update
There's been quite a few fixes to usb since your kernel.

**Comment by hvenzke** [comment]
@popcornmix has there been some changes at  rpi-update ? 

when i use  

BRANCH=next ; rpi-update, that_ not_ point me to current 3.8.11

Instead i got the 3.6.11

**Comment by popcornmix** [comment]
You need 
`sudo BRANCH=next rpi-update`

I think the ";" will break it.

**Comment by hvenzke** [comment]
okay Got it - sorry , user error.

**Comment by Mickael-Martin** [comment]
I try this now. Thank you.

**Comment by Mickael-Martin** [comment]
I have the same issue after the update : 
"Your firmware is already up to date"

Linux raspberrypi 3.8.12+ #440 PREEMPT Wed May 8 23:14:03 BST 2013 armv6l GNU/Linux

I use a remote share (and no USB connection directly with my raspberry) to save my torrents with transmission-deamon.

**Comment by hvenzke** [comment]
have the same issue with "Your firmware is already up to date". msg.

and how to reproduce it 

<pre>
cd /root
rm -rf .rpi-firmware
BRANCH=next rpi-update
</pre>

@Mickael-Martin   please be shure NOT enter an " ; "between BRANCH setting and the rpi-update.

@popcornmix  

1- can you add an fsck -f -y       command 
   for next boot( once exec ..)  after updating kernel to be SHURE that kernel updates not cause fs corruption.
2 - can rpi-update please BLOCK  the distro kernel update while use the BRANCH=next 
     witch cause an kenrel downgrade  to 3.6.11

**Comment by P33M** [comment]
My Pi running as a NAS with CIFS works just fine with latest kernel.
