### ISSUE TITLE
Kernel Header 4.14.78-v7+

### ISSUE THREAD

**Issue by Tanrikulu** [raspberrypi/linux#2901]
Hello all,

I am using a raspberry pi 3B+. Ubuntu Mate is running on the Raspberry. I need some support regarding to getting and installation of kernel headers for Ubuntu Mate. Has anyone an idea firstly how to get the headers?

**Comment by JamesH65** [comment]
We do not support Ubuntu Mate - our supported OS is Raspbian.

I suggest using asking the Ubuntu forums.

**Comment by 6by9** [comment]
Normally on Ubuntu you use apt to install package ```linux-headers-`uname -r` ```, so something like linux-headers-4.14.78-v7+ in your case.
