### ISSUE TITLE
My Wi-Fi scanner based on Raspberry pi was stopped with some problems

### ISSUE THREAD

**Issue by ghost** [raspberrypi/linux#2909]
My Wi-Fi scanner was developed by Nexmon (https://github.com/seemoo-lab/nexmon) based on Raspberry Pi 3B. During capturing the Wi-Fi probes, the scanner sometimes is stopped. The stop time is Mar 26 12:32:15 because we haven't had any data since then. 

In fact, when I see the log file of the Pi, there are many warning like this: Could you understand that kinds of warning..?

> Mar 26 12:32:15 monitoring-pi kernel: [126742.472373] python3: page allocation stalls for 10060ms, order:1,
>  mode:0x15080c0(GFP_KERNEL_ACCOUNT|__GFP_ZERO), nodemask=(null)
> Mar 26 12:32:15 monitoring-pi kernel: [126742.472401] python3 cpuset=/ mems_allowed=0
> Mar 26 12:32:15 monitoring-pi kernel: [126742.472422] CPU: 0 PID: 530 Comm: python3 Tainted: G         C O
>    4.14.79-v7+ #1159
> Mar 26 12:32:15 monitoring-pi kernel: [126742.472425] Hardware name: BCM2835
> Mar 26 12:32:15 monitoring-pi kernel: [126742.472448] [<8010ff30>] (unwind_backtrace) from [<8010c174>] (sh
> ow_stack+0x20/0x24)
> Mar 26 12:32:15 monitoring-pi kernel: [126742.472460] [<8010c174>] (show_stack) from [<80788fa4>] (dump_sta
> ck+0xd4/0x118)
> Mar 26 12:32:15 monitoring-pi kernel: [126742.472473] [<80788fa4>] (dump_stack) from [<80228fc8>] (warn_all
> oc+0xcc/0x17c)
> Mar 26 12:32:15 monitoring-pi kernel: [126742.472483] [<80228fc8>] (warn_alloc) from [<80229dbc>] (__alloc_
> pages_nodemask+0xc90/0x11d8)
> Mar 26 12:32:15 monitoring-pi kernel: [126742.472493] [<80229dbc>] (__alloc_pages_nodemask) from [<8011b398
> >] (copy_process.part.5+0xec/0x1858)
> Mar 26 12:32:15 monitoring-pi kernel: [126742.472500] [<8011b398>] (copy_process.part.5) from [<8011cc94>]
> (_do_fork+0xc8/0x408)
> Mar 26 12:32:15 monitoring-pi kernel: [126742.472507] [<8011cc94>] (_do_fork) from [<8011d0f8>] (SyS_clone+
> 0x34/0x3c)
> Mar 26 12:32:15 monitoring-pi kernel: [126742.472516] [<8011d0f8>] (SyS_clone) from [<80108000>] (ret_fast_
> syscall+0x0/0x28)
> Mar 26 12:32:15 monitoring-pi kernel: [126742.472520] Mem-Info:
> Mar 26 12:32:15 monitoring-pi kernel: [126742.472532] active_anon:112178 inactive_anon:112151 isolated_anon
> :32
> Mar 26 12:32:15 monitoring-pi kernel: [126742.472532]  active_file:458 inactive_file:504 isolated_file:0
> Mar 26 12:32:15 monitoring-pi kernel: [126742.472532]  unevictable:0 dirty:4 writeback:0 unstable:0
> Mar 26 12:32:15 monitoring-pi kernel: [126742.472532]  slab_reclaimable:1571 slab_unreclaimable:2173
> Mar 26 12:32:15 monitoring-pi kernel: [126742.472532]  mapped:1269 shmem:193 pagetables:626 bounce:0
> Mar 26 12:32:15 monitoring-pi kernel: [126742.472532]  free:5003 free_pcp:0 free_cma:1696
> Mar 26 12:32:15 monitoring-pi kernel: [126742.472540] Node 0 active_anon:448712kB inactive_anon:448604kB ac
> tive_file:1832kB inactive_file:2016kB unevictable:0kB isolated(anon):128kB isolated(file):0kB mapped:5076kB
>  dirty:16kB writeback:0kB shmem:772kB writeback_tmp:0kB unstable:0kB all_unreclaimable? no
> Mar 26 12:32:15 monitoring-pi kernel: [126742.472552] Normal free:20012kB min:16384kB low:20480kB high:2457
> 6kB active_anon:448664kB inactive_anon:448608kB active_file:1832kB inactive_file:2016kB unevictable:0kB wri
> tepending:16kB present:970752kB managed:949448kB mlocked:0kB kernel_stack:800kB pagetables:2504kB bounce:0k
> B free_pcp:0kB local_pcp:0kB free_cma:6784kB
> Mar 26 12:32:15 monitoring-pi kernel: [126742.472554] lowmem_reserve[]: 0 0
> Mar 26 12:32:15 monitoring-pi kernel: [126742.472562] Normal: 281*4kB (UMEC) 307*8kB (UMEC) 169*16kB (UMEC)
>  35*32kB (UMEC) 19*64kB (UMEC) 7*128kB (UEC) 3*256kB (U) 1*512kB (E) 1*1024kB (E) 2*2048kB (EC) 1*4096kB (C
> ) = 20012kB
> Mar 26 12:32:15 monitoring-pi kernel: [126742.472611] 1176 total pagecache pages
> Mar 26 12:32:15 monitoring-pi kernel: [126742.472615] 0 pages in swap cache
> Mar 26 12:32:15 monitoring-pi kernel: [126742.472618] Swap cache stats: add 25725, delete 25725, find 223/2
> 97
> Mar 26 12:32:15 monitoring-pi kernel: [126742.472622] Free swap  = 4kB
> Mar 26 12:32:15 monitoring-pi kernel: [126742.472625] Total swap = 102396kB
> Mar 26 12:32:15 monitoring-pi kernel: [126742.472627] 242688 pages RAM
> Mar 26 12:32:15 monitoring-pi kernel: [126742.472630] 0 pages HighMem/MovableOnly
> Mar 26 12:32:15 monitoring-pi kernel: [126742.472632] 5326 pages reserved
> Mar 26 12:32:15 monitoring-pi kernel: [126742.472634] 2048 pages cma reserved
> Mar 26 12:32:25 monitoring-pi kernel: [126752.433790] python3: page allocation stalls for 20020ms, order:1,
>  mode:0x15080c0(GFP_KERNEL_ACCOUNT|__GFP_ZERO), nodemask=(null)
> Mar 26 12:32:25 monitoring-pi kernel: [126752.433815] python3 cpuset=/ mems_allowed=0
> Mar 26 12:32:25 monitoring-pi kernel: [126752.433829] CPU: 3 PID: 530 Comm: python3 Tainted: G         C O
>    4.14.79-v7+ #1159
> Mar 26 12:32:25 monitoring-pi kernel: [126752.433832] Hardware name: BCM2835
> Mar 26 12:32:25 monitoring-pi kernel: [126752.433854] [<8010ff30>] (unwind_backtrace) from [<8010c174>] (sh
> ow_stack+0x20/0x24)
> Mar 26 12:32:25 monitoring-pi kernel: [126752.433864] [<8010c174>] (show_stack) from [<80788fa4>] (dump_sta
> ck+0xd4/0x118)
> Mar 26 12:32:25 monitoring-pi kernel: [126752.433877] [<80788fa4>] (dump_stack) from [<80228fc8>] (warn_all
> oc+0xcc/0x17c)
> Mar 26 12:32:25 monitoring-pi kernel: [126752.433888] [<80228fc8>] (warn_alloc) from [<80229dbc>] (__alloc_
> pages_nodemask+0xc90/0x11d8)
> Mar 26 12:32:25 monitoring-pi kernel: [126752.433898] [<80229dbc>] (__alloc_pages_nodemask) from [<8011b398
> >] (copy_process.part.5+0xec/0x1858)
> Mar 26 12:32:25 monitoring-pi kernel: [126752.433906] [<8011b398>] (copy_process.part.5) from [<8011cc94>]
> (_do_fork+0xc8/0x408)
> Mar 26 12:32:25 monitoring-pi kernel: [126752.433913] [<8011cc94>] (_do_fork) from [<8011d0f8>] (SyS_clone+
> 0x34/0x3c)
> Mar 26 12:32:25 monitoring-pi kernel: [126752.433921] [<8011d0f8>] (SyS_clone) from [<80108000>] (ret_fast_
> syscall+0x0/0x28)
> Mar 26 12:32:25 monitoring-pi kernel: [126752.433925] Mem-Info:
> Mar 26 12:32:25 monitoring-pi kernel: [126752.433937] active_anon:112140 inactive_anon:112156 isolated_anon
> :64
> Mar 26 12:32:25 monitoring-pi kernel: [126752.433937]  active_file:321 inactive_file:413 isolated_file:0
> Mar 26 12:32:25 monitoring-pi kernel: [126752.433937]  unevictable:0 dirty:0 writeback:0 unstable:0
> Mar 26 12:32:25 monitoring-pi kernel: [126752.433937]  slab_reclaimable:1573 slab_unreclaimable:2173
> Mar 26 12:32:25 monitoring-pi kernel: [126752.433937]  mapped:1018 shmem:196 pagetables:626 bounce:0
> Mar 26 12:32:25 monitoring-pi kernel: [126752.433937]  free:5053 free_pcp:0 free_cma:1697
> Mar 26 12:32:25 monitoring-pi kernel: [126752.433946] Node 0 active_anon:448660kB inactive_anon:448624kB ac
> tive_file:1284kB inactive_file:1652kB unevictable:0kB isolated(anon):256kB isolated(file):0kB mapped:4072kB
>  dirty:0kB writeback:0kB shmem:784kB writeback_tmp:0kB unstable:0kB all_unreclaimable? no
> Mar 26 12:32:25 monitoring-pi kernel: [126752.433957] Normal free:20212kB min:16384kB low:20480kB high:2457
> 6kB active_anon:448352kB inactive_anon:448940kB active_file:788kB inactive_file:1952kB unevictable:0kB writ
> epending:0kB present:970752kB managed:949448kB mlocked:0kB kernel_stack:792kB pagetables:2504kB bounce:0kB
> free_pcp:0kB local_pcp:0kB free_cma:6788kB
> Mar 26 12:32:25 monitoring-pi kernel: [126752.433960] lowmem_reserve[]: 0 0
> Mar 26 12:32:25 monitoring-pi kernel: [126752.433968] Normal: 379*4kB (UMEC) 354*8kB (UMEC) 169*16kB (UMEC)
>  34*32kB (UMEC) 18*64kB (UMEC) 8*128kB (UMEC) 3*256kB (U) 1*512kB (E) 1*1024kB (E) 2*2048kB (EC) 1*4096kB (
> C) = 20812kB
> Mar 26 12:32:25 monitoring-pi kernel: [126752.434017] 965 total pagecache pages
> Mar 26 12:32:25 monitoring-pi kernel: [126752.434020] 0 pages in swap cache
> Mar 26 12:32:25 monitoring-pi kernel: [126752.434025] Swap cache stats: add 25731, delete 25731, find 225/3
> 00
> Mar 26 12:32:25 monitoring-pi kernel: [126752.434028] Free swap  = 4kB
> Mar 26 12:32:25 monitoring-pi kernel: [126752.434030] Total swap = 102396kB
> Mar 26 12:32:25 monitoring-pi kernel: [126752.434033] 242688 pages RAM
> Mar 26 12:32:25 monitoring-pi kernel: [126752.434035] 0 pages HighMem/MovableOnly
> Mar 26 12:32:25 monitoring-pi kernel: [126752.434037] 5326 pages reserved
> Mar 26 12:32:25 monitoring-pi kernel: [126752.434040] 2048 pages cma reserved
> Mar 26 12:32:35 monitoring-pi kernel: [126762.492476] python3: page allocation stalls for 30080ms, order:1,
>  mode:0x15080c0(GFP_KERNEL_ACCOUNT|__GFP_ZERO), nodemask=(null)
> Mar 26 12:32:36 monitoring-pi kernel: [126762.492516] python3 cpuset=/ mems_allowed=0
> Mar 26 12:32:37 monitoring-pi kernel: [126762.492541] CPU: 2 PID: 530 Comm: python3 Tainted: G         C O
>    4.14.79-v7+ #1159
> Mar 26 12:32:37 monitoring-pi kernel: [126762.492546] Hardware name: BCM2835
> Mar 26 12:32:37 monitoring-pi kernel: [126762.492579] [<8010ff30>] (unwind_backtrace) from [<8010c174>] (sh
> ow_stack+0x20/0x24)
> Mar 26 12:32:37 monitoring-pi kernel: [126762.492597] [<8010c174>] (show_stack) from [<80788fa4>] (dump_sta
> ck+0xd4/0x118)
> Mar 26 12:32:37 monitoring-pi kernel: [126762.492618] [<80788fa4>] (dump_stack) from [<80228fc8>] (warn_all
> oc+0xcc/0x17c)
> Mar 26 12:32:37 monitoring-pi kernel: [126762.492639] [<80228fc8>] (warn_alloc) from [<80229dbc>] (__alloc_
> pages_nodemask+0xc90/0x11d8)
> Mar 26 12:32:37 monitoring-pi kernel: [126762.492657] [<80229dbc>] (__alloc_pages_nodemask) from [<8011b398
> >] (copy_process.part.5+0xec/0x1858)
> Mar 26 12:32:37 monitoring-pi kernel: [126762.492672] [<8011b398>] (copy_process.part.5) from [<8011cc94>]
> (_do_fork+0xc8/0x408)
> Mar 26 12:32:37 monitoring-pi kernel: [126762.492685] [<8011cc94>] (_do_fork) from [<8011d0f8>] (SyS_clone+
> 0x34/0x3c)
> Mar 26 12:32:37 monitoring-pi kernel: [126762.492701] [<8011d0f8>] (SyS_clone) from [<80108000>] (ret_fast_
> syscall+0x0/0x28)
> Mar 26 12:32:37 monitoring-pi kernel: [126762.492709] Mem-Info:
> Mar 26 12:32:37 monitoring-pi kernel: [126762.492731] active_anon:112151 inactive_anon:112232 isolated_anon
> :0
> Mar 26 12:32:37 monitoring-pi kernel: [126762.492731]  active_file:101 inactive_file:435 isolated_file:0
> Mar 26 12:32:37 monitoring-pi kernel: [126762.492731]  unevictable:0 dirty:0 writeback:0 unstable:0
> Mar 26 12:32:37 monitoring-pi kernel: [126762.492731]  slab_reclaimable:1573 slab_unreclaimable:2173
> Mar 26 12:32:37 monitoring-pi kernel: [126762.492731]  mapped:967 shmem:198 pagetables:628 bounce:0
> Mar 26 12:32:37 monitoring-pi kernel: [126762.492731]  free:5360 free_pcp:2 free_cma:1697
> Mar 26 12:32:37 monitoring-pi kernel: [126762.492748] Node 0 active_anon:448604kB inactive_anon:448928kB ac
> tive_file:404kB inactive_file:1740kB unevictable:0kB isolated(anon):0kB isolated(file):0kB mapped:3868kB di
> rty:0kB writeback:0kB shmem:792kB writeback_tmp:0kB unstable:0kB all_unreclaimable? no
> Mar 26 12:32:37 monitoring-pi kernel: [126762.492773] Normal free:21440kB min:16384kB low:20480kB high:2457
> 6kB active_anon:448604kB inactive_anon:448928kB active_file:404kB inactive_file:1876kB unevictable:0kB writ
> epending:0kB present:970752kB managed:949448kB mlocked:0kB kernel_stack:792kB pagetables:2512kB bounce:0kB
> free_pcp:8kB local_pcp:0kB free_cma:6788kB
> Mar 26 12:32:37 monitoring-pi kernel: [126762.492781] lowmem_reserve[]: 0 0
> Mar 26 12:32:37 monitoring-pi kernel: [126762.492810] Normal: 551*4kB (UMEC) 367*8kB (UMEC) 169*16kB (UMEC)
>  35*32kB (UMEC) 18*64kB (UMEC) 8*128kB (UMEC) 3*256kB (U) 1*512kB (E) 1*1024kB (E) 2*2048kB (EC) 1*4096kB (
> C) = 21636kB
> Mar 26 12:32:37 monitoring-pi kernel: [126762.492921] 752 total pagecache pages
> Mar 26 12:32:37 monitoring-pi kernel: [126762.492928] 3 pages in swap cache
> Mar 26 12:32:37 monitoring-pi kernel: [126762.492935] Swap cache stats: add 25738, delete 25735, find 226/3
> 02
> Mar 26 12:32:37 monitoring-pi kernel: [126762.492939] Free swap  = 0kB
> Mar 26 12:32:37 monitoring-pi kernel: [126762.492944] Total swap = 102396kB
> Mar 26 12:32:37 monitoring-pi kernel: [126762.492949] 242688 pages RAM
> Mar 26 12:32:37 monitoring-pi kernel: [126762.492953] 0 pages HighMem/MovableOnly
> Mar 26 12:32:37 monitoring-pi kernel: [126762.492958] 5326 pages reserved
> Mar 26 12:32:37 monitoring-pi kernel: [126762.492966] 2048 pages cma reserved
> Mar 26 12:32:37 monitoring-pi kernel: [126764.421946] python3 invoked oom-killer: gfp_mask=0x15080c0(GFP_KE
> RNEL_ACCOUNT|__GFP_ZERO), nodemask=(null),  order=1, oom_score_adj=0
> Mar 26 12:32:37 monitoring-pi kernel: [126764.421959] python3 cpuset=/ mems_allowed=0
> Mar 26 12:32:37 monitoring-pi kernel: [126764.421975] CPU: 3 PID: 530 Comm: python3 Tainted: G         C O
>    4.14.79-v7+ #1159
> Mar 26 12:32:37 monitoring-pi kernel: [126764.421977] Hardware name: BCM2835
> Mar 26 12:32:37 monitoring-pi kernel: [126764.421998] [<8010ff30>] (unwind_backtrace) from [<8010c174>] (sh
> ow_stack+0x20/0x24)
> Mar 26 12:32:37 monitoring-pi kernel: [126764.422008] [<8010c174>] (show_stack) from [<80788fa4>] (dump_sta
> ck+0xd4/0x118)
> Mar 26 12:32:37 monitoring-pi kernel: [126764.422019] [<80788fa4>] (dump_stack) from [<802249ec>] (dump_hea
> der+0xac/0x208)
> Mar 26 12:32:37 monitoring-pi kernel: [126764.422029] [<802249ec>] (dump_header) from [<80223d54>] (oom_kil
> l_process+0x478/0x584)
> Mar 26 12:32:37 monitoring-pi kernel: [126764.422037] [<80223d54>] (oom_kill_process) from [<802246b4>] (ou
> t_of_memory+0x124/0x334)
> Mar 26 12:32:37 monitoring-pi kernel: [126764.422047] [<802246b4>] (out_of_memory) from [<8022a18c>] (__all
> oc_pages_nodemask+0x1060/0x11d8)
> Mar 26 12:32:37 monitoring-pi kernel: [126764.422057] [<8022a18c>] (__alloc_pages_nodemask) from [<8011b398
> >] (copy_process.part.5+0xec/0x1858)
> Mar 26 12:32:37 monitoring-pi kernel: [126764.422065] [<8011b398>] (copy_process.part.5) from [<8011cc94>]
> (_do_fork+0xc8/0x408)
> Mar 26 12:32:37 monitoring-pi kernel: [126764.422071] [<8011cc94>] (_do_fork) from [<8011d0f8>] (SyS_clone+
> 0x34/0x3c)
> Mar 26 12:32:37 monitoring-pi kernel: [126764.422080] [<8011d0f8>] (SyS_clone) from [<80108000>] (ret_fast_
> syscall+0x0/0x28)
> Mar 26 12:32:37 monitoring-pi kernel: [126764.422084] Mem-Info:
> Mar 26 12:32:37 monitoring-pi kernel: [126764.422096] active_anon:112151 inactive_anon:112232 isolated_anon
> :0
> Mar 26 12:32:37 monitoring-pi kernel: [126764.422096]  active_file:58 inactive_file:59 isolated_file:0
> Mar 26 12:32:37 monitoring-pi kernel: [126764.422096]  unevictable:0 dirty:3 writeback:0 unstable:0
> Mar 26 12:32:37 monitoring-pi kernel: [126764.422096]  slab_reclaimable:1573 slab_unreclaimable:2173
> Mar 26 12:32:37 monitoring-pi kernel: [126764.422096]  mapped:695 shmem:198 pagetables:628 bounce:0
> Mar 26 12:32:37 monitoring-pi kernel: [126764.422096]  free:5709 free_pcp:0 free_cma:1697
> Mar 26 12:32:37 monitoring-pi kernel: [126764.422104] Node 0 active_anon:448604kB inactive_anon:448928kB ac
> tive_file:232kB inactive_file:236kB unevictable:0kB isolated(anon):0kB isolated(file):0kB mapped:2780kB dir
> ty:12kB writeback:0kB shmem:792kB writeback_tmp:0kB unstable:0kB all_unreclaimable? no
> Mar 26 12:32:37 monitoring-pi kernel: [126764.422116] Normal free:22836kB min:16384kB low:20480kB high:2457
> 6kB active_anon:448604kB inactive_anon:448928kB active_file:668kB inactive_file:692kB unevictable:0kB write
> pending:4kB present:970752kB managed:949448kB mlocked:0kB kernel_stack:792kB pagetables:2512kB bounce:0kB f
> ree_pcp:0kB local_pcp:0kB free_cma:6788kB
> Mar 26 12:32:37 monitoring-pi kernel: [126764.422117] lowmem_reserve[]: 0 0
> Mar 26 12:32:37 monitoring-pi kernel: [126764.422125] Normal: 920*4kB (UMEC) 364*8kB (UMEC) 167*16kB (UMEC)
>  37*32kB (UMEC) 18*64kB (UMEC) 8*128kB (UMEC) 3*256kB (U) 1*512kB (E) 1*1024kB (E) 2*2048kB (EC) 1*4096kB (
> C) = 23120kB
> Mar 26 12:32:37 monitoring-pi kernel: [126764.422174] 397 total pagecache pages
> Mar 26 12:32:37 monitoring-pi kernel: [126764.422178] 3 pages in swap cache
> Mar 26 12:32:37 monitoring-pi kernel: [126764.422181] Swap cache stats: add 25738, delete 25735, find 226/3
> 02
> Mar 26 12:32:37 monitoring-pi kernel: [126764.422184] Free swap  = 0kB
> Mar 26 12:32:37 monitoring-pi kernel: [126764.422186] Total swap = 102396kB
> Mar 26 12:32:37 monitoring-pi kernel: [126764.422189] 242688 pages RAM
> Mar 26 12:32:37 monitoring-pi kernel: [126764.422191] 0 pages HighMem/MovableOnly
> Mar 26 12:32:37 monitoring-pi kernel: [126764.422193] 5326 pages reserved
> Mar 26 12:32:37 monitoring-pi kernel: [126764.422196] 2048 pages cma reserved
> Mar 26 12:32:37 monitoring-pi kernel: [126764.422199] [ pid ]   uid  tgid total_vm      rss nr_ptes nr_pmds
>  swapents oom_score_adj name
> Mar 26 12:32:37 monitoring-pi kernel: [126764.422216] [  105]     0   105     3199      205       9       0
>        62             0 systemd-journal
> Mar 26 12:32:37 monitoring-pi kernel: [126764.422222] [  125]     0   125     3586       15       8       0
>       144         -1000 systemd-udevd
> Mar 26 12:32:37 monitoring-pi kernel: [126764.422229] [  276]   100   276     4321       37       9       0
>        74             0 systemd-timesyn
> Mar 26 12:32:37 monitoring-pi kernel: [126764.422234] [  330]     0   330      516        0       4       0
>        24             0 rfcomm
> Mar 26 12:32:37 monitoring-pi kernel: [126764.422240] [  335]     0   335     5937       98      11       0
>        89             0 rsyslogd
> Mar 26 12:32:37 monitoring-pi kernel: [126764.422246] [  338]   105   338     1596       46       8       0
>        57          -900 dbus-daemon
> Mar 26 12:32:37 monitoring-pi kernel: [126764.422251] [  374]     0   374     1324       17       6       0
>        37             0 cron
> Mar 26 12:32:37 monitoring-pi kernel: [126764.422258] [  375]     0   375     1729       26       7       0
>        65             0 systemd-logind
> Mar 26 12:32:37 monitoring-pi kernel: [126764.422264] [  376] 65534   376     1324        4       7       0
>        56             0 thd
> Mar 26 12:32:37 monitoring-pi kernel: [126764.422270] [  380]   108   380     1601        0       6       0
>        85             0 avahi-daemon
> Mar 26 12:32:37 monitoring-pi kernel: [126764.422275] [  389]   108   389     1601        0       6       0
>        77             0 avahi-daemon
> Mar 26 12:32:37 monitoring-pi kernel: [126764.422281] [  433]     0   433     2542       17       9       0
>       130             0 wpa_supplicant
> Mar 26 12:32:37 monitoring-pi kernel: [126764.422287] [  457]     0   457      524        0       4       0
>        34             0 hciattach
> Mar 26 12:32:37 monitoring-pi kernel: [126764.422293] [  460]     0   460     1769        0       8       0
>        89             0 bluetoothd
> Mar 26 12:32:37 monitoring-pi kernel: [126764.422299] [  483]     0   483      737        0       6       0
>       100             0 dhcpcd
> Mar 26 12:32:37 monitoring-pi kernel: [126764.422305] [  484]     0   484   254830   223717     496       0
>     22873             0 python3
> Mar 26 12:32:37 monitoring-pi kernel: [126764.422310] [  496]     0   496     1049        0       6       0
>        35             0 agetty
> Mar 26 12:32:37 monitoring-pi kernel: [126764.422316] [  499]     0   499     2553        0       8       0
>       138         -1000 sshd
> Mar 26 12:32:37 monitoring-pi kernel: [126764.422322] Out of memory: Kill process 484 (python3) score 911 o
> r sacrifice child
> Mar 26 12:32:37 monitoring-pi kernel: [126764.422338] Killed process 484 (python3) total-vm:1019320kB, anon
> -rss:894868kB, file-rss:0kB, shmem-rss:0kB
> Mar 26 12:32:37 monitoring-pi kernel: [126764.642532] oom_reaper: reaped process 484 (python3), now anon-rs
> s:0kB, file-rss:2048kB, shmem-rss:0kB
> Mar 26 12:32:37 monitoring-pi kernel: [126764.646377] device mon0 left promiscuous mode
> Mar 26 12:32:37 monitoring-pi systemd[1]: wifi_monitor.service: Main process exited, code=killed, status=9/
> KILL
> Mar 26 12:32:37 monitoring-pi systemd[1]: wifi_monitor.service: Unit entered failed state.
> Mar 26 12:32:37 monitoring-pi systemd[1]: wifi_monitor.service: Failed with result 'signal'.
> Mar 26 12:32:51 monitoring-pi kernel: [126778.151918] Under-voltage detected! (0x00050005)
> Mar 26 12:32:57 monitoring-pi kernel: [126784.391911] Voltage normalised (0x00000000)
> Mar 26 12:34:51 monitoring-pi kernel: [126898.791909] Under-voltage detected! (0x00050005)
> Mar 26 12:34:55 monitoring-pi kernel: [126902.951937] Voltage normalised (0x00000000)

**Comment by JamesH65** [comment]
Two obvious fauls in there

1. Your power supply/cabling is inadequate
2. Something is using up all the memory (Python?) and subsequently the OOM process killer is being activated.

**Comment by XECDesign** [comment]
Also, I don't think we support patched firmware.

**Comment by ghost** [comment]
> Two obvious fauls in there
> 
> 1. Your power supply/cabling is inadequate
> 2. Something is using up all the memory (Python?) and subsequently the OOM process killer is being activated.

Can I ask which sentences means your post in the pi log??

**Comment by ghost** [comment]
> Also, I don't think we support patched firmware.

Can I ask what is the patched firmware?? I patched the Pi based on the Nexmon's instructions. It works well but suddenly it was stopped with the log..

**Comment by XECDesign** [comment]
> Can I ask what is the patched firmware??

The 'what is nexmon' section of the page you linked earlier provides a good description. Anything you do that involves nexmon is not something that can be supported here.

**Comment by ghost** [comment]
> > Can I ask what is the patched firmware??
> 
> The 'what is nexmon' section of the page you linked earlier provides a good description. Anything you do that involves nexmon is not something that can be supported here.

I followed "Build patches for bcm43430a1 on the RPI3/Zero W or bcm434355c0 on the RPI3+ using Raspbian (recommended)". In addition, my python code run that the pi turn off the wireless (wlan0) and turn on the wlan0 in order to change the channel of WiFi per 20 seconds. Is it too much burden to the pi...??

**Comment by pelwell** [comment]
> ...using Raspbian (recommended)

Not recommended by Raspbian.

>> Anything you do that involves nexmon is not something that can be supported here.

Read and understand that sentence.

**Comment by ghost** [comment]
> > ...using Raspbian (recommended)
> 
> Not recommended by Raspbian.
> 
> > > Anything you do that involves nexmon is not something that can be supported here.
> 
> Read and understand that sentence.

I understood that now. Thanks for your comments!!!
