### ISSUE TITLE
Branch 3.9.y - 'enable_whitelist' undeclared

### ISSUE THREAD

**Issue by srcshelton** [raspberrypi/linux#292]
```
  CC      drivers/usb/core/hub.o - due to: arch/arm/include/generated/asm/bitsperlong.h arch/arm/include/generated/asm/errno.h include/config/uidgid/strict/type/checks.h include/config/user/ns.h include/generated/bounds.h arch/arm/include/generated/asm/percpu.h arch/arm/include/generated/asm/auxvec.h arch/arm/include/generated/asm/cputime.h arch/arm/include/generated/asm/siginfo.h include/config/seccomp/filter.h arch/arm/include/generated/asm/resource.h arch/arm/include/generated/asm/ioctl.h
In file included from raspberrypi/src/kernel-3.9.y/drivers/usb/core/hub.c:2097:0:
raspberrypi/src/kernel-3.9.y/drivers/usb/core/otg_whitelist.h: In function 'is_targeted':
raspberrypi/src/kernel-3.9.y/drivers/usb/core/otg_whitelist.h:110:14: error: 'enable_whitelist' undeclared (first use in this function)
raspberrypi/src/kernel-3.9.y/drivers/usb/core/otg_whitelist.h:110:14: note: each undeclared identifier is reported only once for each function it appears in
raspberrypi/src/kernel-3.9.y/drivers/usb/core/otg_whitelist.h:185:1: warning: control reaches end of non-void function [-Wreturn-type]
make[6]: *** [drivers/usb/core/hub.o] Error 1
make[5]: *** [drivers/usb/core] Error 2
make[4]: *** [drivers/usb] Error 2
make[3]: *** [drivers] Error 2
make[2]: *** [sub-make] Error 2
make[1]: *** [vmlinux] Error 2
make: *** [sub-make] Error 2

raspberrypi kernel-3.9.y # grep -R enable_whitelist .
./drivers/usb/core/otg_whitelist.h:     } else if (!enable_whitelist) {
./drivers/usb/core/otg_whitelist.h:     if (enable_whitelist) {
raspberrypi kernel-3.9.y # grep -i white .config
# CONFIG_USB_OTG_WHITELIST is not set
# CONFIG_USB_SERIAL_WHITEHEAT is not set
```

**Comment by hvenzke** [comment]
Kconfig Bug for CONFIG_USB_OTG  as i assume , must be not tristate  as most of the RPI stuff.
Had the same error here.
reqire  both to be "y"

**Comment by popcornmix** [comment]
Have you enabled CONFIG_USB_OTG?
That's not something that's ever been tested.

**Comment by hvenzke** [comment]
...  testing compile it on fresh 3.8.12 ..
 .. will report soon.. what happen.
  in ~22h  we know it... my Pi´s was busy past days with samba 404.. 

Testcompile oldconfig changes  against my "stable"  3.8.7 tested .config
( http://www.raspberrypi.org/phpBB3/download/file.php?id=3174 )

<pre>
 CONFIG_USB_DYNAMIC_MINORS=y
 CONFIG_USB_SUSPEND=y
 CONFIG_USB_OTG=y
 CONFIG_USB_OTG_WHITELIST=y
 CONFIG_USB_OTG_BLACKLIST_HUB=y
 CONFIG_USB_MON=y
</pre>

@popcornmix   CONFIG_USB_OTG shuold be allways ON for RPI´s
Thats the onboard Hub staff, don´t it .-) 

msgs from 3.8.11 ( rpi-update kernel )

<pre>
dmesg | grep otg
[    0.000000] Kernel command line: dma.dmachans=0x7f35 bcm2708_fb.fbwidth=800 bcm2708_fb.fbheight=600 bcm2708.boardrev=0xf bcm2708.serial=0x7c978107 smsc95xx.macaddr=B8:27:EB:97:81:07 sdhci-bcm2708.emmc_clock_freq=100000000 vc_mem.mem_base=0x1ec00000 vc_mem.mem_size=0x20000000  dwc_otg.lpm_enable=0 console=ttyAMA0,115200 kgdboc=ttyAMA0,115200 console=tty1 root=/dev/mmcblk0p2 vga=normal highres=off rootfstype=ext4 elevator=deadline rootwait
[    1.321921] dwc_otg: version 3.00a 10-AUG-2012 (platform bus)
[    1.788946] dwc_otg: Microframe scheduler enabled
[    1.789146] dwc_otg bcm2708_usb: DWC OTG Controller
[    1.796778] dwc_otg bcm2708_usb: new USB bus registered, assigned bus number 1
[    1.806779] dwc_otg bcm2708_usb: irq 32, io mem 0x00000000
[    1.854083] usb usb1: Manufacturer: Linux 3.8.11+ dwc_otg_hcd
[    1.883807] dwc_otg: FIQ enabled
[    1.883825] dwc_otg: NAK holdoff enabled
[    2.350736] usb 1-1: new high-speed USB device number 2 using dwc_otg
[    2.910987] usb 1-1.1: new high-speed USB device number 3 using dwc_otg
</pre>

**Comment by hvenzke** [comment]
HMM as i remember due my past plenty compiles , just remind my self if one of this options was set like that 

<pre>
 CONFIG_USB_OTG_WHITELIST=m
 CONFIG_USB_OTG_BLACKLIST_HUB=m
 CONFIG_USB_OTG=m
</pre>

 OTG failed if m while  compiled on PI

and My PI failed  to boot from  without  CONFIG_USB_OTG=m
if Module not pushed to initrd.img

So that CONFIG_USB_OTG\*  Kconfigs   shuold be bolean rather then tristate.

**Comment by srcshelton** [comment]
```
$ grep OTG .config
CONFIG_USB_OTG=y
# CONFIG_USB_OTG_WHITELIST is not set
# CONFIG_USB_OTG_BLACKLIST_HUB is not set
CONFIG_USB_DWCOTG=y
# OTG and related infrastructure
```

I note that the official kernel.org 3.9.0 release contains no references to 'enable_whitelist'...

**Comment by hvenzke** [comment]
3.8.y( 3.8.12)  compiled well  as normal.
Thus this was´t  changed in 3.9.y  its the same  there.

<pre>
CONFIG_USB_OTG_WHITELIST=y
 CONFIG_USB_OTG_BLACKLIST_HUB=y
 CONFIG_USB_OTG=y
</pre>

@popcornmix :  must changed to Kconfig bolean  rather then tristate

@srcshelton issue solved - Kconfig error   :-

**Comment by popcornmix** [comment]
I'm not following:

```
config USB_OTG
    bool "OTG support"
...
config USB_OTG_WHITELIST
    bool "Rely on OTG Targeted Peripherals List"
...

config USB_OTG_BLACKLIST_HUB
    bool "Disable external hubs"
...
```

They all seem to be bool anyway. What option would like to be changed to bool?

**Comment by hvenzke** [comment]
from today stressttest with 3.9.y ( git from 24.05.2013 )

Its still the same - <b>its an Code BUG . </b>
@popcornmix try out yourself and fix it .
Please  tell me where to search for the symbol ( what header file, libary ..)

<pre>
In file included from drivers/usb/core/hub.c:2097:0:
drivers/usb/core/otg_whitelist.h: In function 'is_targeted':
drivers/usb/core/otg_whitelist.h:110:14: error: 'enable_whitelist' undeclared (first use in this function)
drivers/usb/core/otg_whitelist.h:110:14: note: each undeclared identifier is reported only once for each function it appears in
make[3]: *** [drivers/usb/core/hub.o] Fehler 1
make[2]: *** [drivers/usb/core] Fehler 2
make[1]: *** [drivers/usb] Fehler 2
make: *** [drivers] Fehler 2
~ :/usr/src/linux#  grep -i otg_whitelist .config
CONFIG_USB_OTG_WHITELIST=y
~ :/usr/src/linux#
</pre>

**Comment by ghollingworth** [comment]
You should search in drivers/USB

grep -r enable_whitelist *

Should do it...

Are you sure you cleaned the tree after adding the config option?

Gordon

On 25 May 2013, at 09:06, "Remsnet LTD," <notifications@github.com<mailto:notifications@github.com>> wrote:

from today stressttest with 3.9.y ( 3.9.1 ):

Its still the same - its an Code BUG .
@popcornmixhttps://github.com/popcornmix try out yourself and fix it .
Please tell me where to search for the symbol ( what header file, libary ..)

<pre
In file included from drivers/usb/core/hub.c:2097:0:
drivers/usb/core/otg_whitelist.h: In function 'is_targeted':
drivers/usb/core/otg_whitelist.h:110:14: error: 'enable_whitelist' undeclared (first use in this function)
drivers/usb/core/otg_whitelist.h:110:14: note: each undeclared identifier is reported only once for each function it appears in
make[3]: **\* [drivers/usb/core/hub.o] Fehler 1
make[2]: **\* [drivers/usb/core] Fehler 2
make[1]: **\* [drivers/usb] Fehler 2
make: **\* [drivers] Fehler 2

~ :/usr/src/linux# grep -i otg_whitelist .config
CONFIG_USB_OTG_WHITELIST=y
~ :/usr/src/linux#

##

**Comment by hvenzke** [comment]
@ghollingworth  - 
Gordon , please reply in an readable text . 
If you reply by email this seems to cause at current remove the carriage returns  and your msgs are near unreadable

And well that was an FRESH compile try .

i may assume it has todo with the removal   of  CONFIG_USB_OTG_UTILS  

see i.e https://lkml.org/lkml/2013/5/13/105 , https://patchwork.kernel.org/patch/2230741 http://marc.info/?t=136266748400001&r=1&w=3  and some more.

**Comment by ghollingworth** [comment]
Does it compile correctly upstream?

On 25 May 2013, at 09:29, "Remsnet LTD," <notifications@github.com<mailto:notifications@github.com>> wrote:

@ghollingworthhttps://github.com/ghollingworth -
Gordon , please reply in an readable text .
If you reply by email this seems to cause at current remove the carriage returns and your msgs.

And well that was an FRESH compile try .

##

**Comment by ghollingworth** [comment]
No you don't need config OTG this just enables the otg functionality which looks broken although I do believe someone had got it working before.

The driver is otg capable which is why it's called dwc_otg but the host doesn't need the config option

Gordon

**Comment by hvenzke** [comment]
Gordon ,

 Just removed CONFIG_USB_OTG_UTILS  USB_OTG_WHITELIST from my .config 
 and started the compile ON RPI ( no crosscompile ) again.

and anyhow , Brocken code shuold be removed or fixed somehow .

**Comment by ghollingworth** [comment]
Nobody is stopping you!

**Comment by hvenzke** [comment]
Godon , that is not realy make the view.
I am NOT an Coder.

the 3.9.y failed to compile .

<pre>
In file included from drivers/usb/core/hub.c:2097:0:
drivers/usb/core/otg_whitelist.h: In function 'is_targeted':
drivers/usb/core/otg_whitelist.h:110:14: error: 'enable_whitelist' undeclared (first use in this function)
drivers/usb/core/otg_whitelist.h:110:14: note: each undeclared identifier is reported only once for each function it appears in
drivers/usb/core/otg_whitelist.h:185:1: warning: control reaches end of non-void function [-Wreturn-type]
make[3]: *** [drivers/usb/core/hub.o] Fehler 1
make[2]: *** [drivers/usb/core] Fehler 2
make[1]: *** [drivers/usb] Fehler 2
make: *** [drivers] Fehler 2
~ #:/usr/src/linux# grep -i otg_whitelist .config
# CONFIG_USB_OTG_WHITELIST is not set
# vi .config
~ #:/usr/src/linux# make
scripts/kconfig/conf --silentoldconfig Kconfig
  CHK     include/generated/uapi/linux/version.h
  CHK     include/generated/utsrelease.h
make[1]: »include/generated/mach-types.h« ist bereits aktualisiert.
  CALL    scripts/checksyscalls.sh
  CC      scripts/mod/devicetable-offsets.s
  GEN     scripts/mod/devicetable-offsets.h
  HOSTCC  scripts/mod/file2alias.o
  HOSTLD  scripts/mod/modpost
  CHK     include/generated/compile.h
  GZIP    kernel/config_data.gz
  CHK     kernel/config_data.h
  UPD     kernel/config_data.h
  CC      kernel/configs.o
  LD      kernel/built-in.o
  CC      drivers/usb/core/hub.o
In file included from drivers/usb/core/hub.c:2097:0:
drivers/usb/core/otg_whitelist.h: In function 'is_targeted':
drivers/usb/core/otg_whitelist.h:110:14: error: 'enable_whitelist' undeclared (first use in this function)
drivers/usb/core/otg_whitelist.h:110:14: note: each undeclared identifier is reported only once for each function it appears in
make[3]: *** [drivers/usb/core/hub.o] Fehler 1
make[2]: *** [drivers/usb/core] Fehler 2
make[1]: *** [drivers/usb] Fehler 2
make: *** [drivers] Fehler 2
~ #:/usr/src/linux# grep -i otg_whitelist .config
CONFIG_USB_OTG_WHITELIST=y
~ #:/usr/src/linux#
</pre>

**Comment by popcornmix** [comment]
Looks like enable_whitelist is no longer present in 3.18 kernel (which we are moving to).
Anyway this is not an issue with the recommended configuration. Closing.

**Comment by hvenzke** [comment]
Thats fine - as the code cleanup at OTG closed this .
