### ISSUE TITLE
Tag "raspberrypi-kernel_1.20190401-1" refers to the kernel tagged with "raspberrypi-kernel_1.20190215-1"

### ISSUE THREAD

**Issue by VladimirTechMan** [raspberrypi/linux#2929]
As far as I can see, tag "raspberrypi-kernel_1.20190401-1", which is supposed to be for the most recent public kernel release for Pi, actually refers to the prior public kernel release that was tagged with "raspberrypi-kernel_1.20190215-1".

Can you, please, check and correct?

**Comment by popcornmix** [comment]
The kernel didn't change in the last update. It was a firmware update only.
(kernel tree has moved to 4.19 for testing, but it's not ready for stable releases).

**Comment by VladimirTechMan** [comment]
Ah, okay, thanks for the clarification, @popcornmix. I was confused.
