### ISSUE TITLE
chmod issue 

### ISSUE THREAD

**Issue by bobypierre** [raspberrypi/linux#2934]
Hello, help! help! help !

I have did a boolshit on my Debian system. 

I can only controling my Debian machine (raspi) in remote via the SSH protocol.

My issue :

I did a chmod -R 700 /usr
for one thing, and now I do not nothing...

When I'm connect via ssh I have : 

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: xxxx
ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
-bash: warning: setlocale: LC_ALL: cannot change locale (fr_FR.UTF-8)
-bash: id: command not found
-bash: [: : integer expression expected
-bash: gettext.sh: No such file or directory
-bash: gettext.sh: No such file or directory
-bash: /usr/share/bash-completion/bash_completion: Permission denied

Even if I do sudo reboot :

pi@raspberrypi:~$ sudo reboot
-bash: sudo: command not found
pi@raspberrypi:~$

How can I do please? 
Thanks 
Pierre

**Comment by pelwell** [comment]
Do you have a card reader and a spare SD card? If so:

1. Install a matching Raspbian image on the spare card.
2. Boot from the new image, and put the card with the broken image in the card reader and plug it into a spare USB port.
3. Mount the second partition of the card on /mnt.
4. sudo cp -R /usr /mnt/usr
5. Power off the system and put the card from the reader back in your Pi.

This should fix your problem, but I won't be held responsible if it doesn't.

**Comment by pelwell** [comment]
On second thoughts, replace the cp -R with a tar, in case there are symbolic links:
```
$ sudo tar cf - /usr | (cd /mnt/usr; tar xf -)
```

**Comment by bobypierre** [comment]
hello,  thank you for your reply.

I can't run with hardware because I m in UK, and my raspi is in France and use only SSH protocol.


If I try :

pi@raspberrypi:~$ sudo tar cf - /usr | (cd /mnt/usr; tar xf -)

-bash: sudo: command not found
-bash: cd: /mnt/usr: No such file or directory
ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors
pi@raspberrypi:~$

I don't know how to do.  
Do you have other idea?  
thank you , good by!

**Comment by pelwell** [comment]
If you have no chance to access the Pi directly then I think you are stuck - you've removed the setuid bit from sudo, and I can't think of any way to put it back without using sudo - it would be a big security problem.

Are you familiar with "Chère Élise" ("There's a hole in my bucket")?

**Comment by bobypierre** [comment]
😂 OK...I understand... 😕 😣 thank you very much ☺
