### ISSUE TITLE
wifi communications keeps being dropped after a 1-2 minutes

### ISSUE THREAD

**Issue by ghost** [raspberrypi/linux#294]
Hi,

Since kernel 3.8, the wifi connection gets dropped after 1-2 minutes and then no longer comes up until the next reboot.
This is with or without powered usb hub, trieed with a different rpi, tried with a different power supply and tried with a different type wifi stick.
In this dmesg output I tried it with a Atheros Communications, Inc. TP-Link TL-WN821N v2 802.11n [Atheros AR9170] stick:

[  107.232163] usb 1-1.3: received invalid command response:got 24, instead of 0
[  107.232358] carl9170 cmd:00000000: 08 01 00 00 04 40 1d 00 00 04 00 00              .....@......
[  107.232481] carl9170 rsp:00000000: 18 09 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
[  107.232541] carl9170 rsp:00000010: 00 00 00 00 00 00 00 00 2c 00 00 00              ........,...
[  107.232778] usb 1-1.3: restart device (9)
[  108.304067] IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready
[  109.303497] usb 1-1.3: kill pending tx urbs.
[  110.570095] usb 1-1.3: received invalid command response:got 4, instead of 0
[  110.570256] carl9170 cmd:00000000: 1c 21 00 00 e0 cd 24 00 00 11 19 22 03 00 00 00  .!....$...."....
[  110.570423] carl9170 cmd:00000010: e9 54 00 00 03 00 00 00 6b 4c 00 00 e8 03 00 00  .T......kL......
[  110.570486] carl9170 rsp:00000000: 04 21 01 00 03 00 00 00                          .!......
[  110.570876] ieee80211 phy0: wrong echo 4a110123 != d9eb9060
[  110.571062] usb 1-1.3: firmware upload failed (-22).
[  111.353638] usb 1-1.3: Failed to restart device (-22).
[  111.583813] usb 1-1.3: reset high-speed USB device number 5 using dwc_otg
[  112.823797] usb 1-1.3: reset high-speed USB device number 5 using dwc_otg
[  113.006101] usb 1-1.3: driver   API: 1.9.6 2012-07-07 [1-1]
[  113.006198] usb 1-1.3: firmware API: 1.9.7 2012-12-15
[  113.393645] ath: EEPROM regdomain: 0x809c
[  113.393765] ath: EEPROM indicates we should expect a country code
[  113.393811] ath: doing EEPROM country->regdmn map search
[  113.393847] ath: country maps to regdmn code: 0x52
[  113.393942] ath: Country alpha2 being used: CN
[  113.393979] ath: Regpair used: 0x52
[  113.396633] ieee80211 phy1: Selected rate control algorithm 'minstrel_ht'
[  113.448252] input: phy1 WPS Button as /devices/platform/bcm2708_usb/usb1/1-1/1-1.3/1-1.3:1.0/ieee80211/phy1/input3
[  113.474604] usb 1-1.3: Atheros AR9170 is registered as 'phy1'
[  114.142341] ieee80211 phy1: channel change: -1 -> 2412 failed (3).
[  114.298338] IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready
[  121.365729] IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready
[  123.738032] IPv6: ADDRCONF(NETDEV_UP): wlan0: link is not ready

Latest kernel tested with: 3.8.12

**Comment by P33M** [comment]
Fiq_fsm has improved wifi adapter stability in a large number of cases.

Please retest.
