### ISSUE TITLE
File gets blocked on a git push

### ISSUE THREAD

**Issue by Dark-Sky** [raspberrypi/linux#2945]
With the rpi-5.1.y branch in the .gitignore file "asterisk .dtb asterisk" prevents the scripts/Makefile.dtbinst file from getting pushed to a repo.

**Comment by lategoodbye** [comment]
Please report this issue to linux-kbuild@vger.kernel.org and the relevant maintainers.

**Comment by popcornmix** [comment]
Actually that is a downstream change.
@pelwell we have:
```
diff --git a/.gitignore b/.gitignore
index 97ba6b79834c..d99301c57cff 100644
--- a/.gitignore
+++ b/.gitignore
@@ -15,7 +15,7 @@
 *.bin
 *.bz2
 *.c.[012]*.*
-*.dtb
+*.dtb*
 *.dtb.S
```
I guess this is to ignore .dtbo files? Should we drop it or change to:
```
*.dtb
*.dtbo
```

**Comment by pelwell** [comment]
Adding `*.dtbo` explicitly is better.

**Comment by popcornmix** [comment]
Added to 4.19, 5.0 and 5.1 trees.
@Dark-Sky does this solve your issue?

**Comment by Dark-Sky** [comment]
It looks good to me. I had temporarily done this here because I have seen in the past some .dtb's with an suffix extension for boards with different revisions and did not remember if that was true for .dtbo's also and you could have had that in mind for the future:

!scripts/Makefile.dtbinst

Thanks!
