### ISSUE TITLE
vcgencmd fails with dmesg showing vchiq: vchiq: could not connect: 1

### ISSUE THREAD

**Issue by zerxy** [raspberrypi/linux#295]
Used rpi-update to update to kernel 3.6.11+ #446 on 256 MB Raspberry Pi with 240/16 memory split.  Getting `vchiq: vchiq: could not connect: 1` error in dmesg when trying to use vcgencmd

**Comment by popcornmix** [comment]
Can you try an rpi-update now?
Seems the start_cd.elf had grown too big and needed pruning. I've updated it.

**Comment by zerxy** [comment]
Used rpi-update and vcgencmd now works.
