### ISSUE TITLE
SPI Bus: Driver(s) not showing-up in /dev

### ISSUE THREAD

**Issue by Moisesbr** [raspberrypi/linux#296]
Please,

Is possible enable the user space driver support, as described in the "userspace driver" SPI support in kernel config, several projects use MCP3008 (analog IC) which is SPI.

Best Regards
Moisés

**Comment by popcornmix** [comment]
We've had this enabled for some time. Is this the option you meant?

```
CONFIG_SPI_SPIDEV:

This supports user mode SPI protocol drivers.

Note that this application programming interface is EXPERIMENTAL
and hence SUBJECT TO CHANGE WITHOUT NOTICE while it stabilizes.

Symbol: SPI_SPIDEV [=m]
```

**Comment by Moisesbr** [comment]
Yes that is right, in older version of kernel 3.6 on Raspian I uncommented out the blacklist entries for spi from /etc/modprobe.d/raspi-blacklist.conf i.e.

blacklist spi-bcm2708

The SPI driver exposes two device files (/dev/spidev-0.0 and /dev/spidev-0.1), one for each cable select line (CE0 and CE1 on RPi). Look in the /usr/include/linux/spi/spidev.h header for how to drive this properly. There are also Python bindings available and I’m sure there are others available for other languages too.

So, This option is very important for electronic interface, include the module is welcome.

Best Regards
Moisés Marangoni

**Comment by ghost** [comment]
+1 re: SPI

In addition, the same thing applies to I2C and 1-Wire: these protocols are also required for communication with countless sensors.

Best regards,
-Fabien.

**Comment by popcornmix** [comment]
If you want any config options added, please specify the names of the options and check if they are missing. E.g:

```
$ zcat /proc/config.gz |grep CONFIG_SPI_SPIDEV
CONFIG_SPI_SPIDEV=m
```

**Comment by popcornmix** [comment]
SPIDEV is present.
A bug with /dev/spi\* has been fixed: https://github.com/raspberrypi/linux/issues/425

Closing - reopen if there is still an issue.

**Comment by Moisesbr** [comment]
Agradeça ao Popcornmix por compilar os novo kernel da raspberry com o
SPIDEV.

2013/11/15 popcornmix notifications@github.com

**Comment by mschorer** [comment]
works for me!

thx
