### ISSUE TITLE
kernel panic when usb disk device is disconnected

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [raspberrypi/linux#2973]
**Describe the bug**

kernel panic when usb disk device is disconnected

**To reproduce**

1. install octoprint
https://octoprint.org/download/

2. connect marlin printer
https://github.com/MarlinFirmware/Marlin

3. perform steps:
* send M21 to expose printer SD card to rpi host
* mount SD card as usb disk on rpi host
* send M997 to reset printer

4. the above results in: 
* usb disk abruptly disappears from the rpi host (expected)
* rpi host crashes 1 time out of 5 (not expected)

**Expected behaviour**

anything but panic

**Actual behaviour**

system crash via kernel panic

**System**

* Which model of Raspberry Pi? e.g. Pi3B+, PiZeroW
```    
product: Raspberry Pi 3 Model B Plus Rev 1.3
```
* Which OS and version (`cat /etc/rpi-issue`)?
```
Raspberry Pi reference 2018-11-13
Generated using pi-gen, https://github.com/RPi-Distro/pi-gen, 7e0c786c641ba15990b5662f092c106beed40c9f, stage2
```
* Which firmware version (`vcgencmd version`)?
```
Mar 27 2019 15:45:53 
Copyright (c) 2012 Broadcom
version 2e98b31d18547962e564bdf88e57b3df7085c29b (clean) (release) (start)
```

* Which kernel version (`uname -a`)?
```
Linux octopi2 4.14.98-v7+ #1200 SMP Tue Feb 12 20:27:48 GMT 2019 armv7l GNU/Linux
```
**Logs**
[lshw.log](https://github.com/raspberrypi/linux/files/3179512/lshw.log)
[kernel-panic.log](https://github.com/raspberrypi/linux/files/3179491/kernel-panic.log)

**Comment by JamesH65** [comment]
This is an Octoprint issue, not Raspbian (unless you get the same fault of Raspbian?) so needs to be reported to Octoprint.
