### ISSUE TITLE
Bluetooth dongle only works on usb 1.0 ...

### ISSUE THREAD

**Issue by Mikerasp** [raspberrypi/linux#299]
Hi all,

I am having a hard time getting my bluetooth dongle (Broadcom chipset) to work ...

A CLEAN RASPBMC INSTALL (kernel 3.6.11) generates following results:

<pre><code>
pi@raspbmc:~$ lsusb
Bus 001 Device 002: ID 0424:9512 Standard Microsystems Corp. 
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 001 Device 003: ID 0424:ec00 Standard Microsystems Corp. 
Bus 001 Device 004: ID 059f:1028 LaCie, Ltd 
Bus 001 Device 005: ID 0a5c:4500 Broadcom Corp. BCM2046B1 USB 2.0 Hub (part of BCM2046 Bluetooth)
Bus 001 Device 006: ID 0a5c:4502 Broadcom Corp. Keyboard (Boot Interface Subclass)
Bus 001 Device 007: ID 0a5c:4503 Broadcom Corp. Mouse (Boot Interface Subclass)
Bus 001 Device 008: ID 0a5c:2146 Broadcom Corp.

pi@raspbmc:~$ hcitool dev
Devices:

pi@raspbmc:~$ hciconfig
hci0:   Type: BR/EDR  Bus: USB
    BD Address: 00:02:72:16:67:21  ACL MTU: 1021:8  SCO MTU: 64:1
    DOWN 
    RX bytes:346 acl:0 sco:0 events:8 errors:0
    TX bytes:57 acl:0 sco:0 commands:13 errors:0

pi@raspbmc:~$ sudo hciconfig hci0 up
Can't init device hci0: Connection timed out (110)
</code></pre>

But now the interesting thing is ...
On usb 1.0 speeds (by adding dwc_otg.speed=1 in my cmdline.txt. this thread https://github.com/raspberrypi/linux/issues/66#issuecomment-8099236 is a very interesting one concerning this problem) the bluetooth behavior is totally normal, so i know there is nothing wrong with the hardware.
The usb-downgrading method seemed like the perfect solution, although in one way or another, the lowered usb speeds cause 720p and up video to be choppy (streamed over network, my raspbmc installed on a SD-card).

When searching Internet it seems like a lot of people are having bluetooth/ usb related problems ...

Hoping someone could help me out with this ... (I've already done lots of research but I'm not confident enough to solve it myself ... although i would like to cooperate by doing some tests ...)

thx,

M.

**Comment by ghollingworth** [comment]
Have you tried the fiq_split branch?

> sudo BRANCH=fiq_split rpi-update

Gordon

## 

Director of Engineering, Raspberry Pi (Trading) Limited
T: +44 (0) 1223 322633
M: +44 (0) 7450 946289
E: gordon@raspberrypi.org
W: www.raspberrypi.org

**Comment by Mikerasp** [comment]
Unfortunately Raspbmc doesn't support these commands (firmware updates are managed by raspbmc) ... http://forum.stmlabs.com/showthread.php?tid=3579

**Comment by hadjedjvincent** [comment]
Hi Mike,

You can still do it if you have the latest version of raspbmc.

rpi-update will do the job.

I've tried it already on raspbmc already, it does work.

Regards

**Comment by P33M** [comment]
Latest kernel has fiq_fsm which fixes this issue.
