### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by deeptuuk** [raspberrypi/linux#2994]
I want to build the rtl8821CU driver,but i recive an error ,show as below:

make ARCH=arm64 CROSS_COMPILE= -C /lib/modules/4.19.46-v7+/build M=/home/k/Downloads/rtl8821CU  modules
make[1]: *** /lib/modules/4.19.46-v7+/build: No such file or directory.  Stop.
Makefile:1923: recipe for target 'modules' failed
make: *** [modules] Error 2

here is my uname -r:
4.19.46-v7+

my device is raspberry 3b,and i use the ubuntu mate 16.04

I want to find the build file,
I try apt install raspberrypi-kernel-headers , but it's still not work right.

I am really appreciate you to help me solve the problem.
thanks

**Comment by mati75** [comment]
Why you build for arm64?

**Comment by JamesH65** [comment]
This sort of question should be asked on the forums. www.raspberrypi.org/forums.
