### ISSUE TITLE
smsc95xx patch unnecessary

### ISSUE THREAD

**Issue by Alan-Cox** [raspberrypi/linux#3]
The Linux kernel supports setting the hardware address by ioctl

ifconfig eth0 down
ifconfig eth0 hw aa:bb:cc:dd:ee:ff
ifconfig eth0 up

So this patch can be dropped and has no chance of going upstream

**Comment by popcornmix** [comment]
OTP bits are connected to the GPU. The ARM currently can't see the OTP bits.
The serial number is stored in the OTP bits. The MAC adress is the OUI + serial number.

The command line is a convenient way of passing information from GPU to ARM.

I agree this is better done from userspace. 

I'll try and get an ARM driver in that exposes the serial/OTP bits, so this is no longer necessary in smsc95xx driver.

**Comment by asb** [comment]
Alan: how about having smsc95xx use system_serial_low and system_serial_high to generate the MAC?

**Comment by huceke** [comment]
Setting the mac adress makes perfect sense. Take the szenario where you have a nfs root without an initial ramdisk.

**Comment by Alan-Cox** [comment]
huceke: so use an initrd (you need to anyway in reality to do the dhcp and the like properly given the usb ethernet will appear at some point during the boot as its asynchronously discovered

asb: if the bits are exposed so the kernel can get at them that sounds ideal - the driver can then just pick them up if its a PI (or better yet if the device usb id is unique to the PI). The problem though if you don't have a unique id is you need to be careful of the case where someone plugs the same device on a dongle into a PI..

**Comment by Alan-Cox** [comment]
(as a PS - the mac= is broken for this case too...)

**Comment by nomis** [comment]
The information for the device is almost completely blank:

```
Bus 001 Device 003: ID 0424:ec00 Standard Microsystems Corp. 
Device Descriptor:
  bLength                18
  bDescriptorType         1
  bcdUSB               2.00
  bDeviceClass          255 Vendor Specific Class
  bDeviceSubClass         0 
  bDeviceProtocol         1 
  bMaxPacketSize0        64
  idVendor           0x0424 Standard Microsystems Corp.
  idProduct          0xec00 
  bcdDevice            2.00
  iManufacturer           0 
  iProduct                0 
  iSerial                 0 
  bNumConfigurations      1
  Configuration Descriptor:
    bLength                 9
    bDescriptorType         2
    wTotalLength           39
    bNumInterfaces          1
    bConfigurationValue     1
    iConfiguration          0 
    bmAttributes         0xe0
      Self Powered
      Remote Wakeup
    MaxPower                2mA
    Interface Descriptor:
      bLength                 9
      bDescriptorType         4
      bInterfaceNumber        0
      bAlternateSetting       0
      bNumEndpoints           3
      bInterfaceClass       255 Vendor Specific Class
      bInterfaceSubClass      0 
      bInterfaceProtocol    255 
      iInterface              0 
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x81  EP 1 IN
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0200  1x 512 bytes
        bInterval               0
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x02  EP 2 OUT
        bmAttributes            2
          Transfer Type            Bulk
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0200  1x 512 bytes
        bInterval               0
      Endpoint Descriptor:
        bLength                 7
        bDescriptorType         5
        bEndpointAddress     0x83  EP 3 IN
        bmAttributes            3
          Transfer Type            Interrupt
          Synch Type               None
          Usage Type               Data
        wMaxPacketSize     0x0010  1x 16 bytes
        bInterval               4
Device Qualifier (for other device speed):
  bLength                10
  bDescriptorType         6
  bcdUSB               2.00
  bDeviceClass          255 Vendor Specific Class
  bDeviceSubClass         0 
  bDeviceProtocol         1 
  bMaxPacketSize0        64
  bNumConfigurations      1
Device Status:     0x0001
  Self Powered
```

If some part of it could be filled in with something unique to the model (e.g. idVendor/idProduct or "Raspberry Pi" in the iProduct) then the driver could safely use the system serial to calculate the MAC.

**Comment by jsarenik** [comment]
```
#3 testing if pre-formatted text makes a link to issue
```

**Comment by jsarenik** [comment]
@popcornmix @davet321 @ollllivier @giraldeau @ffeldbauer @syntheticpp and others...

Please see https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code and use quotes to mark everything (at least what could contain `#3`) - i.e. three back-ticks on a line by themselves before and after the quoted text.

I understand this is an extra effort when the console output is just pasted. On the other hand it allows some processing (which GitHub does in order to cross-reference issues for example).
