### ISSUE TITLE
unplugging usb remote caused kernel oops and system freeze

### ISSUE THREAD

**Issue by s7mx1** [raspberrypi/linux#30]
Was using (lirc) usb remote with my pi. Everything works fine but it will kernel opps if I
1) unplug the usb remote when there is a lirc client connected
2) any lirc client  disconnects from lircd

If I unload the relevant kernel module first however the kernel oops does not happen. When kernel oops does happen the screen, network and everything seems to freeze and the serial console (tail -f /var/log/kernel.log) was flooded was error messages and I was not able to exit the tail by holding ctrl+c. I had to power cycle it get it back.  

Here is the kernel.log message when I unplugged the usb remote

http://db.tt/11UZWZJW

kernel messages when I stop lircd with active lirc client

http://db.tt/V26UHG2e

kernel messages when lirc client disconnects from lircd
http://db.tt/PNR9P1Jy

**Comment by popcornmix** [comment]
Are you running with latest kernel? (e.g. by using Hexxeh's firmware updater)

**Comment by s7mx1** [comment]
I am using a fairly rent kernel and firmware (1 or 2  days old)

**Comment by guisacouto** [comment]
This is an old issue. If you test it with other linux system it's likely it will also happen.. it's not rpi related, my guess is that it's mceusb module fault

**Comment by s7mx1** [comment]
Just built the latest kernel from source and looks like this dwc_otg patch fixed the issue for me.
https://github.com/raspberrypi/linux/commit/68b4a993dc006f80b7d19e461fcecd8191c5b9a3

**Comment by s7mx1** [comment]
I am happy to report that two of my remotes (xbox1 dvd remote and one MCE remote) no longer causing the system to freeze when I unplug them. This is with the kernel built from latest git tree.
