### ISSUE TITLE
Future Reguest

### ISSUE THREAD

**Issue by symbios24** [raspberrypi/linux#3008]
Hello

Is it possible to add to a future update the network manager from normal ubuntu eg ubuntu mate
at it is more detailed,or to tell me how to install it on raspbian stretch

thanks

**Comment by XECDesign** [comment]
This isn't a linux kernel issue, but to address it anyway, there are no plans to switch to NetworkManager. 

If you would like help switching it over, I'd recommend the forum:
https://www.raspberrypi.org/forums/index.php
