### ISSUE TITLE
Kernel 4.19.42+ dtoverlay=i2c-rtc,ds1307 not working

### ISSUE THREAD

**Issue by gsnw** [raspberrypi/linux#3013]
**Describe the bug**
config.txt Parameter dtoverlay=i2c-rtc,ds1307=on stopped working after Kernel 4.19.42+ Update

**To reproduce**
Add config.txt Parameter dtoverlay=i2c-rtc,ds1307 or dtoverlay=i2c-rtc,ds1307=on
Reboot and update Kernel from 4.14.98+ to 4.19.42+

**Expected behaviour**
_Kernel 4.14.98+ Output:_
kernel: [   18.758598] rtc-ds1307 1-0068: registered as rtc0

**Actual behaviour**
The system does not generate an RTC device with DS1307 connected.

**System**

* Which model of Raspberry Pi? e.g. Pi3B+, PiZeroW
  - Raspberry Pi 1 B+
  - Raspberry Pi 3 B+

* Which OS and version (`cat /etc/rpi-issue`)?
Raspberry Pi reference 2018-04-18
Generated using pi-gen, https://github.com/RPi-Distro/pi-gen, d6c238c1b2b1b070a574d3e25048ca442e3e221f, stage2

* Which firmware version (`vcgencmd version`)?
Mar 27 2019 15:46:32 
Copyright (c) 2012 Broadcom
version 2e98b31d18547962e564bdf88e57b3df7085c29b (clean) (release) (start_cd)

* Which kernel version (`uname -a`)?
Linux test 4.19.42+ #1219 Tue May 14 21:16:38 BST 2019 armv6l GNU/Linux

**Logs**
[    0.000000] Booting Linux on physical CPU 0x0
[    0.000000] Linux version 4.19.42+ (dom@dom-XPS-13-9370) (gcc version 4.9.3 (crosstool-NG crosstool-ng-1.22.0-88-g8460611)) #1219 Tue May 14 21:16:38 BST 2019
[    0.000000] CPU: ARMv6-compatible processor [410fb767] revision 7 (ARMv7), cr=00c5387d
[    0.000000] CPU: PIPT / VIPT nonaliasing data cache, VIPT nonaliasing instruction cache
[    0.000000] OF: fdt: Machine model: Raspberry Pi Model B Rev 2
[    0.000000] Memory policy: Data cache writeback
[    0.000000] cma: Reserved 8 MiB at 0x1e400000
[    0.000000] On node 0 totalpages: 126976
[    0.000000]   Normal zone: 1116 pages used for memmap
[    0.000000]   Normal zone: 0 pages reserved
[    0.000000]   Normal zone: 126976 pages, LIFO batch:31
[    0.000000] random: get_random_bytes called from start_kernel+0x8c/0x49c with crng_init=0
[    0.000000] pcpu-alloc: s0 r0 d32768 u32768 alloc=1*32768
[    0.000000] pcpu-alloc: [0] 0 
[    0.000000] Built 1 zonelists, mobility grouping on.  Total pages: 125860
[    0.000000] Kernel command line: coherent_pool=1M bcm2708_fb.fbwidth=656 bcm2708_fb.fbheight=416 bcm2708_fb.fbdepth=16 bcm2708_fb.fbswap=1 vc_mem.mem_base=0x1fa00000 vc_mem.mem_size=0x20000000  dwc_otg.lpm_enable=0 console=tty1 root=PARTUUID=9f2d13a6-3a9c-49a1-af84-f7bf3f200d7e rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait rootdelay=5 net.ifnames=0
[    0.000000] Dentry cache hash table entries: 65536 (order: 6, 262144 bytes)
[    0.000000] Inode-cache hash table entries: 32768 (order: 5, 131072 bytes)
[    0.000000] Memory: 483208K/507904K available (6932K kernel code, 633K rwdata, 2068K rodata, 456K init, 797K bss, 16504K reserved, 8192K cma-reserved)
[    0.000000] Virtual kernel memory layout:
                   vector  : 0xffff0000 - 0xffff1000   (   4 kB)
                   fixmap  : 0xffc00000 - 0xfff00000   (3072 kB)
                   vmalloc : 0xdf800000 - 0xff800000   ( 512 MB)
                   lowmem  : 0xc0000000 - 0xdf000000   ( 496 MB)
                   modules : 0xbf000000 - 0xc0000000   (  16 MB)
                     .text : 0x(ptrval) - 0x(ptrval)   (6934 kB)
                     .init : 0x(ptrval) - 0x(ptrval)   ( 456 kB)
                     .data : 0x(ptrval) - 0x(ptrval)   ( 634 kB)
                      .bss : 0x(ptrval) - 0x(ptrval)   ( 798 kB)
[    0.000000] SLUB: HWalign=32, Order=0-3, MinObjects=0, CPUs=1, Nodes=1
[    0.000000] ftrace: allocating 25044 entries in 74 pages
[    0.000000] NR_IRQS: 16, nr_irqs: 16, preallocated irqs: 16
[    0.000028] sched_clock: 32 bits at 1000kHz, resolution 1000ns, wraps every 2147483647500ns
[    0.000084] clocksource: timer: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 1911260446275 ns
[    0.000192] bcm2835: system timer (irq = 27)
[    0.000792] Console: colour dummy device 80x30
[    0.001429] console [tty1] enabled
[    0.001511] Calibrating delay loop... 697.95 BogoMIPS (lpj=3489792)
[    0.060372] pid_max: default: 32768 minimum: 301
[    0.060964] Mount-cache hash table entries: 1024 (order: 0, 4096 bytes)
[    0.061023] Mountpoint-cache hash table entries: 1024 (order: 0, 4096 bytes)
[    0.062505] CPU: Testing write buffer coherency: ok
[    0.063891] Setting up static identity map for 0x8200 - 0x8238
[    0.065358] devtmpfs: initialized
[    0.076232] VFP support v0.3: implementor 41 architecture 1 part 20 variant b rev 5
[    0.076718] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 19112604462750000 ns
[    0.076795] futex hash table entries: 256 (order: -1, 3072 bytes)
[    0.078182] pinctrl core: initialized pinctrl subsystem
[    0.079790] NET: Registered protocol family 16
[    0.083135] DMA: preallocated 1024 KiB pool for atomic coherent allocations
[    0.090337] hw-breakpoint: found 6 breakpoint and 1 watchpoint registers.
[    0.090414] hw-breakpoint: maximum watchpoint size is 4 bytes.
[    0.090744] Serial: AMBA PL011 UART driver
[    0.094289] bcm2835-mbox 2000b880.mailbox: mailbox enabled
[    0.137444] bcm2835-dma 20007000.dma: DMA legacy API manager at (ptrval), dmachans=0x1
[    0.140022] SCSI subsystem initialized
[    0.140359] usbcore: registered new interface driver usbfs
[    0.140505] usbcore: registered new interface driver hub
[    0.140864] usbcore: registered new device driver usb
[    0.160954] raspberrypi-firmware soc:firmware: Attached to firmware from 2019-03-27 15:46, variant start_cd
[    0.170983] raspberrypi-firmware soc:firmware: Firmware hash is 2e98b31d18547962e564bdf88e57b3df7085c29b
[    0.183397] clocksource: Switched to clocksource timer
[    0.284679] VFS: Disk quotas dquot_6.6.0
[    0.284866] VFS: Dquot-cache hash table entries: 1024 (order 0, 4096 bytes)
[    0.285234] FS-Cache: Loaded
[    0.285611] CacheFiles: Loaded
[    0.304505] NET: Registered protocol family 2
[    0.305910] tcp_listen_portaddr_hash hash table entries: 512 (order: 0, 4096 bytes)
[    0.306033] TCP established hash table entries: 4096 (order: 2, 16384 bytes)
[    0.306144] TCP bind hash table entries: 4096 (order: 2, 16384 bytes)
[    0.306263] TCP: Hash tables configured (established 4096 bind 4096)
[    0.306467] UDP hash table entries: 256 (order: 0, 4096 bytes)
[    0.306532] UDP-Lite hash table entries: 256 (order: 0, 4096 bytes)
[    0.306982] NET: Registered protocol family 1
[    0.308156] RPC: Registered named UNIX socket transport module.
[    0.308222] RPC: Registered udp transport module.
[    0.308250] RPC: Registered tcp transport module.
[    0.308276] RPC: Registered tcp NFSv4.1 backchannel transport module.
[    0.310438] hw perfevents: no irqs for PMU, sampling events not supported
[    0.310565] hw perfevents: enabled with armv6_1176 PMU driver, 3 counters available
[    0.314699] Initialise system trusted keyrings
[    0.315160] workingset: timestamp_bits=14 max_order=17 bucket_order=3
[    0.330005] FS-Cache: Netfs 'nfs' registered for caching
[    0.331373] NFS: Registering the id_resolver key type
[    0.331471] Key type id_resolver registered
[    0.331506] Key type id_legacy registered
[    0.331556] nfs4filelayout_init: NFSv4 File Layout Driver Registering...
[    0.337367] Key type asymmetric registered
[    0.337437] Asymmetric key parser 'x509' registered
[    0.337573] Block layer SCSI generic (bsg) driver version 0.4 loaded (major 250)
[    0.338087] io scheduler noop registered
[    0.338142] io scheduler deadline registered (default)
[    0.338785] io scheduler cfq registered
[    0.338839] io scheduler mq-deadline registered (default)
[    0.338873] io scheduler kyber registered
[    0.342091] BCM2708FB: allocated DMA memory 0x5e500000
[    0.342207] BCM2708FB: allocated DMA channel 0
[    0.347681] Console: switching to colour frame buffer device 82x26
[    0.355888] bcm2835-rng 20104000.rng: hwrng registered
[    0.357829] vc-mem: phys_addr:0x00000000 mem_base=0x1fa00000 mem_size:0x20000000(512 MiB)
[    0.362118] vc-sm: Videocore shared memory driver
[    0.364742] gpiomem-bcm2835 20200000.gpiomem: Initialised: Registers at 0x20200000
[    0.388641] brd: module loaded
[    0.403777] loop: module loaded
[    0.405521] Loading iSCSI transport class v2.0-870.
[    0.408134] usbcore: registered new interface driver smsc95xx
[    0.409861] dwc_otg: version 3.00a 10-AUG-2012 (platform bus)
[    0.439519] dwc_otg 20980000.usb: base=(ptrval)
[    0.641570] Core Release: 2.80a
[    0.643183] Setting default values for core params
[    0.644870] Finished setting default values for core params
[    0.846933] Using Buffer DMA mode
[    0.848604] Periodic Transfer Interrupt Enhancement - disabled
[    0.850265] Multiprocessor Interrupt Enhancement - disabled
[    0.851932] OTG VER PARAM: 0, OTG VER FLAG: 0
[    0.853738] Dedicated Tx FIFOs mode
[    0.856327] WARN::dwc_otg_hcd_init:1045: FIQ DMA bounce buffers: virt = de514000 dma = 0x5e514000 len=9024
[    0.859761] FIQ FSM acceleration enabled for :
               Non-periodic Split Transactions
               Periodic Split Transactions
               High-Speed Isochronous Endpoints
               Interrupt/Control Split Transaction hack enabled
[    0.867586] dwc_otg: Microframe scheduler enabled
[    0.867842] WARN::hcd_init_fiq:457: FIQ on core 0
[    0.869487] WARN::hcd_init_fiq:458: FIQ ASM at c04f48a0 length 36
[    0.871089] WARN::hcd_init_fiq:484: MPHI regs_base at f0006000
[    0.872746] dwc_otg 20980000.usb: DWC OTG Controller
[    0.874487] dwc_otg 20980000.usb: new USB bus registered, assigned bus number 1
[    0.876184] dwc_otg 20980000.usb: irq 56, io mem 0x00000000
[    0.877815] Init: Port Power? op_state=1
[    0.879377] Init: Power Port (0)
[    0.881306] usb usb1: New USB device found, idVendor=1d6b, idProduct=0002, bcdDevice= 4.19
[    0.884526] usb usb1: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[    0.886226] usb usb1: Product: DWC OTG Controller
[    0.887868] usb usb1: Manufacturer: Linux 4.19.42+ dwc_otg_hcd
[    0.889539] usb usb1: SerialNumber: 20980000.usb
[    0.892321] hub 1-0:1.0: USB hub found
[    0.894142] hub 1-0:1.0: 1 port detected
[    0.896794] dwc_otg: FIQ enabled
[    0.896807] dwc_otg: NAK holdoff enabled
[    0.896814] dwc_otg: FIQ split-transaction FSM enabled
[    0.896834] Module dwc_common_port init
[    0.897387] usbcore: registered new interface driver usb-storage
[    0.899537] mousedev: PS/2 mouse device common for all mice
[    0.902650] bcm2835-wdt 20100000.watchdog: Broadcom BCM2835 watchdog timer
[    0.905086] bcm2835-cpufreq: min=700000 max=700000
[    0.907540] sdhci: Secure Digital Host Controller Interface driver
[    0.909277] sdhci: Copyright(c) Pierre Ossman
[    0.911608] sdhost-bcm2835 20202000.mmc: could not get clk, deferring probe
[    0.913738] sdhci-pltfm: SDHCI platform and OF driver helper
[    0.916164] ledtrig-cpu: registered to indicate activity on CPUs
[    0.918117] hidraw: raw HID events driver (C) Jiri Kosina
[    0.920144] usbcore: registered new interface driver usbhid
[    0.921915] usbhid: USB HID core driver
[    0.924877] vchiq: vchiq_init_state: slot_zero = (ptrval), is_master = 0
[    0.928794] [vc_sm_connected_init]: start
[    0.932923] vc_vchi_sm_init: failed to open VCHI service (-1)
[    0.932946] [vc_sm_connected_init]: failed to initialize shared memory service
[    0.936627] [vc_sm_connected_init]: end - returning -1
[    0.940194] Initializing XFRM netlink socket
[    0.942075] NET: Registered protocol family 17
[    0.944056] Key type dns_resolver registered
[    0.947676] registered taskstats version 1
[    0.949480] Loading compiled-in X.509 certificates
[    0.961244] uart-pl011 20201000.serial: cts_event_workaround enabled
[    0.963205] 20201000.serial: ttyAMA0 at MMIO 0x20201000 (irq = 81, base_baud = 0) is a PL011 rev2
[    0.969973] sdhost: log_buf @ (ptrval) (5e513000)
[    1.019283] mmc0: sdhost-bcm2835 loaded - DMA enabled (>1)
[    1.022691] of_cfs_init
[    1.044924] of_cfs_init: OK
[    1.047425] Waiting 5 sec before mounting root device...
[    1.060194] random: fast init done
[    1.113662] Indeed it is in host mode hprt0 = 00021501
[    1.180448] mmc0: host does not support reading read-only switch, assuming write-enable
[    1.187475] mmc0: new high speed SDHC card at address e624
[    1.191219] mmcblk0: mmc0:e624 ADLCD 29.7 GiB
[    1.197229]  mmcblk0: p1 p2
[    1.323474] usb 1-1: new high-speed USB device number 2 using dwc_otg
[    1.325541] Indeed it is in host mode hprt0 = 00001101
[    1.563912] usb 1-1: New USB device found, idVendor=0424, idProduct=9512, bcdDevice= 2.00
[    1.567546] usb 1-1: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[    1.570773] hub 1-1:1.0: USB hub found
[    1.572924] hub 1-1:1.0: 3 ports detected
[    1.893494] usb 1-1.1: new high-speed USB device number 3 using dwc_otg
[    2.023902] usb 1-1.1: New USB device found, idVendor=0424, idProduct=ec00, bcdDevice= 2.00
[    2.027556] usb 1-1.1: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[    2.032657] smsc95xx v1.0.6
[    2.128951] smsc95xx 1-1.1:1.0 eth0: register 'smsc95xx' at usb-20980000.usb-1.1, smsc95xx USB 2.0 Ethernet, b8:27:eb:86:40:ea
[    2.233510] usb 1-1.3: new high-speed USB device number 4 using dwc_otg
[    2.364935] usb 1-1.3: New USB device found, idVendor=152d, idProduct=1561, bcdDevice= 2.04
[    2.369035] usb 1-1.3: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[    2.371130] usb 1-1.3: Product: SABRENT
[    2.373185] usb 1-1.3: Manufacturer: SABRENT
[    2.375318] usb 1-1.3: SerialNumber: DB9876543214E
[    2.378566] usb 1-1.3: The driver for the USB controller dwc_otg_hcd does not support scatter-gather which is
[    2.382653] usb 1-1.3: required by the UAS driver. Please try an other USB controller if you wish to use UAS.
[    2.386752] usb-storage 1-1.3:1.0: USB Mass Storage device detected
[    2.390018] scsi host0: usb-storage 1-1.3:1.0
[    3.444586] scsi 0:0:0:0: Direct-Access     SABRENT                   0204 PQ: 0 ANSI: 6
[    3.450397] sd 0:0:0:0: [sda] 234455040 512-byte logical blocks: (120 GB/112 GiB)
[    3.456309] sd 0:0:0:0: [sda] Write Protect is off
[    3.458474] sd 0:0:0:0: [sda] Mode Sense: 47 00 00 08
[    3.459653] sd 0:0:0:0: [sda] Write cache: enabled, read cache: enabled, doesn't support DPO or FUA
[    3.483659]  sda: sda1 sda2 sda3 sda4 sda5
[    3.491086] sd 0:0:0:0: [sda] Attached SCSI disk
[    6.099561] EXT4-fs (sda1): mounted filesystem with ordered data mode. Opts: (null)
[    6.103910] VFS: Mounted root (ext4 filesystem) readonly on device 8:1.
[    6.114489] devtmpfs: mounted
[    6.121129] Freeing unused kernel memory: 456K
[    6.123235] This architecture does not have kernel memory protection.
[    6.125401] Run /sbin/init as init process
[    6.605133] systemd[1]: System time before build time, advancing clock.
[    6.752700] NET: Registered protocol family 10
[    6.757301] Segment Routing with IPv6
[    6.795686] random: systemd: uninitialized urandom read (16 bytes read)
[    6.808079] systemd[1]: systemd 232 running in system mode. (+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN)
[    6.815462] systemd[1]: Detected architecture arm.
[    6.835791] systemd[1]: Set hostname to <white-queen>.
[    6.904096] random: systemd: uninitialized urandom read (16 bytes read)
[    7.168942] random: systemd-cryptse: uninitialized urandom read (16 bytes read)
[    8.008231] systemd[1]: Listening on fsck to fsckd communication Socket.
[    8.014738] systemd[1]: Listening on udev Kernel Socket.
[    8.020426] systemd[1]: Started Forward Password Requests to Wall Directory Watch.
[    8.028172] systemd[1]: Listening on /dev/initctl Compatibility Named Pipe.
[    8.035112] systemd[1]: Created slice User and Session Slice.
[    8.041022] systemd[1]: Listening on Journal Socket (/dev/log).
[    8.046906] systemd[1]: Listening on Syslog Socket.
[    8.758548] i2c /dev entries driver
[    9.624857] random: crng init done
[    9.626461] random: 7 urandom warning(s) missed due to ratelimiting
[   11.176315] EXT4-fs (sda1): re-mounted. Opts: (null)
[   14.029213] vc_sm_cma: module is from the staging directory, the quality is unknown, you have been warned.
[   14.031371] bcm2835_vc_sm_cma_probe: Videocore shared memory driver
[   14.031396] [vc_sm_connected_init]: start
[   14.075116] vc_sm_cma_vchi_init: failed to open VCHI service (-1)
[   14.075144] [vc_sm_connected_init]: failed to initialize shared memory service
[   14.075153] [vc_sm_connected_init]: failed, ret -1
[   14.093122] media: Linux media interface: v0.10
[   14.293749] videodev: Linux video capture interface: v2.00
[   14.381450] bcm2835_mmal_vchiq: module is from the staging directory, the quality is unknown, you have been warned.
[   14.434458] bcm2835_v4l2: module is from the staging directory, the quality is unknown, you have been warned.
[   14.464346] bcm2835_mmal_vchiq: Failed to open VCHI service connection (status=-1)
[   14.466171] bcm2835_codec: module is from the staging directory, the quality is unknown, you have been warned.
[   14.508403] bcm2835_mmal_vchiq: Failed to open VCHI service connection (status=-1)
[   15.099433] snd_bcm2835: module is from the staging directory, the quality is unknown, you have been warned.
[   15.231496] bcm2835_audio soc:audio: card created with 8 channels
[   16.174082] usbcore: registered new interface driver uas
[   16.402426] sd 0:0:0:0: Attached scsi generic sg0 type 0
[   18.032326] Adding 2097148k swap on /dev/sda2.  Priority:-2 extents:1 across:2097148k FS
[   20.049698] EXT4-fs (sda4): mounted filesystem with ordered data mode. Opts: (null)
[   22.828628] EXT4-fs (sda5): mounted filesystem with ordered data mode. Opts: (null)
[   23.933770] EXT4-fs (sda3): mounted filesystem with ordered data mode. Opts: (null)
[   24.642814] systemd-journald[64]: Received request to flush runtime journal from PID 1
[   27.186132] cfg80211: Loading compiled-in X.509 certificates for regulatory database
[   27.465631] cfg80211: Loaded X.509 cert 'sforshee: 00b28ddf47aef9cea7'
[   28.124068] smsc95xx 1-1.1:1.0 eth0: hardware isn't capable of remote wakeup
[   29.728437] smsc95xx 1-1.1:1.0 eth0: link up, 100Mbps, full-duplex, lpa 0xC1E1
[   35.888742] uart-pl011 20201000.serial: no DMA platform data

**Additional context**

**Comment by pelwell** [comment]
The generation of module aliases for I2C devices changed in 4.19. Previously, I2C aliases (e.g. "i2c:ds1307") were generated for all I2C devices, even those declared in Device Tree (i.e. from an overlay), but as of 4.19 the compatible strings in Device Tree (e.g. "maxim,ds1307") are converted to OF module aliases (e.g. "of:N*T*Cmaxim,ds1307"). In most cases this change is harmless (or even beneficial), but it does mean that the compatible strings have to be correct. In the case of the ds1307 mode of the i2c-rtc overlay, the string is wrong - it should have been "dallas,ds1307". Only the newer DS3231 (the device I have...) has a "maxim" compatible string.

The correct fix is to update the overlay to include the correct compatible string, but that will take a while to propagate through the system to a Raspbian package update. In the meantime, adding `rtc-ds1307` to the end of `/etc/modules` (or perhaps using "dtoverlay=i2c-rtc,ds3231") should work around the problem.

**Comment by brabl2** [comment]
Adding `rtc-ds1307` to the `/etc/modules` works for me as a temporary fix.

**Comment by gsnw** [comment]
I believe the workaround with dtoverlay=i2c-rtc,ds3231 works, too.

```
[   21.116034] rtc-ds1307 1-0068: registered as rtc0
[   32.794637] rtc rtc0: __rtc_set_alarm: err=-22
```

A request with `hwclock -r` gives a clock response

**Comment by Trotter73** [comment]
Hi,

dtoverlay=i2c-sensor,lm75 also appears to be broken, I assume by the same mechanism, shall I raise a new issue for this ?

**Comment by pelwell** [comment]
Yes please - it makes tracking easier.

**Comment by gsnw** [comment]
@pelwell The issues can be closed from my side. Thanks for the correction and quick help

I have test the config.txt parameter with dtoverlay=i2c-rtc,ds1307 and it works with new raspbian buster and the default kernel 4.19.57+

`[   25.055118] rtc-ds1307 1-0068: registered as rtc0`

Which OS and version (cat /etc/rpi-issue)?
Raspberry Pi reference 2019-07-10
Generated using pi-gen, https://github.com/RPi-Distro/pi-gen, 175dfb027ffabd4b8d5080097af0e51ed9a4a56c, stage2

Which firmware version (vcgencmd version)?
Jul  9 2019 14:41:21 
Copyright (c) 2012 Broadcom
version 6c3fe3f096a93de3b34252ad98cdccadeb534be2 (clean) (release) (start_cd)

Which kernel version (uname -a)?
Linux test 4.19.57+ #1244 Thu Jul 4 18:42:50 BST 2019 armv6l GNU/Linux
