### ISSUE TITLE
rt2800_init_eeprom: Error - Invalid RF chipset 0x3070 detected.

### ISSUE THREAD

**Issue by ricsim** [raspberrypi/linux#303]
This WiFi Dongle is not supported out of box:
Bus 001 Device 004: ID 148f:3070 Ralink Technology, Corp. RT2870/RT3070 Wireless Adapter

It seems that it can be handeled as 5370:
http://www.geekamole.com/2013/rt2800usb-fix-for-ralinkmediatek-3070-gentoo-linux/

Would be great if that dongle would be supported out of the box, without compiling a new driver!

**Comment by Ruffio** [comment]
@ricsim has this issue been resolved? If yes, then please close this issue.

**Comment by Ruffio** [comment]
@popcornmix please consider to close this issue as it was initially raised in 2013 and there has been no response to my ping a month ago
