### ISSUE TITLE
Linksys AE3000 WiFi USB NIC Support

### ISSUE THREAD

**Issue by CrimsonKnight13** [raspberrypi/linux#306]
Would it be possible to have support for the Linksys AE3000 drivers & firmware? It has a Ralink RT3573 chip.

I have attempted to compile the provided drivers ( 20120911_RT3573_Linux_STA_v2.5.0.0_Rev1_DPO.tar.bz2 ) from Mediatek/Ralink but it complains about not being able to access the build file within the kernel headers.

I appreciate any insight. Thanks!

**Comment by popcornmix** [comment]
Sorry, the policy is not to pull in out-of-tree drivers without a compelling reason.
You can lobby for it to get included in the upstream linux kernel, and in time the Pi will get this.

**Comment by CrimsonKnight13** [comment]
Does this apply to the standard kernel as well as the rpi-update kernels? How would one lobby to have it happen? Any pointers how to compile the drivers for the Pi if this is a dead end?

**Comment by popcornmix** [comment]
Have you read this:
http://elinux.org/RPi_Kernel_Compilation

It's probably simplest to build the kernel first, then add the extra module.

**Comment by CrimsonKnight13** [comment]
Thanks. I'll explore that option. I appreciate the help!
