### ISSUE TITLE
RTL8192 driver fails to build

### ISSUE THREAD

**Issue by UrsusArctos** [raspberrypi/linux#307]
CC      drivers/net/wireless/rtl8192cu/hal/hal_init.o
  CC      drivers/net/wireless/rtl8192cu/hal/rtl8192c/rtl8192c_hal_init.o
  CC      drivers/net/wireless/rtl8192cu/hal/rtl8192c/rtl8192c_phycfg.o
  CC      drivers/net/wireless/rtl8192cu/hal/rtl8192c/rtl8192c_rf6052.o
  CC      drivers/net/wireless/rtl8192cu/hal/rtl8192c/rtl8192c_dm.o
  CC      drivers/net/wireless/rtl8192cu/hal/rtl8192c/rtl8192c_rxdesc.o
  CC      drivers/net/wireless/rtl8192cu/hal/rtl8192c/rtl8192c_cmd.o
  CC      drivers/net/wireless/rtl8192cu/hal/rtl8192c/rtl8192c_mp.o
  CC      drivers/net/wireless/rtl8192cu/hal/rtl8192c/usb/usb_ops_linux.o
  CC      drivers/net/wireless/rtl8192cu/hal/rtl8192c/usb/usb_halinit.o
  CC      drivers/net/wireless/rtl8192cu/hal/rtl8192c/usb/rtl8192cu_led.o
  CC      drivers/net/wireless/rtl8192cu/hal/rtl8192c/usb/rtl8192cu_xmit.o
  CC      drivers/net/wireless/rtl8192cu/hal/rtl8192c/usb/rtl8192cu_recv.o
  CC      drivers/net/wireless/rtl8192cu/hal/rtl8192c/rtl8192c_sreset.o
  CC      drivers/net/wireless/rtl8192cu/hal/rtl8192c/usb/Hal8192CUHWImg.o
  CC      drivers/net/wireless/rtl8192cu/os_dep/osdep_service.o
  CC      drivers/net/wireless/rtl8192cu/os_dep/linux/os_intfs.o
drivers/net/wireless/rtl8192cu/os_dep/linux/os_intfs.c: In function ‘rtw_init_netdev’:
drivers/net/wireless/rtl8192cu/os_dep/linux/os_intfs.c:778:9: error: ‘struct net_device’ has no member named ‘wireless_handlers’
make[4]: **\* [drivers/net/wireless/rtl8192cu/os_dep/linux/os_intfs.o] Error 1
make[3]: **\* [drivers/net/wireless/rtl8192cu] Error 2
make[2]: **\* [drivers/net/wireless] Error 2
make[1]: **\* [drivers/net] Error 2
make: **\* [drivers] Error 2

Orbiter linux # grep -i 8192 .config
CONFIG_EXTRA_FIRMWARE="rtlwifi/rtl8192cufw.bin"
CONFIG_RTL8192CU=y

also my kernel config here http://pastebin.com/YcsreH9j

**Comment by popcornmix** [comment]
Sounds like you've not enabled 
CONFIG_WIRELESS_EXT=y

**Comment by UrsusArctos** [comment]
I haven't indeed.
But there's no easy way to enable it.
It is not on menuconfig as a trigger, and none of its dependencies (PS3, Raytheon and Cisco Aironet) are accessible.
Your advice on enabling this option will be greatly appreciated.

**Comment by popcornmix** [comment]
Can you try editing drivers/net/wireless/rtl8192cu/Kconfig and add "select WIRELESS_EXT". E.g.

```
config RTL8192CU
    tristate "Realtek 8192C USB WiFi"
    depends on USB
    select WIRELESS_EXT
    ---help---
      Help message of RTL8192CU
```

**Comment by UrsusArctos** [comment]
It helped but not much. The error is now in another file:

  CC      drivers/net/wireless/rtl8192cu/os_dep/osdep_service.o
  CC      drivers/net/wireless/rtl8192cu/os_dep/linux/os_intfs.o
  CC      drivers/net/wireless/rtl8192cu/os_dep/linux/usb_intf.o
  CC      drivers/net/wireless/rtl8192cu/os_dep/linux/ioctl_linux.o
drivers/net/wireless/rtl8192cu/os_dep/linux/ioctl_linux.c:9317:2: error: unknown field ‘private’ specified in initializer
drivers/net/wireless/rtl8192cu/os_dep/linux/ioctl_linux.c:9317:2: warning: initialization from incompatible pointer type [enabled by default]
drivers/net/wireless/rtl8192cu/os_dep/linux/ioctl_linux.c:9317:2: warning: (near initialization for ‘rtw_handlers_def.get_wireless_stats’) [enabled by default]
drivers/net/wireless/rtl8192cu/os_dep/linux/ioctl_linux.c:9318:2: error: unknown field ‘private_args’ specified in initializer
drivers/net/wireless/rtl8192cu/os_dep/linux/ioctl_linux.c:9318:26: warning: excess elements in struct initializer [enabled by default]
drivers/net/wireless/rtl8192cu/os_dep/linux/ioctl_linux.c:9318:26: warning: (near initialization for ‘rtw_handlers_def’) [enabled by default]
drivers/net/wireless/rtl8192cu/os_dep/linux/ioctl_linux.c:9319:2: error: unknown field ‘num_private’ specified in initializer
drivers/net/wireless/rtl8192cu/os_dep/linux/ioctl_linux.c:9319:2: warning: excess elements in struct initializer [enabled by default]
drivers/net/wireless/rtl8192cu/os_dep/linux/ioctl_linux.c:9319:2: warning: (near initialization for ‘rtw_handlers_def’) [enabled by default]
drivers/net/wireless/rtl8192cu/os_dep/linux/ioctl_linux.c:9320:3: error: unknown field ‘num_private_args’ specified in initializer
drivers/net/wireless/rtl8192cu/os_dep/linux/ioctl_linux.c:9320:64: warning: excess elements in struct initializer [enabled by default]
drivers/net/wireless/rtl8192cu/os_dep/linux/ioctl_linux.c:9320:64: warning: (near initialization for ‘rtw_handlers_def’) [enabled by default]
make[4]: **\* [drivers/net/wireless/rtl8192cu/os_dep/linux/ioctl_linux.o] Error 1
make[3]: **\* [drivers/net/wireless/rtl8192cu] Error 2
make[2]: **\* [drivers/net/wireless] Error 2
make[1]: **\* [drivers/net] Error 2
make: **\* [drivers] Error 2

**Comment by ghollingworth** [comment]
Which config are you using?

bcmrpi_defconfig already contains CONFIG_RTL8192CU=m and it builds fine...

Gordon

**Comment by UrsusArctos** [comment]
Being Gentoo user I don't like loadable modules and default configurations.
I always prefer to build custom kernels through menuconfig with the support for only that hardware and functions which is present on the target machine. bcmrpi_defconfig is messy and has a whole zoo of drivers I'll never use on my RPI.
But now at least I know where and how to dig.
Thanks for that :)

**Comment by UrsusArctos** [comment]
anyway, here's the patch http://pastebin.com/Ttzff7iV

**Comment by popcornmix** [comment]
Okay, added.

**Comment by UrsusArctos** [comment]
thanks, it works now

**Comment by thiagovespa** [comment]
Same problem on rpi-3.10.y branch
