### ISSUE TITLE
CMA hangs kernel early when booting

### ISSUE THREAD

**Issue by wrobelda** [raspberrypi/linux#308]
I have enabled CMA and noticed that about 8/10 boots it would hang the RPI during early phase when booting:

[    1.301514] io scheduler noop registered
[    1.305563] io scheduler deadline registered
[    1.309890] io scheduler cfq registered (default)
[    1.345174] Console: switching to colour frame buffer device 228x61
[    1.371584] kgdb: Registered I/O driver kgdboc.
[    1.376914] vc-cma: Videocore CMA driver
[    1.380960] vc-cma: vc_cma_base      = 0x0d400000
[    1.385830] vc-cma: vc_cma_size      = 0x11800000 (280 MiB)
[    1.391532] vc-cma: vc_cma_initial   = 0x00000000 (0 MiB)
[    1.406255] brd: module loaded
[    1.414592] loop: module loaded
[    1.418209] vchiq: vchiq_init_state: slot_zero = 0xcd400000, is_master = 0
[    1.426039] vchiq_get_state: g_state.remote->initialised != 1 (0)

I have no extra options defined in config.txt except for gpu_mem=128. 
cmdline is also standard with extra: coherent_pool=6M cma=2M smsc95xx.turbo_mode=N

Right upon disabling the cma, everything is back to normal. 

me@rpi ~ $ uname -a
Linux rpi 3.6.11+ #456 PREEMPT Mon May 20 17:42:15 BST 2013 armv6l GNU/Linux

me@rpi ~ $ /opt/vc/bin/vcgencmd version
May 26 2013 21:47:02 
Copyright (c) 2012 Broadcom
version 53261d4ede3ba2b660e4201aca9bd4544565a3ce (clean) (release)

**Comment by licaon-kter** [comment]
Do test without **coherent_pool=6M cma=2M** too since afaik is not needed as long as _config.txt_ has say:

> gpu_mem_256=112
> cma_lwm=16
> cma_hwm=32
> cma_offline_start=16

**Comment by wrobelda** [comment]
I tried - nothing's changed, same issue.

**Comment by wrobelda** [comment]
I also tried this on another PI board with same result.

**Comment by popcornmix** [comment]
From my point of view, CMA has never been completely reliable, so it not recommended, nor supported.
I'm hoping we'll some more kernel bug tracking manpower soon, and CMA is one of the things that would be good to get reliable (but it won't be top of the list...)

**Comment by licaon-kter** [comment]
WTH? 
I had Raspbian+custom 3.9.x for a while.
I reinstalled Raspbian+custom 3.9.x+prior packages and now CMA fails like @wrobelda said. 

/LE: adding **coherent_pool=6M** in _/boot/cmdline.txt_ fixed it, strangely it worked without it before.

@wrobelda: can you test like this too? ( just **coherent_pool=6M** added, but _not_ **cma=2M** and the _config.txt_ like I said above )

**Comment by wrobelda** [comment]
@licaon-kter  
I tried that today the way you described but it still failed in the same way as previously.

**Comment by programista-zacny** [comment]
I have the same issue. I tried everything desribed above.

**Comment by Ruffio** [comment]
@wrobelda has this issue been resolved? If yes, then please close this issue.

**Comment by Ruffio** [comment]
@popcornmix please consider closing this issue, as there has been merged a commit a year ago and no response to my ping a month ago has been performed
