### ISSUE TITLE
Unable to parse Prov_db.json file while accessing meshctl 

### ISSUE THREAD

**Issue by rahul30694** [raspberrypi/linux#3091]
Hi ,
I followed all steps of  https://3pl46c46ctx02p7rzdsvsg21-wpengine.netdna-ssl.com/wp-content/uploads/2019/03/T1804_How-to-set-up-BlueZ_LFC_FINAL-1.pdf?utm_campaign=developer&utm_source=internal&utm_medium=blog&utm_content=bluez-on-pi3
**Developer Study Guide: Deploying BlueZ v5.50 on Raspberry Pi3**

But I am facing an issue of **Unable to parse Prov_db.json file**, at very last stage , while writing command  meshctl from bluez/mesh directory 
I used Rpi 3
Please help me out 

Regards

**Comment by P33M** [comment]
This is a user program issue - not with the kernel. Issues unrelated to the linux kernel should be posted on the community forum at https://www.raspberrypi.org/forum
