### ISSUE TITLE
rpi-3.9.y: stuttering h264 playback

### ISSUE THREAD

**Issue by CrawX** [raspberrypi/linux#310]
Hey everyone,

I have found a possible regression in the newest 3.9 kernel.
Im using archlinuxarm and their linux-raspberrypi-latest kernel and I am experiencing some stuttering in xbmc while playing some h264 files which worked flawlessy on the 3.6.y kernel.

The files themselves have 1080p24 h264 video and 1510kbits/s dts audio, their size is about 20g.
The are mounted on a kernel-space mounted nfs-share using big buffersizes and udp. This has been proven to be the fastest combination, at least for me.
I have also overclocked my device to have enough power to do the software-decoding of the dts-tracks.
I know the files themselves coupled with the fact that they're being streamed over the network is kinda heavy for the pi, but it worked on 3.6.y.

Other than that, I can report a speedup on the newer kernel (noticeable faster boot-times for example).

I have reported the issue in the [archlinux forum](http://archlinuxarm.org/forum/viewtopic.php?f=31&t=5521&sid=957824aeed9a6b0a2e69f05b62371bbf&start=10#p32333) but as they only apply rather small patches to the kernel, I am starting to think this could be a kernel-specific issue.

My issue has been reproduced by at least one other member of the archlinux forum.

I'd be glad to provide more information or to help test something as I am really, really enjoing this little device :)

Greets,
CruX

**Comment by moonman** [comment]
The -latest is meant as an experimental kernel and the source is maintained at at raspberrypi foundation github. I've only added a bfq patch. If you know the source of the problem and know how to fix it feel free to submit a pull request. However i havent been able to reproduce it.

**Comment by popcornmix** [comment]
I have a test clip I use for benchmarking. I play a tricky clip (Prometheus dream sequence) from USB with software dts decode. I wind down the arm clock frequency until it just plays without stuttering.

I have ran this on 3.6 and 3.9 and get the same result.

To help narrow it down, can I ask you to run the same test on this build:
http://forum.xbmc.org/showthread.php?tid=140518&pid=1440939#pid1440939

which includes a 3.9.5 kernel.

**Comment by CrawX** [comment]
Okay I retested it and it seems like bfq is responsible for the stuttering. I dont really get why it is like that, but if I change the elevator entry to bfq it stutters, if I change it to noop it works again.
Of course changing the scheduler for the sd-card at runtime doesnt really make a difference.

I apologize for opening this issue.

Greets,
CruX

**Comment by popcornmix** [comment]
No problem, thanks for the info.
