### ISSUE TITLE
3.9.y 'make modules' build failure in 8192cu.ko

### ISSUE THREAD

**Issue by srcshelton** [raspberrypi/linux#311]
Immediately after '`make bcmrpi_defconfig`':

``` make
  Building modules, stage 2.
  MODPOST 1164 modules - due to target is PHONY
ERROR: "kernel_thread" [drivers/net/wireless/rtl8192cu/8192cu.ko] undefined!
make[4]: *** [__modpost] Error 1
make[3]: *** [modules] Error 2
make[2]: *** [sub-make] Error 2
make[1]: *** [modules] Error 2
make: *** [sub-make] Error 2
```

Interestingly, the osdep_service.c code generating this error reads:

``` c
#if (LINUX_VERSION_CODE < KERNEL_VERSION(3,7,0))
        *t_hdl = kernel_thread(threadfn, data, CLONE_FS|CLONE_FILES);
        if(*t_hdl < 0)
#else   
        *t_hdl = kthread_run(threadfn, data, name);
        if(IS_ERR(*t_hdl))
#endif
```

... so is the 3.9.y branch incorrectly defined to still be version 3.6, or something similar?

**Comment by popcornmix** [comment]
Can you try 
`rm include/linux/version.h`

**Comment by srcshelton** [comment]
`version.h` contains:

``` c
#define LINUX_VERSION_CODE 198155
#define KERNEL_VERSION(a,b,c) (((a) << 16) + ((b) << 8) + (c))
```

This has been built with `make O=<alternative build dir>`, which may have a bearing, but I've removed version.h from the build directory (and confirmed that it doesn't exist in the clone of the git repo).  Rebuilding now...

**Comment by popcornmix** [comment]
198155 = 0x3060b = linux 3.6.11

I'm guessing you've switched branches in git. linux kernel doesn't detect that file needs rebuilding - you need to delete it when switching branches.

**Comment by srcshelton** [comment]
Interesting - I have a clone of the main repo which follows the 3.6.y branch, but also fetches 3.8.y and 3.9.y.  I've then cloned each of these branches into local repos, and then built with `O=` to output to final build directories.  I'm pretty sure I've done a `make mrproper` on the 3.9.y build directory, but I may be thinking of one of the others...

Thanks for the help!
