### ISSUE TITLE
AM2302 temperature sensor - one wire

### ISSUE THREAD

**Issue by sriTeki** [raspberrypi/linux#3128]
Hello,

I am trying to read temperature and humidity values from ASAIR AM2302 sensor. Data signal is connected to GPIO4 of raspberrypi b+ model

Overlayers and modules are added to activate one-wire communication in raspberrypi. 

Queries:

- According to the data sheet, GPIO4 has to be intially configured as output and is pulled down. After few seconds, the sensor sends the data and hence GPIO has to be configured as input. 
I would like to know how to dynamically change GPIO configuration of raspberrypi b+ via Codesys environment.

- I would want to know the unique ID of sensor which is not visible in w1_bus_master directory, even though the modules (w1-them) are added.

Any help is greatly appreciated

Thank you in advance.

**Comment by pelwell** [comment]
This is a question, not an issue, and would be better asked in the Interfacing forum: https://www.raspberrypi.org/forums/viewforum.php?f=44
