### ISSUE TITLE
fbtft does not work on kernel 5.2.0 and above

### ISSUE THREAD

**Issue by alexandref75** [raspberrypi/linux#3149]
A fbtft, more specifically a pitft 2.8" resistive (uses the fb_ili9340 driver does not work with kernels 5.2.0 and above. Images do not appear on the display.

**Describe the bug**
Changes to internal kernel API of gpiod invalidates that way that fbtft identifies the GPIO pins. Without the dc-gpio pin, the SPI interface to the display does not work.

**To reproduce**
Connect a fbtft display that uses GPIO pins and boot a 5.2.X kernel or above, use the following command to present an image at the display:
fbi -T 2 -d /dev/fb1 -noverbose -a adapiluv320x240.jpg

**Expected behaviour**
An framebuffer that presents the image at the display.

**Actual behaviour**
The backlight and the display remain off and no image is shown.

**System**
pi@raspberrypi1:~ $ raspinfo 
System Information
------------------

Raspberry Pi Model B Rev 2
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"

Raspberry Pi reference 2019-06-20
Generated using pi-gen, https://github.com/RPi-Distro/pi-gen, 150e25c4f8123a4c9c63e8dca1b4737fa6c1135c, stage2

Linux raspberrypi1 5.2.6+ #23 Tue Aug 13 21:00:43 CDT 2019 armv6l GNU/Linux
Hardware        : BCM2835
Revision        : 000e
Serial          : 000000008ceda0f9
Throttled flag  : throttled=0x0
Camera          : supported=0 detected=0

Videocore information
---------------------

Jul  9 2019 14:40:53 
Copyright (c) 2012 Broadcom
version 6c3fe3f096a93de3b34252ad98cdccadeb534be2 (clean) (release) (start)

alloc failures:     0
compactions:        0
legacy block fails: 0

Filesystem information
----------------------
Filesystem     1K-blocks    Used Available Use% Mounted on
/dev/root        7429824 1686896   5408336  24% /
devtmpfs          217628       0    217628   0% /dev
tmpfs             221960       0    221960   0% /dev/shm
tmpfs             221960    3092    218868   2% /run
tmpfs               5120       0      5120   0% /run/lock
tmpfs             221960       0    221960   0% /sys/fs/cgroup
/dev/mmcblk0p1    258096   44152    213944  18% /boot
tmpfs              44392       0     44392   0% /run/user/1000

Filename                                Type            Size    Used    Priority
/var/swap                               file            102396  0       -2

Package version information
---------------------------
raspberrypi-ui-mods:
  Installed: (none)
raspberrypi-sys-mods:
  Installed: 20190730
openbox:
  Installed: (none)
lxpanel:
  Installed: (none)
pcmanfm:
  Installed: (none)
rpd-plym-splash:
  Installed: (none)

Networking Information
----------------------

eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet x.x.x.x  netmask x.x.x.x  broadcast x.x.x.x
        inet6 y::y.y.y.y  prefixlen 64  scopeid 0x20<link>
        ether m.m.m.m  txqueuelen 1000  (Ethernet)
        RX packets 271  bytes 18417 (17.9 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 287  bytes 58019 (56.6 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet x.x.x.x  netmask x.x.x.x
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

USB Information
---------------

/:  Bus 01.Port 1: Dev 1, Class=root_hub, Driver=dwc_otg/1p, 480M
    |__ Port 1: Dev 2, If 0, Class=Hub, Driver=hub/5p, 480M
        |__ Port 1: Dev 3, If 0, Class=Vendor Specific Class, Driver=smsc95xx, 480M

config.txt
----------

aphy_params_current=547
audio_pwm_mode=514
config_hdmi_boost=2
disable_auto_turbo=1
disable_commandline_tags=2
display_hdmi_rotate=-1
display_lcd_rotate=-1
dphy_params_current=547
enable_uart=1
force_pwm_open=1
framebuffer_ignore_alpha=1
framebuffer_swap=1
ignore_lcd=1
init_uart_clock=0x2dc6c00
pause_burst_frames=1
program_serial_random=1
hdmi_force_cec_address:0=65535
hdmi_force_cec_address:1=65535
hdmi_pixel_freq_limit:0=0x9a7ec80
hdmi_pixel_freq_limit:1=0x9a7ec80
device_tree=-
kernel=kernel-5.2.6.img
hdmi_cvt:0=
hdmi_cvt:1=
hdmi_edid_filename:0=
hdmi_edid_filename:1=
hdmi_timings:0=
hdmi_timings:1=

cmdline.txt
-----------
coherent_pool=1M bcm2708_fb.fbwidth=1824 bcm2708_fb.fbheight=984 bcm2708_fb.fbswap=1 vc_mem.mem_base=0x1ec00000 vc_mem.mem_size=0x20000000  dwc_otg.lpm_enable=0 console=ttyAMA0,115200 console=tty1 root=PARTUUID=93d699ac-02 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait

raspi-gpio settings
-------------------

BANK0 (GPIO 0 to 27):
GPIO 0: level=1 fsel=4 alt=0 func=SDA0
GPIO 1: level=1 fsel=4 alt=0 func=SCL0
GPIO 2: level=1 fsel=4 alt=0 func=SDA1
GPIO 3: level=1 fsel=4 alt=0 func=SCL1
GPIO 4: level=1 fsel=0 func=INPUT
GPIO 5: level=0 fsel=1 func=OUTPUT
GPIO 6: level=1 fsel=1 func=OUTPUT
GPIO 7: level=1 fsel=1 func=OUTPUT
GPIO 8: level=1 fsel=1 func=OUTPUT
GPIO 9: level=0 fsel=4 alt=0 func=SPI0_MISO
GPIO 10: level=0 fsel=4 alt=0 func=SPI0_MOSI
GPIO 11: level=0 fsel=4 alt=0 func=SPI0_SCLK
GPIO 12: level=0 fsel=0 func=INPUT
GPIO 13: level=0 fsel=0 func=INPUT
GPIO 14: level=1 fsel=4 alt=0 func=TXD0
GPIO 15: level=1 fsel=4 alt=0 func=RXD0
GPIO 16: level=1 fsel=1 func=OUTPUT
GPIO 17: level=0 fsel=0 func=INPUT
GPIO 18: level=0 fsel=0 func=INPUT
GPIO 19: level=0 fsel=0 func=INPUT
GPIO 20: level=0 fsel=0 func=INPUT
GPIO 21: level=0 fsel=1 func=OUTPUT
GPIO 22: level=0 fsel=0 func=INPUT
GPIO 23: level=0 fsel=0 func=INPUT
GPIO 24: level=1 fsel=0 func=INPUT
GPIO 25: level=0 fsel=0 func=INPUT
GPIO 26: level=0 fsel=0 func=INPUT
GPIO 27: level=0 fsel=0 func=INPUT
BANK1 (GPIO 28 to 45):
GPIO 28: level=0 fsel=0 func=INPUT
GPIO 29: level=0 fsel=0 func=INPUT
GPIO 30: level=0 fsel=0 func=INPUT
GPIO 31: level=0 fsel=0 func=INPUT
GPIO 32: level=0 fsel=0 func=INPUT
GPIO 33: level=0 fsel=0 func=INPUT
GPIO 34: level=1 fsel=0 func=INPUT
GPIO 35: level=1 fsel=0 func=INPUT
GPIO 36: level=1 fsel=0 func=INPUT
GPIO 37: level=0 fsel=0 func=INPUT
GPIO 38: level=0 fsel=0 func=INPUT
GPIO 39: level=0 fsel=0 func=INPUT
GPIO 40: level=0 fsel=4 alt=0 func=PWM0
GPIO 41: level=0 fsel=0 func=INPUT
GPIO 42: level=0 fsel=0 func=INPUT
GPIO 43: level=0 fsel=0 func=INPUT
GPIO 44: level=0 fsel=0 func=INPUT
GPIO 45: level=0 fsel=4 alt=0 func=PWM1
BANK2 (GPIO 46 to 53):
GPIO 46: level=1 fsel=0 func=INPUT
GPIO 47: level=0 fsel=0 func=INPUT
GPIO 48: level=0 fsel=4 alt=0 func=SD0_CLK
GPIO 49: level=1 fsel=4 alt=0 func=SD0_CMD
GPIO 50: level=1 fsel=4 alt=0 func=SD0_DAT0
GPIO 51: level=1 fsel=4 alt=0 func=SD0_DAT1
GPIO 52: level=1 fsel=4 alt=0 func=SD0_DAT2
GPIO 53: level=1 fsel=4 alt=0 func=SD0_DAT3

vcdbg log messages
------------------

001178.330: brfs: File read: /mfs/sd/config.txt
001178.889: brfs: File read: 778 bytes
001261.995: brfs: File read: /mfs/sd/config.txt
001262.546: gpioman: gpioman_get_pin_num: pin LEDS_PWR_OK not defined
001272.392: gpioman: gpioman_get_pin_num: pin WL_LPO_CLK not defined
001272.465: gpioman: gpioman_get_pin_num: pin BT_ON not defined
001272.529: gpioman: gpioman_get_pin_num: pin WL_ON not defined
001444.850: gpioman: gpioman_get_pin_num: pin LEDS_PWR_OK not defined
001444.945: *** Restart logging
001445.007: brfs: File read: 778 bytes
001478.181: hdmi: HDMI:hdmi_get_state is deprecated, use hdmi_get_display_state instead
001480.430: brfs: File read: /mfs/sd/cmdline.txt
001480.507: Read command line from file 'cmdline.txt':
001480.564: 'dwc_otg.lpm_enable=0 console=serial0,115200 console=tty1 root=PARTUUID=93d699ac-02 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait'
001480.876: brfs: File read: 142 bytes
001831.256: brfs: File read: /mfs/sd/kernel-5.2.6.img
001831.324: Loading 'kernel-5.2.6.img' to 0x8000 size 0x4b5bf0
001831.422: No kernel trailer - assuming DT-capable
001831.514: brfs: File read: 4938736 bytes
001835.300: brfs: File read: /mfs/sd/bcm2708-rpi-b.dtb
001835.366: Loading 'bcm2708-rpi-b.dtb' to 0x4bdbf0 size 0x5dcd
001926.007: brfs: File read: 24013 bytes
001927.885: brfs: File read: /mfs/sd/config.txt
001928.099: dtparam: spi=on
001937.597: dtparam: i2c1=on
001948.739: dtparam: i2c_arm=on
001959.773: brfs: File read: 778 bytes
001971.873: brfs: File read: /mfs/sd/overlays/pitft28-resistive.dtbo
001990.894: Loaded overlay 'pitft28-resistive'
001990.953: dtparam: rotate=90
001992.065: dtparam: speed=64000000
001993.168: dtparam: fps=30
003770.129: gpioman: gpioman_get_pin_num: pin EMMC_ENABLE not defined
003794.010: Device tree loaded to 0x1bfe9a00 (size 0x65d8)
003795.515: gpioman: gpioman_get_pin_num: pin SDCARD_CONTROL_POWER not defined
006888.288: vchiq_core: vchiq_init_state: slot_zero = 0x5b580000, is_master = 1
006894.573: hdmi: HDMI:hdmi_get_state is deprecated, use hdmi_get_display_state instead
006901.599: TV service:host side not connected, dropping notification 0x00000002, 0x00000001, 0x00000010
023794.826: brfs: File read: 2746 bytes

dmesg log
---------

[    0.000000] Booting Linux on physical CPU 0x0
[    0.000000] Linux version 5.2.6+ (alexandr@alexandre-main) (gcc version 8.3.0 (GNU Toolchain for the A-profile Architecture 8.3-2019.03 (arm-rel-8.36))) #23 Tue Aug 13 21:00:43 CDT 2019
[    0.000000] CPU: ARMv6-compatible processor [410fb767] revision 7 (ARMv7), cr=00c5387d
[    0.000000] CPU: PIPT / VIPT nonaliasing data cache, VIPT nonaliasing instruction cache
[    0.000000] OF: fdt: Machine model: Raspberry Pi Model B Rev 2
[    0.000000] Memory policy: Data cache writeback
[    0.000000] cma: Reserved 8 MiB at 0x1b400000
[    0.000000] On node 0 totalpages: 114688
[    0.000000]   Normal zone: 896 pages used for memmap
[    0.000000]   Normal zone: 0 pages reserved
[    0.000000]   Normal zone: 114688 pages, LIFO batch:31
[    0.000000] pcpu-alloc: s0 r0 d32768 u32768 alloc=1*32768
[    0.000000] pcpu-alloc: [0] 0 
[    0.000000] Built 1 zonelists, mobility grouping on.  Total pages: 113792
[    0.000000] Kernel command line: coherent_pool=1M bcm2708_fb.fbwidth=1824 bcm2708_fb.fbheight=984 bcm2708_fb.fbswap=1 vc_mem.mem_base=0x1ec00000 vc_mem.mem_size=0x20000000  dwc_otg.lpm_enable=0 console=ttyAMA0,115200 console=tty1 root=PARTUUID=93d699ac-02 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait
[    0.000000] Dentry cache hash table entries: 65536 (order: 6, 262144 bytes)
[    0.000000] Inode-cache hash table entries: 32768 (order: 5, 131072 bytes)
[    0.000000] Memory: 435260K/458752K available (6996K kernel code, 642K rwdata, 2232K rodata, 468K init, 797K bss, 15300K reserved, 8192K cma-reserved)
[    0.000000] SLUB: HWalign=32, Order=0-3, MinObjects=0, CPUs=1, Nodes=1
[    0.000000] ftrace: allocating 25187 entries in 50 pages
[    0.000000] NR_IRQS: 16, nr_irqs: 16, preallocated irqs: 16
[    0.000000] random: get_random_bytes called from start_kernel+0x2ac/0x4b4 with crng_init=0
[    0.000025] sched_clock: 32 bits at 1000kHz, resolution 1000ns, wraps every 2147483647500ns
[    0.000079] clocksource: timer: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 1911260446275 ns
[    0.000199] bcm2835: system timer (irq = 27)
[    0.000625] Console: colour dummy device 80x30
[    0.001103] printk: console [tty1] enabled
[    0.001197] Calibrating delay loop... 697.95 BogoMIPS (lpj=3489792)
[    0.050391] pid_max: default: 32768 minimum: 301
[    0.050899] Mount-cache hash table entries: 1024 (order: 0, 4096 bytes)
[    0.050965] Mountpoint-cache hash table entries: 1024 (order: 0, 4096 bytes)
[    0.052430] CPU: Testing write buffer coherency: ok
[    0.054095] Setting up static identity map for 0x8200 - 0x8238
[    0.055407] devtmpfs: initialized
[    0.068395] VFP support v0.3: implementor 41 architecture 1 part 20 variant b rev 5
[    0.068902] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 19112604462750000 ns
[    0.068988] futex hash table entries: 256 (order: -1, 3072 bytes)
[    0.070310] pinctrl core: initialized pinctrl subsystem
[    0.072245] NET: Registered protocol family 16
[    0.076677] DMA: preallocated 1024 KiB pool for atomic coherent allocations
[    0.084425] hw-breakpoint: found 6 breakpoint and 1 watchpoint registers.
[    0.084501] hw-breakpoint: maximum watchpoint size is 4 bytes.
[    0.084701] Serial: AMBA PL011 UART driver
[    0.090225] bcm2835-mbox 2000b880.mailbox: mailbox enabled
[    0.151211] bcm2835-dma 20007000.dma: DMA legacy API manager at (ptrval), dmachans=0x1
[    0.154310] SCSI subsystem initialized
[    0.154641] usbcore: registered new interface driver usbfs
[    0.154792] usbcore: registered new interface driver hub
[    0.155073] usbcore: registered new device driver usb
[    0.171097] raspberrypi-firmware soc:firmware: Attached to firmware from 2019-07-09 14:40, variant start
[    0.181116] raspberrypi-firmware soc:firmware: Firmware hash is 6c3fe3f096a93de3b34252ad98cdccadeb534be2
[    0.193663] clocksource: Switched to clocksource timer
[    1.400098] VFS: Disk quotas dquot_6.6.0
[    1.400284] VFS: Dquot-cache hash table entries: 1024 (order 0, 4096 bytes)
[    1.400664] FS-Cache: Loaded
[    1.401093] CacheFiles: Loaded
[    1.421158] NET: Registered protocol family 2
[    1.422629] tcp_listen_portaddr_hash hash table entries: 512 (order: 0, 4096 bytes)
[    1.422737] TCP established hash table entries: 4096 (order: 2, 16384 bytes)
[    1.422846] TCP bind hash table entries: 4096 (order: 2, 16384 bytes)
[    1.422946] TCP: Hash tables configured (established 4096 bind 4096)
[    1.423154] UDP hash table entries: 256 (order: 0, 4096 bytes)
[    1.423226] UDP-Lite hash table entries: 256 (order: 0, 4096 bytes)
[    1.423869] NET: Registered protocol family 1
[    1.425168] RPC: Registered named UNIX socket transport module.
[    1.425235] RPC: Registered udp transport module.
[    1.425269] RPC: Registered tcp transport module.
[    1.425299] RPC: Registered tcp NFSv4.1 backchannel transport module.
[    1.426708] hw perfevents: no irqs for PMU, sampling events not supported
[    1.426833] hw perfevents: enabled with armv6_1176 PMU driver, 3 counters available
[    1.431826] Initialise system trusted keyrings
[    1.432541] workingset: timestamp_bits=30 max_order=17 bucket_order=0
[    1.447830] FS-Cache: Netfs 'nfs' registered for caching
[    1.449419] NFS: Registering the id_resolver key type
[    1.449533] Key type id_resolver registered
[    1.449571] Key type id_legacy registered
[    1.449628] nfs4filelayout_init: NFSv4 File Layout Driver Registering...
[    1.451811] Key type asymmetric registered
[    1.451879] Asymmetric key parser 'x509' registered
[    1.451999] Block layer SCSI generic (bsg) driver version 0.4 loaded (major 250)
[    1.452050] io scheduler mq-deadline registered
[    1.452085] io scheduler kyber registered
[    1.455461] bcm2708_fb soc:fb: FB found 1 display(s)
[    1.456873] cma: cma_alloc: alloc failed, req-size: 1753 pages, ret: -12
[    1.503109] Console: switching to colour frame buffer device 228x61
[    1.537088] bcm2708_fb soc:fb: Registered framebuffer for display 0, size 1824x984
[    1.542932] bcm2835-rng 20104000.rng: hwrng registered
[    1.544036] vc-mem: phys_addr:0x00000000 mem_base=0x1ec00000 mem_size:0x20000000(512 MiB)
[    1.545955] vc-sm: Videocore shared memory driver
[    1.547167] gpiomem-bcm2835 20200000.gpiomem: Initialised: Registers at 0x20200000
[    1.571401] brd: module loaded
[    1.588518] loop: module loaded
[    1.590278] Loading iSCSI transport class v2.0-870.
[    1.591726] usbcore: registered new interface driver smsc95xx
[    1.592022] dwc_otg: version 3.00a 10-AUG-2012 (platform bus)
[    1.620534] dwc_otg 20980000.usb: base=(ptrval)
[    1.821583] Core Release: 2.80a
[    1.821770] Setting default values for core params
[    1.821998] Finished setting default values for core params
[    2.022987] Using Buffer DMA mode
[    2.023180] Periodic Transfer Interrupt Enhancement - disabled
[    2.023416] Multiprocessor Interrupt Enhancement - disabled
[    2.023638] OTG VER PARAM: 0, OTG VER FLAG: 0
[    2.024035] Dedicated Tx FIFOs mode
[    2.025168] WARN::dwc_otg_hcd_init:1045: FIQ DMA bounce buffers: virt = db514000 dma = 0x5b514000 len=9024
[    2.025580] FIQ FSM acceleration enabled for :
               Non-periodic Split Transactions
               Periodic Split Transactions
               High-Speed Isochronous Endpoints
               Interrupt/Control Split Transaction hack enabled
[    2.026345] dwc_otg: Microframe scheduler enabled
[    2.026579] WARN::hcd_init_fiq:457: FIQ on core 0
[    2.035719] WARN::hcd_init_fiq:458: FIQ ASM at c04efe50 length 36
[    2.044943] WARN::hcd_init_fiq:497: MPHI regs_base at dc810000
[    2.053917] dwc_otg 20980000.usb: DWC OTG Controller
[    2.063156] dwc_otg 20980000.usb: new USB bus registered, assigned bus number 1
[    2.072227] dwc_otg 20980000.usb: irq 56, io mem 0x00000000
[    2.081442] Init: Port Power? op_state=1
[    2.090332] Init: Power Port (0)
[    2.099799] usb usb1: New USB device found, idVendor=1d6b, idProduct=0002, bcdDevice= 5.02
[    2.109228] usb usb1: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[    2.118357] usb usb1: Product: DWC OTG Controller
[    2.127783] usb usb1: Manufacturer: Linux 5.2.6+ dwc_otg_hcd
[    2.136888] usb usb1: SerialNumber: 20980000.usb
[    2.147763] hub 1-0:1.0: USB hub found
[    2.157006] hub 1-0:1.0: 1 port detected
[    2.167519] dwc_otg: FIQ enabled
[    2.167540] dwc_otg: NAK holdoff enabled
[    2.167551] dwc_otg: FIQ split-transaction FSM enabled
[    2.167580] Module dwc_common_port init
[    2.168275] usbcore: registered new interface driver usb-storage
[    2.178380] mousedev: PS/2 mouse device common for all mice
[    2.189438] bcm2835-wdt bcm2835-wdt: Broadcom BCM2835 watchdog timer
[    2.199241] bcm2835-cpufreq: min=700000 max=700000
[    2.209688] sdhci: Secure Digital Host Controller Interface driver
[    2.218846] sdhci: Copyright(c) Pierre Ossman
[    2.228084] random: fast init done
[    2.238149] sdhost-bcm2835 20202000.mmc: could not get clk, deferring probe
[    2.248035] sdhci-pltfm: SDHCI platform and OF driver helper
[    2.258243] ledtrig-cpu: registered to indicate activity on CPUs
[    2.267520] hidraw: raw HID events driver (C) Jiri Kosina
[    2.277553] usbcore: registered new interface driver usbhid
[    2.286699] usbhid: USB HID core driver
[    2.297639] vchiq: vchiq_init_state: slot_zero = (ptrval)
[    2.309569] [vc_sm_connected_init]: start
[    2.323117] [vc_sm_connected_init]: end - returning 0
[    2.334338] Initializing XFRM netlink socket
[    2.343600] NET: Registered protocol family 17
[    2.352500] Key type dns_resolver registered
[    2.363629] registered taskstats version 1
[    2.372266] Loading compiled-in X.509 certificates
[    2.395329] uart-pl011 20201000.serial: cts_event_workaround enabled
[    2.404277] 20201000.serial: ttyAMA0 at MMIO 0x20201000 (irq = 81, base_baud = 0) is a PL011 rev2
[    4.690547] printk: console [ttyAMA0] enabled
[    4.706452] bcm2835-power bcm2835-power: Broadcom BCM2835 power domains driver
[    4.725838] sdhost: log_buf @ (ptrval) (5b513000)
[    4.739753] Indeed it is in host mode hprt0 = 00021501
[    4.864061] mmc0: sdhost-bcm2835 loaded - DMA enabled (>1)
[    4.883305] of_cfs_init
[    4.916311] of_cfs_init: OK
[    4.932655] Waiting for root device PARTUUID=93d699ac-02...
[    4.963796] usb 1-1: new high-speed USB device number 2 using dwc_otg
[    4.981606] Indeed it is in host mode hprt0 = 00001101
[    5.062051] mmc0: host does not support reading read-only switch, assuming write-enable
[    5.082095] mmc0: new high speed SDHC card at address b368
[    5.099225] mmcblk0: mmc0:b368 NCard 7.48 GiB
[    5.115995]  mmcblk0: p1 p2
[    5.174238] EXT4-fs (mmcblk0p2): mounted filesystem with ordered data mode. Opts: (null)
[    5.191867] VFS: Mounted root (ext4 filesystem) readonly on device 179:2.
[    5.221513] devtmpfs: mounted
[    5.234844] usb 1-1: New USB device found, idVendor=0424, idProduct=9514, bcdDevice= 2.00
[    5.252783] usb 1-1: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[    5.276392] Freeing unused kernel memory: 468K
[    5.290363] This architecture does not have kernel memory protection.
[    5.306264] Run /sbin/init as init process
[    5.321713] hub 1-1:1.0: USB hub found
[    5.335500] hub 1-1:1.0: 5 ports detected
[    5.673844] usb 1-1.1: new high-speed USB device number 3 using dwc_otg
[    5.814425] usb 1-1.1: New USB device found, idVendor=0424, idProduct=ec00, bcdDevice= 2.00
[    5.832585] usb 1-1.1: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[    5.855377] smsc95xx v1.0.6
[    5.962274] smsc95xx 1-1.1:1.0 eth0: register 'smsc95xx' at usb-20980000.usb-1.1, smsc95xx USB 2.0 Ethernet, m.m.m.m
[    6.302675] systemd[1]: System time before build time, advancing clock.
[    6.502989] NET: Registered protocol family 10
[    6.520732] Segment Routing with IPv6
[    6.602389] systemd[1]: systemd 241 running in system mode. (+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN -PCRE2 default-hierarchy=hybrid)
[    6.646929] systemd[1]: Detected architecture arm.
[    6.721951] systemd[1]: Set hostname to <rasppi@raspberrypi1:~ $ berrypi1>.
[    6.754953] systemd[1]: Failed to bump fs.file-max, ignoring: Invalid argument
[    8.525914] uart-pl011 20201000.serial: no DMA platform data
[    8.933795] systemd[1]: File /lib/systemd/system/systemd-journald.service:12 configures an IP firewall (IPAddressDeny=any), but the local system does not support BPF/cgroup based firewalling.
[    8.962696] systemd[1]: Proceeding WITHOUT firewalling in effect! (This warning is only shown for the first loaded unit using IP firewalling.)
[    9.938330] random: systemd: uninitialized urandom read (16 bytes read)
[   10.004695] random: systemd: uninitialized urandom read (16 bytes read)
[   10.025111] systemd[1]: Set up automount Arbitrary Executable File Formats File System Automount Point.
[   10.060746] random: systemd: uninitialized urandom read (16 bytes read)
[   10.085762] systemd[1]: Created slice system-serial\x2dgetty.slice.
[   10.170297] systemd[1]: Condition check resulted in Journal Audit Socket being skipped.
[   10.202655] systemd[1]: Listening on Syslog Socket.
[   11.616131] systemd[1]: Starting udev Coldplug all Devices...
[   11.747586] systemd[1]: Reached target Swap.
[   11.859745] systemd[1]: Created slice system-systemd\x2dfsck.slice.
[   12.048048] systemd[1]: Started Journal Service.
[   15.147862] EXT4-fs (mmcblk0p2): re-mounted. Opts: (null)
[   15.882966] systemd-journald[75]: Received request to flush runtime journal from PID 1
[   18.400606] media: Linux media interface: v0.10
[   18.674385] videodev: Linux video capture interface: v2.00
[   18.709413] stmpe-spi spi0.1: stmpe610 detected, chip id: 0x811
[   18.745075] stmpe-gpio stmpe-gpio: DMA mask not set
[   18.908753] vc_sm_cma: module is from the staging directory, the quality is unknown, you have been warned.
[   19.000759] bcm2835_mmal_vchiq: module is from the staging directory, the quality is unknown, you have been warned.
[   19.056368] bcm2835_v4l2: module is from the staging directory, the quality is unknown, you have been warned.
[   27.236682] fbtft: module is from the staging directory, the quality is unknown, you have been warned.
[   27.406241] fb_ili9340: module is from the staging directory, the quality is unknown, you have been warned.
[   27.436429] fbtft_of_value: buswidth = 8
[   27.436463] fbtft_of_value: debug = 0
[   27.436485] fbtft_of_value: rotate = 90
[   27.436503] fbtft_of_value: fps = 30
[   27.436951] fb_ili9340 spi0.0: Failed to request dc-gpios GPIO:-2
[   27.437155] fb_ili9340: probe of spi0.0 failed with error -2
[   28.217859] stmpe-ts stmpe-ts: DMA mask not set
[   28.282698] input: stmpe-ts as /devices/platform/soc/20204000.spi/spi_master/spi0/spi0.1/stmpe-ts/input/input0
[   31.164353] random: crng init done
[   31.164387] random: 7 urandom warning(s) missed due to ratelimiting
[   32.153048] 8021q: 802.1Q VLAN Support v1.8
[   33.375783] cfg80211: Loading compiled-in X.509 certificates for regulatory database
[   34.329002] Adding 102396k swap on /var/swap.  Priority:-2 extents:1 across:102396k SSFS
[   34.367140] cfg80211: Loaded X.509 cert 'sforshee: 00b28ddf47aef9cea7'
[   34.838188] smsc95xx 1-1.1:1.0 eth0: hardware isn't capable of remote wakeup
[   36.331010] smsc95xx 1-1.1:1.0 eth0: link up, 100Mbps, full-duplex, lpa 0xC5E1

**Patch**

The attached patch fixes the problem. It is tested on kernel 5.2.6.
[0001-Fix-fbtft-for-kernels-5.2.0-and-above.patch.txt](https://github.com/raspberrypi/linux/files/3499568/0001-Fix-fbtft-for-kernels-5.2.0-and-above.patch.txt)

**Comment by pelwell** [comment]
Thanks - that looks good, apart from one or two cosmetic issues that I can fix. Do you have a Signed-off-by line I may add?

**Comment by alexandref75** [comment]
Signed-off-by: Alexandre Peixoto Ferreira <alexandref75@gmail.com>
Thanks,

**Comment by pelwell** [comment]
Reading through the patch again, I think it should be split in two: a one-line fix that removes the spurious `!` in `if (!par->gpio.dc)`, and a cleanup patch. Have you tried with just the one-line fix?

**Comment by lategoodbye** [comment]
Looks like a squash of some upstream commits:
Staging: fbtft: Fix probing of gpio descriptor
Staging: fbtft: Fix reset assertion when using gpio descriptor (not included by seems to be relevant)
Staging: fbtft: Fix GPIO handling

So they might be backported soon.

**Comment by pelwell** [comment]
I'll hold off on a push/merge.

**Comment by alexandref75** [comment]
Wow. i should improve my searching, it would have saved a lot of debugging. the commits are much better than mine so this issue can be closed. the commits are from jun/11. it is already on 5.3.0-rc4 but i could not find references of backporting.

**Comment by lategoodbye** [comment]
The patches has been applied at the end of July, so it will take some time until they backported.

**Comment by pelwell** [comment]
The back-ports  have now appeared in 5.2:
* 3558601
* 1dd12a5
* 46af9cb

Please retest, and close if appropriate.

**Comment by JamesH65** [comment]
@alexandref75 Can this be closed?

**Comment by alexandref75** [comment]
Yes, it can be closed. Sorry for the delay.
