### ISSUE TITLE
[Feature Request] Support Arm8/aarch64

### ISSUE THREAD

**Issue by aeltawela** [raspberrypi/linux#3160]
It would really nice to provide Rasbpian 64bits variant and utilize the hardware capabilities in Raspberry PI 3/4.

The advantages and performance gain are explained in these slides https://www.arm.com/files/event/C2_64-bit_Android_Open_Source_Project_Applications_and_Advantages.pdf

**Comment by satmandu** [comment]
See these projects:
https://github.com/sakaki-/raspbian-nspawn-64
https://github.com/sakaki-/gentoo-on-rpi3-64bit
https://github.com/satmandu/docker-rpi4-imagebuilder

And also this thread:

https://www.raspberrypi.org/forums/viewtopic.php?f=63&t=247959

**Comment by JamesH65** [comment]
Not a bug, and a 64 kernel is being developed.
