### ISSUE TITLE
kernel 4.19: Please enable DRM for ST7735R

### ISSUE THREAD

**Issue by heeplr** [raspberrypi/linux#3173]
While framebuffer support (CONFIG_FB_TFT_ST7735R) is enabled, the DRM support is disabled (CONFIG_TINYDRM_ST7735R).

DRM probably is the preferable way to use for rendering so it should be enabled by default.

**Comment by popcornmix** [comment]
Do you mean 4.9 or 4.19?

**Comment by heeplr** [comment]
thanks, fixed the typo

**Comment by popcornmix** [comment]
Added https://github.com/raspberrypi/linux/commit/9798c94b34db4a32707f7f501616dbcbd088a696
Will be in next rpi-update kernel.
