### ISSUE TITLE
Enable CONFIG_GPIO_PCA953X

### ISSUE THREAD

**Issue by Aydan** [raspberrypi/linux#3182]
I noticed that the module for the PCA95xx series of GPIO expanders is not available. Please enable CONFIG_GPIO_PCA953X and maybe also CONFIG_LEDS_PCA9532 and CONFIG_LEDS_PCA955X

**Comment by pelwell** [comment]
Sorry for the delay - fixed by https://github.com/raspberrypi/linux/commit/8a32d41f63c5789d8cbada3e014fac96ae813300.

**Comment by popcornmix** [comment]
This is in latest rpi-update kernel. Can you test and close if happy?

**Comment by Aydan** [comment]
Thanks for the fix. Will this be in the next official kernel release?

**Comment by popcornmix** [comment]
Yes, next stable release (through apt) will have this change.
