### ISSUE TITLE
Missing 64 bit kernel for rpi4

### ISSUE THREAD

**Issue by chriscamacho** [raspberrypi/linux#3185]
I've been using a 64bit kernel for the pi4 (from https://github.com/sakaki-/gentoo-on-rpi-64bit) which seems to be fully functional, I'm working towards a "live" image for void linux, and it would be very helpful to have a 64bit kernel for the pi4 in the official "firmware" repo

**Comment by popcornmix** [comment]
This repo is for bug reports in the linux kernel. 
Feature requests are best directed at the forum.

It is likely there will be a thread in raspberry pi advanced users forum in the near future for testing a 64-bit kernel on raspbian, but this is early days. We are aware of features that will be missing and so any switch to 64-bit being the default will be some way off (assuming it is determined the switch is worthwhile).
