### ISSUE TITLE
Newer 4.19.x kernels do not load bcm2835_wdt automatically resulting in a system that will not reboot

### ISSUE THREAD

**Issue by dflogeras** [raspberrypi/linux#3187]
I run Gentoo, and build my kernel from this repo.  Since the last two tagged releases (20190718-1, 20190819-1) both on arm32 and arm64, my Pi's no longer automatically load the watchdog driver.  This will require a physical power cycle to reboot the machine if I forget to load the driver myself.

I _can_ work around it by just making the OS modprobe the driver, but I would expect it to be handled by DT like before.  I checked, and unlike another similar report, it is not blacklisted.  I have tried adding dtparam=watchdog=on to my config.txt but that didn't load it either.  I guess I could also just build the driver into the kernel as well since it seems to be required in order to reboot the device whether it is being used in userspace?

This happens on RPi B (old 256MB, and later 512MB), RPi0-W, as well as Rpi3-B running 64bit.  For the time being I just manually load the module to work around.

**Comment by lategoodbye** [comment]
Yes, this was a regression with conversion of power management to a MFD driver. Unfortunately i missed to a add a Fixes tag.

@popcornmix @pelwell 
Please backport this [fix](https://github.com/raspberrypi/linux/commit/215e06f0d18d5d653d6ea269e4dfc684854d48bf) from Linux 5.3

**Comment by lategoodbye** [comment]
I've send this patch to stable@vger.kernel.org, so it should be applied to Linux 5.2 (linux-stable) soon.

**Comment by popcornmix** [comment]
Thanks. It's been cherry-picked to 4.19 and 5.2 for now.

**Comment by dflogeras** [comment]
Thanks folks! closing.
