### ISSUE TITLE
 compiling with all the newest fix?" 

### ISSUE THREAD

**Issue by qtfp** [raspberrypi/linux#319]
Hey~
I have problem compiling. I compiled with the page for my touchscreen with the page:

http://engineering-diy.blogspot.tw/2013/01/adding-7inch-display-with-touchscreen.html

Then, I met problem with the ftdi ft232 usb-serial converter hang. Then, I rpi-updated to fix the ftdi ft232 hang problem.
Here I cant find a way to fix these two problem the same time.
How can I compile a version with the newest kernel version?
Thx

**Comment by popcornmix** [comment]
Sorry this isn't a linux kernel issue.
For compiling advice, I'd suggest the forums.
