### ISSUE TITLE
4.19.68 kernel arm64 dtbs not getting built

### ISSUE THREAD

**Issue by Dark-Sky** [raspberrypi/linux#3190]
Used make bcm2711_defconfig and no overlays or .dtb's are getting built here cross compiling. When I run the command it calls scripts/checksyscalls.sh and returns to the prompt.

```
[ray@ray-pc linux]$ make DTC_FLAGS="-@" ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- dtbs
  CALL    scripts/checksyscalls.sh
[ray@ray-pc linux]$
```

**Comment by Dark-Sky** [comment]
Closing this issue. I did another fresh clone and the dtbs built. Had a bad clone I guess.

**Comment by Necktwi** [comment]
a new clone didn't help me. I'm stuck.

**Comment by pelwell** [comment]
What have you tried? Copy and paste the actual commands you typed (the `history` command may be helpful).

**Comment by Necktwi** [comment]
If I reconfigure the kernel after `distclean`, starting from `bcmrpi3_defconfig` then the `dtbs` are generated. If I copy a old config to `.config` and clean & build, then `dtbs` are not generated.
