### ISSUE TITLE
Pi4 No audio from HDMI

### ISSUE THREAD

**Issue by tiagoboldt** [raspberrypi/linux#3197]
**Describe the bug**
No hdmi audio after a recent upgrade. Setup is an LG tv into a sony dn1080. Rpi 4 with arch linux and kodi-rbp4 into dn1080 as well. Also, if the pi is on, the av receiver cannot use arc from tv, for example, when I'm using netflix from the TV. `sudo /opt/vc/bin/tvservice -o` makes ARC start to work immediately, but I have to reboot the pi to get the screen back `tvservice -p` does nothing.

My config is:
> dtparam=audio=on
hdmi_drive=2
gpu_mem=512
dtoverlay=pi3-disable-bt
dtoverlay=pi3-disable-wifi
dtoverlay=vc4-fkms-v3d
hdmi_ignore_cec_init=1
initramfs initramfs-linux.img followkernel

I've played with multiple configs, changing resolutions, changing kodi output config from alsa to hdmi and back. nothing provided results. Including adding and removing `hdmi_drive`, `hdmi_ignore_cec_init` and `hdmi_force_edid_audio`.

**To reproduce**
Just boot with recent firmware. Currently using `linux-firmware-20190815.07b925b-1-any` and arch linux.

**Expected behaviour**
Audio is sent via hdmi to av receiver like it was about a month ago.

**Actual behaviour**
No audio via HDMI. 

**System**
 Copy and paste the results of the raspinfo command in to this section. Alternatively, copy and paste a pastebin link, or add answers to the following questions:

* Which model of Raspberry Pi? 
> pi4
* Which OS and version (`cat /etc/rpi-issue`)? 
> arch linux
* Which firmware version (`vcgencmd version`)?
> Aug 28 2019 15:05:34
Copyright (c) 2012 Broadcom
version 37b3ec82ae67937050af33d61eadf0445377646b (clean) (release) (start)

* Which kernel version (`uname -a`)?
already running the linux-raspberrypi4 kernel released these past days, but the issue started with the generic linux-raspberrypi kernel. 
> Linux rpi 4.19.68-1-ARCH #1 SMP PREEMPT Thu Aug 29 00:24:13 UTC 2019 armv7l GNU/Linux

**Logs**
The only thing weird in dmesg is this very threatening line ([dmesg.txt](https://github.com/raspberrypi/linux/files/3562527/dmesg.txt)):
> snd_bcm2835: module is from the staging directory, the quality is unknown, you have been warned.

Possibly related to #3181.

**Comment by pelwell** [comment]
> No hdmi audio after a recent upgrade.

1. Please identify the last known good firmware.
3. Confirm that the headphone audio output still works.
3. Reproducing the issue with Raspbian will lower the barrier for testing and increase the priority.
4. Report it in the [firmware repo](https://github.com/raspberrypi/firmware/), where it belongs.
