### ISSUE TITLE
non-void function 'brcmstb_platform_notifier' should return a value

### ISSUE THREAD

**Issue by MarkDunn-ObjectiveIntegration** [raspberrypi/linux#3216]
**Describe the bug**

the source checked with:
git checkout remotes/origin/rpi-4.19.y

fails to compile at:
../drivers/pci/controller/pcie-brcmstb.c

 CC      drivers/pci/controller/pcie-brcmstb.o
../drivers/pci/controller/pcie-brcmstb.c:656:5: error: non-void function 'brcmstb_platform_notifier' should return a value [-Wreturn-type]
                                return;
change it to:
				return ret;

**Comment by pelwell** [comment]
Thanks - [fixed](https://github.com/raspberrypi/linux/commit/13ce09db830e0c2fe524460b0673afb974359bc2).
