### ISSUE TITLE
issue with fiq split code, linux kernel bug : CIFS access issue

### ISSUE THREAD

**Issue by camelator** [raspberrypi/linux#323]
as requested to my issue:
https://github.com/Hexxeh/rpi-update/issues/101

Here is what I've done:
latest raspbian installation
partitions extended
reboot
sudo apt-get update
sudo apt-get upgrade
reboot
sudo mkdir /media/Musiques
sudo mkdir /media/Musiques/Albums
sudo nano /etc/fstab
add lines:
//192.168.1.1/my_passport/Musiques/Albums /media/Musiques/Albums cifs _netdev,guest,directio,uid=1000,iocharset=utf8,file_mode=0777,dir_mode=0777 0 0
sudo mount -a
/media/Musiques/Albums now contains my cifs share content
I  confirm it works after a reboot

then I did:
sudo wget http://goo.gl/1BOfJ -O /usr/bin/rpi-update && sudo chmod +x /usr/bin/rpi-update
sudo BRANCH=fiq_split rpi-update
reboot

and my share didn't work

result of mount -a
mount error(22): Invalid argument
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)

result of dmesg
[ 30.266847] smsc95xx 1-1.1:1.0 eth0: link up, 100Mbps, full-duplex, lpa 0x45E1
[ 33.453230] CIFS: Unknown mount option "directio"
[ 33.519859] CIFS: Unknown mount option "directio"
[ 38.064523] Adding 102396k swap on /var/swap. Priority:-1 extents:2 across:507900k SS
[ 150.376452] CIFS: Unknown mount option "directio"
[ 618.911850] CIFS: Unknown mount option "directio"

**Comment by P33M** [comment]
Hi,

Can you confirm the version of kernel running before and after the update?

uname -a will tell you.

The fiq_split branch is based on a newer revision of upstream kernel, in which there may have been changes to the CIFS subsystem/drivers. It is possible that in a more recent revision, the "directio" mount option has been removed or changed.

It should be noted that the FIQ implementation is now applied to most of the branches in github, so a plain rpi-update will pull in the latest "default" branch with the FIQ-split changes applied.

**Comment by camelator** [comment]
uname -a:
Linux raspberrypi 3.6.11+ #488 PREEMPT Tue Jul 2 16:37:47 BST 2013 armv6l GNU/Linux

I also tried without the direction parameter, it does not work with the fiq branch

**Comment by P33M** [comment]
CIFS works fine for me on latest kernel.
