### ISSUE TITLE
3.10 does not compile (implicit declaration... vc_cma*)

### ISSUE THREAD

**Issue by moonman** [raspberrypi/linux#324]
Hello,

Here's the partial compile log:

drivers/char/broadcom/vc_cma/vc_cma.c: In function 'vc_cma_init':
 drivers/char/broadcom/vc_cma/vc_cma.c:1088:2: error: implicit declaration of function 'create_proc_entry' [-Werror=implicit-function-declaration]
 drivers/char/broadcom/vc_cma/vc_cma.c:1088:20: error: assignment makes pointer from integer without a cast [-Werror]
 drivers/char/broadcom/vc_cma/vc_cma.c:1095:19: error: dereferencing pointer to incomplete type
 drivers/char/broadcom/vc_cma/vc_cma.c: In function 'vc_cma_exit':
 drivers/char/broadcom/vc_cma/vc_cma.c:1134:38: error: dereferencing pointer to incomplete type
 cc1: all warnings being treated as errors
 distcc[13074] ERROR: compile drivers/char/broadcom/vc_cma/vc_cma.c on localhost failed
 make[4]: **\* [drivers/char/broadcom/vc_cma/vc_cma.o] Error 1
 make[3]: **\* [drivers/char/broadcom/vc_cma] Error 2
 make[2]: **\* [drivers/char/broadcom] Error 2
 make[1]: **\* [drivers/char] Error 2
 make: **\* [drivers] Error 2

Full log can be found here: http://archlinuxarm.org:81/builder/in-log/linux-raspberrypi-latest-3.10.0-2-armv6.log.html.gz 

Kernel config is here: https://github.com/archlinuxarm/PKGBUILDs/blob/master/core/linux-raspberrypi-latest/config

**Comment by CrimsonKnight13** [comment]
I can confirm that I have the same issue.

**Comment by P33M** [comment]
https://github.com/torvalds/linux/commit/80e928f7ebb958f4d79d4099d1c5c0a015a23b93

This is why. Function has been removed from upstream.

**Comment by moonman** [comment]
What helped is I disabled bcm_vc_cma driver in config and it compiles, though I'm not too sure what functionality will be lost without this driver. Since default config does not enable this driver I guess it is not that important.

**Comment by akolesen** [comment]
The following patch fixes it. Please, review:
https://github.com/raspberrypi/linux/pull/338

**Comment by moonman** [comment]
Will build the kernel tonight. Thanks for working on this!
