### ISSUE TITLE
 Pi4 - Kernel 5.3.x - Setting/change of screen refresh rate fails inside Kodi

### ISSUE THREAD

**Issue by mkreisl** [raspberrypi/linux#3267]
The setting or change of screen refresh rate fails inside Kodi if Raspberry Pi4 is running kernel 5.3.x (as time of writing 5.3.3).
A short flickering of screen is noticeable, but rate is **not** changed. Don't see any ERROR-log in the log of Kodi or syslog/dmesg
Works on kernel 4.19.x though.

Running **same** kernel on Pi3B+ hardware,  changing screen refresh rate is ok there, so being unsure if issue depends on Kodi or kernel. 

FXI: Posted same issue [in Kodi forum](https://forum.kodi.tv/showthread.php?tid=347991)

**Comment by 6by9** [comment]
5.3 is still a work in progress with v3d - #3162

**Comment by mkreisl** [comment]
That's what I was afraid of.

And even at 4.19, the v3d driver seems to have serious problems using BTRFS with compression enabled

But in this regard I will open a new issue later

**Comment by mkreisl** [comment]
5.4.1 is working now, so closing issue
