### ISSUE TITLE
kernel panic accessing camera and i2c-1 bus

### ISSUE THREAD

**Issue by oklitz** [raspberrypi/linux#327]
Hi Folks !

I have a kernel panic when trying to start a camera command like raspivid or raspistill while accessing
the I2C Bus /dev/i2c-1.

When I stop the proccess which accesses to the I2C Bus then the camera works.

I have a Arch Linux (newest and updated)
- i2c_dev module loaded
  - /etc/modprobe.d/i2c_bcm2708.conf
    options i2c_bcm2708 baudrate=400000

Here is the Picture:

http://www.oklitz.com/images/kernel_panic.jpg

**Comment by popcornmix** [comment]
Sound like you don't have this kernel commit:
https://github.com/raspberrypi/linux/commit/470f0a770fca4d972106a7ec76130f9eb16eb864

Can you confirm that?

**Comment by oklitz** [comment]
[root@flypi ~]# uname -v
#1 PREEMPT Tue Jun 11 16:09:48 CDT 2013
[root@flypi ~]#

i dont think so but i have posted this issue to the rapberry pi forum and to the arch arm forum.

I dont want to compile a kernel by my self, i can wait a few days for the newest arch kernel update.
But it sounds very good that this problems is already known. I hope this commit you mentioned will solve this problem !

mfg marco

**Comment by oklitz** [comment]
New Kernel !
3.6.11-13-ARCH+ #1 PREEMPT Sun Jul 7 12:05:39 CDT 2013 armv6l GNU/Linux
Problem solved ! All works fine !
thanx !
