### ISSUE TITLE
Enable modules for Wiznet chips in the default config

### ISSUE THREAD

**Issue by geeks-r-us** [raspberrypi/linux#3276]
Please add the kernel modules for the Wiznet SPI Ethernet chips to ease the use of chips like W5100 and W5500, which are very cheap and support 100 MBit/s in opposite to the ENC28J60.

To make it more convenient I've attached these tested .dts files to connect the W5500 on CE0 and CE1

Many thx

[w5500-overlay.dts.txt](https://github.com/raspberrypi/linux/files/3707415/w5500-overlay.dts.txt)
[w5500-overlay-spi2.dts.txt](https://github.com/raspberrypi/linux/files/3707416/w5500-overlay-spi2.dts.txt)

**Comment by pelwell** [comment]
See #3278 - please test it before I merge it.

**Comment by geeks-r-us** [comment]
works fine. 
Thx

**Comment by pelwell** [comment]
#3278 is now merged, and will be in future builds.
