### ISSUE TITLE
ERROR: ld.so: 

### ISSUE THREAD

**Issue by 0xh0n3y** [raspberrypi/linux#3283]
i'm getting this error in raspberrypi jessi:-
ERROR: ld.so: object '�'�&�&�'�&�&�'�&�&�'�&�&�'�&�&�' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
whenever i type ls command in the pi terminal
![Screenshot from 2019-10-13 09-29-51](https://user-images.githubusercontent.com/23690578/66710743-1f75b680-ed9c-11e9-9437-3c480c1e9780.png)

**Comment by XECDesign** [comment]
Looks like your /etc/ld.so.preload files got corrupted (at least) rather than an issue with the Linux kernel.

**Comment by JamesH65** [comment]
Indeed - this looks like a corrupted SD card. I suggest re-imaging the card to see if that helps, if not, then getting a new card -  this one could be end of life.

This issue will be closed within 30 days unless further interactions are posted. If you wish this issue to remain open, please add a comment. A closed issue may be reopened if requested.
