### ISSUE TITLE
Digione driver mclk_div parameter need to correct as in  4.14.y

### ISSUE THREAD

**Issue by allocom** [raspberrypi/linux#3296]
@pelwell 

in 4.19.y  latest drivers 192k sample rate files are some time not playing properly.
we analyzed the code and noticed that mclk_div condition not satisfying in new driver.

refer previously working driver 
https://github.com/raspberrypi/linux/blob/rpi-4.14.y/sound/soc/bcm/allo-digione.c
lines 111- 113  : AlloDigiOne working  always mclk_div = WM8804_MCLKDIV_256FS;

![image](https://user-images.githubusercontent.com/14052398/67190275-4de33980-f40d-11e9-9a82-b8652a13e6e4.png)

On latest driver can you please add the condition for AlloDigiOne to configure only  WM8804_MCLKDIV_256FS  

https://github.com/raspberrypi/linux/blob/rpi-4.19.y/sound/soc/bcm/rpi-wm8804-soundcard.c
line 97 to 103

**Comment by pelwell** [comment]
Does #3299 work for you?

**Comment by allocom** [comment]
yes working. 
please proceed with merging.
thanks.

**Comment by pelwell** [comment]
Closing issue, as the matter has been resolved.
