### ISSUE TITLE
PREEMPT_RT Patch Kernel 5.2 undefined reference 

### ISSUE THREAD

**Issue by fortrieb** [raspberrypi/linux#3305]
**Describe the bug**
Try to apply PREEMPT_RT Patch for Kernel 5.2.y, but got a compiler error.
```
  ...
  AR      init/built-in.a
  LD      vmlinux.o
  MODPOST vmlinux.o
  MODINFO modules.builtin.modinfo
kernel/sched/core.o: In function »migrate_enable«:
:(.text+0x69dc): Warning: undefined reference »takedown_cpu_task«
make: *** [Makefile:1054: vmlinux] Error 1
```

**To reproduce**

* get Raspberry Pi Kernel source code for Kernel 5.2.y
* get PREEMPT_RT patch from [kernel.org](http://cdn.kernel.org/pub/linux/kernel/projects/rt/5.2/patches-5.2.21-rt13.tar.gz) for Kernel 5.2 and apply to kernel source
* configure with full preempt rt support
* start compiling, described in raspberry pi documentation https://www.raspberrypi.org/documentation/linux/kernel/building.md

**System**
Crosscompile on x86 machine.

* Which model of Raspberry Pi? 
  * Pi4
* Which OS and version (`cat /etc/rpi-issue`)?
  * Ubuntu 18.04 x86_64
* Which kernel version (`uname -a`)?
  * 5.0.0

I can't find any information about these ``takedown_cpu_task`` reference. Can anybody give a hint how to solve this?

**Comment by JamesH65** [comment]
This issue will be closed within 30 days unless further interactions are posted. If you wish this issue to remain open, please add a comment. A closed issue may be reopened if requested.

**Comment by JamesH65** [comment]
This does not appear to be a Pi/Raspbian problem.
