### ISSUE TITLE
Bluetooth PAN not working on PI 3B+ and 4B works on 3B

### ISSUE THREAD

**Issue by carpa5** [raspberrypi/linux#3313]
**Describe the bug**
PAN connection time out on PI 3B+ and 4B, but works on 3B using latest Buster

**To reproduce**
In Windows or Android connect to PAN, wait 60 seconds and try to SSH into PI. It will not work

**Expected behaviour**
Should be able to SSH into PI anytime after connecting to PAN and SSH session should not drop.

**Actual behaviour**
Connect to PAN wait 60 seconds and one will not be able to SSH to Pi. Now we have to connect to PAN again and SSH immediately into Pi. Once SSH session is made if we do not press any key for about 60 seconds the connection is dropped and PAN connection has to be made again. If we change putty setting "Connection", "Seconds between keepalives" from the default 60 to 10 connection will not drop.

**System**
System Information
------------------

Raspberry Pi 4 Model B Rev 1.1
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"

Raspberry Pi reference 2013-02-09 (armhf)
Generated using spindle, http://asbradbury.org/projects/spindle/, 1f91088, stage4-lxde-edu.qed

Linux pi4 4.19.75-v7l+ #1270 SMP Tue Sep 24 18:51:41 BST 2019 armv7l GNU/Linux
Revision        : c03111
Serial          : 1000000098bd5f91
Model           : Raspberry Pi 4 Model B Rev 1.1
Throttled flag  : throttled=0x0
Camera          : supported=0 detected=0

Videocore information
---------------------

Sep 24 2019 17:34:59
Copyright (c) 2012 Broadcom
version cd3add54955f8fa065b414d8fc07c525e7ddffc8 (clean) (release) (start_cd)

alloc failures:     0
compactions:        0
legacy block fails: 0

Filesystem information
----------------------
Filesystem     1K-blocks    Used Available Use% Mounted on
/dev/root       14728124 1752140  12208112  13% /
devtmpfs         1991720       0   1991720   0% /dev
tmpfs            2025512       0   2025512   0% /dev/shm
tmpfs            2025512   17728   2007784   1% /run
tmpfs               5120       0      5120   0% /run/lock
tmpfs            2025512       0   2025512   0% /sys/fs/cgroup
none               81920     312     81608   1% /var/log
none               40960       0     40960   0% /tmp
/dev/mmcblk0p1    524000   54384    469616  11% /boot
tmpfs             405100       0    405100   0% /run/user/0

Filename                                Type            Size    Used    Priority

Package version information
---------------------------
raspberrypi-ui-mods:
  Installed: (none)
raspberrypi-sys-mods:
  Installed: 20190730
openbox:
  Installed: (none)
lxpanel:
  Installed: (none)
pcmanfm:
  Installed: (none)
rpd-plym-splash:
  Installed: (none)

Networking Information
----------------------

eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet x.x.x.x  netmask x.x.x.x  broadcast x.x.x.x
        ether m.m.m.m  txqueuelen 1000  (Ethernet)
        RX packets 17930  bytes 14771002 (14.0 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 5385  bytes 548859 (535.9 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet x.x.x.x  netmask x.x.x.x
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 8  bytes 400 (400.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 8  bytes 400 (400.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

pan0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet x.x.x.x  netmask x.x.x.x  broadcast x.x.x.x
        ether m.m.m.m  txqueuelen 1000  (Ethernet)
        RX packets 284  bytes 49955 (48.7 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 53  bytes 8623 (8.4 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

wlan0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet x.x.x.x  netmask x.x.x.x  broadcast x.x.x.x
        ether m.m.m.m  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 29  bytes 6724 (6.5 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

USB Information
---------------

/:  Bus 03.Port 1: Dev 1, Class=root_hub, Driver=dwc_otg/1p, 480M
/:  Bus 02.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/4p, 5000M
/:  Bus 01.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/1p, 480M
    |__ Port 1: Dev 2, If 0, Class=Hub, Driver=hub/4p, 480M

config.txt
----------

arm_freq=1500
audio_pwm_mode=514
config_hdmi_boost=5
core_freq=500
core_freq_min=200
disable_commandline_tags=2
disable_l2cache=1
display_hdmi_rotate=-1
display_lcd_rotate=-1
enable_gic=1
force_eeprom_read=1
force_pwm_open=1
framebuffer_depth=16
framebuffer_ignore_alpha=1
framebuffer_swap=1
gpu_freq=500
gpu_freq_min=500
init_uart_clock=0x2dc6c00
lcd_framerate=60
pause_burst_frames=1
program_serial_random=1
hdmi_force_cec_address:0=65535
hdmi_force_cec_address:1=65535
hdmi_pixel_freq_limit:0=0x11e1a300
hdmi_pixel_freq_limit:1=0x11e1a300
device_tree=-
hdmi_cvt:0=
hdmi_cvt:1=
hdmi_edid_filename:0=
hdmi_edid_filename:1=
hdmi_timings:0=
hdmi_timings:1=

cmdline.txt
-----------
coherent_pool=1M 8250.nr_uarts=0 cma=64M bcm2708_fb.fbwidth=0 bcm2708_fb.fbheight=0 bcm2708_fb.fbdepth=16 bcm2708_fb.fbswap=1 smsc95xx.macaddr=DC:A6:32:16:83:93 vc_mem.mem_base=0x3f000000 vc_mem.mem_size=0x3f600000  dwc_otg.lpm_enable=0 console=tty1 root=/dev/mmcblk0p2 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait consoleblank=0 ipv6.disable=1

* Which model of Raspberry Pi? e.g. Pi3B+, PiZeroW
Problem occurs on PI3B+ and PI4B, but works on 3B

* Which OS and version (`cat /etc/rpi-issue`)?
Raspberry Pi reference 2013-02-09 (armhf)
Generated using spindle, http://asbradbury.org/projects/spindle/, 1f91088, stage4-lxde-edu.qed

* Which firmware version (`vcgencmd version`)?
Sep 24 2019 17:34:59
Copyright (c) 2012 Broadcom
version cd3add54955f8fa065b414d8fc07c525e7ddffc8 (clean) (release) (start_cd)

* Which kernel version (`uname -a`)?
Linux pi4 4.19.75-v7l+ #1270 SMP Tue Sep 24 18:51:41 BST 2019 armv7l GNU/Linux

**Logs**
Log of connecting to PAN and how it disconnects:

Oct 30 07:45:05 localhost bluetoothd[468]: bnep: bridge pan0: interface bnep0 added
Oct 30 07:45:05 localhost systemd-udevd[2500]: Using default interface naming scheme 'v240'.
Oct 30 07:45:05 localhost kernel: [ 1123.805457] pan0: port 1(bnep0) entered blocking state
Oct 30 07:45:05 localhost kernel: [ 1123.805471] pan0: port 1(bnep0) entered disabled state
Oct 30 07:45:05 localhost kernel: [ 1123.805823] device bnep0 entered promiscuous mode
Oct 30 07:45:05 localhost kernel: [ 1123.806693] pan0: port 1(bnep0) entered blocking state
Oct 30 07:45:05 localhost kernel: [ 1123.806706] pan0: port 1(bnep0) entered forwarding state
Oct 30 07:45:05 localhost systemd-udevd[2500]: link_config: autonegotiation is unset or enabled, the speed and duplex are not writable.
Oct 30 07:45:05 localhost dhcpd[702]: DHCPREQUEST for 192.168.3.101 from 80:86:f2:dc:36:a0 via pan0
Oct 30 07:45:05 localhost dhcpd[702]: Wrote 1 leases to leases file.
Oct 30 07:45:05 localhost dhcpd[702]: DHCPACK on 192.168.3.101 to 80:86:f2:dc:36:a0 (richardp14s) via pan0
Oct 30 07:46:11 localhost kernel: [ 1190.186874] pan0: port 1(bnep0) entered disabled state
Oct 30 07:46:11 localhost kernel: [ 1190.187640] device bnep0 left promiscuous mode
Oct 30 07:46:11 localhost kernel: [ 1190.187657] pan0: port 1(bnep0) entered disabled state
Oct 30 07:46:13 localhost ntpd[1939]: Deleting interface #4 pan0, 192.168.3.1#123, interface stats: received=0, sent=0, dropped=0, active_time=471 secs

**Additional context**
Since this works on a 3B I thought it might be firmware related, so I replaced the "/lib/firmware" (I don't know which specific module is used for bluetooth) folder from the previous release:

Aug 15 2019 12:07:10
Copyright (c) 2012 Broadcom
version 0e6daa5106dd4164474616408e0dc24f997ffcf3 (clean) (release) (start_cd)

Then I rebooted and now the PAN does not disconnect anymore.

Any help would be appreciated.

**Comment by pelwell** [comment]
I think this is a duplicate/variation of https://github.com/RPi-Distro/firmware-nonfree/issues/7, so please follow that thread (I'll ping you) and I'll close this one.
