### ISSUE TITLE
Delock 61959 support

### ISSUE THREAD

**Issue by stoprocent** [raspberrypi/linux#333]
Hi guys 

Is it possible you can apply this patch?
https://linuxtv.org/patch/17931/

It has been approved by linuxtv.org 
should be something simple i guess

**Comment by popcornmix** [comment]
We're unlikely to accept out of tree patches without overwhelming support.
(It creates a maintenance headache when we update, and there's no guarantee the patches won't cause issues elsewhere).

If the patch is good, then encourage it to be accepted into upstream linux kernel. We're more likely to accept patches from there.

**Comment by stoprocent** [comment]
Is there any tutorial which I can follow just to apply this patch on my own build ?
Do I have to recompile whole rasbian ?

**Comment by popcornmix** [comment]
Not raspbian, but the linux kernel. Try here:
http://elinux.org/RPi_Kernel_Compilation

Support questions are better asked in the forum.
