### ISSUE TITLE
5.4.y branch arm64 build error 

### ISSUE THREAD

**Issue by djazo** [raspberrypi/linux#3339]
The file `drivers/pci/controller/pcie-brcmstb-bounce64.c`
has call to non-specified function `is_device_dma_coherent`.

Cross building on x86_64 with:
`make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu-`

It should be `dev_is_dma_coherent` and `#include <linux/dma-noncoherent.h>` should be added to load the header.

**Comment by popcornmix** [comment]
@djazo can you confirm with this change 5.4 worked fine with 64-bit kernel?

**Comment by popcornmix** [comment]
I tested change and it built and booted. Added https://github.com/raspberrypi/linux/commit/88322f50733f8e1e55d2b5561a3911d292137267

**Comment by djazo** [comment]
I've been running 5.4-rc7 now on rpi4 since my original report, so can also confirm that it's been running ok.

**Comment by popcornmix** [comment]
Okay to close the issue now the patch is added?

**Comment by djazo** [comment]
Yeah. Closing.

**Comment by popcornmix** [comment]
Thanks for report.
