### ISSUE TITLE
raspivid kernel: Internal error: Oops: 807 [#1] ARM

### ISSUE THREAD

**Issue by hailongz-dev** [raspberrypi/linux#3343]
Raspberry Zero W

raspivid -n -ih -t 0 -rot 0 -w 1920 -h 1080 -fps 60 -fl -b 2500000 -o - | nc -lkv4 18001
Listening on [0.0.0.0] (family 2, port 18001)
Too many macroblocks/s: Increasing H264 Level to 4.2
Connection from 192.168.2.1 63644 received!

Message from syslogd@raspberrypi at Nov 22 06:11:15 ...
 kernel:[  225.252302] Internal error: Oops: 807 [#1] ARM

Message from syslogd@raspberrypi at Nov 22 06:11:15 ...
 kernel:[  225.252410] Process nc (pid: 509, stack limit = 0x96704b15)

Message from syslogd@raspberrypi at Nov 22 06:11:15 ...
 kernel:[  225.252413] Stack: (0xd3051890 to 0xd3052000)

Message from syslogd@raspberrypi at Nov 22 06:11:15 ...
 kernel:[  225.252417] 1880:                                     00000000 20000193 00000000 00000001

Message from syslogd@raspberrypi at Nov 22 06:11:15 ...
 kernel:[  225.252422] 18a0: 00000a40 00000000 00000002 00000040 00000002 d97b000c c0591294 00000000

Message from syslogd@raspberrypi at Nov 22 06:11:15 ...
 kernel:[  225.252426] 18c0: d72d0822 d72d253c 00000000 00000001 000000ff d702a400 d30518f4 d30518e8

Message from syslogd@raspberrypi at Nov 22 06:11:15 ...
 kernel:[  225.252430] 18e0: c03f9474 c03f8648 d30519c4 d30518f8 c03f70b0 c03f9468 00000001 d9100e20

Message from syslogd@raspberrypi at Nov 22 06:11:15 ...
 kernel:[  225.252434] 1900: d3051944 d72149c0 d305199c d702a508 ffffffff d703e218 ffffffff 00000000

Message from syslogd@raspberrypi at Nov 22 06:11:15 ...
 kernel:[  225.252439] 1920: 00000200 00000000 00000000 d703e070 d72d2538 00000002 00000002 c03f9468

Message from syslogd@raspberrypi at Nov 22 06:11:15 ...
 kernel:[  225.252443] 1940: 00000010 00000000 00000000 00000001 00000000 00000010 d305199c 00000060

Message from syslogd@raspberrypi at Nov 22 06:11:15 ...
 kernel:[  225.252447] 1960: 00000070 00000010 00000010 00000007 00000000 d3051901 d72d0820 c03f7280

Message from syslogd@raspberrypi at Nov 22 06:11:15 ...
 kernel:[  225.252451] 1980: c0028c3c c09e4e94 c0a62870 00000002 00000773 491d63b4 d30519c4 d703e070

Message from syslogd@raspberrypi at Nov 22 06:11:15 ...
 kernel:[  225.252456] 19a0: d702a400 00000007 d72d2538 00000002 c03f6e34 00000007 d3051a04 d30519c8

Message from syslogd@raspberrypi at Nov 22 06:11:15 ...
 kernel:[  225.252460] 19c0: c03f08bc c03f6e40 00000007 0000000c 00000007 00000000 00000052 d72d253e

Message from syslogd@raspberrypi at Nov 22 06:11:15 ...
 kernel:[  225.252465] 19e0: 00000765 00000003 d72d2498 00000700 0000000c d72d2538 d3051a4c d3051a08

Message from syslogd@raspberrypi at Nov 22 06:11:15 ...
 kernel:[  225.252469] 1a00: c03f2d2c c03f07d4 0000000c d3051a18 00000012 d702a400 00000007 d72d25c4

Message from syslogd@raspberrypi at Nov 22 06:11:15 ...
 kernel:[  225.252473] 1a20: d3051a64 d702a400 00000001 00000000 c0b1b8f4 c09e3b94 00000019 00000005

Message from syslogd@raspberrypi at Nov 22 06:11:15 ...
 kernel:[  225.252477] 1a40: d3051ab4 d3051a50 c03f5938 c03f2bd4 00000052 d703e070 d72d30a8 00000052

Message from syslogd@raspberrypi at Nov 22 06:11:15 ...
 kernel:[  225.252481] 1a60: 00000000 0000001a 00000005 d703e070 00000000 c0b1d8ec d702a400 00000000

Message from syslogd@raspberrypi at Nov 22 06:11:15 ...
 kernel:[  225.252485] 1a80: 00000001 c0b1b93c 00000190 00000005 00000000 c0a81f73 0000001a d702a400

Message from syslogd@raspberrypi at Nov 22 06:11:15 ...
 kernel:[  225.252490] 1aa0: c09e3028 00000000 d3051afc d3051ab8 c0430098 c03f56c8 00000001 491d63b4

Message from syslogd@zaspberrypi at Nov 22 06:11:15 ...
 kernel:[  225.252494] 1ac0: d3051aec d703e070 d702a400 00000000 d72d3004 d702a400 c09e3028 c0a81f73

Message from syslogd@raspberrypi at Nov 22 06:11:15 ...
 kernel:[  225.252498] 1ae0: 00000000 00000052 c09e3028 00000000 d3051b2c d3051b00 c0430154 c042fed4

Message from syslogd@raspberrypi at Nov 22 06:11:15 ...
 kernel:[  225.252503] 1b00: 00000001 d702a400 00000020 c0a81f73 00000000 491d63b4 d702a400 00000020

**Comment by 6by9** [comment]
Firstly 1080p60 is not supported from the camera, nor through the H264 encoder.

The v1 camera only does 60fps at VGA, whilst the v2 will do 60fps at 720p. Those images will be being upscaled to 1080p through the ISP but look blurry.

The H264 encoder is specced at level 4.0, which is 1080p30. 1080p60 is level 4.2, hence the log line about increasing the level due to too many macroblocks/sec. It may or may not achieve this - the higher levels are mainly enabled for transcode purposes where the stream needs to be defined correctly but not encode in real-time.

With regard the kernel panic, that one is generally a brownout within the SoC when the camera is running, and is generally only seen on the Pi0. Try adding ```over_voltage=4``` to /boot/config.txt.

**Comment by JamesH65** [comment]
This issue will be closed within 30 days unless further interactions are posted. If you wish this issue to remain open, please add a comment. A closed issue may be reopened if requested.
