### ISSUE TITLE
Enable CONFIG_HID_STEAM

### ISSUE THREAD

**Issue by rodrigorc** [raspberrypi/linux#3344]
In a desktop PC, the Steam Controller is usually managed by the Steam Client, by Valve. But in the RPI the best option is to enable the hid-steam kernel module. It would be nice to have it enabled by default.

**Comment by popcornmix** [comment]
@pelwell looks okay to me.
It's a tristate and the source for it looks fairly modest in size.

**Comment by AnsisMalins** [comment]
Liked, favorited and upvoted. I'm too stupid to compile custom kernels.

**Comment by pelwell** [comment]
Apologies - this one slipped through the net. It's in the rpi-4.19.y tree now (2620ff62e7e747acac5ceaeae88491a34a174945) and will be included in future builds.

**Comment by AnsisMalins** [comment]
Thank you. I'm not familiar with your process. When is the next build expected?

**Comment by pelwell** [comment]
There is no fixed schedule - it depends on what has changed - but there is usually at least one per week made available via rpi-update. The Raspbian kernel package is updated much less frequently - every few months, perhaps - and there are typically two or three full images released per year.

**Comment by rodrigorc** [comment]
This is already available for rpi-update. And it works perfectly.

Thank you.
