### ISSUE TITLE
NOOBS v3.2.1->RaspbianFull - RPi4 Kernel panic not syncing. Attempted to kill init exit code 0x00007f00

### ISSUE THREAD

**Issue by slrslr** [raspberrypi/linux#3349]
I have downloaded official torrent of the NOOBS v3.2.1 (magnet:?xt=urn:btih:0f816fa2bbad8358efd1ffe4abed11ee5fc7cb07&dn=NOOBS_v3_2_1.zip), (after download, the downloaded files are checked by the torrent client if are complete). I extracted .zip archive, formated the SDHC using SD Formatter and copied over the files. Inserted SDHC card into a RPi 4B 4GB RAM and ran. It shown NOOBS boot menu where i selected Raspbian FULL (it was 3 days back), it installed and i clicked OK button. It rebooted and ended with errors
Kernel panic not syncing. Attempted to kill init exit code 0x00007f00

![NOOBS v3 2 1 RPi4 kernel panic](https://user-images.githubusercontent.com/6596726/69616994-6e676a80-102f-11ea-81e3-592a45b2b8c2.jpg)

Sidenote: when i tried to flash Raspbian directly to SDHC, i had problem "[Caught <SEGV>, core dump failed, Freezing execution](https://github.com/raspberrypi/linux/issues/3345)". The first OS (LibreELEC) that i have installed when i received the RPi4 like 4 weeks ago and that i have on different SDHC card still working good. I am using TVhat.

Please let me know if i need to try anything (describe it exactly as i am a linux noob).

**Comment by XECDesign** [comment]
This looks like an unreliable sd card or an issue with the power supply.

**Comment by slrslr** [comment]
> This looks like an unreliable sd card or an issue with the power supply.

it is possible, because this time i have used Windows 10 disk formating tool to quick format **different SDHC card** as FAT32 and copied over noobs v3.2.1 files, installed light weight raspbian buster desktop successfully. Should this be closed or i should try something?

**Comment by pelwell** [comment]
If everything is working and we have a plausible explanation for the original problem then I would say close the issue. You can always reopen it later without losing the history if it recurs.
