### ISSUE TITLE
Can't use external USB HDD to be used for root partition

### ISSUE THREAD

**Issue by xenoist** [raspberrypi/linux#336]
In 3.9.10 the error shows "irqpoll" needed.

Updated /boot on sdcard with new firmware, but no luck to get it working at all.

Hardware setup Rasp with Powersupply, External hdd with power supply.

System settings of  the gentoo 2.2 image

sdcard
/dev/mmcblk0p1 2 GB vfat 

external hdd
/dev/sda3 48G ext4

Was working short before last update of 3.9.7.

"commit 7889cd6eedb2f40d4e3184a9c72b978e559b0cbb"
"Merge: bbd6677 ccd0dcb"
"Author: popcornmix popcornmix@gmail.com"
"Date:   Mon Jun 24 05:03:37 2013 -0700"

"    Merge pull request #317 from rm-hull/rpi-3.9.y"

"    Build failure caused by missing EXPORT_SYMBOL_GPL(bcm_dma_wait_idle); in dma.c"

The hdd is not shown when starting the rasp.

SDcard only setup with root partition on sdcard is doing fine. (3.10.y/3.9.y)

Will write full error message this evening when testing is possible.

**Comment by popcornmix** [comment]
Will need complete boot log.

**Comment by xenoist** [comment]
Hm seems to work on the one rasp.

I'll UART the other one tomorrow.

But it could be power related.

**Comment by xenoist** [comment]
OK could be closed.
I changed the USB Ports for the HDD to the Rasp, and now it boots kernel again from SD and root from USB HDD.
The device named changed from sdc to sda.

It was power related!
