### ISSUE TITLE
Raspberry 3B+ with purethermal 2 failed

### ISSUE THREAD

**Issue by imostlove17** [raspberrypi/linux#3384]
I am a novice. And a lepton 3.5 installed on purethermal 2, my Raspberry pi 3B+ installed Raspbian Buster.
I tried to run this program: uvc-radiometry.py 
I got this error message :

$ sudo ./uvc-radiometry.py 
unsupported descriptor subtype VS_COLORFORMAT
unsupported descriptor subtype VS_COLORFORMAT
unsupported descriptor subtype VS_COLORFORMAT
unsupported descriptor subtype VS_COLORFORMAT
unsupported descriptor subtype VS_COLORFORMAT
device opened!
Version gpp: 3.3.26 dsp: 3.3.26
FLIR part #: 500-0771-01
FLIR serial #: '{"(\x00\x00\x00\x00\x00'
format: UYVY
  frame 160x120 @ 9fps
format: Y16 
  frame 160x120 @ 9fps
  frame 160x122 @ 9fps
format: Y8  
  frame 160x120 @ 9fps
format: RGBP
  frame 160x120 @ 9fps
format: }�6�
  frame 160x120 @ 9fps
uvc_start_streaming failed: -2

please help me.

**Comment by pelwell** [comment]
This is not the place for help requests - please use the [Raspberry Pi forums](https://www.raspberrypi.org/forums/).
