### ISSUE TITLE
rpi-3.10.y branch bcmrpi_defconfig no longer sets CONFIG_TASKSTATS

### ISSUE THREAD

**Issue by xmw** [raspberrypi/linux#339]
It's usefull for monitors like iostat, and was working with 3.2/3.6/3.9 series.

--- .config.old 2013-07-23 12:51:28.279197927 +0200
+++ .config 2013-07-23 13:02:12.026347892 +0200
@@ -79,7 +79,10 @@
 # CONFIG_IRQ_TIME_ACCOUNTING is not set
 CONFIG_BSD_PROCESS_ACCT=y
 CONFIG_BSD_PROCESS_ACCT_V3=y
-# CONFIG_TASKSTATS is not set
+CONFIG_TASKSTATS=y
+CONFIG_TASK_DELAY_ACCT=y
+CONFIG_TASK_XACCT=y
+CONFIG_TASK_IO_ACCOUNTING=y

 #
 # RCU Subsystem

**Comment by popcornmix** [comment]
Updated.
