### ISSUE TITLE
unzip tarball fail on symlink error: File name too long

### ISSUE THREAD

**Issue by neofutur** [raspberrypi/linux#34]
trying to unzip the current zip ( downloaded from the "zip" link on main page )  fails with this error : 
( more exactly dowloaded from https://github.com/raspberrypi/linux/zipball/rpi-patches )

unzip raspberrypi-linux-b683e89.zip

finishing deferred symbolic links:
  raspberrypi-linux-b683e89/arch/microblaze/boot/dts/system.dts -> ../../platform/generic/system.dts
  raspberrypi-linux-b683e89/drivers/scsi/aacraid/linit.c -> /_^J *^IAdaptec AAC series RAID controller driver^J *^I(c) Copyright 2001 Red Hat Inc.^J *^J \* based on the old aacraid driver that is..^J \* Adaptec aacraid device driver for Linux.^J *^J \* Copyright (c) 2000-2010 Adaptec, Inc.^J \*               2010 PMC-Sierra, Inc. (aacraid@pmc-sierra.com)^J *^J \* This program is free software; you can redistribute it and/or modify^J \* it under the terms of the GNU General Public License as published by^J \* the Free Software Foundation; either version 2, or (at your option)^J \* any later version.^J *^J \* This program is distributed in the hope that it will be useful,^J \* but WITHOUT ANY WARRANTY; without even the implied warranty of^J \* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the^J \* GNU General Public License for more details.^J *^J \* You should have received a copy of the GNU General Public License^J \* along with this program; see the file COPYING.  If not, write to^J \* the Free Software Foundation, 675 Mass Ave, Cambridge, MA 02139, USA.^J *^J \* Module Name:^J \*   linit.c^J *^J \* Abstract: Linux Driver entry module for Adaptec RAID Array Controller^J */^J^J^J#include <linux/compat.h>^J#include <linux/blkdev.h>^J#include <linux/completion.h>^J#include <linux/init.h>^J#include <linux/interrupt.h>^J#include <linux/kernel.h>^J#include <linux/module.h>^J#include <linux/moduleparam.h>^J#include <linux/pci.h>^J#include <linux/pci-aspm.h>^J#include <linux/slab.h>^J#include <linux/mutex.h>^J#include <linux/spinlock.h>^J#include <linux/syscalls.h>^J#include <linux/delay.h>^J#include <linux/kthread.h>^J^J#include <scsi/scsi.h>^J#include <scsi/scsi_cmnd.h>^J#include <scsi/scsi_device.h>^J#include <scsi/scsi_host.h>^J#include <scsi/scsi_tcq.h>^J#include <scsi/scsicam.h>^J#include <scsi/scsi_eh.h>^J^J#include "aacraid.h"^J^J#define AAC_DRIVER_VERSION^I^I"1.1-7"^J#ifndef AAC_DRIVER_BRANCH^J#define AAC_DRIVER_BRANCH^I^I""^J#endif^J#define AAC_DRIVERNAME^I^I^I"aacraid"^J^J#ifdef AAC_DRIVER_BUILD^J#define _str(x) #x^J#define str(x) _str(x)^J#define AAC_DRIVER_FULL_VERSION^IAAC_DRIVER_VERSION "[" str(AAC_DRIVER_BUILD) "]" AAC_DRIVER_BRANCH^J#else^J#define AAC_DRIVER_FULL_VERSION^IAAC_DRIVER_VERSION AAC_DRIVER_BRANCH^J#endif^J^JMODULE_AUTHOR("Red Hat Inc and Adaptec");^JMODULE_DESCRIPTION("Dell PERC2, 2/Si, 3/Si, 3/Di, "^J^I^I   "Adaptec Advanced Raid Products, "^J^I^I   "HP NetRAID-4M, IBM ServeRAID & ICP SCSI driver");^JMODULE_LICENSE("GPL");^JMODULE_VERSION(AAC_DRIVER_FULL_VERSION);^J^Jstatic DEFINE_MUTEX(aac_mutex);^Jstatic LIST_HEAD(aac_devices);^Jstatic int aac_cfg_major = -1;^Jchar aac_driver_version[] = AAC_DRIVER_FULL_VERSION;^J^J/_^J \* Because of the way Linux names scsi devices, the order in this table has^J \* become important.  Check for on-board Raid first, add-in cards second.^J _^J \* Note: The last field is used to index into aac_drivers below.^J */^J#ifdef DECLARE_PCI_DEVICE_TABLE^Jstatic DECLARE_PCI_DEVICE_TABLE(aac_pci_tbl) = {^J#elif defined(__devinitconst)^Jstatic const struct pci_device_id aac_pci_tbl[] __devinitconst = {^J#else^Jstatic const struct pci_device_id aac_pci_tbl[] __devinitdata = {^J#endif^J^I{ 0x1028, 0x0001, 0x1028, 0x0001, 0, 0, 0 }, /_ PERC 2/Si (Iguana/PERC2Si) _/^J^I{ 0x1028, 0x0002, 0x1028, 0x0002, 0, 0, 1 }, /_ PERC 3/Di (Opal/PERC3Di) _/^J^I{ 0x1028, 0x0003, 0x1028, 0x0003, 0, 0, 2 }, /_ PERC 3/Si (SlimFast/PERC3Si _/^J^I{ 0x1028, 0x0004, 0x1028, 0x00d0, 0, 0, 3 }, /_ PERC 3/Di (Iguana FlipChip/PERC3DiF _/^J^I{ 0x1028, 0x0002, 0x1028, 0x00d1, 0, 0, 4 }, /_ PERC 3/Di (Viper/PERC3DiV) _/^J^I{ 0x1028, 0x0002, 0x1028, 0x00d9, 0, 0, 5 }, /_ PERC 3/Di (Lexus/PERC3DiL) _/^J^I{ 0x1028, 0x000a, 0x1028, 0x0106, 0, 0, 6 }, /_ PERC 3/Di (Jaguar/PERC3DiJ) _/^J^I{ 0x1028, 0x000a, 0x1028, 0x011b, 0, 0, 7 }, /_ PERC 3/Di (Dagger/PERC3DiD) _/^J^I{ 0x1028, 0x000a, 0x1028, 0x0121, 0, 0, 8 }, /_ PERC 3/Di (Boxster/PERC3DiB) _/^J^I{ 0x9005, 0x0283, 0x9005, 0x0283, 0, 0, 9 }, /_ catapult _/^J^I{ 0x9005, 0x0284, 0x9005, 0x0284, 0, 0, 10 }, /_ tomcat _/^J^I{ 0x9005, 0x0285, 0x9005, 0x0286, 0, 0, 11 }, /_ Adaptec 2120S (Crusader) _/^J^I{ 0x9005, 0x0285, 0x9005, 0x0285, 0, 0, 12 }, /_ Adaptec 2200S (Vulcan) _/^J^I{ 0x9005, 0x0285, 0x9005, 0x0287, 0, 0, 13 }, /_ Adaptec 2200S (Vulcan-2m) _/^J^I{ 0x9005, 0x0285, 0x17aa, 0x0286, 0, 0, 14 }, /_ Legend S220 (Legend Crusader) _/^J^I{ 0x9005, 0x0285, 0x17aa, 0x0287, 0, 0, 15 }, /_ Legend S230 (Legend Vulcan) _/^J^J^I{ 0x9005, 0x0285, 0x9005, 0x0288, 0, 0, 16 }, /_ Adaptec 3230S (Harrier) _/^J^I{ 0x9005, 0x0285, 0x9005, 0x0289, 0, 0, 17 }, /_ Adaptec 3240S (Tornado) _/^J^I{ 0x9005, 0x0285, 0x9005, 0x028a, 0, 0, 18 }, /_ ASR-2020ZCR SCSI PCI-X ZCR (Skyhawk) _/^J^I{ 0x9005, 0x0285, 0x9005, 0x028b, 0, 0, 19 }, /_ ASR-2025ZCR SCSI SO-DIMM PCI-X ZCR (Terminator) _/^J^I{ 0x9005, 0x0286, 0x9005, 0x028c, 0, 0, 20 }, /_ ASR-2230S + ASR-2230SLP PCI-X (Lancer) _/^J^I{ 0x9005, 0x0286, 0x9005, 0x028d, 0, 0, 21 }, /_ ASR-2130S (Lancer) _/^J^I{ 0x9005, 0x0286, 0x9005, 0x029b, 0, 0, 22 }, /_ AAR-2820SA (Intruder) _/^J^I{ 0x9005, 0x0286, 0x9005, 0x029c, 0, 0, 23 }, /_ AAR-2620SA (Intruder) _/^J^I{ 0x9005, 0x0286, 0x9005, 0x029d, 0, 0, 24 }, /_ AAR-2420SA (Intruder) _/^J^I{ 0x9005, 0x0286, 0x9005, 0x029e, 0, 0, 25 }, /_ ICP9024RO (Lancer) _/^J^I{ 0x9005, 0x0286, 0x9005, 0x029f, 0, 0, 26 }, /_ ICP9014RO (Lancer) _/^J^I{ 0x9005, 0x0286, 0x9005, 0x02a0, 0, 0, 27 }, /_ ICP9047MA (Lancer) _/^J^I{ 0x9005, 0x0286, 0x9005, 0x02a1, 0, 0, 28 }, /_ ICP9087MA (Lancer) _/^J^I{ 0x9005, 0x0286, 0x9005, 0x02a3, 0, 0, 29 }, /_ ICP5445AU (Hurricane44) _/^J^I{ 0x9005, 0x0285, 0x9005, 0x02a4, 0, 0, 30 }, /_ ICP9085LI (Marauder-X) _/^J^I{ 0x9005, 0x0285, 0x9005, 0x02a5, 0, 0, 31 }, /_ ICP5085BR (Marauder-E) _/^J^I{ 0x9005, 0x0286, 0x9005, 0x02a6, 0, 0, 32 }, /_ ICP9067MA (Intruder-6) _/^J^I{ 0x9005, 0x0287, 0x9005, 0x0800, 0, 0, 33 }, /_ Themisto Jupiter Platform _/^J^I{ 0x9005, 0x0200, 0x9005, 0x0200, 0, 0, 33 }, /_ Themisto Jupiter Platform _/^J^I{ 0x9005, 0x0286, 0x9005, 0x0800, 0, 0, 34 }, /_ Callisto Jupiter Platform _/^J^I{ 0x9005, 0x0285, 0x9005, 0x028e, 0, 0, 35 }, /_ ASR-2020SA SATA PCI-X ZCR (Skyhawk) _/^J^I{ 0x9005, 0x0285, 0x9005, 0x028f, 0, 0, 36 }, /_ ASR-2025SA SATA SO-DIMM PCI-X ZCR (Terminator) _/^J^I{ 0x9005, 0x0285, 0x9005, 0x0290, 0, 0, 37 }, /_ AAR-2410SA PCI SATA 4ch (Jaguar II) _/^J^I{ 0x9005, 0x0285, 0x1028, 0x0291, 0, 0, 38 }, /_ CERC SATA RAID 2 PCI SATA 6ch (DellCorsair) _/^J^I{ 0x9005, 0x0285, 0x9005, 0x0292, 0, 0, 39 }, /_ AAR-2810SA PCI SATA 8ch (Corsair-8) _/^J^I{ 0x9005, 0x0285, 0x9005, 0x0293, 0, 0, 40 }, /_ AAR-21610SA PCI SATA 16ch (Corsair-16) _/^J^I{ 0x9005, 0x0285, 0x9005, 0x0294, 0, 0, 41 }, /_ ESD SO-DIMM PCI-X SATA ZCR (Prowler) _/^J^I{ 0x9005, 0x0285, 0x103C, 0x3227, 0, 0, 42 }, /_ AAR-2610SA PCI SATA 6ch _/^J^I{ 0x9005, 0x0285, 0x9005, 0x0296, 0, 0, 43 }, /_ ASR-2240S (SabreExpress) _/^J^I{ 0x9005, 0x0285, 0x9005, 0x0297, 0, 0, 44 }, /_ ASR-4005 _/^J^I{ 0x9005, 0x0285, 0x1014, 0x02F2, 0, 0, 45 }, /_ IBM 8i (AvonPark) _/^J^I{ 0x9005, 0x0285, 0x1014, 0x0312, 0, 0, 45 }, /_ IBM 8i (AvonPark Lite) _/^J^I{ 0x9005, 0x0286, 0x1014, 0x9580, 0, 0, 46 }, /_ IBM 8k/8k-l8 (Aurora) _/^J^I{ 0x9005, 0x0286, 0x1014, 0x9540, 0, 0, 47 }, /_ IBM 8k/8k-l4 (Aurora Lite) _/^J^I{ 0x9005, 0x0285, 0x9005, 0x0298, 0, 0, 48 }, /_ ASR-4000 (BlackBird) _/^J^I{ 0x9005, 0x0285, 0x9005, 0x0299, 0, 0, 49 }, /_ ASR-4800SAS (Marauder-X) _/^J^I{ 0x9005, 0x0285, 0x9005, 0x029a, 0, 0, 50 }, /_ ASR-4805SAS (Marauder-E) _/^J^I{ 0x9005, 0x0286, 0x9005, 0x02a2, 0, 0, 51 }, /_ ASR-3800 (Hurricane44) _/^J^J^I{ 0x9005, 0x0285, 0x1028, 0x0287, 0, 0, 52 }, /_ Perc 320/DC_/^J^I{ 0x1011, 0x0046, 0x9005, 0x0365, 0, 0, 53 }, /_ Adaptec 5400S (Mustang)_/^J^I{ 0x1011, 0x0046, 0x9005, 0x0364, 0, 0, 54 }, /_ Adaptec 5400S (Mustang)_/^J^I{ 0x1011, 0x0046, 0x9005, 0x1364, 0, 0, 55 }, /_ Dell PERC2/QC _/^J^I{ 0x1011, 0x0046, 0x103c, 0x10c2, 0, 0, 56 }, /_ HP NetRAID-4M _/^J^J^I{ 0x9005, 0x0285, 0x1028, PCI_ANY_ID, 0, 0, 57 }, /_ Dell Catchall _/^J^I{ 0x9005, 0x0285, 0x17aa, PCI_ANY_ID, 0, 0, 58 }, /_ Legend Catchall _/^J^I{ 0x9005, 0x0285, PCI_ANY_ID, PCI_ANY_ID, 0, 0, 59 }, /_ Adaptec Catch All _/^J^I{ 0x9005, 0x0286, PCI_ANY_ID, PCI_ANY_ID, 0, 0, 60 }, /_ Adaptec Rocket Catch All _/^J^I{ 0x9005, 0x0288, PCI_ANY_ID, PCI_ANY_ID, 0, 0, 61 }, /_ Adaptec NEMER/ARK Catch All _/^J^I{ 0x9005, 0x028b, PCI_ANY_ID, PCI_ANY_ID, 0, 0, 62 }, /_ Adaptec PMC Catch All _/^J^I{ 0,}^J};^JMODULE_DEVICE_TABLE(pci, aac_pci_tbl);^J^J/_^J \* dmb - For now we add the number of channels to this structure.^J \* In the future we should add a fib that reports the number of channels^J \* for the card.  At that time we can remove the channels from here^J _/^Jstatic struct aac_driver_ident aac_drivers[] = {^J^I{ aac_rx_init, "percraid", "DELL    ", "PERCRAID        ", 2, AAC_QUIRK_31BIT | AAC_QUIRK_34SG | AAC_QUIRK_SCSI_32 }, /_ PERC 2/Si (Iguana/PERC2Si) _/^J^I{ aac_rx_init, "percraid", "DELL    ", "PERCRAID        ", 2, AAC_QUIRK_31BIT | AAC_QUIRK_34SG | AAC_QUIRK_SCSI_32 }, /_ PERC 3/Di (Opal/PERC3Di) _/^J^I{ aac_rx_init, "percraid", "DELL    ", "PERCRAID        ", 2, AAC_QUIRK_31BIT | AAC_QUIRK_34SG | AAC_QUIRK_SCSI_32 }, /_ PERC 3/Si (SlimFast/PERC3Si _/^J^I{ aac_rx_init, "percraid", "DELL    ", "PERCRAID        ", 2, AAC_QUIRK_31BIT | AAC_QUIRK_34SG | AAC_QUIRK_SCSI_32 }, /_ PERC 3/Di (Iguana FlipChip/PERC3DiF _/^J^I{ aac_rx_init, "percraid", "DELL    ", "PERCRAID        ", 2, AAC_QUIRK_31BIT | AAC_QUIRK_34SG | AAC_QUIRK_SCSI_32 }, /_ PERC 3/Di (Viper/PERC3DiV) _/^J^I{ aac_rx_init, "percraid", "DELL    ", "PERCRAID        ", 2, AAC_QUIRK_31BIT | AAC_QUIRK_34SG | AAC_QUIRK_SCSI_32 }, /_ PERC 3/Di (Lexus/PERC3DiL) _/^J^I{ aac_rx_init, "percraid", "DELL    ", "PERCRAID        ", 1, AAC_QUIRK_31BIT | AAC_QUIRK_34SG | AAC_QUIRK_SCSI_32 }, /_ PERC 3/Di (Jaguar/PERC3DiJ) _/^J^I{ aac_rx_init, "percraid", "DELL    ", "PERCRAID        ", 2, AAC_QUIRK_31BIT | AAC_QUIRK_34SG | AAC_QUIRK_SCSI_32 }, /_ PERC 3/Di (Dagger/PERC3DiD) _/^J^I{ aac_rx_init, "percraid", "DELL    ", "PERCRAID        ", 2, AAC_QUIRK_31BIT | AAC_QUIRK_34SG | AAC_QUIRK_SCSI_32 }, /_ PERC 3/Di (Boxster/PERC3DiB) _/^J^I{ aac_rx_init, "aacraid",  "ADAPTEC ", "catapult        ", 2, AAC_QUIRK_31BIT | AAC_QUIRK_34SG | AAC_QUIRK_SCSI_32 }, /_ catapult _/^J^I{ aac_rx_init, "aacraid",  "ADAPTEC ", "tomcat          ", 2, AAC_QUIRK_31BIT | AAC_QUIRK_34SG | AAC_QUIRK_SCSI_32 }, /_ tomcat _/^J^I{ aac_rx_init, "aacraid",  "ADAPTEC ", "Adaptec 2120S   ", 1, AAC_QUIRK_31BIT | AAC_QUIRK_34SG },^I^I      /_ Adaptec 2120S (Crusader) _/^J^I{ aac_rx_init, "aacraid",  "ADAPTEC ", "Adaptec 2200S   ", 2, AAC_QUIRK_31BIT | AAC_QUIRK_34SG },^I^I      /_ Adaptec 2200S (Vulcan) _/^J^I{ aac_rx_init, "aacraid",  "ADAPTEC ", "Adaptec 2200S   ", 2, AAC_QUIRK_31BIT | AAC_QUIRK_34SG | AAC_QUIRK_SCSI_32 }, /_ Adaptec 2200S (Vulcan-2m) _/^J^I{ aac_rx_init, "aacraid",  "Legend  ", "Legend S220     ", 1, AAC_QUIRK_31BIT | AAC_QUIRK_34SG | AAC_QUIRK_SCSI_32 }, /_ Legend S220 (Legend Crusader) _/^J^I{ aac_rx_init, "aacraid",  "Legend  ", "Legend S230     ", 2, AAC_QUIRK_31BIT | AAC_QUIRK_34SG | AAC_QUIRK_SCSI_32 }, /_ Legend S230 (Legend Vulcan) _/^J^J^I{ aac_rx_init, "aacraid",  "ADAPTEC ", "Adaptec 3230S   ", 2 }, /_ Adaptec 3230S (Harrier) _/^J^I{ aac_rx_init, "aacraid",  "ADAPTEC ", "Adaptec 3240S   ", 2 }, /_ Adaptec 3240S (Tornado) _/^J^I{ aac_rx_init, "aacraid",  "ADAPTEC ", "ASR-2020ZCR     ", 2 }, /_ ASR-2020ZCR SCSI PCI-X ZCR (Skyhawk) _/^J^I{ aac_rx_init, "aacraid",  "ADAPTEC ", "ASR-2025ZCR     ", 2 }, /_ ASR-2025ZCR SCSI SO-DIMM PCI-X ZCR (Terminator) _/^J^I{ aac_rkt_init, "aacraid",  "ADAPTEC ", "ASR-2230S PCI-X ", 2 }, /_ ASR-2230S + ASR-2230SLP PCI-X (Lancer) _/^J^I{ aac_rkt_init, "aacraid",  "ADAPTEC ", "ASR-2130S PCI-X ", 1 }, /_ ASR-2130S (Lancer) _/^J^I{ aac_rkt_init, "aacraid",  "ADAPTEC ", "AAR-2820SA      ", 1 }, /_ AAR-2820SA (Intruder) _/^J^I{ aac_rkt_init, "aacraid",  "ADAPTEC ", "AAR-2620SA      ", 1 }, /_ AAR-2620SA (Intruder) _/^J^I{ aac_rkt_init, "aacraid",  "ADAPTEC ", "AAR-2420SA      ", 1 }, /_ AAR-2420SA (Intruder) _/^J^I{ aac_rkt_init, "aacraid",  "ICP     ", "ICP9024RO       ", 2 }, /_ ICP9024RO (Lancer) _/^J^I{ aac_rkt_init, "aacraid",  "ICP     ", "ICP9014RO       ", 1 }, /_ ICP9014RO (Lancer) _/^J^I{ aac_rkt_init, "aacraid",  "ICP     ", "ICP9047MA       ", 1 }, /_ ICP9047MA (Lancer) _/^J^I{ aac_rkt_init, "aacraid",  "ICP     ", "ICP9087MA       ", 1 }, /_ ICP9087MA (Lancer) _/^J^I{ aac_rkt_init, "aacraid",  "ICP     ", "ICP5445AU       ", 1 }, /_ ICP5445AU (Hurricane44) _/^J^I{ aac_rx_init, "aacraid",  "ICP     ", "ICP9085LI       ", 1 }, /_ ICP9085LI (Marauder-X) _/^J^I{ aac_rx_init, "aacraid",  "ICP     ", "ICP5085BR       ", 1 }, /_ ICP5085BR (Marauder-E) _/^J^I{ aac_rkt_init, "aacraid",  "ICP     ", "ICP9067MA       ", 1 }, /_ ICP9067MA (Intruder-6) _/^J^I{ NULL        , "aacraid",  "ADAPTEC ", "Themisto        ", 0, AAC_QUIRK_SLAVE }, /_ Jupiter Platform _/^J^I{ aac_rkt_init, "aacraid",  "ADAPTEC ", "Callisto        ", 2, AAC_QUIRK_MASTER }, /_ Jupiter Platform _/^J^I{ aac_rx_init, "aacraid",  "ADAPTEC ", "ASR-2020SA       ", 1 }, /_ ASR-2020SA SATA PCI-X ZCR (Skyhawk) _/^J^I{ aac_rx_init, "aacraid",  "ADAPTEC ", "ASR-2025SA       ", 1 }, /_ ASR-2025SA SATA SO-DIMM PCI-X ZCR (Terminator) _/^J^I{ aac_rx_init, "aacraid",  "ADAPTEC ", "AAR-2410SA SATA ", 1, AAC_QUIRK_17SG }, /_ AAR-2410SA PCI SATA 4ch (Jaguar II) _/^J^I{ aac_rx_init, "aacraid",  "DELL    ", "CERC SR2        ", 1, AAC_QUIRK_17SG }, /_ CERC SATA RAID 2 PCI SATA 6ch (DellCorsair) _/^J^I{ aac_rx_init, "aacraid",  "ADAPTEC ", "AAR-2810SA SATA ", 1, AAC_QUIRK_17SG }, /_ AAR-2810SA PCI SATA 8ch (Corsair-8) _/^J^I{ aac_rx_init, "aacraid",  "ADAPTEC ", "AAR-21610SA SATA", 1, AAC_QUIRK_17SG }, /_ AAR-21610SA PCI SATA 16ch (Corsair-16) _/^J^I{ aac_rx_init, "aacraid",  "ADAPTEC ", "ASR-2026ZCR     ", 1 }, /_ ESD SO-DIMM PCI-X SATA ZCR (Prowler) _/^J^I{ aac_rx_init, "aacraid",  "ADAPTEC ", "AAR-2610SA      ", 1 }, /_ SATA 6Ch (Bearcat) _/^J^I{ aac_rx_init, "aacraid",  "ADAPTEC ", "ASR-2240S       ", 1 }, /_ ASR-2240S (SabreExpress) _/^J^I{ aac_rx_init, "aacraid",  "ADAPTEC ", "ASR-4005        ", 1 }, /_ ASR-4005 _/^J^I{ aac_rx_init, "ServeRAID","IBM     ", "ServeRAID 8i    ", 1 }, /_ IBM 8i (AvonPark) _/^J^I{ aac_rkt_init, "ServeRAID","IBM     ", "ServeRAID 8k-l8 ", 1 }, /_ IBM 8k/8k-l8 (Aurora) _/^J^I{ aac_rkt_init, "ServeRAID","IBM     ", "ServeRAID 8k-l4 ", 1 }, /_ IBM 8k/8k-l4 (Aurora Lite) _/^J^I{ aac_rx_init, "aacraid",  "ADAPTEC ", "ASR-4000        ", 1 }, /_ ASR-4000 (BlackBird & AvonPark) _/^J^I{ aac_rx_init, "aacraid",  "ADAPTEC ", "ASR-4800SAS     ", 1 }, /_ ASR-4800SAS (Marauder-X) _/^J^I{ aac_rx_init, "aacraid",  "ADAPTEC ", "ASR-4805SAS     ", 1 }, /_ ASR-4805SAS (Marauder-E) _/^J^I{ aac_rkt_init, "aacraid",  "ADAPTEC ", "ASR-3800        ", 1 }, /_ ASR-3800 (Hurricane44) _/^J^J^I{ aac_rx_init, "percraid", "DELL    ", "PERC 320/DC     ", 2, AAC_QUIRK_31BIT | AAC_QUIRK_34SG }, /_ Perc 320/DC_/^J^I{ aac_sa_init, "aacraid",  "ADAPTEC ", "Adaptec 5400S   ", 4, AAC_QUIRK_34SG }, /_ Adaptec 5400S (Mustang)_/^J^I{ aac_sa_init, "aacraid",  "ADAPTEC ", "AAC-364         ", 4, AAC_QUIRK_34SG }, /_ Adaptec 5400S (Mustang)_/^J^I{ aac_sa_init, "percraid", "DELL    ", "PERCRAID        ", 4, AAC_QUIRK_34SG }, /_ Dell PERC2/QC _/^J^I{ aac_sa_init, "hpnraid",  "HP      ", "NetRAID         ", 4, AAC_QUIRK_34SG }, /_ HP NetRAID-4M _/^J^J^I{ aac_rx_init, "aacraid",  "DELL    ", "RAID            ", 2, AAC_QUIRK_31BIT | AAC_QUIRK_34SG | AAC_QUIRK_SCSI_32 }, /_ Dell Catchall _/^J^I{ aac_rx_init, "aacraid",  "Legend  ", "RAID            ", 2, AAC_QUIRK_31BIT | AAC_QUIRK_34SG | AAC_QUIRK_SCSI_32 }, /_ Legend Catchall _/^J^I{ aac_rx_init, "aacraid",  "ADAPTEC ", "RAID            ", 2 }, /_ Adaptec Catch All _/^J^I{ aac_rkt_init, "aacraid", "ADAPTEC ", "RAID            ", 2 }, /_ Adaptec Rocket Catch All _/^J^I{ aac_nark_init, "aacraid", "ADAPTEC ", "RAID           ", 2 }, /_ Adaptec NEMER/ARK Catch All _/^J^I{ aac_src_init, "aacraid", "ADAPTEC ", "RAID            ", 2 } /_ Adaptec PMC Catch All _/^J};^J^J/__^J *^Iaac_queuecommand^I-^Iqueue a SCSI command^J *^I@cmd:^I^ISCSI command to queue^J *^I@done:^I^IFunction to call on command completion^J *^J *^IQueues a command for execution by the associated Host Adapter.^J *^J *^ITODO: unify with aac_scsi_cmd().^J */^J^Jstatic int aac_queuecommand_lck(struct scsi_cmnd *cmd, void (_done)(struct scsi_cmnd *)...
symlink error: File name too long

**Comment by asb** [comment]
I suspect this is a github issue rather than anything we are able to address. Closing, but do re-open if you can provide evidence to the contrary. I recommend either using git to clone the repo or trying to download the .tar.gz.

**Comment by neofutur** [comment]
yup it worked well with the tar.gz

**Comment by pankajr141** [comment]
Above is a issue of unzip utility for the linux
You can find the patch for unzip in below link. 
http://git.661346.n2.nabble.com/quot-git-archive-quot-seems-to-be-broken-wrt-zip-files-td6780039.html

The original src of unzip is available at http://sourceforge.net/projects/infozip/?source=dlp

**Comment by gamicklisafisher** [comment]
For copying and deleting “Long Path Tool” utility should be try, many articles refer this for such solutions.

**Comment by kaushalbisht2005** [comment]
Correct  "Above is a issue of unzip utility for the linux" try the above way OR yiu ca try..

Try to install p7zip
$ sudo apt-get install p7zip-full 

and extract
7za x linux.zip
