### ISSUE TITLE
RPi4: Cannot use multiple USB webcams at higher resolutions

### ISSUE THREAD

**Issue by maximumsomething** [raspberrypi/linux#3406]
**Describe the bug**
A single usb camera works fine at high resolutions, but an additional camera on a different USB port will not work if they are both running at the same time. Lowering the resolution of both cameras is a workaround.

This seems remarkably like the issues with the old Pis where all USB ports were connected to an internal hub and shared only 480 mbps of bandwidth total, but this is not the case on the Raspberry Pi 4.

I tried enabling `UVC_QUIRK_FIX_BANDWIDTH`, but the result was the same as before.

**To reproduce**
Connect two USB 2.0 webcams to a Raspberry Pi 4 and make them both capture raw (YUYV) video at 800x448 resolution.

**Expected behaviour**
Both cameras work.

**Actual behaviour**
The first camera will work fine, but the second will hang on the `ioctl(VIDIOC_DQBUF)` call (which gets called every frame).

**System**
```
System Information
------------------

Raspberry Pi 4 Model B Rev 1.1
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"

Raspberry Pi reference 2019-09-26
Generated using pi-gen, https://github.com/RPi-Distro/pi-gen, 80d486687ea77d31fc3fc13cf3a2f8b464e129be, stage4

Linux team5708pi 4.19.75-v7l+ #1270 SMP Tue Sep 24 18:51:41 BST 2019 armv7l GNU/Linux
Revision	: b03111
Serial		: 100000000e728cb2
Model		: Raspberry Pi 4 Model B Rev 1.1
Throttled flag  : throttled=0x0
Camera          : supported=0 detected=0

Videocore information
---------------------

Sep 24 2019 17:34:30 
Copyright (c) 2012 Broadcom
version cd3add54955f8fa065b414d8fc07c525e7ddffc8 (clean) (release) (start)

alloc failures:     0
compactions:        0
legacy block fails: 0

Filesystem information
----------------------
Filesystem     1K-blocks    Used Available Use% Mounted on
/dev/root       14989948 3800556  10529236  27% /
devtmpfs          769564       0    769564   0% /dev
tmpfs             901660       0    901660   0% /dev/shm
tmpfs             901660   98908    802752  11% /run
tmpfs               5120       4      5116   1% /run/lock
tmpfs             901660       0    901660   0% /sys/fs/cgroup
/dev/mmcblk0p1    258095   54661    203434  22% /boot
tmpfs             180332       0    180332   0% /run/user/1000

Filename				Type		Size	Used	Priority
/var/swap                               file		102396	0	-2

Package version information
---------------------------
raspberrypi-ui-mods:
  Installed: 1.20200115
raspberrypi-sys-mods:
  Installed: 20191105
openbox:
  Installed: 3.6.1-8+rpt3
lxpanel:
  Installed: 0.10.0-2+rpt7
pcmanfm:
  Installed: 1.3.1-1+rpt16
rpd-plym-splash:
  Installed: 0.20

USB Information
---------------

/:  Bus 03.Port 1: Dev 1, Class=root_hub, Driver=dwc_otg/1p, 480M
/:  Bus 02.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/4p, 5000M
/:  Bus 01.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/1p, 480M
    |__ Port 1: Dev 2, If 0, Class=Hub, Driver=hub/4p, 480M
        |__ Port 1: Dev 8, If 0, Class=Audio, Driver=snd-usb-audio, 480M
        |__ Port 1: Dev 8, If 1, Class=Audio, Driver=snd-usb-audio, 480M
        |__ Port 1: Dev 8, If 2, Class=Video, Driver=uvcvideo, 480M
        |__ Port 1: Dev 8, If 3, Class=Video, Driver=uvcvideo, 480M
        |__ Port 2: Dev 9, If 0, Class=Audio, Driver=snd-usb-audio, 480M
        |__ Port 2: Dev 9, If 3, Class=Video, Driver=uvcvideo, 480M
        |__ Port 2: Dev 9, If 1, Class=Audio, Driver=snd-usb-audio, 480M
        |__ Port 2: Dev 9, If 2, Class=Video, Driver=uvcvideo, 480M
        |__ Port 4: Dev 10, If 1, Class=Video, Driver=uvcvideo, 480M
        |__ Port 4: Dev 10, If 2, Class=Audio, Driver=snd-usb-audio, 480M
        |__ Port 4: Dev 10, If 0, Class=Video, Driver=uvcvideo, 480M
        |__ Port 4: Dev 10, If 3, Class=Audio, Driver=snd-usb-audio, 480M

config.txt
----------

arm_freq=1500
audio_pwm_mode=514
config_hdmi_boost=5
core_freq=500
core_freq_min=200
disable_commandline_tags=2
disable_l2cache=1
display_hdmi_rotate=-1
display_lcd_rotate=-1
enable_gic=1
force_eeprom_read=1
force_pwm_open=1
framebuffer_depth=16
framebuffer_ignore_alpha=1
framebuffer_swap=1
gpu_freq=500
gpu_freq_min=500
init_uart_clock=0x2dc6c00
lcd_framerate=60
mask_gpu_interrupt0=1024
mask_gpu_interrupt1=0x10000
max_framebuffers=2
pause_burst_frames=1
program_serial_random=1
hdmi_force_cec_address:0=65535
hdmi_force_cec_address:1=65535
hdmi_pixel_freq_limit:0=0x11e1a300
hdmi_pixel_freq_limit:1=0x11e1a300
device_tree=-
hdmi_cvt:0=
hdmi_cvt:1=
hdmi_edid_filename:0=
hdmi_edid_filename:1=
hdmi_timings:0=
hdmi_timings:1=

cmdline.txt
-----------
coherent_pool=1M 8250.nr_uarts=0 cma=64M cma=256M  smsc95xx.macaddr=DC:A6:32:0F:3E:59 vc_mem.mem_base=0x3ec00000 vc_mem.mem_size=0x40000000  console=ttyS0,115200 console=tty1 root=PARTUUID=d9b3f436-02 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait quiet splash plymouth.ignore-serial-consoles
```

**Logs**
Here is the dmesg log when `echo 0xffff | sudo tee /sys/module/uvcvideo/parameters/trace` is ran then the cameras are activated:
```
[  625.381174] uvcvideo: uvc_v4l2_open
[  625.621027] uvcvideo: Resuming interface 0
[  625.621033] uvcvideo: Resuming interface 1
[  625.621109] uvcvideo: Trying format 0x56595559 (YUYV): 800x448.
[  625.621115] uvcvideo: Using default frame interval 33333.3 us (30.0 fps).
[  625.623883] uvcvideo: uvc_v4l2_mmap
[  625.624995] uvcvideo: uvc_v4l2_mmap
[  625.626018] uvcvideo: uvc_v4l2_mmap
[  625.627056] uvcvideo: uvc_v4l2_mmap
[  625.628266] uvcvideo: Device requested 3060 B/frame bandwidth.
[  625.628275] uvcvideo: Selecting alternate setting 11 (3060 B/frame bandwidth).
[  625.802845] uvcvideo: Allocated 5 URB buffers of 32x3060 bytes each.
[  625.845977] uvcvideo: Control 3/4 value change len 7.
[  625.936218] uvcvideo: Frame complete (EOF found).
[  625.936227] uvcvideo: EOF in empty payload.
[  625.936824] uvcvideo: uvc_v4l2_open
[  625.947935] uvcvideo: frame 1 stats: 0/236/237 packets, 0/0/237 pts (!early initial), 236/237 scr, last pts/stc/sof 620271536/639183936/43843
[  625.979906] uvcvideo: Frame complete (EOF found).
[  625.979916] uvcvideo: EOF in empty payload.
[  625.991933] uvcvideo: frame 2 stats: 0/236/237 packets, 0/0/237 pts (!early initial), 236/237 scr, last pts/stc/sof 632703536/651410136/43879
[  626.020081] uvcvideo: Frame complete (EOF found).
[  626.020091] uvcvideo: EOF in empty payload.
[  626.022181] uvcvideo: Resuming interface 2
[  626.022193] uvcvideo: Resuming interface 3
[  626.022267] uvcvideo: Trying format 0x56595559 (YUYV): 800x448.
[  626.022279] uvcvideo: Using default frame interval 33333.3 us (30.0 fps).
[  626.031949] uvcvideo: frame 3 stats: 0/236/237 packets, 0/0/237 pts (!early initial), 236/237 scr, last pts/stc/sof 645202936/664011736/43916
[  626.050180] uvcvideo: uvc_v4l2_mmap
[  626.053405] uvcvideo: uvc_v4l2_mmap
[  626.054085] uvcvideo: Control 3/4 value change len 7.
[  626.055709] uvcvideo: uvc_v4l2_mmap
[  626.058676] uvcvideo: uvc_v4l2_mmap
[  626.060225] uvcvideo: Frame complete (EOF found).
[  626.060234] uvcvideo: EOF in empty payload.
[  626.066392] uvcvideo: Device requested 3060 B/frame bandwidth.
[  626.066409] uvcvideo: Selecting alternate setting 11 (3060 B/frame bandwidth).
[  626.076003] uvcvideo: frame 4 stats: 0/236/237 packets, 0/0/237 pts (!early initial), 236/237 scr, last pts/stc/sof 657703136/676425736/43953
[  626.079445] uvcvideo: Allocated 5 URB buffers of 32x3060 bytes each.
[  626.115965] uvcvideo: frame 5 stats: 0/236/237 packets, 0/0/237 pts (!early initial), 236/237 scr, last pts/stc/sof 670203336/688989736/43990
[  626.155972] uvcvideo: frame 6 stats: 0/236/237 packets, 0/0/237 pts (!early initial), 236/237 scr, last pts/stc/sof 682703336/701441336/44027
[  626.199975] uvcvideo: frame 7 stats: 0/236/237 packets, 0/0/237 pts (!early initial), 236/237 scr, last pts/stc/sof 695202936/714005336/44064
[  626.240069] uvcvideo: frame 8 stats: 0/236/237 packets, 0/0/237 pts (!early initial), 236/237 scr, last pts/stc/sof 707703336/726419336/44101
```
After that, it spams `uvcvideo: USB isochronous frame lost (-18).` Between those messages, it will report every frame a message like this one:

```
Marking buffer as bad (error bit set).
uvcvideo: Frame complete (EOF found).
uvcvideo: frame 72 stats: 108/1/109 packets, 1/103/109 pts (early initial), 108/109 scr, last pts/stc/sof 3923567593/3923957787/1908
uvcvideo: frame 65 stats: 0/236/237 packets, 0/0/237 pts (!early initial), 236/237 scr, last pts/stc/sof 1406594448/1425309848/18759
```

**Comment by timg236** [comment]
Try updating the VL805 (USB controller) firmware to 0137ad. See this forum thread
https://www.raspberrypi.org/forums/viewtopic.php?t=260879

**Comment by maximumsomething** [comment]
I'm closing this issue, I will reopen it if it still occurs after the firmware update.

**Comment by maximumsomething** [comment]
I'm experiencing the same problem after the firmware update.

**Comment by P33M** [comment]
I wouldn't expect that configuration to work with either firmware.

>This seems remarkably like the issues with the old Pis where all USB ports were connected to an internal hub and shared only 480 mbps of bandwidth total, but this is not the case on the Raspberry Pi 4.

This is also the case on Pi 4. There is an (internal) USB2.0 hub and all ports share the same upstream USB2.0 link.

Add up the bandwidth consumed by each endpoint and you'll find that it exceeds the maximum allowed by the USB spec - 80% of the total is the maximum for all aggregate periodic traffic.

3060bytes per USB microframe * 2 devices = 391mbit/s best-case (ignoring bit stuffing, inter-packet gaps and host IN tokens), 81% of 480mbit/s. Peak bandwidth is what matters, not the average output bitrate, because if it doesn't fit in a microframe then the transfer is terminated with a babble error.

I recommend either using USB3.0 cameras, or cameras that do mjpeg/h264 compression.

**Comment by maximumsomething** [comment]
> This is also the case on Pi 4. There is an (internal) USB2.0 hub and all ports share the same upstream USB2.0 link.

The official docs say that's not the case:

https://www.raspberrypi.org/documentation/hardware/raspberrypi/usb/README.md#overview_pi4

> For the Pi 4, a fully-featured host controller drives the downstream USB ports. Downstream USB is provided by a Via Labs VL805 chip - that supports two USB 2.0 ports and two USB 3.0 ports. This is connected to the BCM2711 SoC using a PCIe link, which is extremely fast. Therefore, the Pi 4 does not have the speed constraints of previous models.

**Comment by P33M** [comment]
All *USB2.0* ports on Pi 4 share the same 480mbit/s of bandwidth, because they are connected by an internal hub. Note that USB3.0 ports contain USB2.0 connections.

**Comment by maximumsomething** [comment]
> All _USB2.0_ ports on Pi 4 share the same 480mbit/s of bandwidth, because they are connected by an internal hub. Note that USB3.0 ports contain USB2.0 connections.

Are you sure? I can find nothing on the internet suggesting USB 2.0 bandwidth is shared through one internal port. Can you point me to an article with more details on the Pi 4's USB controller?

**Comment by pelwell** [comment]
You can treat @P33M's comments on the matter as gospel.

**Comment by P33M** [comment]
Look at your lsusb output above: all your connected USB devices are connected via 
```
 Bus 01.Port 1: Dev 1, Class=root_hub, Driver=xhci_hcd/1p, 480M
    |__ Port 1: Dev 2, If 0, Class=Hub, Driver=hub/4p, 480M
```
That is to say, a single 480mbit root port with a downstream 4-port hub.

**Comment by JamesH65** [comment]
> > This is also the case on Pi 4. There is an (internal) USB2.0 hub and all ports share the same upstream USB2.0 link.
> 
> The official docs say that's not the case:
> 
> https://www.raspberrypi.org/documentation/hardware/raspberrypi/usb/README.md#overview_pi4
> 
> > For the Pi 4, a fully-featured host controller drives the downstream USB ports. Downstream USB is provided by a Via Labs VL805 chip - that supports two USB 2.0 ports and two USB 3.0 ports. This is connected to the BCM2711 SoC using a PCIe link, which is extremely fast. Therefore, the Pi 4 does not have the speed constraints of previous models.

Docs appear to be 'wrong', or at least misleading - I'll update them.

**Comment by JamesH65** [comment]
See https://github.com/raspberrypi/documentation/pull/1390 for proposed change to docs.
