### ISSUE TITLE
FT5406 driver in rpi-5.4.y

### ISSUE THREAD

**Issue by alucryd** [raspberrypi/linux#3412]
Hi there,

Would it be possible to cherry pick the https://github.com/raspberrypi/linux/commit/fa2b33b614fead97a2eb8b950fb1c77e73f0eb28 commit into the rpi-5.4.y branch so we can make use of the official touchscreen  on distros like Alpine Linux for example ?

Also would you know if something like the edt-ft5x06 driver would work ?

**Comment by pelwell** [comment]
In rpi-5.0.y we switched to the upstream raspberrypi-ts driver (compatible string "raspberrypi,firmware-ts") - see https://github.com/raspberrypi/linux/blob/rpi-5.4.y/arch/arm/boot/dts/overlays/rpi-ft5406-overlay.dts.

**Comment by alucryd** [comment]
Oh, great, thanks a lot for the heads up!
