### ISSUE TITLE
Trying to patch with a better scheduler for interactive tasks (MUQSS)

### ISSUE THREAD

**Issue by vanfanel** [raspberrypi/linux#3414]
Hi there,

I have been trying to patch latest sources in the 5.4.y branch with this, in order to to some experiments on RetroArch and SDL2 latency improvement:

http://ck.kolivas.org/patches/5.0/5.4/5.4-ck1/patches/0001-MultiQueue-Skiplist-Scheduler-v0.196.patch

Thing is, patching goes well (no skipped hunks, all good according to `patch -p1 < patch`).
But trying to build I get this:
```

/home/manuel/src/linux/kernel/sched/MuQSS.c:6758:17: error: 'cpu_llc_shared_map' undeclared (first use in this function); did you mean 'sd_llc_shared'?
  return per_cpu(cpu_llc_shared_map, cpu);

/home/manuel/src/linux/kernel/sched/MuQSS.c:7071:85: error: 'cpu_llc_id' undeclared (first use in this function); did you mean 'sd_llc_id'?
    printk(KERN_DEBUG "MuQSS CPU %d llc %d RQ order %d RQ %d llc %d\n", cpu, per_cpu(cpu_llc_id, cpu), i,
```

Since there was interest in RT kernels on the Pi, I was wondering if someone had succeeded on this MUQSS scheduler patching as its VERY promising (the MUQSS scheduler uses hires timers and does not depend on 1000Hz!).
So, someone knows what the problem could be? I can not see these undeclared symbols anywere in the current 5.4.8 kernel code outside the arch/x86 specific code...
Maybe this MUQSS scheduler is designed for x86 kernels only?

**Comment by pelwell** [comment]
A brief search suggests they are x86-specific variables - I don't think this a cross-platform patch. In fact, the change to the kernel parameters documentation says:
```
+	rqshare=	[X86] Select the MuQSS scheduler runqueue sharing type.
+			Format: <string>
+			smt -- Share SMT (hyperthread) sibling runqueues
...
```
(note the `[X86]`).

**Comment by JamesH65** [comment]
This issue will be closed within 30 days unless further interactions are posted. If you wish this issue to remain open, please add a comment. A closed issue may be reopened if requested.
