### ISSUE TITLE
gpio.h

### ISSUE THREAD

**Issue by cleverca22** [raspberrypi/linux#342]
i was trying to compile code that worked on the 3.10 branch and i had moved it to the 3.6 branch, and i noticed an unexpected error

error: initializer element is not constant

when looking at the code, i found out, that there are 2 completely different implementations of gpio_to_irq, 3.10 uses #define which the compiler happily accepts
3.6 uses an inline function, which the compiler thinks isn't constant, causing the above error

any reason against putting the 3.10 version of gpio_to_irq in the 3.6 branch?

arch/arm/mach-bcm2708/include/mach/gpio.h

**Comment by popcornmix** [comment]
No, that won't happen. Your code can do:
`#if LINUX_VERSION_CODE < KERNEL_VERSION(3,10,0)`
if you want to support both versions.

**Comment by cleverca22** [comment]
is there any special reason why 3.6 and 3.10 have to do it differently?

**Comment by popcornmix** [comment]
That's a decision for the upstream linux kernel, not for us.
I can't modify the 3.6 kernel to use the 3.10 API, as that could break lots of existing code developed on 3.6.

**Comment by cleverca22** [comment]
ah, ok, i'll just #if it out like you said
