### ISSUE TITLE
Getting error 404 from mirror 

### ISSUE THREAD

**Issue by Igmu** [raspberrypi/linux#3423]
I am getting Error 404 for mirror http://mirrors.syringanetworks.net/raspbian/raspbian/ buster main when using first "sudo apt upgrade" from clean OS. All other default repostories work fine. Changing //etc/apt/sources.list to alternate mirror sourced from https://www.raspbian.org/RaspbianMirrors resolved error.

**Comment by XECDesign** [comment]
Not a kernel issue.

https://bugs.launchpad.net/raspbian/
