### ISSUE TITLE
lirc-gpio-tx adds a parasitic pulse at the end of the transmit sequence

### ISSUE THREAD

**Issue by kot-begemot-uk** [raspberrypi/linux#3427]
Lirc gpio-tx adds an extra long pulse at the end of a sequence.

Example - this is what should be going out as seen by mode2 on a different machine:

...
space 423
pulse 417
pulse 19325

This is what is actually coming out:

space 420
pulse 19920
pulse 128199 

The data before that in the beginning of the sequence is transmitted correctly.

**Comment by kot-begemot-uk** [comment]
Tested on buster with Linux raspberrypi 4.19.75+ #1270 Tue Sep 24 18:38:54 BST 2019 armv6l GNU/Linux

**Comment by pelwell** [comment]
The gpio-ir-tx module is an unmodified upstream file that is not specific to Raspberry Pi. Please report the problem upstream.
