### ISSUE TITLE
GPSD does not listen on other addresses even -G used

### ISSUE THREAD

**Issue by ktuulos** [raspberrypi/linux#3455]
**Describe the bug**
GPSD does not listen to other addresses, i.e. it does not serve clients on network, even though -G is defined in /etc/default/gpsd.

Netstat output is as follows:
```
user@mydevice:~ $ netstat -l | grep gps
tcp        0      0 localhost:gpsd          0.0.0.0:*               LISTEN     
tcp6       0      0 localhost:gpsd          [::]:*                  LISTEN     
unix  2      [ ACC ]     STREAM     LISTENING     316956   /var/run/gpsd.sock
```
And ps -ax shows as follows:
```
32172 ?        S<s    0:00 /usr/sbin/gpsd -G /dev/ttyUSB0
```

If GPSD is started from command line, then it serves network clients fine. Here is an example:
```
sudo /usr/sbin/gpsd -N -G /dev/ttyUSB0 -F /var/run/gpsd.sock
```
Let's check this on another terminal:
```
user@mydevice:~ $ netstat -l | grep gps
tcp        0      0 0.0.0.0:gpsd            0.0.0.0:*               LISTEN     
tcp6       0      0 [::]:gpsd               [::]:*                  LISTEN     
unix  2      [ ACC ]     STREAM     LISTENING     317863   /var/run/gpsd.sock
user@mydevice:~ $ ps -ax | grep gps
32280 pts/0    S+     0:00 sudo /usr/sbin/gpsd -N -G /dev/ttyUSB0 -F /var/run/gpsd.sock
32285 pts/0    S<+    0:00 /usr/sbin/gpsd -N -G /dev/ttyUSB0 -F /var/run/gpsd.sock
32314 pts/2    S+     0:00 grep --color=auto gps
```

**System**
* Which model of Raspberry Pi? 
Pi3B+

* Which OS and version (`cat /etc/rpi-issue`)?
```
Raspberry Pi reference 2019-07-10
Generated using pi-gen, https://github.com/RPi-Distro/pi-gen, 175dfb027ffabd4b8d5080097af0e51ed9a4a56c, stage2
```

* Which firmware version (`vcgencmd version`)?
```
Sep 24 2019 17:37:19 
Copyright (c) 2012 Broadcom
version 6820edeee4ef3891b95fc01cf02a7abd7ca52f17 (clean) (release) (start)
```

* Which kernel version (`uname -a`)?
```
Linux mydevice 4.19.75-v7+ #1270 SMP Tue Sep 24 18:45:11 BST 2019 armv7l GNU/Linux
```

* GPSD package version (`dpkg-query -W`)?
```
gpsd 3.17-7
```

**Additional context**
This problem is most likely due to systemd messing around with listen socket, as -G option worked fine in Jessie.

This problem seems to be also in Ubuntu 18.04, at least the netstat produces the same output there. I don't have USB GPS receiver on my desktop computer, so I can't test this on Ubuntu.

**Comment by pelwell** [comment]
I'm sympathetic to your problem, but this isn't the place to report it. We have a forum for Raspbian bugs, but as this issue is also present in Ubuntu it falls outside our remit.

Your best option would be to open an issue in the [Interfacing forum](https://www.raspberrypi.org/forums/viewforum.php?f=44) and hope that somebody else has found a solution.
