### ISSUE TITLE
USB devices causing "XactErr without NYET/NAK/ACK"

### ISSUE THREAD

**Issue by thom-nic** [raspberrypi/linux#35]
I have two USB devices that fail to work when plugged into any of the onboard USB ports.  The following appears in dmesg:

```
DEBUG:handle_hc_chhltd_intr_dma:: XactErr without NYET/NAK/ACK
```

One is the aluminum Apple USB keyboard, the other is a realtek wifi adapter.  Both of the devices work if plugged into a powered USB hub (I haven't tried when the hub is not AC powered.)  Some folks are suggesting that this is not a power problem though, that it could be a USB issue that is inadvertently solved when a hub is used.  

So - is this a power issue or a USB timing issue?

**Comment by jstsch** [comment]
I have seen the same errors quite often. I think this is similar to issue #29 and I doubt it is power related.

**Comment by kghost** [comment]
I have tested, this is _not_ power issue, my powered hub don't drain any power from pi (measured 0V over usb fuse), still got this error.

On the contract, when plugin the usb device on pi directly, it drains 80-100mA from pi (measured 0.4V over usb fuse), but works perfect

**Comment by FiloSottile** [comment]
I am affected too, with a rt73usb wireless dongle over a powered hub.

**Comment by FiloSottile** [comment]
For me it happened during boot or as soon as the device was connected and never stopped. Now preloading `usbcore` (from `/etc/modules`) it shows up for a couple of seconds and then everything get working (also the Wi-Fi).

**Comment by FiloSottile** [comment]
Nevermind, it stopped working as soon as I tried to connect to a network (scanning was working). Now `dmesg` is filled up with these errors and everything that tries to use the device freeze until I plug it out.

**Comment by popcornmix** [comment]
Can you try with latest firmware and with:
dwc_otg.microframe_schedule=1
in cmdline.txt

**Comment by popcornmix** [comment]
Is this still a problem with latest firmware?

**Comment by ghollingworth** [comment]
There was no further report of this case
