### ISSUE TITLE
Kernel crash: BTRFS on LUKS encrypted partition

### ISSUE THREAD

**Issue by kirgene** [raspberrypi/linux#350]
I'm using kernel 3.10.4 (revision 9ab62f0c8d6b945d78d031e74e491ac5619783ae).
Also I have LUKS encrypted BTRFS rootfs partition.

But when I boot my Pi I'm getting kernel crash (the image is attached).
![crash1](https://f.cloud.github.com/assets/1386147/909251/dae63f82-fdb8-11e2-8118-73672dc7b6a1.jpeg)

**Comment by popcornmix** [comment]
Does this work on 3.9 or 3.6 kernels?

**Comment by kirgene** [comment]
It works on 3.6 and 3.9 kernels without problems.

**Comment by popcornmix** [comment]
Sounds like an upstream bug. Might be worth searching for others with the same problem, or keep an eye out for updates to 3.10 kernel tree.

**Comment by kirgene** [comment]
Just checked this scenario on x86 platform and everything works fine.
So the problem is in raspberry branch.

**Comment by Ruffio** [comment]
@kirgene do you still experience this issue? If not, please close this issue. Thanks.
