### ISSUE TITLE
RTL8188EU driver outdated

### ISSUE THREAD

**Issue by wewa00** [raspberrypi/linux#3521]
Hello,

lots of Raspbian users are struggling with the RTL8188EU driver because the one shipped with Raspbian is not working correctly (e.g. it is not working in combination with hostapd). Therefore MrEngman is providing pre-compiled versions of the RTL8188EU driver based on the actual [sources from lwfinger](https://github.com/lwfinger/rtl8188eu). MrEngmen describes the installation of this driver [here](https://www.raspberrypi.org/forums/viewtopic.php?f=28&t=62371&sid=71b1e3696b36109c83d31260b3cff9d4#p462982) and how the driver is compiled is described [here](https://www.raspberrypi.org/forums/viewtopic.php?f=28&t=62371&sid=71b1e3696b36109c83d31260b3cff9d4#p467026).

Please integrate the up-to-date version of the RTL8188EU driver from https://github.com/lwfinger/rtl8188eu so that we do not need to struggle to get the driver working again every time we update the kernel.

Best regards
wewa

**Comment by popcornmix** [comment]
The drivers need to be submitted upstream to the linux kernel.
If they are merged upstream we'll support them. If not, we won't.
