### ISSUE TITLE
Kernel panic -- not syncing : attempt to kill init!  exitcode=0×00000100

### ISSUE THREAD

**Issue by babahadjsaid** [raspberrypi/linux#3522]
![received_253477065787702](https://user-images.githubusercontent.com/45628941/77928841-d4dfec00-72a0-11ea-8b26-3f6c0656757a.jpeg)
Can any one help 
The problem occur because of unexpected cut of power here is a picture of the bug

**Comment by JamesH65** [comment]
Probably a corrupted SD card. One option is, using another device, copy any important content then reimage the SD card.

**Comment by pelwell** [comment]
That link is broken - try again. This isn't the best place to report user-generated errors like this - the [Raspberry Pi forums](https://raspberrypi.org/Forums) are intended for that - but if it's obvious I'll tell you.

**Comment by babahadjsaid** [comment]
It's a laptop related problem it's not an SD card sir

**Comment by pelwell** [comment]
You appear to be lost - this is a place to report problems in the Raspberry Pi Linux kernel.

**Comment by babahadjsaid** [comment]
It's a linux problem didn't you see that the os is kali linux

**Comment by pelwell** [comment]
"didn't you see that the os is kali linux" - no, because you've only just fixed the broken image (there are no notifications for that).

Anyway "laptop" != "Raspberry Pi".
