### ISSUE TITLE
Using 5.4 LTS instead of current default 4.19

### ISSUE THREAD

**Issue by kraj** [raspberrypi/linux#3525]
This is a simple question on plans for switching to 5.4 kernel. Are there plans to use 5.4 anytime soon, or do you expect to stay with 4.19 until everything is upstreamed and then direct users and distro builders to use mainline.

**Comment by popcornmix** [comment]
5.4 is the next kernel we're switching to. There will be test releases (next branch of rpi-update in a couple of weeks, with moves to master branch of rpi-update and apt in due course, depending on issues reported).
