### ISSUE TITLE
linux/types.h missing error 

### ISSUE THREAD

**Issue by mvphatak** [raspberrypi/linux#354]
In file included from scripts/sortextable.c:31:
/Volumes/raspberrypi-kernel-3.8/src/tools/include/tools/be_byteshift.h:4:25: error: linux/types.h: No such file or directory

**Comment by licaon-kter** [comment]
Cross compiling are you? you might not have the gcc dev kit installed. like: http://elinux.org/Rpi_kernel_compilation

**Comment by mvphatak** [comment]
Yes I am. However I was able to successfully cross compile 3.6. I am seeing issue with only 3.8 :(

**Comment by licaon-kter** [comment]
Any reason not to jump ship to 3.9 or 3.10 since 3.8 has not been/will not be updated ?

**Comment by mvphatak** [comment]
no specific reason, thanks will go for 3.10
