### ISSUE TITLE
DTS missing compatible string for pl011 on linux 5.4

### ISSUE THREAD

**Issue by pvizeli** [raspberrypi/linux#3576]
The new device tree from Linux 5.4 branch missing the compatible string fro pl011 like the 4.19 branch. I created a patch for my self, but feel free to merge it into the 5.4 branch:
https://github.com/home-assistant/operating-system/blob/dev/buildroot-external/board/raspberrypi/patches/linux/0001-rpi-dts-allow-uboot-find-serial.patch

U-boot use that to get the right serial driver in which support some features added by firmware dynamic available.

**Comment by pelwell** [comment]
That compatible string isn't defined by any drivers - I'm not sure why Eric used it - and it's disappeared from the DTS in newer kernel versions, and we're trying to make as few changes as possible from the upstream sources, so U-boot will have to find some other mechanism.
