### ISSUE TITLE
Multicast routing requires kernel options

### ISSUE THREAD

**Issue by vk5tu** [raspberrypi/linux#358]
Multicast routing is not possible using the stock image as bcmrpi_defconfig does not have the necessary kernel options enabled. These are:

CONFIG_IP_MROUTE=y
CONFIG_IP_MROUTE_MULTIPLE_TABLES=y
CONFIG_IP_PIMSM_V1=y
CONFIG_IP_PIMSM_V2=y
CONFIG_IPV6_MROUTE=y
CONFIG_IPV6_MROUTE_MULTIPLE_TABLES=y
CONFIG_IPV6_PIMSM_V2=y

Note that the RasPi can act as a multicast host without these options, but it cannot forward multicast.

**Comment by vk5tu** [comment]
Forum discussion at http://www.raspberrypi.org/phpBB3/viewtopic.php?f=66&t=51704

**Comment by popcornmix** [comment]
As these option are "=y" rather than modules, I'll need some evidence that the memory cost is minimal.
Can you show the output of "free" after boot with and without these options enabled.

**Comment by J-Rey** [comment]
Relaying response from the forum thread:

<pre>
Here is output from "free -h" called from /etc/rc.local:
without mroute config:
             total       used       free     shared    buffers     cached
Mem:          184M        42M       142M         0B       7.7M        19M
-/+ buffers/cache:        14M       169M
Swap:          99M         0B        99M
with mroute config:
             total       used       free     shared    buffers     cached
Mem:          184M        42M       141M         0B       7.8M        19M
-/+ buffers/cache:        14M       169M
Swap:          99M         0B        99M</pre>

**Comment by popcornmix** [comment]
These options should be added in latest rpi-update firmware.

**Comment by popcornmix** [comment]
These should be present now. Please test and close if happy.
