### ISSUE TITLE
vncserver not working

### ISSUE THREAD

**Issue by bobypierre** [raspberrypi/linux#3582]
Hello, 

When I do: 
vncserver
I have in return :
vncserver: error while loading shared libraries: libbcm_host.so: cannot open shared object file: No such file or directory

What's happen please?

**Comment by pelwell** [comment]
Please provide some basic information:

1. What type of Raspberry Pi are you using?

2. Which OS (e.g. Raspbian) are you running? `cat /etc/os-release` may provide the information.

3. Which kernel versions? The output of `uname -a` will tell us that.

**Comment by bobypierre** [comment]
yes.
1- Raspberry PI 3
2- PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
3- Linux raspberrypi 4.19.97-v7+ #1294 SMP Thu Jan 30 13:15:58 GMT 2020 armv7l GNU/Linux
- I am using the RPI as server via SSH

**Comment by bobypierre** [comment]
hello,

I have resolve the issue in installing vnc4server package.
