### ISSUE TITLE
Some bridging scenarios difficult without dummy ethernet interface

### ISSUE THREAD

**Issue by vk5tu** [raspberrypi/linux#359]
The "dummy" ethernet interface is useful for some ethernet bridging scenarios. That module is missing from the stock RasPi kernel as CONFIG_DUMMY is not set.

Setting
CONFIG_DUMMY=m
will allow dummy ethernet interfaces to be created, and thus used as targets for complex ethernet bridging designs.

Forum discussion at http://www.raspberrypi.org/phpBB3/viewtopic.php?f=36&t=52926

**Comment by popcornmix** [comment]
This is enabled it latest update.
