### ISSUE TITLE
kea-admin error directly after installing, packages up to date

### ISSUE THREAD

**Issue by DirkLaurenz** [raspberrypi/linux#3624]
Raspbian Version: 10

Steps to reproduce:
apt-get install kea-admin
root@dc01:~# kea-admin
/usr/sbin/kea-admin: 39: .: Can't open /build/isc-kea-NiDGuv/isc-kea-1.4.0.P1/obj-arm-linux-gnueabihf/../src/bin/admin/admin-utils.sh

**Comment by pelwell** [comment]
The kea-admin script is looking for /usr/share/kea/scripts/admin-utils.sh (and other things under /usr/share/kea), but the Debian package (which I doubt we've altered) is installed to /usr/share/kea-admin.

This isn't a kernel issue, so this isn't the right place to report it. @XECDesign Is this possibly a Raspbian-specific problem, or should this go straight to Debian?

**Comment by DirkLaurenz** [comment]
Hello,

 

i’m sorry, thougth this is the raspbian bug report system.

Where should i post it?

 

Von: Phil Elwell <notifications@github.com> 
Gesendet: Dienstag, 19. Mai 2020 21:41
An: raspberrypi/linux <linux@noreply.github.com>
Cc: DirkLaurenz <dirk@laurenz.ws>; Author <author@noreply.github.com>
Betreff: Re: [raspberrypi/linux] kea-admin error directly after installing, packages up to date (#3624)

 

The kea-admin script is looking for /usr/share/kea/scripts/admin-utils.sh (and other things under /usr/share/kea), but the Debian package (which I doubt we've altered) is installed to /usr/share/kea-admin.

This isn't a kernel issue, so this isn't the right place to report it. @XECDesign <https://github.com/XECDesign>  Is this possibly a Raspbian-specific problem, or should this go straight to Debian?

**Comment by XECDesign** [comment]
Raspbian doesn't seem to clear packages that have been removed from a given Debian release.

kea-admin is not meant to be available Buster. https://packages.debian.org/search?keywords=kea-admin

If you would like to report it, the place to do it would be https://bugs.launchpad.net/raspbian/

**Comment by pelwell** [comment]
Thanks, @XECDesign.
