### ISSUE TITLE
Code for RTL8188EU available

### ISSUE THREAD

**Issue by lwfinger** [raspberrypi/linux#363]
I have just committed the code for an RTL8188EU driver to the linux-staging tree, and it was accepted by GregKH.

I have also modified it to apply to the 3.6.y branch of this repo, and I would like to submit those patches to the repo. What would be the best way to do so?

Thanks,  Larry

**Comment by popcornmix** [comment]
I assume there is no overlap between your driver and the existing rtl8192cu and rtlwifi drivers?

Can you point me at the upstream linux commit? If it applies cleanly, I can just cherry-pick it.

**Comment by lwfinger** [comment]
This is a totally new driver. It has no overlap with any driver presently in the kernel. When I stripped out the KERNELVERSION tests, that made the new driver work only for kernels 3.6 and newer. It will not work on the 3.2.27 branch.

The upstream commit is at git://git.kernel.org/pub/scm/linux/kernel/git/gregkh/staging.git, but that version will not apply cleanly. I cloned raspberrypi/linux and pushed my changes into the rpi-3.6.y branch at
http://github.com/lwfinger/linux.

I have also modified the rpi-3.8.y branch there, but ignore that code for the moment as the new driver has not yet been tested. I will also generate and test on the 3.9 and 3.10 branches ASAP.

BTW, are the standard .config files for the 3.8, 3.9, and 3.10 branches available somewhere. I tried to build 3.8, but the 39 different varieties of ARM CPUs stopped me as I did not know which to select.

**Comment by popcornmix** [comment]
arch/arm/config/bcmrpi_defconfig
is the .config used to build official firmware.

Can you provide a link to the commit, and any upstream discussion?

**Comment by lwfinger** [comment]
The submission can be found at http://driverdev.linuxdriverproject.org/pipermail/driverdev-devel/2013-August/thread.html. There were a total of 33 RFC/RFT submissions. The only discussion was by GregKH who stated "Looks good enough to me, now applied, thanks for doing this work!" and one off-list message from Dan Carpenter asking why I split it into separate hunks rather than putting all the new code into one submission. My reply was that I did it for review purposes.

**Comment by popcornmix** [comment]
I assume it should be appearing on:
https://git.kernel.org/cgit/linux/kernel/git/next/linux-next.git/
and then
https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/

I'm not sure what has to happen between gregkh's tree and next or torvalds tree.
I suspect that may require more review.

**Comment by lwfinger** [comment]
Greg will let it reside in staging for a while and then push to next and ultimately to the torvalds mainline tree. From my previous experience, there will be no further review. I would expect the driver to be in the 3.12 kernel.

**Comment by Ruffio** [comment]
@lwfinger has this issue been resolved? If yes, then please close this issue.
