### ISSUE TITLE
Not tagged: raspberrypi-kernel 1.20200512-2

### ISSUE THREAD

**Issue by Ve2mrx** [raspberrypi/linux#3643]
The package **raspberrypi-kernel 1.20200512-2** is available on the Raspberry Pi OS APT repo, but is not tagged for cloning. Custom build not possible (yet).

Solution: Please Tag it on GitHub.

Nice work with the new Pi4! 8GB will arrive soon :-)
Thanks,
Martin

**Comment by sunfic** [comment]
I have similar issue. trying to build with  raspberrypi-kernel 1.20200512-2.

@Ve2mrx Can you guide me how you download the source of raspberrypi-kernel 1.20200512-2 right now? thanks

**Comment by Ve2mrx** [comment]
> @Ve2mrx Can you guide me how you download the source of raspberrypi-kernel 1.20200512-2 right now? thanks

@sunfic All I can suggest is to try to compile from Git branch rpi-4.19.y and wish for the best until the release is tagged.

**Comment by sunfic** [comment]
@Ve2mrx Thanks, seems right now it is 4.19-122 and I got some bugs in it. Hope we can get formal 1.20200512-2 release.

**Comment by popcornmix** [comment]
@XECDesign is this something you normally do?

**Comment by XECDesign** [comment]
Tags added

**Comment by sunfic** [comment]
Thanks,

Another question
raspberrypi-kernel_1.20200512-2 and raspberrypi-kernel_1.20200601-1 are identical after I compared them. Why there are two tags there? anything updated?

**Comment by XECDesign** [comment]
The tags correspond to the package version they come from in apt. The kernel and firmware both come from the same source package. If the firmware i updated, the kernel package gets a new version as well, even if the content doesn't change.

**Comment by sunfic** [comment]
@XECDesign 
Thank you very much for you reply.

**Comment by popcornmix** [comment]
@Ve2mrx okay to close?

**Comment by Ve2mrx** [comment]
Sure!
