### ISSUE TITLE
Audio output lost if HDMI device lost during playback

### ISSUE THREAD

**Issue by tghewett** [raspberrypi/linux#365]
If playing to the HDMI output and the HDMI device is lost (switched off, disconnected etc.), it is no longer possible to play even to the analogue output (no audio is heard) until the HDMI device is restored. If the HDMI device is lost while playing to the analogue device then there is no problem.

When the problem occurs, audio is still taken from the file as if it is being played, but it isn't heard.

Both the OMX and ALSA playback paths are affected.

**Comment by popcornmix** [comment]
Does hdmi_force_hotplug in config.txt affect this?

**Comment by tghewett** [comment]
It was tested without hdmi_force_hotplug existing in config.txt, nor hdmi_safe which implies a value for hdmi_force_hotplug, not sure what the defaults are but it doesn't seem to make any difference.

**Comment by Ruffio** [comment]
@tghewett has this issue been resolved? If yes, then please close this issue.

**Comment by tghewett** [comment]
I see no evidence that any work has been done to fix it. By continuing to use older /opt/vc libraries I do not see the problem, it is masked. However if it is still a problem I imagine someone else will report it.
