### ISSUE TITLE
Why are there different source releases for arm and arm64?

### ISSUE THREAD

**Issue by g-p-n** [raspberrypi/linux#3662]
This is more of a question than a bug/issue report.

In the [releases](https://github.com/raspberrypi/linux/releases) page, there are two archives. Both are made with or based off the exact same commit hash [971a2bb14b459819db1bda8fcdf953e493242b42](https://github.com/raspberrypi/linux/commit/971a2bb14b459819db1bda8fcdf953e493242b42).

- [raspberrypi-kernel_1.20200601+arm64-1](https://github.com/raspberrypi/linux/releases/tag/raspberrypi-kernel_1.20200601%2Barm64-1)
- [raspberrypi-kernel_1.20200527-1](https://github.com/raspberrypi/linux/releases/tag/raspberrypi-kernel_1.20200527-1)

The contents of both the archives are the same.

Given that these are source releases, what is the significance of naming one with arm64 suffix?

**Comment by pelwell** [comment]
The releases page doesn't list archives - they are tags, placed there when a Raspberry Pi OS kernel package release is made, indicating what was the top of tree at that point. Each tag is essentially just an association of a name and a commit hash. GitHub is capable of generating an archive of the tree at any commit you like, but it does so on demand (probably with some degree of caching), so there is almost no overhead associated with a tag.

The new 64-bit Raspberry Pi OS is completely independent of the 32-bit OS, although there is obviously a lot of commonality - releases can be made at different times and from different commits, so it is necessary to have tags for each OS. On this occasion we used the same kernel commit for both OSs, but this is unlikely to always be the case.
