### ISSUE TITLE
Cannot activate quota, not supported in kernel

### ISSUE THREAD

**Issue by Nardol** [raspberrypi/linux#367]
Hello,
When I do sudo apt-get install quota, I have the following error:
[ ok ] Checking quotas...done.
[....] Turning on quotas...quotaon: using //aquota.group on /dev/root [/] : No such process
quotaon: Quota format not supported in kernel.
quotaon: using //aquota.user on /dev/root [/] : No such process
quotaon: Quota format not supported in kernel.
quotaon: using /mnt/ssd1/aquota.group on /dev/sda1 [/mnt/ssd1] : No such process
quotaon: Quota format not supported in kernel.
quotaon: using /mnt/ssd1/aquota.user on /dev/sda1 [/mnt/ssd1] : No such process
quotaon: Quota format not supported in kernel.
quotaon: using /mnt/ssd2/aquota.group on /dev/sda2 [/mnt/ssd2] : No such process
quotaon: Quota format not supported in kernel.
quotaon: using /mnt/ssd2/aquota.user on /dev/sda2 [/mnt/ssd2] : No such process
quotaon: Quota format not supported in kernel.
invoke-rc.d: initscript quota, action "start" failed.
I seen a post which repport this issue, but no solutions:
http://www.raspberrypi.org/phpBB3/viewtopic.php?f=27&t=28392

I am not sure it is relative to raspbian or not so I posted it to raspbian to at:
https://bugs.launchpad.net/raspbian/+bug/1218865

Some informations:
pzajda@rsp1:~$ uname -a
Linux rsp1 3.6.11+ #528 PREEMPT Tue Aug 20 00:25:53 BST 2013 armv6l GNU/Linux
pzajda@rsp1:~$ sudo dpkg -s libc6 | grep ^Version
Version: 2.13-38+rpi2

**Comment by popcornmix** [comment]
Added the QFMT_V1 and QFMT_V2 modules in latest update.
Please test.

**Comment by Nardol** [comment]
Hi,

Le 08/09/2013 18:59, popcornmix a écrit :

> Added the QFMT_V1 and QFMT_V2 modules in latest update.
> Please test.

OK, it works well now.

Thanks!

## 

Patrick ZAJDA
patrick@zajda.fr
Skype : gansta93
MSN : patrickzajda@hotmail.com

**Comment by acastano59** [comment]
Hi,

I have the same problem, 

# apt-get install quota -y

Reading package lists... Done
Building dependency tree  
Reading state information... Done
The following packages were automatically installed and are no longer required:
  g++-4.6 libstdc++6-4.6-dev
Use 'apt-get autoremove' to remove them.
Suggested packages:
  libnet-ldap-perl default-mta mail-transport-agent
The following NEW packages will be installed:
  quota
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/614 kB of archives.
After this operation, 1,373 kB of additional disk space will be used.
Preconfiguring packages ...
Selecting previously unselected package quota.
(Reading database ... 67494 files and directories currently installed.)
Unpacking quota (from .../quota_4.00-4+deb7u1_armhf.deb) ...
Processing triggers for man-db ...
Setting up quota (4.00-4+deb7u1) ...
[ ok ] Checking quotas...done.
[....] Turning on quotas...quotaon: using /home/aquota.user on /dev/sda [/home]: No such process
quotaon: Quota format not supported in kernel.
invoke-rc.d: initscript quota, action "start" failed.
dpkg: error processing quota (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 quota
E: Sub-process /usr/bin/dpkg returned an error code (1)

uname -a
Linux noname 3.6.11+ #538 PREEMPT Fri Aug 30 20:42:08 BST 2013 armv6l GNU/Linux

**Comment by Nardol** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

Hi,

With the latest firmware, this problem doesn't occurs anymore...

Patrick
Le 11/12/2013 10:10, acastano59 a écrit :

> Hi,
> 
> I have the same problem,
> 
> # apt-get install quota -y Reading package lists... Done Building
> 
> dependency tree Reading state information... Done The following
> packages were automatically installed and are no longer required: 
> g++-4.6 libstdc++6-4.6-dev Use 'apt-get autoremove' to remove
> them. Suggested packages: libnet-ldap-perl default-mta
> mail-transport-agent The following NEW packages will be installed: 
> quota 0 upgraded, 1 newly installed, 0 to remove and 0 not
> upgraded. Need to get 0 B/614 kB of archives. After this operation,
> 1,373 kB of additional disk space will be used. Preconfiguring
> packages ... Selecting previously unselected package quota. 
> (Reading database ... 67494 files and directories currently
> installed.) Unpacking quota (from
> .../quota_4.00-4+deb7u1_armhf.deb) ... Processing triggers for
> man-db ... Setting up quota (4.00-4+deb7u1) ... [ ok ] Checking
> quotas...done. [....] Turning on quotas...quotaon: using
> /home/aquota.user on /dev/sda [/home]: No such process quotaon:
> Quota format not supported in kernel. invoke-rc.d: initscript
> quota, action "start" failed. dpkg: error processing quota
> (--configure): subprocess installed post-installation script
> returned error exit status 1 Errors were encountered while
> processing: quota E: Sub-process /usr/bin/dpkg returned an error
> code (1)
> 
> uname -a Linux noname 3.6.11+ #538 PREEMPT Fri Aug 30 20:42:08 BST
> 2013 armv6l GNU/Linux
> 
> --- Reply to this email directly or view it on GitHub: 
> https://github.com/raspberrypi/linux/issues/367#issuecomment-30304515
> 
> ---
> 
> Patrick ZAJDA
> Skype : gansta93
> -----BEGIN PGP SIGNATURE-----
> Version: GnuPG v2.0.22 (MingW32)
> Comment: Using GnuPG with Thunderbird - http://www.enigmail.net/

iQEcBAEBAgAGBQJSqDR5AAoJEKPVT2DeSPb4Mn0IAI/c8M3yqCDTluPER8Ln9w+O
0XYhFUbUQbOqTFldG8izKE8qenPJ0M4pWcZ64p2fODgIRdEDA4rXJSslcnqdlCw3
hyQwd4vd0payrURdcjoM5XJatP6abIJphwj4c20wnwMsvcGcIKjFlgpiL7sQGZ+6
kkMWKPwiBvJWYNwpSrd0Vw+PQFjluiKG5In8kVhLc/XTupqQbL0ybW91OABaHnzz
Bf42Lc9agv9hmwG0doCEYG3tkwmIs+slKGXTd0qjD1rXNrtd7YVTA0v5woefGL17
5D5RzNquEF99KqtuSp0IUA7Uwq9SErh0VKUSejrm78lKfKXhNbGfjGs7dbx4cwg=
=ZS/R
-----END PGP SIGNATURE-----

**Comment by acastano59** [comment]
Shame on me!! I did not reboot the raspberry, once I did it, it works like
a charm.

Sorry and have a nice day!

---

Alejandro Castaño Fernández
