### ISSUE TITLE
ADS1015 overlay is loading ads1015 and ti-ads1015

### ISSUE THREAD

**Issue by phryniszak** [raspberrypi/linux#3674]
ti-ads1015 is registered with the same alias as ads1015 so kernel is trying to load both the same time

**Comment by pelwell** [comment]
The ads1015 driver is absent in 5.4 and later - the removing commit says:
```
    hwmon: Remove ads1015 driver
    
    A driver for ADS1015 with more functionality is available in the iio
    subsystem.
    
    Remove the hwmon driver as duplicate. If the chip is used for hardware
    monitoring, the iio->hwmon bridge should be used.
```
The problem will disappear in the switch to 5.4 (which should happen soon), but in the meantime you can use a blacklist file to prevent the old driver from being loaded:
```
$ sudo sh -c "echo blacklist ads1015 > /etc/modprobe.d/blacklist-ads1015.conf"
```
