### ISSUE TITLE
DAPM with volatile I2C bus on sound card

### ISSUE THREAD

**Issue by AMuszkat** [raspberrypi/linux#3678]
Hi!

I'm looking for a way to enable and disable  an IC of a sound card( a HAT in this case) when playing and not playing audiorespectively. The problem is that the IC I2C bus does not work when power is disabled. IS there an way to achieve this? I can't find any examples on the codecs or sound card drivers.

Best,
Ariel

**Comment by pelwell** [comment]
This isn't the right place to ask a general question like that, but if it were you would need to provide a clearer description of exactly what you are trying to achieve and the limitations of the devices in question (including part numbers). Try opening on issue on the Interfacing forum (https://www.raspberrypi.org/forums/viewforum.php?f=44) - create a new topic, but perhaps add a note to the end of the I2S Sound thread (https://www.raspberrypi.org/forums/viewtopic.php?f=44&t=8496), and hope that @HiassofT sees it.  ;-)
