### ISSUE TITLE
Upper level translation table Access permission 

### ISSUE THREAD

**Issue by raks8877** [raspberrypi/linux#3679]
Hi,

I just want to get some clarification regarding translation table access permission (in particular write protection).
To protect the page, there are defined macros in https://github.com/raspberrypi/linux/blob/rpi-4.19.y/arch/arm64/include/asm/pgtable-hwdef.h with PTE_RDONLY and PMD_SECT_RDONLY.

My question is how can we make upper levels (pgd, pud, pmd, pte) of translation table write protected?

**Comment by pelwell** [comment]
This is not the place to ask general questions about the Linux internals - try the linux-mm mailing list: https://linux-mm.org/
