### ISSUE TITLE
Why is the sound driver a loadable module?

### ISSUE THREAD

**Issue by keylevel** [raspberrypi/linux#37]
Given that the onboard sound system can't be changed, wouldn't it make sense for the sound driver to be built-in module? It seems as if this would make sound easier to use for less experienced users.

One thing I have noticed if it is configured as built-in, it currently loads after the ALSA system and therefore isn't ready soon enough at boot time.

**Comment by huceke** [comment]
It makes sense. Not all aplications use alsa to output sound. For example XBMC uses OpenMAX.

**Comment by keylevel** [comment]
Ah, good point.

However, I still think loading of the driver should take place before the ALSA layer if they are configured as built-in.

**Comment by asb** [comment]
keylevel, could you explain what problems you're having? On the latest wheezy test image http://www.raspberrypi.org/phpBB3/viewtopic.php?f=50&t=8071 snd-bcm2835 is loaded by default, and seems to work as expected.

**Comment by keylevel** [comment]
I'm building my own disto using Yocto. It seems to work ok when I build the kernel with the driver as a builtin, even though it's not ready when the ALSA layer loads.
