### ISSUE TITLE
linux-3.10.y won't compile - ext4 problem.

### ISSUE THREAD

**Issue by coRpTitan** [raspberrypi/linux#370]
Hello,

Today I tried to download and use kernel source linux-3.10.y. During compilation I received following error:

make[2]: **\* No rule to make target fs/ext4/resize.o, needed by fs/ext4/ext4.o.  Stop.
make[1]: **\* [fs/ext4] Error 2
make: **\* [fs] Error 2

Steps to re-produce:
1] Download zip GIT snapshot.
2] Unpack it on Raspberry
3] #zcat /proc/config.gz > .config
4] make menuconfig    # Just go there and save files again to let gui update it for new kernel version.
5] make

I'm not attaching my .config as I think it's something missing in Makefile and is not related to .config .

Git is showing me that I'm using snapshot with last latest commit c1af7c6db3 .
sha1sum of rpi-3.10.y.zip is:

`cd937ff8e74416e43ebb49a9625463c48ea07797`

**Comment by popcornmix** [comment]
You get the default config with

```
make ARCH=arm bcmrpi_defconfig
```

Does that work for you?

**Comment by coRpTitan** [comment]
I have same result:

rpi linux # make mrproper
  CLEAN   .
  CLEAN   arch/arm/kernel
  CLEAN   kernel
  CLEAN   .tmp_versions
  CLEAN   scripts/basic
  CLEAN   scripts/kconfig
  CLEAN   scripts/mod
  CLEAN   scripts
  CLEAN   include/config include/generated arch/arm/include/generated
  CLEAN   .config .config.old .version include/generated/uapi/linux/version.h
rpi linux # make ARCH=arm bcmrpi_defconfig
  HOSTCC  scripts/basic/fixdep
  HOSTCC  scripts/kconfig/conf.o
  SHIPPED scripts/kconfig/zconf.tab.c
  SHIPPED scripts/kconfig/zconf.lex.c
  SHIPPED scripts/kconfig/zconf.hash.c
  HOSTCC  scripts/kconfig/zconf.tab.o
  HOSTLD  scripts/kconfig/conf

 configuration written to .config

rpi linux # make
...
...
...
  CC      fs/ext4/balloc.o
  CC      fs/ext4/bitmap.o
  CC      fs/ext4/dir.o
  CC      fs/ext4/file.o
  CC      fs/ext4/fsync.o
  CC      fs/ext4/ialloc.o
  CC      fs/ext4/inode.o
  CC      fs/ext4/page-io.o
  CC      fs/ext4/ioctl.o
  CC      fs/ext4/namei.o
  CC      fs/ext4/super.o
  CC      fs/ext4/symlink.o
  CC      fs/ext4/hash.o
make[2]: **\* No rule to make target fs/ext4/resize.o, needed by fs/ext4/ext4.o.  Stop.
make[1]: **\* [fs/ext4] Error 2
make: **\* [fs] Error 2
rpi linux #

**Comment by popcornmix** [comment]
I think something has failed when you unzipped.
First I'd suggest you install linux tree from git:
`git clone https://github.com/raspberrypi/linux.git``

Check that you have resize.c
`dc4@dc4-VirtualBox:~/linux$ ls -l fs/ext4/resize.*
-rw-rw-r-- 1 dc4 dc4 58404 Sep  8 16:00 fs/ext4/resize.c
-rw-rw-r-- 1 dc4 dc4 25684 Sep 12 22:12 fs/ext4/resize.o`

It's obviously not a problem with the linux tree, as it is built regularly by me and many others.

**Comment by coRpTitan** [comment]
Hello,

You are right, there was some problem with unzip command. Then I downloaded same sources on another linux box, extracted them, packed them with .tar.gz, transferred them to RPI and there extracted and compiled all was OK.

I'm sorry for this issue.
