### ISSUE TITLE
firmaware/extra/Module.symvers - Which kernel version does this support

### ISSUE THREAD

**Issue by hashken** [raspberrypi/linux#373]
I have 2013-07-26-wheezy-raspbian with kernel 3.6.11+
I want to know if the Module.symvers file you have is for this kernel version?

**Comment by popcornmix** [comment]
Run "uname -a" first

**Comment by hashken** [comment]
This is the output of uname -a
Linux raspberrypi 3.6.11+ #474 PREEMPT Thu Jun 13 17:14:42 BST 2013 armv6l GNU/Linux

**Comment by popcornmix** [comment]
You can find the matching uname string here:

```
https://github.com/raspberrypi/firmware/commits/master/extra/uname_string
```

Yours is

```
https://github.com/raspberrypi/firmware/blob/470b34d635343bb7c878f12ea696f16ef6318801/extra/uname_string
```

You can see the corresponding git hash here

```
https://github.com/raspberrypi/firmware/blob/470b34d635343bb7c878f12ea696f16ef6318801/extra/git_hash
```

and hence find the corresponding source tree

```
https://github.com/raspberrypi/linux/commit/470f0a770fca4d972106a7ec76130f9eb16eb864
```

It turns out the symvers didn't change with that commit, so the immediately preceding one is:

```
https://github.com/raspberrypi/firmware/blob/8a1dac251e06a44c61c13c664a2822f7c3026c50/extra/Module.symvers
```
