### ISSUE TITLE
Can you enable CONFIG_MAXIM_THERMOCOUPLE in the RPi configs?

### ISSUE THREAD

**Issue by DougieLawson** [raspberrypi/linux#3732]
Is it possible to enable CONFIG_MAXIM_THERMOCOUPLE in your default Raspberry Pi kernel configs and in your automatically built kernels? 

I'd like to get a MAX6675 and MAX31855 thermo couple amplifier working as an IIO device.

**Comment by pelwell** [comment]
Done - it's in rpi-5.4.y, and will be propagated to 5.6 and 5.7.

**Comment by DougieLawson** [comment]
Thanks Phil.
