### ISSUE TITLE
Upgrade to 5.4.51 broke snd-rpi-hifiberry-dacplus 

### ISSUE THREAD

**Issue by lyn1337** [raspberrypi/linux#3743]
Recent upgrade broke snd-rpi-hifiberry-dacplus (and hifiberry amp 2 head compatibility).

dmesg:
`[    4.722147] snd-rpi-hifiberry-dacplus soc:sound: ASoC: failed to init link HiFiBerry DAC+: -517`
```
uname -a
Linux home 5.4.51-v7l+ #1326 SMP Fri Jul 17 10:51:18 BST 2020 armv7l GNU/Linux
vcgencmd version
Jul 17 2020 10:59:17 
Copyright (c) 2012 Broadcom
version 21a15cb094f41c7506ad65d2cb9b29c550693057 (clean) (release) (start)
```

**Comment by pelwell** [comment]
That message isn't in itself an indication of an error - it should really be suppressed - but if the ALSA device doesn't appear then it is. What does `aplay -l` report?

@j-schambacher Have you tried the latest release?

**Comment by lyn1337** [comment]
@pelwell My bad! The card didn't show up trying that, just forgot to mention.

**Comment by j-schambacher** [comment]
I've tried with 5.4.50. I will have a look to it.

@lyn1337 is there any other error message than the -517 in the dmesg output?

**Comment by lyn1337** [comment]
@j-schambacher None, I believe just the one over and over.

**Comment by j-schambacher** [comment]
@lyn1337 I've x-checked and it works with a couple of different DACplus boards here. I've also done an 'update/upgrade' without problems. I can see some -517 (it's on our backlog to be fixed), but as Phil said it's not nice but the nature of deferred probing of kernel modules. Do you have any other hint? What PI version? ....

**Comment by lyn1337** [comment]
@j-schambacher Hmm, let's see...
```
cat /sys/firmware/devicetree/base/model
Raspberry Pi 4 Model B Rev 1.2
```

**Comment by lyn1337** [comment]
Seems working now despite the message. I left out specifying `dtoverlay=hifiberry-dacplus` in the /boot/config.txt, which wasn't needed before.
Thanks everyone involved!

**Comment by mishka81** [comment]
@lyn1337 I got the same issue, had to add dtoverlay=hifiberry-dacplus in my /boot/config.txt
But now I have no HDMI sound output ! 
```
pi@rpi4:~ $ cat /proc/asound/cards
 0 [sndrpihifiberry]: HifiberryDacp - snd_rpi_hifiberry_dacplus
                      snd_rpi_hifiberry_dacplus
```
Same for you ?
