### ISSUE TITLE
Upgrade to 5.4.51-v7+ breaks Hats that use SPI and expect GPIO07 to be free (LoRa Gateways)

### ISSUE THREAD

**Issue by ludionisio** [raspberrypi/linux#3749]
**Describe the bug**
I can no longer do an `echo "7" > /sys/class/gpio/export` and `-bash: echo: write error: Device or resource busy` is thrown.

I tried disabling and reenabling SPI through `raspi-config` and even though there is effectively a `/dev/spidev0.0` and `/dev/spidev0.1` the fore mentioned command can no longer be executed.

**To reproduce**
After an upgrade through `sudo apt upgrade` from kernel 4.19.118-v7+ I am unable to use SPI

**System**

Result from `sudo cat /sys/kernel/debug/gpio`:
`gpiochip0: GPIOs 0-53, parent: platform/3f200000.gpio, pinctrl-bcm2835:`
 `gpio-7   (                    |spi0 CS1            ) out hi ACTIVE LOW`
 `gpio-8   (                    |spi0 CS0            ) out hi ACTIVE LOW`
 `gpio-29  (                    |led0                ) out lo `

* Which model of Raspberry Pi? Pi3B+
* Which OS and version (`cat /etc/rpi-issue`)? Raspberry Pi reference 2020-05-27 Generated using pi-gen, https://github.com/RPi-Distro/pi-gen, 825107f04027269db77426046f5085475b1ea22f, stage2
* Which firmware version (`vcgencmd version`)? Jul 17 2020 11:04:27 version 21a15cb094f41c7506ad65d2cb9b29c550693057 (clean) (release) (start)
* Which kernel version (`uname -a`)? Linux raspberrypi 5.4.51-v7+ #1327 SMP Thu Jul 23 10:58:46 BST 2020 armv7l GNU/Linux

**Logs**
`dmesg`:
`[    0.000000] Booting Linux on physical CPU 0x0
[    0.000000] Linux version 5.4.51-v7+ (dom@buildbot) (gcc version 4.9.3 (crosstool-NG crosstool-ng-1.22.0-88-g8460611)) #1327 SMP Thu Jul 23 10:58:46 BST 2020
[    0.000000] CPU: ARMv7 Processor [410fd034] revision 4 (ARMv7), cr=10c5383d
[    0.000000] CPU: div instructions available: patching division code
[    0.000000] CPU: PIPT / VIPT nonaliasing data cache, VIPT aliasing instruction cache
[    0.000000] OF: fdt: Machine model: Raspberry Pi 3 Model B Plus Rev 1.3
[    0.000000] Memory policy: Data cache writealloc
[    0.000000] Reserved memory: created CMA memory pool at 0x37400000, size 64 MiB
[    0.000000] OF: reserved mem: initialized node linux,cma, compatible id shared-dma-pool
[    0.000000] On node 0 totalpages: 242688
[    0.000000]   Normal zone: 1896 pages used for memmap
[    0.000000]   Normal zone: 0 pages reserved
[    0.000000]   Normal zone: 242688 pages, LIFO batch:63
[    0.000000] percpu: Embedded 20 pages/cpu s49792 r8192 d23936 u81920
[    0.000000] pcpu-alloc: s49792 r8192 d23936 u81920 alloc=20*4096
[    0.000000] pcpu-alloc: [0] 0 [0] 1 [0] 2 [0] 3 
[    0.000000] Built 1 zonelists, mobility grouping on.  Total pages: 240792
[    0.000000] Kernel command line: coherent_pool=1M 8250.nr_uarts=0 snd_bcm2835.enable_compat_alsa=0 snd_bcm2835.enable_hdmi=1 snd_bcm2835.enable_headphones=1 bcm2708_fb.fbwidth=656 bcm2708_fb.fbheight=416 bcm2708_fb.fbswap=1 vc_mem.mem_base=0x3ec00000 vc_mem.mem_size=0x40000000  console=ttyS0,115200 console=tty1 root=PARTUUID=df2829cd-02 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait
[    0.000000] Dentry cache hash table entries: 131072 (order: 7, 524288 bytes, linear)
[    0.000000] Inode-cache hash table entries: 65536 (order: 6, 262144 bytes, linear)
[    0.000000] mem auto-init: stack:off, heap alloc:off, heap free:off
[    0.000000] Memory: 882468K/970752K available (8192K kernel code, 681K rwdata, 2532K rodata, 1024K init, 824K bss, 22748K reserved, 65536K cma-reserved)
[    0.000000] SLUB: HWalign=64, Order=0-3, MinObjects=0, CPUs=4, Nodes=1
[    0.000000] ftrace: allocating 27966 entries in 55 pages
[    0.000000] rcu: Hierarchical RCU implementation.
[    0.000000] rcu: RCU calculated value of scheduler-enlistment delay is 10 jiffies.
[    0.000000] NR_IRQS: 16, nr_irqs: 16, preallocated irqs: 16
[    0.000000] random: get_random_bytes called from start_kernel+0x328/0x4e8 with crng_init=0
[    0.000000] arch_timer: cp15 timer(s) running at 19.20MHz (phys).
[    0.000000] clocksource: arch_sys_counter: mask: 0xffffffffffffff max_cycles: 0x46d987e47, max_idle_ns: 440795202767 ns
[    0.000007] sched_clock: 56 bits at 19MHz, resolution 52ns, wraps every 4398046511078ns
[    0.000022] Switching to timer-based delay loop, resolution 52ns
[    0.000292] Console: colour dummy device 80x30
[    0.000871] printk: console [tty1] enabled
[    0.000937] Calibrating delay loop (skipped), value calculated using timer frequency.. 38.40 BogoMIPS (lpj=192000)
[    0.000985] pid_max: default: 32768 minimum: 301
[    0.001334] Mount-cache hash table entries: 2048 (order: 1, 8192 bytes, linear)
[    0.001380] Mountpoint-cache hash table entries: 2048 (order: 1, 8192 bytes, linear)
[    0.002570] CPU: Testing write buffer coherency: ok
[    0.003139] CPU0: thread -1, cpu 0, socket 0, mpidr 80000000
[    0.004100] Setting up static identity map for 0x100000 - 0x10003c
[    0.004324] rcu: Hierarchical SRCU implementation.
[    0.005018] smp: Bringing up secondary CPUs ...
[    0.006155] CPU1: thread -1, cpu 1, socket 0, mpidr 80000001
[    0.007409] CPU2: thread -1, cpu 2, socket 0, mpidr 80000002
[    0.008559] CPU3: thread -1, cpu 3, socket 0, mpidr 80000003
[    0.008711] smp: Brought up 1 node, 4 CPUs
[    0.008800] SMP: Total of 4 processors activated (153.60 BogoMIPS).
[    0.008828] CPU: All CPU(s) started in HYP mode.
[    0.008853] CPU: Virtualization extensions available.
[    0.009805] devtmpfs: initialized
[    0.026221] VFP support v0.3: implementor 41 architecture 3 part 40 variant 3 rev 4
[    0.026523] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 19112604462750000 ns
[    0.026579] futex hash table entries: 1024 (order: 4, 65536 bytes, linear)
[    0.029621] pinctrl core: initialized pinctrl subsystem
[    0.030841] NET: Registered protocol family 16
[    0.035020] DMA: preallocated 1024 KiB pool for atomic coherent allocations
[    0.041304] hw-breakpoint: found 5 (+1 reserved) breakpoint and 4 watchpoint registers.
[    0.041345] hw-breakpoint: maximum watchpoint size is 8 bytes.
[    0.041582] Serial: AMBA PL011 UART driver
[    0.043528] bcm2835-mbox 3f00b880.mailbox: mailbox enabled
[    0.060081] raspberrypi-firmware soc:firmware: Attached to firmware from 2020-07-17 11:04, variant start
[    0.070095] raspberrypi-firmware soc:firmware: Firmware hash is 21a15cb094f41c7506ad65d2cb9b29c550693057
[    0.121506] bcm2835-dma 3f007000.dma: DMA legacy API manager, dmachans=0x1
[    0.123691] SCSI subsystem initialized
[    0.123966] usbcore: registered new interface driver usbfs
[    0.124048] usbcore: registered new interface driver hub
[    0.124200] usbcore: registered new device driver usb
[    0.126181] clocksource: Switched to clocksource arch_sys_counter
[    1.283529] VFS: Disk quotas dquot_6.6.0
[    1.283684] VFS: Dquot-cache hash table entries: 1024 (order 0, 4096 bytes)
[    1.283886] FS-Cache: Loaded
[    1.284125] CacheFiles: Loaded
[    1.293743] thermal_sys: Registered thermal governor 'step_wise'
[    1.294134] NET: Registered protocol family 2
[    1.295087] tcp_listen_portaddr_hash hash table entries: 512 (order: 0, 6144 bytes, linear)
[    1.295156] TCP established hash table entries: 8192 (order: 3, 32768 bytes, linear)
[    1.295297] TCP bind hash table entries: 8192 (order: 4, 65536 bytes, linear)
[    1.295507] TCP: Hash tables configured (established 8192 bind 8192)
[    1.295687] UDP hash table entries: 512 (order: 2, 16384 bytes, linear)
[    1.295760] UDP-Lite hash table entries: 512 (order: 2, 16384 bytes, linear)
[    1.296070] NET: Registered protocol family 1
[    1.296990] RPC: Registered named UNIX socket transport module.
[    1.297022] RPC: Registered udp transport module.
[    1.297048] RPC: Registered tcp transport module.
[    1.297074] RPC: Registered tcp NFSv4.1 backchannel transport module.
[    1.298786] hw perfevents: enabled with armv7_cortex_a7 PMU driver, 7 counters available
[    1.302054] Initialise system trusted keyrings
[    1.302315] workingset: timestamp_bits=30 max_order=18 bucket_order=0
[    1.312763] FS-Cache: Netfs 'nfs' registered for caching
[    1.313529] NFS: Registering the id_resolver key type
[    1.313610] Key type id_resolver registered
[    1.313637] Key type id_legacy registered
[    1.313674] nfs4filelayout_init: NFSv4 File Layout Driver Registering...
[    1.314974] Key type asymmetric registered
[    1.315004] Asymmetric key parser 'x509' registered
[    1.315081] Block layer SCSI generic (bsg) driver version 0.4 loaded (major 249)
[    1.315119] io scheduler mq-deadline registered
[    1.315146] io scheduler kyber registered
[    1.318663] bcm2708_fb soc:fb: FB found 1 display(s)
[    1.331163] Console: switching to colour frame buffer device 82x26
[    1.338027] bcm2708_fb soc:fb: Registered framebuffer for display 0, size 656x416
[    1.347901] bcm2835-rng 3f104000.rng: hwrng registered
[    1.350942] vc-mem: phys_addr:0x00000000 mem_base=0x3ec00000 mem_size:0x40000000(1024 MiB)
[    1.356725] vc-sm: Videocore shared memory driver
[    1.359757] gpiomem-bcm2835 3f200000.gpiomem: Initialised: Registers at 0x3f200000
[    1.376499] brd: module loaded
[    1.390810] loop: module loaded
[    1.394672] Loading iSCSI transport class v2.0-870.
[    1.398190] libphy: Fixed MDIO Bus: probed
[    1.400850] usbcore: registered new interface driver lan78xx
[    1.403470] usbcore: registered new interface driver smsc95xx
[    1.405985] dwc_otg: version 3.00a 10-AUG-2012 (platform bus)
[    2.136779] Core Release: 2.80a
[    2.139166] Setting default values for core params
[    2.141588] Finished setting default values for core params
[    2.344419] Using Buffer DMA mode
[    2.346878] Periodic Transfer Interrupt Enhancement - disabled
[    2.349367] Multiprocessor Interrupt Enhancement - disabled
[    2.351832] OTG VER PARAM: 0, OTG VER FLAG: 0
[    2.354218] Dedicated Tx FIFOs mode
[    2.357179] WARN::dwc_otg_hcd_init:1074: FIQ DMA bounce buffers: virt = b7514000 dma = 0xf7514000 len=9024
[    2.361892] FIQ FSM acceleration enabled for :
               Non-periodic Split Transactions
               Periodic Split Transactions
               High-Speed Isochronous Endpoints
               Interrupt/Control Split Transaction hack enabled
[    2.372964] dwc_otg: Microframe scheduler enabled
[    2.373031] WARN::hcd_init_fiq:457: FIQ on core 1
[    2.375272] WARN::hcd_init_fiq:458: FIQ ASM at 806bdcbc length 36
[    2.377519] WARN::hcd_init_fiq:497: MPHI regs_base at bb810000
[    2.379761] dwc_otg 3f980000.usb: DWC OTG Controller
[    2.382064] dwc_otg 3f980000.usb: new USB bus registered, assigned bus number 1
[    2.384445] dwc_otg 3f980000.usb: irq 56, io mem 0x00000000
[    2.386780] Init: Port Power? op_state=1
[    2.389025] Init: Power Port (0)
[    2.391561] usb usb1: New USB device found, idVendor=1d6b, idProduct=0002, bcdDevice= 5.04
[    2.396072] usb usb1: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[    2.398525] usb usb1: Product: DWC OTG Controller
[    2.400897] usb usb1: Manufacturer: Linux 5.4.51-v7+ dwc_otg_hcd
[    2.403322] usb usb1: SerialNumber: 3f980000.usb
[    2.406470] hub 1-0:1.0: USB hub found
[    2.408787] hub 1-0:1.0: 1 port detected
[    2.411723] dwc_otg: FIQ enabled
[    2.411733] dwc_otg: NAK holdoff enabled
[    2.411742] dwc_otg: FIQ split-transaction FSM enabled
[    2.411758] Module dwc_common_port init
[    2.412098] usbcore: registered new interface driver usb-storage
[    2.414621] mousedev: PS/2 mouse device common for all mice
[    2.418373] bcm2835-wdt bcm2835-wdt: Broadcom BCM2835 watchdog timer
[    2.422157] cpufreq: cpufreq_online: CPU0: Running at unlisted freq: 600000 KHz
[    2.427849] cpufreq: cpufreq_online: CPU0: Unlisted initial frequency changed to: 700000 KHz
[    2.432573] sdhci: Secure Digital Host Controller Interface driver
[    2.434783] sdhci: Copyright(c) Pierre Ossman
[    2.437525] mmc-bcm2835 3f300000.mmcnr: could not get clk, deferring probe
[    2.440269] sdhost-bcm2835 3f202000.mmc: could not get clk, deferring probe
[    2.442730] sdhci-pltfm: SDHCI platform and OF driver helper
[    2.446683] ledtrig-cpu: registered to indicate activity on CPUs
[    2.449352] hidraw: raw HID events driver (C) Jiri Kosina
[    2.451781] usbcore: registered new interface driver usbhid
[    2.454033] usbhid: USB HID core driver
[    2.457189] vchiq: vchiq_init_state: slot_zero = (ptrval)
[    2.460941] [vc_sm_connected_init]: start
[    2.469353] [vc_sm_connected_init]: end - returning 0
[    2.473238] Initializing XFRM netlink socket
[    2.475391] NET: Registered protocol family 17
[    2.477772] Key type dns_resolver registered
[    2.480469] Registering SWP/SWPB emulation handler
[    2.482864] registered taskstats version 1
[    2.484939] Loading compiled-in X.509 certificates
[    2.487403] Key type ._fscrypt registered
[    2.489421] Key type .fscrypt registered
[    2.500448] uart-pl011 3f201000.serial: cts_event_workaround enabled
[    2.502512] 3f201000.serial: ttyAMA0 at MMIO 0x3f201000 (irq = 81, base_baud = 0) is a PL011 rev2
[    2.508136] bcm2835-power bcm2835-power: Broadcom BCM2835 power domains driver
[    2.511482] mmc-bcm2835 3f300000.mmcnr: mmc_debug:0 mmc_debug2:0
[    2.513528] mmc-bcm2835 3f300000.mmcnr: DMA channel allocated
[    2.539852] sdhost: log_buf @ (ptrval) (f7513000)
[    2.577475] mmc1: queuing unknown CIS tuple 0x80 (2 bytes)
[    2.581079] mmc1: queuing unknown CIS tuple 0x80 (3 bytes)
[    2.584597] mmc1: queuing unknown CIS tuple 0x80 (3 bytes)
[    2.589347] mmc1: queuing unknown CIS tuple 0x80 (7 bytes)
[    2.593363] mmc0: sdhost-bcm2835 loaded - DMA enabled (>1)
[    2.597328] of_cfs_init
[    2.599319] of_cfs_init: OK
[    2.601905] Waiting for root device PARTUUID=df2829cd-02...
[    2.626351] Indeed it is in host mode hprt0 = 00021501
[    2.697185] random: fast init done
[    2.741288] mmc1: new high speed SDIO card at address 0001
[    2.745870] mmc0: host does not support reading read-only switch, assuming write-enable
[    2.754057] mmc0: new high speed SDHC card at address aaaa
[    2.756795] mmcblk0: mmc0:aaaa SB32G 29.7 GiB
[    2.763698]  mmcblk0: p1 p2
[    2.789851] EXT4-fs (mmcblk0p2): mounted filesystem with ordered data mode. Opts: (null)
[    2.793551] VFS: Mounted root (ext4 filesystem) readonly on device 179:2.
[    2.803725] devtmpfs: mounted
[    2.811605] Freeing unused kernel memory: 1024K
[    2.836222] usb 1-1: new high-speed USB device number 2 using dwc_otg
[    2.838572] Run /sbin/init as init process
[    2.838736] Indeed it is in host mode hprt0 = 00001101
[    3.076568] usb 1-1: New USB device found, idVendor=0424, idProduct=2514, bcdDevice= b.b3
[    3.081048] usb 1-1: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[    3.084120] hub 1-1:1.0: USB hub found
[    3.086651] hub 1-1:1.0: 4 ports detected
[    3.406230] usb 1-1.1: new high-speed USB device number 3 using dwc_otg
[    3.484831] systemd[1]: System time before build time, advancing clock.
[    3.536536] usb 1-1.1: New USB device found, idVendor=0424, idProduct=2514, bcdDevice= b.b3
[    3.541324] usb 1-1.1: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[    3.544458] hub 1-1.1:1.0: USB hub found
[    3.547053] hub 1-1.1:1.0: 3 ports detected
[    3.638752] NET: Registered protocol family 10
[    3.642317] Segment Routing with IPv6
[    3.694818] systemd[1]: systemd 241 running in system mode. (+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN -PCRE2 default-hierarchy=hybrid)
[    3.703087] systemd[1]: Detected architecture arm.
[    3.788103] systemd[1]: Set hostname to <raspberrypi>.
[    3.902576] dwc_otg_handle_wakeup_detected_intr lxstate = 2
[    4.336239] usb 1-1.1.1: new high-speed USB device number 4 using dwc_otg
[    4.466749] usb 1-1.1.1: New USB device found, idVendor=0424, idProduct=7800, bcdDevice= 3.00
[    4.471428] usb 1-1.1.1: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[    4.602474] random: systemd: uninitialized urandom read (16 bytes read)
[    4.619455] random: systemd: uninitialized urandom read (16 bytes read)
[    4.622698] systemd[1]: Listening on Journal Socket.
[    4.628671] random: systemd: uninitialized urandom read (16 bytes read)
[    4.639598] systemd[1]: Starting Restore / save the current clock...
[    4.650836] systemd[1]: Mounting POSIX Message Queue File System...
[    4.659171] systemd[1]: Created slice User and Session Slice.
[    4.665585] systemd[1]: Condition check resulted in Huge Pages File System being skipped.
[    4.675635] systemd[1]: Starting Set the console keyboard layout...
[    4.682287] systemd[1]: Listening on initctl Compatibility Named Pipe.
[    4.741697] lan78xx 1-1.1.1:1.0 (unnamed net_device) (uninitialized): No External EEPROM. Setting MAC Speed
[    4.742881] libphy: lan78xx-mdiobus: probed
[    4.786043] lan78xx 1-1.1.1:1.0 (unnamed net_device) (uninitialized): int urb period 64
[    5.429759] EXT4-fs (mmcblk0p2): re-mounted. Opts: (null)
[    5.517912] systemd-journald[126]: Received request to flush runtime journal from PID 1
[    6.358016] vc_sm_cma: module is from the staging directory, the quality is unknown, you have been warned.
[    6.361154] bcm2835_vc_sm_cma_probe: Videocore shared memory driver
[    6.361175] [vc_sm_connected_init]: start
[    6.365531] mc: Linux media interface: v0.10
[    6.369086] [vc_sm_connected_init]: installed successfully
[    6.418476] videodev: Linux video capture interface: v2.00
[    6.460550] snd_bcm2835: module is from the staging directory, the quality is unknown, you have been warned.
[    6.474972] bcm2835_audio bcm2835_audio: card created with 8 channels
[    6.476510] bcm2835_mmal_vchiq: module is from the staging directory, the quality is unknown, you have been warned.
[    6.478001] bcm2835_mmal_vchiq: module is from the staging directory, the quality is unknown, you have been warned.
[    6.478914] bcm2835_mmal_vchiq: module is from the staging directory, the quality is unknown, you have been warned.
[    6.488998] bcm2835_v4l2: module is from the staging directory, the quality is unknown, you have been warned.
[    6.490291] bcm2835_isp: module is from the staging directory, the quality is unknown, you have been warned.
[    6.502201] bcm2835_codec: module is from the staging directory, the quality is unknown, you have been warned.
[    6.509219] bcm2835-isp bcm2835-isp: Device node output[0] registered as /dev/video13
[    6.509722] bcm2835-isp bcm2835-isp: Device node capture[0] registered as /dev/video14
[    6.510261] bcm2835-isp bcm2835-isp: Device node capture[1] registered as /dev/video15
[    6.510657] bcm2835-isp bcm2835-isp: Device node stats[2] registered as /dev/video16
[    6.510685] bcm2835-isp bcm2835-isp: Register output node 0 with media controller
[    6.510704] bcm2835-isp bcm2835-isp: Register capture node 1 with media controller
[    6.510720] bcm2835-isp bcm2835-isp: Register capture node 2 with media controller
[    6.510735] bcm2835-isp bcm2835-isp: Register capture node 3 with media controller
[    6.512531] bcm2835-isp bcm2835-isp: Loaded V4L2 bcm2835-isp
[    6.553018] bcm2835-codec bcm2835-codec: Device registered as /dev/video10
[    6.553172] bcm2835-codec bcm2835-codec: Loaded V4L2 decode
[    6.574061] bcm2835-codec bcm2835-codec: Device registered as /dev/video11
[    6.574107] bcm2835-codec bcm2835-codec: Loaded V4L2 encode
[    6.582280] bcm2835-codec bcm2835-codec: Device registered as /dev/video12
[    6.582793] bcm2835-codec bcm2835-codec: Loaded V4L2 isp
[    6.843495] cfg80211: Loading compiled-in X.509 certificates for regulatory database
[    7.025837] cfg80211: Loaded X.509 cert 'sforshee: 00b28ddf47aef9cea7'
[    7.132415] brcmfmac: F1 signature read @0x18000000=0x15264345
[    7.151595] brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac43455-sdio for chip BCM4345/6
[    7.152773] usbcore: registered new interface driver brcmfmac
[    7.188839] brcmfmac mmc1:0001:1: Direct firmware load for brcm/brcmfmac43455-sdio.raspberrypi,3-model-b-plus.txt failed with error -2
[    7.405405] brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac43455-sdio for chip BCM4345/6
[    7.419727] brcmfmac: brcmf_c_preinit_dcmds: Firmware: BCM4345/6 wl0: Mar  2 2020 23:30:41 version 7.45.202 (r724630 CY) FWID 01-72f6ece2
[    7.447401] random: crng init done
[    7.447414] random: 7 urandom warning(s) missed due to ratelimiting
[    8.809686] uart-pl011 3f201000.serial: no DMA platform data
[    8.898374] 8021q: 802.1Q VLAN Support v1.8
[    9.236256] Adding 102396k swap on /var/swap.  Priority:-2 extents:1 across:102396k SSFS
[    9.259628] brcmfmac: brcmf_cfg80211_set_power_mgmt: power save enabled
[    9.516893] 8021q: adding VLAN 0 to HW filter on device eth0
[    9.520097] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
[   10.798619] ICMPv6: process `dhcpcd' is using deprecated sysctl (syscall) net.ipv6.neigh.eth0.retrans_time - use net.ipv6.neigh.eth0.retrans_time_ms instead
[   15.852055] Bluetooth: Core ver 2.22
[   15.852131] NET: Registered protocol family 31
[   15.852136] Bluetooth: HCI device and connection manager initialized
[   15.852151] Bluetooth: HCI socket layer initialized
[   15.852160] Bluetooth: L2CAP socket layer initialized
[   15.852175] Bluetooth: SCO socket layer initialized
[   15.918870] Bluetooth: HCI UART driver ver 2.3
[   15.918882] Bluetooth: HCI UART protocol H4 registered
[   15.918929] Bluetooth: HCI UART protocol Three-wire (H5) registered
[   15.919079] Bluetooth: HCI UART protocol Broadcom registered
[   17.101439] Bluetooth: BNEP (Ethernet Emulation) ver 1.3
[   17.101453] Bluetooth: BNEP filters: protocol multicast
[   17.101474] Bluetooth: BNEP socket layer initialized`

**Comment by pelwell** [comment]
Why do you need GPIO access to GPIO 7? Why does not having that prevent you from using SPI?

**Comment by ludionisio** [comment]
Being able to compare the updated system with the previous one I identified with the command `cat /sys/kernel/debug/gpio` that before the GPIO07 was:
`gpiochip0: GPIOs 0-53, parent: platform/3f200000.gpio, pinctrl-bcm2835:`
 `gpio-7   (                    |sysfs               ) in  lo`    
 `gpio-29  (                    |led0                ) out lo`

Investigating further It seems that the current configuration actually reserves pins 7 and 8 for the SPI Chip Select. Which seems the right thing to do, even though this wasn't being done before.

But I am working with LoRa Gateway PiHats (different brands) that share a common design following SemTech's one. They all use GPIO07 to reset the concentrator chip and it is not possible to change it (unless some trail cutting and some hack wiring takes place). I realize now that the update does not affect SPI, but only Hats that use SPI and expect GPIO07 to be free.

I am not sure now what would be the proper solution because it is not clear what exactly changed. Is the latest kernel using a different device tree overlay? I saw that many others were having similar problems with other peripherals as well after the upgrade.

Would you have any suggestion?

**Comment by pelwell** [comment]
If you have a spare GPIO somewhere then the spi0-cs overlay will let you reassign either or both CS pins:
```
pi@raspberrypi:~ $ dtoverlay -h spi0-cs
Name:   spi0-cs

Info:   Allows the (software) CS pins for SPI0 to be changed

Usage:  dtoverlay=spi0-cs,<param>=<val>

Params: cs0_pin                 GPIO pin for CS0 (default 8)
        cs1_pin                 GPIO pin for CS1 (default 7)
```
You would need to add `dtoverlay=spi0-cs,cs1_pin=99`, where you replace 99 with the number of the spare GPIO.

If you don't have one spare then it wouldn't be difficult to modify this overlay or create a new one that makes CS1 optional. At the same time I'd probably also make the use of the MISO optional because users seem to have borrowed GPIO 9 for their own purposes.

**Comment by ludionisio** [comment]
Excelent!
Thanks a lot!

**Comment by sp193** [comment]
> If you have a spare GPIO somewhere then the spi0-cs overlay will let you reassign either or both CS pins:
> 
> ```
> pi@raspberrypi:~ $ dtoverlay -h spi0-cs
> Name:   spi0-cs
> 
> Info:   Allows the (software) CS pins for SPI0 to be changed
> 
> Usage:  dtoverlay=spi0-cs,<param>=<val>
> 
> Params: cs0_pin                 GPIO pin for CS0 (default 8)
>         cs1_pin                 GPIO pin for CS1 (default 7)
> ```
> 
> You would need to add `dtoverlay=spi0-cs,cs1_pin=99`, where you replace 99 with the number of the spare GPIO.
> 
> If you don't have one spare then it wouldn't be difficult to modify this overlay or create a new one that makes CS1 optional. At the same time I'd probably also make the use of the MISO optional because users seem to have borrowed GPIO 9 for their own purposes.

Sorry to bring up this issue again, but is this really all that needs to be done? For example, if GPIO4 is unused and I would like to reassign the kernel's claim on GPIO7 to GPIO4, do I just enter this command as the ``pi`` user?
``dtoverlay=spi0-cs,cs1_pin=4``

There's no output from dtoverlay after entering the command. GPIO7 remained unusable, even after rebooting the RPi. I'm not sure what else to check, since I'm also quite new to the RPi.

Unlike the OP, I'm trying out a RisingHF RHF0M301 with RHF4T002 bridge. The RHF4T002 also has the reset pin connected to GPIO7.

**Comment by pelwell** [comment]
Since the original issue was opened, a new overlay - spi0-1cs - had been added. This configures SPI0 to use only one CS line:
```
dtoverlay=spi0-1cs,cs0_pin=4
```

**Comment by sp193** [comment]
Thanks. I eventually also figured out that I needed to add the line to ``/boot/config.txt``.
Once added and the RPi is rebooted, the GPIO configuration gets changed to:
```
pi@raspberrypi:sudo cat /sys/kernel/debug/gpio
gpiochip0: GPIOs 0-53, parent: platform/3f200000.gpio, pinctrl-bcm2835:
 gpio-4   (                    |spi0 CS0            ) out hi ACTIVE LOW
 gpio-35  (                    |led1                ) in  lo 
 gpio-47  (                    |led0                ) out lo
```
I am now able to use GPIO7. Once again, thanks.

**Comment by sp193** [comment]
Pardon me for asking, but why would I get a difference in behaviour between using these two, given that I do not use the CS0/CS1 signals and only CS1 (GPIO7) is actually in the way:
```
dtoverlay=spi0-1cs,cs0_pin=5
```
```
dtoverlay=spi0-cs,cs1_pin=5
```
With the latter, the LoRa gateway library appears to work fine. But with the former, the library seems to read all registers as 0x00 values:
```
pi@raspberrypi:~/lora_gateway/libloragw $ ./test_loragw_reg
Beginning of test for loragw_reg.c
Note: SPI port opened and configured ok
Note: SPI read success
lgw_connect:532: INFO: no FPGA detected or version not supported (v0)
Note: SPI read success
lgw_connect:555: ERROR: NOT EXPECTED CHIP VERSION (v0)
ERROR: CONCENTRATOR UNCONNECTED
ERROR: CONCENTRATOR UNCONNECTED
ERROR: CONCENTRATOR UNCONNECTED
ERROR: CONCENTRATOR UNCONNECTED
ERROR: CONCENTRATOR UNCONNECTED
IMPLICIT_PAYLOAD_LENGHT = 0 (should be 197)
ERROR: CONCENTRATOR UNCONNECTED
ERROR: CONCENTRATOR UNCONNECTED
FRAME_SYNCH_PEAK2_POS = 0 (should be 11)
ERROR: CONCENTRATOR UNCONNECTED
ERROR: CONCENTRATOR UNCONNECTED
PREAMBLE_SYMB1_NB = 0 (should be 49253)
ERROR: CONCENTRATOR UNCONNECTED
ERROR: CONCENTRATOR UNCONNECTED
ADJUST_MODEM_START_OFFSET_SF12_RDX4 = 0 (should be 3173)
ERROR: CONCENTRATOR UNCONNECTED
ERROR: CONCENTRATOR UNCONNECTED
IF_FREQ_1 = 0 (should be -1947)
ERROR: CONCENTRATOR UNCONNECTED
ERROR: CONCENTRATOR UNCONNECTED
Note: SPI port closed
Note: success disconnecting the concentrator
End of test for loragw_reg.c
```

The healthy output is actually quite long, but the chip version should be detected (no error logged) and fields like IMPLICIT_PAYLOAD_LENGHT, FRAME_SYNCH_PEAK2_POS and IF_FREQ_1 should have their written values reflected correctly (not 0). My board has no FPGA, so the log message about the FPGA is expected.

Previously, I asked about how to map CS1 to GPIO4. I'm now using GPIO5 because GPIO4 was actually used for the LCD panel's backlight.

Once again, thanks in advance.

**Comment by pelwell** [comment]
```
dtoverlay=spi0-1cs,cs0_pin=5
```
configures GPIO5 to be CE/CS line 0, and
```
dtoverlay=spi0-cs,cs1_pin=5
```
(which gets converted to "spi0-2cs,...") configures GPIO8 as CE/CS line 0 and GPIO5 as CE/CS line 1.

If you only want to use 1 CS line then it must be CS0, so you'll need to reconfigure the rest of your overlay/software to take account of that.

**Comment by sp193** [comment]
Thanks. I understand the problem now. I incorrectly assumed it never used a CS line, due to a lack of experience with SPI and documentation. You are right, it appears to be using CS0 (GPIO8) for its CSN pin input, while CS1 (GPIO7) is used for reset. So I need to keep CS0 as GPIO8, otherwise the board stops working since it never gets enabled.
