### ISSUE TITLE
Today's jessie update removes amavisd-new

### ISSUE THREAD

**Issue by jors** [raspberrypi/linux#375]
Steps to reproduce:

<ol>
<li>apt-get update && apt-get -u dist-upgrade</li>
<li>Accept upgrade, amavisd-new is removed.</li>
<li>Cannot be installed again due to dependency issues:</li>
</ol>

<pre>
# apt-get install amavisd-new
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 amavisd-new : Depends: libmail-dkim-perl but it is not going to be installed
               Recommends: libnet-patricial-perl but it is not installable
E: Unable to correct problems, you have held broken packages.

# apt-get install libmail-dkim-perl
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libmail-dkim-perl : Depends: libcrypt-openssl-rsa-perl (>= 0.24) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

# apt-get install libcrypt-openssl-rsa-perl
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libcrypt-openssl-rsa-perl : Depends: perlapi-5.14.2 but it is not installable
E: Unable to correct problems, you have held broken packages.

# apt-get install perlapi-5.14.2
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package perlapi-5.14.2 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'perlapi-5.14.2' has no installation candidate
</pre>

My <i>/etc/apt/sources.list</li>:

<pre>deb http://mirrordirector.raspbian.org/raspbian/ jessie main contrib non-free rpi</pre>

I have checked that on Debian jessie this problem does not exist, even if I found a possible related bug [1]. Please, let me know if I can provide any other information or do some testing.

Regards.

[1] <a href="http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=535932">http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=535932</a>

**Comment by asb** [comment]
This bug should be reported either on the Raspbian forum on
raspberrypi.orgor on the Raspbian bug tracker. The note at
http://www.raspbian.org/RaspbianBugs is I suppose misleading, as this bug
tracker is really only for bugs related to the Linux kernel put out by the
Raspberry Pi team.

**Comment by jors** [comment]
Ooops, sorry, you are right. Will proceed there [1]. Cheers!

[1] <a href="https://bugs.launchpad.net/raspbian">https://bugs.launchpad.net/raspbian</a>
