### ISSUE TITLE
3.6.10: fiq compilation warnings

### ISSUE THREAD

**Issue by ghost** [raspberrypi/linux#376]
arch/arm/kernel/fiq.c: In function 'set_fiq_handler':
arch/arm/kernel/fiq.c:92:3: warning: passing argument 1 of 'v6_coherent_kern_range' makes integer from pointer without a cast [enabled by default]
In file included from arch/arm/kernel/fiq.c:44:0:
/home/hagbard/raspberry/3.10/linux/arch/arm/include/asm/cacheflush.h:154:1: note: expected 'long unsigned int' but argument is of type 'void *'

**Comment by popcornmix** [comment]
Are you referring to 3.6.y tree (which is at 3.6.11) or the 3.10.y tree?

**Comment by ghost** [comment]
Oops, typo in the title. I'm referring to the 3.10.y tree.

**Comment by popcornmix** [comment]
Upstream bug. See:
http://www.spinics.net/lists/arm-kernel/msg267587.html
It's fixed in 3.11.y tree. I've pulled in the commit, and will push it out shortly.

**Comment by popcornmix** [comment]
This is now fixed
