### ISSUE TITLE
None of my devices show up in HA / Cannot install Hassio

### ISSUE THREAD

**Issue by Insomniac-ai** [raspberrypi/linux#3781]
**Is this the right place for my bug report?**
This repository contains the Linux kernel used on the Raspberry Pi. If you believe that the issue you are seeing is kernel-related, this is the right place. If not, we have other repositories for the GPU firmware at [github.com/raspberrypi/firmware](https://github.com/raspberrypi/firmware) and Raspberry Pi userland applications at [github.com/raspberrypi/userland](https://github.com/raspberrypi/userland). If you have problems with the Raspbian distribution packages, report them in the [github.com/RPi-Distro/repo](https://github.com/RPi-Distro/repo). If you simply have a question, then [the Raspberry Pi forums](https://www.raspberrypi.org/forums) are the best place to ask it.

**Describe the bug**
Add a clear and concise description of what you think the bug is.

**To reproduce**
List the steps required to reproduce the issue.

**Expected behaviour**
Add a clear and concise description of what you expected to happen.

**Actual behaviour**
Add a clear and concise description of what actually happened.

**System**
 Copy and paste the results of the raspinfo command in to this section. Alternatively, copy and paste a pastebin link, or add answers to the following questions:

* Which model of Raspberry Pi? e.g. Pi3B+, PiZeroW
* Which OS and version (`cat /etc/rpi-issue`)?
* Which firmware version (`vcgencmd version`)?
* Which kernel version (`uname -a`)?

**Logs**
If applicable, add the relevant output from `dmesg` or similar.

**Additional context**
I recently purchased a Raspberry Pi 4 with 8gb of RAM. I installed Raspbian then docker and then Home Assistant. I created a Nabu Casa account. I'm very new to linux, so that has made it even more difficult. I'm familiar with some very basic commands.

When I first started up, the only device that HA recognized was my printer (I was later able to add my Ring). I tried to integrate my Wiz light bulbs and they weren't available under integration. Same thing with my Roborock S5Max (not available), my ThinkEco modlets for my AC, and my SmartLife sockets. They're all WiFi connected and don't go through a hub.

My Home Assistant UI doesn't have an add-on option (at least none that I can see).

I tried then to see if maybe I could integrate my Smartthings account to have access to the devices. I went through all the steps and first it said, "Cannot start the smart app." After I restarted the RPi, it said, "Please wait while the integration is being installed" and then it goes back to the "Setup a New Integration" box without anything happening.

I also tried to integrate my IFTTT and the instructions said that I need to use IFTTT's "Make a Web Request" but the only option available in IFTTT is "Receive a Web Request."

If I go to to the "Home Assistant Cloud" both Smartthings and IFTTT appear under webhooks with the proper URLs.

I read that some of these problems might be fixable if I could edit the configuration file but I don't know how to do that. And since I don't have the add-on option, I don't think that I can download an editor.

I then flashed a different SD card and tried to directly boot HASSos. I followed all of the instructions including creating the my-network file on a separate USB.

With HASS – 64bit, I can get as far as the HASS-CLI during installation but don’t know what to do from there to actually use HA and a the UI. With HASS – 32bit, it also hangs during the installation and cycles through 1 of 5, 2 of 5, etc. and says, “A start job is running for HassOS ZRAM…” and “Wait until kernel time synchronized”. I don't know if I'm having these problems with the HASSos b/c it doesn't yet support 8gb on a RPi 4 or if there's another reason. So it seems that my only option right now is to run HA on Raspian with Docker.

I have spent the last five days combing through every forum that I could find and either there was no answer available or, if there was an answer available, it didn't explain how I could do it (e.g. editing the configuration file).

I should mention that I have both a zigbee and z-wave plus USB "hubs" that I can plug in to the pi. I haven't used them yet but ultimately, I'd like to use devices that require either of these. I would also want to use the pi for things like PiHole, PiVPN, and maybe some other things in the future but right now, I really just want to get HA to work.

I'm using HA 0.113.3, Raspberry Pi 4 (8gb), and Docker.

**Comment by pelwell** [comment]
This "issue" is about Hassio on a Pi rather than about the Pi itself. Unless you have found a problem with the Linux kernel on Pi we can't help you here.
