### ISSUE TITLE
Wifi detecting but not connecting on Kali Linux on 8GB(PI)

### ISSUE THREAD

**Issue by rayavarapuvikram1** [raspberrypi/linux#3784]
When I am connecting to wifi it is asking password again and again. I reinstalled [Kali ](https://www.offensive-security.com/kali-linux-arm-images/) more than 10 times but it didn't work. Please, someone, help me.

**Comment by JamesH65** [comment]
Does the same issue occur on Raspberry Pi OS? If so, then we can look at it, if not, you need to approach the Kali developers as they will need to fix their distro.

**Comment by rayavarapuvikram1** [comment]
Happening only in Kali Linux, Ubuntu, Raspian is fine.

**Comment by JamesH65** [comment]
So, nothing to do with us then - you need to talk to the Kali developers.
