### ISSUE TITLE
pizero kernel 5.4 does not build after update

### ISSUE THREAD

**Issue by Claudenw** [raspberrypi/linux#3786]
**Describe the bug**

From the build:
```
drivers/net/usb/lan78xx.c: In function 'lan78xx_probe':
drivers/net/usb/lan78xx.c:3777:15: error: 'struct lan78xx_net' has no member named 'ep_intr'
   period = dev->ep_intr->desc.bInterval;
               ^
```

It looks like ep_intr was removed from the lan78xx.net structure.  However line 3777 of lan78xx.c requires it.  Not sure what should be done here.

**To reproduce**

```
git clone --depth=1 --branch rpi-5.4.y https://github.com/raspberrypi/linux.git
export PATH=$PATH:/opt/tools/arm-bcm2708/arm-linux-gnueabihf/bin 
export KERNEL=kernel 
make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- bcmrpi_defconfig 
make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- -j 4 zImage modules dtbs 


**Expected behaviour**
The make should succeed

**Actual behaviour**
the make failed with error noted above

**System**

Compiling for PIZeroW.
cross compiling on
```
$uname -a
Linux zoltan-the-great 5.4.0-42-generic #46~18.04.1-Ubuntu SMP Fri Jul 10 07:21:24 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

**Logs**
If applicable, add the relevant output from `dmesg` or similar.

**Additional context**
Add any other relevant context for the problem.

**Comment by Claudenw** [comment]
Checking out 4b945d5fb69233f4ddf66d67c3d35145f1039e01 the build works so only the changes in a6825094038507f5eafdca6328ac6ddeb44e3502 contain the error.

**Comment by hvenev** [comment]
It looks like upstream commit ea060b352654a8de1e070140d25fe1b7e4d50310 changed the driver a bit.

**Comment by Dark-Sky** [comment]
I know 5.4-51 @ 1baaf03127861d00b69e3eba4a32a119ffe37e01 compiles but I have not compiled the latest 5.4-58 commit today.

```
[ray@pi4 ~]$ uname -a
Linux pi4 5.4.51-1-MANJARO-ARM #1 SMP PREEMPT Tue Jul 28 11:19:11 CDT 2020 aarch64 GNU/Linux
```

**Comment by pelwell** [comment]
The upstream commit broke a downstream patch, but the fix is easy (`dev->ep_intr` becomes `ep_intr`). There's another issue in the ath9k driver that needs fixing, but then I'll merge them both.

**Comment by popcornmix** [comment]
I've pushed a fixed.

**Comment by ncopa** [comment]
> There's another issue in the ath9k driver that needs fixing, but then I'll merge them both.

As mentioned in #3788 , this can be fixed by cherry-picking e6eb815beccca7018ce7b7c4b52059712dd1232d

**Comment by pelwell** [comment]
Which I've done - just building now.

**Comment by ncopa** [comment]
ah, i didnt notice that @pelwell and @popcornmix are two different persons :smile:  sorry.

Thank you for your quick response! :heart:

**Comment by pelwell** [comment]
With the ath9k cherry-pick included it all builds again. That was an upstream error.

**Comment by pelwell** [comment]
@popcornmix is up earlier than I expected.

**Comment by Exaga** [comment]
Thanks guys. I have been head-scratching over the past 12 hours with this  too.

**Comment by Dark-Sky** [comment]
I can confirm 5.4-58 @ a6825094038507f5eafdca6328ac6ddeb44e3502 now compiles with the fixes.

**Comment by Claudenw** [comment]
The fixes applied resolved this problem.

Thank you to all who assisted.
