### ISSUE TITLE
64 bit bcmrpi3_defconfig CONFIG_USB_GADGET is not set

### ISSUE THREAD

**Issue by Dark-Sky** [raspberrypi/linux#3796]
Is there a reason why CONFIG_USB_GADGET is not enabled after running make bcmrpi3_defconfig with kernel 5.4.58.

**Comment by pelwell** [comment]
Only that is a user-contributed defconfig and not one that we use. Do you just want "CONFIG_USB_GADGET=m" or "CONFIG_USB_GADGET=y", or is there something else?

**Comment by Dark-Sky** [comment]
Guess it does not make any difference. Seems like you have it by default CONFIG_USB_GADGET=y in all of the other defconfigs. I compile all kernels here. I have had devices in the past that will not work with it disabled.

**Comment by Dark-Sky** [comment]
As you can see a multitude of dvb modules will not get compiled. There are a ton more not showing in this window. bcmrpi3_defconfig is the right hand pane.

![gadget](https://user-images.githubusercontent.com/22453495/90269129-baf11100-de1d-11ea-9225-f26c0215173a.png)

**Comment by pelwell** [comment]
Done - see https://github.com/raspberrypi/linux/commit/96be00073b63c170b6916f35abb58748bc8f6d26.

**Comment by Dark-Sky** [comment]
Thanks. Will save me some time in the future building kernels.
