### ISSUE TITLE
getchar does not work in non blocking mode under Raspbian GNU/Linux 10 (buster)"

### ISSUE THREAD

**Issue by alphatech56** [raspberrypi/linux#3803]
I tried to use getchar in non blocking mode.  Program was working "as expected" with Raspbian GNU/Linux 9 (stretch). When I recompiled and run the same program with Raspbian GNU/Linux 10 (buster)" getchar always timed out, even if I typed characters on keyboard. Attached is code. 
[testGetcharTxt.txt](https://github.com/raspberrypi/linux/files/5091590/testGetcharTxt.txt)

**Comment by popcornmix** [comment]
This repo is for reporting bugs in the linux kernel. Your issue is not related to this.
Try asking in the forums.
Also read [here](https://github.com/popcornmix/omxplayer/issues/649) which may be the issue you are hitting.
