### ISSUE TITLE
Geniatech T230C2 TV dongle is unusable on kernel 5.4.y

### ISSUE THREAD

**Issue by leshniak** [raspberrypi/linux#3809]
**Describe the bug**
Geniatech T230C2 TV dongle is unusable on kernel 5.4.y. Please cherry-pick the fix from upstream: https://github.com/torvalds/linux/commit/cecf0bbbcb6f035a5ca2197f3e11ec2b7fb3da83

**To reproduce**
The issue occurs usually after few minutes of using the dongle.

**Expected behaviour**
The TV dongle is usable all the time. No errors in dmesg.

**Actual behaviour**
The TV dongle is not responding anymore after the issue occurs. Reboot is needed.

**System**
* Which model of Raspberry Pi? Pi 4B
* Which OS and version (`cat /etc/rpi-issue`)? RaspberryPi OS Buster
* Which firmware version (`vcgencmd version`)? af3edc2de473197cdfe1ff5a8ff2d34095d5b336
* Which kernel version (`uname -a`)? 5.4.51-v8

**Logs**
Error from dmesg:
`dvb_usb_v2: usb_bulk_msg() failed=-110` (flood)

**Additional context**
This commit from upstream fixes the issue: https://github.com/torvalds/linux/commit/cecf0bbbcb6f035a5ca2197f3e11ec2b7fb3da83

**Comment by pelwell** [comment]
I've taken your word that the patch fixes the problem - had it been marked as a fix it would have been automatically back-ported upstream.

**Comment by leshniak** [comment]
I've already tested the patch on 5.4 kernel and it works.

Thank you.
