### ISSUE TITLE
Raspberry Pi4 GPIO video add-ons don't work using KMS driver

### ISSUE THREAD

**Issue by rtomasa** [raspberrypi/linux#3810]
I'm trying to use RGB-Pi and Gert-VGA666 in Raspberry OS 32 bits kernel 5.4, but whether I got black screen, or when using vc4-kms-kippah-7inch, I get image but some applications do not start due to the lack of display context:

**Scenario A (does not display image but there is image context)**

```
[pi4]
dtoverlay=vc4-kms-v3d-pi4
max_framebuffers=2
```

**Scenario B (does display image but there is not display context)**

```
dtoverlay=vc4-kms-v3d-pi4
dtoverlay=vc4-kms-kippah-7inch
max_framebuffers=2
```

And here an example issue of no display context when executing retroarch application (scenario B):

```
$ ./retroarch --verbose
[INFO] RetroArch 1.8.8 (Git 9552f87)
[INFO] === Build =======================================
[INFO] Capabilities:  NEON VFPv3 VFPv4
[INFO] Built: Jun  9 2020
[INFO] Version: 1.8.8
[INFO] Git: 9552f87
[INFO] =================================================
[INFO] [Environ]: SET_PIXEL_FORMAT: RGB565.
[INFO] Version of libretro API: 1
[INFO] Compiled against API: 1
[INFO] [Audio]: Set audio input rate to: 30000.00 Hz.
[INFO] [Video]: Video @ 6309x720
[WARN] [DRM]: Couldn't get device resources.
[WARN] [DRM]: Couldn't get device resources.
[ERROR] [KMS]: Couldn't find a suitable DRM device.
[WARN] [SDL_GL]: Failed to initialize SDL gfx context driver: The video driver did not add any displays
[INFO] [GL]: Found GL context: null
[INFO] [GL]: Detecting screen resolution 320x240.
[INFO] [GL]: Vendor: (null), Renderer: (null).
[INFO] [GL]: Version: (null).
[ERROR] [Video]: Cannot open video driver ... Exiting ...
[ERROR] Fatal error received in: "init_video()"
```

**Comment by michaeloneill1** [comment]
Please resolve this!!

**Comment by dgore27** [comment]
Gracias de antemano

**Comment by JamesH65** [comment]
The KMS driver is still under development. You should be using the FKMS driver unless testing KMS.

**Comment by kase6** [comment]
Pelase !!!

**Comment by sarmient** [comment]
Please resolve this!!

**Comment by pelwell** [comment]
These kind of comments are counterproductive - they don't increase the priority of a task and just annoy the devs.

**Comment by mortaca** [comment]
> The KMS driver is still under development. You should be using the FKMS driver unless testing KMS.

With the FKMS driver we cannot use libdrm for resolution changes without restarting the Pi

> These kind of comments are counterproductive - they don't increase the priority of a task and just annoy the devs.

And how can you increase the priority on this question then?

**Comment by rtomasa** [comment]
> The KMS driver is still under development. You should be using the FKMS driver unless testing KMS.

So is it expected that once the KMS driver is completed and set as the default driver, all DPI configurations will function correctly back again as in previous models?
Please do note that I was using the KMS driver because vcgen does not work properly with FKMS anymore, so I was using KMS in order to be able to use libdrm for messing around with custom modelines on the fly.

**Comment by JamesH65** [comment]
>
> And how can you increase the priority on this question then?

You cannot. We are a small team with a lot to do. KMS is being worked on by us and Igalia. When it's done it will be done.

The expectation is that all previous stuff *should* similar to before, but this is a big change (legacy firmware to standard Linux API's) so there is no guarantee that things will be entirely the same.

**Comment by mortaca** [comment]
> > And how can you increase the priority on this question then?
> 
> You cannot. We are a small team with a lot to do. KMS is being worked on by us and Igalia. When it's done it will be done.
> 
> The expectation is that all previous stuff _should_ similar to before, but this is a big change (legacy firmware to standard Linux API's) so there is no guarantee that things will be entirely the same.

That is precisely why we want you to know that there is a community of a few thousand users who use this function and a lot of designed hardware that would be obsolete, and that is what we want to highlight.

**Comment by PixelPerfext** [comment]
Gracias Rubén

**Comment by thundercato** [comment]
Would love this to be solved. Wish I could help!

**Comment by spastik10** [comment]
Please resolve this, thanks!

**Comment by pelwell** [comment]
Whichever forum you all hang out on, please spread the word that this issue will be closed if there are more pointless "Me too!", "Fix it now!" comments.

**Comment by rtomasa** [comment]
Please gents, this is not a forum but a technical issue. Comments claiming for a fix now won't help. AFAIK there is just a single person already working in the KMS driver so there is nothing to fix yet, so what we need is just having the confirmation that once the driver is finished, all DPI configurations will be working back again.

**Comment by JamesH65** [comment]
Whilst I understand the frustration that an alpha test bit of software that is still under development doesn't yet do what you want, it worth remembering that a community of a few thousand users is less than half of one day's production of Raspberry Pi's. We have tasks on our backlog that affect many many more people than that, and of course they will have priority. So although this will get fixed at some point, we cannot say when that point will be. And as above, continual commenting on it doesn't make any difference (in fact, it could make things take longer).

**Comment by rtomasa** [comment]
@JamesH65 Thanks James, just one final question. Is there any target date for the final KMS driver? Is it a matter of a few months, a year?
I will close this issue until the same is released and I can test everything again with the same.

BR

**Comment by JamesH65** [comment]
We are making progress, but we never announce any dates in advance. It's quite a complex thing. I'd say months rather than years.

**Comment by rtomasa** [comment]
Thanks James. Closing the issue and looking forward for the final driver.

BR
