### ISSUE TITLE
 libc6-dev : Breaks: libgcc-8-dev (< 8.4.0-2~) but 8.3.0-6+rpi1 is to be installed

### ISSUE THREAD

**Issue by M0dred** [raspberrypi/linux#3812]
Cannot install metasploit from Kali source.list

root@raspberrypi:~# apt-get install metasploit-framework 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libc6-dev : Breaks: libgcc-8-dev (< 8.4.0-2~) but 8.3.0-6+rpi1 is to be installed
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.

## Version
uname -a
Linux raspberrypi 4.19.118-v7+ #1311 SMP Mon Apr 27 14:21:24 BST 2020 armv7l GNU/Linux

Thanks.

**Comment by XECDesign** [comment]
Although Raspberry Pi OS ARMHF isn't Debian, this still applies:

https://wiki.debian.org/DontBreakDebian#Don.27t_make_a_FrankenDebian

But either way, this tracker is for issues with the linux kernel.
