### ISSUE TITLE
Raspbian package with kernel headers for kernel 3.6.11+ (#474) missing

### ISSUE THREAD

**Issue by nona00** [raspberrypi/linux#382]
I'm using Raspbian 2012-12-16 with all updates and Raspbian 2013-07-26.

There seems to be no package with the kernel-headers for the installed kernel 3.6.11+ (#474).

[root@pi2:~]# uname -a
Linux pi2 3.6.11+ #474 PREEMPT Thu Jun 13 17:14:42 BST 2013 armv6l GNU/Linux

[root@pi2:~]# apt-cache search linux-headers
linux-headers-3.2.0-4-all - All header files for Linux 3.2 (meta-package)
linux-headers-3.2.0-4-all-armhf - All header files for Linux 3.2 (meta-package)
linux-headers-3.2.0-4-common - Common header files for Linux 3.2.0-4
linux-headers-3.2.0-4-rpi - Header files for Linux 3.2.0-4-rpi
linux-headers-3.6-trunk-all - All header files for Linux 3.6 (meta-package)
linux-headers-3.6-trunk-all-armhf - All header files for Linux 3.6 (meta-package)
linux-headers-3.6-trunk-common - Common header files for Linux 3.6-trunk
linux-headers-3.6-trunk-rpi - Header files for Linux 3.6-trunk-rpi
linux-headers-rpi - Header files for Linux rpi configuration (meta-package)
linux-headers-rpi-rpfv - This metapackage will pull in the headers for the raspbian kernel based on

[root@pi2:~]# apt-cache showpkg linux-headers-3.6-trunk-common
Package: linux-headers-3.6-trunk-common
Versions:
3.6.9-1~experimental.1+rpi6 (/var/lib/apt/lists/mirrordirector.raspbian.org_raspbian_dists_wheezy_main_binary-armhf_Packages)

Raspbian Bug report:
https://bugs.launchpad.net/raspbian/+bug/1228643

**Comment by popcornmix** [comment]
Not a kernel issue, but a raspbian packaging issue.
