### ISSUE TITLE
libequinox-osgi-java (3.9.1-4)

### ISSUE THREAD

**Issue by xplatform-dev** [raspberrypi/linux#3830]
The config file that comes with the eclipse package points to osgi_3.8.1
The jar file is also missing from the package libequinox-osgi-java.

The java files are present in the source, so it's still technically possible to build it...

Everything else looks fine.

The files are present in the Debian repo and properly configured.

(Yes I realize this is probably the wrong place -- directions were not clear -- Sorry)

**Comment by XECDesign** [comment]
We don't ship eclipse or libequinox-osgi-java in our repo. Raspbian bugs can be reported here https://www.raspbian.org/RaspbianBugs
