### ISSUE TITLE
not generating zimage or img or gz

### ISSUE THREAD

**Issue by skywo1f** [raspberrypi/linux#3852]
I am following the guide:
https://www.raspberrypi.org/documentation/linux/kernel/building.md

When I get to the last step:
make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- zImage modules dtbs

it compiles for a while then finishes compiling. But I am not able to find the compiled kernel image anywhere. Where does it put it and under what name?

**Comment by pelwell** [comment]
Read on a few paragraphs:
> Finally, copy the kernel and Device Tree blobs onto the SD card, making sure to back up your old kernel:
```
sudo cp mnt/fat32/$KERNEL.img mnt/fat32/$KERNEL-backup.img
sudo cp arch/arm/boot/zImage mnt/fat32/$KERNEL.img
sudo cp arch/arm/boot/dts/*.dtb mnt/fat32/
sudo cp arch/arm/boot/dts/overlays/*.dtb* mnt/fat32/overlays/
sudo cp arch/arm/boot/dts/overlays/README mnt/fat32/overlays/
sudo umount mnt/fat32
sudo umount mnt/ext4
```
