### ISSUE TITLE
Request: include AppleTalk kernel module in Raspbian

### ISSUE THREAD

**Issue by IvanExpert** [raspberrypi/linux#386]
The AppleTalk kernel module is part of the standard Linux tree, and kernel configuration options. It makes it possible for the Netatalk 2.x package to use the Raspberry Pi as a file and print server for classic Mac and Apple II computers. I have simplified this setup in my A2SERVER project at http://appleii.ivanx.com/a2server.

The AppleTalk module is provided by default in most standard Linux installations, but not Raspbian, so I have compiled and provided an AppleTalk kernel module for every release, using the method I outline at http://appleii.ivanx.com/a2server/a2server_raspberrypi_kernel.html.

However, I can't make it work for NOOBS (which seems to use a modified kernel), and, even worse, I can no longer even make a module for the raw Raspbian 2013-09-10 image. (See issue 387.)

For my purposes, the best solution to this would be to have Raspbian provide appletalk.ko as part of the standard Raspbian build. Is this something you could consider?

**Comment by popcornmix** [comment]
Are you asking for CONFIG_ATALK=m
to be added to default kernel config options?

**Comment by IvanExpert** [comment]
Yes. I sure am. Thanks.

**Comment by popcornmix** [comment]
Okay, seems reasonable. It's on the list.

**Comment by IvanExpert** [comment]
Great! Thank you.

**Comment by popcornmix** [comment]
CONFIG_ATALK enabled some other kernel options, which have sub options. 
Do you need:
DEV_APPLETALK
GFS2_FS_LOCKING_DLM
OCFS2_FS_USERSPACE_CLUSTER
DLM_DEBUG

if you don't care, I'll just use the defaults.

**Comment by IvanExpert** [comment]
I don't care. Defaults are fine AFAIK.

**Comment by popcornmix** [comment]
rpi-update should get a kernel with AppleTalk module.

**Comment by IvanExpert** [comment]
It's there. Awesome. Thank you.
