### ISSUE TITLE
How to generate deb package for the kernel

### ISSUE THREAD

**Issue by jfbette** [raspberrypi/linux#3867]
Hi,

I have to build a specific kernel for the Raspeberry PI 4 to have some specific option (support for auditd). I managed to compile the kernel for my purpose following the page https://wiki.ubuntu.com/KernelTeam/ARMKernelCrossCompile

However it forced me to copy files unpackaged. I would like to generate a deb to be compliant with the DEB packaging system. I tried to sucessfully genrate one with 
`make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- -j10 deb-pkg`

However files inside it are not compliant with raspberry pi kernel installations ways (not kernel8 file, ...). How to achieve that? Have you a script be include in the DEB package?

Thanks in advance.

**Comment by pelwell** [comment]
This is not the place to ask questions - it's for bug reports and the occasional module request - but the Raspberry Pi OS kernel .deb is a packaged version of the firmware files [here](https://github.com/raspberrypi/firmware/tree/master/boot), which in turn are the result of multiple builds following the instructions [here](https://www.raspberrypi.org/documentation/linux/kernel/building.md).
