### ISSUE TITLE
Can't compile modules or replacement kernel since raspberrypi-bootloader 2013-09-04

### ISSUE THREAD

**Issue by IvanExpert** [raspberrypi/linux#387]
Prior to raspberrypi-bootloader 2013-09-04, I have always been able to compile Linux kernel modules for Raspbian, or a replacement kernel, by using the method I outline at http://appleii.ivanx.com/a2server/a2server_raspberrypi_kernel.html.

As of raspberrypi-bootloader dated 2013-09-04, this is no longer possible. Any modules I create yield "ERROR: could not insert 'modulename': Exec format error" when I attempt to modprobe them. If I build an entire replacement kernel, it won't load ANY of the included modules.

I get the checkout hash for the correct Linux source tree with:
fwhash=$(zcat /usr/share/doc/raspberrypi-bootloader/changelog.Debian.gz | grep -m 1 'as of' | awk '{print $NF}')
wget -qO- https://raw.github.com/raspberrypi/firmware/$fwhash/extra/git_hash

But I think that with this latest release, the hash in changelog.Debian.gz must not be yielding the source tree that actually corresponds to the kernel and modules in raspberrypi-bootloader 2013-09-04, or 2013-12-10. Or something else is amiss.

**Comment by popcornmix** [comment]
Can you report output of:
`zcat /usr/share/doc/raspberrypi-bootloader/changelog.Debian.gz | grep -m 1 'as of' | awk '{print $NF}'`
`uname -a`

**Comment by IvanExpert** [comment]
zcat /usr/share/doc/raspberrypi-bootloader/changelog.Debian.gz:
  "d4f5315cfac4e"
which finds in raspberrypi/firmware/extra/git_hash:
  "1587f775d0a3c437485262ba951afc5e30be69fa"
uname -a:
  "Linux raspberrypi 3.6.11+ #538 PREEMPT Fri Aug 30 20:42:08 BST 2013 armv6l GNU/Linux"

If it helps, these hashes have been consistent (and the problem has been present) since the raspberrypi-bootloader package update dated 2013-09-04 in /usr/share/doc/raspberrypi-bootloader/changelog.Debian.gz, which was released sometime shortly prior to Raspbian 2013-09-10. It's still the same in Raspbian 2013-09-25.

**Comment by popcornmix** [comment]
I agree that:
https://github.com/raspberrypi/firmware/blob/8ec87498a913d2499880ff9a6a033e889e47758e/extra/git_hash
or
"1587f775d0a3c437485262ba951afc5e30be69fa"
should be the correct hash.

You can confirm this with:
https://github.com/raspberrypi/firmware/blob/8ec87498a913d2499880ff9a6a033e889e47758e/extra/uname_string

@asb any ideas why this is not working?

**Comment by IvanExpert** [comment]
Thought I'd mention that this is still the case in Raspbian 2013-09-25, as there has been no change to raspberrypi-bootloader from 2013-09-10.

**Comment by FozzTexx** [comment]
I'm having the same problem, I'm trying to compile the iec module for my ninepin project. Nothing I do will generate a module that works with the 2013-09-25 kernel.

**Comment by IvanExpert** [comment]
Just tried it again using the commits that correspond to the rpi-bootloader package dated 10-Dec-2013, which uses kernel 3.10.23+, and the subsequent one, dated 20-Dec-2013, which uses kernel 3.10.24+.

I was hopeful, but no dice. Same issues: any modules that I build refuse to be loaded by the included kernel; if I replace the kernel outright, it won't work with any of the included modules. Again, it seems as if what's there doesn't correspond to what I'm building, somehow. But this didn't use to be the case; prior to the version of 04-Sep-13, I could always use a single module that I built, or replace just the kernel that I built, without having to rock the rest of the boat.

Might this be a problem with spindle? Should I put in a report there?

**Comment by brabl2** [comment]
I had similar problem. I was not able to load modules compiled on the Raspberry Pi / Raspbian (using gcc installed with apt-get). I remember it was working with versions 3.2.y.
My problems disappeared after I switched to cross-compiler from here: https://github.com/raspberrypi/tools/tree/master/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian
May be you can try it instead of gcc-arm-linux-gnueabi you are using.
It works with the Raspbian kernel 3.10.25+
Linux raspberrypi 3.10.25+ #622 PREEMPT Fri Jan 3 18:41:00 GMT 2014 armv6l GNU/Linux
https://github.com/raspberrypi/firmware/blob/3a4ba0c3964f8f0ecc2dd46246a83258d9e4046d/extra/uname_string
https://github.com/raspberrypi/firmware/blob/3a4ba0c3964f8f0ecc2dd46246a83258d9e4046d/extra/git_hash
https://github.com/raspberrypi/linux/tree/16eb921a96db3dc3555a65b53b99c15753e6b770

**Comment by IvanExpert** [comment]
That worked! (To clarify, after cloning "tools" to be along side the "linux" folder, I used CROSS_COMPILE=../tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian/bin/arm-linux-gnueabihf-)

THANK YOU.

**Comment by Ruffio** [comment]
@IvanExpert has this issue been resolved? If yes, then please close this issue.

**Comment by IvanExpert** [comment]
Yes, this is resolved.
