### ISSUE TITLE
mDNS domain name has changed from local to lan

### ISSUE THREAD

**Issue by mats-nk** [raspberrypi/linux#3871]
mDNS default configuration has changed so the Rasspberry Pi OS doesnt respond to the previous mDNS hostname `raspberrypi.local` but `raspberrypi.lan`

But when examining the processes running a `ps aux` shows a row with:

`avahi      297  0.0  0.6   5756  2920 ?        Ss   13:56   0:00 avahi-daemon: running [raspberrypi.local]`

So its a bit confusing!

**Comment by ghost** [comment]
By any chance have you recently installed Pi-Hole?

**Comment by mats-nk** [comment]
A clean install of "2020-08-20-raspios-buster-armhf-lite".

Only installed updates and git

And I did 3 images and downloaded the image file once more to be sure.

**Comment by cmitu** [comment]
@mats-nk are you sure the `raspberrypi.lan` isn't set by your local router/DNS server ? Either way, this is not really a Linux kernel issue, you should use the Raspberry Pi forums or the Raspbian issue tracker.
