### ISSUE TITLE
rpi-5.9.y BRCM_CHAR_DRIVERS are not selectable/available in menuconfig

### ISSUE THREAD

**Issue by asavah** [raspberrypi/linux#3875]
**Describe the bug**
rpi-5.9.y BRCM_CHAR_DRIVERS are not selectable/available in menuconfig
make oldconfig did not pick them up from 5.8.y config either.
Thus CONFIG_BCM2708_VCMEM, CONFIG_RPIVID_MEM, CONFIG_BCM2835_DEVGPIOMEM , CONFIG_BCM_VCIO and friends are not available.
This was noticed because RPi.GPIO stopped working on rpi-5.9.y (aarch64).
The error is "Not running on a RPi!"; examining RPi.GPIO source code pointed me to missing /dev/gpiomem node.

**Additional context**
It seems that these lines
https://github.com/raspberrypi/linux/blob/rpi-5.8.y/drivers/char/Kconfig#L8
https://github.com/raspberrypi/linux/blob/rpi-5.8.y/drivers/char/Makefile#L50
may have been lost in the rebase(s).

Readding said lines fixes the issue.
After patching , reconfiguring and rebuilding the kernel /dev/gpiomem was runtime tested, RPi.GPIO works again.

**Comment by popcornmix** [comment]
Thanks I've pushed it.

It got dropped as it was initially included as part of the vcsm commit, which is deprecated and was dropped for 5.9.
But as other char drivers are still working they should be built.

**Comment by asavah** [comment]
Thanks.
