### ISSUE TITLE
registration of SPI-devices on the command line without recompiling the kernel

### ISSUE THREAD

**Issue by msperl** [raspberrypi/linux#391]
Hi!

After so many people have a hard time reconfiguring their system to enable specific SPI devices (see especially PYCAN module issue) here a solution that may help people to make some bought modules work out of the box - or with minimal effort...

This module - for now called spi-config - accepts an argrument that allows registration of the SPI devices on the fly.

The following:
`modprobe spi-config devices=bus=0:cs=0:modalias=mcp2515:speed=10000000:gpioirq=25:pd=140024f4000220`

would configure a mcp2515 controller with a max_spi_speed of 10MHz and the IRQ on GPIO25 on SPI0.0.
It will also configure the CAN controller clock rate (@16MHz).

Configuring an ADC or similar would also using the same means.

I know that this may be a bit to the contrary to the device-tree approach which we need to follow in the long run, but then for dts you will again need the kernel sources to compile it and risk is much higher that "newbies" would kill their system immediately due to a bad config and then need to "rip out" the SD card and boot into recovery mode...

So I believe this may be a valid approach that would help a lot of people starting with SPI and their newly bought extension modules. It would also help all those who have to support such modules to get the devices deployed with minimal effort...

So please have a look at the module at: https://github.com/msperl/spi-config
and think of if you may not want to integrate it with the "default" kernel you ship with Raspian...

Thank,
          Martin

P.s: the requirement on arch/arm/mach-bcm-2708.c is that it does not register SPI devices (SPIDEV) there - otherwise it might not work, as the devices are already installed

**Comment by msperl** [comment]
Update: the module does not require the removal of registered devices any longer - there is now an argument to force the release of the original SPI-device, but this will taint the kernel, so that we know about it...

Note that only with the latest release of the code the kernel compiles for linux <3.9 - there was a change a with that version where add_taint got an additional parameter, so the original code did not compile on earlier kernels.

now I have also tested using a self-compiled 3.6.11 kernel and it works the same...

Martin

**Comment by popcornmix** [comment]
Can you submit a PR against the main linux tree (the 3.10.y branch may be best, as we will move to that as a default soon).
SPI isn't something I use, but if there are no objections to the PR, and it doesn't break anything for me, then I'm willing to accept it, as it sounds useful.

**Comment by msperl** [comment]
I develop against 3.11 and have compiled it against 3.6.

I will try to create a patch for either of those (probably putting it into driver/staging/spi).
The pull requests should apply "cleanly" to the kernel of your choice (as it would not touch anything - besides KConfig)

I am also waiting for some reply from the upstream SPI dev group to get their feedback as well, as it is not only valuable to the RPI, but to other boards as well...
