### ISSUE TITLE
Request: kernel initrd support

### ISSUE THREAD

**Issue by retux** [raspberrypi/linux#392]
Would you please consider including this option in stock kernel build?

CONFIG_BLK_DEV_INITRD=y

initrd is a very useful feature, i.e. for using uuid ID in cmdline.txt.

Thanks!

**Comment by popcornmix** [comment]
Can you determine the memory cost of this option?
i.e. after booting from default kernel what does
`free -h`
report? After enabling that option what does it report?

**Comment by retux** [comment]
kernel using initrd:

$ free -h
             total       used       free     shared    buffers     cached
Mem:          438M        52M       385M         0B       6,6M        25M
-/+ buffers/cache:        21M       417M
Swap:          99M         0B        99M

Reported by dmesg:

[    1.049995] Trying to unpack rootfs image as initramfs...
[    1.501765] Freeing initrd memory: 3456K

kernel not using initrd:

 $ zcat /proc/config.gz | grep -i initrd
 # CONFIG_BLK_DEV_INITRD is not set

pi@raspberrypi ~ $ dmesg | grep -i initr
pi@raspberrypi ~ $ 

$ free -h
             total       used       free     shared    buffers     cached
Mem:          438M        51M       386M         0B       7.9M        23M
-/+ buffers/cache:        20M       417M
Swap:          99M         0B        99M

It seems there's no big differences in terms of memory usage.

**Comment by popcornmix** [comment]
Can you test next firmware branch - should be added.
sudo BRANCH=next rpi-update

**Comment by retux** [comment]
cool! I'll test it as soon as possible.
I tested and everything initrd related works just fine.
Thanks a lot!

**Comment by evilpower** [comment]
This was the only reason why I was compiling my own kernels for the past year. With initrd enabled and a simple initramfs we can set up root fs as btrfs or f2fs or anything else that's built in the kernel with a breeze. I hope this gets carried over to the master branch as well. Thank you!

**Comment by retux** [comment]
lurch,
Yes, it does. I'm using UUID through cmdline.txt, but in order to use it is required to create an initial ram disk (initrd). That's why adding initrd support to the stock kernel has been very useful.
Now initrd support is included in the stock kernel using initrd and all the features it allows is much easier.

**Comment by lurch** [comment]
In that case, maybe both this bug and your other one I linked to ( https://github.com/raspberrypi/firmware/issues/209 ) should both be closed? ;-)

**Comment by retux** [comment]
You're right. Sorry I just closed both issues.
Regards,
Matías
