### ISSUE TITLE
MAC address is forced on all connected lan95xx devices

### ISSUE THREAD

**Issue by P33M** [raspberrypi/linux#394]
Ref commit https://github.com/raspberrypi/linux/commit/b102abd4d519186f3ed132242c896308e853c509

If additional 10/100 ethernet dongles using the smsc 9500/951x chipset are attached to the Pi. they all end up with the same MAC address. This is bad if they end up attached to the same network segment.

**Comment by notro** [comment]
Changing the order will help chips that has an eeprom connected:

``` text
 static void smsc95xx_init_mac_address(struct usbnet *dev)
 {
-      /* Check module parameters */
-      if (smsc95xx_is_macaddr_param(dev, dev->net->dev_addr))
-              return;
- 
    /* try reading mac address from EEPROM */
    if (smsc95xx_read_eeprom(dev, EEPROM_MAC_OFFSET, ETH_ALEN,
            dev->net->dev_addr) == 0) {
        if (is_valid_ether_addr(dev->net->dev_addr)) {
            /* eeprom values are valid so use them */
            netif_dbg(dev, ifup, dev->net, "MAC address read from EEPROM\n");
            return;
        }
    }

+        /* Check module parameters */
+        if (smsc95xx_is_macaddr_param(dev, dev->net->dev_addr))
+                return;
+ 
    /* no eeprom, or eeprom values are invalid. generate random MAC */
    eth_hw_addr_random(dev->net);
    netif_dbg(dev, ifup, dev->net, "MAC address set to eth_random_addr\n");
 }
```

In the case of more than one chip without an eeprom, the address can be changed like this:

_/etc/network/interfaces_

``` text
auto eth0
iface eth0 inet dhcp
hwaddress ether b8:27:eb:39:78:8f
```

I don't know how common it is to not have an eeprom with these chips. Maybe the cheap dongles don't have it?

**Comment by Ruffio** [comment]
@P33M has this issue been resolved? If yes, then please close this issue.

**Comment by popcornmix** [comment]
If there is an eprom, it will now take precedence: https://github.com/raspberrypi/linux/commit/55e8519aa4c86b37f1933e8e53c6e97372d61871

**Comment by Ruffio** [comment]
@P33M has this issue been fixed? If so, please this issue, thanks.

**Comment by JamesH65** [comment]
@P33M Can this be closed?

**Comment by P33M** [comment]
smsc95xx.c now looks up of_get_mac_address. Our DT specifies a local-mac-address for one USB device node only, so this is fixed.
