### ISSUE TITLE
How to turn off the shortcut key of the console

### ISSUE THREAD

**Issue by git-chenjiqing** [raspberrypi/linux#3952]
for example

ctrl+alt+f1 \ alt+f1

**Comment by pelwell** [comment]
This is not the right place to ask general Linux questions - this is for reporting bugs and problems with the Raspberry Pi kernels.

Read this (https://www.thegeekdiary.com/centos-rhel-7-how-to-disable-all-tty-consoles-and-enable-only-1/), and if that still doesn't answer your question go to the Raspberry Pi Forums, e.g. https://www.raspberrypi.org/forums/viewforum.php?f=66.
