### ISSUE TITLE
PL011: no DMA platform data

### ISSUE THREAD

**Issue by jansendup** [raspberrypi/linux#396]
in drivers/tty/serial/amba-pl011.c uap->port.dev->platform_data is NULL on the bcm2835 arch causing DMA probe to fail. thus no DMA on the uart module.

**Comment by popcornmix** [comment]
Is there an upstream commit I can pull in?

**Comment by jansendup** [comment]
Not quite sure where to look. Maybe you can check.
In arch/arm/mach-bcm2708/bcm2708.c line 242: "AMBA_DEVICE(uart0, "dev:f1", UART0, NULL);"
The last parameter of AMBA_DEVICE should be a pointer to a "struct amba_pl011_data" that is defined in include/linux/amba/serial.h line 201.

**Comment by popcornmix** [comment]
It is not possible to dma from/to the uart, so I think a DMA probe failure is correct.

**Comment by P33M** [comment]
In the BCM2835 peripherals datasheet, UART1 is explicitly defined as having no DMA support. UART0 has a DREQ line entry for tx/rx in the DMA controller section - DREQ 12/14 respectively.

Are there free DMA channels for use by the UART?

**Comment by jansendup** [comment]
I quickly tried setting filter_fn in struct dma_chan *dma_request_channel(dma_cap_mask_t mask,dma_filter_fn filter_fn,void *filter_param); to NULL. If I understand it correctly, dma_request_channel should just then return any available channel. It returned NULL so it might be that there aren't any available channels. dma_request_slave_channel(dev, "tx") also returned NULL.

**Comment by jansendup** [comment]
It seems that there is no dmaengine driver for the BCM2835 so thats probably why the last parameter in arch/arm/mach-bcm2708/bcm2708.c line 242: "AMBA_DEVICE(uart0, "dev:f1", UART0, NULL);" is NULL.

**Comment by P33M** [comment]
It appears you are correct; there are no dma engine drivers for either the bcm2708 port (this repo) or the upstream bcm2835 port. It looks like several people have had a go but not upstreamed it.

It would be necessary to get a platform DMA driver implemented before adding support to the peripheral drivers (i2c/spi/uart).

**Comment by popcornmix** [comment]
@jansendup 
I assume there is nothing to change here - okay to close?
