### ISSUE TITLE
[5.10] enable feature: F2FS compression

### ISSUE THREAD

**Issue by pasman1** [raspberrypi/linux#3960]
Hi.

There are plans to polish f2fs compression for production use:

https://lore.kernel.org/lkml/20201015225508.GA2465821@google.com/

I think it's worth testing this feature. 
Initially only lz4 compression method may be enabled, to check a kernel size & memory consumption.

**Comment by popcornmix** [comment]
Can you build a kernel with this enabled and confirm it works?
CONFIG_F2FS_FS_COMPRESSION
https://www.raspberrypi.org/documentation/linux/kernel/building.md

We'd also be intersted in kernel size (of /boot/kernel7l.img) with and without the change and the free memory ("free" after boot) with and without.

**Comment by pasman1** [comment]
This take some time - I have 2-core laptop only.

**Comment by pelwell** [comment]
We can wait.

**Comment by pasman1** [comment]
First compilation of 5.10-rc3 32bit. Compressed kernel is bigger about 92kb 
for all compression methods enabled or 26kb for lz4 only

**Comment by pasman1** [comment]
Ok. I do not need this feature.
