### ISSUE TITLE
logger not sending information over the wire

### ISSUE THREAD

**Issue by douglagm** [raspberrypi/linux#397]
Hi,
I am trying to use logger to send the status of local scripts to a rsyslog server, but they never seem to even leave the PI.

I am using the following command: sudo logger -n rsyslog-server -P 514 -p local0.err -t enviro -d "Hello from PI"

I run tcpdump on the PI and on the rsyslog server: tcpdump -i eth0 -s0 port 514

It never captures any syslog traffic.

System Info
uname -a
Linux raspberrypi 3.6.11+ #538 PREEMPT Fri Aug 30 20:42:08 BST 2013 armv6l GNU/Linux

sudo dpkg -l | grep util-linux
ii  util-linux                            2.20.1-5.3                             armhf        Miscellaneous system utilities

Regards
Gregg

**Comment by P33M** [comment]
This does not appear to be a kernel-specific issue. You may have better luck diagnosing what's probably a userspace/network issue on the forums.
