### ISSUE TITLE
rpi-4.19.y-rt kernel building issue in compute module 4

### ISSUE THREAD

**Issue by TopgunZh** [raspberrypi/linux#3970]
I build the rpi-4.19.y-rt kernel done.But i can't find the bcm2711-rpi-cm4.dtb.
![image](https://user-images.githubusercontent.com/39727447/100197394-3beb9880-2f35-11eb-9124-faea1b8e1229.png)

**Comment by pelwell** [comment]
We don't currently support CM4 on 4.19 - it launched on 5.4, and we haven't back-ported it. There's no reason why it shouldn't work, but it hasn't been done.

**Comment by TopgunZh** [comment]
Now i apply patches on 5.4,it works well.Thanks.
