### ISSUE TITLE
Microsoft wireless mouse 3500 cursor overshoot 

### ISSUE THREAD

**Issue by jwcolby54** [raspberrypi/linux#3973]
Mouse works however the mouse overshoots, i.e. keeps travelling after stopping the mouse physically.  

RPI4 8gb, latest 32 bit version, all updates applied.  

Not a Linux geek so if more is needed please let me know.

**Comment by P33M** [comment]
This is a repository for reporting bugs in our downstream Linux kernel. Issues unrelated to the Linux kernel (such as support requests) should be posted on the community forum at https://www.raspberrypi.org/forum
