### ISSUE TITLE
Audio channels swap constantly when playing over HDMI at > 96kHz (8 channel PCM)

### ISSUE THREAD

**Issue by tghewett** [raspberrypi/linux#402]
Audio channels swap about every second when playing 8 channel PCM at 176.4kHz and 192kHz over HDMI. If playing stereo PCM, i.e. just front left and right, all other 6 channels silent, the sound sometimes comes out the front speakers, sometimes the rear, sometimes very loud, sometimes quieter.

Sample size makes no difference. The problem doesn't happen at 96kHz or lower.

**Comment by popcornmix** [comment]
Correct. This is a hardware limitation. 8 channel 192kHz does result in a fifo underrun, and I guess channel swapping could be a symptom of that.
I don't believe there is a workaroud.

**Comment by tghewett** [comment]
Closed as not fixable.
