### ISSUE TITLE
Add BTRFS to the kernal for a root mount

### ISSUE THREAD

**Issue by DoubleAgentDave** [raspberrypi/linux#4029]
BTRFS is not the unstable mess that it used to be, it would be really helpful to add support to allow people to experiment with a modern file-system on the pi. Especially with booting from SSDs on USB sticks or via pci-e on the compute module.

**Comment by pelwell** [comment]
It's a currently a 2.3MB module - that would be a large penalty for users of (say) a Pi Zero which only has 512MB, or a Model B with only 256MB. Like all the other modules that a few people like to have before the filesystem comes up, you'll have to use an initrd/initramfs - or just build your own kernel.
