### ISSUE TITLE
Problems with mixing the centre channel to FL and FR speakers in 8-ch PCM

### ISSUE THREAD

**Issue by tghewett** [raspberrypi/linux#403]
At 96kHz sample rate or less, for systems without a centre speaker the centre channel doesn't get mixed into the front left and right speakers when sent as part of 8 channel PCM (the LFE channel is mixed fine when no subwoofer is present). Checked to see if the amp is bugged by playing from another source as 8-ch PCM but it has no problem with mixing the centre channel into the FL and FR speakers. Possible channel labelling issue?

**Comment by popcornmix** [comment]
How are you outputting audio - with hello_audio?

Currently multichannel audio mapping hasn't been used much (although there are plans for omxplayer/xbmc to support multichannel PCM, so this is something that should be improved).
Currently the audio info frame channel mapping is fixed to:
static const char map[] = {0, 0, 0, 1, 3, 7, 0xb, 0xf, 0x13};

(where index is number of channels). These numbers come from:
7.5.3 Speaker Allocation Data Block of CEA-861.

I'm not sure there is any other channel labelling info available.

**Comment by tghewett** [comment]
The problem is experienced when using hello_audio. When using a Blu-ray player to play the same audio (actually 5.1 AC3 music where the centre channel carries the vocals), with the player set to decode the AC3 to multichannel PCM before sending it over the HDMI link (confirmed as 7.1 PCM by the amp's display), the centre channel is clearly mixed into the FL and FR speakers.

**Comment by popcornmix** [comment]
How are you ordering the PCM channels?
I think one issue is there are many standards for that (e.g. AAC differs from WAV on channel ordering).

**Comment by tghewett** [comment]
In my tests it shouldn't make any difference - all channels were made to carry audio and all were muted with each de-muted in turn to see if one was being treated as the centre speaker and mixed into the FL and FR speakers. Only the LFE channel was found to be mixed in this way.

**Comment by popcornmix** [comment]
Do you believe the channels are being mixed inside the GPU?
Or is the signalling causing the receiver to mix channels?

Can you provide your version of hello audio that shows the problem?

**Comment by tghewett** [comment]
[edited 20:53 GMT 17/10/13]

The problem seems to be the amp. Changing the speaker configuration to having a subwoofer and centre speaker connected turns off the mixing of them into the FL/FR speakers, and confirmed I had the centre and LFE channels ordered wrongly (so really the amp was mixing the centre channel and not the LFE instead of the opposite as was heard previously). Now with LFE switched to the third channel and centre on the fourth channel (and all other channels muted), and also the speaker settings restored to having no centre or LFE, the amp was now mixing in the vocals but still no LFE. For entirely separate reasons the amp was power-cycled and now it is mixing both channels, all others still muted, so somehow the sequence of events has fixed the problem. Heisenbug?
