### ISSUE TITLE
bcm2835-v4l2-codec.c has logic error identified by clang.

### ISSUE THREAD

**Issue by iucoen** [raspberrypi/linux#4040]
**Describe the bug**

When compiling the kernel with clang, clang warns:

`
drivers/staging/vc04_services/bcm2835-codec/bcm2835-v4l2-codec.c:911:7: warning: logical not is only applied to the left hand side of this bitwise operator [-Wlogical-not-parentheses]

                if (!mmal_buf->mmal_flags & MMAL_BUFFER_HEADER_FLAG_EOS) {

                    ^                     ~

drivers/staging/vc04_services/bcm2835-codec/bcm2835-v4l2-codec.c:911:7: note: add parentheses after the '!' to evaluate the bitwise operator first

                if (!mmal_buf->mmal_flags & MMAL_BUFFER_HEADER_FLAG_EOS) {

                    ^

drivers/staging/vc04_services/bcm2835-codec/bcm2835-v4l2-codec.c:911:7: note: add parentheses around left hand side expression to silence this warning

                if (!mmal_buf->mmal_flags & MMAL_BUFFER_HEADER_FLAG_EOS) {

                    ^

drivers/staging/vc04_services/bcm2835-codec/bcm2835-v4l2-codec.c:1137:6: warning: logical not is only applied to the left hand side of this bitwise operator [-Wlogical-not-parentheses]

        if (!fmt->flags & V4L2_FMT_FLAG_COMPRESSED) {

            ^           ~

drivers/staging/vc04_services/bcm2835-codec/bcm2835-v4l2-codec.c:1137:6: note: add parentheses after the '!' to evaluate the bitwise operator first

        if (!fmt->flags & V4L2_FMT_FLAG_COMPRESSED) {

            ^

drivers/staging/vc04_services/bcm2835-codec/bcm2835-v4l2-codec.c:1137:6: note: add parentheses around left hand side expression to silence this warning

        if (!fmt->flags & V4L2_FMT_FLAG_COMPRESSED) {

            ^
`

The warning identifies a legitimate bug. Parentheses are needed around operator&.

**To reproduce**
LLVM=1 ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- make bcm2709_defconfig
LLVM=1 ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- make -j$(nproc) zImage modules dtbs

**System**
 Cross compiling from Ubuntu-20.04 x86_64

**Comment by popcornmix** [comment]
I agree - looks like a genuine bug in the code. @6by9?

**Comment by 6by9** [comment]
Yes, patch in progress. It may explain some of the oddities that @jc-kynesim sometimes sees too.
