### ISSUE TITLE
RPi4 does not detect 5GHz WiFi as higher channels aren't enabled

### ISSUE THREAD

**Issue by stealthm0d3** [raspberrypi/linux#4042]
**Describe the bug**
Latest builds of RPi4 do not show the higher channels such as channel 149, despite selecting the correct country, and therefore prevents from joining 5GHz WiFI networks that operate on these channels.

**To reproduce**
Install RaspberrPi OS 4.

**Expected behaviour**
Add a clear and concise description of what you expected to happen.

**Actual behaviour**
Add a clear and concise description of what actually happened.

**System**
 Copy and paste the results of the raspinfo command in to this section. Alternatively, copy and paste a pastebin link, or add answers to the following questions:

* Which model of Raspberry Pi? 
* 
* 
Pi4
* Which OS and version (`cat /etc/rpi-issue`)?
* Which firmware version (`vcgencmd version`)?

kali@kali:~$ vcgencmd version
Apr 27 2020 14:33:37
Copyright (c) 2012 Broadcom
version 3a8f1793b758d6fb7f375edaa260e069ecd34c88 (clean) (release) (start)

* Which kernel version (`uname -a`)?

kali@kali:~$ uname -a
Linux kali 4.19.118-Re4son-v8l+ #1 SMP PREEMPT Thu May 7 02:54:03 UTC 2020 aarch64 GNU/Linux

**Logs**

wlan0     32 channels in total; available frequencies :
          Channel 01 : 2.412 GHz
          Channel 02 : 2.417 GHz
          Channel 03 : 2.422 GHz
          Channel 04 : 2.427 GHz
          Channel 05 : 2.432 GHz
          Channel 06 : 2.437 GHz
          Channel 07 : 2.442 GHz
          Channel 08 : 2.447 GHz
          Channel 09 : 2.452 GHz
          Channel 10 : 2.457 GHz
          Channel 11 : 2.462 GHz
          Channel 12 : 2.467 GHz
          Channel 13 : 2.472 GHz
          Channel 34 : 5.17 GHz
          Channel 36 : 5.18 GHz
          Channel 38 : 5.19 GHz
          Channel 40 : 5.2 GHz
          Channel 42 : 5.21 GHz
          Channel 44 : 5.22 GHz
          Channel 46 : 5.23 GHz
          Channel 48 : 5.24 GHz
          Channel 52 : 5.26 GHz
          Channel 56 : 5.28 GHz
          Channel 60 : 5.3 GHz
          Channel 64 : 5.32 GHz
          Channel 100 : 5.5 GHz
          Channel 104 : 5.52 GHz
          Channel 108 : 5.54 GHz
          Channel 112 : 5.56 GHz
          Channel 116 : 5.58 GHz
          Channel 120 : 5.6 GHz
          Channel 124 : 5.62 GHz
          Current Frequency:2.442 GHz (Channel 7)

kali@kali:~$ sudo iw reg get
[sudo] password for kali:
global
country IN: DFS-UNSET
	(2402 - 2482 @ 40), (N/A, 20), (N/A)
	(5150 - 5250 @ 80), (N/A, 30), (N/A)
	(5250 - 5350 @ 80), (N/A, 24), (N/A)
	(5470 - 5725 @ 160), (N/A, 24), (N/A)
	(5725 - 5875 @ 80), (N/A, 30), (N/A)

**Additional context**
It also seems that the RaspberryPi has been hardcoded to IN frequency. I am unable to set the country to another code by using `raspi-config` or even with using `iw reg set` command. 

How can I change the country to test this?

**Comment by pelwell** [comment]
Unless your problem is also present in Raspberry Pi OS (and I don't think it is) this is not the place to report it - we have no control over Kali Linux and do not support it.
