### ISSUE TITLE
[rpi 4 4gb] - kernel 5.10]  720 not working kms

### ISSUE THREAD

**Issue by jamieS95** [raspberrypi/linux#4044]
**Is this the right place for my bug report?**
not sure

**Describe the bug**
720 not working kms

**To reproduce**
added to config:
hdmi_group=1
hdmi_mode=3
dtoverlay=vc4-kms-v3d

changed resoultion to 720 in raspi-config

xrandr reports: 1080p 

**Expected behaviour**
720 resolution

**Actual behaviour**
1080 resolution

**System**
 Copy and paste the results of the raspinfo command in to this section. Alternatively, copy and paste a pastebin link, or add answers to the following questions:

* Which model of Raspberry Pi? 4 4gb
cat /etc/rpi-issue
Raspberry Pi reference 2020-08-20
Generated using pi-gen, https://github.com/RPi-Distro/pi-gen, 7252c154838ec5b4576f29c996ac8fe3750cae12, stage4

vcgencmd version
Dec 15 2020 18:28:46
Copyright (c) 2012 Broadcom
version 4b4aff21f72c5b9ba39d83c7b0f8fa910a6ef99b (clean) (release) (start)

 uname -a
Linux raspberrypi 5.10.3-v8+ #1386 SMP PREEMPT Sun Dec 27 14:09:57 GMT 2020 aarch64 GNU/Linux

**Logs**

[    0.000000] Booting Linux on physical CPU 0x0000000000 [0x410fd083]
[    0.000000] Linux version 5.10.3-v8+ (dom@buildbot) (aarch64-linux-gnu-gcc-8 (Ubuntu/Linaro 8.4.0-3ubuntu1) 8.4.0, GNU ld (GNU Binutils for Ubuntu) 2.34) #1386 SMP PREEMPT Sun Dec 27 14:09:57 GMT 2020
[    0.000000] Machine model: Raspberry Pi 4 Model B Rev 1.1
[    0.000000] efi: UEFI not found.
[    0.000000] Reserved memory: created CMA memory pool at 0x000000001ec00000, size 256 MiB
[    0.000000] OF: reserved mem: initialized node linux,cma, compatible id shared-dma-pool
[    0.000000] Zone ranges:
[    0.000000]   DMA      [mem 0x0000000000000000-0x000000003fffffff]
[    0.000000]   DMA32    [mem 0x0000000040000000-0x00000000fbffffff]
[    0.000000]   Normal   empty
[    0.000000] Movable zone start for each node
[    0.000000] Early memory node ranges
[    0.000000]   node   0: [mem 0x0000000000000000-0x000000003b3fffff]
[    0.000000]   node   0: [mem 0x0000000040000000-0x00000000fbffffff]
[    0.000000] Initmem setup node 0 [mem 0x0000000000000000-0x00000000fbffffff]
[    0.000000] On node 0 totalpages: 1012736
[    0.000000]   DMA zone: 3792 pages used for memmap
[    0.000000]   DMA zone: 0 pages reserved
[    0.000000]   DMA zone: 242688 pages, LIFO batch:63
[    0.000000]   DMA32 zone: 12032 pages used for memmap
[    0.000000]   DMA32 zone: 770048 pages, LIFO batch:63
[    0.000000] percpu: Embedded 32 pages/cpu s91160 r8192 d31720 u131072
[    0.000000] pcpu-alloc: s91160 r8192 d31720 u131072 alloc=32*4096
[    0.000000] pcpu-alloc: [0] 0 [0] 1 [0] 2 [0] 3
[    0.000000] Detected PIPT I-cache on CPU0
[    0.000000] CPU features: detected: Spectre-v2
[    0.000000] CPU features: detected: Spectre-v4
[    0.000000] CPU features: detected: ARM errata 1165522, 1319367, or 1530923
[    0.000000] Built 1 zonelists, mobility grouping on.  Total pages: 996912
[    0.000000] Kernel command line: coherent_pool=1M 8250.nr_uarts=0 snd_bcm2835.enable_compat_alsa=0 snd_bcm2835.enable_hdmi=1 video=HDMI-A-1:1920x1080M@60 smsc95xx.macaddr=DC:A6:32:55:43:C6 vc_mem.mem_base=0x3ec00000 vc_mem.mem_size=0x40000000  console=ttyS0,115200 console=tty1 root=PARTUUID=c98ea287-02 rootfstype=ext4 elevator=deadline fsck.repair=yes rootwait quiet splash plymouth.ignore-serial-consoles
[    0.000000] Kernel parameter elevator= does not have any effect anymore.
               Please use sysfs to set IO scheduler for individual devices.
[    0.000000] Dentry cache hash table entries: 524288 (order: 10, 4194304 bytes, linear)
[    0.000000] Inode-cache hash table entries: 262144 (order: 9, 2097152 bytes, linear)
[    0.000000] mem auto-init: stack:off, heap alloc:off, heap free:off
[    0.000000] software IO TLB: mapped [mem 0x0000000037400000-0x000000003b400000] (64MB)
[    0.000000] Memory: 3620704K/4050944K available (10880K kernel code, 1908K rwdata, 3908K rodata, 3648K init, 1242K bss, 168096K reserved, 262144K cma-reserved)
[    0.000000] SLUB: HWalign=64, Order=0-3, MinObjects=0, CPUs=4, Nodes=1
[    0.000000] ftrace: allocating 36043 entries in 141 pages
[    0.000000] ftrace: allocated 141 pages with 4 groups
[    0.000000] rcu: Preemptible hierarchical RCU implementation.
[    0.000000] rcu:     RCU event tracing is enabled.
[    0.000000] rcu:     RCU restricting CPUs from NR_CPUS=256 to nr_cpu_ids=4.
[    0.000000]  Trampoline variant of Tasks RCU enabled.
[    0.000000]  Rude variant of Tasks RCU enabled.
[    0.000000]  Tracing variant of Tasks RCU enabled.
[    0.000000] rcu: RCU calculated value of scheduler-enlistment delay is 25 jiffies.
[    0.000000] rcu: Adjusting geometry for rcu_fanout_leaf=16, nr_cpu_ids=4
[    0.000000] NR_IRQS: 64, nr_irqs: 64, preallocated irqs: 0
[    0.000000] GIC: Using split EOI/Deactivate mode
[    0.000000] random: get_random_bytes called from start_kernel+0x3b8/0x578 with crng_init=0
[    0.000000] arch_timer: cp15 timer(s) running at 54.00MHz (phys).
[    0.000000] clocksource: arch_sys_counter: mask: 0xffffffffffffff max_cycles: 0xc743ce346, max_idle_ns: 440795203123 ns
[    0.000002] sched_clock: 56 bits at 54MHz, resolution 18ns, wraps every 4398046511102ns
[    0.000113] Console: colour dummy device 80x25
[    0.000139] printk: console [tty1] enabled
[    0.000165] Calibrating delay loop (skipped), value calculated using timer frequency.. 108.00 BogoMIPS (lpj=216000)
[    0.000175] pid_max: default: 32768 minimum: 301
[    0.000234] LSM: Security Framework initializing
[    0.000342] Mount-cache hash table entries: 8192 (order: 4, 65536 bytes, linear)
[    0.000381] Mountpoint-cache hash table entries: 8192 (order: 4, 65536 bytes, linear)
[    0.000997] Disabling memory control group subsystem
[    0.001743] rcu: Hierarchical SRCU implementation.
[    0.002175] EFI services will not be available.
[    0.002380] smp: Bringing up secondary CPUs ...
[    0.002785] Detected PIPT I-cache on CPU1
[    0.002829] CPU1: Booted secondary processor 0x0000000001 [0x410fd083]
[    0.003276] Detected PIPT I-cache on CPU2
[    0.003293] CPU2: Booted secondary processor 0x0000000002 [0x410fd083]
[    0.003680] Detected PIPT I-cache on CPU3
[    0.003697] CPU3: Booted secondary processor 0x0000000003 [0x410fd083]
[    0.003748] smp: Brought up 1 node, 4 CPUs
[    0.003754] SMP: Total of 4 processors activated.
[    0.003759] CPU features: detected: 32-bit EL0 Support
[    0.003764] CPU features: detected: CRC32 instructions
[    0.003768] CPU features: detected: 32-bit EL1 Support
[    0.015723] CPU: All CPU(s) started at EL2
[    0.015750] alternatives: patching kernel code
[    0.016647] devtmpfs: initialized
[    0.020720] Enabled cp15_barrier support
[    0.020737] Enabled setend support
[    0.021063] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 7645041785100000 ns
[    0.021077] futex hash table entries: 1024 (order: 4, 65536 bytes, linear)
[    0.025384] pinctrl core: initialized pinctrl subsystem
[    0.025738] DMI not present or invalid.
[    0.025914] NET: Registered protocol family 16
[    0.027116] DMA: preallocated 1024 KiB GFP_KERNEL pool for atomic allocations
[    0.027209] DMA: preallocated 1024 KiB GFP_KERNEL|GFP_DMA pool for atomic allocations
[    0.027513] DMA: preallocated 1024 KiB GFP_KERNEL|GFP_DMA32 pool for atomic allocations
[    0.027555] audit: initializing netlink subsys (disabled)
[    0.027725] audit: type=2000 audit(0.024:1): state=initialized audit_enabled=0 res=1
[    0.027922] thermal_sys: Registered thermal governor 'step_wise'
[    0.028140] cpuidle: using governor menu
[    0.028284] hw-breakpoint: found 6 breakpoint and 4 watchpoint registers.
[    0.028346] ASID allocator initialised with 65536 entries
[    0.028395] Serial: AMBA PL011 UART driver
[    0.041024] bcm2835-mbox fe00b880.mailbox: mailbox enabled
[    0.048109] raspberrypi-firmware soc:firmware: Attached to firmware from 2020-12-15T18:28:46, variant start
[    0.052112] raspberrypi-firmware soc:firmware: Firmware hash is 4b4aff21f72c5b9ba39d83c7b0f8fa910a6ef99b
[    0.066131] bcm2835-dma fe007000.dma: DMA legacy API manager, dmachans=0x1
[    0.067580] vgaarb: loaded
[    0.067783] SCSI subsystem initialized
[    0.067869] usbcore: registered new interface driver usbfs
[    0.067889] usbcore: registered new interface driver hub
[    0.067937] usbcore: registered new device driver usb
[    0.068067] usb_phy_generic phy: supply vcc not found, using dummy regulator
[    0.068958] clocksource: Switched to clocksource arch_sys_counter
[    0.411487] VFS: Disk quotas dquot_6.6.0
[    0.411531] VFS: Dquot-cache hash table entries: 512 (order 0, 4096 bytes)
[    0.411617] FS-Cache: Loaded
[    0.411739] CacheFiles: Loaded
[    0.412276] simple-framebuffer 3e3cf000.framebuffer: framebuffer at 0x3e3cf000, 0x7f8000 bytes, mapped to 0x(____ptrval____)
[    0.412282] simple-framebuffer 3e3cf000.framebuffer: format=a8r8g8b8, mode=1920x1080x32, linelength=7680
[    0.412474] Console: switching to colour frame buffer device 240x67
[    0.416426] simple-framebuffer 3e3cf000.framebuffer: fb0: simplefb registered!
[    0.419966] NET: Registered protocol family 2
[    0.420315] tcp_listen_portaddr_hash hash table entries: 2048 (order: 3, 32768 bytes, linear)
[    0.420340] TCP established hash table entries: 32768 (order: 6, 262144 bytes, linear)
[    0.420445] TCP bind hash table entries: 32768 (order: 7, 524288 bytes, linear)
[    0.420863] TCP: Hash tables configured (established 32768 bind 32768)
[    0.421043] UDP hash table entries: 2048 (order: 4, 65536 bytes, linear)
[    0.421077] UDP-Lite hash table entries: 2048 (order: 4, 65536 bytes, linear)
[    0.421218] NET: Registered protocol family 1
[    0.421697] RPC: Registered named UNIX socket transport module.
[    0.421701] RPC: Registered udp transport module.
[    0.421705] RPC: Registered tcp transport module.
[    0.421708] RPC: Registered tcp NFSv4.1 backchannel transport module.
[    0.421719] PCI: CLS 0 bytes, default 64
[    0.422759] hw perfevents: enabled with armv8_cortex_a72 PMU driver, 7 counters available
[    0.422877] kvm [1]: IPA Size Limit: 44 bits
[    0.423306] kvm [1]: vgic interrupt IRQ9
[    0.423425] kvm [1]: Hyp mode initialized successfully
[    0.424287] Initialise system trusted keyrings
[    0.424443] workingset: timestamp_bits=46 max_order=20 bucket_order=0
[    0.426649] zbud: loaded
[    0.427293] FS-Cache: Netfs 'nfs' registered for caching
[    0.427597] NFS: Registering the id_resolver key type
[    0.427615] Key type id_resolver registered
[    0.427618] Key type id_legacy registered
[    0.427666] nfs4filelayout_init: NFSv4 File Layout Driver Registering...
[    0.428124] Key type asymmetric registered
[    0.428129] Asymmetric key parser 'x509' registered
[    0.428151] Block layer SCSI generic (bsg) driver version 0.4 loaded (major 249)
[    0.428269] io scheduler mq-deadline registered
[    0.428273] io scheduler kyber registered
[    0.429909] brcm-pcie fd500000.pcie: host bridge /scb/pcie@7d500000 ranges:
[    0.429918] brcm-pcie fd500000.pcie:   No bus range found for /scb/pcie@7d500000, using [bus 00-ff]
[    0.429942] brcm-pcie fd500000.pcie:      MEM 0x0600000000..0x063fffffff -> 0x00c0000000
[    0.429971] brcm-pcie fd500000.pcie:   IB MEM 0x0000000000..0x00bfffffff -> 0x0400000000
[    0.479016] brcm-pcie fd500000.pcie: link up, 5.0 GT/s PCIe x1 (SSC)
[    0.479160] brcm-pcie fd500000.pcie: PCI host bridge to bus 0000:00
[    0.479166] pci_bus 0000:00: root bus resource [bus 00-ff]
[    0.479172] pci_bus 0000:00: root bus resource [mem 0x600000000-0x63fffffff] (bus address [0xc0000000-0xffffffff])
[    0.479209] pci 0000:00:00.0: [14e4:2711] type 01 class 0x060400
[    0.479303] pci 0000:00:00.0: PME# supported from D0 D3hot
[    0.480618] pci 0000:01:00.0: [1106:3483] type 00 class 0x0c0330
[    0.480676] pci 0000:01:00.0: reg 0x10: [mem 0x00000000-0x00000fff 64bit]
[    0.480913] pci 0000:01:00.0: PME# supported from D0 D3cold
[    0.494032] pci 0000:00:00.0: BAR 8: assigned [mem 0x600000000-0x6000fffff]
[    0.494040] pci 0000:01:00.0: BAR 0: assigned [mem 0x600000000-0x600000fff 64bit]
[    0.494057] pci 0000:00:00.0: PCI bridge to [bus 01]
[    0.494065] pci 0000:00:00.0:   bridge window [mem 0x600000000-0x6000fffff]
[    0.497023] iproc-rng200 fe104000.rng: hwrng registered
[    0.497155] vc-mem: phys_addr:0x00000000 mem_base=0x3ec00000 mem_size:0x40000000(1024 MiB)
[    0.497498] gpiomem-bcm2835 fe200000.gpiomem: Initialised: Registers at 0xfe200000
[    0.497638] cacheinfo: Unable to detect cache hierarchy for CPU 0
[    0.501798] brd: module loaded
[    0.507110] loop: module loaded
[    0.507804] Loading iSCSI transport class v2.0-870.
[    0.508746] libphy: Fixed MDIO Bus: probed
[    0.509241] bcmgenet fd580000.ethernet: GENET 5.0 EPHY: 0x0000
[    0.524973] libphy: bcmgenet MII bus: probed
[    0.577005] unimac-mdio unimac-mdio.-19: Broadcom UniMAC MDIO bus
[    0.577455] usbcore: registered new interface driver r8152
[    0.577481] usbcore: registered new interface driver lan78xx
[    0.577502] usbcore: registered new interface driver smsc95xx
[    0.578753] pci 0000:00:00.0: enabling device (0000 -> 0002)
[    0.578767] xhci_hcd 0000:01:00.0: enabling device (0000 -> 0002)
[    0.578814] xhci_hcd 0000:01:00.0: xHCI Host Controller
[    0.578827] xhci_hcd 0000:01:00.0: new USB bus registered, assigned bus number 1
[    0.579246] xhci_hcd 0000:01:00.0: hcc params 0x002841eb hci version 0x100 quirks 0x0000030000000890
[    0.579643] usb usb1: New USB device found, idVendor=1d6b, idProduct=0002, bcdDevice= 5.10
[    0.579649] usb usb1: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[    0.579654] usb usb1: Product: xHCI Host Controller
[    0.579658] usb usb1: Manufacturer: Linux 5.10.3-v8+ xhci-hcd
[    0.579662] usb usb1: SerialNumber: 0000:01:00.0
[    0.579945] hub 1-0:1.0: USB hub found
[    0.579973] hub 1-0:1.0: 1 port detected
[    0.580196] xhci_hcd 0000:01:00.0: xHCI Host Controller
[    0.580203] xhci_hcd 0000:01:00.0: new USB bus registered, assigned bus number 2
[    0.580211] xhci_hcd 0000:01:00.0: Host supports USB 3.0 SuperSpeed
[    0.580390] usb usb2: New USB device found, idVendor=1d6b, idProduct=0003, bcdDevice= 5.10
[    0.580395] usb usb2: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[    0.580399] usb usb2: Product: xHCI Host Controller
[    0.580404] usb usb2: Manufacturer: Linux 5.10.3-v8+ xhci-hcd
[    0.580408] usb usb2: SerialNumber: 0000:01:00.0
[    0.580634] hub 2-0:1.0: USB hub found
[    0.580663] hub 2-0:1.0: 4 ports detected
[    0.581382] dwc_otg: version 3.00a 10-AUG-2012 (platform bus)
[    0.581486] dwc_otg: FIQ enabled
[    0.581490] dwc_otg: NAK holdoff enabled
[    0.581493] dwc_otg: FIQ split-transaction FSM enabled
[    0.581498] Module dwc_common_port init
[    0.581750] usbcore: registered new interface driver uas
[    0.581792] usbcore: registered new interface driver usb-storage
[    0.581878] mousedev: PS/2 mouse device common for all mice
[    0.582520] bcm2835-wdt bcm2835-wdt: Broadcom BCM2835 watchdog timer
[    0.583332] sdhci: Secure Digital Host Controller Interface driver
[    0.583336] sdhci: Copyright(c) Pierre Ossman
[    0.583597] mmc-bcm2835 fe300000.mmcnr: could not get clk, deferring probe
[    0.583793] sdhci-pltfm: SDHCI platform and OF driver helper
[    0.585958] ledtrig-cpu: registered to indicate activity on CPUs
[    0.586052] hid: raw HID events driver (C) Jiri Kosina
[    0.586120] usbcore: registered new interface driver usbhid
[    0.586124] usbhid: USB HID core driver
[    0.589560] Initializing XFRM netlink socket
[    0.589580] NET: Registered protocol family 17
[    0.589646] Key type dns_resolver registered
[    0.589923] registered taskstats version 1
[    0.589937] Loading compiled-in X.509 certificates
[    0.590165] Key type ._fscrypt registered
[    0.590169] Key type .fscrypt registered
[    0.590173] Key type fscrypt-provisioning registered
[    0.594559] uart-pl011 fe201000.serial: there is not valid maps for state default
[    0.594685] uart-pl011 fe201000.serial: cts_event_workaround enabled
[    0.594745] fe201000.serial: ttyAMA0 at MMIO 0xfe201000 (irq = 22, base_baud = 0) is a PL011 rev2
[    0.598931] bcm2835-power bcm2835-power: Broadcom BCM2835 power domains driver
[    0.599298] mmc-bcm2835 fe300000.mmcnr: mmc_debug:0 mmc_debug2:0
[    0.599303] mmc-bcm2835 fe300000.mmcnr: DMA channel allocated
[    0.626193] of_cfs_init
[    0.626258] of_cfs_init: OK
[    0.645098] mmc1: queuing unknown CIS tuple 0x80 (2 bytes)
[    0.646605] mmc1: queuing unknown CIS tuple 0x80 (3 bytes)
[    0.648112] mmc1: queuing unknown CIS tuple 0x80 (3 bytes)
[    0.650823] mmc1: queuing unknown CIS tuple 0x80 (7 bytes)
[    0.652333] mmc1: queuing unknown CIS tuple 0x80 (3 bytes)
[    0.662973] mmc0: SDHCI controller on fe340000.emmc2 [fe340000.emmc2] using ADMA
[    0.663229] Waiting for root device PARTUUID=c98ea287-02...
[    0.690526] random: fast init done
[    0.707380] mmc1: new high speed SDIO card at address 0001
[    0.731863] mmc0: new ultra high speed SDR25 SDHC card at address b368
[    0.732361] mmcblk0: mmc0:b368 CBADS 30.0 GiB
[    0.734053]  mmcblk0: p1 p2
[    0.750396] EXT4-fs (mmcblk0p2): mounted filesystem with ordered data mode. Opts: (null)
[    0.750442] VFS: Mounted root (ext4 filesystem) readonly on device 179:2.
[    0.751033] devtmpfs: mounted
[    0.754723] Freeing unused kernel memory: 3648K
[    0.757040] Run /sbin/init as init process
[    0.757045]   with arguments:
[    0.757048]     /sbin/init
[    0.757052]     splash
[    0.757055]   with environment:
[    0.757059]     HOME=/
[    0.757062]     TERM=linux
[    0.912981] usb 1-1: new high-speed USB device number 2 using xhci_hcd
[    1.063584] usb 1-1: New USB device found, idVendor=2109, idProduct=3431, bcdDevice= 4.21
[    1.063594] usb 1-1: New USB device strings: Mfr=0, Product=1, SerialNumber=0
[    1.063599] usb 1-1: Product: USB2.0 Hub
[    1.064862] hub 1-1:1.0: USB hub found
[    1.065177] hub 1-1:1.0: 4 ports detected
[    1.364973] usb 1-1.2: new high-speed USB device number 3 using xhci_hcd
[    1.365792] systemd[1]: System time before build time, advancing clock.
[    1.466648] usb 1-1.2: New USB device found, idVendor=05e3, idProduct=0610, bcdDevice=32.98
[    1.466659] usb 1-1.2: New USB device strings: Mfr=0, Product=1, SerialNumber=0
[    1.466664] usb 1-1.2: Product: USB2.0 Hub
[    1.467935] hub 1-1.2:1.0: USB hub found
[    1.468286] hub 1-1.2:1.0: 4 ports detected
[    1.472161] NET: Registered protocol family 10
[    1.472871] Segment Routing with IPv6
[    1.527305] systemd[1]: systemd 241 running in system mode. (+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD -IDN2 +IDN -PCRE2 default-hierarchy=hybrid)
[    1.527582] systemd[1]: Detected architecture arm64.
[    1.561868] systemd[1]: Set hostname to <raspberrypi>.
[    1.760990] usb 1-1.2.1: new low-speed USB device number 4 using xhci_hcd
[    1.912896] usb 1-1.2.1: New USB device found, idVendor=04d9, idProduct=0006, bcdDevice= 1.10
[    1.912907] usb 1-1.2.1: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[    1.912912] usb 1-1.2.1: Product: RPI Wired Keyboard 1
[    1.912917] usb 1-1.2.1: Manufacturer:
[    1.938032] input:   RPI Wired Keyboard 1 as /devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.2/1-1.2.1/1-1.2.1:1.0/0003:04D9:0006.0001/input/input0
[    1.973283] random: systemd: uninitialized urandom read (16 bytes read)
[    1.975789] random: systemd: uninitialized urandom read (16 bytes read)
[    1.976738] systemd[1]: Created slice User and Session Slice.
[    1.976883] random: systemd: uninitialized urandom read (16 bytes read)
[    1.977352] systemd[1]: Listening on Journal Socket.
[    1.977718] systemd[1]: Listening on Journal Audit Socket.
[    1.978221] systemd[1]: Set up automount Arbitrary Executable File Formats File System Automount Point.
[    1.979620] systemd[1]: Condition check resulted in Set Up Additional Binary Formats being skipped.
[    1.979661] systemd[1]: Condition check resulted in Kernel Module supporting RPCSEC_GSS being skipped.
[    1.980512] systemd[1]: Created slice system-systemd\x2dfsck.slice.
[    1.997278] hid-generic 0003:04D9:0006.0001: input,hidraw0: USB HID v1.11 Keyboard [  RPI Wired Keyboard 1] on usb-0000:01:00.0-1.2.1/input0
[    2.025134] input:   RPI Wired Keyboard 1 as /devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.2/1-1.2.1/1-1.2.1:1.1/0003:04D9:0006.0002/input/input1
[    2.085236] hid-generic 0003:04D9:0006.0002: input,hidraw1: USB HID v1.11 Device [  RPI Wired Keyboard 1] on usb-0000:01:00.0-1.2.1/input1
[    2.121914] i2c /dev entries driver
[    2.169442] usb 1-1.2.2: new low-speed USB device number 5 using xhci_hcd
[    2.280734] usb 1-1.2.2: New USB device found, idVendor=093a, idProduct=2510, bcdDevice= 1.00
[    2.280748] usb 1-1.2.2: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[    2.280753] usb 1-1.2.2: Product: USB Optical Mouse
[    2.280758] usb 1-1.2.2: Manufacturer: PixArt
[    2.291586] input: PixArt USB Optical Mouse as /devices/platform/scb/fd500000.pcie/pci0000:00/0000:00:00.0/0000:01:00.0/usb1/1-1/1-1.2/1-1.2.2/1-1.2.2:1.0/0003:093A:2510.0003/input/input2
[    2.291860] hid-generic 0003:093A:2510.0003: input,hidraw2: USB HID v1.11 Mouse [PixArt USB Optical Mouse] on usb-0000:01:00.0-1.2.2/input0
[    2.415866] EXT4-fs (mmcblk0p2): re-mounted. Opts: (null)
[    2.444118] systemd-journald[119]: Received request to flush runtime journal from PID 1
[    2.807178] brcmstb-i2c fef04500.i2c:  @97500hz registered in polling mode
[    2.810142] brcmstb-i2c fef09500.i2c:  @97500hz registered in polling mode
[    2.815053] vc_sm_cma: module is from the staging directory, the quality is unknown, you have been warned.
[    2.816122] bcm2835_vc_sm_cma_probe: Videocore shared memory driver
[    2.816139] [vc_sm_connected_init]: start
[    2.825330] [vc_sm_connected_init]: installed successfully
[    2.850367] mc: Linux media interface: v0.10
[    2.934959] videodev: Linux video capture interface: v2.00
[    3.003471] snd_bcm2835: module is from the staging directory, the quality is unknown, you have been warned.
[    3.007555] bcm2835_audio bcm2835_audio: card created with 8 channels
[    3.037048] [drm] Initialized v3d 1.0.0 20180419 for fec00000.v3d on minor 0
[    3.092187] bcm2835_mmal_vchiq: module is from the staging directory, the quality is unknown, you have been warned.
[    3.092190] bcm2835_mmal_vchiq: module is from the staging directory, the quality is unknown, you have been warned.
[    3.092333] bcm2835_mmal_vchiq: module is from the staging directory, the quality is unknown, you have been warned.
[    3.141483] bcm2835_isp: module is from the staging directory, the quality is unknown, you have been warned.
[    3.144549] bcm2835-isp bcm2835-isp: Device node output[0] registered as /dev/video13
[    3.144728] bcm2835-isp bcm2835-isp: Device node capture[0] registered as /dev/video14
[    3.144876] bcm2835-isp bcm2835-isp: Device node capture[1] registered as /dev/video15
[    3.145444] bcm2835-isp bcm2835-isp: Device node stats[2] registered as /dev/video16
[    3.145460] bcm2835-isp bcm2835-isp: Register output node 0 with media controller
[    3.145469] bcm2835-isp bcm2835-isp: Register capture node 1 with media controller
[    3.145475] bcm2835-isp bcm2835-isp: Register capture node 2 with media controller
[    3.145480] bcm2835-isp bcm2835-isp: Register capture node 3 with media controller
[    3.145563] bcm2835-isp bcm2835-isp: Loaded V4L2 bcm2835-isp
[    3.153163] bcm2835_v4l2: module is from the staging directory, the quality is unknown, you have been warned.
[    3.172543] bcm2835_codec: module is from the staging directory, the quality is unknown, you have been warned.
[    3.175940] bcm2835-codec bcm2835-codec: Device registered as /dev/video10
[    3.175972] bcm2835-codec bcm2835-codec: Loaded V4L2 decode
[    3.179393] bcm2835-codec bcm2835-codec: Device registered as /dev/video11
[    3.179419] bcm2835-codec bcm2835-codec: Loaded V4L2 encode
[    3.183530] bcm2835-codec bcm2835-codec: Device registered as /dev/video12
[    3.183558] bcm2835-codec bcm2835-codec: Loaded V4L2 isp
[    3.312747] cfg80211: Loading compiled-in X.509 certificates for regulatory database
[    3.332729] debugfs: Directory 'fef00700.hdmi' with parent 'vc4-hdmi-0' already present!
[    3.336559] vc4_hdmi fef00700.hdmi: ASoC: no DMI vendor name!
[    3.340753] vc4-drm gpu: bound fef00700.hdmi (ops vc4_hdmi_ops [vc4])
[    3.342414] debugfs: Directory 'fef05700.hdmi' with parent 'vc4-hdmi-1' already present!
[    3.350157] vc4_hdmi fef05700.hdmi: ASoC: no DMI vendor name!
[    3.350650] vc4-drm gpu: bound fef05700.hdmi (ops vc4_hdmi_ops [vc4])
[    3.350824] vc4-drm gpu: bound fe400000.hvs (ops vc4_hvs_ops [vc4])
[    3.351013] vc4-drm gpu: bound fe004000.txp (ops vc4_txp_ops [vc4])
[    3.351163] vc4-drm gpu: bound fe206000.pixelvalve (ops vc4_crtc_ops [vc4])
[    3.351262] vc4-drm gpu: bound fe207000.pixelvalve (ops vc4_crtc_ops [vc4])
[    3.351357] vc4-drm gpu: bound fe20a000.pixelvalve (ops vc4_crtc_ops [vc4])
[    3.351435] vc4-drm gpu: bound fe216000.pixelvalve (ops vc4_crtc_ops [vc4])
[    3.351532] vc4-drm gpu: bound fec12000.pixelvalve (ops vc4_crtc_ops [vc4])
[    3.351810] checking generic (3e3cf000 7f8000) vs hw (0 ffffffffffffffff)
[    3.351816] fb0: switching to vc4drmfb from simple
[    3.354762] Console: switching to colour dummy device 80x25
[    3.377297] cfg80211: Loaded X.509 cert 'sforshee: 00b28ddf47aef9cea7'
[    3.394451] [drm] Initialized vc4 0.0.0 20140616 for gpu on minor 1
[    3.450797] Console: switching to colour frame buffer device 240x67
[    3.450829] vc4-drm gpu: [drm] fb0: vc4drmfb frame buffer device
[    3.452397] brcmfmac: F1 signature read @0x18000000=0x15264345
[    3.456809] brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac43455-sdio for chip BCM4345/6
[    3.457314] usbcore: registered new interface driver brcmfmac
[    3.496854] brcmfmac mmc1:0001:1: Direct firmware load for brcm/brcmfmac43455-sdio.raspberrypi,4-model-b.txt failed with error -2
[    3.696110] brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac43455-sdio for chip BCM4345/6
[    3.700934] rpivid-mem feb00000.hevc-decoder: rpivid-hevcmem initialised: Registers at 0xfeb00000 length 0x00010000
[    3.701202] rpivid-mem feb10000.rpivid-local-intc: rpivid-intcmem initialised: Registers at 0xfeb10000 length 0x00001000
[    3.701369] rpivid-mem feb20000.h264-decoder: rpivid-h264mem initialised: Registers at 0xfeb20000 length 0x00010000
[    3.701538] rpivid-mem feb30000.vp9-decoder: rpivid-vp9mem initialised: Registers at 0xfeb30000 length 0x00010000
[    3.763268] brcmfmac: brcmf_c_preinit_dcmds: Firmware: BCM4345/6 wl0: Mar 23 2020 02:19:54 version 7.45.206 (r725000 CY) FWID 01-88ee44ea
[    4.927480] uart-pl011 fe201000.serial: no DMA platform data
[    5.018636] random: crng init done
[    5.018650] random: 7 urandom warning(s) missed due to ratelimiting
[    5.426567] 8021q: 802.1Q VLAN Support v1.8
[    5.871234] brcmfmac: brcmf_cfg80211_set_power_mgmt: power save enabled
[    6.065010] Adding 102396k swap on /var/swap.  Priority:-2 extents:1 across:102396k SSFS
[    6.178071] bcmgenet fd580000.ethernet: configuring instance for external RGMII (RX delay)
[    6.178294] bcmgenet fd580000.ethernet eth0: Link is Down
[    7.318320] broken atomic modeset userspace detected, disabling atomic
[    9.670057] fuse: init (API version 7.32)
[   11.049187] vc4_hdmi fef00700.hdmi: ASoC: error at snd_soc_dai_startup on fef00700.hdmi: -19
[   11.416806] IPv6: ADDRCONF(NETDEV_CHANGE): wlan0: link becomes ready
[   11.795960] Bluetooth: Core ver 2.22
[   11.796009] NET: Registered protocol family 31
[   11.796014] Bluetooth: HCI device and connection manager initialized
[   11.796028] Bluetooth: HCI socket layer initialized
[   11.796036] Bluetooth: L2CAP socket layer initialized
[   11.796048] Bluetooth: SCO socket layer initialized
[   11.819420] Bluetooth: HCI UART driver ver 2.3
[   11.819434] Bluetooth: HCI UART protocol H4 registered
[   11.819473] Bluetooth: HCI UART protocol Three-wire (H5) registered
[   11.819634] Bluetooth: HCI UART protocol Broadcom registered
[   12.080171] Bluetooth: BNEP (Ethernet Emulation) ver 1.3
[   12.080184] Bluetooth: BNEP filters: protocol multicast
[   12.080204] Bluetooth: BNEP socket layer initialized
[   12.119972] Bluetooth: RFCOMM TTY layer initialized
[   12.119995] Bluetooth: RFCOMM socket layer initialized
[   12.120012] Bluetooth: RFCOMM ver 1.11

**Additional context**
Add any other relevant context for the problem.

**Comment by 6by9** [comment]
With the switch to DRM/KMS many of the config.txt parameters are being replaced. ```hdmi_mode``` and ```hdmi_group``` fall into this category with regard use within X.  (They should still set the resolution of the console via the kernel command line, but X ignores this).

Use the Screen Configuration application within X and the setting should persist over reboots.

**Comment by jamieS95** [comment]
Screen Configuration application worked to change resolution
