### ISSUE TITLE
Kernel 5.10.7 Compile Warnings

### ISSUE THREAD

**Issue by Dark-Sky** [raspberrypi/linux#4076]
When compiling kernel 5.10.7 I get these warnings. I usually do not pay attention to warnings but do not recall seeing any before involving the overlays. Is this normal:

Using gcc version 10.2.0

```
arch/arm64/boot/dts/overlays/i2c-gpio-overlay.dts:15.5-24: Warning (reg_format): /fragment@0/__overlay__/i2c@0:reg: property has invalid length (4 bytes) (#address-cells == 2, #size-cells == 1)
arch/arm64/boot/dts/overlays/i2c-gpio.dtbo: Warning (pci_device_bus_num): Failed prerequisite 'reg_format'
arch/arm64/boot/dts/overlays/i2c-gpio.dtbo: Warning (i2c_bus_reg): Failed prerequisite 'reg_format'
arch/arm64/boot/dts/overlays/i2c-gpio.dtbo: Warning (spi_bus_reg): Failed prerequisite 'reg_format'
arch/arm64/boot/dts/overlays/i2c-gpio-overlay.dts:14.20-23.6: Warning (avoid_default_addr_size): /fragment@0/__overlay__/i2c@0: Relying on default #address-cells value
arch/arm64/boot/dts/overlays/i2c-gpio-overlay.dts:14.20-23.6: Warning (avoid_default_addr_size): /fragment@0/__overlay__/i2c@0: Relying on default #size-cells value
```

**Comment by pelwell** [comment]
It is - I tried getting rid of them once, with dire consequences.

I'll buy a case of beer (or equivalent) if someone can get it to compile cleanly.

**Comment by Dark-Sky** [comment]
Lol. Close this when you want to.

**Comment by pelwell** [comment]
Thanks, but I'm going to leave it here as a challenge.

**Comment by luoxiangzhen** [comment]
any updates ? seems have the same warning now

**Comment by pelwell** [comment]
You shouldn't see these warnings in one of our downstream branches because we have patches to suppress them:
* rpi-5.10.y: f4590cfb672e86de142af37c11776d1510c48018
* rpi-5.15.y: d88be102ffc9c66abde1fba7d7bf69ff1e19d4d4
etc.
Aside from that, I've given up.
