### ISSUE TITLE
XFS filesystem support in stock kernel

### ISSUE THREAD

**Issue by dergrunepunkt** [raspberrypi/linux#410]
Would be possible to include XFS support in stock kernel?, 

I been using XFS on servers and workstations for almost 10 years with no problems. So strong is it that I got used I to remove my laptop battery to turn it off, I know it's not a good practice but XFS can take that kind punishment flawlessly.

In 4 weeks of Pi with EXT4 I had more data loss and corruption in that in 10ys of XFS.

Thanks a lot

Luis

**Comment by ajs124** [comment]
That seems more like an issue with the pi itself than with ext4. I have to hard-reboot my pc quite often for various reasons and all my ext4 filesystems still work perfectly.
Since this probably requires quite some resources and won't be used by many people, I don't think it should be included. Besides, isn't booting with an initrd that include the xfs module an option in a scenario like this?

**Comment by dergrunepunkt** [comment]
Well... it's true at some extent, nobody will use it, if they need to
invest time and effort to create an initrd/initramfs  assuming they have
the knowledge to do so, instead using that time and effort to do what they
really want to do.

Regarding the resources, the XFS kernel module is not that big to say that
is a waste of resources giving the improvement in reliability and
performance.

If you did not had problems with EXT3/4 it's either you never used too much
or you're blessed, give a try to extend a filesystem in EXT3/4 on a
production environment, everything with blow-up in the sky with diamonds,
just like Lucy :D.

Kind regards

**Comment by lurch** [comment]
According to #413 it sounds like there are still SD-card issues on the RPi that are so low-level they can potentially cause corruption on _any_ filesystem...

**Comment by popcornmix** [comment]
Latest kernel:

```
$ zcat /proc/config.gz |grep XFS
CONFIG_XFS_FS=m
CONFIG_XFS_QUOTA=y
CONFIG_XFS_POSIX_ACL=y
CONFIG_XFS_RT=y
```

okay to close?
