### ISSUE TITLE
not able to change keyboard layout to qwertz

### ISSUE THREAD

**Issue by kitingChris** [raspberrypi/linux#411]
Nothing worked yet it is desperating!

"raspi-config" changed keyboard => still qwerty

"dpkg-reconfigure keyboard-configuration" generic pc-keyboard 105 intl - Layout: German => still qwerty
## locale:

LANG=de_DE.UTF-8
LANGUAGE=
LC_CTYPE="de_DE.UTF-8"
LC_NUMERIC="de_DE.UTF-8"
LC_TIME="de_DE.UTF-8"
LC_COLLATE="de_DE.UTF-8"
LC_MONETARY="de_DE.UTF-8"
LC_MESSAGES="de_DE.UTF-8"
LC_PAPER="de_DE.UTF-8"
LC_NAME="de_DE.UTF-8"
LC_ADDRESS="de_DE.UTF-8"
LC_TELEPHONE="de_DE.UTF-8"
LC_MEASUREMENT="de_DE.UTF-8"
LC_IDENTIFICATION="de_DE.UTF-8"
LC_ALL=
## /etc/default/keyboard 

XKBMODEL="pc105"
XKBLAYOUT="de"
XKBVARIANT=""
XKBOPTIONS=""
BACKSPACE="guess"

**Comment by popcornmix** [comment]
I don't believe this is a kernel issue. May be best to ask in the forum.

**Comment by kitingChris** [comment]
It seems to be a X-Server/Session problem. 

When running "setxkbmap de" the keymap changes as expected... 

strange thing was only that even console-setup did only work on tty consoles...

raspi-config should change this too...

**Comment by popcornmix** [comment]
Closing as not a linux kernel issue.
