### ISSUE TITLE
SD card corruption issues

### ISSUE THREAD

**Issue by ghollingworth** [raspberrypi/linux#413]
This is a list of all the issues we've seen with SD card corruption... 
#412 Timeout issue
#414 Sandisk Ultra SD cards can fail to boot
#415 Arasan SD host fifo overrun causes corruption

Be interested to see if people find issues that don't fall into these catagories...

Thanks

Gordon

**Comment by popcornmix** [comment]
Experimental instructions for avoiding corruption here: https://github.com/raspberrypi/linux/issues/415

**Comment by popcornmix** [comment]
I believe all known issues are resolved.
