### ISSUE TITLE
Please support DS1340 in i2c-rtc overlay

### ISSUE THREAD

**Issue by e107steved** [raspberrypi/linux#4180]
Second post here: https://www.raspberrypi.org/forums/viewtopic.php?f=107&t=305248 gives the instructions if that helps.

**Comment by pelwell** [comment]
The source of the i2c-rtc overlay has been updated in rpi-5.10.y - see https://github.com/raspberrypi/linux/commit/f45e8420c8d3a12837817a5de5985af2e95757d6. Future compiled releases will include ds1340 support.
