### ISSUE TITLE
Pixel desktop taskbar transparency

### ISSUE THREAD

**Issue by racedowling** [raspberrypi/linux#4182]
Raspberry pi OS latest version as of 20 Feb 2021

Using pixel desktop with taskbar on left screen set to transparency. It uses the background from the right screen (see attached).
When setting up taskbar on the right screen it acts normally.

![2021-02-28-145336_3840x1080_scrot](https://user-images.githubusercontent.com/58705020/109431892-b44f7300-79d6-11eb-8663-eaf5805a9e8f.png)

**Comment by pelwell** [comment]
@spl237 Would https://github.com/raspberrypi-ui/lxpanel-buster be a better home for this issue (not that I can simply transfer it there)?

**Comment by spl237** [comment]
In theory it would, but...

As it happens, I was looking at this code the other day, and it's very broken, and looks as if it has never worked properly, so I don't think there is likely to be a fix at any point in the near future. The short answer is that transparency in lxpanel doesn't work, so don't use it...

**Comment by pelwell** [comment]
Ta. Sorry, @racedowling.
