### ISSUE TITLE
[Bluetooth] Unable to handle kernel paging request at

### ISSUE THREAD

**Issue by Stefangemfind** [raspberrypi/linux#419]
Hello.

I am having an issue with a bluetooth headset. When I connect to the headset using bluez and try to play audio through it I sometimes get a kernel panic saying "Unable to handle kernel paging request at <hex>", the stacktrace further down in the kernel panic seem to point to "bt_sock_unlink" which I believe is located in /net/bluetooth/af_bluetooth.c in the kernel.

I have so far tried 3 different dongles, 1 of them is of the type Hama, A known working dongle if im not mistaken.

I also get flodded in dmesg with "Unknown connection handle". I have tried many solutions such as the "dwc_otg.speed=1" parameter, but still no luck.

I have also tried in Raspbian(2.6 and 3.10 kernel), Slackware-amd, Gentoo, Debian and Arch, same results on all.

This headset and dongle's work fine on my Laptop running Slackware i386.

Has anyone had this issue before?

EDIT:
This issue seem to happen more often when the audio has finished playing, if i do CTRL-C on mplayer when playing a sound I can trigger the bug. Which would make sense I guess since "bt_sock_unlink()", the function listen in the stacktrace of the kernel panic would be called when the audio has finished playing.

Stefan.

**Comment by Stefangemfind** [comment]
UPDATE:

After adding "vm.min_free_kbytes = 16384" to my /etc/sysctl.conf I don't get a kernel panic, however the USB device seem to disconnect. After playing sound through the bluetooth device for a while it stops working and I cannot connect to it again. The device is stilled recognized by the system and Bluez as plugged in.

The kernel panic now instead happens when I unplug the device. I get "Unable to handle kernel NULL pointer dereference at virtual address 00000000".

Stack trace now says:
PC: is at 0x0
LR: is at sco_conn_del+0x5c/0x194 [bluetooth]

**Comment by Stefangemfind** [comment]
UPDATE:

Problem still occurring when using a powered USB slot as power source. I know this can be unsafe but it was not exposed to hit for longer than 4 minutes. Everything booted as it should, I could once again play sound in the device however it disconnected the USB bluetooth dongle when playback was finished.

Using "aplay -D btheadset test.wav" in an infinite loop I was able to get the headset to play sound without disconnecting the device. From time to time it wasn't able to connect to the headset however it resumed playback automatically after that. The bluetooth dongle did however disconnect again once I pushed CTRL-C to escape the loop.

I say this confirms that the issue and previous errors are triggered when the software(be it aplay, mplayer or mpg123) tried to disconnect from the headset.

Stefan.

**Comment by P33M** [comment]
Please retest using latest rpi-update firmware.

**Comment by P33M** [comment]
No response from OP in two weeks: assuming functional

**Comment by Stefangemfind** [comment]
Yes sorry, I must have missed the first email sent there.
I did resolve this, although I cannot remember how. If memory serves the fix was to cross-compile a new kernel(latest), and use that.

I believe this was the guide I used-> http://elinux.org/RPi_Kernel_Compilation

Stefan Larsson.
