### ISSUE TITLE
5Ghz WiFi bands are no longer visible after upgrade to Linux version 5.10.17-v8+ 

### ISSUE THREAD

**Issue by mgrouch** [raspberrypi/linux#4192]
5Ghz WiFi bands are no longer visible after upgrade to Linux version 5.10.17-v8+

**Comment by Enjoy-Combi** [comment]
[same issue](https://github.com/raspberrypi/linux/issues/4188#issue-821867939)

**Comment by pelwell** [comment]
They're working here. Do you want to say a bit more about your setup, or should I just close this now?

**Comment by mgrouch** [comment]
They get found eventually. Takes way long. Might be it’s my enclosure issue (it’s not fully plastic).

**Comment by mgrouch** [comment]
3 hours and still no 5G WiFi and all 2.4G wifi connections fail (with correct passwords).
5.10.17-v8+

Might be it's latest firmware issue. 

https://github.com/raspberrypi/linux/issues/4134

**Comment by mgrouch** [comment]
I've noticed raspberry pi OS added this line:

dtoverlay=dwc2,dr_mode=host

at the end of my boot/config.txt

without it wifi works.

**Comment by mgrouch** [comment]
WiFi still very bad. 

5.10.11-v8+ 
was finding 5Ghz band right away. 
I’ve boot it it from SSD and I can tell
Somewhere between 5.10.11 and 5.0.17 things got worse. 

I’ve upgraded with apt to 5.10.17 and started getting lots of issues with WiFi (basically not working) and one usb error on boot which I reported separately. 

Armhf version with 5.10.17 has same issues with WiFi and USB. 

so both 32 and 64 bit kernels are impacted.

**Comment by mgrouch** [comment]
I’ve found the reason for issues. 
I didn’t set WiFi country. 
After setting WiFi country in
wpasupplicant it works just fine
