### ISSUE TITLE
Micro SD card

### ISSUE THREAD

**Issue by ghost** [raspberrypi/linux#4195]
when I use my rpi4 sometimes /dev/mmcblk0p1 and /dev/mmcblk0 dismount out of thin air and i got to restart the whole thing i can't do it by software shutdown i got to do it by cutting power to it

**Comment by pelwell** [comment]
That sounds like a power supply or hardware problem. You might be able to get some logs out of it if you can `ssh pi@<ip-address> dmesg -w` to constantly capture the kernel log - after the initial boot it should be relatively quiet during normal use.

**Comment by ghost** [comment]
well it started when I got a 64gb micro sd card

**Comment by ghost** [comment]
may a bug with the huge disk capacity
it's a pny 64gb elite-X

**Comment by pelwell** [comment]
> well it started when I got a 64gb micro sd card

SD cards count as hardware. 64GB is not huge, but there could be some other problem with it. Have you tried running an SD card checking tool - h2testw or similar?

**Comment by ghost** [comment]
let me try

**Comment by ghost** [comment]
Buffer IO error

**Comment by pelwell** [comment]
Is that from a card tester? Running on a Pi or a PC?

**Comment by ghost** [comment]
no logs

**Comment by ghost** [comment]
it's the logs

**Comment by pelwell** [comment]
Understood. If you have a Pi image on another SD card, and a USB card reader, and if you don't mind destroying the image on the 64GB card, you could install the f3 utilities: https://fight-flash-fraud.readthedocs.io/en/stable/introduction.html
You just have to download and extract a zip file, then type `make` (and optionally `sudo make install`).

**Comment by ghost** [comment]
ok

**Comment by pelwell** [comment]
I could also have said that you boot the other Pi image from the Pi's SD slot, install the f3 tools onto that Card, then put the 64GB card in the USB card reader and test it there - but you've probably worked that out already.

**Comment by ghost** [comment]
they're not fake and it was a 4.5 star on amazon too idk if the rating
counts

**Comment by ghost** [comment]
i used h2testw

**Comment by pelwell** [comment]
You've not mentioned which power supply you are using and what else is attached to the Pi - all of which would be useful information.

**Comment by ghost** [comment]
so it doesn't look like a sd card problem (somewhat because it started with
the 64gb and not the 32gb)

**Comment by pelwell** [comment]
I don't think we can rule it out completely, but at this point other causes seem more likely.

**Comment by ghost** [comment]
Power Supply:

Labists Rating for 5V 3 Amps

**Comment by ghost** [comment]
Overclocked:
CPU: 2ghz GPU: 600mhz Overvolt: 6

I think when I had mine to default settings it work fine it's prob because
of overclock

**Comment by pelwell** [comment]
Ookaayyy - close when you're ready.

**Comment by ghost** [comment]
So default clock for me then

**Comment by ghost** [comment]
And everytime my fans ramp up to full max speed but levels out after a min

**Comment by Dell-Glitch** [comment]
Nvm you just gotta slap it to make it stop being so noisy

**Comment by Dell-Glitch** [comment]
Like what the my teacher does to make the crying kid stop crying but she
doesn't slap she uses this purple rod and shoves it in they ass

**Comment by ghost** [comment]
FAILED AGAIN io error

**Comment by ghost** [comment]
im trying my 32gb

**Comment by ghost** [comment]
they are faulty
