### ISSUE TITLE
PPP kernel module

### ISSUE THREAD

**Issue by jfedyczak** [raspberrypi/linux#42]
Any possibility to add PPP options to support GSM modems?

**Comment by popcornmix** [comment]
Recent kernel's have:
dc4@dc4-VirtualBox:~/linux$ grep PPP .config
CONFIG_PPP=m
CONFIG_PPP_ASYNC=m
CONFIG_PPP_SYNC_TTY=m
CONFIG_PPP_DEFLATE=m
CONFIG_PPP_BSDCOMP=m
CONFIG_PPP_MPPE=m
CONFIG_PPPOE=m

Have you tried updating?

**Comment by jfedyczak** [comment]
It appears that my problem concerns linux-raspberry ArchLinux ARM package. I'm sorry for the confusion.
