### ISSUE TITLE
8192cu: needs to update

### ISSUE THREAD

**Issue by NukeMania** [raspberrypi/linux#420]
Hello,

There is new driver v4.0.2_9000

http://www.realtek.com.tw/downloads/downloadsView.aspx?Langid=1&PNid=48&PFid=48&Level=5&Conn=4&DownTypeID=3&GetDown=false&Downloads=true#RTL8192CU

**Comment by popcornmix** [comment]
Download links don't work for me - could you download it?

**Comment by NukeMania** [comment]
yes I did and compiled from source works fine but there is no 3.10 kernel support so still needs to deprecated/undefined create_proc_entry patch
https://github.com/raspberrypi/linux/commit/57d128dde601f36fd6651fdf3df89e56ce36c9b7

**Comment by popcornmix** [comment]
Driver updated (as source). Can you confim it works okay before I push out a firmware update.

**Comment by NukeMania** [comment]
as I checked source i think you forgot one more patch because old source already came patched as well
patch will disable debug mode 
without patch debug messages are horribly annoying in the kernel log 

 drivers/net/wireless/rtl8192cu/include/autoconf.h

-#define CONFIG_DEBUG_RTL819X
+//#define CONFIG_DEBUG_RTL819X

**Comment by popcornmix** [comment]
Good point - added.

**Comment by NukeMania** [comment]
tested, it works fine 

http://pastebin.com/dBmBtcUZ

**Comment by popcornmix** [comment]
Thanks, will push in next update.

**Comment by popcornmix** [comment]
Should be in latest rpi-update firmware.

**Comment by NukeMania** [comment]
works fine with new driver after fw update

thanks

**Comment by smillerk2** [comment]
@NukeMania can you please re-post your pastebin so I can see how you got the v4.0.2 RTL8192CU driver working on 3.10+. Thanks.
