### ISSUE TITLE
Add Cmake 3.20

### ISSUE THREAD

**Issue by ghost** [raspberrypi/linux#4203]

**Comment by ghost** [comment]
So you will do it?

**Comment by pelwell** [comment]
What does cmake have to do with the Linux kernel?

**Comment by ghost** [comment]
oh.. where do you report to update something for apt

**Comment by pelwell** [comment]
You could try here: https://github.com/RPi-Distro/repo/issues

However, even Debian Sid (the testing version) is only on 3.18.4-2, the same as Bullseye that we will switch to in the fullness of time.

As usual, failing to make the effort to write some words about why we should consider your request/demand reduces the chances of a positive outcome.

**Comment by ghost** [comment]
k
