### ISSUE TITLE
FR: PoE-hat more variable fan control, where PWM ranges from 1 to 255 step = 1

### ISSUE THREAD

**Issue by ProBackup-nl** [raspberrypi/linux#4218]
**Describe the Feature Request**
The RPi PoE-hat (c) 2018 currently makes a lot of noise when the fan spins and RPi is idle at 17ºC ambient.

The (Sunon) fan is near silent at PWM levels 1 and 2 and the poe hat fan already start spinning at PWM=1.
`echo 1 > /sys/class/hwmon/hwmon1/pwm1`

I find it strange that from all the 254 available PWM levels only 4 levels are used. Result is a noisy fan where the subjective sound pressure feels increased by the repetitive stopping and starting of the fan.

**Expected behaviour**
I'd wish that the Power over Ethernet hat fan runs silently when it can and uses all 254 PWM levels and that the driver uses less configuration. I'd wish to configure only 3 things:
1. Lower Temperature at which the fan starts spinning (default 40ºC, for PWM=1)
2. Upper Temperature at which the fan will run at full speed (default 55ºC, for PWM=255)
3. Hysteresis (current default 2ºC is good)

When the fan is spinning (previous PWM value > 0), the PWM value could be set like: 
```
if Temp < (Lower-Hysteresis) then PWM=0
if Temp < Lower then PWM=1
if Temp > Upper then PWM=255
else PWM = Int((Temp-Lower) / ((Upper-Lower)/254)) + 1
```

**Actual behaviour**
The [dtoverlay=rpi-poe](https://github.com/raspberrypi/linux/blob/rpi-5.4.y/arch/arm/boot/dts/overlays/rpi-poe-overlay.dts) and its driver rpi-poe-fan have only rudimentary fan control in 5 levels: [off, PWM=31, PWM=63, PWM=150, PWM=255](https://github.com/raspberrypi/linux/blob/rpi-5.4.y/arch/arm/boot/dts/overlays/rpi-poe-overlay.dts#L19).

**Comment by pelwell** [comment]
The POE fan overlay is tying together the basic fan driver (that communicates with the firmware) and the Linux thermal management subsystem. The knowledge of the current temperature and the fan speed to select is all managed by standard Linux components - only the fan driver is Pi-specific.

You could try raising your idea with the maintainers of the "thermal" subsystem - the relevant section of the MAINTAINERS file says:
```
THERMAL
M:      Zhang Rui <rui.zhang@intel.com>
M:      Daniel Lezcano <daniel.lezcano@linaro.org>
R:      Amit Kucheria <amitk@kernel.org>
L:      linux-pm@vger.kernel.org
S:      Supported
Q:      https://patchwork.kernel.org/project/linux-pm/list/
...
```
