### ISSUE TITLE
3.12.0 git 4f8a88a40eda2b4c6733127e9e460c55ffa320d1

### ISSUE THREAD

**Issue by ghost** [raspberrypi/linux#422]
Built the 3.12.y kernel current as of today (2013-11-07) last commit:
4f8a88a40eda2b4c6733127e9e460c55ffa320d1

The config used is (unchanged) bcmrpi_defconfig.

At boot, the kernel hangs hard immediately after initializing the smsc95xx (see attached image). The only way to recover is to power down and switch back to an older kernel on the sdcard.

![tvtime-output-05 19 35 pm](https://f.cloud.github.com/assets/603592/1496464/4bed7484-47fb-11e3-8300-a7858f1e2504.png)

**Comment by popcornmix** [comment]
Do you have any usb devices plugged in? Can you try booting without any?

**Comment by ghost** [comment]
There are no USB devices plugged in (the Ethernet is of course USB). The previous kernel I used, built the same way, is 3.11.7 and boots correctly. This is a 512MB model B Raspberry Pi.

**Comment by ghost** [comment]
Some additional notes...

I'm using the latest Pidora 18 (fully updated), with raspberrypi-vc-firmware-20131018git4c14569-5.rpfr18.armv6hl. The kernel is built on my desktop with the cross compilation tool chain obtained with:

git clone git://github.com/raspberrypi/tools.git

I've tried building with both softfp and hardfp, with the same result, though I don't know if that makes a difference for the kernel.

**Comment by popcornmix** [comment]
Out of interest, here is a 3.12 kernel I've build (without the modules).
https://dl.dropboxusercontent.com/u/3669512/temp/kernel.img
Does that boot for you?

**Comment by ghost** [comment]
No, it hangs at the same point.

**Comment by ghost** [comment]
I also tried updating the firmware to the newer upstream with Hexxeh / rpi-update:

```
   # SKIP_KERNEL=1 rpi-update

   # vcgencmd version
   Nov  7 2013 16:49:03 
   Copyright (c) 2012 Broadcom
   version 8573b0747a17baf22e97e08254737a13d80430dd (clean) (release)
```

The 3.12 kernel still hangs at the same point, and the 3.11.7 kernel still boots normally.

**Comment by P33M** [comment]
Dupe of https://github.com/raspberrypi/linux/issues/423

Please test latest; a potential fix has been pushed.

**Comment by ghost** [comment]
Confirmed.  The fix corrects the issue.  Closing.
