### ISSUE TITLE
kernel-3.12.0: MMC fails to initialise

### ISSUE THREAD

**Issue by srcshelton** [raspberrypi/linux#423]
When booting with a USB root-filesystem:

```
[    4.766800] sdhci: Secure Digital Host Controller Interface driver
[    4.774901] sdhci: Copyright(c) Pierre Ossman
[    4.781188] sdhci: Enable low-latency mode
[    4.787208] mmc0: Hardware doesn't report any support voltages.
[    4.795020] bcm2708_sdhci bcm2708_sdhci.0: probe failed, err -19
```

This may be a timing issue, as the 'rootwait' parameter hasn't paused until the SDHC controller has become available - but this same configuration worked correctly with the 3.10.y kernels.  I had unrelated problems with 3.11.y, so don't know if this series had the same issue.

err == -19 looks to be -ENODEV, which seems to suggest that 'sdhci_alloc_host' is failing - although this would seem to return -ENOMEM on error.

Relevant configuration:

```
CONFIG_MMC=y
# CONFIG_MMC_DEBUG is not set
CONFIG_MMC_UNSAFE_RESUME=y
CONFIG_MMC_CLKGATE=y
# MMC/SD/SDIO Card Drivers
CONFIG_MMC_BLOCK=y
CONFIG_MMC_BLOCK_MINORS=8
CONFIG_MMC_BLOCK_BOUNCE=y
# CONFIG_MMC_TEST is not set
# MMC/SD/SDIO Host Controller Drivers
# CONFIG_MMC_ARMMMCI is not set
CONFIG_MMC_SDHCI=y
CONFIG_MMC_SDHCI_IO_ACCESSORS=y
# CONFIG_MMC_SDHCI_PLTFM is not set
# CONFIG_MMC_SDHCI_PXAV3 is not set
# CONFIG_MMC_SDHCI_PXAV2 is not set
CONFIG_MMC_SDHCI_BCM2708=y
CONFIG_MMC_SDHCI_BCM2708_DMA=y
# CONFIG_MMC_SPI is not set
# CONFIG_MMC_DW is not set
# CONFIG_MMC_VUB300 is not set
# CONFIG_MMC_USHC is not set
```

**Comment by srcshelton** [comment]
... additionally, it doesn't look as if this driver can be built as a module:

```
ERROR: "sdhci_spin_unlock" [drivers/mmc/host/sdhci-bcm2708.ko] undefined!
ERROR: "sdhci_spin_lock" [drivers/mmc/host/sdhci-bcm2708.ko] undefined!
ERROR: "frc_clock_ticks32" [drivers/mmc/host/sdhci-bcm2708.ko] undefined!
make[2]: *** [__modpost] Error 1
make[1]: *** [modules] Error 2
make: *** [sub-make] Error 2
```

**Comment by P33M** [comment]
http://permalink.gmane.org/gmane.linux.kernel.mmc/22140

An override mask was included in that patch which seems to have turned up in 3.12.

I'm clueless as to how this mask is nonzero - we don't set it.

**Comment by popcornmix** [comment]
I think this fixes it:
https://github.com/raspberrypi/linux/commit/c7768e2beacacbef7d6d05f40f45f0aa96cf7082

**Comment by P33M** [comment]
Seems logical. There has been a PM/regulator interface rewrite for the 3v3/1v8 capabilities detection for 3.12. It's probable that by not setting _any_ voltages, we just fell through and succeeded before.

**Comment by popcornmix** [comment]
@srcshelton 
okay to close?

**Comment by srcshelton** [comment]
Built and tested last night, and I can see my boot MMC again ;)

Thanks, all!

**Comment by gopintj** [comment]
@Mr srcshelton,
I am getting this strange error as you got before.

```
ERROR: "sdhci_spin_unlock" [drivers/mmc/host/sdhci-bcm2708.ko] undefined!
ERROR: "sdhci_spin_lock" [drivers/mmc/host/sdhci-bcm2708.ko] undefined!
ERROR: "frc_clock_ticks32" [drivers/mmc/host/sdhci-bcm2708.ko] undefined!
make[2]: *** [__modpost] Error 1
make[1]: *** [modules] Error 2
make: *** [sub-make] Error 2
```

Could anyone tell me how to get my kernel modules compiled for Raspberry Pi by overcoming this issue? 
Also, please tell me how to create code snippets in this comment box.

**Comment by popcornmix** [comment]
Don't try to build CONFIG_MMC_SDHCI_BCM2708 as a module.
Use 

```
make ARCH=arm bcmrpi_defconfig
```

to build with the default config options (used by official kernel).

(I've edited your reply to quote the code - use the edit button to see how).
