### ISSUE TITLE
Bluetooth Errors with Raspberry Pi reference 2021-03-04 

### ISSUE THREAD

**Issue by mgrouch** [raspberrypi/linux#4239]
Bluetooth and others.
They weren't present in previous kernel build

[   85.988295] Bluetooth: hci0: command 0x0401 tx timeout
[  112.100292] Bluetooth: hci0: command 0x0401 tx timeout
[  133.554922] broken atomic modeset userspace detected, disabling atomic
[  136.358306] Bluetooth: RFCOMM TTY layer initialized
[  136.358333] Bluetooth: RFCOMM socket layer initialized
[  136.358356] Bluetooth: RFCOMM ver 1.11
[  136.644858] input: Simulated Right Button as /devices/virtual/input/input8
[  138.212353] Bluetooth: hci0: command 0x0401 tx timeout
[  138.368778] fuse: init (API version 7.32)
[  139.670267] rfkill: input handler disabled
[  140.228314] Bluetooth: hci0: command 0x0c24 tx timeout
[  142.244306] Bluetooth: hci0: command 0x0c52 tx timeout
[  144.470861] w1_master_driver w1_bus_master1: Attaching one wire slave 00.400000000000 crc 46
[  144.476945] w1_master_driver w1_bus_master1: Family 0 for 00.400000000000.46 is not registered.
[  149.392746] brcmfmac: brcmf_cfg80211_set_power_mgmt: power save enabled
[  149.596071] IPv6: ADDRCONF(NETDEV_CHANGE): wlan0: link becomes ready
[  164.324305] Bluetooth: hci0: command 0x0401 tx timeout
[  190.436896] Bluetooth: hci0: command 0x0401 tx timeout
[  191.238630] w1_master_driver w1_bus_master1: Attaching one wire slave 00.c00000000000 crc ca
[  191.243492] w1_master_driver w1_bus_master1: Family 0 for 00.c00000000000.ca is not registered.
[  216.548300] Bluetooth: hci0: command 0x0401 tx timeout
[  242.660302] Bluetooth: hci0: command 0x0401 tx timeout
[  261.670601] w1_master_driver w1_bus_master1: Attaching one wire slave 00.200000000000 crc 23
[  261.676038] w1_master_driver w1_bus_master1: Family 0 for 00.200000000000.23 is not registered.
[  268.772310] Bluetooth: hci0: command 0x0401 tx timeout
[  294.884303] Bluetooth: hci0: command 0x0401 tx timeout
[  320.322769] w1_master_driver w1_bus_master1: Attaching one wire slave 00.a00000000000 crc af
[  320.327668] w1_master_driver w1_bus_master1: Family 0 for 00.a00000000000.af is not registered.
[  320.996295] Bluetooth: hci0: command 0x0401 tx timeout
[  323.646933] ieee80211 phy0: brcmf_vif_set_mgmt_ie: vndr ie set error : -52
[  323.647323] ieee80211 phy0: brcmf_vif_set_mgmt_ie: vndr ie set error : -52
[  323.650162] ieee80211 phy0: brcmf_proto_bcdc_query_dcmd: brcmf_proto_bcdc_msg failed w/status -110
[  323.650172] ieee80211 phy0: brcmf_cfg80211_get_channel: chanspec failed (-110)
[  323.650186] ieee80211 phy0: brcmf_proto_bcdc_query_dcmd: brcmf_proto_bcdc_msg failed w/status -110
[  323.650192] ieee80211 phy0: brcmf_cfg80211_get_tx_power: error (-110)

Kernel:

    0.000000] Booting Linux on physical CPU 0x0000000000 [0x410fd083]
[    0.000000] Linux version 5.10.17-v8+ (dom@buildbot) (aarch64-linux-gnu-gcc-8 (Ubuntu/Linaro 8.4.0-3ubuntu1) 8.4.0, GNU ld 
(GNU Binutils for Ubuntu) 2.34) #1403 SMP PREEMPT Mon Feb 22 11:37:54 GMT 2021
[    0.000000] Machine model: Raspberry Pi 4 Model B Rev 1.4
[    0.000000] efi: UEFI not found.
[    0.000000] Reserved memory: created CMA memory pool at 0x000000000fc00000, size 256 MiB
[    0.000000] OF: reserved mem: initialized node linux,cma, compatible id shared-dma-pool
[    0.000000] Zone ranges:
[    0.000000]   DMA      [mem 0x0000000000000000-0x000000003fffffff]
[    0.000000]   DMA32    [mem 0x0000000040000000-0x00000000ffffffff]
[    0.000000]   Normal   [mem 0x0000000100000000-0x00000001ffffffff]
[    0.000000] Movable zone start for each node
[    0.000000] Early memory node ranges
[    0.000000]   node   0: [mem 0x0000000000000000-0x000000001fffffff]
[    0.000000]   node   0: [mem 0x0000000040000000-0x00000000fbffffff]
[    0.000000]   node   0: [mem 0x0000000100000000-0x00000001ffffffff]
[    0.000000] Initmem setup node 0 [mem 0x0000000000000000-0x00000001ffffffff]
[    0.000000] On node 0 totalpages: 1949696
[    0.000000]   DMA zone: 2048 pages used for memmap
[    0.000000]   DMA zone: 0 pages reserved
[    0.000000]   DMA zone: 131072 pages, LIFO batch:31
[    0.000000]   DMA32 zone: 12288 pages used for memmap
[    0.000000]   DMA32 zone: 770048 pages, LIFO batch:63
[    0.000000]   Normal zone: 16384 pages used for memmap
[    0.000000]   Normal zone: 1048576 pages, LIFO batch:63
[    0.000000] percpu: Embedded 32 pages/cpu s91224 r8192 d31656 u131072

**Comment by mgrouch** [comment]
Looks like power management related in latest broadcom firmware are breaking
bluetooth

**Comment by mgrouch** [comment]
There are even more errors I thin related.
When I try to turn off bluetooth and wifi power saving
I get error:

[ 3320.800397] ieee80211 phy0: brcmf_vif_set_mgmt_ie: vndr ie set error : -52
[ 3320.800780] ieee80211 phy0: brcmf_vif_set_mgmt_ie: vndr ie set error : -52
[ 3320.837426] Bluetooth: hci0: command 0x0401 tx timeout

And the other started popping up (all after recent update)

[   86.555659] v3d fec00000.v3d: MMU error from client L2T (0) at 0x1181000, pte invalid

**Comment by mgrouch** [comment]
I’ve turned off 1wire put a better power supply 5.2 volts 15 watts
And see still same Bluetooth errors
both on arm64 kernel and armhf. 
Somehow I think it points to Broadcom firmware

**Comment by pelwell** [comment]
What is Bluetooth being used for in your system?

Please try adding `over_voltage=2` to your config.txt.

**Comment by mgrouch** [comment]
I’ve tried over_voltage=2 same errors. 
I’ve tried only switching airplane mode back and force. Nothing is even connected to Bluetooth yet. 

[  100.554748] v3d fec00000.v3d: MMU error from client L2T (0) at 0x1361000, pte invalid
[  122.689402] Bluetooth: hci0: command 0x1003 tx timeout
[  124.705455] Bluetooth: hci0: command 0x1001 tx timeout
[  136.673556] Bluetooth: hci0: command 0x1003 tx timeout
[  138.689577] Bluetooth: hci0: command 0x1001 tx timeout
[  140.705615] Bluetooth: hci0: command 0x1009 tx timeout
[  214.914252] bcmgenet fd580000.ethernet eth0: Link is Down
[  217.986389] bcmgenet fd580000.ethernet eth0: Link is Up - 100Mbps/Full - flow control rx/tx

And ethernet link keeps being bounced too for no apparent reason.


More from logs

Mar 31 17:12:29 lysmarine systemd[1]: Starting Configure Bluetooth Modems connected by UART...
Mar 31 17:12:31 lysmarine NetworkManager[504]: <info>  [1617207151.5926] Loaded device plugin: NMBluezManager (/usr/lib/aarch64-linux-gnu/NetworkManager/1.14.6/libnm-device-plugin-bluetooth.so)
Mar 31 17:12:36 lysmarine kernel: [   45.813495] Bluetooth: Core ver 2.22
Mar 31 17:12:36 lysmarine kernel: [   45.814907] Bluetooth: HCI device and connection manager initialized
Mar 31 17:12:36 lysmarine kernel: [   45.814924] Bluetooth: HCI socket layer initialized
Mar 31 17:12:36 lysmarine kernel: [   45.814932] Bluetooth: L2CAP socket layer initialized
Mar 31 17:12:36 lysmarine kernel: [   45.814959] Bluetooth: SCO socket layer initialized
Mar 31 17:12:37 lysmarine kernel: [   47.111484] Bluetooth: HCI UART driver ver 2.3
Mar 31 17:12:37 lysmarine kernel: [   47.111498] Bluetooth: HCI UART protocol H4 registered
Mar 31 17:12:37 lysmarine kernel: [   47.113481] Bluetooth: HCI UART protocol Three-wire (H5) registered
Mar 31 17:12:37 lysmarine kernel: [   47.113698] Bluetooth: HCI UART protocol Broadcom registered
Mar 31 17:12:37 lysmarine systemd[1]: Started Configure Bluetooth Modems connected by UART.
Mar 31 17:12:37 lysmarine systemd[1]: Starting Bluetooth service...
Mar 31 17:12:39 lysmarine bluetoothd[1232]: Bluetooth daemon 5.50
Mar 31 17:12:39 lysmarine systemd[1]: Started Bluetooth service.
Mar 31 17:12:39 lysmarine systemd[1]: Reached target Bluetooth.
Mar 31 17:12:39 lysmarine systemd[1]: Started Raspberry Pi bluetooth helper.
Mar 31 17:12:39 lysmarine bluetoothd[1232]: Starting SDP server
Mar 31 17:12:39 lysmarine bluetoothd[1232]: Bluetooth management interface 1.18 initialized
Mar 31 17:12:39 lysmarine kernel: [   48.504436] Bluetooth: BNEP (Ethernet Emulation) ver 1.3
Mar 31 17:12:39 lysmarine kernel: [   48.504448] Bluetooth: BNEP filters: protocol multicast
Mar 31 17:12:39 lysmarine kernel: [   48.504464] Bluetooth: BNEP socket layer initialized
Mar 31 17:12:40 lysmarine bluetoothd[1232]: Sap driver initialization failed.
Mar 31 17:12:40 lysmarine bluetoothd[1232]: sap-server: Operation not permitted (1)
Mar 31 17:12:40 lysmarine bluetoothd[1232]: Failed to set privacy: Rejected (0x0b)
Mar 31 17:13:09 lysmarine kernel: [   62.693101] Bluetooth: hci0: command 0x0401 tx timeout
Mar 31 17:13:21 lysmarine bluetoothd[1232]: Endpoint registered: sender=:1.36 path=/MediaEndpoint/A2DPSource
Mar 31 17:13:21 lysmarine bluetoothd[1232]: Endpoint registered: sender=:1.36 path=/MediaEndpoint/A2DPSink
Mar 31 17:13:21 lysmarine kernel: [   74.839326] Bluetooth: RFCOMM TTY layer initialized
Mar 31 17:13:21 lysmarine kernel: [   74.839351] Bluetooth: RFCOMM socket layer initialized
Mar 31 17:13:21 lysmarine kernel: [   74.839372] Bluetooth: RFCOMM ver 1.11
Mar 31 17:13:23 lysmarine kernel: [   76.869240] Bluetooth: hci0: command 0x0c24 tx timeout

**Comment by Matheritasiv** [comment]
My 3b+ had run into the same problem right after I upgraded package `linux-firmware` from version `20201218.646f159-1` to `20210208.b79d239-1`, when the kernel was 5.10.4-v8+. Here are booting logs
```
Booting Linux on physical CPU 0x0000000000 [0x410fd034]
Linux version 5.10.4-v8 (wasiv@Sarch) (aarch64-linux-gnu-gcc (GCC) 10.2.0, GNU ld (GNU Binutils) 2.35.1) #1 SMP PREEMPT Tue Jan 5 10:59:11 CST 2021
Machine model: Raspberry Pi 3 Model B Plus Rev 1.3
efi: UEFI not found.
Reserved memory: created CMA memory pool at 0x000000001e800000, size 256 MiB
OF: reserved mem: initialized node linux,cma, compatible id shared-dma-pool
Zone ranges:
  DMA      [mem 0x0000000000000000-0x000000003bffffff]
  DMA32    empty
............
Bluetooth: Core ver 2.22
Bluetooth: HCI device and connection manager initialized
Bluetooth: HCI socket layer initialized
Bluetooth: L2CAP socket layer initialized
Bluetooth: SCO socket layer initialized
Bluetooth: HCI UART driver ver 2.3
Bluetooth: HCI UART protocol H4 registered
Bluetooth: HCI UART protocol Three-wire (H5) registered
Bluetooth: HCI UART protocol Broadcom registered
Bluetooth: hci0: command 0xfc18 tx timeout
brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac43455-sdio for chip BCM4345/6
usbcore: registered new interface driver brcmfmac
brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac43455-sdio for chip BCM4345/6
brcmfmac: brcmf_c_preinit_dcmds: Firmware: BCM4345/6 wl0: Feb 27 2018 03:15:32 version 7.45.154 (r684107 CY) FWID 01-4fbe0b04
Bluetooth: hci0: BCM: failed to write update baudrate (-110)
Bluetooth: hci0: Failed to set baudrate
Bluetooth: hci0: command 0x0c03 tx timeout
Bluetooth: hci0: BCM: Reset failed (-110)
Bluetooth: hci0: hardware error 0x00
Bluetooth: hci0: command 0xfc18 tx timeout
Bluetooth: hci0: BCM: failed to write update baudrate (-110)
Bluetooth: hci0: Failed to set baudrate
Bluetooth: hci0: command 0x0c03 tx timeout
brcmfmac: brcmf_cfg80211_set_power_mgmt: power save enabled
Bluetooth: BNEP (Ethernet Emulation) ver 1.3
Bluetooth: BNEP filters: protocol multicast
Bluetooth: BNEP socket layer initialized
Bluetooth: hci0: BCM: Reset failed (-110)
............
```
and logs before that upgradation
```
Booting Linux on physical CPU 0x0000000000 [0x410fd034]
Linux version 5.10.4-v8 (wasiv@Sarch) (aarch64-linux-gnu-gcc (GCC) 10.2.0, GNU ld (GNU Binutils) 2.35.1) #1 SMP PREEMPT Tue Jan 5 10:59:11 CST 2021
Machine model: Raspberry Pi 3 Model B Plus Rev 1.3
efi: UEFI not found.
Reserved memory: created CMA memory pool at 0x000000001e800000, size 256 MiB
OF: reserved mem: initialized node linux,cma, compatible id shared-dma-pool
Zone ranges:
  DMA      [mem 0x0000000000000000-0x000000003bffffff]
  DMA32    empty
............
Bluetooth: Core ver 2.22
Bluetooth: HCI device and connection manager initialized
Bluetooth: HCI socket layer initialized
Bluetooth: L2CAP socket layer initialized
Bluetooth: SCO socket layer initialized
Bluetooth: HCI UART driver ver 2.3
Bluetooth: HCI UART protocol H4 registered
Bluetooth: HCI UART protocol Three-wire (H5) registered
Bluetooth: HCI UART protocol Broadcom registered
Bluetooth: hci0: BCM: chip id 107
Bluetooth: hci0: BCM: features 0x2f
Bluetooth: hci0: BCM4345C0
Bluetooth: hci0: BCM4345C0 (003.001.025) build 0000
Bluetooth: hci0: BCM4345C0 'brcm/BCM4345C0.hcd' Patch
Bluetooth: hci0: BCM4345C0 UART 37.4 MHz wlbga_ref_iLNA_iTR_eLG 0139
Bluetooth: hci0: BCM4345C0 (003.001.025) build 0139
brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac43455-sdio for chip BCM4345/6
usbcore: registered new interface driver brcmfmac
brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac43455-sdio for chip BCM4345/6
brcmfmac: brcmf_c_preinit_dcmds: Firmware: BCM4345/6 wl0: Feb 27 2018 03:15:32 version 7.45.154 (r684107 CY) FWID 01-4fbe0b04
brcmfmac: brcmf_cfg80211_set_power_mgmt: power save enabled
Bluetooth: BNEP (Ethernet Emulation) ver 1.3
Bluetooth: BNEP filters: protocol multicast
Bluetooth: BNEP socket layer initialized
............
```
Now my kernel version is 5.10.17-v8+ and I have tried downgrading `linux-firmware` to the old version, but the problem remains.

**Comment by Matheritasiv** [comment]
My 3b+ had run into the same problem right after I upgraded package `linux-firmware` from version `20201218.646f159-1` to `20210208.b79d239-1`, when the kernel was 5.10.4-v8+. Here are booting logs
```
Booting Linux on physical CPU 0x0000000000 [0x410fd034]
Linux version 5.10.4-v8 (wasiv@Sarch) (aarch64-linux-gnu-gcc (GCC) 10.2.0, GNU ld (GNU Binutils) 2.35.1) #1 SMP PREEMPT Tue Jan 5 10:59:11 CST 2021
Machine model: Raspberry Pi 3 Model B Plus Rev 1.3
efi: UEFI not found.
Reserved memory: created CMA memory pool at 0x000000001e800000, size 256 MiB
OF: reserved mem: initialized node linux,cma, compatible id shared-dma-pool
Zone ranges:
  DMA      [mem 0x0000000000000000-0x000000003bffffff]
  DMA32    empty
............
Bluetooth: Core ver 2.22
Bluetooth: HCI device and connection manager initialized
Bluetooth: HCI socket layer initialized
Bluetooth: L2CAP socket layer initialized
Bluetooth: SCO socket layer initialized
Bluetooth: HCI UART driver ver 2.3
Bluetooth: HCI UART protocol H4 registered
Bluetooth: HCI UART protocol Three-wire (H5) registered
Bluetooth: HCI UART protocol Broadcom registered
Bluetooth: hci0: command 0xfc18 tx timeout
brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac43455-sdio for chip BCM4345/6
usbcore: registered new interface driver brcmfmac
brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac43455-sdio for chip BCM4345/6
brcmfmac: brcmf_c_preinit_dcmds: Firmware: BCM4345/6 wl0: Feb 27 2018 03:15:32 version 7.45.154 (r684107 CY) FWID 01-4fbe0b04
Bluetooth: hci0: BCM: failed to write update baudrate (-110)
Bluetooth: hci0: Failed to set baudrate
Bluetooth: hci0: command 0x0c03 tx timeout
Bluetooth: hci0: BCM: Reset failed (-110)
Bluetooth: hci0: hardware error 0x00
Bluetooth: hci0: command 0xfc18 tx timeout
Bluetooth: hci0: BCM: failed to write update baudrate (-110)
Bluetooth: hci0: Failed to set baudrate
Bluetooth: hci0: command 0x0c03 tx timeout
brcmfmac: brcmf_cfg80211_set_power_mgmt: power save enabled
Bluetooth: BNEP (Ethernet Emulation) ver 1.3
Bluetooth: BNEP filters: protocol multicast
Bluetooth: BNEP socket layer initialized
Bluetooth: hci0: BCM: Reset failed (-110)
............
```
and logs before that upgradation
```
Booting Linux on physical CPU 0x0000000000 [0x410fd034]
Linux version 5.10.4-v8 (wasiv@Sarch) (aarch64-linux-gnu-gcc (GCC) 10.2.0, GNU ld (GNU Binutils) 2.35.1) #1 SMP PREEMPT Tue Jan 5 10:59:11 CST 2021
Machine model: Raspberry Pi 3 Model B Plus Rev 1.3
efi: UEFI not found.
Reserved memory: created CMA memory pool at 0x000000001e800000, size 256 MiB
OF: reserved mem: initialized node linux,cma, compatible id shared-dma-pool
Zone ranges:
  DMA      [mem 0x0000000000000000-0x000000003bffffff]
  DMA32    empty
............
Bluetooth: Core ver 2.22
Bluetooth: HCI device and connection manager initialized
Bluetooth: HCI socket layer initialized
Bluetooth: L2CAP socket layer initialized
Bluetooth: SCO socket layer initialized
Bluetooth: HCI UART driver ver 2.3
Bluetooth: HCI UART protocol H4 registered
Bluetooth: HCI UART protocol Three-wire (H5) registered
Bluetooth: HCI UART protocol Broadcom registered
Bluetooth: hci0: BCM: chip id 107
Bluetooth: hci0: BCM: features 0x2f
Bluetooth: hci0: BCM4345C0
Bluetooth: hci0: BCM4345C0 (003.001.025) build 0000
Bluetooth: hci0: BCM4345C0 'brcm/BCM4345C0.hcd' Patch
Bluetooth: hci0: BCM4345C0 UART 37.4 MHz wlbga_ref_iLNA_iTR_eLG 0139
Bluetooth: hci0: BCM4345C0 (003.001.025) build 0139
brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac43455-sdio for chip BCM4345/6
usbcore: registered new interface driver brcmfmac
brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac43455-sdio for chip BCM4345/6
brcmfmac: brcmf_c_preinit_dcmds: Firmware: BCM4345/6 wl0: Feb 27 2018 03:15:32 version 7.45.154 (r684107 CY) FWID 01-4fbe0b04
brcmfmac: brcmf_cfg80211_set_power_mgmt: power save enabled
Bluetooth: BNEP (Ethernet Emulation) ver 1.3
Bluetooth: BNEP filters: protocol multicast
Bluetooth: BNEP socket layer initialized
............
```
Now my kernel version is 5.10.17-v8+ and I have tried downgrading `linux-firmware` to the old version, but the problem remains.

**Comment by mgrouch** [comment]
Found the cause:

Full story here: https://github.com/bareboat-necessities/lysmarine_gen/issues/120
