### ISSUE TITLE
Missing IP Protocol 97 for Strongswan IPSEC VPN

### ISSUE THREAD

**Issue by gstreeter** [raspberrypi/linux#424]
I've updated a Pi to kernel 3.10.18+ #585 with rpi-update and found that Strongswan 5.1.1 IPSEC VPN no longer functions. This works fine on the current 3.6.11+ #538 kernel.

The following error message appears in the IPsec log file:

"received netlink error: Address family not supported by protocol (97)"

Looks like there something missing out of the kernel 3.10.18+ build that was present in the 3.6.11 version.

**Comment by popcornmix** [comment]
From here:
http://wiki.strongswan.org/projects/strongswan/wiki/KernelModules
I think these are needed:
CONFIG_IP_ADVANCED_ROUTER=y
CONFIG_IP_MULTIPLE_TABLES=y

I'll add in next update (probably later today)

**Comment by gstreeter** [comment]
It was suggested in the Pi forum that the ipip module was missing from the build which indeed it is. I was able to get this to be built by adding the module option under the menuconfig item Network Support -> Networking options -> IP: tunneling

The additional modules that are loaded when I start the Strongswan IPSEC VPN server on the 3.6.11 kernel are listed below:

xfrm4_tunnel  
tunnel4  
ipcomp  
xfrm_ipcomp  
esp4  
ah4  
af_key

**Comment by popcornmix** [comment]
Can you try after updating?

**Comment by gstreeter** [comment]
Hi,

I&#39;ve just updated to #587 and this has fixed the issue. Thanks for the prompt turn-around.

Gary

**Comment by popcornmix** [comment]
Good to hear.
