### ISSUE TITLE
3.10.18+ spidev does not auto load, and when loaded does not enumerate /dev/spidev*

### ISSUE THREAD

**Issue by chrisy** [raspberrypi/linux#425]
Fresh official Raspbian, updated with `dist-upgrade` and `rpi-update` gets kernel 3.10.18+.

With kernel 3.10.18+, `spi_bcm2708` apparently loads fine after modifying the blacklist, but `spidev` does not load automagically at boot.

Manually loading `spidev` does not enumerate SPI nodes in `/dev/spidev*`, rendering SPI unusable.

**Comment by mschorer** [comment]
exact same here.

**Comment by popcornmix** [comment]
I've made a change to config and get:

```
 $ sudo modprobe spi-bcm2708
[12751.762387] bcm2708_spi bcm2708_spi.0: master is unqueued, this is deprecated
[12751.780632] bcm2708_spi bcm2708_spi.0: SPI Controller at 0x20204000 (irq 80)
$ ls -l /dev/spidev0.*
crw------- 1 root root 153, 0 Nov 14 18:03 /dev/spidev0.0
crw------- 1 root root 153, 1 Nov 14 18:03 /dev/spidev0.1
```

I don't have any SPI devices, but I assume that is a good sign.

**Comment by mschorer** [comment]
yep. when can i get it? ;-)

**Comment by popcornmix** [comment]
I should push it tomorrow.

**Comment by mschorer** [comment]
yey!

On 14 November 2013 19:59, popcornmix notifications@github.com wrote:

> I should push it tomorrow.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/raspberrypi/linux/issues/425#issuecomment-28511880
> .

## 

---

markus schorer          | reicheteile/landsberg
fon +49 172 8932067    | http://www.alrightythen.de/blog/

**Comment by chrisy** [comment]
Jolly good stuff!

**Comment by popcornmix** [comment]
It's pushed. Please update and test.

**Comment by mschorer** [comment]
works for me!

thy

**Comment by popcornmix** [comment]
Great!
@chrisy okay to close?

**Comment by g7ruh** [comment]
My SPI works fine now in 3.10. Thanks.

**Comment by chrisy** [comment]
Just ssh'ed into a test Pi at home, from work. Testing now :)

**Comment by chrisy** [comment]
```
root@pith:/home/pi# ls -l /dev/spi*
crw------- 1 root root 153, 0 Dec 31  1969 /dev/spidev0.0
crw------- 1 root root 153, 1 Dec 31  1969 /dev/spidev0.1
root@pith:/home/pi# uname -a
Linux pith.flirble.org 3.10.18+ #596 PREEMPT Fri Nov 15 13:57:24 GMT 2013 armv6l GNU/Linux
root@pith:/home/pi# 
```

Yay!

Looks good to me!

**Comment by pacmac** [comment]
Just updated ARCH LINUX to 3.10.19-1 and spidev still appears to be broken, same as with 3.10.18-1

**Comment by popcornmix** [comment]
@pacmac 
My guess is that arch haven't taken patch 49e62a2. You should report the issue there.
