### ISSUE TITLE
[Kernel build file is changed but not work] Apply extra file system support failed

### ISSUE THREAD

**Issue by Twilight-Dream-Of-Magic** [raspberrypi/linux#4253]
# Hello everyone, I have a hard problem
### I need help

From discord chat history:
(Unoffical Gentoo Linux)

https://cdn.discordapp.com/attachments/711824009930735697/826895604260405258/20210401030651.png
https://cdn.discordapp.com/attachments/711824009930735697/826896272530604052/20210401031018.png
Twilight_Magical 03:11
Why did it become like this?
https://cdn.discordapp.com/attachments/711824009930735697/826896777062907984/20210401031220.png

Chris 03:25
are you trying to boot from xfs partition?

Twilight_Magical 03:26
No, I just load and save data in the xfs partition or virtual disk service

Chris 03:27
If nothing works I'd try loading xfs as module but recompiling kernel sounds like a pain so maybe somebody might come up with something better

[03:29]
Chris
also do you have `sys-fs/xfsprogs` installed?

Twilight_Magical 03:31
Yes, I installed it `sys-fs/xfsprogs`

Chris
If nothing works I'd try loading xfs as module but recompiling kernel sounds like a pain so maybe somebody might come up with something better

### **That didn't work, I tried to modprobe XFS as a file system module before**

Chris 03:31
have you tried mounting with mount?

https://cdn.discordapp.com/attachments/711824009930735697/826904191480889364/20210401034131.png

Twilight_Magical 03:42
Not work again

goll 03:42
what shows up when you run modinfo xfs?

### **I’m sure I rebuilt the Raspberry Linux kernel and manually changed the kernel build configuration file**

goll
what shows up when you run modinfo xfs?

Twilight_Magical 03:46
```
twilight-dream-rpi64# modinfo xfs
modinfo: ERROR: Module alias xfs not found.
twilight-dream-rpi64#
```
Chris 03:46
just to be sure, you're booted with the custom kernel? a.k.a installed it where needed

goll 03:47
then that means the kernel doesnt support xfs
[03:47]
(modinfo works for builtin components as well)

https://cdn.discordapp.com/attachments/711824009930735697/826906252045975552/20210401034913.png

goll 03:50
that is if the name of the module for xfs is xfs which idk

Chris 03:51
https://cdn.discordapp.com/attachments/711824009930735697/826906523203928064/unknown.png

Chris

Twilight_Magical 03:53
Your custom build-ed gentoo linux on the raspberry pi is successful ?

Chris 03:53
hehe I'm using pi for octoprint atm
[03:54]
so it's not even gentoo there

Chris
hehe I'm using pi for octoprint atm

Twilight_Magical 03:55
Okay, what can I do to solve this problem?
You think?

Chris 03:56
I'm not sure tbh
[03:56]
what kernel are you running `uname -r`

Twilight_Magical 03:57
```
twilight-dream-rpi64# uname -r
5.10.16-v8+
twilight-dream-rpi64#
```
Chris 03:57
and you were compiling 5.10.16?

Twilight_Magical 03:58
.config file is linux kernel config in the building progress

```
CONFIG_XFS_FS=y
CONFIG_XFS_QUOTA=y
CONFIG_XFS_POSIX_ACL=y
CONFIG_XFS_RT=y
```

y = yes, apply this to kernel
m = yes, apply this to kernel module
n = no, not apply this to kernel

Chris 03:59
yes but you also have to install that kernel
[03:59]
that's my only idea
[03:59]
that it booted with older kernel for some reason
[04:00]
try 
`zcat /proc/config.gz | grep XFS`

Chris
try `zcat /proc/config.gz | grep XFS`

Twilight_Magical 04:08

```
twilight-dream-rpi64# zcat /proc/config.gz | grep XFS
gzip: /proc/config.gz: No such file or directory
twilight-dream-rpi64#
```

**Comment by pelwell** [comment]
Your .config file must contain either `CONFIG_XFS_FS=y` or `CONFIG_XFS_FS=m`.

**Comment by Twilight-Dream-Of-Magic** [comment]
> Your .config file must contain either `CONFIG_XFS_FS=y` or `CONFIG_XFS_FS=m`.
I have discord chat history, please to look up

**Comment by pelwell** [comment]
You'll need to `sudo modprobe config` (or perhaps `sudo modprobe configs`) before `zcat /proc/config.gz` will work, which will allow you to check the running kernel configuration.

**Comment by Twilight-Dream-Of-Magic** [comment]
> You'll need to `sudo modprobe config` (or perhaps `sudo modprobe configs`) before `zcat /proc/config.gz` will work, which will allow you to check the running kernel configuration.
```
twilight-dream-rpi64# sudo modprobe configs
modprobe: FATAL: Module configs not found in directory /lib/modules/5.10.16-v8+
twilight-dream-rpi64# sudo modprobe config 
modprobe: FATAL: Module config not found in directory /lib/modules/5.10.16-v8+
twilight-dream-rpi64#
```

**Comment by Twilight-Dream-Of-Magic** [comment]
> > You'll need to `sudo modprobe config` (or perhaps `sudo modprobe configs`) before `zcat /proc/config.gz` will work, which will allow you to check the running kernel configuration.
> 
> ```
> twilight-dream-rpi64# sudo modprobe configs
> modprobe: FATAL: Module configs not found in directory /lib/modules/5.10.16-v8+
> twilight-dream-rpi64# sudo modprobe config 
> modprobe: FATAL: Module config not found in directory /lib/modules/5.10.16-v8+
> twilight-dream-rpi64#
> ```

Never not work

**Comment by pelwell** [comment]
Your kernel config must not include the setting to enable the /proc entry.

Your are not reporting a bug in the kernel, and this isn't a help forum, so I'm closing the issue.
