### ISSUE TITLE
Smart pi Touch configuration with buildroot

### ISSUE THREAD

**Issue by Aziz1296** [raspberrypi/linux#4265]
Hello , I deploying QT app using buildroot toolchain to raspberry pi 3. Currently my app appears On target but i have problems with my touchscreen it's not working . when i clicked on button nothing move on .  
So how can i configure the touchscreen using  buildroot menuconfig . Any help please

**Comment by pelwell** [comment]
Qt and buildroot and a touchscreen - that's three problems in one, and none of them a kernel bug. For help requests, try the Raspberry Pi forums.

**Comment by Aziz1296** [comment]
Any help please ?
