### ISSUE TITLE
lost of power

### ISSUE THREAD

**Issue by slippy2016** [raspberrypi/linux#4275]
Hi I am new at this  I am supplying 5v dc to a switch b3f  but when I press it to go to the transistor to send a signal to a relay to  energize it  lose power.

Also the metal bit of the Arduinos USB is live

**Comment by JamesH65** [comment]
Hi, this repo is for bug reports on the Linux kernel. Your question would be much better served by posting it on the forums. 

https://www.raspberrypi.org/forums/
