### ISSUE TITLE
Network problem with 3.10.17

### ISSUE THREAD

**Issue by ottuzzi** [raspberrypi/linux#428]
Hi,

   on my raspi running 3.10.17 I saw the following in syslog:

<pre>
------------[ cut here ]------------
WARNING: at net/ipv4/tcp_input.c:2776 tcp_fastretrans_alert+0x9a0/0x9dc()
Modules linked in: fuse snd_bcm2835 snd_pcm snd_page_alloc snd_seq snd_seq_device snd_timer snd sd_mod leds_gpio ums_cypress led_class
CPU: 0 PID: 0 Comm: swapper Not tainted 3.10.17+ #571
[<c00153c8>] (unwind_backtrace+0x0/0xfc) from [<c0011ecc>] (show_stack+0x20/0x24)
[<c0011ecc>] (show_stack+0x20/0x24) from [<c0445204>] (dump_stack+0x20/0x28)
[<c0445204>] (dump_stack+0x20/0x28) from [<c0021038>] (warn_slowpath_common+0x5c/0x78)
[<c0021038>] (warn_slowpath_common+0x5c/0x78) from [<c0021080>] (warn_slowpath_null+0x2c/0x34)
[<c0021080>] (warn_slowpath_null+0x2c/0x34) from [<c03d4fd0>] (tcp_fastretrans_alert+0x9a0/0x9dc)
[<c03d4fd0>] (tcp_fastretrans_alert+0x9a0/0x9dc) from [<c03d59a4>] (tcp_ack+0x8e4/0xc4c)
[<c03d59a4>] (tcp_ack+0x8e4/0xc4c) from [<c03d6194>] (tcp_rcv_established+0xe4/0x5e0)
[<c03d6194>] (tcp_rcv_established+0xe4/0x5e0) from [<c03de618>] (tcp_v4_do_rcv+0x104/0x250)
[<c03de618>] (tcp_v4_do_rcv+0x104/0x250) from [<c03e0d6c>] (tcp_v4_rcv+0x720/0x758)
[<c03e0d6c>] (tcp_v4_rcv+0x720/0x758) from [<c03bed48>] (ip_local_deliver_finish+0xdc/0x254)
[<c03bed48>] (ip_local_deliver_finish+0xdc/0x254) from [<c03bf01c>] (ip_local_deliver+0x40/0x98)
[<c03bf01c>] (ip_local_deliver+0x40/0x98) from [<c03bea64>] (ip_rcv_finish+0x124/0x32c)
[<c03bea64>] (ip_rcv_finish+0x124/0x32c) from [<c03bf278>] (ip_rcv+0x204/0x32c)
[<c03bf278>] (ip_rcv+0x204/0x32c) from [<c038d398>] (__netif_receive_skb_core+0x6b0/0x814)
[<c038d398>] (__netif_receive_skb_core+0x6b0/0x814) from [<c038f718>] (__netif_receive_skb+0x20/0x70)
[<c038f718>] (__netif_receive_skb+0x20/0x70) from [<c038f7f4>] (process_backlog+0x8c/0x140)
[<c038f7f4>] (process_backlog+0x8c/0x140) from [<c038ff6c>] (net_rx_action+0x110/0x228)
[<c038ff6c>] (net_rx_action+0x110/0x228) from [<c0028d50>] (__do_softirq+0xf0/0x260)
[<c0028d50>] (__do_softirq+0xf0/0x260) from [<c0028f90>] (do_softirq+0x74/0x7c)
[<c0028f90>] (do_softirq+0x74/0x7c) from [<c00292a0>] (irq_exit+0xb0/0xec)
[<c00292a0>] (irq_exit+0xb0/0xec) from [<c000f10c>] (handle_IRQ+0x44/0x94)
[<c000f10c>] (handle_IRQ+0x44/0x94) from [<c0008470>] (asm_do_IRQ+0x18/0x1c)
[<c0008470>] (asm_do_IRQ+0x18/0x1c) from [<c04484d8>] (__irq_svc+0x38/0xb0)
Exception stack(0xc066ff40 to 0xc066ff88)
ff40: 00000000 00000000 c06a5ea8 c0676e84 c066e000 c06af8b4 c06b006c c066e000
ff60: c06af8b4 c066e000 c0676094 c066ff94 c066ff88 c066ff88 c000f310 c000f314
ff80: 60000013 ffffffff
[<c04484d8>] (__irq_svc+0x38/0xb0) from [<c000f314>] (arch_cpu_idle+0x3c/0x4c)
[<c000f314>] (arch_cpu_idle+0x3c/0x4c) from [<c005a470>] (cpu_startup_entry+0x70/0x1b0)
[<c005a470>] (cpu_startup_entry+0x70/0x1b0) from [<c04411c4>] (rest_init+0x6c/0x84)
[<c04411c4>] (rest_init+0x6c/0x84) from [<c0627a94>] (start_kernel+0x2ec/0x350)
---[ end trace 99c6779e438efcf7 ]---
</pre>

Please ask if you need more information.

Thanks for your work
Bye
Piero

**Comment by ottuzzi** [comment]
It looks like it is the same reported here: http://forums.gentoo.org/viewtopic-p-7380374.html

**Comment by popcornmix** [comment]
This commit appears to be in the 3.10.y kernel:
https://github.com/raspberrypi/linux/commit/d8ac0f178f98d4e7c23cf9526d789d4869ec6e4c
You should update.

**Comment by ottuzzi** [comment]
I just update to 3.10.18: I'll let you know if I'll something good about it.

Thanks
Bye
Piero

**Comment by popcornmix** [comment]
Okay to close?

**Comment by ottuzzi** [comment]
After updating to 3.10.18 it never happened again. I close this issue.
