### ISSUE TITLE
Camera control callback  cmd=0x4f525245mmal: No data received from sensor. Check all connections, including the Sunny one on the camera board

### ISSUE THREAD

**Issue by cchristion** [raspberrypi/linux#4282]
How can i resolve this ?
Currently running in headless mode in raspberry pi - 4B ( 2GB RAM ) with ssh.

raspistill -v -o test.png 

> "raspistill" Camera App (commit 4a0a19b88b43 Tainted)
> Camera Name ov5647
> Width 2592, Height 1944, filename test.png
> Using camera 0, sensor mode 0
> GPS output Disabled
> Quality 85, Raw no
> Thumbnail enabled Yes, width 64, height 48, quality 35
> Time delay 5000, Timelapse 0
> Link to latest frame enabled  no
> Full resolution preview No
> Capture method : Single capture
> Preview Yes, Full screen Yes
> Preview window 0,0,1024,768
> Opacity 255
> Sharpness 0, Contrast 0, Brightness 50
> Saturation 0, ISO 0, Video Stabilisation No, Exposure compensation 0
> Exposure Mode 'auto', AWB Mode 'auto', Image Effect 'none'
> Flicker Avoid Mode 'off'
> Metering Mode 'average', Colour Effect Enabled No with U = 128, V = 128
> Rotation 0, hflip No, vflip No
> ROI x 0.000000, y 0.000000, w 1.000000 h 1.000000
> Camera component done
> Encoder component done
> Starting component connection stage
> Connecting camera preview port to video render.
> Connecting camera stills port to encoder input port
> Opening output file test.png
> Enabling encoder output port
> Starting capture -1
> **Camera control callback  cmd=0x4f525245mmal: No data received from sensor. Check all connections, including the Sunny one on the camera board**

**Comment by 6by9** [comment]
You have a hardware connection issue. There is no software fix, and it's not a Linux kernel issue.

The I2C control for the sensor is fine, but no data is being received over the CSI2 bus.
Check all connections (as the error message tells you). If you're certain they're good, then try swapping to an alternate sensor to verify whether it is the Pi or sensor that is at fault. The sensors are static sensitive, and it is possible to kill just the CSI2 transmitter side with static.
