### ISSUE TITLE
What's changed? Later kernels fail to boot...

### ISSUE THREAD

**Issue by keylevel** [raspberrypi/linux#43]
I'm building from source (Yocto Project) and the latest kernels just give me the 'four-colour' screen.

1) I'm using the latest firmware (https://github.com/raspberrypi/firmware/commit/9308c7ed387e5422883753f7fb71a75506abd1f8);
2) https://github.com/raspberrypi/linux/commit/3fc65f9f291fb19cad434968a4a0f66ab749e637 is the last kernel that I can get to run.

Is there something new that I need to add to config.txt or similar?

**Comment by popcornmix** [comment]
So if you use prebuilt kernel does it boot, or is it only your own build that fails?
So this works:
3fc65f9f291fb19cad434968a4a0f66ab749e637 Explicitly set usb host channels to 8, as in the spec
And this fails?
cc5758b24650164cfbeb351983f4127e7b682426 Add hfs/hfsplus modules

Well you can see what's changed, and there's nothing controversial there.

**Comment by keylevel** [comment]
Yes, that's correct. The fact that nothing significant has changed is what's confusing me. Build environment is exactly the same in each case.

**Comment by keylevel** [comment]
What version of GCC are you using / do you recommend? I've been using 4.6.3. Someone else using 4.7 has had not been able to get any builds to run.

**Comment by popcornmix** [comment]
I use this:
https://github.com/raspberrypi/tools/tree/master/arm-bcm2708/linux-x86

**Comment by keylevel** [comment]
Thanks. I've tried building using the same version as that (4.5.1), but still no luck. Is this toolchain based on a clean 4.5.1, or are there patches as well? I didn't spot a source tree, so it looks as it it's unmodified ?

**Comment by keylevel** [comment]
Looks like this is down to compression.

Compressed images sometimes work (most recent commit does), some don't.

Uncompressed images always work.

**Comment by keylevel** [comment]
Fixes to restore booting of compressed images have solved this. Thanks ;-)
