### ISSUE TITLE
Enable ARM-specific crypto modules

### ISSUE THREAD

**Issue by jplitza** [raspberrypi/linux#430]
Please set the kernel options

```
CONFIG_CRYPTO_AES_ARM=m
CONFIG_CRYPTO_SHA1_ARM=m
```

These enable implementations of the algorithms that use ARM assembler and are quite a bit faster than the stock C versions. They accelerated encryption-heavy tasks by factor 1.5 in [my short tests](https://blog.jplitza.de/2013/09/15/aes-arm-and-sha1-arm-for-kernel-3-6/).

**Comment by popcornmix** [comment]
SHA1_ARM was already in. I've added AES_ARM too.
Should be in latest rpi-update kernel.

**Comment by jplitza** [comment]
That was fast, thanks! Just ran rpi-update and got it, works as expected.

SHA1_ARM wasn't in a week ago (when I last updated), but was added 5 days ago in raspberrypi/firmware@452637c3 - should have updated right before posting the issue, sorry.

Anyway, issue can be closed in my opinion.

**Comment by popcornmix** [comment]
Thanks for the suggestion!
