### ISSUE TITLE
Jack connector audio on Pi4 with vc4hdmi ALSA device

### ISSUE THREAD

**Issue by vanfanel** [raspberrypi/linux#4332]
Hi,

Using Pi4 with the KMS overlay:
`dtoverlay=vc4-kms-v3d`

..and the vc4hdmi ALSA device (ie: NO bcm2835 audio module loaded):
`#dtparam=audio=on` <---Commented out line.

I have very good audio (and low-latency capable) via the vc4hdmi ALSA device, vs the old, laggy, not-working-with-small-buffers BCM audio. I won't be caught dead going back to the BCM stuff.

So, my question is very simple:
**Is it possible to have JACK connector audio without the BCM2835 module? In other words, is it possible to have JACK connector audio using the arm-side audio stack, be it via vc4hdmi or with another method?**
If so, how?

Thanks!

**Comment by pelwell** [comment]
The short answer is no - you need the bcm2835 audio module in order to send the streams to the VPU. One _could_ drive the PWM output using a custom driver running on the ARMs, but doing so would lose out on the SDM magic the firmware performs, and you really don't want that.

**Comment by vanfanel** [comment]
@pelwell Ah, thanks. Clear and good response, just what I needed :)

**Comment by popcornmix** [comment]
Note `dtparam=audio=on` when using the vc4 driver will only enable the firmware driver for the analogue jack.
The firmware driver for hdmi is automatically disabled when using vc4, which I believe is the behaviour you want.
