### ISSUE TITLE
no camera at 3.12

### ISSUE THREAD

**Issue by oklitz** [raspberrypi/linux#434]
Hello !

When I boot with 3.12 dmesg:
[ 0.000000] vc_cma: dma_declare_contiguous(11800000,d400000) failed

and raspivid says:

mmal: mmal_vc_component_enable: failed to enable component: ENOSPC
mmal: camera component couldn't be enabled
mmal: main: Failed to create camera component
mmal: Failed to run camera app. Please check for firmware updates

when i'm running 3.10.18 its all OK !
just changing the kernel, and no changes on config files

need more info ?

mfg Marco Oklitz

**Comment by crashmaster1** [comment]
Hello Marco,
i agree. 
Never before the cam has worked with _experimental_ kernel versions (not only 3.12).
3.10.18 comes from the _official_ branch, this works.
I would also appreciate to see it working with the latest test versions . ;)
greets, cm1

**Comment by JamesH65** [comment]
Weird. Never seen problems like this - are you using any odd HW attached to your PI's?

**Comment by moonman** [comment]
The important clue is this line: [ 0.000000] vc_cma: dma_declare_contiguous(11800000,d400000) failed

XBMC does not start because of this too.

**Comment by crashmaster1** [comment]
I only use wlan (8192cu) and raspicam on Model A but nothing else.

And i want to mention:
The RPi has two i2c busses, the cam works with <b>bus 0</b> but "i2cdetect -y 0" shows:

<pre>
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          03 04 05 06 07 08 09 0a 0b 0c 0d 0e 0f 
10: 10 11 12 13 14 15 16 17 18 19 1a 1b 1c 1d 1e 1f 
20: 20 21 22 23 24 25 26 27 28 29 2a 2b 2c 2d 2e 2f 
30: 30 31 32 33 34 35 36 37 38 39 3a 3b 3c 3d 3e 3f
40: 40 41 42 43 44 45 46 47 48 49 4a 4b 4c 4d 4e 4f 
50: 50 51 52 53 54 55 56 57 58 59 5a 5b 5c 5d 5e 5f 
60: 60 61 62 63 64 65 66 67 68 69 6a 6b 6c 6d 6e 6f 
70: 70 71 72 73 74 75 76 77
</pre>

Very strange !

There should be lots of dashes like on <b>bus 1</b> (i2cdetect -y 1):

<pre>
      0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- -- 
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
70: -- -- -- -- -- -- -- --
</pre>

**Comment by crashmaster1** [comment]
It's me again ;) 
I spent some time to find this bug now.

1wire (w1_gpio) in kernel versions >= 3.10 destroys the bus 0 structure of i2c (see my comment above).
This is a reason why raspicam doesn't work. If you don't need 1wire don't load this module and it will work fine. I opened a new thread for this.

@Marco:
I guess you don't use 1wire and don't load the modules, so this is not your problem.
But check your config.txt. I commented:

<pre>
# cma_lwm=...
# cma_hwm=...
# cma_offline_start=...
</pre>

Now i have no "vc_cma: dma_declare_contiguous(11800000,d400000) failed" anymore and the cam works fine!

**Comment by JamesH65** [comment]
Dom, I've assigned this to you - bit out of my realm of expertise.

**Comment by popcornmix** [comment]
I believe this is resolved now. Reopen if needed.
