### ISSUE TITLE
Missing IPSEC modules

### ISSUE THREAD

**Issue by gstreeter** [raspberrypi/linux#441]
The kernel does not currently have the modules needed to utilise additional IPSEC encryption ciphers and modes beyond the basic AES-CBC. This means that IPSEC connections cannot be created to nodes using more advanced features and ciphers such as counter (CTR) mode. Please enable the following modules in the Cryptographic API Section of the menuconfig parameters to allow additional IPSEC interoperability:

CCM Support
GCM/GMAC Support 
CTR Support
Blowfish cipher algorithm 
Camellia cipher algorithm
Serpent cipher algorithm
Twofish cipher algorithm 
ZLIB compression algorithm 
LZO compression algorithm

**Comment by P33M** [comment]
What is the use case that requires these options?

**Comment by Ruffio** [comment]
@popcornmix please consider closing this issue, as there haven't been any response for the question asked 14 Jul 2015.
