### ISSUE TITLE
Install openjdk on aarch64

### ISSUE THREAD

**Issue by AliaChe** [raspberrypi/linux#4445]
Hey all,

I'm trying to install openjdk-11-jdk on an aarch64/ubuntu:focal (ros foxy) docker image using :

`$ sudo apt update && sudo apt install -y --no-install-recommends openjdk-11-jdk`

Errors were encountered while processing:
 ca-certificates-java

The error is :
```
cannot open '/etc/ssl/certs/java/cacerts' for reading
INFO:Docker Client:: No such file or directory
```

Any ideas? 

Thanks

**Comment by JamesH65** [comment]
Please use the forums for this sort of question. www.raspberrypi.org/forums
