### ISSUE TITLE
IFB module is missing

### ISSUE THREAD

**Issue by ktsaou** [raspberrypi/linux#445]
IFB devices are used for classfull QoS on ingress (download direction).

Check this: https://github.com/ktsaou/firehol/wiki/FireQOS-Tutorial

It would be great if you could add this as a module on the standard kernel for Pi.

**Comment by popcornmix** [comment]
Added in latest firmware. Please run rpi-update and test.

**Comment by ktsaou** [comment]
perfect. It works.
Thank you very much.
