### ISSUE TITLE
Kernel crash on boot with 20210727 update

### ISSUE THREAD

**Issue by mgrouch** [raspberrypi/linux#4491]
Kernel crash on boot with 20210727 update  
attaching a screenshot 

![D5D796B8-E1E3-4D3A-978D-CD4FAF3A5481](https://user-images.githubusercontent.com/8263013/127672444-7ccf1aab-ff4d-43b7-9a9f-5cf64ae174ee.jpeg)

**Comment by popcornmix** [comment]
What do you mean by 20210727 update? Is this from rpi-update? On RPiOS (32-bit buster)?
Can you post contents of your config.txt and cmdline.txt?

**Comment by pelwell** [comment]
Possibly related to https://github.com/raspberrypi/linux/issues/4490. Will respond there for now.

**Comment by mgrouch** [comment]
Yes. Duplicate then
