### ISSUE TITLE
Unable to find source for rasperrypi firmware blobs for bluetooth

### ISSUE THREAD

**Issue by benjumanji** [raspberrypi/linux#4508]
Hi, 

I am using buildroot to produce an image for an rpi3b+. I need bluetooth to function. I have taken the patches for bluez 5.55 from the source packge. The only way I have found to get the bluez stack to function is to copy the firmware blobs out of an raspberrypi os image. This isn't great. I have tried to discover what package covers these blobs: 

```
pi@raspberrypi:~$ dpkg -S /lib/firmware/brcm/BCM4345C0.hcd
bluez-firmware: /lib/firmware/brcm/BCM4345C0.hcd
```

Ok... so bluez firmware it is. If you pull that package, those files are not contained in it, so what's going on?

```
 ❯ ls lib/firmware/
BCM2033-FW.bin  BCM2033-MD.hex  STLC2500_R4_00_03.ptc  STLC2500_R4_00_06.ssf  STLC2500_R4_02_02_WLAN.ssf  STLC2500_R4_02_04.ptc
```

What's weird is if I query apt about this package I get two records:

```
pi@raspberrypi:~$ apt show bluez-firmware -a
Package: bluez-firmware
Version: 1.2-4+rpt8
Priority: optional
Section: non-free/kernel
Maintainer: Debian Bluetooth Maintainers <team+pkg-bluetooth@tracker.debian.org>
Installed-Size: 332 kB
Download-Size: 175 kB
APT-Manual-Installed: no
APT-Sources: http://archive.raspberrypi.org/debian buster/main armhf Packages
Description: Firmware for Bluetooth devices
 This firmware is required for operation of Bluetooth dongles based on
 the Broadcom BCM203x chipset.

Package: bluez-firmware
Version: 1.2-4
Priority: optional
Section: non-free/kernel
Maintainer: Debian Bluetooth Maintainers <team+pkg-bluetooth@tracker.debian.org>
Installed-Size: 143 kB
Download-Size: 64.9 kB
APT-Sources: http://raspbian.raspberrypi.org/raspbian buster/non-free armhf Packages
Description: Firmware for Bluetooth devices
 This firmware is required for operation of Bluetooth dongles based on
 the Broadcom BCM203x chipset.
 ```
 
 The second one seems to correspond to what's available in the package repo. Where is the second one located? Does that have the file I want? I am very confused.

**Comment by asavah** [comment]
See https://github.com/RPi-Distro/bluez-firmware 

> What's weird is if I query apt about this package I get two records:

1.2-4+rpt8 (the first one) is the one that gets installed on the pis, it's RPF/RPT/RPWHATEVER vendored package which has preference and which contains the blobs you are looking for. http://archive.raspberrypi.org/debian/pool/main/b/bluez-firmware/

The latter is a generic raspbian package which does not contain the blobs.

**Comment by benjumanji** [comment]
Thank you so much! Problem solved.

I see what was throwing me off: the second package is in non-free which is where I was looking, the first is in main where I was not looking.
