### ISSUE TITLE
Kernel panic after upgrade to 5.10.17

### ISSUE THREAD

**Issue by sakos** [raspberrypi/linux#4509]
**Short description:**
Kernel panic shortly after installing Raspberry Pi OS Lite and configuring Wifi.

**Detailed description:**
I run an irrigation system on Raspberry Pi Zero W v1.1. I had to reinstall the system after an SD card corruption. I downloaded and installed latest Raspberry Pi OS Lite (May 7th 2021). Some seconds after configuring wifi with raspi-config, the system crashes with kernel panic.
The system cannot reboot anymore as the same kernel panic happens during the boot.

**Reproduction steps:**
- download, extract and write the Raspberry Pi OS Lite image file to an SD card
- Install the SD card and power up the RPi
- login
- run raspi-config
- configure wifi access (region HU if matters)
- exit raspi-config
- wait less than 30 seconds
- kernel panic happens

- power cycle the RPi
- boot cannot complete due to kernel panic

**Reproduction rate:**
10/10

**Expected behavior:**
System is stable

**Actual behavior:**
Severe fault. The system crashes during boot. No workaround or recovery

**Additional info:**
This issue reminds me to https://github.com/raspberrypi/linux/issues/3948. However this cannot be a hardware fault.
My system works like a charm with older Raspberry Pi OS Lite **(May 27th 2020)** Linux kernel 4.19.118

**System:**
Raspberry Pi Zero W v1.1
Raspberry Pi OS Lite (May 7th 2021)
Wifi router: ASUS RT-AC65P, Firmware OpenWrt SNAPSHOT r12173-01c8f2e97c / LuCI Master git-20.035.20355-1edb551

**Logs:**
https://photos.app.goo.gl/c6pPGjZfCAREw7816

**Comment by kralo** [comment]
What is the text of the kernel panic? Your 'logs' link is dead.

**Comment by sakos** [comment]
It seems that the screenshot is accidentally deleted. I neither can recall how did overcome the problem.
Due to lack of information the ticket can be closed.
