### ISSUE TITLE
[Kernel 3.11 and 3.12] drivers/bus/arm-cci.c issue

### ISSUE THREAD

**Issue by dragon28** [raspberrypi/linux#452]
Hello Developer,

Having issue with drivers/bus/arm-cci.c:

drivers/bus/arm-cci.c: In function 'cci_probe':
drivers/bus/arm-cci.c:402:49: warning: dereferencing 'void _' pointer [enabled by default]
drivers/bus/arm-cci.c:402:49: error: request for member 'data' in something not a structure or union
make[2]: *_\* [drivers/bus/arm-cci.o] Error 1
make[1]: **\* [drivers/bus] Error 2
make: **\* [drivers] Error 2

Previously, it were:

drivers/bus/arm-cci.c: In function 'cci_probe':
drivers/bus/arm-cci.c:398:2: error: implicit declaration of function 'of_find_matching_node' [-Werror=implicit-function-declaration]
drivers/bus/arm-cci.c:398:5: warning: assignment makes pointer from integer without a cast [enabled by default]
drivers/bus/arm-cci.c:402:49: warning: dereferencing 'void _' pointer [enabled by default]
drivers/bus/arm-cci.c:402:49: error: request for member 'data' in something not a structure or union
cc1: some warnings being treated as errors
make[2]: *_\* [drivers/bus/arm-cci.o] Error 1
make[1]: **\* [drivers/bus] Error 2
make: **\* [drivers] Error 2

but it was fixed at:

http://www.spinics.net/lists/devicetree/msg08072.html

**Comment by popcornmix** [comment]
Have you enabled ARM_CCI? What is it enabled for?

**Comment by dragon28** [comment]
Hello Dev :)

Yes, I have enable ARM_CCI

ARM_CCI :

ARM multi-cluster systems rely on the cache coherent interconnect (CCI) to
support inter-cluster cache coherency and distributed virtual memory (DVM)
messaging.

CCI kernel driver requires tweaks to the kernel and device tree
bindings in order to link specific resources to groups of logical CPUs
so that resources can be associated to specific cpu sets (slave ports can
be associated with a set of CPUs which are part of a cluster).

ARM DT topology bindings [1] allow one to describe the hierarchy of CPUs in the
system. Cache Coherent Interconnect CCI is by definition a consumer of
topology bindings in that CCI slave ports must be associated with specific
bus masters in the system so that whenever a CCI operation is requested for
a specific master (ie disable its CCI slave port, read its PMU counters) the
association can be carried out dynamically in the OS through dynamically
built data structures.

The CCI driver provides an example of how to use the newly introduced bindings
and is meant to kickstart discussion on the best way to deploy them on
forthcoming ARM systems.

The current CCI DT bindings define the CCI address space as the same one
as the root device tree node, which means that the CCI bus can address the
entire address space visible to CPUs.

You could refer to:

http://lwn.net/Articles/547432/

:)

**Comment by popcornmix** [comment]
But does it make any sense on the Pi with a single ARM core?

**Comment by dragon28** [comment]
-.-''''''''''''''''''

It just for testing :D

Any plan for fixing it? 

:)

**Comment by dragon28** [comment]
I just close this one issue and hope the dev able to provide support and hoping we can use this feature in the future :)

**Comment by popcornmix** [comment]
If it's not critical, I'll wait for the upstream fix. Seems likely it will be fixed in next 3.11/3.12 bump.
