### ISSUE TITLE
raspberry pi 4 doesn"t read sd card

### ISSUE THREAD

**Issue by raidhu** [raspberrypi/linux#4528]
last four month in using raspberry pi 4 board, yesterday when I turn on the power supply to pi 4 it doesn't connect to WIFI  (by the way I'm installed ubuntu 16.04 OS in pi) I tried it multiple time but it never work so i uninstalled the OS and reinstall it and boot the pi but this time it doesn't even boot.

red light was in constant and green light blinks three time in every 1 seconds.

can any one help me to solve this problem is this hardware issue or software issue.

SD card works properly.

**Comment by popcornmix** [comment]
This repo is for reporting bugs in the linux kernel, which this doesn't sound like. 
I'd suggest asking this in the [forums](https://www.raspberrypi.org/forums/)
