### ISSUE TITLE
Please add ifb as a module (CONFIG_IFB=m)

### ISSUE THREAD

**Issue by jovermann** [raspberrypi/linux#453]
I would kindly like to ask you to enable the intermediate functional block, ifb, as a module in the default kernel config for the Pi:
CONFIG_IFB=m

It is currently disabled in the 3.10.18+ kernel.

It should not hurt anyone as it is just a module. The ifb network device is quite useful when doing experiments with tc (trafficx control), and it is absolutely necessary when you want to affect incoming traffic (normal tc netem works only on outgoing packets)

http://www.linuxfoundation.org/collaborate/workgroups/networking/netem#How_can_I_use_netem_on_incoming_traffic.3F

Thanks a lot!
Cheers,
Johannes

**Comment by popcornmix** [comment]
It's added to linux source:
https://github.com/raspberrypi/linux/commit/57d2b3afe0fb757c9a3109772fc57510ac07ac90
Just rebuild binary firmware.

**Comment by popcornmix** [comment]
Added in latest firmware. Please run rpi-update and test.

**Comment by jovermann** [comment]
Hi popcornmix,

thanks a lot! You rock! This works now! I can happily modprobe ifbs and configure them!

Thanks for the ultra fast and most helpful response!

Cheers,
Johannes

Am 02.12.2013 um 18:12 schrieb popcornmix:

> Added in latest firmware. Please run rpi-update and test.
> 
> —
> Reply to this email directly or view it on GitHub.

## 

Johannes.Overmann@gmx.de (http://overmann-consulting.de)
