### ISSUE TITLE
Display goes black with kernel error "MMU error from client CLE (4) at 0xb0e1000, pte invalid"

### ISSUE THREAD

**Issue by anyc** [raspberrypi/linux#4549]
When running Stepmania (GL game) on a RPi4 with kernel 5.10.52 (1.20210805), after about 10-15 minutes of playtime the screen goes black. The X server and the game process are still there but there is no display. The only log entry is:

[  902.458724] v3d fec00000.v3d: MMU error from client CLE (4) at 0xb0e1000, pte invalid

When I restart the game, the display comes back.

This is a custom Linux system with Mesa 20.1.4 and Xorg 1.20.8, RPi firmware 1.20210805. Thank you!

**Comment by anyc** [comment]
I found a related forum thread but there was no real solution posted: https://www.raspberrypi.org/forums/viewtopic.php?t=277917

**Comment by popcornmix** [comment]
Are you sure the MMU error and screen going black occur at the same time?
The MMU error is believed so be harmless (and quite common), so it's appearance may be coincidental.

**Comment by anyc** [comment]
Looks like you are right, I couldn't reproduce it. Thank you!
