### ISSUE TITLE
Please add bcache as a module (CONFIG_BCACHE=m)

### ISSUE THREAD

**Issue by TimeZlicer** [raspberrypi/linux#455]
drivers/md/bcache/Kconfig
config BCACHE

Motivation:
To use SD card or USB flash backed with a spinning HDD
To achieve seek performance of flash and size abundance of HDD
(and maybe better power consumption, more spin down time for HDD)

Thanks in advance!

**Comment by popcornmix** [comment]
Should be in now.
Please run rpi-update and test.
