### ISSUE TITLE
request taking patch on standard raspbian kernel

### ISSUE THREAD

**Issue by dingo35** [raspberrypi/linux#456]
Hi all,

First of all big thanks to all Raspbian maintainers who provide such a beautiful OS for us all!

I was wondering whether it would be a good idea to have this patch http://everpi.tsar.in/2013/11/patch-para-controlar-os-leds-ethernet-do-raspberrypi.html included in future Raspbian images?

It would help newbies in giving them control on the Raspi LEDs, one of the most innocent experiments a young learner could do. It opens up possibilities to driving all those leds with scripts, seducing them on programming.

On the other hand I suppose we want to keep the number of Raspi-specific patches as low as possible.

Any thoughts from the Raspbian image maintainers?

**Comment by asb** [comment]
As the current Raspbian image maintainer, I'm only going to include the standard kernel as built by Dom and shared in the raspberrypi/firmware repo. The OK LED is already controllable from software so pi users can write a first 'blinky' program with no external components that way. Though I suppose controlling the other LEDs could be fun also.

**Comment by P33M** [comment]
The LEDs aside from PWR and ACT/OK are actually controlled by the SMSC LAN9512 chip.

In normal operation they reflect the state of the ethernet controller as you would expect - LAN activity, link status, 100Mbit operation.

Technically they are just basic GPIO pins - which that blog post presumably describes how to twiddle to turn into GPIO-controlled LEDs. The implementation is sorely lacking in robustness, however.

There are better ways to do this. The OK LED is perfectly accessible - and there are multiple examples of using an LED attached to a GPIO pin on P1 that suffice.

There are 5 more generic GPIO pins on the SMSC chip (that are not connected) aside from the LED pins. If they REALLY want to poke an LED, then they have to solder stuff to an 0.5mm pad on the Pi.

**Comment by dingo35** [comment]
The OK LED is OT in this thread.

Which "better ways to do this" would you suggest? I have some code in userspace that would not require any patching, but this code is not working (reporting "busy" on writing to the 9512 chip's register, even when unloading the sms95xx kernel module).

**Comment by popcornmix** [comment]
I don't believe the limited benefit of this patch outways the maintenance cost of an out of tree patch, and the possible stability risk.
If you think this is useful to a significant number of people, then submit the patch to the upstream linux tree, where people who know the code better can comment.
If it is accepted there, I'll pull it in here.

**Comment by popcornmix** [comment]
Closing. Let me know if this appears upstream and we can pull it in.
