### ISSUE TITLE
Can you please add Toneport UX1 Line 6 driver (USB soundcard) into kernel?

### ISSUE THREAD

**Issue by Mikka123T** [raspberrypi/linux#4562]
Can you please add Toneport UX1 Line 6 driver (USB soundcard) into kernel?

This is the config change that I need to apply before I recompile kernel with required drivers. 

sed -ri "/CONFIG_SND_USB_TONEPORT/ { s/# (\w+).*/\1=m/; i CONFIG_SND_USB_LINE6=m
}" .config

Thank you

**Comment by pelwell** [comment]
Sure - see https://github.com/raspberrypi/linux/commit/1c384f032011fe012db04802c09c3b0437d92215.

**Comment by Mikka123T** [comment]
That was quick :-), thanks a lot
