### ISSUE TITLE
[module request] Enable Peak CAN USB

### ISSUE THREAD

**Issue by schultetwin** [raspberrypi/linux#4583]
Hi Raspberry Pi kernel maintainers. I would like to set `CONFIG_CAN_PEAK_USB=m` in the default kernel config to allow PEAK CAN usb devices to be installed on a raspberry pi and used out of the box.

I'm unsure what the policy is on requesting specific modules to be enabled, and understand this increases code size slightly. However, given this is a USB device, I hope we can get support for it in the raspberry pi kernel.

Happy to open a pull request with this change if that helps!

**Comment by pelwell** [comment]
Sure - see https://github.com/raspberrypi/linux/commit/27f5c22ebb463ebd43ab246e671854197bda4b05.

The module will appear in future kernel releases.

**Comment by schultetwin** [comment]
Thank you!
