### ISSUE TITLE
Raspian mount issue

### ISSUE THREAD

**Issue by symbios24** [raspberrypi/linux#4589]
Hello
I currently have an issue with latest raspbian in a Raspberry pi 4
In first boot it auto mounts usb flash drives in the second or third boot stops auto mount any incerted flash drives if i incert a flash drive and press open in the dialog that says open with file manager then i get an error that the directory /media/pi/disk/ is not valid

**Comment by XECDesign** [comment]
Since it's unlikely to be a linux kernel issue, it should probably be reported here: https://github.com/RPi-Distro/repo/issues/

@spl237
