### ISSUE TITLE
Problems pulling master

### ISSUE THREAD

**Issue by sjau** [raspberrypi/linux#46]
Hi there

I have a problem with this repo. First I clone it locally:

root@debian:/usr/local/src/raspi.orig# git clone https://github.com/raspberrypi/linux.gitCloning into linux...
remote: Counting objects: 2275163, done.
remote: Compressing objects: 100% (354613/354613), done.
remote: Total 2275163 (delta 1901476), reused 2268622 (delta 1898739)
Receiving objects: 100% (2275163/2275163), 465.59 MiB | 1.13 MiB/s, done.
Resolving deltas: 100% (1901476/1901476), done.
root@debian:/usr/local/src/raspi.orig# cd linux
root@debian:/usr/local/src/raspi.orig/linux# git pull origin master
From https://github.com/raspberrypi/linux
- branch            master     -> FETCH_HEAD
  warning: too many files (created: 2074 deleted: 1981), skipping inexact rename detection

[.... long list of stuff .... }

CONFLICT (content): Merge conflict in net/sched/sch_teql.c
Auto-merging net/sctp/associola.c
Auto-merging net/sctp/outqueue.c
Auto-merging net/sctp/protocol.c
Auto-merging net/sctp/socket.c
Auto-merging net/sunrpc/auth_gss/auth_gss.c
Auto-merging net/sunrpc/rpc_pipe.c
Auto-merging net/sunrpc/xprtsock.c
Auto-merging net/wireless/nl80211.c
Auto-merging net/wireless/reg.c
Auto-merging net/xfrm/xfrm_policy.c
Auto-merging scripts/kconfig/menu.c
CONFLICT (content): Merge conflict in scripts/kconfig/menu.c
Removing security/integrity/ima/ima_iint.c
Removing security/keys/encrypted.c
Removing security/keys/encrypted.h
Auto-merging security/tomoyo/realpath.c
Removing sound/pci/hda/alc268_quirks.c
CONFLICT (delete/modify): sound/pci/hda/alc269_quirks.c deleted in 645fd9b0c0b3c1f79f71f92dac79bd2f87010444 and modified in HEAD. Version HEAD of sound/pci/hda/alc269_quirks.c left in tree.
Removing sound/pci/hda/alc662_quirks.c
Removing sound/pci/hda/alc680_quirks.c
Removing sound/pci/hda/alc861_quirks.c
Removing sound/pci/hda/alc861vd_quirks.c
Auto-merging sound/pci/hda/hda_codec.c
CONFLICT (content): Merge conflict in sound/pci/hda/hda_codec.c
Auto-merging sound/pci/hda/hda_eld.c
CONFLICT (content): Merge conflict in sound/pci/hda/hda_eld.c
Auto-merging sound/pci/hda/hda_intel.c
Auto-merging sound/pci/hda/patch_cirrus.c
Auto-merging sound/pci/hda/patch_conexant.c
CONFLICT (content): Merge conflict in sound/pci/hda/patch_conexant.c
Auto-merging sound/pci/hda/patch_hdmi.c
CONFLICT (content): Merge conflict in sound/pci/hda/patch_hdmi.c
Auto-merging sound/pci/hda/patch_realtek.c
CONFLICT (content): Merge conflict in sound/pci/hda/patch_realtek.c
Auto-merging sound/pci/hda/patch_sigmatel.c
CONFLICT (content): Merge conflict in sound/pci/hda/patch_sigmatel.c
Auto-merging sound/pci/hda/patch_via.c
Auto-merging sound/pci/lx6464es/lx_core.c
Auto-merging sound/pci/sis7019.c
Removing sound/soc/atmel/playpaq_wm8510.c
Removing sound/soc/codecs/ads117x.h
Auto-merging sound/soc/codecs/ak4535.c
CONFLICT (content): Merge conflict in sound/soc/codecs/ak4535.c
Auto-merging sound/soc/codecs/ak4642.c
CONFLICT (content): Merge conflict in sound/soc/codecs/ak4642.c
Auto-merging sound/soc/codecs/sta32x.c
Auto-merging sound/soc/codecs/wm8711.c
Auto-merging sound/soc/codecs/wm8731.c
Auto-merging sound/soc/codecs/wm8741.c
Auto-merging sound/soc/codecs/wm8753.c
Auto-merging sound/soc/codecs/wm8904.c
Auto-merging sound/soc/codecs/wm8940.c
Auto-merging sound/soc/codecs/wm8962.c
Auto-merging sound/soc/codecs/wm8994.c
Auto-merging sound/soc/codecs/wm8996.c
Auto-merging sound/soc/fsl/fsl_ssi.c
Removing sound/soc/omap/mcpdm.c
Removing sound/soc/omap/mcpdm.h
Auto-merging sound/soc/soc-utils.c
Auto-merging sound/usb/misc/ua101.c
Auto-merging sound/usb/mixer.c
CONFLICT (content): Merge conflict in sound/usb/mixer.c
Removing sound/usb/urb.c
Removing sound/usb/urb.h
Auto-merging tools/perf/util/trace-event-parse.c
Removing tools/perf/util/ui/browsers/top.c
Automatic merge failed; fix conflicts and then commit the result.
root@debian:/usr/local/src/raspi.orig/linux#

**Comment by popcornmix** [comment]
Sounds like you've got something unwated in the your local linux directory. Can you try removing it first, or cloning from a different directory?

**Comment by sjau** [comment]
it was done on an empty dir

if it was not empty, then git clone would already have complained about the dir existing.

**Comment by popcornmix** [comment]
I've just tried 
git clone https://github.com/raspberrypi/linux.git
and it completed happily. Can you try on a different machine. I think you have git setup problem.

**Comment by sjau** [comment]
clone works

now go into the linux folder and issue:

git pull origin master

**Comment by popcornmix** [comment]
I'm not a git expert, but are you sure that's a sensible command to do?
If you want the latest code, then "git pull" or "git pull --rebase" would be advised.
I believe your command will merge the branches rpi_patches and master together.

**Comment by sjau** [comment]
I've always used git pull origin master :) anyway, it seems I can't cross compile the kernel from debian :(
