### ISSUE TITLE
An error occured when emerge 

### ISSUE THREAD

**Issue by atykhonov** [raspberrypi/linux#460]
I got following error while emerge `emerge -av sys-kernel/raspberrypi-sources`

> > > /usr/src/linux-3.6.11-raspberrypi-r20130711/init/do_mounts_md.c
> > > /usr/src/linux-3.6.11-raspberrypi-r20130711/init/Kconfig
> > > /usr/src/linux-3.6.11-raspberrypi-r20130711/init/init_task.c
> > > /usr/src/linux-3.6.11-raspberrypi-r20130711/init/do_mounts.h
> > > /usr/src/linux-3.6.11-raspberrypi-r20130711/CREDITS
> > > Safely unmerging already-installed instance...
> > > Traceback (most recent call last):
> > >   File "/usr/lib/portage/pym/portage/dbapi/vartree.py", line 1947, in unmerge
> > >     phase.start()
> > >   File "/usr/lib/portage/pym/_emerge/AsynchronousTask.py", line 30, in start
> > >     self._start()
> > >   File "/usr/lib/portage/pym/_emerge/EbuildPhase.py", line 127, in _start
> > >     self._start_task(env_extractor, self._env_extractor_exit)
> > >   File "/usr/lib/portage/pym/_emerge/CompositeTask.py", line 151, in _start_task
> > >     task.start()
> > >   File "/usr/lib/portage/pym/_emerge/AsynchronousTask.py", line 30, in start
> > >     self._start()
> > >   File "/usr/lib/portage/pym/_emerge/BinpkgEnvExtractor.py", line 43, in _start
> > >     self._start_task(extractor_proc, self._extractor_exit)
> > >   File "/usr/lib/portage/pym/_emerge/CompositeTask.py", line 151, in _start_task
> > >     task.start()
> > >   File "/usr/lib/portage/pym/_emerge/AsynchronousTask.py", line 30, in start
> > >     self._start()
> > >   File "/usr/lib/portage/pym/_emerge/SpawnProcess.py", line 106, in _start
> > >     retval = self._spawn(self.args, *_kwargs)
> > >   File "/usr/lib/portage/pym/_emerge/SpawnProcess.py", line 163, in _spawn
> > >     return spawn_func(args, *_kwargs)
> > >   File "/usr/lib/portage/pym/portage/process.py", line 310, in spawn
> > >     pid = os.fork()
> > >   File "/usr/lib/portage/pym/portage/__init__.py", line 259, in **call**
> > >     rval = self._func(_wrapped_args, *_wrapped_kwargs)
> > > OSError: [Errno 12] Cannot allocate memory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/portage/pym/portage/dbapi/_MergeProcess.py", line 234, in _spawn
    prev_mtimes=self.prev_mtimes, counter=counter)
  File "/usr/lib/portage/pym/portage/dbapi/vartree.py", line 4839, in merge
    counter=counter)
  File "/usr/lib/portage/pym/portage/dbapi/vartree.py", line 4130, in treewalk
    preserve_paths=preserve_paths)
  File "/usr/lib/portage/pym/portage/dbapi/vartree.py", line 2030, in unmerge
    phase.start()
  File "/usr/lib/portage/pym/_emerge/AsynchronousTask.py", line 30, in start
    self._start()
  File "/usr/lib/portage/pym/_emerge/EbuildPhase.py", line 132, in _start
    self._start_lock()
  File "/usr/lib/portage/pym/_emerge/EbuildPhase.py", line 152, in _start_lock
    self._start_ebuild()
  File "/usr/lib/portage/pym/_emerge/EbuildPhase.py", line 184, in _start_ebuild
    self._start_task(ebuild_process, self._ebuild_exit)
  File "/usr/lib/portage/pym/_emerge/CompositeTask.py", line 151, in _start_task
    task.start()
  File "/usr/lib/portage/pym/_emerge/AsynchronousTask.py", line 30, in start
    self._start()
  File "/usr/lib/portage/pym/_emerge/AbstractEbuildProcess.py", line 145, in _start
    SpawnProcess._start(self)
  File "/usr/lib/portage/pym/_emerge/SpawnProcess.py", line 106, in _start
    retval = self._spawn(self.args, *_kwargs)
  File "/usr/lib/portage/pym/_emerge/EbuildProcess.py", line 25, in _spawn
    actionmap=actionmap, *_kwargs)
  File "/usr/lib/portage/pym/portage/package/ebuild/doebuild.py", line 157, in _doebuild_spawn
    return spawn(cmd, settings, *_portage._native_kwargs(kwargs))
  File "/usr/lib/portage/pym/portage/package/ebuild/doebuild.py", line 1571, in spawn
    *_portage._native_kwargs(keywords))
  File "/usr/lib/portage/pym/portage/process.py", line 115, in spawn_bash
    return spawn(args, opt_name=opt_name, **keywords)
  File "/usr/lib/portage/pym/portage/process.py", line 310, in spawn
    pid = os.fork()
  File "/usr/lib/portage/pym/portage/__init__.py", line 259, in **call**
    rval = self._func(_wrapped_args, *_wrapped_kwargs)
OSError: [Errno 12] Cannot allocate memory

> > > Failed to install sys-kernel/raspberrypi-sources-3.6.11-r20130711, Log file:
> > > 
> > >  '/var/tmp/portage/sys-kernel/raspberrypi-sources-3.6.11-r20130711/temp/build.log'
- GNU info directory index is up-to-date.
- IMPORTANT: 6 news items need reading for repository 'gentoo'.
- Use eselect news to read news items.

localhost / #

About memory on the device:

localhost / # df
Filesystem     1K-blocks    Used Available Use% Mounted on
rootfs           7306400 2268144   4644068  33% /
/dev/root        7306400 2268144   4644068  33% /
devtmpfs          215848       0    215848   0% /dev
tmpfs              44824     204     44620   1% /run
shm               224112       0    224112   0% /dev/shm
cgroup_root

From `top`:

top - 01:02:21 up  9:00,  1 user,  load average: 0.00, 0.02, 0.13
Tasks:  49 total,   1 running,  48 sleeping,   0 stopped,   0 zombie
%Cpu(s): 37.3 us,  4.9 sy,  0.0 ni, 55.5 id,  2.1 wa,  0.1 hi,  0.2 si,  0.0 st
KiB Mem:    448224 total,    94912 used,   353312 free,    25192 buffers
KiB Swap:   102396 total,      432 used,   101964 free,    19892 cached

**Comment by kripton** [comment]
Did you report on http://bugs.gentoo.org ?
These error messages have nothing to do with the linux kernel provided here but are Gentoo specific.

**Comment by kripton** [comment]
And reading your post more closely it looks like emerge simply ran out of memory. Do you use a swap partition/file on your Pi? Could you enable one?

**Comment by popcornmix** [comment]
Setting gpu_mem=16 in config.txt will allow more memory for the ARM.
But otherwise, this doesn't look a linux kernel issue.

**Comment by atykhonov** [comment]
Thank you guys! That was error due to small swap partition.
Thank you!
