### ISSUE TITLE
Untagged release: 1.20210831-3~buster

### ISSUE THREAD

**Issue by Ve2mrx** [raspberrypi/linux#4602]
The recently released package raspberrypi-kernel 1:1.20210831-3~buster isn't tagged here

**Expected behaviour**
To find a tagged release 1:1.20210831-3~buster

Secondary question: is there some sort of release_notes.txt for the kernel updates or I must look at commit history?

**Comment by XECDesign** [comment]
The tag to use is 1.20210831. Only the 'upstream' component of the version is used for tags because everything else only affects the packaging.

**Comment by Ve2mrx** [comment]
So, if I understand correctly, the difference between the raspberrypi-kernel 1:1.20210831-1 and 1:1.20210831-3~buster packages are not in the kernel itself but in packaging?

Edit: So it has no impact if installed from source?
Edit 2: Sorry, I meant 1.20210831-1/1.20210831-3, I would have removed the "1:" after looking at the tags

**Comment by XECDesign** [comment]
Yes, that's right. In this case, the vchiq udev rule was updated: https://github.com/RPi-Distro/repo/issues/264

**Comment by Ve2mrx** [comment]
Great, thanks! 
I've already installed the package with apt but I'm using a custom-built kernel installed in parallel and set in config.txt. I checked and I'm all set!

Thanks,
Martin
