### ISSUE TITLE
Raspberry pi 4 8gb not working 

### ISSUE THREAD

**Issue by FaresAbuIram** [raspberrypi/linux#4614]
The raspberry pi was working fine, then I install **ArduCAM** as this [link ](https://www.arducam.com/docs/arducam-obisp-mipi-camera-module/3-use-on-raspberry-pi/3-0-emergent-temporary-driver-for-the-lastest-rpi-2020-12-02-update/)
then I reboot the raspberry pi 

after that, this message appears on a black screen and doesn't work anymore 
`xhci_hcd 0000:01:00.0: can't setup: -110
xhci_hcd 0000:01:00.0: init 0000:01:00.0 fail, -110`

So, I need help !! :(

**Comment by 6by9** [comment]
Those instructions download a custom 5.4.79 kernel version, datestamped 10 December 2020. That is pretty old, and we're not supporting the 5.4 branch any longer.

You really need Arducam to do a release on a supported 5.10 kernel, or you may be able to build their drivers from source - https://github.com/ArduCAM/Arducam_OBISP_MIPI_Camera_Module

**Comment by FaresAbuIram** [comment]
@6by9 
I tried to download the new one, but it's the same problem ( black screen with `xhci_hcd 0000:01:00.0: can't setup: -110 xhci_hcd 0000:01:00.0: init 0000:01:00.0 fail, -110`

**Comment by FaresAbuIram** [comment]
@6by9  
Do you know how to solve ( black screen with `xhci_hcd 0000:01:00.0: can't setup: -110 xhci_hcd 0000:01:00.0: init 0000:01:00.0 fail, -110`) ?? maybe delete the last version or something else ?

**Comment by 6by9** [comment]
If it has actually booted and has a network connection, then ```sudo apt install --reinstall raspberrypi-kernel```.
If not, then reimage the SD card (you could try copying the relevant files from https://github.com/raspberrypi/firmware/tree/stable, but be prepared to totally reimage if you mess it up).

**Comment by FaresAbuIram** [comment]
@6by9  It's working thanks
about an Arducam (5.10 ), that needs to talk with the Arducam's team, right?

**Comment by 6by9** [comment]
> about an Arducam (5.10 ), that needs to talk with the Arducam's team, right?

You may be able to build it for yourself from https://github.com/ArduCAM/Arducam_OBISP_MIPI_Camera_Module
```
git clone https://github.com/ArduCAM/Arducam_OBISP_MIPI_Camera_Module
cd Arducam_OBISP_MIPI_Camera_Module
./build_driver.sh
```
When asked which branch you want to build from, you want rpi-5.10.y.

**Comment by FaresAbuIram** [comment]
There is only one branch "mater"

**Comment by FaresAbuIram** [comment]
![image](https://user-images.githubusercontent.com/51198097/135768572-450aec92-aedf-463f-b70a-d56b864231e1.png)

**Comment by FaresAbuIram** [comment]
I am using the last version of the kernel. 
![image](https://user-images.githubusercontent.com/51198097/135772115-7493caf5-73d0-4c6a-98cf-19a8002f2576.png)
![image](https://user-images.githubusercontent.com/51198097/135772351-05a5f475-b0c5-4e53-924e-499ece9c2dd5.png)

**Comment by FaresAbuIram** [comment]
I tried to add the last release here but nothing happened 
![image](https://user-images.githubusercontent.com/51198097/135773072-4b995db7-9706-401c-b568-7d2d156ab2a0.png)

but I don't know if these files should change their content or not !! 
![image](https://user-images.githubusercontent.com/51198097/135773129-c93c8a31-af86-4005-b5c4-2042c9c81630.png)

this what happened exactly 
![image](https://user-images.githubusercontent.com/51198097/135773178-85d1780d-14e0-41bc-8615-d25135ec0acc.png)

**Comment by 6by9** [comment]
The link you'd originally provided was for the Arducam OBISP boards, not PiVariety.
What sensor are you actually trying to connect?

**Comment by FaresAbuIram** [comment]
I have a raspberry pi camera 1.3 
I moved to` Arducam_OBISP_MIPI_Camera_Module` and the same result

**Comment by FaresAbuIram** [comment]
I want to make live streaming between the raspberry pi and the labtop I don't know if there is another solution

**Comment by 6by9** [comment]
If you have a Pi camera module, why are you messing with Arducam drivers? The OV5647 (V1), IMX219 (V2), and IMX477 (HQ) camera modules are all supported as standard by the Pi kernel and firmware.

**Comment by FaresAbuIram** [comment]
I tried with this one `raspistill` but it doesn't work on my 64bit machine, So when I search for another thing I found Arducam. 
`bash: /opt/vc/bin/raspistill: No such file or directory`

If one of these work with 64bit can you tell me how to configure it :)

**Comment by 6by9** [comment]
MMAL is not supported on 64 bit OSes - https://github.com/raspberrypi/userland/issues/688

For 64 bit, use libcamera.
Or you can use V4L2 with the legacy camera stack (bcm2835-v4l2, which should show up as /dev/video0).

**Comment by FaresAbuIram** [comment]
@6by9 I can't find `/dev/video0 ` or `/dev/video1 `, I connected the camera with raspberry but I can't find it, what is the problem? 
![image](https://user-images.githubusercontent.com/51198097/135904087-4e89648b-91ff-40d0-9493-850dd90059be.png)

![image](https://user-images.githubusercontent.com/51198097/135904930-3b5402b0-d63b-4e64-bd09-51760a64379c.png)

**Comment by 6by9** [comment]
For libcamera you need to enable the relevant overlay 
```dtoverlay=ov5647``` for v1 camera.
https://www.raspberrypi.org/documentation/accessories/camera.html#libcamera-and-libcamera-apps-installation

For the legacy camera stack, have you enabled the camera via raspi-config?
https://www.raspberrypi.org/documentation/accessories/camera.html#enabling-the-camera

**Comment by FaresAbuIram** [comment]
@6by9 
The same problem 
note: I am using this camera 
![image](https://user-images.githubusercontent.com/51198097/136221526-3fa921a6-76a6-4294-9ba5-1a32c68a5fd8.png)

**Comment by JamesH65** [comment]
So, you are using the Raspberry Pi OS, set up to run in 64bit mode, and you have followed the libcamera installation instructions linked above? And it's still is not working? What are the symptoms?

**Comment by FaresAbuIram** [comment]
This is the last thing that I reached 

![image](https://user-images.githubusercontent.com/51198097/136223851-91cf97e0-8c48-49ce-98e7-b584a3035371.png)

**Comment by 6by9** [comment]
When you create an issue on this repo there is a template asking for a load of standard information. Please provide it.

```v4l2-ctl --list-devices``` will list all V4L2 devices and their providers. Please provide that output.

Add ```dtdebug=1``` to config.txt, reboot, and then run ```sudo vcdbg log msg``` to grab the logs. (I think that works on 64bit, but not sure).
Otherwise REMOVE ```dtoverlay=ov5647``` from config.txt, reboot, and then ```sudo dtoverlay -v ov5647```. Report any error messages.

**Comment by FaresAbuIram** [comment]
The first command provides these devices and their providers `v4l2-ctl --list-devices`
![image](https://user-images.githubusercontent.com/51198097/136227886-3e9472d1-2cb0-4b7c-977f-11fab8b3d302.png)

`sudo vcdbg log msg` doesn't work for me 

`sudo dtoverlay -v ov5647` provide these lines 
![image](https://user-images.githubusercontent.com/51198097/136228175-7256df79-8d06-4dc4-8119-8851ac9d4acd.png)

**Comment by pelwell** [comment]
You can download a static build of vcdbg that works on a 64-bit kernel here: https://drive.google.com/file/d/1HS9E5vnxxNqrizB4mEYrnFoQQ1axSRKm/view?usp=sharing

**Comment by FaresAbuIram** [comment]
After run the `libcamera-hello`, I see these logs 
![image](https://user-images.githubusercontent.com/51198097/136288045-6032de38-35d2-4108-95fc-5978d6b89b62.png)

and there is a black screen that doesn't have anything 
![image](https://user-images.githubusercontent.com/51198097/136288326-66d47358-48cc-42ff-a3e3-20b6b060dadb.png)

What is the problem? why I can't see the camera? sorry for a lot of comments here but I am trying to solve this for my graduation project :(

**Comment by FaresAbuIram** [comment]
Anyway I tried to use a USB camera with motion and it works fine 
Thanks to all of you 
@6by9 
@JamesH65 
@pelwell

**Comment by FaresAbuIram** [comment]
@6by9 Do you know what is this wrong? 
When I am using motion with my camera(old one not USB) this error is in the motion.log file. 
![image](https://user-images.githubusercontent.com/51198097/136452149-4eea71e7-277e-400a-80b1-b0a9be1a72e7.png)

**Comment by PeterPablo** [comment]
You should take the time to provide thorough information, as asked by 6by9:

> When you create an issue on this repo there is a template asking for a load of standard information. Please provide it.

**Comment by FaresAbuIram** [comment]
I am sorry but I think that is a clear problem so it's doesn't need more details to describe. 
Ok, 
I have a raspberry pi 4 8GB, the pic below describes the information about it 
![image](https://user-images.githubusercontent.com/51198097/136524506-6054809e-1515-4ce3-8bc1-e8048faacf58.png)

I want to do live streaming with the raspberry pi camera ( raspberry pi REV 1.3), I downloaded the Libcamera driver but there is a problem, look at the below pics 
![image](https://user-images.githubusercontent.com/51198097/136525029-977eba2d-c948-4ed1-95b1-fd4a457db83f.png)
![image](https://user-images.githubusercontent.com/51198097/136524994-3d22603c-68f9-4210-bab3-e57537a3f770.png)

then I moved to the motion to see if it's work or not, I saw this error message in the motion.log 
![image](https://user-images.githubusercontent.com/51198097/136525214-1af7197e-a40c-4933-b9fd-28c97cfff415.png)

it's clear?

**Comment by PeterPablo** [comment]
Let me step in again as a mediator. I assume it is not clear to the Raspberry Pi developers, otherwise they would not have asked specifically to provide the information. You still do only provide a subset of the requested information (as screenshots). Your chances of the issue (user settings, actual SW bug, ...) being resolved will rise, if you do your best to support the process.

So, please go over all comments again, to see what further information you shall supply. I take it is specifically this one:
> Add `dtdebug=1` to config.txt, reboot, and then run `sudo vcdbg log msg` to grab the logs

(edit: make sure to use the file linked by Phil for your 64bit operating system)
Possibly, providing output of `dmesg` would also help. You can redirect logs to a file using `yourCommand > myLogfile.xt`. You may also upload to a site like pastebin using `myCommand | pastebinit`.

Best regards

**Comment by 6by9** [comment]
Github's issue tracker is meant for actual issues with the Linux kernel, not general support. Please use the forums for that - https://forums.raspberrypi.com/index.php

You're mixing and matching use of the raw sensor drivers for use with libcamera, and generic V4L2 apps. This will cause issues as you have noted.

The libcamera apps should work as distributed. As you've messed with alternate drivers and kernels I can not guess what state your system is in. I would suggest you download a clean copy of Raspberry Pi OS 64bit, install to a new SD card, and test there.

I'm not sure which message you believe to be an issue in that Motion log.
"Configuration palette index 17 (YU12) doesn't work"? 
AFAIK Motion doesn't handle raw Bayer images, so having the libcamera raw sensor drivers loaded which only offer 8 and 10 bit Bayer isn't going to get very far with it. Remove "dtoverlay=ov5647" if you wish to use Motion on processed YUV or RGB images.

**Comment by FaresAbuIram** [comment]
The problem is because my camera is broken. 
Thanks for your time
