### ISSUE TITLE
Two issues after upgrade.

### ISSUE THREAD

**Issue by kukabu** [raspberrypi/linux#462]
Hello
Today I updated the Raspbian and I found two small issues.
1. The ax88179_178a is builded in kernel now. why?
   $ zcat /proc/config.gz | fgrep -i ax88179
   CONFIG_USB_NET_AX88179_178A=y
2. I guess now isn't properly considered the BogoMIPS.
   Calibrating delay loop (skipped), value calculated using timer frequency.. 2.00 BogoMIPS (lpj=10000)

$ cat /proc/version 
Linux version 3.10.23+ (dc4@dc4-arm-01) (gcc version 4.7.2 20120731 (prerelease) (crosstool-NG linaro-1.13.1+bzr2458 - Linaro GCC 2012.08) ) #608 PREEMPT Mon Dec 9 21:11:23 GMT 2013
$ vcgencmd version
Dec  9 2013 21:22:17 
Copyright (c) 2012 Broadcom
version c7215df85576f3e72f9c390db9bc2da642453b10 (clean) (release)

**Comment by kukabu** [comment]
also xpad is builded in kernel.
$ zcat /proc/config.gz | fgrep -i xpad
CONFIG_JOYSTICK_XPAD=y
CONFIG_JOYSTICK_XPAD_FF=y

I think the ax88179 and xpad must be modules.

**Comment by licaon-kter** [comment]
Regarding issue 1: https://github.com/raspberrypi/linux/issues/225#issuecomment-16332052

Any reason you want those (xpad, ax88179) as modules?

**Comment by popcornmix** [comment]
Agree with 1. No good reason for the "=y". Will make them modules.
For 2. see https://github.com/raspberrypi/linux/issues/225#issuecomment-16332052.

**Comment by kukabu** [comment]
thanks

**Comment by popcornmix** [comment]
Updated. rpi-update to test.

**Comment by kukabu** [comment]
Thanks
