### ISSUE TITLE
rpi-5.10.y: QCA7000 data corruption fix

### ISSUE THREAD

**Issue by lategoodbye** [raspberrypi/linux#4623]
Hi,

i don't know when you plan to merge linux-5.10.y the next time. But it would be nice to merge this bugfix:
https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/commit/?h=v5.10.71&id=a67c66c1bb1244c0a9028fa1003e99a264a1abd8

Regards

**Comment by pelwell** [comment]
When have we not pulled in the latest upstream commits for our current mainstream kernel version?

**Comment by lategoodbye** [comment]
Maybe i missed something, but from what i see
current linux-5.10.y: 5.10.71
current rpi-5.10.y: 5.10.63

**Comment by popcornmix** [comment]
Yes, it's been longer that usual as we've had a stable release about to pushed for a couple of weeks.
The stable release will be pushed soon (or we'll branch it and bump rpi-update anyway).

**Comment by lategoodbye** [comment]
Thanks
