### ISSUE TITLE
Can't get SPI/GPIO to work on Raspberry Pi 4B 8GB

### ISSUE THREAD

**Issue by nsftwr** [raspberrypi/linux#4626]
**Describe the bug**
I've been trying to get my GPIO pins to work for the last couple of days so I can accomplish [this project](https://pimylifeup.com/raspberry-pi-rfid-rc522/) It's very interesting, because I've reinstalled my Pi numerous times, and none of them had `raspi-config` already on it. After installing `raspi-config` and enabling SPI I was still out of luck. Entering `raspi-config` again shows that it is enabled, but I keep getting the same error again and again. I've tried so many things, I've already forgotten what I've tried. 

_**Please see the picture attached below in additional context.**_

Currently my `/boot/firmware/config.txt`:
```
# Please DO NOT modify this file; if you need to modify the boot config, the
# "usercfg.txt" file is the place to include user changes. Please refer to
# the README file for a description of the various configuration files on
# the boot partition.

# The unusual ordering below is deliberate; older firmwares (in particular the
# version initially shipped with bionic) don't understand the conditional
# [sections] below and simply ignore them. The Pi4 doesn't boot at all with
# firmwares this old so it's safe to place at the top. Of the Pi2 and Pi3, the
# Pi3 uboot happens to work happily on the Pi2, so it needs to go at the bottom
# to support old firmwares.

[pi4]
kernel=uboot_rpi_4.bin
max_framebuffers=2

[pi2]
kernel=uboot_rpi_2.bin

[pi3]
kernel=uboot_rpi_3.bin

[all]
arm_64bit=1
device_tree_address=0x03000000

# The following settings are "defaults" expected to be overridden by the
# included configuration. The only reason they are included is, again, to
# support old firmwares which don't understand the "include" command.

enable_uart=1
cmdline=cmdline.txt

include syscfg.txt
include usercfg.txt
```
Currently my `/boot/firmware/usercfg.txt`:
```
# Place "config.txt" changes (dtparam, dtoverlay, disable_overscan, etc.) in
# this file. Please refer to the README file for a description of the various
# configuration files on the boot partition.

dtparam=i2c0=on,i2c1=on,spi=on
```

**To reproduce**

> N/A

**Expected behaviour**
Expecting to see `spi_bcm2835` when doing `lsmod | grep spi` without errors.

**Actual behaviour**
I keep getting `spi-bcm2835 fe204000.spi: could not get clk: -517`

**System**

* Which model of Raspberry Pi? e.g. Pi3B+, PiZeroW

> Raspberry Pi 4 Model B Rev 1.1 8GB

* Which OS and version (`cat /etc/rpi-issue`)?

> Ubuntu 20.04.3 LTS aarch64

* Which firmware version (`vcgencmd version`)?
```
 ubuntu@ubuntu:~$ sudo vcgencmd version
 Feb 25 2021 12:10:40
 Copyright (c) 2012 Broadcom
 version 564e5f9b852b23a330b1764bcf0b2d022a20afd0 (clean) (release) (start)
```
* Which kernel version (`uname -a`)?

> 5.4.0-1044-raspi

**Logs**
```
ubuntu@ubuntu:~$ dmesg | grep spi
[    0.000000] Linux version 5.4.0-1044-raspi (buildd@bos02-arm64-040) (gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04))
#48-Ubuntu SMP PREEMPT Thu Sep 9 15:24:01 UTC 2021 (Ubuntu 5.4.0-1044.48-raspi 5.4.140)
[    5.297822] spi-bcm2835 fe204000.spi: could not get clk: -517
[    5.370385] usb usb1: Manufacturer: Linux 5.4.0-1044-raspi xhci-hcd
[    5.371977] usb usb2: Manufacturer: Linux 5.4.0-1044-raspi xhci-hcd
```
```
ubuntu@ubuntu:~$ lsmod | grep spi`
spidev                 24576  0`
```

**Additional context**
[Photo](https://i.imgur.com/fnXoexp.jpg)

**Comment by pelwell** [comment]
1. You are using u_boot, which may or may not pass on the FDT (Flattened Device Tree) prepared by the firmware, depending on how it is configured.
2. `[    5.297822] spi-bcm2835 fe204000.spi: could not get clk: -517` is not an error, just in indication that the clock wasn't ready straight away.
3. The presence of /dev/spidev* is the best indication of success or otherwise.
4. `device_tree_address=0x03000000` is not required for a correctly configured U-boot - just use `fdt addr ${fdt_addr}` (AFAIK).

**Comment by nsftwr** [comment]
Sorry @pelwell , all of this is very new to me. I just used the Windows Raspberry pi imager. How do I configure it in a way that allows me to use the GPIO pins on my Pi4B?

**Comment by pelwell** [comment]
You haven't proven to me yet that they aren't configured correctly. How do you you know that SPI isn't working?

**Comment by nsftwr** [comment]
My appologies, @pelwell. I started this project with 21.04 which didn't support GPIO anymore due the Kernel 5.11. I expected the whole thing to fail since it wasn't showing `spi-bcm2835` when I did `lsmod | grep spi`. 

Long story short, you are right. I don't have any proof it doesn't work, because it works.
