### ISSUE TITLE
build ip6_tunnel.ko module

### ISSUE THREAD

**Issue by totaluser** [raspberrypi/linux#464]
Hello everybody,
I upgraded with apt-get update/upgrade to Linux raspberrypi 3.10.23+ #608 PREEMPT Mon Dec 9 21:11:23 GMT 2013 armv6l GNU/Linux

and I am missing ip6_tunnel.ko module for my 4to6 tunnel
http://www.raspberrypi.org/phpBB3/viewtopic.php?f=66&t=32684&p=356665#p356665

I tried to compile it on raspberry itself but it fails to load
ip6_tunnel: version magic '3.10.23 SMP preempt mod_unload modversions ARMv6 p2v8 ' should be '3.10.23+ preempt mod_unload modversions ARMv6 '

could you please build it in the next iteration of building new revision of kernel please?
just set CONFIG_IPV6_TUNNEL=m in the .config file

thanks in advance

**Comment by popcornmix** [comment]
Should be in latest update. Please rpi-update and test.

**Comment by totaluser** [comment]
excellent
just updated to Linux raspberrypi 3.10.24+ #614 PREEMPT Thu Dec 19 20:38:42 GMT 2013 armv6l

and it works as I hoped it would.

thanks
