### ISSUE TITLE
rpi-5.15.y - drivers/gpu/drm/msm/disp/dpu1/dpu_crtc.c:800:25: error: redefinition of ‘old_crtc_state’

### ISSUE THREAD

**Issue by leezu** [raspberrypi/linux#4642]
In rpi-5.15.y, after rebase to rc5 / rc6, https://github.com/raspberrypi/linux/commit/a40d37ed7f14b152d098532802d2a676b76d145c introduces redefinition of ‘old_crtc_state’ error. Should it be reverted @popcornmix?

**Comment by popcornmix** [comment]
Yes - just done (command and revert will be dropped on a future rebase).
It was a remant of a downstream commit that's appeared upstream.
