### ISSUE TITLE
CM4 4.19.y Backport

### ISSUE THREAD

**Issue by RuhanSA079** [raspberrypi/linux#4653]
Hello, 

As I have a few drivers and other kernel patches for the OS that I'm trying to compile 4.19.y for the CM4 module that I have, it seems like that the kernel compiles, but stops at the dtbs.
I know that this is very dirty and NOT the way to do it, but I have to test this.

What I did is, I got the 4.19.y branch, and copied over the dtbs + Makefile (arch/arm/boot/dts/ and overlays) from the 5.10.y, and tried to get the modules compiled one by one.
The dt-bindings was outdated, so I manually copied over all the files from 5.10.y to the 4.19.y branch. (The dtbs was not able to compile, was complaining about missing labels, etc)

It successfully compiles, but at "install" stage, it breaks.
make[2]: Nothing to be done for '__dtbs_install'.
  INSTALL crypto/async_tx/async_memcpy.ko
  INSTALL crypto/async_tx/async_pq.ko
make[2]: *** No rule to make target 'arch/arm64/boot/dts/overlays/act-led.dtbo', needed by 'act-led.dtbo'.  Stop.
make[1]: *** [scripts/Makefile.dtbinst:39: overlays] Error 2
  INSTALL crypto/async_tx/async_raid6_recov.ko
make: *** [arch/arm64/Makefile:143: dtbs_install] Error 2

(Copied over the 5.10.y Makefile.dtbinst located in "scripts/", seems to have no effect)
make[2]: *** No rule to make target '/overlays/act-led.dtbo', needed by '__dtbs_install'.  Stop.

Any hints?

**Comment by pelwell** [comment]
Please push your work in progress to a GitHub branch so we can take a look.

**Comment by RuhanSA079** [comment]
@pelwell Apologies,
After some investigation, it seems like that the rpi-5.4.y branch is compiling/working with the patched Amba-pl011 driver from Hase86, as referenced here: https://github.com/raspberrypi/linux/pull/3241
and supports the CM4. I wanted a CM4 with the RS485 driver support, so that I can use it with the MAX485 chip without any hassles.

All other drivers works as expected, so no need to push code changes, etc.
Thanks.
