### ISSUE TITLE
VC4 HDMI audio devices only support IEC958 formatted data

### ISSUE THREAD

**Issue by KonstaT** [raspberrypi/linux#4654]
Continuing the previous discussion in https://github.com/raspberrypi/linux/issues/4651.

Android uses a small subset of ALSA and it doesn't support all formats. It does not support SNDRV_PCM_FORMAT_IEC958_SUBFRAME_LE (https://android.googlesource.com/platform/system/media/+/refs/heads/master/alsa_utils/alsa_format.c#48). It only supports SNDRV_PCM_FORMAT_S8, SNDRV_PCM_FORMAT_S16_LE, SNDRV_PCM_FORMAT_S24_LE, SNDRV_PCM_FORMAT_S32_LE, SNDRV_PCM_FORMAT_S24_3LE and frame conversion between these formats. Android Audio HAL implementation opens the PCM device directly and also sets the format (e.g. https://github.com/lineage-rpi/android_device_brcm_rpi3/blob/lineage-15.1/audio/audio_hw.c#L463).

As I see options would be to add support for IEC958_SUBFRAME_LE (and conversion to other supported formats) in Android's audio-utils or to do the conversion on the kernel driver and report that SNDRV_PCM_FMTBIT_S16_LE can be used as well (https://github.com/raspberrypi/linux/blob/rpi-5.10.y/drivers/gpu/drm/vc4/vc4_hdmi.c#L1492).

Any thoughts/input what would be the best approach here? I personally would of course prefer the latter. Would adding FORMAT_S16_LE support for the VC4 HDMI be something that you could do or is it possibly already somewhere in your TODO? It would also make VC4 HDMI audio devices use the same format as bcm2835-audio and various audio DACs use.

And not to get into the whole Pi Foundation's stance "not to support Android because it serves no educational purpose" this is not a request to support any specific OS but to support more widely used industry standards.

**Comment by popcornmix** [comment]
We have no plans to make kernel driver support FORMAT_S16_LE.
That really seems to be the job of ALSA. Duplicating ALSA code in the kernel seems unproductive (and unlikely to be acceptable upstream).

Improving Android's ALSA support would seem a better solution.

**Comment by KonstaT** [comment]
What is the reasoning that IEC958_SUBFRAME_LE was selected for these devices? Is it a hardware limitation? Is it the best current practice? I grep'ed the kernel source, read the code for other drivers that use this and checked the change history. Anything else that uses this pretty much dates to Linux 2.6. Only reference I found for S16_LE <-> IEC958_SUBFRAME_LE is https://github.com/raspberrypi/linux/commit/b46be727286a93056db851ababc85c0ac3f2f91c and it was just masking a bit (for the hw to do something?).

Bringing full ALSA to Android is certainly not how this should be done. Doing the conversion in Android audio_utils (https://android.googlesource.com/platform/system/media/+/refs/heads/master/audio_utils/format.c, https://android.googlesource.com/platform/system/media/+/refs/heads/master/audio_utils/primitives.c) even having https://github.com/alsa-project/alsa-lib/blob/master/src/pcm/pcm_iec958.c as a reference seems pretty overwhelming. Having done some low level network/application protocol stuff for academics I'm not totally unfamiliar with pushing bits into frames but it's not something I'm going to spend my spare time on. I can of course also open an issue on AOSP bug tracker and see what Google engineers' opinions are on adding support for IEC958_SUBFRAME_LE to Android (and wait for few Android versions for it to happen if they even find it reasonable).

Sorry if these questions seem silly but I'm not an expert on this matter and not that familiar with Raspberry Pi hardware at this level. Just reporting what I've found so far to make the information available for others as well.

**Comment by 6by9** [comment]
HDMI audio is sent on the wire as IEC958 subframes during island periods - https://prodigytechno.com/hdmi-protocol/

The Pi HDMI hardware does almost no repacking of the data between being submitted to the FIFO and sent on the wire, hence requiring properly formatted data to be submitted to the FIFO. That correct format is IEC958_SUBFRAME_LE. Exposing it as such also allows for transport of multi-channel and compressed formats such as Dolby Digital etc to suitable sink devices.

Repacking the data is not overly onerous (as can be seen from the ALSA conversion), and is described by https://en.wikipedia.org/wiki/AES3.

About the only bit that I recall the hardware manipulating is correctly signalling Z/B frames in the preamble, so the userspace formatter has to match the configuration of the driver, and that is set as 8 (see https://github.com/raspberrypi/linux/blob/rpi-5.10.y/drivers/gpu/drm/vc4/vc4_hdmi.c#L1416) to match ALSA (https://github.com/alsa-project/alsa-lib/blob/master/src/pcm/pcm_iec958.c#L653)

**Comment by KonstaT** [comment]
Closing this as it's been resolved in one way at least. VC4 HDMI audio is now also working on Android with 5.10 kernel.

Ended up doing exactly what I said not to do and brought alsa-lib to Android. Android audio HAL implementation can only use actual PCM devices (/dev/snd/*) and not the virtual devices alsa-lib creates e.g. to do the IEC958 conversion for VC4 HMDI so the audio now travels through loopback devices. Solution is not exactly great but it's not terrible either and the good thing is that it required no changes on the Android media framework or the device audio HAL itself.
