### ISSUE TITLE
New release tag is a duplicate

### ISSUE THREAD

**Issue by notcarbide** [raspberrypi/linux#4671]
The latest release (1.20211029) and the tag before it (1.20211007) are both at commit abff5012a. If intentional, feel free to close.

Thank you!

**Comment by popcornmix** [comment]
I suspect it is deliberate.
The two most recent commits here: https://github.com/raspberrypi/rpi-firmware/commits/stable
match the tag dates, but the second one didn't modify the kernel, only the firmware.

**Comment by notcarbide** [comment]
Thank you for responding! I thought something like that was the case after looking through older releases. While not common, I noticed that this has happened before multiple times and releases did not seem kernel specific. (Hence why I closed the issue).

Have a great weekend!
