### ISSUE TITLE
Include l2tp Kernel-Modules

### ISSUE THREAD

**Issue by fmu83** [raspberrypi/linux#469]
Can you include 

l2tp_eth
l2tp_netlink

as module?

I try to compile the modules multiple times seperatly but they did not fit to my my current installed kernel, so it would be nice to have them in the official kernel.

**Comment by P33M** [comment]
Is enabled.

```
CONFIG_NETFILTER_XT_MATCH_L2TP=m
CONFIG_L2TP=m
# CONFIG_L2TP_DEBUGFS is not set
CONFIG_L2TP_V3=y
CONFIG_L2TP_IP=m
CONFIG_L2TP_ETH=m
```
