### ISSUE TITLE
Please turn on CONFIG_SUNRPC_DEBUG

### ISSUE THREAD

**Issue by DurvalMenezes** [raspberrypi/linux#4698]
**Describe the bug**

CONFIG_SUNRPC_DEBUG is turned off, which makes it very hard to troubleshoot NFS server or client issues on the machine as `rpcdebug` just fails (see below). 

To fix this, it would be necessary to set `CONFIG_SUNRPC_DEBUG=y` in the kernel config (it can't be set to `=m`).

**To reproduce**
```
#  rpcdebug -m nfsd all
    /proc/sys/sunrpc/nfsd_debug: No such file or directory
```

**Expected behaviour**
The above command should complete with no errors.

**Actual behaviour**
The above command shows the depicted error.

**System**

* Which model of Raspberry Pi? e.g. Pi3B+, PiZeroW
   RPi4B v1.4 8GB, but this should not matter 

* Which OS and version (`cat /etc/rpi-issue`)?
      Raspberry Pi reference 2021-10-30 
      Generated using pi-gen, https://github.com/RPi-Distro/pi-gen, 288b21fc27e128ea6b330777aca68e0061ebf4fe, stage2

* Which firmware version (`vcgencmd version`)?
    version b8a114e5a9877e91ca8f26d1a5ce904b2ad3cf13 (clean) (release) (start)

* Which kernel version (`uname -a`)?
    Linux raspberrypi 5.10.63-v7l+ {hashmark}1459 SMP Wed Oct 6 16:41:57 BST 2021 armv7l GNU/Linux

**Logs**
    N/A

*Full `raspinfo` output can be found here: https://0x0.st/-RBJ.txt

**Additional context**
* Impact for adding this should be minimal, as it consumes no resources (except by the few KBs for the text for the added debug messages) unless turned on explicity with `rpcdebug`;
* Even the added debug messages would only be in memory if/when the `sunrpc` kernel module is loaded;
* Other distributions, have already turned this on, eg Archlinux which is known for being lean and efficient: https://bugs.archlinux.org/task/34539

**Comment by pelwell** [comment]
Believe it or not, this option adds about 90kB of code and data to the core kernel for a Pi 4. That's a lot for a feature that is likely to be only occasionally used and by very few people (you are the first person to ask). The Arch Linux link config request is for X86 systems, which are likely to have more RAM.

Building a custom kernel is not difficult for those occasions when you have an NFS problem - see https://www.raspberrypi.com/documentation/computers/linux_kernel.html#building.
