### ISSUE TITLE
Kernels 5.15.2 & 5.10.79: Screen flickering back when using KMS

### ISSUE THREAD

**Issue by Dark-Sky** [raspberrypi/linux#4725]
I had posted this issue a few days ago on this same issue https://github.com/raspberrypi/linux/issues/4660 and never received a response so I have no clue if it is being worked on or if it was even read so starting a new issue as this really involves newer kernels. Until this is resolved KMS with V3D rendering is almost to the point of being unusable using a DE.

Others reporting the same issue on arch-arm as I never released these kernels after testing them to the manjaro-arm repo:

https://archlinuxarm.org/forum/viewtopic.php?f=65&t=15629

**Comment by pelwell** [comment]
Is this issue still needed, or has it been eclipsed by updates to #4660?

**Comment by Dark-Sky** [comment]
It is fine right now but I am worried about if changes are made again here it could come back again as this started the issue time after time trying to get this working. I do not care anything about having to adjust setting on my monitor but if I did I would use my monitor's menu to make the changes.

https://github.com/raspberrypi/firmware/issues/1274#issuecomment-1051020968
