### ISSUE TITLE
RTL8188RU chipset / 8192cu driver stopped working

### ISSUE THREAD

**Issue by iomode** [raspberrypi/linux#474]
The 8192cu driver stopped working with the RTL8188RU chipset (tested with ALFA AWUS036NHR).
Scanning works but connecting to an wifi access point does not work. Also the AP mode with hostapd (driver=rtl871xdrv) stopped working. 

The last working commit is Hexxeh/rpi-firmware@964576cffdb8097ce65ce36ae07c25d951226cb7.

``` bash
~ $ uname -a
Linux raspberrypi 3.10.18+ #585 Thu Nov 7 15:16:15 GMT 2013 armv6l GNU/Linux

~ $ modinfo 8192cu
filename:       /lib/modules/3.10.18+/kernel/drivers/net/wireless/rtl8192cu/8192cu.ko
version:        v3.4.4_4749.20121105
author:         Realtek Semiconductor Corp.
description:    Realtek Wireless Lan Driver
license:        GPL
srcversion:     98AA12E4E7910C3009C8ADF
```

All newer commits have the same problem  (e.g. Hexxeh/rpi-firmware@8fd111f77895450323abc5b34efde19548ffc480):

``` bash
~ $ uname -a
Linux raspberrypi 3.10.18+ #587 Sun Nov 10 15:30:45 GMT 2013 armv6l GNU/Linux

~ $ modinfo 8192cu
filename:       /lib/modules/3.10.18+/kernel/drivers/net/wireless/rtl8192cu/8192cu.ko
version:        v4.0.2_9000.20130911
author:         Realtek Semiconductor Corp.
description:    Realtek Wireless Lan Driver
license:        GPL
srcversion:     92ABD77EE49D06D8157B4F8
```

I think the problem is the new 8192cu 4.0.2 driver. (#420)

Additional info:

``` bash
~ $ lsusb
Bus 001 Device 006: ID 0bda:817f Realtek Semiconductor Corp. RTL8188RU 802.11n WLAN Adapter

~ $ iw wlan0 info
nl80211 not found.

~ $ iwconfig wlan0
wlan0     unassociated  Nickname:"<WIFI@REALTEK>"
          Mode:Managed  Frequency=2.427 GHz  Access Point: Not-Associated
          Sensitivity:0/0
          Retry:off   RTS thr:off   Fragment thr:off
          Power Management:off
          Link Quality:0  Signal level:0  Noise level:0
          Rx invalid nwid:0  Rx invalid crypt:0  Rx invalid frag:0
          Tx excessive retries:0  Invalid misc:0   Missed beacon:0

hostapd error:
ioctl[RTL_IOCTL_HOSTAPD]: Invalid argument
```

Additional info from modinfo:
V4: http://pastebin.com/82YmtMUi
V3: http://pastebin.com/6ypWmcjm

**Comment by popcornmix** [comment]
The 4.0.2 update did come from realtek, and presumably is being used on other linux platforms.
I wonder if there are any similar bug reports (and hopefully fixes)?

**Comment by NukeMania** [comment]
sorry i can't test new driver for hostapd but did you try hostapd with driver=nl80211 instead of the driver=rtl871xdrv

edit: someone was able to use the new driver for hostapd
http://colocsbar.blogspot.com/2013/12/raspberry-pi-et-hotspot-wifi-avec-le.html

**Comment by iomode** [comment]
Currently I am using the hostapd version from here: 
http://jenssegers.be/blog/43/Realtek-RTL8188-based-access-point-on-Raspberry-Pi (jenssegers/RTL8188-hostapd@783ec4b69be4baadaee0b5134740645dd307383e)
It is the same version as the hostapd from the 4.0.2_9000 source (v0.8.x). (last updated 2011?)
It works fine with the 3.4.4_4749 driver and rtl871xdrv (nl80211 is not possible).
The repository hostapd (v1.0) does not work with nl80211 or rtl871xdrv on 3.4.4_4749.

**Comment by NukeMania** [comment]
wpa_supplicant_hostapd-0.8_rtw_r7475.20130812.tar.gz from 4.0.2 source package updated to 12.08.2013

you should use this

**Comment by iomode** [comment]
I am almost sure that wpa_supplicant_hostapd-0.8_rtw_r7475.20130812.tar.gz is no update, the changelog and version.h files did not change and some source files I have checked have the same line count.

**Comment by NukeMania** [comment]
this is diff result of  wpa_supplicant_hostapd-0.8_rtw_r7475.20130812 and jenssegers/RTL8188-hostapd@783ec4b)
archives

result file is 12,6mb i pretty sure there are not identical source even pastebin refuses to upload :)
http://www15.zippyshare.com/v/67254673/file.html

I don't think vendor care about updating version.h and changelog they just patching the source
vendor provides the source with driver i think just give a try

**Comment by iomode** [comment]
ok, you are right.

``` bash
diff -u -w -r -s RTL8188-hostapd/src  wpa_supplicant_hostapd-0.8_rtw_r7475.20130812/src | diffstat
 ap/wpa_auth.c         |    2 
 common/version.h      |    6 
 crypto/random.c       |   18 +-
 drivers/driver_rtl.h  |    3 
 drivers/driver_rtw.c  |  382 +++++++++++++++++++++++++++++++++++---------------
 drivers/driver_wext.c |   31 +++-
 drivers/drivers.mk    |   11 +
 wps/wps.c             |   13 +
 wps/wps.h             |    3 
 wps/wps_defs.h        |    2 
 10 files changed, 344 insertions(+), 127 deletions(-)
diff -u -w -r -s RTL8188-hostapd/hostapd/  wpa_supplicant_hostapd-0.8_rtw_r7475.20130812/hostapd/ | diffstat
 Android.mk    |    5 +++--
 Makefile      |    4 ----
 hostapd_cli.c |    1 -
 3 files changed, 3 insertions(+), 7 deletions(-)
´´´
```

**Comment by syntheticpp** [comment]
Related:
https://github.com/raspberrypi/linux/pull/938

**Comment by Ruffio** [comment]
@iomode has this issue been resolved? If yes, then please close this issue.

**Comment by Ruffio** [comment]
@popcornmix please consider to close this issue as it was regarding kernel 3.10, there have been no real  activity since 12 Apr 2014, the X-referenced issue is close and there have been no response to my ping 19 days ago
