### ISSUE TITLE
3.12.6 memory issues

### ISSUE THREAD

**Issue by ha5di** [raspberrypi/linux#477]
Tested 3.12.6 kernel on piCore 5.1rc3. Using it intensively found it buggy, there is something wrong probably with memory management. Loop mount fails frequently with file unavaliable which is there and processes get killed. I can't make medium size applications, loosing SSH connection, etc. With 3.12.1 in the otherwise same environment no such issues, I built even full Qt5 which took 5 days, used 500Mbyte swap in peeks.

**Comment by popcornmix** [comment]
Well, if it worked better in 3.12.1, then it's likely an upstream kernel bug which will hopefully be fixed in a future update.

I can say that OpenELEC is using 3.12.6 kernel without issue, so I guess the problem only affects some kernel configuration options.

**Comment by ha5di** [comment]
Thanks for the comment. Using the same .config for 3.12.6 as 3.12.1 without touching new features it behaves badly. Will see next releases.

**Comment by ha5di** [comment]
Just for the records, 3.12.7 / 3.12.13 is OK.

**Comment by popcornmix** [comment]
Okay to close this?

**Comment by ha5di** [comment]
Sure

popcornmix notifications@github.com írta:
