### ISSUE TITLE
5.10.85 on armv6 will not enable onboard audio

### ISSUE THREAD

**Issue by gearhead** [raspberrypi/linux#4778]
If `dtparam=audio=on` is enabled in config.txt on a v6 Pi that has onboard audio (B1), it will fail to boot. If it is enabled on a Pi ZeroW, it boots fine as there is no 3.5mm audio jack, I guess. but on a B1, it will not boot.  I noticed that this happened sometime after 5.10.63.

**Comment by popcornmix** [comment]
Can you clarify the model of Pi with the problem? Output of this would be useful.
```
grep Revision /proc/cpuinfo
```
Also report output of `vcgencmd version` and `uname -a`.
And are you using RPiOS bullseye or something else?

**Comment by gearhead** [comment]
please disregard. It was user error. Works as advertised.
