### ISSUE TITLE
Oops in snd-bcm2852

### ISSUE THREAD

**Issue by werwurm** [raspberrypi/linux#478]
There is a race in the sound driver. When controls on the device are set while a new alsa stream is being added to the device there is a time window where the new stream can be accessed uninitialized causing a NULL pointer dereference (at least).

git revision: 4bbea92 (should be the current raspbian kernel as of this writing)
in sound/arm/bcm2835-vchiq.c:

```
462: if(mutex_lock_interruptible(&instance->vchi_mutex))
```

"instance" is NULL causing an Oops if another process is between
sound/arm/bcm2835-pcm.c:131 and 148

I could easily reproduce this by starting at least 3 instances of mplayer in a scripted loop like so:

```
$ for i in 1 2 3
> do
> mplayer -slave -really-quiet <some.mp3> &
> done
```

Looking at the code there seems to be a similar race upon closing a stream although I did not menage to trigger a bug there (did't try very hard though).

As a quick fix I moved 
sound/arm/bcm2835-pcm.c:

```
130: chip->alsa_stream[idx] = alsa_stream;
```

past line 151.

I pushed the quick-fix to
https://github.com/werwurm/linux/tree/werwurm/snd-bcm2835-fix

This however does not address the race upon stream closing. I think this cannot be fixed as easily. IMHO alsa stream access through chip->alsa_stream needs some means of synchronization.

Cheers

**Comment by popcornmix** [comment]
I've included your patch in latest update, until a better solution is found. Thanks.
