### ISSUE TITLE
Can I use USB in RPI-4.19.y-rt?

### ISSUE THREAD

**Issue by yangfan852219770** [raspberrypi/linux#4781]
I used the 4.19-rt kernel, when I plugged USB, I could not find the device. In addtion, the **usb-storage** module isn't included in **lsmod | grep -i usb** command.

**Comment by burakgerz** [comment]
Did you follow exactly this guide?
https://www.raspberrypi.com/documentation/computers/linux_kernel.html

Most probably you did not deploy the compiled kernel modules to your raspberry?

**Comment by kdoren** [comment]
Not sure about 4.19 but in later kernels usb-storage appears to be an interface driver that's part of usb-core.  You can see it with dmeg but not with lsmod.:

```
$ dmesg | grep storage 
[    1.415058] usbcore: registered new interface driver usb-storage
```
The physical device will likely show up under /dev/sda
Mounted USB storage volumes show up under /media/pi/

If you want to try a later RT kernel, I posted 32 & 64-bit deb packages of kernel 5.10.74 and also 5.15.10 built with PREEMPT_RT and low-latency PREEMPT.

https://github.com/kdoren/linux/releases

**Comment by yangfan852219770** [comment]
> Did you follow exactly this guide? https://www.raspberrypi.com/documentation/computers/linux_kernel.html
> 
> Most probably you did not deploy the compiled kernel modules to your raspberry?

Thank you! I have solved this problem by re-installing the system.
