### ISSUE TITLE
pCP updates / Full Update - Internet not accessible!!

### ISSUE THREAD

**Issue by MrSiO** [raspberrypi/linux#4784]
**Describe the bug**
Trying to use the _pCP updates - FULL UPDATE_ button to upgrade my piCorePlayer with no success lately.

Tried from:
- RPi Zero W  (running 6.0.0)
- RPi 3 (running 6.0.0)
- RPi 4 (running 8.1.0)

I alway get the following error:
`Internet not accessible!!`

Tried both with ehternet and wifi.
No firewall involved.  
From SSH I can issues WGET all over the internet so internet acces is fine from RPi's.

**To reproduce**
I can reproduce anytime by clicking the FULL UPDATE button on all 3 of my RPi's.

**Expected behaviour**
It should update as it used to.  

**Actual behaviour**
After about 30 seconds I get a timeout with error message: ` Internet not accessible!!`

**System**
* Which model of Raspberry Pi?  `RPi Zero W & RPi3 & RPi4`
* Which OS and version (`cat /etc/rpi-issue`)?  `6.0.0  &  8.1.0`
* Which kernel version (`uname -a`)?
`Linux RPi-LMS-Player1-Sonette 4.19.105-pcpCore_v7 #1 SMP Sat Feb 22 00:32:02 EST 2020 armv7l GNU/Linux
`

**Logs**
`[    0.000000] Booting Linux on physical CPU 0x0
[    0.000000] Linux version 4.19.105-pcpCore_v7 (pCP@SoundStation) (gcc version 7.4.1 20181213 (crosstool-NG 1.24.0.6-afaf7b9)) #1 SMP Sat Feb 22 00:32:02 EST 2020
[    0.000000] CPU: ARMv7 Processor [410fd034] revision 4 (ARMv7), cr=10c5383d
[    0.000000] CPU: div instructions available: patching division code
[    0.000000] CPU: PIPT / VIPT nonaliasing data cache, VIPT aliasing instruction cache
[    0.000000] OF: fdt: Machine model: Raspberry Pi 3 Model B Rev 1.2
[    0.000000] Memory policy: Data cache writealloc
[    0.000000] cma: Reserved 8 MiB at 0x3dc00000
[    0.000000] On node 0 totalpages: 255488
[    0.000000]   Normal zone: 2246 pages used for memmap
[    0.000000]   Normal zone: 0 pages reserved
[    0.000000]   Normal zone: 255488 pages, LIFO batch:63
[    0.000000] random: get_random_bytes called from start_kernel+0xb0/0x4b4 with crng_init=0
[    0.000000] percpu: Embedded 16 pages/cpu s36748 r8192 d20596 u65536
[    0.000000] pcpu-alloc: s36748 r8192 d20596 u65536 alloc=16*4096
[    0.000000] pcpu-alloc: [0] 0 [0] 1 [0] 2 [0] 3 
[    0.000000] Built 1 zonelists, mobility grouping on.  Total pages: 253242
[    0.000000] Kernel command line: coherent_pool=1M 8250.nr_uarts=0 bcm2708_fb.fbwidth=656 bcm2708_fb.fbheight=416 bcm2708_fb.fbdepth=16 bcm2708_fb.fbswap=1 smsc95xx.macaddr=B8:27:EB:F8:60:28 vc_mem.mem_base=0x3f000000 vc_mem.mem_size=0x3f600000  host=RPi-LMS-Player1-Sonette tz=EST5EDT,M3.2.0,M11.1.0 dwc_otg.fiq_fsm_mask=0xF dwc_otg.lpm_enable=0 console=tty1 root=/dev/ram0 elevator=deadline rootwait quiet nortc loglevel=3 noembed smsc95xx.turbo_mode=N noswap consoleblank=0 waitusb=2
[    0.000000] Dentry cache hash table entries: 131072 (order: 7, 524288 bytes)
[    0.000000] Inode-cache hash table entries: 65536 (order: 6, 262144 bytes)
[    0.000000] Memory: 985292K/1021952K available (8192K kernel code, 626K rwdata, 2184K rodata, 1024K init, 821K bss, 28468K reserved, 8192K cma-reserved)
[    0.000000] Virtual kernel memory layout:
[    0.000000]     vector  : 0xffff0000 - 0xffff1000   (   4 kB)
[    0.000000]     fixmap  : 0xffc00000 - 0xfff00000   (3072 kB)
[    0.000000]     vmalloc : 0xbe800000 - 0xff800000   (1040 MB)
[    0.000000]     lowmem  : 0x80000000 - 0xbe600000   ( 998 MB)
[    0.000000]     modules : 0x7f000000 - 0x80000000   (  16 MB)
[    0.000000]       .text : 0x(ptrval) - 0x(ptrval)   (9184 kB)
[    0.000000]       .init : 0x(ptrval) - 0x(ptrval)   (1024 kB)
[    0.000000]       .data : 0x(ptrval) - 0x(ptrval)   ( 627 kB)
[    0.000000]        .bss : 0x(ptrval) - 0x(ptrval)   ( 822 kB)
[    0.000000] SLUB: HWalign=64, Order=0-3, MinObjects=0, CPUs=4, Nodes=1
[    0.000000] ftrace: allocating 26373 entries in 78 pages
[    0.000000] rcu: Hierarchical RCU implementation.
[    0.000000] NR_IRQS: 16, nr_irqs: 16, preallocated irqs: 16
[    0.000000] arch_timer: cp15 timer(s) running at 19.20MHz (phys).
[    0.000000] clocksource: arch_sys_counter: mask: 0xffffffffffffff max_cycles: 0x46d987e47, max_idle_ns: 440795202767 ns
[    0.000003] sched_clock: 56 bits at 19MHz, resolution 52ns, wraps every 4398046511078ns
[    0.000009] Switching to timer-based delay loop, resolution 52ns
[    0.000153] Console: colour dummy device 80x30
[    0.000164] console [tty1] enabled
[    0.000189] Calibrating delay loop (skipped), value calculated using timer frequency.. 38.40 BogoMIPS (lpj=192000)
[    0.000197] pid_max: default: 32768 minimum: 301
[    0.000368] Mount-cache hash table entries: 2048 (order: 1, 8192 bytes)
[    0.000378] Mountpoint-cache hash table entries: 2048 (order: 1, 8192 bytes)
[    0.000909] CPU: Testing write buffer coherency: ok
[    0.001191] CPU0: thread -1, cpu 0, socket 0, mpidr 80000000
[    0.001548] Setting up static identity map for 0x100000 - 0x10003c
[    0.001630] rcu: Hierarchical SRCU implementation.
[    0.002058] smp: Bringing up secondary CPUs ...
[    0.002540] CPU1: thread -1, cpu 1, socket 0, mpidr 80000001
[    0.003048] CPU2: thread -1, cpu 2, socket 0, mpidr 80000002
[    0.003512] CPU3: thread -1, cpu 3, socket 0, mpidr 80000003
[    0.003574] smp: Brought up 1 node, 4 CPUs
[    0.003580] SMP: Total of 4 processors activated (153.60 BogoMIPS).
[    0.003583] CPU: All CPU(s) started in HYP mode.
[    0.003586] CPU: Virtualization extensions available.
[    0.004169] devtmpfs: initialized
[    0.010985] VFP support v0.3: implementor 41 architecture 3 part 40 variant 3 rev 4
[    0.011109] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 19112604462750000 ns
[    0.011119] futex hash table entries: 1024 (order: 4, 65536 bytes)
[    0.011463] pinctrl core: initialized pinctrl subsystem
[    0.011933] NET: Registered protocol family 16
[    0.013688] DMA: preallocated 1024 KiB pool for atomic coherent allocations
[    0.016653] hw-breakpoint: found 5 (+1 reserved) breakpoint and 4 watchpoint registers.
[    0.016657] hw-breakpoint: maximum watchpoint size is 8 bytes.
[    0.016776] Serial: AMBA PL011 UART driver
[    0.017944] bcm2835-mbox 3f00b880.mailbox: mailbox enabled
[    0.030013] raspberrypi-firmware soc:firmware: Attached to firmware from 2020-02-20 16:44, variant start_cd
[    0.040019] raspberrypi-firmware soc:firmware: Firmware hash is 1614a1ded604d11f395044be137350df84e3d8ee
[    0.066324] bcm2835-dma 3f007000.dma: DMA legacy API manager at (ptrval), dmachans=0x1
[    0.067168] SCSI subsystem initialized
[    0.067286] usbcore: registered new interface driver usbfs
[    0.067314] usbcore: registered new interface driver hub
[    0.067363] usbcore: registered new device driver usb
[    0.068279] clocksource: Switched to clocksource arch_sys_counter
[    0.103614] VFS: Disk quotas dquot_6.6.0
[    0.103668] VFS: Dquot-cache hash table entries: 1024 (order 0, 4096 bytes)
[    0.103767] FS-Cache: Loaded
[    0.103897] CacheFiles: Loaded
[    0.108770] NET: Registered protocol family 2
[    0.109233] tcp_listen_portaddr_hash hash table entries: 512 (order: 0, 6144 bytes)
[    0.109253] TCP established hash table entries: 8192 (order: 3, 32768 bytes)
[    0.109309] TCP bind hash table entries: 8192 (order: 4, 65536 bytes)
[    0.109402] TCP: Hash tables configured (established 8192 bind 8192)
[    0.109482] UDP hash table entries: 512 (order: 2, 16384 bytes)
[    0.109508] UDP-Lite hash table entries: 512 (order: 2, 16384 bytes)
[    0.109636] NET: Registered protocol family 1
[    0.109966] RPC: Registered named UNIX socket transport module.
[    0.109969] RPC: Registered udp transport module.
[    0.109972] RPC: Registered tcp transport module.
[    0.109975] RPC: Registered tcp NFSv4.1 backchannel transport module.
[    0.110104] Trying to unpack rootfs image as initramfs...
[    0.308553] Freeing initrd memory: 4544K
[    0.311654] hw perfevents: enabled with armv7_cortex_a7 PMU driver, 7 counters available
[    0.313304] Initialise system trusted keyrings
[    0.313436] workingset: timestamp_bits=14 max_order=18 bucket_order=4
[    0.318562] FS-Cache: Netfs 'nfs' registered for caching
[    0.318865] NFS: Registering the id_resolver key type
[    0.318881] Key type id_resolver registered
[    0.318884] Key type id_legacy registered
[    0.318893] nfs4filelayout_init: NFSv4 File Layout Driver Registering...
[    0.319707] Key type asymmetric registered
[    0.319712] Asymmetric key parser 'x509' registered
[    0.319740] Block layer SCSI generic (bsg) driver version 0.4 loaded (major 250)
[    0.319822] io scheduler noop registered
[    0.319825] io scheduler deadline registered (default)
[    0.319916] io scheduler cfq registered
[    0.319920] io scheduler mq-deadline registered (default)
[    0.319923] io scheduler kyber registered
[    0.321675] bcm2708_fb soc:fb: FB found 1 display(s)
[    0.324937] Console: switching to colour frame buffer device 82x26
[    0.326368] bcm2708_fb soc:fb: Registered framebuffer for display 0, size 656x416
[    0.327458] bcm2835-rng 3f104000.rng: hwrng registered
[    0.327628] vc-mem: phys_addr:0x00000000 mem_base=0x3f000000 mem_size:0x3f600000(1014 MiB)
[    0.327882] vc-sm: Videocore shared memory driver
[    0.328045] gpiomem-bcm2835 3f200000.gpiomem: Initialised: Registers at 0x3f200000
[    0.333401] brd: module loaded
[    0.338808] loop: module loaded
[    0.339141] Loading iSCSI transport class v2.0-870.
[    0.339540] libphy: Fixed MDIO Bus: probed
[    0.339598] usbcore: registered new interface driver lan78xx
[    0.339628] usbcore: registered new interface driver smsc95xx
[    0.339636] dwc_otg: version 3.00a 10-AUG-2012 (platform bus)
[    0.367318] dwc_otg 3f980000.usb: base=(ptrval)
[    0.567499] Core Release: 2.80a
[    0.567504] Setting default values for core params
[    0.567520] Finished setting default values for core params
[    0.767681] Using Buffer DMA mode
[    0.767685] Periodic Transfer Interrupt Enhancement - disabled
[    0.767688] Multiprocessor Interrupt Enhancement - disabled
[    0.767692] OTG VER PARAM: 0, OTG VER FLAG: 0
[    0.767701] Dedicated Tx FIFOs mode
[    0.767948] WARN::dwc_otg_hcd_init:1074: FIQ DMA bounce buffers: virt = bdd04000 dma = 0xfdd04000 len=9024
[    0.767963] FIQ FSM acceleration enabled for :
[    0.767963] Non-periodic Split Transactions
[    0.767963] Periodic Split Transactions
[    0.767963] High-Speed Isochronous Endpoints
[    0.767963] Interrupt/Control Split Transaction hack enabled
[    0.767967] dwc_otg: Microframe scheduler enabled
[    0.767997] WARN::hcd_init_fiq:457: FIQ on core 1
[    0.768002] WARN::hcd_init_fiq:458: FIQ ASM at 80635a1c length 36
[    0.768008] WARN::hcd_init_fiq:497: MPHI regs_base at be810000
[    0.768017] dwc_otg 3f980000.usb: DWC OTG Controller
[    0.768035] dwc_otg 3f980000.usb: new USB bus registered, assigned bus number 1
[    0.768054] dwc_otg 3f980000.usb: irq 56, io mem 0x00000000
[    0.768090] Init: Port Power? op_state=1
[    0.768093] Init: Power Port (0)
[    0.768230] usb usb1: New USB device found, idVendor=1d6b, idProduct=0002, bcdDevice= 4.19
[    0.768235] usb usb1: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[    0.768240] usb usb1: Product: DWC OTG Controller
[    0.768244] usb usb1: Manufacturer: Linux 4.19.105-pcpCore_v7 dwc_otg_hcd
[    0.768249] usb usb1: SerialNumber: 3f980000.usb
[    0.768592] hub 1-0:1.0: USB hub found
[    0.768621] hub 1-0:1.0: 1 port detected
[    0.768922] dwc_otg: FIQ enabled
[    0.768925] dwc_otg: NAK holdoff enabled
[    0.768928] dwc_otg: FIQ split-transaction FSM enabled
[    0.768935] Module dwc_common_port init
[    0.769094] usbcore: registered new interface driver usb-storage
[    0.769185] mousedev: PS/2 mouse device common for all mice
[    0.769645] bcm2835-wdt bcm2835-wdt: Broadcom BCM2835 watchdog timer
[    0.769763] bcm2835-cpufreq: min=600000 max=1200000
[    0.770697] sdhci: Secure Digital Host Controller Interface driver
[    0.770699] sdhci: Copyright(c) Pierre Ossman
[    0.770914] mmc-bcm2835 3f300000.mmcnr: could not get clk, deferring probe
[    0.771124] sdhost-bcm2835 3f202000.mmc: could not get clk, deferring probe
[    0.771190] sdhci-pltfm: SDHCI platform and OF driver helper
[    0.772302] ledtrig-cpu: registered to indicate activity on CPUs
[    0.772401] hidraw: raw HID events driver (C) Jiri Kosina
[    0.772483] usbcore: registered new interface driver usbhid
[    0.772486] usbhid: USB HID core driver
[    0.773002] vchiq: vchiq_init_state: slot_zero = (ptrval), is_master = 0
[    0.773929] [vc_sm_connected_init]: start
[    0.776608] vc_vchi_sm_init: failed to open VCHI service (-1)
[    0.776611] [vc_sm_connected_init]: failed to initialize shared memory service
[    0.776617] [vc_sm_connected_init]: end - returning -1
[    0.777261] Initializing XFRM netlink socket
[    0.777275] NET: Registered protocol family 17
[    0.777339] Key type dns_resolver registered
[    0.777663] Registering SWP/SWPB emulation handler
[    0.777984] registered taskstats version 1
[    0.777995] Loading compiled-in X.509 certificates
[    0.781701] uart-pl011 3f201000.serial: cts_event_workaround enabled
[    0.781750] 3f201000.serial: ttyAMA0 at MMIO 0x3f201000 (irq = 81, base_baud = 0) is a PL011 rev2
[    0.782726] mmc-bcm2835 3f300000.mmcnr: mmc_debug:0 mmc_debug2:0
[    0.782731] mmc-bcm2835 3f300000.mmcnr: DMA channel allocated
[    0.808523] sdhost: log_buf @ (ptrval) (fdd07000)
[    0.846333] mmc1: queuing unknown CIS tuple 0x80 (2 bytes)
[    0.847844] mmc1: queuing unknown CIS tuple 0x80 (3 bytes)
[    0.849351] mmc1: queuing unknown CIS tuple 0x80 (3 bytes)
[    0.852055] mmc1: queuing unknown CIS tuple 0x80 (7 bytes)
[    0.855802] mmc0: sdhost-bcm2835 loaded - DMA enabled (>1)
[    0.856477] of_cfs_init
[    0.856556] of_cfs_init: OK
[    0.879721] Freeing unused kernel memory: 1024K
[    0.908484] Run /init as init process
[    0.924177] random: fast init done
[    0.941312] mmc0: host does not support reading read-only switch, assuming write-enable
[    0.945010] mmc0: new high speed SDHC card at address b030
[    0.945715] mmcblk0: mmc0:b030 SA08G 7.40 GiB
[    0.947747]  mmcblk0: p1 p2
[    0.965651] mmc1: new high speed SDIO card at address 0001
[    0.988435] Indeed it is in host mode hprt0 = 00021501
[    1.199417] usb 1-1: new high-speed USB device number 2 using dwc_otg
[    1.199569] Indeed it is in host mode hprt0 = 00001101
[    1.438550] usb 1-1: New USB device found, idVendor=0424, idProduct=9514, bcdDevice= 2.00
[    1.438558] usb 1-1: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[    1.438961] hub 1-1:1.0: USB hub found
[    1.439013] hub 1-1:1.0: 5 ports detected
[    1.758297] usb 1-1.1: new high-speed USB device number 3 using dwc_otg
[    1.888435] usb 1-1.1: New USB device found, idVendor=0424, idProduct=ec00, bcdDevice= 2.00
[    1.888441] usb 1-1.1: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[    1.890866] smsc95xx v1.0.6
[    1.980260] smsc95xx 1-1.1:1.0 eth0: register 'smsc95xx' at usb-3f980000.usb-1.1, smsc95xx USB 2.0 Ethernet, b8:27:eb:f8:60:28
[    3.295710] zram: Added device: zram0
[    3.311521] zram0: detected capacity change from 0 to 245407744
[    3.314925] random: mkswap: uninitialized urandom read (16 bytes read)
[    3.318778] Adding 239652k swap on /dev/zram0.  Priority:-2 extents:1 across:239652k SSFS
[    3.409116] squashfs: version 4.0 (2009/01/31) Phillip Lougher
[    3.811957] EXT4-fs (mmcblk0p2): mounted filesystem with ordered data mode. Opts: (null)
[    3.888416] EXT4-fs (mmcblk0p2): mounted filesystem with ordered data mode. Opts: (null)
[    8.868433] usb 1-1.3: new high-speed USB device number 4 using dwc_otg
[    9.008752] usb 1-1.3: New USB device found, idVendor=059b, idProduct=0070, bcdDevice= 0.00
[    9.008768] usb 1-1.3: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[    9.008777] usb 1-1.3: Product: eGo USB
[    9.008786] usb 1-1.3: Manufacturer: Iomega
[    9.008795] usb 1-1.3: SerialNumber: 030000000000B475
[    9.017542] usb-storage 1-1.3:1.0: USB Mass Storage device detected
[    9.035651] scsi host0: usb-storage 1-1.3:1.0
[   10.099841] scsi 0:0:0:0: Direct-Access     OEM      Ext Hard Disk    0000 PQ: 0 ANSI: 5
[   10.137975] sd 0:0:0:0: [sda] 975339568 512-byte logical blocks: (499 GB/465 GiB)
[   10.159615] sd 0:0:0:0: [sda] Write Protect is off
[   10.159633] sd 0:0:0:0: [sda] Mode Sense: 10 00 00 00
[   10.178712] scsi 0:0:0:1: CD-ROM            Virtual  CDROM                 PQ: 0 ANSI: 0
[   10.200178] sd 0:0:0:0: [sda] Write cache: enabled, read cache: enabled, doesn't support DPO or FUA
[   10.323934]  sda: sda1
[   10.398498] sd 0:0:0:0: [sda] Attached SCSI disk
[   11.221218] random: dbus-uuidgen: uninitialized urandom read (12 bytes read)
[   11.221300] random: dbus-uuidgen: uninitialized urandom read (8 bytes read)
[   12.143330] Starting piCorePlayer v6.0.0 startup.
[   12.877426] FAT-fs (mmcblk0p1): Volume was not properly unmounted. Some data may be corrupt. Please run fsck.
[   13.005111] snd_bcm2835: module is from the staging directory, the quality is unknown, you have been warned.
[   13.017090] bcm2835_audio soc:audio: card created with 8 channels
[   13.224506] EXT4-fs (sda1): mounted filesystem with ordered data mode. Opts: (null)
[   13.391695] smsc95xx 1-1.1:1.0 eth0: hardware isn't capable of remote wakeup
[   13.560378] Bluetooth: Core ver 2.22
[   13.560467] NET: Registered protocol family 31
[   13.560473] Bluetooth: HCI device and connection manager initialized
[   13.561432] Bluetooth: HCI socket layer initialized
[   13.561452] Bluetooth: L2CAP socket layer initialized
[   13.561507] Bluetooth: SCO socket layer initialized
[   13.572866] Bluetooth: HCI UART driver ver 2.3
[   13.572884] Bluetooth: HCI UART protocol H4 registered
[   13.573066] Bluetooth: HCI UART protocol Three-wire (H5) registered
[   13.574465] Bluetooth: HCI UART protocol Broadcom registered
[   13.689250] uart-pl011 3f201000.serial: no DMA platform data
[   14.194998] random: crng init done
[   14.882858] smsc95xx 1-1.1:1.0 eth0: link up, 100Mbps, full-duplex, lpa 0xC1E1
[   15.128502] Under-voltage detected! (0x00050005)
[   18.510310] Bluetooth: BNEP (Ethernet Emulation) ver 1.3
[   18.510319] Bluetooth: BNEP filters: protocol multicast
[   18.510335] Bluetooth: BNEP socket layer initialized
[   18.533637] Bluetooth: RFCOMM TTY layer initialized
[   18.533662] Bluetooth: RFCOMM socket layer initialized
[   18.533696] Bluetooth: RFCOMM ver 1.11
[   18.782220] EXT4-fs (sda1): mounted filesystem with ordered data mode. Opts: (null)
[   25.528479] Voltage normalised (0x00000000)
[   35.738721] Finished piCorePlayer v6.0.0 startup.
`

**Additional context**
Used to work a while ago...
Any other logs I could get to to see why internet access is timing out?  Thx !

Note1: Patch update is working - checking the repo for newer version.
Note2: But Minor Update has same internet issue as the Full Update......

**Comment by JamesH65** [comment]
Pi Core player is not a Raspberry Pi supplied OS, so unless you see the same issue on our Raspberry Pi OS, I'd suggest approaching the PiCorePlayer devs for help, as the problem is almost certainly at their end.

https://docs.picoreplayer.org/

**Comment by MrSiO** [comment]
> Pi Core player is not a Raspberry Pi supplied OS, so unless you see the same issue on our Raspberry Pi OS, I'd suggest approaching the PiCorePlayer devs for help, as the problem is almost certainly at their end.
> 
> https://docs.picoreplayer.org/

Thx.
Will do.
