### ISSUE TITLE
libcamera dead if Lens of OV9281 camera is covered

### ISSUE THREAD

**Issue by waveshare** [raspberrypi/linux#4810]
### Describe the bug

Stand the camera on the desktop and block the lens with hand, the application is always dead when most of the view is covered. Once the application stop working and the preview steaming is stuck, the preview windows cannot be closed by Alt-F4 or clicking the exit icon, I need to use Ctrl-C to stop the application and restart the command. After testing multiple times, I found that the exp value is about 33000+ when the application is dead, in this case, I just think that the bug is caused by the limitation of the exposure compensation.

### Steps to reproduce the behaviour

1. Connect OV9281 camera and modify config.txt file:
   camera_auto_detect=0
   dtoverlay=ov9281
2. reboot
3. Preview the camera with the command: libcamera-vid -t 0
4. Close object or hand to the lens and try to cover the lens

### Device (s)

Raspberry Pi Zero 2 W, Raspberry Pi 3 Mod. B, Raspberry Pi 3 Mod. B+, Raspberry Pi 4 Mod. B

### System

**OS and version:** 
Raspberry Pi reference 2021-10-30
Generated using pi-gen, https://github.com/RPi-Distro/pi-gen, 288b21fc27e128ea6b330777aca68e0061ebf4fe, stage4

**firmware version:**
Oct 29 2021 10:47:33
Copyright (c) 2012 Broadcom
version b8a114e5a9877e91ca8f26d1a5ce904b2ad3cf13 (clean) (release) (start)

**kernel version:**
Linux raspberrypi 5.10.63-v7l+ #1459 SMP Wed Oct 6 16:41:57 BST 2021 armv7l GNU/Linux

**Comment by 6by9** [comment]
Already resolved via #4807.
