### ISSUE TITLE
mpv --hwdec=v4l2m2m-copy issue

### ISSUE THREAD

**Issue by Dark-Sky** [raspberrypi/linux#4823]
### Describe the bug

Using mpv --hwdec=v4l2m2m-copy to play a some (not all) .mp4 video results in no video but has audio. I went back installing kernels and the last good one was 5.10.52. Then the next kernel I have 5.10.64 was when the issue started. This is the issue started trying to boot with V3D so I do not have any kernels between these kernel versions to test. Eventually this issue has crept in to all of newer kernel trees.

### Steps to reproduce the behaviour

Play the attached video with mpv --hwdec=v4l2m2m-copy ./2minvideo.mp4

### Device (s)

Raspberry Pi 4 Mod. B

### System

[ray@pi4 ~]$ vcgencmd version
Jan  4 2022 18:09:05 
Copyright (c) 2012 Broadcom
version 89012f19c33b91cbe9df3933e2a21375bb4f0274 (clean) (release) (start)

### Logs

Here are the logs with mpv with --msg-level=all=v First the last working kernel then the first non working kernel playing a .mp4 that has the issue.

Kernel 5.10.52 --hwdec=v4l2m2m-copy working:

[ray@pi4 Desktop]$ mpv --msg-level=all=v --hwdec=v4l2m2m-copy ./2minvideo.mp4 
[cplayer] Command line options: '--msg-level=all=v' '--hwdec=v4l2m2m-copy' './2minvideo.mp4'
[cplayer] mpv 0.34.0-dirty Copyright © 2000-2021 mpv/MPlayer/mplayer2 projects
[cplayer]  built on UNKNOWN
[cplayer] FFmpeg library versions:
[cplayer]    libavutil       56.70.100
[cplayer]    libavcodec      58.134.100
[cplayer]    libavformat     58.76.100
[cplayer]    libswscale      5.9.100
[cplayer]    libavfilter     7.110.100
[cplayer]    libswresample   3.9.100
[cplayer] FFmpeg version: n4.4.1
[cplayer] 
[cplayer] Configuration: /usr/bin/waf configure --prefix=/usr --confdir=/etc/mpv --enable-cdda --enable-dvb --enable-dvdnav --enable-libarchive --enable-libmpv-shared --disable-build-date --disable-caca
[cplayer] List of enabled features: alsa asm cdda cplayer cplugins cuda-hwaccel cuda-interop debug-build drm dvbin dvdnav egl egl-drm egl-helpers egl-x11 ffmpeg ffmpeg-aviocontext-bytes-read ffnvcodec gbm gbm.h gl gl-wayland glibc-thread-name glob glob-posix gpl iconv jack javascript jpeg lcms2 libarchive libass libavdevice libbluray libdl libm libmpv-shared libplacebo librt linux-fstatfs linux-input-event-codes lua lua52 memfd_create optimize plain-gl posix posix-or-mingw pthreads pulse rubberband shaderc shaderc-shared stdatomic uchardet vaapi vaapi-drm vaapi-egl vaapi-vulkan vaapi-wayland vaapi-x-egl vaapi-x11 vdpau vector vt.h vulkan wayland wayland-protocols x11 xv zimg zlib
[cplayer] Reading config file /etc/mpv/encoding-profiles.conf
[cplayer] Applying profile 'default'...
[cplayer] Reading config file /home/ray/.config/mpv/config
[cplayer] Applying profile 'default'...
[cplayer] Setting option 'ao' = 'pulse' (flags = 4)
[cplayer] Setting option 'autofit-smaller' = '90%' (flags = 4)
[cplayer] Setting option 'autofit-larger' = '90%' (flags = 4)
[cplayer] Setting option 'volume-max' = '400' (flags = 4)
[cplayer] Setting option 'msg-level' = 'all=v' (flags = 8)
[cplayer] Setting option 'hwdec' = 'v4l2m2m-copy' (flags = 8)
[cplayer] Waiting for scripts...
[osd/libass] libass API version: 0x1502000
[osd/libass] libass source: commit: 0.15.2-0-gc967a5a3d9ec0d36af1148b3fdf2f307a21dd122
[osd/libass] Shaper: FriBidi 1.0.10 (SIMPLE) HarfBuzz-ng 3.2.0 (COMPLEX)
[osd/libass] Setting up fonts...
[osd/libass] Using font provider fontconfig
[osd/libass] Done.
[cplayer] Set property: shared-script-properties -> 1
[cplayer] Set property: shared-script-properties -> 1
[cplayer] Done loading scripts.
[cplayer] Running hook: ytdl_hook/on_load
[ytdl_hook] ytdl:// hook 
[ytdl_hook] not a ytdl:// url 
[cplayer] Set property: shared-script-properties -> 1
[ifo_dvdnav] Opening ./2minvideo.mp4
[bdmv/bluray] Opening ./2minvideo.mp4
[file] Opening ./2minvideo.mp4
[demux] Trying demuxers for level=normal.
[cplayer] Set property: shared-script-properties -> 1
[osd/libass] libass API version: 0x1502000
[osd/libass] libass source: commit: 0.15.2-0-gc967a5a3d9ec0d36af1148b3fdf2f307a21dd122
[osd/libass] Shaper: FriBidi 1.0.10 (SIMPLE) HarfBuzz-ng 3.2.0 (COMPLEX)
[osd/libass] Setting up fonts...
[lavf] Found 'mov,mp4,m4a,3gp,3g2,mj2' at score=100 size=2048.
[file] stream level seek from 131072 to 69688987
[osd/libass] Using font provider fontconfig
[osd/libass] Done.
[demux] Detected file format: mov,mp4,m4a,3gp,3g2,mj2 (libavformat)
[cplayer] Opening done: ./2minvideo.mp4
[find_files] Loading external files in ./
[cplayer] Running hook: ytdl_hook/on_preloaded
[lavf] select track 0
[lavf] select track 1
 (+) Video --vid=1 (*) (h264 1920x1080 49.313fps)
 (+) Audio --aid=1 --alang=ita (*) (ac3 2ch 48000Hz)
[vo/gpu] Probing for best GPU context.
[vo/gpu/opengl] Initializing GPU context 'wayland'
[vo/gpu/opengl] Initializing GPU context 'x11egl'
[vo/gpu/x11] X11 opening display: :0.0
[vo/gpu/x11] Display 0 (HDMI-1): [0, 0, 1440, 900] @ 74.984427 FPS
[vo/gpu/x11] Current display FPS: 74.984427
[vo/gpu/opengl] EGL_VERSION=1.4
[vo/gpu/opengl] EGL_VENDOR=Mesa Project
[vo/gpu/opengl] EGL_CLIENT_APIS=OpenGL OpenGL_ES 
[vo/gpu/opengl] Trying to create Desktop OpenGL context.
[vo/gpu/opengl] Choosing visual EGL config 0x9, visual ID 0x21
[vo/gpu/opengl] GL_VERSION='2.1 Mesa 21.3.3'
[vo/gpu/opengl] Detected desktop OpenGL 2.1.
[vo/gpu/opengl] GL_VENDOR='Broadcom'
[vo/gpu/opengl] GL_RENDERER='V3D 4.2'
[vo/gpu/opengl] GL_SHADING_LANGUAGE_VERSION='1.20'
[vo/gpu/opengl] Loaded extension GL_ARB_map_buffer_range.
[vo/gpu/opengl] Loaded extension GL_ARB_framebuffer_object.
[vo/gpu/opengl] Loaded extension GL_ARB_vertex_array_object.
[vo/gpu/opengl] Loaded extension GL_ARB_texture_rg.
[vo/gpu/opengl] Loaded extension GL_ARB_texture_float.
[vo/gpu/opengl] Loaded extension GL_ARB_sync.
[vo/gpu/opengl] Loaded extension GL_ARB_get_program_binary.
[vo/gpu/opengl] Loaded extension GL_ARB_buffer_storage.
[vo/gpu/opengl] Loaded extension GL_ARB_shader_image_load_store.
[vo/gpu/opengl] Loaded extension GL_ARB_uniform_buffer_object.
[vo/gpu/opengl] Loaded extension GL_ARB_shader_storage_buffer_object.
[vo/gpu/opengl] Loaded extension GL_ARB_arrays_of_arrays.
[vo/gpu/opengl] Loaded extension GL_ARB_debug_output.
[vo/gpu] Testing FBO format rgba16f
[vo/gpu] Using FBO format rgba16f.
[vo/gpu] Disabling HDR peak computation (one or more of the following is not supported: compute shaders=0, SSBO=0).
[vo/gpu] No advanced processing required. Enabling dumb mode.
[vo/gpu] Assuming 74.984427 FPS for display sync.
[vd] Container reported FPS: 49.312542
[vd] Codec list:
[vd]     h264 - H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
[vd]     h264_v4l2m2m (h264) - V4L2 mem2mem H.264 decoder wrapper
[vd] Opening decoder h264
[vd] Looking at hwdec h264_v4l2m2m-v4l2m2m-copy...
[vd] Trying hardware decoding via h264_v4l2m2m-v4l2m2m-copy.
[vd] Using underlying hw-decoder 'h264_v4l2m2m'
[ffmpeg/video] h264_v4l2m2m: Using device /dev/video10
[ffmpeg/video] h264_v4l2m2m: driver 'bcm2835-codec' on card 'bcm2835-codec-decode' in mplane mode
[ffmpeg/video] h264_v4l2m2m: requesting formats: output=H264 capture=YU12
[vd] Selected codec: h264 (H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10)
[vf] User filter list:
[vf]   (empty)
[ad] Codec list:
[ad]     ac3 - ATSC A/52A (AC-3)
[ad]     ac3_fixed (ac3) - ATSC A/52A (AC-3)
[ad] Opening decoder ac3
[ad] Requesting 1 threads for decoding.
[ad] Selected codec: ac3 (ATSC A/52A (AC-3))
[af] User filter list:
[af]   (empty)
[cplayer] Starting playback...
[file] stream level seek from 69816380 to 48
[cplayer] Set property: shared-script-properties -> 1
[af] [in] 48000Hz stereo 2ch floatp
[af] [userspeed] 48000Hz stereo 2ch floatp
[af] [userspeed] (disabled)
[af] [convert] 48000Hz stereo 2ch floatp
[ao] Trying audio driver 'pulse'
[ao/pulse] requested format: 48000 Hz, stereo channels, floatp
[ao/pulse] Library version: 15.0.0
[ao/pulse] Proto: 35
[ao/pulse] Server proto: 4294967295
[ao/pulse] Channel layouts:
[ao/pulse]  - #fl
[ao/pulse]  - #fr
[ao/pulse]  - #fc
[ao/pulse]  - #lfe
[ao/pulse]  - #bl
[ao/pulse]  - #br
[ao/pulse]  - #flc
[ao/pulse]  - #frc
[ao/pulse]  - #bc
[ao/pulse]  - #sl
[ao/pulse]  - #sr
[ao/pulse]  - #tc
[ao/pulse]  - #tfl
[ao/pulse]  - #tfc
[ao/pulse]  - #tfr
[ao/pulse]  - #tbl
[ao/pulse]  - #tbc
[ao/pulse]  - #tbr
[ao/pulse] result: stereo
[ao/pulse] device buffer: 4800 samples.
[ao/pulse] using soft-buffer of 9600 samples.
AO: [pulse] 48000Hz stereo 2ch float
[cplayer] AO: Description: PulseAudio audio output
[autoconvert] inserting resampler
[swresample] format change, reinitializing resampler
[swresample] 48000Hz stereo floatp -> 48000Hz stereo float
[af] [out] 48000Hz stereo 2ch float
Using hardware decoding (v4l2m2m-copy).
[vd] Decoder format: 1920x1080 [0:0] yuv420p auto/auto/auto/auto/auto CL=unknown
[vd] Using container aspect ratio.
[vf] [in] 1920x1080 yuv420p bt.709/bt.709/bt.1886/limited/display SP=1.000000 CL=mpeg2/4/h264
[vf] [userdeint] 1920x1080 yuv420p bt.709/bt.709/bt.1886/limited/display SP=1.000000 CL=mpeg2/4/h264
[vf] [userdeint] (disabled)
[vf] [autorotate] 1920x1080 yuv420p bt.709/bt.709/bt.1886/limited/display SP=1.000000 CL=mpeg2/4/h264
[vf] [autorotate] (disabled)
[vf] [convert] 1920x1080 yuv420p bt.709/bt.709/bt.1886/limited/display SP=1.000000 CL=mpeg2/4/h264
[vf] [convert] (disabled)
[vf] [out] 1920x1080 yuv420p bt.709/bt.709/bt.1886/limited/display SP=1.000000 CL=mpeg2/4/h264
VO: [gpu] 1920x1080 yuv420p
[cplayer] VO: Description: Shader-based GPU Renderer
[vo/gpu] reconfig to 1920x1080 yuv420p bt.709/bt.709/bt.1886/limited/display SP=1.000000 CL=mpeg2/4/h264
[vo/gpu] Resize: 1296x729
[vo/gpu] Window size: 1296x729 (Borders: l=0 t=0 r=0 b=0)
[vo/gpu] Video source: 1920x1080 (1:1)
[vo/gpu] Video display: (0, 0) 1920x1080 -> (0, 0) 1296x729
[vo/gpu] Video scale: 0.675000/0.675000
[vo/gpu] OSD borders: l=0 t=0 r=0 b=0
[vo/gpu] Video borders: l=0 t=0 r=0 b=0
[vo/gpu] Reported display depth: 8
[vo/gpu] Texture for plane 0: 1920x1080
[vo/gpu] Texture for plane 1: 960x540
[vo/gpu] Texture for plane 2: 960x540
[vo/gpu] Testing FBO format rgba16f
[vo/gpu] Using FBO format rgba16f.
[vo/gpu] No advanced processing required. Enabling dumb mode.
[cplayer] first video frame after restart shown
[cplayer] audio ready
[cplayer] starting audio playback
[ao/pulse] starting AO
[cplayer] playback restart complete @ 0.800000, audio=playing, video=playing
AV: 00:00:00 / 00:02:00 (1%) A-V: -0.000
[cplayer] Set property: shared-script-properties -> 1
[cplayer] Set property: shared-script-properties -> 1
[vo/gpu/x11] Disabling screensaver.
AV: 00:00:04 / 00:02:00 (3%) A-V:  0.000
[cplayer] EOF code: 5  
[cplayer] finished playback, success (reason 3)

Exiting... (Quit)

Kernel 5.10.64 --hwdec=v4l2m2m-copy not working:

[ray@pi4 Desktop]$ mpv --msg-level=all=v --hwdec=v4l2m2m-copy ./2minvideo.mp4 
[cplayer] Command line options: '--msg-level=all=v' '--hwdec=v4l2m2m-copy' './2minvideo.mp4'
[cplayer] mpv 0.34.0-dirty Copyright © 2000-2021 mpv/MPlayer/mplayer2 projects
[cplayer]  built on UNKNOWN
[cplayer] FFmpeg library versions:
[cplayer]    libavutil       56.70.100
[cplayer]    libavcodec      58.134.100
[cplayer]    libavformat     58.76.100
[cplayer]    libswscale      5.9.100
[cplayer]    libavfilter     7.110.100
[cplayer]    libswresample   3.9.100
[cplayer] FFmpeg version: n4.4.1
[cplayer] 
[cplayer] Configuration: /usr/bin/waf configure --prefix=/usr --confdir=/etc/mpv --enable-cdda --enable-dvb --enable-dvdnav --enable-libarchive --enable-libmpv-shared --disable-build-date --disable-caca
[cplayer] List of enabled features: alsa asm cdda cplayer cplugins cuda-hwaccel cuda-interop debug-build drm dvbin dvdnav egl egl-drm egl-helpers egl-x11 ffmpeg ffmpeg-aviocontext-bytes-read ffnvcodec gbm gbm.h gl gl-wayland glibc-thread-name glob glob-posix gpl iconv jack javascript jpeg lcms2 libarchive libass libavdevice libbluray libdl libm libmpv-shared libplacebo librt linux-fstatfs linux-input-event-codes lua lua52 memfd_create optimize plain-gl posix posix-or-mingw pthreads pulse rubberband shaderc shaderc-shared stdatomic uchardet vaapi vaapi-drm vaapi-egl vaapi-vulkan vaapi-wayland vaapi-x-egl vaapi-x11 vdpau vector vt.h vulkan wayland wayland-protocols x11 xv zimg zlib
[cplayer] Reading config file /etc/mpv/encoding-profiles.conf
[cplayer] Applying profile 'default'...
[cplayer] Reading config file /home/ray/.config/mpv/config
[cplayer] Applying profile 'default'...
[cplayer] Setting option 'ao' = 'pulse' (flags = 4)
[cplayer] Setting option 'autofit-smaller' = '90%' (flags = 4)
[cplayer] Setting option 'autofit-larger' = '90%' (flags = 4)
[cplayer] Setting option 'volume-max' = '400' (flags = 4)
[cplayer] Setting option 'msg-level' = 'all=v' (flags = 8)
[cplayer] Setting option 'hwdec' = 'v4l2m2m-copy' (flags = 8)
[cplayer] Waiting for scripts...
[osd/libass] libass API version: 0x1502000
[osd/libass] libass source: commit: 0.15.2-0-gc967a5a3d9ec0d36af1148b3fdf2f307a21dd122
[osd/libass] Shaper: FriBidi 1.0.10 (SIMPLE) HarfBuzz-ng 3.2.0 (COMPLEX)
[osd/libass] Setting up fonts...
[osd/libass] Using font provider fontconfig
[osd/libass] Done.
[cplayer] Set property: shared-script-properties -> 1
[cplayer] Set property: shared-script-properties -> 1
[cplayer] Done loading scripts.
[cplayer] Running hook: ytdl_hook/on_load
[ytdl_hook] ytdl:// hook 
[ytdl_hook] not a ytdl:// url 
[cplayer] Set property: shared-script-properties -> 1
[ifo_dvdnav] Opening ./2minvideo.mp4
[bdmv/bluray] Opening ./2minvideo.mp4
[file] Opening ./2minvideo.mp4
[demux] Trying demuxers for level=normal.
[cplayer] Set property: shared-script-properties -> 1
[osd/libass] libass API version: 0x1502000
[osd/libass] libass source: commit: 0.15.2-0-gc967a5a3d9ec0d36af1148b3fdf2f307a21dd122
[osd/libass] Shaper: FriBidi 1.0.10 (SIMPLE) HarfBuzz-ng 3.2.0 (COMPLEX)
[osd/libass] Setting up fonts...
[lavf] Found 'mov,mp4,m4a,3gp,3g2,mj2' at score=100 size=2048.
[file] stream level seek from 131072 to 69688987
[demux] Detected file format: mov,mp4,m4a,3gp,3g2,mj2 (libavformat)
[cplayer] Opening done: ./2minvideo.mp4
[osd/libass] Using font provider fontconfig
[osd/libass] Done.
[find_files] Loading external files in ./
[cplayer] Running hook: ytdl_hook/on_preloaded
[lavf] select track 0
[lavf] select track 1
 (+) Video --vid=1 (*) (h264 1920x1080 49.313fps)
 (+) Audio --aid=1 --alang=ita (*) (ac3 2ch 48000Hz)
[vo/gpu] Probing for best GPU context.
[vo/gpu/opengl] Initializing GPU context 'wayland'
[vo/gpu/opengl] Initializing GPU context 'x11egl'
[vo/gpu/x11] X11 opening display: :0.0
[vo/gpu/x11] Display 0 (HDMI-1): [0, 0, 1440, 900] @ 74.984427 FPS
[vo/gpu/x11] Current display FPS: 74.984427
[vo/gpu/opengl] EGL_VERSION=1.4
[vo/gpu/opengl] EGL_VENDOR=Mesa Project
[vo/gpu/opengl] EGL_CLIENT_APIS=OpenGL OpenGL_ES 
[vo/gpu/opengl] Trying to create Desktop OpenGL context.
[vo/gpu/opengl] Choosing visual EGL config 0x9, visual ID 0x21
[vo/gpu/opengl] GL_VERSION='2.1 Mesa 21.3.3'
[vo/gpu/opengl] Detected desktop OpenGL 2.1.
[vo/gpu/opengl] GL_VENDOR='Broadcom'
[vo/gpu/opengl] GL_RENDERER='V3D 4.2'
[vo/gpu/opengl] GL_SHADING_LANGUAGE_VERSION='1.20'
[vo/gpu/opengl] Loaded extension GL_ARB_map_buffer_range.
[vo/gpu/opengl] Loaded extension GL_ARB_framebuffer_object.
[vo/gpu/opengl] Loaded extension GL_ARB_vertex_array_object.
[vo/gpu/opengl] Loaded extension GL_ARB_texture_rg.
[vo/gpu/opengl] Loaded extension GL_ARB_texture_float.
[vo/gpu/opengl] Loaded extension GL_ARB_sync.
[vo/gpu/opengl] Loaded extension GL_ARB_get_program_binary.
[vo/gpu/opengl] Loaded extension GL_ARB_buffer_storage.
[vo/gpu/opengl] Loaded extension GL_ARB_shader_image_load_store.
[vo/gpu/opengl] Loaded extension GL_ARB_uniform_buffer_object.
[vo/gpu/opengl] Loaded extension GL_ARB_shader_storage_buffer_object.
[vo/gpu/opengl] Loaded extension GL_ARB_arrays_of_arrays.
[vo/gpu/opengl] Loaded extension GL_ARB_debug_output.
[vo/gpu] Testing FBO format rgba16f
[vo/gpu] Using FBO format rgba16f.
[vo/gpu] Disabling HDR peak computation (one or more of the following is not supported: compute shaders=0, SSBO=0).
[vo/gpu] No advanced processing required. Enabling dumb mode.
[vo/gpu] Assuming 74.984427 FPS for display sync.
[vd] Container reported FPS: 49.312542
[vd] Codec list:
[vd]     h264 - H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10
[vd]     h264_v4l2m2m (h264) - V4L2 mem2mem H.264 decoder wrapper
[vd] Opening decoder h264
[vd] Looking at hwdec h264_v4l2m2m-v4l2m2m-copy...
[vd] Trying hardware decoding via h264_v4l2m2m-v4l2m2m-copy.
[vd] Using underlying hw-decoder 'h264_v4l2m2m'
[ffmpeg/video] h264_v4l2m2m: Using device /dev/video10
[ffmpeg/video] h264_v4l2m2m: driver 'bcm2835-codec' on card 'bcm2835-codec-decode' in mplane mode
[ffmpeg/video] h264_v4l2m2m: requesting formats: output=H264 capture=YU12
[vd] Selected codec: h264 (H.264 / AVC / MPEG-4 AVC / MPEG-4 part 10)
[vf] User filter list:
[vf]   (empty)
[ad] Codec list:
[ad]     ac3 - ATSC A/52A (AC-3)
[ad]     ac3_fixed (ac3) - ATSC A/52A (AC-3)
[ad] Opening decoder ac3
[ad] Requesting 1 threads for decoding.
[ad] Selected codec: ac3 (ATSC A/52A (AC-3))
[af] User filter list:
[af]   (empty)
[cplayer] Starting playback...
[file] stream level seek from 69816380 to 48
[vf] filter input EOF
[vf] [userdeint] (disabled)
[vf] [autorotate] (disabled)
[vf] [convert] (disabled)
[vf] filter output EOF
[af] [in] 48000Hz stereo 2ch floatp
[af] [userspeed] 48000Hz stereo 2ch floatp
[af] [userspeed] (disabled)
[af] [convert] 48000Hz stereo 2ch floatp
[cplayer] video EOF reached
[ao] Trying audio driver 'pulse'
[ao/pulse] requested format: 48000 Hz, stereo channels, floatp
[ao/pulse] Library version: 15.0.0
[ao/pulse] Proto: 35
[ao/pulse] Server proto: 4294967295
[ao/pulse] Channel layouts:
[ao/pulse]  - #fl
[ao/pulse]  - #fr
[ao/pulse]  - #fc
[ao/pulse]  - #lfe
[ao/pulse]  - #bl
[ao/pulse]  - #br
[ao/pulse]  - #flc
[ao/pulse]  - #frc
[ao/pulse]  - #bc
[ao/pulse]  - #sl
[ao/pulse]  - #sr
[ao/pulse]  - #tc
[ao/pulse]  - #tfl
[ao/pulse]  - #tfc
[ao/pulse]  - #tfr
[ao/pulse]  - #tbl
[ao/pulse]  - #tbc
[ao/pulse]  - #tbr
[ao/pulse] result: stereo
[ao/pulse] device buffer: 4800 samples.
[ao/pulse] using soft-buffer of 9600 samples.
AO: [pulse] 48000Hz stereo 2ch float
[cplayer] AO: Description: PulseAudio audio output
[autoconvert] inserting resampler
[swresample] format change, reinitializing resampler
[swresample] 48000Hz stereo floatp -> 48000Hz stereo float
[af] [out] 48000Hz stereo 2ch float
[cplayer] audio ready
[cplayer] starting audio playback
[ao/pulse] starting AO
[vo/gpu/x11] Disabling screensaver.
[cplayer] playback restart complete @ 0.000000, audio=playing, video=eof
[cplayer] Set property: shared-script-properties -> 1
AV: 00:00:01 / 00:02:00 (1%) A-V:  0.000
[cplayer] EOF code: 5  
[vo/gpu/x11] Enabling screensaver.
[cplayer] finished playback, success (reason 3)

Exiting... (Quit)
[cplayer] Set property: shared-script-properties -> 1

### Additional context

Here is a link to a sample 2 minute .mp4 video that has the issue. Like I said above not all .mp4 has the issue but if I remember right I had to change config.txt to get the ones that did work. I believe I used a config used with kodi (dtoverlay=rpivid-v4l2) which I never did when the video was playing correctly.

https://drive.google.com/file/d/1_hC8hIGIQFnyBVwIEanwG_iEbgc7LsuD/view?usp=sharing

**Comment by stl3** [comment]
Have you gotten any further with this issue? I'm on the same pi model as you, using latest Dietpi and experiencing the same problem but on youtube videos with these formats:
```
ID  EXT  RESOLUTION FPS │   FILESIZE   TBR PROTO │ VCODEC        VBR ACODEC      ABR     ASR MORE INFO
───────────────────────────────────────────────────────────────────
137 mp4  1920x1080   30 │    2.11MiB 1803k https │ avc1.640028 1803k video only              1080p, mp4_dash
248 webm 1920x1080   30 │  965.31KiB  804k https │ vp9          804k video only              1080p, webm_dash

```
Although it didn't like vp9 on 720p, it still played both audio/video, and mp4/webm were fine with v4l2m2m at 720p
```
❯ vcgencmd version
Jan 20 2022 13:57:40
Copyright (c) 2012 Broadcom
version bd88f66f8952d34e4e0613a85c7a6d3da49e13e2 (clean) (release) (start_x)
```

**Comment by Dark-Sky** [comment]
No I have not. It seems to be kernel related. I can install an older kernel and it works fine but any kernel after that it will not work. I personally do not use it but some on our forums does. Waiting for some one here to get time to look in to it......

**Comment by stl3** [comment]
Yeah, I'm not finding much else info on it either, and when I searched about mpv and v4l2m2m in general I don't get much cept for these and no one else talking about the kernel issue. Guess we'll have to wait.
https://github.com/jellyfin/jellyfin-ffmpeg/issues/310
https://github.com/jellyfin/jellyfin/pull/7227
