### ISSUE TITLE
Yet another SD card problem -- Kingston 16GB class 10 micro SD

### ISSUE THREAD

**Issue by nejasmicz** [raspberrypi/linux#484]
My apologies if there's a better way of reporting problems with SD cards seeing they're quite common.
## OS and board specific stuff

I am using model B, not overclocked, headless.
**cmdline.txt**
`dwc_otg.lpm_enable=0 console=ttyAMA0,115200 kgdboc=ttyAMA0,115200 console=tty1 root=/dev/mmcblk0p6 rootfstype=ext4 elevator=deadline rootwait`
**config.txt**
`hdmi_ignore_hotplug=1`
`sdtv_mode=2`
**uname -a**
`Linux PITA 3.10.24+ #614 PREEMPT Thu Dec 19 20:38:42 GMT 2013 armv6l GNU/Linux`
(Raspbian installed using NOOBS)
**SD card info**
`man: 0x000002`
`oem: 0x544d`
`name: SA16G`
`hwrev: 0x1`
`fwrev: 0x2`
`serial: 0x20db7465`
**syslog from where the problem occurred**
`Jan  5 16:53:19 PITA kernel: [200665.920401] mmc0: resetting ongoing cmd 18DMA before 4096/4096 [2]/[32] complete
Jan  5 16:53:29 PITA kernel: [200675.921420] mmc0: Timeout waiting for hardware interrupt - cmd12.
Jan  5 16:53:39 PITA kernel: [200685.941794] mmc0: Timeout waiting for hardware interrupt - cmd13.
Jan  5 16:53:39 PITA kernel: [200685.941898] mmcblk0: error -110 sending status command, retrying
Jan  5 16:53:49 PITA kernel: [200695.962159] mmc0: Timeout waiting for hardware interrupt - cmd13.
Jan  5 16:53:49 PITA kernel: [200695.963262] mmcblk0: error -110 sending status command, retrying
Jan  5 16:53:59 PITA kernel: [200705.982525] mmc0: Timeout waiting for hardware interrupt - cmd13.
Jan  5 16:53:59 PITA kernel: [200705.983641] mmcblk0: error -110 sending status command, aborting
Jan  5 16:54:09 PITA kernel: [200716.002900] mmc0: Timeout waiting for hardware interrupt - cmd13.
Jan  5 16:54:20 PITA kernel: [200726.023278] mmc0: Timeout waiting for hardware interrupt - cmd13.
Jan  5 16:54:30 PITA kernel: [200736.043659] mmc0: Timeout waiting for hardware interrupt - cmd13.
Jan  5 16:54:40 PITA kernel: [200746.064006] mmc0: Timeout waiting for hardware interrupt - cmd13.
Jan  5 16:54:40 PITA kernel: [200746.065368] Buffer I/O error on device mmcblk0p6, logical block 2677852
Jan  5 16:54:40 PITA kernel: [200746.065416] EXT4-fs warning (device mmcblk0p6): ext4_end_bio:286: I/O error writing to inode 660326 (offset 28672 size 4096 starting block 2725981)
Jan  5 16:54:40 PITA kernel: [200746.065443] Buffer I/O error on device mmcblk0p6, logical block 2677853
Jan  5 16:54:40 PITA kernel: [200746.065468] EXT4-fs warning (device mmcblk0p6): ext4_end_bio:286: I/O error writing to inode 654162 (offset 40960 size 4096 starting block 2725982)
Jan  5 16:54:40 PITA kernel: [200746.065507] Buffer I/O error on device mmcblk0p6, logical block 2686243
Jan  5 16:54:40 PITA kernel: [200746.065534] EXT4-fs warning (device mmcblk0p6): ext4_end_bio:286: I/O error writing to inode 660330 (offset 0 size 4096 starting block 2734372)
Jan  5 16:54:40 PITA kernel: [200746.065979] Aborting journal on device mmcblk0p6-8.
Jan  5 16:54:40 PITA kernel: [200746.066107] mmc0: card 1234 removed
Jan  5 16:54:40 PITA kernel: [200746.066319] EXT4-fs error (device mmcblk0p6) in ext4_reserve_inode_write:4962: Journal has aborted
Jan  5 16:54:40 PITA kernel: [200746.075795] EXT4-fs error (device mmcblk0p6) in __ext4_new_inode:757: Journal has aborted
Jan  5 16:54:40 PITA kernel: [200746.086938] JBD2: Error -5 detected when updating journal superblock for mmcblk0p6-8.
Jan  5 16:54:40 PITA kernel: [200746.126701] EXT4-fs (mmcblk0p6): previous I/O error to superblock detected
Jan  5 16:54:40 PITA kernel: [200746.129562] EXT4-fs error (device mmcblk0p6) in ext4_dirty_inode:5081: Journal has aborted
Jan  5 16:54:40 PITA kernel: [200746.116745] EXT4-fs error (device mmcblk0p6): __ext4_journal_start_sb:62: Detected aborted journal
Jan  5 16:54:40 PITA kernel: [200746.154313] EXT4-fs (mmcblk0p6): Remounting filesystem read-only
Jan  5 16:54:40 PITA kernel: [200746.160593] EXT4-fs (mmcblk0p6): previous I/O error to superblock detected
Jan  5 16:54:40 PITA kernel: [200746.164304] EXT4-fs (mmcblk0p6): previous I/O error to superblock detected
Jan  5 16:54:40 PITA kernel: [200746.174332] journal commit I/O error`
## Status right now

RPi is running torrent client (rtorrent), samba with printer (cups, hplip) besides from the standard server stuff.

I've had to pull the plug to reset it (while we're talking about power, I'm using a 2.1A 5V power charger and a 1TB external usb 3.0 disk along the printer is connected to it) and it booted up fine with just one line in log mentioning any problems (as far as I can see):
`Jan  5 17:17:22 PITA kernel: [   11.351341] EXT4-fs (mmcblk0p6): recovery complete`
**/etc/fstab**
`/dev/mmcblk0p6  /               ext4    defaults,noatime  0       1`
**fdisk -l**
`/dev/mmcblk0p6          385024    30638079    15126528   83  Linux`

Haven't run rpi-update since I've installed raspbian via NOOBS because the same issue occurred when the raspbian was directly installed without the NOOBS with all and every update installed afterward and because I wanted to see if it's something introduced in newer versions of the kernel.

I've just run both apt-get dist-upgrade and rpi-update and rebooted so I'll update this if the issue occurs again; uname -a now looks like:
`Linux PITA 3.10.25+ #622 PREEMPT Fri Jan 3 18:41:00 GMT 2014 armv6l GNU/Linux`

If someone has got any suggestions regarding troubleshooting this, I'd gladly listen. So far, I've enabled remote logging to my linux laptop so the issues will get logged.

**Comment by ghollingworth** [comment]
So is this the first time you saw this problem?  Or is it repeatable, from
your uptime it looks like it took three days to hitŠ

Gordon

**Comment by nejasmicz** [comment]
Unfortunately, I can't say it's reproducible as it was sometimes working great for a week, sometimes a few days. I've had my doubts it was due to CPU and network load being high, but I can't say for sure.

I'll try adding bunch of torrents and see if it'll make it break any sooner.

**Comment by ghollingworth** [comment]
You could try playing around with overclocking to see if you can make it happen more, we shouldn't see this bug at all even with overclock...

Gordon

**Comment by nejasmicz** [comment]
Happened again:

`Jan  6 09:40:15 PITA kernel: [50882.211618] net_ratelimit: 16808 callbacks suppressed
Jan  6 09:40:15 PITA kernel: [50882.211708] smsc95xx 1-1.1:1.0 eth0: kevent 2 may have been dropped
Jan  6 09:40:15 PITA kernel: [50882.211919] smsc95xx 1-1.1:1.0 eth0: kevent 2 may have been dropped
Jan  6 09:40:15 PITA kernel: [50882.212027] smsc95xx 1-1.1:1.0 eth0: kevent 2 may have been dropped
Jan  6 09:40:15 PITA kernel: [50882.212411] smsc95xx 1-1.1:1.0 eth0: kevent 2 may have been dropped
Jan  6 09:40:15 PITA kernel: [50882.216622] smsc95xx 1-1.1:1.0 eth0: kevent 2 may have been dropped
Jan  6 09:40:15 PITA kernel: [50882.216721] smsc95xx 1-1.1:1.0 eth0: kevent 2 may have been dropped
Jan  6 09:40:15 PITA kernel: [50882.220804] smsc95xx 1-1.1:1.0 eth0: kevent 2 may have been dropped
Jan  6 09:40:15 PITA kernel: [50882.222000] smsc95xx 1-1.1:1.0 eth0: kevent 2 may have been dropped
Jan  6 09:40:15 PITA kernel: [50882.222094] smsc95xx 1-1.1:1.0 eth0: kevent 2 may have been dropped
Jan  6 09:40:16 PITA kernel: [50882.859662] smsc95xx 1-1.1:1.0 eth0: kevent 2 may have been dropped
Jan  6 11:51:23 PITA kernel: [58750.177253] mmc0: resetting ongoing cmd 18DMA before 4096/4096 [15]/[32] complete
Jan  6 11:51:33 PITA kernel: [58760.203026] mmc0: Timeout waiting for hardware interrupt - cmd12.`

Last boot up was done Jan 5 ~19:30, so an uptime of around 16h.

I cannot access it anymore via ssh so this is an excerpt from my laptop syslog (sent remotely from the PITA).

**Comment by popcornmix** [comment]
The fact you have USB errors and sdcard errors does make me suspect power supply.
Can you meaure voltage when under load:
http://elinux.org/R-Pi_Troubleshooting#Troubleshooting_power_problems

It's possibly the external disk is drawing too much power. Externally powered hard disks normally use the external power supply for 12V and take 5V from USB. Have you tried using a powered usb hub?

**Comment by nejasmicz** [comment]
I'll try in the following days to test the voltages. 
Do you reckon some dd on the external along with scp via network should suffice in the terms of load testing?

Haven't considered USB hub till now; have you got any recommendations?

Just for the info, the external drive is Silicon Power A30 USB 3.0 1TB.

**Comment by popcornmix** [comment]
Ideally you should measure voltage in the conditions the corruption occurs - e.g. running the torrent software.
Running something with 3d like quake or penguinspuzzle is also a good test.

For hub, see:
http://www.raspberrypi.org/archives/4803

**Comment by nejasmicz** [comment]
Quick update -- measured voltage with freshly installed Raspbian (and only that, no customization whatsoever) and it came around 4.97V. Upon attaching external USB drive, the voltage goes down to ~4.75V.

Please note that the drive hasn't been mounted nor was under any kind of user initiated load (meaning I just plugged it in); almost forgot to mention that when the RPi was powered on and raspbian installed, and I tried to plug in USB drive, the RPi went through a restart.

Is any of the following meriting a further testing with regards to power supply?

**Comment by ghollingworth** [comment]
4.75 is too low...  You need either a y-cable to power the hard drive or an external hub

**Comment by nejasmicz** [comment]
So, I'd need to use both USB ports on RPi for the external drive or to use externally powered USB hub? 

As for me, we can close this ticket now.

**Comment by ghollingworth** [comment]
No using both ports won't do anything, the idea would be to power the hard drive from an external power source

Gordon

On 7 Jan 2014, at 18:11, "nejasmicz" <notifications@github.com<mailto:notifications@github.com>> wrote:

So, I'd need to use both USB ports on RPi for the external drive or to use externally powered USB hub?

As for me, we can close this ticket now.

##

**Comment by nejasmicz** [comment]
Alright, in that case I'm closing this ticket and will try to update once I get a USB hub or some other way of powering my setup.

Thanks, guys, for all your help!
