### ISSUE TITLE
New rpi-5.17.y branch

### ISSUE THREAD

**Issue by Dark-Sky** [raspberrypi/linux#4842]
### Describe the bug

New New rpi-5.17.y branch seems to have 5.16.1 Makefile. Is it a WIP?

### Steps to reproduce the behaviour

Look at the Makefile

### Device (s)

Raspberry Pi 4 Mod. B

### System

Does not matter.

### Additional context

Makefile snip:

```
# SPDX-License-Identifier: GPL-2.0
VERSION = 5
PATCHLEVEL = 16
SUBLEVEL = 1
EXTRAVERSION =
NAME = Gobble Gobble
```

**Comment by popcornmix** [comment]
Yes.

**Comment by popcornmix** [comment]
I've pushed a version that builds and boots on pi4. Kodi runs. kms and fkms seem to work.
But, this is bleeding edge. Anything else may or may not work.

**Comment by Dark-Sky** [comment]
Thanks and understood.
