### ISSUE TITLE
Bullseye 64-bit 6x slower than 32-bit on RPi Zero 2.

### ISSUE THREAD

**Issue by Qengineering** [raspberrypi/linux#4876]
### Describe the bug

The 64-bit version of Bullseye runs very slow on a Raspberry Pi Zero 2 compared to the 32-bit Bullseye version.

### Steps to reproduce the behaviour

1. Flash a 64-bit Bullseye OS on a new SD.
2. Boot as usual, following the startup instructions.
3. Get WiFi working and install the latest updates.
4. Fire-up Chromium and see how long it takes to load the default [home page](https:://www.raspberrypi.com/).
5. Repeat the same steps with a 32-bit Bullseye.
6. Repeat both steps with a RPi 3 B+ (1 GB RAM, 1.4 GHz).

The outcome:

![chromium_timing](https://user-images.githubusercontent.com/44409029/152792417-ea11793f-24f0-4880-97b3-351a706eedfd.png)

Chromium was chosen here solely for the reproducibility of the test.

Note the almost identical load times of the 32-bit RPi 3 and RPi Zero 2 once corrected for their clock frequency.

Not only does Chromium suffers this lack of speed, all other programs as well. For instance gcc compile times.

![gcc_timing3](https://user-images.githubusercontent.com/44409029/152797404-b8a90525-763a-44fd-b42f-3c0e7352f977.png)

### Device (s)

Raspberry Pi Zero 2 W

### System

![image](https://user-images.githubusercontent.com/44409029/152791119-139027f6-5880-404e-a18e-c03a27fc26fa.png)

**Comment by pelwell** [comment]
The 64-bit image is not recommended on Zero 2 W - RAM is too constrained - but run the Lite image if you must.

**Comment by JamesH65** [comment]
Also, Chromium is a major memory hog, and the 512 on the Zero is simply not enough to run it with any sort of decent performance.

**Comment by Qengineering** [comment]
@JamesH65 ,
You'd expect the same "memory hunger" regardless of whether you're running a 32 or 64-bit OS on the RPi Zero 2.

**Comment by popcornmix** [comment]
> You'd expect the same "memory hunger" regardless of whether you're running a 32 or 64-bit OS on the RPi Zero 2.

No. 64-bit requires more memory than 32-bit. Compiled code is larger. Basic types (like pointers) are larger.

**Comment by pelwell** [comment]
Why? Those 64-bit pointers do take up more space, and when you are balanced on the edge of not-enough-memory, every byte counts.
