### ISSUE TITLE
symlink error: file name too long, again

### ISSUE THREAD

**Issue by oneway3124** [raspberrypi/linux#488]
My environment is windows 7, then installing the virtualbox ,ubuntu 12.04 on it.
1. I download the zip from https://github.com/raspberrypi/linux,
2. I copy the to ubuntu , my ubuntu cannot connect to internet.
3. unzip linux-rpi-3.10.y.zip
4. symlink error: File name too long;
5. I search some information about this issue from internet https://github.com/raspberrypi/linux/issues/34
6. how can I download the  .tar.gz format .

Thanks a lot!

Thanks a lot!
Best Regards,
David Wang | Engineer, SW |VOIP: 3163571  | Mobile: +86-159-0810-6107 | E-mail: oneway3124@gmail.com David.Wang@harman.com,

**Comment by popcornmix** [comment]
Try https://github.com/raspberrypi/linux/archive/rpi-3.10.y.tar.gz

**Comment by oneway3124** [comment]
Thanks for your support! This issue has been fixed.
