### ISSUE TITLE
Please enable sysfsgpio in OpenOCD

### ISSUE THREAD

**Issue by VP-** [raspberrypi/linux#489]
OpenOCD has a compile-time option --enable-sysfsgpio which allows the Raspberry Pi GPIO pins to be used for JTAG-debugging of other chips/boards. Please enable it in the Jessie/testing version of the openocd package. What's the point of having a Raspberry-specific distribution, if not to enable the Raspberry-specific features?

**Comment by asb** [comment]
This should be raised in the Raspbian subforum on rasperrypi.org or the Raspbian bug tracker (http://raspbian.org/RaspbianBugs). This repository is purely for issues with the Linux kernel for Pi.
