### ISSUE TITLE
Can't read BME280 Correctly Using DTOverlay But via Python Works!

### ISSUE THREAD

**Issue by Jibun-no-Kage** [raspberrypi/linux#4896]
Enable DTOverLay for BME280 in /boot/config.txt...

dtparam=i2c_arm=on
dtoverlay=i2c-sensor,bme280,addr=0x77

\# i2cdetect -y 1
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:                         -- -- -- -- -- -- -- --
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
50: -- -- -- -- -- -- -- 57 -- -- -- -- -- -- -- --
60: -- -- -- -- -- -- -- -- 68 -- -- -- -- -- -- --
70: -- -- -- -- -- -- -- UU

And thus...
 
/sys/bus/i2c/devices/i2c-1/1-0077/iio:device0

Doing above, I get something weird...

\# dmesg | grep bmp
[   40.014592] bmp280 1-0077: supply vddd not found, using dummy regulator
[   40.016315] bmp280 1-0077: supply vdda not found, using dummy regulator
[  366.730552] bmp280 1-0077: reading temperature skipped

But something is working given i2cdetect reports UU for address 0x77.  And...

\# ls -l /sys/bus/i2c/devices/i2c-1/1-0077/iio:device0
total 0
-r--r--r-- 1 root root 4096 Feb 17 17:06 dev
-rw-r--r-- 1 root root 4096 Feb 17 17:06 in_humidityrelative_input
-rw-r--r-- 1 root root 4096 Feb 17 17:06 in_humidityrelative_oversampling_ratio
-rw-r--r-- 1 root root 4096 Feb 17 17:06 in_pressure_input
-rw-r--r-- 1 root root 4096 Feb 17 17:06 in_pressure_oversampling_ratio
-rw-r--r-- 1 root root 4096 Feb 17 17:06 in_temp_input
-rw-r--r-- 1 root root 4096 Feb 17 17:06 in_temp_oversampling_ratio
-r--r--r-- 1 root root 4096 Feb 17 17:06 name
lrwxrwxrwx 1 root root    0 Feb 17 17:06 of_node -> ../../../../../../../firmware/devicetree/base/soc/i2c@7e804000/bme280@77
drwxr-xr-x 2 root root    0 Feb 17 17:06 power
lrwxrwxrwx 1 root root    0 Feb 17 17:06 subsystem -> ../../../../../../../bus/iio
-rw-r--r-- 1 root root 4096 Feb 17 17:06 uevent

And... I seem to be able to read the sensor for temperature and pressure...

\# cat /sys/bus/i2c/devices/i2c-1/1-0077/iio:device0/in_pressure_input
102.316898437
\# cat /sys/bus/i2c/devices/i2c-1/1-0077/iio:device0/in_temp_input
26380

But I can't read humidity?

\# cat /sys/bus/i2c/devices/i2c-1/1-0077/iio:device0/in_humidityrelative_input
cat: '/sys/bus/i2c/devices/i2c-1/1-0077/iio:device0/in_humidityrelative_input': Input/output error

If I remove the overlay, and use say python to read the sensor, everything works!  For example my python script output...
Sensor BME280 (BMX@77), Method BMX, Index 07, Device 0x77, Temperature 25.2490234375 C, Humidity 22.80308219212777 %, Pressure 1023.1955739321498 hPA

**Comment by 6by9** [comment]
Duplicates https://forums.raspberrypi.com/viewtopic.php?p=1975145

**Comment by pelwell** [comment]
The behaviour is as if you were using a BMP280 (not a BME280), but if that were the case the driver should have complained - and presumably the Python script would not have worked.

Please comment out the `dtvoverlay=i2c-sensor` line in config.txt, reboot, and run the following (harmless) commands:
```
sudo dmesg -C                                                     # Clear out the kernel messages for this boot
sudo sh -c "echo 1 > /sys/kernel/debug/tracing/events/i2c/enable"
sudo dtoverlay i2c-sensor bme280 addr=0x77
dmesg
cat /sys/bus/i2c/devices/1-0077/iio\:device0/in_temp_input
sudo sh -c "echo 0 > /sys/kernel/debug/tracing/events/i2c/enable"
sudo cat /sys/kernel/debug/tracing/trace
```
Post the output you get.

P.S. The `dtparam=i2c_arm=on` is unnecessary here - the `i2c-sensor` overlay enables I2C1.

**Comment by pelwell** [comment]
You might prefer to replace the last line with `sudo cat /sys/kernel/debug/tracing/trace > trace.txt`, then the output will end up in `trace.txt`.

**Comment by Jibun-no-Kage** [comment]
Ah... I will give this shot ASAP.  Thanks.  Ok, got a chance to do this right away. Attached is the trace capture
[trace.txt](https://github.com/raspberrypi/linux/files/8109739/trace.txt).

And this going to sound odd, but just as curious thought, I tried reading the temperature, pressure, and humidity via the overlay, as manually loaded for the trace.  Yes, i2cdect -y 1 reported UU for the i2c device address as expected.

And I was able to read the temperature, pressure, and... humidity.  Have not changed anything, hardware or software wise.  So, not sure if the trace is going to show anything of significance?

\# cat /sys/bus/i2c/devices/1-0077/iio\:device0/in_temp_input
27190
\# cat /sys/bus/i2c/devices/1-0077/iio\:device0/in_pressure_input
100.477964843
\# cat /sys/bus/i2c/devices/1-0077/iio\:device0/in_humidityrelative_input
23358

I am going to re-enable overlay load via config.txt, and do some more testing.  This has me scratching my head, because I checked the wiring, setup, etc., several times before ever opening this issue.  Color me surprised.  I even turned on fsck.mode=force to validate the SD card.

**Comment by pelwell** [comment]
Editing posts for typos etc. is fine but they don't trigger a notification, so I had no idea that you had added some real information.

The trace shows it accessing the ID register and retrieving 0x60 - the chip identifier for the BME280. All the subsequent accesses complete without any errors, so everything seems to be working.

Let me know how you get on, but I'm hoping it behaves for you from now on.

**Comment by Jibun-no-Kage** [comment]
Ah, good to know about the notification.  Yeah, appears I can could not recreate the issue, it was odd to begin with, in that I could read some values but not others.  Usually if the i2c bus is hung up or wire fault you lose all communication.  I have since tested the device, with the same sensors and connections... no changes other than a reboot and a different SD card, but same image.  Even the original SD card tested, passed, is now back in the device, but reimaged.  Odd.  Regardless, thanks for the proactive response... and now, I know how to generate an overlay trace, which is good know, never mind... just cool.
