### ISSUE TITLE
Compression patch error

### ISSUE THREAD

**Issue by alphaonex86** [raspberrypi/linux#49]
Hello, with the last compression to try fix the compression:
arch/arm/mach-bcm2708/include/mach/uncompress.h:61 error: UART0_CLOCK underclared

**Comment by keylevel** [comment]
You need to apply the patch at https://github.com/bootc/linux-rpi-orig/commit/bff06d1c4d3fe1edb8522dfe03459fe1e604a521 as well.

With this in, it looks as if compressed kernels are now working again.

**Comment by popcornmix** [comment]
Apologies. I missed a bit. Please try again.

**Comment by agherzan** [comment]
UART0_CLOCK is not defined anywhere as i see....

**Comment by popcornmix** [comment]
Sorry, hadn't pushed.. Try now..

**Comment by agherzan** [comment]
Confirmed.

**Comment by alphaonex86** [comment]
That's work now, compressed kernel work too
