### ISSUE TITLE
Ugly Screen Tearing on Kernel 5.15.X and up with OGL apps in DRM

### ISSUE THREAD

**Issue by bluestang2006** [raspberrypi/linux#4901]
### Describe the bug

I am seeing very bad screen tearing in OpenGL apps, specifically vkQuake3, when using the app in KMS+DRM aka console.

This behavior is not seen in an X11 session, and it not seen using the Vulkan driver in either session (X11 or KMS+DRM).

As I said before it's strictly being seen in DRM using an OGL context. 

Switching back to the latest stable firmware (5.10) the issue goes away.

### Steps to reproduce the behaviour

This is easily reproducible if you compile/setup [vkQuake3](https://github.com/suijingfeng/vkQuake3) and set the default renderer to opengl1 - `seta cl_renderer "opengl1"`. This is best done by creating an autoexec.cfg in the baseq3 folder and running the app in DRM.

### Device (s)

Raspberry Pi 4 Mod. B

### System

64-bit RPiOS (Bullseye)
vc4-kms-v3d
kernel 5.15 (latest master branch)
NOTE: I am using the latest MESA git for the v3d+v3dv drivers.

**Comment by mripard** [comment]
It seems like it could be the same issue than the one we fixed in #4571 

Interestingly, that patch never got applied to the rpi-5.15.y branch, which might explain why it works on 5.10 but doesn't on 5.15.

@pelwell

**Comment by pelwell** [comment]
Being discussed offline, but this was one of the many patches that doesn't apply when moving from 5.10 to 5.15.

**Comment by pelwell** [comment]
Or rather, it applies but then produces a build error due to `dma_resv_get_excl` no longer being defined.

**Comment by pelwell** [comment]
@mripard Are you going to update this patch for 5.15?

**Comment by mripard** [comment]
Yes, I was planning on sending a new version but got distracted by the writeback issues, I'll send a PR today or on monday

**Comment by pelwell** [comment]
Sure - when you're ready.

**Comment by mripard** [comment]
I've just done it with PR #4925

**Comment by bluestang2006** [comment]
#4925 fixed this issue. Tested with Quake3e and another OpenGL app called RetroFE and the vysnc issue is resolved. As a bonus this patch was tested on the rpi-5.16.y branch and everything looked great.

**Comment by pelwell** [comment]
Thanks - forward-ported to rpi-5.16.y and rpi-5.17y.
