### ISSUE TITLE
USB Tethering not working after cable reconnection

### ISSUE THREAD

**Issue by Adrian-Rosoga** [raspberrypi/linux#492]
Raspbian Wheezy - Linux adipi1 3.10.26+ #628 PREEMPT Fri Jan 10 17:18:51 GMT 2014 armv6l GNU/Linux

I'm connecting from a Samsung Galaxy S2 phone using USB Tethering. The connectivity is ok until the USB cable is disconnected and reconnected.

After re-enabling USB Tethering the Pi is no longer reachable, the SSH client on the phone reports:
failed to connect to /192.168.42.42 (port 22): connect failed: EHOSTUNREACH (No route to host)

Only by rebooting the Pi I was able to reconnect. Unfortunately rebooting is not always desirable/possible.

Although I haven't tried with a different device other than the above phone, I don't think the issue was with the phone as cable reconnection was not a problem when doing the same with a machine running Fedora (3.6.11-4.fc16.x86_64 #1). This looks like a Pi issue.

I've followed the USB Tethering recipe from http://www.raspberrypi.org/phpBB3/viewtopic.php?t=18916&p=331361. This assigns a static address:
iface usb0 inet static
address 192.168.42.42
...

One difference between the Pi and the Fedora machine is that an arp entry appears in Fedora after 'USB tethering' is enabled on the phone. The entry appears on the Pi after an SSH client (or other) is started.
After cable reconnection no entry in arp for usb0 appears on the Pi.

arp -a
? (192.168.42.129) at b6:f9:66:ec:2e:21 [ether] on usb0
...

It appears that after cable reconnection usb0 comes up but no longer gets an IP address:
usb0      Link encap:Ethernet  HWaddr 02:3a:68:33:6d:5a  
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:123 errors:0 dropped:6 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:3660 (3.5 KiB)  TX bytes:0 (0.0 B)

Please let me know if any other detail needed. Would be great to have this fixed.

My other point is that the Pi should have support/the right configuration for USB tethering out of the box, without extra configuration. The Pi would be used headless in many cases and having the ability to connect to it when needed is important.

Thanks,

Adrian

**Comment by P33M** [comment]
fiq_fsm should no longer have dropouts.
