### ISSUE TITLE
Manufacture isn't show in pi zero 2 wch wifi network 

### ISSUE THREAD

**Issue by hotrungnhan** [raspberrypi/linux#4933]
### Describe the bug

![image](https://user-images.githubusercontent.com/40029631/157491573-379b2e64-b004-4d6f-954e-e5740a201ba5.png)
I need to use some tool like advanced ip scanner to know my pi IP (192.168.1.11 in the image) using wifi network
so I used the manufacturer's name to distinguish this device. 
Sorry if the problem is not in this report.
my pi is like brand a new device bought from cytron, they print in the plastic bag is pi zero 2 WCH, i cant found it infomation any where.But the one thing i known pinout didn't recognize my device as the right name. Hope this information can help your guy
![image](https://user-images.githubusercontent.com/40029631/157492827-26a7a5b4-9fe7-4691-8212-fb03e9785517.png)

### Steps to reproduce the behaviour

Show the manufacture name in wifi network

### Device (s)

Raspberry Pi Zero 2 W

### System

Raspberry Pi reference 2022-01-28
Generated using pi-gen, https://github.com/RPi-Distro/pi-gen, f01430c9d8f67a4b9719cc00e74a2079d3834d5d, stage2
Jan 20 2022 13:58:22
Copyright (c) 2012 Broadcom
version bd88f66f8952d34e4e0613a85c7a6d3da49e13e2 (clean) (release) (start)
Linux raspberrypi 5.10.92-v7+ #1514 SMP Mon Jan 17 17:36:39 GMT 2022 armv7l GNU/Linux

**Comment by pelwell** [comment]
`36:07:3b:2c:0e:ac` is not from any of Raspberry Pi's OUIs. Is that address the same every boot, or does it change?

**Comment by 6by9** [comment]
To expand on pelwell's comment, the manufacturer name you are seeing is simply a lookup in a table of assigned Organizational Unique Identifiers (OUI), which is used in the first 3 bytes of the 6 byte MAC address.

Raspberry Pi have a number of OUIs allocated, and the onboard wifi of a Pi02 should use one of them. Checking mine it is e4:5f:01, which looks up correctly to Raspberry Pi Trading Ltd - https://ouilookup.com/mac/E4-5F-01.
The other two we use are https://ouilookup.com/mac/B8-27-EB and https://ouilookup.com/mac/DC-A6-32

What does ```ip addr``` print out on the Pi?
If you're not using the onboard wifi, then the address you're seeing is the address assigned to your wifi dongle.

**Comment by hotrungnhan** [comment]
> `36:07:3b:2c:0e:ac` is not from any of Raspberry Pi's OUIs. Is that address the same every boot, or does it change?

![image](https://user-images.githubusercontent.com/40029631/157509513-5332182f-d028-4c43-9a5d-b54fd60b19d5.png)
oh sorry,this it the last day ip, it now actually is 192.168.1.19 with mac address is  e4:5f:01:4d:52:30.

> What does `ip addr` print out on the Pi? If you're not using the onboard wifi, then the address you're seeing is the address assigned to your wifi dongle.

This 100% percent the on board  in rasberry pi zero 2 w , but i found on the internet it use a wifi chip from synapse SYN43436 instead of chip from broadcom like BCM43143 in pi zero v1 , could it be the problem ? 
https://www.jeffgeerling.com/blog/2021/look-inside-raspberry-pi-zero-2-w-and-rp3a0-au

**Comment by 6by9** [comment]
> oh sorry,this it the last day ip, it now actually is 192.168.1.19 with mac address is e4:5f:01:4d:52:30.

In which case your scan tool has an out of date list of OUIs.
As linked above, e4:5f:01 is correctly registered as being Raspberry Pi Trading Ltd.

**Comment by hotrungnhan** [comment]
> > oh sorry,this it the last day ip, it now actually is 192.168.1.19 with mac address is e4:5f:01:4d:52:30.
> 
> In which case your scan tool has an out of date list of OUIs. As linked above, e4:5f:01 is correctly registered as being Raspberry Pi Trading Ltd.

it cant be , last serveral day , i was use pi zero  w  v1.3 , it prefix is alike,manufacture still show up . then i sell it and bought pi zero 2 .hold on ,i will check in  the different tools

**Comment by hotrungnhan** [comment]
any way tks your guy to explain me

**Comment by 6by9** [comment]
Pi Zero W used the older B8-27-EB OUI. That is the same one that was used on the original Pi model B 10 years ago.
E4:5F:01 is a newer allocation.

**Comment by hotrungnhan** [comment]
ah < that is it , tks you too much @@ love u

**Comment by hotrungnhan** [comment]
![image](https://user-images.githubusercontent.com/40029631/157511009-beb2fa10-7f4f-4cc0-8a7e-a01b7cd50049.png)
woa it work , you are so great @6by9 now i can close this thread .... one more time thank you
