### ISSUE TITLE
rpi-5.15.y branch is frequently rebased

### ISSUE THREAD

**Issue by kraj** [raspberrypi/linux#4944]
### Describe the bug

Repo is defaulting to `rpi-5.15.y` branch on checkout, but the branch gets rebased frequently, in Yocto we upgraded to use 5.15 as default kernel for rpi machines but we lock to a known revision and rebase breaks that since the SHAs get re-written
so my question is, whats the ETA for this branch to become publicly consumable ?

### Steps to reproduce the behaviour

build yocto after one week of kernel SRCREV bump.

### Device (s)

Raspberry Pi 4 Mod. B

### System

cant find the revision to checkout see
https://github.com/agherzan/meta-raspberrypi/issues/1037#event-6262566909

**Comment by popcornmix** [comment]
We are close to switching to 5.15 for apt, so there will be no more rebases.
Next upstream bump will be a merge.

**Comment by kraj** [comment]
thanks @popcornmix
