### ISSUE TITLE
how to make filesystem?

### ISSUE THREAD

**Issue by oneway3124** [raspberrypi/linux#496]
I know that bootcode.bin(from broadcom), kernel.img produce method.
But how can I make file system ? or intergrate the bootcode.bin and kernel.img and other things into the release version ?

Thanks a lot!
Best Regards,
David.Wang
E-mail:oneway3124@gmail.com

**Comment by popcornmix** [comment]
This system is for reporting bugs in the linux kernel.
For general questions you should ask on the forum:
http://www.raspberrypi.org/phpBB3/index.php
