### ISSUE TITLE
Can't boot kernel use UEFI + Grub2 Invalid magic number 

### ISSUE THREAD

**Issue by maximdogonov** [raspberrypi/linux#4968]
### Describe the bug

I try build kernel for boot system from USB drive: 

On USB Drive we install UEFI + GRUB2 and make settings 

menuentry 'Boot Plazma (kernel: debian)' --class gnu-linux --class os {
	set prefix=(hd0,gpt1)
        set root=(hd0,gpt1)
	insmod ext2
	linux /boot/kernel/vmlinuz-5.15.30-v7l+ root=/dev/mmcblk0p2 panic=15  
	initrd /boot/kernel/initrd.img-5.15.30-v7l+

When Grub2 try load kernel, we got errors: Invalid magic number 

```
file vmlinuz-5.15.30-v7l+
         vmlinuz-5.15.30-v7l+: data
```

May be need turn on some option? 

Thank you! 

 

### Steps to reproduce the behaviour

apt install git bc bison flex libssl-dev make libncurses5-dev raspberrypi-kernel-headers
git clone --depth=1 https://github.com/raspberrypi/linux
cd linux
KERNEL=kernel7l
make bcm2711_defconfig
CONFIG_LOCALVERSION="-v7l-PLAZMA_KERNEL"
make menuconfig

make -j5 bzImage modules dtbs
make install 

### Device (s)

Raspberry Pi 4 Mod. B

### System

Raspberry Pi reference 2021-01-20
Generated using pi-gen, https://github.com/RPi-Distro/pi-gen, c20a7f5878dcad0c49e931213a2d5f1de72326ae, stage4.5

vcgencmd version
Dec  1 2021 15:01:54 
Copyright (c) 2012 Broadcom
version 71bd3109023a0c8575585ba87cbb374d2eeb038f (clean) (release) (start)

uname -a
Linux linuxcnc 4.19.71-rt24-v7l+ #1 SMP PREEMPT RT Fri Jan 1 21:15:16 GMT 2021 armv7l GNU/Linux

**Comment by timg236** [comment]
Sorry, we don't support GRUB or U-BOOT. 

You could try asking on the Advanced Users forum https://forums.raspberrypi.com/viewforum.php?f=29&sid=576800a53ecce04ce8556f2ce4359ef5
