### ISSUE TITLE
Unable to unload modules compiled on the RasPi for 3.10.26+

### ISSUE THREAD

**Issue by MrEngman** [raspberrypi/linux#498]
Hi,

I'm having an issue with modules I am compiling on my RasPi for versions 3.10.y. I can compile them without errors and they appear to operate OK but as an example the command cat /proc/modules reports they are marked as permanent and they can not be unloaded

8812au 1098550 0 [permanent], Live 0xbf23b000 (O)
8192cu 547346 0 [permanent], Live 0xbf19b000 (O)
8188eu 790078 0 [permanent], Live 0xbf0b9000 (O)

This is even if CONFIG_MODULE_UNLOAD=y is included in the linux source .config file. The module I am really interested in is 8188eu.ko but to check things out I compiled the module 8192cu.ko. This module is included in the Raspbian image and does not have this problem. The 8192cu module I compiled on the RasPi compiles without errors, however it ends up as marked permanent when loaded and cannot be unloaded if I use command sudo rmmod 8192cu, whereas the 8192cu module included with the kernel image does not have this problem and can be unloaded at will.

Attempting to unload these modules, using for example command sudo rmmod 8192cu, gives the error

libkmod: ERROR ../libkmod/libkmod-module.c:753 kmod_module_remove_module: could not remove '8192cu': Device or resource busy
Error: could not remove module 8192cu: Device or resource busy

The error for the 8188eu module is the same, other than the module name shown. Further info https://github.com/lwfinger/rtl8188eu/issues/37#issuecomment-32213965.

It has been suggested that I should cross compile on a PC and use the toolchain included in the Raspberry Pi Tools git repository tools/arm-bcm2708/gcc-linaro-arm-linux-gnueabihf-raspbian. I do not have another Linux machine I can do this on and anyway I find compiling individual modules directly on the Pi is convenient and does not usually take too long.

Can someone help me out with this issue and perhaps explain why I am getting this problem and provide a fix or maybe suggest how I can use the linaro tools as the defaults for compiling code to see if that helps?

Some additional info I have been shown is:- 

gcc used to compile the kernel:

$ cat /proc/version 
Linux version 3.10.26+ (dc4@dc4-arm-01) (gcc version 4.7.2 20120731 (prerelease) (crosstool-NG linaro-1.13.1+bzr2458 - Linaro GCC 2012.08) ) #628 PREEMPT Fri Jan 10 17:18:51 GMT 2014

gcc provided in raspberrypi/tools:

$ ./arm-linux-gnueabihf-gcc -v 2>&1 | grep 'gcc version'
gcc version 4.7.2 20120731 (prerelease) (crosstool-NG linaro-1.13.1+bzr2458 - Linaro GCC 2012.08)

gcc provided on raspbian pi:

$ gcc -v 2>&1 | grep 'gcc version'
gcc version 4.6.3 (Debian 4.6.3-14+rpi1) 

This could explain why there is a problem and perhaps the toolchain included with the Raspberry Pi should be updated to match the one used to compile the kernel so modules can be compile with the same toolchain used to compile the kernel.

MrEngman

**Comment by MrEngman** [comment]
I've finally found a solution - compile the modules on my WINDOWS laptop, yes Windows laptop.

Doesn't say much for the Raspberry Pi and the toolchain included in the latest versions of Raspbian.

I have Oracle VM VirtualBox on my laptop wth an old version of Debian. Did a git clone of linux, firmware and tools and bumbled through the RPI Kernel Compilation instructions, primarily section 4, in the RPi Wiki.

I ended up with modules that worked and I was able to unload them which wasn't possible when the modules were compiled directly on the RPi.

**Comment by popcornmix** [comment]
I wonder if it is gcc version. Can you try with gcc 4.7 on Pi (sudo apt-get install gcc-4.7) and compile with that?

**Comment by MrEngman** [comment]
OK installed gcc-4.7 and compiled the rtl8188eu module and it failed to unload, HOWEVER, I checked directory /usr/bin and there was a symlink /usr/bin/gcc -> gcc-4.6. So changed the symlink to /usr/bin/gcc -> gcc-4.7 and recompiled the module.

And hey presto the module loaded and I was now able to unload it. gcc-4.7 seems to have fixed it. 

That seems to have done the trick, Thanks

**Comment by MrEngman** [comment]
Just tried with a couple more modules from the OP that I'd had problems with and they are now OK as well.

Guess the answer is gcc-4.7. Certainly makes life, with the Pi, much less complicated.

**Comment by popcornmix** [comment]
I guess it's a compatability issue between building kernel and modules with different gcc versions.
Surprised it only broke things a bit.

I don't suppose there's anything that can be done in this repo, so okay to close?

**Comment by MrEngman** [comment]
Guess so. At least I have a fix.
