### ISSUE TITLE
Build IIO software trigger modules?

### ISSUE THREAD

**Issue by nwf** [raspberrypi/linux#4984]
### Describe the bug

By making use of the `i2c-sensor` overlay for a `bme680`, the `iio` subsystem creates files in `/sys` for the sensor's outputs, which is lovely... but neglects the entire kernel-side infrastructure for collecting samples in ring buffers.  The `bme680` does not, itself, export any triggers for this machinery, so it would be nice to have software-defined triggers available.  Specifically, I think that means setting...

```
CONFIG_IIO_SW_TRIGGER=m
CONFIG_IIO_HRTIMER_TRIGGER=m
CONFIG_IIO_INTERRUPT_TRIGGER=m
CONFIG_IIO_SYSFS_TRIGGER=m
```

### Steps to reproduce the behaviour

Enable the `i2c-sensor` overlay for a `bme680` and observe that `iio_info` says "No trigger on this device" and enumerates no other triggers on the machine.

### Device (s)

Raspberry Pi Zero W / WH

### System

```
pi@pi0:~ $ cat /etc/rpi-issue 
Raspberry Pi reference 2022-01-28
Generated using pi-gen, https://github.com/RPi-Distro/pi-gen, f01430c9d8f67a4b9719cc00e74a2079d3834d5d, stage2
pi@pi0:~ $ vcgencmd version
Jan 20 2022 13:58:22 
Copyright (c) 2012 Broadcom
version bd88f66f8952d34e4e0613a85c7a6d3da49e13e2 (clean) (release) (start)
pi@pi0:~ $ uname -a
Linux pi0 5.10.103+ #1530 Tue Mar 8 13:00:30 GMT 2022 armv6l GNU/Linux
```

**Comment by pelwell** [comment]
Apologies - this is one of a number of issues from that time that have had no attention.

All the current branches should now include the necessary config settings. so future builds will ship with the required modules.

**Comment by JinShil** [comment]
I've used these triggers in the latest Bullseye OS.  I suppose this issue can be closed.
