### ISSUE TITLE
CONFIG_RANDOMIZE_BASE / KASLR for raspberrypi 4

### ISSUE THREAD

**Issue by ghost** [raspberrypi/linux#4989]
### Describe the bug

https://github.com/raspberrypi/linux/pull/1792 enabled KASLR for the raspberriyi 3. I was wondering why this settings isn't enabled for the pi 4/cm4 as well. (it's missing from https://github.com/raspberrypi/linux/blob/rpi-5.15.y/arch/arm64/configs/bcm2711_defconfig)

### Steps to reproduce the behaviour

Check `/proc/config.gz` on a raspberrypi 4/CM4.

### Device (s)

Raspberry Pi CM4

### System

Neither the 5.10 and 5.15 tree has this option in the defconfig.

**Comment by pelwell** [comment]
The `CONFIG_RANDOMIZE_BASE` option has been enabled in the arm64 bcm2711_defconfig - see https://github.com/raspberrypi/linux/commit/ed0918e65a6f96009fda5d21abf7e88c6a4c7504.
