### ISSUE TITLE
smart card reader timeout when compiling or downloading a file

### ISSUE THREAD

**Issue by Krosik** [raspberrypi/linux#500]
Hi

I have latest firmware, when i compiling some program, card reader cause delays like 4-5 seconds or timeout, same when I downloading something. normally there is delay like 200-300 ms

Before there was similar issue, it is here http://www.raspberrypi.org/forum/viewtopic.php?f=28&t=56216

Im not sure if delay is cause by cpu using or when something is downloading, before it was downloading and it was some problem with usb hub handling by Pi firmware.
I run stresstest and in this case delays are OK, but when I compiling delays are high.

The card reader is smartreader v2.

Let me know how can I provide more details, or send me skype etc, and I can allow you access to Pi to check it better.

thanks

**Comment by Krosik** [comment]
Ok I downgraded firmware to Sep 7, what was working in previous case and there are still timeouts when downloading something, so it won't be firmware problem this time.

**Comment by popcornmix** [comment]
Can you bisect the point where it broke? (using rpi-update <git hash> to test older version).

**Comment by Krosik** [comment]
I tried that, I moved to firmware that I know it worked (read the forum link) so it was from beginning of Sept 2013 and timeout problems was still there.

Now I downloaded raspbian from  2013-07-26 and it is working ok. Of course I did not used apt-get upgrade

**Comment by popcornmix** [comment]
If you look here:
https://github.com/Hexxeh/rpi-firmware/commits/master

You can click on a firmware update, and the end of the url is the git hash. e.g. latest is

```
https://github.com/Hexxeh/rpi-firmware/commit/43f305ced0a037d700f3fd7873b0de623e18b63d
```

If you run

```
sudo rpi-update 43f305ced0a037d700f3fd7873b0de623e18b63d
```

you will get that firmware. You should be able to work out the exist commit that broke it.

**Comment by Krosik** [comment]
The problem is diffrent now. Before, sometimes after reboot smartreader works, sometimes not, I though it was cardreader problem and I solved it by multiple times disconnecting reader from usb or ejecting card. 

Now I find out, that the not-always starting reader is also problem with firmware, it is like this:

Jul 05, 2013 - cardreader is not reading card after reboot
Jul 02, 2013 - cardreader is working ok

Because I have problems to get reader to work with firmware after Jul 05, I'm not able to go find out where starts the timeout problems. Maybe it is also the firmware Jul 05 but I'm not able to get reader working.

**Comment by popcornmix** [comment]
Are you sure Jul 02 was okay?
Jul 02 enabled the "fiq split" option which could have caused a problem. No other commits nearby seem related.

Can you try latest firmware with "dwc_otg.fiq_split_enable=0" added to cmdline.txt?

**Comment by Krosik** [comment]
rpi-update
did not worked

then set dwc_otg.fiq_split_enable=0
did not worked

then back to Jul 02
`rpi-update 1060b4e6f6ef7d62a50730656cd7c7f832bd2b45`
did not worked

then deleted dwc_otg.fiq_split_enable=0
worked

**Comment by Krosik** [comment]
Forgot to say, even in the wrong case the application appear to see reader and is able get CD signal (card detect) but can not initialize card. the reader is there always as ttyUSB0

**Comment by P33M** [comment]
Please retry with BRANCH=next rpi-update firmware.

See http://www.raspberrypi.org/phpBB3/viewtopic.php?f=28&t=70437 for information.

**Comment by P33M** [comment]
No update from OP in 2 months: assuming fixed with fiq_fsm.
