### ISSUE TITLE
neither minicom nor screen (nor stty) working with serial speed 74880 (regardless if ttyAMA0 or ttyS0)

### ISSUE THREAD

**Issue by FredFirestone** [raspberrypi/linux#5000]
### Describe the bug

I'd like to connect a Raspberry Zero W to an ESP8266 for monitoring, particularly of boot messages. These are transmitted using a non standard baud rate of 74880 (see http://cholla.mmto.org/esp8266/weird_baud/).
When using a (SuSE) system with a USB serial adapter minicom as well as screen work without any problems with 74880 speed.

But when using Raspbian on a Raspberry Pi Zero W I've failed to get it to work: It only printed garbage.

I did try with both uarts (see https://www.raspberrypi.com/documentation/computers/configuration.html#configuring-uarts) but never got any legible output with minicom (manually edited configuration) nor with screen (nor with stty) - while all three do work on the SuSE system.

After using http://cholla.mmto.org/esp8266/weird_baud/baud.c serial output on ttyS0 was legible, so I assume something inhibits 74880 baud from beeing set correctly in minicom or screen in raspbian.

### Steps to reproduce the behaviour

None of the tree following works:

`screen /dev/ttyS0 74880`
`minicom serial0` with config file containing device and "`pu baudrate         74880`"
`stty -F /dev/ttyS0 ispeed 74880; cat /dev/ttyS0` 

### Device (s)

Raspberry Pi Zero W / WH

### System

/etc/rpi-issue
Raspberry Pi reference 2021-05-07
Generated using pi-gen, https://github.com/RPi-Distro/pi-gen, dcfd74d7d1fa293065ac6d565711e9ff891fe2b8, stage2

vcgencmd version
Apr 30 2021 00:47:07 
Copyright (c) 2012 Broadcom
version d7f29d96450abfc77cd6cf011af1faf1e03e5e56 (clean) (release) (start)

uname -a
Linux raspberrypi-zw 5.10.17+ #1414 Fri Apr 30 00:16:27 BST 2021 armv6l GNU/Linux

**Comment by pelwell** [comment]
As the [linked page](http://cholla.mmto.org/esp8266/weird_baud/) says (my emphasis):

> If you are curious (like me) you would like to see the messages, but this is a significant problem given that _no linux utility that I have found has 74880 as an available baud rate option_.

That's just the way it is. You may have been lucky enough to find some system that allows random baud rates to be used, but this is far from common. Fortunately you have a workaround.

**Comment by FredFirestone** [comment]
What a pitty. Obviously this strange baud rate can be set not only on some system but even on raspbian. Trouble is: It can't be set with regular tools like stty or minicom, while on other systems/distributions the same tools can set it.

**Comment by gpreviato** [comment]
Actually I've found that miniterm works without problem with this baudrate... simply use: miniterm <your_serial> 74880
