### ISSUE TITLE
Bad panel applet

### ISSUE THREAD

**Issue by Quelconque** [raspberrypi/linux#5007]
### Describe the bug

In the french version of Bullseye-64, there is an applet named "Gestionnaire de bureau virtuel". If you install it in the panel, the taskbar will be damaged and you won't be able to reboot the desktop anymore.
Surprisingly, it seems that this applet do not exist in the list of the english version.

### Steps to reproduce the behaviour

As written

### Device (s)

Raspberry Pi 4 Mod. B

### System

Raspberry Pi reference 2022-01-28
Generated using pi-gen, https://github.com/RPi-Distro/pi-gen, fbe448ccdc995d295d24c7596e5f0ef62cc2488f, stage4

**Comment by lurch** [comment]
This should probably be reported at https://github.com/RPi-Distro/pi-gen/issues rather than in the Linux repo.
