### ISSUE TITLE
fixrtc issue

### ISSUE THREAD

**Issue by ghost** [raspberrypi/linux#5010]
### Describe the bug

Correct me if I'm wrong but fixrtc was a valid kernel parameter. 

However I recently noticed this:

Mar 27 08:42:12 raspberrypi kernel: Unknown kernel command line parameters "fixrtc", will be passed to user space.

### Steps to reproduce the behaviour

Boot with the "fixrtc" parameter passed to kernel.

### Device (s)

Raspberry Pi 4 Mod. B

### System

Raspberry Pi reference 2022-01-28
Generated using pi-gen, https://github.com/RPi-Distro/pi-gen, f01430c9d8f67a4b9719cc00e74a2079d3834d5d, stage2

Mar 24 2022 13:19:26
Copyright (c) 2012 Broadcom
version e5a963efa66a1974127860b42e913d2374139ff5 (clean) (release) (start)

Linux raspberrypi 5.15.32-v7l+ #1538 SMP Thu Mar 31 19:39:41 BST 2022 armv7l GNU/Linux

**Comment by pelwell** [comment]
I'm pretty sure that `fixrtc` is an option recognised by part of the Ubuntu userspace initialisation - systemd, udev, etc. - that just happens to be provided on the kernel command line for convenience. I think the kernel has started warning about such (ab)use of the command line, but that doesn't make it any more or less legitimate.

**Comment by pelwell** [comment]
If you have an RTC problem that you are trying to fix with this option, open an issue about it.
