### ISSUE TITLE
RTL2832 (DVB-T) FCI 2580 driver broken

### ISSUE THREAD

**Issue by Janghou** [raspberrypi/linux#502]
It is correctly recognised but skips channels on certain frequencies. 
Seems to be a general Linux 32 bits issue, works fine on amd64.
https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1270145
http://www.mail-archive.com/linux-media@vger.kernel.org/msg66429.html (other tuner, same problem?)

Dexatek Technology Ltd. DK mini DVB-T Dongle. Rtl2832U FCI 2580 based.
w_scan
 Info: using DVB adapter auto detection.
  /dev/dvb/adapter0/frontend0 -> TERRESTRIAL "Realtek RTL2832 (DVB-T)": good :-)

**Comment by P33M** [comment]
Can you find the relevant 3.12 commit and link it here?

**Comment by Janghou** [comment]
https://linuxtv.org/patch/20096/ (?)

**Comment by Janghou** [comment]
http://git.linuxtv.org/media_tree.git/commit/35c00c98a28835bcbf7450ab74cc112c28e5f59c

**Comment by P33M** [comment]
Main branch is now 3.12.

**Comment by Janghou** [comment]
IMHO this is not fixed. 
Device is not working on a Pi, but  is working on a Pi 2.
So the 32/64 bits issue isn't solved.

**Comment by P33M** [comment]
Pi 1 and Pi 2 are ARMv6 and ARMv7 architectures respectively. Both architectures are 32-bit.

What version of kernel (`uname -a`) is being used on the Pi 1 and Pi 2?

**Comment by Janghou** [comment]
Pi:
Linux OpenElec 3.17.8 #1 Tue Mar 31 16:15:02 CEST 2015 armv6l GNU/Linux

Pi2:
Linux OpenELEC 3.18.10 #1 SMP Tue Mar 31 14:50:33 CEST 2015 armv7l GNU/Linux
