### ISSUE TITLE
FKMS drivers interfering with Secondary Memory Interface Usage

### ISSUE THREAD

**Issue by gvx64** [raspberrypi/linux#5027]
### Describe the bug

Hello, I am a hobbyist and I am working on a project where I am using the Secondary Memory Interface (SMI) of the Raspberry Pi 4B to transmit RGB pixel and PCM audio data from Retropie to an old video game console.  The problem that I am experiencing is that in order to capture the screen RGB pixel data I need to use the FKMS drivers (DispmanX is not available with KMS) and, unfortunately, the FKMS drivers appear to frequently clear the SMICS register as a part of what seems to be a VSync interrupt process, rendering the SMI completely unusable.  Using FKMS, it is pretty much impossible to complete a full SMI transfer without the SMI being cleared by the FKMS drivers (at most I can complete a 10mS transfer before getting interrupted but it is generally much shorter than this).  In my view, this should be looked at as a potential bug because usage of the SMI for special applications is becoming increasingly common on the Pi thanks to more mainstream documentation becoming available and not being able to use it at all while running the default video drivers is a problem. Note that I have attached two logic analyzer traces of the same 16-bit SMI DMA step transfer, one using the KMS drivers and the other using FKMS.  There is clearly something interrupting the FKMS case.
FKMS:
![SMI_DMA_FKMS](https://user-images.githubusercontent.com/79026228/167601237-00ea189f-211a-4d6f-b078-b9a76df32ddf.png)
KMS:
![SMI_DMA_KMS](https://user-images.githubusercontent.com/79026228/167601258-90ee8546-efc9-4fda-90b3-2c173fec7630.png)

I was wondering if somebody could help me with creating a patch (or even just give me some tips on how I could create one) to prevent the SMI from being usurped by the FKMS drivers while still being able to use the FKMS drivers.   I believe that a patch would likely have something to do with editing the vc4_firmware_kms.c file which contains two SMICS clears, however, my initial attempts to remove the SMI activity from the code manually has either resulted in an unstable kernel or failed to stop the SMI clears.  If someone were to create a formal patch, it would be great if there was a configuration option where one could turn the SMI usage off in /boot/config.txt even at the expense of losing VSync, because I could really live without VSync if it meant having the access to the SMI. 

If you might be able to provide any assistance at all, I would be extremely appreciative.

Thank you very much for your time.

### Steps to reproduce the behaviour

Setup and initiate a 16-bit SMI DMA transfer that should continue for more than 10mS while enabling VC4-FKMS-V3D in /boot/config.txt.  The transfer should be interrupted prematurely.  Conversely, repeating the same transfer using VC4-KMS-V3D and it should continue until completion without any interruption.

### Device (s)

Raspberry Pi 4 Mod. B

### System

Raspberry Pi reference 2020-08-20
Generated using pi-gen, https://github.com/RPi-Distro/pi-gen, 9a3a10bf1019ebb2d59053564dc6b90068bad27d, stag2

Dec 2021 15:01:54
Copyright (c) 2012 Broadcom
version 71bd3109023a0c857558ba87cbb374d2eeb038f (clean) (release) (start)

Linux retropie 5.15.38-v71

**Comment by pelwell** [comment]
The "F" in FKMS stands for "Firmware" - it's a driver with a KMS interface but that leaves the HVS part of the display pipeline controlled by the firmware running on the VPU. The firmware needs a high performance way of signalling to the ARM side of FKMS, and software interrupt is the best way of doing that. Unfortunately there are no real software interrupts, but the SMI interface is a (very) rarely used hardware block that is capable of raising an interrupt under software control.

It should now be clear why changing the FKMS driver didn't solve your problem - the firmware would also have to be changed. I'll let somebody else comment on the possibility of using some other interrupt for FKMS, but the likelihood of that changing is essentially zero because FKMS is no longer supported.

**Comment by popcornmix** [comment]
I gave a similar response in [forum thread](https://forums.raspberrypi.com/viewtopic.php?p=2001038#p2001038).

**Comment by pelwell** [comment]
Cross posting like this is just a waste of time.

**Comment by 6by9** [comment]
If device tree does not have a node with a name starting with one of
```
              "v3d",
              "hdmi",
              "pixelvalve",
              "hvs",
              "txp",
              "firmwarekms",
              "csi0",
              "csi1",
              "csi",
              "interrupt-controller",
              "dsi",
```
that claims the SMI interrupt (```GIC_SPI 112``` on Pi4, or ```2 16``` on Pi0-3), then the firmware will not trigger that interrupt for VSYNCs.
