### ISSUE TITLE
Broken sound in accounts different than pi

### ISSUE THREAD

**Issue by henrykmichalewski** [raspberrypi/linux#504]
In a freshly created linux account, from inside Scratch interpreter sounds do not play (regardless if they are mp3 or wav). The problem does not exist for the pi user.  Version 3.6.11 #538.

**Comment by popcornmix** [comment]
Sounds like a user/groups issue. Type in:

```
$ groups pi
pi : pi adm tty dialout cdrom sudo audio video plugdev games users netdev input indiecity
```

So pi is in audio group. You want to add your new user to the same groups.

**Comment by henrykmichalewski** [comment]
Thanks, it helped.
