### ISSUE TITLE
[PATCH] Enable reading dht11 with lm-sensors

### ISSUE THREAD

**Issue by dagbdagb** [raspberrypi/linux#5051]
### Describe the bug

The current dht11 driver does not allow for reading sensor data via lm-sensors. The dht11 overlay does not enable the iio-hwmon bridge.

### Steps to reproduce the behaviour

1. install dht11 sensor
2. enable dht11 overlay
3. verify that 'cat /sys/bus/iio/devices/iio\:device0/in_temp_input ' returns data
4. run command 'sensors', observe that output lacks data from dht11 sensor

### Device (s)

Raspberry Pi 2 Mod. B

### System

root@rpi2:~/net-snmp# cat /etc/rpi-issue 
Raspberry Pi reference 2022-04-04
Generated using pi-gen, https://github.com/RPi-Distro/pi-gen, 226b479f8d32919c9fe36dd5b4c20c02682f8180, stage2

root@rpi2:~/net-snmp# vcgencmd version
May 24 2022 13:25:56 
Copyright (c) 2012 Broadcom
version 2c647ef4127e289d4a0cb5cfbb22855bfb7f1723 (clean) (release) (start)

root@rpi2:~/net-snmp# uname -a
Linux rpi2 5.15.41-v7+ #1557 SMP Mon May 23 16:46:23 BST 2022 armv7l GNU/Linux

### Additional context

```
From 18baf344f61abe32154fe76a9548c381804fff3d Mon Sep 17 00:00:00 2001
From: Dag Bakke <dag@bakke.com>
Date: Mon, 30 May 2022 11:57:06 +0200
Subject: [PATCH] Add code to make sensor readable via the IIO hwmon bridge.

Signed-off-by: Dag Bakke <dag@bakke.com>
---
 arch/arm/boot/dts/overlays/dht11-overlay.dts | 7 +++++++
 1 file changed, 7 insertions(+)

diff --git a/arch/arm/boot/dts/overlays/dht11-overlay.dts b/arch/arm/boot/dts/overlays/dht11-overlay.dts
index 6feeeb402493..3363e3075f75 100644
--- a/arch/arm/boot/dts/overlays/dht11-overlay.dts
+++ b/arch/arm/boot/dts/overlays/dht11-overlay.dts
@@ -17,7 +17,14 @@ dht11: dht11@0 {
 				pinctrl-0 = <&dht11_pins>;
 				gpios = <&gpio 4 0>;
 				status = "okay";
+				#io-channel-cells = <1>;
 			};
+			iio-hwmon {
+				compatible = "iio-hwmon";
+				status = "okay";
+				io-channels = <&dht11 0>, <&dht11 1>;
+			};
+
 		};
 	};
 
-- 
2.35.1

```

**Comment by dagbdagb** [comment]
Patch in previous comment enables the iio-hwmon bridge for dht11, allowing sensor data to be read with the 'sensors' command.

**Comment by dagbdagb** [comment]
net-snmp built with the optional lm-sensors module can generally read lm-sensors data. The current net-snmp package does *not* read the humidity data via SNMP, but upstream net-snmp does have fixes related to humidity sensors. Trying to build the very latest net-snmp for testing this.

**Comment by dagbdagb** [comment]
Illustrating that the dht11 overlay patch does what is required for sensors(1) to be happy:

```
root@rpi2:~/net-snmp-5.9+dfsg/debian# sensors
rpi_volt-isa-0000
Adapter: ISA adapter
in0:              N/A  

cpu_thermal-virtual-0
Adapter: Virtual device
temp1:        +39.0°C  

iio_hwmon-isa-0000
Adapter: ISA adapter
temp1:        +19.4°C  
humidity1:     51.7 %RH
```

**Comment by pelwell** [comment]
I won't be in a position to apply and merge your patch until later in the week, but this looks okay to me.

**Comment by dagbdagb** [comment]
Great. I have verified that upstream net-snmp can relate to lm-sensors humidity sensors. Only tangentially relevant for this ticket, but I mention it for the benefit of whoever comes looking for this.  The net-snmp commit in question is 8757342e593c8a83ed96bbcc94e199449982e23a.

**Comment by pelwell** [comment]
You'll find your patch merged, with a few changes, as https://github.com/raspberrypi/linux/commit/45599fd8fe420ede67b0a28767a335d1d203f9cf, the main change being to allow it to be applied multiple times with different gpiopin parameters.

**Comment by dagbdagb** [comment]
Thank you! And thank you for improving on it!

**Comment by pelwell** [comment]
Closing as resolved.
