### ISSUE TITLE
bcm2710-rpi-zero-2-w.dts defines "TXD0" and "RXD0" twice

### ISSUE THREAD

**Issue by mattjlewis** [raspberrypi/linux#5058]
### Describe the bug

File bcm2710-rpi-zero-2-w.dts has "TXD0" and "RXD0" defined twice. I believe the first definitions should be TXD1 and RXD1 in line with other boards.

### Steps to reproduce the behaviour

The `gpioinfo` command lists TXD0 and RXD0 twice.

### Device (s)

Raspberry Pi Zero 2 W

### System

$ cat /etc/rpi-issue
Raspberry Pi reference 2022-04-04
Generated using pi-gen, https://github.com/RPi-Distro/pi-gen, 27a8050c3c06e567c794620394a8c2d74262a516, stage2

$ vcgencmd version
Mar 24 2022 13:20:54
Copyright (c) 2012 Broadcom
version e5a963efa66a1974127860b42e913d2374139ff5 (clean) (release) (start)

$ uname -a
Linux zero2-1 5.15.32-v8+ #1538 SMP PREEMPT Thu Mar 31 19:40:39 BST 2022 aarch64 GNU/Linux

### Additional context

I appreciate this is a minor issue, however, confuses GPIO auto discovery.

**Comment by pelwell** [comment]
This duplication comes as a result of the mixed heritage of the Zero 2 W - half Zero and half 3B. The Zero 2W schematic calls the first two of these `GPIO14` and `GPIO15`, and in a way that's the most accurate, but they are also commented as `(TXD0)` and `(RXD0)`. Meanwhile GPIOs 30-33 are actually labelled `BT_CTS`, `BT_RTS`, `BT_TXD` and `BT_RXD` respectively. Note that these are the same labels and comments as appear on the 3B schematic (and probably others as well), so one could argue that both/all are wrong, but I agree that for consistency these would be better as `TXD1` and `RXD1`.

Thanks for reporting this - see 83bb3768c8823ec294e4a7f30d1c9e1b308b7e96 for the fix.

**Comment by mattjlewis** [comment]
Thank you for the swift response. Apologies, I should have also checked other Zero variants - I notice that the [Zero W dts](https://github.com/raspberrypi/linux/blob/rpi-5.15.y/arch/arm/boot/dts/bcm2708-rpi-zero-w.dts#L48) also has this oddity.

**Comment by pelwell** [comment]
Also fixed now.

**Comment by pelwell** [comment]
Closing as the reported fault has been fixed.
