### ISSUE TITLE
i2c6 clock fails to leave GPIO1 on some CM4 modules

### ISSUE THREAD

**Issue by drayna5** [raspberrypi/linux#5073]
### Describe the bug

When using dtoverlay=i2c6,pins_0_1,baudrate=100000, 2 of 15 CM4 modules tried fail to output I2C6 clocks.
Data comes out GPIO 0, but GPIO 1 remains at 3.3v on the scope.
The same firmware image on the other CM4s plugged into the same hardware work ok including talking to all devices attached to i2c6. Other i2c, i2s, spi and serial buses seem to work ok.

$ raspi-gpio get 0,1
GPIO 0: level=1 fsel=2 alt=5 func=SDA6 pull=UP
GPIO 1: level=1 fsel=2 alt=5 func=SCL6 pull=UP
$ i2cdetect -y 6
---- On failing CM4s, scope shows data pulses to 150mV but clock remains at 3.3v.
---- On working CM4s, data & clock are fine and all devices work when running code

Reprogramming GPIO 0,1 on the fly shows the same pins can drive the outputs to ground correctly like:
raspi-gpio set 0,1 op dl --- data AND clock go to around 200mV

Restoring operation with raspi-gpio set 0,1 a5 returns to the previous results.

Additional: Directing i2c0 to pins 0,1 also had the same effect on 1 unit tested -- data appeared on GPIO 0 but GPIO 1 remained at 3.3v.

### Steps to reproduce the behaviour

It does not happen on most of my CM4s. I don't know if there are internal versions or variations to consider.
Use dtoverlay=i2c6,pins_0_1,baudrate=100000 in config.txt and i2cdetect -y 6 and some CM4s will not output clocks on GPIO 1.

### Device (s)

Raspberry Pi CM4

### System

 $ cat /etc/rpi-issue
Raspberry Pi reference 2022-04-04
Generated using pi-gen, https://github.com/RPi-Distro/pi-gen, 910e079df1266036159ce4ea2aaa2ba9976ea3f1, stage2
$ vcgencmd version
Dec  1 2021 15:01:54
Copyright (c) 2012 Broadcom
version 71bd3109023a0c8575585ba87cbb374d2eeb038f (clean) (release) (start)
$ uname -a
Linux ipvideo-iot.local 5.10.103-v7l+ #1529 SMP Tue Mar 8 12:24:00 GMT 2022 armv7l GNU/Linux

**Comment by pelwell** [comment]
Duplicates the (stalled) forum thread https://forums.raspberrypi.com/viewtopic.php?t=336845.
