### ISSUE TITLE
Kernel 5.18: Faulty playback of HEVC videos (KODI)

### ISSUE THREAD

**Issue by mkreisl** [raspberrypi/linux#5077]
### Describe the bug

I already noticed it with 5.18.2, and today I had another chance with 5.18.7 to play 1080p HEVC videos with Kodi without errors.
Unfortunately with the same result: the playback is simply broken. AVC videos, on the other hand, are played back flawlessly.

The same kernel settings were used that worked perfectly up to and including 5.17. So my question is, are any magical new settings required or is this simply a bug?

### Steps to reproduce the behaviour

Play HEVC video

### Device (s)

Raspberry Pi 4 Mod. B

### System

XBian (based on Debian Bullseye)
Kodi 19.4
vcgencmd version:
Jun 15 2022 20:02:09 
Copyright (c) 2012 Broadcom
version ede5f7d365ef42ebbd4aa144ee5b51ea75604c82 (clean) (release) (start_x)

### Additional context

Oh yes, the simple hello_drmprime ( https://github.com/jc-kynesim/hello_drmprime ) plays the HEVC videos just as incorrectly. 

**Addition**:
Today I tested the 5.19.0-rc4. It works much better there (sorry for the sarcasm), because no HEVC video is displayed at all. With 5.18 it is at least still extremely pixelated and just barely recognisable. Now nothing is displayed at all. already a step forward, unfortunately in the completely wrong direction.

dmesg is completely silent on this issue

**Comment by popcornmix** [comment]
The state structure has changed (used for communicating between kernel and ffmpeg).
You need to rebuild ffmpeg with updated headers.
Check updated branches on @jc-kynesim 's ffmpeg repo. e.g. https://github.com/jc-kynesim/rpi-ffmpeg/tree/dev/4.3.4/hevc_api_4

**Comment by mkreisl** [comment]
@popcornmix, thank you for your answer. 
The same idea came to me today and I am currently testing it.

**Comment by mkreisl** [comment]
@popcornmix, FYI:

I have now done this with Kodi 20 Alpha (dev/4.4/rpi_import_1 branch) and with kernel 5.18.7 the playback of HEVC works again without problems. Fortunately, it also still works with 5.15.45 kernel.

For Kodi 19 I still have to create the FFmpeg patch to test it further.

**Comment by jc-kynesim** [comment]
FFmpeg does try to check that the structures match its expectations and it should cope correctly with all "released" versions of the linux driver but it can be fooled (rubbish) by some intermediate versions.  If it knows that it can't work then it won't start (black screen).

**Comment by mkreisl** [comment]
Kodi 19/20 with kernel 5.18 and 5.19 is working again. Time to close this issue here.
