### ISSUE TITLE
new 5.19 kernel out

### ISSUE THREAD

**Issue by xevilstar** [raspberrypi/linux#5098]
### Describe the bug

the actual 5.19 kernel is behind

### Steps to reproduce the behaviour

download and install the latest 5.19 kernel 
uname -a shows it is not the .7 release

### Device (s)

Raspberry Pi 4 Mod. B

### System

cat /etc/rpi-issue 
Raspberry Pi reference 2022-04-04
Generated using pi-gen, https://github.com/RPi-Distro/pi-gen, 27a8050c3c06e567c794620394a8c2d74262a516, stage4
vcgencmd version
Mar 24 2022 13:19:26 
Copyright (c) 2012 Broadcom
version e5a963efa66a1974127860b42e913d2374139ff5 (clean) (release) (start)

uname -a (I would like to see)
Linux raspberrypi 5.19.0-rc7-v8 #3 SMP PREEMPT Tue Jul 19 13:00:19 CEST 2022 aarch64 GNU/Linux

### Additional context

I would like for someone to tell me how to add the overlays to the actual kernel

**Comment by xevilstar** [comment]
the new version includes some gpio patches

**Comment by popcornmix** [comment]
The latest kernel is 5.19-rc7 (see https://github.com/raspberrypi/linux/blob/rpi-5.19.y/Makefile).
But we don't provide 5.19 kernel pre-built - you have to build it yourself.

5.15 is the supported kernel for RPiOS.

**Comment by xevilstar** [comment]
why when I compiled it it gave me 5.19-rc4 ?

**Comment by popcornmix** [comment]
> why when I compiled it it gave me 5.19-rc4 ?

You tell me. What do you see if you look at Makfile in root directory? I see:
```
VERSION = 5
PATCHLEVEL = 19
SUBLEVEL = 0
EXTRAVERSION = -rc7
```

**Comment by xevilstar** [comment]
Ok, I'll check it out.

**Comment by xevilstar** [comment]
uname -a
Linux raspberrypi 5.19.0-rc7-v8+ #1 SMP PREEMPT Tue Jul 19 14:43:47 CEST 2022 aarch64 GNU/Linux


done
