### ISSUE TITLE
Usb problem

### ISSUE THREAD

**Issue by alphaonex86** [raspberrypi/linux#51]
INFO:: periodic_channel_available: Total channels: 8, Periodic: 6, Non-periodic: 2

INFO:: schedule_periodic: No host channel available for periodic transfer.

ERROR::dwc_otg_hcd_urb_enqueue:518: DWC OTG HCD URB Enqueue failed adding QTD. Error status -4008

When I try connect my keyboard (hub with power, with on it: usb<->network adapter + my keyboard)

**Comment by popcornmix** [comment]
I think this is a duplicate of #29. You'll be better off posting there.
