### ISSUE TITLE
Kernel/modules 3.10.25+ possible bug report

### ISSUE THREAD

**Issue by ghost** [raspberrypi/linux#511]
Hello everybody,

On January 17th I made full update and upgrade to the system
running on Raspberry Pi v2, my server and gateway.

Before I started I had perfect bi-directional connectivity
betwen my desktop PC and RaspberryPi in many aspects.
(both appliances hooked to TL-MR3420 router!)

I'm running pretty complex set of software on RaspberryPi:
full blown LAMP server, Dovecot, RoundCube, WebMin
and some ham radio software working as AMPRNet gateway.

Update/Upgrade process included some packages,
linux kernel with kernel modules and RaspberryPi bootloader.
After upgrade process was completed but before reboot
with new kernel, system still was running O.K.
The old kernel was 3.6.11+ and the new one is 3.10.25+

After reboot took place I was simply taken aback.
I lost possibility to use IMAP/SMTP servers on Raspberry Pi,
i.e. I couldn't receive or send e-mails by means of Evolution.

Additionally I observed exactly the same problem on my
Sony Xperia Z1 smartphone - it wasn't possible to send
or receive e-mails through RaspberryPi's SMTP/IMAP.

Unexpectedly to my astonishment I discovered that
after I send just one ping packet from desktop PC
to RaspberryPi server I can receive and send e-mails!!!
But, also very strange, for a limited period of time.
If the idle time was longer than 5 minutes, 
again it wasn't possible to use RaspberyPi's SMTP/IMAP!
This did not applied to Sony Xperia Z1, unfortunately.

Another observation, absolutely strange too,
I couldn't open from desktop PC my www site neither
on linux.sp2lob.ampr.org nor on sp2lob.no-ip.org addresses!

Please note that except above mentioned issue
it was possible to telnet or ssh from my desktop PC
to RaspberryPi (both wired to TL-MR3420 router).

It was more than I can bear! Something is badly broken.
Quick decision: let's go back to 3.6.11+ kernel!!!
Now I'm back on 3.6.11+ kernel, running as before - O.K!!!

Where's the troublemaker? 

Best regards.
Tom

**Comment by popcornmix** [comment]
Can you try with latest 3.12.23 kernel?

**Comment by ghost** [comment]
Thank you for suggestion...
Investigated problem by myself and last not least found troublemaker.
My problem wasn't because of kernel bug, but it was caused by some changes in kernel modules.
It was directly connected with the way tunl0 interface was configured. 
In kernel 3.10.25+ it is necessary to  _EXPLICITLY_   specify MTU value!!!

So, I close issue #511 now.
Thank you again.
Tom
