### ISSUE TITLE
Teamviewer

### ISSUE THREAD

**Issue by ammous** [raspberrypi/linux#512]
Hello,
when i install Teamviewer  to can connect without IP.
i have the message,, can everybody can help me

TeamViewer: 9.0.24147 - TAR
Profile: /root (root)
Desktop: 
xprop:  unable to open display ''
XServer TTY: 
/etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 7 (wheezy)"
NAME="Raspbian GNU/Linux"
VERSION_ID="7"
VERSION="7 (wheezy)"
ID=raspbian
ID_LIKE=debian
ANSI_COLOR="1;31"
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
ok
/home/pi/download/teamviewer9/tv_bin/script/tvw_exec: ligne22: /home/pi/download/teamviewer9/tv_bin/wine/bin/wineserver : fichier binaire impossible Ã  lancer
/home/pi/download/teamviewer9/tv_bin/script/tvw_profile: ligne110: /home/pi/download/teamviewer9/tv_bin/wine/bin/wine : fichier binaire impossible Ã  lancer
/home/pi/download/teamviewer9/tv_bin/script/tvw_profile: ligne110: /home/pi/download/teamviewer9/tv_bin/wine/bin/wine : fichier binaire impossible Ã  lancer
/home/pi/download/teamviewer9/tv_bin/script/tvw_profile: ligne110: /home/pi/download/teamviewer9/tv_bin/wine/bin/wine : fichier binaire impossible Ã  lancer
/home/pi/download/teamviewer9/tv_bin/script/tvw_profile: ligne110: /home/pi/download/teamviewer9/tv_bin/wine/bin/wine : fichier binaire impossible Ã  lancer

**Comment by licaon-kter** [comment]
TeamViewer needs WINE, on ARM ( RaspberryPi ) the support is pretty bad at this moment: http://wiki.winehq.org/ARM?highlight=%28arm%29

**Comment by sequoiar** [comment]
@ammous you can try peer-vnc 
https://github.com/InstantWebP2P/peer-vnc

**Comment by popcornmix** [comment]
This is not a linux kernel issue.
Looks like teamviewer is not compatible with ARM.
For teamviewer alternatives I'd suggest asking in the forum.

**Comment by ammous** [comment]
Hello,
did you know teamviewer equivalent, which use a code and not address IP to connect to the other PC

A+

**Comment by asb** [comment]
@ammous: you may get some answers on the forum, this is the wrong place to ask http://www.raspberrypi.org/forum/

**Comment by Eltechs** [comment]
@ammous: you can launch Teamviewer on any Arm device (including Raspberry PI) using Exagear.
Here is a simple instruction how to do that: http://eltechs.com/run-teamviewer-on-raspberry-pi/

**Comment by jtyle6** [comment]
@Eltechs look at the post date. Before posting a lot of things can change in two years.

**Comment by licaon-kter** [comment]
@jtyle6 s/he just advertising for his/hers commercial products.

**Comment by jtyle6** [comment]
@licaon-kter but [TeamViewer IoT Developer Contest](https://www.teamviewer.com/iotcontest/) and [TeamViewer IoT](https://www.raspberrypi.org/forums/viewtopic.php?f=63&t=144608)

[Drops mic](http://i.imgur.com/E7pVmOe.gifv)
