### ISSUE TITLE
v4l2 driver for camera: image fades to black when using yuyv

### ISSUE THREAD

**Issue by ghost** [raspberrypi/linux#516]
When using the v4l2 driver for the rpi camera, the image fades to black after a while if it doesn't go through the proper video path, e.g. when directly fetching yuyv data from it.
As discussed in the forum at http://www.raspberrypi.org/forum/viewtopic.php?f=43&t=67793&p=495328#p495328

**Comment by 6by9** [comment]
https://github.com/raspberrypi/linux/commit/44fe4d7e3e1526e2c63347940cf0216d5c77885f allows the user to specify when loading the module the resolution at which to switch from video to stills mode processing. Push that limit above the resolution you want and the problem will go away (although with the potential for a slight reduction in image quality).

**Comment by Ruffio** [comment]
@flok99 has this issue been resolved? If yes, then please close this issue.
