### ISSUE TITLE
The Linux kernel cannot read to m.2 hard disks

### ISSUE THREAD

**Issue by hanxinwu1** [raspberrypi/linux#5163]
### Describe the bug

My Linux-4.19.6 kernel does not recognize the m.2 interface sata hard disk on the server board, please ask what configuration information should I add in the .config or menuconfig to identify my hard disk.

### Steps to reproduce the behaviour

My Linux-4.19.6 kernel does not recognize the m.2 interface sata hard disk on the server board, please ask what configuration information should I add in the .config or menuconfig to identify my hard disk.

### Device (s)

Raspberry Pi 1 Mod. A+

### System

linux kernel:linux-4.19.6
SSD: LITEON EGT 240N9S

**Comment by pelwell** [comment]
You are not going to get support on Linux 4.19 here - it's far too old. What you have is a question, and as such is best asked in the [Raspberry Pi Forums](https://forums.raspberrypi.com/).
