### ISSUE TITLE
v4l2 camera driver: some resolutions are cropped, not scaled

### ISSUE THREAD

**Issue by ghost** [raspberrypi/linux#517]
E.g. when viewing the raspberry pi video stream using 1280x720 or 640x480 then things is not scaled but cropped (pieces of the image are cut off).

**Comment by 6by9** [comment]
This should have been resolved in the firmware release https://github.com/raspberrypi/firmware/commit/be2ba9bd18adaea9f8e466dc05ef77a4c8d3e15e back in March.

See http://www.raspberrypi.org/forums/viewtopic.php?f=43&t=62364&sid=90669534834c7e6886b52149ea9d4ff7&start=250#p520078 for more details of remaining limitations (summary: anything over around 1296x972 will still be cropped as the sensor can not read out the data fast enough without binning).

**Comment by Ruffio** [comment]
@flok99 has this issue been resolved? If yes, then please close this issue.
