### ISSUE TITLE
Typo in the original /etc/network/interfaces

### ISSUE THREAD

**Issue by securedirective** [raspberrypi/linux#519]
The original file has "allow_hotplug wlan0", but according to the interfaces man-page, the correct command is "allow-hotplug wlan0" (dash, rather than underscore). This has been causing me much headache, when configuring new Pi's.

Also, may I suggest the blank lines are moved around to make the file more concise to begin with?...

---

auto lo
iface lo inet loopback

iface eth0 inet dhcp

allow-hotplug wlan0
iface wlan0 inet manual
wpa-roam /etc/wpa_supplicant/wpa_supplicant.conf

iface default inet dhcp

**Comment by asb** [comment]
What image are you using? The Raspbian image at http://raspberrypi.org definitely has the correct `allow-hotplug wlan0`. I suggest you report this bug to whoever created your image.

```
# cat /etc/network/interfaces  
auto lo 

iface lo inet loopback 
iface eth0 inet dhcp 

allow-hotplug wlan0 
iface wlan0 inet manual 
wpa-roam /etc/wpa_supplicant/wpa_supplicant.conf 
iface default inet dhcp
```

**Comment by securedirective** [comment]
You are correct. My mistake; this is embarrassing. Apparently, the typo is not from the original.
