### ISSUE TITLE
Crash when use of the sd card + network card

### ISSUE THREAD

**Issue by alphaonex86** [raspberrypi/linux#52]
Hello, I rsync the folder on the sd card (normal folder /usr/portage/), it use the intensive the network and sd card. After 10min of work all it crashed, I need hard reboot. I'm under console, and the linux put the back screen after inactivity, I can't press key board my keyboard not work (see the previous reported bug).
But I have noted lot of similar problem of stability when you use the sd card (read + write). My sd card is kingstone class 4 of 16GB.
Freeze mean for me: no responds to the ping.

**Comment by popcornmix** [comment]
What does "uname -a" report?

**Comment by alphaonex86** [comment]
Linux toc 3.1.9 #3 PREEMPT Tue Jul 17 20:20:00 CEST 2012 armv6l ARMv6-compatible processor rev 7 (v6l) BCM2708 GNU/Linux
Then the official kernel, but with custom config (add some modules, remove other, but nothing important)

**Comment by popcornmix** [comment]
Can you confirm it happens with official build of kernel?
Can you capture a stack trace?

**Comment by alphaonex86** [comment]
How capture the stack trace?

EDIT: On console, the cursor stop to blink

**Comment by alphaonex86** [comment]
Linked only with the usb/network/general because I have crash too without disk access (I think: find ./ -mmin -60 say nothing, and lot of stuff is under tmpfs).

**Comment by popcornmix** [comment]
Normally stack trace is output to screen when a crash occurs. 
Are you overclocking? Are you sure power supply is good?

**Comment by alphaonex86** [comment]
Then like my normal computer.
No overclocking (official clock). I presume my power supply as good (provided by the raspberry pi resseller), but I have any tools to check it. I have nothing to weld an capacitor to test (and If I failed the weld, it's 30$ more + 450$ to ship where I live).
All my router/computer/device seam work here.

**Comment by alphaonex86** [comment]
But I note red light up when the power is disconnected and hub powered connected (no diode to prevent alimenting by usb I presume).

**Comment by alphaonex86** [comment]
I have a dmesg on my custom kernel:
Backtrace: 
http://pastebin.com/01gtGESk

I search enable my symboles to debug better...

**Comment by alphaonex86** [comment]
No bt but when I disconnect the network card, the rpi stop freeze and display in loop the message for the network card:
event key 5 dropped... I will note it.

**Comment by alphaonex86** [comment]
To do a bug, it's very easy:
I launch 10x ping command like that's, on my personal computer on the lan:
ping www.google.com
my rpi is router/gateway, eth0 (internal interface) is for the lan 192.168.158.0/24, the eth1 is for the adsl routeur 192.168.1.0/24 (linked with gateway/masquerade mode?)

I have in loop on the hdmi output:
smsc95xx 1-1.1:1.0: eth0: kevent 4 may have been dropped
and unable to acces to the dmesg (I have try loop into screen session, dmesg > /boot/dmesg;sleep 60, with /boot as sync)

**Comment by alphaonex86** [comment]
No crash the same device but with routing/gateway disabled.

confirmed by the bt::
http://pastebin.com/01gtGESk

**Comment by alphaonex86** [comment]
Power is correct, I have changed all the device to be sure.
The back trace is clear, no? The card asix receive RX, then the data is transmited into an interruption to smsc95xx, and sometime that's do a infinity loop.

I need very quickly a solution, if you can do that's, thanks to you.

**Comment by alphaonex86** [comment]
With CONFIG_CPU_IDLE that's do lot of time before the problem with my custom kernel, but the ping and bandwith to internet is more and more worse (I need reset each 6h). But at final it crash too.
Mem leak?

**Comment by alphaonex86** [comment]
I'm without swap.

**Comment by alphaonex86** [comment]
Now I have error:
Error::handle_he_chhltd_intr_dma:1988 handle_he_chhltd_intr_dma: Channel 3, DMA Mode -- but reason for halting is unknow, hcint 0x00000402, insts 0x0660001
Error::handle_he_chhltd_intr_dma:1988 handle_he_chhltd_intr_dma: Channel 3, DMA Mode -- but reason for halting is unknow, hcint 0x00000402, insts 0x0660009
Error::handle_he_chhltd_intr_dma:1988 handle_he_chhltd_intr_dma: Channel 3, DMA Mode -- but reason for halting is unknow, hcint 0x00000402, insts 0x0660021
in loop

**Comment by popcornmix** [comment]
Can you test with latest kernel. Also can you try with:
dwc_otg.microframe_schedule=1
in cmdline.txt

**Comment by alphaonex86** [comment]
The bug is same, I have tryied with the last kernel at this time.

**Comment by ashleyw** [comment]
I had this exact problem @alphaonex86, "Channel 3, DMA Mode -- but reason for halting is unknown", caused by simply wget'ing a large file (it'd freeze after ~2 minutes.)

It turned out it was my Apple USB wired keyboard causing it — once I removed it, everything ran smoothly! I guess it was sucking too much power?

Others seem to agree: [Report: Apple Wired Keyboard Incompatible](http://www.raspberrypi.org/phpBB3/viewtopic.php?f=28&t=6771)

**Comment by alphaonex86** [comment]
I have external power, then I my case it's not linked with power problem. But it seam like have infinity loop after disconnect the device (like when connected) and consume all the cpu.

For my it's context problem and software only bug.

**Comment by alphaonex86** [comment]
Now I have:

[ 1201.006730] VCHIQka-0       D c0372168     0    23      2 0x00000000
[ 1201.013922] [<c0372168>](__schedule+0x4b0/0x51c) from [<c03727a8>](schedule+0x80/0x84)
[ 1201.020866] [<c03727a8>](schedule+0x80/0x84) from [<c0049414>](kthread+0x7c/0x9c)
[ 1201.027978] [<c0049414>](kthread+0x7c/0x9c) from [<c000f1f0>](kernel_thread_exit+0x0/0x8)
[ 1321.032970] INFO: task VCHIQka-0:23 blocked for more than 120 seconds.
[ 1321.039772] "echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
[ 1321.062936] VCHIQka-0       D c0372168     0    23      2 0x00000000
[ 1321.069966] [<c0372168>](__schedule+0x4b0/0x51c) from [<c03727a8>](schedule+0x80/0x84)
[ 1321.092995] [<c03727a8>](schedule+0x80/0x84) from [<c0049414>](kthread+0x7c/0x9c)
[ 1321.100052] [<c0049414>](kthread+0x7c/0x9c) from [<c000f1f0>](kernel_thread_exit+0x0/0x8)

**Comment by popcornmix** [comment]
@alphaonex86 
That is a known problem. See here:
http://www.raspberrypi.org/phpBB3/viewtopic.php?f=29&t=19334

**Comment by alphaonex86** [comment]
I don't know if is linked with my problem, but before I was slow down and after freeze, now I have just slow down (but after more time, freeze after more time?)
The slow down is show by ping to rpi greater than 1000ms (the normal at starting is <1ms).
I can disable the videocore module if needed, I use kms (just to have console output) but no X.

**Comment by alphaonex86** [comment]
Same, do just more time to bug (1 day).

**Comment by alphaonex86** [comment]
I have try disable the turbo mode, with more large network buffer (problem after more time, ...), I have try large the memory kernel min size...

**Comment by alphaonex86** [comment]
Same with the last kernel

**Comment by ghollingworth** [comment]
Which kernel revision?

"uname -a"

**Comment by alphaonex86** [comment]
Not usefull information, because you don't have the real version:
Linux toc 3.2.27 #1 Mon Nov 5 03:14:21 CET 2012 armv6l ARMv6-compatible processor rev 7 (v6l) BCM2708 GNU/Linux
I have try at this commit:
https://github.com/raspberrypi/linux/commit/df41b42914892c539de4ec16a6d9184d031ae0bf

**Comment by alphaonex86** [comment]
Better after this commit, due the previous commit on network card:
https://github.com/raspberrypi/linux/commit/1aa222e240afd6c2f27be96381ddb1fbb595c3b5
But remain crashed after few hour (about 8h with network trafic as gateway).

**Comment by ghollingworth** [comment]
Make sure turbo mode is N

On 10/11/2012, BRULE Herman notifications@github.com wrote:

> Better with:
> https://github.com/raspberrypi/linux/commit/1aa222e240afd6c2f27be96381ddb1fbb595c3b5
> But remain crashed after few hour (about 8h with network trafic as
> gateway).
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/raspberrypi/linux/issues/52#issuecomment-10257777

## 

Sent from my mobile device

**Comment by alphaonex86** [comment]
I'm sure to that's. But I can check by sysctl or dmesg?

**Comment by ghollingworth** [comment]
Can you re-check with latest 3.6.y kernel, reopen if still found
