### ISSUE TITLE
Missing driver for rtc-rv3032

### ISSUE THREAD

**Issue by Gadgetoid** [raspberrypi/linux#5205]
### Describe the bug

Missing support in `i2c-rtc.dtbo` for the rv3032 RTC.

### Steps to reproduce the behaviour

Add:

```
dtoverlay=i2c-rtc,rv3032
```

To `/boot/config.txt`

### Device (s)

Raspberry Pi 4 Mod. B

### System

```
cat /etc/rpi-issue 
Raspberry Pi reference 2022-04-04
Generated using pi-gen, https://github.com/RPi-Distro/pi-gen, 226b479f8d32919c9fe36dd5b4c20c02682f8180, stage4

vcgencmd version
Aug 26 2022 14:03:16 
Copyright (c) 2012 Broadcom
version 102f1e848393c2112206fadffaaf86db04e98326 (clean) (release) (start)

uname -a
Linux inkypi 5.15.61-v7l+ #1579 SMP Fri Aug 26 11:13:03 BST 2022 armv7l GNU/Linux
```

### Additional context

A working module for `rtc-rv3032` exists. I have built it with DKMS and modified the dtbo accordingly. Setting and getting time via `hwclock` is successful.

I believe this needs adding to `i2c-rtc-common.dtsi`:

```
        fragment@21 {
                target = <&i2cbus>;
                __dormant__ {
                        #address-cells = <1>;
                        #size-cells = <0>;

                        rv3032: rv3032@51 {
                                compatible = "microcrystal,rv3032";
                                reg = <0x51>;
                        };
                };
        };
```

Plus the `rtc-rv3032` module added to the build.

If you need/want a sample RTC board, let me know!

**Comment by pelwell** [comment]
That should be done now - see [d8eacff ](https://github.com/raspberrypi/linux/commit/d8eacffe332f7dc429c38e789543899fda3076d6) and [f0f6d95](https://github.com/raspberrypi/linux/commit/f0f6d95653281453004b67cfd3ce56b10579fcb6).

Thanks for the offer, but I don't think I need more RTC modules - things in the RTC world rarely change.

**Comment by Gadgetoid** [comment]
> things in the RTC world rarely change

They are.. indeed... not exciting.  :laughing: 

Thank you very much!

Shout if you need anything.
