### ISSUE TITLE
bcm2708_fb: bcm2708_fb_debugfs_init() is called twice.

### ISSUE THREAD

**Issue by kukabu** [raspberrypi/linux#521]
Hello

bcm2708_fb_debugfs_init() is called twice in bcm2708_fb_probe().

https://github.com/raspberrypi/linux/blob/rpi-3.10.y/drivers/video/bcm2708_fb.c#L647-L650

**Comment by popcornmix** [comment]
Removed in https://github.com/raspberrypi/linux/commit/4127b11079ec7a89ed9e49355b0d682104287dd4

Thanks for heads up.
