### ISSUE TITLE
glPixelStorei() parameters for partial texture update 

### ISSUE THREAD

**Issue by vanfanel** [raspberrypi/linux#522]
I'm trying to port some programs to the Pi. This time, I'm fighting SimCoupe, a Sam Coupe emulator.
This emulator already has an OpenGL backend wich I'm adapting to Pi's GLES2.
This backend has an update function that partially updates a GL texture using glTexSubImage2D(), based on how many lines have been changed in each frame, to minimize the data upload.

For that, reading only a part of the source video buffer in RAM is essential: that would be done by setting:

glPixelStorei(GL_UNPACK_ROW_LENGTH, nWidth);
glPixelStorei(GL_UNPACK_SKIP_ROWS, y);

just before calling glTexSubImage2D().
These GLenums seem to be defined in gl2ext.h, but they don't work at all.
Is it possible to implement them, please?

thanks!

**Comment by popcornmix** [comment]
Sorry, you'll only get what's supported by GL ES
http://www.khronos.org/opengles/sdk/1.1/docs/man/glPixelStorei.xml
which is GL_PACK_ALIGNMENT and GL_UNPACK_ALIGNMENT.

I believe glTexSubImage2D will let you upload a sub-image - you just need to ensure that alignment matches a supported one.

**Comment by vanfanel** [comment]
Ok, popcornmix, now I understand why those extensions aren't working: they are non-GLES2 standard!

Thanks, as always, for your patient help :)
