### ISSUE TITLE
USB3.0 ports cannot detect devices

### ISSUE THREAD

**Issue by cybericius** [raspberrypi/linux#5225]
### Describe the bug

I would use a Logitech Unifier and a Natec Rhino Go USB3.0 external SSD case (NKZ-0941) with Asmedia chip, but these can only be detected by the USB2.0 ports. Of course, the major issue is with the SSD due to the degrades speed it has (¬31MB/s).
I tried the quirks hack in the /boot/cmdline.txt, but didn't change anything, the boot sequence is rolling through the options without seeing the solid state drive.
I read that the UASP support of the Raspberry Pi 4 is not that good, so I would like to finally find a solution to the problem.

`Bus 001 Device 003: ID 174c:235c ASMedia Technology Inc. USB3.1 External HDD
`
```
T:  Bus=01 Lev=02 Prnt=02 Port=02 Cnt=01 Dev#=  3 Spd=480 MxCh= 0
D:  Ver= 2.10 Cls=00(>ifc ) Sub=00 Prot=00 MxPS=64 #Cfgs=  1
P:  Vendor=174c ProdID=235c Rev=01.00
S:  Manufacturer=ASMedia
S:  Product=USB3.1 External HDD
S:  SerialNumber=2016050500000000010F
C:  #Ifs= 1 Cfg#= 1 Atr=c0 MxPwr=0mA
I:  If#=0x0 Alt= 0 #EPs= 2 Cls=08(stor.) Sub=06 Prot=50 Driver=usb-storage
```

```
cat /boot/cmdline.txt 
usb-storage.quirks=174c:235c:u console=serial0,115200 console=tty1 root=PARTUUID=2f80bedc-02 rootfstype=ext4 fsck.repair=yes rootwait
ip=192.168.0.199

```
I'll provide any other info as requested to assist. Thank you!

### Steps to reproduce the behaviour

Plug the external USB3-SATA case on a USB3.0 port and try to boot.

### Device (s)

Raspberry Pi 4 Mod. B

### System

```
a@a:~ $ cat /etc/rpi-issue 
Raspberry Pi reference 2022-09-22
Generated using pi-gen, https://github.com/RPi-Distro/pi-gen, 8a42abcd1dbd8c9c1fdfca4e0c3778255b2f9cc4, stage4
a@a:~ $ vcgencmd version
Aug 26 2022 14:03:16 
Copyright (c) 2012 Broadcom
version 102f1e848393c2112206fadffaaf86db04e98326 (clean) (release) (start)
a@a:~ $ uname -a
Linux malna 5.15.61-v7l+ #1579 SMP Fri Aug 26 11:13:03 BST 2022 armv7l GNU/Linux

```

**Comment by timg236** [comment]
This sounds like a support question rather than a specific bug report. Please try the Troubleshooting forum for support questions
https://forums.raspberrypi.com/viewforum.php?f=28
