### ISSUE TITLE
libgps missing shared memory support

### ISSUE THREAD

**Issue by wb2osz** [raspberrypi/linux#523]
Problem:

It appears that libgps was built without shared memory support.

Test case:

```
#include <stdio.h>
#include <errno.h>
#include <gps.h>
main ()
{
        struct gps_data_t gpsdata;
        if (gps_open (GPSD_SHARED_MEMORY, NULL, &gpsdata) == 0)
                printf ("Success!\n");
        else
                printf ("Failure.\n%s\n", gps_errstr(errno));
}
```

The error message is “can’t get host entry.”

Theory:  

The libgps binary package was built without shared memory support.
Look at the source code and notice that shared memory is an optional feature:

```
int gps_open(/*@null@*/const char *host, 
           /*@null@*/const char *port CONDITIONALLY_UNUSED,
           /*@out@*/ struct gps_data_t *gpsdata)
{
    int status = -1;

    /*@ -branchstate -compdef @*/
    if (!gpsdata)
      return -1;

#ifdef SHM_EXPORT_ENABLE
    if (host != NULL && strcmp(host, GPSD_SHARED_MEMORY) == 0) {
      status = gps_shm_open(gpsdata);
      if (status == -1)
          status = SHM_NOSHARED;
      else if (status == -2)
          status = SHM_NOATTACH;
    }
#endif /* SHM_EXPORT_ENABLE */
```

Supporting evidence:

GPSD_SHARED_MEMORY is defined like this:
# define GPSD_SHARED_MEMORY      "shared memory"

This string does not appear in libgps.

$ strings /usr/lib/_/libgps_ | grep “shared memory”

Workaround:  Rebuild it from source.

Edit /etc/apt/sources.list.   Make a copy of the “deb” line and change it to “deb-src” so it looks something like this:

deb http://mirrordirector.raspbian.org/raspbian/ wheezy main contrib non-free rpi
deb-src http://mirrordirector.raspbian.org/raspbian/ wheezy main contrib non-free rpi

Type commands:

```
sudo apt-get update
sudo apt-get build-dep gpsd
apt-get source gpsd
cd gpsd-3.6
scons prefix=/usr shm_export=True
Sudo scons udev-install
```

Issue:   we now have libraries in two different places

/usr/lib/libgps.so   ---- new one
/usr/lib/arm-linux-gnueabihf/libgps.so   ---- original

There is probably some way to set the library subdirectory, but just for this test move to right place.

sudo mv /usr/lib/libgps\* /usr/lib/arm-linux-gnueabihf/

Test program now reports success.

We also find the string “shared memory” in the library.

$ strings /usr/lib/_/libgps_ | grep "shared memory"
shared memory
shared memory
shared memory
shared memory

**Comment by popcornmix** [comment]
This isn't a kernel issue (what this github issue tracker is for).
It is a raspbian distribution issue (assuming you are asking for something to be changed).
I would suggest reporting it here:
http://www.raspbian.org/
or
http://www.raspberrypi.org/phpBB3/viewforum.php?f=66

**Comment by kukabu** [comment]
wb2osz, also gpsd shared memory doesn't work prior gpsd 3.10. Uses last release.
http://git.savannah.gnu.org/cgit/gpsd.git/commit/?id=b99aade97201c7eee4e1f96d59c1b729e238478c
