### ISSUE TITLE
Feature Request:  Add more information to issue.txt file on boot partiton of Pi OS

### ISSUE THREAD

**Issue by Jibun-no-Kage** [raspberrypi/linux#5252]
### Describe the bug

Feature Request:  Add more information to issue.txt file on boot partiton of Pi OS.

Please add the following to issue.txt file:

1) Architecture (bit width, i.e. 32 or 64), Format is not critical, just requesting some way to know the image on SD card is 32 or 64 bit OS variant.

Change this...
Raspberry Pi reference 2022-09-22
Generated using pi-gen, https://github.com/RPi-Distro/pi-gen, 005a8c73b05a2cab394073150208bf4f069e861a, stage2

To this, suggestion...
Raspberry Pi reference 2022-09-22, 32 bit
Generated using pi-gen, https://github.com/RPi-Distro/pi-gen, 005a8c73b05a2cab394073150208bf4f069e861a, stage2

Raspberry Pi reference 2022-09-22, 64 bit
Generated using pi-gen, https://github.com/RPi-Distro/pi-gen, 005a8c73b05a2cab394073150208bf4f069e861a, stage2

I am writing a PowerShell script, later a true application, that allows for greater customization of cmdline.txt and config.txt files, and would like to be able have a better method of knowing the image as 32 or 64 bit, than relying on config.txt 'arm_64bit=' setting which operator could change or delete in error.  Plan to have my script warn operator this is a configuration mismatch, if operator selects such option.

If there is a better way to determine image architecture width, please suggest.

### Steps to reproduce the behaviour

Not Applicable

### Device (s)

Other

### System

Not Applicable

### Logs

Not Applicable

**Comment by popcornmix** [comment]
This repo is for reporting bugs with the linux kernel.
https://github.com/RPi-Distro/pi-gen/issues may be a better place for this request.

**Comment by Jibun-no-Kage** [comment]
Right, this is not a kernel issue per se, just indirectly related.  Thanks for the information.
