### ISSUE TITLE
spidev module doesn't load; no /dev/spi* in core/linux-raspberrypi-latest 3.13.1-1

### ISSUE THREAD

**Issue by hugoferreira** [raspberrypi/linux#526]
SPI support, present in core/linux-raspberrypi 3.10.29-1, hasn't been working at least since 3.12.

**Comment by ghost** [comment]
Might be the same issue I'm having. SPI (/dev/spi) using spidev only works when spidev is not a module but is statically built into the kernel. the spi-bcm2708 can be used as a module though.

https://github.com/raspberrypi/linux/blob/7193cfe22b63ae92d1f7e955c2276adbdafd28e0/arch/arm/mach-bcm2708/bcm2708.c#L556

**Comment by P33M** [comment]
spidev is working on recent firmware, but not enabled by default. The recommended method to enable this by default is to add the module name to /etc/modules.

**Comment by pelwell** [comment]
With a DT-enabled kernel, enable the spi interface by adding `dtparam=spi=on` to config.txt. This will also cause the spidev module to be loaded (but see https://github.com/raspberrypi/linux/issues/1054 ...)

**Comment by xevilmaxx** [comment]
Hi, 
Recently had some issues with **SPI** module too.
OS used: **Debian10 arm64**
Soc: **Raspberry Pi 3 B v1.2**

As many sugested, i added **dtparam=spi=on** to **config.txt** in: **/boot/firmware/**
but after several tries (including adding more specific dtparams) and kernel changes, nothing worked.

**Solution:**
1. Backup/Move ***.dtb** from **/boot/firmware/** into **/boot/firmware/oldDtbs**
2. Clone this repo: [https://github.com/raspberrypi/firmware/tree/master/boot](https://github.com/raspberrypi/firmware/tree/master/boot)
3. Copy ***.dtb** and **overlays folder** into: **/boot/firmware/**
4. **sudo shutdown -r now**
5. Check if SPI si ok: **ls /dev/spi***

**Comment by transplier** [comment]
I had the same issue with my old B Rev. 2. Attempting the above suggestions did not fix it. Copying over the official firmware as per the previous comment unfortunately crashes the board on boot.

**Comment by pelwell** [comment]
Install a fresh RPiOS to a spare card and verify that it works as expected. If it does (and it will), your issue must be the result of some unknown combination of kernel + firmware + Device Tree files, and an issue from 2015 is not the right venue for getting some help - try the Raspberry Pi Forums.

**Comment by transplier** [comment]
OK. This is a fresh install of Debian 10, but I'll take this elsewhere.
