### ISSUE TITLE
Display preferences "small screens" does not survive a power cycle.

### ISSUE THREAD

**Issue by rin67630** [raspberrypi/linux#5268]
### Describe the bug

Preferences MUST be remnant. 
The Display preferences "small screens" does not survive a power cycle and defaults again to middle.

This was not the case in Buster and is a regression.

### Steps to reproduce the behaviour

Boot a fresh install of Bullseyes. 
Go to preferences, display, select Small screen.
Shutdown or Power off
The preference setting Small screen is lost, defaults to Medium again.

This is NOT a minor bug, the users of on board-LCD screens (as sold by Adafruit, Seedstudio or Waveshare) with 320*240 resolution must rely on the "Small screens" settings, else they get an unusable mess that cannot be fixed locally.

### Device (s)

Raspberry Pi Zero, Raspberry Pi Zero W / WH, Raspberry Pi Zero 2 W, Raspberry Pi 1 Mod. A, Raspberry Pi 1 Mod. A+, Raspberry Pi 1 Mod. B, Raspberry Pi 1 Mod. B+, Raspberry Pi 2 Mod. B, Raspberry Pi 2 Mod. B v1.2, Raspberry Pi 3 Mod. A+, Raspberry Pi 3 Mod. B, Raspberry Pi 3 Mod. B+, Raspberry Pi 4 Mod. B, Raspberry Pi 400

### System

All devices with Desktop

OS Version Bullseyes, current stock delivery

**Comment by popcornmix** [comment]
This repo is for reporting issues with the linux kernel.
Your issue sounds like a problem with RPiOS. Can you post it here where the right people may see it:
https://github.com/RPi-Distro/repo/issues/
