### ISSUE TITLE
alsa: HDMI passthrough support

### ISSUE THREAD

**Issue by julianscheel** [raspberrypi/linux#528]
It would be nice to be able to use the snd_bcm2835 alsa driver not only for PCM playback but also for passthrough of encoded audio formats like AC3 through the HDMI port.

**Comment by popcornmix** [comment]
Do you have any references to what the alsa driver should do to support this?

Technically you can do it with spdif encapsulated AC3 or DTS sent as stereo PCM:
https://github.com/raspberrypi/firmware/issues/183

You should add config options "no_hdmi_resample=1" and "hdmi_stream_channels=1" to config.txt to ensure data gets through uncorrupted.

**Comment by julianscheel** [comment]
Thanks for the notes. From the alsa side there's nothing special. A 2 chanel S16_LE device should be just fine. So likely it will just work with these parameters set.
I will test and report.
Would it be possible to set these parameters at runtime instead of config.txt? Sounds like they could harm normal PCM playback in some circumstance (ie low sampling rates)

**Comment by popcornmix** [comment]
Actually latest (rpi-update) firmware has no_hdmi_resample=1 as a default, and 

```
vcgencmd hdmi_stream_channels 1
```

will enable hdmi_stream_channels at runtime (0 to disable).

hdmi_stream_channels determines if the AV infoframe reports the actual number of channels (i.e. 2) or 0 (which means refer to stream).

I did try using "refer to stream" in a build a while back which all the hdmi devices we have here worked correctly for either stereo PCM or passthrough formats.
Unfortunately there were a few reports of PCM stereo not working so it needs to be something switchable.

I'm trying to find if there is a way of indictating to alsa driver when passthrough is in use, so the switch can be done. XBMC ALSA sink (for other platforms) uses "AES0-0x06" for passthrough and AES0=0x04" for non-passthrough formats - I think appended to the device name that is opened, but I didn't find a description of what exactly this does.

**Comment by julianscheel** [comment]
The AES0 suffix to the device name can indeed be used to detect non-audio streams. When it's set to 0x06 the bit IEC958_AES0_NONAUDIO (see asounddef.h) is set. Using IEC958_AES0_NONAUDIO as indicator should be a good choice. A quick grep over the kernel shows that some drivers handle it like that.

**Comment by popcornmix** [comment]
I can't see where the AES0=0x60 is parsed in the (any) ALSA kernel driver.
Yes, in theory I could parse the spdif stream and extract the IEC958_AES0_NONAUDIO bit, but that would be an expensive operation compared to parsing the ALSA device name.

**Comment by julianscheel** [comment]
Afaict the flags are parsed in alsa-lib when you open the device (see src/conf/pcm/iec958.conf or hdmi.conf). And are applied to the appropriate control, which the driver has to expose. See http://www.alsa-project.org/~tiwai/writing-an-alsa-driver/ch10s03.html

**Comment by julianscheel** [comment]
I finally was able to do some more testing and got it working with VLC. Had to remove the arguments that VLC adds to the device (the AES ones). So adding a dedicated alsa device iec958 or hdmi which understands these sounds like a good idea.
If you instruct me how to set the no_hdmi_resample option out of the kernel instead of through vcgencmd I can try extending the alsa driver.

**Comment by popcornmix** [comment]
Latest firmware has no_hdmi_resample as default (for alsa). It will only resample if output sample rate is not supported, but using 44.1kHz or 48kHz should be fine.

The only thing you may want to set is hdmi_stream_channels=1 (which can be done with a vcgencmd). Actually many receivers don't care and passthrough may well work with or without this setting.

I can easily add this option as a flag when opening the alsa driver. If you find the right way to name the driver and extract the AES flags so it looks like a passthrough capable sound card that would be good.

A suggestion for how to flag passthrough it is to use channels=0 in the VC_AUDIO_CONFIG_T. structure. That will be interpreted as two channels in most uses, but will signal 0 (refer to stream header) for number of channels in the audio infoframe.

If that sounds okay I'll add that option to the next firmware update.

**Comment by julianscheel** [comment]
Ok, I've got this coded together roughly already. Using channels=0 sounds ok. Is there a possibility to set any of the further iec958 status flags to the chip? Like consumer/professional mode or emphasis settings?
Right now I only care about the NONAUDIO flag which I would use to set channels=0.

As of now I created a dedicated subdevice hw:0,1 for this, probably we could also skip this and configure iec958 to use hw:0,0 as well. It seems that basically all cards seem to make up a dedicated device for spdif, even if it's actually the same device.

**Comment by popcornmix** [comment]
If you make any useful iec958 status bits available in the driver (e.g. where config structure is filled in) I can look at plumbing it through.

**Comment by julianscheel** [comment]
The driver allows the userspace to set AES0...AES3 as parameters. Each one is a byte. Possible values are defined in asoundef.h - I could pass through any of these. Although I doubt it makes sense.
NONAUDIO is important to distinguish PCM vs encoded formats, so this one is handled anyway. Most userspace applications seem to set EMPHASIS on AES0. AES3 can be used to signal FS, don't know if it makes sense to pass that through?
Besides I don't know if any of these flags are really needed in our use-cases. What do you think?

**Comment by popcornmix** [comment]
I can't see any of these being important apart from the NONAUDIO one.
The 192 status bits will be set to sensible defaults by GPU. Looks like we set bits:
1: when passthrough
2: no copyright
24:27: samplerate
32:35: 24-bit samples
36:39: samplerate
all others are clear.

**Comment by julianscheel** [comment]
What about the consumer/professional flag? Does it make any sense for us to set it. Otherwise I will limit the options to just allow userspace to set NONAUDIO and ignore the rest.

I just pushed my wip code: https://github.com/julianscheel/linux/commit/b0d39719c1d606d61a30c7d5d7d5311752cd2b75
Also rebased it onto the rpi-3.10.y branch, just haven't testet it with 3.10, but should work. Additionally to the updated driver you will need a bcm2835.conf (be aware I renamed the driver to just bcm2835 to avoid a long filename with spaces) into /usr/sshare/alsa/cards.
See here: https://gist.github.com/julianscheel/9094131

I have tested this with vlc (--spdif option and --aout alsa). Works very well so far.

**Comment by popcornmix** [comment]
Bit 0 is set to 0 (consumer). I'm not sure what difference professional makes.

I'll test your patch. In theory I should be able to make xbmc output passthrough audio through it and can use that for testing the channels=0 code path.

**Comment by popcornmix** [comment]
Out of interest if driving multichannel PCM through HDMI (without passthrough) how is the speaker mapping configured?
i.e. can the application request 2.1 (left, right, lfe) and 3.0 (left, right, centre)?
Any interest in getting this working?

**Comment by julianscheel** [comment]
I think professional mode is not relevant when looking at hdmi, so we can ignore it. So I will limit the mask of settable bits to IEC958_AES0_NONAUDIO.

Yes, with xbmc you should be able to get it work. Don't forget to install the bcm2835.conf and use iec958 output device.

multichannel PCM: I have no clue, but would be nice to support it. I will try to dig around a little to figure out how this is handled.

**Comment by popcornmix** [comment]
Good new is xbmc detects the sound card "bcm2835 IEC958/HDMI S/PDIF" as passthrough capable. I enable passthough and play, and the log says:

```
16:46:26 513.949951 T:3035858016    INFO: CAESinkALSA::Initialize - Opened device "iec958:CARD=ALSA,DEV=0,AES0=0x06,AES1=0x82,AES2=0x00,AES3=0x02"
```

but it gets opened with 2 channels (rather than 0 I was expecting), so I can't auto-switch the hdmi_stream_channels.
If I manually run "vcgencmd hdmi_stream_channels 1" before playing the file, then passthrough does work.

Any idea why channels=0 is not happening?

**Comment by julianscheel** [comment]
Somehow the control mapping does not work as I expected yet. Just looking at it...

**Comment by julianscheel** [comment]
I just force pushed ammended versions of the patch. They actually store the passend in argument settings properly now.
But there is one issue left: The controls are set after the hw_params call is done. So at the time were I check them they are still wrong. If you open the device two times sequentially (without anyone clearing the flags in between) you should see channels=0 now.
It seems pcm_prepare() would be a better place to signal the spdif stuff to the vchiq. Do you think it would be ok to call bcm2835_audio_set_params there again?
Maybe it would be better to have a dedicated set function just for the spdif stuff then?

**Comment by popcornmix** [comment]
VC_AUDIO_MSG_TYPE_CONFIG is the message that actually opens the audio driver (on GPU) including setting the AV infoframe (so channels is required at this point).

Now you can send that message more than once. The audio driver will be closed and reopened with new settings. That may cause a TV/receiver to do something (e.g. you could see some effect in LCD status indicators).

I believe we normally get the sequence of messages:
VC_AUDIO_MSG_TYPE_OPEN
VC_AUDIO_MSG_TYPE_CONFIG
VC_AUDIO_MSG_TYPE_WRITE (multiple calls)
VC_AUDIO_MSG_TYPE_START 
VC_AUDIO_MSG_TYPE_WRITE (multiple calls)
VC_AUDIO_MSG_TYPE_STOP
VC_AUDIO_MSG_TYPE_CLOSE

We open the driver on the config, rather than the start, so we can submit samples to the driver from the writes before the start message comes.

I could try to do the driver open on the start message, but that would involve keeping hold of the samples submitted since the config so would have some risk of breaking things.
However if you say that not all the information required to open the hdmi driver is available when VC_AUDIO_MSG_TYPE_CONFIG is sent, then perhaps something has to change.

**Comment by julianscheel** [comment]
Looking at the alsa docs (http://www.alsa-project.org/alsa-doc/alsa-lib/group___p_c_m.html#ga1ca0dc120a484965e26cabf966502330) for snd_pcm_hw_params I understand that snd_pcm_prepare is automatically called after the params where successfully set. So from my point of view it sound like it would be safe to move the audio_set_params call into the prepare method. We'd just make sure that snd_pcm_hw_params accepts only allowed hw params, so that the pcm_prepare would not fail later on.
From my debug logs I see that the parameters are always set before snd_pcm_prepare is entered, so this should be safe. What do you think?

**Comment by popcornmix** [comment]
Sounds okay to me. 

I know some calls come from a proper task context and some come from an interrupt context.
snd_bcm2835_pcm_trigger for example is not called from a task context, and so can't call vchiq functions (see the worker queue in bcm2835-vchiq that is needed to deal with this).

That's the only thing to watch out for, but I'd imagine prepare would be triggered by the calling task so I'd expect it to be okay.

**Comment by julianscheel** [comment]
Alright, I'll give it a try.

**Comment by julianscheel** [comment]
Ok, modified this and at least nothing crashes. I only have remote access to an rpi right now so I could not check that sound is really still working. Will do that tomorrow.
Still feel free to give this reworked patch a try:
https://github.com/julianscheel/linux/commit/61735106b41bb1129f66b48df0d971dfa89aa53b
rpi-3.10.y branch is updated as well.
Patch contains a lot of debug output at the moment...

**Comment by julianscheel** [comment]
Just did some testing with the rpi and the patch seems to work fine for me. As long as I do not actually send channels=0. With the current firmware this seems to render the firmware into an erroneous state.

**Comment by popcornmix** [comment]
Here is a test build with a fixed 256M/256M memory split:
https://dl.dropboxusercontent.com/u/3669512/temp/start_alsa_passthrough.elf

It should work with channels=0 and set hdmi_stream_channels.
It also should support setting channels up to 8 and output multichannel PCM.
Currently it gets the speaker placement wrong, but it would be nice to determine how that should be handled.

**Comment by julianscheel** [comment]
Have you tested with that firmware? For me it still seems to go mad when channels=0 is set.

<pre>
[  210.652456] > snd_bcm2835_pcm_prepare()
[  210.652516] snd_bcm2835_pcm_prepare(): spdif_status=0x2008202
[  210.652528] snd_bcm2835_pcm_prepare(): channels=0
[  228.848835] bcm2835_audio_set_ctls_chan:495 bcm2835_audio_set_ctls_chan: failed on waiting for event (status=0)
[  228.849377] bcm2835_audio_set_params:560  Alsa controls not supported
[  228.849712] snd_bcm2835_pcm_prepare:311  error setting hw params
</pre>

**Comment by popcornmix** [comment]
I tested xbmc which used the bcm2835 output for gui sounds, and switched to "bcm2835 IEC958/HDMI S/PDIF driver" when playing video with ac3/dts.
In a debugger I was seeing channels=2 for gui sounds and channels=0 for passthrough and it was working for me.

It is possible that some slightly different configuration is provoking a bug.
Can you provide an executable I can run that will provoke the failure?

**Comment by julianscheel** [comment]
For me the problem raises as soon as channels=0 is set by the driver. I can trigger it with vlc as well as with a simple speaker-test:

<pre>
speaker-test -D iec958:AES0=0x6 -c 2
</pre>

That one will open the device, but closing on terminate will fail and afterwards no audio commands are working at all.

**Comment by popcornmix** [comment]
You are correct - speakertest wasn't working with that firmware. I've uploaded a fixed version (same url).

**Comment by julianscheel** [comment]
Are you sure you've uploaded the corrected version? I've just downloaded it at it still ash build date 20. Feb, same checksum and same error.

**Comment by popcornmix** [comment]
Can you try now?

**Comment by julianscheel** [comment]
This looks better. Just tested it remotely and everything starts and stops smooth now. I will verify that the audio is fine tomorrow and confirm. I will also push a cleaned up version of the driver without all the debug prints then.

**Comment by popcornmix** [comment]
Great. Changing number of channels in driver to 8 should also work, although the channel mapping is wrong. I can take a channel map as a config option, or hard code it if you know what the correct behaviour should be.

**Comment by julianscheel** [comment]
Ok, finally verified that all is working well. With your latest firmware I can easily use spdif passthrough in vlc with the --spdif option :)
I've cleaned up the patch from all the debug print

For rpi-3.6.y: https://github.com/julianscheel/linux/commit/dc0d9f428b59228c490faad94cf83a3717c0d273
For rpi-3.10.y: https://github.com/julianscheel/linux/commit/db269a86d361cd03756d69508b03ceeee4860383

I tested with 3.6, but should be fine with 3.10.
Don't forget that the bcm2835.conf is required :)

**Comment by julianscheel** [comment]
What do you think about merging this patch?
I think would be beneficial for many people.

**Comment by popcornmix** [comment]
Any thoughts on what the implication will be for existing users updating to this kernel (but otherwise not changing .conf files)?

**Comment by julianscheel** [comment]
It should not cause any difference for users which do not have a config file. The soundcard will just not have a iec958 device in that case, so they have no benefit.

The only relevant difference is the renaming of the driver from "BRCM bcm2835 ALSA Driver" to just "bcm2835" which will render existing asound.state files useless. But looking at the triviality of the options the driver exposes this should not be too painful.

Still the question is how to go ahead with the config file. I assume that mainlining in libalsa won't work out as long as the alsa driver itself is not in the mainline kernel. Maybe it can be added to the firmware package for raspbian users?

**Comment by julianscheel** [comment]
@popcornmix Any plans to merge this? Or do you see any outstanding things to be dealt with before merging?

**Comment by popcornmix** [comment]
It's actually on the 3.12.y kernel tree that we should be moving to soon.
I think I'll bump BRANCH=next firmware to 3.12.y (in addition to USB rewrite), and see if any problems are reported.

**Comment by julianscheel** [comment]
Ah, sorry I only checked the 3.10 kernel. Perfect then. Thank you :)

**Comment by julianscheel** [comment]
I just tested this with the latest start.elf from the firmware repository. It behaves like the old versions before your start_alsa_passthrough.elf. Did you incorporate the changes into the main firmware yet?
My testing system ran on start_alsa_passthrough.elf last weeks.

**Comment by popcornmix** [comment]
It looks like it's not in main firmware.

I've found the stashed code from when I was working on this, but it seemed these changes were occurring along with some multichannel audio restructuring that got abandoned for a simpler scheme, so I'll have to unpick the necessary bits (the channels=0 codepath)...

**Comment by julianscheel** [comment]
Ok, do you think you can merge it soon?
I was just about to deploy new firmware to our customers to enable spdif for them. Have to wait for the merge now :)

**Comment by adn770** [comment]
I'm also working on audio pass trough scenarios but by using OpenMax in GStreamer [1].

I've already got a working sink for PCM raw audio with the information at [2] but with the the audio passtrough scenario I get an error in the attempt to allocate the buffers in the input port of audio_render.

audio_render got error: Insufficient resources (0x80001000)

Please could you give us some hint on what might be wrong ?

In order to reproduce the issue you can build with the following:

$ git clone https://github.com/metrological/buildroot
$ cd buildroot
$ make rpi_qt5webkit_defconfig
$ make

To deploy into an SD card with two partitions boot (fat32) and rootfs (ext4):
$ cp output/images/rpi-firmware/\* /media//boot/
$ cp output/images/zImage /media/boot/
$ sudo tar xvf output/images/rootfs.tar -C /media/rootfs/

Download and copy some media with a dolby digital audio track, for example [3]

Once booted the rpi to reproduce the issue run the following GStreamer pipeline:

GST_DEBUG=omx*:4 gst-launch-1.0 filesrc location=/root/h264_720p_hp_5.1_6mbps_ac3_planet.mp4 ! qtdemux ! ac3parse ! queue ! omxhdmiaudiosink

[1] http://cgit.freedesktop.org/~adn770/gst-omx/log/?h=audiosink
[2] http://home.nouwen.name/RaspberryPi/documentation/ilcomponents/audio_render.html
[3] http://www.auby.no/files/video_tests/h264_720p_hp_5.1_6mbps_ac3_planet.mp4

**Comment by julianscheel** [comment]
@AD-N770 I think you should open another bug, as this one is clearly about the alsa kernel driver and not about openmax.

**Comment by adn770** [comment]
@julianscheel sure, I don't want to hijack that ticket just it was so related to my scenario...

Anyway I've opened https://github.com/raspberrypi/linux/issues/564

**Comment by julianscheel** [comment]
@popcornmix Have you had a chance to look into forwardporting the channels==0 change in the firmware?

**Comment by popcornmix** [comment]
I've tidied up the stashed code (which also adds multichannel and 32-bit support) but it needs a bit more testing. I'll push it out by the weekend.

**Comment by julianscheel** [comment]
Perfect, thank you!

**Comment by popcornmix** [comment]
Please test latest rpi-update firmware.

**Comment by julianscheel** [comment]
Seems to work well for me. Thanks :)
I've started some start/stop stress-testing to verify a bit more now. Will close once this ran for a while without issues.

**Comment by popcornmix** [comment]
Note that latest rpi-update firmware is now 3.12 kernel which includes the HDMI passthrough support in alsa driver.

**Comment by julianscheel** [comment]
I'm testing the firmware alone as I am not running raspbian. I'm on my own kernel tree which has the alsa driver patch included anyway.

**Comment by julianscheel** [comment]
Tests were all good for me, I'll close the ticket. Thanks for your efforts.
