### ISSUE TITLE
Support for lfs (large file size)

### ISSUE THREAD

**Issue by lgg2** [raspberrypi/linux#53]
Well, by default the Linux kernel (libc) has a file size limit in 2Gb. If someone want to use RPi as Samba server, would need it.

**Comment by asb** [comment]
I'm certain we are not disabling any support for large files. Have you tested on a non FAT filesystem?

**Comment by lgg2** [comment]
Yes, Try to make a file (dd) of more than 2gb into a ext3 partition...
dd if=/dev/zero of=ABigFile bs=3G
3G number not valid

With 2G without problems....

**Comment by thammi** [comment]
'bs' is the blocksize and not the file size. If you want to use 'dd', try the 'count' option (and read the manual).

Btw: You might want to look at the difference between libc (userland) and the Linux (kernel).

**Comment by lgg2** [comment]
Yes, I know the diferemce of the kernel and libc.

In this case seems to be more problem of libc (I have tested better the problem....)

Thanks and sorry.
