### ISSUE TITLE
watchdog is not installable

### ISSUE THREAD

**Issue by highjagger** [raspberrypi/linux#530]
dpkg --configure -a
Setting up watchdog (5.12-1) ...
/run/udev or .udevdb or .udev presence implies active udev.  Aborting MAKEDEV invocation.
/run/udev or .udevdb or .udev presence implies active udev.  Aborting MAKEDEV invocation.
insserv: warning: script 'mathkernel' missing LSB tags and overrides
insserv: There is a loop between service watchdog and mathkernel if stopped
insserv:  loop involving service mathkernel at depth 2
insserv:  loop involving service watchdog at depth 1
insserv: Stopping mathkernel depends on watchdog and therefore on system facility `$all' which can not be true!
insserv: exiting now without changing boot order!
update-rc.d: error: insserv rejected the script header
dpkg: error processing watchdog (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 watchdog

**Comment by highjagger** [comment]
i can "solve" it by removing wolfram-engine

**Comment by popcornmix** [comment]
Sounds like a raspbian distribution issue rather than a kernel issue.
Best report it here:
http://www.raspbian.org/
or
http://www.raspberrypi.org/phpBB3/viewforum.php?f=66

**Comment by vk5tu** [comment]
It's a bug in the packaging of wolfram-engine (it's missing LSB init tags in /etc/init.d/mathkernel). That package is not part of the Raspbian project.

The reporter can workaround their issue by editing /etc/init.d/mathkernel to add:

### BEGIN INIT INFO

# Provides:          mathkernel

# Required-Start:    $local_fs

# Required-Stop:     $local_fs

# Default-Start:     2 3 4 5

# Default-Stop:      0 1 6

# Short-Description: mathkernel

### END INIT INFO

-glen

**Comment by asb** [comment]
Indeed, I'll talk with the person at Wolfram doing the packaging work.

**Comment by IvanExpert** [comment]
For what it's worth, I just performed an apt-get dist-upgrade over Raspbian 2014-06-20 and got this issue. Don't know if it's been resolved in newer distributions, but thought I'd mention it here.
