### ISSUE TITLE
USB sound card makes ALSA crash with SIP codecs

### ISSUE THREAD

**Issue by Mevon** [raspberrypi/linux#531]
Hello,

I've been struggling for a while now on a trouble I have with my external usb sound card that makes ALSA drivers crash when I use a sip softphone application (linphone, ekiga, etc.). I can play sound files nicely with aplay and record also with arecord, no bug here at all but when I start a VOIP call in linphone, all I get is popping noises and after a while the ALSA layer stops woking. I get some "usb_set_interface failed (-32)" and some "retire_capture_urb callbacks suppressed" in dmesg, and somethings about ALSA libraries not working ("pcm_direct.c (line 980) unable to install hw params" and "pcm_dmix.c (line 1030) unable to initialize slave") when I try to run aplay after the call. The only way to bring it back is to unplug/plug the usb soundcard.

I tried with another usb sound device and the headset works fine with sip calls. I tried plugging the faulty usb card in a win7 laptop and it works fine with another sip phone application.

My sound card is connected directly in the usb port (no hub between) and I could describe the sounds I get like as if a lot of packets are dropped. My guesses would be it's a bandwidth versus bitrate condition that makes a lot of packets to be dropped OR something about opening 2 channels or more when the sip app starts a call.

I'm thinking it could be a ALSA configuration problem or a usb sound card driver missing something or doing something my Conexant Usb Soundcard is not allowing. At some point, I had it working but then the next day it stopped working. 

Now, when I make a call with the sip app, sometimes I get the "I cannot hear the other talking but they hear me" symptoms where the one receiving my call hears my voice like I've been inhaling helium (under sampling resampled to higher sampling rates I guess maybe 44.1k to 48k). 

Any help to troubleshoot this problem or to circumvent where the trouble really comes from (usb stack vs alsa driver configs vs sip phone codec) would be appreciated.

MH

**Comment by Mevon** [comment]
Interesting,

After looking up this webpage: 

http://www.voxforge.org/home/docs/faq/faq/linux-how-to-determine-your-audio-cards-or-usb-mics-maximum-sampling-rate

I tried to figure max sampling rate and arecord gives me this error "arecord set_params:1087 Channels count non available" but works with the option "-c 2".

Maybe I should find a way to set the inputs to stereo or find a way to make my stereo mono.

MH

**Comment by Mevon** [comment]
Here is more information on the usb device Im using 

http://www.conexant.com/Product/Audio/usbaudio/CX20709/Pages/default.aspx

MH

**Comment by P33M** [comment]
When you say a VOIP call, does that mean a sound source and sink are being used at the same time?

Please post a full `dmesg` and `sudo lsusb -v`

**Comment by Mevon** [comment]
Hi P33M,

Thank you for helping me, it is very much appreciated.

Here is the "lsusb - v" pastebin link:

http://pastebin.com/ERkBPETc

Here is the "dmesg" pastebin link:

http://pastebin.com/gtLJWnqt

And yes SIP softphone apps like Linphone, Ekiga, etc. are full duplex VoIP applications that are opening Transmit and Receive streams when making a call. I could be wrong but I'm pretty sure they are using Microphone input and Headphone output at the same time. My device is specified for USB 2.0 and its not connected through a USB hub, even though I have one listed, I have the same results if it is not plugged in the RasPi at all.

Thanks again, best regards,
MH

**Comment by P33M** [comment]
There will be a certain threshold of bitrate/sample rate that will currently work. A mono microphone recording at 48k/16bit _should_ work, but playback is likely to be distorted also unless you pick a mono output channel.

**Comment by Mevon** [comment]
Hi P33M,

I have a stereo microphone and I can playback mono sound files with no problem.

Thank you,
MH

**Comment by P33M** [comment]
Can you give `sudo BRANCH=next rpi-update` a go?

**Comment by Mevon** [comment]
Hello,

I just tried the above command and it seemed to help a little. Now, it looks like the microphone input works better but the playback seems to be more choppy. So choppy, that when I am making a VoIP call, what I receive in my headphones is just scratchy noise BUT on the other end of the call, the receiving is good. In other words, what I am capturing from the microphone input, sending through VoIP and is received on the other end of the call, the quality is perfect. 

I have tried some "aplay" with some audio files and it is real buggy too now. Before the update, I could play wavefiles without any noise or scratching of any kind, now it is barely acceptable, quality wise. I tried playing stereo 48000 WAV files from this site: 

http://www.kozco.com/tech/soundtests.html

and some mono low quality files from the /usr/share/scratch/Media/Sounds/ folders, with the same result: scratchy and barely acceptable playback quality.

Just let me know what you want me to do next, thanks for your support,
MH

**Comment by P33M** [comment]
There's a known issue with Split-isoc OUT transactions. fiq_fsm schedules and performs the transactions correctly: there's a bug where the actual data transmitted is garbled.

**Comment by Mevon** [comment]
Ok, just to confirm, I tried with the other usb soundcard (Microsoft usb headphone) and sound output is garbled too. Seems worst then before the "rpi-update" now, as in I don't get the microphone input at the other end of the call and I cannot hear the caller neither.

Thanks again for the support, let me know when this bug will be fixed.
MH

**Comment by P33M** [comment]
Please update to latest BRANCH=next firmware and see if there any changes.

You could try with the playback device as the 3.5 jack on the Pi as a workaround (and separate Mic connected to the USB sound card). I will investigate duplex audio in due course.

Can you post a lsusb -v for the Microsoft headphones?

**Comment by Mevon** [comment]
Here you go:

http://pastebin.com/8Lt2RdqM

Thanks again for your support,
MH

**Comment by P33M** [comment]
Duplex audio should now be functional in rpi-update firmware.

**Comment by P33M** [comment]
No response from OP in two weeks: assuming functional.
