### ISSUE TITLE
my wifi is shit :( can anyone help me

### ISSUE THREAD

**Issue by lamvu22078** [raspberrypi/linux#5310]
### Describe the bug

i cant dowload :(((

### Steps to reproduce the behaviour

a

### Device (s)

Other

### System

a

### Additional context

![image](https://user-images.githubusercontent.com/111492806/211327594-f64fec02-ef87-412f-a99a-1d745be62b71.png)

**Comment by lamvu22078** [comment]
21.9kbps dowload:(

**Comment by lamvu22078** [comment]
![image](https://user-images.githubusercontent.com/111492806/211328238-d5af7cb4-7175-4d38-bfba-0ecb2c4c4307.png)

**Comment by pelwell** [comment]
What kind of problem report is this? For all I know, you aren't even using a Raspberry Pi.

We don't have time to walk individual users through what could just be a configuration issue. Start a thread here (https://forums.raspberrypi.com/viewforum.php?f=29), and expect to be ignored if you can't be bothered to provide some details about your system (which model of Pi, software version, type of AP etc.).
