### ISSUE TITLE
Boot end mode of gpios 28-31 seems to have changed from INPUT to ALT2

### ISSUE THREAD

**Issue by joan2937** [raspberrypi/linux#532]
Some time between May 2013 and today (probably a couple of months ago) the mode of gpios 28, 29, 30, and 31 appears to have changed from INPUT to ALT2.

A consequence is that gpio28 transmits the PCM clock once PCM is enabled.

I went back to the last Debian image dated May 2013 and booted.  Gpios 28-31 were mode INPUT.  I performed an rpi-update and rebooted.  Gpios 28-31 were mode ALT2.

**Comment by popcornmix** [comment]
Are you using 1-wire (or similar) module?
I think there is a bug where it tramples some GPIO settings:
https://github.com/raspberrypi/linux/issues/435

**Comment by joan2937** [comment]
It seems to be the module snd_soc_bcm2708_i2s.  Given I2S uses the PCM perhaps it's not so surprising.

When I blacklist that module gpios 28-31remain as inputs at the end of boot.

I didn't knowingly make any changes to the sound system (as I never use sound on the Pi).

**Comment by popcornmix** [comment]
Yes. That's not entirely desired. We get the same behaviour from I2C/SPI drivers and so raspbian blacklists them by default, so we probably need to do that for i2s as well.

Blacklisting is the correct solution for now.

**Comment by joan2937** [comment]
Ok, I'll consider this closed as a kernel issue.
