### ISSUE TITLE
h.265 movie titles stopped playing on Kodi 19.5 OSMC 

### ISSUE THREAD

**Issue by climons** [raspberrypi/linux#5322]
### Describe the bug

After one of the latest OSMC updates (December 2022 - early January 2023) all the movie titles encoded with h.265, both 2K and 4K stopped playing. The symptoms are uniform - "sad  face" screen on OSMC. For the last 2 years there hadn't been any problem with this until the last week. 

### Steps to reproduce the behaviour

Just start any movie encoded with HEVC, 10-bit.

the previously vieawable title starts loading at the time stamp 2023-01-14 21:28:13.403 T:785

The last entries in the OSMC log - 
2023-01-14 21:28:13.864 T:1027 ERROR : ffmpeg[(nil)X]: [hevc] Unable to set controls: Bad address
2023-01-14 21:28:13.864 T:1027 ERROR : ffmpeg[(nil)X]: [hevc] v4l2_request_hevc_decode_slice: Failed to set ext ctrl slice params

### Device (s)

Raspberry Pi 4 Mod. B

### System

Kernel:
Linux MediaPi4 5.15.83-2-osmc #1 SMP PREEMPT Sat Jan 7 04:20:21 UTC 2023 aarch64 GNU/Linux

Firmware:
Oct 26 2022 11:09:58
Copyright (c) 2012 Broadcom
version c72ad6b26ff40c91ef776b847436094ee63fabee (clean) (release) (start_x)

### Logs

OSMC log link - https://paste.osmc.tv/asiruwavun
dmesg - 
[dmesg.txt](https://github.com/raspberrypi/linux/files/10428646/dmesg.txt)

**Comment by popcornmix** [comment]
You need to report this to OSMC.
I think their stable kernel is on 5.10, and the 5.15 was only on testing, and it requires a ffmpeg update that hasn't been done yet.

But this isn't something we can solve here. Ask on the osmc forum.

**Comment by climons** [comment]
Thank you !
