### ISSUE TITLE
enable drivers/staging/comedi (data acquisition)

### ISSUE THREAD

**Issue by berndporr** [raspberrypi/linux#534]
comedi is a data acquisition framework which allows easy driver development for anything that is analogue and digital IO. This would be very useful to have this enabled in the kernel. I'm developer of the USBDUX boards and I use the raspberry PI in conjunction with these boards:
http://www.linux-usb-daq.co.uk/software2/rpi/
However in order to use the boards I need to re-compile the kernel. I've also developed a small add on card for the RPI which could serve as an example how to write drivers for this framework:
http://web.eng.gla.ac.uk/rpi/

**Comment by bigguiness** [comment]
On Friday, February 14, 2014 12:32 PM, Bernd Porr wrote:

> comedi is a data acquisition framework which allows easy driver
> development for anything that is analogue and digital IO. This
> would be very useful to have this enabled in the kernel. I'm
> developer of the USBDUX boards and I use the raspberry PI
> in conjunction with these boards:
> http://www.linux-usb-daq.co.uk/software2/rpi/
> However in order to use the boards I need to re-compile the
> kernel. I've also developed a small add on card for the RPI
> which could serve as an example how to write drivers for
> this framework:
> http://web.eng.gla.ac.uk/rpi/

Hello Bernd,

Do you have any of the add-on cards for the RPI? I would love
to have one to test with comedi.

BTW, I would also love to have one of the USBDUX boards to
test with. :-)

Are you planning on submitting a driver for this board?

Regards,
Hartley

**Comment by popcornmix** [comment]
Are you requesting additional module(s) are enabled in bcmrpi_defconfig? If so which one(s)?

**Comment by berndporr** [comment]
Hi Hartley,

I can send you the newest version of the add on card. We will be using 
it for teaching in two weeks. I haven't managed to write a driver for 
comedi yet but if you have time to write one with me that would be grand.

I'm sure I have a USBDUX-D kicking about. PM me with your postal 
address: mail@berndporr.me.uk

/Bernd
P.S.: will send the kernel config to enable comedi later here on GIT.

H Hartley Sweeten wrote:

> On Friday, February 14, 2014 12:32 PM, Bernd Porr wrote:
> 
> > comedi is a data acquisition framework which allows easy driver
> > development for anything that is analogue and digital IO. This
> > would be very useful to have this enabled in the kernel. I'm
> > developer of the USBDUX boards and I use the raspberry PI
> > in conjunction with these boards:
> > http://www.linux-usb-daq.co.uk/software2/rpi/
> > However in order to use the boards I need to re-compile the
> > kernel. I've also developed a small add on card for the RPI
> > which could serve as an example how to write drivers for
> > this framework:
> > http://web.eng.gla.ac.uk/rpi/
> 
> Hello Bernd,
> 
> Do you have any of the add-on cards for the RPI? I would love
> to have one to test with comedi.
> 
> BTW, I would also love to have one of the USBDUX boards to
> test with. :-)
> 
> Are you planning on submitting a driver for this board?
> 
> Regards,
> Hartley
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/raspberrypi/linux/issues/534#issuecomment-35122365.

## 

www:    http://www.linux-usb-daq.co.uk/
    http://www.berndporr.me.uk/
    http://www.imdb.com/name/nm3293421/
Mobile: +44 (0)7840 340069
Work:   +44 (0)141 330 5237
         University of Glasgow
         School of Engineering
         72 Oakfield Avenue (Rankine Building for deliveries)
         Glasgow, G12 8LT

**Comment by berndporr** [comment]
CONFIG_COMEDI=m
CONFIG_COMEDI_DEFAULT_BUF_SIZE_KB=2048
CONFIG_COMEDI_DEFAULT_BUF_MAXSIZE_KB=20480
CONFIG_COMEDI_MISC_DRIVERS=y
CONFIG_COMEDI_USB_DRIVERS=y
CONFIG_COMEDI_DT9812=m
CONFIG_COMEDI_USBDUX=m
CONFIG_COMEDI_USBDUXFAST=m
CONFIG_COMEDI_USBDUXSIGMA=m
CONFIG_COMEDI_VMK80XX=m
CONFIG_COMEDI_8255=m
CONFIG_COMEDI_FC=m

that enables the USB based drivers and a couple of other drivers which might be useful.

**Comment by graeme-hattan** [comment]
I've just made a new custom kernel for the B+:
http://www.linux-usb-daq.co.uk/software2/rpi/
It would be really great if you guys could enable comedi on the RPI kernel by default (see above). That would then allow all USB based data acquision devices to be used out of the box with the RPI. I've got a couple of customers who use the USB-DUX with the RPI and it's a real pain for them to download my comedi enabled kernel from the webpage and then untar them over the standard Raspbian image. Ubuntu and other distros have the comedi kernel drivers enabled by default but not the Raspbian.
I would really appreciate your help here. /Bernd

**Comment by Ruffio** [comment]
@berndporr has this issue been resolved? If yes, then please close this issue.

**Comment by Ruffio** [comment]
@popcornmix please consider closing this issue as there haven't been any activity since Oct 2014 and no response to my ping 19 days ago.

**Comment by berndporr** [comment]
Since the COMEDI drivers are still removed from the RPI kernel I've extracted the sources from the vanilla kernel and made them compile outwidth of the kernel:
https://github.com/glasgowneuro/comedi_raspberry_pi_bullseye

See also this thread:
https://groups.google.com/g/comedi_list/c/tBYH4iQeL14/m/iL5r4wlNBAAJ

Note the USB-DUX boards are now open hard- and software: https://github.com/glasgowneuro/usbdux
