### ISSUE TITLE
Built-in BTRFS support

### ISSUE THREAD

**Issue by solskogen** [raspberrypi/linux#5342]
### Describe the bug

BTRFS is, as of now, enabled as a module. This means that to be able to use BTRFS as your root filesystem you must use initrd ramdisk, and this part is a bit tricky to get to work (but it can be done).  With BTRFS compiled in the kernel, this part would a lot easier. 

### Steps to reproduce the behaviour

.

### Device (s)

Raspberry Pi 4 Mod. B

### System

Linux raspberrypi 5.15.84-v8+ #1613 SMP PREEMPT Thu Jan 5 12:03:08 GMT 2023 aarch64

**Comment by zhiyuan1i** [comment]
I can not agree more, and I wish I could have btrfs built into the kernel when it was built

**Comment by solskogen** [comment]
With the newest Raspberry PI OS, using btrfs is quite easy. Closing the issue.

**Comment by Fantu** [comment]
hi, I not tried rapsberry based on debian 12 yet.
rpi kernel now have btrfs built-in or is only faster/easier workaround for kernel/bootloader/firmware changes to debian based that is better?

**Comment by brian6932** [comment]
But this isn't an issue with Pi OS, it's an issue with rpi-kernel. I'm on Void Linux, and use this kernel, I had to use an initramfs (on an installation via xchroot to install booster) to have btrfs root.

**Comment by pelwell** [comment]
> I had to use an initramfs (on an installation via xchroot to install booster) to have btrfs root.

That is the intended behaviour. Bookworm RPiOS makes that easy, which is what @solskogen was referring to.

**Comment by brian6932** [comment]
The issue states that it's a module and not built into the kernel, how's the issue resolved?

**Comment by XECDesign** [comment]
Wouldn't it be more appropriate to request that whoever maintains the relevant kernel package in void linux enables the option on their end? I'm not sure it makes sense to enable it in the defconfigs here.

**Comment by pelwell** [comment]
> The issue states that it's a module and not built into the kernel, how's the issue resolved?

initramfs includes enough modules to get the rootfs loaded:  https://www.linuxfromscratch.org/blfs/view/svn/postlfs/initramfs.html
and it is loaded by the firmware.
