### ISSUE TITLE
Cannot build rpi-3.10.y: Warning as error in drivers/net/wireless/rtl8192cu

### ISSUE THREAD

**Issue by mdittmer** [raspberrypi/linux#536]
I am using github.com/rapberrypi/tools softfp cross-compiler [1] and following instructions from elinux.org [2] to build a fresh clone of the rpi-3.10.y branch (current default branch). I copied arch/arm/configs/bcmrpi_defconfig, set my cross-compiler prefix, and chose defaults for other kernel configuration options. I see the following error:

In file included from drivers/net/wireless/rtl8192cu/core/rtw_cmd.c:23:0: drivers/net/wireless/rtl8192cu/include/osdep_service.h: In function 'thread_enter': drivers/net/wireless/rtl8192cu/include/osdep_service.h:1482:2: error: implicit declaration of function 'daemonize' [-Werror=implicit-function-declaration]

This is strange because the line of code in question is surrounded by"
# if (LINUX_VERSION_CODE < KERNEL_VERSION(3, 8, 0))

...
# endif

When I looked into it, I found that the KERNEL_VERSION_CODE on the branch is 197120; i.e., 3.3.0. Why is this the case? Shouldn't it be 3.10.something?

[1] http://elinux.org/RPi_Kernel_Compilation
[2] https://github.com/raspberrypi/tools/tree/master/arm-bcm2708/arm-bcm2708-linux-gnueabi/bin

**Comment by popcornmix** [comment]
Have you switched firmware branches in git?
Try deleting:
include/generated/uapi/linux/version.h
and making again - it will be recreated.

**Comment by mdittmer** [comment]
That seems to have worked. Thanks!

//Mark
