### ISSUE TITLE
3.12.y: In function ‘bcm2708_dma_tx_status’: error: ‘DMA_COMPLETE’ undeclared (first use in this function)

### ISSUE THREAD

**Issue by rolsch** [raspberrypi/linux#537]
I've see this error in my compile-log:

...
  CC [M]  drivers/dma/virt-dma.o
  CC [M]  drivers/dma/bcm2708-dmaengine.o
drivers/dma/bcm2708-dmaengine.c: In function ‘bcm2708_dma_tx_status’:
drivers/dma/bcm2708-dmaengine.c:215:13: error: ‘DMA_COMPLETE’ undeclared (first use in this function)
  if (ret == DMA_COMPLETE || !txstate)
             ^
drivers/dma/bcm2708-dmaengine.c:215:13: note: each undeclared identifier is reported only once for each function it appears in
make[2]: **\* [drivers/dma/bcm2708-dmaengine.o] Fehler 1
make[1]: **\* [drivers/dma] Fehler 2
make: **\* [drivers] Fehler 2
desktop:~/rpi1/kernel312$ 
...

**Comment by popcornmix** [comment]
I think that should be DMA_SUCCESS in 3.12.y (it changed to DMA_COMPLETE in 3.13.y).
I've pushed a rebased 3.12.y tree - does that build okay?

**Comment by rolsch** [comment]
Hello,
here is the next compile log, sorry, the next error:
...
  CALL    scripts/checksyscalls.sh
  CC [M]  sound/soc/bcm/bcm2708-i2s.o
sound/soc/bcm/bcm2708-i2s.c:700:2: error: unknown field ‘set_bclk_ratio’ specified in initializer
  .set_bclk_ratio = bcm2708_i2s_set_dai_bclk_ratio
  ^
sound/soc/bcm/bcm2708-i2s.c:701:1: warning: initialization from incompatible pointer type [enabled by default]
 };
 ^
sound/soc/bcm/bcm2708-i2s.c:701:1: warning: (near initialization for ‘bcm2708_i2s_dai_ops.set_tdm_slot’) [enabled by default]
make[3]: **\* [sound/soc/bcm/bcm2708-i2s.o] Fehler 1
make[2]: **\* [sound/soc/bcm] Fehler 2
make[1]: **\* [sound/soc] Fehler 2
make: **\* [sound] Fehler 2
...

**Comment by popcornmix** [comment]
I've reapplied the i2s patches, and 3.12.y builds for me.

Are you using 3.12.y for a specific purpose?
Generally stable (3.10.y) and latest (3.13.y currently) kernels will be tested by me. The others get less attention.

**Comment by rolsch** [comment]
I'm using the 3.12.y kernel for my rpi-usb-wifi-stick with RTL8188EU.

(my cross-compile script: http://pastebin.com/XtUxfxZ8) 

The kernel menuconfig
- Device drivers
- Staging drivers
- Realtek RTL8188EU
- ... AP Mode
- ... Peer to Peer mode

===> this Driver is not in the 3.10.y tree.

I think the 3.13.y ist too fresh for a "stable" kernel.

**Comment by Ruffio** [comment]
has this issue been resolved? If yes, then please close this issue.

**Comment by Ruffio** [comment]
@popcornmix please consider to close this issue as there have not been any activity since Feb 2014 and no response to my ping a month ago...
