### ISSUE TITLE
Please please add slram + phram as modules (config MTD_SLRAM=m, config MTD_PHRAM=m))

### ISSUE THREAD

**Issue by TimeZlicer** [raspberrypi/linux#538]
drivers/mtd/devices/Kconfig
config MTD_SLRAM
config MTD_PHRAM

Motivation:
To squeeze the last drop of RAM on a headless setup

Thanks in advance!

**Comment by popcornmix** [comment]
Have you tried these?
What are you using as the extra memory device?

**Comment by TimeZlicer** [comment]
have not tried this

using Pi Model B, 512 MB RAM (496 MB, 16 MB minimum reserved for video), 16 MB swap file on SD

**Comment by popcornmix** [comment]
I don't really understand how it is expected to help.
How is this better than using swap on sdcard?

**Comment by TimeZlicer** [comment]
assuming RAM is faster than sdcard, performance could be better?

would like to use the 16MB RAM reserved for video in a headless setup
if not as swap, could be a RAM drive

**Comment by popcornmix** [comment]
I don't think this is possible on the Pi.
The 16M used by GPU cannot be used by the ARM.

**Comment by TimeZlicer** [comment]
from this article, it seems slram/phram is to do that
(but it's not on arm)

http://www.gentoo-wiki.info/TIP_Use_memory_on_video_card_as_swap

**Comment by ghollingworth** [comment]
This is not possible on the Raspberry Pi
