### ISSUE TITLE
Find

### ISSUE THREAD

**Issue by Danielb323** [raspberrypi/linux#5383]
find / -cmin -60

**Comment by pelwell** [comment]
Is that it? We'll need more information if you are reporting a problem.

**Comment by Danielb323** [comment]
It will not let me run it it say permission denied

**Comment by popcornmix** [comment]
This repo is for reporting bugs with the linux kernel.
For help with using linux commands, you'd get a better response on the [forum](https://forums.raspberrypi.com/index.php)
