### ISSUE TITLE
Kernel panic on plugging in USB AV capture device

### ISSUE THREAD

**Issue by tvjon** [raspberrypi/linux#539]
This is a relatively old device so not too concerned about it, rather plugging it in shouldn't crash the RPi, & it may be helpful wrt the new FIQ handler. 

![image](https://f.cloud.github.com/assets/5360158/2286202/9174297c-9fde-11e3-8360-93a2f26c5e03.jpg)

**Comment by P33M** [comment]
Is this with or without fiq_fsm?

**Comment by tvjon** [comment]
With.

Would you like me to change the mask bits?

**Comment by P33M** [comment]
Please post a full lsusb -v.

A quick google suggests that this may be a full-speed device: if it is, then try again with fiq_fsm_mask=0x1.

**Comment by tvjon** [comment]
I used the Pi's described in the KVM post, so same lsusb applies. I can't  post such with device plugged in as it's guaranteed to crash the Pi.

I think it's a usb 1.x device, but will investigate further....

**Comment by tvjon** [comment]
Here's a display of the result plugging in this capture device on the same setup as I just posted in the other thread. 

I'll have another attempt at finding out more about the device too. 

![image](https://f.cloud.github.com/assets/5360158/2359348/8b7a13d6-a616-11e3-8e49-271b16f18e06.jpg)

**Comment by tvjon** [comment]
http://www.echofx.com/usbvision.html

gives a bit more info. I remebered I used their OS X driver for the device.

Would it help you to have this device for testing? If so, let me know & I'll pop it in a Jiffy bag. I don't know if there's a PM system on Github.

**Comment by P33M** [comment]
It would be useful to at least see if there's anything particular that the driver (or this device) does that's "wrong". Can you part with it for ~2 weeks?

**Comment by tvjon** [comment]
I've just emailed but it's bounced. Forget that, it's gone ok this time.

**Comment by P33M** [comment]
The device itself can be communicated with fine.

The problem is within the device driver: i.e. an upstream bug. As the device is USB1.1 it will have bad performance anyway: USB2.0 capture devices will work a lot better.
