### ISSUE TITLE
Update from 19. or 20.03.2023: Driver files were not unpacked

### ISSUE THREAD

**Issue by kosmosgit** [raspberrypi/linux#5391]
### Describe the bug

Since the last update of March 19th or 20th, 2023, several directories, e.g

/lib/modules/6.1..../kernel/drivers/staging/vc04_services/bcm2835-audio....

the archives are not unpacked. The Raspberry therefore lacks drivers such as the sound driver.

There is no longer a choice between audio jack and HDMI as the audio symbol only shows mute

### Steps to reproduce the behaviour

i have do an Update sudo apt-get update && sudo apt-get upgrade && sudo apt-get dist-upgrade

### Device (s)

Raspberry Pi 4 Mod. B

### System

Raspberry Pi reference 2019-09-26
Generated using pi-gen, https://github.com/RPi-Distro/pi-gen, 80d486687ea77d31fc3fc13cf3a2f8b464e129be, stage5

Mar 17 2023 10:50:39 
Copyright (c) 2012 Broadcom
version 82f3750a65fadae9a38077e3c2e217ad158c8d54 (clean) (release) (start)

Linux RPi4WZ 6.1.19-v8+ #1637 SMP PREEMPT Tue Mar 14 11:11:47 GMT 2023 aarch64 GNU/Linux

**Comment by pelwell** [comment]
What does `df /` report?

**Comment by kosmosgit** [comment]
i have delete /boot/.firmware_revision and make rpi-update again, now it works again. It is normal that the drivers are unpack. Boot partition is big enough

df: /run/user/1000/doc: Die Operation ist nicht erlaubt
Dateisystem    1K-Blöcke  Benutzt Verfügbar Verw% Eingehängt auf
/dev/root      122565724 87602388  29903380   75% /
devtmpfs         1652924        0   1652924    0% /dev
tmpfs            1917148       12   1917136    1% /dev/shm
tmpfs             766860     1592    765268    1% /run
tmpfs               5120        4      5116    1% /run/lock
/dev/loop0           128      128         0  100% /snap/bare/5
/dev/loop1         47232    47232         0  100% /snap/core18/2711
/dev/loop2         47232    47232         0  100% /snap/core18/2719
/dev/loop3        145536   145536         0  100% /snap/gnome-3-28-1804/129
/dev/loop4        147968   147968         0  100% /snap/gnome-3-28-1804/163
/dev/loop5         66816    66816         0  100% /snap/gtk-common-themes/1519
/dev/loop7         41856    41856         0  100% /snap/snapd/18601
/dev/loop6         83328    83328         0  100% /snap/gtk-common-themes/1534
/dev/loop11        74112    74112         0  100% /snap/teams-for-linux/290
/dev/loop8        146816   146816         0  100% /snap/gnome-3-28-1804/146
/dev/loop9         41856    41856         0  100% /snap/snapd/18359
/dev/loop10        93952    93952         0  100% /snap/gtk-common-themes/1535
/dev/loop12        74112    74112         0  100% /snap/teams-for-linux/292
/dev/mmcblk0p1    258095    51406    206689   20% /boot
tmpfs             383428       52    383376    1% /run/user/1000

**Comment by pelwell** [comment]
Comment if this happens again, but for now I'm putting this down to a one-off glitch. Perhaps the unpacking got interrupted?
