### ISSUE TITLE
framebuffer not working without "framebuffer console" support

### ISSUE THREAD

**Issue by LarsWeber** [raspberrypi/linux#54]
setting CONFIG_FRAMEBUFFER_CONSOLE=n results in not working frambuffer.

bcm2708_fb_set_par doesn't get called.

[  124.796663] BCM2708FB: registering framebuffer (656x416@16)
[  124.802794] BCM2708FB: register framebuffer (0)
# fbset -g  656 416 656 416 16 -fb /dev/fb0
# dd if=/dev/zero of=/dev/fb0

dd: writing '/dev/fb0': No such device

**Comment by Ferroin** [comment]
As far as I know, you need CONFIG_FRAMEBUFFER_CONSOLE=y for the Pi to do any video output at all, although you don't need it if you are running it headless (without a display).

**Comment by LarsWeber** [comment]
yes i know - thats exactly my problem.

usualy you expect the framebuffer to work even without the console support!

**Comment by jeffreyscottgraham** [comment]
What is the status now? Do you still need to set CONFIG_FRAMEBUFFER_CONSOLE=y in order to get a functioning fb?

**Comment by LarsWeber** [comment]
Have not tried it since then...

Am 17.01.2013 19:06, schrieb jeffreyscottgraham:
