### ISSUE TITLE
Enable SCSI Generic Kernel Support/Module

### ISSUE THREAD

**Issue by jolouis** [raspberrypi/linux#540]
Please enable compilation of the SCSI Generic Kernel Module (sg.ko) as defined by:
CONFIG_CHR_DEV_ST=m
in kernel configuration. This is mainly to support cameras and Digital Picture Frames that rely on this low-level interface in order to communicate with gphoto. 

The driver is in the mainline kernel and has been for a long time, it just needs to be enabled and compiled in order to be useful.

**Comment by popcornmix** [comment]
I believe this is enabled.

```
$ uname -a
Linux raspberrypi 3.10.30+ #922 PREEMPT Fri Feb 14 13:10:46 GMT 2014 armv6l GNU/Linux
$ zcat /proc/config.gz |grep CHR_DEV_ST
CONFIG_CHR_DEV_ST=m
```

**Comment by jolouis** [comment]
Sorry my bad that's what I get for posting after spending hours fighting kernels. The SCSI Generic module is SG, not ST. So kernel config needed is:

```
CONFIG_CHR_DEV_SG=m
```

I did an update via rpi-update last night and am showing:

```
$ uname -a
Linux raspberrypi 3.10.32+ #648 PREEMPT Fri Feb 28 16:29:56 GMT 2014 armv6l GNU/Linux
$zcat /proc/config.gz |grep CHR_DEV_SG
# CONFIG_CHR_DEV_SG is not set

```

**Comment by popcornmix** [comment]
Okay, added to linux tree. Will be in next firmware build.

**Comment by jolouis** [comment]
Awesome thanks!

**Comment by popcornmix** [comment]
This is now in latest rpi-update firmware.
