### ISSUE TITLE
Main Info Could not load the Qt platform plugin "xcb" in "" even though it was found.

### ISSUE THREAD

**Issue by yaz29** [raspberrypi/linux#5406]
### Describe the bug

Start the test. Run the Pi with internal WLAN(2.4GHz) . I installed wireshark Not issue
The issue started when I try to run Wireshark

error should 23:51:14.549     Main Warn could not connect to display 
23:51:14.549     Main Info Could not load the Qt platform plugin "xcb" in "" even though it was found.
Aborted

I installed "sudo apt-get install libxcb-xinerama0"
sudo apt-get install libxkbcommon-x11-0

<img width="568" alt="Screenshot 2023-03-28 at 00 38 59" src="https://user-images.githubusercontent.com/29466688/228091267-9a425767-a69f-4142-84ca-746fd8140a7b.png">

### Steps to reproduce the behaviour

 - install wireshark
 - Created group
 - 

<img width="568" alt="Screenshot 2023-03-28 at 00 38 59" src="https://user-images.githubusercontent.com/29466688/228091411-7a84cbf8-54ba-4843-b10b-137db4406c06.png">

### Device (s)

Raspberry Pi 4 Mod. B

### System

Raspberry Pi reference 2023-02-21
Generated using pi-gen, https://github.com/RPi-Distro/pi-gen, f2d385517c9631f2ded876deb1115725d0c75995, stage4

pi@gponcekpi:~ $ vcgencmd version
Jan  5 2023 10:46:54 
Copyright (c) 2012 Broadcom
version 8ba17717fbcedd4c3b6d4bce7e50c7af4155cba9 (clean) (release) (start)

pi@gponcekpi:~ $ uname -a
Linux gponcekpi 5.15.84-v7l+ #1613 SMP Thu Jan 5 12:01:26 GMT 2023 armv7l GNU/Linux

### Logs

[    0.000000] Booting Linux on physical CPU 0x0
[    0.000000] Linux version 5.15.84-v7l+ (dom@buildbot) (arm-linux-gnueabihf-gcc-8 (Ubuntu/Linaro 8.4.0-3ubuntu1) 8.4.0, GNU ld (GNU Binutils for Ubuntu) 2.34) #1613 SMP Thu Jan 5 12:01:26 GMT 2023
[    0.000000] CPU: ARMv7 Processor [410fd083] revision 3 (ARMv7), cr=30c5383d
[    0.000000] CPU: div instructions available: patching division code
[    0.000000] CPU: PIPT / VIPT nonaliasing data cache, PIPT instruction cache
[    0.000000] OF: fdt: Machine model: Raspberry Pi 4 Model B Rev 1.4
[    0.000000] random: crng init done
[    0.000000] Memory policy: Data cache writealloc
[    0.000000] Reserved memory: created CMA memory pool at 0x000000001ac00000, size 320 MiB
[    0.000000] OF: reserved mem: initialized node linux,cma, compatible id shared-dma-pool
[    0.000000] Zone ranges:
[    0.000000]   DMA      [mem 0x0000000000000000-0x000000002fffffff]
[    0.000000]   Normal   empty
[    0.000000]   HighMem  [mem 0x0000000030000000-0x00000000fbffffff]
[    0.000000] Movable zone start for each node
[    0.000000] Early memory node ranges
[    0.000000]   node   0: [mem 0x0000000000000000-0x000000003b3fffff]
[    0.000000]   node   0: [mem 0x0000000040000000-0x00000000fbffffff]
[    0.000000] Initmem setup node 0 [mem 0x0000000000000000-0x00000000fbffffff]
[    0.000000] percpu: Embedded 16 pages/cpu s35788 r8192 d21556 u65536
[    0.000000] pcpu-alloc: s35788 r8192 d21556 u65536 alloc=16*4096
[    0.000000] pcpu-alloc: [0] 0 [0] 1 [0] 2 [0] 3 
[    0.000000] Built 1 zonelists, mobility grouping on.  Total pages: 1011008
[    0.000000] Kernel command line: coherent_pool=1M 8250.nr_uarts=0 snd_bcm2835.enable_compat_alsa=0 snd_bcm2835.enable_hdmi=1  smsc95xx.macaddr=E4:5F:01:3E:4A:DB vc_mem.mem_base=0x3ec00000 vc_mem.mem_size=0x40000000  console=ttyS0,115200 console=tty1 root=PARTUUID=b0ef97d1-02 rootfstype=ext4 fsck.repair=yes rootwait
[    0.000000] Dentry cache hash table entries: 131072 (order: 7, 524288 bytes, linear)
[    0.000000] Inode-cache hash table entries: 65536 (order: 6, 262144 bytes, linear)
[    0.000000] mem auto-init: stack:off, heap alloc:off, heap free:off
[    0.000000] software IO TLB: mapped [mem 0x0000000014890000-0x0000000018890000] (64MB)
[    0.000000] Memory: 3601324K/4050944K available (10240K kernel code, 1386K rwdata, 3308K rodata, 2048K init, 591K bss, 121940K reserved, 327680K cma-reserved, 3264512K highmem)
[    0.000000] SLUB: HWalign=64, Order=0-3, MinObjects=0, CPUs=4, Nodes=1
[    0.000000] ftrace: allocating 35518 entries in 105 pages
[    0.000000] ftrace: allocated 105 pages with 4 groups
[    0.000000] trace event string verifier disabled
[    0.000000] rcu: Hierarchical RCU implementation.
[    0.000000] 	Rude variant of Tasks RCU enabled.
[    0.000000] 	Tracing variant of Tasks RCU enabled.
[    0.000000] rcu: RCU calculated value of scheduler-enlistment delay is 10 jiffies.
[    0.000000] NR_IRQS: 16, nr_irqs: 16, preallocated irqs: 16
[    0.000000] GIC: Using split EOI/Deactivate mode
[    0.000000] irq_brcmstb_l2: registered L2 intc (/soc/interrupt-controller@7ef00100, parent irq: 25)
[    0.000000] arch_timer: cp15 timer(s) running at 54.00MHz (phys).
[    0.000000] clocksource: arch_sys_counter: mask: 0xffffffffffffff max_cycles: 0xc743ce346, max_idle_ns: 440795203123 ns
[    0.000000] sched_clock: 56 bits at 54MHz, resolution 18ns, wraps every 4398046511102ns
[    0.000022] Switching to timer-based delay loop, resolution 18ns
[    0.000383] Console: colour dummy device 80x30
[    0.001051] printk: console [tty1] enabled
[    0.001128] Calibrating delay loop (skipped), value calculated using timer frequency.. 108.00 BogoMIPS (lpj=540000)
[    0.001180] pid_max: default: 32768 minimum: 301
[    0.001335] LSM: Security Framework initializing
[    0.001546] Mount-cache hash table entries: 2048 (order: 1, 8192 bytes, linear)
[    0.001594] Mountpoint-cache hash table entries: 2048 (order: 1, 8192 bytes, linear)
[    0.003137] cgroup: Disabling memory control group subsystem
[    0.003392] CPU: Testing write buffer coherency: ok
[    0.003462] CPU0: Spectre BHB: enabling loop workaround for all CPUs
[    0.003916] CPU0: thread -1, cpu 0, socket 0, mpidr 80000000
[    0.005426] Setting up static identity map for 0x200000 - 0x20003c
[    0.005641] rcu: Hierarchical SRCU implementation.
[    0.006654] smp: Bringing up secondary CPUs ...
[    0.007821] CPU1: thread -1, cpu 1, socket 0, mpidr 80000001
[    0.009127] CPU2: thread -1, cpu 2, socket 0, mpidr 80000002
[    0.010449] CPU3: thread -1, cpu 3, socket 0, mpidr 80000003
[    0.010610] smp: Brought up 1 node, 4 CPUs
[    0.010689] SMP: Total of 4 processors activated (432.00 BogoMIPS).
[    0.010721] CPU: All CPU(s) started in HYP mode.
[    0.010746] CPU: Virtualization extensions available.
[    0.011508] devtmpfs: initialized
[    0.026440] VFP support v0.3: implementor 41 architecture 3 part 40 variant 8 rev 0
[    0.026675] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 19112604462750000 ns
[    0.026730] futex hash table entries: 1024 (order: 4, 65536 bytes, linear)
[    0.036435] pinctrl core: initialized pinctrl subsystem
[    0.037686] NET: Registered PF_NETLINK/PF_ROUTE protocol family
[    0.042056] DMA: preallocated 1024 KiB pool for atomic coherent allocations
[    0.042887] audit: initializing netlink subsys (disabled)
[    0.043158] audit: type=2000 audit(0.040:1): state=initialized audit_enabled=0 res=1
[    0.043798] thermal_sys: Registered thermal governor 'step_wise'
[    0.044480] hw-breakpoint: found 5 (+1 reserved) breakpoint and 4 watchpoint registers.
[    0.044538] hw-breakpoint: maximum watchpoint size is 8 bytes.
[    0.044945] Serial: AMBA PL011 UART driver
[    0.058478] bcm2835-mbox fe00b880.mailbox: mailbox enabled
[    0.090045] raspberrypi-firmware soc:firmware: Attached to firmware from 2023-01-05T10:46:54, variant start
[    0.100061] raspberrypi-firmware soc:firmware: Firmware hash is 8ba17717fbcedd4c3b6d4bce7e50c7af4155cba9
[    0.159539] Kprobes globally optimized
[    0.165513] bcm2835-dma fe007000.dma: DMA legacy API manager, dmachans=0x1
[    0.170078] vgaarb: loaded
[    0.170636] SCSI subsystem initialized
[    0.170890] usbcore: registered new interface driver usbfs
[    0.170967] usbcore: registered new interface driver hub
[    0.171052] usbcore: registered new device driver usb
[    0.171458] usb_phy_generic phy: supply vcc not found, using dummy regulator
[    0.171670] usb_phy_generic phy: dummy supplies not allowed for exclusive requests
[    0.172015] pps_core: LinuxPPS API ver. 1 registered
[    0.172045] pps_core: Software ver. 5.3.6 - Copyright 2005-2007 Rodolfo Giometti <giometti@linux.it>
[    0.172094] PTP clock support registered
[    0.173696] clocksource: Switched to clocksource arch_sys_counter
[    0.254389] VFS: Disk quotas dquot_6.6.0
[    0.254519] VFS: Dquot-cache hash table entries: 1024 (order 0, 4096 bytes)
[    0.254720] FS-Cache: Loaded
[    0.254916] CacheFiles: Loaded
[    0.264012] NET: Registered PF_INET protocol family
[    0.264283] IP idents hash table entries: 16384 (order: 5, 131072 bytes, linear)
[    0.265887] tcp_listen_portaddr_hash hash table entries: 512 (order: 0, 6144 bytes, linear)
[    0.265943] Table-perturb hash table entries: 65536 (order: 6, 262144 bytes, linear)
[    0.265988] TCP established hash table entries: 8192 (order: 3, 32768 bytes, linear)
[    0.266071] TCP bind hash table entries: 8192 (order: 4, 65536 bytes, linear)
[    0.266159] TCP: Hash tables configured (established 8192 bind 8192)
[    0.266330] UDP hash table entries: 512 (order: 2, 16384 bytes, linear)
[    0.266386] UDP-Lite hash table entries: 512 (order: 2, 16384 bytes, linear)
[    0.266659] NET: Registered PF_UNIX/PF_LOCAL protocol family
[    0.267677] RPC: Registered named UNIX socket transport module.
[    0.267711] RPC: Registered udp transport module.
[    0.267738] RPC: Registered tcp transport module.
[    0.267764] RPC: Registered tcp NFSv4.1 backchannel transport module.
[    0.267800] PCI: CLS 0 bytes, default 64
[    1.327532] hw perfevents: enabled with armv7_cortex_a7 PMU driver, 7 counters available
[    1.330147] Initialise system trusted keyrings
[    1.330460] workingset: timestamp_bits=14 max_order=20 bucket_order=6
[    1.339571] zbud: loaded
[    1.341528] FS-Cache: Netfs 'nfs' registered for caching
[    1.342451] NFS: Registering the id_resolver key type
[    1.342508] Key type id_resolver registered
[    1.342536] Key type id_legacy registered
[    1.342682] nfs4filelayout_init: NFSv4 File Layout Driver Registering...
[    1.342715] nfs4flexfilelayout_init: NFSv4 Flexfile Layout Driver Registering...
[    1.343863] Key type asymmetric registered
[    1.343894] Asymmetric key parser 'x509' registered
[    1.344139] bounce: pool size: 64 pages
[    1.344215] Block layer SCSI generic (bsg) driver version 0.4 loaded (major 247)
[    1.344467] io scheduler mq-deadline registered
[    1.344499] io scheduler kyber registered
[    1.354053] brcm-pcie fd500000.pcie: host bridge /scb/pcie@7d500000 ranges:
[    1.354118] brcm-pcie fd500000.pcie:   No bus range found for /scb/pcie@7d500000, using [bus 00-ff]
[    1.354234] brcm-pcie fd500000.pcie:      MEM 0x0600000000..0x063fffffff -> 0x00c0000000
[    1.354355] brcm-pcie fd500000.pcie:   IB MEM 0x0000000000..0x00bfffffff -> 0x0400000000
[    1.415801] brcm-pcie fd500000.pcie: link up, 5.0 GT/s PCIe x1 (SSC)
[    1.416240] brcm-pcie fd500000.pcie: PCI host bridge to bus 0000:00
[    1.416277] pci_bus 0000:00: root bus resource [bus 00-ff]
[    1.416312] pci_bus 0000:00: root bus resource [mem 0x600000000-0x63fffffff] (bus address [0xc0000000-0xffffffff])
[    1.416425] pci 0000:00:00.0: [14e4:2711] type 01 class 0x060400
[    1.416694] pci 0000:00:00.0: PME# supported from D0 D3hot
[    1.420335] PCI: bus0: Fast back to back transfers disabled
[    1.420690] pci 0000:01:00.0: [1106:3483] type 00 class 0x0c0330
[    1.420835] pci 0000:01:00.0: reg 0x10: [mem 0x00000000-0x00000fff 64bit]
[    1.421313] pci 0000:01:00.0: PME# supported from D0 D3hot
[    1.424923] PCI: bus1: Fast back to back transfers disabled
[    1.425001] pci 0000:00:00.0: BAR 8: assigned [mem 0x600000000-0x6000fffff]
[    1.425044] pci 0000:01:00.0: BAR 0: assigned [mem 0x600000000-0x600000fff 64bit]
[    1.425149] pci 0000:00:00.0: PCI bridge to [bus 01]
[    1.425187] pci 0000:00:00.0:   bridge window [mem 0x600000000-0x6000fffff]
[    1.425626] pcieport 0000:00:00.0: enabling device (0140 -> 0142)
[    1.425875] pcieport 0000:00:00.0: PME: Signaling with IRQ 77
[    1.439226] iproc-rng200 fe104000.rng: hwrng registered
[    1.439623] vc-mem: phys_addr:0x00000000 mem_base=0x3ec00000 mem_size:0x40000000(1024 MiB)
[    1.441145] gpiomem-bcm2835 fe200000.gpiomem: Initialised: Registers at 0xfe200000
[    1.453816] brd: module loaded
[    1.464029] loop: module loaded
[    1.464770] Loading iSCSI transport class v2.0-870.
[    1.469955] bcmgenet fd580000.ethernet: GENET 5.0 EPHY: 0x0000
[    1.563859] unimac-mdio unimac-mdio.-19: Broadcom UniMAC MDIO bus
[    1.565063] usbcore: registered new interface driver r8152
[    1.565162] usbcore: registered new interface driver lan78xx
[    1.565239] usbcore: registered new interface driver smsc95xx
[    1.612990] xhci_hcd 0000:01:00.0: xHCI Host Controller
[    1.613044] xhci_hcd 0000:01:00.0: new USB bus registered, assigned bus number 1
[    1.618697] xhci_hcd 0000:01:00.0: hcc params 0x002841eb hci version 0x100 quirks 0x0001e40000000890
[    1.619795] xhci_hcd 0000:01:00.0: xHCI Host Controller
[    1.619838] xhci_hcd 0000:01:00.0: new USB bus registered, assigned bus number 2
[    1.619883] xhci_hcd 0000:01:00.0: Host supports USB 3.0 SuperSpeed
[    1.620287] usb usb1: New USB device found, idVendor=1d6b, idProduct=0002, bcdDevice= 5.15
[    1.620331] usb usb1: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[    1.620368] usb usb1: Product: xHCI Host Controller
[    1.620398] usb usb1: Manufacturer: Linux 5.15.84-v7l+ xhci-hcd
[    1.620428] usb usb1: SerialNumber: 0000:01:00.0
[    1.621149] hub 1-0:1.0: USB hub found
[    1.621235] hub 1-0:1.0: 1 port detected
[    1.622259] usb usb2: New USB device found, idVendor=1d6b, idProduct=0003, bcdDevice= 5.15
[    1.622304] usb usb2: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[    1.622342] usb usb2: Product: xHCI Host Controller
[    1.622372] usb usb2: Manufacturer: Linux 5.15.84-v7l+ xhci-hcd
[    1.622402] usb usb2: SerialNumber: 0000:01:00.0
[    1.623114] hub 2-0:1.0: USB hub found
[    1.623228] hub 2-0:1.0: 4 ports detected
[    1.625140] dwc_otg: version 3.00a 10-AUG-2012 (platform bus)
[    1.625505] dwc_otg: FIQ enabled
[    1.625519] dwc_otg: NAK holdoff enabled
[    1.625532] dwc_otg: FIQ split-transaction FSM enabled
[    1.625550] Module dwc_common_port init
[    1.625986] usbcore: registered new interface driver uas
[    1.626115] usbcore: registered new interface driver usb-storage
[    1.626341] mousedev: PS/2 mouse device common for all mice
[    1.632022] sdhci: Secure Digital Host Controller Interface driver
[    1.632058] sdhci: Copyright(c) Pierre Ossman
[    1.632774] sdhci-pltfm: SDHCI platform and OF driver helper
[    1.636585] ledtrig-cpu: registered to indicate activity on CPUs
[    1.636933] hid: raw HID events driver (C) Jiri Kosina
[    1.637148] usbcore: registered new interface driver usbhid
[    1.637179] usbhid: USB HID core driver
[    1.643335] Initializing XFRM netlink socket
[    1.643398] NET: Registered PF_PACKET protocol family
[    1.643524] Key type dns_resolver registered
[    1.644177] Registering SWP/SWPB emulation handler
[    1.644990] registered taskstats version 1
[    1.645048] Loading compiled-in X.509 certificates
[    1.645931] Key type .fscrypt registered
[    1.645961] Key type fscrypt-provisioning registered
[    1.658353] uart-pl011 fe201000.serial: there is not valid maps for state default
[    1.658711] uart-pl011 fe201000.serial: cts_event_workaround enabled
[    1.658876] fe201000.serial: ttyAMA0 at MMIO 0xfe201000 (irq = 34, base_baud = 0) is a PL011 rev2
[    1.668307] bcm2835-wdt bcm2835-wdt: Broadcom BCM2835 watchdog timer
[    1.668815] bcm2835-power bcm2835-power: Broadcom BCM2835 power domains driver
[    1.670132] mmc-bcm2835 fe300000.mmcnr: mmc_debug:0 mmc_debug2:0
[    1.670171] mmc-bcm2835 fe300000.mmcnr: DMA channel allocated
[    1.700594] of_cfs_init
[    1.700850] of_cfs_init: OK
[    1.736451] mmc0: SDHCI controller on fe340000.mmc [fe340000.mmc] using ADMA
[    1.736795] Waiting for root device PARTUUID=b0ef97d1-02...
[    1.835461] mmc0: new ultra high speed DDR50 SDHC card at address 59b4
[    1.836483] mmcblk0: mmc0:59b4 SDU1  29.1 GiB 
[    1.843430]  mmcblk0: p1 p2
[    1.844126] mmcblk0: mmc0:59b4 SDU1  29.1 GiB
[    1.845339] mmc1: new high speed SDIO card at address 0001
[    1.867611] EXT4-fs (mmcblk0p2): mounted filesystem with ordered data mode. Opts: (null). Quota mode: none.
[    1.867729] VFS: Mounted root (ext4 filesystem) readonly on device 179:2.
[    1.868429] devtmpfs: mounted
[    1.879452] Freeing unused kernel image (initmem) memory: 2048K
[    1.894016] Run /sbin/init as init process
[    1.894047]   with arguments:
[    1.894060]     /sbin/init
[    1.894073]   with environment:
[    1.894085]     HOME=/
[    1.894098]     TERM=linux
[    1.903742] usb 1-1: new high-speed USB device number 2 using xhci_hcd
[    2.086426] usb 1-1: New USB device found, idVendor=2109, idProduct=3431, bcdDevice= 4.21
[    2.086487] usb 1-1: New USB device strings: Mfr=0, Product=1, SerialNumber=0
[    2.086522] usb 1-1: Product: USB2.0 Hub
[    2.097796] hub 1-1:1.0: USB hub found
[    2.098103] hub 1-1:1.0: 4 ports detected
[    2.214399] systemd[1]: System time before build time, advancing clock.
[    2.416577] NET: Registered PF_INET6 protocol family
[    2.418347] Segment Routing with IPv6
[    2.418408] In-situ OAM (IOAM) with IPv6
[    2.496198] systemd[1]: systemd 247.3-7+rpi1+deb11u1 running in system mode. (+PAM +AUDIT +SELINUX +IMA +APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +ZSTD +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=unified)
[    2.497140] systemd[1]: Detected architecture arm.
[    2.509285] systemd[1]: Set hostname to <gponcekpi>.
[    3.198567] systemd[1]: /lib/systemd/system/plymouth-start.service:16: Unit configured to use KillMode=none. This is unsafe, as it disables systemd's process lifecycle management for the service. Please update your service to use a safer KillMode=, such as 'mixed' or 'control-group'. Support for KillMode=none is deprecated and will eventually be removed.
[    3.381312] systemd[1]: Queued start job for default target Graphical Interface.
[    3.386765] systemd[1]: Created slice system-getty.slice.
[    3.388495] systemd[1]: Created slice system-modprobe.slice.
[    3.389884] systemd[1]: Created slice system-systemd\x2dfsck.slice.
[    3.391069] systemd[1]: Created slice User and Session Slice.
[    3.391915] systemd[1]: Started Forward Password Requests to Wall Directory Watch.
[    3.393451] systemd[1]: Set up automount Arbitrary Executable File Formats File System Automount Point.
[    3.394565] systemd[1]: Reached target Slices.
[    3.395071] systemd[1]: Reached target Swap.
[    3.398999] systemd[1]: Listening on Syslog Socket.
[    3.400146] systemd[1]: Listening on fsck to fsckd communication Socket.
[    3.400957] systemd[1]: Listening on initctl Compatibility Named Pipe.
[    3.402478] systemd[1]: Listening on Journal Audit Socket.
[    3.403563] systemd[1]: Listening on Journal Socket (/dev/log).
[    3.405262] systemd[1]: Listening on Journal Socket.
[    3.410519] systemd[1]: Listening on udev Control Socket.
[    3.411768] systemd[1]: Listening on udev Kernel Socket.
[    3.413002] systemd[1]: Condition check resulted in Huge Pages File System being skipped.
[    3.418608] systemd[1]: Mounting POSIX Message Queue File System...
[    3.425369] systemd[1]: Mounting RPC Pipe File System...
[    3.432608] systemd[1]: Mounting Kernel Debug File System...
[    3.440522] systemd[1]: Mounting Kernel Trace File System...
[    3.441898] systemd[1]: Condition check resulted in Kernel Module supporting RPCSEC_GSS being skipped.
[    3.450931] systemd[1]: Starting Restore / save the current clock...
[    3.459430] systemd[1]: Starting Set the console keyboard layout...
[    3.467796] systemd[1]: Starting Create list of static device nodes for the current kernel...
[    3.475827] systemd[1]: Starting Load Kernel Module configfs...
[    3.484456] systemd[1]: Starting Load Kernel Module drm...
[    3.493030] systemd[1]: Starting Load Kernel Module fuse...
[    3.497717] systemd[1]: Condition check resulted in Set Up Additional Binary Formats being skipped.
[    3.504402] systemd[1]: Starting File System Check on Root Device...
[    3.516906] systemd[1]: Starting Journal Service...
[    3.532153] systemd[1]: Starting Load Kernel Modules...
[    3.554805] systemd[1]: Starting Coldplug All udev Devices...
[    3.588296] systemd[1]: Mounted POSIX Message Queue File System.
[    3.590288] systemd[1]: Mounted RPC Pipe File System.
[    3.591361] systemd[1]: Mounted Kernel Debug File System.
[    3.592398] systemd[1]: Mounted Kernel Trace File System.
[    3.607114] systemd[1]: Finished Restore / save the current clock.
[    3.610607] systemd[1]: Finished Create list of static device nodes for the current kernel.
[    3.612790] fuse: init (API version 7.34)
[    3.613898] systemd[1]: modprobe@configfs.service: Succeeded.
[    3.617231] systemd[1]: Finished Load Kernel Module configfs.
[    3.631795] systemd[1]: Mounting Kernel Configuration File System...
[    3.641129] i2c_dev: i2c /dev entries driver
[    3.649591] systemd[1]: Started File System Check Daemon to report status.
[    3.654355] systemd[1]: modprobe@fuse.service: Succeeded.
[    3.656241] systemd[1]: Finished Load Kernel Module fuse.
[    3.671196] systemd[1]: Finished Load Kernel Modules.
[    3.673522] systemd[1]: Mounted Kernel Configuration File System.
[    3.681690] systemd[1]: Mounting FUSE Control File System...
[    3.699139] systemd[1]: Starting Apply Kernel Variables...
[    3.728827] systemd[1]: Mounted FUSE Control File System.
[    3.763840] systemd[1]: Finished Apply Kernel Variables.
[    3.791715] systemd[1]: modprobe@drm.service: Succeeded.
[    3.793236] systemd[1]: Finished Load Kernel Module drm.
[    3.820145] systemd[1]: Finished File System Check on Root Device.
[    3.826140] systemd[1]: Starting Remount Root and Kernel File Systems...
[    3.950209] systemd[1]: Started Journal Service.
[    3.998433] EXT4-fs (mmcblk0p2): re-mounted. Opts: (null). Quota mode: none.
[    4.066425] systemd-journald[138]: Received client request to flush runtime journal.
[    4.075463] systemd-journald[138]: File /var/log/journal/fde2a7bc981a491bbb429a184e56f65d/system.journal corrupted or uncleanly shut down, renaming and replacing.
[    5.552318] mc: Linux media interface: v0.10
[    5.628653] vc_sm_cma: module is from the staging directory, the quality is unknown, you have been warned.
[    5.678831] videodev: Linux video capture interface: v2.00
[    5.683146] bcm2835_vc_sm_cma_probe: Videocore shared memory driver
[    5.683181] [vc_sm_connected_init]: start
[    5.692388] [vc_sm_connected_init]: installed successfully
[    5.874373] brcmstb-i2c fef04500.i2c:  @97500hz registered in polling mode
[    5.903518] snd_bcm2835: module is from the staging directory, the quality is unknown, you have been warned.
[    5.940676] bcm2835_audio bcm2835_audio: card created with 8 channels
[    5.950578] brcmstb-i2c fef09500.i2c:  @97500hz registered in polling mode
[    6.087949] bcm2835_mmal_vchiq: module is from the staging directory, the quality is unknown, you have been warned.
[    6.140322] bcm2835_isp: module is from the staging directory, the quality is unknown, you have been warned.
[    6.174861] bcm2835_codec: module is from the staging directory, the quality is unknown, you have been warned.
[    6.190143] bcm2835_v4l2: module is from the staging directory, the quality is unknown, you have been warned.
[    6.200982] rpivid_hevc: module is from the staging directory, the quality is unknown, you have been warned.
[    6.219597] bcm2835-isp bcm2835-isp: Device node output[0] registered as /dev/video13
[    6.221225] bcm2835-isp bcm2835-isp: Device node capture[0] registered as /dev/video14
[    6.221896] bcm2835-isp bcm2835-isp: Device node capture[1] registered as /dev/video15
[    6.226120] rpivid feb10000.codec: Device registered as /dev/video19
[    6.226127] bcm2835-isp bcm2835-isp: Device node stats[2] registered as /dev/video16
[    6.226158] bcm2835-isp bcm2835-isp: Register output node 0 with media controller
[    6.226184] bcm2835-isp bcm2835-isp: Register capture node 1 with media controller
[    6.226207] bcm2835-isp bcm2835-isp: Register capture node 2 with media controller
[    6.226230] bcm2835-isp bcm2835-isp: Register capture node 3 with media controller
[    6.228332] bcm2835-codec bcm2835-codec: Device registered as /dev/video10
[    6.228404] bcm2835-codec bcm2835-codec: Loaded V4L2 decode
[    6.234165] bcm2835-codec bcm2835-codec: Device registered as /dev/video11
[    6.234217] bcm2835-codec bcm2835-codec: Loaded V4L2 encode
[    6.249780] bcm2835-codec bcm2835-codec: Device registered as /dev/video12
[    6.249850] bcm2835-codec bcm2835-codec: Loaded V4L2 isp
[    6.258595] bcm2835-codec bcm2835-codec: Device registered as /dev/video18
[    6.258647] bcm2835-codec bcm2835-codec: Loaded V4L2 image_fx
[    6.266479] bcm2835-isp bcm2835-isp: Device node output[0] registered as /dev/video20
[    6.267983] [drm] Initialized v3d 1.0.0 20180419 for fec00000.v3d on minor 0
[    6.275491] bcm2835-codec bcm2835-codec: Device registered as /dev/video31
[    6.275568] bcm2835-codec bcm2835-codec: Loaded V4L2 encode_image
[    6.279200] bcm2835-isp bcm2835-isp: Device node capture[0] registered as /dev/video21
[    6.314878] bcm2835-isp bcm2835-isp: Device node capture[1] registered as /dev/video22
[    6.317851] bcm2835-isp bcm2835-isp: Device node stats[2] registered as /dev/video23
[    6.317902] bcm2835-isp bcm2835-isp: Register output node 0 with media controller
[    6.317928] bcm2835-isp bcm2835-isp: Register capture node 1 with media controller
[    6.317950] bcm2835-isp bcm2835-isp: Register capture node 2 with media controller
[    6.317972] bcm2835-isp bcm2835-isp: Register capture node 3 with media controller
[    6.323626] bcm2835-isp bcm2835-isp: Loaded V4L2 bcm2835-isp
[    6.361714] cfg80211: Loading compiled-in X.509 certificates for regulatory database
[    6.405864] cfg80211: Loaded X.509 cert 'sforshee: 00b28ddf47aef9cea7'
[    6.426397] cfg80211: loaded regulatory.db is malformed or signature is missing/invalid
[    6.545967] brcmfmac: F1 signature read @0x18000000=0x15264345
[    6.555004] brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac43455-sdio for chip BCM4345/6
[    6.604076] usbcore: registered new interface driver brcmfmac
[    6.840339] vc4-drm gpu: bound fe400000.hvs (ops vc4_hvs_ops [vc4])
[    6.846489] Registered IR keymap rc-cec
[    6.846722] rc rc0: vc4 as /devices/platform/soc/fef00700.hdmi/rc/rc0
[    6.846947] input: vc4 as /devices/platform/soc/fef00700.hdmi/rc/rc0/input0
[    6.859800] vc4-drm gpu: bound fef00700.hdmi (ops vc4_hdmi_ops [vc4])
[    6.862883] brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac43455-sdio for chip BCM4345/6
[    6.866496] Registered IR keymap rc-cec
[    6.866691] rc rc1: vc4 as /devices/platform/soc/fef05700.hdmi/rc/rc1
[    6.866932] input: vc4 as /devices/platform/soc/fef05700.hdmi/rc/rc1/input1
[    6.868732] brcmfmac: brcmf_c_preinit_dcmds: Firmware: BCM4345/6 wl0: Nov  1 2021 00:37:25 version 7.45.241 (1a2f2fa CY) FWID 01-703fd60
[    6.890255] vc4-drm gpu: bound fef05700.hdmi (ops vc4_hdmi_ops [vc4])
[    6.890862] vc4-drm gpu: bound fe004000.txp (ops vc4_txp_ops [vc4])
[    6.891605] vc4-drm gpu: bound fe206000.pixelvalve (ops vc4_crtc_ops [vc4])
[    6.892330] vc4-drm gpu: bound fe207000.pixelvalve (ops vc4_crtc_ops [vc4])
[    6.893112] vc4-drm gpu: bound fe20a000.pixelvalve (ops vc4_crtc_ops [vc4])
[    6.894237] vc4-drm gpu: bound fe216000.pixelvalve (ops vc4_crtc_ops [vc4])
[    6.894963] vc4-drm gpu: bound fec12000.pixelvalve (ops vc4_crtc_ops [vc4])
[    6.900630] [drm] Initialized vc4 0.0.0 20140616 for gpu on minor 1
[    6.901058] vc4-drm gpu: [drm] Cannot find any crtc or sizes
[    8.189315] 8021q: 802.1Q VLAN Support v1.8
[    8.216835] uart-pl011 fe201000.serial: no DMA platform data
[    8.470995] Adding 102396k swap on /var/swap.  Priority:-2 extents:1 across:102396k SSFS
[    8.919107] brcmfmac: brcmf_cfg80211_set_power_mgmt: power save enabled
[    9.314457] bcmgenet fd580000.ethernet: configuring instance for external RGMII (RX delay)
[    9.316639] bcmgenet fd580000.ethernet eth0: Link is Down
[   13.514032] bcmgenet fd580000.ethernet eth0: Link is Up - 1Gbps/Full - flow control off
[   13.514100] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
[   15.929423] Bluetooth: Core ver 2.22
[   15.929519] NET: Registered PF_BLUETOOTH protocol family
[   15.929531] Bluetooth: HCI device and connection manager initialized
[   15.929552] Bluetooth: HCI socket layer initialized
[   15.929567] Bluetooth: L2CAP socket layer initialized
[   15.929590] Bluetooth: SCO socket layer initialized
[   15.942572] Bluetooth: HCI UART driver ver 2.3
[   15.942594] Bluetooth: HCI UART protocol H4 registered
[   15.942675] Bluetooth: HCI UART protocol Three-wire (H5) registered
[   15.942928] Bluetooth: HCI UART protocol Broadcom registered
[   16.136059] Bluetooth: BNEP (Ethernet Emulation) ver 1.3
[   16.136071] Bluetooth: BNEP filters: protocol multicast
[   16.136084] Bluetooth: BNEP socket layer initialized
[   16.148139] NET: Registered PF_ALG protocol family
[   16.165099] cryptd: max_cpu_qlen set to 1000
[   16.598032] ICMPv6: process `dhcpcd' is using deprecated sysctl (syscall) net.ipv6.neigh.eth0.retrans_time - use net.ipv6.neigh.eth0.retrans_time_ms instead
[   17.114003] vc4-drm gpu: [drm] Cannot find any crtc or sizes
[   31.833764] cam-dummy-reg: disabling
pi@gponcekpi:~ $ 

### Additional context

The Wireshark works fine outside of raspberry Pi 4

**Comment by pelwell** [comment]
Not a kernel issue.

[Wireshark is a GUI app and needs to know which X display to use. Try "DISPLAY=:0.0 wireshark"](https://www.wireshark.org/lists/wireshark-users/200702/msg00152.html)

Or use tshark (the command-line version) instead.
