### ISSUE TITLE
3.13.3/3.13.5 WLAN deauthentication

### ISSUE THREAD

**Issue by ha5di** [raspberrypi/linux#542]
My TP-LINK USB WLAN stick (TL-WN721N) with Atheros AR9271 (is getting deauthenticated with reason code1 few seconds after it is authenticated using 3.13.3/3.13.5 It works perfectly with 3.12.y

**Comment by popcornmix** [comment]
Nothing has changed in the Pi patches, so it's probably an upstream regression.
Best to search for any bug reports and/or fixes in upstream kernel.

**Comment by ha5di** [comment]
You are right, it is not related to RPi but changes in crypto module dependencies using SHA encryption. I got it working fine. Ticket can be closed.

**Comment by popcornmix** [comment]
Do any options need adding to bcmrpi_defconfig to make this work, or were you using your own config?

**Comment by ha5di** [comment]
OS is piCore-5.2 the Raspberry Pi port of Tiny Core Linux. Base system comes with minimal set of kernel modules. Moving to 3.13.y from 3.12.y I had to add two kernel crypto modules, ccm.ko and ctr.ko to the base while using WPA with SHA encryption. Interesting, 3.12.y works without them. Anyhow, it affects only our distro side, nothing at kernel.

**Comment by popcornmix** [comment]
Okay, good to understand.
