### ISSUE TITLE
One wire and I2C do not play well together.

### ISSUE THREAD

**Issue by richard-tx** [raspberrypi/linux#545]
Version 12-20-2013

Enabling the one wire bus causes i2cdetect to show all available I2C addresses as occupied.

root@alphapi:~# i2cdetect -y 0
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- --
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
50: 50 -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
60: -- -- -- -- -- -- -- -- 68 -- -- -- -- -- -- --
70: -- -- -- -- -- -- -- --
root@alphapi:~# modprobe w1-gpio
root@alphapi:~# i2cdetect -y 0
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          03 04 05 06 07 08 09 0a 0b 0c 0d 0e 0f
10: 10 11 12 13 14 15 16 17 18 19 1a 1b 1c 1d 1e 1f
20: 20 21 22 23 24 25 26 27 28 29 2a 2b 2c 2d 2e 2f
30: 30 31 32 33 34 35 36 37 38 39 3a 3b 3c 3d 3e 3f
40: 40 41 42 43 44 45 46 47 48 49 4a 4b 4c 4d 4e 4f
50: 50 51 52 53 54 55 56 57 58 59 5a 5b 5c 5d 5e 5f
60: 60 61 62 63 64 65 66 67 UU 69 6a 6b 6c 6d 6e 6f
70: 70 71 72 73 74 75 76 77
root@alphapi:~#

**Comment by richard-tx** [comment]
I missed the version of wheeZy.

root@alphapi:~# uname -a
Linux alphapi 3.10.33+ #654 PREEMPT Fri Mar 7 16:32:08 GMT 2014 armv6l GNU/Linux

**Comment by popcornmix** [comment]
Duplicate of https://github.com/raspberrypi/linux/issues/435
