### ISSUE TITLE
lirc_rpi doesn't work with GPIO28 to GPIO31 in rev2 board

### ISSUE THREAD

**Issue by geniejhang** [raspberrypi/linux#546]
I recently found out that lirc_rpi doesn't work with through GPIO28 to GPIO31,
saying that invalid GPIO pin is provided.

I'm using 3.10.33+

Thank you.

**Comment by geniejhang** [comment]
I tried to compile the kernel with modified lirc_rpi.c file.
I added 28 through 31 in valid_gpio_pin array inside lirc_rpi.c.
It looked like okay but the pins are not working.
It keeps pulled up state.

Any idea?

**Comment by eduvik** [comment]
I've just discovered the same thing - I modified the binary of the driver module (changing 25 to 28) and it works successfully. 

But it would be good to have the driver updated to support rev2 boards (which also support GPIO pins 2, 3 and 27 in addition to 28-31)

I'm using 3.10.25+

**Comment by geniejhang** [comment]
Would you tell me how you did it？

**Comment by eduvik** [comment]
I used hexedit to find the series of bytes that represent the array. Then I changed the 25 into 28 (in hex, 19 -> 1c). Each int is 32 bits, so look for 0000000100000002, etc.

**Comment by eduvik** [comment]
I've submitted a pull request https://github.com/raspberrypi/linux/pull/547

**Comment by geniejhang** [comment]
Thank you, eduvik.

I've just changed the binary file.
I'll test it when I get home.

**Comment by lurch** [comment]
@geniejhang perhaps the "It looked like okay but the pins are not working. It keeps pulled up state." has been fixed by https://github.com/raspberrypi/linux/commit/c7de2839922e1948259c2c2a2beb58ad795a51ba ? Could you re-test with the latest kernel?

**Comment by geniejhang** [comment]
I just updated the kernel using rpi-update and it is now 3.12.21+.
With that, the pins worked fine!
Thank you!

**Comment by lurch** [comment]
In that case, can you please close this issue :)

**Comment by geniejhang** [comment]
Many thanks!
