### ISSUE TITLE
Crun permission denied in podman since kernel 6.1.28

### ISSUE THREAD

**Issue by Elrondo46** [raspberrypi/linux#5483]
### Describe the bug

Use rlimit in podman engine at rootless results as permission denied. Tested in two rpi4 in Arch Arm

### Steps to reproduce the behaviour

Upgrade to last kernels and you can't start any pods

### Device (s)

Raspberry Pi 4 Mod. B

### System

Kernel 6.1.27 or 6.1.28 all subversions in Arch ARM

**Comment by Elrondo46** [comment]
sorry for bad kernel number in title

**Comment by pelwell** [comment]
Is it a 32-bit or 64-bit Arch? If 32-bit, does adding `arm_64bit=0` to config.txt make a difference?

**Comment by Elrondo46** [comment]
It's 64bit arch

26 mai 2023 10:39:28 Phil Elwell ***@***.***>:

**Comment by pelwell** [comment]
In that case I don't think you'll get much help here, unless you can identify what is causing the problem. You might have more luck asking the Podman devs.

**Comment by Elrondo46** [comment]
Hi,

But this is after the kernel 6.1.27, there is a problem. Not before it…



De : Phil ***@***.***>
Envoyé le :vendredi 26 mai 2023 11:13
À : ***@***.***>
Cc : ***@***.***>; ***@***.***>
Objet :Re: [raspberrypi/linux] Crun permission denied in podman since kernel 6.1.28 (Issue #5483)


In that case I don't think you'll get much help here, unless you can identify what is causing the problem. You might have more luck asking the Podman devs.

**Comment by pelwell** [comment]
What was the last working version? You don't make it clear whether 6.1.27 works or doesn't.

**Comment by Elrondo46** [comment]
In 6.1.27, podman in rootless working without problems. Downgrading successfully. It's since 6.1.28 the problem appears.

**Comment by pelwell** [comment]
The podman devs are still much more likely to know what is going wrong (especially when you've provided so little information): https://github.com/containers/podman/issues

**Comment by Elrondo46** [comment]
Submitted, I post if I have a solution from them of if they redirect to you

https://github.com/containers/podman/issues/18696

**Comment by pelwell** [comment]
Thanks - I hope that have some suggestions.

**Comment by Elrondo46** [comment]
They redirect the bug solving to a kernel cause

https://github.com/containers/podman/issues/18696#issuecomment-1564234363

**Comment by Elrondo46** [comment]
Please note, users have to recreate pods to be compatible with the last kernel 6.1.28 or 6.1.29. Thats the first time I had this problem...

**Comment by pelwell** [comment]
So some upstream kernel change (not one of ours) has caused a parameter saved at "pod" creation to no longer be valid. The Podman team may find a way to handle that more gracefully, but for now you have a workaround.
