### ISSUE TITLE
EMC2305 not starting fan

### ISSUE THREAD

**Issue by JN19aban** [raspberrypi/linux#5490]
### Describe the bug

After adding the following overlay the EMC2301 is not recognized anymore as cooling_device:

`dtoverlay=i2c-fan,emc2301,i2c_csi_dsi,minpwm=0,maxpwm=255,midtemp=40000,maxtemp=75000`

It is only working with this overlay,

`dtoverlay=i2c-fan,emc2301,i2c_csi_dsi`

 but the fan not spinning at all and cannot set custom fan speed. The minpwm and maxpwm parameters not working and the cooling_device disappears from `/sys/class/thermal/`.

### Steps to reproduce the behaviour

Add the overlays on /boot/config.txt

### Device (s)

Raspberry Pi CM4

### System

Raspberry Pi reference 2023-02-21

version 82f3750a65fadae9a38077e3c2e217ad158c8d54 

Kernel 6.1.21-v8+

### Logs

$ watch -n 1 "grep -s . /sys/class/thermal/thermal_zone*/* /sys/class/thermal/cooling_device*/*"

/sys/class/thermal/thermal_zone0/available_policies:step_wise
/sys/class/thermal/thermal_zone0/integral_cutoff:0
/sys/class/thermal/thermal_zone0/k_d:0
/sys/class/thermal/thermal_zone0/k_i:0
/sys/class/thermal/thermal_zone0/k_po:0
/sys/class/thermal/thermal_zone0/k_pu:0
/sys/class/thermal/thermal_zone0/mode:enabled
/sys/class/thermal/thermal_zone0/offset:410040
/sys/class/thermal/thermal_zone0/policy:step_wise
/sys/class/thermal/thermal_zone0/slope:-487
/sys/class/thermal/thermal_zone0/sustainable_power:0
/sys/class/thermal/thermal_zone0/temp:49173
/sys/class/thermal/thermal_zone0/trip_point_0_hyst:2000
/sys/class/thermal/thermal_zone0/trip_point_0_temp:75000
/sys/class/thermal/thermal_zone0/trip_point_0_type:active
/sys/class/thermal/thermal_zone0/trip_point_1_hyst:2000
/sys/class/thermal/thermal_zone0/trip_point_1_temp:40000
/sys/class/thermal/thermal_zone0/trip_point_1_type:active
/sys/class/thermal/thermal_zone0/trip_point_2_hyst:0
/sys/class/thermal/thermal_zone0/trip_point_2_temp:110000
/sys/class/thermal/thermal_zone0/trip_point_2_type:critical
/sys/class/thermal/thermal_zone0/type:cpu-thermal

**Comment by 6by9** [comment]
Why spam issues #5202  and #4632 if you're going to open a new one? Please don't.

The EMC2305 driver on the 6.1 kernel was sorted with #5440 and #5441. Those were merged at the end of April, which roughly coincides with 6.1.24, but have not hit apt yet.

**Comment by JN19aban** [comment]
Sorry for the spam, Fixed with 6.1.31.
