### ISSUE TITLE
Missing /boot/config-[kernel_version], prevents initramfs generation 

### ISSUE THREAD

**Issue by SylvainGarrigues** [raspberrypi/linux#5496]
### Describe the bug

The initramfs-tools package in Debian bookworm includes the mkinitramfs script which checks if the kernel supports the compression method used to compress the initramfs, by `grep`ping the `/boot/config-[new_kernel_version]` file which the `raspberrypi-kernel` package does not install.

Can the package install the configs for the provided kernel* in /boot?

### Steps to reproduce the behaviour

```
update-initramfs -c -v -k 6.1.21-v8+
```

### Device (s)

Raspberry Pi 3 Mod. B

### System

Debian Bookworm

### Logs

/usr/sbin/mkinitramfs includes a line like `grep /boot/config-VERSION` and this file don't exist.

**Comment by alsldlflglhljlk** [comment]
You can download the config file from here: [https://pastebin.com/raw/AVmn0AgF](https://pastebin.com/raw/AVmn0AgF)

But running `sudo touch /boot/config-6.1.21-v8+` should work as well.

**Comment by SylvainGarrigues** [comment]
My workaround is actually:
```
modprobe configs && zcat /proc/config.gz > /boot/config-6.1.21-v8+
```

But this doesn't solve the problem that when the Raspberry Pi foundation kernel package will be upgraded, the `/boot/config-[kernel_version]` file won't be found, and the `update-initramfs` script will fail, since the `initramfs-tools` package in Debian bookworm script expects it (I guess kernel packages provided by Debian all provide the config file in the `boot` partition). 

So I guess either the Raspberry Pi repository needs to provided a patched `initramfs-tools` package, or the kernel image package needs to install the kernel config.

**Comment by alsldlflglhljlk** [comment]
I haven't seen this error in a while, so can you post the exact error message you get?

**Comment by SylvainGarrigues** [comment]
There was no much log except what I already mentioned in the initial report: the post install script of the kernel package fails, I ran `update-initramfs` like the script does, it also failed with a generic error, so I added `set -e -x`
to `/usr/sbin/mkinitramfs` to discover the culprit, which was like: `grep: /boot/config-version: file not found` due to a failing `grep` line in that script (because of the missing file): it does need the config file to know what kind of initrd compression is supported by the kernel, so as to include the relevant modules in the ramfs. 

I guess this only happens if you have configured a ramfs image generation.

**Comment by alsldlflglhljlk** [comment]
Run `sudo nano /usr/sbin/mkinitramfs`, and add `sudo modprobe configs && zcat /proc/config.gz > /boot/config-$(uname -r)` to the second line. That should do the trick.

**Comment by SylvainGarrigues** [comment]
Sure, but this is a trick / hack just for my machine. I am not looking for help (I fixed this problem weeks ago), I just want to report the issue: anyone who needs an initramfs in bookworm will have this issue, so either the kernel package needs to include the config file, or the initramfs-tools package needs to be specific to raspberry pi OS and patched with what you mentioned. 

Is this the right place to report this issue?

**Comment by alsldlflglhljlk** [comment]
[https://github.com/RPi-Distro/repo](https://github.com/RPi-Distro/repo) is probably the right place to report this. Please close this issue.

**Comment by poizan42** [comment]
FWIW here are the commands I used to extract the configs for all installed kernel versions:
```shell
wget https://raw.githubusercontent.com/torvalds/linux/master/scripts/extract-ikconfig
for f in /usr/lib/modules/*; do
    v=${f#/usr/lib/modules/}
    sh ./extract-ikconfig "/usr/lib/modules/$v/kernel/kernel/configs.ko.xz" | sudo tee /boot/config-$v > /dev/null
done
```

**Comment by popcornmix** [comment]
I'll close this as it's not a kernel issue (there is nothing we can commit in this repo that will solve the issue).
@alsldlflglhljlk gave a better location.

My understanding is that bookworm improves how the kernel is packaged which results in initramfs and dkms working more straightforwardly (but I don't know the details).
