### ISSUE TITLE
config: CONFIG_VETH for virtual ethernet devices

### ISSUE THREAD

**Issue by darkbuck** [raspberrypi/linux#550]
'veth' is widely used with network namespaces to create a container. I added 'CONFIG_VETH=m' to compile 'veth' as a module and loaded on demand. I tested with 3.10.24+, 3.10.25+, and linux-3.10.34+.

**Comment by popcornmix** [comment]
Okay, will add.

**Comment by popcornmix** [comment]
This is added in latest rpi-update firmware.

**Comment by Ruffio** [comment]
@darkbuck have your issue been resolved? Please close this issue if this is the case, thanks.

**Comment by popcornmix** [comment]
It is in:

```
pi@domnfs:~ $ sudo modprobe configs
pi@domnfs:~ $ zcat /proc/config.gz |grep VETH
CONFIG_VETH=m
```
