### ISSUE TITLE
lirc_rpi module problems when only one direction specified

### ISSUE THREAD

**Issue by eduvik** [raspberrypi/linux#551]
in linux/drivers/staging/media/lirc/lirc_rpi.c I've found that _occasionally_ when trying to load the module with only gpio_out_pin defined (i.e. gpio_in_pin is not specified), the module fails to load with and invalid argument. Strangely, it seems to work OK on some pin definitions, but not others. In my case, gpio_out_pin=18 did not work, but others I tried (1,4,25,26) did. The loop checking for a valid gpio pin assumes both will be specified, but does not appear to validate if both have been defined?

**Comment by eduvik** [comment]
Just discovered the default values for these; it seems I was setting gpio_out_pin to the default value of gpio_in_pin (18), which can't really work. 

Are default values here sensible? 

Should there be the possibility of only defining one direction?

**Comment by Ruffio** [comment]
@eduvik has this issue been resolved? If yes, then please close this issue.

**Comment by Ruffio** [comment]
This issue should be closed due to inactivity. Last activity was on 26 Mar 2014, and I have pinged on 10 Aug 2016 without any response...
