### ISSUE TITLE
kern.log and syslog fill up disk space with rc rc0: IR event FIFO is full!

### ISSUE THREAD

**Issue by haiph-dev** [raspberrypi/linux#5512]
### Describe the bug

I have issues that /var/log/kern.log and syslog files filled up with "rc rc0: IR event FIFO is full!". Both files start filled up at the same time and until disk space consumed. This Pi just run python code to check sensor input and trigger relay output.
OS: 5.10.103-v7l+ #1529 SMP Tue Mar 8 12:24:00 GMT 2022 armv7l GNU/Linux

Sample logs:
Jun 20 07:24:38 Pi-Monitor kernel: [82292.526731] rc rc0: IR event FIFO is full!
Jun 20 07:24:38 Pi-Monitor kernel: [82292.526754] rc rc0: IR event FIFO is full!
Jun 20 07:24:38 Pi-Monitor kernel: [82292.526781] rc rc0: IR event FIFO is full!
...

Please help to advise,

### Steps to reproduce the behaviour

My python code main function read sensor input and trigger relay output. At the moment kern.log start to fill, there was paper covering sensor so below function will trigger relay output.
---------------------python code----------------------
#Function for controlling LED
def LEDcontrol():
    global result
    while True:
        if checksensor(s2pin):
            if checksensor(s1pin):
                print 'Sensor %s up' %s1pin
                GPIO.output(led1,True)
                GPIO.output(led2,False)
                GPIO.output(led3,False)
            elif checksensor(s3pin):
                print 'Sensor %s up' %s3pin
                GPIO.output(led1,False)
                GPIO.output(led2,False)
                GPIO.output(led3,True)
            else:
                print 'Sensor %s up' %s2pin
                GPIO.output(led1,False)
                GPIO.output(led2,True)
                GPIO.output(led3,False)
        else:
            GPIO.output(led1,False)
            GPIO.output(led2,False)
            GPIO.output(led3,False)
        time.sleep(0.5)

### Device (s)

Raspberry Pi 4 Mod. B

### System

pi@Pi-Monitor:~ $ cat /etc/rpi-issue
Raspberry Pi reference 2020-05-27
Generated using pi-gen, https://github.com/RPi-Distro/pi-gen, 825107f04027269db77426046f5085475b1ea22f, stage4
pi@Pi-Monitor:~ $ vcgencmd version
Dec  1 2021 15:01:54 
Copyright (c) 2012 Broadcom
version 71bd3109023a0c8575585ba87cbb374d2eeb038f (clean) (release) (start)
pi@Pi-Monitor:~ $ uname -a
Linux Pi-Monitor 5.10.103-v7l+ #1529 SMP Tue Mar 8 12:24:00 GMT 2022 armv7l GNU/Linux

### Logs

when issue happened, our team restart few times so there was no dmesg avaiable

**Comment by pelwell** [comment]
That kernel error message is indicative of a real problem - something is storing IR events faster than they are being consumed. There is a standard kernel mechanism to rate-limit error messages like that, and the fact that rate-limiting isn't being used tells us this isn't a common problem.

It sounds like this was one-off for you. You've tried turning it off and on again, and the problem has gone away. I'm going to close the issue until such time as the problem recurs. In the meantime, try not to sit on the remote.  ;-)
