### ISSUE TITLE
CONFIG_TASK_DELAY_ACCT missing in 6.1.21, `iotop` not working

### ISSUE THREAD

**Issue by twelho** [raspberrypi/linux#5529]
### Describe the bug

Similar to https://github.com/raspberrypi/linux/issues/90, `iotop` complains about CONFIG_TASK_DELAY_ACCT missing, and will not show I/O percentages. This is with a clean, up to date installation of Raspberry Pi OS Lite (64-bit) on a Raspberry Pi 3B.

### Steps to reproduce the behaviour

1. Install https://downloads.raspberrypi.org/raspios_lite_arm64/images/raspios_lite_arm64-2023-05-03/2023-05-03-raspios-bullseye-arm64-lite.img.xz
2. `sudo apt update && sudo apt -y full-upgrade`
3. `sudo apt -y install iotop`
4. `sudo iotop`
5. Observe complaint about CONFIG_TASK_DELAY_ACCT missing and a lot of `?unavailable?` entries

### Device (s)

Raspberry Pi 3 Mod. B

### System

```
$ cat /etc/rpi-issue 
Raspberry Pi reference 2023-05-03
Generated using pi-gen, https://github.com/RPi-Distro/pi-gen, 7c750947a959fb626a70c09fd17c65815df192ac, stage2
```

```
$ vcgencmd version
Mar 17 2023 10:52:42 
Copyright (c) 2012 Broadcom
version 82f3750a65fadae9a38077e3c2e217ad158c8d54 (clean) (release) (start)
```

```
$ uname -a
Linux raspberrypi 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux
```

```
$ apt show iotop
Package: iotop
Version: 0.6-24-g733f3f8-1.1
Priority: optional
Section: admin
Maintainer: Paul Wise <pabs@debian.org>
Installed-Size: 102 kB
Depends: python3:any
Homepage: http://guichaz.free.fr/iotop/
Tag: admin::monitoring, implemented-in::python, interface::text-mode,
 role::program, scope::utility, use::monitor
Download-Size: 33.3 kB
APT-Manual-Installed: yes
APT-Sources: http://deb.debian.org/debian bullseye/main arm64 Packages
Description: simple top-like I/O monitor
 iotop does for I/O usage what top(1) does for CPU usage. It watches I/O
 usage information output by the Linux kernel and displays a table of
 current I/O usage by processes on the system. It is handy for answering
 the question "Why is the disk churning so much?".
 .
 iotop can only run under a Linux 2.6.20 or later kernel built with the
 CONFIG_TASKSTATS, CONFIG_TASK_DELAY_ACCT, CONFIG_TASK_IO_ACCOUNTING and
 CONFIG_VM_EVENT_COUNTERS build config options on.
```

### Additional context

Adding `delayacct` to `boot/cmdline.txt` does not seem to help either, `iotop` gives the same complaint.

**Comment by pelwell** [comment]
Having got around to trying this I was surprised to discover that delay accounting support is included (but not enabled by default) in the other Raspberry Pi defconfigs. 78dd782a2e40 adds it, and it will be included in future kernel builds.

Note that you will still need to add `delayacct` to cmdline.txt to enable it.
