### ISSUE TITLE
All the SoC Audio's are missing in 3.13.9

### ISSUE THREAD

**Issue by amtssp** [raspberrypi/linux#555]
Hi, I have been waiting for the new 3.13.y kernel with support for the IQaudIO DAC - however all the SoC options are not present when using "make menuconfig". So even the HiFiBerry DAC and Digi are missing now.
If I manually look inside the bcmrpi_defconfig the SOC modules are listed - but after having used menuconfig on this file these modules have been removed. 

I therefore also downloaded the new 3.10.36 kernel and did exactly the same - and here all the SoCt Audio devices are present (hifiberry dac, digi, RPI DAC and the new IQaudIO dac).

Steen

**Comment by amtssp** [comment]
It is OK in kernel 3.14.y also - so the problem is isolated to version 3.13.9

Steen

**Comment by popcornmix** [comment]
I've rebased 3.14 patches onto 3.13 branch. Does that work okay?

**Comment by amtssp** [comment]
Sorry - still not fixed with the new 3.13 version.
I'm using 3.14 now - but will test 3.13 when you want me to.

**Comment by popcornmix** [comment]
Okay, found a missing kconfig include. Can you try now?

**Comment by amtssp** [comment]
Thanks - the new 3.13.y is all OK now.

**Comment by amtssp** [comment]
Hi I reopened this, because it is not completely solved.
It is now possible to add these I2S DACs via menuconfig, however, they are not build as modules.

They used to be build in kernel/sound/soc/bcm , however there is no bcm directory build.
The only directories in the soc directory are codecs dwc and generic

**Comment by popcornmix** [comment]
Okay, found a missing entry in sound/soc/Makefile
Can you try now?

**Comment by amtssp** [comment]
Hi Sorry for my delay, but I just tried again. It is better, but still not perfect.

The bcm directory is now made, and it contains:
snd-soc-rpi-dac.ko
snd-soc-hifiberry-digi.ko
snd-soc-hifiberry-dac.ko
snd-soc-bcm2708-i2s.ko

BUT the IQaudIO dac module is still not created (it is selected as a module in menuconfig - just as all the other DACs)

**Comment by amtssp** [comment]
sorry false alarm - tried again and now all the modules are here.
Problem seems to be fixed now
