### ISSUE TITLE
Installation bug

### ISSUE THREAD

**Issue by ghost** [raspberrypi/linux#5575]
### Describe the bug

![install](https://github.com/raspberrypi/linux/assets/142316563/3f1ff2bd-ff4a-4df6-84e2-7fa8499afda7)
This setup should give me a Norwegian keyboard layout, I would think? But it does not, it gives me a US layout. No matter if the US keyboard box is ticked or not, it will always give me a US keyboard. Even when the English language box is not ticked, it will give me a US layout.

Also, the Norwegian letter å is shown as a code, in Bokmål. If the Norwegian letter å cannot be shown, then it is standard to use a double aa, like Bokmaal. That would be more correct and look a lot better than what is shown on the screen

### Steps to reproduce the behaviour

Chose the country Norway and the language Bookmål during installation, and you get the US keyboard layout.

### Device (s)

Raspberry Pi 4 Mod. B, Raspberry Pi 400

### System

Any version of Raspberry Pi OS.

**Comment by XECDesign** [comment]
Again, this doesn't look like a linux kernel issue.

It should be reported here - https://github.com/raspberrypi-ui/piwiz/issues

@spl237

**Comment by ghost** [comment]
No wonder that the bugs don't get reported, it's almost impossible :-)
I have tried the Raspberry Pi forum, Raspberry Pi contact, Github and now
another Github page.
But thanks for replying, anyway :-)

tir. 15. aug. 2023 kl. 14:37 skrev XECDesign ***@***.***>:

**Comment by spl237** [comment]
The bug (if it is indeed a bug...) should be reported here - https://github.com/raspberrypi-ui/piwiz

**Comment by ghost** [comment]
I'll do :)

tir. 15. aug. 2023 kl. 14:44 skrev Simon Long ***@***.***>:
