### ISSUE TITLE
Raspberry Pi OS (64-bit kernel) uses kodi to play video kodi will freeze

### ISSUE THREAD

**Issue by Oliv1a** [raspberrypi/linux#5579]
### Describe the bug

My environment is Raspberry Pi 4 v1.2 hardware version, using the latest Raspberry Pi OS, the latest version of kodi installed through apt, the specific performance is that when using kodi to watch local video or streaming media for a long time, it will randomly freeze and can’t do any operation on kodi, and the kill -9 command can’t end the process of kodi stuck. I can only restart the system. 

### Steps to reproduce the behaviour

1. Install Raspberry pi OS (64-bit kernel) on Raspberry Pi 4B
2. Install kodi from raspberry pi official repository using apt install kodi kodi-pvr-iptvsimple
3. Connect the display device and use kodi to play local video or streaming media
4. Continue to play for a period of time, usually Kodi will be stuck for several hours at most one day

### Device (s)

Raspberry Pi 4 Mod. B

### System

cat /etc/rpi-issue
Raspberry Pi reference 2022-09-22
Generated using pi-gen, https://github.com/RPi-Distro/pi-gen, 8a42abcd1dbd8c9c1fdfca4e0c3778255b2f9cc4, stage4

vcgencmd version
Mar 17 2023 10:50:39 
Copyright (c) 2012 Broadcom
version 82f3750a65fadae9a38077e3c2e217ad158c8d54 (clean) (release) (start)

uname -a
Linux pi.local 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr 3 17:24:16 BST 2023 aarch64 GNU/Linux

### Additional context

The problem can be reproduced whether using the 64-bit kernel of the 32-bit system or the 64-bit system and whether using kms or fkms.

**Comment by popcornmix** [comment]
Output of `sudo vclog -m`, `dmesg` and `~/.kodi/temp/kodi.log` after a freeze may have some clues.

What is the format of the videos being played when it freezes? (i.e. codec and resolution/framerate).
It may be useful to disable hw acceleration in kodi, and confirm if you still have the issue (but this will limit the resolution of videos that play well).

**Comment by qrp73** [comment]
When freeze happens try to switch into tty1 with Ctrl+Alt+F1 and then back into desktop with Ctrl+Alt+F7. Does it fix freeze?

**Comment by Oliv1a** [comment]
> Output of `sudo vclog -m`, `dmesg` and `~/.kodi/temp/kodi.log` after a freeze may have some clues.
> 
> What is the format of the videos being played when it freezes? (i.e. codec and resolution/framerate). It may be useful to disable hw acceleration in kodi, and confirm if you still have the issue (but this will limit the resolution of videos that play well).

I recorded two freezes. The video format played was H.264/25FPS/1080p. The logs are as follows:

1.

vclog -m

004195.568: brfs: File read: /mfs/sd/config.txt
004196.631: brfs: File read: 2308 bytes
004217.351: brfs: File read: /mfs/sd/edid.dat
004230.925: HDMI1:EDID error reading EDID block 0 attempt 0
004231.941: HDMI1:EDID giving up on reading EDID block 0
004232.021: brfs: File read: 256 bytes
004238.558: brfs: File read: /mfs/sd/config.txt
004999.874: gpioman: gpioman_get_pin_num: pin DISPLAY_DSI_PORT not defined
005002.397: *** Restart logging
005002.418: brfs: File read: 2308 bytes
005019.388: hdmi: HDMI1:EDID error reading EDID block 0 attempt 0
005020.406: hdmi: HDMI1:EDID giving up on reading EDID block 0
005025.445: hdmi: HDMI1:EDID error reading EDID block 0 attempt 0
005026.460: hdmi: HDMI1:EDID giving up on reading EDID block 0
005026.479: hdmi: HDMI:hdmi_get_state is deprecated, use hdmi_get_display_state instead
005026.494: HDMI0: hdmi_pixel_encoding: 300000000
005026.506: HDMI1: hdmi_pixel_encoding: 300000000
005027.020: kernel=
005048.848: dtb_file 'bcm2711-rpi-4-b.dtb'
005053.396: brfs: File read: /mfs/sd/bcm2711-rpi-4-b.dtb
005053.413: Loaded 'bcm2711-rpi-4-b.dtb' to 0x100 size 0xcd71
005066.512: brfs: File read: 52593 bytes
005075.641: brfs: File read: /mfs/sd/overlays/overlay_map.dtb
005156.438: brfs: File read: 2347 bytes
005160.046: brfs: File read: /mfs/sd/config.txt
005160.592: dtparam: audio=on
005165.270: brfs: File read: 2308 bytes
005178.031: brfs: File read: /mfs/sd/overlays/vc4-kms-v3d-pi4.dtbo
005240.006: Loaded overlay 'vc4-kms-v3d'
005436.816: brfs: File read: 3913 bytes
005441.216: brfs: File read: /mfs/sd/overlays/disable-wifi.dtbo
005462.802: Loaded overlay 'disable-wifi'
005497.413: brfs: File read: 387 bytes
005501.345: brfs: File read: /mfs/sd/overlays/disable-bt.dtbo
005538.580: Loaded overlay 'disable-bt'
005637.064: brfs: File read: 1073 bytes
005638.905: brfs: File read: /mfs/sd/cmdline.txt
005639.018: Read command line from file 'cmdline.txt':
005639.055: 'console=serial0,115200 console=tty1 root=PARTUUID=62367d8a-02 rootfstype=ext4 fsck.repair=yes rootwait usbhid.mousepoll=0 quiet splash plymouth.ignore-serial-consoles vc4.force_hotplug=1 video=HDMI-A-1:1360x768M@60D'
005961.289: brfs: File read: 215 bytes
006361.313: brfs: File read: /mfs/sd/kernel8.img
006361.348: Loaded 'kernel8.img' to 0x80000 size 0x7d6bd0
009127.555: Kernel relocated to 0x200000
009127.583: Device tree loaded to 0x2eff2a00 (size 0xd53a)
009134.696: bfs_xhci_stop
009134.711: XHCI-STOP
009135.136: xHC ver: 256 HCS: 05000420 fc000031 00e70004 HCC: 002841eb
009135.197: USBSTS 18
011048.210: vchiq_core: vchiq_init_state: slot_zero = 0xcf000000, is_master = 1
011058.296: TV service:host side not connected, dropping notification 0x00000002, 0x00000002, 0x00000027
209156.619: video_decode:8:RIL: resolution changing
240543.593: video_decode:10:RIL: resolution changing
-1525995.-301: video_decode:13:RIL: resolution changing
974451.376: video_decode:16:RIL: resolution changing
1077202.361: video_decode:17:RIL: resolution changing
1634162.961: video_decode:18:RIL: resolution changing
-1713572.-223: video_decode:19:RIL: resolution changing
-1671497.-588: video_decode:20:RIL: resolution changing
-162943.-939: video_decode:21:RIL: resolution changing
-129077.-894: video_decode:22:RIL: resolution changing
-91245.-552: video_decode:23:RIL: resolution changing
018287.497: video_decode:24:RIL: resolution changing
054468.333: video_decode:25:RIL: resolution changing
-1983030.-736: video_decode:26:RIL: resolution changing
1111692.016: video_decode:27:RIL: resolution changing
1134567.398: video_decode:28:RIL: resolution changing
1151083.688: video_decode:29:RIL: resolution changing
1258803.099: video_decode:30:RIL: resolution changing
1265342.507: video_decode:31:RIL: resolution changing
1285746.407: video_decode:32:RIL: resolution changing
-262857.-670: video_decode:33:RIL: resolution changing
-248791.-587: video_decode:35:RIL: resolution changing
-227048.-56: video_decode:36:RIL: resolution changing
-183235.-519: video_decode:38:RIL: resolution changing
-180503.-616: video_decode:39:RIL: resolution changing
-174504.-352: video_decode:41:RIL: resolution changing
-171435.-982: video_decode:42:RIL: resolution changing
-166828.-141: video_decode:43:RIL: resolution changing
207616.799: video_decode:44:RIL: resolution changing
315455.232: video_decode:45:RIL: resolution changing
334153.884: video_decode:46:RIL: resolution changing
343292.266: video_decode:47:RIL: resolution changing
1255363.409: video_decode:48:RIL: resolution changing
-2143132.-118: video_decode:49:RIL: resolution changing
-1283121.-867: video_decode:50:RIL: resolution changing
-1023009.-431: video_decode:51:RIL: resolution changing
-1015123.-652: video_decode:52:RIL: resolution changing
-985223.-986: video_decode:53:RIL: resolution changing
-978454.-318: video_decode:54:RIL: resolution changing
-971596.-890: video_decode:55:RIL: resolution changing
-960384.-231: video_decode:56:RIL: resolution changing
-955985.-722: video_decode:57:RIL: resolution changing
-850689.-190: video_decode:58:RIL: resolution changing
-843805.-47: video_decode:59:RIL: resolution changing
-834965.-612: video_decode:60:RIL: resolution changing
-820310.-990: video_decode:61:RIL: resolution changing
-784983.-551: video_decode:62:RIL: resolution changing
-770104.-368: video_decode:63:RIL: resolution changing
-756136.-541: video_decode:64:RIL: resolution changing
-752742.-421: video_decode:65:RIL: resolution changing
-672256.-27: video_decode:66:RIL: resolution changing
-411713.-398: video_decode:67:RIL: resolution changing
118403.726: video_decode:68:RIL: resolution changing
129645.245: video_decode:69:RIL: resolution changing
138864.878: video_decode:70:RIL: resolution changing
144398.665: video_decode:71:RIL: resolution changing
166335.635: video_decode:72:RIL: resolution changing
1382280.906: video_decode:73:RIL: resolution changing
-1904880.-930: video_decode:74:RIL: resolution changing
076856.944: video_decode:75:RIL: resolution changing
1932431.795: video_decode:76:RIL: resolution changing
2032003.269: video_decode:77:RIL: resolution changing
2082206.615: video_decode:78:RIL: resolution changing
-1008942.-313: video_decode:79:RIL: resolution changing
-780937.-360: video_decode:80:RIL: resolution changing
1217202.238: video_decode:81:RIL: resolution changing
1324208.643: video_decode:82:RIL: resolution changing
1371815.930: video_decode:83:RIL: resolution changing
1537402.764: video_decode:84:RIL: resolution changing
1707183.041: video_decode:85:RIL: resolution changing
-1927861.-94: video_decode:86:RIL: resolution changing
-1640308.-145: video_decode:87:RIL: resolution changing
-1066223.-545: video_decode:88:RIL: resolution changing
-852697.-331: video_decode:89:RIL: resolution changing
-839185.-477: video_decode:91:RIL: resolution changing
1205806.318: video_decode:94:RIL: resolution changing
1259206.222: video_decode:100:RIL: resolution changing
1458228.804: video_decode:103:RIL: resolution changing
-517726.-249: video_decode:107:RIL: resolution changing
-2075178.-892: video_decode:108:RIL: resolution changing
-2035520.-470: video_decode:109:RIL: resolution changing
-1107137.-09: video_decode:110:RIL: resolution changing
-272098.-789: video_decode:111:RIL: resolution changing
468991.210: video_decode:112:RIL: resolution changing

dmesg

[96696.237498] bcm2835_mmal_vchiq: timed out waiting for sync completion
[96696.237523] bcm2835-codec bcm2835-codec: bcm2835_codec_stop_streaming: Failed disabling i/p port, ret -62
[96699.309512] bcm2835_mmal_vchiq: timed out waiting for sync completion
[96699.309533] bcm2835-codec bcm2835-codec: bcm2835_codec_start_streaming: Failed enabling i/p port, ret -62
[96702.381527] bcm2835_mmal_vchiq: timed out waiting for sync completion
[96702.381550] bcm2835-codec bcm2835-codec: bcm2835_codec_start_streaming: Failed enabling i/p port, ret -62
[96705.453576] bcm2835_mmal_vchiq: timed out waiting for sync completion
[96705.453608] bcm2835-codec bcm2835-codec: bcm2835_codec_start_streaming: Failed enabling i/p port, ret -62
[96708.525567] bcm2835_mmal_vchiq: timed out waiting for sync completion
[96708.525587] bcm2835-codec bcm2835-codec: bcm2835_codec_start_streaming: Failed enabling i/p port, ret -62
[96711.597585] bcm2835_mmal_vchiq: timed out waiting for sync completion
[96711.597606] bcm2835-codec bcm2835-codec: bcm2835_codec_start_streaming: Failed enabling i/p port, ret -62
[96714.669611] bcm2835_mmal_vchiq: timed out waiting for sync completion
[96714.669633] bcm2835-codec bcm2835-codec: bcm2835_codec_start_streaming: Failed enabling i/p port, ret -62
[96717.741890] bcm2835_mmal_vchiq: timed out waiting for sync completion
[96717.741922] bcm2835-codec bcm2835-codec: bcm2835_codec_start_streaming: Failed enabling i/p port, ret -62
[96720.813641] bcm2835_mmal_vchiq: timed out waiting for sync completion
[96720.813662] bcm2835-codec bcm2835-codec: bcm2835_codec_start_streaming: Failed enabling i/p port, ret -62
[96723.885659] bcm2835_mmal_vchiq: timed out waiting for sync completion
[96723.885682] bcm2835-codec bcm2835-codec: bcm2835_codec_start_streaming: Failed enabling i/p port, ret -62
[96726.957679] bcm2835_mmal_vchiq: timed out waiting for sync completion
[96726.957699] bcm2835-codec bcm2835-codec: bcm2835_codec_start_streaming: Failed enabling i/p port, ret -62
[96730.029699] bcm2835_mmal_vchiq: timed out waiting for sync completion
[96730.029720] bcm2835-codec bcm2835-codec: bcm2835_codec_start_streaming: Failed enabling i/p port, ret -62
[96733.101719] bcm2835_mmal_vchiq: timed out waiting for sync completion
[96733.101740] bcm2835-codec bcm2835-codec: bcm2835_codec_start_streaming: Failed enabling i/p port, ret -62
[96736.173749] bcm2835_mmal_vchiq: timed out waiting for sync completion
[96736.173770] bcm2835-codec bcm2835-codec: bcm2835_codec_start_streaming: Failed enabling i/p port, ret -62
[96739.245754] bcm2835_mmal_vchiq: timed out waiting for sync completion
[96739.245775] bcm2835-codec bcm2835-codec: bcm2835_codec_start_streaming: Failed enabling i/p port, ret -62
[96742.317778] bcm2835_mmal_vchiq: timed out waiting for sync completion
[96742.317799] bcm2835-codec bcm2835-codec: bcm2835_codec_start_streaming: Failed enabling i/p port, ret -62
[96745.389813] bcm2835_mmal_vchiq: timed out waiting for sync completion
[96745.389839] bcm2835-codec bcm2835-codec: bcm2835_codec_start_streaming: Failed enabling i/p port, ret -62
[96748.461813] bcm2835_mmal_vchiq: timed out waiting for sync completion
[96748.461833] bcm2835-codec bcm2835-codec: bcm2835_codec_start_streaming: Failed enabling i/p port, ret -62
[96751.533846] bcm2835_mmal_vchiq: timed out waiting for sync completion
[96751.533867] bcm2835-codec bcm2835-codec: bcm2835_codec_start_streaming: Failed enabling i/p port, ret -62
[96754.605862] bcm2835_mmal_vchiq: timed out waiting for sync completion
[96754.605884] bcm2835-codec bcm2835-codec: bcm2835_codec_start_streaming: Failed enabling i/p port, ret -62
[96757.677872] bcm2835_mmal_vchiq: timed out waiting for sync completion
[96757.677893] bcm2835-codec bcm2835-codec: bcm2835_codec_start_streaming: Failed enabling i/p port, ret -62
[96760.749911] bcm2835_mmal_vchiq: timed out waiting for sync completion
[96760.749932] bcm2835-codec bcm2835-codec: bcm2835_codec_start_streaming: Failed enabling i/p port, ret -62
[96763.821947] bcm2835_mmal_vchiq: timed out waiting for sync completion
[96763.821968] bcm2835-codec bcm2835-codec: bcm2835_codec_start_streaming: Failed enabling i/p port, ret -62
[96766.893939] bcm2835_mmal_vchiq: timed out waiting for sync completion
[96766.893959] bcm2835-codec bcm2835-codec: bcm2835_codec_start_streaming: Failed enabling i/p port, ret -62
[96769.965948] bcm2835_mmal_vchiq: timed out waiting for sync completion
[96769.965971] bcm2835-codec bcm2835-codec: bcm2835_codec_start_streaming: Failed enabling i/p port, ret -62
[96773.037986] bcm2835_mmal_vchiq: timed out waiting for sync completion
[96773.038006] bcm2835-codec bcm2835-codec: bcm2835_codec_start_streaming: Failed enabling i/p port, ret -62
[96776.109997] bcm2835_mmal_vchiq: timed out waiting for sync completion
[96776.110017] bcm2835-codec bcm2835-codec: bcm2835_codec_start_streaming: Failed enabling i/p port, ret -62
[96779.182014] bcm2835_mmal_vchiq: timed out waiting for sync completion
[96779.182034] bcm2835-codec bcm2835-codec: bcm2835_codec_start_streaming: Failed enabling i/p port, ret -62

~/.kodi/temp/kodi.log

[https://paste.kodi.tv/oqesuquham.kodi](https://paste.kodi.tv/oqesuquham.kodi)

2.

vclog -m

004198.072: brfs: File read: /mfs/sd/config.txt
004199.136: brfs: File read: 2308 bytes
004220.821: brfs: File read: /mfs/sd/edid.dat
004234.400: HDMI1:EDID error reading EDID block 0 attempt 0
004235.416: HDMI1:EDID giving up on reading EDID block 0
004235.496: brfs: File read: 256 bytes
004244.293: brfs: File read: /mfs/sd/config.txt
005005.976: gpioman: gpioman_get_pin_num: pin DISPLAY_DSI_PORT not defined
005008.500: *** Restart logging
005008.521: brfs: File read: 2308 bytes
005026.475: hdmi: HDMI1:EDID error reading EDID block 0 attempt 0
005027.493: hdmi: HDMI1:EDID giving up on reading EDID block 0
005032.532: hdmi: HDMI1:EDID error reading EDID block 0 attempt 0
005033.549: hdmi: HDMI1:EDID giving up on reading EDID block 0
005033.567: hdmi: HDMI:hdmi_get_state is deprecated, use hdmi_get_display_state instead
005033.583: HDMI0: hdmi_pixel_encoding: 300000000
005033.594: HDMI1: hdmi_pixel_encoding: 300000000
005034.108: kernel=
005061.069: dtb_file 'bcm2711-rpi-4-b.dtb'
005065.591: brfs: File read: /mfs/sd/bcm2711-rpi-4-b.dtb
005065.608: Loaded 'bcm2711-rpi-4-b.dtb' to 0x100 size 0xcd71
005078.722: brfs: File read: 52593 bytes
005087.630: brfs: File read: /mfs/sd/overlays/overlay_map.dtb
005168.469: brfs: File read: 2347 bytes
005173.188: brfs: File read: /mfs/sd/config.txt
005173.734: dtparam: audio=on
005178.395: brfs: File read: 2308 bytes
005191.204: brfs: File read: /mfs/sd/overlays/vc4-kms-v3d-pi4.dtbo
005252.688: Loaded overlay 'vc4-kms-v3d'
005437.886: brfs: File read: 3913 bytes
005442.214: brfs: File read: /mfs/sd/overlays/disable-wifi.dtbo
005463.831: Loaded overlay 'disable-wifi'
005498.276: brfs: File read: 387 bytes
005502.156: brfs: File read: /mfs/sd/overlays/disable-bt.dtbo
005539.423: Loaded overlay 'disable-bt'
005637.921: brfs: File read: 1073 bytes
005639.765: brfs: File read: /mfs/sd/cmdline.txt
005639.878: Read command line from file 'cmdline.txt':
005639.915: 'console=serial0,115200 console=tty1 root=PARTUUID=62367d8a-02 rootfstype=ext4 fsck.repair=yes rootwait usbhid.mousepoll=0 quiet splash plymouth.ignore-serial-consoles vc4.force_hotplug=1 video=HDMI-A-1:1360x768M@60D'
005962.204: brfs: File read: 215 bytes
006362.481: brfs: File read: /mfs/sd/kernel8.img
006362.516: Loaded 'kernel8.img' to 0x80000 size 0x7d6bd0
009128.660: Kernel relocated to 0x200000
009128.686: Device tree loaded to 0x2eff2a00 (size 0xd53a)
009135.762: bfs_xhci_stop
009135.776: XHCI-STOP
009136.224: xHC ver: 256 HCS: 05000420 fc000031 00e70004 HCC: 002841eb
009136.284: USBSTS 18
011061.758: vchiq_core: vchiq_init_state: slot_zero = 0xcf000000, is_master = 1
011071.781: TV service:host side not connected, dropping notification 0x00000002, 0x00000002, 0x00000027
116421.297: video_decode:8:RIL: resolution changing
1252116.426: video_decode:9:RIL: resolution changing
1291676.498: video_decode:10:RIL: resolution changing
-1969200.-861: video_decode:11:RIL: resolution changing
-1644422.-66: video_decode:12:RIL: resolution changing
-227995.-933: video_decode:13:RIL: resolution changing

dmesg

[ 4766.209432] bcm2835_mmal_vchiq: timed out waiting for sync completion
[ 4766.209453] bcm2835-codec bcm2835-codec: bcm2835_codec_stop_streaming: Failed disabling i/p port, ret -62
[ 4769.281470] bcm2835_mmal_vchiq: timed out waiting for sync completion
[ 4769.281492] bcm2835-codec bcm2835-codec: bcm2835_codec_start_streaming: Failed enabling i/p port, ret -62
[ 4772.353514] bcm2835_mmal_vchiq: timed out waiting for sync completion
[ 4772.353681] bcm2835-codec bcm2835-codec: bcm2835_codec_start_streaming: Failed enabling i/p port, ret -62
[ 4775.425499] bcm2835_mmal_vchiq: timed out waiting for sync completion
[ 4775.425522] bcm2835-codec bcm2835-codec: bcm2835_codec_start_streaming: Failed enabling i/p port, ret -62
[ 4778.497532] bcm2835_mmal_vchiq: timed out waiting for sync completion
[ 4778.497559] bcm2835-codec bcm2835-codec: bcm2835_codec_start_streaming: Failed enabling i/p port, ret -62
[ 4781.569553] bcm2835_mmal_vchiq: timed out waiting for sync completion
[ 4781.569574] bcm2835-codec bcm2835-codec: bcm2835_codec_start_streaming: Failed enabling i/p port, ret -62
[ 4784.641585] bcm2835_mmal_vchiq: timed out waiting for sync completion
[ 4784.641611] bcm2835-codec bcm2835-codec: bcm2835_codec_start_streaming: Failed enabling i/p port, ret -62
[ 4787.713595] bcm2835_mmal_vchiq: timed out waiting for sync completion
[ 4787.713615] bcm2835-codec bcm2835-codec: bcm2835_codec_start_streaming: Failed enabling i/p port, ret -62
[ 4790.785714] bcm2835_mmal_vchiq: timed out waiting for sync completion
[ 4790.785770] bcm2835-codec bcm2835-codec: bcm2835_codec_start_streaming: Failed enabling i/p port, ret -62
[ 4793.857735] bcm2835_mmal_vchiq: timed out waiting for sync completion
[ 4793.857797] bcm2835-codec bcm2835-codec: bcm2835_codec_start_streaming: Failed enabling i/p port, ret -62
[ 4796.929689] bcm2835_mmal_vchiq: timed out waiting for sync completion
[ 4796.929708] bcm2835-codec bcm2835-codec: bcm2835_codec_start_streaming: Failed enabling i/p port, ret -62
[ 4800.001793] bcm2835_mmal_vchiq: timed out waiting for sync completion
[ 4800.001814] bcm2835-codec bcm2835-codec: bcm2835_codec_start_streaming: Failed enabling i/p port, ret -62
[ 4803.073826] bcm2835_mmal_vchiq: timed out waiting for sync completion
[ 4803.073847] bcm2835-codec bcm2835-codec: bcm2835_codec_start_streaming: Failed enabling i/p port, ret -62
[ 4806.145772] bcm2835_mmal_vchiq: timed out waiting for sync completion
[ 4806.145792] bcm2835-codec bcm2835-codec: bcm2835_codec_start_streaming: Failed enabling i/p port, ret -62
[ 4809.217764] bcm2835_mmal_vchiq: timed out waiting for sync completion
[ 4809.217786] bcm2835-codec bcm2835-codec: bcm2835_codec_start_streaming: Failed enabling i/p port, ret -62
[ 4812.289772] bcm2835_mmal_vchiq: timed out waiting for sync completion
[ 4812.289787] bcm2835-codec bcm2835-codec: bcm2835_codec_start_streaming: Failed enabling i/p port, ret -62
[ 4815.361800] bcm2835_mmal_vchiq: timed out waiting for sync completion
[ 4815.361820] bcm2835-codec bcm2835-codec: bcm2835_codec_start_streaming: Failed enabling i/p port, ret -62
[ 4818.433830] bcm2835_mmal_vchiq: timed out waiting for sync completion
[ 4818.433852] bcm2835-codec bcm2835-codec: bcm2835_codec_start_streaming: Failed enabling i/p port, ret -62
[ 4821.505855] bcm2835_mmal_vchiq: timed out waiting for sync completion
[ 4821.505877] bcm2835-codec bcm2835-codec: bcm2835_codec_start_streaming: Failed enabling i/p port, ret -62
[ 4824.577873] bcm2835_mmal_vchiq: timed out waiting for sync completion
[ 4824.577894] bcm2835-codec bcm2835-codec: bcm2835_codec_start_streaming: Failed enabling i/p port, ret -62
[ 4827.653882] bcm2835_mmal_vchiq: timed out waiting for sync completion
[ 4827.653904] bcm2835-codec bcm2835-codec: bcm2835_codec_start_streaming: Failed enabling i/p port, ret -62
[ 4830.721921] bcm2835_mmal_vchiq: timed out waiting for sync completion
[ 4830.721942] bcm2835-codec bcm2835-codec: bcm2835_codec_start_streaming: Failed enabling i/p port, ret -62
[ 4833.793940] bcm2835_mmal_vchiq: timed out waiting for sync completion
[ 4833.793961] bcm2835-codec bcm2835-codec: bcm2835_codec_start_streaming: Failed enabling i/p port, ret -62
[ 4836.865966] bcm2835_mmal_vchiq: timed out waiting for sync completion
[ 4836.866009] bcm2835-codec bcm2835-codec: bcm2835_codec_start_streaming: Failed enabling i/p port, ret -62
[ 4839.937990] bcm2835_mmal_vchiq: timed out waiting for sync completion
[ 4839.938018] bcm2835-codec bcm2835-codec: bcm2835_codec_start_streaming: Failed enabling i/p port, ret -62
[ 4843.010007] bcm2835_mmal_vchiq: timed out waiting for sync completion
[ 4843.010028] bcm2835-codec bcm2835-codec: bcm2835_codec_start_streaming: Failed enabling i/p port, ret -62
[ 4846.082048] bcm2835_mmal_vchiq: timed out waiting for sync completion
[ 4846.082069] bcm2835-codec bcm2835-codec: bcm2835_codec_start_streaming: Failed enabling i/p port, ret -62
[ 4849.154063] bcm2835_mmal_vchiq: timed out waiting for sync completion
[ 4849.154084] bcm2835-codec bcm2835-codec: bcm2835_codec_start_streaming: Failed enabling i/p port, ret -62

~/.kodi/temp/kodi.log

[https://paste.kodi.tv/afazogisot.kodi](https://paste.kodi.tv/afazogisot.kodi)

I then tried to disable hardware acceleration, but the video playback was severely stuck and could not be tested.

**Comment by Oliv1a** [comment]
> When freeze happens try to switch into tty1 with Ctrl+Alt+F1 and then back into desktop with Ctrl+Alt+F7. Does it fix freeze?

There seems to be no response

**Comment by popcornmix** [comment]
Does this reliably fail with a certain video?
If so, can you post a sample video file (e.g. a 1 or 2 minute cut of video to google drive or dropbox) that exhibits the issue?

The messages suggest the video is unusual and contains resolution changes.

Also it could be worth adding `over_voltage=2` to `/boot/config.txt` and rebooting and trying again.
We have had occasional reports of h264 fails that get fixed that way.

**Comment by Oliv1a** [comment]
> Does this reliably fail with a certain video? If so, can you post a sample video file (e.g. a 1 or 2 minute cut of video to google drive or dropbox) that exhibits the issue?
> 
> The messages suggest the video is unusual and contains resolution changes.
> 
> Also it could be worth adding `over_voltage=2` to `/boot/config.txt` and rebooting and trying again. We have had occasional reports of h264 fails that get fixed that way.

What I have observed for a long time here is that whether it is local video or streaming media, regardless of the video format and encoding, as long as you switch to a 64-bit kernel, the problem can generally be reproduced within 24 hours of continuous video playback. This problem has persisted since I started using Raspberry Pi 4 (5.x kernel). I don’t know if it’s related to my 1.2 hardware version or because my monitor resolution is 1366*768? But with the same hardware and configuration, this problem disappears as long as you switch to the 32-bit kernel, so I guessed whether there is something wrong with the 64-bit kernel. I would try adding over_voltage=2 to /boot/config.txt to test and see if that resolves the issue.

**Comment by Oliv1a** [comment]
> Does this reliably fail with a certain video? If so, can you post a sample video file (e.g. a 1 or 2 minute cut of video to google drive or dropbox) that exhibits the issue?
> 
> The messages suggest the video is unusual and contains resolution changes.
> 
> Also it could be worth adding `over_voltage=2` to `/boot/config.txt` and rebooting and trying again. We have had occasional reports of h264 fails that get fixed that way.

After a long period of observation and testing, it is confirmed that the problem has been solved, thank you very much!
