### ISSUE TITLE
Problem with repo php5 apache2 libapache2-mod-php5

### ISSUE THREAD

**Issue by Alan410** [raspberrypi/linux#558]
when running sudo apt-get install apache2 php5 libapache2-mod-php5 on my raspberry pi i get following error:

Failed to fetch http://mirrordirector.raspbian.org/raspbian/pool/main/p/php5/php5-common_5.4.4-14+deb7u7_armhf.deb  404  Not Found
Failed to fetch http://mirrordirector.raspbian.org/raspbian/pool/main/a/apache2/apache2.2-bin_2.2.22-13_armhf.deb  404  Not Found
Failed to fetch http://mirrordirector.raspbian.org/raspbian/pool/main/a/apache2/apache2-utils_2.2.22-13_armhf.deb  404  Not Found
Failed to fetch http://mirrordirector.raspbian.org/raspbian/pool/main/a/apache2/apache2.2-common_2.2.22-13_armhf.deb  404  Not Found
Failed to fetch http://mirrordirector.raspbian.org/raspbian/pool/main/a/apache2/apache2-mpm-prefork_2.2.22-13_armhf.deb  404  Not Found
Failed to fetch http://mirrordirector.raspbian.org/raspbian/pool/main/a/apache2/apache2_2.2.22-13_armhf.deb  404  Not Found
Failed to fetch http://mirrordirector.raspbian.org/raspbian/pool/main/p/php5/libapache2-mod-php5_5.4.4-14+deb7u7_armhf.deb  404  Not Found
Failed to fetch http://mirrordirector.raspbian.org/raspbian/pool/main/p/php5/php5_5.4.4-14+deb7u7_all.deb  404  Not Found
Failed to fetch http://mirrordirector.raspbian.org/raspbian/pool/main/p/php5/php5-cli_5.4.4-14+deb7u7_armhf.deb  404  Not Found

i checked the repository and these packages do not exist. There are only slight differences in the repo like for example the first one. It should be "http://mirrordirector.raspbian.org/raspbian/pool/main/p/php5/php5-common_5.4.4-14+deb7u8_armhf.deb" instead of "http://mirrordirector.raspbian.org/raspbian/pool/main/p/php5/php5-common_5.4.4-14+deb7u7_armhf.deb"

**Comment by asb** [comment]
You need to run `sudo apt-get update` first, as your local package database is out of date. This repository is for issues with the Linux kernel itself on the Raspberry Pi. Your best avenue for questions like this is our [Raspberry Pi forums](http://www.raspberrypi.org/forums/) Closing.
