### ISSUE TITLE
usb audio noise during network traffic

### ISSUE THREAD

**Issue by edfardos** [raspberrypi/linux#559]
I've been going through the archive of kernel/firmware updates for my Pi's trying to get audio to render correctly on my C-Media usb (0d8c:0139) audio dongle.  Research indicates the problem exists with all/most usb audio devices however.  

Two years ago audio apps would simply produce distortion, almost white-noise.  At some point this was fixed, and everything was perfect.  Fast forward a number of months (year), and now audio has clicks and pops when and only if there is network traffic, either via the rj45 port, or a usb wifi adapter.

So get an old firmware and you get static/distortion, get a new firmware and you get pops and clicks during network transfers.  Through logarithmic deduction, I found that kernel/firmware commits in the August-September 2013 timeframe worked perfectly.

Using mpg123 as an example:

May 25th 2013 has whitenoise/distortion
001a8517f67182c278e1eff33f1fc2aac0bb22cc

Aug 15th 2013 works perfectly:
74fb6cd381391aaca5591f949b36ec29ee59ba20

Apr  7 2014 has pops and clicks only during network transfers
f85d26d96b56f0e29e1ac37fbf65050eb923c32a

Some audio enthusiasts have resigned themselves to using the 9/25/13 raspbian forever and never again do an rpi-update.  But with new Micron sdram hardware, we need newer firmware just to boot, so I was hoping we could figure out which commits broke what and when.

example thread on the issue:

http://www.raspberrypi.org/forums/viewtopic.php?f=63&t=22280&p=533403#p533403

r,
-edfardos

**Comment by popcornmix** [comment]
Have you tried:
`sudo BRANCH=next rpi-update`
See: http://www.raspberrypi.org/forums/viewtopic.php?f=28&t=70437

**Comment by edfardos** [comment]
Not yet, but I will!

one tester already indicated my problem decription was solved, so it looks very promising.

thank you,
edfardos

**Comment by P33M** [comment]
Fixed with fiq_fsm.
