### ISSUE TITLE
using torrent apps crashes rpi

### ISSUE THREAD

**Issue by reemplazable** [raspberrypi/linux#56]
Hi:
Using rtorrent or tranmission gives me a kernel panic, Can't find the kernel dump.

**Comment by reemplazable** [comment]
http://www.raspberrypi.org/phpBB3/viewtopic.php?f=66&t=11418

**Comment by sdebruyn** [comment]
I experienced this "bug" with the official Debian squeeze image and with the official Debian wheezy image (Raspbian).

**Comment by reemplazable** [comment]
There is a log attached by another user with the same problem here:

http://www.raspberrypi.org/phpBB3/viewtopic.php?f=66&t=11658

**Comment by sdebruyn** [comment]
Also found this thread, some users have been trying a lot of images and keep having the same problem:

http://www.raspberrypi.org/phpBB3/viewtopic.php?f=36&t=6958

**Comment by sdebruyn** [comment]
I guess the following is the same issue, could someone merge or close this one?
https://github.com/raspberrypi/firmware/issues/9

**Comment by reemplazable** [comment]
Seems true, then close this thread!
