### ISSUE TITLE
Mozplugger in Distro

### ISSUE THREAD

**Issue by rsenio** [raspberrypi/linux#562]
I've been speaking with the maintainer of the Mozplugger software with regards to a bug. 

He stated... 
"In that version there was a restriction on the length of some strings to 128 characters which has since been removed. Strings > 128 did not crash mozplugger,  but mozplugger would exit with a suitable error code which the Browser interprets as a crash. Can I suggest you update to latest version of Mozplugger or raise the issue with the distro maintainers if 1.4.5 is the latest version they offer"

How can we get the version in the raspian distro updated to a newer/latest one?

**Comment by popcornmix** [comment]
This sounds like a raspbian distribution question and should be brought up here:
http://www.raspberrypi.org/forums/viewforum.php?f=66

This githu repo is for linux kernel issues.
