### ISSUE TITLE
Usbtv module

### ISSUE THREAD

**Issue by hebaishi** [raspberrypi/linux#563]
Would it be possible to add support for the fushicai easycap usb stick? Module is in gkaindl's ambitv repu under misc/Usbtv. Driver is just a tiny bit of C

**Comment by popcornmix** [comment]
Sorry, we don't take out of tree drivers without a very good reason.
They produce a maintenance headache when updating to newer kernels and have the potential to create instability.

What we do encourage is that useful drivers are submitted upstream.
Once it has been reviewed and accepted upstream, we can merge it in.

See here for details:
http://kernelnewbies.org/UpstreamMerge
