### ISSUE TITLE
raspberrypi-kernel-headers missing in 2023-10-10 bookwork image (64bit, armhf)

### ISSUE THREAD

**Issue by delijati** [raspberrypi/linux#5643]
### Describe the bug

In the current build from 2023-10-10 there is a package missing error for "raspberrypi-kernel-headers". Also i can't see the deb package on https://archive.raspberrypi.org/debian/pool/main/r/raspberrypi-firmware/

### Steps to reproduce the behaviour

Use current image 2023-10-10

### Device (s)

Raspberry Pi CM4

### System

2023-10-10

**Comment by XECDesign** [comment]
For bookworm, we have switched to debian-style packaging for the kernel. If you want the headers for kernel8.img, you'd install `linux-headers-rpi-v8`.

**Comment by delijati** [comment]
Hmm i tried that [1] but still get [2] 

[1] linux-headers-rpi-v8 is already the newest version (1:6.1.54-1+rpt2).
[2] make[1]: *** /lib/modules/6.1.54-v8+/build: No such file or directory.  Stop.

**Comment by delijati** [comment]
ahh i see its now also called `/lib/modules/6.1.0-rpi4-rpi-v8`

**Comment by XECDesign** [comment]
Right, it should match the output of `uname -r`

**Comment by delijati** [comment]
Perfect it works :)

**Comment by darlovic** [comment]
> ahh i see its now also called `/lib/modules/6.1.0-rpi4-rpi-v8`

I am having the same issue, in my case I am trying to install: kernel-headers=6.1.21-v8+. What do you mean by called /lib/modules/6.1.0-rpi4-rpi-v8. Can you make it simple. Thanks in advance

**Comment by neverkid** [comment]
Can 6.1.0-rpi6-rpi-v8 support AppArmor module?I need to install version 2.13.x of the AppArmor module to run the homeassistant service.Thank you for your answer!

**Comment by XECDesign** [comment]
As far as I can tell, apparmor is already compiled in. But, that's not related to this issue, so it's probably best discussed on the forum.

**Comment by neverkid** [comment]
Thank you for your answer. I didn't realize that the main issue has nothing to do with it. Thank you for the reminder.
