### ISSUE TITLE
mpd hangs

### ISSUE THREAD

**Issue by audetto** [raspberrypi/linux#565]
I got this strange behaviour whereby mpd daemon seems to hangs and must be killed with "kill -s KILL". systemctl stop is not enough.
It has happened twice in a couple of months, after changing http stream via the python client (i.e. the equivalent of "mpc next")

I know this does not sound a kernel issue, but once I kill it, I can see in the journal

Apr 19 13:56:35 alarmpi kernel: bcm2835_audio_close:744 bcm2835_audio_close: failed on waiting for event (status=0)
Apr 19 13:56:35 alarmpi kernel: vc_vchi_audio_deinit:331 vc_vchi_audio_deinit: failed to close VCHI service connection (status=1)
Apr 19 13:56:35 alarmpi systemd[1]: mpd.service: main process exited, code=killed, status=9/KILL
Apr 19 13:56:35 alarmpi systemd[1]: Stopped Music Player Daemon.
Apr 19 13:56:35 alarmpi systemd[1]: Unit mpd.service entered failed state.

and I wonder if bcm2835_audio_close or vc_vchi_audio_deinit could be related to this issue.

or maybe it is just a bug in mpd...

**Comment by popcornmix** [comment]
What do "uname -a" and "vcgencmd version" report?
It's not going to be easy to fix without a reproducible test case.
If you can find a way of provoking this failure on demand then we might have a chance.

**Comment by audetto** [comment]
I know this is a weak bug report.

I am on ARCH, custom built kernel from rpi-3.14.y (+ a PS3 bluetooth fix), fiq_mask=0x7

Apr 15 2014 15:01:06 
Copyright (c) 2012 Broadcom
version c1dc12512d5fe9340b6a2ca9badf9441fe6675a8 (clean) (release)

Linux alarmpi 3.14.1-andsoft+ #2 PREEMPT Fri Apr 18 10:30:18 BST 2014 armv6l GNU/Linux

**Comment by popcornmix** [comment]
Can you try with default 3.10 kernel on a raspbian image to confirm if it also happens there?

**Comment by njordan77** [comment]
I'm having the same issue which makes me crazy...using pyhton scripts in background running for my solar power plant which I have to run to log the data.....in parallel trying to run an audio webradio stream crashes by standard ALSA audio immediately so you only can remove the power plug to reboot....reproduces all the time, immediately by using MPC/MPD.....

as soon as I kill the python scrpit it works well....I'm on the latest kernel, from MArch 28th I think (remember) also tried branch-next but did not solve the issue....

**Comment by njordan77** [comment]
one more comment.....when using mplayer instead of mpd at least for the last minutes it did not crash compared to "all the time within seconds" with mpd.....

One other observation, using Bluetooth Audio A2DP streaming it stops playing also with mplayer after 1minute or so, but I guess this is a different kind of issue

**Comment by njordan77** [comment]
sorry me again, mplayer seems to survive little longer, but in the end it crashes also the same hard way....annoying, also as it seems that this issue has been brought up in several ways now back in history....hope that somebody can find the root cause as many RPi users have the feeling that Raspberry with Audio streaming is not the right choice...I still hope not :-)

**Comment by popcornmix** [comment]
Can you try with latest "rpi-update" firmware. There are a couple of changes to ALSA that could have an effect here.

**Comment by njordan77** [comment]
Hi, as I guess mentioned before, I tried Branch-Next and I'm alway "trendy", which means my Firmware looks as follows.....
Linux MyRPi 3.10.34+ #1 PREEMPT Fri Mar 28 20:10:54 CET 2014

Or is there anything new'er that by whatever means I can install....

**Comment by popcornmix** [comment]
master branch is currently newer than next

**Comment by njordan77** [comment]
OK, do not know the details...but I'm right now on the rpi-update branch, which shows the Kernel mentioned above.....is this the one you expect? or how can i get it if not the one you mentioned....thanks

**Comment by popcornmix** [comment]
Latest master rpi-update is 

```
Linux version 3.12.18+ (dc4@dc4-arm-01) (gcc version 4.7.2 20120731 (prerelease) (crosstool-NG linaro-1.13.1+bzr2458 - Linaro GCC 2012.08) ) #677 PREEMPT Mon Apr 28 22:45:00 BST 2014
```

See:
https://github.com/raspberrypi/firmware/blob/master/extra/uname_string

**Comment by njordan77** [comment]
sorry, could not find a way to go to master, as github says that "By default, clones the firmware files from the master branch".....so by RPI-UPDATE i should be on master? guess not, can you please provide a short hint

**Comment by popcornmix** [comment]
`sudo rpi-update`
should be all that's needed. If it thinks you are up to date and you want to force it, then:
`sudo rm /boot/.firmware_revision && sudo rpi-update`
should force it.
Obviously you should reboot after updating.

**Comment by njordan77** [comment]
Thanks, took me some time to find out why rpi-update does not do the same as with other wheezy images....I have a touch display and use a preloaded image based on wheezy, and it seems that it forces to not update the same way.....so started from scratch, now having the right firmware/kernel.....and voila......it works much much better, almost doesn't crash at all....so many thanks!!!!

**Comment by njordan77** [comment]
sorry, i was to quick in saying that everything works fine now.....definitely mpd does never crash.....tried for days now, but what happens now is that my python script tool which logs all solar power data is heavily instable or does not work at all, until I STOP mpd.....

So the initial problem of python not compatible with mpd (ALSA) now seems to be shifted from mpd crashing to python not working properly anymore....

I'm on the latest firmware now: Linux myRPi 3.12.18+ #679 PREEMPT Thu May 1 14:40:27 BST 2014 armv6l GNU/Linux
thanks for your feedback

**Comment by popcornmix** [comment]
Are you getting any errors in dmesg log now?

**Comment by popcornmix** [comment]
Closing due to lack of response
