### ISSUE TITLE
Please don't alter the rtl8192cu driver in 3.14.*.

### ISSUE THREAD

**Issue by konsolebox** [raspberrypi/linux#566]
I believe commit 29437a3891e1daf8664a80819ea086e4fc9498b5 (Add non-mainline source for rtl8192cu wireless driver version v4.0.2_9000 as this is widely used. Disabled older rtlwifi driver) for branch 3.14.y shouldn't have been done. My USB WiFi module works well with the original driver along with firmware rtlwifi/rtl8192cufw_TMSC.bin, but not with the other one that had overridden it. Perhaps the module rtlwifi.ko is also crucial and shouldn't have been skipped.

Some messages that may be notable:

[   11.543987] rtl8192cu: Chip version 0x10
[   11.709457] rtl8192cu: MAC address: 00:1a:ef:41:3d:7d
[   11.709501] rtl8192cu: Board Type 0
[   11.709945] rtl_usb: rx_max_size 15360, rx_urb_num 8, in_ep 1
[   11.710106] rtl8192cu: Loading firmware rtlwifi/rtl8192cufw_TMSC.bin
[   11.710337] usbcore: registered new interface driver rtl8192cu
[   11.806401] ieee80211 phy0: Selected rate control algorithm 'rtl_rc'
[   11.811309] rtlwifi: wireless switch is on
[  309.973101] rtl8192cu: MAC auto ON okay!
[  310.060448] rtl8192cu: Tx queue select: 0x05

**Comment by popcornmix** [comment]
I believe openelec switched to the in-kernel rtl8192cu driver on 3.14 
https://github.com/OpenELEC/OpenELEC.tv/commit/8484e30e6a441ea834d79efa407a7a81abd44b10
about a month ago and reverted the change 2 days later. I believe the in-kernel driver is less stable for most people.

**Comment by moonman** [comment]
ArchLinuxARM in linux-raspberrypy-latest (3.14 at the moment) disables the out of tree driver. However if you wish to reenable you can always install dkms-8192cu package.

**Comment by popcornmix** [comment]
Closing as I believe the in-kernel rtl8192cu driver still has issues.
