### ISSUE TITLE
audio volume cannot be adjusted after switching to another audio output device

### ISSUE THREAD

**Issue by wenqingj** [raspberrypi/linux#5673]
### Describe the bug

Connect to a bluetooth headset, make sure that the audio volume is adjustable (up & down). Then turn off your bluetooth device and connect a wired audio headset to the pi's 3.5mm audio output. The wired headset works but its volume is not adjustable.
The following "workaround" may also serve as a hint on possible underlying cause: right-click on the audio icon (at top-right of the screen), select the bluetooth device (which is disconnected now). You'll get an error message (which is expected). Click okay to accept the error message. After that the wired audio volume becomes adjustable. 
If you switch back to bluetooth again you'll have the same issue. Use the top-right corner icon to switch twice (to wired, then back to bluetooth), and the volume control is back.

### Steps to reproduce the behaviour

It's already been detailed in the bug description.

### Device (s)

Raspberry Pi 4 Mod. B

### System

OS: Raspberry Pi reference 2022-09-22
Generated using pi-gen, https://github.com/RPi-Distro/pi-gen, 005a8c73b05a2cab394073150208bf4f069e861a, stage4
firmware version: Raspberry Pi reference 2022-09-22
Generated using pi-gen, https://github.com/RPi-Distro/pi-gen, 005a8c73b05a2cab394073150208bf4f069e861a, stage4
kernel version: Linux raspberrypi 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64 GNU/Linux
ouput of "sudo rpi-eeprom-update":
BOOTLOADER: up to date
   CURRENT: Thu 11 May 2023 06:26:03 AM UTC (1683786363)
    LATEST: Thu 11 May 2023 06:26:03 AM UTC (1683786363)
   RELEASE: stable (/lib/firmware/raspberrypi/bootloader/stable)
            Use raspi-config to change the release.

  VL805_FW: Using bootloader EEPROM
     VL805: up to date
   CURRENT: 000138c0
    LATEST: 000138c0

### Logs

Not sure if it's relevant but here are the lines from dmesg that has the word "Bluetooth":
[   52.062749] Bluetooth: HCI device and connection manager initialized
[   52.062767] Bluetooth: HCI socket layer initialized
[   52.062783] Bluetooth: L2CAP socket layer initialized
[   52.062799] Bluetooth: SCO socket layer initialized
[   52.925790] Bluetooth: HCI UART driver ver 2.3
[   52.925819] Bluetooth: HCI UART protocol H4 registered
[   52.925921] Bluetooth: HCI UART protocol Three-wire (H5) registered
[   52.926206] Bluetooth: HCI UART protocol Broadcom registered
[   55.286671] Bluetooth: BNEP (Ethernet Emulation) ver 1.3
[   55.286692] Bluetooth: BNEP filters: protocol multicast
[   55.286707] Bluetooth: BNEP socket layer initialized
[   55.291589] Bluetooth: MGMT ver 1.22
[   55.364886] NET: Registered PF_ALG protocol family
[   65.773341] Bluetooth: RFCOMM TTY layer initialized
[   65.773370] Bluetooth: RFCOMM socket layer initialized
[   65.773388] Bluetooth: RFCOMM ver 1.11

### Additional context

The bluetooth device I am using is a wireless 2-in-1 adapter. I use it as a bluetooth signal receiver and connect it to a wired 3.5mm headset (while the receiver connects to pi 4B via bluetooth). My Pi 4B runs 64-bit Raspberry Pi OS based on Bullseye, updated to the latest.

**Comment by popcornmix** [comment]
This repo is for reporting bugs in the linux kernel.
This is almost certainly a higher level OS issue.

Also Bullseye is no longer the current OS install. It will only be getting critical bug fixes in the future.
I'd suggest you test with RPiOS bookworm image.
If there is still a problem then report it here: https://github.com/raspberrypi/bookworm-feedback/issues
