### ISSUE TITLE
Sporadic CIFS errors with 3.1.9-30 kernel

### ISSUE THREAD

**Issue by ph0ng** [raspberrypi/linux#57]
I have been using omxplayer to play video from Windows samba drives on Arch Linux for some time without any problems. Yesterday I did a system upgrade including linux-raspberrypi 3.1.9-28 -> 3.1.9-30. Since then the movie playback has frozen once in each of the two movies I've watched. /var/log/everything.log gives: 

> kernel: CIFS VFS: Send error in read = -512

After this, I cannot unmount (umount: device is busy) and playback can only be resumed after a reboot. 

cifs-utils has not been updated since installation and I believe that the error originates from the kernel update. In addition to the CIFS errors, I have also experienced an unexpected ssh client disconnection (RPI was host).

**Comment by asb** [comment]
Well can you downgrade and confirm the issue disappears? Is 3.1.9-28 a kernel compiled by and distributed by the Arch Linux guys or a kernel from our firmware repository?

**Comment by ph0ng** [comment]
It was compiled yesterday and is distributed by Arch Linux ARM, I did not think about reporting it directly to them. I have downgraded the package and will test for stability in the coming days. However, it is impossible to say that the problem is solved - just that it becomes more and more probable :)

EDIT: Would the correct way be to report to github.com/archlinuxarm and let them report to you if applicable?

**Comment by asb** [comment]
We're happy to help out, it's just it would be useful to know if for instance the kernel config used changed between those two versions. I also don't know which version of the source they correspond to, so it's a little difficult for us to help out. If you can get that information for us we're more likely to be able to assist. It may also be worth trying out the kernel as distributed from github.com/raspberrypi/firmware to see the issue is specific to the Arch Linux Arm kernel

**Comment by xenoxaos** [comment]
The kernel compile pulls the most recent commits from the rpi/linux git repo.  So, it would have been the kernel as of last night maybe...the day before?

EDIT: Actually, it was finished building at:

linux-raspberrypi-3.1.9-30-arm.pkg.tar.xz          17-Jul-2012 04:16 

Give or take an hour MST.

**Comment by ph0ng** [comment]
That matches my kernel timestamp quite well (04:09:57). 

One of the commits between these builds includes changes to the kernel config (don't know if anything is relevant though): https://github.com/archlinuxarm/PKGBUILDs/commit/fe4b037bc3335b9c3d7a183a29d1bcbbc7c089b3

Will put the two movies on repeat tomorrow and see if the problem disappears with linux-raspberrypi-3.1.9-28.

**Comment by ph0ng** [comment]
##### Update

After reverting to kernel 3.1.9-28 I have been playing 1080p video from my CIFS share for more than 8 hours straight with no problems. With the latest Arch kernel build (3.1.9-30) I experienced the problem once per hour on average. The same two movies were used in both setups. Build information for the working setup: 

> Linux **\* 3.1.9-28-ARCH+ #1 PREEMPT Fri Jul 6 23:07:26 UTC 2012 armv6l GNU/Linux

The only difference between the systems is that linux-headers-raspberrypi-3.1.9-28-arm and linux-raspberrypi-3.1.9-28-arm were used instead of *-30. 

So, we have two timestamps for the kernel builds -- will you continue from here or should I report an issue on the Arch repo? I have saved both SD card images and I am happy to assist with further debugging if needed.

**Comment by ph0ng** [comment]
##### Update 2

Eventually the problem showed up on 3.1.9-28 as well, so I guess it was not related to the kernel upgrade after all. Some forum entries suggest setting vm.min_free_kbytes = 8192 in /etc/sysctl.conf and with this setting it seems to be more stable (knock on wood).

**Comment by ph0ng** [comment]
Before closing the issue, perhaps someone can give me a hint on where to continue from here. If the vm.min_free_kbytes setting indeed solves the problem I guess it is distro specific and I should talk to them. Perhaps I should wait and see if the 3.2 kernel is released anytime soon, since some CIFS log messages say that the security mechanism will be updated in 3.2.

**Comment by asb** [comment]
If they're not setting vm.min_free_kbytes in sysctl.conf then they should be - it seems to be required for solid networking on the current kernel (this actually isn't a Raspberry Pi specific issue - Ubuntu for pandaboard and beagleboard ship with that as well to avoid memory allocation errors in the smsc95xx driver).

**Comment by ph0ng** [comment]
I do believe they set vm.min_free_kbytes in the latest packages, it was probably just my ignorance in not merging configuration files after a system upgrade. 

I am still experiencing these issues from time to time and I do not know how to proceed. Perhaps I should cross my fingers and hope that CIFS will work better under the 3.2 kernel. Still, it is bugging me that dmesg fills up with 

> CIFS VFS: Received no data, expecting 4

If you have any additional information on this topic I would be thankful, but then I think it is time to close this issue.

**Comment by ph0ng** [comment]
Turns out that this issue (like many other I assume) was caused by insignificant power. Not outside the foundation's specs, but still not enough for the Ethernet controller.
