### ISSUE TITLE
[ALSA] wrong volume when starting playback

### ISSUE THREAD

**Issue by computer007** [raspberrypi/linux#570]
When I set the global system volume with alsa-lib before running VLC or mpg123, the level is properly modified when looking at alsamixer, but the playback starts with a very high volume, ignoring the one configured with alsa-lib. Once playback has started, calling again alsa-lib to set the volume properly modifies the volume and the displayed volume level (alsamixer).

OS: raspbian
Kernel 3.10.36+ #665 PREEMPT
firmware updated with "rpi-update"
pulse-audio not installled, only ALSA

Result of "modinfo" command:

```
pi@rasp /home/pi/ $ modinfo snd_bcm2835
filename:       /lib/modules/3.10.36+/kernel/sound/arm/snd-bcm2835.ko
alias:          platform:bcm2835_alsa license:        GPL description:
Alsa driver for BCM2835 chip author:         Dom Cobley srcversion:   
0D8794C6E1A26AEFC7F8534 depends:        snd-pcm,snd intree:         Y
vermagic:       3.10.36+ preempt mod_unload modversions ARMv6 parm:   
force_bulk:Force use of vchiq bulk for audio (bool)
```

To reproduce the bug with raspbian:
1) install ALSA headers with: "sudo apt-get install libasound2-dev"
2) have VLC installed (should be the case by default, otherwise "sudo apt-get install vlc")
3) configure ALSA in order it outputs the sound on the jack: "sudo amixer cset numid=3 1 (1 is the jack output)"
4) compile my source code (provided below with makefile) with a simple "make"
5) open 2 SSH consoles in order to monitor the volume level while running the demo code
6) run "alsamixer" in the firt one and set the volume to 100% (in a second attempt you can set it to 10 percents to view that the volume is also ignored whatever the value). Keep alsamixer opened.
7) in the second console, run the compiled program: "./ALSA_test"

Here is what I experience:
1) the volume level moves to 20% in alsamixer (ordered by the call to alsa-lib in the program)
2) VLC starts the playback (french webradio ;)) with a very high volume (the problem is here, whatever the audio source)
3) After 1 minute, the program sets the volume to 21% (you can see that with alsamixer), and the volume becomes low (here the real volume level has been applied)

Here is the code "test-alsa-vlc.c":

```
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <iostream>
#include <signal.h>
#include <pthread.h>
#include <thread>
#include <alsa/asoundlib.h>
#include <cstdint>

// Prototypes
int run_VLC();
void set_alsa_volume(long vol);

// Main function
int main(int argc, const char* argv[])
{
    // Set the initial volume
    set_alsa_volume(-3837); // 20% in alsamixer

    pid_t child_pid = -1;

    // Fork to run VLC in a child process
    if ( (child_pid=fork()) == -1) {
        perror("An error occured during fork");
        exit(EXIT_FAILURE);

    } else if ( child_pid == 0 ) { // Child process
        // Run VLC
        run_VLC();

    } else { // Parent process  
        sleep(60); // Wait for 1 minute

        // Set a volume level higher than the previous
        set_alsa_volume(-3706); // 21% in alsamixer

        sleep(60); // Wait for 1 minute

        // Kill VLC
        if (child_pid != -1) {
            kill(child_pid, SIGTERM);
        }
    }
    return EXIT_SUCCESS;
}

void set_alsa_volume(long vol)
{
    snd_mixer_t *m_handle;
    snd_mixer_elem_t* m_elem;

    // Open an empty mixer
    if (snd_mixer_open(&(m_handle), SND_MIXER_ELEM_SIMPLE) < 0) {
        printf("Error snd_mixer_open");
        return;
    }

    if (snd_mixer_attach(m_handle, "hw:0") < 0) {
        printf("Error snd_mixer_attach");
        return;
    }

    if (snd_mixer_selem_register(m_handle, NULL, NULL) < 0) {
        printf("Error snd_mixer_selem_register");
        return;
    }

    // Load the mixer elements
    if (snd_mixer_load(m_handle) < 0) {
        printf("Error snd_mixer_load");
        return;
    }

    snd_mixer_selem_id_t *simpleElemId; 
    snd_mixer_selem_id_alloca(&simpleElemId);
    snd_mixer_selem_id_set_index(simpleElemId, 0);
    snd_mixer_selem_id_set_name(simpleElemId, "PCM");

    m_elem = snd_mixer_find_selem(m_handle, simpleElemId);
    if (m_elem == NULL) {
        printf("Error snd_mixer_find_selem");
        return;
    }

    // Set the volume
    if (snd_mixer_selem_set_playback_volume_all(m_elem, vol) == 0) {
        std::cout << "ALSA volume level set to " << vol << std::endl;
    }
}


int run_VLC()
{
    // Build the array of arguments
    char * arguments[4] = { "cvlc",
                             "-vvv", // Verbose mode
                             "http://streaming.radio.funradio.fr/fun-1-44-128",
                              NULL
                              };

    if ( execv("/usr/bin/cvlc", const_cast<char * const *>(arguments)) == -1 ) {
        // Should never be printed if execv() is properly executed
        perror("Error in execv() when trying to run VLC");
    }

    return EXIT_FAILURE;
}
```

And the "makefile":

```
# Compiler to use for C++
CC=g++

CFLAGS=-std=c++0x

LIBRARY=-lasound

all: test-alsa-vlc.o
    $(CC) $(CFLAGS) $(LIBRARY) -o ALSA_test $^

test-alsa-vlc.o: test-alsa-vlc.c
    $(CC) $(CFLAGS) -c $< -o $@
```

In the case where it works when launching for the first time, try rebooting, and the bug should occur.

If you need more info, just ask!

Thank you

**Comment by Jeoffreybauvin** [comment]
Same issue here, with my Raspberry Pi model B, and a fresh new Raspbian ;).

**Comment by popcornmix** [comment]
@computer007 
Thanks for the detailed bug report.
I think I have a fix. I'll push it in next firmware update, but if you want to test try:
https://dl.dropboxusercontent.com/u/3669512/temp/start_alsavol.elf

This is a fixed 256M/256M arm/gpu memory split test build. Replace your current start.elf file with it.

**Comment by popcornmix** [comment]
Now in latest rpi-update firmware. Please test.

**Comment by computer007** [comment]
@popcornmix Thank you. I just tried it, and it seems to have solved the bug. I will confirm it after  further tests by the end of the week :)

PS: By curiosity, what caused the bug. I had a look at this file https://github.com/raspberrypi/linux/blob/rpi-patches/sound/arm/bcm2835.c, but I did not notice something special.

**Comment by popcornmix** [comment]
The fix was done on the firmware side.
Basically a volume change occurring before the channel was started was lost (subsequent ones would work okay).

**Comment by computer007** [comment]
Hello,
After further tests I can say that it solved the issue. Thank you again!
