### ISSUE TITLE
please help me rpmbuild: --build-in-place: unknown option

### ISSUE THREAD

**Issue by linke131** [raspberrypi/linux#5707]
### Describe the bug

Use command: make -j$(nproc) binrpm-pkg LOCALVERSION=-bbrplus 2>&1 | tee build.log
build version Linux kernel 6.6.0 Compile and generate rpm package Error

### Steps to reproduce the behaviour

make -j$(nproc) binrpm-pkg LOCALVERSION=-bbrplus.el7.x86_64 2>&1 | tee build.log
  UPD     include/config/kernel.release
  GEN     kernel.spec
rpmbuild -bb kernel.spec --define='_topdir /root/linux-6.6/rpmbuild' --target x86_64-linux --build-in-place --noprep --define='_smp_mflags %{nil}' $(rpm -q rpm
>/dev/null 2>&1 || echo --nodeps) --without devel
rpmbuild: --build-in-place: unknown option
make[2]: *** [binrpm-pkg] Error 1
make[1]: *** [binrpm-pkg] Error 2
make: *** [__sub-make] Error 2

### Device (s)

Other

### System

LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 7.9.2009 (Core)
Release:        7.9.2009
Codename:       Core

Linux 192-46-213-125.ip.linodeusercontent.com 6.5.9-bbrplus.el7.x86_64 #1 SMP PREEMPT_DYNAMIC Sun Oct 29 20:49:50 CST 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by pelwell** [comment]
Although I'd like to think we're a helpful bunch, support for building random packages on a non-Pi OS running on non-Pi hardware is too much of a stretch.
