### ISSUE TITLE
Power Management & Control

### ISSUE THREAD

**Issue by dejannenov** [raspberrypi/linux#571]
Hello,
1. I am looking for the correct way to power on/off the USB ports from the command line. Could you please provide an example?
2. Is there a "low-level  reboot" mechanism, apart form a "sudo reboot", that get the device closer to a true "power cycle" (i.e. power off/on) boot?

**Comment by JamesH65** [comment]
This github is for bug reports, not technical support. You are more likely to get a reply to your questions by posting them to the Raspberry Pi forums, www.raspberrypi.org/forums.
