### ISSUE TITLE
LXC Support

### ISSUE THREAD

**Issue by bullshit** [raspberrypi/linux#572]
Is it possible to include all necessary modules for linux container support?  (Support multiple instances of devpts) VETH was added in #550 . I successful compiled it on the last kernel updates in the 3.10.y branch. It would be nice if it is always on.. 

```
CONFIG_DEVPTS_MULTIPLE_INSTANCES=y
```

**Comment by popcornmix** [comment]
Duplicate of https://github.com/raspberrypi/linux/pull/603
