### ISSUE TITLE
Partial resurce memory updates with vc_dispmanx_resource_write_data()

### ISSUE THREAD

**Issue by vanfanel** [raspberrypi/linux#573]
Hi there

I'm trying to make an optimization to my DispmanX backend for SDL 1.2.x, consisting on partial updates from pixel memory buffer (in RAM) to the video memory. Until now, I used a dispmanx update rect (called bmp_rect) with the same size as the entire screen, but I _think_ I can save a lot of CPU time if I do partial updates instead.

However, I can't get it to work well, and it seems I eventually write out of the resource memory, wich causes the Rpi video to hang.

What SDL 1.2.x does in this function is passing an SDL_Rect array with the areas changed in pixmem (pixel buffer in RAM) since last time. An SDL_Rect is an area description (width, height, x position, y position), the same as a DispmanX rect is.

Here's the small code I came up with, just in case you guys can point me to what could I be doing wrong here:

```
<obsolete>
```

Thanks

**Comment by popcornmix** [comment]
vc_dispmanx_resource_write_data can only take a contiguous block of memory, so rect->x and rect->width are ignored.
I believe a full width rectangle update should be possible.

**Comment by vanfanel** [comment]
Ok, so I've simplified the function upon your advice, popcornmix. I'm simply trying to do a full width rectangle update now.
The function is much simpler now:

```

static void DISPMANX_DirectUpdate(_THIS, int numrects, SDL_Rect *rects)
{    
        /*Partial update version*/

        int i;
        void *src_start;
        for (i = 0; i < numrects; i++){ 
           int src_y = rects[i].y;
           int src_height = rects[i].h;

           src_start = ((char*)dispvars->pixmem) + (src_y * dispvars->pitch);

           vc_dispmanx_rect_set (&(dispvars->bmp_rect), 0, src_y, 0, src_height);    

           vc_dispmanx_resource_write_data (dispvars->resources[flip_page], 
              dispvars->pix_format, dispvars->pitch , src_start, 
              &(dispvars->bmp_rect));

        }   

        dispvars->update = vc_dispmanx_update_start( 0 );

        vc_dispmanx_element_change_source ( dispvars->update,
           dispvars->element, dispvars->resources[flip_page] );

        vc_dispmanx_update_submit_sync ( dispvars->update );

        flip_page = !flip_page;

        return;
}

```

However, it's still not working as expected: if I cause an update down the screen, using my test app, this update is still drawn on the upper part of the screen. 
My understanding of this behaviour is that this call

```
vc_dispmanx_rect_set (&(dispvars->bmp_rect), 0, src_y, 0, src_height);
```

is ignoring the src_y parameter. Coud that be the cause?

**Comment by popcornmix** [comment]
You can check the host side code, e.g.
https://github.com/raspberrypi/userland/blob/master/interface/vmcs_host/vc_vchi_dispmanx.c#L367
vc_dispmanx_rect_set does use the src_y parameter.
I believe src_start should always point at the start of the buffer. Internally it increments by src_y \* pitch.

**Comment by vanfanel** [comment]
Ok, I almost fixed it.
The function looks like this now:

```
static void DISPMANX_DirectUpdate(_THIS, int numrects, SDL_Rect *rects)
{    
        //Partial update version
        int i=0;

        for (i = 0; i < numrects; i++){ 

           int src_y = rects[i].y;
           int src_height = rects[i].h;

           vc_dispmanx_rect_set (&(dispvars->bmp_rect), 0, src_y, 0, src_height);    

           vc_dispmanx_resource_write_data (dispvars->resources[flip_page], 
              dispvars->pix_format, dispvars->pitch, dispvars->pixmem, 
              &(dispvars->bmp_rect));
        }   

        dispvars->update = vc_dispmanx_update_start( 0 );

        vc_dispmanx_element_change_source ( dispvars->update, 
           dispvars->element, dispvars->resources[flip_page] );

        vc_dispmanx_update_submit_sync ( dispvars->update );    

        flip_page = !flip_page;
}
```

However, the mouse cursor in Scummvm, for example, leaves a visible trail
What's happening now is that double-buffering + partial updates is a no-go, or so I think: when partial changes are made to one of the two buffers (the one off-screen in that moment), these changes are made to that buffer and NOT to the other. 
When another set of changes are made to the other buffer, they are made to the second one but not to the first.
So after a while, each buffer has his own set of changes made, different from the changes made to the other buffer, wich desults on these mouse cursor trails and similar problems.
Maybe I'm wrong.. what do you think, popcornmix?

**Comment by popcornmix** [comment]
Well that's a client side choice.

If you have two resources then obviously updating one won't affect the other.
It does sound like you may have to consider the update list of rectangles from the previous frame when updating the current frame. You'll probably want to draw a picture of what's happening.

Note, you seem to updating the "live" buffer in the code pasted above. That is never correct, as you will see tearing. I think the logic may need to be, only update the back buffer, but consider the rectangle list from current and previous frame.

(As an aside, if numrects is large, you may be updating parts of the screen multiple times, and the partial update may be slower than the full update. You may be better off splitting this into two passes, where you build a bitmask of the rows that are dirty in first pass, and then issue the calls to vc_dispmanx_resource_write_data on second pass).

**Comment by vanfanel** [comment]
I have eliminated the second vc_dispmanx_resource_write_data() call from the code above, wich I believe is what you meant when you said I was updating the live buffer. Now I'm not updating the live buffer but just the back one, right? That call was accidentally delft there in my experimentations. 

Keeping track of the changes in past frames sounds like too much added code: in the end, it may be faster simply to dump the whole screen as I've been doing until now.
vc_dispmanx_resource_write_data() is supposed to be pretty fast, isn't it?

**Comment by popcornmix** [comment]
vc_dispmanx_resource_write_data will end up as a memcpy using dma so pretty fast.
You should time a full frame update, and a single pixel row update to see what the difference is.

I imagine the memcpy time may well be comparable to the time taken to send the message, so a single frame update is probably quicker than doing a few single row updates, but you'd need to measure it to be sure.
