### ISSUE TITLE
USB Audio Dropouts

### ISSUE THREAD

**Issue by lnicola** [raspberrypi/linux#575]
Since the new FIQ work, (31a8f3f12c, actually), the audio on my USB DAC is full of crackles.

dmesg: http://pastebin.com/DVjm57k0
lsusb -v: http://pastebin.com/VPQa17hE
vmstat 2 a while before and during playback: http://pastebin.com/5SqwfwR9
/proc/asound/card0/stream0: http://pastebin.com/r0hQijyD

The stream I'm playing is 16-bit at 44.1 kHz. I've also unbound the HID endpoint of the DAC because it made things better at some point. This issue still occurs even if I keep it.

**Comment by ghollingworth** [comment]
Have you tried rpi-update since last night (the new fiq_fsm was pushed to the head branch), this should have been fixed already

**Comment by lnicola** [comment]
Yes, it's the version from the master branch.

**Comment by kursusHC** [comment]
I have the same issue, both with the recent Master branch and the recent Next. 
I'm running Arch up to date  with a Hifimediy Sabre USB DAC ES9023 (CMA options disabled).

When I revert to an old Next commit (April 15th), the problem disappears.

**Comment by P33M** [comment]
I have 3 DACs using different manufacturers of ASIC that do not exhibit this problem.

It would be good to get a minimal set of conditions that cause this to happen. Does this happen with a simple "aplay test.wav" - it would be good to use a sinewave test file or similar:

http://www.audiocheck.net/audiofrequencysignalgenerator_sinetone.php

That webpage will let you generate a sinewave test tone up to 10 seconds long.

Also, is this DAC widely available for purchase in the EU? It would be easier if I just got my hands on one.

**Comment by lnicola** [comment]
Yes, it happens to me with a raw file (aplay -f cd foo.raw). Do you think it would help if I tried with a sine wave and perhaps send you a recording?

I do have some specific settings:  snd-usb-audio.nrpacks=1 and

```
pcm.!default {
        type hw
        card 0
}
```

in asound.conf to prevent the sample rate defaulting to 48000 Hz (I don't remember exactly, but I think it's using plug:hw without it).

My DAC is the one from http://www.amazon.co.uk/Behringer-UCA202-U-Control-low-latency-Interface/dp/B000KW2YEI/ , but note that it's a bit finicky: both Windows and the Raspberry Pi tend to hang when I connect it -- or at least they did when I got it. If I keep it connected during boot it's fine, though.

**Comment by P33M** [comment]
snd_usb_audio.nrpacks now has no effect in 3.12: the URB allocation is now completely automatic.

I have that device (or at least something with the same badge) on my desk. It works fine. It may well be that yours has a different codec inside: I will compare the device I have to see if there are any differences.

Please do send a recording of a sinewave test.

**Comment by andrea-iob** [comment]
I've the same problem. My DAC is a HRT Music Streamer II+. I've the first version of the DAC (http://www.headfonia.com/hrt-music-streamer-ii-2496-usb-dac) the one they are selling now should have just a different case and a different PCB layout (http://www.hirestech.com/product/?pid=128).

I've the latest revision of the DAC firmware. I've also tried with a firmware version specifically designed for use with NAS and similar lower processing power hosts, but the problem remains.

I hear the noise on all the files I play, also with a sinewave test file.

**Comment by lnicola** [comment]
Are you sure that change was in 3.12? I thought the argument was actually removed in 3.13: http://www.raspberrypi.org/forums/viewtopic.php?p=541704#p541704 .

It's too bad that the revision in which this issue appeared contained two changes; I suppose one thing to try would be to see which of those is actually causing it.

Regarding the recording, I don't think I have an audio cable to be able to record it properly. Would using a microphone suffice?

**Comment by P33M** [comment]
My mistake: yes the patch was in the 3.13 release. Even so, altering nrpacks should have no effect since the glitches appear to happen more frequently than the ~10ms URB interval.

If you can get any sort of recording (of a sine test) that is of reasonable quality then it would help.

**Comment by andrea-iob** [comment]
Looking at the 3.12.18 kernel sources I still see the nrpacks parameter being used (see line 82 of https://git.kernel.org/cgit/linux/kernel/git/stable/linux-stable.git/tree/sound/usb/card.c?id=refs/tags/v3.12.18).

However I've tried the "ALSA: improve buffer size computations for USB PCM audio" patch, but I didn't notice any improvements.

**Comment by lnicola** [comment]
It seems that I can't get a decent recording with my laptop microphone :(.

**Comment by andrea-iob** [comment]
I connected the line out of my hi-fi to the mic in of my notebook. Here is the results: "https://www.dropbox.com/s/mz4wkilqj9xtyur/HRT_Music_streamer_Pi_Noise.wav".

Could it be useful to you?

**Comment by lnicola** [comment]
Mine sounds about the same. I noticed, however, that the noise is much more audible with a 20 Hz tone. Perhaps andrea-iob could repeat the test using that?

**Comment by andrea-iob** [comment]
Here is a 20Hz sinewave: "https://www.dropbox.com/s/d6zv4m4jsq9e0mt/HRT_Music_streamer_Pi_Noise_20Hz.wav".

**Comment by lnicola** [comment]
Of course I have a cable, from my DAC to the amplifier. Sorry for the high volume, I can't seem to figure out how to reduce it.

Oh, my: http://i.imgur.com/EGYSFQz.png . Download link: https://www.wetransfer.com/downloads/a1d630b523384d2181aabfdf536afbaa20140429204918/2176f0f73803024943fe56222cd6cd1b20140429204918/e97241

**Comment by P33M** [comment]
(ಠ_ಠ)

Well that puts paid to any theories I have about what's causing this.

If it were reads off the end of the bounce buffers, I would expect there to be a constant value transmitted (the buffers are rewritten with 0x6B on transaction completion). This isn't happening - in fact it appears that random corruption is happening at random times.

**Comment by lnicola** [comment]
Sorry, please consider the file above invalid. I had a "monitor" switch on, which supposedly mixes together the analog and the USB input; weird thing is, recording didn't work without the analog input, even with the switch on.

Anyway, that takes care of the clipping issue. I've also switched to mono recording to take that out of the picture. The waveform still looks bad, though.

Here is a new set: http://i.imgur.com/eckeYK5.png https://www.dropbox.com/s/qt6wlm34uafu9gu/quux.flac .

**Comment by ski522** [comment]
I just upgraded my Pi and my USB PCM2704 is exhibiting similar symptons. To temporarily resolve the issue I lowered my USB ports speed down by adding the "dwc_otg.speed=1" Not ideal as I use my Pi as a NAS, but works for now.  My post about the problem is at the Pi Forum http://www.raspberrypi.org/forums/viewtopic.php?f=63&t=76026&p=543139#p543139

**Comment by lnicola** [comment]
You mention a constant value being transmitted on overruns. However, my source is 16-bit. Is the transfer size a multiple of the sample size? I wonder if the corruption could happen in the middle of a frame or sample.

Now this sounds fun..

```
- /* Bugette: for some reason, memcpy corrupts the data in the bounce buffers. May be a
-  * cache coherency issue */
```

**Comment by kursusHC** [comment]
The device is lost after a few minutes of playback/forward/volume change (just like it was before the huge work on FIQ drivers). But unlike @GrayShade it runs perfectly on all my linux desktops. 

I've tried "dwc_otg.speed=1" but it prevents ALSA from detecting my [DAC](https://github.com/raspberrypi/linux/issues/575#issuecomment-41717228).

Can we provide something to help ?

**Comment by giddyhup** [comment]
I am also running into this and probably related problems. I updated about twelve hours ago. USB sound is crackling, transferring data via WIFI (samba) times out. I get NYET messages related to my bluetooth dongle.  

I updated because I hoped my SDR solution (based on a DVB-T USB stick) would improve, but everything has become worse. I will revert to my backup I created before the update.

lsusb -v http://pastebin.com/LRcq8xva
dmesg (up until WIFI related samba errors) http://pastebin.com/y21Skth5

**Comment by P33M** [comment]
dwc_otg.speed=1 should not be required.

It should be sufficient to disable the FSM: put dwc_otg.fiq_fsm_enable=0 into /boot/cmdline.txt

@all:
How many of you are running overclocked?

**Comment by lnicola** [comment]
I recently overclocked my Pi, however the issue also occurs when running at the normal clock rate.

**Comment by giddyhup** [comment]
I run overclocked. I now disabled the FSM. Sound is back to normal and samba/WIFI throughput is better/without errors. I don't need to revert to my old image after all.

**Comment by ski522** [comment]
Yes dwc_otg.fiq_fsm_enable=0 seemed to fix the problem as well for me.

I am overclocking my Pi at 900MHz.

**Comment by P33M** [comment]
I can replicate this with an overclock.

Edit: I can also replicate this without an overclock.

**Comment by andrea-iob** [comment]
My Pi is not overclocked.

Disabling the FSM does not fix the problem: with some files I still hear some random pops, with other files I hear only noise. The files that with FSM disabled are completely broken are 16/44 files that, for some reasons I don't understand, are played as S24_3LE. 

As reported in the FIQ_FSM forum thread, before the kernel upgrade the files played as S24_3LE were working good whereas the files played as S16_LE where distorted (there were NYET errors). After the kernel upgrade I hear noise on all the files I play.

**Comment by P33M** [comment]
You will get unreliable playback with the FSM disabled. Interrupt latency will mess up audio transfers from time to time. 24-bit audio is particularly vulnerable as you may get what is effectively an endian swap (and thus everything turns into noise) if you lose a frame of data.

**Comment by amtssp** [comment]
Hi I have the same problem (using 3.14.1 kernel) constant crackling noise in my USB audio out.
But If I add dwc_otg.fiq_fsm_mask=0x1 to the cmdline file - the USB-audio is playing without problems.

If I add dwc_otg.fiq_fsm_mask=0x3  ....... I get the crackling noise
If I add dwc_otg.fiq_fsm_mask=0x7  ........I get the crackling noise

My USB adapter is:
[    4.746893] usb 1-1.2: new full-speed USB device number 4 using dwc_otg
[    4.849367] usb 1-1.2: New USB device found, idVendor=0d8c, idProduct=000c
[    4.849403] usb 1-1.2: New USB device strings: Mfr=0, Product=1, SerialNumber=0
[    4.849421] usb 1-1.2: Product: C-Media USB Headphone Set
[    4.862167] input: C-Media USB Headphone Set   as /devices/platform/bcm2708_usb/usb1/1-1/1-1.2/1-1.2:1.3/0003:0D8C:000C.0001/input/input0
[    4.862840] hid-generic 0003:0D8C:000C.0001: input,hidraw0: USB HID v1.00 Device [C-Media USB Headphone Set  ] on usb-bcm2708_usb-1.2/input3

And the new fiq-fsm is enabled:
[    3.522091] OTG VER PARAM: 0, OTG VER FLAG: 0
[    3.522109] Dedicated Tx FIFOs mode
[    3.522357] WARN::dwc_otg_hcd_init:1040: FIQ DMA bounce buffers: virt = 0xdcc27000 dma = 0x5ab94000 len=9024
[    3.522391] FIQ FSM acceleration enabled for :
[    3.522391] Non-periodic Split Transactions
[    3.522411] dwc_otg: Microframe scheduler enabled
[    3.522452] WARN::hcd_init:473: FIQ at 0xc03329d0
[    3.522469] WARN::hcd_init:474: FIQ ASM at 0xc0332c4c length 36
...
[    3.524484] dwc_otg: FIQ enabled
[    3.524502] dwc_otg: NAK holdoff enabled
[    3.524512] dwc_otg: FIQ split-transaction FSM enabled

Hope this info is helpfull

**Comment by P33M** [comment]
It's an issue with cache coherency in the ARM D-Cache. Sometimes lines aren't written out which means that 32 bytes of "old" data sits in the videocore L2 (or system RAM as the case may be). When the USB DMA engine fetches data for transfer, chunks of old 32-byte data get transmitted.

What's interesting is that I'm using the same method that the original driver used to ensure 32-bit transfer alignment (hc->align_buf): this means the failure mode potentially exists there as well.

Currently the only thing that solidly fixes this is turning off the ARM D-Cache, which is not a real solution. dma_sync_\* and friends in the DMA API don't appear to do what they say on the tin, and require further digging.

**Comment by giddyhup** [comment]
One more thing: my LCD keychain display keeps crashing (even though I disabled the driver). This didn't happen with older firmwares.

```
bulk write: Resource temporarily unavailable
bulk write: Resource temporarily unavailable
forked process 18887 for thread exec-f1b2
thread exec-f1b2 starting...
bulk write: Resource temporarily unavailable
forked process 18889 for thread exec-4d14
thread exec-4d14 starting...
thread exec-4b09 starting...
forked process 18891 for thread exec-4b09
thread exec-b24c starting...
forked process 18894 for thread exec-b24c
lcd4linux.c: got signal 15
lcd4linux.c: got signal 15
lcd4linux.c: got signal 15
Timer #0 skipped 1 interval(s) or 1500 ms.
lcd4linux.c: leaving main loop
DPF: shutting down.
drv_dpf.c: closing connection
```

**Comment by P33M** [comment]
The thing that's thrown me is that I did the development work for fiq_fsm on 3.10. The NEXT branch got pushed alongside 3.12 - and in fact the one commit that "broke" everything wasn't to do with my driver at all: it was the rebase to 3.12.

The issue was masked because previously I used the already dma-mapped buffer that the URB submitter provided: assuming that there was some subtle API change, all the mainline device drivers would have been updated in sync. Changing the buffer source had no effect for me on 3.10, but rebasing to 3.12 incorporated $unspecified_change which apparently means the D-cache is no longer flushed on writes to DMA contiguous areas.

It gives me a start and end point for a bisect, at least.

**Comment by P33M** [comment]
I have added `CONFIG_DMA_CMA=y` to .config and rebuilt the kernel. This allows DMA allocations to come from the CMA pool - 16MiB by default.

I no longer get corrupted audio output.

http://lxr.free-electrons.com/source/include/linux/dma-contiguous.h?v=3.12

The side effect is that dma_alloc_coherent() calls all now come from the 16MiB boot-time reserved pool (or per-device CMA pool). It appears that the uses of this in other device drivers of interest are few and far between (and allocate at most 1 page each time).

I see no degradation in performance when running an assortment of additional I/O heavy stuff.

@popcornmix - could you add this option to the defconfig?

**Comment by popcornmix** [comment]
@P33M Does this reduce usable memory to linux by 16M?
Have you tried:
CONFIG_CMA_SIZE_MBYTES=8
(or 4 or 2 or 1?)

**Comment by lnicola** [comment]
Did anything related to CMA change in 3.12? I had to remove my CMA options from config.txt to be able to boot.

I'll test it when the new binaries come out.

**Comment by popcornmix** [comment]
CONFIG_DMA_CMA=y seems to enable other disabled CMA config options, so it's possible adding this will make CMA work.

**Comment by P33M** [comment]
CMA is already enabled (or at least the reservation happens) - therefore 16M is reserved on boot anyway.

Edit: by changing cma=xM in /boot/cmdline.txt, the minimum to boot is 5M.

**Comment by lnicola** [comment]
20 Hz wave looks good. I'll try listening to something a bit later, but I think I'll leave this issue open until @andrea-iob or someone else gets to test it. Any ideas on why some people never had this issue?

Anyway, thanks for your work!

EDIT: Streaming over the network seems to work fine too.

I suppose the memory fragmentation problem reported by milhouse at the beginning of the FIQ_FSM rewrite testing thread will remain, right?

**Comment by P33M** [comment]
Memory fragmentation is orthogonal to this issue. It will always happen with a buddy allocator, and is only a "Problem" because the ARM has to do a relatively large amount of work if it wants to shift pages around to reclaim a contiguous area of memory. The net effect is lowered throughput and higher CPU load with some workloads that particularly fragment memory.

The coherency issue disappears if you get sufficient cache activity such that in the 125uS between a transaction being queued, and the hardware executing it, that all the affected cache lines are written out into main memory. You can make the issue go away by having the Pi do "other stuff" at the same time as playback.

**Comment by andrea-iob** [comment]
No more noise, pops or clicks. The issue seems fixed for me.

Thanks a lot! I really appreciate your hard work!

**Comment by amtssp** [comment]
Also fixed for me after building a new kernel 3.14.1 and update firmware. USB audio is good now.

Thank you..

**Comment by kursusHC** [comment]
Same here after a simple rpi-update. Thanks a lot, I can finally enjoy my Pi !!

**Comment by lnicola** [comment]
Seems fixed, then.

**Comment by ski522** [comment]
Yup...PCM2704 USB DAC is back to normal...thank you for the prompt fix!!

**Comment by giddyhup** [comment]
The recent update from May 1 initially looked like an improvement. Even my USB connected DPF became stable. Yet, with my USB sound dongle some sounds sounded odd or wouldn't play at all. dmesg showed some NYET messages related to the sound card, I had to disable the driver again.

```
[  141.005422] Transfer to device 7 endpoint 0x1 frame 1150 failed - FIQ reported NYET. Data may have been lost.
[  141.325427] Transfer to device 7 endpoint 0x1 frame 1470 failed - FIQ reported NYET. Data may have been lost.
```
