### ISSUE TITLE
Update fuse and ntfs-3g to prevent driver crashes (Transport endpoint is not connected)

### ISSUE THREAD

**Issue by tkafka** [raspberrypi/linux#576]
I am having ntfs drive connected to pi, and after few hours of use the drive disconnects and cd'ing into it ends with 'Transport endpoint is not connected' message.

If you google, you find that this has been fixed in newer fuse (2.9.2+) and ntfs-3g (2014.*), but those packages are very old in raspbian (fuse 2.9.0, ntfs-3g 2012.1).

Replacing fuse and ntfs-3g with the actual versions above fixed the disconnection problems for me.

**Comment by asb** [comment]
I'm afraid this repo is just for issues with the kernel itself. It might be worth reporting this on the raspbian bug tracker or the forums at raspberrypi.org. Ultimately, raspbian follows upstream Debian where possible though, so upstream Debian may be the best place to report this. Closing.

**Comment by tkafka** [comment]
Thanks.
