### ISSUE TITLE
RPi5: Kernel 6.1.0-rpi6-rpi-2712 doesn't work with ARMHF chroot

### ISSUE THREAD

**Issue by free-x** [raspberrypi/linux#5761]
### Describe the bug

I'm trying to build and use ARMHF chroots on RPi5. It fails with "Segmentation  fault"

### Steps to reproduce the behaviour

sudo apt install debootstrap
sudo debootstrap --arch=armhf bookworm /opt/mychroot

If you have Ready-to-use ARMHF Chroot 
sudo chroot /path/to/chrooted-env

### Device (s)

Other

### System

$ cat /etc/rpi-issue 
Raspberry Pi reference 2023-10-10
Generated using pi-gen, https://github.com/RPi-Distro/pi-gen, 962bf483c8f326405794827cce8c0313fd5880a8, stage2

$ vcgencmd version
2023/10/30 16:45:10 
Copyright (c) 2012 Broadcom
version 30de0ba5 (release) (embedded)

$ uname -a
Linux pi5 6.1.0-rpi6-rpi-2712 #1 SMP PREEMPT Debian 1:6.1.58-1+rpt2 (2023-10-27) aarch64 GNU/Linux

### Additional context

$ sudo chroot "/opt/test" /bin/true
/bin/true: error while loading shared libraries: libc.so.6: ELF load command address/offset not page-aligned
$ echo $?
127

$ sudo chroot bookworm-armhf
Segmentation fault

**Comment by popcornmix** [comment]
This is know. e.g. https://github.com/raspberrypi/bookworm-feedback/issues/107
You need to use the 4k pagesize kernel to run 32-bit elf files.
Add `kernel=kernel8.img` to config.txt
