### ISSUE TITLE
3.14.2 - No USB audio dropouts , but no playback at 48000 samplerate

### ISSUE THREAD

**Issue by jactmp** [raspberrypi/linux#577]
Contiuous audio dropouts finally disappeared after upgrade from 3.10.25+ to 3.14.2 - for 32000 and 44100 samplerate. For 48000 - I hear only clicks every few seconds. I'm using PCM2707.

DEVICE:

```
Apr 29 23:19:26 rp kernel: [  384.300654] usb 1-1.2: new full-speed USB device number 7 using dwc_otg
Apr 29 23:19:26 rp kernel: [  384.404327] usb 1-1.2: New USB device found, idVendor=08bb, idProduct=2707
Apr 29 23:19:26 rp kernel: [  384.404361] usb 1-1.2: New USB device strings: Mfr=1, Product=2, SerialNumber=0
Apr 29 23:19:26 rp kernel: [  384.404378] usb 1-1.2: Product: USB Audio DAC
Apr 29 23:19:26 rp kernel: [  384.404393] usb 1-1.2: Manufacturer: Burr-Brown from TI
Apr 29 23:19:26 rp kernel: [  384.415241] ALSA sound/usb/stream.c:710 7:1:1: add audio endpoint 0x2
Apr 29 23:19:26 rp kernel: [  384.415648] ALSA sound/usb/stream.c:710 7:1:2: add audio endpoint 0x2
Apr 29 23:19:26 rp kernel: [  384.416143] ALSA sound/usb/mixer.c:1312 [3] FU [PCM Playback Switch] ch = 1, val = 0/1/1
Apr 29 23:19:26 rp kernel: [  384.419306] ALSA sound/usb/mixer.c:474 cannot set ctl value: req = 0x4, wValue = 0x201, wIndex = 0x300, type = 4, data = 0x80/0x0
Apr 29 23:19:26 rp kernel: [  384.423225] ALSA sound/usb/mixer.c:1312 [3] FU [PCM Playback Volume] ch = 2, val = -32768/0/256
Apr 29 23:19:26 rp kernel: [  384.433274] input: Burr-Brown from TI USB Audio DAC    as /devices/platform/bcm2708_usb/usb1/1-1/1-1.2/1-1.2:1.2/0003:08BB:2707.0003/input/input2
Apr 29 23:19:26 rp kernel: [  384.442802] hid-generic 0003:08BB:2707.0003: input,hidraw0: USB HID v1.00 Device [Burr-Brown from TI USB Audio DAC   ] on usb-bcm2708_usb-1.2/input2
Apr 29 23:19:26 rp mtp-probe: checking bus 1, device 7: "/sys/devices/platform/bcm2708_usb/usb1/1-1/1-1.2"
Apr 29 23:19:26 rp mtp-probe: bus: 1, device: 7 was not an MTP device
```

PLAYBACK:

```
Apr 29 23:23:09 rp kernel: [  607.509482] ALSA sound/usb/pcm.c:490 setting usb interface 1:2
Apr 29 23:23:09 rp kernel: [  607.509520] ALSA sound/usb/endpoint.c:438 Creating new playback data endpoint #2
Apr 29 23:23:09 rp kernel: [  607.509882] ALSA sound/usb/endpoint.c:834 Setting params for ep #2 (type 0, 3 urbs), ret=0
Apr 29 23:23:09 rp kernel: [  607.509909] ALSA sound/usb/pcm.c:229 Starting data EP @dd27e000
Apr 29 23:23:09 rp kernel: [  607.513708] ALSA sound/usb/pcm.c:490 setting usb interface 1:1
Apr 29 23:23:09 rp kernel: [  607.513744] ALSA sound/usb/endpoint.c:438 Creating new playback data endpoint #2
Apr 29 23:23:09 rp kernel: [  607.513938] ALSA sound/usb/endpoint.c:834 Setting params for ep #2 (type 0, 3 urbs), ret=0
Apr 29 23:23:09 rp kernel: [  607.513964] ALSA sound/usb/pcm.c:229 Starting data EP @dd27c000
```

**Comment by P33M** [comment]
Please retest with the latest 3.14 branch. An update has been pushed which may affect this.

**Comment by jactmp** [comment]
Done. Results as follows:
============= 3.14.2+ (latest) =============
$ cat ~/a.raw | aplay -r <any_samplerate> -c 2 -f S16_LE -t raw -
---  harsh sound ...

$ cat ~/a.raw | aplay -r <any_samplerate> -c 2 -f S16_LE -t raw -Dfront -
--- more harsh sound ...

============= 3.14.2 (before latest update) =============
$ cat ~/a.raw | aplay -r 44100 -c 2 -f S16_LE -t raw -Dfront -
.... sound OK ....

$ cat ~/a.raw | aplay -r 44100 -c 2 -f S16_LE -t raw -
$ cat ~/a.raw | aplay -r 48000 -c 2 -f S16_LE -t raw -
$ cat ~/a.raw | aplay -r 48000 -c 2 -f S16_LE -t raw -Dfront -
.... silence +  clicks every few second ...

================ syslog (when playing) =================
May  2 15:30:46 rpi kernel: [  511.479598] ALSA sound/usb/pcm.c:490 setting usb interface 1:1
May  2 15:30:46 rpi kernel: [  511.479676] ALSA sound/usb/endpoint.c:430 Re-using EP 2 in iface 1,1 @ce816000
May  2 15:30:46 rpi kernel: [  511.479902] ALSA sound/usb/endpoint.c:834 Setting params for ep #2 (type 0, 3 urbs), ret=0
May  2 15:30:46 rpi kernel: [  511.479925] ALSA sound/usb/pcm.c:229 Starting data EP @ce81600

================ configuration =================
$ aplay -L
null
    Discard all samples (playback) or generate zero samples (capture)
default:CARD=DAC
    USB Audio DAC, USB Audio
    Default Audio Device
sysdefault:CARD=DAC
    USB Audio DAC, USB Audio
    Default Audio Device
front:CARD=DAC,DEV=0
    USB Audio DAC, USB Audio
    Front speakers
.....

**Comment by jactmp** [comment]
Also tested with different soundcard (C-Media). 3.14.2+ broke sound for this card as well (3.14.2 behaved more less properly - only few clicks every 20-30 seconds).

May  2 15:37:17 rpi kernel: [   78.867313] usb 1-1.2: new full-speed USB device number 7 using dwc_otg
May  2 15:37:17 rpi kernel: [   78.969558] usb 1-1.2: New USB device found, idVendor=0b05, idProduct=1743
May  2 15:37:17 rpi kernel: [   78.969620] usb 1-1.2: New USB device strings: Mfr=3, Product=1, SerialNumber=0
May  2 15:37:17 rpi kernel: [   78.969642] usb 1-1.2: Product: USB Advanced Audio Device
May  2 15:37:17 rpi kernel: [   78.969657] usb 1-1.2: Manufacturer: C-Media Electronics Inc.
May  2 15:37:17 rpi kernel: [   79.017807] input: C-Media Electronics Inc. USB Advanced Audio Device as /devices/platform/bcm2708_usb/usb1/1-1/1-1.2/1-1.2:1.3/0003:0B05:1743.0003/input/input2
May  2 15:37:17 rpi kernel: [   79.018691] hid-generic 0003:0B05:1743.0003: input,hidraw0: USB HID v1.00 Device [C-Media Electronics Inc. USB Advanced Audio Device] on usb-bcm2708_usb-1.2/input3
May  2 15:37:17 rpi mtp-probe: checking bus 1, device 7: "/sys/devices/platform/bcm2708_usb/usb1/1-1/1-1.2"
May  2 15:37:17 rpi mtp-probe: bus: 1, device: 7 was not an MTP device
May  2 15:37:20 rpi kernel: [   81.447768] usb 1-1.2: USB disconnect, device number 7
May  2 15:37:20 rpi kernel: [   81.767457] usb 1-1.2: new full-speed USB device number 8 using dwc_otg
May  2 15:37:20 rpi kernel: [   81.869571] usb 1-1.2: New USB device found, idVendor=0b05, idProduct=1743
May  2 15:37:20 rpi kernel: [   81.869636] usb 1-1.2: New USB device strings: Mfr=3, Product=1, SerialNumber=0
May  2 15:37:20 rpi kernel: [   81.869656] usb 1-1.2: Product: USB Advanced Audio Device
May  2 15:37:20 rpi kernel: [   81.869672] usb 1-1.2: Manufacturer: C-Media Electronics Inc.
May  2 15:37:20 rpi kernel: [   81.909109] input: C-Media Electronics Inc. USB Advanced Audio Device as /devices/platform/bcm2708_usb/usb1/1-1/1-1.2/1-1.2:1.3/0003:0B05:1743.0004/input/input3
May  2 15:37:20 rpi kernel: [   81.911174] hid-generic 0003:0B05:1743.0004: input,hidraw0: USB HID v1.00 Device [C-Media Electronics Inc. USB Advanced Audio Device] on usb-bcm2708_usb-1.2/input3
May  2 15:37:20 rpi mtp-probe: checking bus 1, device 8: "/sys/devices/platform/bcm2708_usb/usb1/1-1/1-1.2"

**Comment by P33M** [comment]
Can you define "harsh"?

Do these devices work on 3.12?

**Comment by jactmp** [comment]
"Explanation" below:
https://www.dropbox.com/s/gd76p5l26cj358i/recording20140502154830.wav

Generally they work more less properly with 3.10.y  and 3.12.y. More less means - that clicks once in a while ( lost frames on USB ?). 
Drops disappeaead when (again - more less) after adding  dwc_otg.microframe_schedule=1 dwc_otg.speed=1 to cmdline.txt (I was forced to add it to resolve problem with Broadcom bluetooth dongle - which dropped data sent trough rfcomm to external android device). 
The problem was solved finally in 3.14.2, but only for 44100.

**Comment by Ruffio** [comment]
@ytpl has this issue been resolved? If yes, then please close this issue.

**Comment by jactmp** [comment]
I can't check it - my RPi is broken. Should I close it anyway?

2016-08-10 13:05 GMT+02:00 Rasmus Christiansen notifications@github.com:

**Comment by Ruffio** [comment]
@ytpl Currently used version is 4.4.x so a lot has happened and since no one else has reported of this not working, I think yes.
