### ISSUE TITLE
USB 3.0 external HDD adpter not working 

### ISSUE THREAD

**Issue by paracetamolo** [raspberrypi/linux#578]
This [Orico](http://www.amazon.fr/ORICO-Stations-daccueil-externes-alimentation/dp/B00BLED24K/ref=sr_1_3?ie=UTF8&qid=1398844624&sr=8-3&keywords=orico) sata-usb3.0 adapter is recognized by the pi, I can mount and use the disk for a while. After some time dmesg if flooded with messages like:

```
 EXT4-fs warning (device sda1): __ext4_read_dirblock:681: error reading directory block (ino 128843780, block 0)
```

interleaved sometimes by

```
lost page write due to I/O error on sda1
```

Additional info: 
- The pi was updated, including firmware

```
$ /opt/vc/bin/vcgencmd version
Apr 28 2014 22:03:25 
Copyright (c) 2012 Broadcom
version ae8e2629010287f876403e09360a80e6d51cb4aa (clean) (release)
$ uname -a
Linux lampona 3.12.18+ #677 PREEMPT Mon Apr 28 22:45:00 BST 2014 armv6l GNU/Linux
```
- The disk is a big 3TB Western Digital. 
- The adapter is self-powered. 
- The pi is powered by a 1A cell phone charger. 
- The software causing the errors was CrashPlan backup server, written in Java, running with oracle java 1.8. 
  I can provide more info and complete logs if necessary.

I solved the problem with the option `dwc_otg.speed=1`.

**Comment by P33M** [comment]
Has the device ever worked successfully for an extended period on any version of the firmware?

**Comment by paracetamolo** [comment]
I don't think so, everytime  time I tried the errors would appear within a few hours. Anyway since I used `dwc_otg.speed=1` everything has worked well for 2 days with the backup running.

I added the current kernel and firmware versions to the report.

**Comment by P33M** [comment]
Please post complete logs.

In addition, have you ever tried swapping the USB cable?

**Comment by alvarogzp** [comment]
Same problem here, using Seagate Expansion 4TB HDD, also USB3.0.
The drive works really bad, spending tens of seconds to do an "ls" on a normal directory. And failing with IO error some minutes after plugging in.

There are also messages like this in syslog:

<pre>usb 1-1.3: device not accepting address 5, error -110
usb 1-1.3: reset high-speed USB device number 5 using dwc_otg</pre>

UPDATE:
Using a USB 2.0 cable solves the issue, the drive works well, only this message appears in syslog from time to time:

<pre>usb 1-1.2: reset high-speed USB device number 4 using dwc_otg</pre>

I paste complete syslog with 2 tries: first with USB 2.0 cable (between 70 and 371 seconds elapsed from boot) and then with USB 3.0 cable (from 382 elapsed seconds until end):

<pre>[    0.000000] Booting Linux on physical CPU 0x0
[    0.000000] Initializing cgroup subsys cpu
[    0.000000] Initializing cgroup subsys cpuacct
[    0.000000] Linux version 3.12.22+ (dc4@dc4-arm-01) (gcc version 4.7.2 20120731 (prerelease) (crosstool-NG linaro-1.13.1+bzr2458 - Linaro GCC 2012.08) ) #691 PREEMPT Wed Jun 18 18:29:58 BST 2014
[    0.000000] CPU: ARMv6-compatible processor [410fb767] revision 7 (ARMv7), cr=00c5387d
[    0.000000] CPU: PIPT / VIPT nonaliasing data cache, VIPT nonaliasing instruction cache
[    0.000000] Machine: BCM2708
[    0.000000] cma: CMA: reserved 8 MiB at 1b800000
[    0.000000] Memory policy: ECC disabled, Data cache writeback
[    0.000000] On node 0 totalpages: 114688
[    0.000000] free_area_init_node: node 0, pgdat c05fcdf0, node_mem_map c06ae000
[    0.000000]   Normal zone: 896 pages used for memmap
[    0.000000]   Normal zone: 0 pages reserved
[    0.000000]   Normal zone: 114688 pages, LIFO batch:31
[    0.000000] pcpu-alloc: s0 r0 d32768 u32768 alloc=1*32768
[    0.000000] pcpu-alloc: [0] 0 
[    0.000000] Built 1 zonelists in Zone order, mobility grouping on.  Total pages: 113792
[    0.000000] Kernel command line: dma.dmachans=0x7f35 bcm2708_fb.fbwidth=656 bcm2708_fb.fbheight=416 bcm2708.boardrev=0xe bcm2708.serial=0x589ddeb8 smsc95xx.macaddr=B8:27:EB:9D:DE:B8 sdhci-bcm2708.emmc_clock_freq=250000000 vc_mem.mem_base=0x1ec00000 vc_mem.mem_size=0x20000000  dwc_otg.lpm_enable=0 console=ttyAMA0,115200 kgdboc=ttyAMA0,115200 console=tty1 root=/dev/mmcblk0p2 rootfstype=ext4 elevator=deadline rootwait
[    0.000000] PID hash table entries: 2048 (order: 1, 8192 bytes)
[    0.000000] Dentry cache hash table entries: 65536 (order: 6, 262144 bytes)
[    0.000000] Inode-cache hash table entries: 32768 (order: 5, 131072 bytes)
[    0.000000] Memory: 439664K/458752K available (4376K kernel code, 238K rwdata, 1340K rodata, 143K init, 701K bss, 19088K reserved)
[    0.000000] Virtual kernel memory layout:
[    0.000000]     vector  : 0xffff0000 - 0xffff1000   (   4 kB)
[    0.000000]     fixmap  : 0xfff00000 - 0xfffe0000   ( 896 kB)
[    0.000000]     vmalloc : 0xdc800000 - 0xff000000   ( 552 MB)
[    0.000000]     lowmem  : 0xc0000000 - 0xdc000000   ( 448 MB)
[    0.000000]     modules : 0xbf000000 - 0xc0000000   (  16 MB)
[    0.000000]       .text : 0xc0008000 - 0xc059d54c   (5718 kB)
[    0.000000]       .init : 0xc059e000 - 0xc05c1ee4   ( 144 kB)
[    0.000000]       .data : 0xc05c2000 - 0xc05fd900   ( 239 kB)
[    0.000000]        .bss : 0xc05fd90c - 0xc06ad0f8   ( 702 kB)
[    0.000000] SLUB: HWalign=32, Order=0-3, MinObjects=0, CPUs=1, Nodes=1
[    0.000000] Preemptible hierarchical RCU implementation.
[    0.000000] NR_IRQS:394
[    0.000000] sched_clock: 32 bits at 1000kHz, resolution 1000ns, wraps every 4294967ms
[    0.000000] Switching to timer-based delay loop
[    0.000000] Console: colour dummy device 80x30
[    0.000000] console [tty1] enabled
[    0.001272] Calibrating delay loop (skipped), value calculated using timer frequency.. 2.00 BogoMIPS (lpj=10000)
[    0.001334] pid_max: default: 32768 minimum: 301
[    0.001830] Mount-cache hash table entries: 512
[    0.002663] Initializing cgroup subsys memory
[    0.002772] Initializing cgroup subsys devices
[    0.002811] Initializing cgroup subsys freezer
[    0.002844] Initializing cgroup subsys blkio
[    0.002985] CPU: Testing write buffer coherency: ok
[    0.003444] Setting up static identity map for 0xc0427670 - 0xc04276cc
[    0.005366] devtmpfs: initialized
[    0.022139] VFP support v0.3: implementor 41 architecture 1 part 20 variant b rev 5
[    0.023723] NET: Registered protocol family 16
[    0.029110] DMA: preallocated 4096 KiB pool for atomic coherent allocations
[    0.029792] cpuidle: using governor ladder
[    0.029837] cpuidle: using governor menu
[    0.030469] bcm2708.uart_clock = 0
[    0.032296] hw-breakpoint: found 6 breakpoint and 1 watchpoint registers.
[    0.032352] hw-breakpoint: maximum watchpoint size is 4 bytes.
[    0.032390] mailbox: Broadcom VideoCore Mailbox driver
[    0.032490] bcm2708_vcio: mailbox at f200b880
[    0.032598] bcm_power: Broadcom power driver
[    0.032636] bcm_power_open() -> 0
[    0.032662] bcm_power_request(0, 8)
[    0.533391] bcm_mailbox_read -> 00000080, 0
[    0.533430] bcm_power_request -> 0
[    0.533661] Serial: AMBA PL011 UART driver
[    0.533832] dev:f1: ttyAMA0 at MMIO 0x20201000 (irq = 83, base_baud = 0) is a PL011 rev3
[    0.893976] console [ttyAMA0] enabled
[    0.920883] bio: create slab <bio-0> at 0
[    0.926395] SCSI subsystem initialized
[    0.930394] usbcore: registered new interface driver usbfs
[    0.936096] usbcore: registered new interface driver hub
[    0.941654] usbcore: registered new device driver usb
[    0.948311] Switched to clocksource stc
[    0.952571] FS-Cache: Loaded
[    0.955728] CacheFiles: Loaded
[    0.971442] NET: Registered protocol family 2
[    0.976942] TCP established hash table entries: 4096 (order: 3, 32768 bytes)
[    0.984348] TCP bind hash table entries: 4096 (order: 2, 16384 bytes)
[    0.990920] TCP: Hash tables configured (established 4096 bind 4096)
[    0.997370] TCP: reno registered
[    1.000667] UDP hash table entries: 256 (order: 0, 4096 bytes)
[    1.006538] UDP-Lite hash table entries: 256 (order: 0, 4096 bytes)
[    1.013299] NET: Registered protocol family 1
[    1.018229] RPC: Registered named UNIX socket transport module.
[    1.024285] RPC: Registered udp transport module.
[    1.029043] RPC: Registered tcp transport module.
[    1.033764] RPC: Registered tcp NFSv4.1 backchannel transport module.
[    1.041168] bcm2708_dma: DMA manager at f2007000
[    1.045910] bcm2708_gpio: bcm2708_gpio_probe c05cfed0
[    1.051474] vc-mem: phys_addr:0x00000000 mem_base=0x1ec00000 mem_size:0x20000000(512 MiB)
[    1.061085] audit: initializing netlink socket (disabled)
[    1.066587] type=2000 audit(0.910:1): initialized
[    1.232784] VFS: Disk quotas dquot_6.5.2
[    1.237054] Dquot-cache hash table entries: 1024 (order 0, 4096 bytes)
[    1.246045] FS-Cache: Netfs 'nfs' registered for caching
[    1.253006] NFS: Registering the id_resolver key type
[    1.258165] Key type id_resolver registered
[    1.262481] Key type id_legacy registered
[    1.267250] msgmni has been set to 874
[    1.273060] Block layer SCSI generic (bsg) driver version 0.4 loaded (major 252)
[    1.280919] io scheduler noop registered
[    1.284873] io scheduler deadline registered (default)
[    1.290470] io scheduler cfq registered
[    1.295636] BCM2708FB: allocated DMA memory 5bc00000
[    1.300819] BCM2708FB: allocated DMA channel 0 @ f2007000
[    1.320254] Console: switching to colour frame buffer device 82x26
[    1.330378] uart-pl011 dev:f1: no DMA platform data
[    1.336710] kgdb: Registered I/O driver kgdboc.
[    1.343374] vc-cma: Videocore CMA driver
[    1.348720] vc-cma: vc_cma_base      = 0x00000000
[    1.354700] vc-cma: vc_cma_size      = 0x00000000 (0 MiB)
[    1.361429] vc-cma: vc_cma_initial   = 0x00000000 (0 MiB)
[    1.377410] brd: module loaded
[    1.387069] loop: module loaded
[    1.391801] vchiq: vchiq_init_state: slot_zero = 0xdb800000, is_master = 0
[    1.400941] Loading iSCSI transport class v2.0-870.
[    1.408292] usbcore: registered new interface driver smsc95xx
[    1.415872] dwc_otg: version 3.00a 10-AUG-2012 (platform bus)
[    1.623171] Core Release: 2.80a
[    1.627580] Setting default values for core params
[    1.633661] Finished setting default values for core params
[    1.840543] Using Buffer DMA mode
[    1.845102] Periodic Transfer Interrupt Enhancement - disabled
[    1.852205] Multiprocessor Interrupt Enhancement - disabled
[    1.859060] OTG VER PARAM: 0, OTG VER FLAG: 0
[    1.864681] Dedicated Tx FIFOs mode
[    1.869769] WARN::dwc_otg_hcd_init:1042: FIQ DMA bounce buffers: virt = 0xdbc14000 dma = 0x5bc14000 len=9024
[    1.882216] FIQ FSM acceleration enabled for :
[    1.882216] Non-periodic Split Transactions
[    1.882216] Periodic Split Transactions
[    1.882216] High-Speed Isochronous Endpoints
[    1.904102] dwc_otg: Microframe scheduler enabled
[    1.904200] WARN::hcd_init:473: FIQ at 0xc03080cc
[    1.910314] WARN::hcd_init:474: FIQ ASM at 0xc0308348 length 36
[    1.917606] WARN::hcd_init:500: MPHI regs_base at 0xdc806000
[    1.924632] dwc_otg bcm2708_usb: DWC OTG Controller
[    1.930896] dwc_otg bcm2708_usb: new USB bus registered, assigned bus number 1
[    1.939551] dwc_otg bcm2708_usb: irq 32, io mem 0x00000000
[    1.946377] Init: Port Power? op_state=1
[    1.951615] Init: Power Port (0)
[    1.956375] usb usb1: New USB device found, idVendor=1d6b, idProduct=0002
[    1.964549] usb usb1: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[    1.973127] usb usb1: Product: DWC OTG Controller
[    1.979162] usb usb1: Manufacturer: Linux 3.12.22+ dwc_otg_hcd
[    1.986281] usb usb1: SerialNumber: bcm2708_usb
[    1.992950] hub 1-0:1.0: USB hub found
[    1.998093] hub 1-0:1.0: 1 port detected
[    2.003796] dwc_otg: FIQ enabled
[    2.003813] dwc_otg: NAK holdoff enabled
[    2.003823] dwc_otg: FIQ split-transaction FSM enabled
[    2.003843] Module dwc_common_port init
[    2.004276] usbcore: registered new interface driver usb-storage
[    2.012013] mousedev: PS/2 mouse device common for all mice
[    2.019597] bcm2835-cpufreq: min=700000 max=700000 cur=700000
[    2.026700] bcm2835-cpufreq: switching to governor powersave
[    2.033702] bcm2835-cpufreq: switching to governor powersave
[    2.040756] sdhci: Secure Digital Host Controller Interface driver
[    2.048186] sdhci: Copyright(c) Pierre Ossman
[    2.053879] sdhci: Enable low-latency mode
[    2.098559] mmc0: SDHCI controller on BCM2708_Arasan [platform] using platform's DMA
[    2.109129] mmc0: BCM2708 SDHC host at 0x20300000 DMA 2 IRQ 77
[    2.116380] sdhci-pltfm: SDHCI platform and OF driver helper
[    2.123553] ledtrig-cpu: registered to indicate activity on CPUs
[    2.133198] hidraw: raw HID events driver (C) Jiri Kosina
[    2.147554] usbcore: registered new interface driver usbhid
[    2.154643] usbhid: USB HID core driver
[    2.164546] TCP: cubic registered
[    2.171338] Initializing XFRM netlink socket
[    2.179093] NET: Registered protocol family 17
[    2.185124] Key type dns_resolver registered
[    2.198562] Indeed it is in host mode hprt0 = 00021501
[    2.208563] registered taskstats version 1
[    2.219018] Waiting for root device /dev/mmcblk0p2...
[    2.310573] mmc0: read SD Status register (SSR) after 5 attempts
[    2.325440] mmc0: new high speed SDHC card at address 1234
[    2.333102] mmcblk0: mmc0:1234 SA08G 7.42 GiB 
[    2.340746]  mmcblk0: p1 p2
[    2.428429] usb 1-1: new high-speed USB device number 2 using dwc_otg
[    2.436490] Indeed it is in host mode hprt0 = 00001101
[    2.638708] usb 1-1: New USB device found, idVendor=0424, idProduct=9514
[    2.646877] usb 1-1: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[    2.656230] hub 1-1:1.0: USB hub found
[    2.661533] hub 1-1:1.0: 5 ports detected
[    2.772968] EXT4-fs (mmcblk0p2): mounted filesystem with ordered data mode. Opts: (null)
[    2.783940] VFS: Mounted root (ext4 filesystem) on device 179:2.
[    2.792727] devtmpfs: mounted
[    2.797593] Freeing unused kernel memory: 140K (c059e000 - c05c1000)
[    2.938605] usb 1-1.1: new high-speed USB device number 3 using dwc_otg
[    3.058833] usb 1-1.1: New USB device found, idVendor=0424, idProduct=ec00
[    3.067585] usb 1-1.1: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[    3.080910] smsc95xx v1.0.4
[    3.143294] smsc95xx 1-1.1:1.0 eth0: register 'smsc95xx' at usb-bcm2708_usb-1.1, smsc95xx USB 2.0 Ethernet, b8:27:eb:9d:de:b8
[    4.341476] udevd[156]: starting version 175
[    6.489432] bcm2708-i2s bcm2708-i2s.0: Failed to create debugfs directory
[   11.862896] EXT4-fs (mmcblk0p2): re-mounted. Opts: (null)
[   12.335024] EXT4-fs (mmcblk0p2): re-mounted. Opts: (null)
[   18.030997] FAT-fs (mmcblk0p1): Volume was not properly unmounted. Some data may be corrupt. Please run fsck.
[   21.244930] smsc95xx 1-1.1:1.0 eth0: hardware isn't capable of remote wakeup
[   22.848679] smsc95xx 1-1.1:1.0 eth0: link up, 100Mbps, full-duplex, lpa 0x45E1
[   70.419608] usb 1-1.2: new high-speed USB device number 4 using dwc_otg
[   70.561872] usb 1-1.2: New USB device found, idVendor=0bc2, idProduct=3320
[   70.561903] usb 1-1.2: New USB device strings: Mfr=2, Product=3, SerialNumber=1
[   70.561919] usb 1-1.2: Product: Expansion Desk
[   70.561932] usb 1-1.2: Manufacturer: Seagate
[   70.561949] usb 1-1.2: SerialNumber: NA4LRAR3
[   70.568313] usb-storage 1-1.2:1.0: USB Mass Storage device detected
[   70.578856] scsi0 : usb-storage 1-1.2:1.0
[   71.580808] scsi 0:0:0:0: Direct-Access     Seagate  Expansion Desk   0711 PQ: 0 ANSI: 6
[   71.585900] sd 0:0:0:0: [sda] Spinning up disk...
[   71.640493] sd 0:0:0:0: Attached scsi generic sg0 type 0
[   72.589500] ..........ready
[   81.680617] sd 0:0:0:0: [sda] 976754645 4096-byte logical blocks: (4.00 TB/3.63 TiB)
[   81.692511] sd 0:0:0:0: [sda] Write Protect is off
[   81.692552] sd 0:0:0:0: [sda] Mode Sense: 4f 00 00 00
[   81.693302] sd 0:0:0:0: [sda] Write cache: enabled, read cache: enabled, doesn't support DPO or FUA
[   81.697675] sd 0:0:0:0: [sda] 976754645 4096-byte logical blocks: (4.00 TB/3.63 TiB)
[   81.775925]  sda: sda1
[   81.785782] sd 0:0:0:0: [sda] 976754645 4096-byte logical blocks: (4.00 TB/3.63 TiB)
[   81.787400] sd 0:0:0:0: [sda] Attached SCSI disk
[  131.373083] EXT4-fs (sda1): mounted filesystem with ordered data mode. Opts: (null)
[  239.313738] usb 1-1.2: reset high-speed USB device number 4 using dwc_otg
[  371.244789] usb 1-1.2: USB disconnect, device number 4
[  371.255983] sd 0:0:0:0: [sda] Synchronizing SCSI cache
[  371.256254] sd 0:0:0:0: [sda]  
[  371.256274] Result: hostbyte=0x01 driverbyte=0x00
[  382.227214] usb 1-1.3: new high-speed USB device number 5 using dwc_otg
[  382.369504] usb 1-1.3: New USB device found, idVendor=0bc2, idProduct=3320
[  382.369536] usb 1-1.3: New USB device strings: Mfr=2, Product=3, SerialNumber=1
[  382.369552] usb 1-1.3: Product: Expansion Desk
[  382.369565] usb 1-1.3: Manufacturer: Seagate
[  382.369579] usb 1-1.3: SerialNumber: NA4LRAR3
[  382.376353] usb-storage 1-1.3:1.0: USB Mass Storage device detected
[  382.382861] scsi1 : usb-storage 1-1.3:1.0
[  383.378375] scsi 1:0:0:0: Direct-Access     Seagate  Expansion Desk   0711 PQ: 0 ANSI: 6
[  383.382197] sd 1:0:0:0: Attached scsi generic sg0 type 0
[  383.384742] sd 1:0:0:0: [sda] Spinning up disk...
[  384.387103] .........ready
[  392.468185] sd 1:0:0:0: [sda] 976754645 4096-byte logical blocks: (4.00 TB/3.63 TiB)
[  392.479236] sd 1:0:0:0: [sda] Write Protect is off
[  392.479311] sd 1:0:0:0: [sda] Mode Sense: 4f 00 00 00
[  392.480079] sd 1:0:0:0: [sda] Write cache: enabled, read cache: enabled, doesn't support DPO or FUA
[  392.484358] sd 1:0:0:0: [sda] 976754645 4096-byte logical blocks: (4.00 TB/3.63 TiB)
[  423.278222] usb 1-1.3: reset high-speed USB device number 5 using dwc_otg
[  423.464127]  sda: sda1
[  423.471640] sd 1:0:0:0: [sda] 976754645 4096-byte logical blocks: (4.00 TB/3.63 TiB)
[  423.473191] sd 1:0:0:0: [sda] Attached SCSI disk
[  431.258420] usb 1-1.3: reset high-speed USB device number 5 using dwc_otg
[  441.778530] usb 1-1.3: device not accepting address 5, error -110
[  441.858685] usb 1-1.3: reset high-speed USB device number 5 using dwc_otg
[  473.279459] usb 1-1.3: reset high-speed USB device number 5 using dwc_otg
[  483.799572] usb 1-1.3: device not accepting address 5, error -110
[  483.879727] usb 1-1.3: reset high-speed USB device number 5 using dwc_otg
[  498.960067] usb 1-1.3: device descriptor read/64, error -110
[  571.281847] usb 1-1.3: reset high-speed USB device number 5 using dwc_otg
[  576.421916] usb 1-1.3: device descriptor read/all, error -110
[  576.501966] usb 1-1.3: reset high-speed USB device number 5 using dwc_otg
[  607.282719] usb 1-1.3: reset high-speed USB device number 5 using dwc_otg
[  638.323456] usb 1-1.3: reset high-speed USB device number 5 using dwc_otg
[  669.284224] usb 1-1.3: reset high-speed USB device number 5 using dwc_otg
[  670.310484] EXT4-fs (sda1): mounted filesystem with ordered data mode. Opts: (null)
[  761.286456] usb 1-1.3: reset high-speed USB device number 5 using dwc_otg
[  771.806571] usb 1-1.3: device not accepting address 5, error -110
[  771.886715] usb 1-1.3: reset high-speed USB device number 5 using dwc_otg
[  782.406833] usb 1-1.3: device not accepting address 5, error -110
[  782.486989] usb 1-1.3: reset high-speed USB device number 5 using dwc_otg
[  839.288377] usb 1-1.3: reset high-speed USB device number 5 using dwc_otg
[  854.368762] usb 1-1.3: device descriptor read/64, error -110
[  896.289753] usb 1-1.3: reset high-speed USB device number 5 using dwc_otg
[  906.809873] usb 1-1.3: device not accepting address 5, error -110
[  906.890026] usb 1-1.3: reset high-speed USB device number 5 using dwc_otg
[  917.410122] usb 1-1.3: device not accepting address 5, error -110
[  917.490276] usb 1-1.3: reset high-speed USB device number 5 using dwc_otg
[  922.530357] usb 1-1.3: device descriptor read/8, error -110
[  927.660481] usb 1-1.3: device descriptor read/8, error -110
[  927.850524] usb 1-1.3: reset high-speed USB device number 5 using dwc_otg
[  938.270631] usb 1-1.3: device not accepting address 5, error -110
[  938.271205] usb 1-1.3: USB disconnect, device number 5
[  938.271637] sd 1:0:0:0: Device offlined - not ready after error recovery
[  938.281971] sd 1:0:0:0: [sda] Unhandled error code
[  938.282008] sd 1:0:0:0: [sda]  
[  938.282023] Result: hostbyte=0x01 driverbyte=0x00
[  938.282036] sd 1:0:0:0: [sda] CDB: 
[  938.282046] cdb[0]=0x28: 28 00 05 70 21 29 00 00 01 00
[  938.282090] end_request: I/O error, dev sda, sector 729876808
[  938.282448] EXT4-fs warning (device sda1): __ext4_read_dirblock:908: error reading directory block (ino 22806874, block 0)
[  938.286321] sd 1:0:0:0: [sda] Synchronizing SCSI cache
[  938.286674] sd 1:0:0:0: [sda]  
[  938.286697] Result: hostbyte=0x01 driverbyte=0x00
[  938.380807] usb 1-1.3: new high-speed USB device number 6 using dwc_otg
[  944.707744] EXT4-fs warning (device sda1): __ext4_read_dirblock:908: error reading directory block (ino 22806874, block 0)
[  948.699216] EXT4-fs warning (device sda1): __ext4_read_dirblock:908: error reading directory block (ino 22806874, block 0)
[  948.704536] EXT4-fs warning (device sda1): __ext4_read_dirblock:908: error reading directory block (ino 22806874, block 0)
[  948.745090] EXT4-fs warning (device sda1): __ext4_read_dirblock:908: error reading directory block (ino 22806874, block 0)
[  948.756789] EXT4-fs warning (device sda1): __ext4_read_dirblock:908: error reading directory block (ino 22806874, block 0)
[  948.901058] usb 1-1.3: device not accepting address 6, error -110
[  948.981248] usb 1-1.3: new high-speed USB device number 7 using dwc_otg
[  952.569691] EXT4-fs warning (device sda1): __ext4_read_dirblock:908: error reading directory block (ino 22806874, block 0)
[  952.583648] EXT4-fs warning (device sda1): __ext4_read_dirblock:908: error reading directory block (ino 22806874, block 0)
[  952.597099] EXT4-fs warning (device sda1): __ext4_read_dirblock:908: error reading directory block (ino 22806874, block 0)
[  952.611521] EXT4-fs warning (device sda1): __ext4_read_dirblock:908: error reading directory block (ino 22806874, block 0)
[  953.345561] EXT4-fs warning (device sda1): __ext4_read_dirblock:908: error reading directory block (ino 22806874, block 0)
[  953.359024] EXT4-fs warning (device sda1): __ext4_read_dirblock:908: error reading directory block (ino 22806874, block 0)
[  953.372981] EXT4-fs warning (device sda1): __ext4_read_dirblock:908: error reading directory block (ino 22806874, block 0)
[  953.386844] EXT4-fs warning (device sda1): __ext4_read_dirblock:908: error reading directory block (ino 22806874, block 0)
[  953.768446] EXT4-fs warning (device sda1): __ext4_read_dirblock:908: error reading directory block (ino 22806874, block 0)
[  953.782406] EXT4-fs warning (device sda1): __ext4_read_dirblock:908: error reading directory block (ino 22806874, block 0)
[  953.790779] EXT4-fs warning (device sda1): __ext4_read_dirblock:908: error reading directory block (ino 22806874, block 0)
[  953.805489] EXT4-fs warning (device sda1): __ext4_read_dirblock:908: error reading directory block (ino 22806874, block 0)
[  954.023609] EXT4-fs error (device sda1): ext4_find_entry:1309: inode #22806874: comm pv: reading directory lblock 0
[  957.187899] EXT4-fs warning (device sda1): __ext4_read_dirblock:908: error reading directory block (ino 21495809, block 0)
[  959.501636] usb 1-1.3: device not accepting address 7, error -110
[  959.581765] usb 1-1.3: new high-speed USB device number 8 using dwc_otg
[  959.624203] usb 1-1.3: New USB device found, idVendor=0bc2, idProduct=3320
[  959.624235] usb 1-1.3: New USB device strings: Mfr=2, Product=3, SerialNumber=1
[  959.624251] usb 1-1.3: Product: Expansion Desk
[  959.624265] usb 1-1.3: Manufacturer: Seagate
[  959.624278] usb 1-1.3: SerialNumber: NA4LRAR3
[  959.630391] usb-storage 1-1.3:1.0: USB Mass Storage device detected
[  959.636884] scsi2 : usb-storage 1-1.3:1.0
[  991.293420] usb 1-1.3: reset high-speed USB device number 8 using dwc_otg
[  991.443983] scsi 2:0:0:0: Direct-Access     Seagate  Expansion Desk   0711 PQ: 0 ANSI: 6
[  991.447788] sd 2:0:0:0: Attached scsi generic sg0 type 0
[  991.450256] sd 2:0:0:0: [sda] 976754645 4096-byte logical blocks: (4.00 TB/3.63 TiB)
[  991.451067] sd 2:0:0:0: [sda] Write Protect is off
[  991.451100] sd 2:0:0:0: [sda] Mode Sense: 4f 00 00 00
[  991.451875] sd 2:0:0:0: [sda] Write cache: enabled, read cache: enabled, doesn't support DPO or FUA
[  991.456298] sd 2:0:0:0: [sda] 976754645 4096-byte logical blocks: (4.00 TB/3.63 TiB)
[  991.732771]  sda: sda1
[ 1022.275052] usb 1-1.3: reset high-speed USB device number 8 using dwc_otg
[ 1022.426894] sd 2:0:0:0: [sda] 976754645 4096-byte logical blocks: (4.00 TB/3.63 TiB)
[ 1022.436970] sd 2:0:0:0: [sda] Attached SCSI disk
[ 1053.296608] usb 1-1.3: reset high-speed USB device number 8 using dwc_otg
[ 1084.338400] usb 1-1.3: reset high-speed USB device number 8 using dwc_otg</pre>

Why is there such a difference between using a USB 3.0 cable and a USB 2.0 one? If the raspberry only supports USB 2.0, the connectors used are the same for both.

**Comment by Ruffio** [comment]
@paracetamolo has this issue been resolved? If yes, then please close this issue.

**Comment by Ruffio** [comment]
@paracetamolo has this issue been resolved? If yes, then please close this issue.
