### ISSUE TITLE
handle_hc_chhltd_intr_dma: Channel 1, DMA Mode -- ChHltd set, but reason for halting is unknown

### ISSUE THREAD

**Issue by ns** [raspberrypi/linux#579]
errors:
https://gist.github.com/ns/80c811d0ebed00d05064

lsusb -v:
https://gist.github.com/ns/95b1d901e70a7b8a6a6f

/boot/cmdline.txt:
https://gist.github.com/ns/ce62b242dbb339d215ac

/boot/config.txt:
https://gist.github.com/ns/b2b7e99ba2517f065c72

/var/log/messages:
https://gist.github.com/ns/c62d5ebf1dcd3c3240f6

uname -a
Linux box 3.12.18+ #677 PREEMPT Mon Apr 28 22:45:00 BST 2014 armv6l GNU/Linux

What I've seen --

Prior to NEXT branch being merged into master all usb devices would stop working after 6-7 hours (and dwc_otg.speed=1 didn't help). After using the next branch I was able to have usb devices freeze up after 5-10 min (tried all the fsm masks). With dwc_otg.speed=1 the system seems to be running for a few days but with tons of errors logged.

USB hub is an powered Belkin F4U040V, approved on http://elinux.org/RPi_Powered_USB_Hubs.

Let me know if anything else would be helpful.

**Comment by ns** [comment]
More information, tested with the following /boot/cmdline.txt and the usb devices froze after 10 minutes.

"Transfer to device 8 endpoint 0x1 frame 178 failed - FIQ reported NYET. Data may have been lost."

/boot/cmdline.txt:
https://gist.github.com/ns/85f7472707b709a616a9

/var/log/messages:
https://gist.github.com/ns/3fb52352537e2a94d5a4

**Comment by P33M** [comment]
You have a single TT hub with 4 full-speed devices connected.

While everything shouldn't grind to a halt just because you have this configuration, you are not going to get reliable performance to any of those devices as the dwc_otg hardware limitations will mean the FIQ aborts transfers as it runs out of bandwidth.

If you are running with dwc_otg.speed=1 then fiq_fsm has practically no effect as it is only nominated for USB2.0->USB1.1 split transactions and USB2.0 isochronous transactions.

Can you replicate the problem with only one of the full-speed devices attached to the hub?

**Comment by ns** [comment]
I don't believe I can replicate the problem with only one USB device plugged in. Am testing now and will report back. Looking into single TT / multi TT, this could be an issue (didn't know about it before).

**Comment by ns** [comment]
Left it running for a day. I can't reproduce the issue with 3 usb devices plugged in, but can with 4.

I found a multi TT usb hub (F4U041v vC1) and tried that as well. It does get rid of the repeated handle_hc_chhltd_intr_dma errors, but replaces them with "Transfer to device 7 endpoint 0x1 frame 1312 failed - FIQ reported NYET. Data may have been lost." and an eventual system crash, so there may be another issue at play.

Tested the multi TT usb hub with the following cmdline.txt:
https://gist.github.com/ns/75f3f3cfb9a353a29c8e

Errors:
https://gist.github.com/ns/92a8554fa9fed0815712

**Comment by P33M** [comment]
Are you sure it's a multi-tt hub?

Post a full lsusb -v with the hub plugged in.

**Comment by ns** [comment]
Quite possible I missed something.

Here's lsusb -v:
https://gist.github.com/ns/33bf08d015508d350e9d

Also, I listed the incorrect usb hub above as being multi-tt. I'm actually using D-Link DUB-H7.

**Comment by ns** [comment]
@P33M Let me know if there's anything else I can do. Would this be more relevant posted under raspberrypi/firmware?

**Comment by Ruffio** [comment]
@ns has this issue been resolved? If yes, then please close this issue.
