### ISSUE TITLE
FTDI interface not working with Scratch and PicoBoard

### ISSUE THREAD

**Issue by cshirky** [raspberrypi/linux#58]
This issue shows up with Scratch and the Picoboard on Raspbian. I am not sure how general it is.

I have a PicoBoard plugged directly into the Pi (and a keyboard and mouse running through a powered hub.) When I boot into Debian 'squeeze', Scratch instantly recognizes the board, the Scratch sensor watcher reports values, and scripts relying on the board work properly.

When I shutdown, swap out the SD card, and boot into Raspbian 'wheezy' with the identical physical setup, Scratch does not recognize the Pico Board, the sensor watcher reports only 0 values, and Picoboard reliant scripts don't run.

Under Raspbian, dmesg reports recognizing an FTDI device on a USB hub:

[    9.475632] usbcore: registered new interface driver usbserial
[    9.646934] USB Serial support registered for generic
[    9.914046] usbcore: registered new interface driver usbserial_generic
[   10.370135] usbserial: USB Serial Driver core
[   10.815102] USB Serial support registered for FTDI USB Serial Device
[   11.107379] ftdi_sio 1-1.2:1.0: FTDI USB Serial Device converter detected
[   11.277210] usb 1-1.2: Detected FT232RL
[   11.386922] usb 1-1.2: Number of endpoints 2
[   11.496964] usb 1-1.2: Endpoint 1 MaxPacketSize 64
[   11.586897] usb 1-1.2: Endpoint 2 MaxPacketSize 64
[   11.662464] usb 1-1.2: Setting MaxPacketSize 64
[   11.731847] usb 1-1.2: FTDI USB Serial Device converter now attached to ttyUSB0
[   11.769734] usbcore: registered new interface driver ftdi_sio
[   11.790153] ftdi_sio: v1.6.0:USB FTDI Serial Converters Driver

Running 'sudo modprobe ftdi_sio', as per this earlier thread about the Picoboard (http://www.raspberrypi.org/phpBB3/viewtopic.php?f=47&t=5327&p=73828&hilit=picoboard#p73828) produces no change in the recognition of FTDI devices.

**Comment by asb** [comment]
Could you try running Scratch as root in case this is a permissions issue? e.g. `gksudo scratch`

**Comment by cshirky** [comment]
It's not permissions, but when I started Scratch a second time, not as
root, I tried Scratch's 'Select serial/USB port' option. I was only given
the option of /dev/ttyUSB0, selected that, and it worked.

dmesg reported the Picoboard appearing on ttyUSB0 before I ran scratch

[   11.731847] usb 1-1.2: FTDI USB Serial Device converter now attached to ttyUSB0

but it worked without being selected from within Scratch in Debian 'squeeze', but not in Raspbian 'wheezy'

**Comment by P33M** [comment]
Closing as 2 years old: there's been a zillion updates to both Scratch and the kernel. There are no known issues with FTDI serial devices.
