### ISSUE TITLE
Include hso driver (Option-branded GSM modem) in default Raspbian kernel configuration?

### ISSUE THREAD

**Issue by ghost** [raspberrypi/linux#580]
Hi,

(Apologies in advance if this is the wrong place to file this; there are a couple Raspbian threads that seem to indicate that the Raspberry Pi foundation is building the distribution's kernel.)

The 2004-01 Raspbian image currently ships a kernel configuration in which the `hso` kernel driver is disabled (both in-kernel and as a module). A number of other GSM modem drivers for other manufacturers' devices (e.g. `option.ko`) are included as modules, but using `hso` currently seems to require that I download and rebuild the kernel with a modified `.config` file.

Is there some specific reason this driver isn't shipped? It's in the mainline kernel and appears to work well now that I've rebuilt the kernel.

**Comment by popcornmix** [comment]
To confirm, you would like CONFIG_USB_HSO=m added to default kernel config?

**Comment by ghost** [comment]
Correct; we've been using the serial interface exposed by the driver (`/dev/ttyHS0`) and AT commands to programmatically send SMS/text messages using the USB-connected HSDPA adapter. I haven't tested the network interface, but can confirm that the serial interface (major 248, minor 0) is functional. Thanks so much for the quick reply.

**Comment by popcornmix** [comment]
Okay, no objections to adding that - will be in next firmware update.

**Comment by ghost** [comment]
Fantastic, thank you.

**Comment by popcornmix** [comment]
Firmware is updated. Please run rpi-update and confirm module is as expected.

**Comment by ghost** [comment]
Updated to 1e98ba5db72d5edceebd05c5e264945ca190b0ec (3.12.18+) and everything works as expected. Thanks again!
