### ISSUE TITLE
Default behaviour i2c-1 - 0x3B - UU

### ISSUE THREAD

**Issue by richard-tx** [raspberrypi/linux#581]
I recently upgraded (May, 1 2014) to the latest firmware.  Since that time i2c-1 address 0x3b is now been taken over by the OS.   Is this a bug?  If intentional, then how do I remove the reserved device?

i2cdetect -y 1
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- --
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
30: -- -- -- -- -- -- -- -- -- -- -- UU -- -- -- --
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
70: -- -- -- -- -- -- -- --

**Comment by popcornmix** [comment]
You need to blacklist the module. Run lsmod to see a list of modules it might be.
Try adding any unwanted modules to this file. E.g.

```
cat /etc/modprobe.d/raspi-blacklist.conf 
# blacklist spi and i2c by default (many users don't need them)
blacklist spi-bcm2708
blacklist i2c-bcm2708
blacklist snd-soc-bcm2708-i2s
```

**Comment by richard-tx** [comment]
I added blacklist snd_soc_wm8804 to the blacklist file.  It fixed the reserved address issue as well as as the mpd/mpc/no audio  issue.

I think that module should be blacklisted by default or not included in the standard distribution.

Richard

**Comment by richard-tx** [comment]
One more thing that blacklisting that module does is solve an issue where there is a 10-15 second delay between the time a logname is given at logon and the password prompt appears.  Something very strange is happening with that module that it affects the entire system.

**Comment by ghost** [comment]
@richard-tx yup it worked with me. http://www.raspberrypi.org/forums/viewtopic.php?f=44&t=31420&p=612513#p612513

**Comment by Ruffio** [comment]
@richard-tx has this issue been resolved? If yes, then please close this issue.

**Comment by richard-tx** [comment]
I am closing this due to age.
