### ISSUE TITLE
No audio output after reboot. 

### ISSUE THREAD

**Issue by richard-tx** [raspberrypi/linux#582]
I recently upgraded (May, 1 2014) to the latest firmware.  Since that time upon reboot audio output does not occur using mpd.  Despite the fact that mpd reports it is playing the audio stream, If I  tell mpd  to stop and then start, then audio output occurs.  This is not normal behaviour.

**Comment by popcornmix** [comment]
When it is playing, but silent, can you run alsamixer and see if changing volume fixes it?

**Comment by richard-tx** [comment]
Playing with alsamixer did not fix it.  What did fix it was adding the following to the blacklist.

blacklist snd_soc_wm8804

It also fixed the reserved  0x3b i2c address issue too.

My recommendation is to:

1 -  blacklist the module
or
2 - Do not include that module in the official release.

**Comment by popcornmix** [comment]
Yes, those audio modules are a menace. The next raspbian image will blacklist them all.
I'd prefer them to not auto-probe, but only probe when the module is explicitly loaded, but I've not found the best way to achieve that.

**Comment by Ruffio** [comment]
@richard-tx has this issue been resolved? If yes, then please close this issue.

**Comment by richard-tx** [comment]
Dead issue.
