### ISSUE TITLE
[PI5][6.6.9] dtparams: eth_led0/1 not supported

### ISSUE THREAD

**Issue by klslz** [raspberrypi/linux#5834]
### Describe the bug

For the RPI 3 and 4  families the dtparams eth_led0 and eth_led1 allowed to manage the behaviour of these LEDs.
The RPI3/4 related dtparams do not work on the PI5.
There's no such support listed for RPi5 in the ./overlays/README

Is this feature already available and the documentation is not reflecting it? 
Is this feature not yet implemented ?
Can it be expected sooner or later ?

### Steps to reproduce the behaviour

###disable ethernet port LEDs
dtparam=eth_led0=4
dtparam=eth_led1=4

### Device (s)

Other

### System

OS RPIOS Bookworm - latest
kernel 6.6.9 - commit: 5007002bb
FW 2023/12/14 16:43:25 

### Logs

NA

### Additional context

NA

**Comment by pelwell** [comment]
This was fixed in the rpi-6.1.y branch last week, and is now in the rpi-6.6.y and rpi-6.7.y branches as well.

**Comment by klslz** [comment]
Just tested it on 6.6. Confirmed - it's working! Case closed!

Great job. THX
