### ISSUE TITLE
Do not rebase the rpi-3.12.y branch

### ISSUE THREAD

**Issue by yann-morin-1998** [raspberrypi/linux#584]
Hello!
Since you've now declared rpi-3.12.y to be the new stable [0], this is now used by automatic builders such as Buildroot. To get reproducible builds, Buildroot uses a sha1 (often the HEAD when we test it) in that rpi-3.12.y branch (we previously did so with the previous stable, rpi-3.10.y).

It worked so far with rpi-3.10.y, because you were merging linux-stable into the rpi-3.10.y branch. But now, with rpi-3.12.y, you are rebasing the branch onto the linux-stable branch. This means that it is no longer possible to use a sha1, and we have to use the branch name. This is not good, as we can not get reproducible builds.

Would it be possible that you revert to merging linux-stable in rpi-3.12.y, instead of rebasing, please?

Thanks! :-)

Regards,
Yann E. MORIN.

[0] http://www.raspberrypi.org/forums/viewtopic.php?f=29&t=75895

**Comment by popcornmix** [comment]
Yes, the plan is to only merge the stable repo, but to rebase the future ones.

**Comment by popcornmix** [comment]
3.12.y has just been updated to 3.12.19 with a merge.
