### ISSUE TITLE
3.14.1 and CONFIG_DMA_CMA results in I2S-DAC problems

### ISSUE THREAD

**Issue by amtssp** [raspberrypi/linux#585]
Hi after building 3.14.1 kernel with the new CONFIG_DMA_CMA enabled, the USB sound is very good. I have build a microcore linux audio player - and everything is working fine with the new kernel option except the I2S - DACs. Also the firmware is updated to the newest version.

It crashes when I try to load the two I2S hifiberry (DAC or DIGI) or the IQaudio modules.

If I do:
sudo modprobe -q snd_soc_iqaudio_dac
It crashes momentarily.

Unable to handle kernel paging request at virtual address ea3fa9e4
pgd = c3e90000
[ea3fa9e4] *pgd=00000000
Internal error: Oops: 5 [#1] PREEMPT ARM
and it continues .......

**Comment by P33M** [comment]
Can you post a picture of the screen console after it has crashed?

**Comment by amtssp** [comment]
Ok here is a photo of  the errors

![20140503_134509](https://cloud.githubusercontent.com/assets/6228518/2870272/b3a736de-d2b9-11e3-943d-f28902ce9671.jpg)

**Comment by P33M** [comment]
Um. Works for me?

`Linux raspberrypi 3.14.2+ #167 PREEMPT Sat May 3 17:34:37 BST 2014 armv6l GNU/Linux`

```
[    6.737984] bcm2708-i2s bcm2708-i2s.0: Failed to create debugfs directory
[   10.426435] EXT4-fs (mmcblk0p2): re-mounted. Opts: (null)
[   10.928057] EXT4-fs (mmcblk0p2): re-mounted. Opts: (null)
[   11.884117] bcm2708_i2c_init_pinmode(0,0)
[   11.889499] bcm2708_i2c_init_pinmode(0,1)
[   11.899544] bcm2708_i2c bcm2708_i2c.0: BSC0 Controller at 0x20205000 (irq 79) (baudrate 100k)
[   11.911182] bcm2708_i2c_init_pinmode(1,2)
[   11.916477] bcm2708_i2c_init_pinmode(1,3)
[   11.925758] bcm2708_i2c bcm2708_i2c.1: BSC1 Controller at 0x20804000 (irq 79) (baudrate 100k)
[   12.070283] pcm512x 1-004c: No SCLK, using BCLK: -2
[   12.100970] pcm512x 1-004c: Completed initialisation - pcm512x_probe
[   12.469640] snd-rpi-iqaudio-dac snd-rpi-iqaudio-dac.0: pcm512x-hifi <-> bcm2708-i2s.0 mapping ok
```

I have an IQaudio device attached to the I2S port, and the following in /etc/modules:

```
# /etc/modules: kernel modules to load at boot time.
#
# This file contains the names of kernel modules that should be loaded
# at boot time, one per line. Lines beginning with "#" are ignored.
# Parameters can be specified after the module name.

snd-bcm2835
i2c-bcm2708
snd-soc-bcm2708
snd-soc-bcm2708-i2s
bcm2708-dmaengine
snd-soc-pcm512x
snd-soc-iqaudio-dac
```

**Comment by amtssp** [comment]
OK- thank you very much for trying this out. 

I must have made an error somewhere. So let me close this one..  
Sorry for taking your time
