### ISSUE TITLE
kernel bug & panic with LVM Mirroring  ubs2 sticks with 3.11.x and up

### ISSUE THREAD

**Issue by hvenzke** [raspberrypi/linux#587]
bastard1:~# uname -a
Linux bastard1 3.11.4-1-raspberrypi #1 PREEMPT Fri Oct 11 00:02:13 UTC 2013 (f1558bf) armv6l armv6l armv6l GNU/Linux

extened usb2 with  belkin 7 hub , ( 3500mA )
Attached 2x usb2 sticks, sandisk Cruzer Glide  64G 

root@bastard1:~$ pvs
  PV             VG      Fmt  Attr PSize  PFree
  /dev/mmcblk0p4 data    lvm2 a--   6.69g   2.69g
  /dev/sda1      nagios4 lvm2 a--  59.62g 480.00m

When i mIrror  any LV ( size don´t matter ), the system breakup with kernel dump.
kernel logs not written  to file  yet .
Trying to capture it still i have no cam here  at moment.
( any ideas to force kernel log dumps to disk ? )

its reproduceable anytime at current.

@popcornmix   and others  any seen sutch behavior on  3.12 or 3.14 kernels ?

**Comment by popcornmix** [comment]
Not aware of an issue like this. Will need to see the kernel backtrace.

**Comment by hvenzke** [comment]
one loks like this:

i´ll gather more at weekend ...

getting strange issues with ext4.

<pre>
[    0.000000] Booting Linux on physical CPU 0x0
[    0.000000] Initializing cgroup subsys cpu
[    0.000000] Initializing cgroup subsys cpuacct
[    0.000000] Linux version 3.11.4-1-raspberrypi (geeko@buildhost) (gcc version 4.8.1 20130909 [gcc-4_8-branch revision 202388] (SUSE Linux) ) #1 PREEMPT Fri Oct 11 00:02:13 UTC 2013 (f1558bf)
[    0.000000] CPU: ARMv6-compatible processor [410fb767] revision 7 (ARMv7), cr=00c5387d
[    0.000000] CPU: PIPT / VIPT nonaliasing data cache, VIPT nonaliasing instruction cache
[    0.000000] Machine: BCM2708
[    0.000000] cma: CMA: reserved 16 MiB at 1b000000
[    0.000000] Memory policy: ECC disabled, Data cache writeback
[    0.000000] On node 0 totalpages: 114688
[    0.000000] free_area_init_node: node 0, pgdat c06d4068, node_mem_map c0783000
[    0.000000]   Normal zone: 896 pages used for memmap
[    0.000000]   Normal zone: 0 pages reserved
[    0.000000]   Normal zone: 114688 pages, LIFO batch:31
[    0.000000] pcpu-alloc: s0 r0 d32768 u32768 alloc=1*32768
[    0.000000] pcpu-alloc: [0] 0
[    0.000000] Built 1 zonelists in Zone order, mobility grouping on.  Total pages: 113792
[    0.000000] Kernel command line: dma.dmachans=0x7f35 bcm2708_fb.fbwidth=1920 bcm2708_fb.fbheight=1080 bcm2708.boardrev=0xe bcm2708.serial=0x4515e625 smsc95xx.macaddr=B8:27:EB:15:E6:25 sdhci-bcm2708.emmc_clock_freq=100000000 vc_mem.mem_base=0x1ec00000 vc_mem.mem_size=0x20000000  dwc_otg.lpm_enable=0 smsc95xx.turbo_mode=N selinux=0 plymouth.enable=0  console=ttyAMA0,115200 kgdboc=ttyAMA0,115200 console=tty1 root=/dev/mmcblk0p3 rootfstype=ext2 elevator=noop rootwait rw
[    0.000000] PID hash table entries: 2048 (order: 1, 8192 bytes)
[    0.000000] Dentry cache hash table entries: 65536 (order: 6, 262144 bytes)
[    0.000000] Inode-cache hash table entries: 32768 (order: 5, 131072 bytes)
[    0.000000] Memory: 430604K/458752K available (5083K kernel code, 226K rwdata, 1508K rodata, 139K init, 697K bss, 28148K reserved)
[    0.000000] Virtual kernel memory layout:
    vector  : 0xffff0000 - 0xffff1000   (   4 kB)
    fixmap  : 0xfff00000 - 0xfffe0000   ( 896 kB)
    vmalloc : 0xdc800000 - 0xff000000   ( 552 MB)
    lowmem  : 0xc0000000 - 0xdc000000   ( 448 MB)
    modules : 0xbf000000 - 0xc0000000   (  16 MB)
      .text : 0xc0008000 - 0xc067812c   (6593 kB)
      .init : 0xc0679000 - 0xc069bfac   ( 140 kB)
      .data : 0xc069c000 - 0xc06d4960   ( 227 kB)
       .bss : 0xc06d4960 - 0xc0782e08   ( 698 kB)
[    0.000000] Preemptible hierarchical RCU implementation.
[    0.000000] NR_IRQS:330
[    0.000000] sched_clock: 32 bits at 1000kHz, resolution 1000ns, wraps every 4294967ms
[    0.000000] Switching to timer-based delay loop
[    0.000000] Console: colour dummy device 80x30
[    0.000000] console [tty1] enabled
[    0.001196] Calibrating delay loop (skipped), value calculated using timer frequency.. 2.00 BogoMIPS (lpj=10000)
[    0.001256] pid_max: default: 32768 minimum: 301
[    0.001600] Mount-cache hash table entries: 512
[    0.002382] Initializing cgroup subsys devices
[    0.002437] Initializing cgroup subsys freezer
[    0.002469] Initializing cgroup subsys blkio
[    0.002557] CPU: Testing write buffer coherency: ok
[    0.003021] Setting up static identity map for 0xc04d7c98 - 0xc04d7cf4
[    0.004944] devtmpfs: initialized
[    0.016578] xor: measuring software checksum speed
[    0.110253]    arm4regs  :   973.600 MB/sec
[    0.210291]    8regs     :   470.800 MB/sec
[    0.310370]    32regs    :   470.800 MB/sec
[    0.310406] xor: using function: arm4regs (973.600 MB/sec)
[    0.312465] NET: Registered protocol family 16
[    0.318470] DMA: preallocated 4096 KiB pool for atomic coherent allocations
[    0.319676] bcm2708.uart_clock = 0
[    0.321200] hw-breakpoint: found 6 breakpoint and 1 watchpoint registers.
[    0.321254] hw-breakpoint: maximum watchpoint size is 4 bytes.
[    0.321288] mailbox: Broadcom VideoCore Mailbox driver
[    0.321382] bcm2708_vcio: mailbox at f200b880
[    0.321482] bcm_power: Broadcom power driver
[    0.321519] bcm_power_open() -> 0
[    0.321544] bcm_power_request(0, 8)
[    0.822225] bcm_mailbox_read -> 00000080, 0
[    0.822263] bcm_power_request -> 0
[    0.822288] Serial: AMBA PL011 UART driver
[    0.822426] dev:f1: ttyAMA0 at MMIO 0x20201000 (irq = 83) is a PL011 rev3
[    1.181734] console [ttyAMA0] enabled
[    1.206074] bio: create slab <bio-0> at 0
[    1.373127] raid6: int32x1     46 MB/s
[    1.542420] raid6: int32x2     70 MB/s
[    1.713211] raid6: int32x4     91 MB/s
[    1.883234] raid6: int32x8     99 MB/s
[    1.887005] raid6: using algorithm int32x8 (99 MB/s)
[    1.891977] raid6: using intx1 recovery algorithm
[    1.897318] SCSI subsystem initialized
[    1.901404] usbcore: registered new interface driver usbfs
[    1.907043] usbcore: registered new interface driver hub
[    1.912650] usbcore: registered new device driver usb
[    1.919347] Switched to clocksource stc
[    1.923522] FS-Cache: Loaded
[    1.926666] CacheFiles: Loaded
[    1.941980] NET: Registered protocol family 2
[    1.947310] TCP established hash table entries: 4096 (order: 3, 32768 bytes)
[    1.954585] TCP bind hash table entries: 4096 (order: 2, 16384 bytes)
[    1.961162] TCP: Hash tables configured (established 4096 bind 4096)
[    1.967601] TCP: reno registered
[    1.970893] UDP hash table entries: 256 (order: 0, 4096 bytes)
[    1.976761] UDP-Lite hash table entries: 256 (order: 0, 4096 bytes)
[    1.983380] NET: Registered protocol family 1
[    1.988291] RPC: Registered named UNIX socket transport module.
[    1.994339] RPC: Registered udp transport module.
[    1.999061] RPC: Registered tcp transport module.
[    2.003807] RPC: Registered tcp NFSv4.1 backchannel transport module.
[    2.011091] bcm2708_dma: DMA manager at f2007000
[    2.015819] bcm2708_gpio: bcm2708_gpio_probe c06a9d30
[    2.021358] vc-mem: phys_addr:0x00000000 mem_base=0x1ec00000 mem_size:0x20000000(512 MiB)
[    2.029937] major device number 252
[    2.029958] vma list size 12, page list size 2008, page size 4096
[    2.029975] allocated dma channel 2 (f2007200), initial state 00000008
[    2.029984] post-reset 00000008
[    2.030855] audit: initializing netlink socket (disabled)
[    2.036335] type=2000 audit(1.870:1): initialized
[    2.200378] VFS: Disk quotas dquot_6.5.2
[    2.204414] Dquot-cache hash table entries: 1024 (order 0, 4096 bytes)
[    2.211513] FS-Cache: Netfs 'nfs' registered for caching
[    2.217263] NFS: Registering the id_resolver key type
[    2.222554] Key type id_resolver registered
[    2.226759] Key type id_legacy registered
[    2.231528] bio: create slab <bio-1> at 1
[    2.236126] Btrfs loaded
[    2.238812] msgmni has been set to 873
[    2.245411] Block layer SCSI generic (bsg) driver version 0.4 loaded (major 251)
[    2.253248] io scheduler noop registered (default)
[    2.258070] io scheduler deadline registered
[    2.262504] io scheduler cfq registered
[    2.267773] BCM2708FB: allocated DMA memory 5b400000
[    2.272896] BCM2708FB: allocated DMA channel 0 @ f2007000
[    2.311794] Console: switching to colour frame buffer device 240x67
[    2.334610] kgdb: Registered I/O driver kgdboc.
[    2.339979] vc-cma: Videocore CMA driver
[    2.344000] vc-cma: vc_cma_base      = 0x00000000
[    2.348787] vc-cma: vc_cma_size      = 0x00000000 (0 MiB)
[    2.354348] vc-cma: vc_cma_initial   = 0x00000000 (0 MiB)
[    2.369639] brd: module loaded
[    2.378156] loop: module loaded
[    2.381762] vchiq: vchiq_init_state: slot_zero = 0xdb000000, is_master = 0
[    2.389926] Loading iSCSI transport class v2.0-870.
[    2.395976] usbcore: registered new interface driver ax88179_178a
[    2.402670] usbcore: registered new interface driver smsc95xx
[    2.408625] dwc_otg: version 3.00a 10-AUG-2012 (platform bus)
[    2.614699] Core Release: 2.80a
[    2.617938] Setting default values for core params
[    2.622934] Finished setting default values for core params
[    2.828712] Using Buffer DMA mode
[    2.832146] Periodic Transfer Interrupt Enhancement - disabled
[    2.838087] Multiprocessor Interrupt Enhancement - disabled
[    2.843789] OTG VER PARAM: 0, OTG VER FLAG: 0
[    2.848237] Dedicated Tx FIFOs mode
[    2.852372] dwc_otg: Microframe scheduler enabled
[    2.852592] dwc_otg bcm2708_usb: DWC OTG Controller
[    2.857627] dwc_otg bcm2708_usb: new USB bus registered, assigned bus number 1
[    2.865088] dwc_otg bcm2708_usb: irq 32, io mem 0x00000000
[    2.870804] Init: Port Power? op_state=1
[    2.874809] Init: Power Port (0)
[    2.878206] usb usb1: New USB device found, idVendor=1d6b, idProduct=0002
[    2.885170] usb usb1: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[    2.892559] usb usb1: Product: DWC OTG Controller
[    2.897357] usb usb1: Manufacturer: Linux 3.11.4-1-raspberrypi dwc_otg_hcd
[    2.904384] usb usb1: SerialNumber: bcm2708_usb
[    2.909929] hub 1-0:1.0: USB hub found
[    2.913809] hub 1-0:1.0: 1 port detected
[    2.923016] dwc_otg: FIQ enabled
[    2.923037] dwc_otg: NAK holdoff enabled
[    2.923047] dwc_otg: FIQ split fix enabled
[    2.923067] Module dwc_common_port init
[    2.923530] usbcore: registered new interface driver usb-storage
[    2.934795] mousedev: PS/2 mouse device common for all mice
[    2.945859] bcm2835-cpufreq: min=700000 max=700000 cur=700000
[    2.956592] bcm2835-cpufreq: switching to governor performance
[    2.967196] bcm2835-cpufreq: switching to governor performance
[    2.977752] cpuidle: using governor ladder
[    2.986520] cpuidle: using governor menu
[    2.995109] sdhci: Secure Digital Host Controller Interface driver
[    3.005934] sdhci: Copyright(c) Pierre Ossman
[    3.015016] sdhci: Enable low-latency mode
[    3.069473] mmc0: SDHCI controller on BCM2708_Arasan [platform] using platform's DMA
[    3.082265] mmc0: BCM2708 SDHC host at 0x20300000 DMA 4 IRQ 20
[    3.093081] sdhci-pltfm: SDHCI platform and OF driver helper
[    3.105553] ledtrig-cpu: registered to indicate activity on CPUs
[    3.119563] Indeed it is in host mode hprt0 = 00021501
[    3.131649] hidraw: raw HID events driver (C) Jiri Kosina
[    3.146817] usbcore: registered new interface driver usbhid
[    3.179378] usbhid: USB HID core driver
[    3.188354] TCP: cubic registered
[    3.208097] mmc0: new high speed SDHC card at address aaaa
[    3.229366] Initializing XFRM netlink socket
[    3.238330] NET: Registered protocol family 17
[    3.248143] mmcblk0: mmc0:aaaa SL16G 14.8 GiB
[    3.270455] Key type dns_resolver registered
[    3.279913]  mmcblk0: p1 p2 p3 p4
[    3.293659] VFP support v0.3: implementor 41 architecture 1 part 20 variant b rev 5
[    3.308102] registered taskstats version 1
[    3.320552] EXT4-fs (mmcblk0p3): mounting ext2 file system using the ext4 subsystem
[    3.342732] EXT4-fs (mmcblk0p3): warning: mounting unchecked fs, running e2fsck is recommended
[    3.367624] EXT4-fs (mmcblk0p3): mounted filesystem without journal. Opts: (null)
[    3.380231] VFS: Mounted root (ext2 filesystem) on device 179:3.
[    3.402389] devtmpfs: mounted
[    3.410411] usb 1-1: new high-speed USB device number 2 using dwc_otg
[    3.422264] Freeing unused kernel memory: 136K (c0679000 - c069b000)
[    3.433792] Indeed it is in host mode hprt0 = 00001101
[    3.650084] usb 1-1: New USB device found, idVendor=0424, idProduct=9512
[    3.662722] usb 1-1: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[    3.677662] hub 1-1:1.0: USB hub found
[    3.686855] hub 1-1:1.0: 3 ports detected
[    3.931629] systemd[1]: systemd 208 running in system mode. (+PAM +LIBWRAP +AUDIT +SELINUX -IMA +SYSVINIT +LIBCRYPTSETUP +GCRYPT +ACL +XZ)
[    3.969769] usb 1-1.1: new high-speed USB device number 3 using dwc_otg
[    4.054001] NET: Registered protocol family 10
[    4.065379] systemd[1]: Inserted module 'ipv6'
[    4.077664] systemd[1]: Set hostname to <nagios1>.
[    4.100126] usb 1-1.1: New USB device found, idVendor=0424, idProduct=ec00
[    4.112842] usb 1-1.1: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[    4.133511] smsc95xx v1.0.4
[    4.208656] smsc95xx 1-1.1:1.0 eth0: register 'smsc95xx' at usb-bcm2708_usb-1.1, smsc95xx USB 2.0 Ethernet, b8:27:eb:15:e6:25
[    4.339695] usb 1-1.3: new high-speed USB device number 4 using dwc_otg
[    4.451813] usb 1-1.3: New USB device found, idVendor=05e3, idProduct=0608
[    4.469227] device-mapper: ioctl: 4.25.0-ioctl (2013-06-26) initialised: dm-devel@redhat.com
[    4.483554] usb 1-1.3: New USB device strings: Mfr=0, Product=1, SerialNumber=0
[    4.502732] usb 1-1.3: Product: USB2.0 Hub
[    4.517843] LVM: Activation generator successfully completed.
[    4.530392] hub 1-1.3:1.0: USB hub found
[    4.543002] hub 1-1.3:1.0: 4 ports detected
[    4.830153] usb 1-1.3.1: new high-speed USB device number 5 using dwc_otg
[    4.940869] usb 1-1.3.1: New USB device found, idVendor=0781, idProduct=5575
[    4.956584] usb 1-1.3.1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[    4.972981] usb 1-1.3.1: Product: Cruzer Glide
[    4.983111] usb 1-1.3.1: Manufacturer: SanDisk
[    4.994649] usb 1-1.3.1: SerialNumber: 2005425572139550A9B5
[    5.018049] systemd[1]: Expecting device dev-ttyAMA0.device...
[    5.030094] usb-storage 1-1.3.1:1.0: USB Mass Storage device detected
[    5.042967] scsi0 : usb-storage 1-1.3.1:1.0
[    5.060525] systemd[1]: Starting Syslog Socket.
[    5.078256] systemd[1]: Listening on Syslog Socket.
[    5.089138] systemd[1]: Starting Remote File Systems (Pre).
[    5.107201] systemd[1]: Reached target Remote File Systems (Pre).
[    5.119080] systemd[1]: Starting Remote File Systems.
[    5.136345] systemd[1]: Reached target Remote File Systems.
[    5.148116] systemd[1]: Starting Replay Read-Ahead Data...
[    5.159884] usb 1-1.3.4: new high-speed USB device number 6 using dwc_otg
[    5.192637] systemd[1]: Starting Collect Read-Ahead Data...
[    5.240206] systemd-readahead[62]: Bumped block_nr parameter of 179:0 to 20480. This is a temporary hack and should be removed one day.
[    5.259275] systemd[1]: Starting /dev/initctl Compatibility Named Pipe.
[    5.290332] systemd[1]: Listening on /dev/initctl Compatibility Named Pipe.
[    5.305607] systemd[1]: Starting Delayed Shutdown Socket.
[    5.317238] usb 1-1.3.4: New USB device found, idVendor=05e3, idProduct=0608
[    5.341583] systemd[1]: Listening on Delayed Shutdown Socket.
[    5.353580] usb 1-1.3.4: New USB device strings: Mfr=0, Product=1, SerialNumber=0
[    5.369309] systemd[1]: Starting Dispatch Password Requests to Console Directory Watch.
[    5.383454] usb 1-1.3.4: Product: USB2.0 Hub
[    5.396525] hub 1-1.3.4:1.0: USB hub found
[    5.407582] systemd[1]: Started Dispatch Password Requests to Console Directory Watch.
[    5.422508] hub 1-1.3.4:1.0: 4 ports detected
[    5.433334] systemd[1]: Starting Journal Socket.
[    5.459332] systemd[1]: Listening on Journal Socket.
[    5.471229] systemd[1]: Mounted Huge Pages File System.
[    5.484291] systemd[1]: Starting Create list of required static device nodes for the current kernel...
[    5.513221] systemd[1]: Mounting Debug File System...
[    5.577147] systemd[1]: Mounting POSIX Message Queue File System...
[    5.645725] systemd[1]: Starting Create dynamic rule for /dev/root link...
[    5.720108] usb 1-1.3.4.1: new low-speed USB device number 7 using dwc_otg
[    5.767067] systemd[1]: Starting Journal Service...
[    5.835571] usb 1-1.3.4.1: New USB device found, idVendor=046d, idProduct=c248
[    5.876981] systemd[1]: Started Journal Service.
[    5.889632] usb 1-1.3.4.1: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[    5.915650] usb 1-1.3.4.1: Product: Gaming Keyboard G105
[    5.915662] usb 1-1.3.4.1: Manufacturer: Logitech
[    5.953146] input: Logitech Gaming Keyboard G105 as /devices/platform/bcm2708_usb/usb1/1-1/1-1.3/1-1.3.4/1-1.3.4.1/1-1.3.4.1:1.0/input/input0
[    5.962822] hid-generic 0003:046D:C248.0001: input,hidraw0: USB HID v1.10 Keyboard [Logitech Gaming Keyboard G105] on usb-bcm2708_usb-1.3.4.1/input0
[    6.012091] input: Logitech Gaming Keyboard G105 as /devices/platform/bcm2708_usb/usb1/1-1/1-1.3/1-1.3.4/1-1.3.4.1/1-1.3.4.1:1.1/input/input1
[    6.012785] hid-generic 0003:046D:C248.0002: input,hiddev0,hidraw1: USB HID v1.10 Device [Logitech Gaming Keyboard G105] on usb-bcm2708_usb-1.3.4.1/input1
[    6.019009] systemd-journald[72]: Vacuuming done, freed 0 bytes
[    6.061342] scsi 0:0:0:0: Direct-Access     SanDisk  Cruzer Glide     2.01 PQ: 0 ANSI: 6
[    6.064329] sd 0:0:0:0: [sda] 125031680 512-byte logical blocks: (64.0 GB/59.6 GiB)
[    6.066601] sd 0:0:0:0: [sda] Write Protect is off
[    6.066626] sd 0:0:0:0: [sda] Mode Sense: 43 00 00 00
[    6.067427] sd 0:0:0:0: [sda] Write cache: disabled, read cache: enabled, doesn't support DPO or FUA
[    6.072567]  sda: sda1
[    6.077078] sd 0:0:0:0: [sda] Attached SCSI disk
[    6.100065] usb 1-1.3.4.2: new low-speed USB device number 8 using dwc_otg
[    6.229569] usb 1-1.3.4.2: New USB device found, idVendor=046d, idProduct=c069
[    6.229586] usb 1-1.3.4.2: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[    6.229595] usb 1-1.3.4.2: Product: USB Laser Mouse
[    6.229602] usb 1-1.3.4.2: Manufacturer: Logitech
[    6.246729] input: Logitech USB Laser Mouse as /devices/platform/bcm2708_usb/usb1/1-1/1-1.3/1-1.3.4/1-1.3.4.2/1-1.3.4.2:1.0/input/input2
[    6.252538] hid-generic 0003:046D:C069.0003: input,hidraw2: USB HID v1.10 Mouse [Logitech USB Laser Mouse] on usb-bcm2708_usb-1.3.4.2/input0
[    8.340880] systemd-udevd[100]: starting version 208
[    9.867003] bcm2708_i2c_init_pinmode(0,0)
[   10.068973] bcm2708_i2c_init_pinmode(0,1)
[   10.224252] bcm2708_i2c bcm2708_i2c.0: BSC0 Controller at 0x20205000 (irq 79) (baudrate 100k)
[   10.428356] bcm2708_spi bcm2708_spi.0: master is unqueued, this is deprecated
[   10.533935] bcm2708_spi bcm2708_spi.0: SPI Controller at 0x20204000 (irq 80)
[   10.624654] bcm2708_i2c_init_pinmode(1,2)
[   10.705175] bcm2708_i2c_init_pinmode(1,3)
[   10.739938] bcm2708_i2c bcm2708_i2c.1: BSC1 Controller at 0x20804000 (irq 79) (baudrate 100k)
[   11.772940] Adding 76796k swap on /dev/mmcblk0p2.  Priority:-1 extents:1 across:76796k SSFS
[   14.094799] bio: create slab <bio-2> at 2
[   14.876803] EXT4-fs (dm-0): mounted filesystem with ordered data mode. Opts: (null)
[   16.799946] Adding 2097148k swap on /dev/mapper/nagios4-swap1.  Priority:-2 extents:1 across:2097148k FS
[   17.828684] SGI XFS with ACLs, security attributes, realtime, large block/inode numbers, no debug enabled
[   17.851262] XFS (dm-2): Mounting Filesystem
[   18.867860] XFS (dm-3): Mounting Filesystem
[   19.622012] XFS (dm-6): Mounting Filesystem
[   19.812604] XFS (dm-4): Mounting Filesystem
[   20.061114] XFS (dm-6): Ending clean mount
[   20.290393] XFS (dm-5): Mounting Filesystem
[   20.951715] XFS (dm-3): Ending clean mount
[   20.962375] XFS (dm-8): Mounting Filesystem
[   20.965662] XFS (dm-7): Mounting Filesystem
[   21.407569] XFS (dm-9): Mounting Filesystem
[   22.217957] XFS (dm-9): Ending clean mount
[   22.225615] XFS (dm-10): Mounting Filesystem
[   22.232956] XFS (dm-11): Mounting Filesystem
[   22.317930] XFS (dm-12): Mounting Filesystem
[   22.806769] XFS (dm-4): Ending clean mount
[   23.388734] XFS (dm-8): Ending clean mount
[   23.695870] XFS (dm-5): Ending clean mount
[   24.259339] XFS (dm-10): Ending clean mount
[   24.942678] XFS (dm-12): Ending clean mount
[   25.536974] XFS (dm-11): Ending clean mount
[   27.217216] XFS (dm-7): Ending clean mount
[   29.445113] XFS (dm-2): Ending clean mount
[   29.591481] systemd-journald[72]: Received request to flush runtime journal from PID 1
[   31.690776] EXT4-fs error (device mmcblk0p3): ext4_mb_generate_buddy:755: group 14, 7970 clusters in bitmap, 7969 in gd
[   41.275462] smsc95xx 1-1.1:1.0 eth0: hardware isn't capable of remote wakeup
[   41.276071] IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready
[   42.815343] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
[   42.817775] smsc95xx 1-1.1:1.0 eth0: link up, 100Mbps, full-duplex, lpa 0x45E1
[  303.999385] EXT4-fs (mmcblk0p3): error count: 2
[  303.999419] EXT4-fs (mmcblk0p3): initial error at 33: ext4_mb_generate_buddy:755
[  303.999437] EXT4-fs (mmcblk0p3): last error at 31: ext4_mb_generate_buddy:755
[14570.752549] systemd-journald[72]: Vacuuming done, freed 0 bytes
[36111.610875] systemd-journald[72]: Vacuuming done, freed 0 bytes
[58676.124814] systemd-journald[72]: Vacuuming done, freed 0 bytes
[80953.154647] systemd-journald[72]: Vacuuming done, freed 0 bytes
[86809.956370] EXT4-fs (mmcblk0p3): error count: 2
[86809.956409] EXT4-fs (mmcblk0p3): initial error at 33: ext4_mb_generate_buddy:755
[86809.956431] EXT4-fs (mmcblk0p3): last error at 31: ext4_mb_generate_buddy:755
[103317.548074] systemd-journald[72]: Vacuuming done, freed 0 bytes
[125759.313064] systemd-journald[72]: Vacuuming done, freed 0 bytes
[148014.091945] systemd-journald[72]: Vacuuming done, freed 0 bytes
[169975.964228] systemd-journald[72]: Vacuuming done, freed 2531328 bytes
[173319.744037] EXT4-fs (mmcblk0p3): error count: 2
[173319.744074] EXT4-fs (mmcblk0p3): initial error at 33: ext4_mb_generate_buddy:755
[173319.744093] EXT4-fs (mmcblk0p3): last error at 31: ext4_mb_generate_buddy:755
[192475.255833] systemd-journald[72]: Vacuuming done, freed 3198976 bytes
[214908.882306] systemd-journald[72]: Vacuuming done, freed 3215360 bytes
[237411.929777] systemd-journald[72]: Vacuuming done, freed 3207168 bytes
[259829.533670] EXT4-fs (mmcblk0p3): error count: 2
[259829.533750] EXT4-fs (mmcblk0p3): initial error at 33: ext4_mb_generate_buddy:755
[259829.533772] EXT4-fs (mmcblk0p3): last error at 31: ext4_mb_generate_buddy:755
[259911.594421] systemd-journald[72]: Vacuuming done, freed 3211264 bytes
[282412.753333] systemd-journald[72]: Vacuuming done, freed 3268608 bytes
[304913.212502] systemd-journald[72]: Vacuuming done, freed 3207168 bytes
[327413.136520] systemd-journald[72]: Vacuuming done, freed 3198976 bytes
[341164.472023] usb 1-1.3.4.1: USB disconnect, device number 7
[346339.323264] EXT4-fs (mmcblk0p3): error count: 2
[346339.323300] EXT4-fs (mmcblk0p3): initial error at 33: ext4_mb_generate_buddy:755
[346339.323320] EXT4-fs (mmcblk0p3): last error at 31: ext4_mb_generate_buddy:755
[349313.637191] systemd-journald[72]: Vacuuming done, freed 3264512 bytes
[371574.621692] systemd-journald[72]: Vacuuming done, freed 3211264 bytes
[393859.442932] systemd-journald[72]: Vacuuming done, freed 3215360 bytes
[416465.490184] systemd-journald[72]: Vacuuming done, freed 3211264 bytes
[432849.121970] EXT4-fs (mmcblk0p3): error count: 2
[432849.122007] EXT4-fs (mmcblk0p3): initial error at 33: ext4_mb_generate_buddy:755
[432849.122025] EXT4-fs (mmcblk0p3): last error at 31: ext4_mb_generate_buddy:755
[438066.663112] systemd-journald[72]: Vacuuming done, freed 3211264 bytes
[440267.087914] usb 1-1.3.4.2: USB disconnect, device number 8
[460317.397542] systemd-journald[72]: Vacuuming done, freed 3215360 bytes
[482817.160362] systemd-journald[72]: Vacuuming done, freed 3268608 bytes
[505317.974769] systemd-journald[72]: Vacuuming done, freed 3194880 bytes
[519358.925293] EXT4-fs (mmcblk0p3): error count: 2
[519358.925332] EXT4-fs (mmcblk0p3): initial error at 33: ext4_mb_generate_buddy:755
[519358.925351] EXT4-fs (mmcblk0p3): last error at 31: ext4_mb_generate_buddy:755
[527768.642067] systemd-journald[72]: Vacuuming done, freed 3203072 bytes
[550319.338060] systemd-journald[72]: Vacuuming done, freed 3203072 bytes
[572879.432242] systemd-journald[72]: Vacuuming done, freed 3215360 bytes
[595569.820585] systemd-journald[72]: Vacuuming done, freed 3211264 bytes
[605868.732673] EXT4-fs (mmcblk0p3): error count: 2
[605868.732709] EXT4-fs (mmcblk0p3): initial error at 33: ext4_mb_generate_buddy:755
[605868.732727] EXT4-fs (mmcblk0p3): last error at 31: ext4_mb_generate_buddy:755
[617580.914099] systemd-journald[72]: Vacuuming done, freed 3207168 bytes
[640022.195625] systemd-journald[72]: Vacuuming done, freed 3215360 bytes
[662581.405415] systemd-journald[72]: Vacuuming done, freed 3268608 bytes
[685023.412802] systemd-journald[72]: Vacuuming done, freed 3211264 bytes
[692378.532190] EXT4-fs (mmcblk0p3): error count: 2
[692378.532229] EXT4-fs (mmcblk0p3): initial error at 33: ext4_mb_generate_buddy:755
[692378.532249] EXT4-fs (mmcblk0p3): last error at 31: ext4_mb_generate_buddy:755
[707524.813191] systemd-journald[72]: Vacuuming done, freed 3268608 bytes
[730274.659789] systemd-journald[72]: Vacuuming done, freed 3219456 bytes
[752774.185341] systemd-journald[72]: Vacuuming done, freed 3219456 bytes
[774783.289086] systemd-journald[72]: Vacuuming done, freed 3198976 bytes
[778888.328700] EXT4-fs (mmcblk0p3): error count: 2
[778888.328742] EXT4-fs (mmcblk0p3): initial error at 33: ext4_mb_generate_buddy:755
[778888.328761] EXT4-fs (mmcblk0p3): last error at 31: ext4_mb_generate_buddy:755
[797175.387911] systemd-journald[72]: Vacuuming done, freed 3264512 bytes
</pre>

**Comment by popcornmix** [comment]
Does it do this with more than one sdcard?

**Comment by popcornmix** [comment]
Closing due to lack of response
