### ISSUE TITLE
ZFS kernel module build fails using dkms on 6.6.y

### ISSUE THREAD

**Issue by baslking** [raspberrypi/linux#5878]
### Describe the bug

The 6.6.y kernel linkage fails due to GPL questions around the zfs filesystem licensing.  The change is a simple one in an include file and prevents use of ZFS with the 6.6.y branch

### Steps to reproduce the behaviour

I am using the Arch arm linux 64 bit aur installation (https://aur.archlinux.org/zfs-dkms.git) but I don't this is distribution specific 
The error is:
```MODPOST /var/lib/dkms/zfs/2.2.2/build/module/Module.symvers
ERROR: modpost: GPL-incompatible module zfs.ko uses GPL-only symbol 'kernel_neon_end'
ERROR: modpost: GPL-incompatible module zfs.ko uses GPL-only symbol 'kernel_neon_begin'
make[3]: *** [scripts/Makefile.modpost:145: /var/lib/dkms/zfs/2.2.2/build/module/Module.symvers] Error 1
make[2]: *** [/usr/lib/modules/6.6.9-1-rpi-ARCH/build/Makefile:1865: modpost] Error 2
make[1]: *** [Makefile:234: __sub-make] Error 2
make[1]: Leaving directory '/usr/lib/modules/6.6.9-1-rpi-ARCH/build'
make: *** [Makefile:56: modules-Linux] Error 2
make: Leaving directory '/var/lib/dkms/zfs/2.2.2/build/module'
```

### Device (s)

Raspberry Pi 400, Raspberry Pi CM1

### System

Oct 17 2023 15:39:16 
Copyright (c) 2012 Broadcom
version 30f0c5e4d076da3ab4f341d88e7d505760b93ad7 (clean) (release) (start)

Linux pi-400 6.6.12-1-rpi #1 SMP PREEMPT Thu Jan 18 15:23:28 CET 2024 aarch64 GNU/Linux

### Logs

The following patch solves the issue and makes the file match the 6.1 definitions:
```
diff --git a/include/linux/export.h b/include/linux/export.h
index 9911508a9604..5d9e8c5304f6 100644
--- a/include/linux/export.h
+++ b/include/linux/export.h
@@ -84,8 +84,8 @@ extern struct module __this_module;
 #endif
 
 #define EXPORT_SYMBOL(sym)             _EXPORT_SYMBOL(sym, "")
-#define EXPORT_SYMBOL_GPL(sym)         _EXPORT_SYMBOL(sym, "GPL")
+#define EXPORT_SYMBOL_GPL(sym)         _EXPORT_SYMBOL(sym, "")
 #define EXPORT_SYMBOL_NS(sym, ns)      __EXPORT_SYMBOL(sym, "", __stringify(ns))
-#define EXPORT_SYMBOL_NS_GPL(sym, ns)  __EXPORT_SYMBOL(sym, "GPL", __stringify(ns))
+#define EXPORT_SYMBOL_NS_GPL(sym, ns)  __EXPORT_SYMBOL(sym, "", __stringify(ns))
 
 #endif /* _LINUX_EXPORT_H */
```

### Additional context

It would be great if this could be added upstream so that downstream users don't have to build their own kernels
thanks

**Comment by pelwell** [comment]
It looks like you are asking us to accept a patch that allows non-GPL code to access kernel APIs that are marked GPL-only. Obviously that's not going to happen.
