### ISSUE TITLE
pcie-32bit-dma overlay does not work on Pi 5's external PCIe interface

### ISSUE THREAD

**Issue by RodrigoRosmaninho** [raspberrypi/linux#5896]
### Describe the bug

This is the same issue as #4197 (that was fixed by #4216).
However, that previous fix (the pcie-32bit-dma dts overlay) is only compatible with CM4 and has no effect on Pi 5.

I tested this on a Raspberry Pi 5 connected to Pineberry Pi's "Hat AI!", to which I plugged in a MikroTik R11e-5HnD (Atheros AR9580) wireless card.

### Steps to reproduce the behaviour

Connect a PCIe device that can only use 32bit DMA addresses in order to function correctly, such as a wireless network card using Atheros AR9580.

### Device (s)

Raspberry Pi 5

### System

Raspberry Pi reference 2023-12-05
Generated using pi-gen, https://github.com/RPi-Distro/pi-gen, 70cd6f2a1e34d07f5cba7047aea5b92457372e05, stage4

Raspberry Pi reference 2023-12-05
Generated using pi-gen, https://github.com/RPi-Distro/pi-gen, 70cd6f2a1e34d07f5cba7047aea5b92457372e05, stage4

Linux opportunity 6.1.0-rpi7-rpi-2712 #1 SMP PREEMPT Debian 1:6.1.63-1+rpt1 (2023-11-24) aarch64 GNU/Linux

### Logs

The symptoms are exactly the same as seen here: https://github.com/geerlingguy/raspberry-pi-pcie-devices/issues/313

**Comment by RodrigoRosmaninho** [comment]
I have created a PR (#5897) to add a new _pcie-32bit-dma-pi5-overlay_ dts overlay that fixes this issue.
I've confirmed that this works correctly on my setup (described above).

**Comment by pelwell** [comment]
Closing this as unnecessary - the PR is sufficient.
