### ISSUE TITLE
XBMC always crashes on linux 3.12 and 3.14

### ISSUE THREAD

**Issue by ghost** [raspberrypi/linux#591]
XBMC stopped working after the kernel got upgraded to the 3.12. I am running Arch Linux. 

I have everything else up-to-date but the kernel downgraded to 3.10.38 and XBMC works normally.

Crash reports at:
http://archlinuxarm.org/forum/viewtopic.php?f=59&t=7230

**Comment by popcornmix** [comment]
You'll have to reproduce with a default kernel from raspbian.
There are too many unknowns when using a custom kernel from Arch.

Note that openelec uses 3.14 (and used 3.12 before then), and I use 3.12 on raspbian in my xbmc development environment, so I don't think it is as simple as 3.12 breaks xbmc.

Perhaps if someone from Arch can identify the kernel commit that stops xbmc working, then we'd have a starting point for investigation.

**Comment by ghost** [comment]
The problem went away when I commented the cma lines at config.txt so I guess this is the same problem as https://github.com/raspberrypi/linux/issues/520

I also got similar messages as this https://github.com/raspberrypi/linux/issues/520#issuecomment-34153874

**Comment by popcornmix** [comment]
CMA is experimental and not recommended, so removing CMA entries is correct solution.
