### ISSUE TITLE
Issue with Pi5 and V2 cameras after updating with kernel newer than 6.1.65 

### ISSUE THREAD

**Issue by sandyol55** [raspberrypi/linux#5915]
### Describe the bug

A recent  apt update/upgrade resulted in previously working picamera2 code to fail with

File "/usr/lib/python3/dist-packages/picamera2/picamera2.py", line 1131, in start_self.camera.start(controls)
RuntimeError: Failed to start camera: Broken pipe

Working back through the releases, reverting to 6.1.65 resolved the problem.

### Steps to reproduce the behaviour

apt update / upgrade and try to run picamera2 example code with Pi5 and dual V2 cameras connected.
(Haven't tried a single camera, so not sure if dual is relevant)

### Device (s)

Raspberry Pi 5

### System

cat /etc/rpi-issue
Raspberry Pi reference 2023-10-10
Generated using pi-gen, https://github.com/RPi-Distro/pi-gen, 962bf483c8f326405794827cce8c0313fd5880a8, stage4

vcgencmd version
2024/01/24 12:16:01 
Copyright (c) 2012 Broadcom
version 1aeae380 (release) (embedded)

uname -a
Linux raspberrypi 6.1.65-v8-16k+ #1703 SMP PREEMPT Tue Dec  5 16:28:46 GMT 2023 aarch64 GNU/Linux
(after reverting)

**Comment by naushir** [comment]
This is almost certainly a userland issue, so I'll close this issue here and track it in the rpicam-apps repo.
