### ISSUE TITLE
V4L2: Increase the MMAL timeout to 3sec - not present in recent kernels

### ISSUE THREAD

**Issue by zboobzor** [raspberrypi/linux#592]
Commit e083ef78b5c543b4a16042fb01afa2a8358cb636 (V4L2: Increase the MMAL timeout to 3sec) does not appear to be applied to linux 3.12 and 3.14.
Please apply this change to the aformentioned kernels.

Thanks.

**Comment by popcornmix** [comment]
Okay. Added to source trees. Will be in next rpi-update.

**Comment by zboobzor** [comment]
Wow, that was fast, thanks :)

**Comment by brabl2** [comment]
Same issue for commit d89bb128f5291ef514328f9720ed88915f8a5a4d (i2c-bcm2708: fixed baudrate)
Could it be also added.
Thanks.

**Comment by popcornmix** [comment]
There two changes should be present in latest rpi-update firmware. Please test and close if happy.
