### ISSUE TITLE
omxplayer_0.3.5~git20140322~39e6342_armhf broke audio hdmi output

### ISSUE THREAD

**Issue by euldulle** [raspberrypi/linux#594]
omxplayer_0.3.3~git20131216~b34143c_armhf.deb

was running smooth and clear, except for subtitles, which is the reason why I upgraded to :

omxplayer_0.3.5~git20140322~39e6342_armhf.deb

But with that version audio output through hdmi is broken (the sound looks like "interlaced", with kind of a bizarre and unbareable echo effect).

I tested twice (back and forth with dpkg between both packages from my cache to make sure that no other modification interferes in the process). So I am back to 0.3.3. 

No error message, log for both version:

0.3.5: (broken one)
Video codec omx-h264 width 720 height 426 profile 77 fps 25.000000
Audio codec aac channels 2 samplerate 48000 bitspersample 16
Subtitle count: 1, state: off, index: 1, delay: 0
V:PortSettingsChanged: 720x426@25.00 interlace:0 deinterlace:0 par:1.42 layer:0

0.3.3: (working version)
Video codec omx-h264 width 720 height 426 profile 77 fps 25.000000
Audio codec aac channels 2 samplerate 48000 bitspersample 16
Subtitle count: 1, state: off, index: 1, delay: 0
V:PortSettingsChanged: 720x426@25.00 interlace:0 deinterlace:0
dest_rect.x_offset 0 dest_rect.y_offset 0 dest_rect.width 0 dest_rect.height 0, pixel_aspect 1.42

**Comment by popcornmix** [comment]
Not a linux issue. 
Best to ask here: https://github.com/popcornmix/omxplayer
