### ISSUE TITLE
CFE driver complains in v4l2_subdev_link_validate()

### ISSUE THREAD

**Issue by naushir** [raspberrypi/linux#5944]
### Describe the bug

With recent changes to the CFE driver to use ``v4l2_subdev_link_validate()``, when running the camera dmesg throws out the following error:

```
source of link 'rp1-cfe-fe_config':0->'pisp-fe':1 is not a V4L2 sub-device, driver bug!
```

This is expected, as ``rp1-cfe-fe_config`` is a device node:

![cfe](https://github.com/raspberrypi/linux/assets/7164802/e56cd341-7c16-4770-8574-14467a529620)

I cannot see how to get rid of this log message.

### Steps to reproduce the behaviour

Run any camera on Pi 5.

### Device (s)

Raspberry Pi 5

### System

Using kernel rpi-6.6.y

**Comment by naushir** [comment]
@tomba any thoughts on this?

**Comment by 6by9** [comment]
Likely one to query with Sakari as he introduced it through 55f1ecb1199000932cf82e357841cc7498ac904f

**Comment by tomba** [comment]
In my WIP streams-enabled version I have a pisp_fe_link_validate() which calls the normal v4l2_subdev_link_validate() for FE_STREAM_PAD, but skips the validation for FE_CONFIG_PAD.

**Comment by tomba** [comment]
```

static int pisp_fe_link_validate(struct media_link *link)
{
	struct v4l2_subdev *sd = media_entity_to_v4l2_subdev(link->sink->entity);
	struct pisp_fe_device *fe = container_of(sd, struct pisp_fe_device, sd);

	pisp_fe_dbg("%s: link \"%s\":%u -> \"%s\":%u\n", __func__,
		    link->source->entity->name, link->source->index,
		    link->sink->entity->name, link->sink->index);

	if (link->sink->index == FE_STREAM_PAD)
		return v4l2_subdev_link_validate(link);

	if (link->sink->index == FE_CONFIG_PAD)
		return 0;

	return -EINVAL;
}

static const struct media_entity_operations pisp_fe_entity_ops = {
	.link_validate = pisp_fe_link_validate,
};
```

**Comment by naushir** [comment]
Great, ill ignore this problem as your changes will fix the log message!
