### ISSUE TITLE
piCore with 3.14.4 stops during reboot

### ISSUE THREAD

**Issue by ha5di** [raspberrypi/linux#595]
Testing piCore-5.3rc with 3.14.4 reported by tester that in certain systems (not all) udev hangs on when rebooted while it works properly when started with power on. Same systems with 3.13.6 kernel works normally. I think it is related to changes in USB part. Unfortunately I can't reproduce, my Pi reboots correctly even when I have a card reader and WiFi stick plugged with the keyboard and mouse via powered hub. You can read details at http://forum.tinycorelinux.net/index.php/topic,17031.msg102222.html#msg102222

Do you have an idea how to fix or get details what is going on?

Thanks.... 

bmarkus @

**Comment by popcornmix** [comment]
I can't do much to help with custom kernels and distributions. Nothing obvious springs to mind.
The only thing I would try is to identify the commit that made this start happening.

If you think it is in the Pi specific patches, then try reverting some. The FIQ FSM ones would be one obvious group.
If you think it is upstream patches, then trying 3.14.1, 3.14.2, 3.14.3 may help narrow it down.

**Comment by ha5di** [comment]
Thanks for the comments. At the moment I don't know where is it comes from. I can't reproduce so can't do too much locally. Anyhow, will try to locate the cause. I reported in hope maybe someone else facing it. If you don't mind, leave it open for some time.

**Comment by ha5di** [comment]
Enabling FIQ-FSM in cmdline.txt fix the problem.
