### ISSUE TITLE
INTERRUPT_VC_USB error

### ISSUE THREAD

**Issue by scratchy** [raspberrypi/linux#596]
Hello,
im unable to build the current kernels (tried 3.6.y and 3.14.y)
heres the error i got while building:

drivers/usb/host/dwc_otg/dwc_otg_hcd_linux.c: In function âhcd_initâ:
drivers/usb/host/dwc_otg/dwc_otg_hcd_linux.c:510:14: error: âINTERRUPT_VC_USBâ undeclared (first use in this function)
   enable_fiq(INTERRUPT_VC_USB);

If you need additional infos, please let me know. Otherwise please tell me how to fix this issue :o

Greetings
Sascha

**Comment by popcornmix** [comment]
What .config are you using?
Start with:
`make ARCH=arm bcmrpi_defconfig`
and see if that builds?

**Comment by scratchy** [comment]
Hello,

its not the first time im building this kernel, anyways i checked the defconfig and its working without issues.

Heres my config i used: http://pastebin.com/xFfVBems

**Comment by scratchy** [comment]
O.K. i think i got the problem. It seems i forgot to pass "make menuconfig" the ARCH=arm option, so it seems menuconfig build a mix out of x86 and arm config and somehow broke that way the configuration for raspi.

**Comment by popcornmix** [comment]
Yes, ARCH=arm is needed for all make targets. Closing.
