### ISSUE TITLE
ASUS USB-AC51 AC600 adapter will not install

### ISSUE THREAD

**Issue by derekdickerson** [raspberrypi/linux#597]
Bus 001 Device 004: ID 0b05:17d1 ASUSTek Computer, Inc. 

Dual-band Wireless-AC600 USB Adapter
Product page
A USB ID of 0b05:17d1 is found for this device within the Elecom WDC-433SU2M's vendor driver set. This is the ID presumed to be used by this device.

[    3.467595] usb 1-1.3: new high-speed USB device number 4 using dwc_otg
[    3.612985] usb 1-1.3: New USB device found, idVendor=0b05, idProduct=17d1
[    3.624537] usb 1-1.3: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[    3.637572] usb 1-1.3: Product: WiFi
[    3.646679] usb 1-1.3: Manufacturer: MediaTek
[    3.667443] usb 1-1.3: SerialNumber: 1.0

pi@raspberrypi ~ $ ifconfig -a
eth0      Link encap:Ethernet  HWaddr b8:27:eb:b7:14:22  
          inet addr:10.0.1.110  Bcast:10.0.1.255  Mask:255.255.255.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:760 errors:0 dropped:0 overruns:0 frame:0
          TX packets:241 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:63816 (62.3 KiB)  TX bytes:33685 (32.8 KiB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:0 (0.0 B)  TX bytes:0 (0.0 B)

pi@raspberrypi ~ $ dpkg -l | grep firmware
ii  firmware-atheros                      0.36+wheezy.1                           all          Binary firmware for Atheros wireless cards
ii  firmware-brcm80211                    0.36+wheezy.1                           all          Binary firmware for Broadcom 802.11 wireless cards
ii  firmware-libertas                     0.36+wheezy.1                           all          Binary firmware for Marvell Libertas 8xxx wireless cards
ii  firmware-ralink                       0.36+wheezy.1                           all          Binary firmware for Ralink wireless cards
ii  firmware-realtek                      0.36+wheezy.1                           all          Binary firmware for Realtek wired and wireless network adapters
ii  rpi-update                            20140321                                all          Raspberry Pi firmware updating tool

**Comment by P33M** [comment]
Please post the full dmesg log since boot.

**Comment by popcornmix** [comment]
Closing due to lack of response

**Comment by chenhan1218** [comment]
Starting from Linux Kernel 4.19, the Asus USB-AC51 is supported.

See https://github.com/torvalds/linux/blob/v4.19/drivers/net/wireless/mediatek/mt76/mt76x0/usb.c#L30

**Comment by lil5** [comment]
The Asus USB-AC51 isn’t working for me on Fedora 36
