### ISSUE TITLE
overlays: config.txt not creating /dev/i2c* on latest 64-bit lite version

### ISSUE THREAD

**Issue by RaulTrombin** [raspberrypi/linux#5979]
### Describe the bug

I was testing a shield with sensors on I2C ports, 
unfortunately it did not create the i2c-* devices in the /dev/ folder.

Something changed on the config.txt sintaxe or devices's folder?

It work on previous versions.

### Steps to reproduce the behaviour

on config.txt

```
[all]
enable_uart=1
dtoverlay=uart1
dtoverlay=uart3
dtoverlay=uart4
dtoverlay=uart5
dtparam=i2c_vc=on
dtoverlay=i2c1
dtparam=i2c_arm_baudrate=1000000
dtoverlay=i2c4,pins_6_7,baudrate=1000000
dtoverlay=i2c6,pins_22_23,baudrate=400000
dtparam=spi=on
dtoverlay=spi0-led
dtoverlay=spi1-3cs
gpio=11,24,25=op,pu,dh
gpio=37=op,pd,dl
dtoverlay=dwc2

```

### Device (s)

Raspberry Pi 4 Mod. B

### System

Raspberry Pi reference 2023-12-11
Generated using pi-gen, https://github.com/RPi-Distro/pi-gen, 2acf7afcba7d11500313a7b93bb55a2aae20b2d6, stage2

pi@raspberrypi:/dev $ vcgencmd version
Oct 17 2023 15:39:16 
Copyright (c) 2012 Broadcom
version 30f0c5e4d076da3ab4f341d88e7d505760b93ad7 (clean) (release) (start)

pi@raspberrypi:/dev $ uname -a
Linux raspberrypi 6.1.0-rpi7-rpi-v8 #1 SMP PREEMPT Debian 1:6.1.63-1+rpt1 (2023-11-24) aarch64 GNU/Linux

**Comment by 6by9** [comment]
Have you loaded i2c_dev?
The kernel will quite happily enable I2C interfaces for use within the kernel, but they are only exposed to userspace via i2c_dev 
(`sudo modprobe i2c_dev`, add it to /etc/modules, or enabling I2C via raspi-config will add it to /etc/modules for you).

**Comment by RaulTrombin** [comment]
```
# /etc/modules: kernel modules to load at boot time.
#
# This file contains the names of kernel modules that should be loaded
# at boot time, one per line. Lines beginning with "#" are ignored.
# Parameters can be specified after the module name.

bcm2835-v4l2
i2c-bcm2835
i2c-dev

```


> Have you loaded i2c_dev? The kernel will quite happily enable I2C interfaces for use within the kernel, but they are only exposed to userspace via i2c_dev (`sudo modprobe i2c_dev`, add it to /etc/modules, or enabling I2C via raspi-config will add it to /etc/modules for you).

in fact using the raspi-config, it enables the i2c-1.
now i have i2c-1, i2c-20 and i2c,21. but still missing the i2c-4 and i2c-6.

```
pi@raspberrypi:/dev $ uname -a && ls /dev/i2c-*
Linux raspberrypi 6.1.0-rpi7-rpi-v8 #1 SMP PREEMPT Debian 1:6.1.63-1+rpt1 (2023-11-24) aarch64 GNU/Linux
/dev/i2c-1  /dev/i2c-20  /dev/i2c-21

```

vs old version:
```
pi@blueos:/dev $ uname -a && ls /dev/i2c-*
Linux blueos 5.10.33-v7l+ #1415 SMP Fri Apr 30 15:50:57 BST 2021 armv7l GNU/Linux
/dev/i2c-0  /dev/i2c-1  /dev/i2c-10  /dev/i2c-11  /dev/i2c-4  /dev/i2c-6

```

**Comment by 6by9** [comment]
bcm2835-v4l2 has been automatically loaded by vchiq_arm since 5.0 in 2018 - https://github.com/torvalds/linux/commit/405e2f98637d79b17434afc2596f5a49f418cc72

i2c-bcm2835 has used device tree to be loaded for a similar period of time.

`spi0-led` is not an overlay that is built from this repo, therefore the contents could be anything.
spi0 would normally be on GPIOs 9-11 for MISO, MOSI, and CLK respectively, with 7 & 8 as the chip selects. GPIO 9 collides with your uart4 on 8&9.

Your system is running a slightly old kernel. My updated Raspberry Pi OS install gives
`Linux raspberrypi 6.1.0-rpi8-rpi-v8 #1 SMP PREEMPT Debian 1:6.1.73-1+rpt1 (2024-01-25) aarch64 GNU/Linux`

Your config.txt without spi0-led on that gives
```
pi@raspberrypi:~ $ ls /dev/i2c*
/dev/i2c-0  /dev/i2c-1  /dev/i2c-10  /dev/i2c-20  /dev/i2c-21  /dev/i2c-22  /dev/i2c-4  /dev/i2c-6
```
and GPIO allocations as expected
```
pi@raspberrypi:~ $ pinctrl get
 0: ip    pu | hi // ID_SDA/GPIO0 = input
 1: ip    pu | hi // ID_SCL/GPIO1 = input
 2: a0    pu | hi // SDA1/GPIO2 = SDA1
 3: a0    pu | hi // SCL1/GPIO3 = SCL1
 4: a4    pn | hi // GPIO_GCLK/GPIO4 = TXD3
 5: a4    pu | hi // GPIO5 = RXD3
 6: a5    pu | hi // GPIO6 = SDA4
 7: a5    pu | hi // SPI_CE1_N/GPIO7 = SCL4
 8: a4    pn | hi // SPI_CE0_N/GPIO8 = TXD4
 9: a4    pu | hi // SPI_MISO/GPIO9 = RXD4
10: ip    pd | lo // SPI_MOSI/GPIO10 = input
11: ip    pd | lo // SPI_SCLK/GPIO11 = input
12: a4    pn | hi // GPIO12 = TXD5
13: a4    pu | hi // GPIO13 = RXD5
14: a5    pn | hi // TXD1/GPIO14 = TXD1
15: a5    pu | hi // RXD1/GPIO15 = RXD1
16: op -- pd | hi // GPIO16 = output
17: op -- pd | hi // GPIO17 = output
18: op -- pd | hi // GPIO18 = output
19: a4    pd | lo // GPIO19 = SPI1_MISO
20: a4    pd | lo // GPIO20 = SPI1_MOSI
21: a4    pd | lo // GPIO21 = SPI1_SCLK
22: a5    pu | hi // GPIO22 = SDA6
23: a5    pu | hi // GPIO23 = SCL6
24: ip    pd | lo // GPIO24 = input
25: ip    pd | lo // GPIO25 = input
26: ip    pd | lo // GPIO26 = input
27: ip    pd | lo // GPIO27 = input
```
So what's in spi0-led?

**Comment by RaulTrombin** [comment]
@6by9 thks for all infos regards modules,

Spi0-led is a custom neopixel that my script installs.

I was using the webpage lite images [here](https://downloads.raspberrypi.com/raspios_lite_arm64/images/?_gl=1*honw8c*_ga*MTMxMzE4MTc3Ni4xNzA3NzY4ODgy*_ga_22FD70LWDS*MTcwODYyNzk0MS42LjEuMTcwODYyNzk1MS4wLjAuMA..)
That I think is the last available officialy for users,

Even when I do a rpi-update, it still not load and show the i2c devices with the new kernel:
```
pi@raspberrypi:/dev $ uname -a
Linux raspberrypi 6.6.17-v8+ #1735 SMP PREEMPT Wed Feb 21 14:39:52 GMT 2024 aarch64 GNU/Linux

```

I'm going to check if the armv7 have the same behavior.

**Comment by popcornmix** [comment]
> I was using the webpage lite images here
That I think is the last available officialy for users,

If you run `sudo apt update / sudo apt full-upgrade` you should get the 6.1.73 kernel.

**Comment by 6by9** [comment]
I would remove `dtoverlay=spi0-led` to eliminate it from being the problem.

If it is the problem, then you'll have to work out where the GPIO conflict is.

**Comment by RaulTrombin** [comment]
but if even without the spi0-led it keep not working yet.
I tryed the current latest 32-bit also, same issue there (after change to boot into correct armv7 kernel which I open an issue).

@6by9 I'm going to use a clean 64 lite image again, and check the "pinctrl get"

**Comment by RaulTrombin** [comment]
y, no i2c shown using latest 64 bit lite:

```
[all]
enable_uart=1
dtoverlay=uart1
dtoverlay=uart3
dtoverlay=uart4
dtoverlay=uart5
dtparam=i2c_vc=on
dtoverlay=i2c1
dtparam=i2c_arm_baudrate=1000000
dtoverlay=i2c4,pins_6_7,baudrate=1000000
dtoverlay=i2c6,pins_22_23,baudrate=400000
dtparam=spi=on
dtoverlay=spi1-3cs
gpio=11,24,25=op,pu,dh
gpio=37=op,pd,dl
dtoverlay=dwc2
```
*removed spi-led

https://www.diffchecker.com/xPvAZU3f/

**Comment by seamusdemora** [comment]
Regard this input as *"unsubstantiated rumor"*: 

I've noticed on a couple of occasions on a Pi4 **bullseye** system that enabling i2c in config.txt followed by a reboot was insufficient to get i2c working. The only way to overcome this was to enable it in `raspi-config`.

**Comment by RaulTrombin** [comment]
@6by9 I did it again, on latest official 64bits lite,
with overlays and etc/modules:

```
i2c-bcm2835
i2c-dev
```
It works fine, just missed the two i2c modules.

Can't explain what happened before.

**Comment by pelwell** [comment]
Of those, only `i2c-dev` needs to be in /etc/modules - `i2c-bcm2835` (or `i2c-designware-platform`/`i2c-brcmstb` on a Pi 5) will be loaded automatically when needed.

**Comment by RaulTrombin** [comment]
can confirm it, thks @pelwell  @6by9
