### ISSUE TITLE
Wayland crashes (segmentation fault) after executing "wlr-randr" command

### ISSUE THREAD

**Issue by marty45714** [raspberrypi/linux#5984]
### Describe the bug

Wayland GUI crashes with a segmentation fault when executing the "wlr-randr" command to power off the HDMI monitor:

export WAYLAND_DISPLAY=wayland-1
export XDG_RUNTIME_DIR=/run/user/1000
/usr/bin/wlr-randr --output HDMI-A-1 --off

From .xsession-errors:

EE 23-02-24 02:37:02.471 - [src/core/output-layout.cpp:614] disabling output: HDMI-A-1
II 23-02-24 02:37:02.471 - [src/core/output-layout.cpp:146] transfer views from HDMI-A-1 -> NOOP-1
EE 23-02-24 02:37:02.477 - [src/main.cpp:144] Fatal error: Segmentation fault
EE 23-02-24 02:37:02.495 - #1  wf::print_trace(bool) ??:?
addr2line: '?,EM?': No such file
addr2line: '?,EM?': No such file
EE 23-02-24 02:37:02.500 - #2  ????? ?????
EE 23-02-24 02:37:02.508 - #3  wf::view_interface_t::close() ??:?

### Steps to reproduce the behaviour

Start Wayland GUI

Execute the following script to turn off the HDMI connected monitor:
#!/bin/bash
export WAYLAND_DISPLAY=wayland-1
export XDG_RUNTIME_DIR=/run/user/1000
/usr/bin/wlr-randr --output HDMI-A-1 --off

Wayland will seg-fault and log you out.

### Device (s)

Raspberry Pi 5

### System

samartin@dakboard:~ $ cat /etc/rpi-issue 
Raspberry Pi reference 2023-12-05
Generated using pi-gen, https://github.com/RPi-Distro/pi-gen, 70cd6f2a1e34d07f5cba7047aea5b92457372e05, stage2

samartin@dakboard:~ $ vcgencmd version
2024/02/16 15:28:41 
Copyright (c) 2012 Broadcom
version 4c845bd3 (release) (embedded)

samartin@dakboard:~ $ uname -a
Linux dakboard 6.6.17-v8-16k+ #1735 SMP PREEMPT Wed Feb 21 14:45:17 GMT 2024 aarch64 GNU/Linux

### Logs

cat .xsession-errors

WW 23-02-24 02:37:02.466 - [src/core/output-layout.cpp:1318] All wayfire outputs have been disabled!
II 23-02-24 02:37:02.466 - [src/core/output-layout.cpp:1039] new output: NOOP-1
II 23-02-24 02:37:02.466 - [src/core/output-layout.cpp:535] loaded mode auto
II 23-02-24 02:37:02.466 - [src/core/output-layout.cpp:711] Couldn't find matching mode 1920x1080@60 for output NOOP-1. Trying to use custom mode(might not work)
(type equals variant: [type: string, value: toplevel] | (type equals variant: [type: string, value: x-or] & focusable equals variant: [type: bool, value: 1]))
type equals variant: [type: string, value: overlay]
false
false
false
app_id equals variant: [type: string, value: Kodi]
(type equals variant: [type: string, value: toplevel] & floating equals variant: [type: bool, value: 1])
EE 23-02-24 02:37:02.470 - [types/wlr_cursor.c:875] Cannot map device "pwr_button" to output (not found in this cursor)
EE 23-02-24 02:37:02.471 - [types/wlr_cursor.c:875] Cannot map device "vc4-hdmi-0" to output (not found in this cursor)
EE 23-02-24 02:37:02.471 - [types/wlr_cursor.c:875] Cannot map device "vc4-hdmi-1" to output (not found in this cursor)
EE 23-02-24 02:37:02.471 - [src/core/output-layout.cpp:614] disabling output: HDMI-A-1
II 23-02-24 02:37:02.471 - [src/core/output-layout.cpp:146] transfer views from HDMI-A-1 -> NOOP-1
EE 23-02-24 02:37:02.477 - [src/main.cpp:144] Fatal error: Segmentation fault
EE 23-02-24 02:37:02.495 - #1  wf::print_trace(bool) ??:?
addr2line: '?,EM?': No such file
addr2line: '?,EM?': No such file
EE 23-02-24 02:37:02.500 - #2  ????? ?????
EE 23-02-24 02:37:02.508 - #3  wf::view_interface_t::close() ??:?
EE 23-02-24 02:37:02.515 - #4  non-virtual thunk to wayfire_layer_shell_view::close() ??:?
EE 23-02-24 02:37:02.523 - #5  wf::transfer_views(wf::output_t*, wf::output_t*) ??:?
EE 23-02-24 02:37:02.531 - #6  wf::output_layout_output_t::destroy_wayfire_output() ??:?
EE 23-02-24 02:37:02.539 - #7  wf::output_layout_output_t::apply_state(wf::output_state_t const&) ??:?
EE 23-02-24 02:37:02.546 - #8  wf::output_layout_t::impl::apply_configuration(std::map<wlr_output*, wf::output_state_t, std::less<wlr_output*>, std::allocator<std::pair<wlr_output* const, wf::output_state_t> > > const&) ??:?
EE 23-02-24 02:37:02.553 - #9  wf::output_layout_t::impl::apply_wlr_configuration(wlr_output_configuration_v1*, bool) ??:?
EE 23-02-24 02:37:02.560 - #10 std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > wf::log::to_string<char const*>(char const*) ??:?
EE 23-02-24 02:37:02.568 - #11 wl_signal_emit_mutable ??:?
EE 23-02-24 02:37:02.573 - #12 ffi_prep_go_closure ??:?
EE 23-02-24 02:37:02.578 - #13 ffi_closure_free ??:?
EE 23-02-24 02:37:02.583 - #14 wl_event_loop_get_destroy_listener ??:?
EE 23-02-24 02:37:02.587 - #15 wl_client_destroy ??:?
EE 23-02-24 02:37:02.592 - #16 wl_event_loop_dispatch ??:?
EE 23-02-24 02:37:02.597 - #17 wl_display_run ??:?
EE 23-02-24 02:37:02.604 - #18 main ??:?
EE 23-02-24 02:37:02.754 - #19 __libc_start_call_main ../sysdeps/unix/sysv/linux/aarch64/libc-start.c:74
EE 23-02-24 02:37:02.847 - #20 call_init ../csu/libc-start.c:128
EE 23-02-24 02:37:02.854 - #21 _start ??:?

### Additional context

This just started after receiving patches on Thursday, February 22nd.

**Comment by giacomocarrozzo** [comment]
did you find a solution?

**Comment by marty45714** [comment]
It stopped happening within a week. I’m assuming they either updated the pi
5 firmware or there was a package update that fixed it.

**Comment by popcornmix** [comment]
Closing as this is a not a linux kernel issue (and OP has reported it's no longer occurring).
If a repeatable case is still present (after updating) then post an issue [here](https://github.com/raspberrypi/bookworm-feedback/issues)
