### ISSUE TITLE
May 16 firmware: AIRPI i2c BMP085 and BMP180 temp and pressure sensors misread

### ISSUE THREAD

**Issue by g7ruh** [raspberrypi/linux#599]
May 16th firmware causes temp and pressure sensors to misread
![Uploading pressure reading issue.PNG . . .]()
![Uploading temp reading issue.PNG . . .]()

reverting to May 13th firmware fixes the problem. This is on 2 PIs here : https://xively.com/develop/a73wzKTeenrmwkbKnrZq and here https://xively.com/develop/5sS4LOiW-HpUN0kuPKG0 Note that the graphs show average so take time to "change". Viewing raw data shows fix works.

reposted here as requested by popcornmix

**Comment by popcornmix** [comment]
Looks to be caused by:
https://github.com/raspberrypi/linux/pull/318

@cbeytas can you help with this?

**Comment by cinhil** [comment]
Hello,
I also have i2c issues since 16 May firmware. Reverting to 13th May fixes the problem.
I have sometimes read and write problem on RTC clock ds1307. It fails in 10% of read/write test.

**Comment by cinhil** [comment]
Hello,
With a revert of "Perform I2C combined transactions when possible" commit, I do not have any problem with the RTC DS1307 anymore.
Regards,

**Comment by Swap-File** [comment]
I also have i2c issues with my Minimu9  http://www.pololu.com/product/1268  running Minimu9-ahrs https://github.com/DavidEGrayson/minimu9-ahrs since the May 16th firmware.  I reverted to May 13th firmware and it fixed it.

**Comment by popcornmix** [comment]
The combined I2C transactions commit is now disabled by default.
Please run rpi-update and test.

**Comment by g7ruh** [comment]
Hi popcornmix,

updated and tested, all back to normal, many thanks for all your hard work making the pi GREAT (and others too)

Roger aka G7RUH

**Comment by popcornmix** [comment]
Exellent. Okay to close?

**Comment by Swap-File** [comment]
It's tested and working for me too.  Thanks!

**Comment by g7ruh** [comment]
Thanks Swap-File too.
Popcornmix, fine to close.
