### ISSUE TITLE
USB/LAN issues with USB hub

### ISSUE THREAD

**Issue by blackarchon** [raspberrypi/linux#60]
RPi usb problems

I'm using the official Raspbian image from the Foundation. This means with the following kernel:

$ uname -a
Linux raspberrypi 3.1.9+ #168 PREEMPT Sat Jul 14 18:56:31 BST 2012 armv6l GNU/Linux

Let me start with what works:
- Plugging my two USB wireless transceivers directly into the Pi (these two devices are from a Logitech K360 keyboard and a Logitech M570 mouse, both have the same IDs of 046d:c52b)
- using a Logilink 7 port USB hub (2x Genesys Logic chipset, 05e3:0608, which is on the known good USB hub list on http://elinux.org/RPi_VerifiedPeripherals#Working_USB_Hubs) which is plugged on one of the Pi's USB ports. Then plugging in one of the two mentioned wireless transceivers.

What doesn't work:
- using both of these wireless transceivers on the hub
- using the hub and plugging one of the transceivers on the hub, the other on the Pi itself
  In both of these cases the network connection has quite some problems and breaks down:

Jul 19 18:52:09 raspberrypi kernel: [ 2476.241913] usb 1-1.2.2: new full speed USB device number 8 using dwc_otg
Jul 19 18:52:10 raspberrypi kernel: [ 2476.345837] usb 1-1.2.2: New USB device found, idVendor=046d, idProduct=c52f
Jul 19 18:52:10 raspberrypi kernel: [ 2476.345883] usb 1-1.2.2: New USB device strings: Mfr=1, Product=2, SerialNumber=0
Jul 19 18:52:10 raspberrypi kernel: [ 2476.345905] usb 1-1.2.2: Product: USB Receiver
Jul 19 18:52:10 raspberrypi kernel: [ 2476.345921] usb 1-1.2.2: Manufacturer: Logitech
Jul 19 18:52:10 raspberrypi kernel: [ 2476.365082] input: Logitech USB Receiver as /devices/platform/bcm2708_usb/usb1/1-1/1-1.2/1-1.2.2/1-1.2.2:1.0/input/input2
Jul 19 18:52:10 raspberrypi kernel: [ 2476.368645] generic-usb 0003:046D:C52F.0004: input: USB HID v1.11 Mouse [Logitech USB Receiver] on usb-bcm2708_usb-1.2.2/input0
Jul 19 18:52:10 raspberrypi kernel: [ 2476.384890] input: Logitech USB Receiver as /devices/platform/bcm2708_usb/usb1/1-1/1-1.2/1-1.2.2/1-1.2.2:1.1/input/input3
Jul 19 18:52:10 raspberrypi kernel: [ 2476.386935] generic-usb 0003:046D:C52F.0005: input,hiddev0: USB HID v1.11 Device [Logitech USB Receiver] on usb-bcm2708_usb-1.2.2/input1
Jul 19 18:52:20 raspberrypi kernel: [ 2486.391748] smsc95xx 1-1.1:1.0: eth0: Failed to read register index 0x00000118
Jul 19 18:52:26 raspberrypi kernel: [ 2492.401868] smsc95xx 1-1.1:1.0: eth0: Failed to write register index 0x00000114
Jul 19 18:52:31 raspberrypi kernel: [ 2497.401969] smsc95xx 1-1.1:1.0: eth0: Failed to read register index 0x00000114
Jul 19 18:52:38 raspberrypi kernel: [ 2504.432119] smsc95xx 1-1.1:1.0: eth0: Failed to read register index 0x00000114
Jul 19 18:52:38 raspberrypi kernel: [ 2504.432156] smsc95xx 1-1.1:1.0: eth0: MII is busy in smsc95xx_mdio_read
Jul 19 18:52:43 raspberrypi kernel: [ 2509.502198] smsc95xx 1-1.1:1.0: eth0: Failed to write register index 0x00000114
Jul 19 18:52:48 raspberrypi kernel: [ 2514.662035] usb 1-1.2.2: USB disconnect, device number 8

Another tested wireless transceiver from a Logitech M185 (as shown) with 046d:c52f shows the same behaviour.
If both of these transceivers are already plugged in when the Pi boots, the LAN chip isn't working at all ("RTNETLINK answers: Unknown error 4008" when running "dhclient eth0")!

As soon as I unplug one of the two USB wireless transceivers, everything gets back to normal:

Jul 19 19:08:44 raspberrypi kernel: [ 3470.294650] smsc95xx 1-1.1:1.0: eth0: Failed to write register index 0x00000114
Jul 19 19:08:49 raspberrypi kernel: [ 3475.294761] smsc95xx 1-1.1:1.0: eth0: Failed to read register index 0x00000114
Jul 19 19:08:54 raspberrypi kernel: [ 3480.294904] smsc95xx 1-1.1:1.0: eth0: Failed to read register index 0x00000118
Jul 19 19:08:59 raspberrypi kernel: [ 3485.295015] smsc95xx 1-1.1:1.0: eth0: Failed to read register index 0x00000114
Jul 19 19:09:04 raspberrypi kernel: [ 3490.295129] smsc95xx 1-1.1:1.0: eth0: Failed to write register index 0x00000114
Jul 19 19:09:09 raspberrypi kernel: [ 3495.295251] smsc95xx 1-1.1:1.0: eth0: Failed to read register index 0x00000114
Jul 19 19:09:14 raspberrypi kernel: [ 3500.295384] smsc95xx 1-1.1:1.0: eth0: Failed to read register index 0x00000118
Jul 19 19:09:19 raspberrypi kernel: [ 3505.295515] smsc95xx 1-1.1:1.0: eth0: Failed to read register index 0x00000114
Jul 19 19:09:33 raspberrypi kernel: [ 3519.395813] smsc95xx 1-1.1:1.0: eth0: Failed to write register index 0x00000008
Jul 19 19:09:33 raspberrypi kernel: [ 3519.395896] smsc95xx 1-1.1:1.0: eth0: Failed to read register index 0x00000114
Jul 19 19:09:39 raspberrypi kernel: [ 3525.405978] smsc95xx 1-1.1:1.0: eth0: Failed to read register index 0x00000114
Jul 19 19:09:44 raspberrypi kernel: [ 3531.146107] smsc95xx 1-1.1:1.0: eth0: Failed to read register index 0x00000114
Jul 19 19:09:51 raspberrypi kernel: [ 3537.416253] smsc95xx 1-1.1:1.0: eth0: Failed to read register index 0x00000114
Jul 19 19:10:01 raspberrypi kernel: [ 3547.309062] usb 1-1.2.3.1: USB disconnect, device number 10
Jul 19 19:10:01 raspberrypi kernel: [ 3547.315758] smsc95xx 1-1.1:1.0: eth0: link up, 100Mbps, full-duplex, lpa 0xCDE1
Jul 19 19:10:01 raspberrypi kernel: [ 3547.350002] smsc95xx 1-1.1:1.0: eth0: link up, 100Mbps, full-duplex, lpa 0xCDE1

I'm using a RPi from RS Online with their 1.2 A power supply. Please let me know if you need any further information.

**Comment by williamhbell** [comment]
Hi,

I see similar errors "smsc95xx 1-1.1:1.0: eth0:" when connecting to two different USB hubs.  In my case, I started with two different Raspberry PI setups:

(1) Raspberry PI, HDMI to DVI cable, DVI montor, cabled logitech keyboard and mouse connected directly to the PI, micro usb phone charger 2A, 5V.  This worked without error, downloading from the internet etc..  There were no errors in /var/log/messages

(2) Raspberry PI, HDMI to DVI cable (second cable), DVI montor (different monitor), cabled logitech keyboard and mouse (slightly different model) connected directly to the PI, micro usb phone charger 0.7A, 5V.  This worked without error, downloading from the internet etc..  There were no errors in /var/log/messages

Using the first setup, I swapped the cabling such that the keyboard and mouse were connected via a Trust 7 port powered hub (2A, 5V, HU-5870V), where the power was still going to the PI using the same micro-USB phone charger as before.  In this case the eth0 went down as smsc95xx errors started to appear.  Attempts to use ifconfig caused the Pi to hang.  The kernel was visibly struggling to handle the errors.  Removing the hub and switching back to connecting the keyboard and mouse directly to the Pi removed the errors.  The experiment was completely repeatable.  While the eth0 went down, the keyboard and mouse worked through the USB-hub as expected.

Using the second setup I did a similar thing, but with a slightly different brand of hub and keyboard and model model.  The same effects were seen.

As a side comment the noise of imaging via the HDMI connector can be heard clearly when a set of Trust USB powered speakers (Trust Universe 2.0 Speaker Set) is plugged into the Pi's audio out and the USB-hub which is connected to the Pi.  The noise seems to come across from the USB connection between the Pi and the USB-hub.  Removing the USB connection from the Pi to the USB-hub removed the noise which was being transmitted to the speakers.  It looks like the Pi needs to be grounded or the USB power should be isolated from the mini-hub.  I do not know if the noise is related to the smsc95xx errors.

Regards,

Will

**Comment by ckuetbach** [comment]
This looks like issue29 https://github.com/raspberrypi/linux/issues/29

I think there may be a connection between this two issues.

**Comment by williamhbell** [comment]
Hi ckuetbach,

There are some similar posts in https://github.com/raspberrypi/linux/issues/29, but many other errors also.  The problem I reported above looks like it might be caused by electrical problems or drivers, since the same keyboard and mouse work successfully when connected directly to the PI.  In the Raspbian forum there is some more information,
http://www.raspberrypi.org/phpBB3/viewtopic.php?f=66&t=11971

It might be the USB drivers, but I would like to rule out the electrical noise problems first.

Regards,

Will

**Comment by huaraz** [comment]
Hi,

I used the initial OS : Linux raspberrypi 3.1.9+ #90 Wed Apr 18 18:23:05 BST 2012 armv6l GNU/Linux
where the Ethernet worked fine, but when I upgraded to the lates Raspbian : Linux raspberrypi 3.1.9+ #168 PREEMPT Sat Jul 14 18:56:31 BST 2012 armv6l GNU/Linux
my ethernet fails and finally the pi hangs. I see the following during boot with an ethernet cable connected:

[ 12.090143] smsc95xx v1.0.4
[ 12.363479] EXT4-fs (mmcblk0p2): re-mounted. Opts: (null)
[ 12.867523] ### snd_bcm2835_alsa_probe c05d07a0 ############### PROBING FOR bcm2835 ALSA device (0):(1) ###############
[ 12.883880] Creating card...
[ 12.889381] Creating device/chip ..
[ 12.896040] Adding controls ..
[ 12.901544] Registering card ....
[ 12.913401] bcm2835 ALSA CARD CREATED!
[ 12.920452] ### BCM2835 ALSA driver init OK ###
[ 17.173108] smsc95xx 1-1.1:1.0: eth0: Failed to read register index 0x00000130
[ 17.184816] smsc95xx 1-1.1:1.0: eth0: Failed to read COE_CR: -110
[ 17.193324] smsc95xx 1-1.1:1.0: eth0: set_features() failed (-110); wanted 0x60004008, left 0x60004808
[ 17.213314] smsc95xx 1-1.1:1.0: eth0: register 'smsc95xx' at usb-bcm2708_usb-1.1, smsc95xx USB 2.0 Ethernet, b8:27:eb:44:55:31
[ 17.251836] usb 1-1: USB disconnect, device number 4
[ 17.273231] usb 1-1.1: USB disconnect, device number 5
[ 17.280933] smsc95xx 1-1.1:1.0: eth0: unregister 'smsc95xx' usb-bcm2708_usb-1.1, smsc95xx USB 2.0 Ethernet
[ 17.753334] usb 1-1: new high speed USB device number 6 using dwc_otg
[ 18.163771] usb 1-1: New USB device found, idVendor=0424, idProduct=9512
[ 18.203259] usb 1-1: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[ 18.239978] hub 1-1:1.0: USB hub found
[ 18.263974] hub 1-1:1.0: 3 ports detected
[ 18.583532] usb 1-1.1: new high speed USB device number 7 using dwc_otg
[ 18.713650] usb 1-1.1: New USB device found, idVendor=0424, idProduct=ec00
[ 18.743251] usb 1-1.1: New USB device strings: Mfr=0, Product=0, SerialNumber=0
[ 18.775979] smsc95xx v1.0.4
[ 18.864558] smsc95xx 1-1.1:1.0: eth0: register 'smsc95xx' at usb-bcm2708_usb-1.1, smsc95xx USB 2.0 Ethernet, b8:27:eb:44:55:31

Markus

**Comment by perone** [comment]
Just to give some feedback, I had the same problem and everything started to work fine after I have changed my power supply, my power supply was signaling 5.34V when the problem happened.

**Comment by huaraz** [comment]
Yes it looks like a power supply issue. I changed from a Hama to a HNP06 USB power supply and it looks stable now.

Thank you
Markus

**Comment by ckuetbach** [comment]
What HAMA did you use? I have a HAMA powersupply, too.

**Comment by huaraz** [comment]
The HAMA is a 73014050 USB charger. 

Input 100-120V ~ 50/60Hz 200mA
Outpt 5.0V 1000mA
Model GPE060B-050100-Z

Regards
Markus

**Comment by popcornmix** [comment]
Can you try with latest firmware and with:
dwc_otg.microframe_schedule=1
in cmdline.txt?

**Comment by huaraz** [comment]
> Can you try with latest firmware and with:
> dwc_otg.microframe_schedule=1
> in cmdline.txt?

Wher do I get the new firmware and how do I install it ?

Markus

**Comment by popcornmix** [comment]
http://elinux.org/R-Pi_Troubleshooting#Updating_firmware

**Comment by nomis05** [comment]
I have the same problem with the smsc95xx failed to write register index error on the official Raspbian release. 
I'm using a sitecom 4 Port powered Usb hub and i'm trying to connect a tp link wifi adapter with it. When it's connected from the beginning the pi will hang on boot giving the errors until i disconnect the wifi device.

I'm using OpenElec and XBian on another SD Card. With the SAME SETUP everything is working fine and I have a good wifi connection and no smsc95xx error. Even this raspbian release works:
http://www.linuxsystems.it/2012/06/raspbian-wheezy-armhf-raspberry-pi-minimal-image/

So my conclusion is that it has somethign to do with the official raspbian release!

**Comment by asb** [comment]
What are the kernel versions for the Foundation Raspbian release
you're using and e.g. the xbian. uname -a should do the trick. I also
refreshed the 'bleeding edge' firmware last night
http://www.raspberrypi.org/phpBB3/viewtopic.php?t=12170&f=66

**Comment by nomis05** [comment]
Ah perfect. Thank you very much. With the untested firmware it works now :) !

**Comment by cioc** [comment]
Raspberry pi network chip (SMSC LAN9514) is connected via usb to the SoC 
~https://www.raspberrypi.org/magpi/raspberry-pi-3-specs-benchmarks/

Wireless is different chip, made by broadcom (Broadcom BCM43438) like the SoC. 
~https://www.raspberrypi.org/magpi/raspberry-pi-3-specs-benchmarks/

Not connected via usb: "Key high-throughput mobility interfaces, including SDIO 3.0, PCIe® and HSIC, make it suitable for smartphone, tablet and computing platforms"
~https://www.broadcom.com/products/wireless/wireless-lan-infrastructure/bcm4335#overview


So, USB problems can have major impact on ethernet but less so on wireless.

**Comment by cioc** [comment]
Older Pi versions had stuck ethernet, guy implemented ifdown-ifup cron job: https://samhobbs.co.uk/2013/11/fix-for-ethernet-connection-drop-on-raspberry-pi

**Comment by JamesH65** [comment]
Have you got an issue that need resolving? This issue has been closed for some time. If you have another issues, please check the forums, ask questions there, if there is a bug/issue, please create a new one here.
