### ISSUE TITLE
I can't color

### ISSUE THREAD

**Issue by MarcelaSantosTech** [raspberrypi/linux#6000]
### Describe the bug

I had a bug when I was trying to set the red color

### Steps to reproduce the behaviour

take your raspberrypi and activate the red color

### Device (s)

Raspberry Pi Zero, Raspberry Pi Zero W / WH

### System

cat /etc/rpi-issue

**Comment by MarcelaSantosTech** [comment]
I've fixed it!

**Comment by MarcelaSantosTech** [comment]
I had the same problem again

**Comment by popcornmix** [comment]
Help questions should be asked in [the forum](https://forums.raspberrypi.com/viewforum.php?f=91).
