### ISSUE TITLE
Support of rtc-pcf2127a

### ISSUE THREAD

**Issue by radjah** [raspberrypi/linux#605]
Can you add this patch? https://github.com/afterthoughtsoftware/linux/commit/2b6f2a465d25f770c24883e398a8c55b1ec016a2
https://github.com/afterthoughtsoftware/linux/commit/2b6f2a465d25f770c24883e398a8c55b1ec016a2.patch

**Comment by popcornmix** [comment]
Latest kernel has PCF2127 module enabled - does that not work?

**Comment by radjah** [comment]
No, PCF2127 does not recognize the existence of PCF2127A.
I'll try to compile a kernel 3/12/20 + with this patch and check the functioning PCF2127A. 
I found instructions on how to compile the kernel 3.10+ with this patch

**Comment by popcornmix** [comment]
We generally don't support out of tree patches.
If you want the linked patch supported, it should be submitted to upstream kernel, and we can pull it in.
https://www.kernel.org/doc/Documentation/SubmittingPatches

**Comment by moonman** [comment]
The patch you provided is for kernel 3.6. RasClock has been working perfectly fine with the in-tree driver since a long time ago: http://archlinuxarm.org/forum/viewtopic.php?f=31&t=5819&start=10#p35316 . This report is invalid.
