### ISSUE TITLE
I2C combined transactions broken

### ISSUE THREAD

**Issue by ghost** [raspberrypi/linux#607]
With the new combined transactions for the I2C controller introduced with commit a5ca1aafc34027e6877163028f2d47dfd223b16b, i2c read operations return incorrect results:
See this example:

sudo i2cget -y 1 0x3b 0
0x11
sudo i2cget -y 1 0x3b 0
0x88
sudo i2cget -y 1 0x3b 0
0x05

The register 0 always contained the value "0x05", but the correct value had been returned only on the third read operation. I have check the I2C communication with the scope, the device returned 0x05 on all 3 read operations.

With combined transactions disabled by default after commit b9a86b036ec71f080e0296f7bcb4c2c1ed9b9679, I2C reads are working again. 

The bug must therefore be in the combined transaction code. This should be fixed as enabling these combined transactions might break support for lots of I2C devices. I can confirm that this problem broke the HiFiBerry Digi/wm8804 driver. 

If needed, I can provide test hardware to the developer, but I guess, the same issue happens with other I2C devices too.

**Comment by popcornmix** [comment]
I'm not understanding the problem.
By default combined transactions are disbabled, and so everything works, correct?

**Comment by ghost** [comment]
Yes, everything works again. But the code is still in the driver. If somebody enables combined transactions later, the problem will be back. Therefore the problematic code should be fixed or completely removed.

**Comment by popcornmix** [comment]
Some use cases benefit from enabling the combined transactions so I see no necessity to remove that as an option.

**Comment by ghost** [comment]
I agree on this. Therefore I recommend the author of this code fixes the bug. I'm not in I2C expert, but even with combined transactions, read operations should return the correct results. Or is this behavior expected with combined transactions?

**Comment by ghost** [comment]
I will have a look at the code and try to find the problem.

**Comment by popcornmix** [comment]
Ideal behaviour is that the combined=1 module parameter is removed and it works with all devices (utilising combined transaction where possible).

But I don't know much about I2C or this driver so would appreciate any fixes that improve the behaviour.

**Comment by ghost** [comment]
Fully agree. I will try to find the bug.

**Comment by popcornmix** [comment]
Closing as default behaviour works. Optional behaviour should be avoided if it causes problems.
Please submit a pull request if you have a way of improving behaviour.
