### ISSUE TITLE
traffic control not working

### ISSUE THREAD

**Issue by ksacry** [raspberrypi/linux#61]
I'm trying to use tc and it's not working:

root@raspberrypi:~# tc -s qdisc show
RTNETLINK answers: Operation not supported
Dump terminated

I believe the needed kernel options are:

CONFIG_IP_ADVANCED_ROUTER
and
NET_SCH_INGRES

Can you turn these on in the next build?

**Comment by ksacry** [comment]
I recompiled the kernel and got this working.
I ended up needing the following for my purposes, not sure if this would help any body else

CONFIG_NET_SCHED=y
  CONFIG_NET_SCH_CBQ=y
  CONFIG_NET_SCH_HTB=y
  CONFIG_NET_SCH_HFSC=m
  CONFIG_NET_SCH_PRIO=y
  CONFIG_NET_SCH_MULTIQ=m
  CONFIG_NET_SCH_RED=m
  CONFIG_NET_SCH_SFB=m
  CONFIG_NET_SCH_SFQ=m
  CONFIG_NET_SCH_TEQL=m
  CONFIG_NET_SCH_TBF=y
  CONFIG_NET_SCH_MQPRIO=m

  CONFIG_NET_SCH_QFQ=m
  CONFIG_NET_CLS=y

  CONFIG_NET_CLS_TCINDEX=y
  CONFIG_NET_CLS_ROUTE4=y
  CONFIG_NET_CLS_FW=y
  CONFIG_NET_CLS_U32=m
  CONFIG_CLS_U32_PERF=y
  CONFIG_CLS_U32_MARK=y

**Comment by popcornmix** [comment]
This should be in latest kernel. Please test and close.

**Comment by ksacry** [comment]
confirmed fixed
