### ISSUE TITLE
dts: missing SPDX-License-Identifier in rp1.dtsi

### ISSUE THREAD

**Issue by delgh1** [raspberrypi/linux#6119]
### Describe the bug

`arch/arm/boot/dts/broadcom/rp1.dtsi` doesn't have an SPDX-License-Identifier or a copyright notice. Is this intentional? Is this file non-free? I hope not. Either way, if it has no SPDX-License-Identifier or copyright notice, it could slow down the process of RPI5 being supported by mainline (we want this right?), because both `bcm2712-rpi-5-b.dts` and `bcm2712-rpi-cm5.dtsi` include `rp1.dtsi`.

### Steps to reproduce the behaviour

N/A

### Device (s)

Other

### System

[https://github.com/raspberrypi/linux/blob/rpi-6.6.y/arch/arm/boot/dts/broadcom/rp1.dtsi](https://github.com/raspberrypi/linux/blob/rpi-6.6.y/arch/arm/boot/dts/broadcom/rp1.dtsi)

**Comment by pelwell** [comment]
There are plenty of files in that directory without SPDX declarations and copyright, and the majority of them are in the upstream kernel. The thought that the lack of SPDX declaration would be anything more than a one line comment in the feedback on rp1.dtsi is fanciful.

Of course it's not deliberate, and of course the information can be copied.

**Comment by 6by9** [comment]
The lack of an SPDX header is very minor in the scope of upstreaming all the relevant modules for Pi5.

We are working on upstreaming the relevant drivers, but it's not a trivial task.
3rd parties randomly sending the downstream DT and drivers will generally get fairly terse responses (eg https://lore.kernel.org/linux-arm-kernel/cover.1713036964.git.andrea.porta@suse.com/)

We know the downstream patches are not perfect, and will be fixing them up as upstreaming progresses.
