### ISSUE TITLE
3.13.y-next missing support for configuring w1-gpio pin 

### ISSUE THREAD

**Issue by anaconda** [raspberrypi/linux#613]
See #457.

Commit: 0dd803a572ee4fe5c8539c79069e85013d2b0d71 (note: it's 3.10.y)

Someone reported (xbianonpi/xbian#550) they aren't able to set the GPIO pin on 3.13.7, which appears to be rpi-3.13.y-next and it's indeed missing that code. Though XBian should probably switch to the more up to date rpi-3.13.y branch, I see no harm in adding this. All other branches have that commit, except 3.13.y-next.

**Comment by popcornmix** [comment]
The "-next" branches are just temporarily updated for testing a new feature (e.q. fiq fsm usb driver).
Once testing is positive the new feature goes into the main branch, and "-next" will get no further updates.

Projects really shouldn't use "-next" trees for more than test builds.

Also, note that generally only two branches will be actively supported, stable and latest.
"stable" is currently 3.12 (usually latest kernel with LTS)
"latest" is 3.14 (latest kernel that is considered stable upstream). Is likely to switch to 3.15 imminently.

I would recommend that XBian chooses either "stable" or "latest". Any other tree will stop getting updates.

**Comment by anaconda** [comment]
Yeah, I already opened an issue to switch to the rpi-3.13.y branch (it's only for the devel repository, we're on rpi-3.12.y for stable).

I interpreted "-next" as "new releases go there and if everything's ok they go to rpi-3.13.y". I was indeed surprised it wasn't getting updates. (Mind to write this down in a README.raspberrypi/GIT-BRANCHES.rpi?)
