### ISSUE TITLE
Kernel Rebuilds - difference from normal Linux kernel

### ISSUE THREAD

**Issue by slackhead** [raspberrypi/linux#614]
Hi. This is more a question than anything. I've noticed over the years that when doing a rebuild of the normal linux kernel after making small changes that the subsequent rebuild will be quite fast. Perhaps taking only a few minutes in all.

This doesn't seem to be the case with the RPI kernel though, which seems to build from scratch every time, so I'd like to ask why is this, and is there any way of making it behave more like the normal linux kernel?

**Comment by popcornmix** [comment]
Small changes result in quick rebuilds for me.
Are you building on Pi, or cross compiling?
Anyone else seen this?

**Comment by popcornmix** [comment]
Closing as no response and I don't believe there is an issue with kernel makefile.
