### ISSUE TITLE
Wider M.2 NVMe ssd support

### ISSUE THREAD

**Issue by malteneuss** [raspberrypi/linux#6152]
### Describe the bug

A lot of NVMe ssd's aren't recognized with `lsblk` or `lspci` on several Pi Hats and adapters.
My impression is that all hats and adapter have a few common ssd models that work, and many that don't work or aren't listed. 

Can the Kernel somehow be adapted to support more ssds? https://github.com/raspberrypi/linux/issues/5873 made me hopeful that this could be possible.

### Steps to reproduce the behaviour

E.g. ARGON 40 Neo 5 case with Kingston SN2S NVMe ssd.

### Device (s)

Raspberry Pi 5

### System

Latest official Raspberry Pi OS (debian)

**Comment by timg236** [comment]
The best place to discuss general interoperabbility issues is the Raspberry Pi forums e.g. the Troubleshooting forum
https://forums.raspberrypi.com/viewforum.php?f=28

Github Issues are for specific bug reports / software reports
