### ISSUE TITLE
No IPv6 address set up after update to kernel 3.12.22+

### ISSUE THREAD

**Issue by daincredibleholg** [raspberrypi/linux#619]
Due to problems described in #612 I updated to the new kernel 3.12.22+. Now, I can set up the security extensions, but no IPv6 address is generated / assigned to my eth0 device. Both, lo and eth0, have a local address. The IPv6 module is loaded, too. Several restarts and interface restarts haven't fixed the issue.

**Comment by popcornmix** [comment]
I don't have an IPv6 capable network.
Anyone else using IPv6? Is it still working with latest (3.12.22) kernel?

**Comment by daincredibleholg** [comment]
Hi, if you are interested in, you can get free IPv6 connections from HE (tunnelbroker.net) or gogo6 (www.gogo6.com/freenet6/tunnelbroker).

What do you mean, is it working with 3.12.22. The 3.12.22+ is the one, I got from rpi-update. The 3.12.20+ had no problem with IPv6 addres resolution. The only problem there was the lack of the IPv6 security extensions.

**Comment by vk5tu** [comment]
popcornmix wrote:

> Anyone else using IPv6? Is it still working with latest (3.12.22) kernel?

Let's see.

Starting with a stock system, up to date with
  apt-get update && apt-get dist-upgrade

Commented out all lines in /etc/modprobe.d/ipv6.conf
Unchanged /etc/network/interfaces
Rebooted
eth0 is a wired connection to a switch on a IPv6 SLAAC subnet with global 
connectivity.

pi@raspberrypi ~ $ uname -a
Linux raspberrypi 3.12.20+ #687 PREEMPT Fri May 30 16:39:11 BST 2014 
armv6l GNU/Linux

pi@raspberrypi ~ $ ip -f inet6 addr show dev eth0
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qlen 1000
    inet6 2001:44b8:1d2:bb00:ba27:ebff:fe44:fc6d/64 scope global dynamic 
       valid_lft 86290sec preferred_lft 14290sec
    inet6 fe80::ba27:ebff:fe44:fc6d/64 scope link 
       valid_lft forever preferred_lft forever

Update to latest kernel.

pi@raspberrypi ~ $ sudo rpi-update
pi@raspberrypi ~ $ sudo shutdown -r now

Test

pi@raspberrypi ~ $ uname -a
Linux raspberrypi 3.12.22+ #690 PREEMPT Mon Jun 16 13:25:46 BST 2014 
armv6l GNU/Linux

pi@raspberrypi ~ $ ip -f inet6 addr show dev eth0
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qlen 1000
    inet6 2001:44b8:1d2:bb00:ba27:ebff:fe44:fc6d/64 scope global dynamic 
       valid_lft 86331sec preferred_lft 14331sec
    inet6 fe80::ba27:ebff:fe44:fc6d/64 scope link 
       valid_lft forever preferred_lft forever

pi@raspberrypi ~ $ ping6 www.google.com
PING www.google.com(2404:6800:4006:804::1013) 56 data bytes
64 bytes from 2404:6800:4006:804::1013: icmp_seq=1 ttl=55 time=55.2 ms
64 bytes from 2404:6800:4006:804::1013: icmp_seq=2 ttl=55 time=57.8 ms
^C
--- www.google.com ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1001ms
rtt min/avg/max/mdev = 55.214/56.549/57.885/1.356 ms

Cheers, glen

## 

Glen Turner http://www.gdt.id.au/~gdt/

**Comment by daincredibleholg** [comment]
Hmm, ok - it looks like a problem that do not appear everywhere.

I've just re-checked my config. Here is my /etc/modprobe.d/ipv6.conf

```
# Don't load ipv6 by default
#alias net-pf-10 off
#alias ipv6 off
```

Here is my module list:

```
Module                  Size  Used by
xt_hl                   1265  6 
ip6t_rt                 2080  3 
nf_conntrack_ipv6       7718  7 
nf_defrag_ipv6         10538  1 nf_conntrack_ipv6
ipt_REJECT              2322  1 
xt_LOG                 11812  9 
xt_limit                1550  12 
xt_tcpudp               2106  30 
xt_addrtype             2689  4 
nf_conntrack_ipv4      12871  7 
nf_defrag_ipv4          1487  1 nf_conntrack_ipv4
xt_state                1174  14 
ip6table_filter         1449  1 
ip6_tables             11945  1 ip6table_filter
nf_conntrack_netbios_ns     1137  0 
nf_conntrack_broadcast     1207  1 nf_conntrack_netbios_ns
nf_nat_ftp              1865  0 
nf_nat                 14710  1 nf_nat_ftp
nf_conntrack_ftp        6777  1 nf_nat_ftp
nf_conntrack           86703  8 nf_nat_ftp,nf_conntrack_netbios_ns,nf_nat,xt_state,nf_conntrack_broadcast,nf_conntrack_ftp,nf_conntrack_ipv4,nf_conntrack_ipv6
iptable_filter          1508  1 
ip_tables              11725  1 iptable_filter
x_tables               17020  12 ip6table_filter,xt_hl,ip_tables,xt_tcpudp,xt_limit,xt_state,xt_LOG,iptable_filter,ip6t_rt,ipt_REJECT,ip6_tables,xt_addrtype
ipv6                  312804  24 nf_defrag_ipv6,nf_conntrack_ipv6
snd_bcm2835            18169  0 
snd_soc_bcm2708_i2s     5486  0 
regmap_mmio             2818  1 snd_soc_bcm2708_i2s
snd_soc_core          128166  1 snd_soc_bcm2708_i2s
snd_compress            8136  1 snd_soc_core
regmap_i2c              1657  1 snd_soc_core
snd_pcm_dmaengine       5481  1 snd_soc_core
regmap_spi              1913  1 snd_soc_core
snd_pcm                81518  3 snd_bcm2835,snd_soc_core,snd_pcm_dmaengine
snd_page_alloc          5168  1 snd_pcm
snd_seq                54581  0 
snd_seq_device          6485  1 snd_seq
snd_timer              20353  2 snd_pcm,snd_seq
leds_gpio               2055  0 
led_class               4119  1 leds_gpio
snd                    61518  7 snd_bcm2835,snd_soc_core,snd_timer,snd_pcm,snd_seq,snd_seq_device,snd_compress
cp210x                  8279  3 
usbserial              26435  7 cp210x
```

My interfaces say:

```
pi@incrediblepione ~ $  ip -f inet6 addr show dev eth0
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qlen 1000
    inet6 fe80::ba27:ebff:fe85:bf0e/64 scope link 
       valid_lft forever preferred_lft forever
```

My other laptops (running Ubuntu) have IPv6 connectivity. Very strange.

I am using a SixXS tunnel for IPv6 connectivity. That tunnel is managed by my AVM FritzBox 7390. Configuration is also SLAAC.

**Comment by vk5tu** [comment]
@daincredibleholg So you have a link local address (which is assigned by the host) and no global address (which requires a router advertisment to be heard).

Firstly, check that the link-local address is reachable by other machines on the same subnet. For example:

```
pi@raspberrypi ~ $ ip -f inet6 addr show dev eth0 scope link
2: eth0:<BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qlen 1000
    inet6 fe80::1234:5678:8765:4322/64 scope link 
       valid_lft forever preferred_lft forever
```

```
pi@raspberrypi ~ $ ping6 -I eth0  fe80::1234:5678:8765:4321
PING fe80::1234:5678::8765:4321(fe80::1234:5678::8765:4321) from fe80::1234:5678::8765:4322 eth0: 56 data bytes
64 bytes from fe80::1234:5678::8765:4321: icmp_seq=1 ttl=64 time=1.36 ms
64 bytes from fe80::1234:5678::8765:4321: icmp_seq=2 ttl=64 time=1.11 ms
^C
--- fe80::1234:5678::8765:4321 ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1001ms
rtt min/avg/max/mdev = 1.116/1.239/1.363/0.128 ms
```

It would be well worthwhile trying to ping6 the link-local address of the router from the RaspberryPi, and vice-versa.

If you need to debug a lack of link-local connectivity then you can use `ip -f inet6 neigh show` to display the neighbour (aka "ARP") cache. You should be looking for faulty ports, VLAN mis-allocations, WPA2 failures and the like.

Secondly, check that you can get a router advertisement. rdisc6 is a user-space utility which simulates SLAAC:

```
pi@raspberrypi ~ $ sudo apt-get install ndisc6

pi@raspberrypi ~ $ rdisc6 -n eth0
Soliciting ff02::2 (ff02::2) on eth0...
Hop limit                 :           64 (      0x40)
Stateful address conf.    :           No
Stateful other conf.      :           No
Router preference         :         high
Router lifetime           :         1800 (0x00000708) seconds
Reachable time            :  unspecified (0x00000000)
Retransmit time           :  unspecified (0x00000000)
 Prefix                   : 2001:1234:5678:9a00::/64
  Valid time              :        86400 (0x00015180) seconds
  Pref. time              :        14400 (0x00003840) seconds
 Recursive DNS server     : 2001:1234:5678:9a00::1
  DNS server lifetime     :          600 (0x00000258) seconds
 MTU                      :         1500 bytes (valid)
 Source link-layer address: B8:12:34:56:78:9a
 from fe80::1234:5678:1234:5678
```

If this fails then use packet capture tool like `wireshark -n -i eth0` to look at the traffic on the wire.

If this succeeds then check `sysctl -a` to make sure you haven't disabled SLAAC by selecting some other IPv6 feature (the Linux IPv6 implementation is notorious for toggling sysctls, thinking it knows better than the sysadmin).

```
pi@raspberrypi ~ $ sudo sysctl -a | grep eth0.accept_ra
net.ipv6.conf.eth0.accept_ra = 1
net.ipv6.conf.eth0.accept_ra_defrtr = 1
net.ipv6.conf.eth0.accept_ra_pinfo = 1
```

**Comment by daincredibleholg** [comment]
@vk5tu: Thanks for your detailed answer. I did your mentioned steps. It still looks like a problem on my pi. But lets start from the beginning.

I started from the bottom, because the last problem (the missing security extensions) were also due to some muddled sysctl settings. But everything looks good here:

```
pi@incrediblepione:/etc/icinga$ sudo sysctl sudo sysctl -a | grep eth0.accept_ra
net.ipv6.conf.eth0.accept_ra = 1
net.ipv6.conf.eth0.accept_ra_defrtr = 1
net.ipv6.conf.eth0.accept_ra_pinfo = 1
```

Next, I checked for any recognizable neighbors, successfully:

```
pi@incrediblepione:/etc/icinga$ ip -f inet6 neigh
fe80:: dev eth0 lladdr 18:87:96:89:ac:7b STALE
fe80::212:3fff:fe64:ca1d dev eth0 lladdr 00:12:3f:64:ca:1d STALE
fe80::1eb0:94ff:fe10:4e3 dev eth0 lladdr 1c:b0:94:10:04:e3 STALE
fe80::2665:11ff:fefd:dee1 dev eth0 lladdr 24:65:11:fd:de:e1 router STALE
fe80::ad4:2bff:fe18:f9f0 dev eth0 lladdr 08:d4:2b:18:f9:f0 STALE
fe80::2677:3ff:fe47:a254 dev eth0 lladdr 24:77:03:47:a2:54 STALE
fe80::221:63ff:fe78:479c dev eth0 lladdr 00:21:63:78:47:9c STALE
```

With this, I had my router's link-local address by the hand and tried to ping it:

```
ping6 -I eth0 fe80::2665:11ff:fefd:dee1
PING fe80::2665:11ff:fefd:dee1(fe80::2665:11ff:fefd:dee1) from fe80::ba27:ebff:fe85:bf0e eth0: 56 data bytes
64 bytes from fe80::2665:11ff:fefd:dee1: icmp_seq=1 ttl=64 time=9.95 ms
64 bytes from fe80::2665:11ff:fefd:dee1: icmp_seq=2 ttl=64 time=2.54 ms
--- fe80::2665:11ff:fefd:dee1 ping statistics ---
2 packets transmitted, 2 received, 0% packet loss, time 1001ms
rtt min/avg/max/mdev = 2.543/6.250/9.958/3.708 ms
```

So, rdisc6 was the next tool for checking. And here we go:

```
pi@incrediblepione:/etc/icinga$ rdisc6 -n eth0
Soliciting ff02::2 (ff02::2) on eth0...

Hop limit                 :          255 (      0xff)
Stateful address conf.    :           No
Stateful other conf.      :          Yes
Router preference         :         high
Router lifetime           :         1800 (0x00000708) seconds
Reachable time            :  unspecified (0x00000000)
Retransmit time           :  unspecified (0x00000000)
 Prefix                   : 2001:4dd0:ff00:90e5::/64
  Valid time              :         7200 (0x00001c20) seconds
  Pref. time              :         3600 (0x00000e10) seconds
 Recursive DNS server     : fd00::2665:11ff:fefd:dee1
  DNS server lifetime     :         1200 (0x000004b0) seconds
 MTU                      :         1280 bytes (valid)
 Route                    : ::/0
  Route preference        :         high
  Route lifetime          :         1800 (0x00000708) seconds
 Route                    : 2001:4dd0:ff00:90e5::/64
  Route preference        :         high
  Route lifetime          :         1800 (0x00000708) seconds
 Source link-layer address: 24:65:11:FD:DE:E1
 from fe80::2665:11ff:fefd:dee1
```

If I understand the latter output correct, I get the expected advertisement - but my link is still not prepared with a global address:

```
pi@incrediblepione:/etc/icinga$ ip -6 addr show eth0
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qlen 1000
    inet6 fe80::ba27:ebff:fe85:bf0e/64 scope link 
       valid_lft forever preferred_lft forever
```

Any further ideas?

**Comment by vk5tu** [comment]
@daincredibleholg Are you aware that `net.ipv6.conf.eth0.accept_ra = 1` has no effect if `net.ipv6.conf.eth0.forwarding = 1`? You might want to read the documentation for those two sysctls, especially for the values `net.ipv6.conf.eth0.accept_ra = 2`, `net.ipv6.conf.default.forwarding = 2`. If this is a standard host I strongly suggest that you set no IPv6 sysctls.

Furthermore, the RA is wrong. A RA implies that the sender has global reachability, and thus the host should insert a ::/0 route with a metric related to the RA's priority. Don't explicitly list ::/0 (and particularly not as a on-link route, because then the globe is accessible from the link local address and no configuration of a global address is required). Do explicitly list as a on-link route the /64 containing the host.

Also, why is the MTU 1280? The MTU in the RA applies to the interface MTU, not to a maxima for path MTUs. ICMP6 will inform the host of any path MTU less than the interface MTU (we are routing down that PPP link, not bridging like IPv4, so there is an opportunity for a router to generate the ICMP in IPv6 which may not be present in IPv4).

Here are my [notes](http://vk5tu.livejournal.com/37206.html). The uplink to the ISP is different to yours, but the downlink should be configured similarly.

It would probably be best to close this fault against the port of the Linux kernel to the RaspberryPi, as this seems to be a difficulty in configuring IPv6 rather than any fault in the port.

**Comment by daincredibleholg** [comment]
@vk5tu: You are right - the curious thing is, I haven't set up any of the *ra properties explicitly. But I have to configure my sysctl settings like this, to get IPv6 with working security extensions up and running:

```
net.ipv6.conf.default.use_tempaddr=1
net.ipv6.conf.all.use_tempaddr=1
net.ipv6.conf.all.accept_ra=2

net.ipv6.conf.eth0.use_tempaddr=1
```

So, to summarize: it looks more like a default configuration muddle than a kernel bug, isn't it?

**Comment by vk5tu** [comment]
What you actually want is `net.ipv6.conf.….use_tempaddr=2` so that privacy addresses are used for new connections. See the documentation in [ip-sysctl.txt](https://github.com/raspberrypi/linux/blob/rpi-3.12.y/Documentation/networking/ip-sysctl.txt).

Agreed, this is not a bug in porting the Linux kernel to the RPi.

**Comment by vk5tu** [comment]
@popcornmix Issue #619 resolved as configuration difficulty, please close at your convenience.
