### ISSUE TITLE
Would like CONFIG_USB_GSPCA_PAC207 to be enabled

### ISSUE THREAD

**Issue by soend** [raspberrypi/linux#62]
Hei, was trying to get my webcam to work, but noticed that CONFIG_USB_GSPCA_PAC207 is not enabled. Would really love if this option would be enabled.

Thanks.

**Comment by popcornmix** [comment]
It is enabled. You can check with:
zcat /proc/config.gz | grep PAC207  
CONFIG_USB_GSPCA_PAC207=m

**Comment by asb** [comment]
Closing.
