### ISSUE TITLE
Couldn't install Ubuntu / Raspberry Pi OS on WD_BLACK SN770M 1TB and Raspberry Pi M.2 HAT+

### ISSUE THREAD

**Issue by iamursky** [raspberrypi/linux#6232]
### Describe the bug

I couldn't install Ubuntu / Raspberry Pi OS on a WD_BLACK SN770M 1TB and a Raspberry Pi M.2 HAT+. The behavior varies for the first 2-3 boots, and most of the time it falls back to initramfs afterward. See the Logs section for captures made using a [Debug Probe](https://www.raspberrypi.com/products/debug-probe/), with comments at the top of each capture file explaining what happened.

### Steps to reproduce the behaviour

1. Set boot order to NVMe on Raspberry Pi
2. Write OS to the SSD using Raspberry Pi Imager
3. Install SSD and launch the board

### Devices

- [Raspberry Pi 5 8GB](https://www.raspberrypi.com/products/raspberry-pi-5/)
- [Raspberry Pi M.2 HAT+](https://www.raspberrypi.com/products/m2-hat-plus/)
- [Raspberry Pi 27W USB-C Power Supply](https://www.raspberrypi.com/products/27w-power-supply/)
- [WD_BLACK SN770M M.2 NVMe 1TB SSD](https://www.westerndigital.com/products/internal-drives/wd-black-sn770m-nvme-ssd?sku=WDBDNH0010BBK-WRSN)

### System

- Raspberry Pi OS (64-bit)
- Ubuntu Desktop 24.04 LTS (64-bit)

### Logs

- Ubuntu: https://gist.github.com/iamursky/1c7c25c751f97fce8f46a6ab755203d4
- Raspberry Pi OS: https://gist.github.com/iamursky/84f150bd435b08d26d457f4c8465f7fb

### Additional context

Forum post: https://forums.raspberrypi.com/viewtopic.php?t=372325

**Comment by kudouta** [comment]
In combination with the Raspberry Pi M.2 HAT+ and SN770M (500GB), I occasionally managed to improve startup by adding the following parameters:

1. Add the following parameters to the /boot/firmware/config.txt
dtparam=pciex1
dtparam=pciex1_gen=3

2. Append the following parameter to the end of the /boot/firmware/cmdline.txt
nvme_core.default_ps_max_latency_us=2500
![smart](https://github.com/raspberrypi/linux/assets/65069371/6aab05aa-b551-41fa-b3e8-c7b4c125a8c9)


If the green ACT LED on the HAT blinks at least once within 5 seconds during startup, it indicates a successful boot.
Unfortunately, I cannot provide serial logs since I don’t have a serial cable.

**Comment by kudouta** [comment]
### **Serial Logs**
- boot OK https://gist.github.com/kudouta/d1a82bb819ac20f56484927722e9d9a7
- boot NG https://gist.github.com/kudouta/2d2c851e84df34515d42eccd157a23ec

**Comment by iamursky** [comment]
I guess the dtparam was the missing piece since Raspberry Pi doesn't see WD_BLACK SN770M in Gen 2 mode. Here's I how I solved the issue:

1. Wrote Ubuntu to the SSD using [Raspberry Pi Imager](https://www.raspberrypi.com/software/). I used [SSD Docking Station](https://www.amazon.es/dp/B0BZ3L6PF3) to connect M.2 SSD to my Mac.
2. Added `dtparam=pciex1` and `dtparam=pciex1_gen=3` to the end of `config.txt` file in the root of SSD.

**Comment by pleich** [comment]
Hi, 
I am currently experiencing  the same / similar problem. I have a SN 770M 1TB and a raspberry pi 5 with m.2 hat +. As soon as I insert the NVME drive the Raspberry Pi is unable to boot. It is completely stuck without any output to HDMI. 

I have tried to reproduce the steps above, but cannot get the Pi to boot with the SSD installed. I also used an m.2 adapter and added the parameters to `boot/config.txt` without any success. 

Is there anything else you did try ? I also do not have access to a serial cable

**Comment by iamursky** [comment]
Try starting with a clean setup, but this time ensure the HDMI cable is unplugged when powering on the Raspberry Pi. Wait until the LED on the M.2 HAT+ stops blinking and then plug the HDMI back. I have a hunch that the SSD might not be getting enough power on the startup.

**Comment by Catch-XXII** [comment]
> Hi, I am currently experiencing the same / similar problem. I have a SN 770M 1TB and a raspberry pi 5 with m.2 hat +. As soon as I insert the NVME drive the Raspberry Pi is unable to boot. It is completely stuck without any output to HDMI.
> 
> I have tried to reproduce the steps above, but cannot get the Pi to boot with the SSD installed. I also used an m.2 adapter and added the parameters to `boot/config.txt` without any success.
> 
> Is there anything else you did try ? I also do not have access to a serial cable

you cannot modify those files from a pc with ssd adapter. instead you should change them when you have a microsd card installed rasp pi os with sudo nano command. nano is a text editor like notepad. sudo is your admin command. try first boot up without m.2 ssd . just plugin 32 or 64 microsd card to its slot. a fresh install then add those lines to config files. finally insert your hat with ssd when your device is fully TURNED OFF dont try it when it is on. good luck

**Comment by pleich** [comment]
Thanks for the attempt to help, but I have given up wasting more time on getting this SSD working.

I did try following the instructions above with Raspbian and Ubuntu, everything from scratch and did not have any luck. 
I also tried modifying the parameters in a system that already booted once without the SSD installed. The result does not change. Sdcard or USB drive also does not influence the result

Still, I did not manage to get any HDMI output with the SSD, even if I let the Pi run for 5min before plugging in the HDMI cable. Also I have not seen the Act led blink even once on the shield

At this point I am strongly suspecting a hardware issue. I have now switched the m.2 ssd with a Sata drive from my PC and use a Sata to usb adapter. It's not pretty but it works for me

**Comment by magore** [comment]
I managed to  resolve this on my system after several 100G of file transfers later
Tested on fresh install of Raspberry Pi Debian Trixie
With WD_BLACK SN770M on two POE hats
```
dtparam=pciex1
dtparam=pciex1_gen=1
```
I used the following POE hats when testing
```
Waveshare PCIe to M.2 Adapter with PoE Function (C)
HackerGadgets NVME and PoE+ Hat for Raspberry Pi 5
```

**Comment by magore** [comment]
I have done more extensive testing with the speed set to gen 1 speeds. Working very well.
I have been using zfs and synced very large datasets. Here are the present results from smart and zpool scrubs 

=== START OF SMART DATA SECTION ===
SMART overall-health self-assessment test result: PASSED

SMART/Health Information (NVMe Log 0x02)
Critical Warning:                   0x00
Temperature:                        41 Celsius
Available Spare:                    100%
Available Spare Threshold:          10%
Percentage Used:                    0%
Data Units Read:                    2,789,843 [1.42 TB]
Data Units Written:                 5,679,722 [2.90 TB]
Host Read Commands:                 13,434,698
Host Write Commands:                25,191,938
Controller Busy Time:               315
Power Cycles:                       71
Power On Hours:                     10
Unsafe Shutdowns:                   10
Media and Data Integrity Errors:    0
Error Information Log Entries:      0
Warning  Comp. Temperature Time:    0
Critical Comp. Temperature Time:    0
Temperature Sensor 1:               50 Celsius
Temperature Sensor 2:               41 Celsius

Error Information (NVMe Log 0x01, 16 of 256 entries)
No Errors Logged


zpool status
  pool: disk-pool
 state: ONLINE
  scan: scrub repaired 0B in 00:48:02 with 0 errors on Tue Oct 28 21:17:20 2025
config:

        NAME         STATE     READ WRITE CKSUM
        disk-pool    ONLINE       0     0     0
          nvme0n1p3  ONLINE       0     0     0

errors: No known data errors
