### ISSUE TITLE
Crash with display_rotate=1 when using Midori

### ISSUE THREAD

**Issue by FreekyFrank** [raspberrypi/linux#628]
Latest update of Raspian (03/07/14)
In /boot/config.txt Set
display_rotate=1
gpu_mem=128
Use Midori to view web sites, also used F11 to go full screen.
Exit return to exisiting terminal, bash no longer able to run built in comments ls, mv, etc.
Pi graphics display degrades Icons disapear etc
Pi locked unable to shutdown.
Set back to display_rotate=0 everything works OK

**Comment by popcornmix** [comment]
What does "vcgencmd version" report.
Did this work before the update?

**Comment by FreekyFrank** [comment]
I must apologise despite repeatedly checking and rebooting on the day, I can no longer reproduce the problem and can give no explanation.

Thanks for the support
