### ISSUE TITLE
Latest 6.1 branch does not compile

### ISSUE THREAD

**Issue by sammirata** [raspberrypi/linux#6308]
### Describe the bug

You get an error on the xhci.c file (fixup_endpoint is undefined)
The merge is missing commit 7c517e79b6ef29b331221829a125d816b87e8d02

### Steps to reproduce the behaviour

Get latest and try to compile ...

### Device (s)

Raspberry Pi 4 Mod. B

### System

6.1.92-v8

### Additional context

I fixed it by applying this missing commit 7c517e79b6ef29b331221829a125d816b87e8d02

**Comment by pelwell** [comment]
The current rpi-6.1.y compiles for me, and the build checks agree (https://github.com/raspberrypi/linux/actions/runs/9553102767). Commit 7c517e7 _is_ present:
1. It originally appeared in rpi-6.1.y as 17cd845185e46.
2. It was reverted by 31dbbc3da26b8.
3. It was re-applied by a0262af1f5b60.
4. If you try to cherry-pick 7c517e7 you get:
    ...
    The previous cherry-pick is now empty, possibly due to conflict resolution.
    If you wish to commit it anyway, use:

        git commit --allow-empty

    Otherwise, please use 'git cherry-pick --skip'

Note that the current head of rpi-6.1.y is:

    fbd8b3facb36c drm/vc4: Use phys addresses for slave DMA config

Check that you are on the same commit, and that your tree is clean.
