### ISSUE TITLE
I2C GPIO-PCA953X interrupt support ?

### ISSUE THREAD

**Issue by ghost** [raspberrypi/linux#631]
Hello,
I am using the PCA953X GPIO driver to interface a PCA9555-equivalent IC via I2C-1 on a Pi Rev 2. The driver is able to provide a polling mechanism to read the Input pin values. I have an interrupt line wired up too. From the kernel driver (3.10 or 3.12), the interrupt line gets registered, but I dont see any interrupts. I was wondering if anybody has got the interrupt version of the driver working on a Pi. From what I can make out, this is a chained gpiochip and it seems to be failing in the irq_create_mapping scenario. What specific changes would be needed ?
   Hopefully this is the right forum to post this on. 
TIA for the help,
Ajit

**Comment by Ruffio** [comment]
@aja91 has this issue been resolved? If yes, then please close this issue.
