### ISSUE TITLE
gpiozero not working on pi 5

### ISSUE THREAD

**Issue by FinDoo20** [raspberrypi/linux#6347]
### Describe the bug

Issue:
>>> %Run solve.py
/usr/lib/python3/dist-packages/gpiozero/devices.py:295: PinFactoryFallback: Falling back from lgpio: 'can not open gpiochip'
  warnings.warn(
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/gpiozero/pins/pi.py", line 408, in pin
    pin = self.pins[info]
KeyError: PinInfo(number=11, name='GPIO17', names=frozenset({17, 'BOARD11', '17', 'WPI0', 'J8:11', 'BCM17', 'GPIO17'}), pull='', row=6, col=1, interfaces=frozenset({'', 'gpio', 'uart', 'spi', 'dpi'}))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jaman/Documents/Systems-Engineering-2024/Official/solve.py", line 34, in <module>
    s_twist = AngularServo (pin = 17, min_pulse_width = .0005, max_pulse_width = .0025, frame_width = 1/315)
  File "/usr/lib/python3/dist-packages/gpiozero/devices.py", line 103, in __call__
    self = super().__call__(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/gpiozero/output_devices.py", line 1725, in __init__
    super().__init__(pin, initial_value=initial_value,
  File "/usr/lib/python3/dist-packages/gpiozero/output_devices.py", line 1503, in __init__
    pwm_device=PWMOutputDevice(
  File "/usr/lib/python3/dist-packages/gpiozero/devices.py", line 103, in __call__
    self = super().__call__(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/gpiozero/output_devices.py", line 392, in __init__
    super().__init__(pin, active_high=active_high, initial_value=None,
  File "/usr/lib/python3/dist-packages/gpiozero/output_devices.py", line 74, in __init__
    super().__init__(pin, pin_factory=pin_factory)
  File "/usr/lib/python3/dist-packages/gpiozero/mixins.py", line 75, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/gpiozero/devices.py", line 549, in __init__
    pin = self.pin_factory.pin(pin)
  File "/usr/lib/python3/dist-packages/gpiozero/pins/pi.py", line 410, in pin
    pin = self.pin_class(self, info)
  File "/usr/lib/python3/dist-packages/gpiozero/pins/rpigpio.py", line 101, in __init__
    GPIO.setup(self._number, GPIO.IN, self.GPIO_PULL_UPS[self._pull])
RuntimeError: Cannot determine SOC peripheral base address

This was working fine before update. Also, when running pinctrl, most pins appear as "none". If i remember correctly from before, I don't recall that, I recall seeing "output" on most.

### Steps to reproduce the behaviour

setup an output using gpiozero. was working before update. (I using angular servo)

### Device (s)

Raspberry Pi 5

### System

Cookie: 9a19:b39d

config.txt
----------

arm_64bit=1
arm_boost=1
arm_freq=2400
arm_freq_min=1500
arm_peri_high=1
audio_pwm_mode=2
auto_initramfs=1
avs_temp=0x16a71
camera_auto_detect=1
core_freq=910
core_freq_min=500
disable_commandline_tags=2
disable_fw_kms_setup=1
disable_l2cache=1
disable_overscan=1
display_auto_detect=1
display_default_lcd=-1
display_hdmi_rotate=-1
display_lcd_rotate=-1
dvfs=4
enable_gic=1
enable_uart=-1
force_eeprom_read=1
force_pwm_open=1
framebuffer_depth=16
framebuffer_ignore_alpha=1
framebuffer_swap=1
gpu_freq_min=500
hdmi_enable_4kp60=1
hevc_freq=910
hevc_freq_min=500
ignore_lcd=-1
init_uart_clock=0x2dc6c00
isp_freq=910
isp_freq_min=500
mask_gpu_interrupt1=16418
max_framebuffers=2
over_voltage_avs=0x1b6ac
pause_burst_frames=1
pciex4_reset=1
pmic_turbo_threshold=600
power_force_3v3_pwm=1
program_serial_random=1
total_mem=4096
v3d_freq=960
v3d_freq_min=500
vpred=8723
vpred_max=8723
hdmi_force_cec_address:0=65535
hdmi_force_cec_address:1=65535
device_tree=-
overlay_prefix=overlays/
hdmi_cvt:0=
hdmi_cvt:1=
hdmi_edid_filename:0=
hdmi_edid_filename:1=
hdmi_timings:0=
hdmi_timings:1=

cmdline.txt
-----------
reboot=w coherent_pool=1M 8250.nr_uarts=1 pci=pcie_bus_safe  smsc95xx.macaddr=2C:CF:67:61:AD:59 vc_mem.mem_base=0x3fc00000 vc_mem.mem_size=0x40000000  console=ttyAMA10,115200 console=tty1 root=PARTUUID=13700b1e-02 rootfstype=ext4 fsck.repair=yes rootwait quiet splash plymouth.ignore-serial-consoles cfg80211.ieee80211_regdom=AU

pin configuration
-----------------

 0: ip    pu | hi // ID_SDA/GPIO0 = input
 1: ip    pu | hi // ID_SCL/GPIO1 = input
 2: a3    pu | hi // GPIO2 = SDA1
 3: a3    pu | hi // GPIO3 = SCL1
 4: no    pu | -- // GPIO4 = none
 5: no    pu | -- // GPIO5 = none
 6: no    pu | -- // GPIO6 = none
 7: no    pu | -- // GPIO7 = none
 8: no    pu | -- // GPIO8 = none
 9: no    pd | -- // GPIO9 = none
10: no    pd | -- // GPIO10 = none
11: no    pd | -- // GPIO11 = none
12: a0    pd | lo // GPIO12 = PWM0_CHAN0
13: a0    pd | lo // GPIO13 = PWM0_CHAN1
14: no    pd | -- // GPIO14 = none
15: no    pd | -- // GPIO15 = none
16: no    pd | -- // GPIO16 = none
17: no    pd | -- // GPIO17 = none
18: no    pd | -- // GPIO18 = none
19: no    pd | -- // GPIO19 = none
20: no    pd | -- // GPIO20 = none
21: no    pd | -- // GPIO21 = none
22: no    pd | -- // GPIO22 = none
23: no    pd | -- // GPIO23 = none
24: no    pd | -- // GPIO24 = none
25: no    pd | -- // GPIO25 = none
26: no    pd | -- // GPIO26 = none
27: no    pd | -- // GPIO27 = none
28: ip    pd | lo // PCIE_RP1_WAKE/GPIO28 = input
29: no    pu | hi // FAN_TACH/GPIO29 = none
30: no    pu | -- // HOST_SDA/GPIO30 = none
31: no    pu | -- // HOST_SCL/GPIO31 = none
32: op dh pd | hi // ETH_RST_N/GPIO32 = output
33: no    pd | lo // GPIO33 = none
34: op dl pd | lo // CD0_IO0_MICCLK/GPIO34 = output
35: no    pd | lo // CD0_IO0_MICDAT0/GPIO35 = none
36: no    pd | lo // RP1_PCIE_CLKREQ_N/GPIO36 = none
37: no    pd | lo // GPIO37 = none
38: ip    pd | hi // CD0_SDA/GPIO38 = input
39: ip    pd | hi // CD0_SCL/GPIO39 = input
40: a2    pu | hi // CD1_SDA/GPIO40 = SDA4
41: a2    pu | hi // CD1_SCL/GPIO41 = SCL4
42: a2    pd | hi // USB_VBUS_EN/GPIO42 = VBUS_EN1
43: a2    pu | hi // USB_OC_N/GPIO43 = VBUS_OC1
44: op dh pd | hi // RP1_STAT_LED/GPIO44 = output
45: ip    pd | lo // FAN_PWM/GPIO45 = input
46: op dl pd | lo // CD1_IO0_MICCLK/GPIO46 = output
47: no    pd | lo // 2712_WAKE/GPIO47 = none
48: no    pd | lo // CD1_IO1_MICDAT1/GPIO48 = none
49: op dl pd | lo // EN_MAX_USB_CUR/GPIO49 = output
50: no    pd | -- // GPIO50 = none
51: no    pd | -- // GPIO51 = none
52: no    pu | -- // GPIO52 = none
53: no    pu | hi // GPIO53 = none
100: ip    pd | lo // GPIO0 = input
101: op dh pu | hi // 2712_BOOT_CS_N/GPIO1 = output
102: a6    pn | hi // 2712_BOOT_MISO/GPIO2 = VC_SPI0_MISO
103: a5    pn | hi // 2712_BOOT_MOSI/GPIO3 = VC_SPI0_MOSI
104: a6    pn | lo // 2712_BOOT_SCLK/GPIO4 = VC_SPI0_SCLK
105: ip    pd | lo // GPIO5 = input
106: ip    pd | lo // GPIO6 = input
107: ip    pd | lo // GPIO7 = input
108: ip    pd | lo // GPIO8 = input
109: ip    pd | lo // GPIO9 = input
110: ip    pd | lo // GPIO10 = input
111: ip    pd | lo // GPIO11 = input
112: ip    pd | lo // GPIO12 = input
113: ip    pd | lo // GPIO13 = input
114: a1    pd | lo // PCIE_SDA/GPIO14 = SPI_S_MOSI_OR_BSC_S_SDA
115: a1    pd | lo // PCIE_SCL/GPIO15 = SPI_S_SCK_OR_BSC_S_SCL
116: ip    pd | lo // GPIO16 = input
117: ip    pd | lo // GPIO17 = input
118: ip    pd | lo // GPIO18 = input
119: ip    pd | lo // GPIO19 = input
120: ip    pu | hi // PWR_GPIO/GPIO20 = input
121: ip    pd | lo // 2712_G21_FS/GPIO21 = input
122: ip    pd | lo // GPIO22 = input
123: ip    pd | lo // GPIO23 = input
124: a3    pn | lo // BT_RTS/GPIO24 = UART_RTS_0
125: a4    pu | lo // BT_CTS/GPIO25 = UART_CTS_0
126: a4    pn | hi // BT_TXD/GPIO26 = UART_TXD_0
127: a4    pu | hi // BT_RXD/GPIO27 = UART_RXD_0
128: op dh pd | hi // WL_ON/GPIO28 = output
129: op dh pd | hi // BT_ON/GPIO29 = output
130: a4    pn | lo // WIFI_SDIO_CLK/GPIO30 = SD2_CLK
131: a4    pu | hi // WIFI_SDIO_CMD/GPIO31 = SD2_CMD
132: a4    pd | hi // WIFI_SDIO_D0/GPIO32 = SD2_DAT0
133: a3    pu | hi // WIFI_SDIO_D1/GPIO33 = SD2_DAT1
134: a4    pn | hi // WIFI_SDIO_D2/GPIO34 = SD2_DAT2
135: a3    pn | hi // WIFI_SDIO_D3/GPIO35 = SD2_DAT3
200: ip    pd | hi // RP1_SDA/AON_GPIO0 = input
201: ip    pd | hi // RP1_SCL/AON_GPIO1 = input
202: op dh pd | hi // RP1_RUN/AON_GPIO2 = output
203: op dh pd | hi // SD_IOVDD_SEL/AON_GPIO3 = output
204: op dh pd | hi // SD_PWR_ON/AON_GPIO4 = output
205: a6    pu | lo // SD_CDET_N/AON_GPIO5 = SD_CARD_PRES_G
206: ip    pd | hi // SD_FLG_N/AON_GPIO6 = input
207: ip    pd | lo // AON_GPIO7 = input
208: ip    pd | lo // 2712_WAKE/AON_GPIO8 = input
209: op dh pd | hi // 2712_STAT_LED/AON_GPIO9 = output
210: ip    pd | lo // AON_GPIO10 = input
211: ip    pd | lo // AON_GPIO11 = input
212: ip    pd | lo // PMIC_INT/AON_GPIO12 = input
213: a3    pu | hi // UART_TX_FS/AON_GPIO13 = VC_TXD0
214: a3    pu | hi // UART_RX_FS/AON_GPIO14 = VC_RXD0
215: ip    pd | lo // AON_GPIO15 = input
216: ip    pu | hi // AON_GPIO16 = input
232: a1    -- | hi // HDMI0_SCL/AON_SGPIO0 = HDMI_TX0_BSC_SCL
233: a1    -- | hi // HDMI0_SDA/AON_SGPIO1 = HDMI_TX0_BSC_SDA
234: a1    -- | hi // HDMI1_SCL/AON_SGPIO2 = HDMI_TX1_BSC_SCL
235: a1    -- | hi // HDMI1_SDA/AON_SGPIO3 = HDMI_TX1_BSC_SDA
236: a2    -- | hi // PMIC_SCL/AON_SGPIO4 = BSC_M2_SCL
237: a2    -- | hi // PMIC_SDA/AON_SGPIO5 = BSC_M2_SDA

vcdbg log messages
------------------

005020.531: Initial voltage 800000 temp 93335
005217.965: avs_2712: AVS pred 8723 872300 temp 92785
005217.976: vpred 872 mV +0
006020.511: FB framebuffer_swap 1
006038.049: Select resolution HDMI0/2 hotplug 0 max_mode 2
006038.065: Select resolution HDMI1/2 hotplug 0 max_mode 2
006884.342: dtb_file 'bcm2712-rpi-5-b.dtb'
006967.561: Found camera 'imx219' on port 1, unicam_port 1
007035.770: Loaded overlay 'imx219'
007134.555: dtparam: i2c_arm=on
007146.658: dtparam: spi=off
007158.134: dtparam: audio=on
007162.589: Unknown dtparam 'audio' - ignored
007216.988: Loaded overlay 'vc4-kms-v3d-pi5'
007328.240: Loaded overlay 'pwm-2chan'
007328.251: dtparam: pin=12
007328.421: dtparam: func=4
007328.599: dtparam: pin2=13
007328.769: dtparam: func2=4
010377.131: Starting OS 10377 ms
010378.865: 00000040: -> 00000480
010378.881: 00000030: -> 00100080
010378.897: 00000034: -> 00100080
010378.911: 00000038: -> 00100080
010378.927: 0000003c: -> 00100080
283748.949: sdram: sdram refresh 2081->1040 (4)

284748.994: sdram: sdram refresh 2081->2081 (3)

352389.242: sdram: sdram refresh 2081->1040 (4)

353476.882: sdram: sdram refresh 2081->2081 (3)

356642.191: sdram: sdram refresh 2081->1040 (4)

369086.034: sdram: sdram refresh 2081->2081 (3)

371196.412: sdram: sdram refresh 2081->1040 (4)

404227.260: sdram: sdram refresh 2081->2081 (3)

405300.897: sdram: sdram refresh 2081->1040 (4)

432297.921: sdram: sdram refresh 2081->2081 (3)

440616.295: sdram: sdram refresh 2081->1040 (4)

441694.112: sdram: sdram refresh 2081->2081 (3)

443773.466: sdram: sdram refresh 2081->1040 (4)

586468.808: sdram: sdram refresh 2081->2081 (3)

592541.612: sdram: sdram refresh 2081->1040 (4)

678200.320: sdram: sdram refresh 2081->2081 (3)

679245.801: sdram: sdram refresh 2081->1040 (4)

dmesg log

**Comment by pelwell** [comment]
This has been covered in the discussion around https://github.com/raspberrypi/linux/pull/6144, but I don't mind leaving this here as a more visible discussion point. However, it's gpiozero which is going to have to change.

The issue has already been reported to the gpiozero devs (https://github.com/gpiozero/gpiozero/issues/1166), but one of them was actually notified 4 months ago as part of the #6144 discussion. RPi-lgpio (a partial RPi.GPIO replacement - https://pypi.org/project/rpi-lgpio/) has already been patched, as has WiringPi (https://github.com/WiringPi/WiringPi/).

**Comment by FinDoo20** [comment]
Thank you so much in responding,

Its interesting but understandable that the raspberry pi team changed chips affecting the GPIO's, but in the meantime, while all the necessary changes by devs to work on the GPIO libraries, slightly off topic, how could I revert back the update (I being quite new) to get the gpio pins working as before?

**Comment by pelwell** [comment]
The easiest way for you to revert to the previous kernel is to use rpi-update on the stable branch (https://github.com/raspberrypi/rpi-firmware/commits/stable). I tried using apt but the old version had been purged already). The previous stable release was `0ccee17`, so you can rewind with:
```
$ sudo rpi-update 0ccee17
```
Note that you won't get back precisely the same kernel, but apart from the different version string I think you would be hard-pressed to see a change.

**Comment by FinDoo20** [comment]
thankyou! ahh should've done this sooner, I in the end reflashed the pi 5 to the cached firmware which I had on PC and reloaded all my backed- up files to it (which weren't too many). Looking on the stable firmware part, I believe I have the 6.1 kernel cached, and that one has gpiozero functionality. It would be a good idea to let people know on the main raspberry pi website that gpiozero and other libraries wont be functional on the pi 5 until it all gets resolved.
