### ISSUE TITLE
Compile "courier-mta" package with "--with-socks"

### ISSUE THREAD

**Issue by renne** [raspberrypi/linux#637]
Hi,

Courier-MTA supports sending mails via SOCKS5-proxy (http://www.courier-mta.org/socks.html). That way one can e.g. use TOR as end-to-end encryption and meta-data anonymizer between mail servers.

Regards,

Renne

**Comment by asb** [comment]
This should be reported to either the upstream Debian bug tracker or the Raspbian tracker: http://www.raspbian.org/RaspbianBugs

This repository is just for the Linux kernel as distributed by the Raspberry Pi Foundation.
