### ISSUE TITLE
amba-pl011 platform_driver bug

### ISSUE THREAD

**Issue by TopgunZh** [raspberrypi/linux#6379]
### Describe the bug

You missed platform_driver_unregister in the pl011_exit function

### Steps to reproduce the behaviour

1.sudo rmmod amba-pl011.ko.xz
2.sudo insmod amba-pl011.ko.xz

miss  platform_driver_unregister(&pl011_axi_platform_driver);

### Device (s)

Raspberry Pi 5

### System

![image](https://github.com/user-attachments/assets/508ac456-837d-4c9a-9646-e77bf58d0be8)

### Logs

![image](https://github.com/user-attachments/assets/568f5237-0c2a-48eb-b077-fa6a190afa7e)

**Comment by popcornmix** [comment]
Does https://github.com/raspberrypi/linux/pull/6380 work for you?

**Comment by TopgunZh** [comment]
> Does #6380 work for you?
It had already been fixed when I opened the issue. The bug is relatively simple.
