### ISSUE TITLE
Add support for SquashFS ZStandard compressed

### ISSUE THREAD

**Issue by mortegai** [raspberrypi/linux#6398]
Please add support for kernel module "squashfs" ZStandard compressed file systems.
CONFIG_SQUASHFS_ZSTD

**Comment by pelwell** [comment]
PR #6400 adds SQUASHFS_ZSTD. After about 40 minutes you should be able to install a trial kernel build using `sudo rpi-update pulls/6400`.

**Comment by mortegai** [comment]
Tested and working properly.
