### ISSUE TITLE
rsync locks up forever if -z flag used, fails with error 130 if ^C given

### ISSUE THREAD

**Issue by PhotoJim** [raspberrypi/linux#64]
Hi,

I use an rsync script to backup up many different machines (Debian, Ubuntu, Linux Mint, and NetBSD) to my server.  Once working, the script is invoked automatically using rsync.  I do the backup using passwordless login.

I accidentally enabled the -z flag on my first script file.  I usually use this when backing up from remote, and don't use it when backing up locally.  This machine is local so it doesn't need -z, but the first iteration used -z:

rsync -a -z -e "ssh  -i /root/.ssh/backup" --progress --delete --exclude /sys --exclude /dev --exclude /proc --exclude /public / fqdnpath.to.server:/home/jim/backup/atherton/

Doing the backup this way, the backup just locks up at some point - not always the same point.

I discovered I could pull the backup from the server (unwittingly not using -z, since I didn't know I was using -z from the Raspberry Pi).  All was fine.

My backup script worked from the pi in this case - probably because it didn't have much to do.

This is when I discovered the -z.  I removed it, deleted the backup from the server, and ran the script.  The backup was created without issue.

It seems that -z does something that causes some sort of failure in rsync.  There's plenty of free RAM (>100 MB) while rsync is running but locked up.  ^C kills it and that's when I get error 130 (Unknown Error).

**Comment by popcornmix** [comment]
Can you try the suggestions here:
http://elinux.org/R-Pi_Troubleshooting#Crashes_occur_with_high_network_load

Also the latest firmware has some fixes. You could also try adding:
dwc_otg.microframe_schedule=1
to cmdline.txt

**Comment by PhotoJim** [comment]
Can do - I'll see if I can find time tonight or tomorrow to experiment.

With -z not used, I have no issues whatsoever which must involve some
occasionally high network load, although the CPU will not be as taxed.

Jim

**Comment by ghollingworth** [comment]
Reopen if issue still exists
