### ISSUE TITLE
rtl8188eu source is in staging but it's not configured

### ISSUE THREAD

**Issue by fgimenezm** [raspberrypi/linux#640]
Please configure rtl8188eu (staging) when building the kernel modules.
The source is already there in the kernel, it just needs to be configured.
I've compiled it myself from source and it works fine with my TP-LINK WN725N v2.
I added "options r8188eu rtw_power_mgnt=0" into /etc/modprobe.d/8188eu.conf because I don't like the small latency leaving it enabled adds temporarily (I honestly could live with it, but I like fast ping).
I've tested it for a while with that option set and it's rock solid. Tested it streaming many videos to XBMC (on raspbian) without a glitch.

**Comment by nsayer** [comment]
Seconded. There is a giant thread on the R-Pi forums with pointers to dropbox binaries for this driver. It's used in a number of USB WiFi dongles used on R-Pi, and really, really should be included in the distribution.

**Comment by fgimenezm** [comment]
Here are the relevant config lines:
CONFIG_R8188EU=m
CONFIG_88EU_AP_MODE=y
CONFIG_88EU_P2P=y

**Comment by fgimenezm** [comment]
_bump_

**Comment by fgimenezm** [comment]
Good news!
The newest firmware with kernel 3.18 has the staging modules built!
You just need to copy the firmware file (if you don't have it already) from https://github.com/lwfinger/rtl8188eu/blob/master/rtl8188eufw.bin to /lib/firmware/rtlwifi/
I think Raspbian Jessie has this firmware file already so in that case you don't need anything and it should just work.
