### ISSUE TITLE
Kernel Panic on shutdown

### ISSUE THREAD

**Issue by sneakernets** [raspberrypi/linux#644]
Today on shutdown I got this panic. I wasn't able to use the keyboard or anything else. My only connected peripherals are a network cable, Powered USB hub with keyboard and mouse attached.
I managed to get a screenshot but not much else.
![img_20140722_173313_074-1](https://cloud.githubusercontent.com/assets/5595293/3666376/9cb6cde2-11f0-11e4-8986-5af983983e49.jpg)

This is using the latest pi firmware on Raspbian stable.

**Comment by popcornmix** [comment]
If you remove the parameter kgdboc=ttyAMA0,115200 from /boot/cmdline.txt then the stacktrace won't end at the kdb prompt. The full stack trace should spew out on the screen.

Does this happen every time you shutdown?

**Comment by sneakernets** [comment]
It doesn't happen every time - this was the first time I've seen it. I've left my pi on for a while today, I'll shut it down and see if it happens again. I'll modify cmdline.txt shortly.

**Comment by sneakernets** [comment]
This happened again today, and it was completely different set of garbage when compiling a ruby gem. I think I've found the problem anyway - my USB cable is likely going bad, or my 1A power supply isn't producing a clean current, or not enough of it. Getting a reliable, clean power supply  has been one of the most frustrating parts of owning this system. That isn't Raspberry Pi's fault, though. :)

**Comment by popcornmix** [comment]
There is now a solution to which power supply to use. This one is officially sanctioned:
http://swag.raspberrypi.org/collections/frontpage/products/raspberry-pi-universal-power-supply

**Comment by sneakernets** [comment]
Thanks! I'll check this out for sure! In fact, I'll buy one soon and report back if I get any errors like I have before.

**Comment by sneakernets** [comment]
Here to report that there are no more issues with this that I can find (at least for now)

**Comment by popcornmix** [comment]
Okay to close?

**Comment by sneakernets** [comment]
Sure! I'll close it I suppose.
