### ISSUE TITLE
3.15.6 new ALSA warnings

### ISSUE THREAD

**Issue by audetto** [raspberrypi/linux#645]
Hi,

I've just rebooted to 3.15.6 (from Arch) and I get a lot of lines like this in dmesg

[    7.998692] systemd-journald[86]: Received request to flush runtime journal from PID 1
[    9.405314] bcm2835_audio_set_ctls:550  No ALSA stream available?! 0:  (null) (ff)
[    9.468559] bcm2835_audio_set_ctls:550  No ALSA stream available?! 1:  (null) (ff)
[    9.528089] bcm2835_audio_set_ctls:550  No ALSA stream available?! 2:  (null) (ff)
[    9.598864] bcm2835_audio_set_ctls:550  No ALSA stream available?! 3:  (null) (ff)
[    9.659463] bcm2835_audio_set_ctls:550  No ALSA stream available?! 4:  (null) (ff)
[    9.733063] bcm2835_audio_set_ctls:550  No ALSA stream available?! 5:  (null) (ff)
[    9.827984] bcm2835_audio_set_ctls:550  No ALSA stream available?! 6:  (null) (ff)
[    9.926731] bcm2835_audio_set_ctls:550  No ALSA stream available?! 7:  (null) (ff)
[   10.085601] bcm2835_audio_set_ctls:550  No ALSA stream available?! 0:  (null) (ff)
[   10.161134] bcm2835_audio_set_ctls:550  No ALSA stream available?! 1:  (null) (ff)
[   10.201654] bcm2835_audio_set_ctls:550  No ALSA stream available?! 2:  (null) (ff)
[   10.256542] bcm2835_audio_set_ctls:550  No ALSA stream available?! 3:  (null) (ff)
[   10.317849] bcm2835_audio_set_ctls:550  No ALSA stream available?! 4:  (null) (ff)
[   10.377875] bcm2835_audio_set_ctls:550  No ALSA stream available?! 5:  (null) (ff)
[   10.435051] bcm2835_audio_set_ctls:550  No ALSA stream available?! 6:  (null) (ff)
[   10.498189] bcm2835_audio_set_ctls:550  No ALSA stream available?! 7:  (null) (ff)
[   12.250675] smsc95xx 1-1.1:1.0 eth0: hardware isn't capable of remote wakeup
[   12.251567] IPv6: ADDRCONF(NETDEV_UP): eth0: link is not ready
[   13.854597] smsc95xx 1-1.1:1.0 eth0: link up, 100Mbps, full-duplex, lpa 0xCDE1
[   13.860076] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
[  202.753889] bcm2835_audio_set_ctls:559  Controls set for stream 0
[  202.760194] bcm2835_audio_set_ctls:550  No ALSA stream available?! 1:  (null) (ff)
[  202.783663] bcm2835_audio_set_ctls:550  No ALSA stream available?! 2:  (null) (ff)
[  202.801252] bcm2835_audio_set_ctls:550  No ALSA stream available?! 3:  (null) (ff)
[  202.809867] bcm2835_audio_set_ctls:550  No ALSA stream available?! 4:  (null) (ff)
[  202.818336] bcm2835_audio_set_ctls:550  No ALSA stream available?! 5:  (null) (ff)
[  202.826904] bcm2835_audio_set_ctls:550  No ALSA stream available?! 6:  (null) (ff)
[  202.835385] bcm2835_audio_set_ctls:550  No ALSA stream available?! 7:  (null) (ff)

The first block happens before I do anything audio related.
Then I start mpd and play a few http streams through internal audio.

e.g. http://mp3.live.tv-radio.com/franceinfo/all/franceinfo.mp3

I cannot say that I notice any difference.

I've reverted to previous version 3.15.5 and no warnings are reported.

The lines seems to be added after I switch to a new channel with mpc.
It always repeats 1->7

Jul  5 2014 19:07:44 
Copyright (c) 2012 Broadcom
version cb433d55f9f5b29b59968019e3b54802894af489 (clean) (release)

and

Linux alarmpi 3.15.6-1-ARCH #1 PREEMPT Fri Jul 18 14:36:05 MDT 2014 armv6l GNU/Linux

**Comment by popcornmix** [comment]
Updated. Please run rpi-update and confirm it is working.

**Comment by audetto** [comment]
yes, it is better now, but I still get a lot of

[734057.875719] bcm2835_audio_set_ctls:559  Controls set for stream 0
[734061.750289] bcm2835_audio_set_ctls:559  Controls set for stream 0
[734065.542537] bcm2835_audio_set_ctls:559  Controls set for stream 0
[734066.846703] bcm2835_audio_set_ctls:559  Controls set for stream 0
[734068.370875] bcm2835_audio_set_ctls:559  Controls set for stream 0
[734070.091759] bcm2835_audio_set_ctls:559  Controls set for stream 0

I am running arch, 

Linux alarmpi 3.16.0-2-ARCH #1 PREEMPT Fri Aug 8 22:23:37 MDT 2014 armv6l GNU/Linux

Jul 23 2014 21:12:29 
Copyright (c) 2012 Broadcom
version 174cdd77563b98023955a94cb8d072d9c7095d6f (clean) (release)

**Comment by linuxgnuru** [comment]
It's October 2015, kernel 3.12.30, and still getting flooded with
 bcm2835_audio_set_ctls:558 Controls set for stream 0
messages when ever I try to play any audio.

**Comment by popcornmix** [comment]
Okay. Seems that message is not actually an error so should be changed to a debug level.
Will include in next update.

**Comment by P33M** [comment]
Debug spam has been nerfed.
