### ISSUE TITLE
Bad message in some files

### ISSUE THREAD

**Issue by Midcc** [raspberrypi/linux#6452]
### Describe the bug

OSError: [Errno 74] Bad message: '/usr/lib/python3.11'
dpkg: error while cleaning up:
 installed python3-libcamera:arm64 package post-installation script subprocess returned error exit status 1
Preparing to unpack .../rpicam-apps_1.5.2-2_arm64.deb ...
Unpacking rpicam-apps (1.5.2-2) over (1.5.0-2) ...
dpkg: error processing archive /var/cache/apt/archives/rpicam-apps_1.5.2-2_arm64.deb (--unpack):
 unable to stat './usr/include/rpicam-apps/post_processing_stages/histogram.hpp' (which was about to be installed): Bad message
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Errors were encountered while processing:
 /var/cache/apt/archives/python3-libcamera_0.3.2+rpt20240927-1_arm64.deb
 /var/cache/apt/archives/rpicam-apps_1.5.2-2_arm64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
(robotchat) pi@raspberrypi:/app/robotchat $ stat /usr/include/rpicam-apps/post_processing_stages/histogram.hpp
stat: cannot statx '/usr/include/rpicam-apps/post_processing_stages/histogram.hpp': Bad message
(robotchat) pi@raspberrypi:/app/robotchat $ ls -l /usr/include/rpicam-apps/post_processing_stages/histogram.hpp
ls: cannot access '/usr/include/rpicam-apps/post_processing_stages/histogram.hpp': Bad message
(robotchat) pi@raspberrypi:/app/robotchat $ ls -l

### Steps to reproduce the behaviour

sudo apt install rpicam-apps
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
The following packages were automatically installed and are no longer required:
  python3-cffi-backend python3-jwt python3-responses
Use 'sudo apt autoremove' to remove them.
The following additional packages will be installed:
  python3-libcamera
The following packages will be upgraded:
  python3-libcamera rpicam-apps
2 upgraded, 0 newly installed, 0 to remove and 184 not upgraded.
6 not fully installed or removed.
Need to get 0 B/898 kB of archives.
After this operation, 73.7 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Python path configuration:
  PYTHONHOME = (not set)
  PYTHONPATH = (not set)
  program name = '/usr/bin/python3'
  isolated = 0
  environment = 1
  user site = 1
  safe_path = 0
  import site = 1
  is in build tree = 0
  stdlib dir = '/usr/lib/python3.11'
  sys._base_executable = '/usr/bin/python3'
  sys.base_prefix = '/usr'
  sys.base_exec_prefix = '/usr'
  sys.platlibdir = 'lib'
  sys.executable = '/usr/bin/python3'
  sys.prefix = '/usr'
  sys.exec_prefix = '/usr'
  sys.path = [
    '/usr/lib/python311.zip',
    '/usr/lib/python3.11',
    '/usr/lib/python3.11/lib-dynload',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1080, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1504, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1476, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1616, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1659, in _fill_cache
OSError: [Errno 74] Bad message: '/usr/lib/python3.11'
Illegal instruction
dpkg: warning: files list file for package 'alacarte' missing; assuming package has no files currently installed
(Reading database ... 137204 files and directories currently installed.)
Preparing to unpack .../python3-libcamera_0.3.2+rpt20240927-1_arm64.deb ...
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Python path configuration:
  PYTHONHOME = (not set)
  PYTHONPATH = (not set)
  program name = '/usr/bin/python3'
  isolated = 0
  environment = 1
  user site = 1
  safe_path = 0
  import site = 1
  is in build tree = 0
  stdlib dir = '/usr/lib/python3.11'
  sys._base_executable = '/usr/bin/python3'
  sys.base_prefix = '/usr'
  sys.base_exec_prefix = '/usr'
  sys.platlibdir = 'lib'
  sys.executable = '/usr/bin/python3'
  sys.prefix = '/usr'
  sys.exec_prefix = '/usr'
  sys.path = [
    '/usr/lib/python311.zip',
    '/usr/lib/python3.11',
    '/usr/lib/python3.11/lib-dynload',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1080, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1504, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1476, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1616, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1659, in _fill_cache
OSError: [Errno 74] Bad message: '/usr/lib/python3.11'
dpkg: warning: old python3-libcamera:arm64 package pre-removal script subprocess returned error exit status 1
dpkg: trying script from the new package instead ...
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Python path configuration:
  PYTHONHOME = (not set)
  PYTHONPATH = (not set)
  program name = '/usr/bin/python3'
  isolated = 0
  environment = 1
  user site = 1
  safe_path = 0
  import site = 1
  is in build tree = 0
  stdlib dir = '/usr/lib/python3.11'
  sys._base_executable = '/usr/bin/python3'
  sys.base_prefix = '/usr'
  sys.base_exec_prefix = '/usr'
  sys.platlibdir = 'lib'
  sys.executable = '/usr/bin/python3'
  sys.prefix = '/usr'
  sys.exec_prefix = '/usr'
  sys.path = [
    '/usr/lib/python311.zip',
    '/usr/lib/python3.11',
    '/usr/lib/python3.11/lib-dynload',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1080, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1504, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1476, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1616, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1659, in _fill_cache
OSError: [Errno 74] Bad message: '/usr/lib/python3.11'
dpkg: error processing archive /var/cache/apt/archives/python3-libcamera_0.3.2+rpt20240927-1_arm64.deb (--unpack):
 new python3-libcamera:arm64 package pre-removal script subprocess returned error exit status 1
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Python path configuration:
  PYTHONHOME = (not set)
  PYTHONPATH = (not set)
  program name = '/usr/bin/python3'
  isolated = 0
  environment = 1
  user site = 1
  safe_path = 0
  import site = 1
  is in build tree = 0
  stdlib dir = '/usr/lib/python3.11'
  sys._base_executable = '/usr/bin/python3'
  sys.base_prefix = '/usr'
  sys.base_exec_prefix = '/usr'
  sys.platlibdir = 'lib'
  sys.executable = '/usr/bin/python3'
  sys.prefix = '/usr'
  sys.exec_prefix = '/usr'
  sys.path = [
    '/usr/lib/python311.zip',
    '/usr/lib/python3.11',
    '/usr/lib/python3.11/lib-dynload',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1140, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1080, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1504, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1476, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1616, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1659, in _fill_cache
OSError: [Errno 74] Bad message: '/usr/lib/python3.11'
dpkg: error while cleaning up:
 installed python3-libcamera:arm64 package post-installation script subprocess returned error exit status 1
Preparing to unpack .../rpicam-apps_1.5.2-2_arm64.deb ...
Unpacking rpicam-apps (1.5.2-2) over (1.5.0-2) ...
dpkg: error processing archive /var/cache/apt/archives/rpicam-apps_1.5.2-2_arm64.deb (--unpack):
 unable to stat './usr/include/rpicam-apps/post_processing_stages/histogram.hpp' (which was about to be installed): Bad message
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Errors were encountered while processing:
 /var/cache/apt/archives/python3-libcamera_0.3.2+rpt20240927-1_arm64.deb
 /var/cache/apt/archives/rpicam-apps_1.5.2-2_arm64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

### Device (s)

Raspberry Pi 5

### System

Raspberry Pi reference 2024-07-04
Generated using pi-gen, https://github.com/RPi-Distro/pi-gen, 48efb5fc5485fafdc9de8ad481eb5c09e1182656, stage4

vcgencmd version
2024/06/05 16:41:49 
Copyright (c) 2012 Broadcom
version 6fe0b091 (release) (embedded)

uname -a
Linux raspberrypi 6.6.31+rpt-rpi-2712 #1 SMP PREEMPT Debian 1:6.6.31-1+rpt1 (2024-05-29) aarch64 GNU/Linux

**Comment by popcornmix** [comment]
This issue tracker is for reporting bugs in the linux kernel.
Your issue seems to be related to camera apt packages.

The [forum](https://forums.raspberrypi.com) may be a better place to discuss this.
