### ISSUE TITLE
hci0: BCM: Reading local name failed (-110)

### ISSUE THREAD

**Issue by manio** [raspberrypi/linux#6462]
### Describe the bug

Hi,
For about 1 of 10 of boots results in hci0 not visible.
I collected the following errors:
```
Jan  1 00:00:06 buildroot kern.err kernel: [    6.473578] Bluetooth: hci0: command 0x0c14 tx timeout
Jan  1 00:00:14 buildroot kern.err kernel: [   14.553559] Bluetooth: hci0: BCM: Reading local name failed (-110)
```
or
```
[    4.406253] Bluetooth: hci0: BCM: features 0x2e
[    4.419622] Bluetooth: hci0: BCM43436 37.4MHz Class 1.5 RaspBerry Pi Zero2 [Version: 1017.1042]
[    4.422736] Bluetooth: hci0: BCM43430A1 (001.002.009) build 1042
[    4.425642] Bluetooth: hci0: BCM: Using default device address (43:43:a1:12:1f:ac)
[    6.553570] Bluetooth: hci0: command 0x201c tx timeout
[    6.556460] Bluetooth: hci0: Opcode 0x201c failed: -110
```
or
```
Jan  1 01:10:55 buildroot kern.err kernel: [ 4255.673572] Bluetooth: hci0: command 0x0c1a tx timeout
Jan  1 01:10:55 buildroot kern.err kernel: [ 4255.673572] Bluetooth: hci0: Opcode 0x c1a failed: -110
```
This is leading to problems with bluetoothd which is not reporting any BT adapters, so I cannot use bluetooth.

I was trying to:
```
modprobe -r hci_uart
modprobe -r rfcomm
modprobe -r btbcm
modprobe -r bluetooth
```
And then after modprobing it again I don't have any initialization lines in `dmesg`.
Is this normal? How can I modprobe it again to have it fully initialized like on clean boot. Is it somehow related with devicetree?

I have to admit that this kind of workaround would be usable for me. I just need to reset/reinit this whole Bluetooth stack/kernel modules (btbcm?) without rebooting the whole Pi.

### Steps to reproduce the behaviour

Boot Pi and on some reboot it will occur. Next reboot most of the time fixes the problem.

### Device (s)

Raspberry Pi Zero 2 W

### System

Linux version 6.1.61-v7

### Logs

[    0.000000] Booting Linux on physical CPU 0x0
[    0.000000] Linux version 6.1.61-v7 (runner@fv-az735-94) (arm-buildroot-linux-gnueabihf-gcc.br_real (Buildroot -g7a59c3a4) 12.3.0, GNU ld (GNU Binutils) 2.40) #1 SMP Sat Mar 30 17:55:00 UTC 2024
[    0.000000] CPU: ARMv7 Processor [410fd034] revision 4 (ARMv7), cr=10c5383d
[    0.000000] CPU: div instructions available: patching division code
[    0.000000] CPU: PIPT / VIPT nonaliasing data cache, VIPT aliasing instruction cache
[    0.000000] OF: fdt: Machine model: Raspberry Pi Zero 2 W Rev 1.0
[    0.000000] random: crng init done
[    0.000000] Memory policy: Data cache writealloc
[    0.000000] Reserved memory: created CMA memory pool at 0x15800000, size 64 MiB
[    0.000000] OF: reserved mem: initialized node linux,cma, compatible id shared-dma-pool
[    0.000000] Zone ranges:
[    0.000000]   DMA      [mem 0x0000000000000000-0x0000000019bfffff]
[    0.000000]   Normal   empty
[    0.000000] Movable zone start for each node
[    0.000000] Early memory node ranges
[    0.000000]   node   0: [mem 0x0000000000000000-0x0000000019bfffff]
[    0.000000] Initmem setup node 0 [mem 0x0000000000000000-0x0000000019bfffff]
[    0.000000] percpu: Embedded 12 pages/cpu s18004 r8192 d22956 u49152
[    0.000000] pcpu-alloc: s18004 r8192 d22956 u49152 alloc=12*4096
[    0.000000] pcpu-alloc: [0] 0 [0] 1 [0] 2 [0] 3 
[    0.000000] Built 1 zonelists, mobility grouping on.  Total pages: 104545
[    0.000000] Kernel command line: coherent_pool=1M 8250.nr_uarts=1 snd_bcm2835.enable_headphones=0 bcm2708_fb.fbwidth=720 bcm2708_fb.fbheight=480 bcm2708_fb.fbswap=1 smsc95xx.macaddr=B8:27:EB:67:7C:18 vc_mem.mem_base=0x1ec00000 vc_mem.mem_size=0x20000000  root=/dev/mmcblk0p2 rootwait console=tty1 ro
[    0.000000] Dentry cache hash table entries: 65536 (order: 6, 262144 bytes, linear)
[    0.000000] Inode-cache hash table entries: 32768 (order: 5, 131072 bytes, linear)
[    0.000000] mem auto-init: stack:all(zero), heap alloc:off, heap free:off
[    0.000000] Memory: 337224K/421888K available (9216K kernel code, 718K rwdata, 2316K rodata, 1024K init, 520K bss, 19128K reserved, 65536K cma-reserved)
[    0.000000] SLUB: HWalign=64, Order=0-3, MinObjects=0, CPUs=4, Nodes=1
[    0.000000] rcu: Hierarchical RCU implementation.
[    0.000000] 	Tracing variant of Tasks RCU enabled.
[    0.000000] rcu: RCU calculated value of scheduler-enlistment delay is 10 jiffies.
[    0.000000] NR_IRQS: 16, nr_irqs: 16, preallocated irqs: 16
[    0.000000] rcu: srcu_init: Setting srcu_struct sizes based on contention.
[    0.000000] arch_timer: cp15 timer(s) running at 19.20MHz (phys).
[    0.000000] clocksource: arch_sys_counter: mask: 0xffffffffffffff max_cycles: 0x46d987e47, max_idle_ns: 440795202767 ns
[    0.000001] sched_clock: 56 bits at 19MHz, resolution 52ns, wraps every 4398046511078ns
[    0.000018] Switching to timer-based delay loop, resolution 52ns
[    0.000337] Console: colour dummy device 80x30
[    0.000847] printk: console [tty1] enabled
[    0.000902] Calibrating delay loop (skipped), value calculated using timer frequency.. 38.40 BogoMIPS (lpj=192000)
[    0.000943] CPU: Testing write buffer coherency: ok
[    0.000999] pid_max: default: 32768 minimum: 301
[    0.001126] LSM: Security Framework initializing
[    0.001244] Mount-cache hash table entries: 1024 (order: 0, 4096 bytes, linear)
[    0.001281] Mountpoint-cache hash table entries: 1024 (order: 0, 4096 bytes, linear)
[    0.002254] cgroup: Disabling memory control group subsystem
[    0.002752] CPU0: thread -1, cpu 0, socket 0, mpidr 80000000
[    0.003507] cblist_init_generic: Setting adjustable number of callback queues.
[    0.003538] cblist_init_generic: Setting shift to 2 and lim to 1.
[    0.003670] Setting up static identity map for 0x100000 - 0x10003c
[    0.003803] rcu: Hierarchical SRCU implementation.
[    0.003825] rcu: 	Max phase no-delay instances is 1000.
[    0.004450] smp: Bringing up secondary CPUs ...
[    0.005210] CPU1: thread -1, cpu 1, socket 0, mpidr 80000001
[    0.005988] CPU2: thread -1, cpu 2, socket 0, mpidr 80000002
[    0.006704] CPU3: thread -1, cpu 3, socket 0, mpidr 80000003
[    0.006791] smp: Brought up 1 node, 4 CPUs
[    0.006864] SMP: Total of 4 processors activated (153.60 BogoMIPS).
[    0.006888] CPU: All CPU(s) started in HYP mode.
[    0.006905] CPU: Virtualization extensions available.
[    0.007496] devtmpfs: initialized
[    0.019717] VFP support v0.3: implementor 41 architecture 3 part 40 variant 3 rev 4
[    0.019962] clocksource: jiffies: mask: 0xffffffff max_cycles: 0xffffffff, max_idle_ns: 19112604462750000 ns
[    0.020011] futex hash table entries: 1024 (order: 4, 65536 bytes, linear)
[    0.022556] pinctrl core: initialized pinctrl subsystem
[    0.023510] NET: Registered PF_NETLINK/PF_ROUTE protocol family
[    0.025585] DMA: preallocated 1024 KiB pool for atomic coherent allocations
[    0.030110] audit: initializing netlink subsys (disabled)
[    0.030341] audit: type=2000 audit(0.030:1): state=initialized audit_enabled=0 res=1
[    0.030831] thermal_sys: Registered thermal governor 'step_wise'
[    0.031103] hw-breakpoint: found 5 (+1 reserved) breakpoint and 4 watchpoint registers.
[    0.031153] hw-breakpoint: maximum watchpoint size is 8 bytes.
[    0.031354] Serial: AMBA PL011 UART driver
[    0.036932] bcm2835-mbox 3f00b880.mailbox: mailbox enabled
[    0.050013] raspberrypi-firmware soc:firmware: Attached to firmware from 2023-10-17T15:42:39, variant start
[    0.060028] raspberrypi-firmware soc:firmware: Firmware hash is 30f0c5e4d076da3ab4f341d88e7d505760b93ad7
[    0.098202] kprobes: kprobe jump-optimization is enabled. All kprobes are optimized if possible.
[    0.099848] bcm2835-dma 3f007000.dma: DMA legacy API manager, dmachans=0x1
[    0.101379] SCSI subsystem initialized
[    0.101592] usbcore: registered new interface driver usbfs
[    0.101658] usbcore: registered new interface driver hub
[    0.101717] usbcore: registered new device driver usb
[    0.101890] usb_phy_generic phy: supply vcc not found, using dummy regulator
[    0.102224] pps_core: LinuxPPS API ver. 1 registered
[    0.102247] pps_core: Software ver. 5.3.6 - Copyright 2005-2007 Rodolfo Giometti <giometti@linux.it>
[    0.102291] PTP clock support registered
[    0.103539] clocksource: Switched to clocksource arch_sys_counter
[    0.103823] VFS: Disk quotas dquot_6.6.0
[    0.103894] VFS: Dquot-cache hash table entries: 1024 (order 0, 4096 bytes)
[    0.104043] FS-Cache: Loaded
[    0.104268] CacheFiles: Loaded
[    0.112586] NET: Registered PF_INET protocol family
[    0.112796] IP idents hash table entries: 8192 (order: 4, 65536 bytes, linear)
[    0.114591] tcp_listen_portaddr_hash hash table entries: 512 (order: 0, 4096 bytes, linear)
[    0.114647] Table-perturb hash table entries: 65536 (order: 6, 262144 bytes, linear)
[    0.114687] TCP established hash table entries: 4096 (order: 2, 16384 bytes, linear)
[    0.114771] TCP bind hash table entries: 4096 (order: 4, 65536 bytes, linear)
[    0.114957] TCP: Hash tables configured (established 4096 bind 4096)
[    0.115072] UDP hash table entries: 256 (order: 1, 8192 bytes, linear)
[    0.115122] UDP-Lite hash table entries: 256 (order: 1, 8192 bytes, linear)
[    0.115329] NET: Registered PF_UNIX/PF_LOCAL protocol family
[    0.115784] RPC: Registered named UNIX socket transport module.
[    0.115810] RPC: Registered udp transport module.
[    0.115829] RPC: Registered tcp transport module.
[    0.115848] RPC: Registered tcp NFSv4.1 backchannel transport module.
[    0.116876] hw perfevents: enabled with armv7_cortex_a7 PMU driver, 7 counters available
[    0.117975] Initialise system trusted keyrings
[    0.118141] workingset: timestamp_bits=14 max_order=17 bucket_order=3
[    0.124237] zbud: loaded
[    0.126115] NFS: Registering the id_resolver key type
[    0.126160] Key type id_resolver registered
[    0.126180] Key type id_legacy registered
[    0.126279] nfs4filelayout_init: NFSv4 File Layout Driver Registering...
[    0.126305] nfs4flexfilelayout_init: NFSv4 Flexfile Layout Driver Registering...
[    0.127339] Key type asymmetric registered
[    0.127363] Asymmetric key parser 'x509' registered
[    0.127507] Block layer SCSI generic (bsg) driver version 0.4 loaded (major 247)
[    0.127539] io scheduler mq-deadline registered
[    0.127560] io scheduler kyber registered
[    0.130364] bcm2708_fb soc:fb: FB found 1 display(s)
[    0.140933] Console: switching to colour frame buffer device 90x30
[    0.147465] bcm2708_fb soc:fb: Registered framebuffer for display 0, size 720x480
[    0.152087] Serial: 8250/16550 driver, 1 ports, IRQ sharing enabled
[    0.155616] bcm2835-rng 3f104000.rng: hwrng registered
[    0.158133] vc-mem: phys_addr:0x00000000 mem_base=0x1ec00000 mem_size:0x20000000(512 MiB)
[    0.172254] brd: module loaded
[    0.179202] loop: module loaded
[    0.182019] Loading iSCSI transport class v2.0-870.
[    0.185584] usbcore: registered new interface driver lan78xx
[    0.187944] usbcore: registered new interface driver smsc95xx
[    0.190175] dwc_otg: version 3.00a 10-AUG-2012 (platform bus)
[    0.192515] dwc_otg: FIQ enabled
[    0.192522] dwc_otg: NAK holdoff enabled
[    0.192529] dwc_otg: FIQ split-transaction FSM enabled
[    0.192540] Module dwc_common_port init
[    0.192734] usbcore: registered new interface driver usb-storage
[    0.195193] mousedev: PS/2 mouse device common for all mice
[    0.198716] sdhci: Secure Digital Host Controller Interface driver
[    0.201021] sdhci: Copyright(c) Pierre Ossman
[    0.203443] sdhci-pltfm: SDHCI platform and OF driver helper
[    0.206337] ledtrig-cpu: registered to indicate activity on CPUs
[    0.208835] hid: raw HID events driver (C) Jiri Kosina
[    0.211189] usbcore: registered new interface driver usbhid
[    0.213436] usbhid: USB HID core driver
[    0.215717] bcm2835_vchiq 3f00b840.mailbox: there is not valid maps for state default
[    0.221216] Initializing XFRM netlink socket
[    0.223625] NET: Registered PF_PACKET protocol family
[    0.226044] Key type dns_resolver registered
[    0.228494] Registering SWP/SWPB emulation handler
[    0.230915] registered taskstats version 1
[    0.233126] Loading compiled-in X.509 certificates
[    0.235844] Key type .fscrypt registered
[    0.237948] Key type fscrypt-provisioning registered
[    0.245405] 3f215040.serial: ttyS0 at MMIO 0x3f215040 (irq = 86, base_baud = 50000000) is a 16550
[    0.249905] serial serial0: tty port ttyS0 registered
[    0.252801] bcm2835-wdt bcm2835-wdt: Broadcom BCM2835 watchdog timer
[    0.255334] bcm2835-power bcm2835-power: Broadcom BCM2835 power domains driver
[    0.258768] mmc-bcm2835 3f300000.mmcnr: mmc_debug:0 mmc_debug2:0
[    0.261140] mmc-bcm2835 3f300000.mmcnr: DMA channel allocated
[    0.291525] sdhost: log_buf @ 23dd9223 (d5910000)
[    0.341451] mmc0: sdhost-bcm2835 loaded - DMA enabled (>1)
[    0.343926] uart-pl011 3f201000.serial: there is not valid maps for state default
[    0.346520] uart-pl011 3f201000.serial: cts_event_workaround enabled
[    0.348959] 3f201000.serial: ttyAMA0 at MMIO 0x3f201000 (irq = 114, base_baud = 0) is a PL011 rev2
[    0.354183] of_cfs_init
[    0.356633] of_cfs_init: OK
[    0.359785] Waiting for root device /dev/mmcblk0p2...
[    0.391468] mmc0: host does not support reading read-only switch, assuming write-enable
[    0.397009] mmc0: new high speed SDXC card at address b387
[    0.400071] mmcblk0: mmc0:b387 CBADS 58.3 GiB 
[    0.404272]  mmcblk0: p1 p2
[    0.407074] mmcblk0: mmc0:b387 CBADS 58.3 GiB
[    0.426517] EXT4-fs (mmcblk0p2): orphan cleanup on readonly fs
[    0.428995] EXT4-fs (mmcblk0p2): mounted filesystem with ordered data mode. Quota mode: none.
[    0.433804] VFS: Mounted root (ext4 filesystem) readonly on device 179:2.
[    0.436631] devtmpfs: mounted
[    0.440760] Freeing unused kernel image (initmem) memory: 1024K
[    0.440838] mmc1: new high speed SDIO card at address 0001
[    0.483964] Run /sbin/init as init process
[    0.486314]   with arguments:
[    0.486320]     /sbin/init
[    0.486326]   with environment:
[    0.486331]     HOME=/
[    0.486337]     TERM=linux
[    0.904837] cfg80211: Loading compiled-in X.509 certificates for regulatory database
[    0.956143] cfg80211: Loaded X.509 cert 'benh@debian.org: 577e021cb980e0e820821ba7b54b4961b8b4fadf'
[    0.963626] cfg80211: Loaded X.509 cert 'romain.perier@gmail.com: 3abbc6ec146e09d1b6016ab9d6cf71dd233f0328'
[    0.971213] cfg80211: Loaded X.509 cert 'sforshee: 00b28ddf47aef9cea7'
[    1.090332] brcmfmac: F1 signature read @0x18000000=0x1541a9a6
[    1.095098] brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac43430-sdio for chip BCM43430/1
[    1.100961] usbcore: registered new interface driver brcmfmac
[    1.292427] brcmfmac: brcmf_c_preinit_dcmds: Firmware: BCM43430/1 wl0: Jun 14 2023 07:27:45 version 7.45.96.s1 (gf031a129) FWID 01-70bd2af7 es7
[    1.348700] Bluetooth: Core ver 2.22
[    1.351545] NET: Registered PF_BLUETOOTH protocol family
[    1.354423] Bluetooth: HCI device and connection manager initialized
[    1.357312] Bluetooth: HCI socket layer initialized
[    1.360141] Bluetooth: L2CAP socket layer initialized
[    1.362941] Bluetooth: SCO socket layer initialized
[    1.383990] Bluetooth: HCI UART driver ver 2.3
[    1.386709] Bluetooth: HCI UART protocol H4 registered
[    1.389369] Bluetooth: HCI UART protocol Three-wire (H5) registered
[    1.392104] Bluetooth: HCI UART protocol Broadcom registered
[    1.392292] hci_uart_bcm serial0-0: supply vbat not found, using dummy regulator
[    1.397354] hci_uart_bcm serial0-0: supply vddio not found, using dummy regulator
[    1.775624] Bluetooth: hci0: BCM: chip id 94
[    1.779280] Bluetooth: hci0: BCM: features 0x2e
[    1.793200] Bluetooth: hci0: BCM43430A1
[    1.795585] Bluetooth: hci0: BCM43430A1 (001.002.009) build 0000
[    1.801079] Bluetooth: hci0: BCM43430A1 'brcm/BCM43430A1.raspberrypi,model-zero-2-w.hcd' Patch
[    2.225426] dwc2 3f980000.usb: supply vusb_d not found, using dummy regulator
[    2.227866] dwc2 3f980000.usb: supply vusb_a not found, using dummy regulator
[    2.333797] dwc2 3f980000.usb: EPs: 8, dedicated fifos, 4080 entries in SPRAM
[    3.112583] NET: Registered PF_INET6 protocol family
[    3.180252] IPv6: ADDRCONF(NETDEV_CHANGE): wlan0: link becomes ready
[    3.182830] Segment Routing with IPv6
[    3.187066] In-situ OAM (IOAM) with IPv6
[    3.390499] file system registered
[    3.439430] read descriptors
[    3.441607] read strings
[    4.456249] Bluetooth: hci0: BCM: features 0x2e
[    4.554131] uart-pl011 3f201000.serial: no DMA platform data
[    6.473577] Bluetooth: hci0: command 0x0c14 tx timeout
[   14.553562] Bluetooth: hci0: BCM: Reading local name failed (-110)

**Comment by pelwell** [comment]
This looks like a symptom of undervoltage.
1. What power supply are you using?
2. What other hardware is attached?
3. What does `vcgencmd get_config int | grep volt` report?
4. How about `vcgencmd measure_volts`?

You could try adding `over_voltage=2` to config.txt, to see if that helps. If you aren't using WiFi, try with `dtoverlay=disable-wifi` in config.txt.

**Comment by manio** [comment]
> This looks like a symptom of undervoltage.
> What power supply are you using?

The Pi is powered from the car headunit's USB - the project is DIY AndroidAuto dongle.

> What other hardware is attached?

LoRa device - but unused during this tests.

> What does vcgencmd get_config int | grep volt report?
> How about vcgencmd measure_volts?

I'll try that later, thanks

> You could try adding over_voltage=2 to config.txt, to see if that helps. If you aren't using WiFi, try with dtoverlay=disable-wifi in config.txt.

I am using WiFi and BT (and serial for LoRa), so I'll start with that `over_voltage` first.

**Comment by manio** [comment]
```
# vcgencmd get_config int | grep volt
over_voltage_avs=6250
# vcgencmd measure_volts
volt=1.2563V
```
Is it ok?

**Comment by pelwell** [comment]
It's fine - I just wanted to see if your Z2W had any voltage headroom, and it does. The limit is 1.4V, so if over_voltage=2 doesn't show any improvement, you can can go higher. Higher voltages won't do any damage in the short term, but they can theoretically shorten the life of the device, so use the lowest that works, and remove it if it doesn't help at all.

**Comment by manio** [comment]
Some small update on this:
I started with over_voltage=1
```
# vcgencmd get_config int | grep volt
over_voltage=1
over_voltage_avs=6250
# vcgencmd measure_volts
volt=1.2813V
```
I had a feeling that it helped but suddenly I encounter the same problem.
So now I am testing it with level 2:
```
# vcgencmd get_config int | grep volt
over_voltage=2
over_voltage_avs=6250
# vcgencmd measure_volts
volt=1.3062V
```

I forgot to mention one important detail:
As I need a full featured serial to the external LoRa device and I also need bluetooth, so I set this:
`dtoverlay=pi3-miniuart-bt` (but without core_freq=250 as I don't want to degrade speed, I believe it is 400 IIRC)

and I also have this:
`dtparam=krnbt=on`
Which means that no hciattach is needed (in fact in this custom build the binary is missing).

I also found this: https://raspberrypi.stackexchange.com/questions/47284/pi3-and-mini-uart-bt
Where there seems to be identical problem which I currently have!
Even despite the proper `core_freq` set.

Overal... if the higher voltage can't fix this, I think I will try with removing `krnbt=on` and manually running:
```/usr/bin/hciattach /dev/ttyS0 bcm43xx 921600 noflow -```

And I believe it will force to reload the firmware (module unload is doing nothing as I stated above).

**Comment by manio** [comment]
Today's update:
Hah... I was pretty sure that `over_voltage=2` helped!
It was working really well - I tested it heavily making a plenty of reboots.
But I decided to test it longer... and unfortunately today the problem appear again:
`[    6.473608] Bluetooth: hci0: Opcode 0x204b failed: -110`
And the same problem... no bt adapter.

This time I decided to not test with higher overvoltage but increase the boot_delay instead:
`boot_delay=3`

Testing...

**Comment by manio** [comment]
Update:
Same problem:
```
[    6.553570] Bluetooth: hci0: command 0x0c25 tx timeout
[    6.556333] Bluetooth: hci0: Opcode 0x c25 failed: -110
```
I now disabled the `boot_delay` and `over_voltage=2` and added:
`core_freq=250`
Testing ...

@pelwell 
I also temporarily disabled the line `dtparam=krnbt=on` with manual hciattach`ing in mind - but to my surprise - I didn't notice any change: the bluetooth started automatically. Is this desired behavior? How can I force to use hciattach by me?

**Comment by pelwell** [comment]
>  I didn't notice any change

That's because, after several years, we changed the default to `on`. You'll need `dtparam=krnbt=off` to revert to using hciattach, but that is not guaranteed to work forever.

**Comment by pelwell** [comment]
```
pi@raspberrypi:~ $ dtparam -h krnbt
krnbt                   Set to "off" to disable autoprobing of Bluetooth
                        driver without need of hciattach/btattach
                        (default "on")
```

**Comment by pelwell** [comment]
There is an experiment you could try:
1. Add `dtparam=krnbt=off` to config.txt.
2. `sudo systemctl disable hciuart`.
3. Reboot.
4. When you get to a command line: `sudo /usr/bin/btuart`
5. Check with `hcitool dev` and `dmesg -l err,warn§`.

To revert, remove the dtparam from config.txt, `sudo systemctl enable hciuart` and reboot.

**Comment by manio** [comment]
@pelwell 
I was trying to do `dtparam=krnbt=off` and then playing with what's inside `btuart` script but it seems the device was still loaded by kernel and not with my `hciattach` util, BUT: this is not currently important, because:

I hope I finally found the root cause of my problems:
It was indeed the missing `core_freq=250` !!!
I know that documentation was saying that. But I was confused because 90% of the time it was working fine, so why downgrade pi performance? No! It seems this was indeed the missing puzzle !

I don't want to declare success prematurely but it is over a week (plenty of reboots) and I have 100% success rate with starting bluetooth, so I want to believe that this was it! :)

Thank you very much for your help and giving me the tips.

**Comment by pelwell** [comment]
I'm glad you solved it. FYI, in recent firmwares there is a new option - `core_freq_fixed`. If you set it to 1, prevents the core clock from changing without the need to know what the platform's core frequency range is. It's intended for users of I2C and SPI, because the firmware doesn't automatically fix the core clock when they have been enabled.
