### ISSUE TITLE
FIQ related warnings in dmesg (3.15.5)

### ISSUE THREAD

**Issue by ha5di** [raspberrypi/linux#649]
Hi

I see below warnings in dmesg. Are they harmless or I have to do someting with them?

Thanks... Bela

[    3.774805] Using Buffer DMA mode
[    3.774827] Periodic Transfer Interrupt Enhancement - disabled
[    3.774838] Multiprocessor Interrupt Enhancement - disabled
[    3.774850] OTG VER PARAM: 0, OTG VER FLAG: 0
[    3.774866] Dedicated Tx FIFOs mode
[    3.775270] WARN::dwc_otg_hcd_init:1042: FIQ DMA bounce buffers: virt = 0xdbc14000 dma = 0x5bc14000 len=9024
[    3.775305] FIQ FSM acceleration enabled for :
Non-periodic Split Transactions
Periodic Split Transactions
[    3.775329] dwc_otg: Microframe scheduler enabled
[    3.775388] WARN::hcd_init:473: FIQ at 0xc034b5f4
[    3.775405] WARN::hcd_init:474: FIQ ASM at 0xc034b8a4 length 36
[    3.775434] WARN::hcd_init:500: MPHI regs_base at 0xdc80e000
[    3.775465] dwc_otg bcm2708_usb: DWC OTG Controller
[    3.775520] dwc_otg bcm2708_usb: new USB bus registered, assigned bus number 1
[    3.775574] dwc_otg bcm2708_usb: irq 32, io mem 0x00000000
[    3.775613] Init: Port Power? op_state=1
[    3.775624] Init: Power Port (0)
[    3.775970] usb usb1: New USB device found, idVendor=1d6b, idProduct=0002
[    3.775994] usb usb1: New USB device strings: Mfr=3, Product=2, SerialNumber=1
[    3.776009] usb usb1: Product: DWC OTG Controller
[    3.776023] usb usb1: Manufacturer: Linux 3.15.5-piCore+ dwc_otg_hcd
[    3.776036] usb usb1: SerialNumber: bcm2708_usb
[    3.776887] hub 1-0:1.0: USB hub found
[    3.776971] hub 1-0:1.0: 1 port detected
[    3.777470] dwc_otg: FIQ enabled
[    3.777488] dwc_otg: NAK holdoff enabled
[    3.777498] dwc_otg: FIQ split-transaction FSM enabled
[    3.777521] Module dwc_common_port init
[    3.777993] usbcore: registered new interface driver usb-storage
[    3.778618] mousedev: PS/2 mouse device common for all mice

**Comment by popcornmix** [comment]
That's normal. Just reporting some debug info.

**Comment by ha5di** [comment]
Thanks.
