### ISSUE TITLE
rp1-firmware: probe of rp1_firmware failed with error -110

### ISSUE THREAD

**Issue by spockfish** [raspberrypi/linux#6493]
### Describe the bug

Latest build (99a0201) introduces this error message which wasn't there before.

### Steps to reproduce the behaviour

boot up.

### Device (s)

Raspberry Pi 5

### System

6.6.63

**Comment by pelwell** [comment]
It means that the Pi 5 EEPROM image isn't the latest version that support the firmware interface. This is harmless.

**Comment by spockfish** [comment]
Ok thanks. I'll close the issue.

**Comment by pelwell** [comment]
I will consider squashing the error message if there are complaints.
