### ISSUE TITLE
Feature request: Include iwlwifi kernel module as part of standard kernel build

### ISSUE THREAD

**Issue by evilmonkeyslayer** [raspberrypi/linux#6497]
### Describe the bug

Feature request:

With the addition of pcie adapters this allows pcie devices to be plugged into the Pi 5 that were previously not usable.

This is a request to include in the standard kernel build the iwlwifi module and related modules so that devices such as the Intel AX210 which is a very common wifi chipset to be usable on the Pi 5.

This requires the following in the kernel .config file:

> CONFIG_IWLWIFI=m
> CONFIG_IWLWIFI_LEDS=y
> CONFIG_IWLDVM=m
> CONFIG_IWLMVM=m
> CONFIG_IWLWIFI_OPMODE_MODULAR=y
> \#
> \# Debugging Options
> \#
> \# CONFIG_IWLWIFI_DEBUG is not set
> CONFIG_IWLWIFI_DEVICE_TRACING=y
> \# end of Debugging Options

### Steps to reproduce the behaviour

N/A

### Device (s)

Raspberry Pi 5

### System

N/A

**Comment by evilmonkeyslayer** [comment]
I rolled a custom kernel with the above config settings applied and with firmware-iwlwifi installed via apt the wifi worked.

The only issue I can see is that the wifi gui applet for some reason doesn't see 6GHz wifi networks, but if the ssid is manually set it will connect to them and work just fine. (with the little gui "5" next to it, even though it's 6GHz)

**Comment by rowingdude** [comment]
This is not something likely to be included. It's not a RPi core piece of hardware and therefore has no place in the mainstream kernel.

**Comment by pelwell** [comment]
That's nonsense (or reverse psychology) - the majority of the hundreds of modules are for non-Raspberry Pi hardware.

**Comment by evilmonkeyslayer** [comment]
> That's nonsense (or reverse psychology) - the majority of the hundreds of modules are for non-Raspberry Pi hardware.

I was going to post a reply along these lines, there are a significant number of nic and wlan drivers set to compile as modules by default with the standard pi kernel. Including the iwlwifi modules doesn't use much space at all.

For example, from the modules dir:

```
184K    iwlwifi/mvm
80K     iwlwifi/dvm
400K    iwlwifi/
```

I would also add that it also has a number of ethernet drivers compiled into the pi kernel itself that are not used at all. There are for example 10GbE PCIE adapters like "Intel(R) 10GbE PCI Express adapters support".

Actually not including iwlwifi seems a bit odd because there is some selections in the default pi kernel that should be the opposite of being selected and some that should be in the default pi kernel.

**Comment by pelwell** [comment]
I'll add them next time I'm near a keyboard.

**Comment by pelwell** [comment]
Pull request #6526 adds the required modules. To install a trial build, wait about 40 minutes then run `sudo rpi-update pulls/6526` (after backing up any important data).

**Comment by pelwell** [comment]
The PR is merged, so the new modules will be hitting all the usual kernel builds soon.

**Comment by timwb** [comment]
Great to have this - however it seems to have disappeared again from the next branch / 6.12 kernel branch. Could this module be included there as well? Thanks!

**Comment by geerlingguy** [comment]
And just like that, another reason I _don't_ have to recompile the kernel so much...
