### ISSUE TITLE
[bcm2708_fb] wrong physical screen dimension info?

### ISSUE THREAD

**Issue by maxnet** [raspberrypi/linux#65]
I am getting very small unreadable fonts displayed in an application that uses the Qt 4 Embedded library (which uses the framebuffer directly, instead of standard Qt that uses X).
This seems to be caused by the framebuffer module advertising wrong physical screen dimensions, which I suspect the library uses to do some kind of DPI/font size calculation.

in bcm2708_fb_register() you have:
# 

```
fb->fb.var.height = fbwidth;
fb->fb.var.width = fbheight;
```
# 

Besides width and height being swapped, it seems those fields are meant to be filled in with the physical size of the display in mm:
# 

```
__u32 height;           /* height of picture in mm    */
__u32 width;            /* width of picture in mm     */
```
# 

My application does work properly if I change the code to:
# 

```
fb->fb.var.height = -1;
fb->fb.var.width = -1;
```
# 

to match what the vesafb driver is setting to indicate it doesn't know the size.

**Comment by popcornmix** [comment]
This should be fixed now. Can you test and close?

**Comment by maxnet** [comment]
Thanks. Works.
