### ISSUE TITLE
[6.12][RPI5][KVM] VGIC interrupt is not initialized

### ISSUE THREAD

**Issue by tolumak** [raspberrypi/linux#6550]
### Describe the bug

On RPI5:
With branch 6.12.y and 6.13.y, vgic interrupt is not initialized.

Output of /proc/interrupts in 6.6.y:
`
$ cat /proc/interrupts  | grep vgic
  9:          0          0          0          0     GICv2  25 Level     vgic
`
The same with 6.12.y:
`
$ cat /proc/interrupts  | grep vgic
`

It prevents KVM to be used.
For example on 6.6, output of following command is "UEFI firmware" message, then a blank screen with blinking cursor and then "PXE boot" prompt as expected. 
`
qemu-system-aarch64 -M virt -cpu max -enable-kvm  -bios /usr/share/AAVMF/AAVMF_CODE.fd -nographic
`
The same on 6.12, is "UEFI firmware" message, then blank screen and nothing else afterwards.
It seems to be a problem with 

### Steps to reproduce the behaviour

1- install qemu-system-arm
2- update to 6.12 with 
`
sudo rpi-update next
sudo reboot
`
3-
`
qemu-system-aarch64 -M virt -cpu max -enable-kvm  -bios /usr/share/AAVMF/AAVMF_CODE.fd -nographic
`

### Device (s)

Raspberry Pi 5

### System

cat /etc/rpi/issue
Raspberry Pi reference 2024-11-19
Generated using pi-gen, https://github.com/RPi-Distro/pi-gen, 891df1e21ed2b6099a2e6a13e26c91dea44b34d4, stage2

vcgencmd version
2024/12/07 12:42:23 
Copyright (c) 2012 Broadcom
version 3858f977 (release) (embedded)

uname -a
Linux raspberrypi 6.12.3-v8+ #1826 SMP PREEMPT Tue Dec 10 10:10:07 GMT 2024 aarch64 GNU/Linux

### Logs

with 6.6:
`
$ dmesg | grep kvm
[    0.649035] kvm [1]: IPA Size Limit: 40 bits
[    0.649046] kvm [1]: GICV region size/alignment is unsafe, using trapping (reduced performance)
[    0.649064] kvm [1]: vgic interrupt IRQ9
[    0.649075] kvm [1]: VHE mode initialized successfully
`

with 6.12:
`
$ dmesg | grep kvm
[    0.694262] kvm [1]: nv: 554 coarse grained trap handlers
[    0.694362] kvm [1]: IPA Size Limit: 40 bits
[    0.694382] kvm [1]: VHE mode initialized successfully
`

The line about vgic interrupt is missing

### Additional context

I found the issue which is missing interrupt declaration in bcm2712.dtsi and I will submit a pull request

**Comment by pelwell** [comment]
Thanks - the GICv2 declaration in the upstream bcm2712.dtsi file (which we are now using) is lacking the `GIC_PPI 9`  interrupt. I'll add it the `bcm2712-ds.dtsi` (downstream adjustments) file - no need to PR.

**Comment by tolumak** [comment]
Ok, thank you very much for the fix.
