### ISSUE TITLE
Weird effect using W1 with DS18B20 and latest firmware

### ISSUE THREAD

**Issue by crashmaster1** [raspberrypi/linux#661]
Using the latest firmware (dated July, 30) the DS18B20 1wire sensor always returns a temperature of 85 degrees on my RPi B. With older firmware versions it works fine.

Due to DS18B20 specification the sensor returns always 85 degrees when it is reset. I use it with 3.3 Volts and a 4.7k pullup at gpio 4 using 3.15.x and 3.16.0 kernels.
I also tried it with internal pullup on/off in w1_gpio and strong_pullup in 'w1_therm' modules without success.

So the question (for me) is: 
What has been changed in the firmware? It looks like the gpio's get another initialization now.

So far i will stay with the older firmware version.

**Comment by popcornmix** [comment]
First run rpi-update to get the 6th August firmware and confirm it's still an issue.

Next you confirm if it is the firmware (start.elf) or kernel that causes the issue?

This firmware: https://github.com/Hexxeh/rpi-firmware/commit/494947fa1719e453ed9d7b48a8a446d3ad689d70
added "gpioman" which allows custom gpio configuration.

so it may be worth using rpi-update to revert to just before and just after that update to see if gpioman caused the issue.

**Comment by crashmaster1** [comment]
Thanks popcornmix, it works again with your very latest firmware and i didn't configure any gpio settings !

I didn't change my selfcompiled kernel (3.16.0), because i use "f2fs" which isn't included in 3.12 versions.

So thanks again!
