### ISSUE TITLE
pcm512x 1-004d: Failed to reset device: -5

### ISSUE THREAD

**Issue by maxnet** [raspberrypi/linux#662]
This probably won't show up on Raspbian because i2c is blacklisted by default there, but on other distributions, some errors are ruining previously quiet console output:

> [   19.315414] pcm512x 1-004d: Failed to reset device: -5
> [   19.322769] pcm512x 1-004c: Failed to reset device: -5

Seems udev is triggered to load the snd_soc_pcm512x module twice and snd_soc_wm8804 once, due to the i2c declarations here: 

https://github.com/raspberrypi/linux/blob/rpi-3.12.y/arch/arm/mach-bcm2708/bcm2708.c#L663
https://github.com/raspberrypi/linux/blob/rpi-3.12.y/arch/arm/mach-bcm2708/bcm2708.c#L708
https://github.com/raspberrypi/linux/blob/rpi-3.12.y/arch/arm/mach-bcm2708/bcm2708.c#L677

Should there really be static declarations for hardware add-ons that may or may not be present?

**Comment by popcornmix** [comment]
> Should there really be static declarations for hardware add-ons that may or may not be present?

No.
Suggestions for the best way to solve this are welcome.

**Comment by maxnet** [comment]
I think the i2c codec can be registered in the init function of the module that actually wants to use the thing (hifiberry?)

Another module seems to be doing that by having i2c_get_adapter / i2c_new_device there, instead of having  i2c_register_board_info in the mach file.
https://github.com/raspberrypi/linux/blob/rpi-3.12.y/sound/soc/pxa/magician.c#L491

Should be tested by someone that actually has that add-on board though.

**Comment by notro** [comment]
This is a really good example of [HAT](https://github.com/raspberrypi/hats) coming to the rescue :-)

I see three solutions for this:
1. as @maxnet suggests, let the driver/module itself take care of this
2. Make a module that just loads the necessary device. Separation of concerns.  
   This module can probe to see if the hardware is present before adding the device.  
   (or add a module that handles all of these "can be present devices".)
3. Add a kernel commandline argument to enable adding the device: bcm2708.hifiberry=1

**Comment by agherzan** [comment]
Hi guys. So just to clarify this for me. pcm512x ti codec is only present on B+ and not on earlier version HW? Because this error is not seen on a B version.

**Comment by pelwell** [comment]
The codec is not present on any Pi, unless you have added a board that includes one.

This is an example of Device Tree coming to the rescue. :-p

If you update to the latest releases, these errors will go away. The flip side is that if you want to use the i2c, i2s or spi interfaces then you have to enable them. Take a look at the new README in /boot/overlays for an introduction to the topic.

**Comment by agherzan** [comment]
Cool stuff. Thanks.

**Comment by popcornmix** [comment]
@maxnet okay to close?
i assume you don't get this issue on 3.18/DT kernel.

**Comment by maxnet** [comment]
Yes, this issue is not present when using the 3.18 kernel with a device tree.
(as long as one does not forget to run mkknlimg, or it will ruin quiet console output with messages about missing cpu node definitions instead)
So can be closed.

**Comment by Mausy5043** [comment]
I'm not sure I understand the above discussion, but I see the error on my Raspberries (all are on `jessie`).
1. R-Pi model B (`Linux rbelec 3.18.0-trunk-rpi #1 PREEMPT Debian 3.18.5-1~exp1+rpi19 (2015-08-08) armv6l GNU/Linux`)
   
   ```
   Oct 18 16:31:17 rbelec kernel: pcm512x 1-004d: Failed to reset device: -5
   Oct 18 16:31:17 rbelec kernel: pcm512x: probe of 1-004d failed with error -5
   Oct 18 16:31:17 rbelec kernel: pcm512x 1-004c: Failed to reset device: -5
   Oct 18 16:31:17 rbelec kernel: pcm512x: probe of 1-004c failed with error -5
   ```
2. R-Pi model B+ (`Linux rbian 3.18.0-trunk-rpi #1 PREEMPT Debian 3.18.5-1~exp1+rpi19 (2015-08-08) armv6l GNU/Linux`)
   
   ```
   Oct 18 16:19:42 rbian kernel: pcm512x 1-004d: Failed to reset device: -5
   Oct 18 16:19:42 rbian kernel: pcm512x: probe of 1-004d failed with error -5
   Oct 18 16:19:42 rbian kernel: pcm512x 1-004c: Failed to reset device: -5
   Oct 18 16:19:42 rbian kernel: pcm512x: probe of 1-004c failed with error -5
   ```

The config.txt files all look like this:

```
$ cat /boot/config.txt
[pi1]
kernel=vmlinuz-3.18.0-trunk-rpi
initramfs initrd.img-3.18.0-trunk-rpi followkernel
# to enable DeviceTree, comment out the next line
device_tree=
gpu_mem=16

arm_freq=950
core_freq=450
sdram_freq=450
over_voltage=6

arm_freq_min=700
core_freq_min=250
sdram_freq_min=400
over_voltage_min=0

force_turbo=0
```

How can I make the errors go away?

**Comment by pelwell** [comment]
Enable Device Tree (comment out/delete the device_tree= line).

**Comment by Mausy5043** [comment]
@pelwell  : That just makes the kernel panicky.
ref: https://github.com/raspberrypi/linux/issues/914#issuecomment-96233829

Just tried it to make sure. Kernel panics at boot. Can't remove the `device_tree=` line

**Comment by pelwell** [comment]
Upload your crash logs somewhere in case they say something useful.

If you _have_ to keep DT disabled then you'll need to blacklist the modules you don't want.

**Comment by Mausy5043** [comment]
@pelwell :  #914 documents the problem pretty well. There's already several logs attached to that issue.

I think there's a relation with that problem.
