### ISSUE TITLE
weird issue in kernel >= 3.12

### ISSUE THREAD

**Issue by pete111** [raspberrypi/linux#670]
I made this thread in conjunction with this https://github.com/raspberrypi/linux/issues/660
As I wrote there it is not stk1160 issue (as I thought before) but kernel >=3.12 issue.
RPi with >=3.12 is not working well but kernel up to 3.10.28 is not affected. 
The main problem is somewhere in the newest kernel >=3.12 because stk1160 device is not working correctly. (please read https://github.com/raspberrypi/linux/issues/660 where I wrote more about various type of kernels and driver versions)

How to fix it?

**Comment by blamesoft** [comment]
I am also having this issue with my B+ and 3.12
STK1160 = /dev/video0 does not show up
Empia = /dev/video0 shows up, but the screenshots are black
USBTV007 = I have one on order, but I'm thinking it'll have the same results as the SKT1160

Lightberry.eu created a custom OpenELEC image, but it only supports the Fushicai USBTV007 grabber, though I'm going to try the STK1160 anyways.

**Comment by Ruffio** [comment]
@pete111 has this issue been resolved? If yes, then please close this issue.

**Comment by Ruffio** [comment]
This issue should be closed due to inactivity. Last activity was on 6 Sep 2014, and I have pinged on 10 Aug 2016 without any response...
