### ISSUE TITLE
rpi-3.15.y: Unable to boot kernel since commit 42f78884c65f580e246331f715f61a54ee139f5c..HEAD

### ISSUE THREAD

**Issue by reubenfarrelly** [raspberrypi/linux#674]
I've got an RPi set up as a stratum 1 NTP server at home, following the instructions here:
http://www.satsignal.eu/ntp/Raspberry-Pi-NTP.html.  I have been building custom kernels for this Pi using the bcm2708 patch and instructions at http://www.satsignal.eu/raspberry-pi/kernel-recompile.html .  Aside from that patch, the code is otherwise cloned straight from https://github.com/raspberrypi/linux/.  The Pi has an up-to-date Pidora installation for it's userspace and I'm cross-compiling the kernels on a Fedora VM (so much faster!).

So far this process and the kernels have worked well and I have been tracking the 3.15.y "stable" git repository for the last few months to do this.

However upon updating this kernel to anything beyond the commit ID above, with no changes to the .config file, the Pi will not boot up.  It loads the kernel and then displays a black screen - which makes it rather difficult to see what is wrong.  If I roll back to my 3.15.5 kernel it all works.   The very next commit further on from the ID above is "BCM2708: Add core Device Tree support", which makes me think that that is where the problem was introduced.

I've also tried using rpi-3.16.y code from the repository as of a few hours ago and it exhibits the same problem.  I am not using Device Tree.

My kernel config for the Pi is at:  http://www.reub.net/files/kernel/config-3.15.5-rpi

I am hoping someone can take a look at this and confirm if this is a code issue and ideally fix it....

If there is a better forum to take this post please let me know.

Thanks,
Reuben

**Comment by Neverous** [comment]
I had similar issues(kernel booting to black and nothing on console) and I resolved them by disabling Flattened Device Tree Support (CONFIG_USE_OF).

**Comment by reubenfarrelly** [comment]
Thanks Neverous, indeed that change fixed it for me as well!  I guess there's still a bug there in that it shouldn't be possible to have kernel config options break things in this way, but at least it's now working and I'm happily running 3.16.1, so I'm happy :+1:

**Comment by notro** [comment]
I just checked out rpi-3.16.y and did: `ARCH=arm make bcmrpi_defconfig`
This gave me:

```
$ grep USE_OF .config
# CONFIG_USE_OF is not set
```

Are you using an old .config to start with?
If so, you're asked questions about what to do with the new config options like: CONFIG_BCM2708_DT. Answering yes on this enables Device Tree support.

**Comment by popcornmix** [comment]
Yes, it's not a bug. If you enable device tree support you need to make other changes to provide a device tree blob. The default config disables device tree. Don't enable it unless you know how to use it.

**Comment by reubenfarrelly** [comment]
This was an "upgrade" .config, ie from 3.14 to 3.15 and 3.16 and at each stage prior to building a new kernel, doing a 'make oldconfig'.  Unfortunately I don't have historical .configs going any further back than when I started seeing the problem though.

However after some consideration I am fairly sure that what has happened is that CONFIG_USE_OF was defined and inherited from the distribution .config file from which I originally based my own .config on, some months ago.  Notably this kernel option is still set in the Pidora config even as of today.  I selected No to CONFIG_BCM2708_DT option at a late date when the option came up in the make oldconfig when I built my own kernel.
That at least explains how I have ended up with "Flattened Device Tree" enabled but "Device Tree" disabled and things not working.  Because I haven't ever attempted to actually enable or use Device Tree...

**Comment by Ruffio** [comment]
@reubenfarrelly has this issue been resolved? If yes, then please close this issue.

**Comment by Ruffio** [comment]
This issue should be closed due to inactivity. Last activity was on 26 Aug 2014, and I have pinged on 10 Aug 2016 without any response...

**Comment by reubenfarrelly** [comment]
Sorry - yes - happy to close off.
