### ISSUE TITLE
modprobe snd-soc-hifiberry-dacplus and DAC+

### ISSUE THREAD

**Issue by zespre** [raspberrypi/linux#678]
Hadrware: Raspberry Pi B+ and HiFiBerry DAC+ (http://www.hifiberry.com/dacplus)
Software: OpenELEC 4.1.5

Trying to make work sound on DAC+

After putting:
modprobe snd-soc-hifiberry-dacplus
sleep 3

in /storage/.config/autostart.sh

there are options in XBMC in Settings: System: Audio Output:
- PI: HDMI
- PI: Analogue
- PI: ALSA: Default (snd_rpi_hifiberry_dacplus Analog)

After selecting ALSA a green led on DAC+ turns on but the is also a total system freeze (no ping, need to power off)

**Comment by hifiberry** [comment]
This is a problem with an older (non B+) kernel. Use OpenElec 3.1.6 it is based on a kernel with B+ support.

**Comment by pelwell** [comment]
Can we close this now?

**Comment by zespre** [comment]
Yes, it's finally working :)
Thanks a lot!
