### ISSUE TITLE
Enable module "elo"

### ISSUE THREAD

**Issue by vranki** [raspberrypi/linux#680]
Please compile module "elo" in the default kernel. It is the most common driver for touchscreen displays. Without it, the only way to get a elo touchscreen to work is to use elographics Xorg driver which it is buggy. Evdev is the modern way  to use touchscreens anyway.

**Comment by popcornmix** [comment]
So you would like
CONFIG_HID_ELO=m
enabled?

**Comment by vranki** [comment]
Yes, exactly.

**Comment by popcornmix** [comment]
Okay will add in next update.

**Comment by vranki** [comment]
Great, thanks!

**Comment by popcornmix** [comment]
This should be in rpi-update firmware.
