### ISSUE TITLE
Linux 3.16, BCM2835 MMC driver - DMA doesn't work

### ISSUE THREAD

**Issue by gentoo-root** [raspberrypi/linux#682]
I've built Linux 3.16.1 (from this tree: https://github.com/raspberrypi/linux/tree/09b94e49b06b57440db8d308900d240dc90c04f4) and I have the following error in dmesg:

mmc-bcm2835: Unable to initialise DMA channels. Falling back to PIO

It looks like DMA does not work for me. I use Raspberry Pi model B+.

Here is my kernel config: http://pastebin.com/WzZMheJv
Here is my dmesg: http://pastebin.com/Xzi14TuV

**Comment by gentoo-root** [comment]
Not a bug, seems I was just missing CONFIG_DMA_BCM2708=y.

**Comment by popcornmix** [comment]
The arch/arm/configs/bcmrpi_defconfig contains the recommended .config settings.

```
make ARCH=arm bcmrpi_defconfig
```

will build with those options (and will have CONFIG_DMA_BCM2708 enabled). If you use a custom config then look closely at the diffs.

**Comment by phlegx** [comment]
Hi, I use https://github.com/debian-pi/raspbian-ua-netinst to install jessie on my Pi1. I get the same error: `mmc-bcm2835: Unable to initialise DMA channels. Falling back to PIO`

Any idea?

**Comment by pelwell** [comment]
I would guess that the DT blob (bcm27*.dtb) in your boot partition doesn't match the kernel. In our attempt to converge with the upstream kernel there will unfortunately be a few changes, like this one to the DMA driver, that require the kernel and DTB to be kept in sync.

**Comment by phlegx** [comment]
OK, so I cannot use Jessie for now?

**Comment by pelwell** [comment]
This problem is likely to be a mismatch between the kernel and the DTB. The fact that you are running a version of Jessie is likely to be irrelevant, but either way, you need to take it up with the maintainer of that distribution.

**Comment by phlegx** [comment]
OK thx @pelwell
