### ISSUE TITLE
3.16.2 - SD card is not available

### ISSUE THREAD

**Issue by ha5di** [raspberrypi/linux#686]
I have piCore running on Kernel 3.16.1 fine. Updating kernel to 3.16.2 with the same config system boots fine, network is OK, USB stick can be mounted, etc. However SD card is not seen. Updated firmware, tried another SD card, no change.

Any idea, how to fix it?

**Comment by popcornmix** [comment]
3.16.2 is used by OpenELEC (and me) so I'm sure sdcard isn't broken for everyone.

Are you using the bcmrpi_defconfig as you kernel config?

**Comment by ha5di** [comment]
I used my working 3.16.1 config just adding the new hifiberry dac as a module. For testing I built a new 3.16.2 kernel with default defconfig settings. It behaves differently; boots but stops in our startup where available disk partitions scanned, do not know yet in which step.

I will make a 3.16.1 kernel with default config to see difference to 3.16.2 if there is any.

**Comment by popcornmix** [comment]
Might be worth trying:
bcm2708.bcm2835_mmc=0
which disables the new mmc driver.

**Comment by ha5di** [comment]
Thanks, it did the trick and now it works with 3.16.2 built with our 3.16.1 config.

**Comment by ghollingworth** [comment]
What SD card are you using?

**Comment by ha5di** [comment]
Kingston HC 16GB Class10
PNY HC 8GB Class4

Same result

**Comment by crashmaster1** [comment]
Had the same problem on A and B (not B+) and disabling it like popcornmix told helped also, although i didn't set BCM2835_MMC in the kernel config.
I use Sony 4GB class4 sdcards.

**Comment by ha5di** [comment]
Rebuilding kernel with different configs now it works as expected enabling the new mmc driver built into the kernel, without. bcm2708.bcm2835_mmc=0

No other issue found, I'm happy with 3.16.2 

Issue can be closed.
