### ISSUE TITLE
bcm2708-i2s - bug with commit?

### ISSUE THREAD

**Issue by plughplover** [raspberrypi/linux#687]
I am **FAR** from being knowledgeable about kernel programming, but doesn't this commit
https://github.com/raspberrypi/linux/commit/c7de2839922e1948259c2c2a2beb58ad795a51ba
result in a, uh, address space leak? That is, every time a stream is initiated, doesn't this line
335     gpio = ioremap(GPIO_BASE, SZ_16K); 
allocate a _new_ page of address space to (re)map the gpio registers?

(If this is a dumb question, please be kind)

**Comment by popcornmix** [comment]
@ghollingworth any comments?

**Comment by ghollingworth** [comment]
It does look that way...

I'm not sure that is going to be a huge leak, but could be fixed...  (although in my defence I didn't write it!)

Gordon

**Comment by plughplover** [comment]
When it was called from the probe routine, it only got executed once; moving it to hw_params makes it an issue. I interpret the text associated with the commit to mean that having the bcm2708-i2s module automagically loaded at system boot (and hence changing the pin config) is a problem for someone using those pins for other purposes (understandable).

Perhaps a better solution is to leave the pin init in the probe (hence no ongoing leak) but require the addition of the i2s module to, uh, /etc/modules (like snd-bcm2835) for it to be loaded? And / Or alternatively add it to /etc/modprobe.d/raspi-blacklist.conf like the i2c-bcm2708 and spi-bcm2708 modules are now?  (not sure how those config files all play together).

Or simply unload the i2s module... oops - a different bug... It doesn't restore the pin config on unload! Bad driver! ;) Hey Koala, you obviously know all the Linux driver rules about using the regmap routines, is there a 'right' way for an Alsa driver to do that pin config (and unconfig)?

**Comment by ghollingworth** [comment]
The reason it was changed is because the alternate settings shouldn't be changed unless you are actually using the driver...  if you move it to the probe function then it does...

In future we'll be using the proper pinctrl driver so this is just a sticking plaster / bandaid solution

**Comment by plughplover** [comment]
Yeah, that's what I figured /said above. How about:

1) move call back to probe (+- one line of code)
2) add the module to raspi-blacklist.conf (+ one line)

then the pins only get tweaked when someone intentionally loads the module,
and you don't have an ever-expanding kernel address space leak...

Note that as things stand, i2s users need to edit /etc/modules anyway to add
bcm2708-dmaengine. They can simply add bcm2708-i2s at the same time.

BTW, the 'pinctrl driver' sounds interesting - where can I read up on it?

Thanks!

**Comment by popcornmix** [comment]
https://www.kernel.org/doc/Documentation/pinctrl.txt

**Comment by plughplover** [comment]
Thanks popcornmix, I'll give it a read.

FWIW, I know I'm 'new kid on the block' and am not trying to step on any toes, I'm just thinking about xbmc and other media player apps that use i2s DACs or spdif and start/stop streams a lot...

**Comment by popcornmix** [comment]
I don't think the ioremap is required. We already map gpio mem as IO in bcm2708.c (see bcm2708_gpio.c which is free to directly access these registers without ioremap).

I'll come up with a patch that removes the ioremap.

**Comment by popcornmix** [comment]
See: https://github.com/raspberrypi/linux/commit/c256eb9968c8997dce47350d2075e42f1b3991d3

This should have the same effect and avoids the ioremap.

**Comment by plughplover** [comment]
popcornmix, your patch is interesting. I've definitely got to look into that "mach/gpio.h" include file (and the pinctrl driver, too). 

I implicitly verified that the patch does not seem to break anything whilst testing #681.

As far as I'm concerned this issue can be closed.
Thanks!
