### ISSUE TITLE
ACT LED does not work in upstream [3.17-rc5] kernel

### ISSUE THREAD

**Issue by rfrht** [raspberrypi/linux#689]
The ACT LED indicating disk activity does not light up on a upstream (at least, 3.17-RC5) kernel when disk is in use.

**Comment by popcornmix** [comment]
I won't attempt to use 3.17 kernel until it goes stable, so can't help with that.
Did you rebase to 3.17 yourself?
Can you force the led high/low using /sys/class/gpio?

**Comment by rfrht** [comment]
Hello, popcornmix!

I've built the kernel following the howto from http://elinux.org/RPI_Upstreaming .

I'm uncertain if is it missing modules, but I couldn't change the LED state using GPIO. See the excerpt below:

```
[root@dimi ~]# echo 16 > /sys/class/gpio/export 
-bash: echo: write error: No such device

[root@dimi ~]# ll /sys/class/gpio
total 0
-rwxrwx--- 1 root gpio 4096 Sep 17 02:09 export
lrwxrwxrwx 1 root gpio    0 Jan  1  1970 gpiochip202 -> ../../devices/soc/20200000.gpio/gpio/gpiochip202
-rwxrwx--- 1 root gpio 4096 Jan  1  1970 unexport
```

**Comment by popcornmix** [comment]
That echo command works for me on 3.16.
If you build 3.16 with the same .config options, does it work for you?

If it does then it suggests something has changed upstream with gpio for 3.17 and needs changing in our mach-bcm2708 driver. Look through the changes for 3.17 and see if any commits affect gpio.

If that fails for you it suggests the .config options are wrong, and perhaps you should try using bcmrpi_defconfig.

**Comment by rfrht** [comment]
I'd happily try your .config. Can you make a pastebin?

**Comment by popcornmix** [comment]
Run:
make ARCH=arm bcmrpi_defconfig

and you'll get the "offical" .config.

**Comment by rfrht** [comment]
Um.... Not really, I think that things have changed in 3.17:

```
[rfreire@rfreire linux-3.17-rc5]$  ARCH=arm CROSS_COMPILE=${CCPREFIX} make bcmrpi_defconfig
***
*** Can't find default configuration "arch/arm/configs/bcmrpi_defconfig"!
***
make[1]: *** [bcmrpi_defconfig] Error 1
make: *** [bcmrpi_defconfig] Error 2
```

I think that the target have changed:

```
[rfreire@rfreire linux-3.17-rc5]$ ARCH=arm CROSS_COMPILE=${CCPREFIX} chrt -i 0 make bcm2835_defconfig
#
# configuration written to .config
#
```

**Comment by popcornmix** [comment]
I can only advise if you are using the raspberrypi kernel tree. This is the config I referred to:
https://github.com/raspberrypi/linux/blob/rpi-3.16.y/arch/arm/configs/bcmrpi_defconfig

**Comment by Ruffio** [comment]
@rfrht has this issue been resolved? If yes, please close this issue. Thanks.

**Comment by rfrht** [comment]
@Ruffio Ramsus, I'm closing it. Didn't try it in a recent fashion and TBH my request was not correct, as @popcornmix stated. Sorry about the confusion and thanks!
