### ISSUE TITLE
libpostproc-dev not installable any more (dependencies issue)

### ISSUE THREAD

**Issue by gkreidl** [raspberrypi/linux#691]
libpostproc-dev cannot be installed any more, because it needs libavutil-dev 6:0.8.13, but current version now is 6:9.14.

BTW, this makes it impossible to compile a newer VLC version with HW acceleration. (which was possible before the dist-upgrade).

**Comment by popcornmix** [comment]
This isn't a linux kernel issue, but a raspbian distribution issue. Best reported here:
http://www.raspberrypi.org/forums/viewforum.php?f=66
