### ISSUE TITLE
Frame lost  driver problem Syntek Semiconductor Co., Ltd STK1160 Video Capture Device

### ISSUE THREAD

**Issue by yovanf** [raspberrypi/linux#696]
I have been experiencing lots of problems trying to make the famous motion (VIDEO SECURITY APPLICATION) to work.
Here are some background information

Everything work well On Raspberry Pi B with ' 3.6.11+ #474 PREEMPT Thu Jun 13 17:14:42 BST 2013 armv6l GNU/Linux'

After my purchase of the Raspberry Pi B+ I had to install new Kernel and Firmware for it to work as the hardware mostly concerning the USB has changed. So I installed "3.12.28+ #709 PREEMPT Mon Sep 8 15:28:00 BST 2014 armv6l GNU/Linux"
What happens when I run motion , the video live stream is all broken up and starts filling the /var/log/messages with

URB packet 1, status -63 [Buffer error (overrun)]
print_err_status: 10 callbacks suppressed[/list]

Now taking the same image and putting it on a Raspberry PI B
Gives the same above errors.
Conclusion
The previous Kernel version 3.6.11 with the associated image works fine but the new Kernel 3.12.28 with the associated firmware has a severe problem.

I
Just would like to mention that I have tried to modify /boot/cmdline with relevant USB tweaks but I did not succeed in improving .

Please refer to https://github.com/raspberrypi/linux/issues/137 where same issue which had been fixed,  has now re-occured in newer firmware.

**Comment by Ruffio** [comment]
@yovanf has this issue been resolved? If yes, please close this issue. Thanks.

**Comment by sassmann** [comment]
Still seeing the problem on openELEC 7.0.1 (kernel 4.4.41 - RPi 3) with stk1160
Bus 001 Device 004: ID 05e1:0408 Syntek Semiconductor Co., Ltd STK1160 Video Capture Device
[   19.314387] URB packet 0, status -63 [Buffer error (overrun)].

**Comment by P33M** [comment]
Closing USB issues as OP has not updated the thread. Further comments by the OP stating that the issue is still present on latest rpi-update kernel will lead to a review.
