### ISSUE TITLE
RPi upstreaming - workflow considerations

### ISSUE THREAD

**Issue by pietrushnic** [raspberrypi/linux#698]
Both with @notro we would like to create and maintain repository with patches required for RPi support in upstream Linux kernel. We have some initial idea about workflow and want to ask about your opinion:
- Repository will based on [linux-stable](http://git.kernel.org/cgit/linux/kernel/git/stable/linux-stable.git)
- Branches will be called same as [raspberrypi/linux](raspberrypi/linux) repository so we will have `rpi-3.16.y` and next
1. Choose patches
2. Add patches to `rpi-3.16.y` branch
3. Prepare build -  `rpi-build`
4. Install it - `rpi-update`
5. Test it  - basic testing like booting, network, serial
6. Publish it on github - `rpi-build`
7. Wait for:
   - `rpi-3.16.y` update - there are few ways of handling this
     - merge update - patches are mixed with other commits
     - rebase `rpi-3.16.y` over upstream update - this breaks history but keeps patches on top
     - create new `rpi-3.16.y` branch on top of upstream changes and cherry-pick patches
     - other suggestions ?
   -  new release - `v3.17` - create `rpi-3.17.y`
     - cherry-pick all patches from `rpi-3.16.y`
     - other suggestions ?
8. goto 1

@notro prepared some initial stuff [rpi-bcm2835](notro/rpi-bcm2835) with little bit different approach. `rpi-bcm2835` keeps upstream patches in its repo and applies them over [linux-stable](http://git.kernel.org/cgit/linux/kernel/git/stable/linux-stable.git). Of course it builds and install results on hardware. I think `rpi-bcm2835` solution can be easily adopted to proposed workflow.

Let us know what you think about proposed workflow. Are we missing something ?

@popcornmix we believe that you can add your two cents as a user experienced with maintaining [raspberrypi/linux](raspberrypi/linux)

**Comment by popcornmix** [comment]
Ideally we'd like to use the upstream mach-bcm2835 kernel for Raspberry Pi.
Realistically there will always be patches that are tricky to upstream, or which are new and haven't appeared in a stable upstream kernel, so we'd end up using upstream kernel + patches.

Getting from where we are now to that position is tricky. Things will change. Things will break. Things will no longer be supported. It will need lots of testing. We'll probably need an optional testing branch (e.g. the BRANCH=next rpi_update firmware) for users who don't build their own kernel, but are happy to help with testing.

So any help you and @notro can provide with getting the upstream kernel functional and tested is welcome. We would have no problem with switching to an upstream kernel if (almost) everything can be made to continue working.

As far as how to maintain the patches, I personally prefer keeping the upstream and local commits well separated. That means either a tree that is rebased on each upstream merge, or a repo of patches with a script to apply those patches to the current upstream kernel tree.

Currently the stable tree (rpi-3.12.y) gets merged with upstream, which makes it hard to see the Pi specific patches. The later trees (e.g. rpi-3.16.y) are rebased which makes the Pi patches easily visible (at the expense of making history less visible).

As long as a rebased tree is tagged whenever an official kernel is produced from it, or the hashes are stored from the stable kernel tree and the patches tree then it should be possible to recreate any historical source tree.

It looks like https://github.com/notro/rpi-bcm2835 has gone for a git repo of patches with a script to apply them which seems fine to me.

**Comment by matthiasklein** [comment]
I would like to help in upstreaming.

Where can I see the progress?

**Comment by pietrushnic** [comment]
Please join #raspberrypi-kernel IRC channel on freenode. Some progress information is tracked [here](http://elinux.org/RPi_Upstreaming).

**Comment by Ruffio** [comment]
@pietrushnic this doesn't look like an 'issue'. Please close it. Thanks.
