### ISSUE TITLE
Add CONFIG_ARPD=Y to kernel config

### ISSUE THREAD

**Issue by nemphys** [raspberrypi/linux#699]
This option has already been included in Ubuntu kernels (after my request, see https://lists.ubuntu.com/archives/kernel-team/2013-August/032042.html discussion) since last year.

It causes no harm whatsoever, but enabling it allows OpenNHRP (http://sourceforge.net/projects/opennhrp) to work properly, which is essential for anyone trying to use the Pi as a router and implement DMVPN.

I already compile Pi kernels just for this option, it would be great if it was enabled by default!

**Comment by popcornmix** [comment]
No need.
The option has been made a default and is no longer configurable.
http://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/commit/?id=3e25c65ed085b361cc91a8f02e028f1158c9f255

**Comment by nemphys** [comment]
Yes, just noticed that, sorry
