### ISSUE TITLE
'GP_LEV0' undeclared

### ISSUE THREAD

**Issue by sraue** [raspberrypi/linux#7]
if i enable CONFIG_MMC_BCM2708 i get:

  CC      drivers/mmc/host/bcm2708_mci.o
drivers/mmc/host/bcm2708_mci.c: In function 'bcm2708_mci_get_cd':
drivers/mmc/host/bcm2708_mci.c:477:117: error: 'GP_LEV0' undeclared (first use in this function)
drivers/mmc/host/bcm2708_mci.c:477:117: note: each undeclared identifier is reported only once for each function it appears in
make[4]: **\* [drivers/mmc/host/bcm2708_mci.o] Error 1
make[3]: **\* [drivers/mmc/host] Error 2
make[2]: **\* [drivers/mmc] Error 2
make[1]: **\* [drivers] Error 2

 'GP_LEV0' is only used in drivers/mmc/host/bcm2708_mci.c and not declared.

**Comment by ghollingworth** [comment]
Old outdated driver
