### ISSUE TITLE
3.17.0 build issue - Arizona codec

### ISSUE THREAD

**Issue by ha5di** [raspberrypi/linux#708]
Building 3.17.0 get this error:

  Building modules, stage 2.
  MODPOST 1458 modules
ERROR: "arizona_request_irq" [sound/soc/codecs/snd-soc-arizona.ko] undefined!
make[1]: **\* [__modpost] Error 1
make: **\* [modules] Error 2

**Comment by crashmaster1** [comment]
+CONFIG_GPIO_ARIZONA=m
+CONFIG_MFD_ARIZONA_I2C=m
+CONFIG_MFD_ARIZONA_SPI=m
+CONFIG_MFD_WM5102=y
+CONFIG_REGULATOR=y
+CONFIG_REGULATOR_FIXED_VOLTAGE=m
+CONFIG_REGULATOR_ARIZONA=m
+CONFIG_SND_BCM2708_SOC_RPI_CODEC_WSP=m
+CONFIG_EXTCON=m
+CONFIG_EXTCON_ARIZONA=m

These are the Wolfson (Arizona) specific config lines.
Seems like a dependancy or module was missed and you have to activate it manually.
just a guess ...

**Comment by ha5di** [comment]
Thanks. What I did I used my working 3.16.3 config and enabled Wolfson, got the reported issue.

With default bcmrpi_defconfig kernel builds.

**Comment by popcornmix** [comment]
Looks like arizona_request_irq is defined when you select CONFIG_MFD_ARIZONA.
It is used when you define CONFIG_SND_SOC_ARIZONA or CONFIG_EXTCON_ARIZONA.

I'd have thought CONFIG_SND_SOC_ARIZONA and CONFIG_EXTCON_ARIZONA should either depend on or select CONFIG_MFD_ARIZONA, but these files weren't changed by the Wolfson PR, so this looks an upstream linux issue.

Check you get the same build error with the same config options on a generic upstream 3.17 kernel and if so report it to upstream linux code.

**Comment by ha5di** [comment]
OK, thanks. I edited manually .config per crashmaster1 advice and got 3.17.0 working in general. Unfortunately had no time to test whether Wolfsson really works or not.
