### ISSUE TITLE
3.17: modprobe snd-bcm2835 causes GPIO reset

### ISSUE THREAD

**Issue by ghost** [raspberrypi/linux#709]
When I modprobe snd-bcm2835 to enable sound, GPIOs reset - I have relays connected, making this easy to detect.  At the same time, in dmesg I get:

Oct 9 14:13:02 dresden kernel: [ 156.549456] LDO1: 1200 <--> 1800 mV at 1200 mV 
Oct 9 14:13:02 dresden kernel: [ 156.549578] LDO1: supplied by DC_1V8
Oct 9 14:13:02 dresden kernel: [ 156.573819] arizona spi0.1: Unknown device ID: 0
Oct 9 14:13:02 dresden kernel: [ 156.579693] pcm512x 1-004d: Failed to get supply 'AVDD': -517
Oct 9 14:13:02 dresden kernel: [ 156.601490] pcm512x 1-004d: Failed to get supplies: -517
Oct 9 14:13:02 dresden kernel: [ 156.615637] i2c 1-004d: Driver pcm512x requests probe deferral
Oct 9 14:13:02 dresden kernel: [ 156.615984] pcm512x 1-004c: Failed to get supply 'AVDD': -517
Oct 9 14:13:02 dresden kernel: [ 156.621922] pcm512x 1-004c: Failed to get supplies: -517
Oct 9 14:13:02 dresden kernel: [ 156.657366] i2c 1-004c: Driver pcm512x requests probe deferral

**Comment by popcornmix** [comment]
Does blacklisting (through /etc/modprobe.d/raspi-blacklist.conf)
snd-soc-arizona
snd-soc-pcm512x-i2c
snd-soc-pcm512x

(and any other sounds modules that are loaded) avoid the issue?

**Comment by ghost** [comment]
Yes, it took a few iterations, but this is the list of modules I needed to blacklist to remove the errors and allow snd-bcm2835 to be loaded without causing a problem:

blacklist arizona_ldo1
blacklist arizona_spi
blacklist i2c_bcm2708
blacklist snd-soc-arizona
blacklist snd-soc-pcm512x
blacklist snd-soc-pcm512x-i2c
blacklist snd_soc_bcm2708_i2s
blacklist snd_soc_tas5713
blacklist snd_soc_wm8804
blacklist spi_bcm2708

Perhaps they should be disabled in bcmrpi_defconfig?

**Comment by popcornmix** [comment]
If they are disabled in bcmrpi_defconfig then no-one can use them without rebuilding kernel (as bcmrpi_defconfig is used for official builds).
Ideally they should be dormant until explicitly modprobe'd, but no-one seems to have found a good way of achieving this.

If we don't find a better solution they will all be blacklisted in the next raspbian image update that includes the new modules. I suggest you continue with blacklisting the modules for now.

**Comment by Ruffio** [comment]
@macemoneta has this issue been resolved? If yes, please close this issue. Thanks.

**Comment by popcornmix** [comment]
Since moving to device tree the modules are not loaded by default so this shouldn't be a problem.

**Comment by Ruffio** [comment]
This issue should be closed due to inactivity. Last activity was on 10 Oct 2014, and I have pinged on 10 Aug 2016 without any response...
