### ISSUE TITLE
Enable USBTV

### ISSUE THREAD

**Issue by gregd72002** [raspberrypi/linux#711]
Hi, can we please enable USBTV module in the default kernel configuration? This is to do with EasyCap UTV007 device for video capturing. All other EasyCap devices are already enabled in the default kernel config but USBTV.

**Comment by popcornmix** [comment]
Okay.

**Comment by gregd72002** [comment]
Having tested the driver, it only supports NTSC format. The newer version of the driver do also support PAL formats. 

There is LKML patch for this:
https://lkml.org/lkml/2013/10/21/335

Kernel 3.14 has this patched applied.

What would it take to have this patch incorporated into rpi-3.12 kernel?

Thanks!

**Comment by popcornmix** [comment]
This should be done. Please rpi-update and test.

**Comment by P33M** [comment]
No response from OP, assuming fixed.

**Comment by gregd72002** [comment]
It is fixed. Thanks.
