### ISSUE TITLE
liblzo2 package compiled with inline x86 ASM, causes illegal instruction

### ISSUE THREAD

**Issue by lostromb** [raspberrypi/linux#712]
The liblzo2 package is a data compression library which uses some inline x86 ASM code to make some functions faster. In order to compile a binary that runs on non-x86 platforms, the build must be configured with a --disable-asm flag. This package in the Raspbian repository (for wheezy) was apparently built without this flag, which causes a kernel "Illegal Instruction" error as soon as any code is executed. Since liblzo2 is a dependency for the openvpn package, this bug breaks OpenVPN for any user that does not build liblzo and openvpn from scratch (or who does not recompile openvpn with the --disable-lzo option)

**Comment by P33M** [comment]
How is this related to the Raspberry Pi foundation shipped Linux kernel?

**Comment by popcornmix** [comment]
Probably best to report here:
http://www.raspberrypi.org/forums/viewforum.php?f=66
