### ISSUE TITLE
Where to find the matching kernel config?

### ISSUE THREAD

**Issue by matthiasklein** [raspberrypi/linux#715]
Where can I find the matching / recommended kernel configuration for e.g. the rpi-3.12.y branch?

The file arch/arm/configs/bcm2835_defconfig is over a year old.

**Comment by notro** [comment]
[bcmrpi_defconfig](https://github.com/raspberrypi/linux/blob/rpi-3.12.y/arch/arm/configs/bcmrpi_defconfig) is used to build the official kernel.

**Comment by matthiasklein** [comment]
Thanks!
