### ISSUE TITLE
Enable touchscreen support

### ISSUE THREAD

**Issue by ChrisHughes** [raspberrypi/linux#718]
I recently bought a [touchscreen LCD](http://www.sainsmart.com/7-inch-tft-lcd-monitor-for-raspberry-pi-touch-screen-driver-board-hdmi-vga-2av.html) marketed as being for Raspberry Pi and was disappointed to find that no touchscreen support is enabled in Raspbian's kernel by default.

With the upcoming focus on RPi launching their own touchscreen LCD add-on, I'm wondering if it is time that we enable support for USB Touch Screens out of the box, or as a downloadable package.

The touchscreen needs the 'USB touchscreen Driver' and Egalax controller [drivers enabled](http://blog.never-afk.de/wp-content/uploads/2014/05/raspi-menuconfig.png). I have tried [building the kernel myself](http://simonmcc.blogspot.ca/2013/08/raspberry-pi-rpi-kernel-build-for.html), but it was a lot of effort, and after several hours and a successful build, it had detected the touchscreen but the compiled kernel caused other issues on the Pi. I hate the idea of having to recompile my kernel constantly just to keep this thing working and stay on top of the latest updates. Forums are full of frustrated users trying to get these things working, so it's clear I'm not alone in requesting this. A few examples of other users struggling with this are below:

http://www.raspberrypi.org/forums/viewtopic.php?f=66&t=78937
http://raspberrypi.stackexchange.com/questions/22868/egalax-touchscreen-support-without-kernel-recompile-raspbian-os

Some other info relating to getting this working on the Pi:
http://engineering-diy.blogspot.ca/2013/02/raspberry-pi-raspbian-xbmc-and-egalax-7.html
http://simonmcc.blogspot.ca/2013/08/raspberry-pi-rpi-kernel-build-for.html
http://karuppuswamy.com/wordpress/2013/01/17/how-to-get-evtouch-touch-screen-kit-working-in-linux/

**Comment by kwagenknight** [comment]
I agree, this is getting taxing that they cant come out with a pre-compiled OS version for us by now! I have had this problem with my B+ for over a year feeling like NOTHING has been done anywhere to address this issue!

**Comment by ChrisHughes** [comment]
Are there any other forums / channels I can post this to in order to get the kernel dev's attention?

**Comment by popcornmix** [comment]
What exactly is required? Just adding:
CONFIG_TOUCHSCREEN_EGALAX=m
to kernel config?

**Comment by ChrisHughes** [comment]
@popcornmix It appears to be all that's needed, see this https://dev.bananian.org/print_bug_page.php?bug_id=54

**Comment by popcornmix** [comment]
Okay will add in next update.

**Comment by kwagenknight** [comment]
Great thank you sir!

**Comment by popcornmix** [comment]
Now added. Please run rpi-update and test.

**Comment by AloisKlingler** [comment]
regrettably this was not the right option for USB egalax touchscreens.

the right option is located in:
Device Drivers  --->
  Input device support  --->
    [*]   Touchscreens  --->
      < >   USB Touchscreen Driver (TOUCHSCREEN_USB_COMPOSITE)
        [ ]   eGalax, eTurboTouch CT-410/510/700 device support (TOUCHSCREEN_USB_EGALAX)

if you could include this also I can test immedaitely. :-))

Thanks for your work!

**Comment by AloisKlingler** [comment]
@popcornmix 
I just recompiled current (or yesterday's current) 3.18.7-v7 with this diff in .config:

```
diff .config.old .config
1829c1829,1847
< # CONFIG_TOUCHSCREEN_USB_COMPOSITE is not set
---
> CONFIG_TOUCHSCREEN_USB_COMPOSITE=m
> CONFIG_TOUCHSCREEN_USB_EGALAX=y
> # CONFIG_TOUCHSCREEN_USB_PANJIT is not set
> # CONFIG_TOUCHSCREEN_USB_3M is not set
> # CONFIG_TOUCHSCREEN_USB_ITM is not set
> # CONFIG_TOUCHSCREEN_USB_ETURBO is not set
> # CONFIG_TOUCHSCREEN_USB_GUNZE is not set
> # CONFIG_TOUCHSCREEN_USB_DMC_TSC10 is not set
> # CONFIG_TOUCHSCREEN_USB_IRTOUCH is not set
> # CONFIG_TOUCHSCREEN_USB_IDEALTEK is not set
> # CONFIG_TOUCHSCREEN_USB_GENERAL_TOUCH is not set
> # CONFIG_TOUCHSCREEN_USB_GOTOP is not set
> # CONFIG_TOUCHSCREEN_USB_JASTEC is not set
> # CONFIG_TOUCHSCREEN_USB_ELO is not set
> # CONFIG_TOUCHSCREEN_USB_E2I is not set
> # CONFIG_TOUCHSCREEN_USB_ZYTRONIC is not set
> # CONFIG_TOUCHSCREEN_USB_ETT_TC45USB is not set
> # CONFIG_TOUCHSCREEN_USB_NEXIO is not set
> # CONFIG_TOUCHSCREEN_USB_EASYTOUCH is not set
```

and now the eGalax touchpanel works flawless:

[    3.542048] input: eGalax Inc. USB TouchController as /devices/platform/bcm2708_usb/usb1/1-1/1-1.3/1-1.3:1.0/input/input0

maybe you can also set the other USB touch panels to y as I think USB-touchpanels are the most used on rpi. :-)
would be great if you can add this to the current config.

thanks!

**Comment by popcornmix** [comment]
Will add in next update.

**Comment by popcornmix** [comment]
Please run rpi-update and test.

**Comment by ChrisHughes** [comment]
@popcornmix It is working now. Thank you very much!

It still does need some config to work with X right out of the box, but at the kernel level it is detecting and registering it as an input device which all works great.

**Comment by mathewpeterson** [comment]
This saves me a TON of time and effort, thank you!

**Comment by hrshadhin** [comment]
In my case everything ok. But its not give proper touch point. If i touch right side of screen the mouse pointer is shows on left side of screen. Where is the problem?

**Comment by mathewpeterson** [comment]
It looks like you need to calibrate it: https://github.com/tias/xinput_calibrator

Specifically, you need to invert your Y axis: http://engineering-diy.blogspot.com/2013/01/adding-7inch-display-with-touchscreen.html?showComment=1394143831422#c2829908384589218823

**Comment by hrshadhin** [comment]
Thanks a lot. Its working great.

**Comment by epikao** [comment]
Hello,  
with teensy 3.2 we can simulate a USB touchscreen, with
TouchscreenUSB.press(finger, x, y);
TouchscreenUSB.release(finger); 

see also:
https://forum.pjrc.com/threads/32331-USB-HID-Touchscreen-support-needed

Unfortunately raspian can only shows a touch if press touch but as soon as a release the touch freezes...
On Windows or Mac it works fine but not with Raspbian, can you add support?
