### ISSUE TITLE
rp_proto/wm8731 switches channels automatically on high load

### ISSUE THREAD

**Issue by wbx-github** [raspberrypi/linux#719]
Hi,

We are trying to use a stereo output with two different mono signals via
interleave.
We are using a custom embedded board with Linux 3.10.x¹.
See following issue for some details:
https://github.com/koalo/linux/issues/33

Broadcom states following in their documentation²:
"If a FIFO error occurs in a two channel frame, then channel synchronisation may be lost
which may result in a left right audio channel swap. RXSYNC and TXSYNC status bits are
provided to help determine if channel slip has occurred."

They suggest on page 123:
"If a FIFO error occurs during operation in which 2 data channels are being used then the
synchronisation of the data may be lost. This can be recovered by either of these two methods:

a) Disable transmit and receive (TXON and RXON =0). Clear the FIFO’s (RXCLR and
TXCLR =1). Note that it may take up to 2 PCM clocks for the FIFOs to be physically
cleared after initiating a clear. Then preload the transmit FIFO and restart
transmission. This of course loses the data in the FIFO and further interrupts the data
flow to the external device.

b) Examine the TXSYNC and RXSYNC flags. These flags indicate if the amount of data in the FIFO
is a whole number of frames, automatically taking into account where we are in the current
frame being transmitted or received. Thus, providing an even number of samples was read
or written to the FIFOs, then if the flags are set then this indicates that a single word needs
to be written or read to adjust the data. Normal exchange of data can then proceed (where
the first word in a data pair is for channel 1). This method should cause less disruption to the
data stream."

On high load while playing a stereo wav file with only a sinus signal on the right channel:
# mplayer -loop 0 -ao alsa:device=hw=1,0 left.wav

the channels are switching after 2-3 minutes while extracting a big tar
archive in the background and calculating, f.e.
# tar xvf linux-3.17.tar.xz
# echo '1585876549522654^56546' |bc.

Sometimes the switching only happens for 4-5 seconds and then directly switch back.
I added following patch:

@@ -615,6 +628,18 @@ static int bcm2708_i2s_trigger(struct snd_pcm_substream *substream, int cmd,
 {
        struct bcm2708_i2s_dev *dev = snd_soc_dai_get_drvdata(dai);
        uint32_t mask;
-       uint32_t csreg;
  +
-       /*
-        \* Check TXSYNC and RXSYNC register, regarding FIFO overflow/underrun
-        */
-       regmap_read(dev->i2s_regmap, BCM2708_I2S_CS_A_REG, &csreg);
  +
-       if (csreg & (BCM2708_I2S_TXSYNC | BCM2708_I2S_RXSYNC))
-               printk("FIFO overflow/underrun detected!\n");
  +

After the channel switch I stopped mplayer and the message then appears in the kernel
log. So we are facing a FIFO overflow or underrun.

Could this be fixed by using DMA residue feature, like implemented by Russell King for
imx-sdma³? Or do we need to implement the suggested way by Broadcom?

Now with an upgrade to 3.12.31+ the problem disappeared. 
Is it just harder to triggger or might it be fixed in some DMA core code?
Does anyone have an opinion about that?

I added this issue as reference, if other developers get the same issue,
because it could be the case for any DAC on RPI system.

best regards
 Waldemar

¹ https://github.com/koalo/linux
² http://www.raspberrypi.org/wp-content/uploads/2012/02/BCM2835-ARM-Peripherals.pdf
³ https://github.com/linux4kix/linux-linaro-stable-mx6/commit/5906f24552cefaaa11e39c23225c660adcf2df08

**Comment by popcornmix** [comment]
Are you about which firmware update fixed it?

The one before 3.12.31 is more likely to have affected DMA behaviour:
https://github.com/raspberrypi/firmware/commit/c23c0022740bb4531e841bd1321d2a652c8b3b0d

```
kernel: bcm2708-dmaengine: nobble peak throughput to prevend SD host lockups
Artificially throttling DMA throughput to/from the SD host prevents errors
seen on very high-spec UHS-1 cards.See: http://www.raspberrypi.org/forums/viewtopic.php?f=63&t=5057&start=275#p626694
```

Throttling DMA used by sdcard may have improved the DMA bandwidth other devices get.

**Comment by wbx-github** [comment]
Hi,
I tried 3.12.29+ before the DMA patch got included. But I can not reproduce the problem here.
So it might be some other DMA related change in 3.12.
But at least we do not have the problem at the moment.

**Comment by popcornmix** [comment]
Okay to close if the issue is not affecting current kernel?

**Comment by wbx-github** [comment]
Hi,
sure. I added the issue just for reference, so that if anyone have this problem get a starting point.

**Comment by popcornmix** [comment]
Well the issue is still here for people searching and can be reopened if it reoccurs.
