### ISSUE TITLE
pcm512x fails to load under 3.17

### ISSUE THREAD

**Issue by hifiberry** [raspberrypi/linux#723]
The pcm512x driver fails to load under Linux 3.17. This is caused by the power regulation code:

[   11.595100] pcm512x 1-004d: Failed to get supply 'AVDD': -517
[   11.614262] pcm512x 1-004d: Failed to get supplies: -517
[   11.626529] i2c 1-004d: Driver pcm512x requests probe deferral

A short fix was removing the complete regulator code. After this, the driver loads. 

As this regulator code is not used anywhere on the Raspberry Pi, removing this in this GIT tree would be a possible solution until this is fixed. I can provide a driver without this code if needed.

**Comment by popcornmix** [comment]
I've removed CONFIG_REGULATOR from default config on 3.17.
Reports are that this fixes hifiberry DAC+ with OpenELEC. See:
http://forum.kodi.tv/showthread.php?tid=192380&pid=1836596#pid1836596

It's also been removed from OpenELEC master config.

**Comment by pelwell** [comment]
Can we close this now?
