### ISSUE TITLE
bcm2835_audio_set_ctls:558  Controls set for stream 0

### ISSUE THREAD

**Issue by beta-tester** [raspberrypi/linux#724]
hello, i am using RPi with newest Raspbian and newest firmware
`Linux ... 3.12.32+ #721 PREEMPT Fri Nov 7 16:50:31`
i have additional installed **sox** and compiled **rtl_sdr**.

when i now let rtl_fm run in background
`sudo rtl_fm -f ... -f ... -M fm -s 8k ... | play -r 8k -t raw -e s -b 16 -c 1 -V1 -v 2.0 - &`
to observe different non-continuous radio transmissions, i get many of these messages left in the dmesg log

```
...
[320125.483334] bcm2835_audio_set_ctls:558  Controls set for stream 0
[320126.523578] bcm2835_audio_set_ctls:558  Controls set for stream 0
[343608.279263] bcm2835_audio_set_ctls:558  Controls set for stream 0
[343609.319881] bcm2835_audio_set_ctls:558  Controls set for stream 0
[343610.360023] bcm2835_audio_set_ctls:558  Controls set for stream 0
...
```

i guess it is from **play**, every time a new transmission is received - some transmissions are very short, when only a status is received similat to
http://upload.wikimedia.org/wikipedia/commons/9/9a/5-Ton-Folge-88022.ogg.

is it a normal behaviour?

**Comment by popcornmix** [comment]
It's normal behaviour. That should be a debug level message rather than error.
Fix here: https://github.com/raspberrypi/linux/commit/8e36324907389c315f7d72bd6a456c984ce8e4cd

and will be in next firmware update.

**Comment by beta-tester** [comment]
thank you...

**Comment by beta-tester** [comment]
hmm, strange.
yesterday, i updated the firmware to
`3.12.32+ #721 PREEMPT Fri Nov 7 16:50:31 GMT 2014 armv6l`
but still i get these messages over and over in **dmesg**
and it looks my firmware were not updated?!
/boot/.firmware_revision sais `2b758e67fcb7c46fe1f770e015f19fb8562aea94`

**Comment by beta-tester** [comment]
ah, ok...
i didn't realize that updating the firmware by using **rpi-update** does not always mean that there is an updated kernel included - only after kernel dumps the kernel is updated as well.
