### ISSUE TITLE
mpd illegal instruction (0.19.1-1 on testing)

### ISSUE THREAD

**Issue by mhinsch** [raspberrypi/linux#726]
A fresh install of mpd fails to start.

> sudo service mpd start

does not give an error message but mpd does not run afterwards.

Attempting to run it manually gives an "Illegal instruction" error.

gdb produces the following output:

> Starting program: /usr/bin/mpd 
> [Thread debugging using libthread_db enabled]
> Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
> 
> Program received signal SIGILL, Illegal instruction.
> 0xb575d4c8 in ?? () from /usr/lib/libmodplug.so.1

I am now in the process of installing from source, I will update this issue accordingly.

**Comment by popcornmix** [comment]
Doesn't sound like a linux (kernel) issue, but perhaps mdp was built with the wrong compiler flags (e.g. for an armv7).
What's the minimum steps to reproduce?
Does installing a clean latest raspbian image, then apt-get installing mpd and running it show the issue?

**Comment by mhinsch** [comment]
Sorry, it turns out this was due to a (very stupid) mistake on my part. I accidentally let a debian line slip into my sources.list. A clean reinstall works fine.
