### ISSUE TITLE
raspberry pi kernel lacks nfs-kernel-server support

### ISSUE THREAD

**Issue by ghost** [raspberrypi/linux#727]
all commands run as root:
`$ service nfs-kernel-server start`
`[warn] Not starting NFS kernel daemon: no support in current kernel. ... (warning).`

`$ uname -a`
`Linux foo0 3.12.26+ #707 PREEMPT Sat Aug 30 17:39:19 BST 2014 armv6l GNU/Linux`

Googling the issue I saw lots of other people have had this problem and it seems the kernel has been compiled lacking NFSD support, and the solution is to recompile the kernel?

**Comment by popcornmix** [comment]
```
$ zcat /proc/config.gz |grep NFSD
CONFIG_NFSD=m
CONFIG_NFSD_V2_ACL=y
CONFIG_NFSD_V3=y
CONFIG_NFSD_V3_ACL=y
CONFIG_NFSD_V4=y
# CONFIG_NFSD_FAULT_INJECTION is not set
```

Do you know what kernel are required? Have you tried:

```
sudo modprobe nfsd
```

**Comment by ghost** [comment]
hi popcornmix, thanks. No I don't know what kernel is required. I have tried that. See below

`$ service rpcbind restart`
`[ ok ] Stopping rpcbind daemon....`
`[ ok ] Starting rpcbind daemon....`
`$ modprobe nfs`
`libkmod: ERROR ../libkmod/libkmod.c:554 kmod_search_moddep: could not open moddep file '/lib/modules/3.12.26+/modules.dep.bin'`
`$ modprobe nfsd`
`libkmod: ERROR ../libkmod/libkmod.c:554 kmod_search_moddep: could not open moddep file '/lib/modules/3.12.26+/modules.dep.bin'`
`$ modprobe lockd`
`libkmod: ERROR ../libkmod/libkmod.c:554 kmod_search_moddep: could not open moddep file '/lib/modules/3.12.26+/modules.dep.bin'`

`$ zcat /proc/config.gz | grep NFSD`
`CONFIG_NFSD=m`
`CONFIG_NFSD_V2_ACL=y`
`CONFIG_NFSD_V3=y`
`CONFIG_NFSD_V3_ACL=y`
`CONFIG_NFSD_V4=y``
`# CONFIG_NFSD_FAULT_INJECTION is not set`

Other people having this issue:
http://www.raspberrypi.org/forums/viewtopic.php?f=5&t=5636
(german) http://raspberrycenter.de/forum/nfs-kernel-server-hilfe-konfiguration
http://forum.osmc.tv/showthread.php?tid=1524
a thread on recompiling the kernel to enable NFS support:
http://www.raspberrypi.org/forums/viewtopic.php?t=13128&p=138512

A more relevant old thread, that didn't help either: http://www.raspberrypi.org/forums/viewtopic.php?f=26&t=15760
`$ rpcinfo -p`
   `program vers proto   port  service`
    `100000    4   tcp    111  portmapper`
    `100000    3   tcp    111  portmapper`
  `100000    2   tcp    111  portmapper`
   `100000    4   udp    111  portmapper`
    `100000    3   udp    111  portmapper`
   `100000    2   udp    111  portmapper`

i tried setting `NEED_IDMAPD=yes` and `NEED_GSSD=yes` in `/etc/default/nfs-common` then restarting `rpcbind` and then `nfsd`, but got the same original error.

**Comment by popcornmix** [comment]
I get no error from

```
sudo modprobe nfsd
```

so I think there's something broken in your installation.
Have you been updating the kernel without updating the associated modules?
Can you do a clean install of raspbian, and test if it works for you?

**Comment by P33M** [comment]
NFS is enabled by default and NFS root partitions are supported. NFSD and associated options are also enabled. Ensure that you're running with a clean set of modules/firmware.
