### ISSUE TITLE
libpam-otpw | undefined symbol: __aeabi_uidivmod

### ISSUE THREAD

**Issue by qswks** [raspberrypi/linux#729]
When trying to authenticate using otpw, the following error shows up in `/var/log/auth.log`

`PAM unable to dlopen(pam_otpw.so): /lib/security/pam_otpw.so: undefined symbol: __aeabi_uidivmod`

Same installation procedure in regular Debian (x86_64) works prefectly.
##### How to reproduce
- `apt-get install libpam-otpw` (1.3-2 in my case)
- Add a new file `/etc/pam.d/otpw-auth` with the following contents
  `auth sufficient pam_otpw.so debug`
  `session optional pam_otpw.so`
- Modify `/etc/pam.d/sshd`, add a new entry `@include otpw-auth` just above `@include common-auth`.
- Enable `ChallengeResponseAuthentication yes` in `/etc/ssh/sshd_config`.
- Add `AuthenticationMethods keyboard-interactive` to `etc/ssh/sshd_config` (OpenSSH 6.2 or above required)
##### uname -a

Linux raspberrypi 3.12.28+ #709 PREEMPT Mon Sep 8 15:28:00 BST 2014 armv6l GNU/Linux
##### syslog entry

PAM unable to dlopen(pam_otpw.so): /lib/security/pam_otpw.so: undefined symbol: __aeabi_uidivmod

Thanks!

**Comment by popcornmix** [comment]
This isn't a linux (kernel) issue but a raspbian distribution issue.
Probably best to ask here: http://www.raspberrypi.org/forums/viewforum.php?f=66
