### ISSUE TITLE
GPIO Interrupt Support

### ISSUE THREAD

**Issue by WetDogNose** [raspberrypi/linux#73]
Is there any planned date to add GPIO interrupt support in to the kernel?  Need varying high/low/rise/fall/change interrupt support and because I am not a Linux person cannot seem to get the various solutions out there working.  Hence, it would really help novice users like me to get on with RPi if it was baked into the official images.

**Comment by popcornmix** [comment]
I believe the GPIO driver supports interrupts:
https://github.com/raspberrypi/linux/blob/rpi-patches/arch/arm/mach-bcm2708/bcm2708_gpio.c

**Comment by WetDogNose** [comment]
Hi popcornmix, apologies for the delay in replying and thanks for taking the time to confirm this.  I will have a go at getting this going but will close this for now and re-raise if problems arise.

Rgrds WetDogNose
