### ISSUE TITLE
MT7610U USB Dongle Kernel Module has to be recompiled every time there is a firmware update.

### ISSUE THREAD

**Issue by Boggartfly** [raspberrypi/linux#730]
It's really difficult to get my system online after a system update because it breaks my wifi. To fix this I have to recompile the kernel module. The source is GNU GPL V2 or later compatible and is free to use and distribute. To fix this I would recommend
1. Add the source to the Raspberry Pi firmware repository.
2. Compile the kernel module every time there's a release. [the maintainers of course]
3. Ship it via the update.

You can find the source at http://www.mediatek.com/en/downloads/mt7610u-usb/

**Comment by Boggartfly** [comment]
Also compilation instructions can be found [here](http://groenholdt.net/Computers/RaspberryPi/MediaTek-MT7601-USB-WIFI-on-the-Raspberry-Pi/MediaTek-MT7601-USB-WIFI-on-the-Raspberry-Pi.html).

**Comment by popcornmix** [comment]
Sorry, out-of-tree kernel modules are a big maintenance headache and adds code that hasn't been reviewed by the kernel maintainers, which could introduce stability issues.

We'll only include this module is it is accepted upstream, so you should request the addition of this module to the upstream kernel, or request that Mediatek submit their module upstream.

**Comment by popcornmix** [comment]
Reopen if this module is accepted upstream, and I'll include it.

**Comment by dummys** [comment]
@popcornmix it seems it's mainlined now :D 

> From 4.2	Included in kernel as mt7601u

**Comment by Boggartfly** [comment]
Awesome!

**Comment by pelwell** [comment]
Are you sure that the MT7601u driver works with the MT7610u? The kernel Kconfig file doesn't mention it.

**Comment by Boggartfly** [comment]
@pelwell I haven't tried using the dongle yet. But I've heard that the driver was accepted upstream.

**Comment by dummys** [comment]
@pelwell @Boggartfly Can't make it work... And Yes you are right, I think it's not the M/7610 but MT7601:( so sad, will have to do my own build then...

**Comment by Boggartfly** [comment]
The accepted driver is for the mt7601. I have that dongle with me. I haven't just tested it yet.

**Comment by Boggartfly** [comment]
@dummys Take initiative to submit patches upstream however insignificant. I did it and my driver was soon accepted with the help of some very knowledgeable people who deserve almost all the credit.

**Comment by dummys** [comment]
Yes but I can't do patch like this, need to learn first.
Btw now I make it works on raspbian, now I need to make it works on RasPlex...
