### ISSUE TITLE
minecraft-pi is not needed in the default setup...

### ISSUE THREAD

**Issue by jarnix** [raspberrypi/linux#733]
I got the image from the torrent linked on the raspbian site, I have minecraft-pi, obviously it's useless to the common user.

The folder is in :
/opt/minecraft-pi

**Comment by asb** [comment]
If you don't want it, `sudo apt-get remove minecraft-pi`. It's included on the Foundation Raspbian image for convenience for the core target demographic of Raspberry Pi - people wanting to learn computer science.
