### ISSUE TITLE
binutils 2.22-8 -> 2.24.51.20140425-1~rpi1rpi2 linking issue

### ISSUE THREAD

**Issue by joolswills** [raspberrypi/linux#735]
We have some packages we build for the retropie-setup project (https://github.com/petrockblog/RetroPie-Setup) that have needed changing since the update of binutils, and I was after clarification or details as to what may have changed to cause this.

an example is https://code.google.com/p/mame4all-pi/

with binutils 2.22-8 it built out of the box. After upgrading to 2.24.51.20140425-1~rpi1rpi2  it requires that "-lrt -lasound" added to link. whereas before it worked with just

-lm -lpthread -lSDL -L$(SDKSTAGE)/opt/vc/lib -lbcm_host -lGLESv2 -lEGL -lglib-2.0

We have other packages that have needed additional link libraries added now also. Is this a bug or an intentional change in the way the linker works ? Apologies if this is not the best place for the report.

**Comment by popcornmix** [comment]
Not the right place (this is for the linux kernel). The tools repo would be better if you are cross compiling, or the raspbian forum if installed locally from apt-get.
What symbols are missing when you don't include -lrt and -lasound?

Pretty sure you are using functions from those libraries and so should be including them.
It's possible that different versions of the tools either include libraries by default or other dependencies in the system mean you get the libraries by chance.

The correct solution is to link with every library that you require symbols from (even if it appears to work without them).

**Comment by joolswills** [comment]
Looking at the package I think the gold linker is now used by default and it is this issue - https://sourceware.org/bugzilla/show_bug.cgi?id=10238 - so it is a behaviour change.

you are right regarding the libraries and functions, but it seems the older linker managed. It just happens to break a lot of stuff out there - I'll feed the changes upstream to the various programs that have broken.

**Comment by joolswills** [comment]
Apologies for reporting this in the wrong place - might be useful though for anyone else wondering what has changed.

**Comment by joolswills** [comment]
(Sorry it's not that the linker has changed to use gold. but I guess the behaviour in the newer binutils has however). Anyway, the solution is still the same - to include all libraries used as is logical - thanks again for the advice.

**Comment by Ruffio** [comment]
@joolswills has this issue been resolved? If yes, please close this issue. Thanks.

**Comment by popcornmix** [comment]
Not the right place for this anyway so closing.

**Comment by joolswills** [comment]
Apologies - yes it should have been closed. sorry.
