### ISSUE TITLE
Unable to play high definition audio using B+ and a I2S DAC like HiFiberry DAC+

### ISSUE THREAD

**Issue by Neo2003** [raspberrypi/linux#737]
Hello

Issue reported here: http://www.raspberrypi.org/forums/viewtopic.php?p=653655
jamesh asked me to report here too.

With any kernel > 3.12.26+, audio files with high bitrate are playing too fast and clipping with MPD. Very high def file like FLAC 24bits/176KHz even hang the pi 100% CPU. With kernel 3.12.26+ the same file play well and use barely 15% CPU.

Configuration I use and tests I made available here: http://www.hifiberry.com/forums/topic/no-sound-with-flac-24bits176khz/

Side note: even if kernel 3.12.26+ play them well, they are all passed to the DAC using 32BIT:
cat /proc/asound/card0/pcm0p/sub0/hw_params
access: RW_INTERLEAVED
format: S32_LE
subformat: STD
channels: 2
rate: 48000 (48000/1)
period_size: 6000
buffer_size: 24000

It's a mp3 radio station sending 16bits/48Khz/320kbps, reported as S16 in kernel 3.12.34+.

FLAC 24bits/176KHz on kernel 3.12.26+
cat /proc/asound/card0/pcm0p/sub0/hw_params
access: RW_INTERLEAVED
format: S32_LE
subformat: STD
channels: 2
rate: 176400 (176400/1)
period_size: 16384
buffer_size: 65536

reported S24 if I remember well on kernel 3.12.34+ just before the pi hang.

Note 2: I am using MPD 0.19.5.

**Comment by popcornmix** [comment]
First identify the exact firmware that changed the behaviour. i.e. is:

```
https://github.com/Hexxeh/rpi-firmware/commit/e38850519c56b835dbd1c81e04d9307e154c36ed
```

the first firmware/kernel with the problem? You can downgrade to a specific version with, e.g.

```
sudo rpi-update e38850519c56b835dbd1c81e04d9307e154c36ed
```

**Comment by Neo2003** [comment]
I found the solution on Volumio forum
The latest working firmware is said to be this, it's the one I pulled.
sudo rpi-update e38850519c56b835dbd1c81e04d9307e154c36ed
So exactly the one you linked.

I did not try many others, only 3.12.34+ pulled by just a sudo rpi-update and the one I had before (3.12.33)

I will try to isolate the commit but expect a bit delay.

**Comment by Neo2003** [comment]
In fact it was fast lol.
The first non working kernel is
https://github.com/Hexxeh/rpi-firmware/commit/995a4c011dd57031bb9290a40286439c9a05c2ed
so the last working is 
https://github.com/Hexxeh/rpi-firmware/commit/3d99bfb69460105c91e688a6031971e641bff354

**Comment by popcornmix** [comment]
Nothing obvious in that firmware update.
Can you take gpu firmware (start.elf and fixup.dat) from 3d99bfb and the rest from 995a4c0 and confirm if that's good or bad.
I imagine it's a kernel change that is relevant, rather than a gpu firmware one, but we need to prove that.

**Comment by Neo2003** [comment]
I did install 995a4c0 and overwritten start.elf and fixup.dat using 3d99bfb ones and as you expected it's not working.
This also cause bcm2708_dmaengine to not load due to mismatch, but does not prevent the audio from working with low bitrate titles.

**Comment by popcornmix** [comment]
With latest (or other non-working firmware) can you try adding:
dma.dmachans=0x0035
to /boot/cmdline.txt and report back.

**Comment by Neo2003** [comment]
I did pull latest with "sudo rpi-update" and added this option on /boot/cmdline.txt and...
... it's working! 

during a FLAC 24bits/176KHz
cat /proc/asound/card0/pcm0p/sub0/hw_params
access: RW_INTERLEAVED
format: S24_LE
subformat: STD
channels: 2
rate: 176400 (176400/1)
period_size: 16384
buffer_size: 65536

And cpu is around 15%, fine.
Now how will you fix for everyone? add this option or change code? :p

**Comment by popcornmix** [comment]
Okay, this was just a guess, good to hear it was the right guess.
GPU supports normal and lite DMA channels. The lite channels can't do multi-word bursts for example.
The identified commit did fix a limitation where lite channels couldn't be allocated.
It looks like the I2S driver needs to request a non-lite channel.

So use the cmdline.txt fix for now, but there will be a firmware update that will fix it soon.

**Comment by Neo2003** [comment]
Many many thanks for your support popcornmix, very appreciated :dancer: 

Kind regards
Stéphane

**Comment by P33M** [comment]
It'd be interesting to know why a Lite channel can't be used. I2S isn't exactly a high-bandwidth output (176kHz/2ch/24bit = 8.4mbit/s) but it's possible that the SCBs grow to >64k in size with that sort of bandwidth...

**Comment by popcornmix** [comment]
Yes, Gellert agreed:

> - fixing cyclic transfers with LITE channels. I'm not convinced the problem actually happens because of the hardware limitations of a LITE channel (eg not being as fast, not being able to do 2D transfer or multi-word bursts). It could be simply because we overflow the registers. Transfers that are too long need to be split into multiple transfers.

He said he'd look into it.

**Comment by popcornmix** [comment]
@Neo2003 Can you start with latest firmware, remove dma.dmachans from cmdline.txt and update kernel.img with this one:
https://dl.dropboxusercontent.com/u/3669512/temp/kernel_i2s.img

(rename to kernel.img). Let us know if that works.

**Comment by Neo2003** [comment]
I did test your new kernel.
I did have latest kernel/firmware. I did a wget from the Pi, removed the dma.dmachans=0x0035 from cmdline.txt, saved my kernel.img and renamed your to kernel.img and rebooted.

I tested a FLAC 24bits/176KHz/~6400kbps and it worked :)
So the issue seams to by fixed with your kernel_i2s.img.

Thanks

**Comment by popcornmix** [comment]
Great. That fix should be in the firmware update.

**Comment by popcornmix** [comment]
Firmware is updated. Please run rpi-update and confirm the bug is fixed.

**Comment by popcornmix** [comment]
Should be fixed in recent firmware. Reopen if still a problem.

**Comment by Neo2003** [comment]
I was far away from PC/Raspberry for 3 weeks, sorry.
I can confirm that latest firmware is working perfect with all my 176khz flac files.
Many thanks again for your great support!!
