### ISSUE TITLE
bcm2708-i2s.c: Can we use an external master clock for PCM_MCLK? 

### ISSUE THREAD

**Issue by ce3a** [raspberrypi/linux#738]
Hello,

do you think it would be possible to use an **external** (fed via **GPIO**) clock for **PCM_MCLK** (I2S master clock)? Can't find anything about it in the "BCM2835 ARM Peripherals" datasheet.

Regards,
Sergej

**Comment by popcornmix** [comment]
@ghollingworth can we do this through dt-blob?

**Comment by ghollingworth** [comment]
I'm not sure what you mean here can we just confirm what you mean.

The MCLK is normally supplied externally from an oscillator and is sent to the DAC.  The DAC then _normally_ has a PLL inside it or a divider to create the SCLK which is the output to the BCM2835 I2S_CLK input.  This is then the bit clock for the I2S data.

Are you asking can we use a GPCLK0 or GPCLK1 output to provide the MCLK to the DAC?  If so then the answer is yes, you can do it using the dt-blob.bin but it's not easy so I'd need to give you the special magic!

Gordon

**Comment by ce3a** [comment]
@ghollingworth The following image shows what I mean:

![clocks](https://cloud.githubusercontent.com/assets/5941722/5425294/071f411e-8311-11e4-80c0-44b783371fdd.png)

The DAC is a bit clock slave. The master clock and the bit clock shall be _synchronized_. Hence, I would like the Pi to derive the bit clock (PCM_CLK) from my external oscillator and not the internal PLL.

**Comment by pelwell** [comment]
What makes you think that they must be synchronised? The master clock is not part of the I2S interface - it seems strange to have to send three clocks - especially one that is 16 times the data rate.

One end of the I2S connection must be the clock master, and the other end must be the slave. This master/slave relationship is separate from the transmitter/receiver relationship. In the case of a DAC you want the BCM2708 to be the tranmitter. For clock stability you probably want to use an external crystal driving the DAC - your MCLK - and to avoid any jitter or drift you want the DAC to be the BCLK master and BCM2708 to be the slave. This is possible. From memory you have to arrange that the BCM2708 I2S master clock is high enough, but I'm pretty sure it DOES NOT have to be synchronised - the interface is perfectly capable of exchanging data using just the four pins.

**Comment by pelwell** [comment]
From http://www.raspberrypi.org/wp-content/uploads/2012/02/BCM2835-ARM-Peripherals.pdf: (pages 119-120)

The front end of the PCM audio interface is run off the PCM_CLK and the PCM signals are
timed against this clock. 

In clock slave mode (CLKM=1), the PCM_CLK is an input, supplied by some external clock
source.

In frame sync slave mode (FSM=1), the PCM_FS is treated as a data input and is sampled on
the negative edge of PCM_CLK. The first clock of a frame is taken as the first clock period
where PCM_FS is sampled as a 1 following a period or periods where it was previously a 0.
The PCM audio interface locks onto the incoming frame sync and uses this to indicate where
the data channels are positioned. The precise timing at the start of frame is shown in Figure
8-3.
Note that in frame sync slave mode there are two synchronising methods. The legacy method
is used when the frame length = 0. In this case the internal frame logic has to detect the
incoming PCM_FS signal and reset the internal frame counter at the start of every frame.
The logic relies on the PCM_FS to indicate the length of the frame and so can cope with
adjacent frames of different lengths. However, this creates a short timing path that will
corrupt the PCM_DOUT for one specific frame/channel setting.
The preferred method is to set the frame length to the expected length. Here the incoming
PCM_FS is used to resynchronise the internal frame counter and this eliminates the short
timing path.

**Comment by pelwell** [comment]
The bcm2708-i2s driver honours the ALSA DAI hardware clock master settings:

```
/*
 * DAI hardware clock masters.
 *
 * This is wrt the codec, the inverse is true for the interface
 * i.e. if the codec is clk and FRM master then the interface is
 * clk and frame slave.
 */
#define SND_SOC_DAIFMT_CBM_CFM      (1 << 12) /* codec clk & FRM master */
#define SND_SOC_DAIFMT_CBS_CFM      (2 << 12) /* codec clk slave & FRM master */
#define SND_SOC_DAIFMT_CBM_CFS      (3 << 12) /* codec clk master & frame slave */
#define SND_SOC_DAIFMT_CBS_CFS      (4 << 12) /* codec clk & FRM slave *
```

**Comment by ce3a** [comment]
@pelwell The [DACs datasheet](http://www.wolfsonmicro.com/media/76428/WM8741.pdf) says on page 24: "_The master clock should be synchronised with LRCLK._" So it's the frame clock that should be synchronised with the master clock, not the bit clock as I said above. Sorry for the confusion.

The datasheet says _should_, not _must_. However, in a test setup where the master clock is generated by an external (low jitter) oscillator, while the frame and the bit clocks are generated by the BCM2708 (not synchronised!) the audio signal has periodical **glitches**, as shown in the following image.

![f0001tek](https://cloud.githubusercontent.com/assets/5941722/5425542/cfa4ed96-831b-11e4-8d9d-7419a2ee104e.png)

If I configure the BCM2708 as clock slave (CLKM=1) and use an external clock divider to derive the bit clock from my master clock, then the glitches are gone.

I see two option to solve this issue:
1. Configure the BCM2708 as clock slave (CLKM=1). Use an external clock divider to derive the bit clock from the external master clock and supply the bit clock to the BCM2708. 
   Drawback: To play files with different sampling rates (48, 96, 192 kHz), the divider value would need to be changed at runtime.
2. Configure the BCM2708 as clock master (CLKM=0). Supply the external master clock signal to the BCM2708 PCM_MCLK clock input. The BCM2708 could generate differen frame and bit clock frequencies which would be synchronised with the external master clock.

I prefer option 2, it would simplify the DAC board design.

**Comment by ce3a** [comment]
To make it more clearer, the [BCM2835-ARM-Peripherals datasheet](http://www.raspberrypi.org/wp-content/uploads/2012/02/BCM2835-ARM-Peripherals.pdf) says on page 119:
- In clock master mode (CLKM=0), the PCM_CLK is an output and is driven from the PCM_MCLK clock input.
- In clock slave mode (CLKM=1), the PCM_CLK is an input, supplied by some external clock source.

**Question:**
In clock master mode (CLKM=0), is it possible to supply the PCM_**M**CLK clock signal (not PCM_CLK) by an external clock source?

**Comment by pelwell** [comment]
**Answer:**
No.

**But,** going back to your two options, option 1) is less complicated than you think. Your design already includes a clock divider in the form of _the DAC_. When you configure the DAC to be the clock(s) master and the BCM2708 I2S as the clock(s) slave, you are reversing the direction of clock signals, i.e. GPIOs 18 and 19 become inputs not outputs. It is then the DACs responsibility to generate coherent clock signals, and for the data source to synchronise to them. This is an easier task for the source since it merely has to clock the bits out of some shift registers at bit clock rates, rather than the _n_ x oversampling the DAC is undoubtedly having to do.

**Comment by ce3a** [comment]
@pelwell Unfortunately, the DAC can not be configured as a clock(s) master, it is a pure slave. If the answer is no, I will have to use an external clock generator -- that complicates the design.

**Comment by pelwell** [comment]
That's a shame - other DACs are capable of being masters - but I wouldn't be surprised if there are potential EMC issues with sending a 10+MHz clock into an IDC header pin that would make an external clock divider a preferable solution (but I'm a computer programmer, not an electrical engineer).

Good luck.

**Comment by ce3a** [comment]
@pelwell You are right, thanks for your replies! Shall we close the issue?
