### ISSUE TITLE
Console Rotataion [fixed]

### ISSUE THREAD

**Issue by RaTTuS-BIG** [raspberrypi/linux#74]
the Kernel does not support 
fbcon=rotate:3
this is very useful for those of us using the RPI with rotated displays [console only]

2111c2111
## < # CONFIG_FRAMEBUFFER_CONSOLE_ROTATION is not set

> CONFIG_FRAMEBUFFER_CONSOLE_ROTATION=y
> fixes the issue with no other noticeable effects

**Comment by popcornmix** [comment]
Did you see my reply here:
http://www.raspberrypi.org/phpBB3/viewtopic.php?f=29&t=9450&p=132201
(that firmware is now on github/rpi-update)

**Comment by RaTTuS-BIG** [comment]
ooh - no I completely missed that, 
trying now
...
awesome working
