### ISSUE TITLE
Disable tickless wothout kernel rebuild?

### ISSUE THREAD

**Issue by gm8arv** [raspberrypi/linux#750]
I have recent upgraded a number of Raspberry Pi cards to the current distribution, and noted that the timekeeping performance for a stratum-1 server with PPS as reported by NTP offset is a factor of about two worse than with my previous kernel which was compiled without the "tickless" option. Current version: Linux raspi-6 3.12.35+ #730 PREEMPT Fri Dec 19 18:31:24 GMT 2014 armv6l GNU/Linux

Is there any way to select non-tickless operation at run time - such as a boot command-line option - so that the good timekeeping performance might be restored? I would very much prefer to use the stick kernel rather than recompiling - as the GPIO-PPS support is now built-in and very helpful thanks!

(It was suggested that I post this request here.)

Thanks,
David

**Comment by kukabu** [comment]
Try nohz=off in kernel cmdline.

**Comment by gm8arv** [comment]
Thanks, kukabu.  I tried that but it didn't make any difference.  I see now that someone reported similar results earlier.  Can you or anyone confirm that the stock Raspian supports nohz=off, and if not, could it be added, please?

**Comment by ghost** [comment]
I'd like to second this request. A functioning nohz=off would be a valuable addition for people running or trying to run a stratum 1 NTP server, especially in light of this recent NTP bug fix: http://bugs.ntp.org/show_bug.cgi?id=2314

tl:dr; Until recently on tickless kernels NTP would look as though it were using the kernel clock discipline when instructed to but was in fact silently ignoring it. NTP now correctly fails to use the kernel discipline on tickless kernels, and will only use it on kernels with tickless disabled. So, though we can now easily enable PPS in the Raspbian kernel (hooray), NTP will ignore (and always has ignored) it at the kernel level (not hooray).

**Comment by Ruffio** [comment]
@gm8arv has this issue been resolved? If yes, please close this issue. Thanks.

**Comment by gm8arv** [comment]
The comment referred to a rather old version of the OS.  Is there now a nohz=on option for the current Raspbian?

**Comment by P33M** [comment]
Adding `nohz=off` to /boot/cmdline.txt has the following effects:

Default:

```
pi@raspberrypi:~$ vmstat 2
procs -----------memory---------- ---swap-- -----io---- -system-- ------cpu-----
 r  b   swpd   free   buff  cache   si   so    bi    bo   in   cs us sy id wa st
 0  0      0 681776  13860 106112    0    0  1580    32  607  795 10 14 64 12  0
 0  0      0 681280  13860 106140    0    0     0     0  562  259  0  1 99  0  0
 0  0      0 681280  13860 106140    0    0     0     0  336   45  0  0 100  0  0
 0  0      0 681024  13868 106140    0    0     0     6  468  251  1  1 99  0  0
 0  0      0 680892  13868 106140    0    0     0     0  359   80  0  0 100  0  0
 0  0      0 681048  13868 106140    0    0     0     0  435  228  1  1 98  0  0
```

nohz=off:

```
pi@raspberrypi:~$ vmstat 2
procs -----------memory---------- ---swap-- -----io---- -system-- ------cpu-----
 r  b   swpd   free   buff  cache   si   so    bi    bo   in   cs us sy id wa st
 0  0      0 681696  13632 106104    0    0  1072    21  487  562  7 10 76  8  0
 0  0      0 681656  13632 106132    0    0     0     0  806  114  0  0 100  0  0
 0  0      0 681488  13632 106132    0    0     0     0  794  260  1  1 98  0  0
 0  0      0 681504  13632 106132    0    0     0     0  706   73  0  0 100  0  0
```

So it appears that scheduling interrupts occur far more often. We've also switched to voluntary preemption, which may have a beneficial effect for more precise timestamping.

**Comment by gm8arv** [comment]
Thanks for that, I will test it out here and see whether there really is any difference as far as NTP is concerend.

**Comment by gm8arv** [comment]
When "nohz=off" was added, on some systems there was no change, on others the NTP jitter was "halved" (approximately).  I ended up with:  ~ 4 µs jitter on RasPi B/B+,  2 µs on model 2 B, and 1 µs on model 3, when using PPS sources with well under 0.1 µs jitter.  Just as a rough guide.

http://www.satsignal.eu/ntp/Raspberry-Pi-NTP.html#nohz

Thanks again.
