### ISSUE TITLE
Please include bluetooth patch (bug 60901 from kernel.org)

### ISSUE THREAD

**Issue by mbinic** [raspberrypi/linux#752]
Can you please include the patch described here: https://bugzilla.kernel.org/show_bug.cgi?id=60901

I have a Raspberry Pi Model B and the Bluetooth dongle in question, and have recompiled with the patch and can confirm the device works with the proposed change.

**Comment by popcornmix** [comment]
In general I'm happy to pull in patches that have been accepted into upstream kernel.
This patch doesn't seem to be present (even in latest "linux-next" kernel) so I'm guessing it's not been okayed upstream:
https://git.kernel.org/cgit/linux/kernel/git/next/linux-next.git/tree/net/bluetooth/hci_core.c?id=refs/tags/next-20141231#n550
I'd suggest you try to get this patch submitted upstream:
https://www.kernel.org/doc/Documentation/SubmittingPatches
and if it's accepted, I'll pull it in here.

**Comment by Ruffio** [comment]
@mbinic has this issue been resolved? If yes, please close this issue. Thanks.

**Comment by mbinic** [comment]
For me, locally, this was resolved by the mentioned patch. From then on I haven't updated, so I'm not sure if the patch has been merged or not, or if the issue persists.

**Comment by popcornmix** [comment]
The linked bug report does suggest the issue was fixed in kernels >= 4.1.4.
We are now newer than that, so should be fixed.
