### ISSUE TITLE
help,  libEGL freeze with futex_ state.

### ISSUE THREAD

**Issue by aureliocurado** [raspberrypi/linux#754]
The program loop through several png/jpg files,
all them with 192x1080 to fill entire screen with wallpaper.
After reached the file "Music-equipment.jpg", the libEGL freezes
in futex_ state.
Is it a bug? Why only that image  freezes, others dozen don't ?
The files was converted with "convert":
/usr/bin/convert $1 -resize "1920x1080^" -gravity center -extent "1920x1080"  $2  2>/dev/null

---

void VJL_TextureLoadImage(VJL_Texture *t, char *filename)
{
    {
        GLuint texId;
        t->image_loaded = false;

```
    if (_load_texture(&t, filename) != 0)
        fprintf(stderr, "VJL_LoadTexture: load image error.\n");
    VJL_MakeCurrentContext(t->win, t->context);

    glGenTextures ( 1, &texId );
    glBindTexture ( GL_TEXTURE_2D, texId );

    glTexImage2D ( GL_TEXTURE_2D,       /*/target: Specifies the target texture of the active texture unit */
                   0,                   /*/level: Specifies the level-of-detail number. Level 0 is the base image level. Level n is the nth mipmap reduction image. */
                   t->internalformat,   /*/internalformat: Specifies the internal format of the texture. Must be one of the following symbolic constants: GL_ALPHA, GL_LUMINANCE, GL_LUMINANCE_ALPHA, GL_RGB, GL_RGBA. */
                   t->w, t->h,          /*/width height: Specifies the width of the texture image. All implementations support 2D texture images that are at least 64 texels wide and cube-mapped texture images that are at least 16 texels wide. */
                   0,                   /*/border: Specifies the width of the border. Must be 0. */
                   t->internalformat,   /*/format: Specifies the format of the texel data. Must match internalformat. The following symbolic values are accepted: GL_ALPHA, GL_RGB, GL_RGBA, GL_LUMINANCE, and GL_LUMINANCE_ALPHA. */
                   GL_UNSIGNED_BYTE,    /*/type: Specifies the data type of the texel data. The following symbolic values are accepted: GL_UNSIGNED_BYTE, GL_UNSIGNED_SHORT_5_6_5, GL_UNSIGNED_SHORT_4_4_4_4, and GL_UNSIGNED_SHORT_5_5_5_1. */
                   t->buffer            /*/data: Specifies a pointer to the image data in memory. */
                   );
    /* Enable blending, necessary for our alpha texture */
    glEnable(GL_BLEND);
    glBlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA);

    glTexParameteri ( GL_TEXTURE_2D, GL_TEXTURE_MIN_FILTER, GL_LINEAR );
    glTexParameteri ( GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_LINEAR );
    glTexParameteri ( GL_TEXTURE_2D, GL_TEXTURE_WRAP_S, GL_CLAMP_TO_EDGE );
    glTexParameteri ( GL_TEXTURE_2D, GL_TEXTURE_WRAP_T, GL_CLAMP_TO_EDGE );

    t->baseMapTexId = texId;
    t->image_loaded = true;
}
```

}

---

ps x -leH :
4 S     0  4340  4338 15  80   0 - 14977 futex_ pts/1      0:16  

Program received signal SIGINT, Interrupt.
0xb6fa9700 in sem_wait@@GLIBC_2.4 () from /lib/arm-linux-gnueabihf/libpthread.so.0
(gdb) bt
#0  0xb6fa9700 in sem_wait@@GLIBC_2.4 () from /lib/arm-linux-gnueabihf/libpthread.so.0
#1  0xb6f38a9c in rpc_send_bulk () from /opt/vc/lib/libEGL.so
#2  0x000fff00 in ?? ()
#3  0x000fff00 in ?? ()

Backtrace stopped: previous frame identical to this frame (corrupt stack?)

**Comment by popcornmix** [comment]
This won't be a kernel issue.
Is there is a bug it will be a firmware bug so should be reported here:
https://github.com/raspberrypi/firmware/issues

However I won't be able to offer any help without a complete (source and makefiles) example of a program that fails.
