### ISSUE TITLE
Please include DS2406 module

### ISSUE THREAD

**Issue by andrewerrington** [raspberrypi/linux#759]
For the bit-banged one-wire support there is a module for the DS2406 GPIO switch.  There should be a kernel option "CONFIG_W1_SLAVE_DS2406"- please turn this on to make the module available.

Source is here:
https://github.com/salfter/pifridge/blob/master/README.md

Thanks!

**Comment by popcornmix** [comment]
Sorry, we generally don't include out-of-tree drivers.
"Note that current releases of Linux don't include support for the DS2406"

You should request this driver gets included in the upstream kernel source, and we can then enable it.
Getting it merged upstream means it will be reviewed by people who understand the code.

See: http://kernelnewbies.org/UpstreamMerge

**Comment by andrewerrington** [comment]
This module was written 6 months ago.  Have you checked that it is not present in the current release?

**Comment by popcornmix** [comment]
Okay, it's not present in 3.12 tree.
It looks like it is present in 3.18 tree, which we'll be moving to soon (and is available for testing with sudo BRANCH=next rpi-update)

Added here: https://github.com/raspberrypi/linux/commit/411b3f01676fd949e40f5ede3ce242cacdd07d4e

I'll comment when the "next" kernel is updated and you'll be able to test.

**Comment by andrewerrington** [comment]
Thank you.

**Comment by lurch** [comment]
`CONFIG_W1_SLAVE_DS2406=m` is now set in both the Pi1 and Pi2 kernel configs, so after a `sudo apt-get update && sudo apt-get upgrade` you should find this module present?

**Comment by Ruffio** [comment]
@andrewerrington has this issue been resolved? If yes, please close this issue. Thanks.

**Comment by popcornmix** [comment]
It is present in current kernel.
