### ISSUE TITLE
Spinlock recursion in sdhci-bcm2708.c

### ISSUE THREAD

**Issue by ddv2005** [raspberrypi/linux#76]
Hi,

sdhci-bcm2708.c has spinlock recursion in sdhci_bcm2708_dma_complete_irq and sdhci_bcm2708_platdma_reset.  Both functions does not need spin_lock_irqsave/spin_unlock_irqrestore because spinlock already locked by main irq handler.

**Comment by popcornmix** [comment]
Do you have a suggested patch/pull request?

**Comment by ddv2005** [comment]
https://github.com/ddv2005/linux/commit/a2b337de4ccdde262e9b4629718d20b28cbd3c4d.patch

**Comment by alphaonex86** [comment]
Can be linked with my issue:
https://github.com/raspberrypi/linux/issues/52

**Comment by popcornmix** [comment]
Patch has been applied.
