### ISSUE TITLE
make oldconfig 3.12->3.18, no default value for PHYS_OFFSET?

### ISSUE THREAD

**Issue by gorskima** [raspberrypi/linux#768]
I'm trying to update my 3.12 config to the 3.18 version using the 'make oldconfig' command. I am then prompted to type in value for the config param PHYS_OFFSET. No default value is suggested. Any hints what a RPi needs here?

**Comment by popcornmix** [comment]
I'd recommand you run:

```
ARCH=arm make bcmrpi_defconfig
```

which will use the official settings (https://github.com/raspberrypi/linux/blob/rpi-3.18.y/arch/arm/configs/bcmrpi_defconfig). Then apply your changes.

But, as you see from bcmrpi_defconfig, PHYS_OFFSET should be 0.

**Comment by gorskima** [comment]
Thanks, worked :)
