### ISSUE TITLE
usb 1-1.2: input irq status -115 received

### ISSUE THREAD

**Issue by hex445** [raspberrypi/linux#77]
uname -a
Linux raspberrypi 3.1.9+ #168 PREEMPT Sat Jul 14 18:56:31 BST 2012 armv6l GNU/Linux

lsusb
Bus 001 Device 004: ID 0471:206c Philips (or NXP) MCE IR Receiver - Spinel plusf0r ASUS

This is remote controller supplied with Asus AT3IonT-I Deluxe

Most of keys does not work and generates these messages:

Aug  7 22:57:56 raspberrypi kernel: [ 3780.184951] usb 1-1.2: input irq status -115 received
Aug  7 22:57:56 raspberrypi kernel: [ 3780.416909] usb 1-1.2: input irq status -115 received
Aug  7 22:57:56 raspberrypi kernel: [ 3780.536908] usb 1-1.2: input irq status -115 received

**Comment by popcornmix** [comment]
Could you try again with latest kernel and with
dwc_otg.microframe_schedule=1
in cmdline.txt?

**Comment by hex445** [comment]
Kernel 3.2.27+
Yes the messages "input irq status -115 received" has gone. Arrows and "OK" button works in xbmc.
Button "back" does not work but generates "^@" code(maybe this is something with xbmc keymap, I'm not sure). Volume up does not generate any code but works in xbmc. Special buttons does not work.

dwc_otg.microframe_schedule=1 - this option has no influence. The above behaviour is the same with or without it.

**Comment by popcornmix** [comment]
Closing as the USB issue seems to be fixed. Please reopen if there is a problem.
