### ISSUE TITLE
how to sync an old fork

### ISSUE THREAD

**Issue by wbx-github** [raspberrypi/linux#774]
Hi,

I would like to create a new pull request for the rpi-proto driver.
What is the best way to sync my old fork (maybe with all branches) with
your repo? Is there a good howto about this? I have read a lot of stuff, but I don't get it
right.

best regards
 Waldemar

**Comment by popcornmix** [comment]
You fork this repo.
You checkout branch rpi-3.18.y of your forked repo.
You apply your commits.
You push.
You press the Pull request button.
