### ISSUE TITLE
Enable CONFIG_DVB_USB_DVBSKY in 3.18

### ISSUE THREAD

**Issue by daramori** [raspberrypi/linux#779]
The 3.18 kernel added support for DVB devices from DVBSky. The appropriate module isn't being built for the Raspberry Pi though. Can the following line be added to the Pi's build config to enable support?

```
CONFIG_DVB_USB_DVBSKY=m
```

**Comment by popcornmix** [comment]
Okay. Will be in next update.

**Comment by popcornmix** [comment]
Try rpi-update now - should be there.

**Comment by daramori** [comment]
Just ran rpi-update and my DVBSky device is working perfectly. Thanks!
