### ISSUE TITLE
which cross compiler can i use on raspberry pi 2?

### ISSUE THREAD

**Issue by zaazbb** [raspberrypi/linux#792]
on raspberry pi 1 B, 
I used gcc-4.7-linaro-rpi-gnueabihf.tbz as a cross compile for qt.
but on raspberry pi 2, which cross compiler can i use, gcc-4.7-linaro-rpi-gnueabihf.tbz was configed for arm11, it should not work for raspberry pi 2.

**Comment by popcornmix** [comment]
An arm11 target will work fine (and allows the library to be used on both Pi1 and Pi2 (like rest of raspbian).

If you to force a Pi2 only build then -mcpu=cortex-a7 is the right flag.
You may also want to play with -mfpu=neon-vfpv4

**Comment by zaazbb** [comment]
thanks
