### ISSUE TITLE
RPi. GPIO error on RPI 2 ?

### ISSUE THREAD

**Issue by MrChristo59** [raspberrypi/linux#794]
Hello (again),

Is their any way to make the GPIO python works for rpi 2 ? Maybe not yet.

"  import RPi.GPIO as GPIO
RuntimeError: This module can only be run on a Raspberry Pi!"

**Comment by P33M** [comment]
This is not a Linux kernel issue.

The author of RPi.GPIO is aware and is working on a fix.

**Comment by MrChristo59** [comment]
Oh ok, sorry about that.
