### ISSUE TITLE
No 1-wire Device found after latest raspbian update

### ISSUE THREAD

**Issue by StephanSchaa** [raspberrypi/linux#809]
Since my latest raspbian update (7.2.2015)  no devices are found anymore in /sys/bus/w1/devices.

Can anybody confirm this?

**Comment by pelwell** [comment]
Read /boot/overlays/README.

You will probably need to add:

```
dtoverlay=w1-gpio
```

to your config.txt, but you have to choose between that overlay and w1-gpio-pullup, and both have multiple parameters whose values will depend on your configuration.

**Comment by StephanSchaa** [comment]
Works perfect! Thank you very much!
Stephan
