### ISSUE TITLE
Please enable CONFIG_CRYPTO_XTS

### ISSUE THREAD

**Issue by Dmole** [raspberrypi/linux#81]
Please enable CONFIG_CRYPTO_XTS

zcat /proc/config.gz | grep CONFIG_CRYPTO_XTS

It is the only reason I need to keep build my own kernels for the raspberrypi.

**Comment by popcornmix** [comment]
Added. Can be got through rpi-update. Please test and close.

**Comment by Dmole** [comment]
Thanks that worked.

raspbian> uname -a
Linux raspbian 3.1.9+ #278 PREEMPT Wed Aug 15 20:59:07 BST 2012 armv6l GNU/Linux
