### ISSUE TITLE
commit c799e6e411 has odd kernel version number

### ISSUE THREAD

**Issue by MrEngman** [raspberrypi/linux#810]
after using rpi-update kernel version is #749 for Pi B 2 but #1 for Pi B plus.

`Linux Pi-B-2 3.18.6-v7+ #749 SMP PREEMPT Sat Feb 7 18:15:06 GMT 2015 armv7l`

`Linux Pi-B-Plus 3.18.6+ #1 PREEMPT Sat Feb 7 18:11:00 GMT 2015 armv6l GNU/Linux`

**Comment by popcornmix** [comment]
Yes, bug in my build script. Should be fixed now.
