### ISSUE TITLE
3.18.6 spi issue

### ISSUE THREAD

**Issue by ha5di** [raspberrypi/linux#814]
Hi,

using own 3.18.5 / 3.18.6 kernel on 'Model B' modprobe spi-bcm2708.ko.gz gives:

modprobe: can't load module spi-bcm2708.ko.gz (kernel/drivers/spi/spi-bcm2708.ko.gz): No such device

Module exists, modinfo displays module info as expected. 

Béla

**Comment by pelwell** [comment]
Add "dtparam=spi=on" to config.txt (and reboot). Then read /boot/overlays/README, and this Forum thread: http://www.raspberrypi.org/forums/viewtopic.php?f=44&t=98318

**Comment by pelwell** [comment]
And make sure your firmware is up-to-date.

**Comment by ha5di** [comment]
Phil,

thanks a lot, it works. Issue closed.

Regards... Bela
