### ISSUE TITLE
3.18.6 i2c issue

### ISSUE THREAD

**Issue by ha5di** [raspberrypi/linux#815]
Hi,

using own 3.18.5 / 3.18.6 kernel on 'Model B' I have i2c_dev and i2c_bcm2708 modules loaded but /dev entries are missing.

Béla

**Comment by pelwell** [comment]
Add "dtparam=i2c_arm=on" to config.txt (and reboot). Then read /boot/overlays/README, and this Forum thread: http://www.raspberrypi.org/forums/viewtopic.php?f=44&t=98318

**Comment by pelwell** [comment]
And make sure your firmware is up-to-date.

**Comment by ha5di** [comment]
Phil,

it works. Thanks for the fast response

Regards... Bela
