### ISSUE TITLE
ulogd broken: ipt_ULOG missing

### ISSUE THREAD

**Issue by lahcejopa** [raspberrypi/linux#816]
Hi,

with the recent version of kernel (3.18) ipt_ULOG is no longer available what breaks ulogd. Unfortunately ulogd2 (relying on xt_NFLOG) is not available in Raspbian Wheezy.

Regards,
Lahc

**Comment by popcornmix** [comment]
CONFIG_IP_NF_TARGET_ULOG is marked as obsolete in the kernel, so I don't think we'll be adding it.
I'd suggest requesting ulogd2 in the Raspbian Wheezy repository (http://www.raspberrypi.org/forums/viewforum.php?f=66), or seeing if you can install it from Raspbian Jessie repo.
