### ISSUE TITLE
IPv6 privacy extensions only seam to work at boot with a RTC

### ISSUE THREAD

**Issue by Asmod4n** [raspberrypi/linux#823]
When you get a IPv6 Address at boot and have ipv6 privacy extensions enabled like this

```
cat /etc/sysctl.d/40-ipv6.conf 
net.ipv6.conf.all.use_tempaddr = 2
net.ipv6.conf.default.use_tempaddr = 2
net.ipv6.conf.eth0.use_tempaddr = 2
```

the "private" addresses get removed when ntpd changes the time to the current time and /proc/sys/net/ipv6/conf/eth0/use_tempaddr gets set to -1 instead of 2.

Here is the dmesg output

```
[   10.085200] IPv6: ipv6_create_tempaddr: regeneration time exceeded - disabled temporary address support
```

**Comment by popcornmix** [comment]
Might be worth reporting this upstream - hard to imagine this is a Pi specific issue.
