### ISSUE TITLE
Please enable 6LoWPAN support

### ISSUE THREAD

**Issue by csett86** [raspberrypi/linux#825]
Please enable 6LoWPAN support

```
CONFIG_6LOWPAN=m
CONFIG_BT_6LOWPAN=m
```

This helps for IoT applications like 6LoWPAN over Bluetooth Low Energy  as in https://www.nordicsemi.com/eng/Products/Bluetooth-Smart-Bluetooth-low-energy/nRF51-IoT-SDK

The modification to the kernel linked above are only these two additional modules.

**Comment by csett86** [comment]
Is there anything I can help to get these two kernel modules into Raspbian? I can create a pull request for the two defconfigs, if that helps.

**Comment by PeterPablo** [comment]
They were just added (https://github.com/raspberrypi/linux/commit/690878e23a8b7a7625514da6d9b005b5c7d178b3) and thus should soon be available via `rpi-update`.

**Comment by popcornmix** [comment]
These modules are now added. Please run rpi-update and test.

**Comment by csett86** [comment]
Thanks a lot for the quick response, both modules work like expected.

**Comment by DerDipper** [comment]
why am i not able to write to the 6lowpan_psm file after the update, is this common or did i do wierd things?
