### ISSUE TITLE
bcmrpi_quick_defconfig is missing an option.

### ISSUE THREAD

**Issue by phire** [raspberrypi/linux#834]
Needs: 

```
CONFIG_PHYS_OFFSET=0
```

Otherwise oldconfig asks for an offset, which causes buildroot to get stuck in an infinite loop.

**Comment by popcornmix** [comment]
I've removed bcmrpi_quick_defconfig.
bcmrpi_defconfig and bcm2709_defconfig are the only ones we maintain, so it's best not to have unmaintained custom configs in our linux tree.

**Comment by phire** [comment]
Close enough.
