### ISSUE TITLE
DTS naming for RPI boards

### ISSUE THREAD

**Issue by agherzan** [raspberrypi/linux#851]
Hi guys,

It seems that the current dts tree is a little confusing. We have some files that are prefixed with the processor family code and some with the actual linux implementation processor code:
bcm2708_.dts
bcm2835_.dts

Are the bcm2835 ones obsolete? Should we remove them to avoid this confusion?

**Comment by pelwell** [comment]
No - bcm2835 is an independent, upstreamed implementation of a BCM2835 port using Device Tree best practices. Current RPi kernels are using some of the bcm2835 modules, and we would like to use more and perhaps even merge the two worlds, but for now they are intentionally separate.

**Comment by agherzan** [comment]
Thank you. That clarifies.
