### ISSUE TITLE
Missing IPSEC modules in raspbian kernel

### ISSUE THREAD

**Issue by ovacikar** [raspberrypi/linux#86]
I am unable to establish ipsec/psk session ,

fails with   ERROR: netlink response for Add SA xxxyyyzzz included errno 93: Protocol not supported 

Found another forum post stating it is missing a module but does not specify which one:

http://www.raspberrypi.org/phpBB3/viewtopic.php?f=36&t=12948

Please add all necessary modules for IPSEC to work

ipsec verify output : (I tried every possible sysctl command to fix the ICP forwarding , but they are still there

Checking for IPsec support in kernel                            [OK]
 SAref kernel support                                           [N/A]
 NETKEY:  Testing XFRM related proc values                      [FAILED]

  Please disable /proc/sys/net/ipv4/conf/*/send_redirects
  or NETKEY will cause the sending of bogus ICMP redirects!

```
[FAILED]
```

  Please disable /proc/sys/net/ipv4/conf/*/accept_redirects
  or NETKEY will accept bogus ICMP redirects!

```
[OK]
```

Checking that pluto is running                                  [OK]
 Pluto listening for IKE on udp 500                             [OK]
 Pluto listening for NAT-T on udp 4500                          [OK]
Two or more interfaces found, checking IP forwarding            [OK]
Checking NAT and MASQUERADEing                                  [OK]
Checking for 'ip' command                                       [OK]
Checking /bin/sh is not /bin/dash                               [WARNING]
Checking for 'iptables' command                                 [OK]
Opportunistic Encryption Support                                [DISABLED]

**Comment by popcornmix** [comment]
You'll need to find the config options required. Build a working kernel, and run
make ARCH=arm savedefconfig
and report the output of:
diff arch/arm/configs/bcmrpi_defconfig defconfig

**Comment by ovacikar** [comment]
The missing modules should be included by default. Can this get assigned to maintainer of kernel or openswan package ?
I do not have the resource to compile a kernel on rpi

**Comment by ovacikar** [comment]
the list of required modules are already listed here

http://wiki.strongswan.org/projects/strongswan/wiki/KernelModules

**Comment by popcornmix** [comment]
IPSEC modeules are added.

**Comment by popcornmix** [comment]
Closing as this option is added. Please reopen if there is a problem.

**Comment by emilhugo** [comment]
which public available kernel level includes the IPSEC modules for OpenSwan?
ipsec verify on kernel 3.2.27+ still print:
Linux Openswan U2.6.37/K(no kernel code presently loaded)
Checking for IPsec support in kernel                            [FAILED]
