### ISSUE TITLE
libtomcrypt package needs rebuild, unable to use libtommath

### ISSUE THREAD

**Issue by RizzoRat** [raspberrypi/linux#862]
Affected: package libtomcrypt-dev
Possibly also packlage libtomcrypt (not tested, but I think libtomcrypt-dev refers to libtomcrypt)

libtomcrypt-dev seem to install a libtomcrypt.a not containing important symbols to enable using libtommath.
nm reveals no symbol for any math lib, hence I presume libtomcrypt was not compiled with -DLTM_DESC -DUSE_LTM for the package.

Background info:
Most software uses libtommath with libtomcrypt, hence it should be enabled. 
By default, ltc should have the ltm_desc on linux (and tfm_desc on apple for example). 
The math library defines for libtomcrypt simply add support for the respective math library and all can be used in parallel, they do not harm except marginal library size. 
Hence, package libtomcrypt woulkd be functional even when libtommath is not present/installed.

Recommended solution: 
Compile library for package using -DLTM_DESC -DUSE_LTM  (default for linux) at least.

Intermediate solution for developers: Remove or Purge libtomcrypt-dev,  compile libtomcrypt from source yourself (which by default creates a static(!) libtomcrypt.a with ltm_desc). "make install" not recommended though, copy or softlink library (and headers) manually.

**Comment by popcornmix** [comment]
This github repo is for the linux kernel. I'm guessing your issue is related to the packages installed from the raspbian repo. Best to ask here:
http://www.raspberrypi.org/forums/viewforum.php?f=66
