### ISSUE TITLE
Need a place to document all the overlays

### ISSUE THREAD

**Issue by msperl** [raspberrypi/linux#869]
As the number of overlays is growing we need a location where we document each overlay.

**Comment by pelwell** [comment]
What's wrong with the existing location?

**Comment by pelwell** [comment]
... which is found here: https://github.com/raspberrypi/firmware/blob/master/boot/overlays/README
and referenced here: https://github.com/raspberrypi/documentation/blob/master/configuration/device-tree.md#35-supported-overlays-and-parameters

**Comment by msperl** [comment]
It sits outside of the code where the overlay dts files are located (not the same repository), so adding a new overlay to linux would mean another merge request for the firmware to get documented.
And this leads to thing not getting documented.
If it was instead in ONE repo, then you could even make it a requirement to have the documentation included with the merge request.

**Comment by pelwell** [comment]
That sounds to me like a different issue.

**Comment by msperl** [comment]
Well, if you want some documentation added when overlays get added (which typically require modules to get enabled) then all should sit in the same repo (which is linux) - and that is mostly my concern: incomplete documentation!

The firmware repo is mostly generated, so why not move those overlay documentation into the linux tree under Documentation and copy the bits and pieces over to firmware when you build the kernel?

Actually you could also just copy the overlay sources as well as the binaries to /boot/overlay and then have the requirement to have the documentation sit in a comment section in those sources.

**Comment by notro** [comment]
This makes me remember that it has become quite easy to make PR's from the github webgui.
And this fits fine with textfiles that don't need compile testing.
Fork https://github.com/raspberrypi/firmware
Go to boot/overlays/README
Click pencil icon to edit
Click 'Preview changes' to see the diff.
Choose 'Create a new branch for this commit and start a pull request'
Add commit message and hit 'Propose file change'
(I didn't actually try that step, but I've done this when it was slightly different, for the pi docu repo)
Then when it's merged, just kill the fork.

**Comment by pelwell** [comment]
@msperl As discussed elsewhere, I do intend to move the overlays and the documentation into one common home, and that probably shouldn't be in the kernel tree. But that task is a lower priority than some others at the moment, so until then I suggest you work with what is there now.

**Comment by Ruffio** [comment]
@msperl has this issue been resolved? If yes, please close this issue. Thanks.

**Comment by msperl** [comment]
Has that mentioned move by pelwell happened?
