### ISSUE TITLE
Kernel panic at boot with the last commit

### ISSUE THREAD

**Issue by alphaonex86** [raspberrypi/linux#87]
Hello, I have kernel panic at boot with the last commit (well the commit just before).
http://files.first-world.info/temp/DSC_0017.JPG
Thanks to fix it.

**Comment by popcornmix** [comment]
Can you be more specific. 
Does this happen with a pre-built kernel, or are you building with source. If you are building from source, is it unmodified and using the bcmrpi_defconfig file?
Can you point at the first git hash that produces the problem?

**Comment by alphaonex86** [comment]
https://github.com/raspberrypi/linux/commit/f599001496e2bbacd54e11fb9fbabda694d308f2
I'm building from source. Same config like the previous build (with this config it work).
Now some branch is out, I will try change the branch.

**Comment by popcornmix** [comment]
Perhaps you have some USB device connected that the 2.94 driver doesn't like. Can you try booting with no USB devices attached.
Perhaps you have locally changed options in .config which 2.94 doesn't like. Can you test official build of kernel.img first? Then test latest source with bcmrpi_defconfig. Then apply your local changes to .config and note which one causes panic.

**Comment by raspberrypi** [comment]
Looks like it's going wrong very early on, during driver init, maybe due to
exhaustion of the coherent memory pool. Perhaps you have something enabled
by your config which is consuming coherent memory?

**Comment by alphaonex86** [comment]
I try without ANY (0) device connect.
Bad luke, sd card broken...

**Comment by popcornmix** [comment]
@alphaonex86 
I didn't really understand the last comment. Are you saying the problem was a bad sdcard, and it's now fixed?
Or are you still having the problem?

**Comment by alphaonex86** [comment]
I have remplaced the sd card. With the last git + official .config it work, I close the bug.

**Comment by Arne-F** [comment]
Do you have a diff from your failing against the official config. I have same problem with my own config and it is no sd-card issue.

The kernel crash very early but i cannot really see why. It scrolls to fast, i think i have to add serial console to get a log.

**Comment by Arne-F** [comment]
Have found it. The kernel doesn't like SLUB memory management. (Chris Boot's patchset has worked with SLUB)

I have not really tested if the dwc_otg update trigger the problem but it crash at the initalisation so i think so. I will use SLAB for now.
