### ISSUE TITLE
kernel compile warning- security issue?

### ISSUE THREAD

**Issue by fhue** [raspberrypi/linux#879]
Hi folks,
just received following warning while cross-compiling the kernel (3.18.y):

crypto/wp512.c:987:1: warning: the frame size of 1240 bytes is larger than 1024 bytes [-Wframe-larger-than=]

I'm not familiar with this stuff, but 1240 looks like a TYPO of 1024!?
Cheers

**Comment by popcornmix** [comment]
It's just reporting the size of the stack (i.e. local variables) is largish.
It's not a problem. Anyway, this is upstream code, and should be reported there:
https://www.kernel.org/pub/linux/docs/lkml/reporting-bugs.html
