### ISSUE TITLE
Oops with new kernel when using NFS

### ISSUE THREAD

**Issue by lintweaker** [raspberrypi/linux#88]
When using the new kernel I get a reproducable oops when using NFS (client). Sometimes it happens fairly quick sometimes it takes a while.

I've taken a screenshot of the oops.

http://slimnet.home.xs4all.nl/raspi-oops-nfs.JPG

**Comment by popcornmix** [comment]
Please be more specific. Is the the default prebuilt kernel (or one you've built yourself)?
There's been a few kernel updates recently. Can you point at the git hash of the first kernel that produces this failure.

**Comment by lintweaker** [comment]
I am using today's pre-build kernel 3.2.27+ #6 
at says it's build Sat Aug 18 15:05:48

Did another update for good measure.
Took this version: https://github.com/Hexxeh/rpi-firmware/commit/424079987166d37652236988f691bbe00f58ba6f
I'll report back when the oops happens again.

**Comment by popcornmix** [comment]
Was that the first kernel that failed?
Can you confirm if "Rebase to kernel 3.2.27" works:
https://github.com/raspberrypi/firmware/commits/master/boot/kernel.img

**Comment by lintweaker** [comment]
I was using the previous kernels from the 3.1.9+ range without this NFS issue. I'll try the version you refer to if the update to 3.2.27+ #12 exhibits the NFS problem.

**Comment by lintweaker** [comment]
So far 3.2.27+ #12 is holding on very well. Have not seen the nfs related oops again.

**Comment by popcornmix** [comment]
Closing as issue appears fixed.
