### ISSUE TITLE
aplay and arecord

### ISSUE THREAD

**Issue by kciszewski** [raspberrypi/linux#890]
In 3.12.33+ aplay and arecord (command line) don't work.

**Comment by popcornmix** [comment]
3.12 is no longer supported. 3.18 is the stable version.
This is unlikely to be a kernel issue. You may be better off asking questions on the forum.

**Comment by kciszewski** [comment]
## So where do I get a 3.18 version?  I tried downloading from the Raspberry PI page last week, and the download didn't work.

On Mon, 3/16/15, popcornmix notifications@github.com wrote:

 Subject: Re: [linux] aplay and arecord (#890)
 To: "raspberrypi/linux" linux@noreply.github.com
 Cc: "kciszewski" kenski@swbell.net
 Date: Monday, March 16, 2015, 9:30 AM

 3.12 is no linger supported. 3.18
 is the stable version.

 This is unlikely to be a kernel issue. You may be better off
 asking questions on the forum.

 —
 Reply to this email directly or view
 it on GitHub.

**Comment by popcornmix** [comment]
```
sudo apt-get update && sudo apt-get upgrade
```

is the usual way of updating an image. You can also:
http://www.raspberrypi.org/downloads/

and click "download zip" next to Raspbian which is working fine for me.
