### ISSUE TITLE
Rather clean install of Raspbian via NOOBS 1.4 doesn't shutdown cleanly on the Pi 2?

### ISSUE THREAD

**Issue by Basilmir** [raspberrypi/linux#901]
Connecting via ssh to the Raspberry Pi 2 and doing a "sudo shutdown now" starts off the shutdown sequence only to show a root shell after:

INIT: Sending processes the KILL signal

PS. All I installed is an "sudo apt-get install netatalk"

**Comment by popcornmix** [comment]
I think this is expected behaviour. See:
http://askubuntu.com/questions/578144/why-doesnt-running-sudo-shutdown-now-shutdown

Try

```
sudo shutdown -h now
```

or

```
sudo halt
```

**Comment by Basilmir** [comment]
Oh! I'm not exactly a newbie but I've never encountered this before. Mainly used GNU Linux on PCs and those usually have Power On/Off buttons that do that for you. Interesting! I guess we can close this then.
