### ISSUE TITLE
direct snd-soc-rpi-wsp Wolfson Cirrus Logic support for 3.18.9 kernel

### ISSUE THREAD

**Issue by jgrulich** [raspberrypi/linux#905]
I was looking for some ready made support for the Wolfson Sound Card support for the 3.18.9 kernel in piCore-6.1 alpha4, but no lucky. I don't like to build it, or test some unofficial ways.

**Comment by popcornmix** [comment]
This is up to wolfson. They submitted a PR https://github.com/raspberrypi/linux/pull/705, but it is not finished, and we are waiting for an update. Please report this to them.

**Comment by jgrulich** [comment]
Hence the PR #705 was closed and that Wolfson is now part of Cirrus Logic, really don't know how to contact them for reporting.

**Comment by popcornmix** [comment]
Perhaps start here:
http://www.element14.com/community/community/raspberry-pi/raspberry-pi-accessories/cirrus_logic_audio_card/blog/2015/01/16/cirrus-logic-audio-card-2015-update
and
https://github.com/CirrusLogic/rpi-linux

But without a driver pull request, we're not able to support this.
