### ISSUE TITLE
hickups in sound when using snd_usb_audio devices

### ISSUE THREAD

**Issue by Farbman** [raspberrypi/linux#91]
I know you already are aware of this issue. Just want to have this as an open issue here.

For me everything got worse when I performed a rpi-update some days ago (In raspbian). The kernel that was shipped with my first raspbian installation had issues but not this many. After reading that some usb issues was resolved I did the update and after this usb audio is almost unlistenable.

Everytime the problem occur (when I play a sound) I get the lots of entries like the following in kern.log
[42641.766854] delay: estimated 0, actual 133
[42641.774864] delay: estimated 0, actual 133
[42641.782877] delay: estimated 0, actual 132
[42641.790866] delay: estimated 0, actual 132
[42641.811869] delay: estimated 0, actual 132
[42641.819878] delay: estimated 0, actual 132
[42641.827874] delay: estimated 0, actual 133
[42641.835876] delay: estimated 0, actual 133

The soundcard (usb-dac) I am trying with is a Cambridge Audio DacMagic Plus and it works just perfect in x86 linux.

**Comment by popcornmix** [comment]
It's not something I can test. It would be useful if you could identify the commit that made it worse.
The older firmware versions are available in github.

**Comment by Farbman** [comment]
Problem got worse in:
commit 0ef3d91e613a3d8db5debbd7eb8105071bfcb9be
Author: Dom Cobley dc4@broadcom.com
Date:   Sat Aug 18 15:30:25 2012 +0100

```
Rebase to kernel 3.2.27
```

**Comment by popcornmix** [comment]
That's unfortunate. I was hoping the offending commit would be something easily identifiable. 
That commit changed tens of thousands of lines of code...

**Comment by Farbman** [comment]
Searching for info I found this:
http://alsa.opensrc.org/Usb-audio#Tuning_USB_devices_for_minimal_latencies

modprobe snd-usb-audio nrpacks=1 removes the delay messages that I experienced above and sound is much better.

Closing this issue. 
(I have not been able to verify if sound works 100% with snd-usb-audio, but it is at least back to kernel 3.1 levels)
