### ISSUE TITLE
linux kernal 3.19.y make error "fs/btrfs/super.c  no such file or directory"

### ISSUE THREAD

**Issue by Ashu2k** [raspberrypi/linux#925]
I am using Raspberry pi 2 with kernal 3.18.7 - v7+ and am trying to install kernal 3.19.y which i downloaded from here  https://github.com/raspberrypi/linux/tree/rpi-3.19.y

when I go for the make command the script runs for a while until this error

```
make[1]: 'include/generated/mach-types.h' is up to date.
CALL    scripts/checksyscalls.sh
CHK     include/generated/compile.h
CHK     kernel/config_data.h
CC [M]  fs/btrfs/super.o
fs/btrfs/super.c:45:27: fatal error: delayed-inode.h: No such file or directory
compilation terminated
.scripts/Makefile.build:257: recipe for target'fs/btrfs/super.o' failed
make[2]: *** [fs/btrfs/super.o] Error 1
scripts/Makefile.build:402: recipe for target 'fs/btrfs' failed
make[1]: *** [fs/btrfs] Error 2
Makefile:939: recipe for target 'fs' failed
make: *** [fs] Error 2
```

can anyone help me out with this?

**Comment by popcornmix** [comment]
Are you using the recommended bcmrpi_defconfig/bcm2709_defconfig config files?

**Comment by Ashu2k** [comment]
I followed the steps from building kernel through the official raspberry pi wesite
And got everything working but after rebooting the system when i try uname -a i get
    Linux raspberrypi 3.18.11-v7+

Why is that? I was installing 3.19

**Comment by popcornmix** [comment]
Are you on Pi2? Did you update kernel7.img?

**Comment by popcornmix** [comment]
Duplicate of: https://github.com/raspberrypi/linux/issues/927

**Comment by Ashu2k** [comment]
yes am on pi2

I used these commands for kernel7.img

```
rm -f /boot/kernel7.img.old
mv /boot/kernel7.img /boot/kernel7.img.old 
cp arch/arm/boot/Image /boot/kernel7.img
```
