### ISSUE TITLE
VC4 status?

### ISSUE THREAD

**Issue by ha5di** [raspberrypi/linux#928]
Hi

what is the plan to add VC4 DRI to the kernel? I know it is not 100% ready yet, but seems to be coming soon.

Thanks... Béla

**Comment by popcornmix** [comment]
Yes this will come in combination with Eric Anholt's DRM/MESA driver work.
It will be widely reported when it is available (e.g. watch the Raspberry Pi blog) but no date yet.
It's going to be some months away.
