### ISSUE TITLE
New kernel module and overly for sound card

### ISSUE THREAD

**Issue by jgrulich** [raspberrypi/linux#929]
Is there some central repo where to find the source files and step by step tutorial how to customize the kernel module and overlay for new sound card?

**Comment by pelwell** [comment]
The source for the existing overlays is in this tree - go to arch/arm/boot/dts and look for *-overlay.dts .

There is no "step by step tutorial", but there is documentation of Device Tree and its usage on Raspberry Pi [here](https://www.raspberrypi.org/documentation/configuration/device-tree.md). You can get support in the forums - [here](https://www.raspberrypi.org/forums/viewtopic.php?f=44&t=99784&sid=11ce65be15cc5b303b10cbb30c05f3e1)'s a reasonable starting point.

**Comment by jgrulich** [comment]
I've already looked around such a pages as a first step. Hence I've not found any tutorial for beginner, I've tried to ask for some support. First of all, I need the kernel driver and later on the device tree overlay. I guess that only overlay is not sufficient. Is this correct?
Seems that I need to find someone who is skilled in kernell programming, but don't know where to look.

**Comment by pelwell** [comment]
So, you will need one kernel module for the DAC, one for the sound card as a whole, and an overlay. I had some success getting a basic configuration working with just DAC module + overlay, using a DAC module that exposed some ALSA parameters, but in the end I ran into some restrictions.

A few questions:
1. Is there already a driver for the DAC/codec in the tree?
2. Is there another RPi sound card already using that DAC?
3. Aside from the DAC, is there any other component that requires programming? Is that boot-time initialisation or is there a dynamic element (crystal switching, for example)?

If your answers are Yes, Yes and No then it should be a trivial cut-and-paste job to construct a driver for your board. Answering Yes to 3 makes it marginally harder, but not much.

**Comment by jgrulich** [comment]
Yes, I already have working card with the driver and overlay which is already in the kernel.
1. Yes, there is driver and overlay hifiberry-dacplus.
2. Yes, hifiberry-dac+ sound card
3. Additionally there is headphone amplifier on my board which enables I2C control - volume and enable. The hifiberry driver need to be only slightly modified and added one more slider for volume control and one ON/OFF switch.

**Comment by jgrulich** [comment]
As a conclusion of before mentioned, there is already codec for DAC and  I need soc-bcm module and corresponding overlay, both tailored to my card.
I need some help with this, because I'm not skilled in the kernel programing.

**Comment by pelwell** [comment]
It is something I could do, and if nobody else comes forward I could probably help you through it.

However, I have pinged somebody I know who frequents these parts and who has the skills. Should they want to get in touch, how should they reach you?

**Comment by jgrulich** [comment]
Thank you for help. How to send you personal message to provide more detailed info?
Or you may join my web: grulich.eu where I have some of my designs and contact e-mail.

**Comment by pelwell** [comment]
My name is Phil, I work for Raspberry Pi, and I have the logical email address.

**Comment by jgrulich** [comment]
Hi Phil, please contact me directly on my e-mail: jan@grulich.eu.
