### ISSUE TITLE
Using bcm2835_defconfig compile error 

### ISSUE THREAD

**Issue by yjxch** [raspberrypi/linux#948]
![1](https://cloud.githubusercontent.com/assets/4832611/7407818/51db1270-ef48-11e4-8e45-3a33c60cfb94.jpg)
![2](https://cloud.githubusercontent.com/assets/4832611/7407819/52025196-ef48-11e4-8303-f3b789ea01ba.jpg)

According to the error , we should enable CONFIG_MMC_BCM2835=y in bcm2835_defconfig.

**Comment by notro** [comment]
PR https://github.com/raspberrypi/linux/pull/947 was merged yesterday and should fix this issue.
