### ISSUE TITLE
bcmrpi_cutdown_defconfig: running modprobe results in: vmalloc: allocation failure: 0 bytes

### ISSUE THREAD

**Issue by maxnet** [raspberrypi/linux#95]
Using a kernel based on bcmrpi_cutdown_defconfig
Since 3.2.27 loading modules often results in kernel errors/warnings:

`
vmalloc: allocation failure: 0 bytes
modprobe: page allocation failure: order:0, mode:0xd0
Backtrace: 
Function entered at [<c0011e48>] from [<c03b1630>]
 r6:c03ddfa4 r5:000000d0 r4:00000001 r3:00000000
Function entered at [<c03b1618>] from [<c006737c>]
Function entered at [<c00672c0>] from [<c0088f9c>]
 r3:00000000 r2:c03ddfa4
 r8:000000d0 r7:ffffffff r6:c0053008 r5:bf009000 r4:00000000
Function entered at [<c0088e54>] from [<c0012ab8>]
 r8:ce88366c r7:00000017 r6:00000000 r5:bf009000 r4:000000d0
Function entered at [<c0012a78>] from [<c0053008>]
 r4:0009c0b6
Function entered at [<c0052ff4>] from [<c0053714>]
 r6:cc957f1c r5:bf009000 r4:0009c0b6 r3:00000000
Function entered at [<c0053080>] from [<c000e5e0>]
Mem-info:
Normal per-cpu:
CPU    0: hi:   90, btch:  15 usd:  37
active_anon:113 inactive_anon:0 isolated_anon:0
 active_file:420 inactive_file:7589 isolated_file:0
 unevictable:0 dirty:0 writeback:0 unstable:0
 free:46701 slab_reclaimable:225 slab_unreclaimable:341
 mapped:326 shmem:0 pagetables:20 bounce:0
Normal free:186804kB min:1908kB low:2384kB high:2860kB active_anon:452kB inactive_anon:0kB active_file:1680kB inactive_file:30356kB unevictable:0kB isolated(anon):0kB isolated(file):0kB present:227584kB mlocked:0kB dirty:0kB writeback:0kB mapped:1304kB shmem:0kB slab_reclaimable:900kB slab_unreclaimable:1364kB kernel_stack:200kB pagetables:80kB unstable:0kB bounce:0kB writeback_tmp:0kB pages_scanned:0 all_unreclaimable? no
lowmem_reserve[]: 0 0
Normal: 1*4kB 0*8kB 1*16kB 3*32kB 1*64kB 2*128kB 2*256kB 1*512kB 3*1024kB 3*2048kB 43*4096kB = 186804kB
8009 total pagecache pages
0 pages in swap cache
Swap cache stats: add 0, delete 0, find 0/0
Free swap  = 0kB
Total swap = 0kB
57344 pages of RAM
46778 free pages
1683 reserved pages
566 slab pages
630 pages shared
0 pages swap cached
vmalloc: allocation failure: 0 bytes
modprobe: page allocation failure: order:0, mode:0xd0
Backtrace: 
Function entered at [<c0011e48>] from [<c03b1630>]
 r6:c03ddfa4 r5:000000d0 r4:00000001 r3:00000000
Function entered at [<c03b1618>] from [<c006737c>]
Function entered at [<c00672c0>] from [<c0088f9c>]
 r3:00000000 r2:c03ddfa4
 r8:000000d0 r7:ffffffff r6:c0053008 r5:bf011000 r4:00000000
Function entered at [<c0088e54>] from [<c0012ab8>]
 r8:ce838590 r7:00000019 r6:00000000 r5:bf011000 r4:000000d0
Function entered at [<c0012a78>] from [<c0053008>]
 r4:0009c0b6
Function entered at [<c0052ff4>] from [<c0053714>]
 r6:cc957f1c r5:bf011000 r4:0009c0b6 r3:00000000
Function entered at [<c0053080>] from [<c000e5e0>]
Mem-info:
Normal per-cpu:
CPU    0: hi:   90, btch:  15 usd:  41
active_anon:113 inactive_anon:0 isolated_anon:0
 active_file:425 inactive_file:7584 isolated_file:0
 unevictable:0 dirty:0 writeback:0 unstable:0
 free:46701 slab_reclaimable:225 slab_unreclaimable:341
 mapped:326 shmem:0 pagetables:20 bounce:0
Normal free:186804kB min:1908kB low:2384kB high:2860kB active_anon:452kB inactive_anon:0kB active_file:1700kB inactive_file:30336kB unevictable:0kB isolated(anon):0kB isolated(file):0kB present:227584kB mlocked:0kB dirty:0kB writeback:0kB mapped:1304kB shmem:0kB slab_reclaimable:900kB slab_unreclaimable:1364kB kernel_stack:200kB pagetables:80kB unstable:0kB bounce:0kB writeback_tmp:0kB pages_scanned:0 all_unreclaimable? no
lowmem_reserve[]: 0 0
Normal: 1*4kB 0*8kB 1*16kB 3*32kB 1*64kB 2*128kB 2*256kB 1*512kB 3*1024kB 3*2048kB 43*4096kB = 186804kB
8009 total pagecache pages
0 pages in swap cache
Swap cache stats: add 0, delete 0, find 0/0
Free swap  = 0kB
Total swap = 0kB
57344 pages of RAM
46782 free pages
1683 reserved pages
566 slab pages
630 pages shared
0 pages swap cached
`

Seems to be related to an upstream kernel bug, as the same issue is reported elsewhere: https://bbs.archlinux.org/viewtopic.php?id=133599
As a workaround I added CONFIG_KALLSYMS=y to the kernel config, and that seems to work.

**Comment by popcornmix** [comment]
Thanks for report (and possible solution). I'll investigate.

**Comment by popcornmix** [comment]
Patch added to kernel source.

**Comment by asb** [comment]
The kernel bugzilla report is https://bugzilla.kernel.org/show_bug.cgi?id=42608

Seems that OpenElec chose to just enable KALLSYMS. The patch looks reasonable.
