### ISSUE TITLE
4.0.y: dma channel only accessible first time

### ISSUE THREAD

**Issue by msperl** [raspberrypi/linux#955]
there is an issue with the current implementation where fetching a DMA-channel again (after releasing it first) may result in the dma not getting found the second time.

The issue https://github.com/torvalds/linux/commit/63f89caad0e32dcfa17b2d17919816253de48996
has been applied to 4.1-rc1 and should also get applied to the foundation kernel.

Issue looks like this:

```
root@rpi2:~# dmesg -c
...
[   13.784768] Adding 102396k swap on /var/swap.  Priority:-1 extents:1 across:102396k SSFS
[   64.761622] spi spi0.0: setting up native-CS0 as GPIO 8
[   64.771466] spi spi0.1: setting up native-CS1 as GPIO 7
root@rpi2:~# rmmod spi-bcm2835
root@rpi2:~# modprobe spi-bcm2835
root@rpi2:~# dmesg
[ 4169.030552] spi-bcm2835 3f204000.spi: no tx-dma found - not using dma mode
[ 4169.039168] spi spi0.0: setting up native-CS0 as GPIO 8
[ 4169.048983] spi spi0.1: setting up native-CS1 as GPIO 7
root@rpi2:~#
```

so after a reload of the module  the tx-dma is not found.

Please merge that into the tree, as it fixes the issue upstream!

**Comment by popcornmix** [comment]
Cherry-picked and pushed.

**Comment by msperl** [comment]
thanks!
