### ISSUE TITLE
A couple of requests. DRBD and REALTEK RTL8192CU

### ISSUE THREAD

**Issue by zardoz99** [raspberrypi/linux#96]
There are a lot of people who are wanting to use the Edimax EW-7811Un Wifi adapter using the RTL8192CU chipset. Would it be possible to integrate this driver into the kernel tree by default to avoid having to rebuild it at every kernel update? 
I suspect that the recipe that most follow is from http://lumux.co.uk/2012/06/07/realtek-rtl8192curtl8192c-wifi-on-raspberrypi/

Also, please could the drbd module and any dependencies be enabled in the default kernel? I am using this as part of High Availability and clustering testing as a means of providing a shared storage solution.

Thanks.

**Comment by asb** [comment]
We were initially not keen on importing this module for two reasons.
Firstly,out of tree drivers add a maintenance burden and secondly it
might prompt requests for more inclusions of out of tree modules.
However, it seems that in practice this is the only external module a
large number of people are interested in. Basically, we'd happily
accept a pull requst. I would appreciate it though if someone would
check for overlap with the existing in kernel realtek driver to assess
the likelihood of regressions for hardware that currently works.

**Comment by Simanova** [comment]
"There are a lot of people who are wanting to use the Edimax EW-7811Un Wifi adapter"

For example: me. Its very frustrating reading tutorials about setting up Edimax EW-7811Un (RTL8192CU)  to find out these drivers will break every kernel update. I understand your reasons, but there is a large number of people out there needing a solution.

Thank you very much!

**Comment by asb** [comment]
@Simanova I think perhaps you misread my response. I was explaining why we were initially not too keen, but the conclusion is that it benefits a large number of people and we'd happily accept a pull request.

**Comment by popcornmix** [comment]
RTL8192CU driver is added. See:
http://www.raspberrypi.org/phpBB3/viewtopic.php?f=26&t=6256&p=165139#p165139

**Comment by zardoz99** [comment]
That is excellent news. All that I personally require now is for the drbd modules and dependencies to be enabled by default as modules. Any chance of that happening please?

**Comment by asb** [comment]
Yep, I'm going to go through all outstanding config requests shortly.

**Comment by popcornmix** [comment]
drbd is added.

**Comment by popcornmix** [comment]
Closing as this option is added. Please reopen if there is a problem.

**Comment by Elunir** [comment]
I have tried every thread i could find on the internet. still i cant get rtl8192cu to monitor mode on my new raspberry pi 2. uname -a = (Linux raspberrypi 4.1.18-v7+ #846 SMP Thu Feb 25 14:22:53 GMT 2016 armv7l GNU/Linux)
i would want some answers about how to fix this issue. thanks
