### ISSUE TITLE
Please enable FB_SSD1307 in default configs

### ISSUE THREAD

**Issue by kad** [raspberrypi/linux#969]
Please enable option FB_SSD1307 in default configs.
This would allow to use very widely available small i2c connected screens to work without big effort.

**Comment by popcornmix** [comment]
Added in latest rpi-update firmware. Please test.

**Comment by kad** [comment]
Thanks. Module appeared and can be loaded. Device detected but no framebuffer device node created for my type of LCD, but that's separate issue that needed to be looked at driver itself.
