### ISSUE TITLE
Error in linux/drivers/usb/host/dwc_common_port/Makefile

### ISSUE THREAD

**Issue by HemantJoshi** [raspberrypi/linux#97]
I checked out raspberrypi linux rpi-3.2.27. As usual was trying to build the kernel. During compilation, make gave error with following message:
"Must give "KDIR=/path/to/kernel/source" on command line or in environment"

So I opened the file in emacs to see the said Makefile and found that around (before) line 34, there was a pink band visible. This appears to me some text formatting characters accidentally got inserted. After removing this band, the compilation was through. Some other editors may not show this typo. Hence will be difficult to know what is wrong.

**Comment by ghollingworth** [comment]
Can you do a clean git checkout and try again?  It is most likely a git issue because I don't believe it is in the code...  But I've not yet been able to build it because I running with local changes...

**Comment by popcornmix** [comment]
I've removed the check for KDIR as it doesn't seem necessary when building from within kernel.

**Comment by HemantJoshi** [comment]
Thanks. But did you see the pink color band (formatting) characters appearing in there (seen in Emacs)?
After a fresh checkout last week, I found the pink band still present was causing error.

-Hemant

**Comment by popcornmix** [comment]
I don't believe there is problem. emacs is probably just hightlighting whitespace.

**Comment by HemantJoshi** [comment]
No I don't think so. There are a couple of white spaces throughout the file. Emacs doesn't show all of those.
Additionally removing the pink band, causes compilation to complete successfully. But keeping the pink band causes error.

-Hemant

**Comment by popcornmix** [comment]
Can you delete all lines except the pink band and then run 
od -t x1 Makefile
so I can see the characters you are refererring to.

**Comment by popcornmix** [comment]
Not convinced there is a problem here. No one else has complained.
Please reopen if more evidence is found.
