### ISSUE TITLE
Merge vcio2 into vcio

### ISSUE THREAD

**Issue by fran6co** [raspberrypi/linux#975]
http://maazl.de/project/vcio2/doc/index.html implements a safer and nicer interface to vcio, it would be nice to merge that code here.

**Comment by JamesH65** [comment]
@popcornmix Do we have any need for this?

**Comment by popcornmix** [comment]
No. You can now access vcio without root as part of video group:
```
pi@domnfs:~ $ ls -l /dev/vcio 
crw-rw---- 1 root video 249, 0 May 17 14:01 /dev/vcio
pi@domnfs:~ $ groups pi
pi : pi adm dialout cdrom sudo audio video plugdev games users input netdev spi i2c gpio
```
