### ISSUE TITLE
Add community 148f:7601 Ralink Technology, Corp kernel driver

### ISSUE THREAD

**Issue by analyser-** [raspberrypi/linux#979]
Dear rpi kernel maintainers,

Could you please add this kernel driver: https://github.com/kuba-moo/mt7601u

It controls this device:

$ lsusb | grep -i ralink
Bus 001 Device 007: ID 148f:7601 Ralink Technology, Corp.

This will save a lot of people a massive headache!

Thank you in advance,
analyser

**Comment by popcornmix** [comment]
In general we don't support non-upstreamed kernel drivers. It causes us massive maintenance headaches, and adds code to the kernel that hasn't been approved by the upstream kernel developers.
You should try to get the driver accepted into the upstream kernel and we can then pick it from there when accepted.
See: http://kernelnewbies.org/UpstreamMerge
