### ISSUE TITLE
Corrupted filesystem after reboot.

### ISSUE THREAD

**Issue by azbesthu** [raspberrypi/linux#98]
If you modify files on the sd card and then you run 'sudo reboot', the modified files may be corrupted.

If you modified start.elf or other firmware specific files, the Pi will not boot, caused by the corrupted files. If you see a lot @@@ at the end of your config.txt after you modified it and rebooted the Pi that is a symptom of this sync problem.

This phenomen can occure also when you first started raspbbian distro and did some update with the ui. If you select restart, then maybe it wont boot up next time. 

Workaround: 
run 'sync' before reboot.

**Comment by popcornmix** [comment]
There was a problem with FAT corruption with kernels before 2nd August. You may be hitting that.
Can you start with the "2012-08-16-wheezy-raspbian.zip" image from download page?

Aleternatively download latest kernel.img from https://github.com/Hexxeh/rpi-firmware and boot from that before trying to upgrade firmware.

**Comment by popcornmix** [comment]
Closing as I believe this is fixed. Please reopen if there is a problem.
