### ISSUE TITLE
rpi-4.0.y: ads7846-overlay.dts is missing

### ISSUE THREAD

**Issue by notro** [raspberrypi/linux#982]
[arch/arm/boot/dts/ads7846-overlay.dts](https://github.com/raspberrypi/linux/blob/rpi-3.18.y/arch/arm/boot/dts/ads7846-overlay.dts) haven't made it to rpi-4.0.y.

**Comment by popcornmix** [comment]
Okay now?

**Comment by notro** [comment]
Thank you.
