### ISSUE TITLE
i have kernel error (Internal error: Oops: 17 [#1] PREEMPT SMP ARM)

### ISSUE THREAD

**Issue by Jerning** [raspberrypi/linux#986]
http://pastebin.com/cWtpNDe0
That's system log /var/log/messages & Direct output to remote terminal(ssh client)

**Comment by pelwell** [comment]
That doesn't give us very much to go on. `dmesg` should give more complete (and compact) output, and it always helps to say what you were doing when the error happened, and if it was just a one-off or whether you can reproduce the error easily. I'm going to close this for lack of information, but feel free to re-open or start a new one if it happens again.
