### ISSUE TITLE
CONFIG_DEVTMPFS_MOUNT

### ISSUE THREAD

**Issue by Hexxeh** [raspberrypi/linux#99]
Can we have this option enabled by default? At the moment I'm pointing my Chromium OS ebuilds to my fork on GitHub that has some extra config stuff, but it seems like you have everything I need except this enabled now.

If you enable it, I can just point straight to this repo and save myself having to keep my fork current.

**Comment by popcornmix** [comment]
Added.

**Comment by popcornmix** [comment]
Closing as this option is added. Please reopen if there is a problem.
