### ISSUE TITLE
TP-Link TL-WN725N issue

### ISSUE THREAD

**Issue by ric96** [raspberrypi/linux#991]
TP-Link TL-WN725N does not work out of the box for raspberry pi, a simple workaround is to 
copy the firmware file (if you don't have it already) from https://github.com/lwfinger/rtl8188eu/blob/master/rtl8188eufw.bin to /lib/firmware/rtlwifi/
referencing #640 
it would be nice to have it pre-installed.
thank you

**Comment by ric96** [comment]
and now i am getting kernel panics :p

**Comment by XECDesign** [comment]
pretty sure this will be in jessie

**Comment by ric96** [comment]
But we are not upgrading to it soon, are we?

**Comment by XECDesign** [comment]
as soon as possible, but can't give any time frame.

**Comment by Ruffio** [comment]
@ric96 has your issue been resolved? If so, please close this issue. Thanks.

**Comment by ric96** [comment]
Work with the latest release of the OS and firmware.
