### ISSUE TITLE
"apt-get update" failes due to Packages.xz hash mismatch on June 2 update

### ISSUE THREAD

**Issue by mlsendian** [raspberrypi/linux#996]
When running "apt-get update", we get the error

> W: Failed to fetch http://archive.raspbian.org/raspbian/dists/wheezy/main/binary-armhf/Packages: Hash Sum mismatch

Looking into this, the Releases file (http://raspbian.mirror.ac.za/raspbian/dists/wheezy/Release) contains:

> Origin: Raspbian
> Label: Raspbian
> Suite: oldstable
> Codename: wheezy
> Version: 7.0
> Date: Tue, 02 Jun 2015 10:17:35 UTC
> Architectures: armhf
> Components: main contrib non-free rpi firmware
> Description: Debian armhf stable distribution for Raspberry Pi
> MD5Sum:
>  693d862c8bbe65ea125f28ecb93d0737 35040388 main/binary-armhf/Packages
>  b4211165253304b98a71c3fab881c85b 9548467 main/binary-armhf/Packages.gz
>  fbdd984893640306ad268b0a2008832a 6903248 main/binary-armhf/Packages.xz
> [..]

Manually downloading and hashing Packages.xz gives:

> wget http://archive.raspbian.org/raspbian/dists/wheezy/main/binary-armhf/Packages.xz && md5sum Packages.xz
> --2015-06-02 14:24:23--  http://archive.raspbian.org/raspbian/dists/wheezy/main/binary-armhf/Packages.xz
> [...]
> 2015-06-02 14:24:32 (853 KB/s) - `Packages.xz' saved [6903248/6903248]
> 
> 6b55f44d15f42e00b37840c1829f4c6e  Packages.xz

Although the file size listed in Release matches the file on the server, the hashes differ (fbdd984893640306ad268b0a2008832a != 6b55f44d15f42e00b37840c1829f4c6e)

**Comment by XECDesign** [comment]
Perhaps you have a proxy or caching issue?

```
pi@serge-pi ~/temp_incoming $ wget http://archive.raspbian.org/raspbian/dists/wheezy/main/binary-armhf/Packages.xz
--2015-06-02 15:35:50--  http://archive.raspbian.org/raspbian/dists/wheezy/main/binary-armhf/Packages.xz
Resolving archive.raspbian.org (archive.raspbian.org)... 5.153.225.206, 2001:41c9:1:3ce::10
Connecting to archive.raspbian.org (archive.raspbian.org)|5.153.225.206|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 6903248 (6.6M) [application/octet-stream]
Saving to: `Packages.xz'

100%[========================================================================================================================================================================>] 6,903,248   5.83M/s   in 1.1s    

2015-06-02 15:35:51 (5.83 MB/s) - `Packages.xz' saved [6903248/6903248]

pi@serge-pi ~/temp_incoming $ md5sum Packages.xz 
fbdd984893640306ad268b0a2008832a  Packages.xz
```

If this isn't a network issue, the problem needs to be reported here:
https://bugs.launchpad.net/raspbian/+filebug
